### PR TITLE
[Segment Replication] Fix for AlreadyClosedException for engine

### LINKED ISSUE #4530: [BUG] [Segment Replication] Flaky engine AlreadyClosedException exception on closed index action
**Describe the bug**
Engine AlreadyClosedException exception on closed index on replica shard. This issue happens when replication is finalized on replica shard and when translog generation is rolled over when last received gen is different than the one received. The roll translog generation ensure underlying engine to be open which fails sometimes. 

```
[2022-09-15T17:40:14,911][WARN ][o.o.i.e.Engine           ] [node_t1] [test-idx-1][0] failed engine [translog roll generation failed]
org.apache.lucene.store.AlreadyClosedException: [test-idx-1][0] engine is closed
	at org.opensearch.index.engine.Engine.ensureOpen(Engine.java:821) ~[main/:?]
	at org.opensearch.index.engine.Engine.ensureOpen(Engine.java:830) ~[main/:?]
	at org.opensearch.index.translog.InternalTranslogManager.rollTranslogGeneration(InternalTranslogManager.java:85) [main/:?]
	at org.opensearch.index.engine.NRTReplicationEngine.updateSegments(NRTReplicationEngine.java:134) [main/:?]
	at org.opensearch.index.shard.IndexShard.finalizeReplication(IndexShard.java:1382) [main/:?]
	at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$finalizeReplication$5(SegmentReplicationTarget.java:219) [main/:?]
	at org.opensearch.action.ActionListener.completeWith(ActionListener.java:342) [main/:?]
	at org.opensearch.indices.replication.SegmentReplicationTarget.finalizeReplication(SegmentReplicationTarget.java:205) [main/:?]
	at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$startReplication$3(SegmentReplicationTarget.java:169) [main/:?]
	at org.opensearch.action.ActionListener$1.onResponse(ActionListener.java:80) [main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:126) [main/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [main/:?]
	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341) [main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120) [main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:112) [main/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:112) [main/:?]
	at org.opensearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:160) [main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:141) [main/:?]
	at org.opensearch.action.StepListener.innerOnResponse(StepListener.java:77) [main/:?]
	at org.opensearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:55) [main/:?]
	at org.opensearch.action.ActionListener$4.onResponse(ActionListener.java:180) [main/:?]
	at org.opensearch.action.ActionListener$6.onResponse(ActionListener.java:299) [main/:?]
	at org.opensearch.action.support.RetryableAction$RetryingListener.onResponse(RetryableAction.java:161) [main/:?]
	at org.opensearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:69) [main/:?]
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1369) [main/:?]
	at org.opensearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:393) [main/:?]
	at org.opensearch.transport.InboundHandler.lambda$handleResponse$1(InboundHandler.java:387) [main/:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [main/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**To Reproduce**
Run below integration test in continuation, the failure is fails pretty consistently
```
    public void testIndexReopenClose() throws Exception {
        final String primary = internalCluster().startNode();
        createIndex(INDEX_NAME);
        ensureYellowAndNoInitializingShards(INDEX_NAME);
        final String replica = internalCluster().startNode();
        ensureGreen(INDEX_NAME);

        client().prepareIndex(INDEX_NAME).setId("1").setSource("foo", "bar").setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE).get();
        refresh(INDEX_NAME);

        final int initialDocCount = scaledRandomIntBetween(10000, 200000);
        try (
            BackgroundIndexer indexer = new BackgroundIndexer(
                INDEX_NAME,
                "_doc",
                client(),
                -1,
                RandomizedTest.scaledRandomIntBetween(2, 5),
                false,
                random()
            )
        ) {
            indexer.start(initialDocCount);
            waitForDocs(initialDocCount, indexer);
            refresh(INDEX_NAME);
            waitForReplicaUpdate();
        }

        flushAndRefresh(INDEX_NAME);
        waitForReplicaUpdate();

        logger.info("--> Closing the index ");
        client().admin().indices().prepareClose(INDEX_NAME).get();

        // Add another node to kick off TransportNodesListGatewayStartedShards which fetches latestReplicationCheckpoint for SegRep enabled indices
        final String replica2 = internalCluster().startNode();

        logger.info("--> Opening the index");
        client().admin().indices().prepareOpen(INDEX_NAME).get();
    }
```

**Expected behavior**
The NRTReplicationEngine should not fail preventing translog rollover.

**Host/Environment (please complete the following information):**
 - OS: iOS
 - Version : Latest changes on main

### PR DESCRIPTION
**Pull request by Poojita-Raj**
Signed-off-by: Poojita Raj <poojiraj@amazon.com>

### Description
Engine AlreadyClosedException exception takes place when replication is finalized on replica shard and when translog generation rollover takes place at which point we see the engine has already been closed. 

We want to make sure we only update the segments when the engine is open. Added an integration test for the same.

### Issues Resolved
Resolves #4530 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 1]
```diff
@@ -235,6 +235,48 @@ public void testReplicationAfterPrimaryRefreshAndFlush() throws Exception {
...
+        final String primary = internalCluster().startNode();
+        createIndex(INDEX_NAME);
+        ensureYellowAndNoInitializingShards(INDEX_NAME);
+        final String replica = internalCluster().startNode();
+        ensureGreen(INDEX_NAME);
+
+        client().prepareIndex(INDEX_NAME).setId("1").setSource("foo", "bar").setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE).get();
+        refresh(INDEX_NAME);
+
+        final int initialDocCount = scaledRandomIntBetween(10000, 200000);
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:248]: This seems like a huge number of docs for an integ test. Given the test waits until replicas catch up to proceed with assertions, can we get by with 100-200?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 2]
```diff
@@ -235,6 +235,48 @@ public void testReplicationAfterPrimaryRefreshAndFlush() throws Exception {
...
+                client(),
+                -1,
+                RandomizedTest.scaledRandomIntBetween(2, 5),
+                false,
+                random()
+            )
+        ) {
+            indexer.start(initialDocCount);
+            waitForDocs(initialDocCount, indexer);
+            refresh(INDEX_NAME);
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:262]: Can we flush here and avoid the flush & refresh on line 266?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 3]
```diff
@@ -235,6 +235,48 @@ public void testReplicationAfterPrimaryRefreshAndFlush() throws Exception {
...
+            waitForReplicaUpdate();
+        }
+
+        flushAndRefresh(INDEX_NAME);
+        waitForReplicaUpdate();
+
+        logger.info("--> Closing the index ");
+        client().admin().indices().prepareClose(INDEX_NAME).get();
+
+        // Add another node to kick off TransportNodesListGatewayStartedShards which fetches latestReplicationCheckpoint for SegRep enabled
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:272]: Not quite following why we need to start 3rd node for this test? Before this step you have 2 nodes, with 1 primary & one replica shard & close the index.  Are you wanting to test if the 3rd node is allocated one of the shards after its opened?

**Review by mch2 — COMMENTED** [review]
I'm not quite following some of the test logic.  Could you describe a bit more in your commit message when/why the exception occurs and how this fixes it?  From reading this and the original issue, it seems this happens when a shard/node is shut down while a replica is currently fetching new segments.

File: server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java [hunk 4]
```diff
@@ -122,17 +123,20 @@ public TranslogManager translogManager() {
...
-        // lower/higher gens are possible from a new primary that was just elected.
-        if (incomingGeneration != lastReceivedGen) {
-            commitSegmentInfos();
-            translogManager.rollTranslogGeneration();
+        ensureOpen();
+        try (ReleasableLock lock = writeLock.acquire()) {
+            final long incomingGeneration = infos.getGeneration();
+            readerManager.updateSegments(infos);
+
+            // Commit and roll the xlog when we receive a different generation than what was last received.
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java:131]: Nit: can we use `translog` instead of `xlog`?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 5]
```diff
@@ -235,6 +235,41 @@ public void testReplicationAfterPrimaryRefreshAndFlush() throws Exception {
...
+            waitForDocs(initialDocCount, indexer);
+            flush(INDEX_NAME);
+            waitForReplicaUpdate();
+        }
+
+        logger.info("--> Closing the index ");
+        client().admin().indices().prepareClose(INDEX_NAME).get();
+
+        logger.info("--> Opening the index");
+        client().admin().indices().prepareOpen(INDEX_NAME).get();
```
Comment (Rishikesh1159) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:270]: can we add assertion of  doc count after reopening the index ?

File: CHANGELOG.md [hunk 6]
```diff
@@ -210,6 +210,7 @@ Inspired from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
 - Fix version check for 2.x release for awareness attribute decommission([#5034](https://github.com/opensearch-project/OpenSearch/pull/5034))
 - Fix flaky test ResourceAwareTasksTests on Windows ([#5077](https://github.com/opensearch-project/OpenSearch/pull/5077))
 - Length calculation for block based fetching ([#5055](https://github.com/opensearch-project/OpenSearch/pull/5055))
+- Fix for AlreadyClosedException for engine ([#4743](https://github.com/opensearch-project/OpenSearch/pull/4743))
```
Comment (mch2) [inline CHANGELOG.md:213]: Nit - Pls specify this as a segrep only issue.

**Review by mch2 — APPROVED** [review]
