### PR TITLE
Fix shard failure on flush during upload failures for remote indexes

### LINKED ISSUE #10512: [BUG] Shard fails on flush due to exception during prepareAndUpload in RemoteFsTranslog for remote indexes
**Describe the bug**
While running stress testing on a remote enabled cluster, observed the behaviour where if the upload to remote store throws an exception, the shard will fail and the indexes become red with underlying shard becoming unassigned on account of flush being triggered internally or externally.

**To Reproduce**
Throw exception from prepareAndUpload while doing flush.

**Expected behavior**
Shard should not fail

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by ashking94**
### Description
If a flush happens while the remote uploads for translog (or ckp or the metadata file) are failing due to whatsoever reasons (be it transient), it was leading to shard failure. With this PR, we are not failing the engine if the exception thrown during flush is TranslogUploadFailedException.

### Related Issues
Resolves #10512

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/engine/InternalEngine.java [hunk 1]
```diff
@@ -1888,6 +1889,9 @@ public void flush(boolean force, boolean waitIfOngoing) throws EngineException {
                         }
 
                         translogManager.trimUnreferencedReaders();
+                    } catch (TranslogUploadFailedException e) {
+                        // Do not fail engine as this is due to translog upload failure
+                        throw new FlushFailedEngineException(shardId, e);
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/engine/InternalEngine.java:1894]: Without this change as well, it would have thrown `FlushFailedEngineException` and should not have failed engine .

File: server/src/main/java/org/opensearch/index/translog/transfer/TranslogUploadFailedException.java [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+import org.opensearch.core.index.shard.ShardId;
+import org.opensearch.index.translog.TranslogException;
+
+import java.io.IOException;
+
+/**
+ * Exception is thrown if there are any exceptions while uploading translog to remote store.
+ * @opensearch.internal
+ */
+public class TranslogUploadFailedException extends TranslogException {
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/translog/transfer/TranslogUploadFailedException.java:21]: should this extend `IOException` ? This is not a runtime exception .

File: server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java [hunk 3]
```diff
@@ -83,11 +84,14 @@ public InternalTranslogManager(
...
     @Override
-    public void rollTranslogGeneration() throws TranslogException {
+    public void rollTranslogGeneration() throws TranslogException, IOException {
         try (ReleasableLock ignored = readLock.acquire()) {
             engineLifeCycleAware.ensureOpen();
             translog.rollGeneration();
             translog.trimUnreferencedReaders();
+        } catch (TranslogUploadFailedException e) {
+            // Do not trigger the translogEventListener as it fails the Engine while this is only an issue with remote upload
+            throw e;
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java:94]: why catch when we need to throw?

File: server/src/main/java/org/opensearch/index/translog/transfer/TranslogUploadFailedException.java [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+ */
+public class TranslogUploadFailedException extends IOException {
+
+    public TranslogUploadFailedException(String message) {
+        super(message);
+    }
+
+    public TranslogUploadFailedException(String message, Throwable cause) {
+        super(message, cause);
+    }
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/translog/transfer/TranslogUploadFailedException.java:25]: Add meaningful message to get a sense of which shard or translog failed

File: server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java (hunk 3 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java:94]: By default, the behavior is to catch the exception and then fail the shard and then throw the exception back to the caller. By catching and throwing, we are skipping the part of failing the shard here.

**Comment by ashking94** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/27604/
> * **CommitID:** [408ffa1](https://github.com/opensearch-project/OpenSearch/commit/408ffa14af020da433967d73a6e14173930e2268)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky tests - https://github.com/opensearch-project/OpenSearch/issues/10542, https://github.com/opensearch-project/OpenSearch/issues/10558, https://github.com/opensearch-project/OpenSearch/issues/10193,

**Comment by ashking94** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/27635/
> * **CommitID:** [2c00f6c](https://github.com/opensearch-project/OpenSearch/commit/2c00f6c50eabbd637e25f9b6c16d963e0c3592cc)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

flaky test - https://github.com/opensearch-project/OpenSearch/issues/10542

**Review by gbbafna — APPROVED** [review]
