### PR TITLE
Fixing plugin installation URL to consume build qualifier

### LINKED ISSUE #3168: [BUG] Core-Plugins installation does not support qualifier fully
```
% ./opensearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/2.0.0/repository-s3-2.0.0-rc1.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.opensearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:450)
	at org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:527)
	at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:318)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:272)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)

```

As you can see despite the zip is `2.0.0-rc1` zip, OpenSearch core still points to `2.0.0` folder to download the zip.
I am not sure if this is a bug or expected to be `2.0.0` folder for `2.0.0-rc1`.
As of now we will hardcode native plugin deployment in production to `2.0.0`.

Thanks.

### PR DESCRIPTION
**Pull request by saratvemulapalli**
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>

### Description
Plugin installation URL for official plugins do not consume build qualifier, causing problems with the folder structure we expose for `artifacts.opensearch.org`. 
This PR fixes it and consumes the build qualifier while populating the URL for native plugins.

Unit tests already cover this, but added manual testing into PR for readability. 

Before the fix:
```
opensearch-3.0.0-rc1 % ./bin/opensearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/3.0.0/repository-s3-3.0.0-rc1.zip
```

After the fix:
```
opensearch-3.0.0-rc1 % ./bin/opensearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/3.0.0-rc1/repository-s3-3.0.0-rc1.zip
```
 
### Issues Resolved
Closes #3168 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saratvemulapalli** [comment]
cc: @peterzhuamazon

File: distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java [hunk 1]
```diff
@@ -1049,7 +1049,7 @@ public void assertInstallPluginFromUrl(
 
     public void testOfficialPlugin() throws Exception {
         String url = "https://artifacts.opensearch.org/releases/plugins/analysis-icu/"
-            + Version.CURRENT
+            + Build.CURRENT.getQualifiedVersion()
```
Comment (reta) [inline distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java:1052]: @saratvemulapalli sorry, as far as I can tell, `Version.CURRENT == Build.CURRENT.getQualifiedVersion()` (at least, should be), why we are changing that?

Comment (reta) [reply distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java:1052]: Answering my own question: `Version.CURRENT == Build.CURRENT.getQualifiedVersion()` is only in tests, otherwise taken from the JAR artifact ...

**Comment by peterzhuamazon** [comment]
Add `backport-2.0` tag as this is needed for 2.0 branch.

File: distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java (hunk 1 above)
Comment (saratvemulapalli) [reply distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java:1052]: Thank you @reta for the review.
`Version.CURRENT` doesnt include the qualifier where as `Build.CURRENT.getQualifiedVersion()` does. 
This helps us structuring artifacts in dedicated folders for releases like `alpha1`, `beta1`, `rc1`

**Comment by saratvemulapalli** [comment]
> Add `backport-2.0` tag as this is needed for 2.0 branch.

@peterzhuamazon do we plan to release 2.0.1? 
Why are we backporting it to a past release?

**Comment by dblock** [comment]
> > Add `backport-2.0` tag as this is needed for 2.0 branch.
> 
> @peterzhuamazon do we plan to release 2.0.1? Why are we backporting it to a past release?

2.0 branch is 2.0 GA that hasn't shipped yet
