### PR TITLE
Fix flaky test testNewlyAddedReplicaIsUpdated

### LINKED ISSUE #6459: [Segment Replication] SegmentReplicationRelocationIT.testNewlyAddedReplicaIsUpdated flaky test failure.
Flaky test failure due to timeout while waiting for cluster health response. Reported in https://github.com/opensearch-project/OpenSearch/pull/6455#issuecomment-1442084445

Gradle Check: https://build.ci.opensearch.org/job/gradle-check/11633

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationRelocationIT.testNewlyAddedReplicaIsUpdated" -Dtests.seed=A3D21C76F7A36009 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CU -Dtests.timezone=Africa/Algiers -Druntime.java=19

org.opensearch.indices.replication.SegmentReplicationRelocationIT > testNewlyAddedReplicaIsUpdated FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([A3D21C76F7A36009:E5CCE64E0859A9D0]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertFalse(Assert.java:65)
        at org.junit.Assert.assertFalse(Assert.java:75)
        at org.opensearch.indices.replication.SegmentReplicationRelocationIT.testNewlyAddedReplicaIsUpdated(SegmentReplicationRelocationIT.java:432)
```

### PR DESCRIPTION
**Pull request by mch2**
### Description
This change fixes flaky test testNewlyAddedReplicaIsUpdated by using ensureYellowAndNoInitializingShards that waits for 30s for a replica to be initialized over the existing 2s timeout.

### Issues Resolved
closes #6459

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java [hunk 1]
```diff
@@ -419,18 +419,7 @@ public void testNewlyAddedReplicaIsUpdated() throws Exception {
...
-            .prepareHealth()
-            .setWaitForEvents(Priority.LANGUID)
-            .setWaitForNodes("2")
-            .setWaitForGreenStatus()
-            .setTimeout(TimeValue.timeValueSeconds(2))
-            .execute()
-            .actionGet();
-        assertFalse(clusterHealthResponse.isTimedOut());
-        ensureGreen(INDEX_NAME);
+        ensureYellowAndNoInitializingShards(INDEX_NAME);
```
Comment (Rishikesh1159) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java:422]: why not use ensureGreen() here? Eventually after adding replica shard the cluster will be green right?

Comment (mch2) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java:422]: Yes you are right, both of these methods would work in this case.

**Review by Rishikesh1159 — APPROVED** [review]

**Review by dreamer-89 — APPROVED** [review]
