### PR TITLE
Avoid override of routes() in BaseRestHandler to respect the default behavior defined in RestHandler

### LINKED ISSUE #694: Update BaseRestHandler to implement default routes
**Describe the bug**
Update BaseRestHandler to implement default routes() instead of an abstract class. 
This will help developers not to implement empty methods even though they don't need it.
They can always override the method if they'd like.

https://github.com/opensearch-project/OpenSearch/blob/0ba0e7cc26060f964fcbf6ee45bae53b3a9941d0/server/src/main/java/org/opensearch/rest/BaseRestHandler.java#L102

**Expected behavior**
Return an empty list so that classes which extend do not have implement empty methods even if they don't have to.

**Plugins**
OpenSearch Anomaly-Detection

**Host/Environment (please complete the following information):**
 - OS: Linux x64

### PR DESCRIPTION
**Pull request by cliu123**
### Description
Remove override for `routes()` in `BaseRestHandler` to respect default behavior of routes() defined in `RestHandler`.
This will help developers avoid re-implementing `routes()` in the subclasses of `BaseRestHandler`
They can always override the method if they'd like.
 
### Issues Resolved
#694 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by CEHENKLE** [comment]
@cliu123 Can you add more information to this PR?  Thanks...

**Comment by cliu123** [comment]
> @cliu123 Can you add more information to this PR? Thanks...

Sure. This can be post-GA. I'll add more info later.

File: server/src/main/java/org/opensearch/rest/BaseRestHandler.java [hunk 1]
```diff
@@ -99,7 +101,7 @@ public final long getUsageCount() {
      * {@inheritDoc}
      */
     @Override
-    public abstract List<Route> routes();
+    public List<Route> routes() { return routes; }
```
Comment (dblock) [inline server/src/main/java/org/opensearch/rest/BaseRestHandler.java:104]: Minor, but 1-liners don't seem to get 1-lined in this project.

```java
public List<Route> routes() { 
    return routes; 
}
```

File: server/src/main/java/org/opensearch/rest/BaseRestHandler.java [hunk 2]
```diff
@@ -66,6 +66,8 @@
  */
 public abstract class BaseRestHandler implements RestHandler {
 
+    public static List<Route> routes;
```
Comment (dblock) [inline server/src/main/java/org/opensearch/rest/BaseRestHandler.java:69]: This shouldn't be public if it's meant to be consumed via `getRoutes()`. Should it be protected? Probably not either.

**Review by dblock — CHANGES_REQUESTED** [review]
Assuming `routes` becomes `private`, how does one add a route? 

How will existing implementers of `BaseRestHandler` need to be changed? I imagine many define `routes` in their own implementations?

**Review by Bukhtawar — COMMENTED** [review]
Can we add more details on what this PR intends to solve

**Comment by cliu123** [comment]
> Can we add more details on what this PR intends to solve

@Bukhtawar The issue #694 describes what this PR intends to solve.

**Comment by cliu123** [comment]
> Assuming `routes` becomes `private`, how does one add a route?
> 
> How will existing implementers of `BaseRestHandler` need to be changed? I imagine many define `routes` in their own implementations?

> I imagine many define `routes` in their own implementations?
That is what happens, for [example.](https://github.com/opensearch-project/security/blob/2aa365854d881165d8b3592a9b0f57f78a9c4293/src/main/java/org/opensearch/security/dlic/rest/api/AccountApiAction.java#L90)
@dblock If defining `routes` field as protected in `BaseRestHandler`, the implementers would be allowed to add routes? Any thoughts? The intention is not to force implementers to implement the method abstract`routes` when they do not need the method.

**Comment by Bukhtawar** [comment]
From what I understand, we need to also ensure one of routes() or replacedRoutes() are implemented so that an implementer cannot get away without specifying any?

**Comment by cliu123** [comment]
> From what I understand, we need to also ensure one of routes() or replacedRoutes() are implemented so that an implementer cannot get away without specifying any?

@Bukhtawar Agree. The intention of this PR is not to force implementers to implement the abstract method `routes` when they do not need the method. Perhaps `routes` was designed as an abstract method on purpose to ensure the implementers specify it?

**Comment by vrozov** [comment]
Why is it necessary to overwrite the default `RestHandler` implementation in the `BaseRestHandler`? Implementing it as `abstract` does not enforce anything. Yes, it needs to be implemented by all subclasses of `BaseRestHandler`, but there is no enforcement on the actual return and it can be `null` or an empty list. The proposed implementation is subject of `NullPointerException` and subclasses of `RestHandler` will still need to initialize `routes` to a list.

**Comment by cliu123** [comment]
> Why is it necessary to overwrite the default `RestHandler` implementation in the `BaseRestHandler`? Implementing it as `abstract` does not enforce anything. Yes, it needs to be implemented by all subclasses of `BaseRestHandler`, but there is no enforcement on the actual return and it can be `null` or an empty list. The proposed implementation is subject of `NullPointerException` and subclasses of `RestHandler` will still need to initialize `routes` to a list.

@vrozov 

> Why is it necessary to overwrite the default `RestHandler` implementation in the `BaseRestHandler`?

IMO, It is actually unnecessary.

> Implementing it as `abstract` does not enforce anything.

Is our goal that the subclasses of `BaseRestHandler`do not have to implement the method `routes` unless the subclasses really need the method?

> there is no enforcement on the actual return and it can be `null` or an empty list.

For this purpose, removing the `routes()` method from the `BaseRestHandler` will make that happen?

**Comment by Bukhtawar** [comment]
Is there a harm returning an empty list and let the contract stay

**Comment by cliu123** [comment]
> Is there a harm returning an empty list and let the contract stay

I do not think there ia a harm returning an empty list, but looks like `BaseRestHandler` does not have to override the method `routes()`, and the abstract class `routes()` in `BaseRestHandler` makes subclasses of `BaseRestHandler` have to implement the method `routes()` even if the subclasses do not need that method.

**Comment by vrozov** [comment]
> Is our goal that the subclasses of BaseRestHandlerdo not have to implement the method routes unless the subclasses really need the method? If not, the issue #694 will need more details to clarify the goal.

@cliu123 The reason `RestHandler` provides the default implementation of `routes()` (and other related methods) is to avoid unnecessary reimplementation of the method in the subclasses. By introducing `abstract routes()` method or introducing `protected List<Route> routes`  to `BaseRestHandler`, the goal of the default interface implementation is defeated.

**Comment by Bukhtawar** [comment]
I think the way to look at it is can a RestHandler exist without a route. If not then I think we should have a mechanism to enforce it. 

The abstract class enforces that and this change will change the enforcement

**Comment by cliu123** [comment]
> I think the way to look at it is can a RestHandler exist without a route. If not then I think we should have a mechanism to enforce it.
> 
> The abstract class enforces that and this change will change the enforcement

@Bukhtawar Would you mind posting the concern on the issue #694 where the goal of this PR is discussed.

**Comment by vrozov** [comment]
> The abstract class enforces that and this change will change the enforcement

@Bukhtawar The abstract class does not enforce that subclasses return nonempty routes. All it (unnecessary) enforces is that subclasses have some implementation of `routes()`, but such implementation may return `null` or an empty list. Should there be a requirement for subclasses to provide an implementation of `routes()`, `RestHandler` should not provide a default implementation.

**Comment by Bukhtawar** [comment]
Interface is meant to enforce a contract not validate if the implementation is correct @vrozov

File: server/src/main/java/org/opensearch/rest/BaseRestHandler.java [hunk 3]
```diff
@@ -95,12 +95,6 @@ public final long getUsageCount() {
      */
     public abstract String getName();
 
-    /**
-     * {@inheritDoc}
-     */
-    @Override
-    public abstract List<Route> routes();
```
Comment (vrozov) [inline server/src/main/java/org/opensearch/rest/BaseRestHandler.java:102]: There are few test cases that unnecessary overwrite `routes()`. IMO, it will be better to delete those overwrites and rely on the default interface implementation.

**Comment by vrozov** [comment]
> Interface is meant to enforce a contract not validate if the implementation is correct @vrozov

There is no difference in enforcing a (compile-time) contract between interface and abstract class. Abstract class enforces that the abstract method is implemented by all subclasses, interface enforces that all methods without default implementation are implemented. There is no enforcement on how they are implemented in both cases. Introducing `abstract routes()` method to `BaseRestHandler` does not add any value, IMO.
 
> Does it make sense for any plugin to not provide that info in the first place?

Yes, it does. Please see my note on the #694. For example, some handlers may be disabled based on settings/run-time configuration.

> Passing invalid or null explicitly is another thing.

My point is that `abstract route()` or implementing `route()` (the way it was implemented) on the `BaseRestHandler` does not help to avoid returning `null` in the subclasses.

> Just to clarify when I am referring to a Rest Handler I am intending a handler defined by the plugin and not the interface name as such

It does not need to be a plugin implementation. It can be a core OpenSearch handler as well. Any subclass of `BaseRestHandler` is the subject of the discussion.

**Comment by dblock** [comment]
1. Looks like we went back and forth on things. Describe what this PR actually does in the description of this PR. 
2. We're removing a method that will no longer need to be implemented. Was it really never used in this codebase? A-OK.

**Comment by cliu123** [comment]
> 1. Looks like we went back and forth on things. Describe what this PR actually does in the description of this PR.

What this PR does is described in issue #694. I don't have the permission to link this PR to that issue. Would you please help do that if you have the permission?

> 2. We're removing a method that will no longer need to be implemented. Was it really never used or called in this codebase? If yes, those need to be removed. Otherwise please confirm and good riddance then.

There're several subclasses of `BaseRestHandler` have to implement the method `routes()` that is never used, for [example](https://github.com/opensearch-project/security/blob/2b69d9c84d807fc68b3ad9770d8bb75f6b99e725/src/main/java/org/opensearch/security/dlic/rest/api/AccountApiAction.java#L90) and a few other handlers in [here](https://github.com/opensearch-project/security/tree/main/src/main/java/org/opensearch/security/dlic/rest/api).

**Comment by vrozov** [comment]
> > 2. We're removing a method that will no longer need to be implemented. Was it really never used or called in this codebase? If yes, those need to be removed. Otherwise please confirm and good riddance then.
> 
> There're several subclasses of `BaseRestHandler` having to implement the method `routes()` that is never used, for [example](https://github.com/opensearch-project/security/blob/2b69d9c84d807fc68b3ad9770d8bb75f6b99e725/src/main/java/org/opensearch/security/dlic/rest/api/AccountApiAction.java#L90) and a few other handlers in [here](https://github.com/opensearch-project/security/tree/main/src/main/java/org/opensearch/security/dlic/rest/api).

The method was used and called. It is not removed. The PR fixes a bug in `BaseRestHandler` that overrides the default implementation of `routes()` method in `RestHandler`. Please see https://github.com/opensearch-project/security/pull/1256#discussion_r658515557

File: server/src/test/java/org/opensearch/usage/UsageServiceTests.java [hunk 4]
```diff
@@ -200,11 +198,6 @@ public String getName() {
             return name;
         }
 
-        @Override
```
Comment (vrozov) [inline server/src/test/java/org/opensearch/usage/UsageServiceTests.java:203]: There are few more unnecessary overrides.

**Comment by dblock** [comment]
> @dblock
> 
> > 1. Looks like we went back and forth on things. Describe what this PR actually does in the description of this PR.
> 
> What this PR does is described in issue #694. I don't have the permission to link this PR to that issue. Would you please help do that if you have the permission?

You don't need permissions, when you paste a link it links. I was referring to this:

Screen Shot 2021-07-12 at 1 15 16 PM


> > 1. We're removing a method that will no longer need to be implemented. Was it really never used or called in this codebase? If yes, those need to be removed. Otherwise please confirm and good riddance then.
> 
> There're several subclasses of `BaseRestHandler` having to implement the method `routes()` that is never used, for [example](https://github.com/opensearch-project/security/blob/2b69d9c84d807fc68b3ad9770d8bb75f6b99e725/src/main/java/org/opensearch/security/dlic/rest/api/AccountApiAction.java#L90) and a few other handlers in [here](https://github.com/opensearch-project/security/tree/main/src/main/java/org/opensearch/security/dlic/rest/api).

I meant, anything in this repo?

Are there any objections to merging this as is from @vrozov and @Bukhtawar ?

**Comment by vrozov** [comment]
> I meant, anything in this repo?

Even in this repo there are methods that have to implement `routes()` only because `routes()` was declared `abstract` in `BaseRestHandler` (one case is already taken care of). IMO, all such occurrences needs to be removed in the PR.

**Comment by vrozov** [comment]
LGTM except for PR title

**Comment by cliu123** [comment]
> LGTM except for PR title

@vrozov Changed the PR title

**Comment by cliu123** [comment]
@dblock @Bukhtawar How do the changes look to you?

**Review by vrozov — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
> @dblock @Bukhtawar How do the changes look to you?

Now that the unnecessary implementations have been removed in tests, this makes a lot more sense! Good with me.

You should still update the description in the PR for anyone reading this for the first time.

**Comment by dblock** [comment]
start gradle check

**Comment by cliu123** [comment]
> You should still update the description in the PR for anyone reading this for the first time.

@dblock Done.

**Comment by saratvemulapalli** [comment]
Looks like I missed the whole party of conversation.
I like where we ended up!

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
@dblock are we waiting for anything else to merge this ?

**Comment by dblock** [comment]
Merged, thanks @cliu123!

**Comment by cliu123** [comment]
@dblock @saratvemulapalli Are we going to backport this to 1.0 or 1.x(for 1.1.0) branches?

**Comment by dblock** [comment]
Since this is not a security fix it definitely doesn't go to 1.0, but I don't see why we wouldn't backport to 1.1. Feel free to make that PR @afazel if you need it.
