### PR TITLE
Handle shard over allocation during partial zone/rack or independent node failures 

### LINKED ISSUE #938: [BUG] Skewness due to Zone balancing during partial AZ failures
**Describe the bug**

Weaknesses in the algorithm
1. Unaware of excluded zones : The awareness decider is oblivious to the fact that a zone can be totally excluded for allocation if the cluster is undergoing a full AZ shutdown 
eg: Moving from AZ1 to → AZ2 will conveniently choose 2AZs to balance data across AZs even though AZ1 is excluded and needs to be shutdown as a result shards might not move out of AZ1
2. Unbalanced AZ capacity causes skewness : Insufficient capacity in any one AZ can cause shards to get stuffed heavily on the surviving nodes of the impacted AZ
eg: AZ1, AZ2, AZ3 having 3 nodes each will cause surviving nodes on AZ3 to get heavily stuffed if one or two nodes in AZ3 fail.

**Proposal**
To avoid skewness the algorithm can figure out the surviving nodes on each AZ and compare for skewness. Let's say AZ3 in the previous example lost 1 node so AZ3 has 33% less capacity as compared to other nodes in the healthy AZ. We can prevent allocation of a third copy in a 3AZ setup or second copy in a 2AZ setup on the surviving nodes of the impacted AZ to avoid nodes from getting burdened with shards of the nodes that dropped in same AZ. This can be based out of a setting that allows how much skewness can be tolerated on the surviving nodes of the impacted AZ. When the x% is reached we prevent allocation of the extra copy on the surviving nodes.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Bukhtawar**
Signed-off-by: Bukhtawar Khan <bukhtawa@amazon.com>

### Description
The changes ensure that in the event of a partial zone failure, the surviving nodes in the minority zone don't get overloaded with shards, this is governed by a skewness limit. 

### Issues Resolved
#938 
 
### Check List
- [ ] Add support for absolute skewness limits
- [ ] Add more unit tests
- [ ] Add integ tests
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+ * based on oveload factor defined as a percentage by
+ * <pre>
+ * cluster.routing.allocation.overload_awareness.factor: X
+ * </pre>
+ */
+public class NodeOverloadAwareAllocationDecider extends AllocationDecider {
+
+    public static final String NAME = "overload_awareness";
+
+    public static final Setting<Integer> CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_PROVISIONED_CAPACITY_SETTING =
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:42]: Today data nodes can be added/ removed from the cluster on demand and master balances the shards on the nodes present in the cluster at any time. But, now anytime nodes are added/ removed from the cluster, this setting has to be updated if it is a planned activity and the setting is turned on. 

During B/G this ProvisionedCapacity and node exclusion setting have to be set atomically otherwise it can leave shards unassigned or un-necessary movement. Thoughts?

**Review by shwetathareja — COMMENTED** [review]
Thanks Bukhtawar. did the first pass, left some thoughts.

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 1 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:42]: Yes they have to be set as a part of the same API call or this can be turned off while maintenance activity is underway and once the cluster is stable, it can be turned ON

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+
+    public NodeOverloadAwareAllocationDecider(Settings settings, ClusterSettings clusterSettings) {
+        this.overloadFactor = CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_FACTOR_SETTING.get(settings);
+        this.provisionedCapacity = CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_PROVISIONED_CAPACITY_SETTING.get(settings);
+        this.allowUnassignedPrimaries = CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_ALLOW_UNASSIGNED_PRIMARIES_SETTING.get(settings);
+        clusterSettings.addSettingsUpdateConsumer(CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_FACTOR_SETTING,
+            this::setOverloadFactor);
+        clusterSettings.addSettingsUpdateConsumer(CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_PROVISIONED_CAPACITY_SETTING,
+            this::setProvisionedCapacity);
+        clusterSettings.addSettingsUpdateConsumer(CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_ALLOW_UNASSIGNED_PRIMARIES_SETTING,
```
[the remark this answers is not in the document]
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:68]: This is for new primaries that get created from index creation, snapshot restore etc. Existing primaries aren't impacted

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+ * cluster.routing.allocation.overload_awareness.provisioned_capacity: N
+ * </pre>
+ * <p>
+ * and prevent allocation on the surviving nodes of the under capacity cluster
+ * based on oveload factor defined as a percentage by
+ * <pre>
+ * cluster.routing.allocation.overload_awareness.factor: X
+ * </pre>
+ */
+public class NodeOverloadAwareAllocationDecider extends AllocationDecider {
```
[the remark this answers is not in the document]
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:38]: +1

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+
+    public static final Setting<Integer> CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_PROVISIONED_CAPACITY_SETTING =
+        Setting.intSetting("cluster.routing.allocation.overload_awareness.provisioned_capacity", -1, -1,
+            Property.Dynamic, Property.NodeScope);
+    public static final Setting<Integer> CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_FACTOR_SETTING =
+        Setting.intSetting("cluster.routing.allocation.overload_awareness.factor", 50, -1, Property.Dynamic,
+            Property.NodeScope);
+    public static final Setting<Boolean> CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_ALLOW_UNASSIGNED_PRIMARIES_SETTING =
+        Setting.boolSetting("cluster.routing.allocation.overload_awareness.allow_unassigned_primaries",
+            true, Setting.Property.Dynamic, Property.NodeScope);
```
Comment (getsaurabh02) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:50]: Why do we really need this explicit setting? Shouldn’t decider be able to detect based on cluster state, such as node local copy? For new index creation, the shard distribution would be even anyways?

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+    public Decision canRemain(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation) {
+        return underCapacity(shardRouting, node, allocation, (count, limit) -> count > limit);
+    }
+
+    private Decision underCapacity(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation,
+                                   BiPredicate<Integer, Integer> decider) {
+        if (provisionedCapacity <= 0 || overloadFactor < 0 ) {
+            return allocation.decision(Decision.YES, NAME,
+                "overload awareness allocation is not enabled, set cluster setting [%s] and cluster se=tting [%s] to enable it",
+                CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_FACTOR_SETTING.getKey(),
```
Comment (getsaurabh02) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:99]: typo ``=``

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+
+    private volatile int overloadFactor;
+
+    private volatile boolean allowUnassignedPrimaries;
+
+    private static final Logger logger = LogManager.getLogger(NodeOverloadAwareAllocationDecider.class);
+
+    public NodeOverloadAwareAllocationDecider(Settings settings, ClusterSettings clusterSettings) {
+        this.overloadFactor = CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_FACTOR_SETTING.get(settings);
+        this.provisionedCapacity = CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_PROVISIONED_CAPACITY_SETTING.get(settings);
```
Comment (getsaurabh02) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:62]: Do you think an uber level setting for decider to be ``enabled/disabled`` makes sense? Given there are multiple scenarios when user would want to temporarily disable the feature (such as cluster sizing changes)?

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+
+    private Decision underCapacity(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation,
+                                   BiPredicate<Integer, Integer> decider) {
+        if (provisionedCapacity <= 0 || overloadFactor < 0 ) {
+            return allocation.decision(Decision.YES, NAME,
+                "overload awareness allocation is not enabled, set cluster setting [%s] and cluster se=tting [%s] to enable it",
+                CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_FACTOR_SETTING.getKey(),
+                CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_PROVISIONED_CAPACITY_SETTING.getKey());
+        }
+        if (shardRouting.unassigned() && shardRouting.primary() && allowUnassignedPrimaries) {
```
Comment (getsaurabh02) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:102]: This can hurt allocation decision for ``PrimaryShardAllocator`` of ``GatewayAllocator``, if a node leaves and joins back the cluster, under an overload scenario. This can prevent primaries which were previously allocated on the nodes to go unassigned, just because node left and joined back?

I feel we should not have explicit setting to control ``allowUnassignedPrimaries``.

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+            return allocation.decision(Decision.YES, NAME,
+                "overload allocation awareness is allowed for unassigned primaries, set cluster setting [%s] to disable it",
+                CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_ALLOW_UNASSIGNED_PRIMARIES_SETTING.getKey());
+        }
+        Metadata metadata = allocation.metadata();
+        float expectedAvgShardsPerNode = (float) metadata.getTotalNumberOfShards() / provisionedCapacity;
+        int nodeShardCount = node.numberOfOwningShards();
```
Comment (getsaurabh02) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:109]: How are we dealing with index close and and open scenarios?

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+public class NodeOverloadAwareAllocationDecider extends AllocationDecider {
+
+    public static final String NAME = "overload_awareness";
+
+    public static final Setting<Integer> CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_PROVISIONED_CAPACITY_SETTING =
+        Setting.intSetting("cluster.routing.allocation.overload_awareness.provisioned_capacity", -1, -1,
+            Property.Dynamic, Property.NodeScope);
+    public static final Setting<Integer> CLUSTER_ROUTING_ALLOCATION_OVERLOAD_AWARENESS_FACTOR_SETTING =
+        Setting.intSetting("cluster.routing.allocation.overload_awareness.factor", 50, -1, Property.Dynamic,
+            Property.NodeScope);
```
Comment (getsaurabh02) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:47]: Having this (feature/setting) at an index level makes more sense, given usually larger clusters have number of shards in the order of thousands (such as 1k per node), and even a small overload percentage lets say (10%) will allow overload of shards in the order of 100s per node. Key point here is not all shards overload is a problem, but only of selective indices, which are expected to have more resource intensive operations. 

Given this feature is supposed to restrict the resource utilization of most active indices, having this decider only to work for select indices, could make this feature more targeted and even customer friendly. Otherwise we may not be be able to effectively limit the overload of desired shards, in a large clusters. Thoughts?

**Review by getsaurabh02 — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 4 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:50]: if the limit is already breached, we still want new index creation to go through assigning the primaries as an exception to the overload limit

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 6 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:62]: The overload limit can be set to -1 meaning unlimited, this is also how ShardLimitAllocationDecider does, avoiding too many settings here

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 7 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:102]: I guess that decision is make by `canForceAllocatePrimary` which tries to force allocate a primary if a previous copy existed on disk?

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 9 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:47]: All allocation deciders use a property called priority to prioritize allocation of shards across indices. This decider inherently uses that same logic prioritizing more recent index/the one having high priority. Having a knob at index level might be hard to manage. Given there is a way to define priority today, we can see if that makes sense as a follow up

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 4 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java:50]: > For new index creation, the shard distribution would be even anyways?

I don't think that is guaranteed, on the contrary node with least weight is more likely to assign most or all primary shards

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java [hunk 10]
```diff
@@ -0,0 +1,120 @@
...
+        if (provisionedCapacity <= 0 || overloadFactor < 0 ) {
+            return allocation.decision(Decision.YES, NAME,
+                "overload awareness allocation is not enabled, set cluster setting [%s] and cluster setting [%s] to enable it",
+                CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_FACTOR_SETTING.getKey(),
+                CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_PROVISIONED_CAPACITY_SETTING.getKey());
+        }
+        if (shardRouting.unassigned() && shardRouting.primary() && allowUnassignedPrimaries) {
+            return allocation.decision(Decision.YES, NAME,
+                "overload allocation awareness is allowed for unassigned primaries, set cluster setting [%s] to disable it",
+                CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_ALLOW_UNASSIGNED_PRIMARIES_SETTING.getKey());
```
Comment (malpani) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:106]: What is the value add from the additional knob on allow unassigned primary here - when would a production cluster set it to false?

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java [hunk 11]
```diff
@@ -0,0 +1,120 @@
...
+        }
+        Metadata metadata = allocation.metadata();
+        float expectedAvgShardsPerNode = (float) metadata.getTotalNumberOfShards() / provisionedCapacity;
```
Comment (malpani) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:109]: this is assuming every data node is equal - wont it need to factor in node attributes eg. hot/warm ?

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java [hunk 12]
```diff
@@ -0,0 +1,927 @@
...
+import static java.util.Collections.singletonMap;
+import static org.hamcrest.Matchers.equalTo;
+import static org.hamcrest.Matchers.is;
+import static org.hamcrest.Matchers.oneOf;
+import static org.hamcrest.Matchers.sameInstance;
+import static org.opensearch.cluster.routing.ShardRoutingState.INITIALIZING;
+import static org.opensearch.cluster.routing.ShardRoutingState.STARTED;
+import static org.opensearch.cluster.routing.ShardRoutingState.UNASSIGNED;
+
+public class NodeLoadAwareAllocationTests extends OpenSearchAllocationTestCase {
```
Comment (malpani) [inline server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:39]: could you please add a test that mimics pinning shards to node attributes eg. hot/warm setup

**Review by malpani — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 8 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java]: Shard for a `CLOSED` index continues to remain in a `STARTED` state usually, so that should be factored in `node.numberOfOwningShards()`

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java (hunk 10 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:106]: It's just a change in behaviour from what `cluster.routing.allocation.total_shards_per_node` limit offers. It doesn't allow unassigned primaries. If users want a similar behaviour as provided by this setting they can opt in for disabling this

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java (hunk 11 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:109]: I gave it some thought. Few reasons why I think keeping it simple and supporting only homogenous deployments as the only default support for now makes sense
1. The `routing.allocation.require` index settings doesn't guarantee that other shards can't get allocated to the node with the particular. So unless all indices mandatorily have a mutually exclusive `routing.allocation.require` settings, it's hard to make a call.
2. The `node.attr` isn't strictly a deployment characteristic, unlike node.role and hence there could be different implementations possible around hot/warm
3. The settings needed as input would make it quite hard to manage for eg there could be different `node.attr` for the same node and for each node key there can be different values. We would need some sort of multi-level provisioned capacity settings per attr key, per attr value

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java (hunk 12 above)
Comment (Bukhtawar) [reply server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:39]: Same as above comments

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java [hunk 13]
```diff
@@ -0,0 +1,129 @@
...
+                CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_SKEW_FACTOR_SETTING.getKey(),
+                CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_PROVISIONED_CAPACITY_SETTING.getKey());
+        }
+        if (shardRouting.unassigned() && shardRouting.primary() && allowUnassignedPrimaries) {
+            return allocation.decision(Decision.YES, NAME,
+                "overload allocation awareness is allowed for unassigned primaries, set cluster setting [%s] to disable it",
+                CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_ALLOW_UNASSIGNED_PRIMARIES_SETTING.getKey());
+        }
+        Metadata metadata = allocation.metadata();
+        float expectedAvgShardsPerNode = (float) metadata.getTotalNumberOfShards() / provisionedCapacity;
```
Comment (getsaurabh02) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:116]: With node exclusion settings enabled, such as with ``ip`` or zone attribute, the ``expectedAvgShardsPerNode`` calculation can go wrong unless the ``provisionedCapacity`` is explicitly updated.

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java [hunk 14]
```diff
@@ -0,0 +1,1220 @@
...
+            .put(NodeLoadAwareAllocationDecider.CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_SKEW_FACTOR_SETTING.getKey(), 50)
+            .put(NodeLoadAwareAllocationDecider.CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_ALLOW_UNASSIGNED_PRIMARIES_SETTING.getKey(),
+                false)
+            .build(), gatewayAllocator);
+
+        logger.info("Building initial routing table for 'testExistingPrimariesAllocationOnOverload'");
+
+        Metadata metadata = Metadata.builder()
+            .put(IndexMetadata.builder("test").settings(settings(Version.CURRENT)).numberOfShards(20).numberOfReplicas(0))
+            .build();
```
Comment (getsaurabh02) [inline server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:264]: Thanks for adding this test. This is useful. Do you think having replicas as well, would have demonstrated that only primaries are being force allocated, while replicas remain unassigned when the nodes join back.

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 4 above)
Comment (getsaurabh02) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java]: > we still want new index creation to go through assigning the primaries as an exception to the overload limit

I agree, and that could be the default behaviour i suppose.

>on the contrary node with least weight is more likely to assign most or all primary shards

This implies that allocation decision is anyways preferring the nodes with relatively less number of shards. And this setting is actually not avoiding any distribution overload for newly created shards.

Wondering if this setting can be unintentionally more intrusive to customer workload, than the wins it actually offers.

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 9 above)
Comment (getsaurabh02) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java]: >Given there is a way to define priority today, we can see if that makes sense as a follow up

That was the concern, since overload limit will be first utilised by the index with highest priority, which in general will also be the index with most resource consumption.

In the above example, lets say if the overload of 100 shards per node is allowed, the impacting index will just fill in those slot first, while less important indices may remain unassigned. This can defy the overall goal.

Agree this can be built incremental, however seems quite necessary. Hence the suggestion.

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java (hunk 13 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:116]: Provisioned capacity is what is actually provisioned and any infra changes would need to appropriately adjust it. For most cases the overload factor should be able to provide sufficient cushion

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java (hunk 14 above)
Comment (Bukhtawar) [reply server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:264]: Thats a test in for the `canForceAllocatePrimary` since there is nothing spl that this code does for 
>while replicas remain unassigned when the nodes join back

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 9 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java]: The right solution is to factor in actual heat and get rid of these limits. Unfortunately that might need more time before we see heat based deciders. I would rather keep this simple for now

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 4 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java]: Have explained it https://github.com/opensearch-project/OpenSearch/pull/1149#discussion_r705311241

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java (hunk 9 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java]: > This can defy the overall goal 

This is not true, the shard allocation algorithm will balance out shards of the same index across nodes. This limit will prevent non-prioritized index to get overloaded on the same node as the one with high priority.

Comment (getsaurabh02) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeOverloadAwareAllocationDecider.java]: >Unfortunately that might need more time before we see heat based deciders

Agree, however I still feel until then capability to avoid overload at the index level, will allow customers to have even distribution of indices that they most care about. 

> This limit will prevent non-prioritized index to get overloaded on the same node as the one with high priority beyond the overload limit

Exactly my point, since for customers the high-priority index would be those with more active reads and writes, they in-turn become the indices which are more resource intensive, and should be more evenly distributed. These indices hence should not be allowed to be overloaded beyond the set threshold by customer. But as stated in the above example, since the overload limit is applicable across all shards, the high-priority index will end up being allocated and skewed. 

I will suggest we evaluate this and do a quick follow-up.

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java (hunk 14 above)
Comment (getsaurabh02) [reply server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:264]: To assert on the exclusiveness of the behaviour which applies to existing primary but not to existing replica. If that is covered elsewhere it is fine.

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java [hunk 15]
```diff
@@ -0,0 +1,1220 @@
...
+            .put(ThrottlingAllocationDecider.CLUSTER_ROUTING_ALLOCATION_NODE_CONCURRENT_RECOVERIES_SETTING.getKey(), 20)
+            .put(ThrottlingAllocationDecider.CLUSTER_ROUTING_ALLOCATION_NODE_INITIAL_PRIMARIES_RECOVERIES_SETTING.getKey(), 20)
+            .put(ThrottlingAllocationDecider.CLUSTER_ROUTING_ALLOCATION_NODE_INITIAL_REPLICAS_RECOVERIES_SETTING.getKey(), 20)
+            .put(ClusterRebalanceAllocationDecider.CLUSTER_ROUTING_ALLOCATION_ALLOW_REBALANCE_SETTING.getKey(), "always")
+            .put(NodeLoadAwareAllocationDecider.CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_PROVISIONED_CAPACITY_SETTING.getKey(), 5)
+            .put(NodeLoadAwareAllocationDecider.CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_SKEW_FACTOR_SETTING.getKey(), 20)
+            .put(NodeLoadAwareAllocationDecider.CLUSTER_ROUTING_ALLOCATION_LOAD_AWARENESS_ALLOW_UNASSIGNED_PRIMARIES_SETTING.getKey(),
+                false)
+            .build(), gatewayAllocator);
+
```
Comment (getsaurabh02) [inline server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:518]: Looks like some of the allocation service initialization can be moved to a common place such as Before Test. And only on settings updates can be applied inside as required.

**Review by getsaurabh02 — APPROVED** [review]

**Review by malpani — APPROVED** [review]
Thanks! this can help mitigate ingestion latency issues seen during zonal imbalance scenarios where multiple shards end up concentrated on a few set of nodes (when there is zonal skew)

**Comment by adnapibar** [comment]
start gradle check

**Comment by adnapibar** [comment]
start gradle check

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java [hunk 16]
```diff
@@ -0,0 +1,129 @@
...
+ * based on overload factor defined as a percentage by
+ * <pre>
+ * cluster.routing.allocation.load_awareness.skew_factor: X
+ * </pre>
+ * The total limit per node based on skew_factor doesn't limit primaries that previously
+ * existed on the disk as those shards are force allocated by
+ * {@link AllocationDeciders#canForceAllocatePrimary(ShardRouting, RoutingNode, RoutingAllocation)}
+ * however new primaries due to index creation, snapshot restore etc can be controlled via the below settings
+ * <pre>
+ * cluster.routing.allocation.load_awareness.allow_unassigned_primaries
```
Comment (muralikpbhat) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:43]: Consider renaming allow_unassigned_primaries or explain the behaviour when it is set to true vs false.

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java [hunk 17]
```diff
@@ -0,0 +1,1220 @@
...
+import static org.opensearch.cluster.routing.ShardRoutingState.INITIALIZING;
+import static org.opensearch.cluster.routing.ShardRoutingState.STARTED;
+import static org.opensearch.cluster.routing.ShardRoutingState.UNASSIGNED;
+
+public class NodeLoadAwareAllocationTests extends OpenSearchAllocationTestCase {
+
+    private final Logger logger = LogManager.getLogger(NodeLoadAwareAllocationTests.class);
+
+    public void testNewUnassignedPrimaryAllocationOnOverload() {
+        AllocationService strategy = createAllocationService(Settings.builder()
```
Comment (muralikpbhat) [inline server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:44]: Each of the test is too long, one option would be to abstract this 10 lines out and only pass values that are changing.

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java [hunk 18]
```diff
@@ -0,0 +1,1220 @@
...
+            .build();
+
+        RoutingTable initialRoutingTable = RoutingTable.builder()
+            .addAsNew(metadata.index("test"))
+            .build();
+
+        ClusterState clusterState = ClusterState.builder(ClusterName.CLUSTER_NAME_SETTING
+            .getDefault(Settings.EMPTY)).metadata(metadata).routingTable(initialRoutingTable).build();
+
+        logger.info("--> adding three nodes on same zone and do rerouting");
```
Comment (muralikpbhat) [inline server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:68]: you are adding 5

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java [hunk 19]
```diff
@@ -0,0 +1,1220 @@
...
+        clusterState = ClusterState.builder(clusterState).nodes(DiscoveryNodes.builder()
+            .add(newNode("node1", singletonMap("zone", "zone_1")))
+            .add(newNode("node2", singletonMap("zone", "zone_1")))
+            .add(newNode("node3", singletonMap("zone", "zone_1")))
+            .add(newNode("node4", singletonMap("zone", "zone_1")))
+            .add(newNode("node5", singletonMap("zone", "zone_1")))
+        ).build();
```
Comment (muralikpbhat) [inline server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:176]: same , consider abstracting

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java [hunk 20]
```diff
@@ -0,0 +1,1220 @@
...
+        newState = strategy.reroute(newState, "reroute");
+
+        newState = startInitializingShardsAndReroute(strategy, newState);
+
+        assertThat(newState.getRoutingNodes().shardsWithState(STARTED).size(), equalTo(120));
+        assertThat(newState.getRoutingNodes().shardsWithState(UNASSIGNED).size(), equalTo(25));
+        assertThat(newState.getRoutingNodes().shardsWithState(UNASSIGNED).stream().filter(x -> x.primary()).count(), equalTo(5L));
+    }
+
+    public void testThreeZoneTwoReplicaLimitsShardAllocationOnOverload(){
```
Comment (muralikpbhat) [inline server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:545]: nit: space before {

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java [hunk 21]
```diff
@@ -0,0 +1,1220 @@
...
+
+        logger.info("--> add five new node in new zone and reroute");
+        clusterState = ClusterState.builder(clusterState).nodes(DiscoveryNodes.builder(clusterState.nodes())
+            .add(newNode("node6", singletonMap("zone", "zone2")))
+            .add(newNode("node7", singletonMap("zone", "zone2")))
+            .add(newNode("node8", singletonMap("zone", "zone2")))
+            .add(newNode("node9", singletonMap("zone", "zone2")))
+            .add(newNode("node10", singletonMap("zone", "zone2")))
+        ).build();
+        clusterState = strategy.reroute(clusterState, "reroute");
```
Comment (muralikpbhat) [inline server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:598]: consider abstracting, pass nodeX-zoneY map to a method

**Review by muralikpbhat — COMMENTED** [review]
Thanks for the changes. One overall comment is to refactor the tests. Those are really lengthy and painful to review and will be hard to maintain.

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java [hunk 22]
```diff
@@ -0,0 +1,129 @@
...
+ * due to node failures or otherwise on the surviving nodes. The allocation limits
+ * are decided by the user provisioned capacity, to determine if there were lost nodes
+ * <pre>
+ * cluster.routing.allocation.overload_awareness.provisioned_capacity: N
+ * </pre>
+ * <p>
+ * and prevent allocation on the surviving nodes of the under capacity cluster
+ * based on overload factor defined as a percentage by
+ * <pre>
+ * cluster.routing.allocation.load_awareness.skew_factor: X
```
Comment (muralikpbhat) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:36]: 50% skew means 25% node failures it can handle. Just thinking what is more easier for user to calculate and set? Is it how much more shards he should allow per node or how many node failures he can tolerate?

Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:36]: shards per node is the common balancing factor and determines the actual performance parameters, node loss can mean data loss without any overload too. So I would say shards per node is more deterministic

Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:36]: Also there is already a settings that clients are exposed to today, so maybe it is actually getting used too 
`cluster.routing.allocation.total_shards_per_node` . This setting is just another relaxed variation of this that also factors in the growing needs of the cluster also very soft on primaries.

Comment (muralikpbhat) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:36]: ok, makes sense

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java [hunk 23]
```diff
@@ -0,0 +1,129 @@
...
+        Metadata metadata = allocation.metadata();
+        float expectedAvgShardsPerNode = (float) metadata.getTotalNumberOfShards() / provisionedCapacity;
+        int nodeShardCount = node.numberOfOwningShards();
+        int limit = (int) Math.ceil(expectedAvgShardsPerNode * (1 + skewFactor / 100.0));
+        if (decider.test(nodeShardCount, limit)) {
+            logger.debug(() -> new ParameterizedMessage("Too many shards [{}] allocated to this node [{}]. Expected average shards" +
+                " per node [{}], overload factor [{}], node limit [{}]", nodeShardCount, node.nodeId(), expectedAvgShardsPerNode,
+                skewFactor, limit));
+            return allocation.decision(Decision.NO, NAME,
+                "too many shards [%d] allocated to this node, limit per node [%d] for overload factor [%s] based on capacity [%d]",
```
[the remark this answers is not in the document]
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:124]: Yes since unassigned primaries don't honour the limits, so we might see a higher count than limit

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java [hunk 24]
```diff
@@ -25,7 +25,9 @@
 /**
  * This {@link NodeLoadAwareAllocationDecider} controls shard over-allocation
  * due to node failures or otherwise on the surviving nodes. The allocation limits
- * are decided by the user provisioned capacity, to determine if there were lost nodes
+ * are decided by the user provisioned capacity, to determine if there were lost nodes.
+ * The provisioned capacity as defined by the below settings needs to updated one every
```
Comment (muralikpbhat) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java:29]: typo

File: server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java [hunk 25]
```diff
@@ -323,20 +278,14 @@ public void testExistingPrimariesAllocationOnOverload() {
         assertThat(newState.getRoutingNodes().node("node4").size(), equalTo(12));
 
         logger.info("--> Remove node4 from zone holding primaries");
-        newState = removeNode(newState, "node4", strategy);
+        newState = removeNodes(newState, strategy,"node4");
```
Comment (muralikpbhat) [inline server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java:281]: nit: space after ,

**Review by muralikpbhat — COMMENTED** [review]
nice refactor, thanks.

**Review by muralikpbhat — APPROVED** [review]

**Review by shwetathareja — APPROVED** [review]

**Comment by shwetathareja** [comment]
start gradle check

**Comment by adnapibar** [comment]
start gradle check
