### PR TITLE
[Segment Replication] Fix shrink Index bug with segment replication.

### LINKED ISSUE #9419: [BUG][Segment Replication] ShrinkIndexIT is failing with segment replication enabled.
**Describe the bug**
ShrinkIndexIT and SplitIndexIT are failing with segment replication enabled.

```
java.lang.AssertionError: failed on [target][0], node[mVHAq0WlTUWjr8Y-urs39A], [R], s[STARTED], a[id=RD-RPj4DS6-rGImemVL1Mg]
Expected: <-1L>
     but: was <-9223372036854775808L>
Expected :<-1L>
Actual   :<-9223372036854775808L>
<Click to see difference>


	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.opensearch.action.admin.indices.create.ShrinkIndexIT.testCreateShrinkIndex(ShrinkIndexIT.java:359)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)

```

**To Reproduce**
`REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.action.admin.indices.create.ShrinkIndexIT.testCreateShrinkIndex" -Dtests.seed=5DDE054F874B4453 -Dtests.locale=is -Dtests.timezone=Europe/Lisbon -Druntime.java=14`

-> Enable segment replication
-> Run ShrinkIndexIT and SplitIndexIT test classes

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR adds logic to check if replicas have caught up on shrink index request path if not it throws exception to user.
This PR also adds few integ tests to verify split and clone index requests work as expected with segment replication.

### Related Issues
Resolves #9419 and #9750

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java [hunk 1]
```diff
@@ -138,26 +146,93 @@ protected void clusterManagerOperation(
...
-            }));
 
+        IndexMetadata indexMetadata = state.metadata().index(sourceIndex);
+        if (state.metadata().isSegmentReplicationEnabled(sourceIndex)
+            && Integer.valueOf(indexMetadata.getSettings().get("index.number_of_replicas")) > 0
+            && resizeRequest.getResizeType().equals(ResizeType.SHRINK)) {
+            client.admin()
+                .indices()
+                .prepareStats(sourceIndex)
+                .setRefresh(true)
```
Comment (mch2) [inline server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java:157]: This is setting the flag for returning refresh stats, why do we need those?  If you do need that, you are clearing flags immediately after so this wont' fetch them.

File: server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java [hunk 2]
```diff
@@ -138,26 +146,93 @@ protected void clusterManagerOperation(
...
+                .setDocs(true)
+                .setStore(true)
+                .execute(ActionListener.delegateFailure(listener, (delegatedListener, indicesStatsResponse) -> {
+                    CreateIndexClusterStateUpdateRequest updateRequest = prepareCreateIndexRequest(resizeRequest, state, i -> {
+                        IndexShardStats shard = indicesStatsResponse.getIndex(sourceIndex).getIndexShards().get(i);
+                        return shard == null ? null : shard.getPrimary().getDocs();
+                    }, indicesStatsResponse.getPrimaries().store, sourceIndex, targetIndex);
+
+                    try {
+                        Thread.sleep(1000);
```
Comment (mch2) [inline server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java:168]: Why are you sleeping here?

File: server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java [hunk 3]
```diff
@@ -138,26 +146,93 @@ protected void clusterManagerOperation(
...
+                        )
+                    );
+                }));
+        }
+
+    }
+
+    private boolean verifyDocCountOnReplicationGroup(IndicesStatsResponse indicesStatsResponse, String index) {
+        Map<ShardId, List<ShardStats>> shardStatsMap = new HashMap<>();
+        for (Map.Entry<ShardRouting, ShardStats> map : indicesStatsResponse.asMap().entrySet()) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java:220]:
```suggestion
        for (Map.Entry<ShardRouting, ShardStats> entry : indicesStatsResponse.asMap().entrySet()) {
```

File: server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java [hunk 4]
```diff
@@ -138,26 +146,93 @@ protected void clusterManagerOperation(
...
+            if (shardStatsMap.containsKey(map.getKey().shardId())) {
+                shardStatsMap.get(map.getKey().shardId()).add(map.getValue());
+            } else {
+                shardStatsMap.put(map.getKey().shardId(), new ArrayList<ShardStats>(Arrays.asList(map.getValue())));
+            }
+        }
+        for (Map.Entry<ShardId, List<ShardStats>> map : shardStatsMap.entrySet()) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java:227]:
```suggestion
        for (Map.Entry<ShardId, List<ShardStats>> entry : shardStatsMap.entrySet()) {
```

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 5]
```diff
@@ -993,7 +993,7 @@ private Engine.IndexResult applyIndexOperation(
 
         // For Segment Replication enabled replica shards we can be skip parsing the documents as we directly copy segments from primary
         // shard.
-        if (indexSettings.isSegRepEnabled() && routingEntry().primary() == false) {
+        if (indexSettings.isSegRepEnabled() && routingEntry().primary() == false && getReplicationEngine().isPresent()) {
```
[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:996]: with segrep during relocation new primary will have nrtengine before it flips it's engine. So this change fixes that bug

File: server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java [hunk 6]
```diff
@@ -438,6 +440,13 @@ protected final void closeNoLock(String reason, CountDownLatch closedLatch) {
         }
     }
 
+    @Override
+    protected final void writerSegmentStats(SegmentsStats stats) {
+        stats.addVersionMapMemoryInBytes(0);
```
[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java:445]: Yeah these aren’t needed for replicas with segrep, but if we enabled segrep accross board in future tests in shrinkIndexIT will fail as the test asserts on replica having stats. we either need to update the test to be compatable with segrep or make the change done here

File: server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java [hunk 7]
```diff
@@ -63,6 +64,7 @@ public class NRTReplicationEngine extends Engine {
     protected final ReplicaFileTracker replicaFileTracker;
 
     private volatile long lastReceivedPrimaryGen = SequenceNumbers.NO_OPS_PERFORMED;
+    private final AtomicLong maxUnsafeAutoIdTimestamp = new AtomicLong(-1);
```
[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java:67]: Yeah these aren’t needed for replicas with segrep, but if we enabled segrep accross board in future tests in shrinkIndexIT will fail as the test asserts on replica having stats. we either need to update the test to be compatible with segrep or make the change done here

File: server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java (hunk 2 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java:168]: sorry got in by mistake

File: server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java [hunk 8]
```diff
@@ -138,26 +146,93 @@ protected void clusterManagerOperation(
...
-                        delegatedListener,
-                        response -> new ResizeResponse(response.isAcknowledged(), response.isShardsAcknowledged(), updateRequest.index())
-                    )
-                );
-            }));
 
+        IndexMetadata indexMetadata = state.metadata().index(sourceIndex);
+        if (state.metadata().isSegmentReplicationEnabled(sourceIndex)
+            && Integer.valueOf(indexMetadata.getSettings().get("index.number_of_replicas")) > 0
+            && resizeRequest.getResizeType().equals(ResizeType.SHRINK)) {
```
[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java:153]: sure I will update this

File: server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java [hunk 9]
```diff
@@ -138,26 +146,93 @@ protected void clusterManagerOperation(
...
-                    ActionListener.map(
-                        delegatedListener,
-                        response -> new ResizeResponse(response.isAcknowledged(), response.isShardsAcknowledged(), updateRequest.index())
-                    )
-                );
-            }));
 
+        IndexMetadata indexMetadata = state.metadata().index(sourceIndex);
+        if (state.metadata().isSegmentReplicationEnabled(sourceIndex)
+            && Integer.valueOf(indexMetadata.getSettings().get("index.number_of_replicas")) > 0
```
[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java:152]: Thanks for catching this. I will add a null check

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (mch2) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:996]: Do you have a test case to repro this bug?  This doesn't seem related to shrink?

File: server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java [hunk 10]
```diff
@@ -138,26 +148,95 @@ protected void clusterManagerOperation(
...
+                                updateRequest.index()
+                            )
+                        )
+                    );
+                }));
+        }
+
+    }
+
+    private boolean verifyDocCountOnReplicationGroup(IndicesStatsResponse indicesStatsResponse, String index) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java:222]: We shouldn't be using doc count here as a reliable measurement for if the replica is current, this will not be accurate post merges.  We could use bytes behind that will be introduced with https://github.com/opensearch-project/OpenSearch/issues/9417.

Comment (mch2) [reply server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java:222]: Another alternative is seqNo stats.  However, these aren't as reliable with segRep because we only update the processed after a new commit has been made on the primary.  So the replica could be caught up and not reflect that in its seqNo stats.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java]: sorry I was wrong it is not related to shrink. I have removed this from my latest commit

File: server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java (hunk 10 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java]: Yes I have updated that in latest commit and added check on bytes behind

**Review by dreamer-89 — APPROVED** [review]
Thanks @Rishikesh1159 for fixing this.
