### PR TITLE
[Searchable Snapshot] Fix bug of Searchable Snapshot Dependency on repository chunk_size

### LINKED ISSUE #9676: [BUG] Searchable snapshot dependency on repository `chunk_size`
## Background

Every repository implementation accepts an [optional `chunk_size` parameter](https://opensearch.org/docs/latest/api-reference/snapshots/create-repository/) at repository creation time. This property defines the maximum file size that will be uploaded to the repository. Any files larger than that will be broken into smaller files of `chunk_size` size (with the last chunk potentially smaller).

Searchable snapshots work by fetching partial index files on-demand at search time, and storing these parts as 8MiB (current hard-coded default) files on disk (unless the entire file is smaller than 8MiB). A virtual `IndexInput` wraps this logic, given the appearance to the upper layers of a single file while the implementation fetches and reads what is needed from these 8MiB partial files. [Some clever logic in this code](https://github.com/opensearch-project/OpenSearch/blob/7da292ba2a75fd394dc782b5ee66c0b560cac9db/server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java#L351-L361) relies on the partial file size being a power of 2 to leverage bit shifting techniques to convert "block number" into an actual byte offset.

## Bug

The searchable snapshot code [does not handle the case that fetching an 8MiB section of a file might cross one of the snapshot chunk boundaries](https://github.com/opensearch-project/OpenSearch/blob/c42ada8e6d63295684303d46492216f3a6f94049/server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java#L139-L155). This means that if the repository `chunk_size` parameter is not a multiple of 8MiB, then this code will fail. In practice, all default chunk sizes are in fact a multiple of 8MiB (fs: no chunking, s3: 1GiB, gcs: 5TiB, hdfs: no chunking). However a user can configure any value. This was discovered while attempting to implement #9514 and some repositories choose a random value between 100 and 1000 bytes for the test case.

## Possible solution
- Improve OnDemandBlockSnapshotIndexInput to always download the configured block size (i.e. 8MiB) even if that means downloading multiple file parts from the repository.

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR is still in draft version and purpose of this PR is to get some feedback on the approach for resolving the issue.
Once approach is finalized I will put this PR out of draft version and refactor with adding some tests.
The PR implements logic of fetching blocks from multiple chunks of snapshot file.

### Related Issues
Resolves #9676 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java [hunk 1]
```diff
@@ -84,17 +88,47 @@ private static FileCachedIndexInput createIndexInput(FileCache fileCache, BlobCo
         return AccessController.doPrivileged((PrivilegedAction<FileCachedIndexInput>) () -> {
             try {
                 if (Files.exists(request.getFilePath()) == false) {
-                    try (
+                    List<InputStream> inputStreamList = new ArrayList<>();
+                    long partSize = request.getFileInfo().partSize().getBytes();
+                    long blockStart = request.getPosition();
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:93]: Sorry. I did not realize we will have to move the entire block calculation logic down into this class.
The transfer manager should not be concerned with this calculation and should act like a utility to fetch the block instead.

This might require some rework on `FileCachedIndexInput`, but it will be useful even for remote index cases that we are building up to.

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java [hunk 2]
```diff
@@ -88,7 +88,7 @@ protected Settings.Builder randomRepositorySettings() {
     private Settings.Builder chunkedRepositorySettings() {
         final Settings.Builder settings = Settings.builder();
         settings.put("location", randomRepoPath()).put("compress", randomBoolean());
-        settings.put("chunk_size", 2 << 23, ByteSizeUnit.BYTES);
+        settings.put("chunk_size", randomBoolean() ? (2 << 23) : 1000, ByteSizeUnit.BYTES);
```
Comment (kotwanikunal) [inline server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java:91]: I'd rather make it parameterized and add another test case for it. You can accept chunk size as an input.

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java (hunk 1 above)
Comment (kotwanikunal) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:93]: A quick thought here (will need refinements) -  

Within `OnDemandSnapshotBlockIndexInput`, we can handle the part calculation logic as follows - 

```
protected IndexInput fetchBlock(int blockId) throws IOException {
        final String blockFileName = fileName + "." + blockId;

        final long blockStart = getBlockStart(blockId);
        final long blockEnd = blockStart + getActualBlockSize(blockId);

        // If the snapshot file is chunked, we must account for this by
        // choosing the appropriate file part and updating the position
        // accordingly.
        final int startPartNumber = (int) (blockStart / partSize);
        final long partStart = startPartNumber * partSize;

        // Detect here if there are two chunks to be visited.
        // Add `append=true` to the blob fetch request
        // Change the API to only download blobs and open later.
        final int endPartNumber = (int) (blockEnd / partSize);

        final long position = blockStart - partStart;
        final long length = blockEnd - blockStart;

        BlobFetchRequest blobFetchRequest = BlobFetchRequest.builder()
            .position(position)
            .length(length)
            .blobName(fileInfo.partName(startPartNumber))
            .directory(directory)
            .fileName(blockFileName)
            .build();
        IndexInput indexInput = transferManager.fetchBlob(blobFetchRequest);

        if (endPartNumber != startPartNumber) {
           // recalculate position and length
            blobFetchRequest = BlobFetchRequest.builder()
                .position(position)
                .length(length)
                .blobName(fileInfo.partName(endPartNumber))
                .directory(directory)
                .fileName(blockFileName)
                .appendToFile(true)
                .build();
           indexInput = transferManager.fetchBlob(blobFetchRequest);
        }

        return indexInput;
    }
```

and within TransferManager - 

```
private static FileCachedIndexInput createIndexInput(FileCache fileCache, BlobContainer blobContainer, BlobFetchRequest request) {
        // We need to do a privileged action here in order to fetch from remote
        // and write to the local file cache in case this is invoked as a side
        // effect of a plugin (such as a scripted search) that doesn't have the
        // necessary permissions.
        return AccessController.doPrivileged((PrivilegedAction<FileCachedIndexInput>) () -> {
            try {
                if (Files.exists(request.getFilePath()) == false || request.appendToFile() == true) {
                    try (
                        InputStream snapshotFileInputStream = blobContainer.readBlob(
                            request.getBlobName(),
                            request.getPosition(),
                            request.getLength()
                        );
                        OutputStream fileOutputStream = Files.newOutputStream(request.getFilePath(), request.appendToFile() ?APPEND : null);
                        OutputStream localFileOutputStream = new BufferedOutputStream(fileOutputStream)
                    ) {
                        snapshotFileInputStream.transferTo(localFileOutputStream);
                    }
                }
                final IndexInput luceneIndexInput = request.getDirectory().openInput(request.getFileName(), IOContext.READ);
                return new FileCachedIndexInput(fileCache, request.getFilePath(), luceneIndexInput);
            } catch (IOException e) {
                throw new UncheckedIOException(e);
            }
        });
    }
```

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:93]: I tried this, but problem of looping every chunk from SnapshotBlockIndexInput is in TransferManger [here](https://github.com/opensearch-project/OpenSearch/blob/03e415e8956dbc63b014f6b49c10650d353c90ca/server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java#L58C1-L66C12) we check if file cache already exists in location if it is  , then we don't create new filecache instead we use existing cache. So, in our case we are only fetching first chunk, and for all of next chunks instead of fetching new chunk, we are returning same old chunk

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java (hunk 2 above)
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java]: Done updated this in latest commit.

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java (hunk 1 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: Using List to collect all blobfetchrequests at once in a loop and sending the `List<BlobFetchRequest>` to TransferManager. Updated the logic in new commit to fix above issue

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java [hunk 3]
```diff
@@ -76,28 +82,41 @@ public IndexInput fetchBlob(BlobFetchRequest blobFetchRequest) throws IOExceptio
...
+                if (Files.exists(requestList.get(0).getFilePath()) == false) {
+                    for (BlobFetchRequest request : requestList) {
+                        try (
+                            InputStream snapshotFileInputStream = blobContainer.readBlob(
+                                request.getBlobName(),
+                                request.getPosition(),
+                                request.getLength()
+                            );
+                            OutputStream fileOutputStream = needsAppend
+                                ? Files.newOutputStream(request.getFilePath(), APPEND)
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:107]: I think you should only need to open the local file once, i.e. create the local file and then start looping over the remote parts writing to the local file. Then the local file gets closed after all parts have been downloaded.

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: Without using APPEND, every loop we will be overriding the local file, so always only last chunk will be written. I have updated this logic in latest commit, instead of create a new outputstream everytime create it only twice: once for creating empty file, another for specifying append option. (without having a new file already created append option will fail).

Please let me know if you have any other suggestions here

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java [hunk 4]
```diff
@@ -76,28 +82,41 @@ public IndexInput fetchBlob(BlobFetchRequest blobFetchRequest) throws IOExceptio
...
-                            request.getBlobName(),
-                            request.getPosition(),
-                            request.getLength()
-                        );
-                        OutputStream fileOutputStream = Files.newOutputStream(request.getFilePath());
-                        OutputStream localFileOutputStream = new BufferedOutputStream(fileOutputStream)
-                    ) {
-                        snapshotFileInputStream.transferTo(localFileOutputStream);
+                boolean needsAppend = false;
+                if (Files.exists(requestList.get(0).getFilePath()) == false) {
```
[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: Thanks for suggestion @andrross . Yes you are right, the structure you suggested is much cleaner and better. I have updated the PR with changes in latest commit

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java [hunk 5]
```diff
@@ -85,15 +87,23 @@ private static FileCachedIndexInput createIndexInput(FileCache fileCache, BlobCo
...
-                            request.getBlobName(),
-                            request.getPosition(),
-                            request.getLength()
-                        );
+                        // Create a new empty file in the specified path
                         OutputStream fileOutputStream = Files.newOutputStream(request.getFilePath());
-                        OutputStream localFileOutputStream = new BufferedOutputStream(fileOutputStream)
+
+                        // All blob parts will be appended to file iteratively.
+                        OutputStream localFileOutputStream = Files.newOutputStream(request.getFilePath(), APPEND)
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:94]:
```suggestion
                        OutputStream localFileOutputStream = new BufferedOutputStream(fileOutputStream)
```

Why doesn't this work? You're missing the buffered output stream in your code, plus I don't see any reason to reopen the file?

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:94]: Sorry while testing I was putting the outstream inside loop and seen overriding in every loop. To overcome this overriding I was using APPEND but when I removed outputstream out of  loop this overriding doesn't happen anymore.

Yes you are right your suggestion is working. Will update the PR in a few

**Comment by Rishikesh1159** [comment]
> ❌ Gradle check result for [04b75fd](https://github.com/opensearch-project/OpenSearch/commit/04b75fdbdb9a482b52aa893e298b3d2f8c86a581): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/34058/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

https://github.com/opensearch-project/OpenSearch/issues/10755

https://github.com/opensearch-project/OpenSearch/issues/12336

File: server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java [hunk 6]
```diff
@@ -139,20 +141,30 @@ protected IndexInput fetchBlock(int blockId) throws IOException {
...
-        return transferManager.fetchBlob(blobFetchRequest);
+        int partNum = (int) (blockStart / partSize);
+        long pos = blockStart;
+        long diff = (blockEnd - blockStart);
+
+        // Block may be present on multiple chunks of a file, so we need
+        // to make multiple blobFetchRequest to fetch an entire block.
+        // Each fetchBlobRequest can fetch only a single chunk of a file.
+        List<BlobFetchRequest.BlobPart> blobParts = new ArrayList<>();
+        while (diff > 0) {
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java:152]: Can we pull this out into a package private method and test different scenarios with UTs?

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java [hunk 7]
```diff
@@ -153,7 +159,11 @@ public IndexInput getIndexInput() throws IOException {
 
         @Override
         public long length() {
-            return request.getLength();
+            long length = 0;
+            for (BlobFetchRequest.BlobPart blobPart : request.blobParts()) {
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:163]: This is better suited as a method of `BlobFetchRequest`. We can calculate it once at object creation / when parts are added to the request and simply return the value here.

File: server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java (hunk 6 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java:152]: Sure I will pull this into a separate method and add some tests

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java (hunk 7 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:163]: Makes sense, I will update this.

File: server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java (hunk 6 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java:163]: Addressed in latest commit

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java (hunk 7 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: Addressed in latest commit

File: server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java [hunk 8]
```diff
@@ -106,7 +106,7 @@ public void testChunkedRepository() throws IOException {
             indexInput.seek(repositoryChunkSize);
         }
         // Verify the second chunk is requested (i.e. ".part1")
-        verify(transferManager).fetchBlob(argThat(request -> request.getBlobName().equals("File_Name.part1")));
+        verify(transferManager).fetchBlob(argThat(request -> request.blobParts().get(0).getBlobName().equals("File_Name.part1")));
     }
 
     private void runAllTestsFor(int blockSizeShift) throws Exception {
```
Comment (andrross) [inline server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java:112]: All the test scenarios in here passed before you made this change (i.e. repository chunk size was a multiple of the block size). We should add some scenarios where the tests would have failed without your change.

Comment (Rishikesh1159) [reply server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java:133]: Sure. Added in latest commit

**Review by andrross — APPROVED** [review]

**Comment by andrross** [comment]
@Rishikesh1159 Looks like a backport was missed, causing the conflict on this PR's backport. Can you create the manual backport after #12485 is merged?

**Comment by kotwanikunal** [comment]
> @Rishikesh1159 Looks like a backport was missed, causing the conflict on this PR's backport. Can you create the manual backport after #12485 is merged?

@Rishikesh1159 / @andrross `opensearch-bot` took care of it :)
