### PR TITLE
[Segment Replication] Fix Flaky Test SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh

### LINKED ISSUE #6531: [Segment Replication][BUG] Flaky Test SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh
**Describe the bug**
When primary shard is relocated, as in this Integ test "testRelocateWhileContinuouslyIndexingAndWaitingForRefresh", on few occurrence old primary is trying to publish checkpoint after switching it's mode from primaryMode to replicaMode and fails. 

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh" -Dtests.seed=EF5EDA2370E498D8 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sl -Dtests.timezone=Europe/Kyiv -Druntime.java=19

org.opensearch.indices.replication.SegmentReplicationRelocationIT > testRelocateWhileContinuouslyIndexingAndWaitingForRefresh FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=117, name=opensearch[node_t0][refresh][T#1], state=RUNNABLE, group=TGRP-SegmentReplicationRelocationIT]
        at __randomizedtesting.SeedInfo.seed([EF5EDA2370E498D8:632A02144EF23820]:0)

        Caused by:
        java.lang.AssertionError: shard [test-idx-1][0], node[aRHMbFpHQ5icIAEeRaxYOQ], relocating [suhONszqTTaGlz_uwm_89w], [P], s[RELOCATING], a[id=hen83BYqQbSNbIsIwoVrfg, rId=XtIfsuxXTZmV3h-e4GoR1Q], expected_shard_size[208] is not a primary shard in primary mode
            at __randomizedtesting.SeedInfo.seed([EF5EDA2370E498D8]:0)
            at org.opensearch.index.shard.IndexShard.assertPrimaryMode(IndexShard.java:2325)
            at org.opensearch.index.shard.IndexShard.getReplicationGroup(IndexShard.java:3004)
            at org.opensearch.indices.replication.checkpoint.PublishCheckpointAction.publish(PublishCheckpointAction.java:121)
            at org.opensearch.indices.replication.checkpoint.SegmentReplicationCheckpointPublisher.publish(SegmentReplicationCheckpointPublisher.java:36)
            at org.opensearch.index.shard.CheckpointRefreshListener.afterRefresh(CheckpointRefreshListener.java:44)
            at org.apache.lucene.search.ReferenceManager.notifyRefreshListenersRefreshed(ReferenceManager.java:275)
            at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:182)
            at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:240)
            at org.opensearch.index.engine.InternalEngine$ExternalReaderManager.refreshIfNeeded(InternalEngine.java:432)
            at org.opensearch.index.engine.InternalEngine$ExternalReaderManager.refreshIfNeeded(InternalEngine.java:412)
            at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:167)
            at org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:213)
            at org.opensearch.index.engine.InternalEngine.refresh(InternalEngine.java:1755)
            at org.opensearch.index.engine.InternalEngine.maybeRefresh(InternalEngine.java:1734)
            at org.opensearch.index.shard.IndexShard.scheduledRefresh(IndexShard.java:4064)
            at org.opensearch.index.IndexService.maybeRefreshEngine(IndexService.java:974)
            at org.opensearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:1107)
            at org.opensearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:159)
            at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
            at java.base/java.lang.Thread.run(Thread.java:1589)
```

**To Reproduce**
Run SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh for few hundred iterations to catch this flaky issue.
**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR triggers refreshes on shards using NRT Engine. We made the decision to not support that behavior wait_until with segrep. So this PR reverts changes made to PublishCheckpointAction class by https://github.com/opensearch-project/OpenSearch/pull/6366

### Issues Resolved
#6531 and #6665

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dreamer-89** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/12301/
> * **CommitID:** [5407a68](https://github.com/opensearch-project/OpenSearch/commit/5407a68131653c93444696ceefb2284b09c12824)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Looks like a legit failure @Rishikesh1159 which needs unit test updates. 
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.replication.checkpoint.PublishCheckpointActionTests.testPublishCheckpointActionOnPrimary" -Dtests.seed=D77C43ABBEE6E324 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ms -Dtests.timezone=Etc/GMT+12 -Druntime.java=19

org.opensearch.indices.replication.checkpoint.PublishCheckpointActionTests > testPublishCheckpointActionOnPrimary FAILED
    junit.framework.AssertionFailedError: Expected exception OpenSearchException but no exception was thrown
        at __randomizedtesting.SeedInfo.seed([D77C43ABBEE6E324:CD7AA1203C0F125B]:0)
        at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2864)
        at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2850)
        at org.opensearch.indices.replication.checkpoint.PublishCheckpointActionTests.testPublishCheckpointActionOnPrimary(PublishCheckpointActionTests.java:109)
```

**Comment by Rishikesh1159** [comment]
When I run `SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh` test locally for 500 iterations to test flakiness, this test fails often with:

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh" -Dtests.seed=E761A1764E6D3555 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en -Dtests.timezone=America/Nassau -Druntime.java=19

org.opensearch.indices.replication.SegmentReplicationRelocationIT > testRelocateWhileContinuouslyIndexingAndWaitingForRefresh FAILED
    java.lang.AssertionError: Expected search hits on node: node_t1 to be at least 1000 but was: 374
        at __randomizedtesting.SeedInfo.seed([E761A1764E6D3555:6B157941707B95AD]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.indices.replication.SegmentReplicationBaseIT.lambda$waitForSearchableDocs$0(SegmentReplicationBaseIT.java:127)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1060)
        at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:122)
        at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:117)
        at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:134)
        at org.opensearch.indices.replication.SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh(SegmentReplicationRelocationIT.java:280)


org.opensearch.transport.RemoteTransportException: [node_t0][127.0.0.1:33209][indices:admin/publishCheckpoint[p]]
  1> Caused by: org.opensearch.action.support.replication.ReplicationOperation$RetryOnPrimaryException: shard is not in primary mode
  1> 	at org.opensearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$1(TransportReplicationAction.java:482) [main/:?]
  1> 	at org.opensearch.action.ActionListener$1.onFailure(ActionListener.java:88) [main/:?]
  1> 	at org.opensearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$34(IndexShard.java:3555) [main/:?]
  1> 	at org.opensearch.action.ActionListener$3.onResponse(ActionListener.java:130) [main/:?]
  1> 	at org.opensearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:58) [main/:?]
  1> 	at org.opensearch.index.shard.IndexShardOperationPermits$2.doRun(IndexShardOperationPermits.java:285) [main/:?]
  1> 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) [main/:?]
  1> 	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:1589) [?:?]
  1> Caused by: org.opensearch.index.shard.ShardNotInPrimaryModeException: CurrentState[STARTED] shard is not in primary mode
  1> 	at org.opensearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$34(IndexShard.java:3555) ~[main/:?]
  1> 	at org.opensearch.action.ActionListener$3.onResponse(ActionListener.java:130) ~[main/:?]
  1> 	at org.opensearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:58) ~[main/:?]
  1> 	at org.opensearch.index.shard.IndexShardOperationPermits$2.doRun(IndexShardOperationPermits.java:285) ~[main/:?]
  1> 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[main/:?]
  1> 	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
  1> 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

Need more deep dive to understand what is causing these to fail.

**Comment by mch2** [comment]
> When I run `SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh` test locally for 500 iterations to test flakiness, this test fails often with:
> 
> ```
> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh" -Dtests.seed=E761A1764E6D3555 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en -Dtests.timezone=America/Nassau -Druntime.java=19
> 
> org.opensearch.indices.replication.SegmentReplicationRelocationIT > testRelocateWhileContinuouslyIndexingAndWaitingForRefresh FAILED
>     java.lang.AssertionError: Expected search hits on node: node_t1 to be at least 1000 but was: 374
>         at __randomizedtesting.SeedInfo.seed([E761A1764E6D3555:6B157941707B95AD]:0)
>         at org.junit.Assert.fail(Assert.java:89)
>         at org.opensearch.indices.replication.SegmentReplicationBaseIT.lambda$waitForSearchableDocs$0(SegmentReplicationBaseIT.java:127)
>         at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1060)
>         at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:122)
>         at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:117)
>         at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:134)
>         at org.opensearch.indices.replication.SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh(SegmentReplicationRelocationIT.java:280)
> 
> 
> org.opensearch.transport.RemoteTransportException: [node_t0][127.0.0.1:33209][indices:admin/publishCheckpoint[p]]
>   1> Caused by: org.opensearch.action.support.replication.ReplicationOperation$RetryOnPrimaryException: shard is not in primary mode
>   1> 	at org.opensearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$1(TransportReplicationAction.java:482) [main/:?]
>   1> 	at org.opensearch.action.ActionListener$1.onFailure(ActionListener.java:88) [main/:?]
>   1> 	at org.opensearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$34(IndexShard.java:3555) [main/:?]
>   1> 	at org.opensearch.action.ActionListener$3.onResponse(ActionListener.java:130) [main/:?]
>   1> 	at org.opensearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:58) [main/:?]
>   1> 	at org.opensearch.index.shard.IndexShardOperationPermits$2.doRun(IndexShardOperationPermits.java:285) [main/:?]
>   1> 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) [main/:?]
>   1> 	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [main/:?]
>   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
>   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
>   1> 	at java.lang.Thread.run(Thread.java:1589) [?:?]
>   1> Caused by: org.opensearch.index.shard.ShardNotInPrimaryModeException: CurrentState[STARTED] shard is not in primary mode
>   1> 	at org.opensearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$34(IndexShard.java:3555) ~[main/:?]
>   1> 	at org.opensearch.action.ActionListener$3.onResponse(ActionListener.java:130) ~[main/:?]
>   1> 	at org.opensearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:58) ~[main/:?]
>   1> 	at org.opensearch.index.shard.IndexShardOperationPermits$2.doRun(IndexShardOperationPermits.java:285) ~[main/:?]
>   1> 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[main/:?]
>   1> 	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[main/:?]
>   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
>   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
>   1> 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
> ```
> 
> Looks like changes made in this PR are not fixing flakiness of this test. Need more deep dive to understand what is causing these to fail. I will soon update the PR with new changes that will fix the flakiness

@Rishikesh1159 
The first exception looks like the new primary that is ahead is not publishing to replicas post relocation, causing the doc count mismatch - This is issue 4 here - https://github.com/opensearch-project/OpenSearch/issues/6065#issuecomment-1436087791.

The second exception look like a checkpoint gets published while the shard is relocating, at some point during relocation it flips out of primary mode, and the publish fails with performOnPrimary step.

There are a couple of options here.  We either 
1. Outright prevent any checkpoint publishing while the shard is relocating.  Meaning replicas will fall behind during the relocation process & catch up from the new primary.
2. Prevent any new checkpoint from being published once the primary successfully blocks operations and/or relocation handoff is in progress.  At which point the only shard that can sync to the primary is the relocation target (this is already done manually) right before the relocation handoff.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 1]
```diff
@@ -566,6 +566,9 @@ public void updateShardState(
                     : "a primary relocation is completed by the cluster-managerr, but primary mode is not active " + currentRouting;
 
                 changeState(IndexShardState.STARTED, "global state is [" + newRouting.state() + "]");
+                if (indexSettings.isSegRepEnabled()) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:569]: Can we add a comment here on why this is required? I think this is so new primary shards will push to replicas after relocation rather than waiting for more docs to get indexed?

File: server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java [hunk 2]
```diff
@@ -569,21 +568,15 @@ public void testReplicaReceivesLowerGeneration() throws Exception {
...
-            assertLatestCommitGen(5, replica_1);
-            assertLatestCommitGen(3, replica_2);
 
             shards.promoteReplicaToPrimary(replica_2).get();
             primary.close("demoted", false);
             primary.store().close();
             IndexShard oldPrimary = shards.addReplicaWithExistingPath(primary.shardPath(), primary.routingEntry().currentNodeId());
             shards.recoverReplica(oldPrimary);
-            assertLatestCommitGen(5, oldPrimary);
-            assertLatestCommitGen(5, replica_2);
```
Comment (mch2) [inline server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java:586]: Thanks for doing this, this test is flaky and we really don't care about the generation only that the doc counts are equal.

File: server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java [hunk 3]
```diff
@@ -51,6 +51,10 @@ public class NRTReplicationReaderManager extends OpenSearchReaderManager {
     @Override
     protected OpenSearchDirectoryReader refreshIfNeeded(OpenSearchDirectoryReader referenceToRefresh) throws IOException {
         Objects.requireNonNull(referenceToRefresh);
+        // checks if an actual refresh (change in segments) happened
+        if (unwrapStandardReader(referenceToRefresh).getSegmentInfos().version == currentInfos.version) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java:55]: Can you pls add a unit test for this change in `NRTReplicationEngineTests` ?

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 1 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:572]: Yes, new primary shards will push to replicas after relocation rather than waiting for more docs to get indexed

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java [hunk 4]
```diff
@@ -494,4 +495,63 @@ public void testAddNewReplicaFailure() throws Exception {
...
+            .prepareHealth()
+            .setWaitForEvents(Priority.LANGUID)
+            .setWaitForNoRelocatingShards(true)
+            .setTimeout(ACCEPTABLE_RELOCATION_TIME)
+            .execute()
+            .actionGet();
+        assertEquals(clusterHealthResponse.isTimedOut(), false);
+
+        // Verify if all docs are present in replica after flush, if new relocated primary doesn't flush after relocation the below assert
+        // will fail
```
[the remark this answers is not in the document]
Comment (dreamer-89) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java:553]: Basically, we need not perform any refresh and turn all aync calls to sync here. 
1. Index docs in sync without refresh so that only primary contains all the data before relocation. 
2. Assert doc count on primary is matching ingested doc count and replica should have 0 doc count
3. Relocate primary to new primary node and wait for it to complete. 
4. Assert replica gets all the docs (this should only be possible from flush operation before state switch to `STARTED`.

[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java:553]: Sure, makes sense. This way it will fail more definitively without flush. Thanks @dreamer-89 , I will update the test

[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java]: Asserting doc count on primary before relocation is not possible as without a refresh even on primary shard, it will have 0 docs, as we open searcher only after a refresh. So instead I am asserting on segrep stats that no replication event has taken place on replica shard before relocation

**Review by dreamer-89 — APPROVED** [review]
LGTM! 
Let's also wait for @mch2 review.

**Review by mch2 — APPROVED** [review]
