### PR TITLE
[Remote Store] Fix relocation failure due to transport receive timeout

### LINKED ISSUE #10727: [BUG] [Remote Store] Timeout on shard relocation
**Describe the bug**
Triggering a relocation event for a large shard results in a failure caused by a timeout.

**To Reproduce**
- Create a 2 node cluster.
- Create an index with 2 primary shards and ensure each node gets 1 shard.
- Index about 25GB of data into each shard.
- Create an exclusion rule to force one of the shards to relocate, e.g.:
```
curl -s -XPUT 'localhost:9200/_cluster/settings' -H 'Content-Type:application/json' -d '{
   "persistent":{
      "cluster.routing.allocation.exclude._name": "8714cc6c80113d27569bbf190a52a669"
   }
}'
```
Observe the following exception in the logs:
```
[2023-10-19T02:05:46,382][WARN ][o.o.i.c.IndicesClusterStateService] [30ddfff069f4928ae20b3f7f9046e41f] [nyc_taxis][2] marking and sending shard failed due to [failed recovery]
RecoveryFailedException[[nyc_taxis][2]: Recovery failed from {, remote_
        at org.opensearch.indices.recovery.RecoveryTarget.notifyListener(RecoveryTarget.java:134)
        at org.opensearch.indices.replication.common.ReplicationTarget.fail(ReplicationTarget.java:177)
        at org.opensearch.indices.replication.common.ReplicationCollection.fail(ReplicationCollection.java:212)
        at org.opensearch.indices.recovery.PeerRecoveryTargetService$RecoveryResponseHandler.onException(PeerRecoveryTargetService.java:743)
        at org.opensearch.indices.recovery.PeerRecoveryTargetService$RecoveryResponseHandler.handleException(PeerRecoveryTargetService.java:669)
        at org.opensearch.security.transport.SecurityInterceptor$RestoringTransportResponseHandler.handleException(SecurityInterceptor.java:412)
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1526)
        at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:438)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:858)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: RecoveryFailedException[[nyc_taxis][2]: Recovery failed from {8714cc6c80113d27569bbf190a52a669}{
        ... 9 more
Caused by: RemoteTransportException[[8714cc6c80113d27569bbf190a52a669][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] prepare target for translog fail
Caused by: [nyc_taxis/FPAU1P1hTH-DcuCuzkHWjA][[nyc_taxis][2]] RecoveryEngineException[Phase[1] prepare target for translog failed]; nested: ReceiveTimeoutTransportException[[30ddfff069f4928ae20b3f7f9046e41f][
        at org.opensearch.indices.recovery.RecoverySourceHandler.lambda$prepareTargetForTranslog$22(RecoverySourceHandler.java:629)
        at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90)
        at org.opensearch.core.action.ActionListener$4.onFailure(ActionListener.java:192)
        at org.opensearch.core.action.ActionListener$6.onFailure(ActionListener.java:311)
        at org.opensearch.action.support.RetryableAction$RetryingListener.onFinalFailure(RetryableAction.java:218)
        at org.opensearch.action.support.RetryableAction$RetryingListener.onFailure(RetryableAction.java:210)
        at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:75)
        at org.opensearch.security.transport.SecurityInterceptor$RestoringTransportResponseHandler.handleException(SecurityInterceptor.java:412)
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1526)
        at org.opensearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1417)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:858)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
Caused by: ReceiveTimeoutTransportException[[30ddfff069f4928ae20b3f7f9046e41f][][internal:index/shard/recovery/prepare_translog] request_id [1304756] timed out after [60018ms]]
        at org.opensearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1420)
        ... 4 more
```

**Additional context**
The cause of this may be [the synchronous call to download segments from the remote store in PeerRecoveryTargetService](https://github.com/opensearch-project/OpenSearch/blob/91f9c5dbf417e179c5ab00e49332c17c84661008/server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java#L248).

### PR DESCRIPTION
**Pull request by ashking94**
### Description
This PR solves Peer Recovery failure that can happen due to receive timeout exceptions during prepare translog phase of peer recovery. This type of failure can be prominent in zero replica remote store backed indexes. However this can also happen during slow remote interactions. This PR fixes the problem handles both kind of issues.

This PR handles the following cases - 
- Removes searchIdle support for remote enabled indexes. This means that we continue to refresh and upload segments periodically at the configured refresh interval.
- Fixes the bug where actual translog retention was higher than the translog flush threshold size. 
- Makes the transport timeout configurable for prepare translog phase in peer recovery. This is now controlled through the `indices.recovery.internal_action_long_timeout` index setting. This, by default, is 30 mins.  

### Related Issues
Resolves #10727

### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java [hunk 1]
```diff
@@ -430,10 +430,11 @@ public String getTranslogUUID() {
      * @return if the translog should be flushed
      */
     public boolean shouldPeriodicallyFlush(long localCheckpointOfLastCommit, long flushThreshold) {
-        final long translogGenerationOfLastCommit = translog.getMinGenerationForSeqNo(
-            localCheckpointOfLastCommit + 1
-        ).translogFileGeneration;
-        if (translog.sizeInBytesByMinGen(translogGenerationOfLastCommit) < flushThreshold) {
+        long minRefSeqNo = translog instanceof RemoteFsTranslog
+            ? ((RemoteFsTranslog) translog).getMinSeqNoToKeep()
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java:434]: Can this logic move to `Translog` so that you get polymorphic behavior as opposed to doing the instanceof/casting logic here?

Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java:434]: @andrross In docrep, the min seq no to keep (as translog) consider is obtained using the segment infos which resides in engine. In case of remote store, the min seq no to keep stays in RemoteFsTranslog. Due to this, we had to handle this way. Let me know if you have any suggestion and I can incorporate it.

File: server/src/main/java/org/opensearch/index/IndexSettings.java [hunk 2]
```diff
@@ -1024,6 +1024,9 @@ public IndexSettings(final IndexMetadata indexMetadata, final Settings nodeSetti
     }
 
     private void setSearchIdleAfter(TimeValue searchIdleAfter) {
+        if (this.isRemoteStoreEnabled) {
+            logger.warn("Search idle is not supported for remote backed indices");
+        }
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/IndexSettings.java:1029]: What is the side effect if we throw unsupported exception

File: server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java [hunk 3]
```diff
@@ -129,7 +132,13 @@ public void prepareForTranslogOperations(int totalTranslogOps, ActionListener<Vo
         );
         final Writeable.Reader<TransportResponse.Empty> reader = in -> TransportResponse.Empty.INSTANCE;
         final ActionListener<TransportResponse.Empty> responseListener = ActionListener.map(listener, r -> null);
-        retryableTransportClient.executeRetryableAction(action, request, responseListener, reader);
+        if (remoteStoreEnabled) {
+            // If remote store is enabled, during the prepare_translog phase, translog is also downloaded on the
+            // target host along with incremental segments download. This
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java:137]: nit: do u want to finish your comment?

File: server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java [hunk 4]
```diff
@@ -129,7 +132,13 @@ public void prepareForTranslogOperations(int totalTranslogOps, ActionListener<Vo
...
+            retryableTransportClient.executeRetryableAction(action, request, translogOpsRequestOptions, responseListener, reader);
+        } else {
+            retryableTransportClient.executeRetryableAction(action, request, responseListener, reader);
+        }
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java:141]: Fortunately both long(30m) and default timeouts(15m) are dynamic in nature.

Comment (ashking94) [reply server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java:141]: Reusing the `internalActionLongTimeout` (defaults to 30 mins) which is already being used in `internal:index/shard/recovery/translog_ops` transport action (applicable for docrep). In the existing state, it was using `indices.recovery.internal_action_retry_timeout` which defaults to 1m and hence if you see [here](https://github.com/opensearch-project/OpenSearch/issues/10727#issue-1951058192), we can see `Caused by: ReceiveTimeoutTransportException[[30ddfff069f4928ae20b3f7f9046e41f][][internal:index/shard/recovery/prepare_translog] request_id [1304756] timed out after [60018ms]]
`.

File: server/src/main/java/org/opensearch/index/IndexSettings.java (hunk 2 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/IndexSettings.java:1029]: The update index setting api caller would see an error response. Sample exception when we throw `throw new IllegalArgumentException("test message")` -
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "test message"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "test message"
  },
  "status" : 400
}

```

File: server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java (hunk 1 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java]: Made the change as suggested. Please take a look, @Bukhtawar.

File: server/src/main/java/org/opensearch/index/IndexSettings.java (hunk 2 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/index/IndexSettings.java:1029]: It's better to fail rather than silently failing to honour it.

File: server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java (hunk 4 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java:141]: Can we use the same `internalActionLongTimeout ` for both remote and non-remote store. Would have ideally preferred it.

**Review by Bukhtawar — APPROVED** [review]
LGTM

File: server/src/main/java/org/opensearch/index/IndexSettings.java (hunk 2 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/IndexSettings.java:1029]: This requires a bit more thought, I have created https://github.com/opensearch-project/OpenSearch/issues/10787 for follow up on this.

**Review by andrross — APPROVED** [review]
