### PR TITLE
Include sources and javadoc artifacts while publishing to a Maven repository

### LINKED ISSUE #1028: [Enhancement] javadoc and sources jars not included in maven publications
A requirement of publishing to maven central is to include javadoc and sources jars for java publications.

There are javadoc and sources jar tasks defined with the OpenSearch publish plugin [here](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java#L146).

When running publish commands these artifacts should be build and included with each publication.  Instead these tasks if run separately place them under src/*.
 
**To Reproduce**
1. Clone the repository
2. Execute publishToMavenLocal command
3. Under ~/.m2/repositories/org/opensearch/** See that only .pom, .jar and .module files are included for each.

**Expected behavior**
These artifacts should be included for any jar publication.

**Additional context**
These commands could obviously be executed and then the artifacts copied over from each dir manually, but they should be built & included with a single publish command.

### PR DESCRIPTION
**Pull request by adnapibar**
### Description

This change fixes the issue where running publish commands, the sources and javadoc artifacts were not built and included with the publications.

### Issues Resolved
#1028 
 
### Check List
- [x] All tests pass
- [x] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Rabi Panda <adnapibar@gmail.com>

### CODE REVIEW

**Comment by adnapibar** [comment]
start gradle check

File: buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java [hunk 1]
```diff
@@ -128,6 +128,11 @@ public String call() throws Exception {
             // have to defer this until archivesBaseName is set
             project.afterEvaluate(p -> publication.setArtifactId(getArchivesBaseName(project)));
 
+            if (project.getPlugins().hasPlugin("opensearch.java")) {
+                publication.artifact(project.getTasks().getByName("sourcesJar"));
+                publication.artifact(project.getTasks().getByName("javadocJar"));
+            }
```
Comment (tlfeng) [inline buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java:134]: Minor: Looks like `getPluginManager()` is preferred rather than `getPlugins()`, according to https://discuss.gradle.org/t/using-plugin-manager-vs-plugin-container-in-java-plugin/34682. While I didn't find the reason for that, so it's fine.

**Review by mch2 — APPROVED** [review]
LGTM

**Comment by adnapibar** [comment]
start gradle check

**Review by tlfeng — APPROVED** [review]
