### PR TITLE
[Segment Replication] Fix Flaky test SegmentReplicationRelocationIT.testPrimaryRelocation

### LINKED ISSUE #10029: [BUG] SegmentReplicationRelocationIT.testPrimaryRelocation flaky test failure
Coming from #8279 (comment), SegmentReplicationRelocationIT.testPrimaryRelocation is flaky.

Build with test failures: (24158,25031,25325,25325)

https://build.ci.opensearch.org/job/gradle-check/25325/testReport/org.opensearch.indices.replication/SegmentReplicationRelocationIT/testPrimaryRelocation/

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationRelocationIT.testPrimaryRelocation" -Dtests.seed=ED1E8CCE7D7E124E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nb-NO -Dtests.timezone=Universal -Druntime.java=20
```

Code assertion trip
```
java.lang.AssertionError: shard [test-idx-1][0], node[YFaFseUBQ22NAic2tf48Jw], relocating [IjN5va7VRbO1qpzpYNmImQ], [P], s[RELOCATING], a[id=T4OogwaCT4C05CjkmnGNBQ, rId=uzJujhPHQqKdJk81axlU-g], expected_shard_size[230] is not a primary shard in primary mode
	at __randomizedtesting.SeedInfo.seed([ED1E8CCE7D7E124E]:0)
	at org.opensearch.index.shard.IndexShard.assertPrimaryMode(IndexShard.java:2532)
	at org.opensearch.index.shard.IndexShard.getReplicationGroup(IndexShard.java:3269)
	at org.opensearch.indices.replication.SegmentReplicationSourceHandler.sendFiles(SegmentReplicationSourceHandler.java:149)
	at org.opensearch.indices.replication.OngoingSegmentReplications.startSegmentCopy(OngoingSegmentReplications.java:123)
	at org.opensearch.indices.replication.SegmentReplicationSourceService$GetSegmentFilesRequestHandler.messageReceived(SegmentReplicationSourceService.java:149)
	at org.opensearch.indices.replication.SegmentReplicationSourceService$GetSegmentFilesRequestHandler.messageReceived(SegmentReplicationSourceService.java:146)
	at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106)
	at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:454)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR fixes flaky test SegmentReplicationRelocationIT.testPrimaryRelocation by removing unnecessary shardRouting check
### Related Issues
Resolves #10029 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Poojita-Raj** [comment]
Hey Rishi, this change seems to fix the sendFiles problem in the issue description. How does it fix the corruption issue mentioned here: https://github.com/opensearch-project/OpenSearch/issues/10029#issuecomment-1736619011

**Comment by Rishikesh1159** [comment]
> Hey Rishi, this change seems to fix the sendFiles problem in the issue description. How does it fix the corruption issue mentioned here: [#10029 (comment)](https://github.com/opensearch-project/OpenSearch/issues/10029#issuecomment-1736619011)

@Poojita-Raj I wasn't able to reproduce the failure mentioned [here](https://github.com/opensearch-project/OpenSearch/issues/10029#issuecomment-1736619011). I am assuming failure was related to specific PR but let me check all occurances of this flaky test and see the failure.

**Comment by mch2** [comment]
> > Hey Rishi, this change seems to fix the sendFiles problem in the issue description. How does it fix the corruption issue mentioned here: [#10029 (comment)](https://github.com/opensearch-project/OpenSearch/issues/10029#issuecomment-1736619011)
> 
> @Poojita-Raj I wasn't able to reproduce the failure mentioned [here](https://github.com/opensearch-project/OpenSearch/issues/10029#issuecomment-1736619011). I am assuming failure was related to specific PR but let me check all occurances of this flaky test and see the failure.

Lets add testlogging as well incase it fails again we have more visibility.

File: server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java [hunk 1]
```diff
@@ -146,11 +146,17 @@ public synchronized void sendFiles(GetSegmentFilesRequest request, ActionListene
                 );
             };
             cancellableThreads.checkForCancel();
-            final IndexShardRoutingTable routingTable = shard.getReplicationGroup().getRoutingTable();
-            ShardRouting targetShardRouting = routingTable.getByAllocationId(request.getTargetAllocationId());
-            if (targetShardRouting == null) {
-                logger.debug("delaying replication of {} as it is not listed as assigned to target node {}", shard.shardId(), targetNode);
-                throw new DelayRecoveryException("source node does not have the shard listed in its state as allocated on the node");
+            if (shard.isPrimaryMode()) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java:149]: Even with this check we have a race where it can flip out of primaryMode.  A few things we should look at here - 
1. If the shard is flipping out of primary mode, active replication events where that shard is the source should be getting cancelled.  If this were to throw with not in primary mode we can handle that as a cancellation.  Even if it were to throw today, the replicas should catch up to the newly elected primary.
2. I don't think we need this shardRouting check at all given the replica chunks are being sent to is not in recovery.  This check be handled by RecoverySourceHandler already.

Comment (mch2) [reply server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java]: Correct, but i would leave that for a separate change.  I'm more interested in why a failure here would fail the test?

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java]: The test fails for point 2 because of assert failure on primary mode. assert failure doesn't throw an exception, if some excception was thrown then SR event would be cancelled and relocation will be complete correctly.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java [hunk 2]
```diff
@@ -55,6 +56,7 @@ private void createIndex(int replicaCount) {
      * This test verifies happy path when primary shard is relocated newly added node (target) in the cluster. Before
      * relocation and after relocation documents are indexed and documents are verified
      */
+    @TestLogging(reason = "Getting trace logs from replication package", value = "org.opensearch.indices.replication:TRACE")
```
Comment (dreamer-89) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java:59]: 1. I suspect this problem appears due to the delay in routing changes propagation to old primary (and thus replication event not cancelled). It will be worth adding loggs for Allocation and IndexShard package. 
 2. Since we are only cleaning up and enabling logging as part of this PR, we can update the description.

**Review by dreamer-89 — APPROVED** [review]
