### PR TITLE
[Segment Replication] Fix SearchableSnapshotIT tests failing with segment replication enabled indices

### LINKED ISSUE #7034: [Segment Replication] SearchableSnapshotIT class tests are failing with Segment Replication enabled Indices
**Describe the bug**
Currently SearchableSnapshotIT class tests are failing with Segment Replication enabled Indices. The failure happens when we are restoring snapshot with storage type as `REMOTE_SNAPSHOT`. The possible cause for this failure is [here](https://github.com/opensearch-project/OpenSearch/blob/8b34e5f724fe2b875731228795f51d523462599a/server/src/main/java/org/opensearch/indices/IndicesService.java#L933), as we are wiring up a `NRTReplicationEngineFactor` instead of `ReadOnlyEngine` when the index is `REMOTE_SNAPSHOT`.

```
java.lang.AssertionError: timed out waiting for green state
	at __randomizedtesting.SeedInfo.seed([7CAA2E07C2E84004:2BEC37D99F2F6F46]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1007)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:938)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:927)
	at org.opensearch.snapshots.SearchableSnapshotIT.restoreSnapshotAndEnsureGreen(SearchableSnapshotIT.java:324)
	at org.opensearch.snapshots.SearchableSnapshotIT.testCreateSearchableSnapshotWithChunks(SearchableSnapshotIT.java:136)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
```

**To Reproduce**
Set Segment replication enabled for indices and then run the  SearchableSnapshotIT test suite.

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
When we are restoring snapshot with storage type as REMOTE_SNAPSHOT we should use ReadOnlyEngine. But currectly we are wiring up a NRTReplicationEngineFactor instead of `ReadOnlyEngine`.

 This PR moves up the `isRemoteSnapshot()` check on index setting before we check if `isSegRepEnabled()`.  This way be wire `ReadOnlyEngine` when using remote snapshot.

### Issues Resolved
Resolves #7034 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/indices/IndicesService.java [hunk 1]
```diff
@@ -930,12 +930,12 @@ private EngineFactory getEngineFactory(final IndexSettings idxSettings) {
...
         if (engineFactories.isEmpty()) {
-            if (idxSettings.isSegRepEnabled()) {
-                return new NRTReplicationEngineFactory();
-            }
             if (idxSettings.isRemoteSnapshot()) {
                 return config -> new ReadOnlyEngine(config, new SeqNoStats(0, 0, 0), new TranslogStats(), true, Function.identity(), false);
             }
+            if (idxSettings.isSegRepEnabled()) {
+                return new NRTReplicationEngineFactory();
+            }
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/indices/IndicesService.java:938]: LGTM! Thank you @Rishikesh1159 for fixing this

**Review by dreamer-89 — APPROVED** [review]

**Comment by andrross** [comment]
Is there a plan to run all tests regularly with segment replication enabled? Or should we add a case to SearchableSnapshotIT the explicitly enables it in order to have a test that catches a failure like this?

**Comment by Rishikesh1159** [comment]
> Is there a plan to run all tests regularly with segment replication enabled? Or should we add a case to SearchableSnapshotIT the explicitly enables it in order to have a test that catches a failure like this?

Not soon but in near future, we are planning to run all integ tests regularly with segment replication, like adding randomization in OpensearchIntegTest class that would make test classes to either use segrep or docrep randomly. But we still don't have a solid plan on how we should do it.

 Yeah we can also add a case for SearchableSnapshotIT the explicitly enables, but rather than duplicating it on every other test class it would be better if we can figure a way out to do it with in OpensearchIntegTest

**Review by andrross — APPROVED** [review]
