### PR TITLE
[2.18] Fix NPE in CatShardsRequestTests on version bump

### LINKED ISSUE #16580: [BUG] Test case org.opensearch.action.admin.cluster.shards.CatShardsRequestTests.testSerializationWithOlderVersionsParametersNotSerialized fails with NPE
### Describe the bug

The test case `org.opensearch.action.admin.cluster.shards.CatShardsRequestTests.testSerializationWithOlderVersionsParametersNotSerialized` fails with NPE:

```
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at __randomizedtesting.SeedInfo.seed([644E83AFC71A1C4F:8FD495376ADAAC0E]:0)
	at org.opensearch.core.common.io.stream.StreamOutput.writeString(StreamOutput.java:444)
	at org.opensearch.core.common.io.stream.StreamOutput.writeStringArray(StreamOutput.java:547)
	at org.opensearch.action.admin.cluster.shards.CatShardsRequest.writeTo(CatShardsRequest.java:57)
	at org.opensearch.action.admin.cluster.shards.CatShardsRequestTests.testSerializationWithOlderVersionsParametersNotSerialized(CatShardsRequestTests.java:101)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Related component

Other

### To Reproduce

Pull `https://github.com/opensearch-project/OpenSearch/pull/16571` and run `./gradlew ':server:test' --tests "org.opensearch.action.admin.cluster.shards.CatShardsRequestTests.testSerializationWithOlderVersionsParametersNotSerialized"` 

### Expected behavior

The test case should pass

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description

One of the version changes from https://github.com/opensearch-project/OpenSearch/pull/16455/files was missed when it was manually backported in https://github.com/opensearch-project/OpenSearch/pull/16396.

The test in question is intended to check for a previous version that does not read the array of null strings.  By leaving it at `Version.CURRENT` it bumped to 2.18.1 where 2.18.0 was the previous version and incorrectly tried to read that array.

### Related Issues
Resolves #16580

### Check List
- [x] Functionality includes testing.
- ~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/action/admin/cluster/shards/CatShardsRequestTests.java [hunk 1]
```diff
@@ -95,7 +95,7 @@ public void testSerializationWithOlderVersionsParametersNotSerialized() throws E
         catShardsRequest.setCancelAfterTimeInterval(TimeValue.timeValueMillis(randomIntBetween(1, 5)));
         catShardsRequest.setIndices(new String[2]);
 
-        Version version = VersionUtils.getPreviousVersion(Version.CURRENT);
+        Version version = VersionUtils.getPreviousVersion(Version.V_2_18_0);
```
Comment (reta) [inline server/src/test/java/org/opensearch/action/admin/cluster/shards/CatShardsRequestTests.java:98]: :+1: thanks @dbwiddis !

**Review by reta — APPROVED** [review]

**Review by owaiskazi19 — APPROVED** [review]
