### PR TITLE
Fix flaky RemoteFSTranslogTests testMetadataFileDeletion test #9605

### LINKED ISSUE #9605: [BUG] Test RemoteFSTranslogTests.testMetadataFileDeletion is flaky
https://github.com/opensearch-project/OpenSearch/pull/9595#issuecomment-1696672926

### PR DESCRIPTION
**Pull request by ashking94**
### Description
This closes #9605. The flakiness in this test is on account of translog.trimUnreferencedReaders() being no-op when called due to previous deletion still ongoing and holding the permits. The current run of translog.trimUnreferencedReaders() on checking for permits sees that the required permits are not available and skips the deletion. To elaborate more on generation deletion, the approach is to acquire the permits, trigger async deletion and post successful deletion, release the permits. With this PR, I am making sure that after `trimUnreferencedReaders()`, we check that the required permits are available before calling the same method back again. 

### Related Issues
Resolves #9605 

### Check List
- [ ] ~New functionality includes testing.~
  - [x] All tests pass
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ashking94** [comment]
> ❕ Gradle check result for [a63fa6a](https://github.com/opensearch-project/OpenSearch/commit/a63fa6a728946859d86fb61dafb58ffd3cbf0193): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/32193/)
> 
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing
> ```
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

Flaky test - https://github.com/opensearch-project/OpenSearch/issues/9191

File: server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java [hunk 1]
```diff
@@ -1048,7 +1056,7 @@ public void testConcurrentWriteViewsAndSnapshot() throws Throwable {
             final int threadId = i;
             writers[i] = new Thread(new AbstractRunnable() {
                 @Override
-                public void doRun() throws BrokenBarrierException, InterruptedException, IOException {
+                public void doRun() throws Exception {
```
Comment (deshsidd) [inline server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java:1059]: Why do we want to not explicitly specify all the Exceptions thrown here?

**Review by deshsidd — COMMENTED** [review]
How many times did we run the test to see if the flakiness still persists?

File: server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java (hunk 1 above)
Comment (ashking94) [reply server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java:1059]: It is either ways same as the test would fail if an exception gets thrown. In this case, the IDE autoformat feature decided to replace n-many exceptions to just one Exception class.

**Comment by ashking94** [comment]
> How many times did we run the test to see if the flakiness still persists?

Had run it for 1K+ iterations on local. Running the entire class test suite for couple of hours more.

**Comment by ashking94** [comment]
2K iterations have run without any failures.

**Comment by ashking94** [comment]
3K iterations ran without any failures.

**Review by sachinpkale — APPROVED** [review]
