### PR TITLE
[Flaky Test] Fix Flaky SearchServiceTests.testConcurrentSegmentSearchWithRandomizedModeSettings

### LINKED ISSUE #18238: [AUTOCUT] Gradle Check Flaky Test Report for SearchServiceTests
## Flaky Test Report for `SearchServiceTests`

Noticed the `SearchServiceTests` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| f2cc655c94d53d0c43e88cd93e4da3994184e294 | [18104](https://github.com/opensearch-project/OpenSearch/pull/18104) | [57849](https://build.ci.opensearch.org/job/gradle-check/57849/testReport/) | `org.opensearch.search.SearchServiceTests.testConcurrentSegmentSearchWithRandomizedModeSettings` |
| fb77cc7826a530a6ebbdb4cfe4bf5d5cce4ec99f | [16908](https://github.com/opensearch-project/OpenSearch/pull/16908) | [57852](https://build.ci.opensearch.org/job/gradle-check/57852/testReport/) | `org.opensearch.search.SearchServiceTests.testConcurrentSegmentSearchWithRandomizedModeSettings` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `SearchServiceTests` class are:

- [16366](https://github.com/opensearch-project/OpenSearch/pull/16366)
- [17881](https://github.com/opensearch-project/OpenSearch/pull/17881)
- [17978](https://github.com/opensearch-project/OpenSearch/pull/17978)
- [15016](https://github.com/opensearch-project/OpenSearch/pull/15016)
- [15289](https://github.com/opensearch-project/OpenSearch/pull/15289)
- [17329](https://github.com/opensearch-project/OpenSearch/pull/17329)
- [13172](https://github.com/opensearch-project/OpenSearch/pull/13172)
- [15363](https://github.com/opensearch-project/OpenSearch/pull/15363)
- [16843](https://github.com/opensearch-project/OpenSearch/pull/16843)
- [17752](https://github.com/opensearch-project/OpenSearch/pull/17752)
- [17759](https://github.com/opensearch-project/OpenSearch/pull/17759)
- [18082](https://github.com/opensearch-project/OpenSearch/pull/18082)
- [18085](https://github.com/opensearch-project/OpenSearch/pull/18085)
- [18090](https://github.com/opensearch-project/OpenSearch/pull/18090)
- [18102](https://github.com/opensearch-project/OpenSearch/pull/18102)
- [18103](https://github.com/opensearch-project/OpenSearch/pull/18103)
- [18161](https://github.com/opensearch-project/OpenSearch/pull/18161)
- [18249](https://github.com/opensearch-project/OpenSearch/pull/18249)
- [18277](https://github.com/opensearch-project/OpenSearch/pull/18277)
- [18280](https://github.com/opensearch-project/OpenSearch/pull/18280)
- [18290](https://github.com/opensearch-project/OpenSearch/pull/18290)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by kkewwei**
### Description
Previously the default value was false, it had nothing to do with aggregation. Now default value is auto in case mode setting is not set, it is also decided by aggregationSupportsConcurrent, We should take aggregationSupportsConcurrent into account.

### Related Issues
Resolves #18238

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/search/SearchServiceTests.java [hunk 1]
```diff
@@ -1498,11 +1498,12 @@ public void testConcurrentSegmentSearchWithRandomizedModeSettings() throws IOExc
...
         String indexMode = randomFrom(modeSettings);
 
-        // default to false in case mode setting is not set
-        boolean concurrentSearchEnabled = false;
-
         boolean aggregationSupportsConcurrent = randomBoolean();
 
+        // Default to auto in case mode setting is not set, we use true to represent,
+        // It is also decided by aggregationSupportsConcurrent.
+        boolean concurrentSearchEnabled = true && aggregationSupportsConcurrent;
```
Comment (jed326) [inline server/src/test/java/org/opensearch/search/SearchServiceTests.java:1505]: This is a small nitpick, but just to be clear when `auto` mode is used, concurrent search is used if aggregations are present (and based on whatever plugin implementations for [`ConcurrentSearchRequestDecider`](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchRequestDecider.java#L29) are present).

See: https://github.com/opensearch-project/OpenSearch/blob/ca3b005021aa0525a8250dcab8b6bd6e2002bed1/server/src/main/java/org/opensearch/search/DefaultSearchContext.java#L976-L984

On the other hand, `aggregationSupportsConcurrent` is evaluated based on the *types* of aggregations that are present in the query. With that in mind, I've made some suggestions on the code comment for clarity:

```suggestion
        // Default concurrent search mode is auto, which enables concurrent segment search when aggregations are present. 
        // aggregationSupportsConcurrent determines if the present aggregation type supports concurrent segment search.
        boolean concurrentSearchEnabled = aggregationSupportsConcurrent;
```

Separately, I think there's probably a missing test case here where we *do not* have aggregations in the query.

**Review by jed326 — COMMENTED** [review]
Thanks for raising this @kkewwei, really appreciate it. I left some minor suggestions with a more detailed explanation of how the concurrent search decision works.

**Comment by kkewwei** [comment]
@jed326  Test case without aggregation has been added, please review when you are free.
