### PR TITLE
CardinalityIT/NestedIT test failures with concurrent search enabled and AssertingCodec

### LINKED ISSUE #8095: [Concurrent Segment Search] CardinalityIT/NestedIT test failures with concurrent search and AssertingCodec enabled
**Describe the bug**
With concurrent search enabled below tests sometimes fails when `AssertingCodec` gets used as it verifies that the thread accessing the codecs remain same throughout the search execution. With concurrent mode, the `postCollection` on Aggregation  which happens in reduce phase can access the docValues. These access happens on the parent `search` thread and not on `index_searcher` thread causing the failure.

#### Test Failures:

```
Cardinality/Nested

 - org.opensearch.search.aggregations.metrics.CardinalityWithRequestBreakerIT.testRequestBreaker
 - org.opensearch.search.aggregations.metrics.CardinalityWithRequestBreakerIT.classMethod
`
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.aggregations.metrics.CardinalityWithRequestBreakerIT" -Dtests.seed=5A2A89155E5AADBB -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-US -Dtests.timezone=UTC -Druntime.java=20
`
- org.opensearch.search.aggregations.metrics.CardinalityIT.testMultiValuedString
`REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.aggregations.metrics.CardinalityIT.testMultiValuedString" -Dtests.seed=5A2A89155E5AADBB -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-PE -Dtests.timezone=Asia/Qyzylorda -Druntime.java=20`

- org.opensearch.search.aggregations.bucket.NestedIT.testNestedAsSubAggregation
`REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.aggregations.bucket.NestedIT.testNestedAsSubAggregation" -Dtests.seed=5A2A89155E5AADBB -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=mk-MK -Dtests.timezone=Europe/Minsk -Druntime.java=20`
```

#### Sample Stack Trace:

```
2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.aggregations.metrics.CardinalityWithRequestBreakerIT" -Dtests.seed=5A2A89155E5AADBB -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-US -Dtests.timezone=UTC -Druntime.java=20
  2> com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=79, name=opensearch[node_s1][search][T#4], state=RUNNABLE, group=TGRP-CardinalityWithRequestBreakerIT]

        Caused by:
        java.lang.AssertionError: Sorted doc values are only supposed to be consumed in the thread in which they have been acquired. But was acquired in Thread[#86,opensearch[node_s1][index_searcher][T#4],5,TGRP-CardinalityWithRequestBreakerIT] and consumed in Thread[#79,opensearch[node_s1][search][T#4],5,TGRP-CardinalityWithRequestBreakerIT].
            at __randomizedtesting.SeedInfo.seed([5A2A89155E5AADBB]:0)
            at org.apache.lucene.tests.index.AssertingLeafReader.assertThread(AssertingLeafReader.java:67)
            at org.apache.lucene.tests.index.AssertingLeafReader$AssertingSortedDocValues.lookupOrd(AssertingLeafReader.java:908)
            at org.apache.lucene.index.SingletonSortedSetDocValues.lookupOrd(SingletonSortedSetDocValues.java:95)
            at org.opensearch.search.aggregations.metrics.CardinalityAggregator$OrdinalsCollector.postCollect(CardinalityAggregator.java:338)
            at org.opensearch.search.aggregations.metrics.CardinalityAggregator.postCollectLastCollector(CardinalityAggregator.java:155)
            at org.opensearch.search.aggregations.metrics.CardinalityAggregator.doPostCollection(CardinalityAggregator.java:165)
            at org.opensearch.search.aggregations.AggregatorBase.postCollection(AggregatorBase.java:278)
            at org.opensearch.search.aggregations.AggregatorBase.postCollection(AggregatorBase.java:279)
            at org.opensearch.search.aggregations.AggregationCollectorManager.reduce(AggregationCollectorManager.java:80)
            at org.opensearch.search.aggregations.NonGlobalAggCollectorManager.reduce(NonGlobalAggCollectorManager.java:22)
            at org.opensearch.search.aggregations.AggregationCollectorManager.reduce(AggregationCollectorManager.java:31)
            at org.apache.lucene.search.MultiCollectorManager.reduce(MultiCollectorManager.java:73)
            at org.opensearch.search.query.QueryCollectorManagerContext$QueryCollectorManager.reduce(QueryCollectorManagerContext.java:41)
            at org.opensearch.search.query.QueryCollectorManagerContext$QueryCollectorManager.reduce(QueryCollectorManagerContext.java:27)
            at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:733)
            at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:688)
            at org.opensearch.search.query.ConcurrentQueryPhaseSearcher.searchWithCollectorManager(ConcurrentQueryPhaseSearcher.java:81)
            at org.opensearch.search.query.ConcurrentQueryPhaseSearcher.searchWithCollector(ConcurrentQueryPhaseSearcher.java:51)
            at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWith(QueryPhase.java:423)
            at org.opensearch.search.query.QueryPhaseSearcherWrapper.searchWith(QueryPhaseSearcherWrapper.java:62)
            at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:278)
            at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:151)
            at org.opensearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:681)
            at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73)
            at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88)
            at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
            at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
            at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
            at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
            at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
            at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
```

**To Reproduce**
1. Enable Concurrent Search Feature Flag in `OpenSearchIntegTestCase` and override the `slices` method in `ContextIndexSearcher` to compute slices with docCount and segmentCount as 1 to force multiple slices.
2. Also use the system property `-Dtests.codec=Asserting` to use the `AssetingCodec` during execution

**Expected behavior**
Ideally, in the concurrent model even though the access is happening across multiple threads (index_searcher and search threadpool) these accesses will happen one after another and not concurrently. But the way `AssertingCodec` validates is based on which thread created the codec (that means during leafCollector creation) and if any access (sequentially or concurrently) happens by other thread it fails. Ref for [AssertingCodec](https://github.com/apache/lucene/blob/main/lucene/test-framework/src/java/org/apache/lucene/tests/codecs/asserting/AssertingCodec.java#L36)

**Plugins**
N/A

**Screenshots**
N/A

### PR DESCRIPTION
**Pull request by sohami**
### Description
The tests were failing because during the concurrent segment search for each slice the codec producers for the leafs were initialized by the slice thread. Later in reduce phase, the post collection happens over those codec producers on the search thread. With AssertingCodec it verifies that all access is done by the same thread causing the failures. More details are in #8095 

### Related Issues
Resolves #8095

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sohami** [comment]
@reta Can you please help to review ?

File: server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java [hunk 1]
```diff
@@ -295,6 +301,38 @@ protected void search(List<LeafReaderContext> leaves, Weight weight, Collector c
...
+     * different threads for different segments (or slices). Whereas the postProcess happens as part of reduce phase and is performed on
+     * the separate thread which is from search threadpool and not from slice threadpool. So two different threads performs the access on
+     * the DocValues causing the AssertingCodec to fail. From functionality perspective, there is no issue as DocValues for each segment
+     * is always accessed by a single thread at a time but those threads may be different (e.g. slice thread during collection and then
+     * search thread during reduce)
+     * @param collector input collector tree used for search
+     */
+    private void postCollection(Collector collector) throws IOException {
+        final Queue<Collector> collectors = new LinkedList<>();
+        collectors.offer(collector);
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:321]: @sohami this is super fragile, I think we should model it using something like: 
```
public interface FinalizingCollector {
    void postCollection() throws IOException;
}
```

The `BucketCollector` naturally implements that but for InternalProfileCollector / MultiCollector / MinimumScoreCollector / ... others we should implement that by checking the wrapping collector(s).

Comment (sohami) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:321]: @reta thanks for sharing the link. I was also planning to create a separate issue in lucene to provide some `postCollect` option in `Collector` interface itself. Considering that will take time to implement and merge this was a workaround meanwhile. But thanks for sharing the link seems like it is getting addressed already, however until that get release we still need other mechanism.

I had thought about The `FinalizingCollector` interface mechanism but that is same as providing the capability in `Collector` interface itself. This mechanism will mean for collectors like `MultiCollector` and others we need to create a wrapper in OpenSearch and use that wrapper everywhere to make it work. Also I was not sure if that `MultiCollectorWrapper` will also get wrapped inside the vanilla `MultiCollector` by lucene in some code path then this interface mechanism will not work. In current mechanism, for `MultiCollector` handling we are unwrapping it recursively until a concrete `Collector` is found, so that issue will not be there. Given the lucene is changing the interface to add the method in `LeafCollector`, I think we can keep this current implementation as a stop gap solution with a follow up issue to move to lucene `postCollect` mechanism once that is merged in. Let me know wdyt ?

Comment (reta) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:321]: Oh right, I though `MultiCollector` is ours, but it is from Apache Lucene indeed :( However, we could (and probably should move this out of `ContextIndexSearcher`:
 - this is very relevant to aggregations only and not the regular search flow
 - we already have mostly identical code in AggregationCollectorManager::reduce

What about we introduce the `SearchContext::postProcessor()`  (similarly to what we did with `ReduceContext` and the postrocessor will only be set during the aggregation flows (and also implemented within aggregation framework), otherwise - NO_OP

Comment (sohami) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:321]: We want this `postCollection` to be done by individual slice threads for the collector instance it is using and thats why it is kept here as each slice related search operation is performed here. This way we don't need to worry about the thread safety as each slice thread will work on its own collector instance.

> this is very relevant to aggregations only and not the regular search flow

We can add a check like `searchContext::aggregations() != null` here before invoking this method.  This will take care of not performing it when aggregations are not present.

> we already have mostly identical code in AggregationCollectorManager::reduce

There is difference between unwrapping of collectors here and in `AggregationCollectorManager::reduce`. In later, the `CollectorManager` expects the input collectors to be the one created by the manager and not the other collectors in the tree. But that is not the case here.

Comment (reta) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:321]: > This way we don't need to worry about the thread safety as each slice thread will work on its own collector instance.

Fair enough, let's go with `SearchContext::newPostProcessor()` (or alike) to eliminate any ambiguity here. I really feel uneasy about this code in `ContextIndexSearcher` there is very far from were it should be (aggregations).

Comment (sohami) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:321]: Do you mean the check for `searchContext::aggregations() != null` right ? Or something else here. I am trying to avoid too much changes here as this is temporary and we want to remove this once the lucene changes are merged in.

Comment (reta) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:321]: > searchContext::aggregations() != null

No, the `ContextIndexSearcher` should be free of this knowledge, I mean to replace

```
postCollection(collector)
```

with (pseudo code):

```
searchContext.newPostProcessor().postProcess(collector);
```

The `searchContext` will be configured with post processors only within aggregation processor(s)

Comment (sohami) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:321]: > No, the ContextIndexSearcher should be free of this knowledge,

May be I am missing something but I don't think that is the case with `ContextIndexSearcher`, it already takes action based on the request context today. It has access to `SearchContext` and we do optimizations like for [sort](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L510) and [dfs-phase](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L199) in this class. So I don't see why we cannot perform this operation for `aggregation` here. Today, the `postCollect` is implemented by `Aggregations` only but if we had it in generic collector interface then it should be called for each of the collectors and that is what now lucene is moving towards. The processing here is done on `Collector` and by different slice threads and IMO `SearchContext` is not meant to provide any capability to perform the operations across threads and is used for keeping track of request level attributes.

Comment (reta) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:321]: > t has access to `SearchContext` and we do optimizations like for [sort](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L510) and [dfs-phase](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L199) in this class.

I am suggesting to use `searchContext` for that (see please previous comment). I would argue that index searcher should know  nothing:
  a)  about aggregation 
  b)  about different types of collectors

The fact it has some more knowledge now is not a reason to do the same

>  if we had it in generic collector interface then it should be called for each of the collectors and that is what now lucene is moving towards. 

The issue I posted to you - please feel free to contribute (either by commenting or submitting the pull request), it may take a long time otherwise (I have no insight)

> The processing here is done on Collector and by different slice threads and IMO SearchContext is not meant to provide any capability to perform the operations across threads

I 100% agree with you here, where you see the mentioning of threads or across threads or anything related to threads in the suggestion to move the implementation off the `ContextIndexSearcher`? Is it very easy to copy / replicate same code in different places but it is very difficult to support that. As I mentioned several times, we sadly have to make some adjustments in the post processing phase - but this code should live in aggregations related implementation. If you see any other ways to achieve that - please share.

Comment (sohami) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java]: @reta Sorry for the delay, have made the changes to create a new processor to keep the logic for collector processing and which gets initialized in Aggregation flow in `SearchContext`.

**Comment by sohami** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:**  ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/19968/
> * **CommitID:** [f493a09](https://github.com/opensearch-project/OpenSearch/commit/f493a093de308fa1956f4f99de53f59c1a9d596e)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Failed tests are unrelated:

```
[org.opensearch.remotestore.RemoteStoreIT.testStaleCommitDeletionWithInvokeFlush](https://build.ci.opensearch.org/job/gradle-check/19968/testReport/junit/org.opensearch.remotestore/RemoteStoreIT/testStaleCommitDeletionWithInvokeFlush/)
[org.opensearch.remotestore.RemoteStoreRefreshListenerIT.testRemoteRefreshRetryOnFailure](https://build.ci.opensearch.org/job/gradle-check/19968/testReport/junit/org.opensearch.remotestore/RemoteStoreRefreshListenerIT/testRemoteRefreshRetryOnFailure/)
[org.opensearch.remotestore.multipart.RemoteStoreMultipartIT.testStaleCommitDeletionWithInvokeFlush](https://build.ci.opensearch.org/job/gradle-check/19968/testReport/junit/org.opensearch.remotestore.multipart/RemoteStoreMultipartIT/testStaleCommitDeletionWithInvokeFlush/)
```

File: server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+import java.util.Queue;
+
+/**
+ * Processor to perform collector level processing specific to {@link BucketCollector} in different stages like: a) PostCollection
+ * after search on each leaf is completed and b) process the collectors to perform reduce after collection is completed
+ */
+public class BucketCollectorProcessor {
+
+    /**
+     * Performs {@link BucketCollector#postCollection()} on all the {@link BucketCollector} in the given {@link Collector} collector tree
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java:33]: Thanks for the comment

File: server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+
+    /**
+     * Unwraps the input collection of {@link Collector} to get the list of the {@link Aggregator} used by different slice threads. The
+     * input is expected to contain the collectors related to Aggregations only as that is passed to {@link AggregationCollectorManager}
+     * during the reduce phase. This list of {@link Aggregator} is used to create {@link InternalAggregation} and optionally perform
+     * reduce at shard level before returning response to coordinator
+     * @param collectors collection of aggregation collectors to reduce
+     * @return list of unwrapped {@link Aggregator}
+     */
+    public List<Aggregator> processOnReduce(Collection<Collector> collectors) {
```
[the remark this answers is not in the document]
Comment (sohami) [reply server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java]: Changed to `toAggregators`

**Comment by reta** [comment]
@sohami could you please add changelog (may be using different phrasing), it seems we are changing not the tests but core functionality.

**Comment by sohami** [comment]
> @sohami could you please add changelog (may be using different phrasing), it seems we are changing not the tests but core functionality.

Added the changelog entry

**Review by reta — APPROVED** [review]

**Comment by sohami** [comment]
@reta Can this be merged ?

**Comment by reta** [comment]
> @reta Can this be merged ?

@sohami  Green build? Please rebase may be

**Comment by sohami** [comment]
> > @reta Can this be merged ?
> 
> @sohami Green build? Please rebase may be

I did rebase yesterday as part of final commit and gradle seems to be failing for bwc2.9 jar. Let me rebase again to see if that fixes below issue.

```
* What went wrong:
Execution failed for task ':distribution:bwc:minor:buildBwcLinuxTar'.
> Building 2.9.0 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/minor/build/bwc/checkout-2.x/distribution/archives/linux-tar/build/distributions/opensearch-min-2.9.0-SNAPSHOT-linux-x64.tar.gz
```

**Comment by reta** [comment]
Hehe @sohami please backport manually to `2.x`, thank you

**Comment by sohami** [comment]
> Hehe @sohami please backport manually to `2.x`, thank you

@reta Created backport pr https://github.com/opensearch-project/OpenSearch/pull/8687. Thanks!
