### PR TITLE
Fix ReadContextListenerTests to avoid inconsistent WindowsFS file han…

### LINKED ISSUE #9776: [BUG] org.opensearch.common.blobstore.stream.read.listener.ReadContextListenerTests.testReadContextListenerFailure is flaky
**Describe the bug**
org.opensearch.common.blobstore.stream.read.listener.ReadContextListenerTests.testReadContextListenerFailure is flaky.

https://build.ci.opensearch.org/job/gradle-check/24473/testReport/junit/org.opensearch.common.blobstore.stream.read.listener/ReadContextListenerTests/testReadContextListenerFailure/

**To Reproduce**

REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.common.blobstore.stream.read.listener.ReadContextListenerTests.testReadContextListenerFailure" -Dtests.seed=5673BC5FFAEF5B76 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-YE -Dtests.timezone=America/Indiana/Knox -Druntime.java=17

**Expected behavior**
Test should always pass.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by kotwanikunal**
…dle simulation

### Description
- Fixes `ReadContextListenerTests` to avoid inconsistent WindowsFS file handle simulation

### Related Issues
Resolves #9776 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java [hunk 1]
```diff
@@ -32,6 +33,7 @@
 
 import static org.opensearch.common.blobstore.stream.read.listener.ListenerTestUtils.CountingCompletionListener;
 
+@SuppressFileSystems("WindowsFS")
```
Comment (andrross) [inline server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java:36]: Might be worth a comment here explaining why it is suppressed

**Comment by kotwanikunal** [comment]
#9891 

> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/25061/
> * **CommitID:** [e781bd6](https://github.com/opensearch-project/OpenSearch/commit/e781bd61bfdcbae282824f37751e251b9ce146ec)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

**Review by andrross — APPROVED** [review]

**Comment by andrross** [comment]
Another failure from #9731

**Comment by kotwanikunal** [comment]
> * https://build.ci.opensearch.org/job/gradle-check/25152/

#9787

**Comment by kotwanikunal** [comment]
#9787 

> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/25155/
> * **CommitID:** [e781bd6](https://github.com/opensearch-project/OpenSearch/commit/e781bd61bfdcbae282824f37751e251b9ce146ec)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

**Comment by kotwanikunal** [comment]
#8329 

> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/25183/
> * **CommitID:** [e872e4f](https://github.com/opensearch-project/OpenSearch/commit/e872e4f29686ff36443e0fda01fc47e3d8e27de5)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

**Comment by kotwanikunal** [comment]
#9116
