### PR TITLE
Fix  #7972 SearchBackpressureIT flaky tests

### LINKED ISSUE #7972: [BUG] org.opensearch.search.backpressure.SearchBackpressureIT.testSearchShardTaskCancellationWithHighCpu is flaky
**Describe the bug**

`org.opensearch.search.backpressure.SearchBackpressureIT.testSearchShardTaskCancellationWithHighCpu` is flaky

https://build.ci.opensearch.org/job/gradle-check/17145/

https://github.com/opensearch-project/OpenSearch/pull/7969#issuecomment-1582958510

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.backpressure.SearchBackpressureIT.testSearchShardTaskCancellationWithHighCpu" -Dtests.seed=8B21150333870C73 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=tr -Dtests.timezone=Africa/Kinshasa -Druntime.java=20

org.opensearch.search.backpressure.SearchBackpressureIT > testSearchShardTaskCancellationWithHighCpu FAILED
    java.lang.AssertionError: 
    Expected: a string containing "cpu usage exceeded"
         but: was null
        at __randomizedtesting.SeedInfo.seed([8B21150333870C73:BBB02F2B23057755]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.opensearch.search.backpressure.SearchBackpressureIT.testSearchShardTaskCancellationWithHighCpu(SearchBackpressureIT.java:196)
```

### PR DESCRIPTION
**Pull request by scrawfor99**
### Description
This PR is attempt number 2 at remediating the flaky tests in `**/SearchBackpressureIT`. The two tests focusing on high CPU usage were prone to failure do to thread concurrency issues where the assignment of the CancellableTask values were not synchronized across the nodes. 

To resolve the issue, I added in a small static class as suggested by @ketanv3 and used an atomic reference through the SetOnce class. This allows for atomic assignments of the class variables without requiring a synchronized block around the `cancel(reason)` method. 

After the change, I ran a runner for 10 times with no failures so it appears to be fixed. 

One note about this test setup: I am not sure we want tests in this vain. The way the tests are made, we end up with non-deterministic behavior. For instance, we set the HIGH_CPU tests to be 1000 iterations, but that is just an arbitrary choice for a iteration count. On a more or less powerful processor this could have different results. This is especially true with different architectures that could have stack unwinding or other features. 

### Related Issues
Resolves #7972

### Check List
- [ ] ~New functionality includes testing.~
  - [ ] ~All tests pass~
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by owaiskazi19** [comment]
@scrawfor99 can you rebase your branch with latest `main` and push again?

**Comment by scrawfor99** [comment]
> @scrawfor99 can you rebase your branch with latest `main` and push again?

Will do!

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 1]
```diff
@@ -47,17 +48,17 @@
...
     /**
      * The time this task was cancelled as a wall clock time since epoch ({@link System#currentTimeMillis()} style).
      */
-    private Long cancellationStartTime = null;
+    private final SetOnce<Long> cancellationStartTime = new SetOnce<>();
     /**
      * The time this task was cancelled as a relative time ({@link System#nanoTime()} style).
      */
-    private Long cancellationStartTimeNanos = null;
+    private final SetOnce<Long> cancellationStartTimeNanos = new SetOnce<>();
```
Comment (ketanv3) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:61]: To clarify, I didn't suggest using SetOnce for all these properties.

Our goal is to make updates to these properties all at once (i.e. atomic). To achieve this, we need to wrap all these properties in a single object, and SetOnce that object atomically. Here's what it could look like:

```java
public abstract class CancellableTask extends Task {

    // ... truncated

    static class CancelledInfo {
        String reason;
        Long cancellationStartTime;
        Long cancellationStartTimeNanos;

        public CancelledInfo(String reason) {
            this.reason = reason;
            this.cancellationStartTime = System.currentTimeMillis();
            this.cancellationStartTimeNanos = System.nanoTime();
        }
    }

    private final SetOnce<CancelledInfo> cancelledInfo = new SetOnce<>();

    public void cancel(String reason) {
        assert reason != null;
        if (cancelledInfo.trySet(new CancelledInfo(reason))) {
            onCancelled();
        }
    }

    public boolean isCancelled() {
        return cancelledInfo.get() != null;
    }

    @Nullable
    public final String getReasonCancelled() {
        CancelledInfo info = cancelledInfo.get();
        return (info != null) ? info.reason : null;
    }
}
```

**Review by ketanv3 — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 2]
```diff
@@ -79,12 +80,12 @@ public CancellableTask(
...
         if (cancelled.compareAndSet(false, true)) {
-            this.cancellationStartTime = System.currentTimeMillis();
-            this.cancellationStartTimeNanos = System.nanoTime();
-            this.reason = reason;
+            this.cancellationStartTime.set(System.currentTimeMillis());
+            this.cancellationStartTimeNanos.set(System.nanoTime());
+            this.reason.set(reason);
             onCancelled();
         }
     }
```
[the remark this answers is not in the document]
Comment (scrawfor99) [reply server/src/main/java/org/opensearch/tasks/CancellableTask.java:91]: Hmmm, after the change, I was unable to replicate the issue so I interpreted that as having solved the issue. 

You had mentioned previously that you did not think using a synchronized block was the correct approach. Changing these all into an object with attributes seemed similar so I figured you meant to set each of the values using the atomic reference.

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java (hunk 1 above)
Comment (scrawfor99) [reply server/src/main/java/org/opensearch/tasks/CancellableTask.java:61]: My apologies. 

I see I misunderstood your previous suggestion. Since I could not replicate the issue in a reasonable number of test trials I figured the issue had been resolved.

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 3]
```diff
@@ -47,17 +48,20 @@
  */
 public abstract class CancellableTask extends Task {
 
-    private volatile String reason;
-    private final AtomicBoolean cancelled = new AtomicBoolean(false);
+    static class CancelledInfo {
```
Comment (ketanv3) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:51]: nitpick: May be make it `private`?

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 4]
```diff
@@ -47,17 +48,20 @@
...
+            this.cancellationStartTime = System.currentTimeMillis();
+            this.cancellationStartTimeNanos = System.nanoTime();
+        }
+    }
+
+    private final SetOnce<CancelledInfo> cancelledInfo = new SetOnce<>();
     private final TimeValue cancelAfterTimeInterval;
-    /**
-     * The time this task was cancelled as a wall clock time since epoch ({@link System#currentTimeMillis()} style).
-     */
```
Comment (ketanv3) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:55]: Please retain these Java docs after refactoring.

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 5]
```diff
@@ -98,22 +103,18 @@ public boolean cancelOnParentLeaving() {
     }
 
     public Long getCancellationStartTime() {
-        return cancellationStartTime;
+        return Objects.requireNonNull(cancelledInfo.get()).cancellationStartTime;
```
Comment (ketanv3) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:106]: Previously, this method returned `null` when the cancellation hasn't happened. But now it'll throw a NullPointerException. Can we preserve the original behaviour?

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 6]
```diff
@@ -98,22 +103,18 @@ public boolean cancelOnParentLeaving() {
...
     }
 
     public Long getCancellationStartTimeNanos() {
-        return cancellationStartTimeNanos;
+        return Objects.requireNonNull(cancelledInfo.get()).cancellationStartTimeNanos;
```
Comment (ketanv3) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:110]: Same as above.

**Review by ketanv3 — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (ketanv3) [reply server/src/main/java/org/opensearch/tasks/CancellableTask.java]: Here's a trick you can use to replicate this issue – We understand that this race-condition is triggered when we access the `reason` string after `cancelled` is set to true, but `reason` string hasn't been updated. We can force this scenario by inducing a delay between these two operations.

Here's how you can do:
```java
    public void cancel(String reason) {
        assert reason != null;
        if (cancelled.compareAndSet(false, true)) {
            
            try {
                Thread.sleep(1000);  // <-- add enough delay to make the test fail
            } catch (InterruptedException ignored) {}
            
            this.cancellationStartTime = System.currentTimeMillis();
            this.cancellationStartTimeNanos = System.nanoTime();
            this.reason = reason;
            onCancelled();
        }
    }
```

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java (hunk 1 above)
Comment (ketanv3) [reply server/src/main/java/org/opensearch/tasks/CancellableTask.java]: Please check my comment above to reliably reproduce this issue.

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java (hunk 3 above)
Comment (scrawfor99) [reply server/src/main/java/org/opensearch/tasks/CancellableTask.java:51]: Yeah no problem!

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java (hunk 4 above)
Comment (scrawfor99) [reply server/src/main/java/org/opensearch/tasks/CancellableTask.java:55]: Oh okay, will do.

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java (hunk 5 above)
Comment (scrawfor99) [reply server/src/main/java/org/opensearch/tasks/CancellableTask.java:106]: Oh shoot good call. I will swap it back.

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java (hunk 6 above)
Comment (scrawfor99) [reply server/src/main/java/org/opensearch/tasks/CancellableTask.java:110]: Will do

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (scrawfor99) [reply server/src/main/java/org/opensearch/tasks/CancellableTask.java]: Oh, I did not realize this. Thank you for the tip! I will try it out.

**Comment by scrawfor99** [comment]
Hi @ketanv3, seems like swapping to the SetOnce is somehow leading to NPEs when other tests try to get the cancellation reason. I looked into this a bit but I am hesitant to wrap things with synchronized for performance reasons. What do you want to do going forward? We can either continue making changes to try to adjust for the backpressure tests or disable them for now until we find a better way to handle them. 

As I mentioned, the fact that the tests are non-deterministic makes them a bit more disposable in my mind. But I also acknowledge they are the best option currently implemented. What do you think?

**Comment by ketanv3** [comment]
Hey @scrawfor99, please share a link to the failed build where you saw NPE.

> As I mentioned, the fact that the tests are non-deterministic makes them a bit more disposable in my mind. But I also acknowledge they are the best option currently implemented. What do you think?

I don't feel the same way. This test caught a real (but latent) issue in the task cancellation framework. I don't think this is a flaky-test problem.

**Comment by ketanv3** [comment]
@scrawfor99 I believe [this](https://build.ci.opensearch.org/job/gradle-check/17681/testReport/junit/org.opensearch.search.query/QueryPhaseTests/testCancellationDuringPreprocess__p0_5_p1_org_opensearch_search_query_ConcurrentQueryPhaseSearcher_1d99ee1b_/) is the NPE you're talking about.

Truncated stacktrace:
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.opensearch.common.SetOnce.get()" because "this.cancelledInfo" is null
	at org.opensearch.tasks.CancellableTask.getReasonCancelled(CancellableTask.java:134)
        ...
```

So my first impression seeing this error was - how can `cancelledInfo` be `null` when we explicitly initialize it to a final variable? In the failing test you'll find that a mock `SearchShardTask` is being created ([here](https://github.com/ketanv3/OpenSearch/blob/068404ed1cef5e1d023816d57054aef98a7aa343/server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java#L1121)).
* Since this is a mock, the field `cancelledInfo` is never initialized.
* Moreover, the `getReasonCancelled` method is defined final ([here](https://github.com/ketanv3/OpenSearch/blob/8d7a544d0c4188bf2968408736014712434d67f3/server/src/main/java/org/opensearch/tasks/CancellableTask.java#L125)). Final methods cannot be mocked, so the real implementation is executed, causing NPEs.

The fix is pretty simple, just remove the `final` keyword from this method. :)

**Comment by ketanv3** [comment]
Changes look good overall. Thanks!

---

Minor correction in the PR description.

> One note about this test setup: I am not sure we want tests in this vain. The way the tests are made, we end up with non-deterministic behavior. For instance, we set the HIGH_CPU tests to be 1000 iterations, but that is just an arbitrary choice for a iteration count. On a more or less powerful processor this could have different results. This is especially true with different architectures that could have stack unwinding or other features.

This isn't true. We don't run 1000 iterations. We run a busy-wait loop until 1000 ms of CPU time is accrued. This will be true for any processor, be it slow or fast.

In fact, there was nothing wrong with these tests. They actually caught an unrelated latent bug in the task cancellation framework.

**Comment by scrawfor99** [comment]
Hi @ketanv3, thank you for the correction. 

Perhaps I misinterpreted the code. I was referring to this code in the `SearchBackpressureIT` 

```
  private void doWork(TestRequest<Task> request) throws InterruptedException {
            switch (request.getType()) {
                case HIGH_CPU:
                    long i = 0, j = 1, k = 1, iterations = 1000;
                    do {
                        j += i;
                        k *= j;
                        i++;
                    } while (i < iterations);
                    break;
```

My interpretation of this code is that you will execute the calculation until there is an exception thrown or until you reach the iteration count. It is likely that the execution of the calculations will result in a thrown exception within the iterations but it is not a guarantee. It is great that the test caught an issue, and there may not be a truly deterministic method of testing the cancellation, but this appears to rely on the assumption that all processors will take at least 1000 ms to execute the calculations. Presumably this will always be true, but it is still system reliant. Maybe there is something more going on that does change this behavior to truly deterministic, but I was simply pointing out that this test setup appears to be theoretically reliant on the task handling of the processor.

**Comment by scrawfor99** [comment]
@owaiskazi19, @reta think this should be all set now. Thank you :)

**Comment by ketanv3** [comment]
@scrawfor99 

> My interpretation of this code is that you will execute the calculation until there is an exception thrown or until you reach the iteration count.

You're partially correct. There are two things here – (1) A [busy-wait loop](https://github.com/opensearch-project/OpenSearch/blame/c268051f5ae369a822675cb5c68cd02885760359/server/src/internalClusterTest/java/org/opensearch/search/backpressure/SearchBackpressureIT.java#L401-L405) and (2) a [doWork method](https://github.com/opensearch-project/OpenSearch/blame/c268051f5ae369a822675cb5c68cd02885760359/server/src/internalClusterTest/java/org/opensearch/search/backpressure/SearchBackpressureIT.java#L418-L441) which is called by the busy-wait loop indefinitely until the exception is thrown or a timeout is reached.

> It is likely that the execution of the calculations will result in a thrown exception within the iterations but it is not a guarantee.

Yes, the doWork method which runs these 1000 iterations may take different time on different systems. But the busy-wait loop will execute it indefinitely, interleaving it with cancellation checks, to ensure that at least 1000 ms of CPU time is accrued irrespective of how long the individual doWork call took. This makes these tests perfectly deterministic. Hope this explains.

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 7]
```diff
@@ -98,32 +107,30 @@ public boolean cancelOnParentLeaving() {
...
         return cancelAfterTimeInterval;
     }
 
     /**
      * The reason the task was cancelled or null if it hasn't been cancelled.
      */
-    @Nullable
-    public final String getReasonCancelled() {
-        return reason;
+    public String getReasonCancelled() {
```
Comment (scrawfor99) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:131]:
```suggestion
    @Nullable
    public String getReasonCancelled() {
```

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 8]
```diff
@@ -98,32 +107,30 @@ public boolean cancelOnParentLeaving() {
     }
 
     public Long getCancellationStartTime() {
-        return cancellationStartTime;
+        CancelledInfo info = cancelledInfo.get();
+        return (info != null) ? info.cancellationStartTime : null;
     }
 
     public Long getCancellationStartTimeNanos() {
```
Comment (scrawfor99) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:114]:
```suggestion
    @Nullable
    public Long getCancellationStartTimeNanos() {
```

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 9]
```diff
@@ -98,32 +107,30 @@ public boolean cancelOnParentLeaving() {
     }
 
     public Long getCancellationStartTime() {
```
Comment (scrawfor99) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:109]:
```suggestion
    @Nullable
    public Long getCancellationStartTime() {
```

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 10]
```diff
@@ -97,23 +106,25 @@ public boolean cancelOnParentLeaving() {
...
 
+    @Nullable
+    @Nullable
     public Long getCancellationStartTime() {
-        return cancellationStartTime;
+        CancelledInfo info = cancelledInfo.get();
+        return (info != null) ? info.cancellationStartTime : null;
     }
 
+    @Nullable
```
Comment (scrawfor99) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:116]:
```suggestion
```

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 11]
```diff
@@ -97,23 +106,25 @@ public boolean cancelOnParentLeaving() {
         return true;
     }
 
+    @Nullable
```
Comment (scrawfor99) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:109]:
```suggestion
```

File: server/src/main/java/org/opensearch/tasks/CancellableTask.java [hunk 12]
```diff
@@ -32,11 +32,10 @@
 
 package org.opensearch.tasks;
 
-import org.opensearch.common.Nullable;
+import org.opensearch.common.SetOnce;
```
Comment (scrawfor99) [inline server/src/main/java/org/opensearch/tasks/CancellableTask.java:35]:
```suggestion
import org.opensearch.common.Nullable;
import org.opensearch.common.SetOnce;
```

**Comment by scrawfor99** [comment]
@dbwiddis, @reta, or @owaiskazi19 would any of you being able to merge this? Thank you.

File: .idea/vcs.xml [hunk 13]
```diff
@@ -1,20 +1,20 @@
...
-                    <option name="linkRegexp" value="https://github.com/opensearch-project/OpenSearch/pulls/$1" />
-                </IssueNavigationLink>
-                <IssueNavigationLink>
-                    <option name="issueRegexp" value="#(\d+)" />
-                    <option name="linkRegexp" value="https://github.com/opensearch-project/OpenSearch/issues/$1" />
-                </IssueNavigationLink>
-            </list>
-        </option>
-    </component>
+  <component name="IssueNavigationConfiguration">
```
Comment (owaiskazi19) [inline .idea/vcs.xml:3]: Why are we pushing this file @scrawfor99?

Comment (scrawfor99) [reply .idea/vcs.xml]: Sorry looks like a bad style change. I reverted it.

Comment (owaiskazi19) [reply .idea/vcs.xml]: Can you remove the change of this file completely? Let's not push it at all

Comment (scrawfor99) [reply .idea/vcs.xml]: Yeah that is what I did.

**Comment by owaiskazi19** [comment]
@scrawfor99 do you think we can document the test setup you tried for reproducing flaky tests like somewhere? I don't know the right place probably in [TESTING.md](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md). Let's see if folks agree to it.

**Comment by scrawfor99** [comment]
Hi @owaiskazi19, I can definitely add something but to be honest it was not very scientific... I use IntelliJ so I just ran the tests a handful of times with the IDE testing framework. @ketanv3 had provided quite a bit of insight here as someone who understands the use case and components around these tests much better than I do.

**Review by owaiskazi19 — APPROVED** [review]

**Comment by scrawfor99** [comment]
@dbwiddis @reta, think we could get this merged? -- I cannot merge things myself.

**Review by reta — APPROVED** [review]
