### PR TITLE
Do not fail replica shard due to primary closure

### LINKED ISSUE #803: [BUG] Data corruption on an actively written primary shard can lead to failing all replicas.
**Describe the bug**
When data corruption is detected on primary, [the engine fails](https://github.com/opensearch-project/OpenSearch/blob/e7d6dcd86765c49fd6a1c43911a90a1c9dd362df/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L1889). This in turn results in [failing primary shard](https://github.com/opensearch-project/OpenSearch/blob/e7d6dcd86765c49fd6a1c43911a90a1c9dd362df/server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java#L765) and [closing it](https://github.com/opensearch-project/OpenSearch/blob/e7d6dcd86765c49fd6a1c43911a90a1c9dd362df/server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java#L729). Closing the shard also causes [closing](https://github.com/opensearch-project/OpenSearch/blob/e7d6dcd86765c49fd6a1c43911a90a1c9dd362df/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L1383) and [cancelling any ongoing replication operations](https://github.com/opensearch-project/OpenSearch/blob/e7d6dcd86765c49fd6a1c43911a90a1c9dd362df/server/src/main/java/org/opensearch/action/support/replication/PendingReplicationActions.java#L111) on primary. One [such operation](https://github.com/opensearch-project/OpenSearch/blob/e7d6dcd86765c49fd6a1c43911a90a1c9dd362df/server/src/main/java/org/opensearch/action/support/replication/ReplicationOperation.java#L252) is shard bulk action on replica. Cancelling this operation in turn [checks the reason for failure](https://github.com/opensearch-project/OpenSearch/blob/e7d6dcd86765c49fd6a1c43911a90a1c9dd362df/server/src/main/java/org/opensearch/action/support/replication/ReplicationOperation.java#L230) and because the reason is shard unavailability, the primary marks the replica as stale.

Both [failing the primary](https://github.com/opensearch-project/OpenSearch/blob/e7d6dcd86765c49fd6a1c43911a90a1c9dd362df/server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java#L744) and [failing the replica](https://github.com/opensearch-project/OpenSearch/blob/e7d6dcd86765c49fd6a1c43911a90a1c9dd362df/server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java#L449) are sent as shard failure actions on master, which in turn serializes them locally only after they are queued on state update task queue. 

As a result, a corruption on primary shard can result in corruption of replica shards in certain cases, especially on high throughput writes. 

**To Reproduce**
Please check [this commit](https://github.com/itiyamas/OpenSearch-1/commit/1267b4360185f99b07d6672753656f8fc1d00117) for the test. You may need to run it 2-3 times to reproduce the behavior.

**Expected behavior**
Corruption on primary should not result in replica being lost and cluster turning red. Instead, replica should have taken over as primary and then a new replica should have been assigned- turning the cluster green after some time.

### PR DESCRIPTION
**Pull request by andrross**
### Description
This commit prevents a replica shard from being failed in the case that
a replication action to a replica is canceled due to the primary shard
being closed.
 
### Issues Resolved
closes #803 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java [hunk 1]
```diff
@@ -149,8 +152,86 @@ protected Collection<Class<? extends Plugin>> nodePlugins() {
     }
 
     /**
-     * Tests that we can actually recover from a corruption on the primary given that we have replica shards around.
+     * Tests that we cannot recover from a corruption on the primary that is actively indexing, even if it has replica.
      */
+    public void testCorruptFileDuringIndexing() throws Exception {
```
Comment (itiyama) [inline server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java:157]: One of the ways of reproducing this:
1. Create a node with overridden send behavior for TransportWriteAction through `MockTransportService`. You could add random delays or repro precisely via a latch.
2. Create an index with a primary and replica. Ensure replica gets initialized on node that executes delays.
3. Issue indexing operations and corrupt primary shard as done in the current test.
4. Release the latch in step 1.
5. Ensure that cluster health is green.


How to create a node with an overridden action:

**Review by itiyama — CHANGES_REQUESTED** [review]
The source changes look good. I have left a recommendation for determinstic repro.

File: server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java (hunk 1 above)
Comment (andrross) [reply server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java]: Apologies for the delay, but I haven't been able to get an integration test that both deterministically fails without the fix and passes with the fix. I've got the fix polished up with more targeted unit tests. Let me know what you think.

File: server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java [hunk 2]
```diff
@@ -514,15 +515,20 @@ public void failShardIfNeeded(
...
-                primaryTerm,
-                true,
-                message,
-                exception,
-                listener
-            );
+            // If a write action fails due to the closure of the primary shard
+            // then the replicas should not be marked as failed since they are
+            // still up-to-date with the (now closed) primary shard
+            if (exception instanceof PrimaryShardClosedException == false) {
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java:521]: For my understanding, I am guessing we would not successfully ack back request to the client and eventually the replica copy would get promoted to primary and the request subsequently retried on the newly promoted copy.
Can we add an integration test in ClusterDisruptionIT to verify this behaviour?

File: server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionTests.java [hunk 3]
```diff
@@ -395,6 +398,48 @@ public void testReplicaProxy() throws InterruptedException, ExecutionException {
         }
     }
 
+    public void testPrimaryClosedDoesNotFailShard() {
```
Comment (itiyama) [inline server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionTests.java:401]: Why not add a test in corruptionIT as well and ensure that the cluster is green after some time?

**Comment by andrross** [comment]
@itiyama @Bukhtawar I've added a test in CorruptedFileIT that deterministically fails without this fix and passes with it.

**Review by kotwanikunal — APPROVED** [review]

**Review by itiyama — APPROVED** [review]
