### PR TITLE
[Flaky Test] Fix Flaky Test ShuffleForcedMergePolicyTests.testDiagnostics

### LINKED ISSUE #17294: [AUTOCUT] Gradle Check Flaky Test Report for ShuffleForcedMergePolicyTests
## Flaky Test Report for `ShuffleForcedMergePolicyTests`

Noticed the `ShuffleForcedMergePolicyTests` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| c06f53e3a73c5fd6011fa6f7581d5a97c25c848a | [17160](https://github.com/opensearch-project/OpenSearch/pull/17160) | [53192](https://build.ci.opensearch.org/job/gradle-check/53192/testReport/) | `org.opensearch.lucene.index.ShuffleForcedMergePolicyTests.testDiagnostics` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `ShuffleForcedMergePolicyTests` class are:

- [14853](https://github.com/opensearch-project/OpenSearch/pull/14853)
- [16366](https://github.com/opensearch-project/OpenSearch/pull/16366)
- [17100](https://github.com/opensearch-project/OpenSearch/pull/17100)
- [17165](https://github.com/opensearch-project/OpenSearch/pull/17165)
- [17229](https://github.com/opensearch-project/OpenSearch/pull/17229)
- [17304](https://github.com/opensearch-project/OpenSearch/pull/17304)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by kkewwei**
### Description
There is a situation where all segments are triggered to  merged into one segment before forceMerging.  When forceMerge is called, there will be no segments to merge.

`reader.leaves()` contains the segments being merged.

It may be caused by upgrading to lucene10.

### Related Issues
Resolves #17294

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/lucene/index/ShuffleForcedMergePolicyTests.java [hunk 1]
```diff
@@ -59,13 +60,17 @@ public class ShuffleForcedMergePolicyTests extends BaseMergePolicyTestCase {
     public void testDiagnostics() throws IOException {
         try (Directory dir = newDirectory()) {
             IndexWriterConfig iwc = newIndexWriterConfig().setMaxFullFlushMergeWaitMillis(0);
-            MergePolicy mp = new ShuffleForcedMergePolicy(newTieredMergePolicy());
+            TieredMergePolicy tieredMergePolicy = newTieredMergePolicy();
```
Comment (reta) [inline server/src/test/java/org/opensearch/lucene/index/ShuffleForcedMergePolicyTests.java:63]: Thanks @kkewwei , I see the defaults for TieredMergePolicy per-tier / max-merge-at-once is `10`, may be we could just bump a number of docs?

```
int numDocs = 110 + random().nextInt(10);
```

**Comment by kkewwei** [comment]
> ❌ Gradle check result for [30137d5](https://github.com/opensearch-project/OpenSearch/commit/30137d5aa664705f0fb20217e4b6ff90ccb0236e): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/53681/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

MetadataCreateIndexServiceTests.testCreateIndexWithContextDisabled #17291

**Comment by cwperks** [comment]
@kkewwei I don't think your branch is synced completely with the latest commits on main. I see that https://github.com/kkewwei/OpenSearch/tree/fix_17294 is 4 commits behind. Can you sync and push?

**Comment by kkewwei** [comment]
@reta @cwperks please have a look when you are free.

**Comment by reta** [comment]
> @reta @cwperks please have a look when you are free.

Thanks a lot @kkewwei !
