### PR TITLE
Fix snapshotting searchable snapshot indexes

### LINKED ISSUE #7204: [BUG] Snapshotting a searchable snapshot index should only copy metadata
Related to #7179

Steps to reproduce:
- create and populate an index, e.g. `my-index`
- take a snapshot: 
```
PUT _snapshot/my-repo/my-snapshot
```
- delete `my-index`
- create a searchable snapshot index, e.g:
```
POST _snapshot/my-repo/my-snapshot
{
  "indices": "my-index",
  "rename_pattern": "(.+)",
  "rename_replacement": "remote_$1",
  "storage_type": "remote_snapshot"
}
```
- take a snapshot:
```
PUT _snapshot/my-repo/my-snapshot-2
```

Expected behavior:
The snapshot repo should look like:
```
<base path>/indices/<my-index id>/meta-uuid.dat
<base path>/indices/<my-index id>/<shard>/<data files...>
<base path>/indices/<remote-my-index id>/meta-uuid.dat
```

Actual behavior:
The snapshot repo looks like:
```
<base path>/indices/<my-index id>/meta-uuid.dat
<base path>/indices/<my-index id>/<shard>/<data files...>
<base path>/indices/<remote-my-index id>/meta-uuid.dat
<base path>/indices/<remote-my-index id>/<data files...>
```

The `<remote-my-index id>/meta-uuid.dat` contains the metadata for the searchable snapshot index that points to the data files in `my-index`. However, the system still redundantly copies the data files. This should be avoided. Upon restore, the right thing happens as `remote-my-index` is restored with pointers back to the `my-index` data files. The redundantly copied data files end up being unused in the repository.

### PR DESCRIPTION
**Pull request by andrross**
Two changes here: First, when snapshotting a searchable snapshot index (or snapshotting a full cluster that contains searchable snapshot indices) then we will snapshot the index metadata which includes the pointer to the original snapshot, but skip copying the data since it already exists in the source snapshot. Second, when restoring an index from a snapshot that is itself a searchable snapshot index, then it must be handled as such and restored as a searchable snapshot index.

Resolves #7204

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 1]
```diff
@@ -3559,6 +3559,13 @@ public boolean isRemoteTranslogEnabled() {
         return indexSettings() != null && indexSettings().isRemoteTranslogStoreEnabled();
     }
 
+    /**
+     * @return True if settings indicate this shard is backed by a remote snapshot, false otherwise.
+     */
+    public boolean isRemoteSnapshot() {
+        return indexSettings != null && indexSettings().isRemoteSnapshot();
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:3566]: Super minor, either `indexSettings()` or `indexSettings`, but probably not both:

```suggestion
        return indexSettings() != null && indexSettings().isRemoteSnapshot();
```

File: server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java [hunk 2]
```diff
@@ -275,42 +277,59 @@ private void startNewShards(SnapshotsInProgress.Entry entry, Map<ShardId, IndexS
...
-                                "snapshot [{}] completed to [{}] with [{}] at generation [{}]",
-                                snapshot,
-                                snapshot.getRepository(),
-                                lastSnapshotStatus,
-                                snapshotStatus.generation()
-                            );
+                if (isRemoteSnapshot(shardId)) {
+                    // If the source of the data is another remote snapshot (i.e. searchable snapshot)
+                    // then no need to snapshot the shard and can immediately notify success.
+                    notifySuccessfulSnapshotShard(snapshot, shardId, UUIDs.randomBase64UUID());
```
Comment (reta) [inline server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java:283]: Shouldn't we return the consistent generation here? `snapshotStatus.generation()` may be? or snapshot's id (it has uuid part)?

**Comment by Rishikesh1159** [comment]
@andrross looks like we need manual backport PR's for 2.x and 2.7
