### PR TITLE
[Segment Replication] Fix flaky tests testSegmentReplicationStatsResponse() and testSegmentReplicationStatsWithTimeout()

### LINKED ISSUE #6261: [BUG] Flaky test SegmentReplicationStatsIT.testSegmentReplicationStatsResponse
**Describe the bug**
The test `org.opensearch.indices.replication.SegmentReplicationStatsIT.testSegmentReplicationStatsResponse` introduced with #5718 is flaky -
```
Error Message
java.lang.AssertionError: 
Expected: <DONE>
     but: was <FINALIZE_REPLICATION>
Stacktrace
java.lang.AssertionError: 
Expected: <DONE>
     but: was <FINALIZE_REPLICATION>
	at __randomizedtesting.SeedInfo.seed([B2577B0DE18AD5BB:FB9EF53F6589927D]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.indices.replication.SegmentReplicationStatsIT.testSegmentReplicationStatsResponse(SegmentReplicationStatsIT.java:50)
```

**To Reproduce**
Check autocut issue - https://github.com/opensearch-project/OpenSearch/issues/6258

**Expected behavior**
Test should pass all the time

### PR DESCRIPTION
**Pull request by Rishikesh1159**
Signed-off-by: Rishikesh1159 <rishireddy1159@gmail.com>

### Description
This PR :
-> Fixes flaky tests testSegmentReplicationStatsWithTimeout() and testSegmentReplicationStatsResponse().
-> Makes timingdata map to a concurrent map to handle concurrent modifications.
-> Moves timing data under detailed flag

### Issues Resolved
Resolves #6261, #6255

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java [hunk 1]
```diff
@@ -51,6 +51,11 @@ protected Collection<Class<? extends Plugin>> nodePlugins() {
         return Collections.singletonList(MockTransportService.TestPlugin.class);
     }
 
+    @Override
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java:54]: I don't think we want to change the behavior of non SR tests, can you pls move the SR specific tests to a new class or move to SegmentReplicationStatsIT?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java [hunk 2]
```diff
@@ -47,7 +47,12 @@ public void testSegmentReplicationStatsResponse() throws Exception {
             .actionGet();
         // Verify API Response
         assertThat(response.shardSegmentReplicationStates().size(), equalTo(SHARD_COUNT));
-        assertThat(response.shardSegmentReplicationStates().get(INDEX_NAME).get(0).getStage(), equalTo(SegmentReplicationState.Stage.DONE));
+        assertBusy(
+            () -> assertThat(
+                response.shardSegmentReplicationStates().get(INDEX_NAME).get(0).getStage(),
+                equalTo(SegmentReplicationState.Stage.DONE)
+            )
+        );
```
Comment (dreamer-89) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java:55]: From https://github.com/opensearch-project/OpenSearch/issues/6259, the underlying cause of `testSegmentReplicationStatsWithTimeout` test failure is `org.apache.lucene.store.LockObtainFailedException` exception, on underlying store during round of segrep. I am not sure if waiting on state will resolve the error. 
The change should help fixing `testSegmentReplicationStatsResponse` though.

File: server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java [hunk 3]
```diff
@@ -152,7 +157,6 @@ public void testRecoveriesWithTimeout() {
         assertThat(recoveryResponse.getShardFailures()[0].reason(), containsString("ReceiveTimeoutTransportException"));
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/opensearch-project/OpenSearch/issues/6255")
```
Comment (dreamer-89) [inline server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java:155]: From https://github.com/opensearch-project/OpenSearch/issues/6259, the underlying cause of `testSegmentReplicationStatsWithTimeout` test failure is `org.apache.lucene.store.LockObtainFailedException` exception, on underlying store during round of segrep. Can you verify this test in loop and ensure it is not flaky ?

Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java:155]: The test from #6259  `testSegmentReplicationStatsWithTimeout` causing `org.apache.lucene.store.LockObtainFailedException` is fixed with addition of :
```
    @Override
    protected boolean addMockInternalEngine() {
        return false;
    }
```
Yes from changes made in this PR this issue is fixed. I ran this test in loop for 500 iterations and seen no failure happening

File: server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java [hunk 4]
```diff
@@ -76,9 +76,10 @@ public static Stage fromId(byte id) {
 
     private Stage stage;
     private ReplicationLuceneIndex index;
-
     private final ReplicationTimer overallTimer;
-    private final Map<String, Long> timingData;
+
+    // Timing data will have as many entries as stages, plus one
+    private final Map<String, Long> timingData = new ConcurrentHashMap<>(Stage.values().length + 1);
```
Comment (mch2) [inline server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java:82]: I think we still want to init this in constructors only and send this map over the wire, otherwise the map will empty on the other end when querying stats.  You can make the map concurrent in the ctor or copy it to write.

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java]: I am going with copying the map and sending copy of map in output stream.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java [hunk 5]
```diff
@@ -22,33 +22,43 @@
...
-        final String primaryNode = internalCluster().startNode();
-        createIndex(INDEX_NAME);
-        ensureYellowAndNoInitializingShards(INDEX_NAME);
-        final String replicaNode = internalCluster().startNode();
-        ensureGreen(INDEX_NAME);
-
-        // index 10 docs
-        for (int i = 0; i < 10; i++) {
-            client().prepareIndex(INDEX_NAME).setId(Integer.toString(i)).setSource("field", "value" + i).execute().actionGet();
+    public void testSegmentReplicationStatsResponse() {
```
Comment (dreamer-89) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java:30]: @Rishikesh1159 : I fixed this flaky test in https://github.com/opensearch-project/OpenSearch/pull/6370. Can you please rebase your changes against `main`?

Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java:29]: Sure let me rebase

Comment (dreamer-89) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java:29]: FYI, I see one run where this is still flaky https://github.com/opensearch-project/OpenSearch/pull/6366#issuecomment-1437664743. 
Previously, I root caused the problem happening due to race condition and fixed by asserting on replication state to be done which fixed it from 20% failing -> 0%. The assertBusy block by default waits for `10s` not sure if segment replication needs more time to complete. May be we can increase the assertBusy timeout to 60secs if this test is still flaky.

Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java:29]: Yes testSegmentReplicationStatsResponse() was flaky previously because of stage not reaching done within certain time. But now I have changed the test completely. As we are only testing API response and we are concerned only about API response but not about segment replication stage. So I changed the test and we no more assert on segrep stage which was causing flakiness.

Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java:29]: With changes in testSegmentReplicationStatsResponse() we only assert if we get a successful or failure response from API call. We are not concerned about if segment replication event has finished processing or not, as urpose of API is only to give response irrespective of state of segrep event.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java [hunk 6]
```diff
@@ -121,6 +131,10 @@ public void testSegmentReplicationStatsResponseForActiveAndCompletedOnly() throw
             completedOnlyResponse.shardSegmentReplicationStates().get(INDEX_NAME).get(0).getStage(),
             SegmentReplicationState.Stage.DONE
         );
+        assertThat(
```
Comment (dreamer-89) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java:134]: We can use `assertEquals` instead of `assertThat` here. This is applicable for other usages of `assertThat` as well

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java (hunk 5 above)
Comment (dreamer-89) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java:29]: I think there is still value in asserting the replication state as it can uncover bugs where replication never completes for various reasons and it is also part of API response. I will leave it for you to decide.

Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java]: Sure, I can add asserts on replication state. It doesn't break anything but as you said there is a chance it can uncover some bugs. I have added that in latest commit. Thanks @dreamer-89

File: server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java [hunk 7]
```diff
@@ -140,7 +140,7 @@ protected SegmentReplicationState shardOperation(SegmentReplicationStatsRequest
             singleIndexWithSegmentReplicationDisabled = shardRouting.getIndexName();
             return null;
         }
-        if (indexShard.indexSettings().isSegRepEnabled() == false) {
+        if (indexShard.indexSettings().isSegRepEnabled() == false || shardRouting.primary()) {
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java:143]: Why this change is needed ?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java [hunk 8]
```diff
@@ -19,34 +19,51 @@
...
+        ensureGreen();
+        final long numDocs = scaledRandomIntBetween(50, 100);
+        for (int i = 0; i < numDocs; i++) {
+            index(INDEX_NAME, "doc", Integer.toString(i));
         }
         refresh(INDEX_NAME);
-        waitForSearchableDocs(10L, asList(primaryNode, replicaNode));
+        ensureSearchable(INDEX_NAME);
 
         assertBusy(() -> {
```
Comment (dreamer-89) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java:51]: As I mentioned [here](https://github.com/opensearch-project/OpenSearch/pull/6268#discussion_r1112410862), seen one instance where this test failed. May be we can increase the assertBusy timeout and see if it helps.

File: server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java (hunk 7 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java:143]: If shard is primary we don't even need to make a call to get segment replication state, as segment replication only happens on replica shards. If we don't have this primary check here, it will make a call to get segment replication state and check some collections and eventually return null on a primary shard. So with this addition of condition check we are just returning null early if it is a primary sahrd

**Review by dreamer-89 — APPROVED** [review]

**Comment by Rishikesh1159** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** UNSTABLE ❕
> * **TEST FAILURES:**
> 
> ```
>       2 org.opensearch.cluster.service.MasterServiceTests.classMethod
>       1 org.opensearch.cluster.service.MasterServiceTests.testThrottlingForMultipleTaskTypes
> ```
> 
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/11531/
> * **CommitID:** [ba41b87](https://github.com/opensearch-project/OpenSearch/commit/ba41b8784429b0ba06784ef0c083f249bfb32842)
>   Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

Issue already opened for these flaky tests https://github.com/opensearch-project/OpenSearch/issues/5958
