### PR TITLE
Java high-level REST client bulk() is not respecting the bulkRequest.requireAlias(true) method call

### LINKED ISSUE #12958: [BUG] Java high-level REST client bulk() is not respecting the bulkRequest.requireAlias(true) method call
### Describe the bug

The Java high-level REST client `bulk(BulkRequest bulkRequest, RequestOptions options)` is not respecting the `bulkRequest.requireAlias(true)` method call. It automatically creates an index with the name of the alias which should not happen when the require alias flag is set.

### Related component

Clients

### To Reproduce

Following are 4 examples of how the require alias flag can be set and should be respected.

Fail 1: Auto creates the index `testindex-1`
```
private RestHighLevelClient osClient;

@Test  
public void t0010_bulkWithRequireAliasUsingGlobalIndex() {  
    String indexAliasName = "testindex-1";  
    try {  
        BulkRequest bulkRequest = new BulkRequest(indexAliasName);  
        bulkRequest.requireAlias(true);  
        bulkRequest.add(new IndexRequest().id("1").source("{ \"name\": \"Biden\" }", XContentType.JSON));  
        bulkRequest.add(new IndexRequest().id("2").source("{ \"name\": \"Trump\" }", XContentType.JSON));  
  
        BulkResponse bulkResponse = osClient.bulk(bulkRequest, RequestOptions.DEFAULT);  
  
        assertFalse(existsIndex(indexAliasName), "Should not auto-create the index.");  
        assertTrue(bulkResponse.hasFailures(), "Bulk response must have failures.");  
    } catch (Exception ex) {  
        Assert.fail("Must not throw an exception");  
    }  
}
```

Fail 2: Auto creates the index `testindex-2`
```
private RestHighLevelClient osClient;

@Test  
public void t0020_bulkWithRequireAliasUsingIndexOnEachRequest() {  
    String indexAliasName = "testindex-2";  
    try {  
        BulkRequest bulkRequest = new BulkRequest();  
        bulkRequest.requireAlias(true);  
        bulkRequest.add(new IndexRequest().index(indexAliasName).id("1").source("{ \"name\": \"Biden\" }", XContentType.JSON));  
        bulkRequest.add(new IndexRequest().index(indexAliasName).id("2").source("{ \"name\": \"Trump\" }", XContentType.JSON));  
  
        BulkResponse bulkResponse = osClient.bulk(bulkRequest, RequestOptions.DEFAULT);  
  
        assertFalse(existsIndex(indexAliasName), "Should not auto-create the index.");  
        assertTrue(bulkResponse.hasFailures(), "Bulk response must have failures.");  
    } catch (Exception ex) {  
        Assert.fail("Must not throw an exception");  
    }  
}
```

Fail 3: Auto creates the index `testindex-3`
```
private RestHighLevelClient osClient;

@Test  
public void t0030_bulkWithRequireAliasOnEachRequestUsingGlobalIndex() {  
    String indexAliasName = "testindex-3";  
    try {  
        BulkRequest bulkRequest = new BulkRequest(indexAliasName);  
        bulkRequest.add(new IndexRequest().id("1").setRequireAlias(true).source("{ \"name\": \"Biden\" }", XContentType.JSON));  
        bulkRequest.add(new IndexRequest().id("2").setRequireAlias(true).source("{ \"name\": \"Trump\" }", XContentType.JSON));  
  
        BulkResponse bulkResponse = osClient.bulk(bulkRequest, RequestOptions.DEFAULT);  
  
        assertFalse(existsIndex(indexAliasName), "Should not auto-create the index.");  
        assertTrue(bulkResponse.hasFailures(), "Bulk response must have failures.");  
    } catch (Exception ex) {  
        Assert.fail("Must not throw an exception");  
    }  
}
```

Fail 4: Auto creates the index `testindex-4`
```
private RestHighLevelClient osClient;

@Test  
public void t0040_bulkWithRequireAliasOnEachRequest() {  
    String indexAliasName = "testindex-4";  
    try {  
        BulkRequest bulkRequest = new BulkRequest();  
        bulkRequest.add(new IndexRequest().index(indexAliasName).id("1").setRequireAlias(true).source("{ \"name\": \"Biden\" }", XContentType.JSON));  
        bulkRequest.add(new IndexRequest().index(indexAliasName).id("2").setRequireAlias(true).source("{ \"name\": \"Trump\" }", XContentType.JSON));  
  
        BulkResponse bulkResponse = osClient.bulk(bulkRequest, RequestOptions.DEFAULT);  
  
        assertFalse(existsIndex(indexAliasName), "Should not auto-create the index.");  
        assertTrue(bulkResponse.hasFailures(), "Bulk response must have failures.");  
    } catch (Exception ex) {  
        Assert.fail("Must not throw an exception");  
    }  
}
```

### Expected behavior

At the moment the 'require alias' flag does not get transferred from the high-level REST client to OpenSearch and OpenSearch automatically creates the index with the name of the alias. This should not happen. It should fail in case there is no index with the alias. 

Logged call from the first example (Fail 1):
```
[TRACE] 2024-03-28 07:34:52.579 [main] tracer - curl -iX POST 'http://localhost:32787/_bulk?timeout=1m' -d '{"index":{"_index":"testindex-1","_id":"1"}}
{"name":"Biden"}
{"index":{"_index":"testindex-1","_id":"2"}}
{"name":"Trump"}
'
# HTTP/1.1 200 OK
# content-type: application/json; charset=UTF-8
# content-length: 373
#
# {"took":192,"errors":false,"items":[{"index":{"_index":"testindex-1","_id":"1","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}},{"index":{"_index":"testindex-1","_id":"2","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1,"status":201}}]}
````

### Additional Details

Belongs to OpenSearch 2.12.0. 

Btw. require alias works fine for single `IndexRequest` calls, thanks to this fix: https://github.com/opensearch-project/OpenSearch/issues/1528

```
private RestHighLevelClient osClient;

@Test  
public void t0060_singleIndexRequest() {  
    String indexAliasName = "testindex-5";  
    try {  
        IndexRequest indexRequest = new IndexRequest(indexAliasName)  
                .id("1")  
                .setRequireAlias(true)  
                .source("{ \"name\": \"Biden\" }", XContentType.JSON);  
  
        IndexResponse indexResponse = osClient.index(indexRequest, RequestOptions.DEFAULT);  
        Assert.fail("Must throw an exception in the line above.");  
    } catch (OpenSearchStatusException ex) {  
        assertEquals(RestStatus.NOT_FOUND, ex.status(), "Index must not found (= must not automatically created)");  
    } catch (Exception ex) {  
        Assert.fail("Must not throw this kind of exception");  
    }  
}
```    

or when the bulk request gets called by hand

```
private RestHighLevelClient osClient;

@Test  
public void t0050_byHandBulkWithRequireAlias() {  
    String indexAliasName = "testindex-6";  
    try {  
        String jsonString = """  
			{ "index" : { "_id" : "1" } }                    
			{ "name": "Biden" }
			{ "index" : { "_id" : "2" } }
			{ "name": "Trump" }
		""";  
  
        Request request = new Request("PUT", "/" + indexAliasName + "/_bulk");  
        request.addParameter("require_alias", "true");  
        request.setJsonEntity(jsonString);  
  
        Response bulkResponse = osClient.getLowLevelClient().performRequest(request);  
  
        assertFalse(existsIndex(indexAliasName), "Should not auto-create the index.");  
		String responseString = EntityUtils.toString(bulkResponse.getEntity());  
		assertTrue(responseString.contains("[require_alias]"));
	} catch (Exception ex) {  
        Assert.fail("Must not throw an exception");  
    }  
}
```

Example content from 'responseString' 
```
{"took":2,"errors":true,"items":[{"index":{"_index":"testindex-6","_id":"1","status":404,"error":{"type":"index_not_found_exception","reason":"no such index [testindex-6] and [require_alias] request flag is [true] and [testindex-6] is not an alias","index":"testindex-6","index_uuid":"_na_"}}},{"index":{"_index":"testindex-6","_id":"2","status":404,"error":{"type":"index_not_found_exception","reason":"no such index [testindex-6] and [require_alias] request flag is [true] and [testindex-6] is not an alias","index":"testindex-6","index_uuid":"_na_"}}}]}
```

### PR DESCRIPTION
**Pull request by parv0201**
### Description
Java high-level REST client bulk() is not respecting the bulkRequest.requireAlias(true) method call

### Related Issues
Resolves #12958 

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java [hunk 1]
```diff
@@ -232,6 +235,10 @@ static Request bulk(BulkRequest bulkRequest) throws IOException {
                             metadata.field("_source", updateRequest.fetchSource());
                         }
                     }
+
+                    if (action.isRequireAlias()) {
+                        metadata.field("require_alias", action.isRequireAlias());
+                    }
```
Comment (dblock) [inline client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java:241]: Does it behave differently without the `if (...)` part? Do other booleans have those conditions as well?

**Review by dblock — COMMENTED** [review]
Thanks. Since we're deprecating this stuff in favor of opensearch-java, and if you have time, check that `requireAlias` is properly implemented in https://github.com/opensearch-project/opensearch-api-specification and https://github.com/opensearch-project/opensearch-java pls.

File: client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java (hunk 1 above)
Comment (parv0201) [reply client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java:241]: Yes, 
It is creating a new index if I remove the if part.

File: client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java [hunk 2]
```diff
@@ -154,6 +154,9 @@ static Request bulk(BulkRequest bulkRequest) throws IOException {
         parameters.withRefreshPolicy(bulkRequest.getRefreshPolicy());
         parameters.withPipeline(bulkRequest.pipeline());
         parameters.withRouting(bulkRequest.routing());
+        if (bulkRequest.requireAlias() != null) {
```
Comment (dblock) [inline client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java:157]: I think this `if` is not required.

How?

https://github.com/opensearch-project/OpenSearch/blob/04a417a7328ef7d4c501508703898ff2b477f302/client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java#L1019

File: client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java (hunk 1 above)
Comment (dblock) [reply client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java:241]: I meant to ask that for the `if` above, sorry.

File: client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java (hunk 2 above)
Comment (parv0201) [reply client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java:157]: That if condition is required because the `bulkRequest.requireAlias()` method is returning Boolean wrapper class instead of boolean keyword. If we do not explicitly pass requireAlias with the request, it will pass on null value to the `withRequireAlias` method since it is expecting primitive type boolean parameter.

https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/bulk/BulkRequest.java#L427

https://github.com/opensearch-project/OpenSearch/blob/04a417a7328ef7d4c501508703898ff2b477f302/client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java#L1018

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
> ❌ Gradle check result for [4828958](https://github.com/opensearch-project/OpenSearch/commit/4828958b03e9482f41d3d6873f1b2c956ba70749): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/40557/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[org.opensearch.action.admin.indices.create.RemoteSplitIndexIT.classMethod](https://build.ci.opensearch.org/job/gradle-check/40557/testReport/junit/org.opensearch.action.admin.indices.create/RemoteSplitIndexIT/classMethod/)

https://github.com/opensearch-project/OpenSearch/issues/13828

**Comment by reta** [comment]
@parv0201 could you please send manual backport pull request towards `2.x` branch? thank you

**Comment by reta** [comment]
https://github.com/opensearch-project/OpenSearch/pull/14184
