### PR TITLE
Remove filter rewrite optimization for range aggregations when segment is not effective match all

### LINKED ISSUE #15169: [BUG] Range aggregation ignores query
### Describe the bug

Range aggregation ignores query. This is working ok in 2.15.0 and started to fail in the recent 2.16.0.

### Related component

Search:Aggregations

### To Reproduce

This problem was initially noticed with a routing filter, but it can also be reproduced with other queries, e.g., a range query.

1. Create a simple index
```http
PUT http://localhost:32772/range-agg-test-000001
Content-Type: application/json

{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "Integer": {
        "type": "integer"
      }
    }
  }
}
```
2. add a few documents to the index:
```http
POST http://localhost:32772/range-agg-test-000001/_doc/1?routing=route1
Content-Type: application/json

{
  "Integer": -2147483648
}
```
```http
POST http://localhost:32772/range-agg-test-000001/_doc/2?routing=route1
Content-Type: application/json

{
  "Integer": -2147483648
}
```
```http
POST http://localhost:32772/range-agg-test-000001/_doc/200?routing=route2
Content-Type: application/json

{
  "Integer": -2147483648
}
```
3.1. Try to get a range aggregation and use the filter on a route:
```http
POST http://localhost:32772/range-agg-test-000001/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": [
        {
          "terms": {
            "_routing": [
              "route1"
            ]
          }
        }
      ]
    }
  },
  "aggregations": {
    "aggregationName": {
      "range": {
        "field": "Integer",
        "keyed": true,
        "ranges": [
          {
            "to": 0,
            "key": "0"
          },
          {
            "from": 0,
            "key": "1"
          }
        ]
      }
    }
  },
  "_source": false
}
```

3.2. Alternatively, try a simple `>` query instead:

```http
POST http://localhost:32768/range-agg-test-000001/_search
Content-Type: application/json

{
  "query": {
    "range": {
      "Integer": {
        "gte": 10
      }
    }
  },
  "aggregations": {
    "aggregationName": {
      "range": {
        "field": "Integer",
        "keyed": true,
        "ranges": [
          {
            "to": 0,
            "key": "0"
          },
          {
            "from": 0,
            "key": "1"
          }
        ]
      }
    }
  },
  "_source": false
}
```

In both  cases, the result is:

```json
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 0,
      "relation": "eq"
    },
    "max_score": null,
    "hits": []
  },
  "aggregations": {
    "aggregationName": {
      "buckets": {
        "0": {
          "to": 0.0,
          "doc_count": 3
        },
        "1": {
          "from": 0.0,
          "doc_count": 0
        }
      }
    }
  }
}
```

### Expected behavior

It would be expected to get

- in the case of 3.1: 2 documents in the bucket "0" as there are only two documents with the `route1` :
```json 
{
  "aggregationName": {
    "buckets": {
      "0": {
        "to": 0.0,
        "doc_count": 2
      },
      "1": {
        "from": 0.0,
        "doc_count": 0
      }
    }
  }
}
```

- in the case of 3.2: 0 doc counts in both ranges, since none of the values are  > 0
```json 
{
  "aggregationName": {
    "buckets": {
      "0": {
        "to": 0.0,
        "doc_count": 0
      },
      "1": {
        "from": 0.0,
        "doc_count": 0
      }
    }
  }
}
```

### Additional Details

**Plugins**
```
ec6d9b89d3cf opensearch-alerting                  2.16.0.0
ec6d9b89d3cf opensearch-anomaly-detection         2.16.0.0
ec6d9b89d3cf opensearch-asynchronous-search       2.16.0.0
ec6d9b89d3cf opensearch-cross-cluster-replication 2.16.0.0
ec6d9b89d3cf opensearch-custom-codecs             2.16.0.0
ec6d9b89d3cf opensearch-flow-framework            2.16.0.0
ec6d9b89d3cf opensearch-geospatial                2.16.0.0
ec6d9b89d3cf opensearch-index-management          2.16.0.0
ec6d9b89d3cf opensearch-job-scheduler             2.16.0.0
ec6d9b89d3cf opensearch-knn                       2.16.0.0
ec6d9b89d3cf opensearch-ml                        2.16.0.0
ec6d9b89d3cf opensearch-neural-search             2.16.0.0
ec6d9b89d3cf opensearch-notifications             2.16.0.0
ec6d9b89d3cf opensearch-notifications-core        2.16.0.0
ec6d9b89d3cf opensearch-observability             2.16.0.0
ec6d9b89d3cf opensearch-performance-analyzer      2.16.0.0
ec6d9b89d3cf opensearch-reports-scheduler         2.16.0.0
ec6d9b89d3cf opensearch-security                  2.16.0.0
ec6d9b89d3cf opensearch-security-analytics        2.16.0.0
ec6d9b89d3cf opensearch-skills                    2.16.0.0
ec6d9b89d3cf opensearch-sql                       2.16.0.0
ec6d9b89d3cf query-insights                       2.16.0.0
```

**Host/Environment (please complete the following information):**
 - OS: Linux fedora 6.9.12-100.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jul 27 16:09:11 UTC 2024 x86_64 GNU/Linux
 - Version: OpenSerarch 2.16.0

**Additional context**
Running OpenSearch using the official `opensearchproject/opensearch:2.16.0` image.

### PR DESCRIPTION
**Pull request by finnegancarroll**
### Description
The filter rewrite optimization does not immediately disqualify requests containing a top level query with an aggregation. For example, date histogram aggregations [consider the top-level query](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Helper.java#L117) to see if it can be accommodated within the optimization by updating the aggregation ranges.

The range aggregation does not include this logic and currently allows for the optimized filter rewrite path even when a top-level query is present. When this top-level query is not match all we risk returning incorrect results to the user as our optimized path does not account for anything other than the range aggregation bounds.

This change disables the filter rewrite optimization path for range aggregations when the query is not **effective match all at the segment level**.

### Related Issues
Resolves #15169 

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java [hunk 1]
```diff
@@ -70,6 +70,7 @@
 import java.util.function.Function;
 
 import static org.opensearch.core.xcontent.ConstructingObjectParser.optionalConstructorArg;
+import static org.opensearch.search.aggregations.bucket.filterrewrite.DateHistogramAggregatorBridge.segmentMatchAll;
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java:73]: Importing from `DateHistogramAggregatorBridge` does not look correct. Can we move `segmentMatchAll` to parent class `AggregatorBridge`?

File: rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml [hunk 2]
```diff
@@ -673,3 +673,49 @@ setup:
   - match: { aggregations.my_range.buckets.3.from: 1.5 }
   - is_false:  aggregations.my_range.buckets.3.to
   - match: { aggregations.my_range.buckets.3.doc_count: 2 }
+
+---
+"Range query and aggregation test":
+  - do:
+      bulk:
+        refresh: true
+        index: range-agg-w-query
```
Comment (jainankitk) [inline rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml:682]: Although, I don't think we need additional code changes, can you still add test case for `date_range` aggregation as well?

File: server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java [hunk 3]
```diff
@@ -310,7 +311,7 @@ public ScoreMode scoreMode() {
 
     @Override
     public LeafBucketCollector getLeafCollector(LeafReaderContext ctx, final LeafBucketCollector sub) throws IOException {
-        boolean optimized = filterRewriteOptimizationContext.tryOptimize(ctx, this::incrementBucketDocCount, false);
+        boolean optimized = filterRewriteOptimizationContext.tryOptimize(ctx, this::incrementBucketDocCount, segmentMatchAll(context, ctx));
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java:314]: Isn't false more conservative? We're always trying to skip the segment level matchAll optimization? Should we keep it as is for this bug fix?

File: server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/FilterRewriteOptimizationContext.java [hunk 4]
```diff
@@ -99,12 +99,10 @@ void setRanges(Ranges ranges) {
     public boolean tryOptimize(final LeafReaderContext leafCtx, final BiConsumer<Long, Long> incrementDocCount, boolean segmentMatchAll)
         throws IOException {
         segments.incrementAndGet();
-        if (!canOptimize) {
-            return false;
-        }
 
+        if (!canOptimize) return false;
+        if (!segmentMatchAll) return false;
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/FilterRewriteOptimizationContext.java:104]: This code path is common across date histogram aggregations as well? Does this mean we have similar issue there as well?

File: server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/FilterRewriteOptimizationContext.java [hunk 5]
```diff
@@ -120,7 +118,7 @@ public boolean tryOptimize(final LeafReaderContext leafCtx, final BiConsumer<Lon
             return false;
         }
 
-        Ranges ranges = getRanges(leafCtx, segmentMatchAll);
+        Ranges ranges = getRanges(leafCtx);
         if (ranges == null) return false;
```
Comment (harshavamsi) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/FilterRewriteOptimizationContext.java:122]: It looks like we return false here if ranges is null and `getRanges` should return null if `segmentMatchAll` is false anyway? So we should be avoiding the optimization anyway, wondering how this change is helping?

File: rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml [hunk 6]
```diff
@@ -673,3 +673,49 @@ setup:
...
+                ranges:
+                  - to: 0
+                    key: "0"
+                  - from: 0
+                    key: "1"
+          _source: false
+
+  - match: { hits.total.value: 3 }
+  - match: { aggregations.aggregationName.buckets.0.doc_count: 2 }
+  - match: { aggregations.aggregationName.buckets.1.doc_count: 1 }
```
Comment (harshavamsi) [inline rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml:721]: Can we also assert on the debug assertions for the optimized segment count like [here](https://github.com/opensearch-project/OpenSearch/pull/15194/files#diff-25ce25483f0456d91edb3f7644f0857bd50c1c3a2c3fbb671e75ec1ba27f855aL607).

**Comment by msfroh** [comment]
Just to be clear, this disables the optimization whenever the top-level query does not match every document in the segment, right? (If the top-level query is "functionally" match-all, like it matches on a term present in every document in the segment, then it still applies. Similarly, if it's a range query where every document is in the range, then it applies.)

Do we still optimize when the top-level query is a range query over the same field as the aggregation? I'm okay with losing that part of the optimization (assuming we ever had it) if it fixes the much-more-serious functional regression. If we do lose it (or we never had it), we should open a follow-up issue to cover that case.

File: server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java (hunk 1 above)
Comment (finnegancarroll) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java]: I've made some updates to fix failing dateHistogram cases and segmentMatchAll is no longer used.

File: server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java (hunk 3 above)
Comment (finnegancarroll) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java]: Leaving as is. Instead failing when the range agg attempts to construct shard level ranges.

File: server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/FilterRewriteOptimizationContext.java (hunk 5 above)
Comment (finnegancarroll) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/FilterRewriteOptimizationContext.java]: Removed tryOptimize changes.

**Comment by finnegancarroll** [comment]
> The original improvement had [this condition](https://github.com/opensearch-project/OpenSearch/blob/0ddbd96291d4ff05499ec53c5a04a5dda32d36ad/server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/FilterRewriteHelper.java#L110) for gating the improvement. I am wondering if we still have it somewhere?

The logic for unwrapping/validating queries is now [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Helper.java#L117). It seems we still support this optimization even when a query is not match all as long as we can update aggregation bounds. I've updated my change to reflect this.

Date histogram changes removed, range aggregator optimization path now fails to build ranges if query is not match all.

**Comment by finnegancarroll** [comment]
> Just to be clear, this disables the optimization whenever the top-level query does not match every document in the segment, right? (If the top-level query is "functionally" match-all, like it matches on a term present in every document in the segment, then it still applies. Similarly, if it's a range query where every document is in the range, then it applies.)
> 
> Do we still optimize when the top-level query is a range query over the same field as the aggregation? I'm okay with losing that part of the optimization (assuming we ever had it) if it fixes the much-more-serious functional regression. If we do lose it (or we never had it), we should open a follow-up issue to cover that case.

Date histogram does [consider the top-level query](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Helper.java#L117) but range aggs do not. Will create an issue to support the filter rewrite optimization for "workable" top level queries. This change prevents the optimization for only range aggs with top level queries that are not match all.

File: server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Helper.java [hunk 7]
```diff
@@ -60,7 +60,7 @@ private Helper() {}
      * Recursively unwraps query into the concrete form
      * for applying the optimization
      */
-    private static Query unwrapIntoConcreteQuery(Query query) {
+    public static Query unwrapIntoConcreteQuery(Query query) {
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Helper.java:63]: Can this be package private?

File: server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/RangeAggregatorBridge.java [hunk 8]
```diff
@@ -51,8 +54,14 @@ protected boolean canOptimize(ValuesSourceConfig config, RangeAggregator.Range[]
...
 
-    protected void buildRanges(RangeAggregator.Range[] ranges) {
+    protected void buildRanges(RangeAggregator.Range[] ranges, SearchContext context) {
         assert fieldType instanceof NumericPointEncoder;
+        Query unwrap = Helper.unwrapIntoConcreteQuery(context.query());
+        if (!(unwrap instanceof MatchAllDocsQuery)) {
+            setRanges.accept(null);
+            return;
+        }
+
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/RangeAggregatorBridge.java:64]: This might be fine for the regression fix. Can you create an issue for including `PointRangeQuery`, `FieldExistsQuery` scenarios similar to `DateHistogram` aggregation?

```
        if (cq instanceof PointRangeQuery) {
            final PointRangeQuery prq = (PointRangeQuery) cq;
            final long[] indexBounds = getShardBounds(leaves, fieldName);
            if (indexBounds == null) return null;
            return getBoundsWithRangeQuery(prq, fieldName, indexBounds);
        } else if (cq instanceof MatchAllDocsQuery) {
            return getShardBounds(leaves, fieldName);
        } else if (cq instanceof FieldExistsQuery) {
            // when a range query covers all values of a shard, it will be rewrite field exists query
            if (((FieldExistsQuery) cq).getField().equals(fieldName)) {
                return getShardBounds(leaves, fieldName);
            }
        }
```

Comment (jainankitk) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/RangeAggregatorBridge.java:64]: Or actually, we can include test case for `PointRangeQuery`, `FieldExistsQuery` along with range aggregation on the same and different fields and validate that the optimization applies only for the same field case?

Comment (finnegancarroll) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/RangeAggregatorBridge.java:64]: Created. Will add this support in a follow up PR.
#15217

**Comment by jainankitk** [comment]
@finnegancarroll - Can we also trigger performance benchmark for this PR, just to know what to expect once this goes in? Are there any operations that will look regressed, although they might not be returning correct results earlier. Related https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/367

**Comment by finnegancarroll** [comment]
{"run-benchmark-test": "id_5"}

**Comment by rishabh6788** [comment]
> It looks like all range aggs in big5 are top-level, so not expecting any regressions on this workload.

`noaa` workload has some complex range queries. https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/main/noaa/operations/default.json
Check it out and let me know if it suits your need, I can add this workload in the config as well. We already have nightlies running for this workload.

**Comment by finnegancarroll** [comment]
> > It looks like all range aggs in big5 are top-level, so not expecting any regressions on this workload.
> 
> `noaa` workload has some complex range queries. https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/main/noaa/operations/default.json Check it out and let me know if it suits your need, I can add this workload in the config as well. We already have nightlies running for this workload.

Thanks! Looked through and don't see any relevant queries here either unfortunately. All the range aggs are top-level it seems. Making a note on the feature request #15217 to add a workload relevant to this feature so we can see it's impact on performance when it does get in.

**Comment by finnegancarroll** [comment]
> Benchmark Baseline Comparison Results

No notable benchmark regressions.

**Review by jainankitk — APPROVED** [review]

**Comment by msfroh** [comment]
This is now *explicitly* checking for `MatchAllDocsQuery`? I thought we were still going to check at the segment level for the `segmentMatchAll` condition (i.e. the top-level query's `Weight.count()` for the segment is equal to `maxDoc()`).

**Comment by finnegancarroll** [comment]
> This is now _explicitly_ checking for `MatchAllDocsQuery`? I thought we were still going to check at the segment level for the `segmentMatchAll` condition (i.e. the top-level query's `Weight.count()` for the segment is equal to `maxDoc()`).

I've updated the change to only impact range aggregations and created a follow up issue for enhancements to allow range aggs to take the optimized path when the top-level query is appropriate. This PR doesn't include any additional optimization changes and just disables the optimization in cases where the range aggregation might return an incorrect response.

**Comment by msfroh** [comment]
> I've updated the change to only impact range aggregations and created a follow up issue for enhancements to allow range aggs to take the optimized path when the top-level query is appropriate. This PR doesn't include any additional optimization changes and just disables the optimization in cases where the range aggregation might return an incorrect response.

But the range aggregation should still return the correct response if the top-level query is **functionally** match-all (which is what `segmentMatchAll` was checking). The bug is that we were apparently missing that check, right?

File: server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregatorTests.java [hunk 9]
```diff
@@ -124,6 +132,36 @@ public void testMatchesNumericDocValues() throws IOException {
...
+            iw.addDocument(doc2);
+            iw.addDocument(doc3);
+        }, range -> {
+            List<? extends InternalRange.Bucket> ranges = range.getBuckets();
+            assertEquals(2, ranges.size());
+            assertEquals(1, ranges.get(0).getDocCount());
+            assertEquals(1, ranges.get(1).getDocCount());
+            assertTrue(AggregationInspectionHelper.hasValue(range));
+        });
+    }
```
Comment (msfroh) [inline server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregatorTests.java:163]: I would create two versions of this test case. 

One would be the existing one, where you should confirm that the optimization doesn't kick in (because the top-level query doesn't match all docs in the segment).

The other version would create all three docs with `"route1"` as the keyword value. In this case, even though it's not literally a `MatchAllDocsQuery`, the top-level query matches all the docs, so you could apply the optimization.

**Review by msfroh — APPROVED** [review]

**Comment by finnegancarroll** [comment]
Moved from checking for explicit `MatchAllQuery` to `segmentMatchAll` when disqualifying segments from optimization path.

**Comment by finnegancarroll** [comment]
{"run-benchmark-test": "id_5"}

**Comment by finnegancarroll** [comment]
No notable benchmark changes after update.
