### PR TITLE
[Segment Replication] Compatibility check for differing lucene codec versions

### LINKED ISSUE #6616: [SegmentReplication] RollingUpgrade - Add a compatibility check to avoid shard failure
**Describe the bug**
As part of rolling upgrades, we don't want to be locked to any version. Right now, in a mixed cluster state where a primary sends segments on a higher lucene codec version to the replicas, we will see the below error on replicas that causes a shard failure: 

```
[2023-03-08T22:03:30,951][WARN ][o.o.i.c.IndicesClusterStateService] [node3] [my-index-000003][0] marking and sending shard failed due to [shard failure, reason [replication failure]]
org.opensearch.indices.replication.common.ReplicationFailedException: [my-index-000003][0]: Replication failed on  (failed to clean after replication)
	at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$finalizeReplication$4(SegmentReplicationTarget.java:254) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.action.ActionListener.completeWith(ActionListener.java:342) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.indices.replication.SegmentReplicationTarget.finalizeReplication(SegmentReplicationTarget.java:209) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$startReplication$2(SegmentReplicationTarget.java:170) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.action.ActionListener$1.onResponse(ActionListener.java:80) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:126) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:343) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:112) ~[opensearch-2.5.0.jar:2.5.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:112) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:160) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:141) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.action.StepListener.innerOnResponse(StepListener.java:77) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:55) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.action.ActionListener$4.onResponse(ActionListener.java:180) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.action.ActionListener$6.onResponse(ActionListener.java:299) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.action.support.RetryableAction$RetryingListener.onResponse(RetryableAction.java:181) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:69) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1404) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:393) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.transport.InboundHandler.lambda$handleResponse$1(InboundHandler.java:387) ~[opensearch-2.5.0.jar:2.5.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.5.0.jar:2.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Could not load codec 'Lucene95'. Did you forget to add lucene-backward-codecs.jar?
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:515) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
	at org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:404) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:363) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:310) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
	at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$finalizeReplication$4(SegmentReplicationTarget.java:218) ~[opensearch-2.5.0.jar:2.5.0]
	... 26 more
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (a859c5b). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(SegmentInfos))
		at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:500) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
		at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:370) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
		at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:310) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
		at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$finalizeReplication$4(SegmentReplicationTarget.java:218) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.action.ActionListener.completeWith(ActionListener.java:342) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.indices.replication.SegmentReplicationTarget.finalizeReplication(SegmentReplicationTarget.java:209) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$startReplication$2(SegmentReplicationTarget.java:170) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.action.ActionListener$1.onResponse(ActionListener.java:80) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:126) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:343) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:112) ~[opensearch-2.5.0.jar:2.5.0]
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
		at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:112) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:160) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:141) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.action.StepListener.innerOnResponse(StepListener.java:77) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:55) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.action.ActionListener$4.onResponse(ActionListener.java:180) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.action.ActionListener$6.onResponse(ActionListener.java:299) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.action.support.RetryableAction$RetryingListener.onResponse(RetryableAction.java:181) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:69) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1404) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:393) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.transport.InboundHandler.lambda$handleResponse$1(InboundHandler.java:387) ~[opensearch-2.5.0.jar:2.5.0]
		at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.5.0.jar:2.5.0]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene95' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene94, Lucene80, Lucene84, Lucene86, Lucene87, Lucene70, Lucene90, Lucene91, Lucene92]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:113) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
	at org.apache.lucene.codecs.Codec.forName(Codec.java:118) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:511) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
	at org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:404) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:363) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:310) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
	at org.opensearch.indices.replication.SegmentReplicationTarget.lambda$finalizeReplication$4(SegmentReplicationTarget.java:218) ~[opensearch-2.5.0.jar:2.5.0]
	... 26 more
 
```

**To Reproduce**
1. Set up a mixed cluster with nodes using differing lucene codec versions (with the primary being on a higher version). 
2. Index a couple of documents and force segment replication to take place. 

**Expected behavior**
To avoid the above situation of a shard failure, we need to add in a compatibility check that just prints out a warning that they are on differing versions and avoid moving forward with the segment replication. 

Risks: This might cause an eventual shard failure if the replica falls too far behind the primary if it's not upgraded in time.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Poojita-Raj**
### Description
This change aims to fail segment replications between the primary and replica if they are utilizing differing lucene codec versions. This is to avoid the current behavior of failing the replica shard in such situations.

### Issues Resolved
Resolves #6616 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java [hunk 1]
```diff
@@ -220,9 +220,9 @@ public void testPreferReplicaWithHighestPrimaryTerm() {
             allocId2,
             allocId3
         );
-        testAllocator.addData(node1, allocId1, false, new ReplicationCheckpoint(shardId, 20, 101, 1));
-        testAllocator.addData(node2, allocId2, false, new ReplicationCheckpoint(shardId, 22, 120, 2));
-        testAllocator.addData(node3, allocId3, false, new ReplicationCheckpoint(shardId, 20, 120, 2));
+        testAllocator.addData(node1, allocId1, false, new ReplicationCheckpoint(shardId, 20, 101, 1, "lucene95"));
+        testAllocator.addData(node2, allocId2, false, new ReplicationCheckpoint(shardId, 22, 120, 2, "lucene95"));
+        testAllocator.addData(node3, allocId3, false, new ReplicationCheckpoint(shardId, 20, 120, 2, "lucene95"));
```
Comment (dreamer-89) [inline server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java:225]: Can you please use code to derive the codec name here `Codec.getDefault().getName()` ?

File: server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java [hunk 2]
```diff
@@ -47,7 +47,7 @@
 public class OngoingSegmentReplicationsTests extends IndexShardTestCase {
 
     private final IndicesService mockIndicesService = mock(IndicesService.class);
-    private ReplicationCheckpoint testCheckpoint;
+    private ReplicationCheckpoint testCheckpoint, testCheckpoint2;
```
Comment (dreamer-89) [inline server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java:50]: nit: testCheckpoint2 -> checkpointOnOlderCode

File: server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java [hunk 3]
```diff
@@ -74,7 +74,8 @@ public void setUp() throws Exception {
         ShardId testShardId = primary.shardId();
 
         // This mirrors the creation of the ReplicationCheckpoint inside CopyState
-        testCheckpoint = new ReplicationCheckpoint(testShardId, primary.getOperationPrimaryTerm(), 0L, 0L);
+        testCheckpoint = new ReplicationCheckpoint(testShardId, primary.getOperationPrimaryTerm(), 0L, 0L, "Lucene95");
+        testCheckpoint2 = new ReplicationCheckpoint(testShardId, primary.getOperationPrimaryTerm(), 0L, 0L, "Lucene94");
```
Comment (dreamer-89) [inline server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java:78]: nit: Can we generate these constants from actual codecs (or helper classes). Is there any utility which provides an older version of codec

**Comment by dreamer-89** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/12717/
> * **CommitID:** [6b4b64b](https://github.com/opensearch-project/OpenSearch/commit/6b4b64b6aaf171199e15980b7756efbfbc3acdd2)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

@Poojita-Raj : Looks like a legit failure.
```
> Task :server:test

org.opensearch.indices.replication.SegmentReplicationTargetServiceTests > testOnNewCheckpointFromNewPrimaryCancelOngoingReplication FAILED
    Argument(s) are different! Wanted:
    segmentReplicationTargetService.startReplication(
        ReplicationCheckpoint{shardId=[index][0], primaryTerm=100, segmentsGen=4, version=8, size=0, codec=Asserting},
        org.opensearch.index.shard.IndexShard@2a88af1e,
        <any>
    );
    -> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication(SegmentReplicationTargetServiceTests.java:240)
    Actual invocations have different arguments:
    segmentReplicationTargetService.startReplication(
        org.opensearch.indices.replication.SegmentReplicationTarget$MockitoMock$DfKM6oI5@6ceac65e
    );
    -> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication(SegmentReplicationTargetServiceTests.java:235)
    segmentReplicationTargetService.onNewCheckpoint(
        ReplicationCheckpoint{shardId=[index][0], primaryTerm=100, segmentsGen=4, version=8, size=0, codec=Asserting},
        org.opensearch.index.shard.IndexShard@2a88af1e
    );
    -> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.lambda$testOnNewCheckpointFromNewPrimaryCancelOngoingReplication$1(SegmentReplicationTargetServiceTests.java:225)
        at __randomizedtesting.SeedInfo.seed([387957A7584E7A9:DABA5C54F5D74498]:0)
        at app//org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication(SegmentReplicationTargetServiceTests.java:240)
```

File: server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java [hunk 4]
```diff
@@ -147,6 +148,16 @@ void startSegmentCopy(GetSegmentFilesRequest request, ActionListener<GetSegmentF
...
         final CopyState copyState = getCachedCopyState(request.getCheckpoint());
+        if (copyState.getCheckpoint()
+            .getLatestSupportedCodec()
+            .equalsIgnoreCase(request.getCheckpoint().getLatestSupportedCodec()) == false) {
+            // cancel(request.getTargetAllocationId(), "Requested unsupported codec version");
+            logger.trace("Requested unsupported codec version {}", request.getCheckpoint().getLatestSupportedCodec());
+            throw new CancellableThreads.ExecutionCancelledException(
+                new ParameterizedMessage("Requested unsupported codec version {}", request.getCheckpoint().getLatestSupportedCodec())
+                    .toString()
+            );
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java:159]: @Poojita-Raj : I think we need integration tests here verifying behavior 
1. Both nodes running on same OS version
2. Source node running on higher lucene codec
3. Target node running on higher lucene codec

File: server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java [hunk 5]
```diff
@@ -61,6 +78,7 @@ public ReplicationCheckpoint(StreamInput in) throws IOException {
         segmentsGen = in.readLong();
         segmentInfosVersion = in.readLong();
         length = in.readLong();
+        latestSupportedCodec = in.readString();
```
[the remark this answers is not in the document]
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java:81]: We need to hide both `length` (missed previously) and `latestSupportedCodec` behind version check.

File: server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java [hunk 6]
```diff
@@ -147,6 +148,16 @@ void startSegmentCopy(GetSegmentFilesRequest request, ActionListener<GetSegmentF
      */
     CopyState prepareForReplication(CheckpointInfoRequest request, FileChunkWriter fileChunkWriter) throws IOException {
         final CopyState copyState = getCachedCopyState(request.getCheckpoint());
+        if (copyState.getCheckpoint()
+            .getLatestSupportedCodec()
+            .equalsIgnoreCase(request.getCheckpoint().getLatestSupportedCodec()) == false) {
+            // cancel(request.getTargetAllocationId(), "Requested unsupported codec version");
+            logger.trace("Requested unsupported codec version {}", request.getCheckpoint().getLatestSupportedCodec());
+            throw new CancellableThreads.ExecutionCancelledException(
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java:156]: It will be good to have one integration test to verify behavior on target around handling this exception and verifying shard is not failed.

**Review by dreamer-89 — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java:81]: Yes, I'm adding it along with the test fix

**Comment by Poojita-Raj** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> 
>     * **RESULT:** FAILURE ❌
> 
>     * **URL:** https://build.ci.opensearch.org/job/gradle-check/12827/
> 
>     * **CommitID:** [67066b8](https://github.com/opensearch-project/OpenSearch/commit/67066b88061521a697b760ec2dcd385a54862000)
>       Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>       Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Failing flaky test unrelated: #6809

File: server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java (hunk 4 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java]: I am verifying 2 and 3 with the unit tests added in OngoingSegmentReplicationTests. Currently with this release, I'm unable to add in integration tests since it requires having this change in 2 different distributions of OS with differing codecs. But they can definitely be included in further releases.

File: server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java (hunk 6 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java:155]: Same as above.

File: server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java [hunk 7]
```diff
@@ -30,37 +32,61 @@ public class ReplicationCheckpoint implements Writeable, Comparable<ReplicationC
...
     private final long length;
+    private final String latestSupportedCodec;
+    private CodecService codecService;
 
     public static ReplicationCheckpoint empty(ShardId shardId) {
         return new ReplicationCheckpoint(shardId);
     }
 
     private ReplicationCheckpoint(ShardId shardId) {
+        codecService = new CodecService(null, null);
```
Comment (nknize) [inline server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java:43]: The problem here is that plugins can implement a custom CodecService provided through [`getCustomCodecServiceFactory`](https://github.com/opensearch-project/OpenSearch/blob/8c9cfdcf77d4a13f74fb010c235ab307b9fe6cc7/server/src/main/java/org/opensearch/plugins/EnginePlugin.java#L87). When you create a new ReplicationCheckpoint I think you'll need to use the codecService defined by the indexSettings?

**Review by nknize — COMMENTED** [review]
Quick look I'm not sure how compatible this will be w/ Plugins overriding CodecService

File: server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java [hunk 8]
```diff
@@ -30,37 +32,59 @@ public class ReplicationCheckpoint implements Writeable, Comparable<ReplicationC
     private final long segmentsGen;
     private final long segmentInfosVersion;
     private final long length;
+    private final String latestSupportedCodec;
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java:35]: nit: This variabled name seems not appropriate as we are using the codec used in engine.

File: server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java (hunk 7 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java]: Modified the constructor for ReplicationCheckpoint to pick up the codecService set up for the shard.

Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java]: Thanks for the review @nknize! Could you take a second look to see if the changes address your concerns?

File: server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java [hunk 9]
```diff
@@ -147,6 +148,12 @@ void startSegmentCopy(GetSegmentFilesRequest request, ActionListener<GetSegmentF
      */
     CopyState prepareForReplication(CheckpointInfoRequest request, FileChunkWriter fileChunkWriter) throws IOException {
         final CopyState copyState = getCachedCopyState(request.getCheckpoint());
+        if (copyState.getCheckpoint().getCodec().equalsIgnoreCase(request.getCheckpoint().getCodec()) == false) {
```
Comment (andrross) [inline server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java:151]: Why the case-insensitive comparison here?

File: server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java [hunk 10]
```diff
@@ -30,37 +32,46 @@ public class ReplicationCheckpoint implements Writeable, Comparable<ReplicationC
...
     }
 
     public ReplicationCheckpoint(StreamInput in) throws IOException {
         shardId = new ShardId(in);
         primaryTerm = in.readLong();
         segmentsGen = in.readLong();
         segmentInfosVersion = in.readLong();
-        length = in.readLong();
+        if (in.getVersion().onOrAfter(Version.V_2_7_0)) {
+            length = in.readLong();
```
Comment (andrross) [inline server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java:69]: Why is `length` inside this version guard where previously it was not?

Also, how does this work? 2.7 doesn't understand this new field (yet). I'm guessing there is no bwc coverage for this functionality?

File: server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java [hunk 11]
```diff
@@ -30,37 +32,46 @@ public class ReplicationCheckpoint implements Writeable, Comparable<ReplicationC
...
     }
 
-    private ReplicationCheckpoint(ShardId shardId) {
+    private ReplicationCheckpoint(ShardId shardId, CodecService codecService) {
         this.shardId = shardId;
         primaryTerm = SequenceNumbers.UNASSIGNED_PRIMARY_TERM;
         segmentsGen = SequenceNumbers.NO_OPS_PERFORMED;
         segmentInfosVersion = SequenceNumbers.NO_OPS_PERFORMED;
         length = 0L;
+        codec = codecService.codec("default").getName();
```
Comment (andrross) [inline server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java:47]: Since all you need here is the name, I would recommend passing in a `String` instead of a `CodecService`. Let the caller figure out how to get the name from the CodecService. I _think_ this means you can probably avoid exposing the CodecService from IndexShard and instead only expose the codec service name.

File: server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java (hunk 9 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java:151]: Good catch, that was a remnant of a previous version where we passed in a string of codec name instead of codec service. I'll make the change.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 12]
```diff
@@ -494,6 +494,10 @@ public boolean isSystem() {
         return indexSettings.getIndexMetadata().isSystem();
     }
 
+    public CodecService codecService() {
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:497]: Can this become `getCodecName()` since it looks like the only thing this is used for is to get the name?

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 13]
```diff
@@ -494,6 +494,10 @@ public boolean isSystem() {
         return indexSettings.getIndexMetadata().isSystem();
     }
 
+    public String getCodecName() {
+        return codecService.codec("default").getName();
```
[the remark this answers is not in the document]
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java]: You're right, this naming makes sense. Added in the change + documentation for the method.

**Review by andrross — APPROVED** [review]
