### PR TITLE
Don't run EmptyDirTaskTests in a Docker container

### LINKED ISSUE #3674: [BUG] testCreateEmptyDirNoPermissions when running gradle check in docker container
Just grab a centos7 docker container like this one:
https://hub.docker.com/r/opensearchstaging/ci-runner/tags?page=1&ordering=last_updated&name=ci-runner-centos7-gradle-check-v1

Export these envvar:
JAVA11_HOME="/opt/java/openjdk-11
JAVA17_HOME="/opt/java/openjdk-17"
JAVA8_HOME="/opt/java/openjdk-8"
JAVA_HOME="/opt/java/openjdk-17"

Check out main or 2.0 branch, run `./gradlew check --no-daemon --no-scan`.

The error log is like this:
```
> Task :build-tools:test FAILED

org.opensearch.gradle.EmptyDirTaskTests > testCreateEmptyDirNoPermissions FAILED
    java.lang.AssertionError at EmptyDirTaskTests.java:81

org.opensearch.gradle.EmptyDirTaskTests > testCreateEmptyDirNoPermissions FAILED
    java.lang.AssertionError at EmptyDirTaskTests.java:81

org.opensearch.gradle.EmptyDirTaskTests > testCreateEmptyDirNoPermissions FAILED
    java.lang.AssertionError at EmptyDirTaskTests.java:81

```

Related to this:
https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java#L90-L92

Thanks.

### PR DESCRIPTION
**Pull request by dbwiddis**
Signed-off-by: Daniel Widdis <widdis@gmail.com>

### Description
Docker doesn't provide the permissions to test EmptyDirTask. Similar to the Windows OS, the test should not run if it detects that environment.

The primary/reliable/consistent test of whether in a Docker container is the presence of a `.dockerenv` file in the root directory. There was mention in 2016 that this could in theory be removed in the future but it's still present 6 years later and other proposed alternatives are not consistently valid in 2022. I added two potential backup tests.
 
### Issues Resolved
Fixes #3674 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java [hunk 1]
```diff
@@ -65,6 +68,7 @@ public void testCreateEmptyDir() throws Exception {
 
     public void testCreateEmptyDirNoPermissions() throws Exception {
         RandomizedTest.assumeFalse("Functionality is Unix specific", Os.isFamily(Os.FAMILY_WINDOWS));
+        RandomizedTest.assumeFalse("Functionality doesn't work in Docker", isRunningInDocker());
```
Comment (owaiskazi19) [inline buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java:71]: Can we add a comment and explain the reason about why it doesn't work in docker?

Comment (dbwiddis) [reply buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java:74]: We can. And we did.

**Comment by owaiskazi19** [comment]
@dbwiddis Precommit failed
```
/home/runner/work/OpenSearch/OpenSearch/buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java:96: error: cannot find symbol
    private File getNewNonExistingTempFolderFile(Project project) throws IOException {
> Task :buildSrc:compileTestJava
                                                 ^
  symbol:   class Project
  location: class EmptyDirTaskTests
/home/runner/work/OpenSearch/OpenSearch/buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java:49: error: cannot find symbol
        Project project = ProjectBuilder.builder().build();
        ^
  symbol:   class Project
  location: class EmptyDirTaskTests
/home/runner/work/OpenSearch/OpenSearch/buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java:76: error: cannot find symbol
        Project project = ProjectBuilder.builder().build();
        ^
  symbol:   class Project
  location: class EmptyDirTaskTests
Note: Some input files use or override a deprecated API.
> Task :buildSrc:compileTestJava FAILED

**Comment by dbwiddis** [comment]
> @dbwiddis Precommit failed

The perils of editing on my home machine where I hadn't suppressed save actions and it went crazy.  All fixed now.

**Review by owaiskazi19 — APPROVED** [review]
LGTM! Thanks for the changes

**Comment by reta** [comment]
> Hi @reta, let me know if I need to make any changes here!

LGTM, I don't know better way to detect if JVM is running in Docker or not ...

**Review by reta — APPROVED** [review]
