### PR TITLE
Fix ingest pipeline cannot be executed when retry the failed index requests for update_by_query and reindex

### LINKED ISSUE #14337: [BUG] Update_by_query call updates document even if ingest pipeline processor has failed with exception
### Describe the bug

Doc values got updated after `update_by_query` call in case ingest pipeline is configured and one of processors in that pipeline has failed. 

### Related component

Indexing

### To Reproduce

1. Setup cluster with distribution OS 2.11 with following plugins: ml-commons, knn, neural. Create index with settings similar to following:
```
{
    "settings": {
        "index.knn": true,
        "default_pipeline": "pipeline-test"
    },
    "mappings": {
        "_source": {
            "excludes": [
                "passage_embedding"
            ]
        },
        "properties": {
            "passage_embedding": {
                "type": "knn_vector",
                "dimension": 1536,
                "method": {
                    "name": "hnsw",
                    "space_type": "cosinesimil",
                    "engine": "nmslib",
                    "parameters": {
                        "ef_construction": 512,
                        "m": 8
                    }
                }
            },
            "name": {
                "type": "text"
            },
            "passage_text": {
                "type": "text"
            }
        }
    }
}
```
2. Setup a model using remote connector of ml-commons (https://opensearch.org/docs/latest/ml-commons-plugin/remote-models/connectors/), configure it in a way it throttles requests. In our test we use openai model and configured it to accept 6 requests per minute. Get model id of that model.
3. Create ingest pipeline with at least one processor that has "ignore_failures" flag "false":
```
PUT /_ingest/pipeline/pipeline-test
{
    "description": "An NLP ingest pipeline",
    "processors": [
        {
            "text_embedding": {
                "model_id": "<model_id>",
                "field_map": {
                    "name": "passage_embedding"
                },
                "ignore_failure": false
            }
        }
    ]
}
```
4. Ingest several documents:
```
POST /_bulk
{ "index": { "_index": "index-test" } }
{ "name": "permission", "test": "Writing a list of random sentences is harder than I initially thought it would be.", "doc_keyword": "workable", "doc_index": 4976 }
{ "index": { "_index": "index-test" } }
{ "name": "sister", "test": "The fifty mannequin heads floating in the pool kind of freaked them out", "doc_keyword": "angry"}
{ "index": { "_index": "index-test" } }
{ "name": "hair", "test": "Too many prisons have become early coffins", "doc_keyword": "likeable", "doc_index": 2351  }
{ "index": { "_index": "index-test" } }
{ "name": "editor", "test": "Greetings from the real universe", "doc_index": 9871 }
{ "index": { "_index": "index-test" } }
{ "name": "statement", "test": "People keep telling me orange but I still prefer pink", "doc_keyword": "entire", "doc_index": 8242  } 
```
5. Check that there are no documents with empty `passage_embedding` value:
```
GET /index-test/_search
{
    "query": {
        "bool": {
            "must_not": [
                {
                    "exists": {
                        "field": "passage_embedding"
                    }
                }
            ]
        }
    }
}
```
6. Execute update_by_query request multiple times until you got an error from the model:
```
POST /index-test/_update_by_query
{
  "query": {
    "range": {
      "doc_index": {
        "gte": 4000,
        "lte": 5000
      }
    }
  },
  "script" : {
    "source": "ctx._source.doc_index++; ctx._source.doc_keyword=\"key1\";ctx._source.test=\"Text random 1\"",
    "lang": "painless"
  }
}
```
7. Run check for documents with empty passage_embedding. If search has returned anything (>= 1 hits) that means there are docs without embeddings. This is not the right behavior, all docs were ingested with embeddings, and only operation that caused embeddings to disappear was `update` :
```
GET /index-test/_search
{
    "query": {
        "bool": {
            "must_not": [
                {
                    "exists": {
                        "field": "passage_embedding"
                    }
                }
            ]
        }
    }
}
```

### Expected behavior

Because processor has been configured with 'ignore_failures` `false` we expect that update call has failed and no changes are stored. 

### Additional Details

**Plugins**
ml-commons, k-NN, neural-search

**Host/Environment (please complete the following information):**
 - Version 2.11

**Additional context**
I've tried same scenario without exclude setting for "passage_embedding" field and it works as expected.
```
        "_source": {
            "excludes": [
                "passage_embedding"
            ]
        },
```
I assume that behind the scenes document is still updated but because all fields are "included" it copies `passage_embedding` field value from original document.

### PR DESCRIPTION
**Pull request by gaobinlong**
### Description
This PR fixes the bug that ingest pipeline cannot be executed again when retrying the failed index requests for update_by_query and reindex, update_by_query and reindex are kind of `AbstractAsyncBulkByScrollAction`, they have retry logic when the index requests failed with 429 status code, but when build a new bulk request for retry, it doesn't honor the global pipeline specified the api request and the `isPipelineResolved` field was set to true in all of the failed indexRequests, so the pipeline won't be executed again when retrying the bulk request.

In addition, we need to find a way to mark the failure step if the BulkItemResponse, only if the ingest pipeline failed with 429 status code, then the `isPipelineResolved` field need to be reset, so I add a `source` field to the `Failure` class to mark which step has failure during the bulk processing, for other cases like the index has a `read_only_allow_delete` block which is also retryable, we shouldn't reset the  `isPipelineResolved` field.

Some unit test are added for the code change, but failed to add some yaml tests or IT because pipeline execution failure with  429 status code is not easy to mock.

### Related Issues
Resolves #14337.

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/action/bulk/Retry.java [hunk 1]
```diff
@@ -169,11 +171,24 @@ private void retry(BulkRequest bulkRequestForRetry) {
...
+            BulkRequest requestToReissue = new BulkRequest().pipeline(globalPipeline);
             int index = 0;
             for (BulkItemResponse bulkItemResponse : bulkItemResponses.getItems()) {
                 if (bulkItemResponse.isFailed()) {
-                    requestToReissue.add(currentBulkRequest.requests().get(index));
+                    DocWriteRequest<?> docWriteRequest = currentBulkRequest.requests().get(index);
+                    // when executing pipeline failed with retryable exception, the pipeline needs to be executed again
+                    if (bulkItemResponse.getFailure().getSource() == BulkItemResponse.Failure.FailureSource.PIPELINE
+                        && docWriteRequest instanceof IndexRequest indexRequest) {
+                        // after the first execution, the pipeline was set to _none, so we need to reset it
```
Comment (owaiskazi19) [inline server/src/main/java/org/opensearch/action/bulk/Retry.java:184]: We can start the comment with `Reset pipeline configuration for retry`

File: server/src/main/java/org/opensearch/action/bulk/BulkItemResponse.java [hunk 2]
```diff
@@ -197,6 +197,35 @@ public static class Failure implements Writeable, ToXContentFragment {
...
         private final long term;
         private final boolean aborted;
+        private final FailureSource source;
+
+        /**
+         * The source of the failure, denotes which step has failure during the bulk processing, only used internally.
+         */
+        @PublicApi(since = "3.0.0")
+        public enum FailureSource {
+            UNKNOWN(0),
```
Comment (owaiskazi19) [inline server/src/main/java/org/opensearch/action/bulk/BulkItemResponse.java:207]:
```suggestion
            UNKNOWN((byte) 0),
```

File: server/src/main/java/org/opensearch/action/bulk/BulkItemResponse.java [hunk 3]
```diff
@@ -197,6 +197,35 @@ public static class Failure implements Writeable, ToXContentFragment {
...
+            // Pipeline execution failure
+            PIPELINE(1);
```
Comment (owaiskazi19) [inline server/src/main/java/org/opensearch/action/bulk/BulkItemResponse.java:209]:
```suggestion
            PIPELINE((byte) 1);
```

**Review by owaiskazi19 — COMMENTED** [review]
Looks good with few minor comments

File: server/src/main/java/org/opensearch/action/bulk/Retry.java [hunk 4]
```diff
@@ -169,11 +171,24 @@ private void retry(BulkRequest bulkRequestForRetry) {
...
-            BulkRequest requestToReissue = new BulkRequest();
+            // global pipeline should be set in the new Bulk Request
+            String globalPipeline = this.currentBulkRequest.pipeline();
+            BulkRequest requestToReissue = new BulkRequest().pipeline(globalPipeline);
             int index = 0;
             for (BulkItemResponse bulkItemResponse : bulkItemResponses.getItems()) {
                 if (bulkItemResponse.isFailed()) {
-                    requestToReissue.add(currentBulkRequest.requests().get(index));
+                    DocWriteRequest<?> docWriteRequest = currentBulkRequest.requests().get(index);
+                    // when executing pipeline failed with retryable exception, the pipeline needs to be executed again
```
Comment (martin-gaievski) [inline server/src/main/java/org/opensearch/action/bulk/Retry.java:181]: how can we tell if exception is retryable or not? Is this `docWriteRequest instanceof IndexRequest indexRequest == true` condition?

Comment (martin-gaievski) [reply server/src/main/java/org/opensearch/action/bulk/Retry.java:181]: nm, we are in the retry object, this means we got 429 code

**Review by martin-gaievski — APPROVED** [review]
Looks good to me, thank you

File: server/src/main/java/org/opensearch/action/bulk/BulkItemResponse.java [hunk 5]
```diff
@@ -197,6 +197,35 @@ public static class Failure implements Writeable, ToXContentFragment {
         private final long seqNo;
         private final long term;
         private final boolean aborted;
+        private final FailureSource source;
+
+        /**
+         * The source of the failure, denotes which step has failure during the bulk processing, only used internally.
+         */
+        @PublicApi(since = "3.0.0")
```
[the remark this answers is not in the document]
Comment (owaiskazi19) [reply server/src/main/java/org/opensearch/action/bulk/BulkItemResponse.java:205]: We can keep it as internal

[the remark this answers is not in the document]
Comment (gaobinlong) [reply server/src/main/java/org/opensearch/action/bulk/BulkItemResponse.java:205]: Thanks, I tried that but it throws `FailureSource is part of the public APIs but is marked as @InternalApi`, as the outer class `Failure` and `BulkItemResponse` are both public, so mark this enum as public makes sense?

**Review by owaiskazi19 — APPROVED** [review]

**Comment by owaiskazi19** [comment]
@andrross can you also take a look here?

**Review by andrross — APPROVED** [review]
