### PR TITLE
fix simultaneously creating a snapshot and updating the repository can potentially trigger an infinite loop

### LINKED ISSUE #17531: [BUG] Simultaneously creating a snapshot and updating the repository can potentially trigger an infinite loop to snapshot creation
### Describe the bug

When I added unit test for the #17488, I found that Simultaneously creating a snapshot and updating the repository can potentially trigger an infinite loop to snapshot creation.

The reason is that when the repository is updated, `RepositoriesService` will create a new one to replace the old, and close the old one.
https://github.com/opensearch-project/OpenSearch/blob/3966ed93beb2ff13854d2a6e1ff51dfa32295830/server/src/main/java/org/opensearch/repositories/RepositoriesService.java#L493

But `creating a snapshot` still depend on the closed repository, which will trigger an infinite when `snapshot creation`.
https://github.com/opensearch-project/OpenSearch/blob/3966ed93beb2ff13854d2a6e1ff51dfa32295830/server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java#L661

The condition will always fail.
Image

https://github.com/opensearch-project/OpenSearch/blob/3966ed93beb2ff13854d2a6e1ff51dfa32295830/server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java#L682

### Related component

Storage:Snapshots

### To Reproduce

Put the unit test in `RepositoriesServiceIT`, and run it.
```
public void testSnapAndRestoreWhenChangeBytesPerSecSetting() throws ExecutionException, InterruptedException {
        // create index
        final InternalTestCluster cluster = internalCluster();
        String indexName = "test-index";
        createIndex(indexName, Settings.builder().put(SETTING_NUMBER_OF_REPLICAS, 0).put(SETTING_NUMBER_OF_SHARDS, 1).build());
        index(indexName, "_doc", "1", Collections.singletonMap("user",
            generateRandomStringArray(1, 1<<19, false, false)));
        flush(indexName);
        IndicesStatsRequest indicesStatsRequest = new IndicesStatsRequest().indices(indexName);
        long indexSize = client().admin().indices().stats(indicesStatsRequest).get().getIndex(indexName).getPrimaries().getStore().getSize().getBytes();
        System.out.println("index size: " + indexSize);

        // create repository
        final String repositoryName = "test-repo";
        //snapshot will cost about 4s
        long costSecond = indexSize/4;
        Settings.Builder repoSettings = Settings.builder().put("location", randomRepoPath()).put("max_snapshot_bytes_per_sec", (costSecond + "b")).put("max_restore_bytes_per_sec", (costSecond + "b"));
        OpenSearchIntegTestCase.putRepositoryWithNoSettingOverrides(
            client().admin().cluster(),
            repositoryName,
            FsRepository.TYPE,
            true,
            repoSettings
        );

        Thread thread = new Thread(() -> {
            String snapshotName = "test-snapshot";
            logger.info("--> starting snapshot");
            long startTime = System.currentTimeMillis();
            CreateSnapshotResponse createSnapshotResponse = client().admin()
                .cluster()
                .prepareCreateSnapshot(repositoryName, snapshotName)
                .setWaitForCompletion(false)
                .setIndices(indexName)
                .get();
            logger.info("--> finishing snapshot");

        });
        thread.start();


        logger.info("--> begin to reset repository");
        costSecond = indexSize;
        repoSettings = Settings.builder().put("location", randomRepoPath()).put("max_snapshot_bytes_per_sec", (costSecond + "b"));
        OpenSearchIntegTestCase.putRepositoryWithNoSettingOverrides(
            client().admin().cluster(),
            repositoryName,
            FsRepository.TYPE,
            true,
            repoSettings
        );
        logger.info("--> finish to reset repository");

        thread.join();
    }
```

### Expected behavior

Fix the infinite loop.

I'm trying to fix it.

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by kkewwei**
### Related Issues
Resolves #17531

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kkewwei** [comment]
> UNSTABLE



> ❕ Gradle check result for [7957cdb](https://github.com/opensearch-project/OpenSearch/commit/7957cdb1b0aa3b37d19c167fe2615be6dffa3590): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/54382/)
> 
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.action.admin.cluster.node.tasks.ResourceAwareTasksTests.testTaskResourceTrackingDuringTaskCancellation
> ```
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

ResourceAwareTasksTests.testTaskResourceTrackingDuringTaskCancellation #https://github.com/opensearch-project/OpenSearch/issues/14293

File: server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java [hunk 1]
```diff
@@ -630,21 +632,44 @@ protected void doClose() {
...
+        Consumer<Exception> onFailure
+    ) {
+        executeConsistentStateUpdate(createUpdateTask, source, () -> this, onFailure);
+    }
+
     @Override
     public void executeConsistentStateUpdate(
         Function<RepositoryData, ClusterStateUpdateTask> createUpdateTask,
         String source,
+        Supplier<Repository> currentRepositeSupplier,
```
Comment (bugmakerrrrrr) [inline server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java:657]: I don't want to change the API, I'm wondering if we can retry in `SnapshotsService`, that is, re-call the `createSnapshot` method when `startRepository != currentRepository`

Comment (kkewwei) [reply server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java:657]: It seems that there is no elegant way to exit unless the `executeConsistentStateUpdate` is modified.

**Comment by kkewwei** [comment]
> ❌ Gradle check result for [b054499](https://github.com/opensearch-project/OpenSearch/commit/b054499f8a03b03269d0c1f28fd4e88e8263ea0c): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/54552/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

S3RemoteStoreIT.testPeerRecoveryWithLowActivityTimeout #16145

File: server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java (hunk 1 above)
Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java:647]: I think you can use the `onFailure` to do retry in `SnapshotService`. When  this repo is closed, not to re-call the `executeConsistentStateUpdate ` and invoke the `onFailure`.

File: server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java [hunk 2]
```diff
@@ -643,6 +646,10 @@ public void executeConsistentStateUpdate(
         String source,
         Consumer<Exception> onFailure
     ) {
+        if (this.isOpen() == false) {
+            onFailure.accept(new RepositoryException(metadata.name(), "the repository is closed, maybe updated or deleted, please retry"));
```
Comment (bugmakerrrrrr) [inline server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java:650]: I think it's ok to throw exception here, we just need to notify the user that the repo have changed and let the user decide whether to retry or not.

File: server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java [hunk 3]
```diff
@@ -4690,6 +4697,11 @@ private void checkAborted() {
         }
     }
 
+    @Override
+    public boolean isOpen() {
```
Comment (bugmakerrrrrr) [inline server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java:4701]: I don't think we need this method, we can track the state within this class

**Comment by kkewwei** [comment]
@bugmakerrrrrr please review again in your spare time.

**Review by bugmakerrrrrr — APPROVED** [review]

**Comment by kkewwei** [comment]
@andrross, please help merge when you are free. After merged, I can continue #17488.

File: server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java [hunk 4]
```diff
@@ -122,4 +126,66 @@ public void testSystemRepositoryCantBeCreated() {
...
+                .setWaitForCompletion(true)
+                .setIndices(indexName)
+                .get();
+            logger.info("--> finishing snapshot");
+        };
+
+        // snapshot mab be failed when updating repository
+        Thread thread = new Thread(() -> {
+            try {
+                createSnapshot.run();
```
Comment (andrross) [inline server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java:167]: Is this guaranteed to fail? This thread may finish before the repository settings are updated, and you're not asserting that this actually does fail.

File: server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java [hunk 5]
```diff
@@ -643,6 +646,10 @@ public void executeConsistentStateUpdate(
         String source,
         Consumer<Exception> onFailure
     ) {
+        if (this.closed) {
```
[the remark this answers is not in the document]
Comment (kkewwei) [reply server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java:649]: The steps are as follows:

1. Initially, Thread 1 acquires the repository to create a snapshot.
2. Subsequently, Thread 2 applies commit. In the process, it closes the existing repository and then creates a new one.
3. Thread 1 then invokes the repository.executeConsistentStateUpdate method to update the repository settings.
 
To prevent the case, If we introduce write lock during phase 1, the step 2(Applying commit) will be blocked. Generally speaking, it is advisable to avoid locking during applying commit because it may potentially trigger cluster instability.

Therefore, during the snapshot creation, if we detect that the repository is closed, throwing RepositoryException to the client can be an effective approach.

File: server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java (hunk 4 above)
Comment (kkewwei) [reply server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java:167]: The steps are as follows:

1. Initially, Thread 1 acquires the repository.
2. Subsequently, Thread 2 applies commit. In the process, it closes the existing repository and then creates a new one.
3. Thread 1 then invokes the repository.executeConsistentStateUpdate method to create the snapt.


In most cases, phase3 occurs after phase2, and then an exception will be thrown, which trigger assertThat, but I cannot guarantee that phase3 will definitely occur after phase2.

So it seems ok.

File: server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (kkewwei) [reply server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java:649]: @ashking94 , please review whether my explanation addresses your question.

File: server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java (hunk 4 above)
Comment (kkewwei) [reply server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java:167]: @andrross Would you mind taking another look?

**Comment by kkewwei** [comment]
> ❌ Gradle check result for [1f76f18](https://github.com/opensearch-project/OpenSearch/commit/1f76f187d3fd261845f31640e6e023e9b4c02283): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/56157/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

RemoteStorePinnedTimestampsGarbageCollectionIT.testLiveIndexNoPinnedTimestamps #16088

**Comment by kkewwei** [comment]
> ❌ Gradle check result for [6ebee6d](https://github.com/opensearch-project/OpenSearch/commit/6ebee6db1eb4b69a9e30615a86c79119c04b7c84): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/56600/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

MinimumClusterManagerNodesIT.testThreeNodesNoClusterManagerBlock #14289
DedicatedClusterSnapshotRestoreIT.testSnapshotWithStuckNode #15806
SimpleSearchIT.testSimpleTerminateAfterTrackTotalHitsUpToSize #16851

**Comment by kkewwei** [comment]
@andrross @ashking94  I'm very sorry to mention you again. Could someone help continue to review or merge the PR? There are too many flaky tests and Gradle check always fails. 

My apologies once more, your help is greatly appreciated. I want to continue #17488, but was blocked by this PR.

File: server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java (hunk 4 above)
Comment (andrross) [reply server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java:167]: Here's my reading of the code. I'll call it "test thread" for the thread running the test method, and "async thread" for the thread in the `thread` variable created on line 165.

1. (test thread) creates a repo
2. (async thread) starts creating a snapshot
3. (test thread) calls `putRepositoryWithNoSettingOverrides` again to reset the repo
4. (test thread) creates a snapshot
5. (test thread) waits for async thread to finish

It looks to me like step 2 could actually start and finish execution anywhere from before step 3 starts or after step 4 finishes. Am I wrong about that? It looks to me like that async thread _might_ execute during the repository reset, but it might also execute entirely beforehand or entirely afterwards. So in summary it seems like you're only sometimes testing the condition that you want to test, depending on when that other actually executes.

**Comment by andrross** [comment]
> @andrross @ashking94 I'm very sorry to mention you again. Could someone help continue to review or merge the PR? There are too many flaky tests and Gradle check always fails.
> 
> Your help is greatly appreciated. I want to continue #17488, but was blocked by this PR.

Thanks for sticking with this @kkewwei. A lot of us are busy with the 3.0 release and as you've noted flaky tests are a major problem at the moment.

File: server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java (hunk 4 above)
Comment (kkewwei) [reply server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java:167]: The overall situation is as described, but there is no fourth step in my test. The test can hit the code I modified, if there are any additional test cases that should be added to ensure comprehensive testing.

**Review by andrross — APPROVED** [review]
