### PR TITLE
Fix QueueResizableOpenSearchThreadPoolExecutorTests

### LINKED ISSUE #14297: [AUTOCUT] Gradle Check Flaky Test Report for QueueResizableOpenSearchThreadPoolExecutorTests
## Flaky Test Report for `QueueResizableOpenSearchThreadPoolExecutorTests`

Noticed the `QueueResizableOpenSearchThreadPoolExecutorTests` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| 15607b1ec44a8428f66c5d26c46b35fe1fc1bc50 | [16441](https://github.com/opensearch-project/OpenSearch/pull/16441) | [50000](https://build.ci.opensearch.org/job/gradle-check/50000/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |
| 33b88a292a69eb46486b7947a079ff3652610fb7 | [18148](https://github.com/opensearch-project/OpenSearch/pull/18148) | [57419](https://build.ci.opensearch.org/job/gradle-check/57419/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |
| 435af893d14b23685aa450169626379c455d1548 | [14154](https://github.com/opensearch-project/OpenSearch/pull/14154) | [40882](https://build.ci.opensearch.org/job/gradle-check/40882/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |
| 436038d2be54df8979466841fccc6db4971bcb75 | [18041](https://github.com/opensearch-project/OpenSearch/pull/18041) | [56989](https://build.ci.opensearch.org/job/gradle-check/56989/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |
| 4c252570ada31ee0b477bb2a09fc84c081598900 | [13909](https://github.com/opensearch-project/OpenSearch/pull/13909) | [40727](https://build.ci.opensearch.org/job/gradle-check/40727/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |
| 4e45c9ed68d7a4ba77c8c3406453c05bede170e2 | [14847](https://github.com/opensearch-project/OpenSearch/pull/14847) | [43008](https://build.ci.opensearch.org/job/gradle-check/43008/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |
| 73882054afcdb74244c07c5be1f54a629ffd0bc2 | [17529](https://github.com/opensearch-project/OpenSearch/pull/17529) | [54246](https://build.ci.opensearch.org/job/gradle-check/54246/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |
| 816787d3e58d3f843207e77b6cb8eb99cd3512da | [18044](https://github.com/opensearch-project/OpenSearch/pull/18044) | [57010](https://build.ci.opensearch.org/job/gradle-check/57010/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |
| a32859bb5a5acc54b62df5384c7b7c949c647c2b | [13777](https://github.com/opensearch-project/OpenSearch/pull/13777) | [39537](https://build.ci.opensearch.org/job/gradle-check/39537/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |
| a54d46603079595aaa0bd469a21e14f85a449d2a | [15546](https://github.com/opensearch-project/OpenSearch/pull/15546) | [46041](https://build.ci.opensearch.org/job/gradle-check/46041/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |
| c987d6b7d9a3d603c09bddfe82c8995d81a7e759 | [14056](https://github.com/opensearch-project/OpenSearch/pull/14056) | [40109](https://build.ci.opensearch.org/job/gradle-check/40109/testReport/) | `org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod`<br><br>`org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `QueueResizableOpenSearchThreadPoolExecutorTests` class are:

- [14437](https://github.com/opensearch-project/OpenSearch/pull/14437)
- [14512](https://github.com/opensearch-project/OpenSearch/pull/14512)
- [13997](https://github.com/opensearch-project/OpenSearch/pull/13997)
- [14514](https://github.com/opensearch-project/OpenSearch/pull/14514)
- [15557](https://github.com/opensearch-project/OpenSearch/pull/15557)
- [17299](https://github.com/opensearch-project/OpenSearch/pull/17299)
- [12982](https://github.com/opensearch-project/OpenSearch/pull/12982)
- [13131](https://github.com/opensearch-project/OpenSearch/pull/13131)
- [13232](https://github.com/opensearch-project/OpenSearch/pull/13232)
- [13694](https://github.com/opensearch-project/OpenSearch/pull/13694)
- [13772](https://github.com/opensearch-project/OpenSearch/pull/13772)
- [13865](https://github.com/opensearch-project/OpenSearch/pull/13865)
- [13870](https://github.com/opensearch-project/OpenSearch/pull/13870)
- [13888](https://github.com/opensearch-project/OpenSearch/pull/13888)
- [13897](https://github.com/opensearch-project/OpenSearch/pull/13897)
- [13966](https://github.com/opensearch-project/OpenSearch/pull/13966)
- [14187](https://github.com/opensearch-project/OpenSearch/pull/14187)
- [14415](https://github.com/opensearch-project/OpenSearch/pull/14415)
- [14454](https://github.com/opensearch-project/OpenSearch/pull/14454)
- [14464](https://github.com/opensearch-project/OpenSearch/pull/14464)
- [14533](https://github.com/opensearch-project/OpenSearch/pull/14533)
- [14630](https://github.com/opensearch-project/OpenSearch/pull/14630)
- [14651](https://github.com/opensearch-project/OpenSearch/pull/14651)
- [14735](https://github.com/opensearch-project/OpenSearch/pull/14735)
- [14754](https://github.com/opensearch-project/OpenSearch/pull/14754)
- [14861](https://github.com/opensearch-project/OpenSearch/pull/14861)
- [14912](https://github.com/opensearch-project/OpenSearch/pull/14912)
- [14948](https://github.com/opensearch-project/OpenSearch/pull/14948)
- [14979](https://github.com/opensearch-project/OpenSearch/pull/14979)
- [14983](https://github.com/opensearch-project/OpenSearch/pull/14983)
- [14985](https://github.com/opensearch-project/OpenSearch/pull/14985)
- [15015](https://github.com/opensearch-project/OpenSearch/pull/15015)
- [15053](https://github.com/opensearch-project/OpenSearch/pull/15053)
- [15249](https://github.com/opensearch-project/OpenSearch/pull/15249)
- [15253](https://github.com/opensearch-project/OpenSearch/pull/15253)
- [15327](https://github.com/opensearch-project/OpenSearch/pull/15327)
- [15333](https://github.com/opensearch-project/OpenSearch/pull/15333)
- [15335](https://github.com/opensearch-project/OpenSearch/pull/15335)
- [15471](https://github.com/opensearch-project/OpenSearch/pull/15471)
- [15492](https://github.com/opensearch-project/OpenSearch/pull/15492)
- [15558](https://github.com/opensearch-project/OpenSearch/pull/15558)
- [15603](https://github.com/opensearch-project/OpenSearch/pull/15603)
- [15608](https://github.com/opensearch-project/OpenSearch/pull/15608)
- [15684](https://github.com/opensearch-project/OpenSearch/pull/15684)
- [15737](https://github.com/opensearch-project/OpenSearch/pull/15737)
- [15769](https://github.com/opensearch-project/OpenSearch/pull/15769)
- [15777](https://github.com/opensearch-project/OpenSearch/pull/15777)
- [16154](https://github.com/opensearch-project/OpenSearch/pull/16154)
- [16254](https://github.com/opensearch-project/OpenSearch/pull/16254)
- [16781](https://github.com/opensearch-project/OpenSearch/pull/16781)
- [16962](https://github.com/opensearch-project/OpenSearch/pull/16962)
- [17041](https://github.com/opensearch-project/OpenSearch/pull/17041)
- [17165](https://github.com/opensearch-project/OpenSearch/pull/17165)
- [17239](https://github.com/opensearch-project/OpenSearch/pull/17239)
- [17275](https://github.com/opensearch-project/OpenSearch/pull/17275)
- [17354](https://github.com/opensearch-project/OpenSearch/pull/17354)
- [17409](https://github.com/opensearch-project/OpenSearch/pull/17409)
- [17507](https://github.com/opensearch-project/OpenSearch/pull/17507)
- [17513](https://github.com/opensearch-project/OpenSearch/pull/17513)
- [17517](https://github.com/opensearch-project/OpenSearch/pull/17517)
- [17532](https://github.com/opensearch-project/OpenSearch/pull/17532)
- [17546](https://github.com/opensearch-project/OpenSearch/pull/17546)
- [17556](https://github.com/opensearch-project/OpenSearch/pull/17556)
- [17738](https://github.com/opensearch-project/OpenSearch/pull/17738)
- [17759](https://github.com/opensearch-project/OpenSearch/pull/17759)
- [17843](https://github.com/opensearch-project/OpenSearch/pull/17843)
- [17889](https://github.com/opensearch-project/OpenSearch/pull/17889)
- [17907](https://github.com/opensearch-project/OpenSearch/pull/17907)
- [17939](https://github.com/opensearch-project/OpenSearch/pull/17939)
- [17996](https://github.com/opensearch-project/OpenSearch/pull/17996)
- [18069](https://github.com/opensearch-project/OpenSearch/pull/18069)
- [18166](https://github.com/opensearch-project/OpenSearch/pull/18166)
- [18215](https://github.com/opensearch-project/OpenSearch/pull/18215)
- [18219](https://github.com/opensearch-project/OpenSearch/pull/18219)
- [18249](https://github.com/opensearch-project/OpenSearch/pull/18249)
- [18277](https://github.com/opensearch-project/OpenSearch/pull/18277)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by andrross**
There was a race condition in testResizeQueueDown() where depending on
random parameters we could submit up to 1002 tasks into an executor with
a queue size of 900. That introduced a race condition where if the tasks
didn't execute fast enough then a rejected execution exception could
happen and fail the test. The fix is to resize down to a queue size of
1500 to ensure there is enough capacity even if all tasks are submitted
before any can be executed.

And finally I refactored the tests to reduce duplication of code and
ensure the executor gets shutdown properly even in case of a test
failure. This will avoid the spurious thread leak failure if a test case
exits because of a failure.

### Related Issues
Resolves #14297

### Check List
- [x] Functionality includes testing.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by andrross** [comment]
> Separate, the testResizeQueueSameSize() was not actually resizing the queue to the same size so I fixed that.

Well, I suppose I should have tested my change first :) I guess I don't know what the intent of testResizeQueueSameSize() is because the class does not allow you to call resize and pass the same size. @reta can you help out here? In the meantime I'll just revert my change to this test case.

**Comment by reta** [comment]
> I guess I don't know what the intent of testResizeQueueSameSize() is because the class does not allow you to call resize and pass the same size.

@andrross I think the name of the method may be confusing; just looking into the test, what it does is that
1. create a pool with a queue of capacity 2000
2. resize the queue capacity to 1000 
3. submit bunch of tasks and checks that queue size it at most 1000 (the same) or less

Is it helpful?

**Comment by andrross** [comment]
> > I guess I don't know what the intent of testResizeQueueSameSize() is because the class does not allow you to call resize and pass the same size.
> 
> @andrross I think the name of the method may be confusing; just looking into the test, what it does is that
> 
>  1. create a pool with a queue of capacity 2000
>  2. resize the queue capacity to 1000
>  3. submit bunch of tasks and checks that queue size it at most 1000 (the same) or less
> 
> 
> Is it helpful?

Got it. I think we can keep the test as it is.

File: server/src/test/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutorTests.java [hunk 1]
```diff
@@ -23,14 +26,19 @@
...
+    private void createExecutor(int queueSize) {
         int threads = randomIntBetween(1, 10);
-        int measureWindow = randomIntBetween(100, 200);
-        logger.info("--> auto-queue with a measurement window of {} tasks", measureWindow);
-        QueueResizableOpenSearchThreadPoolExecutor executor = new QueueResizableOpenSearchThreadPoolExecutor(
+        measureWindow = randomIntBetween(100, 200);
+        ThreadContext context = new ThreadContext(Settings.EMPTY);
+        this.queue = new ResizableBlockingQueue<>(
+            ConcurrentCollections.newBlockingQueue(),
+            Objects.requireNonNull(queueSize, "All tests must set a queue size")
```
Comment (ashking94) [inline server/src/test/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutorTests.java:39]: Objects.requireNonNull() is designed for reference types only. For primitive data types, this check would always pass. Did you intend to do something else? may be value check?

File: server/src/test/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutorTests.java [hunk 2]
```diff
@@ -44,152 +52,67 @@ public void testResizeQueueSameSize() throws Exception {
...
         executeTask(executor, 1);
-        assertBusy(() -> { assertThat((long) executor.getTaskExecutionEWMA(), equalTo(83L)); });
-
-        executor.shutdown();
-        executor.awaitTermination(10, TimeUnit.SECONDS);
+        assertBusy(() -> assertThat((long) executor.getTaskExecutionEWMA(), equalTo(83L)));
     }
 
     /** Use a runnable wrapper that simulates a task with unknown failures. */
-    public void testExceptionThrowingTask() throws Exception {
```
Comment (ashking94) [inline server/src/test/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutorTests.java:155]: for testExceptionThrowingTask, the runnable wrapper was earlier `exceptionalWrapper()` which is changed to `fastWrapper`. What's the reason for this change?

**Review by ashking94 — DISMISSED** [review]
>There was a race condition in testResizeQueueDown() where depending on random parameters we could submit up to 1002 tasks into an executor with a queue size of 900. That introduced a race condition where if the tasks didn't execute fast enough then a rejected execution exception could happen and fail the test.

I am unable to see on what fixed this flakiness in the test testResizeQueueDown?

**Comment by andrross** [comment]
> > There was a race condition in testResizeQueueDown() where depending on random parameters we could submit up to 1002 tasks into an executor with a queue size of 900. That introduced a race condition where if the tasks didn't execute fast enough then a rejected execution exception could happen and fail the test.
> 
> I am unable to see on what fixed this flakiness in the test testResizeQueueDown?

Instead of resizing down to 900, it resizes down to 1500 which guarantees that the executor has enough capacity to not reject anything if all tasks are submitted before any are able to be executed.

File: server/src/test/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutorTests.java (hunk 1 above)
Comment (andrross) [reply server/src/test/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutorTests.java:39]: Good catch! This was leftover from a previous version of the code where it actually made sense.

File: server/src/test/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutorTests.java (hunk 2 above)
Comment (andrross) [reply server/src/test/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutorTests.java:155]: Another good catch, this got mixed up in the refactoring. I'll fix it.

**Comment by andrross** [comment]
@ashking94 Can you take another look at this? Thanks!

**Review by mch2 — APPROVED** [review]
