### PR TITLE
Fix Flaky Test RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction

### LINKED ISSUE #14304: [AUTOCUT] Gradle Check Flaky Test Report for RecoveryFromGatewayIT
## Flaky Test Report for `RecoveryFromGatewayIT`

Noticed the `RecoveryFromGatewayIT` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| 0753461986cd5746bf7b7ed2ba153cc65cea9a59 | [14775](https://github.com/opensearch-project/OpenSearch/pull/14775) | [46624](https://build.ci.opensearch.org/job/gradle-check/46624/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 0d38d1498bc6c4b87461378ce91447dca46b2b58 | [14372](https://github.com/opensearch-project/OpenSearch/pull/14372) | [41072](https://build.ci.opensearch.org/job/gradle-check/41072/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode` |
| 16782e5af0e7ab581343a8c7423bdaba49ca23ac | [15801](https://github.com/opensearch-project/OpenSearch/pull/15801) | [47488](https://build.ci.opensearch.org/job/gradle-check/47488/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 1d14569622f36fb163ee45e0e52620553a050a7d | [14360](https://github.com/opensearch-project/OpenSearch/pull/14360) | [41178](https://build.ci.opensearch.org/job/gradle-check/41178/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode` |
| 1e49aa8625d26846ee7bea663bcc1e9296eb219a | [15249](https://github.com/opensearch-project/OpenSearch/pull/15249) | [49031](https://build.ci.opensearch.org/job/gradle-check/49031/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 30edd6fbf7eaebc0c6a97f990c72a60761eab846 | [14429](https://github.com/opensearch-project/OpenSearch/pull/14429) | [41260](https://build.ci.opensearch.org/job/gradle-check/41260/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode` |
| 3681b52081fc6e2f9c158800ce5639405811d792 | [15563](https://github.com/opensearch-project/OpenSearch/pull/15563) | [46967](https://build.ci.opensearch.org/job/gradle-check/46967/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 3696c296220acf4bf0ecb1bc10cb4a71675d4939 | [16036](https://github.com/opensearch-project/OpenSearch/pull/16036) | [49037](https://build.ci.opensearch.org/job/gradle-check/49037/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 3a38a6c86e34c5abbb0eb95d919e585e2af78feb | [14365](https://github.com/opensearch-project/OpenSearch/pull/14365) | [41154](https://build.ci.opensearch.org/job/gradle-check/41154/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode` |
| 43e7597cdc5ba2c1852ec1796628f948633f0c57 | [16146](https://github.com/opensearch-project/OpenSearch/pull/16146) | [48697](https://build.ci.opensearch.org/job/gradle-check/48697/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 49d9dee25deb7217f58a000b5d99253d11785951 | [14422](https://github.com/opensearch-project/OpenSearch/pull/14422) | [41229](https://build.ci.opensearch.org/job/gradle-check/41229/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode` |
| 4c252570ada31ee0b477bb2a09fc84c081598900 | [13909](https://github.com/opensearch-project/OpenSearch/pull/13909) | [40727](https://build.ci.opensearch.org/job/gradle-check/40727/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 5642ce7b4a432e25e6d71ceab961165bcd7eaad4 | [15684](https://github.com/opensearch-project/OpenSearch/pull/15684) | [47541](https://build.ci.opensearch.org/job/gradle-check/47541/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 5cb0bad94a4dcf13aabc9c4be4ccd7f3f4da0d58 | [16117](https://github.com/opensearch-project/OpenSearch/pull/16117) | [48557](https://build.ci.opensearch.org/job/gradle-check/48557/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 625dd5a3bcd1a56d07f49492225413eae5db58fb | [15223](https://github.com/opensearch-project/OpenSearch/pull/15223) | [44496](https://build.ci.opensearch.org/job/gradle-check/44496/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 62c6d08f62309aed374ceb46d238cab52a492e0e | [15862](https://github.com/opensearch-project/OpenSearch/pull/15862) | [47647](https://build.ci.opensearch.org/job/gradle-check/47647/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 62e943c14b11750e464b61be7272da608db5e8ae | [15569](https://github.com/opensearch-project/OpenSearch/pull/15569) | [46499](https://build.ci.opensearch.org/job/gradle-check/46499/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 64e503d01010e40a2d596b9d9002aa4456b0df90 | [15740](https://github.com/opensearch-project/OpenSearch/pull/15740) | [47435](https://build.ci.opensearch.org/job/gradle-check/47435/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 66d18a4a3da4fe094f7464156e5723959b9f73c9 | [15623](https://github.com/opensearch-project/OpenSearch/pull/15623) | [46619](https://build.ci.opensearch.org/job/gradle-check/46619/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 6b5386030622790113a8da52920410a3e653dd3a | [15129](https://github.com/opensearch-project/OpenSearch/pull/15129) | [44091](https://build.ci.opensearch.org/job/gradle-check/44091/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 7dbaf25aa1b1b33b09ef0eeb4df92f41225fd0fc | [16176](https://github.com/opensearch-project/OpenSearch/pull/16176) | [48836](https://build.ci.opensearch.org/job/gradle-check/48836/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 81288b1044348d99cce6d23770755a464121f7cc | [15957](https://github.com/opensearch-project/OpenSearch/pull/15957) | [47925](https://build.ci.opensearch.org/job/gradle-check/47925/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 8b629484277b161e01fd6affc8ab7ab2f580bbeb | [13953](https://github.com/opensearch-project/OpenSearch/pull/13953) | [39797](https://build.ci.opensearch.org/job/gradle-check/39797/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 8f4b1cd4aa16b4fce26877b0e8c47a332835e0b7 | [13513](https://github.com/opensearch-project/OpenSearch/pull/13513) | [48728](https://build.ci.opensearch.org/job/gradle-check/48728/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 908fefeed32ce205e7b6128a5a344bbf333a5e62 | [15978](https://github.com/opensearch-project/OpenSearch/pull/15978) | [48742](https://build.ci.opensearch.org/job/gradle-check/48742/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| 961456180a4d1a23d74cc1e4666c4dd375121d37 | [14390](https://github.com/opensearch-project/OpenSearch/pull/14390) | [41106](https://build.ci.opensearch.org/job/gradle-check/41106/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode` |
| 9a5c7b2eae405d08c4d5d64f0fef087821c18655 | [16128](https://github.com/opensearch-project/OpenSearch/pull/16128) | [48659](https://build.ci.opensearch.org/job/gradle-check/48659/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| a2cef8fcdeeaed4ca11f6c6d69a9c9cb5cd4d2c5 | [14512](https://github.com/opensearch-project/OpenSearch/pull/14512) | [42598](https://build.ci.opensearch.org/job/gradle-check/42598/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| a2f795469b3801a782a003bdfda8ba3f43cfd516 | [14188](https://github.com/opensearch-project/OpenSearch/pull/14188) | [40726](https://build.ci.opensearch.org/job/gradle-check/40726/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| aa7cb055f229ddaf0f839cbb1c2f0178ce3d9e4d | [14111](https://github.com/opensearch-project/OpenSearch/pull/14111) | [40433](https://build.ci.opensearch.org/job/gradle-check/40433/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| b3a5f1dcbf032ca8f736a6b33a7036638068ca69 | [15666](https://github.com/opensearch-project/OpenSearch/pull/15666) | [46833](https://build.ci.opensearch.org/job/gradle-check/46833/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| c0e33279df04f02a7981327b81f39f3716dd673d | [15021](https://github.com/opensearch-project/OpenSearch/pull/15021) | [43637](https://build.ci.opensearch.org/job/gradle-check/43637/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testBatchModeEnabledWithInSufficientTimeoutButClusterGreen` |
| c19cf88d266d15d6e8c69296cd0626099e562e38 | [15010](https://github.com/opensearch-project/OpenSearch/pull/15010) | [46589](https://build.ci.opensearch.org/job/gradle-check/46589/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| e7ee950992911739eb1b079491731073ddd52e4f | [15039](https://github.com/opensearch-project/OpenSearch/pull/15039) | [43735](https://build.ci.opensearch.org/job/gradle-check/43735/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| eb1cbb807298145e40b533d35a70d3e416f7bfc3 | [15545](https://github.com/opensearch-project/OpenSearch/pull/15545) | [46601](https://build.ci.opensearch.org/job/gradle-check/46601/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| ed66587bed303a363ca21d6d1e92a81abd91800a | [15706](https://github.com/opensearch-project/OpenSearch/pull/15706) | [47047](https://build.ci.opensearch.org/job/gradle-check/47047/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |
| f99a6f8f682a79d052b68eb6610b631dd9ce0e41 | [14395](https://github.com/opensearch-project/OpenSearch/pull/14395) | [41150](https://build.ci.opensearch.org/job/gradle-check/41150/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode` |
| fcc231dfc349e092c3f68e49f49e32a062313f71 | [14739](https://github.com/opensearch-project/OpenSearch/pull/14739) | [43376](https://build.ci.opensearch.org/job/gradle-check/43376/testReport/) | `org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `RecoveryFromGatewayIT` class are:

- [14972](https://github.com/opensearch-project/OpenSearch/pull/14972)
- [13748](https://github.com/opensearch-project/OpenSearch/pull/13748)
- [14979](https://github.com/opensearch-project/OpenSearch/pull/14979)
- [14339](https://github.com/opensearch-project/OpenSearch/pull/14339)
- [13865](https://github.com/opensearch-project/OpenSearch/pull/13865)
- [13703](https://github.com/opensearch-project/OpenSearch/pull/13703)
- [13897](https://github.com/opensearch-project/OpenSearch/pull/13897)
- [14383](https://github.com/opensearch-project/OpenSearch/pull/14383)
- [14409](https://github.com/opensearch-project/OpenSearch/pull/14409)
- [14817](https://github.com/opensearch-project/OpenSearch/pull/14817)
- [15077](https://github.com/opensearch-project/OpenSearch/pull/15077)
- [14348](https://github.com/opensearch-project/OpenSearch/pull/14348)
- [14374](https://github.com/opensearch-project/OpenSearch/pull/14374)
- [14394](https://github.com/opensearch-project/OpenSearch/pull/14394)
- [14415](https://github.com/opensearch-project/OpenSearch/pull/14415)
- [14421](https://github.com/opensearch-project/OpenSearch/pull/14421)
- [14809](https://github.com/opensearch-project/OpenSearch/pull/14809)
- [15513](https://github.com/opensearch-project/OpenSearch/pull/15513)
- [15521](https://github.com/opensearch-project/OpenSearch/pull/15521)
- [16040](https://github.com/opensearch-project/OpenSearch/pull/16040)
- [16254](https://github.com/opensearch-project/OpenSearch/pull/16254)
- [12782](https://github.com/opensearch-project/OpenSearch/pull/12782)
- [13304](https://github.com/opensearch-project/OpenSearch/pull/13304)
- [13684](https://github.com/opensearch-project/OpenSearch/pull/13684)
- [13694](https://github.com/opensearch-project/OpenSearch/pull/13694)
- [13719](https://github.com/opensearch-project/OpenSearch/pull/13719)
- [13760](https://github.com/opensearch-project/OpenSearch/pull/13760)
- [13772](https://github.com/opensearch-project/OpenSearch/pull/13772)
- [13788](https://github.com/opensearch-project/OpenSearch/pull/13788)
- [13793](https://github.com/opensearch-project/OpenSearch/pull/13793)
- [13801](https://github.com/opensearch-project/OpenSearch/pull/13801)
- [13843](https://github.com/opensearch-project/OpenSearch/pull/13843)
- [13896](https://github.com/opensearch-project/OpenSearch/pull/13896)
- [13914](https://github.com/opensearch-project/OpenSearch/pull/13914)
- [13920](https://github.com/opensearch-project/OpenSearch/pull/13920)
- [13934](https://github.com/opensearch-project/OpenSearch/pull/13934)
- [13986](https://github.com/opensearch-project/OpenSearch/pull/13986)
- [13988](https://github.com/opensearch-project/OpenSearch/pull/13988)
- [14027](https://github.com/opensearch-project/OpenSearch/pull/14027)
- [14089](https://github.com/opensearch-project/OpenSearch/pull/14089)
- [14135](https://github.com/opensearch-project/OpenSearch/pull/14135)
- [14167](https://github.com/opensearch-project/OpenSearch/pull/14167)
- [14182](https://github.com/opensearch-project/OpenSearch/pull/14182)
- [14214](https://github.com/opensearch-project/OpenSearch/pull/14214)
- [14221](https://github.com/opensearch-project/OpenSearch/pull/14221)
- [14274](https://github.com/opensearch-project/OpenSearch/pull/14274)
- [14333](https://github.com/opensearch-project/OpenSearch/pull/14333)
- [14335](https://github.com/opensearch-project/OpenSearch/pull/14335)
- [14338](https://github.com/opensearch-project/OpenSearch/pull/14338)
- [14345](https://github.com/opensearch-project/OpenSearch/pull/14345)
- [14362](https://github.com/opensearch-project/OpenSearch/pull/14362)
- [14371](https://github.com/opensearch-project/OpenSearch/pull/14371)
- [14378](https://github.com/opensearch-project/OpenSearch/pull/14378)
- [14380](https://github.com/opensearch-project/OpenSearch/pull/14380)
- [14398](https://github.com/opensearch-project/OpenSearch/pull/14398)
- [14402](https://github.com/opensearch-project/OpenSearch/pull/14402)
- [14412](https://github.com/opensearch-project/OpenSearch/pull/14412)
- [14416](https://github.com/opensearch-project/OpenSearch/pull/14416)
- [14433](https://github.com/opensearch-project/OpenSearch/pull/14433)
- [14436](https://github.com/opensearch-project/OpenSearch/pull/14436)
- [14445](https://github.com/opensearch-project/OpenSearch/pull/14445)
- [14464](https://github.com/opensearch-project/OpenSearch/pull/14464)
- [14485](https://github.com/opensearch-project/OpenSearch/pull/14485)
- [14488](https://github.com/opensearch-project/OpenSearch/pull/14488)
- [14489](https://github.com/opensearch-project/OpenSearch/pull/14489)
- [14514](https://github.com/opensearch-project/OpenSearch/pull/14514)
- [14529](https://github.com/opensearch-project/OpenSearch/pull/14529)
- [14533](https://github.com/opensearch-project/OpenSearch/pull/14533)
- [14562](https://github.com/opensearch-project/OpenSearch/pull/14562)
- [14595](https://github.com/opensearch-project/OpenSearch/pull/14595)
- [14605](https://github.com/opensearch-project/OpenSearch/pull/14605)
- [14693](https://github.com/opensearch-project/OpenSearch/pull/14693)
- [14718](https://github.com/opensearch-project/OpenSearch/pull/14718)
- [14735](https://github.com/opensearch-project/OpenSearch/pull/14735)
- [14811](https://github.com/opensearch-project/OpenSearch/pull/14811)
- [14848](https://github.com/opensearch-project/OpenSearch/pull/14848)
- [14854](https://github.com/opensearch-project/OpenSearch/pull/14854)
- [14896](https://github.com/opensearch-project/OpenSearch/pull/14896)
- [14912](https://github.com/opensearch-project/OpenSearch/pull/14912)
- [14930](https://github.com/opensearch-project/OpenSearch/pull/14930)
- [14955](https://github.com/opensearch-project/OpenSearch/pull/14955)
- [15017](https://github.com/opensearch-project/OpenSearch/pull/15017)
- [15031](https://github.com/opensearch-project/OpenSearch/pull/15031)
- [15267](https://github.com/opensearch-project/OpenSearch/pull/15267)
- [15274](https://github.com/opensearch-project/OpenSearch/pull/15274)
- [15281](https://github.com/opensearch-project/OpenSearch/pull/15281)
- [15328](https://github.com/opensearch-project/OpenSearch/pull/15328)
- [15349](https://github.com/opensearch-project/OpenSearch/pull/15349)
- [15352](https://github.com/opensearch-project/OpenSearch/pull/15352)
- [15353](https://github.com/opensearch-project/OpenSearch/pull/15353)
- [15370](https://github.com/opensearch-project/OpenSearch/pull/15370)
- [15372](https://github.com/opensearch-project/OpenSearch/pull/15372)
- [15412](https://github.com/opensearch-project/OpenSearch/pull/15412)
- [15418](https://github.com/opensearch-project/OpenSearch/pull/15418)
- [15488](https://github.com/opensearch-project/OpenSearch/pull/15488)
- [15501](https://github.com/opensearch-project/OpenSearch/pull/15501)
- [15508](https://github.com/opensearch-project/OpenSearch/pull/15508)
- [15509](https://github.com/opensearch-project/OpenSearch/pull/15509)
- [15535](https://github.com/opensearch-project/OpenSearch/pull/15535)
- [15575](https://github.com/opensearch-project/OpenSearch/pull/15575)
- [15578](https://github.com/opensearch-project/OpenSearch/pull/15578)
- [15613](https://github.com/opensearch-project/OpenSearch/pull/15613)
- [15634](https://github.com/opensearch-project/OpenSearch/pull/15634)
- [15644](https://github.com/opensearch-project/OpenSearch/pull/15644)
- [15646](https://github.com/opensearch-project/OpenSearch/pull/15646)
- [15651](https://github.com/opensearch-project/OpenSearch/pull/15651)
- [15662](https://github.com/opensearch-project/OpenSearch/pull/15662)
- [15664](https://github.com/opensearch-project/OpenSearch/pull/15664)
- [15677](https://github.com/opensearch-project/OpenSearch/pull/15677)
- [15678](https://github.com/opensearch-project/OpenSearch/pull/15678)
- [15681](https://github.com/opensearch-project/OpenSearch/pull/15681)
- [15749](https://github.com/opensearch-project/OpenSearch/pull/15749)
- [15777](https://github.com/opensearch-project/OpenSearch/pull/15777)
- [15778](https://github.com/opensearch-project/OpenSearch/pull/15778)
- [15784](https://github.com/opensearch-project/OpenSearch/pull/15784)
- [15786](https://github.com/opensearch-project/OpenSearch/pull/15786)
- [15800](https://github.com/opensearch-project/OpenSearch/pull/15800)
- [15854](https://github.com/opensearch-project/OpenSearch/pull/15854)
- [15860](https://github.com/opensearch-project/OpenSearch/pull/15860)
- [15906](https://github.com/opensearch-project/OpenSearch/pull/15906)
- [15915](https://github.com/opensearch-project/OpenSearch/pull/15915)
- [15916](https://github.com/opensearch-project/OpenSearch/pull/15916)
- [15938](https://github.com/opensearch-project/OpenSearch/pull/15938)
- [15943](https://github.com/opensearch-project/OpenSearch/pull/15943)
- [15955](https://github.com/opensearch-project/OpenSearch/pull/15955)
- [15988](https://github.com/opensearch-project/OpenSearch/pull/15988)
- [15999](https://github.com/opensearch-project/OpenSearch/pull/15999)
- [16073](https://github.com/opensearch-project/OpenSearch/pull/16073)
- [16098](https://github.com/opensearch-project/OpenSearch/pull/16098)
- [16135](https://github.com/opensearch-project/OpenSearch/pull/16135)
- [16155](https://github.com/opensearch-project/OpenSearch/pull/16155)
- [16158](https://github.com/opensearch-project/OpenSearch/pull/16158)
- [16211](https://github.com/opensearch-project/OpenSearch/pull/16211)
- [7771](https://github.com/opensearch-project/OpenSearch/pull/7771)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by kkewwei**
### Description
In RecoveryFromGatewayIT test, the created indices may be not started yet, but is used immediately, which will cause unexpected exception. when it throws the exception, the scene is as follows:
img_v3_02f3_5a00dfcc-7a54-4a19-a23d-eb24554f53cg

### Related Issues
Resolves #14304

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by harshavamsi — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java [hunk 1]
```diff
@@ -1366,7 +1366,8 @@ public void testSingleShardStoreFetchUsingBatchAction() throws ExecutionExceptio
         DiscoveryNode[] nodes = getDiscoveryNodes();
         TransportNodesListShardStoreMetadataBatch.NodesStoreFilesMetadataBatch response = prepareAndSendRequest(
             new String[] { indexName },
-            nodes
+            nodes,
+            false
```
Comment (gaobinlong) [inline server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:1370]: Could you explain why this case doesn't need the index to be green?

Comment (kkewwei) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:1370]: I have tested that if we don't define the number of nodes in the cluster, there will be one data node by default. The created index has 1 replicas, so it will never be green.

Comment (gaobinlong) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:1370]: Thanks. Please merge the latest code of main branch and make sure the gradle checks can pass.

**Comment by kkewwei** [comment]
@gaobinlong it's ok now, please have a look.

**Review by gaobinlong — APPROVED** [review]
