### PR TITLE
Fix flaky test in RemoteStoreMigrationSettingsUpdateIT

### LINKED ISSUE #15810: [AUTOCUT] Gradle Check Flaky Test Report for RemoteStoreMigrationSettingsUpdateIT
## Flaky Test Report for `RemoteStoreMigrationSettingsUpdateIT`

Noticed the `RemoteStoreMigrationSettingsUpdateIT` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| 245fa4703d1b61bfa07f881e82d2ff9ac8a2e064 | [15664](https://github.com/opensearch-project/OpenSearch/pull/15664) | [47327](https://build.ci.opensearch.org/job/gradle-check/47327/testReport/) | `org.opensearch.remotemigration.RemoteStoreMigrationSettingsUpdateIT.testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode` |
| 3c6019dfca1e89bde6d82eb7d366621245defb86 | [15558](https://github.com/opensearch-project/OpenSearch/pull/15558) | [47413](https://build.ci.opensearch.org/job/gradle-check/47413/testReport/) | `org.opensearch.remotemigration.RemoteStoreMigrationSettingsUpdateIT.testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode` |
| 6f45a74765ecc77fcaed85721f6067a292e21162 | [15772](https://github.com/opensearch-project/OpenSearch/pull/15772) | [47395](https://build.ci.opensearch.org/job/gradle-check/47395/testReport/) | `org.opensearch.remotemigration.RemoteStoreMigrationSettingsUpdateIT.testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode` |
| 89915b65dc51126189dd42d74c82d2cbac0cb154 | [15492](https://github.com/opensearch-project/OpenSearch/pull/15492) | [47471](https://build.ci.opensearch.org/job/gradle-check/47471/testReport/) | `org.opensearch.remotemigration.RemoteStoreMigrationSettingsUpdateIT.testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode` |
| 8f34ce5ca3849687d509205bfe4378e1183eb6fb | [15077](https://github.com/opensearch-project/OpenSearch/pull/15077) | [47341](https://build.ci.opensearch.org/job/gradle-check/47341/testReport/) | `org.opensearch.remotemigration.RemoteStoreMigrationSettingsUpdateIT.testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode` |
| debd04008b56f9f7e54f1d9380dff869d6d81141 | [15524](https://github.com/opensearch-project/OpenSearch/pull/15524) | [47397](https://build.ci.opensearch.org/job/gradle-check/47397/testReport/) | `org.opensearch.remotemigration.RemoteStoreMigrationSettingsUpdateIT.testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode` |
| f5c897cf1db3d413c6ccd9bcad1284a7873a1556 | [15705](https://github.com/opensearch-project/OpenSearch/pull/15705) | [47338](https://build.ci.opensearch.org/job/gradle-check/47338/testReport/) | `org.opensearch.remotemigration.RemoteStoreMigrationSettingsUpdateIT.testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `RemoteStoreMigrationSettingsUpdateIT` class are:

- [15330](https://github.com/opensearch-project/OpenSearch/pull/15330)
- [15758](https://github.com/opensearch-project/OpenSearch/pull/15758)
- [14631](https://github.com/opensearch-project/OpenSearch/pull/14631)
- [15557](https://github.com/opensearch-project/OpenSearch/pull/15557)
- [15656](https://github.com/opensearch-project/OpenSearch/pull/15656)
- [15145](https://github.com/opensearch-project/OpenSearch/pull/15145)
- [15424](https://github.com/opensearch-project/OpenSearch/pull/15424)
- [15580](https://github.com/opensearch-project/OpenSearch/pull/15580)
- [15759](https://github.com/opensearch-project/OpenSearch/pull/15759)
- [14993](https://github.com/opensearch-project/OpenSearch/pull/14993)
- [15766](https://github.com/opensearch-project/OpenSearch/pull/15766)
- [15777](https://github.com/opensearch-project/OpenSearch/pull/15777)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by ashking94**
### Description
This PR fixes the failing test testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode. The fix has been achieved by adding the SNAPSHOT_SHARD_PATH_PREFIX_SETTING to the docrep node as well.

### Related Issues
Resolves #15810 

### Check List
- [x] Functionality includes testing.
- ~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java [hunk 1]
```diff
@@ -68,15 +69,17 @@ public void testNewIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode()
...
 
-    @AwaitsFix(bugUrl = "https://github.com/opensearch-project/OpenSearch/issues/15793")
     public void testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode() throws Exception {
         logger.info("Initialize cluster: gives non remote cluster manager");
         initializeCluster(false);
 
         logger.info("Add remote and non-remote nodes");
         setClusterMode(MIXED.mode);
         addRemote = false;
-        String nonRemoteNodeName = internalCluster().startNode();
```
Comment (gbbafna) [inline server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java:79]: do we need this at other places involving `startNode` as well ?

Comment (gbbafna) [reply server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java:79]: Wondering why there are not failing .

Comment (ashking94) [reply server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java:79]: Only this test involves taking snapshot and restoring it for mixed mode operations.

**Review by gbbafna — APPROVED** [review]
