### PR TITLE
Fix sync method to account for block files in Composite Directory

### LINKED ISSUE #18657: [BUG] Writable Warm - Composite Directory sync() method doesn't take into account block files
### Describe the bug

Currently in composite directory, in the [sync() method](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/store/CompositeDirectory.java#L249) we filter out the files that hare present in Remote and then delegate the sync() call to localDirectory with the filtered set of files. But there can arise cases where the file is present in blocks instead of a full file and that results in a `NoSuchFileException` for the localDirectory sync() call.

Example stacktrace below:

```
2025-06-04T13:21:03,574][ERROR][o.o.i.r.PeerRecoveryTargetService] [c2af93180a503303bf0aa093eb62a955] Exception while downloading segment files from remote store, will continue with peer to peer segment copy
[test_idxx/1010101T7R9GrsTUi9RjDhMmAcPg][[test_idxx][1]] IndexShardRecoveryException[Exception while copying segment files from remote segment store]; nested: NoSuchFileException[/<path>/var/es/data/nodes/0/indices/1010101T7R9GrsTUi9RjDhMmAcPg/1/index/_o_Lucene90_0.dvd];
	at org.opensearch.index.shard.IndexShard.syncSegmentsFromRemoteSegmentStore(IndexShard.java:5294)
	at org.opensearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:256)
	at org.opensearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:626)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.nio.file.NoSuchFileException: /<path>/var/es/data/nodes/0/indices/1010101T7R9GrsTUi9RjDhMmAcPg/1/index/_o_Lucene90_0.dvd
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:224)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:369)
	at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:465)
	at org.apache.lucene.store.FSDirectory.fsync(FSDirectory.java:303)
	at org.apache.lucene.store.FSDirectory.sync(FSDirectory.java:255)
	at org.opensearch.index.store.CompositeDirectory.sync(CompositeDirectory.java:233)
	at org.apache.lucene.store.FilterDirectory.sync(FilterDirectory.java:86)
	at org.apache.lucene.store.FilterDirectory.sync(FilterDirectory.java:86)
	at org.opensearch.index.store.Store.commitSegmentInfos(Store.java:905)
	at org.opensearch.index.shard.IndexShard.syncSegmentsFromRemoteSegmentStore(IndexShard.java:5290)
	... 7 more
```

### Related component

Storage:Remote

### To Reproduce

Run ingestion for some prolonged time.

### Expected behavior

Composite Directory should be able to handle sync for block files as well.

### Additional Details

N/A

### PR DESCRIPTION
**Pull request by rayshrey**
### Description
Fix sync method to account for block files in Composite Directory

### Related Issues
Resolves #18657 

### Check List
- [x] Functionality includes testing.
- [ ] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/store/CompositeDirectory.java [hunk 1]
```diff
@@ -105,6 +106,24 @@ protected List<String> listBlockFiles(String fileName) throws IOException {
...
+     * @param fileNames The set of files to search for, along with its associated block files.
+     * @return A list of file names, including the original file (if present) and all its block files.
+     * @throws IOException in case of I/O error while listing files.
+     */
+    protected List<String> listBlockFiles(String[] fileNames) throws IOException {
+        Set<String> files = Set.of(fileNames);
+        return Stream.of(listLocalFiles())
+            .filter(
+                file -> files.contains(file)
+                    || (isBlockFile(file) && files.contains(file.substring(0, file.indexOf(BLOCK_FILE_IDENTIFIER))))
```
Comment (skumawat2025) [inline server/src/main/java/org/opensearch/index/store/CompositeDirectory.java]: Can we re-use `listBlockFiles(String fileName)` here?

File: server/src/main/java/org/opensearch/index/store/CompositeDirectory.java [hunk 2]
```diff
@@ -105,6 +106,24 @@ protected List<String> listBlockFiles(String fileName) throws IOException {
...
+            )
+            .collect(Collectors.toList());
+    }
+
     /**
      * Returns names of all files stored in this directory in sorted order
      * Does not include locally stored block files (having _block_ in their names) and files pending deletion
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/store/CompositeDirectory.java]: need to change this as well ?

File: server/src/main/java/org/opensearch/index/store/CompositeDirectory.java (hunk 1 above)
Comment (rayshrey) [reply server/src/main/java/org/opensearch/index/store/CompositeDirectory.java]: listBlockFiles returns all the block files for a specific file, but here we are just checking if a block/full file is present in the directory or not.

File: server/src/main/java/org/opensearch/index/store/CompositeDirectory.java [hunk 3]
```diff
@@ -249,8 +268,15 @@ public IndexOutput createOutput(String name, IOContext context) throws IOExcepti
     public void sync(Collection<String> names) throws IOException {
         ensureOpen();
         logger.trace("Composite Directory[{}]: sync() called {}", this::toString, () -> names);
-        Collection<String> remoteFiles = Arrays.asList(getRemoteFiles());
-        Collection<String> filesToSync = names.stream().filter(name -> remoteFiles.contains(name) == false).collect(Collectors.toList());
+        Set<String> remoteFiles = Set.of(getRemoteFiles());
+        Set<String> localFiles = Arrays.stream(listLocalFiles())
+            .map(file -> isBlockFile(file) ? file.substring(0, file.indexOf(BLOCK_FILE_IDENTIFIER)) : file)
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/store/CompositeDirectory.java]: would the block files already present in `remoteFiles` ?
