### PR TITLE
Fix race with eviction when reading from FileCache

### LINKED ISSUE #6536: [BUG] [Searchable Snapshot] Index input clone races with close on cache eviction
From https://github.com/opensearch-project/OpenSearch/issues/6295#issuecomment-1453240299

Adding the following unit test to [TransferManagerTests](https://github.com/opensearch-project/OpenSearch/blob/23ee1415f20ad07b0139ac14b6a805b34f569a63/server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java) will reliably reproduce the error:

```java
public void testFetchBlobWithConcurrentCacheEvictions() throws Exception {
    final ExecutorService testRunner = Executors.newFixedThreadPool(16);
    final AtomicReference<Boolean> pruneThreadStop = new AtomicReference<>(false);
    try {
        // Kick of a thread to aggressively prune the cache, which evicts entries with
        // a zero reference count even if the cache is not at capacity
        testRunner.submit(() -> {
            while (pruneThreadStop.get() == false) {
                this.fileCache.prune();
                Thread.yield();
            }
        });

        final List<Future<?>> futures = new ArrayList<>();
        for (int i = 0; i < 128; i++) {
            // request an index input and immediately close it
            futures.add(testRunner.submit(() -> {
                try {
                    this.fetchBlob().close();
                } catch (Exception e) {
                    throw new AssertionError(e);
                }
            }));
        }
        // Wait for all threads to complete
        for (Future<?> future : futures) {
            future.get(1, TimeUnit.SECONDS);
        }
    } finally {
        pruneThreadStop.set(true);
        terminate(testRunner);
    }
}
```

### PR DESCRIPTION
**Pull request by andrross**
The previous implementation had an inherent race condition where a zero-reference count IndexInput read from the cache could be evicted before the IndexInput was cloned (and therefore had its reference count incremented). Since the IndexInputs are stateful this is very bad. The least-recently-used semantics meant that in a properly-configured system this would be unlikely since accessing a zero-reference count item would move it to be most-recently used and therefore least likely to be evicted. However, there was still a latent bug that was possible to encounter (see issue #6295).

The only way to fix this, as far as I can see, is to change the cache behavior so that fetching an item from the cache atomically increments its reference count. This also led to a change to TransferManager to ensure that all requests for an item ultimately read through the cache to eliminate any possibility of a race. I have implement some concurrent unit tests that put the cache into a worst-case thrashing scenario to ensure that concurrent access never closes an IndexInput while it is still being used.

### Issues Resolved
Closes #6536

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java [hunk 1]
```diff
@@ -81,20 +74,38 @@ private IndexInput fetchOriginBlob(BlobFetchRequest blobFetchRequest) throws IOE
...
 
-        if (Objects.isNull(origin)) {
-            // origin is not in file cache, download origin
-
-            // open new origin
-            IndexInput downloaded = downloadBlockLocally(blobFetchRequest);
-
-            // refcount = 0 at the beginning
-            FileCachedIndexInput newOrigin = new FileCachedIndexInput(fileCache, blobFetchRequest.getFilePath(), downloaded);
+        if (origin == null) {
```
[the remark this answers is not in the document]
Comment (kotwanikunal) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:77]: We do not keep the `IndexInput` open always. In case of cache restore, we insert a `ClosedIndexInput` instance which just has the length of the index input to keep track of capacity. We surely do need a mechanism to keep track of `isClosed` mechanism if the file hasn't been completely eliminated from local disk.

[the remark this answers is not in the document]
Comment (reta) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:77]: >  We surely do need a mechanism to keep track of isClosed mechanism if the file hasn't been completely eliminated from local disk.

Correct, those should be removed, right? And `computeIfAbsent` would work as expected

File: server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java [hunk 2]
```diff
@@ -137,9 +136,7 @@ public V get(K key) {
                 return null;
             }
             // hit
-            if (node.evictable()) {
-                lru.moveToBack(node);
-            }
+            incRef(key);
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java:139]: I might be missing something here but if we `incRef` on every get and put, wouldn't it mess with the logic of making the node evictable - since every clone operation originally increased the ref?

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (kotwanikunal) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:77]: Is your suggestion on the lines of - 

```
// Do download/network fetches with this block
IndexInput origin = fileCache.computeIfAbsent(key, (key) -> downloadBlockLocally(...));
// Once we have the block, either downloaded or on disk, do the following?
if (cachedIndexInput.isClosed()) {
}

```

[the remark this answers is not in the document]
Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:77]: > > We surely do need a mechanism to keep track of isClosed mechanism if the file hasn't been completely eliminated from local disk.
> 
> Correct, those should be removed, right? And `computeIfAbsent` would work as expected

@reta We still need to handle the closed IndexInput case. On startup, we populate the cache with placeholder IndexInput entries and defer creating the real IndexInput entry that actually opens a handle to the file on disk until it is actually needed to be used.

File: server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java (hunk 2 above)
Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java:139]: The logic is now like this:

- get from cache (ref count = 1)
- create clone (ref count = 2)
- dec ref (ref count = 1)
- return clone
...
- clone is closed (ref count = 0)


Previously it was:

- get from cache (ref count = 0)
- __!!!!!!!!!!!!!!!!! potential race with eviction !!!!!!!!!!!!!!__
- create clone (ref count = 1)
- return clone
...
- clone is closed (ref count = 0)

Comment (kotwanikunal) [reply server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java:139]: Ahh. I misread the function name, I thought `put` also did an `incRef` but it was `computeIfPresent`. This makes sense.

Comment (kotwanikunal) [reply server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java:139]: Sorry. I reread. GH diff is hard. :( 
What about the `put`s - I think there is also `incRef` in there

File: server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java [hunk 3]
```diff
@@ -52,21 +51,17 @@ public long capacity() {
...
-    }
-
-    @Override
-    public CachedIndexInput computeIfPresent(
+    public CachedIndexInput compute(
         Path key,
         BiFunction<? super Path, ? super CachedIndexInput, ? extends CachedIndexInput> remappingFunction
     ) {
-        return theCache.computeIfPresent(key, remappingFunction);
+        return theCache.compute(key, remappingFunction);
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java:64]: Looks pretty clean to me @andrross

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java [hunk 4]
```diff
@@ -48,53 +45,46 @@ public TransferManager(final BlobContainer blobContainer, final FileCache fileCa
...
-     * not already cached. This instance must be cloned before using. This method is
-     * accessed through the ConcurrentInvocationLinearizer so read-check-write is
-     * acceptable here
-     */
-    private IndexInput fetchOriginBlob(BlobFetchRequest blobFetchRequest) throws IOException {
-        // check if the origin is already in block cache
-        IndexInput origin = fileCache.computeIfPresent(blobFetchRequest.getFilePath(), (path, cachedIndexInput) -> {
-            if (cachedIndexInput.isClosed()) {
-                // if it's already in the file cache, but closed, open it and replace the original one
+        final IndexInput origin = fileCache.compute(key, (path, cachedIndexInput) -> {
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:51]: Look much cleaner to me, thanks @andrross !

Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java:51]: Thank you! This approach seems kind of obvious in hindsight. This is why code reviews are good :)

**Comment by andrross** [comment]
Another failure of #6531

**Comment by andrross** [comment]
More SegmentReplicationRelocationIT failures...

**Review by kotwanikunal — APPROVED** [review]

**Comment by kotwanikunal** [comment]
Whitesource issue unrelated to the PR changes. Raised a PR for the fix - https://github.com/opensearch-project/OpenSearch/pull/6629

File: server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java [hunk 5]
```diff
@@ -263,30 +206,12 @@ public void remove(K key) {
...
-                    activeUsage -= node.weight;
-                }
-                usage -= node.weight;
-                if (node.evictable()) {
-                    lru.remove(node);
-                }
-                statsCounter.recordRemoval(node.weight);
-                listener.onRemoval(new RemovalNotification<>(node.key, node.value, RemovalReason.EXPLICIT));
-            }
+            removeNode(key);
```
Comment (skumawat2025) [inline server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java:209]: Hi @andrross I have one question here. 

The `RefCountedCache` interface states that remove function will remove the key entry from the cache regardless of its refCount. 
```
/**
     * Discards any cached value for key {@code key}, regardless of reference count.
 */
    void remove(K key);
 ```
 
 Here we are calling removeNode(key) which will only remove the entry when ref is 0. Is this intentional or a possible bug? We might need to change this behaviour or the documentation.

Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java:209]: Hmm, I don't quite follow. `removeNode(key)` will unconditionally remove the entry here:

https://github.com/opensearch-project/OpenSearch/blob/b8c78196438897132f6819460ebb7d4222b39297/server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java#L356

Maybe write a unit test that exposes the bug you're seeing? Please do open a new issue if you think there's a problem.

Comment (skumawat2025) [reply server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java:209]: OK! Got it now. Sorry for the confusion!.
