### PR TITLE
Fix auto date histogram rounding assertion bug

### LINKED ISSUE #16932: [BUG] auto_date_histogram query with time_zone can throw AssertionError
### Describe the bug

Running an `auto_date_histogram` query with `time_zone` can sometimes cause the cluster to crash with an AssertionError. 

I don't think AssertionErrors crash clusters running on a tar install, but the stacktrace seems to show the error comes from checking the doc's timestamp is within certain bounds. So it still might indicate there's a problem with the query results. 

The error doesn't happen if `time_zone` is absent since the error comes from code handling time zone lookup. It seems like the presence/value of `buckets` doesn't matter. 

It seems like this only happens if I index the documents one by one (using opensearchpy). If I bulk index the same number of docs through opensearchpy, I don't see the error. I believe this is why I haven't seen this error when running benchmarks like nyc_taxis which use nearly identical queries. 

When indexing one-by-one, if I refresh after each document, or if I manually refresh once at the very end, I've always seen the error. If I don't refresh at all, it succeeds (and there are nonzero doc counts in the returned buckets, so it's not that the docs aren't searched). If I refresh after bulk indexing, it still succeeds. 

[auto_date_histogram_tz_stacktrace.txt](https://github.com/user-attachments/files/18294142/auto_date_histogram_tz_stacktrace.txt)

Python script to set up an index that causes the error (.txt format as github doesn't support .py): 
[repro_autodatehisto_crash.txt](https://github.com/user-attachments/files/18294302/repro_autodatehisto_crash.txt)

### Related component

Search

### To Reproduce

Start the cluster with `./gradlew run` 

Add some docs to an index with mapping: 
```
"mappings": {
            "properties": {
            "day":    { "type" : "date", "format":"yyyy-MM-dd HH:mm:ss" } 
            }
        }
```
(I used the script attached in the bug description). 
I've seen this crash using any number of docs between 50 and 2000 when indexing one at a time. 

Run the query: `curl -XGET http://localhost:9200/jan-index/_search -H 'Content-Type: application/json' -d'{"size": 0,"aggs": {"agg_name": {"auto_date_histogram": {"field": "day", "time_zone":"America/New_York"}}}}'`

See the cluster crash with an AssertionError. 

### Expected behavior

No error should be thrown. 

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by finnegancarroll**
### Description

The auto date histogram agg contains an optimization which skips traditional doc collection and instead examines the "pre-aggregated" doc counts contained in the BKD tree of each segment. Several conditions need to be true before this optimization can execute for a given segment. One such condition is we must be able to determine a set of ranges (or rounding) for the segment under consideration before optimizing.

Normally ranges for the auto date histogram aggregation are updated as needed over the course of collecting documents but the filter rewrite optimization will [update](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java#L193) the `preparedRounding` of the agg in accordance with the min & max values of the segment under consideration ahead of time since it skips regular doc collection.

As a result, it is possible for our `preparedRounding` to shrink as the rounding built from the segment could easily be smaller than the rounding previously used by our shard level aggregator.

This usually does not pose a problem as the `preparedRounding` will be [updated accordingly](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java#L406) when we collect our next document, or reduce our shard level aggs into a single top level agg.

The specific case where this becomes problematic is when our `preparedRounding` is delegating to a "bounded" structure. When we prepare a rounding we do so for the min & max epoch time of our shard since this allows us to optimize the structure we delegate rounding to. 

For some ranges of epoch time and time zones rounding will be little more than a modulo operation. However if our min & max epoch time crosses "transitions" such as daylight savings we may want to delegate rounding to a linked list or array structure to quickly lookup these transitions. This is why the specific occurrence of this bug linked in the initial issue only appears when `"time_zone":"America/New_York"`.

The combination of delegating rounding to these strictly bounded structures and the filter rewrite optimization "replaying" our previous bucket keys fails an assertion within our `preparedRounding` as our previous bucket keys are not guaranteed to fit within the strict bounds of the rounding prepared for the current segment being collected.

The changes in this PR resolve this by ensuring the filter rewrite optimization only ever increases the granularity of our `preparedRounding`.

### Related Issues
Resolves #16932

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by finnegancarroll** [comment]
@bowenlan-amzn can you take a look when you have a chance? Thank you!

File: server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java [hunk 1]
```diff
@@ -190,6 +201,8 @@ protected Rounding getRounding(final long low, final long high) {
                     roundingIdx++;
                 }
 
+                // Ensure preparedRounding never shrinks
+                roundingIdx = Math.max(prevRoundingIdx, roundingIdx);
```
Comment (bowenlan-amzn) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java:205]: If the roundingIdx is smaller than prevRoundingIdx, seems we can save a call to `prepareRounding(roundingIdx)`

**Comment by bowenlan-amzn** [comment]
> The combination of delegating rounding to these strictly bounded structures and the filter rewrite optimization "replaying" our previous bucket keys fails an assertion within our preparedRounding as our previous bucket keys are not guaranteed to fit within the strict bounds of the rounding prepared for the current segment being collected.

A little more explaination on the root cause

https://github.com/opensearch-project/OpenSearch/blob/1e49aa8625d26846ee7bea663bcc1e9296eb219a/server/src/main/java/org/opensearch/common/Rounding.java#L577

For different date unit, the boundary of the prepared rounding is different. For example, for date unit of `month` the min lookup will minus millis of a month, but for `second`, min lookup only need to minus 1000.
So if we shrink the prepared rounding from month to second, the min lookup actually increase and not able to cover previous rounded value, and this failes an assertion.

**Comment by finnegancarroll** [comment]
> The block of timezone is inside getInterval
> 
> https://github.com/opensearch-project/OpenSearch/blob/1e49aa8625d26846ee7bea663bcc1e9296eb219a/server/src/main/java/org/opensearch/common/Rounding.java#L1385-L1388

Ah, I didn't realize we already disallow non UTC timezones. It makes sense we may not want to support this optimization for non UTC in general as this could produce intervals which are not of fixed size.

> I recommend we add a simple timezone check right before
> 
> https://github.com/opensearch-project/OpenSearch/blob/ef87b397e3c4d9571e6a29a96e438c3e006a0ea7/server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/DateHistogramAggregatorBridge.java#L67-L68

I've added this check to `canOptimize()`. I was thinking this would be slightly more convenient since we already have the `ValuesSourceConfig` to access the timezone and it's the earliest we can disable the optimization path. Please lmk what you think of this.

File: server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java (hunk 1 above)
Comment (finnegancarroll) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java:205]: Added a small check here to avoid this extra call if `roundingIdx` is unchanged.

**Comment by finnegancarroll** [comment]
> The block of timezone is inside getInterval
> 
> https://github.com/opensearch-project/OpenSearch/blob/1e49aa8625d26846ee7bea663bcc1e9296eb219a/server/src/main/java/org/opensearch/common/Rounding.java#L1385-L1388

Not that we disallow non UTC timezones from the start for this optimization i've added an additional change to remove this check from `getInterval()`. My thought is the check is now redundant and `Rounding.java` should not be aware of specific conditions for the filter rewrite optimization.

**Comment by finnegancarroll** [comment]
@jainankitk can you take a look when you have a chance? Thanks!

**Comment by bowenlan-amzn** [comment]
Hard to describe my suggest change, so I create a commit, please take a look.
https://github.com/opensearch-project/OpenSearch/commit/ac0faa9cdf2021032c9d1aa18700f574e1325565

**Comment by bowenlan-amzn** [comment]
Another thing I'm wondering is why we cannot support timezone in this optimization.

When timezone is there, the aggregation default method first converts the date values to local value, do the rounding, then convert it back to UTC
We can imagine with DST, for a daily aggregation, some day may have 23 hours, some day may have 25 hours

To support that in our optimization, we should figure out the right ranges for certain timezone and represent in UTC, then use these ranges to intersect the index structure of date field which saves UTC values.

**Comment by finnegancarroll** [comment]
> Hard to describe my suggest change, so I create a commit, please take a look.

I see what you mean this is much cleaner. Cherry picked this commit.

File: server/src/main/java/org/opensearch/common/Rounding.java [hunk 2]
```diff
@@ -489,7 +489,7 @@ public double roundingSize(long utcMillis, DateTimeUnit timeUnit) {
      *
      * @opensearch.internal
      */
-    static class TimeUnitRounding extends Rounding {
+    public static class TimeUnitRounding extends Rounding {
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/common/Rounding.java:492]: This is not needed

File: server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java [hunk 3]
```diff
@@ -190,7 +201,12 @@ protected Rounding getRounding(final long low, final long high) {
                     roundingIdx++;
                 }
 
-                preparedRounding = prepareRounding(roundingIdx);
+                // Ensure preparedRounding never shrinks
+                roundingIdx = Math.max(prevRoundingIdx, roundingIdx);
+                if (roundingIdx != prevRoundingIdx) {
+                    preparedRounding = prepareRounding(roundingIdx);
+                }
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java:208]: slightly more readable?
```
if (roundingIdx > prevRoundingIdx) {
    roundingIdx = prevRoundingIdx;
    preparedRounding = prepareRounding(roundingIdx);
}
```

File: server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java [hunk 4]
```diff
@@ -403,12 +419,39 @@ private void collectValue(int doc, long rounded) throws IOException {
...
+                     * DAYS_OF_MONTH rounding where the maximum inner interval is 7 days (i.e. 1 week buckets).
+                     * targetBuckets * roundingInfos[roundingIdx].getMaximumInnerInterval() would then be the number of
+                     * 1 day buckets possible such that if we re-bucket to 1 week buckets we will have more 1 week buckets
+                     * than our targetBuckets limit. If the current count of buckets exceeds this limit we must update
+                     * our rounding.
+                     *
+                     * 2. [targetBuckets * roundingInfos[roundingIdx].getMaximumRoughEstimateDurationMillis()]
+                     * The total duration of ms covered by our current rounding. In the case of MINUTES_OF_HOUR rounding
+                     * getMaximumRoughEstimateDurationMillis is 60000. If our current total range in millis (max - min)
+                     * exceeds this range we must update our rounding.
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java:453]: Thank you for adding details documentation!

**Comment by jainankitk** [comment]
> Another thing I'm wondering is why we cannot support timezone in this optimization.

I agree with @bowenlan-amzn. We should try to support the optimization with timezones as well to have wider coverage. @bowenlan-amzn - Can you please create issue for same?

File: server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java (hunk 3 above)
Comment (finnegancarroll) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java]: You're right that's cleaner. Thanks!
`roundingIdx = prevRoundingIdx;` is not needed I think.

**Comment by finnegancarroll** [comment]
{"run-benchmark-test": "id_5"}

File: server/src/main/java/org/opensearch/common/Rounding.java [hunk 5]
```diff
@@ -1412,7 +1419,5 @@ public static OptionalLong getInterval(Rounding rounding) {
      * Helper function for checking if the time zone requested for date histogram
      * aggregation is utc or not
      */
-    private static boolean isUTCTimeZone(final ZoneId zoneId) {
-        return "Z".equals(zoneId.getDisplayName(TextStyle.FULL, Locale.ENGLISH));
-    }
+    public abstract boolean isUTC();
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/common/Rounding.java:1422]: I am wondering if this will break the backward compat check for 2.x? Probably not used as much outside of core

**Review by jainankitk — APPROVED** [review]

**Comment by jainankitk** [comment]
Retrying "Gradle Assemble / assemble (21, macos-13) (pull_request)"

File: server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java (hunk 3 above)
Comment (jainankitk) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java]: Oh yeah, `prevRoundingIdx` was never changing. `roundingIdx = prevRoundingIdx;` was a mistake by me.

**Comment by rishabh6788** [comment]
@finnegancarroll @jainankitk asc sort, range and keyword-in-range queries seem to have regressed.

**Comment by finnegancarroll** [comment]
> @finnegancarroll @jainankitk asc sort, range and keyword-in-range queries seem to have regressed.

I think I ran the wrong workload here. This PR should have been id_15 since that's the lucene 10 snapshot and baseline is main.

**Comment by rishabh6788** [comment]
The local benchmark doesn't replicate this behavior, could be a one-off bad run. Submitting one more confirm.

**Comment by rishabh6788** [comment]
{"run-benchmark-test": "id_5"}

**Comment by rishabh6788** [comment]
results look fine now. 
updated the snapshot as well.
