### PR TITLE
Increase suite timeout for HighlighterSearchIT

### LINKED ISSUE #12119: [BUG] org.opensearch.search.fetch.subphase.highlight.HighlighterSearchIT.testBoostingQueryTermVector is flaky
### Describe the bug

https://build.ci.opensearch.org/job/gradle-check/32933/testReport/junit/org.opensearch.search.fetch.subphase.highlight/HighlighterSearchIT/testBoostingQueryTermVector__p0___search_concurrent_segment_search_enabled___true___/

Error Message
java.lang.Exception: Test abandoned because suite timeout was reached.
Stacktrace
java.lang.Exception: Test abandoned because suite timeout was reached.
	at __randomizedtesting.SeedInfo.seed([FD0BF0F6E14F1BF1]:0)

### Related component

Search

### To Reproduce

Tried run this test 500 times, all passed. So using this issue to track for now.

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.fetch.subphase.highlight.HighlighterSearchIT" -Dtests.method="testBoostingQueryTermVector {p0={"search.concurrent_segment_search.enabled":"true"}}" -Dtests.seed=FD0BF0F6E14F1BF1 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-KW -Dtests.timezone=Pacific/Enderbury -Druntime.java=21

### Expected behavior

This test should always pass. But seems there's a slight chance of failing somehow.

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by jed326**
### Description
Increase suite timeout as parameterization has doubled the number of tests being run.

From the cases where the test does time out the non-concurrent search case is taking ~14 minutes, so bumping the timeout up to 35 to be safe. 
Ref: https://github.com/opensearch-project/OpenSearch/issues/12119#issuecomment-1973937864

### Related Issues
Resolves #12119

### Check List
~- [x] New functionality includes testing.~
  - [x] All tests pass
~- [x] New functionality has been documented.~
~- [x] New functionality has javadoc added~
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
~- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))!~
~- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
@peternied @reta could you help review? Thanks!

File: server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java [hunk 1]
```diff
@@ -127,6 +129,7 @@
 import static org.hamcrest.Matchers.not;
 import static org.hamcrest.Matchers.startsWith;
 
+@TimeoutSuite(millis = 35 * TimeUnits.MINUTE)
```
Comment (peternied) [inline server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java:132]: This seems like a really long time.  Is there any insight you can provide for why it should take this long?

**Review by peternied — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java (hunk 1 above)
Comment (jed326) [reply server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java:132]: I think this is mostly a function of how many tests are squeezed into this 1 class.
The suite has ~90 tests, which turns into ~180 when parameterized with concurrent search. Looking at the logs for several of the failures ([ref](https://github.com/opensearch-project/OpenSearch/issues/12119#issuecomment-1922017503)), we see that the first pass (either concurrent search disabled or enabled) takes around 14 minutes, which averages out to ~10 seconds per test. The is corroborated by the [junit report](https://build.ci.opensearch.org/job/gradle-check/32902/testReport/junit/org.opensearch.search.fetch.subphase.highlight/HighlighterSearchIT/) as well.

Looking at what the tests are actually doing, most of them are actually creating an index and then indexing docs and then searching instead of re-using indices across tests, so 10 seconds per test does not seem unreasonable to me.

**Comment by jed326** [comment]
https://build.ci.opensearch.org/job/gradle-check/34314/
- https://github.com/opensearch-project/OpenSearch/issues/12197

**Comment by reta** [comment]
> @peternied @reta could you help review? Thanks!

@jed326 my apologies , I am on vacation till the end of next week

File: server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java (hunk 1 above)
Comment (kkmr) [reply server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java:132]: Please add that comment to the code, so the context is preserved

**Review by kkmr — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java (hunk 1 above)
Comment (jed326) [reply server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java:133]: Added a comment and a link to the GitHub issue
