### PR TITLE
Fix SimpleNestedExplainIT.testExplainMultipleDocs flakiness

### LINKED ISSUE #12318: [BUG] org.opensearch.search.nested.SimpleNestedExplainIT.testExplainMultipleDocs is flaky
### Describe the bug

The test case `org.opensearch.search.nested.SimpleNestedExplainIT.testExplainMultipleDocs` is flaky:

```
org.opensearch.search.nested.SimpleNestedExplainIT.testExplainMultipleDocs


java.lang.AssertionError: expected:<0.36464313 = Score based on 2 child docs in range from 0 to 1, using score mode Total
  0.18232156 = weight(nested1.n_field1:n_value1 in 0) [PerFieldSimilarity], result of:
    0.18232156 = score(freq=1.0), computed as boost * idf * tf from:
      2.2 = boost
      0.18232156 = idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:
        2 = n, number of documents containing term
        2 = N, total number of documents with field
      0.45454544 = tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:
        1.0 = freq, occurrences of term within document
        1.2 = k1, term saturation parameter
        0.75 = b, length normalization parameter
        1.0 = dl, length of field
        1.0 = avgdl, average length of field
> but was:<0.36464313 = Score based on 2 child docs in range from 14 to 15, using score mode Total
  0.18232156 = weight(nested1.n_field1:n_value1 in 14) [PerFieldSimilarity], result of:
    0.18232156 = score(freq=1.0), computed as boost * idf * tf from:
      2.2 = boost
      0.18232156 = idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:
        2 = n, number of documents containing term
        2 = N, total number of documents with field
      0.45454544 = tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:
        1.0 = freq, occurrences of term within document
        1.2 = k1, term saturation parameter
        0.75 = b, length normalization parameter
        1.0 = dl, length of field
        1.0 = avgdl, average length of field
>
```

### Related component

Search

### To Reproduce

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.nested.SimpleNestedExplainIT.testExplainMultipleDocs" -Dtests.seed=52C9CA95BCB30A28 
```

### Expected behavior

The test must always pass

### Additional Details

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/33757/testReport/junit/org.opensearch.search.nested/SimpleNestedExplainIT/testExplainMultipleDocs/

### PR DESCRIPTION
**Pull request by neetikasinghal**
### Description
The explain itself is coming from Lucene: https://github.com/apache/lucene/blob/a6f70ad2bb0b682eb65feb522358ee6d16cad766/lucene/join/src/java/org/apache/lucene/search/join/ToParentBlockJoinQuery.java#L432-L440

Here's some info on the docIds in lucene:
- A DocId in lucene is not actually unique to the Index but is unique to a Segment. Lucene does this mainly to optimize writing and compression. Since it is only unique to a Segment, how can a Doc be uniquely identified at the Index level? The solution is simple. The segments are ordered. To take a simple example, an Index has two segments and each segment has 100 docs respectively. The DocId's in the Segment are 0-100 but when they are converted to the Index level, the range of the DocId's in the second Segment is converted to 100-200.

- DocId's are unique within a Segment, numbered progressively from zero. But this does not mean that the DocId's are continuous. When a Doc is deleted, there is a gap.

- The DocId corresponding to a document can change, usually when Segments are merged.

The test fails on the validation of range of the docIds in the assertion, the range changes as with indexRandomForMultipleSlices function there are several bogus documents ingested and deleted which could trigger background merges and cause the range of the docIds matched with the search query to change.

One of the solutions is to not the delete the bogus documents as part of the indexRandomForMultipleSlices, perform search for concurrent search and non-concurrent search and delete the bogus docs at the end. This is done as part of this PR.

Validated the success of the tests for 500 times.

Relates: #11681

### Related Issues
Resolves #12318

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by neetikasinghal** [comment]
@reta @jed326 please review

**Comment by jed326** [comment]
FYI I think the "resolves" issue is wrong:
- https://github.com/opensearch-project/OpenSearch/pull/12605

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java [hunk 1]
```diff
@@ -111,5 +114,7 @@ public void testExplainMultipleDocs() throws Exception {
             .prepareUpdateSettings()
             .setPersistentSettings(Settings.builder().putNull(CLUSTER_CONCURRENT_SEGMENT_SEARCH_SETTING.getKey()).build())
             .get();
+
+        deleteBogusDocs(bogusIds);
```
Comment (jed326) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java:118]: Is this actually needed? It doesn't look like this index is used anywhere else.

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java [hunk 2]
```diff
@@ -1574,13 +1574,29 @@ public void indexRandom(boolean forceRefresh, boolean dummyDocuments, boolean ma
...
      * are formed. This is useful for testing with the concurrent search use-case as it creates
-     * multiple slices based on segment count.
-     * @param indices         the indices in which bogus documents should be ingested
+     * multiple slices based on segment count. When calling this method with value of toDeleteBogusDocs
+     * as true, don't forget to call deleteBogusDocs at the end of the test to delete the bogus docs
+     * @param toDeleteBogusDocs  provides an option to delete the bogus docs optionally
+     * @param indices            the indices in which bogus documents should be ingested
      * */
-    protected void indexRandomForMultipleSlices(String... indices) throws InterruptedException {
+    protected Set<List<String>> indexRandomForMultipleSlices(boolean toDeleteBogusDocs, String... indices) throws InterruptedException {
```
Comment (jed326) [inline test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1599]: If there are multiple indices how do we map the `bogusIds` to a given index as `Set` is an unordered collection?

**Review by jed326 — COMMENTED** [review]
Perhaps I do not understand the problem correctly, but If the issue here is background merges are happening between the concurrent and non-concurrent search queries, would a simpler solution be to add a small sleep after indexing is completed so we wait for background merges to complete before we perform the search request?
Or we could even force merge to 2 segments ourselves?

It seems like making deletion of bogus docs optional is a pretty heavy duty solution to what seems like a pretty simple problem.

**Comment by neetikasinghal** [comment]
> add a small sleep after indexing is completed so we wait for background merges to complete before we perform the search request?
> Or we could even force merge to 2 segments ourselves?

@jed326 I thought the same, but looks like even a sleep time of 5 seconds or force merge (which defeats the purpose of indexing multiple docs)doesn't guarantee for successful runs of the tests. 

Hence, I came up with this approach of not deleting the bogus docs before the search.

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java (hunk 1 above)
Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java:118]: this is to avoid bogus docs affecting the search for the other tests added in the class as the cluster will be shared.

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java (hunk 2 above)
Comment (neetikasinghal) [reply test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1599]: the map of an index to bogus id doesnt matter, as bogus ids set would be returned for all the indices passed in the function call and deletion will be done for the same set of bogus ids (which will be bogus doc for all the indices)

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java [hunk 3]
```diff
@@ -1574,13 +1574,29 @@ public void indexRandom(boolean forceRefresh, boolean dummyDocuments, boolean ma
         }
     }
 
+    /*
+     * This method deletes the given bogus documents
+     * @param bogusIds doc ids to be deleted
+     */
+    protected void deleteBogusDocs(Set<List<String>> bogusIds) {
```
Comment (neetikasinghal) [inline test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1581]: this function needs to have some validation checks like bogus docs exists or not, will update this

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java (hunk 1 above)
Comment (jed326) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java:118]: I get that suite scope is the default but there's no other tests in this class and `setupSuiteScopeCluster` is not used to create the indices so it doesn't seem like they're meant to be shared across tests.

**Comment by jed326** [comment]
> Hence, I came up with this approach of not deleting the bogus docs before the search.

Instead of adding bogus docs could we just add more "real" docs instead?

**Comment by neetikasinghal** [comment]
> > Hence, I came up with this approach of not deleting the bogus docs before the search.
> 
> Instead of adding bogus docs could we just add more "real" docs instead?

I think it would be same as calling indexRandomForSlices function with deletion of bogus docs set to false, which is currently happening. This would cause code duplication.

**Comment by jed326** [comment]
> I think it would be same as calling indexRandomForSlices function with deletion of bogus docs set to false,

This would ingest bogus docs while what I was suggesting is modify the test to ingest more (looks like only 1 more would be needed?) non-bogus docs.

Overall it feels like not deleting bogus docs is a sledgehammer solution approach here that I don't think is generically useful for other tests so in my opinion it looks like a better solution to modify the singular test that is flaky.

**Comment by neetikasinghal** [comment]
> > I think it would be same as calling indexRandomForSlices function with deletion of bogus docs set to false,
> 
> This would ingest bogus docs while what I was suggesting is modify the test to ingest more (looks like only 1 more would be needed?) non-bogus docs.
> 
> Overall it feels like not deleting bogus docs is a sledgehammer solution approach here that I don't think is generically useful for other tests so in my opinion it looks like a better solution to modify the singular test that is flaky.

ok, so I modified the change to ingest one more doc and just have one shard for this test class such that multiple slices are created and there is no need to call the indexRandomForMultipleSlices for this test. As you said, we can also avoid the modification of the function as well. @jed326 thanks for your feedback.

**Review by jed326 — APPROVED** [review]
Awesome, I think this is a much more straightforward solution. Thanks!

**Comment by neetikasinghal** [comment]
@reta could u also take a look and merge if it looks good to you?

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java [hunk 4]
```diff
@@ -70,7 +75,23 @@ public void testExplainMultipleDocs() throws Exception {
             .setRefreshPolicy(IMMEDIATE)
             .get();
 
-        indexRandomForMultipleSlices("test");
+        client().prepareIndex("test")
```
Comment (reta) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java:78]: @neetikasinghal apologies if that was asked, but why we need this doc? It is not searched against ...

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java [hunk 5]
```diff
@@ -30,6 +30,11 @@
  */
 public class SimpleNestedExplainIT extends OpenSearchIntegTestCase {
 
+    @Override
+    protected int numberOfShards() {
+        return 1;
+    }
+
```
Comment (jed326) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java:37]: I actually wonder if this change by itself is enough to stabilize the tests. We can still use `indexRandomForMultipleSlices("test")` but hopefully the docs won't get spread across multiple shards in that case then.

Comment (reta) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java:37]: Yeah, 👍 to this

Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java:37]: this change should be enough to stabilize the tests. We dont need to call the `indexRandomForMultipleSlices` as the sole purpose of that function is to create multiple slice which is happening by ingesting two docs.

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java (hunk 4 above)
Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java:78]: this is to ensure that 2 slices get created for concurrent search path to kick in and avoid the `indexRandomForMultipleSlices ` as that has deletion of bogus docs that messes up with the range in the explanation of the search results.

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java (hunk 5 above)
Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java:37]: also there is no deletion of docs done here so it should stabilize the flakiness of the range seen in the tests.

Comment (reta) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java:37]: ah, that's right, nonetheless method is called `indexXxx`, there are deletes as well

**Review by reta — APPROVED** [review]

**Review by dblock — APPROVED** [review]
