### PR TITLE
Remove clone holder and add Cleaner logic to clean up clones in FullFileCachedIndexInput

### LINKED ISSUE #18659: [BUG] Writable Warm - FullFileCachedIndexInput Clone map can cause memory explosion
### Describe the bug

The current implementation of FullFileCachedIndexInput [maintain a set of all clones](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/store/remote/filecache/FullFileCachedIndexInput.java#L32) generated from an IndexInput
These clones get cleaned up only when their parent IndexInput gets closed.

When the base parent IndexInput is not closed, it results in all the clones being still open and having their entries in the clone set.

The size of the set grows too large and contributes significantly to memory overhead.

### Related component

Storage:Remote

### To Reproduce

Run update test procedure for `nyc_taxis` workload.and monitor heap usage (it will keep on increasing)

### Expected behavior

Clones should get cleaned up as soon as they become unreferenced.

### Additional Details

Heap dump analysis showing FullFileCachedIndexInput objects as the main contributor to memory.

Image

---

Image

---

### PR DESCRIPTION
**Pull request by rayshrey**
### Description
Remove clone holder and add Cleaner logic to clean up clones in FullFileCachedIndexInput

### Related Issues
Resolves #18659 

### Check List
- [x] Functionality includes testing.
- [ ] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/store/remote/filecache/FullFileCachedIndexInput.java [hunk 1]
```diff
@@ -88,21 +87,37 @@ public void close() throws IOException {
...
+            this.indexInput = indexInput;
+            this.isClone = isClone;
+            this.cache = cache;
+            this.path = path;
+        }
+
+        @Override
+        public void run() {
+            try {
+                indexInput.close();
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/store/remote/filecache/FullFileCachedIndexInput.java:116]: would this automatically do `decRef`  ?

Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/store/remote/filecache/FullFileCachedIndexInput.java:116]: Oh now i get it . It is `underlyingIndexInput` only and not `FullFileCachedIndexInput`.
