### PR TITLE
Fix SimpleNestedIT.testExplain flaky test

### LINKED ISSUE #11413: [BUG] org.opensearch.search.nested.SimpleNestedIT.testExplain is flaky
**Describe the bug**
The test case `org.opensearch.search.nested.SimpleNestedIT.testExplain {p0={"search.concurrent_segment_search.enabled":"true"}}` is flaky

```
java.lang.AssertionError: 
Expected: a string starting with "0.36464313 = Score based on 2 child docs in range from 0 to 1"
     but: was "0.36464313 = Score based on 2 child docs in range from 12 to 13, using score mode Total
  0.18232156 = weight(nested1.n_field1:n_value1 in 12) [PerFieldSimilarity], result of:
    0.18232156 = score(freq=1.0), computed as boost * idf * tf from:
      2.2 = boost
      0.18232156 = idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:
        2 = n, number of documents containing term
        2 = N, total number of documents with field
      0.45454544 = tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:
        1.0 = freq, occurrences of term within document
        1.2 = k1, term saturation parameter
        0.75 = b, length normalization parameter
        1.0 = dl, length of field
        1.0 = avgdl, average length of field
"
```

```
java.lang.AssertionError: 
Expected: a string starting with "0.36464313 = Score based on 2 child docs in range from 0 to 1"
     but: was "0.36464313 = Score based on 2 child docs in range from 12 to 13, using score mode Total
  0.18232156 = weight(nested1.n_field1:n_value1 in 12) [PerFieldSimilarity], result of:
    0.18232156 = score(freq=1.0), computed as boost * idf * tf from:
      2.2 = boost
      0.18232156 = idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:
        2 = n, number of documents containing term
        2 = N, total number of documents with field
      0.45454544 = tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:
        1.0 = freq, occurrences of term within document
        1.2 = k1, term saturation parameter
        0.75 = b, length normalization parameter
        1.0 = dl, length of field
        1.0 = avgdl, average length of field
"
	at __randomizedtesting.SeedInfo.seed([A16D8358F150F61C:1799CEB9DDFB0C53]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.search.nested.SimpleNestedIT.testExplain(SimpleNestedIT.java:500)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**To Reproduce**
```
/gradlew ':server:internalClusterTest' --tests "org.opensearch.search.nested.SimpleNestedIT" -Dtests.method="testExplain {p0={"search.concurrent_segment_search.enabled":"true"}}" -Dtests.seed=A16D8358F150F61C 
```

**Expected behavior**
The test must always pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI
 - 
**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/30636/testReport/junit/org.opensearch.search.nested/SimpleNestedIT/testExplain__p0___search_concurrent_segment_search_enabled___true___/

### PR DESCRIPTION
**Pull request by neetikasinghal**
### Description
The explain itself is coming from Lucene: https://github.com/apache/lucene/blob/a6f70ad2bb0b682eb65feb522358ee6d16cad766/lucene/join/src/java/org/apache/lucene/search/join/ToParentBlockJoinQuery.java#L432-L440

Here's some info on the docIds in lucene:
- A DocId in lucene is not actually unique to the Index but is unique to a Segment. Lucene does this mainly to optimize writing and compression. Since it is only unique to a Segment, how can a Doc be uniquely identified at the Index level? The solution is simple. The segments are ordered. To take a simple example, an Index has two segments and each segment has 100 docs respectively. The DocId's in the Segment are 0-100 but when they are converted to the Index level, the range of the DocId's in the second Segment is converted to 100-200.

- DocId's are unique within a Segment, numbered progressively from zero. But this does not mean that the DocId's are continuous. When a Doc is deleted, there is a gap.

- The DocId corresponding to a document can change, usually when Segments are merged.

The test fails on the validation of range of the docIds in the assertion, the range changes as with indexRandomForConcurrentSearch function there are several bogus documents ingested and deleted which could trigger background merges and cause the range of the docIds matched with the search query to change.

One of the solutions is to call refresh after indexing the actual document which would create a new segment for the actual document and prevent it to be merged with the bogus documents, this is done as part of this PR.

### Related Issues
Resolves #11413

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by neetikasinghal** [comment]
@sohami @jed326 please review

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java [hunk 1]
```diff
@@ -497,7 +497,13 @@ public void testExplain() throws Exception {
...
         Explanation explanation = searchResponse.getHits().getHits()[0].getExplanation();
         assertThat(explanation.getValue(), equalTo(searchResponse.getHits().getHits()[0].getScore()));
-        assertThat(explanation.toString(), startsWith("0.36464313 = Score based on 2 child docs in range from 0 to 1"));
+        // Concurrent search will have deleted doc count, hence the assertion string will be different
+        // ref: https://github.com/opensearch-project/OpenSearch/issues/11413
+        if (isConcurrentSearchEnabled()) {
+            assertThat(explanation.toString(), startsWith("0.36464313 = Score based on 2 child docs in range"));
+        } else {
+            assertThat(explanation.toString(), startsWith("0.36464313 = Score based on 2 child docs in range from 0 to 1"));
+        }
```
Comment (jed326) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:506]: Do we really need to check the range in the non-concurrent case? And if not we also don't need the `isConcurrentSearchEnabled` logic then?

If we do need to check the range then shouldn't we do it for the concurrent search case as well? Not sure if it's possible to calculate it based on the number of randomly ingested + deleted docs.

Comment (sohami) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:506]: Lets have 2 separate test cases: one with deleted docs and other without deleted docs. Then in both the tests the explain output should probably be same and assertions will be same for both concurrent and non-concurrent path.

Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java]: updated the PR by introducing three different test cases: 
- single doc indexed with no deleted docs by removing indexRandomForConcuurentSearch (assertion for explain API remains same in this case)
- multiple docs indexed with no deleted docs (assertion for explain API changes in this case)
- single doc indexed with deleted docs by adding indexRandomForConcuurentSearch (assertion for explain API changes in this case)

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java [hunk 2]
```diff
@@ -500,6 +500,98 @@ public void testExplain() throws Exception {
...
+
+        SearchResponse searchResponse = client().prepareSearch("test")
+            .setQuery(nestedQuery("nested1", termQuery("nested1.n_field1", "n_value1"), ScoreMode.Total))
+            .setExplain(true)
+            .get();
+        assertNoFailures(searchResponse);
+        assertThat(searchResponse.getHits().getTotalHits().value, equalTo(1L));
+        Explanation explanation = searchResponse.getHits().getHits()[0].getExplanation();
+        assertThat(explanation.getValue(), equalTo(searchResponse.getHits().getHits()[0].getScore()));
+        assertThat(explanation.toString(), startsWith("0.36464313 = Score based on 2 child docs in range"));
```
Comment (sohami) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:592]: Is there no difference in explain string with and without deleted docs ?

Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:592]: yes, there is no other difference apart from the range.

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java [hunk 3]
```diff
@@ -500,6 +499,98 @@ public void testExplain() throws Exception {
...
+        );
+
+        ensureGreen();
+
+        for (int i = 0; i < 5; i++) {
+            client().prepareIndex("test")
+                .setId(String.valueOf(i))
+                .setSource(
+                    jsonBuilder().startObject()
+                        .field("field" + i, "value" + i)
```
Comment (jed326) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:522]: nit: shouldn't only the value change change in the loop?

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java [hunk 4]
```diff
@@ -500,6 +499,98 @@ public void testExplain() throws Exception {
...
+
+        SearchResponse searchResponse = client().prepareSearch("test")
+            .setQuery(nestedQuery("nested1", termQuery("nested1.n_field1", "n_value1"), ScoreMode.Total))
+            .setExplain(true)
+            .get();
+        assertNoFailures(searchResponse);
+        assertThat(searchResponse.getHits().getTotalHits().value, equalTo(1L));
+        Explanation explanation = searchResponse.getHits().getHits()[0].getExplanation();
+        assertThat(explanation.getValue(), equalTo(searchResponse.getHits().getHits()[0].getScore()));
+        assertThat(explanation.toString(), startsWith("0.36464313 = Score based on 2 child docs in range"));
```
Comment (jed326) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:545]: This may be slightly outside of the scope of this test but just thinking out loud -- If we know the number of deleted docs is it possible to also know the specific range?

**Review by jed326 — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java (hunk 4 above)
Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:545]: Not sure on how to calculate range on deleted doc count basis, from the code it doesnt really look that we can directly calculate range from deleted doc count: https://github.com/apache/lucene/blob/a6f70ad2bb0b682eb65feb522358ee6d16cad766/lucene/join/src/java/org/apache/lucene/search/join/ToParentBlockJoinQuery.java#L402


To make the difference significant in the tests, I have added a separate assertion for range for `testExplainSingleDocIndexingNoDeletedDoc` which is non-existent in the other tests for explain.

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java (hunk 3 above)
Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:529]: updated the mappings above to make it clearer.

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java [hunk 5]
```diff
@@ -487,6 +487,105 @@ public void testExplain() throws Exception {
...
+                    .field("n_field1", "n_value1")
+                    .endObject()
+                    .endArray()
+                    .endObject()
+            )
+            .setRefreshPolicy(IMMEDIATE)
+            .get();
+
+        // this will lead to deleted docs
         indexRandomForConcurrentSearch("test");
```
Comment (sohami) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:589]: I think we should use `indexRandomForMultipleSlices` instead here to add deleted docs even in non-concurrent search path. That way test will be validating explain output for deleted docs for both concurrent/non-concurrent flow.

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java [hunk 6]
```diff
@@ -487,6 +487,105 @@ public void testExplain() throws Exception {
...
+
+        SearchResponse searchResponse = client().prepareSearch("test")
+            .setQuery(nestedQuery("nested1", termQuery("nested1.n_field1", "n_value1"), ScoreMode.Total))
+            .setExplain(true)
+            .get();
+        assertNoFailures(searchResponse);
+        assertThat(searchResponse.getHits().getTotalHits().value, equalTo(1L));
+        Explanation explanation = searchResponse.getHits().getHits()[0].getExplanation();
+        assertThat(explanation.getValue(), equalTo(searchResponse.getHits().getHits()[0].getScore()));
+        assertThat(explanation.toString(), startsWith("0.36464313 = Score based on 2 child docs"));
```
Comment (sohami) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:552]: Can we understand why range is changing with multiple docs even when data is constant. And can't we know the range before hand to add in assertion here ?

Also in deleted docs case, given the deleted docs are some garbage docs why is it affecting the explain output ?

Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:552]: @sohami I did some investigation and found out that the range specifies the docIds of the child docs in the explain output. DocIds are loaded from the scoreDocs of the topDocs [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/SearchService.java#L1469).

After that, during the execute of the FetchPhase, call comes to the [ExplainPhase](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/fetch/subphase/ExplainPhase.java#L64) that passes docId to the explain function in lucene.
So, as an example say a document with doc Id 83 matches with the query passed, and there are 2 child docs that are part of the parent doc matching the query, the explain API will output contain `Score based on 2 child docs in range from 81 to 82, using score mode Total`.

In case of concurrent search case, since we are indexing so many documents, the docId is varying and hence the explain output contains the range for different numbers. Hope that answers your question.

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java (hunk 5 above)
Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:589]: As explained below, I don't think we need 3 different test cases, we can keep one test case as before and add `indexRandomForMultipleSlices` and remove the validation for the range as that can vary.

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java [hunk 7]
```diff
@@ -487,7 +487,8 @@ public void testExplain() throws Exception {
             )
             .setRefreshPolicy(IMMEDIATE)
             .get();
-        indexRandomForConcurrentSearch("test");
+
+        indexRandomForMultipleSlices("test");
```
Comment (neetikasinghal) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:491]: adding this function as the bogus docs will be added in both the cases concurrent/non-concurrent case and the range of the doc ids will be different with each run in both the cases.

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java [hunk 8]
```diff
@@ -487,6 +487,13 @@ public void testExplain() throws Exception {
             )
             .setRefreshPolicy(IMMEDIATE)
             .get();
+
+        // refresh is important to enforce creation of a segment for document ingest above
+        // and prevent merging with deleted segemnts created by the index random function
+        // this ensures that the range doesnt change for the child docs asserted below
+        // ref: https://github.com/opensearch-project/OpenSearch/issues/11413
+        refresh("test");
```
Comment (reta) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:495]: @neetikasinghal I am confused by this change to be fair, the statement just above adds the single document with `RefreshPolicy.IMMEDIATE`, that is:

```
        /**
         * Force a refresh as part of this request. This refresh policy does not scale for high indexing or search throughput but is useful
         * to present a consistent view to for indices with very low traffic. And it is wonderful for tests!
         */
        IMMEDIATE("true"),

```

I suspect that either a) `RefreshPolicy.IMMEDIATE` is not respected, clearly a bug or b) this is noop. Could you please clarify my understanding here? Thank you.

Comment (jed326) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:495]: In addition to @reta's comment above, can't merges still happen as a part of `indexRandomForConcurrentSearch("test")`? I don't see how this would prevent merges

Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:495]: @reta thanks, you are right, there is already a refresh being called as part of the request above. Let me double check on why this solves the issue or try a few more runs to validate if there is any failure.

Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:495]: this was working in my local due to random seed getting messed up in IntelliJ, however this is not the right solution.

**Comment by neetikasinghal** [comment]
@reta updated the PR based on the discussion: https://github.com/opensearch-project/OpenSearch/issues/11413

**Review by kkmr — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java [hunk 9]
```diff
@@ -455,51 +452,6 @@ public void testDeleteNestedDocsWithAlias() throws Exception {
         assertDocumentCount("test", 6);
     }
 
-    public void testExplain() throws Exception {
```
Comment (sohami) [inline server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:458]: I think there is still value in keeping this specific test with single doc and asserting for exact explain string as done here. For concurrent path, it will run with 1 slice and still we should have the same output. You can remove `indexRandomForConcurrentSearch` from the test and rename it to `testExplainWithSingleDoc`

Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:458]: makes sense to add a test case for single doc as well, but for concurrent search use-case since it will run with 1 slice, the test will become somewhat redundant. So, I am thinking to add a test for single doc in the new test class introduced that has explain related test already and test only for non-concurrent use-case. Thoughts?

Comment (sohami) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:458]: Not really, it will verify that with 1 slice and concurrent search path, there is no change in explain API output. The other test class is capturing the multi-slice case.

Comment (neetikasinghal) [reply server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java:458]: since we want to test for 1 slice and concurrent search path, I will add the test in SimpleNestedIT as in the new class there is no parameterization despite of having explain based tests.

**Review by sohami — APPROVED** [review]
LGTM
