### PR TITLE
Moving get snapshot requests to listener based async calls

### LINKED ISSUE #1788: [BUG] Too many get snapshot calls causing generic threadpool to be busy completely
**Describe the bug**
Too many get snapshot calls for custom repo which has more than 70k snapshots caused generic threadpool to be exhausted completely. They were in indefinite wait state, looks like a deadlock.

Observed this behavior in 7.10 and 7.1 but the stack traces were different.

In 7.10 the code to fetch repository is under Future.get blocking call and the repositoriesService.getRepositoryData executes internal method in generic threadpool which was exhausted causing the deadlock
       [ threadPool.generic().execute(ActionRunnable.wrap(listener, this::doGetRepositoryData));](https://github.com/opensearch-project/OpenSearch/blob/996d33adb22ac6a523962166f3677f8dc6ac9c1f/server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java#L1590)

This issue would exist in OpenSearch as well, haven't tried explicit repro yet.

In 7.1 though, there was no deadlock but the get snapshot calls were taking really long to finish keeping the whole threadpool busy.

**Expected behavior**
The TransportGetSnapshotAction shouldn't block wait on the 
```repositoriesService.getRepositoryData``` and move to async processing

Repository.getRepositoryData was made async in https://github.com/opensearch-project/OpenSearch/commit/0acba44a2e8e22ae2899b4b267837e19ff525f11 and  blocking step for the
Blocking call was removed from snapshot status API TransportSnapshotsStatusAction  here - https://github.com/opensearch-project/OpenSearch/commit/1cde4a6364ce26ab38c99d2bc08aa4a1d4ce3be6 

Due to this, pending tasks were stuck for hours on master.

7.10

All the 128 thread of generic threadpool were busy waiting

```
"elasticsearch[dd229155bf9aa56a13617a858a541448][generic][T#234]" #6225 daemon prio=5 os_prio=0 cpu=308056.43ms elapsed=274126.86s tid=0x00007fd52424b000 nid=0x32ed waiting on condition  [0x00007fd33a257000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.6/Native Method)
	- parking to wait for  <0x00000004f9b75ec0> (a org.elasticsearch.common.util.concurrent.BaseFuture$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.6/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.6/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.6/AbstractQueuedSynchronizer.java:1039)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.6/AbstractQueuedSynchronizer.java:1345)
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:259)
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:87)
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:56)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:37)
	at org.elasticsearch.action.support.PlainActionFuture.get(PlainActionFuture.java:33)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:114)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:67)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:100)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:173)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$$Lambda$3646/0x00000008018b2040.accept(Unknown Source)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:752)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.6/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.6/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.6/Thread.java:834)

   Locked ownable synchronizers:
	- <0x00000004739d8ce0> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

7.1 

All 128 threads either were waiting for connection for S3 or running at the conscrypt library code.

```
"elasticsearch[e7e76d2dd2e0ed6731c77440058decee][generic][T#367]" #1145 daemon prio=5 os_prio=0 cpu=703963.76ms elapsed=48932.59s tid=0x00007f89f4294000 nid=0x5297 waiting on condition  [0x00007f894f7cb000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.6/Native Method)
	- parking to wait for  <0x00000005ccf7c690> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkUntil(java.base@11.0.6/LockSupport.java:275)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitUntil(java.base@11.0.6/AbstractQueuedSynchronizer.java:2166)
	at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:377)
	at org.apache.http.pool.AbstractConnPool.access$200(AbstractConnPool.java:69)
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:245)
	- locked <0x000000058546b608> (a org.apache.http.pool.AbstractConnPool$2)
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:193)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:304)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:280)
	at jdk.internal.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.6/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.6/Method.java:566)
	at com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
	at com.amazonaws.http.conn.$Proxy112.get(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1323)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5054)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5000)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1486)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1341)
	at org.elasticsearch.repositories.s3.S3BlobContainer.lambda$readBlob$1(S3BlobContainer.java:98)
	at org.elasticsearch.repositories.s3.S3BlobContainer$$Lambda$3012/0x0000000801697c40.run(Unknown Source)
	at java.security.AccessController.doPrivileged(java.base@11.0.6/Native Method)
	at org.elasticsearch.repositories.s3.SocketAccess.doPrivileged(SocketAccess.java:42)
	at org.elasticsearch.repositories.s3.S3BlobContainer.readBlob(S3BlobContainer.java:98)
	at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.readBlob(ChecksumBlobStoreFormat.java:101)
	at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:93)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotInfo(BlobStoreRepository.java:718)
	at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:239)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:135)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:54)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:127)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:208)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:760)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.6/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.6/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.6/Thread.java:834)
```

```
"elasticsearch[e7e76d2dd2e0ed6731c77440058decee][generic][T#368]" #1147 daemon prio=5 os_prio=0 cpu=702831.23ms elapsed=48912.59s tid=0x00007f89f4131800 nid=0x52ae runnable  [0x00007f8972ce9000]
   java.lang.Thread.State: RUNNABLE
	at org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at org.conscrypt.NativeSsl.read(NativeSsl.java:409)
	at org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:548)
	- locked <0x00000005a1a28020> (a java.lang.Object)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1323)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5054)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5000)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1486)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1341)
	at org.elasticsearch.repositories.s3.S3BlobContainer.lambda$readBlob$1(S3BlobContainer.java:98)
	at org.elasticsearch.repositories.s3.S3BlobContainer$$Lambda$3012/0x0000000801697c40.run(Unknown Source)
	at java.security.AccessController.doPrivileged(java.base@11.0.6/Native Method)
	at org.elasticsearch.repositories.s3.SocketAccess.doPrivileged(SocketAccess.java:42)
	at org.elasticsearch.repositories.s3.S3BlobContainer.readBlob(S3BlobContainer.java:98)
	at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.readBlob(ChecksumBlobStoreFormat.java:101)
	at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:93)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotInfo(BlobStoreRepository.java:718)
	at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:239)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:135)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:54)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:127)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:208)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:760)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.6/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.6/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.6/Thread.java:834)
```

### PR DESCRIPTION
**Pull request by indrajohn7**
### Description
This PR is to discuss the optimisation changes for listener based get_snapshot calls handled through async based model.

The TransportGetSnapshotAction shouldn't block wait on the
repositoriesService.getRepositoryData and move to async processing

Due to this, pending tasks were stuck for hours on master.

### Reproduction:

- 700 shards.
- Concurrent create_snapshot() calls and PUT mapping requests.
- 140 concurrent get_snapshot calls
- It keeps all the generic threadpool busy and the pending_tasks queue piles up.

```
"opensearch[c007f9bc9cbee0de09eb93767897e305][generic][T#24]" #131865 daemon prio=5 os_prio=0 cpu=1319.41ms elapsed=20.31s tid=0x00007effe406a2b0 nid=0x1d2f waiting on condition  [0x00007effa9b92000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.18/Native Method)
        - parking to wait for  <0x00000006ac9752d8> (a org.opensearch.common.util.concurrent.BaseFuture$Sync)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.18/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.18/AbstractQueuedSynchronizer.java:885)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.18/AbstractQueuedSynchronizer.java:1039)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.18/AbstractQueuedSynchronizer.java:1345)
        at org.opensearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:272)
        at org.opensearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:104)
        at org.opensearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:74)
        at org.opensearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:55)
        at org.opensearch.action.support.PlainActionFuture.get(PlainActionFuture.java:51)
        at org.opensearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.clusterManagerOperation(TransportGetSnapshotsAction.java:143)
        at org.opensearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.clusterManagerOperation(TransportGetSnapshotsAction.java:82)
        at org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction.masterOperation(TransportClusterManagerNodeAction.java:144)
        at org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction.clusterManagerOperation(TransportClusterManagerNodeAction.java:153)
        at org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction$AsyncSingleAction.lambda$doStart$3(TransportClusterManagerNodeAction.java:269)
        at org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction$AsyncSingleAction$$Lambda$5035/0x00000008015ff440.accept(Unknown Source)
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:815)
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.18/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.18/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.18/Thread.java:829)
        
```

- Too many pending tasks queue:
 ```14300  5.6h NORMAL cluster_reroute(reroute after starting shards)
 5252  1.1d NORMAL update snapshot after shards started [false] or node configuration changed [true]
10377   12h NORMAL cluster_reroute(reroute after starting shards)
13056  7.2h NORMAL cluster_reroute(reroute after starting shards)
11170 10.3h NORMAL cluster_reroute(reroute after starting shards)
15289 11.7m HIGH   shard-failed
15283 11.7m HIGH   shard-failed
15269   28m HIGH   shard-failed
 9039 14.3h NORMAL cluster_reroute(reroute after starting shards)

% curl localhost:9200/_cat/pending_tasks | wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  411k  100  411k    0     0  1674k      0 --:--:-- --:--:-- --:--:-- 1680k
**10022**
```
- Pending tasks queue piles up to > 10K.

### With Fix:

- With the similar cluster configurations:
- The pending task queue never piles up for more than 10 - 20 count with similar number of concurrent create/ get snapshot calls and PUT mapping requests.
- All the generic threadpools are also not blocked with the get_snapshot() calls.
```
% grep -irn "getRepositoryData" ./output.jstk | wc -l
0
...

% grep -irn "getRepositoryData" ./output.jstk| wc -l 
2
...

% grep -irn "getRepositoryData" ./output.jstk| wc -l 
6
```

### Use of `SNAPSHOT` Threadpool

- Use `SNAPSHOT` threadpool in stead of `GENERIC` threadpool for the get_snapshot calls.
- The create snapshot calls use the  SNAPSHOTS threadpool, the same can be expedited here as well unblocking the generic threadpool.
     

Observations:

* This has a ripple effect on Latency. With too many get_snapshot concurrent calls, it was observed that there is always a single entry in the thread dump for the SNAPSHOT threadpool, processing processing the get_snapshot request.
    * For 10 concurrent GET calls, where the generic threadpool response time is ~1 secs, with listener based async model the SNAPSHOT threadpool is being latent, where the latency is ~100 - ~110 secs, which is a real impact to the performance metrics.
    *get_snapshot response:
```
        % tail -f nohup.out         
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
          0     0    0     0    0     0      0      0 --:--:--  0:01:49 --:--:--     02023-06-13t08-50-54.5a5cb21d-8563-46ca-9779-4ee58443fa91     SUCCESS 1686646257 08:50:57 1686646259 08:50:59  1.2s   2    2 0    2
        2023-06-13t09-21-44.d9879b36-162b-7c62-f194-240b355be809     SUCCESS 1686648104 09:21:44 1686648104 09:21:44 200ms   2    2 0    2
        2023-06-13t10-21-44.bd67e503-9d29-d63e-0efd-c4f3763891fe     SUCCESS 1686651704 10:21:44 1686651711 10:21:51  6.8s  34  322 0  322
        2023-06-13t11-21-44.16b7bd58-7ca0-de6a-6537-cdd99236cc17
```
- This is because the number of `SNAPSHOT` threadpools are lesser compared to the generic one.
```
final int genericThreadPoolMax = boundedBy(4 * allocatedProcessors, 128, 512);
builders.put(Names.GENERIC, new ScalingExecutorBuilder(Names.GENERIC, 4, genericThreadPoolMax, TimeValue.timeValueSeconds(30)));
builders.put(Names.SNAPSHOT, new ScalingExecutorBuilder(Names.SNAPSHOT, 1, halfProcMaxAt5, TimeValue.timeValueMinutes(5)));

```
- Hence use of `SNAPSHOT` threadpool would not be recommended here as it may block the create snapshot calls as well if its shared across get_snapshot requests.

> 

### Related Issues
Resolves #1788 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by shwetathareja** [comment]
Porting the comment from old PR here

> For 10 concurrent GET calls, where the generic threadpool response time is ~1 secs, with listener based async model the SNAPSHOT threadpool is being latent, where the latency is ~100 - ~110 secs, which is a real impact to the performance metrics.

@indrajohn7 This is because SNAPSHOT threadpool can scale up to only 5 threads
```
builders.put(Names.SNAPSHOT, new ScalingExecutorBuilder(Names.SNAPSHOT, 1, halfProcMaxAt5, TimeValue.timeValueMinutes(5)));
```

where as GENERIC threadpool can scale upto 512 depending on no. of cores.

```
final int genericThreadPoolMax = boundedBy(4 * allocatedProcessors, 128, 512);
builders.put(Names.GENERIC, new ScalingExecutorBuilder(Names.GENERIC, 4, genericThreadPoolMax, TimeValue.timeValueSeconds(30)));
```

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 1]
```diff
@@ -2136,6 +2138,17 @@ public void onFailure(final Exception e) {
                         indexNameExpressionResolver
                     )
                 );
+                actions.put(
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:2141]: this is just registering the action. Where is the TransportGetSnapshotsAction triggered? If the tests are missing for this action, please add them.

Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:2141]: Ack. Adding a separate test class to track the Transport actions.

**Comment by andrross** [comment]
@indrajohn7 How do PRs #8216 and #8347 relate to this? Can you close any PRs that are no longer relevant?

**Comment by indrajohn7** [comment]
> @indrajohn7 How do PRs #8216 and #8347 relate to this? Can you close any PRs that are no longer relevant?

@andrross I have closed those 2 draft PRs and deleted the branches.

File: server/src/main/java/org/opensearch/repositories/RepositoriesService.java [hunk 2]
```diff
@@ -149,6 +149,19 @@ public RepositoriesService(
...
+    public RepositoriesService repositories(Map<String, Repository> repositories) {
+        this.repositories = repositories;
+        return this;
+    }
+
+    public Map<String, Repository> repositories() {
+        return this.repositories;
+    }
+
+    public Map<String, Repository.Factory> typesRegistry() {
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/repositories/RepositoriesService.java:161]: why did you expose these methods? We dont allow updating repos like this.

File: server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java [hunk 3]
```diff
@@ -210,15 +210,15 @@ private void assertThrowsOnRegister(String repoName) {
         expectThrows(RepositoryException.class, () -> repositoriesService.registerRepository(request, null));
     }
 
-    private static class TestRepository implements Repository {
+    public static class TestRepository implements Repository {
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java:213]: dont make them public from one test class. This would add un-necessary dependency across test classes.

File: server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java [hunk 4]
```diff
@@ -0,0 +1,245 @@
...
+            assertNotNull("snapshots should be set as we are checking the current snapshot", repoSnapshotResponse.getSnapshots());
+        }, exception -> { throw new AssertionError(exception); }));
+
+        repoSnapshotRequest = new GetSnapshotsRequest().repository(repoName)
+            .snapshots(currSnapshotOnly)
+            .ignoreUnavailable(true)
+            .verbose(false);
+        getSnapshotsAction.execute(task, repoSnapshotRequest, ActionListener.wrap(repoSnapshotResponse -> {
+            assertNotNull("snapshots should be set as we are checking the current snapshot", repoSnapshotResponse.getSnapshots());
+        }, exception -> { throw new AssertionError(exception); }));
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java:211]: why are you trying to call it multiple times here? if really needed it can be a for loop instead.

File: server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java [hunk 5]
```diff
@@ -0,0 +1,245 @@
...
+
+        getSnapshotsAction.execute(null, repoMissingRequest, ActionListener.wrap(repoMissingResponse -> {
+            assertThrows(ActionRequestValidationException.class, () -> { repoMissingResponse.getSnapshots(); });
+        }, exception -> { assertTrue(exception.getMessage().contains("repository is missing")); }));
+
+        repoMissingRequest = new GetSnapshotsRequest().verbose(false);
+
+        getSnapshotsAction.execute(null, repoMissingRequest, ActionListener.wrap(repoMissingResponse -> {
+            assertThrows(ActionRequestValidationException.class, () -> { repoMissingResponse.getSnapshots(); });
+        }, exception -> { assertTrue(exception.getMessage().contains("repository is missing")); }));
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java:169]: i dont think we need each request param combination here as you are testing for repo missing.

File: server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java [hunk 6]
```diff
@@ -0,0 +1,245 @@
...
+        getSnapshotsAction.execute(null, repoSnapshotRequest, ActionListener.wrap(repoSnapshotResponse -> {
+            assertNotNull("snapshots should be set as we are checking the current snapshot", repoSnapshotResponse.getSnapshots());
+        }, exception -> { throw new AssertionError(exception); }));
+
+        repoSnapshotRequest = new GetSnapshotsRequest().repository(repoName)
+            .snapshots(currSnapshotOnly)
+            .ignoreUnavailable(true)
+            .verbose(false);
+        getSnapshotsAction.execute(null, repoSnapshotRequest, ActionListener.wrap(repoSnapshotResponse -> {
+            assertNotNull("snapshots should be set as we are checking the current snapshot", repoSnapshotResponse.getSnapshots());
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java:194]: we should assert on the snapshots list

File: server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java [hunk 7]
```diff
@@ -0,0 +1,245 @@
...
+
+    public void testCurrentRepoSnapshot() {
+        final Task task = createTask();
+        RepositoryMetadata repositoryMetadata = new RepositoryMetadata(repoName, repoType, Settings.EMPTY);
+        Repository repository = repositoriesService.createRepository(repositoryMetadata, repositoriesService.typesRegistry());
+        ;
+        Map<String, Repository> repositoryMap = new HashMap<>();
+        repositoryMap.put(repoName, repository);
+        repositoriesService = repositoriesService.repositories(repositoryMap);
+        assertEquals(repositoryMap, repositoriesService.repositories());
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java:180]: no sure what are you trying to do here, we dont need to test RepositoriesService here.

File: server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java [hunk 8]
```diff
@@ -0,0 +1,245 @@
...
+            );
+        }
+
+        @Override
+        protected void clusterManagerOperation(
+            GetSnapshotsRequest request,
+            ClusterState state,
+            ActionListener<GetSnapshotsResponse> listener
+        ) {
+            ClusterState stateWithIndex = ClusterStateCreationUtils.state(indexName, 1, 1);
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java:80]: you can create ClusterState directly here with snapshots

**Review by shwetathareja — COMMENTED** [review]
Thanks @indrajohn7 for the changes. We need to clean up the tests.

File: server/src/main/java/org/opensearch/repositories/RepositoriesService.java (hunk 2 above)
Comment (indrajohn7) [reply server/src/main/java/org/opensearch/repositories/RepositoriesService.java:161]: I had to mock repositoriesService object, which was needed for the tests; else all the tests were reporting to nukl check failure for empty repositories: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/repositories/RepositoriesService.java#L489.

File: server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java (hunk 3 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java:213]: This test class already has a few mock objects of respositoriesService which could be leveraged, else the same code had to be duplicated here as well for mocking purpose.

File: server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java (hunk 4 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java:211]: This is to capture all the combinations of `ignoreUnavailable` and `verbose` attribute of the getSnapshotRequest call.

File: server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java (hunk 7 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java:180]: Ack. This was checked to complete the codeCov check, as the similar method was exposed on the RepositoriesService call.

File: server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java (hunk 8 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java:80]: There are no utils as such available with the snapshots, Did not create one as of now.is it required for this test class? As we are able to mock the other objects as well from here.

File: server/src/main/java/org/opensearch/repositories/RepositoriesService.java (hunk 2 above)
Comment (indrajohn7) [reply server/src/main/java/org/opensearch/repositories/RepositoriesService.java:161]:
```
 public Repository repository(String repositoryName) {
        Repository repository = repositories.get(repositoryName);
        if (repository != null) {
            return repository;
        }
        repository = internalRepositories.get(repositoryName);
        if (repository != null) {
            return repository;
        }
        throw new RepositoryMissingException(repositoryName);
    }
```

File: server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java (hunk 7 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java]: This has been revoked.

File: server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java (hunk 6 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsActionTests.java]: Ack.

File: server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java (hunk 3 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java]: This has been revoked.

File: server/src/main/java/org/opensearch/repositories/RepositoriesService.java (hunk 2 above)
Comment (indrajohn7) [reply server/src/main/java/org/opensearch/repositories/RepositoriesService.java]: Ack.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 9]
```diff
@@ -686,6 +687,107 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
...
+            testClusterNodes.nodes.values().iterator().next().clusterService.state()
+        );
+
+        for (int i = 0; i < snapshotsList.length; i++) {
+            final StepListener<CreateSnapshotResponse> createSnapshotResponseStepListener = new StepListener<>();
+            final String snapshot = snapshotsList[i];
+            final String index = indexList[i];
+            continueOrDie(
+                createRepoAndIndex(repoName, index, shards),
+                createIndexResponse -> client().admin()
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:708]: [minor]: createIndexResponse -> createSnapshotResponse

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 10]
```diff
@@ -686,6 +687,107 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
...
+        if (getSnapshotsAction instanceof TransportGetSnapshotsAction) {
+            TransportGetSnapshotsAction transportGetSnapshotsAction = (TransportGetSnapshotsAction) getSnapshotsAction;
+            transportGetSnapshotsAction.execute(null, repoSnapshotRequest, ActionListener.wrap(repoSnapshotResponse -> {
+                assertNotNull("snapshots should be set as we are checking the current snapshot", repoSnapshotResponse.getSnapshots());
+                assertThat(repoSnapshotResponse.getSnapshots(), hasSize(2));
+            }, exception -> { throw new AssertionError(exception); }));
+        }
+    }
+
+    public void testTransportGetCurrentSnapshotOnly() {
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:745]: why do we need this separate test for currentSnapshot?

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 11]
```diff
@@ -686,6 +687,107 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
...
+                    .cluster()
+                    .prepareCreateSnapshot(repoName, snapshot)
+                    .setWaitForCompletion(true)
+                    .execute(createSnapshotResponseStepListener)
+            );
+
+            final StepListener<GetSnapshotsResponse> getSnapshotsResponseStepListener = new StepListener<>();
+            continueOrDie(getSnapshotsResponseStepListener, getSnapshotsResponse -> {
+                client().admin().cluster().prepareGetSnapshots(repoName).execute(getSnapshotsResponseStepListener);
+            });
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:718]: why are we doing this?

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 12]
```diff
@@ -686,6 +687,107 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
...
+            assertEquals(SnapshotState.SUCCESS, snapshotInfo.state());
+            assertEquals(0, snapshotInfo.failedShards());
+            assertTrue(Arrays.stream(snapshotsList).anyMatch(snapshotInfo.snapshotId().getName()::equals));
+        }
+
+        TransportAction getSnapshotsAction = clusterManagerNode.actions.get(GetSnapshotsAction.INSTANCE);
+        GetSnapshotsRequest repoSnapshotRequest = new GetSnapshotsRequest().repository(repoName)
+            .snapshots(snapshotsList)
+            .ignoreUnavailable(true);
+        if (getSnapshotsAction instanceof TransportGetSnapshotsAction) {
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:736]: we dont need the if check.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 13]
```diff
@@ -686,6 +687,107 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
...
+            TransportGetSnapshotsAction transportGetSnapshotsAction = (TransportGetSnapshotsAction) getSnapshotsAction;
+            transportGetSnapshotsAction.execute(null, repoSnapshotRequest, ActionListener.wrap(repoSnapshotResponse -> {
+                assertNotNull("snapshots should be set as we are checking the current snapshot", repoSnapshotResponse.getSnapshots());
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:739]: assert message seems wrong here

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 10 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:745]: CodeCoverage improvement, This has a specific code path to fall through and checks.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 12 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:736]: Ack.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 11 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:718]: This is required for the listener based calls. as createSnapshot is following as well, else the repositoryData will be empty.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 13 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:739]: Ack.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 9 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java]: Ack.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 14]
```diff
@@ -686,6 +687,105 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
...
+        final String[] snapshotsList = { GetSnapshotsRequest.CURRENT_SNAPSHOT };
+        TransportAction getSnapshotsAction = clusterManagerNode.actions.get(GetSnapshotsAction.INSTANCE);
+        GetSnapshotsRequest repoSnapshotRequest = new GetSnapshotsRequest().repository(repoName)
+            .snapshots(snapshotsList)
+            .ignoreUnavailable(true);
+
+        TransportGetSnapshotsAction transportGetSnapshotsAction = (TransportGetSnapshotsAction) getSnapshotsAction;
+        transportGetSnapshotsAction.execute(null, repoSnapshotRequest, ActionListener.wrap(repoSnapshotResponse -> {
+            assertNotNull("Empty Snapshot info should be registered for current snapshots", repoSnapshotResponse.getSnapshots());
+            assertThat(repoSnapshotResponse.getSnapshots(), hasSize(0));
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:785]: how is the current snapshot tested here. I see you are asserting for size 0?

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 10 above)
Comment (shwetathareja) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:744]: can you cover current snapshot scenario above itself, you will need the code from Line 776 onwards

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 11 above)
Comment (shwetathareja) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:718]: i dont see any link of below getRepositoryData with this extra get call.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 14 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:785]: @shwetathareja This is to test the below codecoverage checks:
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java#L147
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java#L156

However, this would only be populated to snapshotInfo if the `_CURRENT` snapshot is in InProgress state: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java#L156, This has not been mocked here. This test can be removed altogether if not required.

Comment (shwetathareja) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:785]: we shouldn't add tests just for code coverage sake if they are not testing intended functionality.

File: server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java [hunk 15]
```diff
@@ -138,57 +138,61 @@ protected void clusterManagerOperation(
                 currentSnapshots.add(snapshotInfo);
             }
 
-            final RepositoryData repositoryData;
-            if (isCurrentSnapshotsOnly(request.snapshots()) == false) {
-                repositoryData = PlainActionFuture.get(fut -> repositoriesService.getRepositoryData(repository, fut));
-                for (SnapshotId snapshotId : repositoryData.getSnapshotIds()) {
-                    allSnapshotIds.put(snapshotId.getName(), snapshotId);
+            final StepListener<RepositoryData> repositoryDataListener = new StepListener<>();
+            repositoriesService.getRepositoryData(repository, repositoryDataListener);
```
[the remark this answers is not in the document]
Comment (indrajohn7) [reply server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java:142]: Ack.

File: server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java [hunk 16]
```diff
@@ -138,57 +138,61 @@ protected void clusterManagerOperation(
...
 
-            final RepositoryData repositoryData;
-            if (isCurrentSnapshotsOnly(request.snapshots()) == false) {
-                repositoryData = PlainActionFuture.get(fut -> repositoriesService.getRepositoryData(repository, fut));
-                for (SnapshotId snapshotId : repositoryData.getSnapshotIds()) {
-                    allSnapshotIds.put(snapshotId.getName(), snapshotId);
+            final StepListener<RepositoryData> repositoryDataListener = new StepListener<>();
+            repositoryDataListener.whenComplete(repositoryData -> {
+                if (isCurrentSnapshotsOnly(request.snapshots()) == false) {
+                    repositoriesService.getRepositoryData(repository, repositoryDataListener);
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java:144]: ```repositoryDataListener``` complete will never be triggered as yo are attaching the listener inside whenComplete itself.

Comment (indrajohn7) [reply server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java]: Ack.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 14 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java]: Ack.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 11 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java]: This is not required anymore.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 10 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java]: not required anymore.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 17]
```diff
@@ -686,6 +686,55 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
         }
     }
 
+    public void testTransportGetSnapshotsAction() {
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:689]: @indrajohn7  now that we have separated the flow for currentSnapshotOnly, please add a coverage for that same with 1 current snapshot in progress.

Comment (shwetathareja) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:689]: You can cover currentSnapshot as below using ClusterStateListener which can check if snapshot is in progress

```
       CountDownLatch latch = new CountDownLatch(1);
        clusterManagerNode.clusterService.addListener(new ClusterStateListener() {
            @Override
            public void clusterChanged(ClusterChangedEvent event) {
                if (event.state().custom(SnapshotsInProgress.TYPE) != null) {
                    // assert here for in progress snapshot and call your transport get snapshot action here
                    SnapshotsInProgress snapshotsInProgress = event.state().custom(SnapshotsInProgress.TYPE);
                    assertTrue(snapshotsInProgress.entries().stream().anyMatch(entry -> entry.state().completed() == false));
                    latch.countDown();
                }
            }
        });

       continueOrDie(createRepoAndIndex(repoName, index, shards), createIndexResponse -> {
            final Runnable afterIndexing = () -> client().admin()
                .cluster()
                .prepareCreateSnapshot(repoName, snapshotName)
                .setWaitForCompletion(false)     // set this to false so that it is unblocked.
                .execute(createSnapshotResponseListener);
```

Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:797]: Ack.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 18]
```diff
@@ -794,6 +794,108 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
...
+        );
+
+        final StepListener<CreateSnapshotResponse> createSnapshotResponseListener = new StepListener<>();
+        clusterManagerNode.clusterService.addListener(new ClusterStateListener() {
+            @Override
+            public void clusterChanged(ClusterChangedEvent event) {
+                if (event.state().custom(SnapshotsInProgress.TYPE) != null) {
+                    TransportAction getSnapshotsAction = clusterManagerNode.actions.get(GetSnapshotsAction.INSTANCE);
+                    TransportGetSnapshotsAction transportGetSnapshotsAction = (TransportGetSnapshotsAction) getSnapshotsAction;
+                    for (boolean mode : snapshotRequestMode) {
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:866]: this is not needed

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 19]
```diff
@@ -794,6 +794,108 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
...
+                            assertThat(repoSnapshotResponse.getSnapshots(), hasSize(snapshotsList.length));
+                            for (SnapshotInfo snapshotInfo : snapshotInfos) {
+                                assertEquals(SnapshotState.IN_PROGRESS, snapshotInfo.state());
+                                assertEquals(0, snapshotInfo.failedShards());
+                                assertTrue(snapshotInfo.snapshotId().getName().contains("last-snapshot"));
+                            }
+                        }, exception -> { throw new AssertionError(exception); }));
+                    }
+                    SnapshotsInProgress snapshotsInProgress = event.state().custom(SnapshotsInProgress.TYPE);
+                    assertTrue(snapshotsInProgress.entries().stream().anyMatch(entry -> entry.state().completed() == false));
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:884]: you can remove this.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 20]
```diff
@@ -794,6 +794,108 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
...
+        TransportAction getSnapshotsAction = clusterManagerNode.actions.get(GetSnapshotsAction.INSTANCE);
+        TransportGetSnapshotsAction transportGetSnapshotsAction = (TransportGetSnapshotsAction) getSnapshotsAction;
+        for (boolean mode : snapshotRequestMode) {
+            GetSnapshotsRequest repoSnapshotRequest = new GetSnapshotsRequest().repository(repoName)
+                .snapshots(snapshotsList)
+                .ignoreUnavailable(mode)
+                .verbose(mode);
+
+            transportGetSnapshotsAction.execute(null, repoSnapshotRequest, ActionListener.wrap(repoSnapshotResponse -> {
+                assertNotNull("Snapshot list should be registered", repoSnapshotResponse.getSnapshots());
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:834]: change the message to "Snapshot list should be non null". Also, change in below test case

Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java]: Ack.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 19 above)
Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java]: Ack.

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 21]
```diff
@@ -782,9 +783,7 @@ public void testConcurrentSnapshotCreateAndDeleteOther() {
         assertFalse(finalSnapshotsInProgress.entries().stream().anyMatch(entry -> entry.state().completed() == false));
         final Repository repository = clusterManagerNode.repositoriesService.repository(repoName);
         Collection<SnapshotId> snapshotIds = getRepositoryData(repository).getSnapshotIds();
-        // We end up with two snapshots no matter if the delete worked out or not
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:785]: why is this comment removed?

Comment (indrajohn7) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:785]: Ack.
