### PR TITLE
[Segment Replication] Add log for failover time 

### LINKED ISSUE #10951: Add logs to get the failover time for segrep enabled clusters for debugging
**Describe the bug**
Currently, we don't have a specific metric that we can surface for failover time. 
We can see symptoms of a long failover through other metrics like write rejection count, yellow cluster, etc. 
Adding in an additional log line with the failover time can help in debugging by letting us know how long it's been going on for.

**Expected behavior**
Add logs to print the failover time. 

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Poojita-Raj**
### Description
Adds a log for duration of failover time that will help in debugging issues. 

### Related Issues
Resolves #10951 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 1]
```diff
@@ -698,7 +699,20 @@ public void updateShardState(
...
+                                    "Resetting engine on promotion of shard [{}] to primary, startTime {}\n",
+                                    shardId,
+                                    timer.startTime()
+                                );
                                 resetEngineToGlobalCheckpoint();
+                                timer.stop();
+                                logger.info(
+                                    "Completed engine failover for shard [{}] in: {} ms",
+                                    shardId,
+                                    timer.stopTime() - timer.startTime()
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:714]: ReplicationTimer already computes this and can be fetched with `timer.time()`.

**Review by mch2 — APPROVED** [review]

**Comment by Rishikesh1159** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> 
>     * **RESULT:** FAILURE ❌
> 
>     * **URL:** https://build.ci.opensearch.org/job/gradle-check/29105/
> 
>     * **CommitID:** [c3733d4](https://github.com/opensearch-project/OpenSearch/commit/c3733d470c11f384db3951355d8cbbde3aadbe04)
>       Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>       Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

#10154 
#9332
