### PR TITLE
Handling concurrent segment search as part of fetch profiling

### LINKED ISSUE #19070: [AUTOCUT] Gradle Check Flaky Test Report for AggregationProfilerIT
## Flaky Test Report for `AggregationProfilerIT`

Noticed the `AggregationProfilerIT` has some flaky, failing tests that failed during **post-merge actions** and **timer trigerred run on main branch**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| main | [null](https://github.com/opensearch-project/OpenSearch/pull/null) | [62373](https://build.ci.opensearch.org/job/gradle-check/62373/testReport/) <br><br>[62682](https://build.ci.opensearch.org/job/gradle-check/62682/testReport/) | `org.opensearch.search.profile.aggregation.AggregationProfilerIT.testTopHitsAggregationFetchProfiling {p0={"search.concurrent_segment_search.enabled":"true"}}` |
| 04d9b493aeeccbb95a355232eba8340b709806d0 | [19054](https://github.com/opensearch-project/OpenSearch/pull/19054) | [62396](https://build.ci.opensearch.org/job/gradle-check/62396/testReport/) | `org.opensearch.search.profile.aggregation.AggregationProfilerIT.testTopHitsAggregationFetchProfiling {p0={"search.concurrent_segment_search.enabled":"true"}}` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `AggregationProfilerIT` class are:

- [18936](https://github.com/opensearch-project/OpenSearch/pull/18936)
- [18568](https://github.com/opensearch-project/OpenSearch/pull/18568)
- [18800](https://github.com/opensearch-project/OpenSearch/pull/18800)
- [18921](https://github.com/opensearch-project/OpenSearch/pull/18921)
- [19057](https://github.com/opensearch-project/OpenSearch/pull/19057)
- [19083](https://github.com/opensearch-project/OpenSearch/pull/19083)
- [19136](https://github.com/opensearch-project/OpenSearch/pull/19136)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by jainankitk**
### Description
During fetch phase profiling, `FlatFetchProfileTree` object is shared across multiple threads and the state needs to be synchronized to prevent intermittent issues. co-author @atris 

### Related Issues
Resolves #19070 

### Check List
- [x] Functionality includes testing.
~- [] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/search/profile/fetch/FlatFetchProfileTree.java [hunk 1]
```diff
@@ -59,8 +60,8 @@ private static class Node {
     }
 
     private final List<Node> roots = new ArrayList<>();
-    private final Map<String, Node> rootsMap = new HashMap<>();
-    private final Map<String, Node> phaseMap = new HashMap<>();
+    private final ConcurrentMap<String, Node> rootsMap = new ConcurrentHashMap<>();
```
Comment (andrross) [inline server/src/main/java/org/opensearch/search/profile/fetch/FlatFetchProfileTree.java:63]: The following code (from line 71) is not thread safe:

```java
Node node = rootsMap.get(uniqueElement);
if (node == null) {
    node = new Node(element); // Keep original element name for display
    roots.add(node);
    rootsMap.put(uniqueElement, node);
}
```

Two threads could end up creating a new node but one of them will be overwritten. Admittedly, this change doesn't make things _worse_, but it does give the appearance that this code is thread safe when it is not.

There's similar non-thread safe access to phaseMap on line 112 where an entry is removed.

Comment (jainankitk) [reply server/src/main/java/org/opensearch/search/profile/fetch/FlatFetchProfileTree.java:63]: I am actually glad that you brought up this point. The code is still thread safe, because of the distinct keys across threads (notice the threadId getting appended). So, essentially we need to ensure that there is no corruption while the metadata is getting updated for the underlying map. Using `ConcurrentHashMap` implementation ensures that, and the same is reflected by tests as well.

```
// Make phase name unique for concurrent slices by including thread info
String uniqueElement = element + "_" + Thread.currentThread().getId();
```

Comment (andrross) [reply server/src/main/java/org/opensearch/search/profile/fetch/FlatFetchProfileTree.java:63]: Ah I see, makes sense.

**Review by andrross — APPROVED** [review]
