### PR TITLE
[Segment Replication] Support realtime reads for GET requests

### LINKED ISSUE #8536: Segment Replication - Support realtime reads with GET requests
**Describe the bug**
Today document replication provides the option for "realtime"  reads with the GET API that reads and parses source from the translog to serve strong reads.  This same option should be supported while using segment replication because each shard copy still has the ability to read the translog, however today the NRTReplicationEngine only reads the index when serving GET requests.

**Expected behavior**
GET requests "realtime" option  to be supported with segment replicaiton.

### PR DESCRIPTION
**Pull request by Poojita-Raj**
### Description
This change supports realtime reads for GET requests when segment replication is enabled. 
If there are no preferences mentioned for the incoming GET request then we route it to primary shards which serve strong reads by parsing source from the translog. 

### Related Issues
Resolves #8536 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/action/get/TransportGetAction.java [hunk 1]
```diff
@@ -90,14 +93,21 @@ protected boolean resolveIndex(GetRequest request) {
 
     @Override
     protected ShardIterator shards(ClusterState state, InternalRequest request) {
+        String preference = request.request().preference();
+        // route realtime GET requests when segment replication is enabled to primary shards,
+        // iff there are no other preferences/routings enabled for routing to a specific shard
+        if (state.getMetadata()
```
Comment (mch2) [inline server/src/main/java/org/opensearch/action/get/TransportGetAction.java:99]: Lets pls move this to a private function for readability?

Something like `isPrimaryBasedRouting`

File: server/src/main/java/org/opensearch/action/get/TransportGetAction.java [hunk 2]
```diff
@@ -90,14 +93,21 @@ protected boolean resolveIndex(GetRequest request) {
...
+            .index(request.concreteIndex())
```
Comment (mch2) [inline server/src/main/java/org/opensearch/action/get/TransportGetAction.java:100]: This will throw if the index is not found, lets add a check here?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 3]
```diff
@@ -1425,4 +1432,34 @@ public void testIndexWhileRecoveringReplica() throws Exception {
...
+        ensureGreen(INDEX_NAME);
+
+        GetResponse response = client().prepareGet(indexOrAlias(), "1").get();
+        assertThat(response.isExists(), equalTo(false));
+
+        logger.info("--> index doc 1");
+        client().prepareIndex(indexOrAlias()).setId("1").setSource("foo", "bar").get();
+
+        logger.info("--> non realtime get 1");
+        response = client().prepareGet(indexOrAlias(), "1").setRealtime(false).get();
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1456]: lets pls specify the replica here and in the next req when intializing the client to ensure the replica is serving the req. `client(replica)` with the 'only_local' preference as well.

File: server/src/main/java/org/opensearch/action/get/TransportGetAction.java [hunk 4]
```diff
@@ -90,14 +93,21 @@ protected boolean resolveIndex(GetRequest request) {
...
+            .getSettings()
+            .get(IndexMetadata.SETTING_REPLICATION_TYPE)
+            .equals(ReplicationType.SEGMENT.toString())
+            && request.request().realtime()
+            && request.request().routing() == null
+            && request.request().preference() == null) {
+            preference = Preference.PRIMARY.type();
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/action/get/TransportGetAction.java:107]: 1. Move this to a try.catch to ensure all null checks are handled. 
2. What if the preference was already overridden to `PRIMARY`

Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/action/get/TransportGetAction.java:107]: Thanks for the review @Bukhtawar! In the case of (2), we will honor the preference to `PRIMARY` that user has set.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 3 above)
Comment (Poojita-Raj) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1456]: Thanks for the review @mch2! All valid comments, I'll make the changes shortly

File: server/src/main/java/org/opensearch/action/get/TransportGetAction.java [hunk 5]
```diff
@@ -90,14 +93,21 @@ protected boolean resolveIndex(GetRequest request) {
 
     @Override
     protected ShardIterator shards(ClusterState state, InternalRequest request) {
+        String preference = request.request().preference();
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/action/get/TransportGetAction.java:96]: Can we also add unit test to ensure preference is changed to `primary` for segment replication enabled indices ?

File: CHANGELOG.md [hunk 6]
```diff
@@ -80,12 +80,13 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 ## [Unreleased 2.x]
 ### Added
 - Add server version as REST response header [#6583](https://github.com/opensearch-project/OpenSearch/issues/6583)
-- Start replication checkpointTimers on primary before segments upload to remote store. ([#8221]()https://github.com/opensearch-project/OpenSearch/pull/8221)
-- [distribution/archives] [Linux] [x64] Provide the variant of the distributions bundled with JRE ([#8195]()https://github.com/opensearch-project/OpenSearch/pull/8195)
+- Start replication checkpointTimers on primary before segments upload to remote store. ([#8221](https://github.com/opensearch-project/OpenSearch/pull/8221))
```
Comment (kotwanikunal) [inline CHANGELOG.md:83]: You might hit into a conflict here with `2.x` backport. Better handle it with a separate PR?

File: server/src/main/java/org/opensearch/action/get/TransportGetAction.java [hunk 7]
```diff
@@ -88,16 +91,37 @@ protected boolean resolveIndex(GetRequest request) {
...
+                .getSettings()
+                .get(IndexMetadata.SETTING_REPLICATION_TYPE)
+                .equals(ReplicationType.SEGMENT.toString())
+                && request.request().realtime()
+                && request.request().routing() == null
+                && request.request().preference() == null) {
+                return true;
+            }
+        } catch (NullPointerException e) {
+            return false;
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/action/get/TransportGetAction.java:110]: Can we do specific `null` checks here instead of catching the NPE and returning? We might miss edge cases here where the preference will not be applied and we wouldn't necessarily know why. It can become a source of flakiness.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 8]
```diff
@@ -1438,4 +1450,161 @@ public void testRestartPrimary_NoReplicas() throws Exception {
...
+        assertTrue(response.isExists());
+        assertThat(response.getIndex(), equalTo(INDEX_NAME));
+        assertThat(response.getSourceAsMap().get("foo").toString(), equalTo("bar"));
+    }
+
+    public void testRealtimeGetRequestsUnsuccessful() {
+        final String primary = internalCluster().startDataOnlyNode();
+        final String replica = internalCluster().startDataOnlyNode();
+
+        assertAcked(
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1492]: In this test and in the other, I think we need to create the index after creating the primary node to guarantee which node holds which shard.  Otherwise either can contain the primary.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 9]
```diff
@@ -1438,4 +1450,161 @@ public void testRestartPrimary_NoReplicas() throws Exception {
...
+            prepareCreate(INDEX_NAME).setSettings(
+                Settings.builder().put("index.refresh_interval", -1).put(indexSettings()).put(IndexMetadata.SETTING_NUMBER_OF_SHARDS, 2)
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1494]: Can you pls add a comment on why setting the interval is required?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 10]
```diff
@@ -1438,4 +1450,161 @@ public void testRestartPrimary_NoReplicas() throws Exception {
...
+            .get();
+        assertThat(mgetResponse.getResponses().length, is(2));
+        assertThat(mgetResponse.getResponses()[0].getIndex(), is(INDEX_NAME));
+        assertFalse(mgetResponse.getResponses()[0].getResponse().isExists());
+
+        assertThat(mgetResponse.getResponses()[1].getIndex(), is("nonExistingIndex"));
+        assertTrue(mgetResponse.getResponses()[1].isFailed());
+
+        // realtime multi get 1 (routing set)
+        mgetResponse = client().prepareMultiGet()
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1599]: This could still hit primary first

File: server/src/main/java/org/opensearch/action/get/TransportMultiGetAction.java [hunk 11]
```diff
@@ -75,6 +78,28 @@ public TransportMultiGetAction(
         this.indexNameExpressionResolver = resolver;
     }
 
+    /**
+     * Returns true if MultiGet request should be routed to primary shards, else false.
+     */
+    boolean isPrimaryBasedRouting(MultiGetRequest request, MultiGetRequest.Item item) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/action/get/TransportMultiGetAction.java:84]: nit - This is largely identical to the other method, can we extract this to a common place and pass in the item/realtime params?  Or at least the SR enabled check?

Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/action/get/TransportMultiGetAction.java:84]: Tried to look into this, but only common base class is TransportAction<Request, Response> which doesn't have access to clusterService which I don't think we should be passing in as an argument.

File: server/src/main/java/org/opensearch/action/get/TransportGetAction.java (hunk 5 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/action/get/TransportGetAction.java:111]: (1) is covered by tests in SegmentReplicationIT testing realtime get and multi get requests. (2) is covered by existing tests in GetActionIT.

File: server/src/main/java/org/opensearch/action/get/TransportGetAction.java [hunk 12]
```diff
@@ -88,16 +92,32 @@ protected boolean resolveIndex(GetRequest request) {
...
+                    .equals(ReplicationType.SEGMENT)
+            )
+            .orElse(false);
+    }
+
+    /**
+     * Returns true if GET request should be routed to primary shards, else false.
+     */
+    protected boolean isPrimaryBasedRouting(ClusterState state, GetRequest request, String indexName) {
+        return request.realtime() && request.preference() == null && isSegmentReplicationEnabled(state, indexName);
```
Comment (mch2) [inline server/src/main/java/org/opensearch/action/get/TransportGetAction.java:108]: nit - for the vast majority of requests realtime will be true & preference will not be set - lets check the SR setting first to avoid the redundant checks?

Can we also make this static and take boolean realtime and preference as params so we can reuse this in mget?  Will also be easier to test.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 13]
```diff
@@ -1440,4 +1452,177 @@ public void testRestartPrimary_NoReplicas() throws Exception {
...
+        assertThat(mgetResponse.getResponses()[0].getResponse().getSourceAsMap().get("foo").toString(), equalTo("bar"));
+
+        assertThat(mgetResponse.getResponses()[1].getIndex(), is(INDEX_NAME));
+        assertFalse(mgetResponse.getResponses()[1].isFailed());
+        assertThat(mgetResponse.getResponses()[1].getResponse().getSourceAsMap().get("foo2").toString(), equalTo("bar2"));
+
+        assertThat(mgetResponse.getResponses()[2].getIndex(), is("nonExistingIndex"));
+        assertTrue(mgetResponse.getResponses()[2].isFailed());
+        assertThat(mgetResponse.getResponses()[2].getFailure().getMessage(), is("no such index [nonExistingIndex]"));
+        assertThat(
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1581]: nit - this is redundant given you check failure message already.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 14]
```diff
@@ -1440,4 +1452,177 @@ public void testRestartPrimary_NoReplicas() throws Exception {
...
+        assertTrue(mgetResponse.getResponses()[1].isFailed());
+
+        // realtime multi get 1 (routing set)
+        mgetResponse = client(replica).prepareMultiGet()
+            .add(new MultiGetRequest.Item(INDEX_NAME, "1").routing(routingOtherShard))
+            .add(new MultiGetRequest.Item("nonExistingIndex", "1"))
+            .get();
+        assertThat(mgetResponse.getResponses().length, is(2));
+        assertThat(mgetResponse.getResponses()[0].getIndex(), is(INDEX_NAME));
+        assertFalse(mgetResponse.getResponses()[0].getResponse().isExists());
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1623]: please add a comment why this does not exist - in that you are explicitly routing the req to a different shard ID.

File: server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java [hunk 15]
```diff
@@ -0,0 +1,253 @@
...
+    private static ThreadPool threadPool;
+    private static TransportService transportService;
+    private static ClusterService clusterService;
+
+    private static ClusterService clusterService2;
+    private static TransportGetAction transportAction;
+
+    @BeforeClass
+    public static void beforeClass() throws Exception {
+        threadPool = new TestThreadPool(TransportGetActionTests.class.getSimpleName());
```
Comment (mch2) [inline server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java:87]: I think we can reduce a lot of this boilerplate setup by making a static method that returns the preference to set.

File: server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java [hunk 16]
```diff
@@ -0,0 +1,108 @@
...
+
+import static org.opensearch.common.UUIDs.randomBase64UUID;
+
+public class TransportGetActionTests extends OpenSearchTestCase {
+
+    private static ClusterState clusterState;
+    private static ClusterState clusterState2;
+
+    @BeforeClass
+    public static void beforeClass() throws Exception {
```
Comment (andrross) [inline server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java:55]: FYI, prefer `@Before` and non-static fields. In general it is better to have instance state that is not shared between test executions to avoid problems with tests interfering with one another.

However, in this case I think you can create a `private static ClusterState clusterState(ReplicationType)` static method and then create the cluster state on-demand for each test case below. That will also solve the problem of the unhelpfully named field `clusterState2` because you can replace it with `clusterState(ReplicationType.DOCUMENT)` :)

File: server/src/main/java/org/opensearch/action/get/TransportGetAction.java [hunk 17]
```diff
@@ -88,16 +92,32 @@ protected boolean resolveIndex(GetRequest request) {
...
+                indexMetadata -> ReplicationType.parseString(indexMetadata.getSettings().get(IndexMetadata.SETTING_REPLICATION_TYPE))
+                    .equals(ReplicationType.SEGMENT)
+            )
+            .orElse(false);
+    }
+
+    /**
+     * Returns true if GET request should be routed to primary shards, else false.
+     */
+    protected static boolean isPrimaryBasedRouting(ClusterState state, boolean realtime, String preference, String indexName) {
```
Comment (andrross) [inline server/src/main/java/org/opensearch/action/get/TransportGetAction.java:107]: Nitpick, `forcePrimaryBasedRouting` or `shouldForcePrimaryRouting` or similar is probably better.

File: server/src/main/java/org/opensearch/action/get/TransportGetAction.java [hunk 18]
```diff
@@ -88,16 +92,32 @@ protected boolean resolveIndex(GetRequest request) {
...
+        return isSegmentReplicationEnabled(state, indexName) && realtime && preference == null;
+    }
+
     @Override
     protected ShardIterator shards(ClusterState state, InternalRequest request) {
+        String preference = request.request().preference();
```
Comment (andrross) [inline server/src/main/java/org/opensearch/action/get/TransportGetAction.java:113]: Nitpick, but assigning variables exactly once is often more readable and less error prone, e.g.:

```
final String preference;
if (isPrimary...) {
    preference = PRIMARY;
} else {
    preference = request.request().preference();
}
```
```

File: server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java (hunk 16 above)
Comment (Poojita-Raj) [reply server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java]: Thanks for the review @andrross! :) Made the changes as suggested

**Review by mch2 — APPROVED** [review]

**Review by Rishikesh1159 — APPROVED** [review]
