### PR TITLE
Flat object field use IndexOrDocValuesQuery to optimize query

### LINKED ISSUE #11635: [BUG] Flat object field should delegate to keyword field for most query types
**Describe the bug**
The flat object field type currently reimplements most of the query-generation methods with code that was copied from KeywordField. Since then, KeywordField had changes to support dynamically switching between indexed fields and doc values to implement these query types, based on which is likely to be more efficient.

Since the flat object field is implemented with a pair of KeywordFields under the hood, we should just ask those fields to create their own darned queries, which will do the correct, optimized thing, and reduce code duplication.

### PR DESCRIPTION
**Pull request by kkewwei**
### Description
The pr mainly support the two features: 
1.flat object field use IndexOrDocValuesQuery to optimize query.
2.flat object field delegate to keyword field to reduce code duplication.

### Related Issues
Resolves #11635 #11537

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java [hunk 1]
```diff
@@ -89,46 +144,780 @@ public void testRewriteValue() {
...
+            );
+            assertEquals(
+                "Cannot search on field [field._valueAndPath] since it is both not indexed, and does not have doc_values " + "enabled.",
+                e.getMessage()
+            );
+        }
+    }
+
+    public void testFuzzyQuery() {
+        // 1.test isSearchable=true, hasDocValues=true, mappedFieldTypeName=null
```
Comment (kkewwei) [inline server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java:661]: after the #14378 being merged, I will cancel the test code comment.

**Comment by kkewwei** [comment]
After #13853 is merged, the pr can be merged later.

**Comment by harshavamsi** [comment]
@kkewwei looks like a bunch of `flat_object` tests are failing. I can review once we have green gradle!

**Comment by kkewwei** [comment]
@harshavamsi PTAL.

File: server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java [hunk 2]
```diff
@@ -502,8 +586,12 @@ public Query existsQuery(QueryShardContext context) {
                 searchKey = this.mappedFieldTypeName;
                 searchField = name();
             } else {
-                searchKey = FieldNamesFieldMapper.NAME;
-                searchField = name();
+                if (hasDocValues()) {
+                    return new FieldExistsQuery(name());
```
[the remark this answers is not in the document]
Comment (kkewwei) [reply server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java:590]: if `doc_values` is true:
1. The `hasDocValues` of `KeywordFieldType` is false(line 160), in `ValueFieldMapper.addField`(line 838).
2. `fieldType().hasDocValues() == false` will be false, we will not call `createFieldNamesField(context)`.
So `Field(_field_names->fieldName)` will not created, in this way, we have to use `DocValuesField`.

[the remark this answers is not in the document]
Comment (harshavamsi) [reply server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java:591]: thanks!

**Comment by harshavamsi** [comment]
@kkewwei can you add an entry in CHANGELOG.md?

**Comment by kkewwei** [comment]
it seems something wrong, the origin ci log can't be find.

**Comment by kkewwei** [comment]
https://build.ci.opensearch.org/blue/organizations/jenkins/gradle-check/detail/gradle-check/41936/pipeline

**Comment by kkewwei** [comment]
@harshavamsi please have a another look.

**Review by harshavamsi — APPROVED** [review]
LGTM! @reta @msfroh @andrross take a look and merge?

**Comment by reta** [comment]
> LGTM! @reta @msfroh @andrross take a look and merge?

Sorry @harshavamsi , not sure how did I miss it, do you think we should align the change with your https://github.com/opensearch-project/OpenSearch/pull/15012? Thanks!

**Comment by harshavamsi** [comment]
> > LGTM! @reta @msfroh @andrross take a look and merge?
> 
> Sorry @harshavamsi , not sure how did I miss it, do you think we should align the change with your #15012? Thanks!

Yes, it is better to rebase this change onto #15012 once that is merged

**Comment by kkewwei** [comment]
@harshavamsi @reta please have a another look when you are free.

File: server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java [hunk 3]
```diff
@@ -395,19 +399,21 @@ public Query termsQuery(List<?> values, QueryShardContext context) {
                 if (!context.keywordFieldIndexOrDocValuesEnabled()) {
                     return super.termsQuery(values, context);
                 }
-                BytesRef[] bytesRefs = new BytesRef[values.size()];
-                for (int i = 0; i < bytesRefs.length; i++) {
-                    bytesRefs[i] = indexedValueForSearch(values.get(i));
+                BytesRef[] iBytesRefs = new BytesRef[values.size()];
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java:402]: This change does not look right: we only need to the rewrite for doc values when doc values are enabled ( hasDocValues()).

**Comment by reta** [comment]
@msfroh could you please take a look? seems like the one of your interest :-)

File: server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java [hunk 4]
```diff
@@ -221,18 +254,27 @@ public FlatObjectFieldType(String name, NamedAnalyzer analyzer) {
...
                 false,
-                true,
+                hasDocValues,
                 new TextSearchInfo(Defaults.FIELD_TYPE, null, Lucene.KEYWORD_ANALYZER, Lucene.KEYWORD_ANALYZER),
                 Collections.emptyMap()
             );
             this.ignoreAbove = Integer.MAX_VALUE;
             this.nullValue = null;
             this.mappedFieldTypeName = mappedFieldTypeName;
+            this.valueFieldType = valueFieldType;
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java:276]: The way the `valueFieldType` and `alueAndPathFieldType` are assigned is through setters, we should stick to the same strategy everywhere: use either setters or constructors. Otherwise it is very hard to trace what the exact values will be.

File: server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java [hunk 5]
```diff
@@ -132,16 +133,42 @@ private ValueFieldMapper buildValueFieldMapper(BuilderContext context, FieldType
...
+                @Override
+                protected BytesRef indexedValueForSearch(Object value) {
+                    return fft.indexedValueForSearch(value);
+                }
+
+                @Override
+                protected String rewriteForDocValue(Object value) {
+                    assert value instanceof String;
+                    return fullName + DOT_SYMBOL + value;
+                }
```
Comment (msfroh) [inline server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java:158]: Can you add a comment to explain why we need this override?

Looking down at `parseValueAddFields`, it looks like the DV field should already be called `fullName + valueType`, and the value should just be the `value`, right? But I'm sure that's not the case or you wouldn't have done this. It's a bit confusing. (I'm guessing the confusing part already existed and you're just adapting to it.)

I guess the idea is that we need to turn a query for `flat.my.full.path:foo` into a query for `flat._valueAndPath:my.full.path=foo`, but that doesn't seem to be what's happening here.

File: server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java [hunk 6]
```diff
@@ -192,20 +219,26 @@ public static final class FlatObjectFieldType extends StringFieldType {
...
         private KeywordFieldMapper.KeywordFieldType valueAndPathFieldType;
 
-        public FlatObjectFieldType(String name, boolean isSearchable, boolean hasDocValues, Map<String, String> meta) {
-            super(name, isSearchable, false, true, TextSearchInfo.SIMPLE_MATCH_ONLY, meta);
+        public FlatObjectFieldType(
+            String name,
+            String mappedFieldTypeName,
+            boolean isSearchable,
+            boolean hasDocValues,
+            Map<String, String> meta
```
Comment (msfroh) [inline server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java:227]: Now that `isSearchable` and `hasDocValues` are not hard-coded, could you please add the parsing logic for them? That way someone could add a `flat_object` field type and give it doc values or make it indexed, or both. (The default, for backward compatibility, should be indexed + doc values.)

File: server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java [hunk 7]
```diff
@@ -636,69 +727,57 @@ private void parseValueAddFields(ParseContext context, String value, String fiel
 
         if (fieldType.indexOptions() != IndexOptions.NONE || fieldType.stored()) {
             // convert to utf8 only once before feeding postings/dv/stored fields
-
             final BytesRef binaryValue = new BytesRef(fieldType().name() + DOT_SYMBOL + value);
-            Field field = new FlatObjectField(fieldType().name(), binaryValue, fieldType);
 
             if (fieldType().hasDocValues() == false && fieldType.omitNorms()) {
                 createFieldNamesField(context);
             }
```
Comment (msfroh) [inline server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java:734]: I just realized that the `omitNorms()` part of this doesn't make a lot of sense. 

Do we ever have norms for flat object fields? We probably shouldn't. I don't think we can rationally do relevance calculations over a flat object field. I think this was a bad copy-paste from `KeywordFieldMapper` that we missed.

**Review by msfroh — COMMENTED** [review]
Thanks a lot @kkewwei for this large effort! This should make flat_object field type much more useful, especially if users can enable/disable doc values and indexing.

After you make indexed/doc-values configurable, can you please add some YAML tests to confirm that things work in the indexed-only, doc-values-only, and both cases? (@harshavamsi did something similar when he added support for DV search to keyword fields. You might even be able to copy his tests then push the values into a `flat_object` field.)

In theory, a future step would be to allow more flexibility on the value field type. For example, it could be a full-text field that tokenizes its values, to let people do text search across a whole JSON sub-document. Alternatively, it could be a WildcardField, to support more efficient wildcard/regex matching. I don't think we can do better than keyword matches on the valueAndPath field, though.

File: server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java (hunk 5 above)
Comment (kkewwei) [reply server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java:158]: Yes, you are right, I have to  be compatible with the previously unreasonable `value`, but I cannot modify it directly, otherwise the previous flat_object query will fail.

For example, when dealing with `_valueAndPath`, the input `value` is :  `my.full.path=foo`, when stored in DV, the `binaryValue` becomes `my.full.path.my.full.path=foo`

https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java#L640

I think we should change it in another new pr by the version control.

File: server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java (hunk 6 above)
Comment (kkewwei) [reply server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java:227]: It will by solved by the pr: https://github.com/opensearch-project/OpenSearch/pull/13853

File: server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java (hunk 7 above)
Comment (kkewwei) [reply server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java:734]: it 's good idea, I will remove the `omitNorms`.

File: server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java (hunk 3 above)
Comment (kkewwei) [reply server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java:402]: I don't quite understand what you mean, could you please describe more detail?

**Comment by kkewwei** [comment]
> Thanks a lot @kkewwei for this large effort! This should make flat_object field type much more useful, especially if users can enable/disable doc values and indexing.
> 
> After you make indexed/doc-values configurable, can you please add some YAML tests to confirm that things work in the indexed-only, doc-values-only, and both cases? (@harshavamsi did something similar when he added support for DV search to keyword fields. You might even be able to copy his tests then push the values into a `flat_object` field.)
> 
> In theory, a future step would be to allow more flexibility on the value field type. For example, it could be a full-text field that tokenizes its values, to let people do text search across a whole JSON sub-document. Alternatively, it could be a WildcardField, to support more efficient wildcard/regex matching. I don't think we can do better than keyword matches on the valueAndPath field, though.

Of course.  I will add YAML.

**Comment by kkewwei** [comment]
@reta @msfroh, By the way, if we should support `wildcardQuery` in the flat_object field? it will only work on the `_value` 
 and `_valueAndPath` value, not the whole JSON.

File: server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java (hunk 3 above)
Comment (reta) [reply server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java:402]: Yeah, non-issue here :) sorry about the confusion

**Comment by reta** [comment]
> @reta @msfroh, By the way, if we should support `wildcardQuery` in the flat_object field? it will only work on the `_value` and `_valueAndPath` value, not the whole JSON.

Thanks @kkewwei , I think that could be useful even with the limitation you mentioned

**Comment by msfroh** [comment]
> > @reta @msfroh, By the way, if we should support `wildcardQuery` in the flat_object field? it will only work on the `_value` and `_valueAndPath` value, not the whole JSON.
> 
> 
> 
> Thanks @kkewwei , I think that could be useful even with the limitation you mentioned

Definitely! 

I'm not even sure if would be possible to use non-keyword types on `_valueAndPath` without exploding the term dictionary. We'd basically have to prepend the path to every token produced by analyzing the value. I implemented something like that years ago, but that system could guarantee that the number of tokens was "reasonable". If we did decide to implement something like that, we'd probably want a bound on the max number of tokens produced.

**Comment by kkewwei** [comment]
> > > @reta @msfroh, By the way, if we should support `wildcardQuery` in the flat_object field? it will only work on the `_value` and `_valueAndPath` value, not the whole JSON.
> > 
> > 
> > Thanks @kkewwei , I think that could be useful even with the limitation you mentioned
> 
> Definitely!
> 
> I'm not even sure if would be possible to use non-keyword types on `_valueAndPath` without exploding the term dictionary. We'd basically have to prepend the path to every token produced by analyzing the value. I implemented something like that years ago, but that system could guarantee that the number of tokens was "reasonable". If we did decide to implement something like that, we'd probably want a bound on the max number of tokens produced.

@msfroh Thanks for you comment.

In the #13853, I'm plan to add parameter:`depth_limit`, which allow to set maximum depth limitation to the JSON document, I'm not sure whether it can meet the requirements?

**Comment by msfroh** [comment]
> In the #13853, I'm plan to add parameter:`depth_limit`, which allow to set maximum depth limitation to the JSON document, I'm not sure whether it can meet the requirements?

I'm more concerned about the number of tokens produced by value side of things.

Suppose we have a dot-path like the following:

```
"flat.my.dot.value": "Here is some text"
```

If we want to support full-text search on that field, using StandardAnalyzer, I think we would translate `{"term":{"flat.my.dot.value":"some"}}` into essentially `{"term":{"flat._valueAndPath":"flat.my.dot.value=text"}}`, which is what we already do.

For that to work, at indexing time, we would run the analyzer on the value, and write the following tokens to `flat._valueAndPath`:

```
my.dot.value=here
my.dot.value=is
my.dot.value=some
my.dot.value=text
```

Essentially, every token for every path needs to be added. It can work (and it definitely did work when I did it 11 years ago), but we might need to be careful.

Anyway, I'll write up a proposal for adding analyzer support to flat object fields. I can dig up some details from that old project.

File: server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java (hunk 5 above)
Comment (kkewwei) [reply server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java]: @msfroh, If we should simple the dv values?

**Comment by kkewwei** [comment]
> FAILURE

SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes #16015

**Comment by kkewwei** [comment]
> ❌ Gradle check result for [d7c880f](https://github.com/opensearch-project/OpenSearch/commit/d7c880f9129c742b0a1c1de69dcea44acbed4460): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/48423/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes https://github.com/opensearch-project/OpenSearch/issues/16015

**Comment by kkewwei** [comment]
> ❌ Gradle check result for [6b21e8b](https://github.com/opensearch-project/OpenSearch/commit/6b21e8b4f58728061d1c5bb45079bfe0132b9af7): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/48598/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?
 
SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes #16015

File: server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java (hunk 5 above)
Comment (msfroh) [reply server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java]: Yeah -- we need to maintain backward compatibility, but I like the this simplification and the ones suggested by @bugmakerrrrrr in https://github.com/opensearch-project/OpenSearch/issues/16061.

I'm going to suggest that we "fork" flat object to keep the behavior before 2.18, then we apply all of these (backward-incompatible) improvements on indices created with 2.18 and later.

File: rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml [hunk 8]
```diff
@@ -0,0 +1,788 @@
...
+                    order: "order8"
+                  }
+                },
+                {
+                  fuzzy: {
+                    issue.labels.name: {
+                      value: "abcx",
+                      fuzziness: 1
+                    }
+                  }
```
Comment (msfroh) [inline rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml:460]: I'm kind of curious about this one. If you did a fuzzy query on `issue.labels.namx` for `abc8`, would it match? 

Unless I'm mistaken, it converts to a fuzzy query on `issue.labels._valueAndPath` for `namx=abc8`, which I think would match. Given that such a false positive is relatively unlikely, I'm wondering if we could use a `TwoPhaseIterator` to filter them out (without adding too much cost to the true positives).

I wouldn't treat it as a blocker for this PR, but we might want to document it as a known issue if we ship it with fuzzy matches on the dot path.

**Review by msfroh — COMMENTED** [review]
Overall, this is looking pretty good to me. Thanks @kkewwei!

I posted one question about the behavior of fuzzy query (though I guess it could apply to some of the other queries? Or maybe not. I think prefix, regexp, wildcard, and range queries all force the dot-path to match exactly.) I don't think it's a blocker, but I'm mostly curious to know if we can get possibly surprising behavior.

File: rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml (hunk 8 above)
Comment (kkewwei) [reply rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml:460]: @msfroh Yes, you are right, I tested that `abc8` can be match with the query `namx=abc8`.

That use `TwoPhaseIterator` to filter makes sense to me, If I fix it in the current pr, or create a new one?

Comment (kkewwei) [reply rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml:460]: @msfroh please help see if there are any other problems?

Comment (msfroh) [reply rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml:460]: Yeah -- I would definitely fix it in a different PR (if we choose to fix it at all). 

As is, I believe fuzzy query is not used very often, so I think we could get away with documenting it as a known issue for now.

**Review by msfroh — APPROVED** [review]

**Comment by msfroh** [comment]
Darn... auto-backport failed. Probably just a conflict on the changelog. 

@kkewwei, could you please open a manual backport PR?

**Comment by kkewwei** [comment]
> Darn... auto-backport failed. Probably just a conflict on the changelog.
> 
> @kkewwei, could you please open a manual backport PR?

Some of the previous commits are not backported, I will complete them and then backport this one.
