### PR TITLE
[Pull-based Ingestion] Fix poller bug and remove persisted pointers

### LINKED ISSUE #19591: [BUG] Fix duplicate or old message skipping logic in pull-based ingestion when versioning is not used
### Describe the bug

This bug is only applicable if versioning is not enabled and we rewind back in time. Though versioning is recommended, it is still possible to ingest without versions today.

If versioning is not used in pull-based ingestion and the streaming source pointer is rewinded back in time, it is possible to skip the latest available message for a document at that time.
1. Assume we have multiple versions of a document present in the stream, and all of them are persisted without versions.
2. If the consumer is explicitly rewinded back in time, to reprocess all the messages from step 1, messages determined to be duplicates (previously processed) are skipped.
3. The issue is the poller is only aware of latest offsets for a given document. This results in processing older messages while skipping the latest message for a given document.

More details will follow.
The fix: Remove persisted pointer concept and rely on versioning to ensure consistent view of docs on rewind. Pull-based ingestion will provide atleast once processing guarantee when versioning is not used.

### Related component

Indexing

### To Reproduce

Create pull-based index without versioning. Have multiple updates for a document. Rewind to early offset and ensure there is no new version of documents published after rewind. We will skip the latest available message known to the shard.

### Expected behavior

Reflect latest version of a document that is seen without skipping valid messages even if versioning is not used.

### Additional Details

**Plugins**
ingestion-kafka, ingestion-kinesis

### PR DESCRIPTION
**Pull request by varunbharadwaj**
### Description
This PR fixes the following bugs and inefficiencies.
1. Removes persisted pointer concept to fix correctness corner cases related to user initiated consumer rewind (as described in the linked issue) when versioning is not used. Pull-based ingestion will provide atleast-once processing guarantees. Versioning must be used to ensure consistent view of documents on rewind/replay, if eventually consistent view is not acceptable.
2. Set`auto.offset.reset` Kafka setting to `none` by default to throw errors on out-of-bounds offsets. This could be possible if the ingestion was paused and exceeds Kafka retention period. The user will be able to monitor consumer errors to identify this error and handle it accordingly. User still has the choice to set `auto.offset.reset` to earliest/latest.
3. Update the Kafka polling logic to remove batch size filtering. This prevents ingestion getting stuck, if user configures `auto.offset.reset` to earliest/latest and offset is out-of-bounds. Instead, the OpenSearch consumer setting `poll.max_batch_size` is used in place of `max.poll.records` for Kafka consumer initialization to control batch size. If `max.poll.records` is configured by user, it takes precedence.

### Related Issues
Resolves #19591

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/IngestionConsumerFactory.java [hunk 1]
```diff
@@ -22,16 +21,16 @@
 public interface IngestionConsumerFactory<T extends IngestionShardConsumer, P extends IngestionShardPointer> {
     /**
      * Initialize the factory with the configuration parameters. This method is called once when the factory is created,
-     * and the parameters are parsed from the {@link org.opensearch.cluster.metadata.IngestionSource} in
+     * and the required parameters are provided from the {@link org.opensearch.cluster.metadata.IngestionSource} in
      * {@link  org.opensearch.cluster.metadata.IndexMetadata}.
-     * @param params the configuration parameters to initialize the factory
+     * @param ingestionSource the ingestion source with configuration parameters to initialize the factory
      */
-    void initialize(Map<String, Object> params);
```
Comment (msfroh) [inline server/src/main/java/org/opensearch/index/IngestionConsumerFactory.java:29]: Good call -- Since `IngestionSource` holds both the universal pull-based ingestion parameters and the implementation-specific `params`, it makes sense to pass the full config to the factory.
