### PR TITLE
Make searchable snapshot indexes read-only but allow deletion

### LINKED ISSUE #4655: [Searchable Snapshots] Fail gracefully with proper error message for invalid operations (e.g. writes)
Searchable snapshot indexes are inherently read only. This goal of this task is to enumerate the operations that are invalid for a read-only searchable snapshot index, and then implement the behavior to respond with a proper error message. The concept of read-only indexes is not new in OpenSearch so existing capabilities may be able to be used here. This task does depend on #4138 to implement the initial framework that will be built upon.

The expected outcome of this task is the design for how this will be implemented. There are existing write block capabilities, but a perhaps important difference here is that the write blocks should not be able to be changed by the user for the life of this type of index, so that may be different than what the current capability allows for.

**Additional context**
- #2919

### PR DESCRIPTION
**Pull request by Vishalks**
Signed-off-by: Vishal Sarda <vsarda@amazon.com>

Co-author: @andrross 

### Description
The changes in this PR are made on top of https://github.com/opensearch-project/OpenSearch/pull/4680. This PR makes the index restored from remote snapshot as read only, but it can be deleted. The write blocks on this index continue to be applicable even when explicitly set to false by user using `"index.blocks.read_only_allow_delete": false`. For any operations other than read on such an index, we throw an unsupported exception.

### Issues Resolved
#4655 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/snapshots/RestoreService.java [hunk 1]
```diff
@@ -1227,6 +1227,7 @@ private static IndexMetadata addSnapshotToIndexSettings(IndexMetadata metadata,
             .put(IndexSettings.SEARCHABLE_SNAPSHOT_ID_UUID.getKey(), snapshot.getSnapshotId().getUUID())
             .put(IndexSettings.SEARCHABLE_SNAPSHOT_ID_NAME.getKey(), snapshot.getSnapshotId().getName())
             .put(IndexSettings.SEARCHABLE_SNAPSHOT_INDEX_ID.getKey(), indexId.getId())
+            .put(IndexMetadata.APIBlock.READ_ONLY_ALLOW_DELETE.settingName(), true)
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/snapshots/RestoreService.java:1230]: With DiskThresholdDecider be able to revert this?

File: server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java [hunk 2]
```diff
@@ -356,6 +357,7 @@ public void onNewInfo(ClusterInfo info) {
         final Set<String> indicesToAutoRelease = StreamSupport.stream(state.routingTable().indicesRouting().spliterator(), false)
             .map(c -> c.key)
             .filter(index -> indicesNotToAutoRelease.contains(index) == false)
+            .filter(index -> !state.getMetadata().settings().get(IndexModule.INDEX_STORE_TYPE_SETTING.getKey()).equals(IndexModule.Type.REMOTE_SNAPSHOT.getSettingsKey()))
```
Comment (Vishalks) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java:360]: @Bukhtawar I have added this so that disk threshold monitor filters out index backed by remote snapshot from list of indices to be released, but currently I can't find a way to test it locally (discussed more details on slack). Can you suggest a way to test this in run time (somehow the monitor selects some indices to auto release but not the remote ones)?

**Comment by andrross** [comment]
Looks like a test failure related to this change: https://build.ci.opensearch.org/job/gradle-check/4913/testReport/junit/org.opensearch.index.reindex/DeleteByQueryBasicTests/testDeleteByQueryOnReadOnlyAllowDeleteIndex/

Looking at the log I found this:

```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.opensearch.common.settings.Settings.get(String)" is null
	at org.opensearch.cluster.routing.allocation.DiskThresholdMonitor.lambda$onNewInfo$4(DiskThresholdMonitor.java:360) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
```

File: server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java (hunk 2 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java:360]: Can we explore using a separate block so that concerns are separate and we don't run into each other?

**Comment by andrross** [comment]
Can you add some tests? Maybe some additional tests to SearchableSnapshotIT

**Comment by andrross** [comment]
The problem with this approach is that the following operation works and will undo this setting:

```
PUT my_index/_settings
{
    "index": {
        "blocks.write": false
    }
}
```

I think _some_ setting changes make sense for searchable snapshots and others don't. A reasonable approach is probably to block all setting changes initially for searchable snapshots and then work through the design and implementation of allowing particular operations where appropriate. That is the ultimate goal of issue #4655.

**Comment by Vishalks** [comment]
> The problem with this approach is that the following operation works and will undo this setting:
> 
> ```
> PUT my_index/_settings
> {
>     "index": {
>         "blocks.write": false
>     }
> }
> ```
> 
> I think _some_ setting changes make sense for searchable snapshots and others don't. A reasonable approach is probably to block all setting changes initially for searchable snapshots and then work through the design and implementation of allowing particular operations where appropriate. That is the ultimate goal of issue #4655.

Isn't that API allowed to be only called by the admin? If yes, letting admin tweak the index settings seems reasonable to me.

**Comment by andrross** [comment]
> Isn't that API allowed to be only called by the admin? If yes, letting admin tweak the index settings seems reasonable to me.

A searchable snapshot index cannot be writable, so it's wrong to let the API block be removed, admin or not. There's a whole host of settings that don't apply to an inherently read-only index.

**Comment by Vishalks** [comment]
> > Isn't that API allowed to be only called by the admin? If yes, letting admin tweak the index settings seems reasonable to me.
> 
> A searchable snapshot index cannot be writable, so it's wrong to let the API block be removed, admin or not. There's a whole host of settings that don't apply to an inherently read-only index.

I assumed that since #4655 mentions 'user should not be able to change index settings', letting them affected through admin should be fine (admin > user). Seems like it's not the case.

**Comment by scrawfor99** [comment]
Hi @Vishalks, I am reaching out from the security team to check in and see if there was anything you may need from our end. I have been going to through active issues tagged for the upcoming release and trying to check in with any that look like they may brush with us. Let me know if you need anything from us.

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java [hunk 3]
```diff
@@ -104,6 +109,76 @@ public void testCreateSearchableSnapshot() throws Exception {
...
+        createRepository("test-repo", "fs");
+        createIndex(
+            indexName,
+            Settings.builder()
+                .put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, "0")
+                .put(IndexMetadata.SETTING_NUMBER_OF_SHARDS, "1")
+                .build()
+        );
+        ensureGreen();
+        indexRandomDocs("test-idx-1", 100);
```
Comment (andrross) [inline server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java:124]: Should use `indexName` here. Or remove this line. It's probably not necessary to index any documents.

File: CHANGELOG.md [hunk 4]
```diff
@@ -31,6 +31,7 @@ Inspired from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
 - Add a new node role 'search' which is dedicated to provide search capability ([#4689](https://github.com/opensearch-project/OpenSearch/pull/4689))
 - Introduce experimental searchable snapshot API ([#4680](https://github.com/opensearch-project/OpenSearch/pull/4680))
 - Recommissioning of zone. REST layer support. ([#4624](https://github.com/opensearch-project/OpenSearch/pull/4604))
+- Make the index restored by remote snapshot as read only but allow deletion ([#4764](https://github.com/opensearch-project/OpenSearch/pull/4764))
```
Comment (andrross) [inline CHANGELOG.md:34]: "index restored by remote snapshot" is an accurate of normal snapshot restores as well so this should probably be more descriptive. Something like "Make searchable snapshot indexes read-only but allow deletion".

Comment (Vishalks) [reply CHANGELOG.md]: Updated PR description

**Comment by kotwanikunal** [comment]
```
rg.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT > testLuceneVersionConstant FAILED
    java.lang.AssertionError: 
    Expected: <9.4.1>
         but: was <9.4.0>
        at __randomizedtesting.SeedInfo.seed([4E6DBD0DFC297DE6:C3088051DB21BEAF]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant(VerifyVersionConstantsIT.java:56)
```

@Vishalks can you please rebase the commit?

**Review by andrross — APPROVED** [review]
