### PR TITLE
Fix SegmentReplicationUsingRemoteStoreIT.testReplicaHasDiffFilesThanPrimary.

### LINKED ISSUE #7643: [BUG] org.opensearch.remotestore.SegmentReplicationRemoteStoreIT.testReplicaHasDiffFilesThanPrimary is flaky
#### Describe the bug
org.opensearch.remotestore.SegmentReplicationRemoteStoreIT.testReplicaHasDiffFilesThanPrimary is flaky
```
  2> java.lang.AssertionError: timed out waiting for green state
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1002)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:933)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:922)
        at org.opensearch.indices.replication.SegmentReplicationIT.testReplicaHasDiffFilesThanPrimary(SegmentReplicationIT.java:780)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
.
.
.
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=84, name=opensearch[node_t3][generic][T#1], state=RUNNABLE, group=TGRP-SegmentReplicationRemoteStoreIT]

        Caused by:
        java.lang.AssertionError: file (name [segment_infos_snapshot_filename__3], reused [false], length [395], recovered [477])
            at __randomizedtesting.SeedInfo.seed([E05CF3CB304D9302]:0)
            at org.opensearch.index.shard.StoreRecovery$StatsDirectoryWrapper.copyFrom(StoreRecovery.java:316)
            at org.opensearch.index.shard.IndexShard.syncSegmentsFromRemoteSegmentStore(IndexShard.java:4520)
            at org.opensearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:248)
            at org.opensearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:604)
            at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806)
            at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)                                                                                      at java.base/java.lang.Thread.run(Thread.java:1589)
```

#### To Reproduce
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.SegmentReplicationRemoteStoreIT.testReplicaHasDiffFilesThanPrimary" -Dtests.seed=E05CF3CB304D9302 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-CA -Dtests.timezone=Asia/Kolkata -Druntime.java=19
```

#### Additional Context
https://build.ci.opensearch.org/job/gradle-check/15752/consoleFull

### PR DESCRIPTION
**Pull request by mch2**
### Description
This test is failing in two ways.
First it fails when copying segments from the remote store and there is a cksum mismatch. In this case it is not guaranteed the directory implementation will replace the existing file when copying from the store.  This change ensures the mismatched file is cleaned up but only if the shard is not serving reads.  In that case we fail the shard so it is re-recovered rather than deleting the segment underneath it.

This test also fails with a divide by 0 in RemoteStoreRefreshListener.

### Related Issues
Resolves #7643 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 1]
```diff
@@ -4809,6 +4809,14 @@ private boolean localDirectoryContains(Directory localDirectory, String file, lo
                 return true;
             } else {
                 logger.warn("Checksum mismatch between local and remote segment file: {}, will override local file", file);
+                // If there is a checksum mismatch and we are not serving reads it is safe to go ahead and delete the file now.
+                // Outside of engine resets this method will be invoked during recovery so this is safe.
+                if (isReadAllowed() == false) {
+                    localDirectory.deleteFile(file);
+                } else {
+                    // segment conflict with remote store while the shard is serving reads.
+                    failShard("Local copy of segment " + file + " has a different checksum than the version in remote store", null);
```
Comment (linuxpi) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:4818]: are we affecting the availability here by failing the shard in case the directory implementation was going to replace the local file?

Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:4818]: 1. With node-node segment replication, when there is difference in store metadata b/w primary and replica, we fail the replica shard. With this change, we allow the file to be overridden when it serves read. Why do we have special handling for remote store ? Is checksum mis-match state a norm under some edge-case scenario.
2. With refactor work in https://github.com/opensearch-project/OpenSearch/pull/8767 we are moving the file download logic inside `RemoteStoreReplicationSource` and diff calculation inside `SegmentReplicationTarget`. With this, we may not need to change this method considering this change is intended only for round of segment replication (I understand it is based on failing IT).

Comment (mch2) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:4818]: @linuxpi - The idea here is to treat this as a corruption case and reset safely to the source of truth which is the remote store.  So yes this could cause an availability hit, the alternative is deleting the file manually while the engine is active and serving reads which I think is more dangerous and would result in corruption elsewhere.

With this flow the only time this should ever hit is if we are doing an engine reset with `resetEngineToGlobalCheckpoint` upon failover.  During that method the new primary syncs with the remote store to pick up where the previous primary left off.  If the replica has a conflicting segment from somewhere we need to treat it as a corruption case.  ll other invocations here the shard is not yet recovered (peer/store recovery).

This is also why it is critical for us to perform cksum validation on upload/download and to introduce features like point in time restore so we can catch and react to bit flips etc in the store.

@dreamer-89 After your refactor this method is still used with segrep in two places, during recovery and when opening/resetting the engine.  What I am proposing is we handle this case similarly in that we fail the shard if it is active & serving reads but overwrite if the shard is still recovering.

**Review by dreamer-89 — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 1 above)
Comment (ankitkala) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:4818]: I agree with the changes here.

**Review by ankitkala — APPROVED** [review]
