### PR TITLE
[Remote Store] Fix shard failure on flush due to upload timeout

### LINKED ISSUE #10924: [BUG] Shard fails on flush due to translog upload taking longer than 30s
**Describe the bug**
If there are connectivity issues with the configured remote store (or degraded remote store uploads) resulting in translog uploads taking longer than 30s, it leads in TimeoutException being thrown. This exception is later tried to be casted to RuntimeException which leads to ClassCastException which ultimately fails the shard.

**To Reproduce**
Induce connectivity issues with remote store.

**Expected behavior**
Transient connectivity issue should not lead to shard failure.

### PR DESCRIPTION
**Pull request by ashking94**
### Description
If there are connectivity issues with the configured remote store (or degraded remote store uploads) resulting in translog uploads taking longer than 30s, it leads in TimeoutException being thrown. This exception is later tried to be casted to RuntimeException which leads to ClassCastException which ultimately fails the shard.

### Related Issues
Resolves #10924

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
~- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
~- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by gbbafna — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java [hunk 1]
```diff
@@ -156,7 +156,7 @@ public boolean transferSnapshot(TransferSnapshot transferSnapshot, TranslogTrans
 
             try {
                 if (latch.await(TRANSFER_TIMEOUT_IN_MILLIS, TimeUnit.MILLISECONDS) == false) {
-                    Exception ex = new TimeoutException("Timed out waiting for transfer of snapshot " + transferSnapshot + " to complete");
+                    Exception ex = new TranslogUploadFailedException("Timed out waiting for transfer of snapshot " + transferSnapshot + " to complete");
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java:159]: can we add an IT for same ?

Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java]: Incorporated as UTs. It is a bit tricky to simulate the timeout in ITs.

**Comment by mch2** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29021/
> * **CommitID:** [310277c](https://github.com/opensearch-project/OpenSearch/commit/310277ced2b3fb6389eb34efebbababbbc1170fd)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

https://github.com/opensearch-project/OpenSearch/issues/10006
