### PR TITLE
Fix unassigned shard allocation for batch mode

### LINKED ISSUE #13702: [BUG] Node concurrent recoveries settings not being honoured.
### Describe the bug

Default/updated concurrency recovery settings (node_concurrent_recoveries, node_initial_primaries_recoveries) settings are not being honored and doesn’t have any effect on the recovery speed for clusters with batch mode enabled

This is happening because of the way we allocate unassigned shards in a batch. For a batch:
1. AllocationDeciders runs for all shards in the batch at once
2. For all eligible shards in the batch, shard state is update to initializing on the assigned node

https://github.com/opensearch-project/OpenSearch/blob/da3ab920fcd0f6a8f5dbfad5c87740261f355f14/server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java#L89-L113

Because the decider execution and update to the shard status is not happening together for a shard, the cluster state doesn't change after running deciders on the unassigned shards. ThrottlingAllocationDecider reads the cluster state to decide if a shard recovery can be started on the node or not by comparing ongoing recoveries on the node with configured value of recovery settings (node_concurrent_recoveries, node_initial_primaries_recoveries). So, when we run the allocation decision together for all shards in a batch, the decider doesn't account for the decisions made for the other shards in the batch and we end up initializing all shards at once.

Logs indicating the same:

```
[2024-05-16T03:14:58,926][DEBUG][o.o.c.r.a.d.ThrottlingAllocationDecider] [0f25c84a727840d82cb5a1c7c7bf368f] ThrottlingAllocationDecider decision, throttle: [false] primary recovery limit [4], primaries in recovery [0] invoked for [[search-1140][35], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=CLUSTER_RECOVERED], at[2024-05-16T03:13:47.416Z], delayed=false, allocation_status[deciders_throttled]]] on node [\{854244060761cf88c3b0c7ad6356b50b\}\{-wlVUFUHTHSJI6gwE2SPEw\}\{D_jWEub0TzewygP5S4af-Q\}\{10.212.77.62\}\{10.212.77.62:9300\}\{dir\}\

[2024-05-16T03:14:58,927][DEBUG][o.o.c.r.a.d.ThrottlingAllocationDecider] [0f25c84a727840d82cb5a1c7c7bf368f] ThrottlingAllocationDecider decision, throttle: [false] primary recovery limit [4], primaries in recovery [0] invoked for [[search-1962][15], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=CLUSTER_RECOVERED], at[2024-05-16T03:13:47.404Z], delayed=false, allocation_status[deciders_throttled]]] on node [\{854244060761cf88c3b0c7ad6356b50b\}\{-wlVUFUHTHSJI6gwE2SPEw\}\{D_jWEub0TzewygP5S4af-Q\}\{10.212.77.62\}\{10.212.77.62:9300\}\{dir\}\

[2024-05-16T03:14:58,928][DEBUG][o.o.c.r.a.d.ThrottlingAllocationDecider] [0f25c84a727840d82cb5a1c7c7bf368f] ThrottlingAllocationDecider decision, throttle: [false] primary recovery limit [4], primaries in recovery [0] invoked for [[test_latency_219][1], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=CLUSTER_RECOVERED], at[2024-05-16T03:13:47.399Z], delayed=false, allocation_status[deciders_throttled]]] on node [\{854244060761cf88c3b0c7ad6356b50b\}\{-wlVUFUHTHSJI6gwE2SPEw\}\{D_jWEub0TzewygP5S4af-Q\}\{10.212.77.62\}\{10.212.77.62:9300\}\{dir\}\

[2024-05-16T03:14:58,930][DEBUG][o.o.c.r.a.d.ThrottlingAllocationDecider] [0f25c84a727840d82cb5a1c7c7bf368f] ThrottlingAllocationDecider decision, throttle: [false] primary recovery limit [4], primaries in recovery [0] invoked for [[search-1058][5], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=CLUSTER_RECOVERED], at[2024-05-16T03:13:47.403Z], delayed=false, allocation_status[deciders_throttled]]] on node [\{854244060761cf88c3b0c7ad6356b50b\}\{-wlVUFUHTHSJI6gwE2SPEw\}\{D_jWEub0TzewygP5S4af-Q\}\{10.212.77.62\}\{10.212.77.62:9300\}\{dir\}\

[2024-05-16T03:14:58,932][DEBUG][o.o.c.r.a.d.ThrottlingAllocationDecider] [0f25c84a727840d82cb5a1c7c7bf368f] ThrottlingAllocationDecider decision, throttle: [false] primary recovery limit [4], primaries in recovery [0] invoked for [[search-1062][4], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=CLUSTER_RECOVERED], at[2024-05-16T03:13:47.401Z], delayed=false, allocation_status[deciders_throttled]]] on node [\{854244060761cf88c3b0c7ad6356b50b\}\{-wlVUFUHTHSJI6gwE2SPEw\}\{D_jWEub0TzewygP5S4af-Q\}\{10.212.77.62\}\{10.212.77.62:9300\}\{dir\}\
```

****

### Related component

Cluster Manager

### To Reproduce

1. Add belwo log line at [ThrottlingAllocationDecider.java#L179](https://github.com/opensearch-project/OpenSearch/blob/da3ab920fcd0f6a8f5dbfad5c87740261f355f14/server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java#L179)
`logger.debug(
                "ThrottlingAllocationDecider decision, throttle: [{}] primary recovery limit [{}]," +
                    " primaries in recovery [{}] invoked for [{}] on node [{}]",
                primariesInRecovery >= primariesInitialRecoveries,
                primariesInitialRecoveries,
                primariesInRecovery,
                shardRouting,
                node.node()
            );`
2. Launch a cluster with batch mode enabled and with shards more than the concurrent recoveries value.
3. Restart the cluster and check added log to see if throttling is working as expected or not

### Expected behavior

Number of ongoing shard recoveries on a node should adhere to the node concurrent recovery setting.

### Additional Details

**OpenSearch Version**: 2.14

### PR DESCRIPTION
**Pull request by SwethaGuptha**
### Description
This change fixes issues shard allocation in batch batch. Changes in the PR :
1.   Move decision evaluation and execution of decision together for each unassigned shard of a batch to ensure the cluster state is updated before we make decision for another shards
2.  In-order to correctly handle cases where shards have multiple unassigned replicas, evaluation and decisions execution will be done for all replica shards of a shard if the shard is part of the batch that needs to be allocated. This is required as our batches will contain only one entry per shard id. 

### Related Issues
Resolves #13702, #13962

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java [hunk 1]
```diff
@@ -158,6 +163,46 @@ public void testMakeAllocationDecisionDataFetchedMultipleShards() {
...
+                node1,
+                "allocId-" + shardId.id(),
+                shardId,
+                true,
+                new ReplicationCheckpoint(shardId, 20, 101, 1, Codec.getDefault().getName()),
+                null
+            );
+        }
+
+        allocateAllUnassignedBatch(routingAllocation);
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:194]: Can we ensure that routingAllocation has two shards that are unassigned ?

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java [hunk 2]
```diff
@@ -158,6 +163,46 @@ public void testMakeAllocationDecisionDataFetchedMultipleShards() {
...
+
+        // Verify the throttling decider was not throttled, recovering shards on node greater than initial concurrent recovery setting
+        assertFalse(routingAllocation.routingNodes().getInitialPrimariesIncomingRecoveries(node1.getId())
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:197]: should this assert for recovery=1 ?

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java [hunk 3]
```diff
@@ -158,6 +163,46 @@ public void testMakeAllocationDecisionDataFetchedMultipleShards() {
...
+            < 1);
+        List<ShardRouting> initializingShards = routingAllocation.routingNodes().shardsWithState(ShardRoutingState.INITIALIZING);
+        assertEquals(2, initializingShards.size());
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:200]: Why is this 2 ? Shouldn't it be one initialising shard on node1 only ?

File: server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java [hunk 4]
```diff
@@ -60,51 +62,42 @@ protected FetchResult<TransportNodesListGatewayStartedShards.NodeGatewayStartedS
     }
 
     @Override
-    public AllocateUnassignedDecision makeAllocationDecision(ShardRouting unassignedShard, RoutingAllocation allocation, Logger logger) {
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java:63]: This needs to be overriden here - otherwise it will fallback to single fetch which is not supported 

```
    protected FetchResult<TransportNodesListGatewayStartedShards.NodeGatewayStartedShards> fetchData(
        ShardRouting shard,
        RoutingAllocation allocation
    ) {
        logger.error("fetchData for single shard called via batch allocator, shard id {}", shard.shardId());
        throw new IllegalStateException("PrimaryShardBatchAllocator should only be used for a batch of shards");
    }

```

**Review by rajiv-kv — COMMENTED** [review]
Can we run the tests in batch and non-batch mode to verify if existing tests pass ?

File: server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java [hunk 5]
```diff
@@ -60,51 +62,42 @@ protected FetchResult<TransportNodesListGatewayStartedShards.NodeGatewayStartedS
...
-    /**
-     * Build allocation decisions for all the shards present in the batch identified by batchId.
-     *
-     * @param shards     set of shards given for allocation
-     * @param allocation current allocation of all the shards
-     * @param logger     logger used for logging
-     * @return shard to allocation decision map
-     */
-    @Override
-    public HashMap<ShardRouting, AllocateUnassignedDecision> makeAllocationDecision(
```
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java:76]: Parent class for PrimaryShardBatchAllocator has an [implementation](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/gateway/PrimaryShardAllocator.java#L119) for method ```makeAllocationDecision(
        final ShardRouting unassignedShard,
        final RoutingAllocation allocation,
        final Logger logger
    )```

File: server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java (hunk 4 above)
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java:63]: Added the method to batch shard allocators.

File: server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java]: Done.

File: server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java [hunk 6]
```diff
@@ -87,32 +87,16 @@ public void allocateUnassigned(
...
-                        executeDecision(shard, decisionMap.remove(shard), allocation, iterator);
-                    }
-                } else {
-                    // no need to keep iterating the unassigned shards, if we don't have anything in decision map
-                    break;
-                }
-            } catch (Exception e) {
-                logger.error("Failed to execute decision for shard {} while initializing {}", shard, e);
-                throw e;
+            ShardRouting shardRouting = iterator.next();
```
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java]: Initialization of shards is handled by the interface UnassignedAllocationHandler and is implemented only by UnassignedShards.UnassignedIterator, hence we need to use this iterator instead of looping through shardRoutings.

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java (hunk 1 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:143]: Updated the test in the latest revision.

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java (hunk 2 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java]: Updated the test in the latest revision.

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java (hunk 3 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java]: Updated the test in the latest revision.

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java [hunk 7]
```diff
@@ -692,6 +745,87 @@ private RoutingAllocation onePrimaryOnNode1And1Replica(AllocationDeciders decide
...
+        Map<ShardId, ShardRouting> shardIdShardRoutingMap = new HashMap<>();
+        Index index = null;
+        for (ShardId shardIdFromBatch : shardsInBatch) {
+            shardIdShardRoutingMap.put(
+                shardIdFromBatch,
+                TestShardRouting.newShardRouting(shardIdFromBatch, node1.getId(), true, ShardRoutingState.STARTED)
+            );
+            if (index == null) {
+                index = shardIdFromBatch.getIndex();
+            }
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:769]: Isn't this always for index `test` ?

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java [hunk 8]
```diff
@@ -692,6 +745,87 @@ private RoutingAllocation onePrimaryOnNode1And1Replica(AllocationDeciders decide
         );
     }
 
+    private RoutingAllocation routingAllocationWithMultipleShards(AllocationDeciders deciders, int primaries, int replicas)
+        throws InterruptedException {
+        return routingAllocationWithMultipleShards(deciders, Settings.EMPTY, primaries, replicas, UnassignedInfo.Reason.CLUSTER_RECOVERED);
+    }
+
+    private RoutingAllocation routingAllocationWithMultipleShards(
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:753]: Can we name this method more specific (`routingAllocationWithMultipleDelayAssigned(nUnassigned)`)

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java [hunk 9]
```diff
@@ -692,6 +745,87 @@ private RoutingAllocation onePrimaryOnNode1And1Replica(AllocationDeciders decide
...
+        AllocationDeciders deciders,
+        Settings settings,
+        int primaries,
+        int replicas,
+        UnassignedInfo.Reason reason
+    ) throws InterruptedException {
+        Map<ShardId, ShardRouting> shardIdShardRoutingMap = new HashMap<>();
+        Index index = null;
+        for (ShardId shardIdFromBatch : shardsInBatch) {
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:762]: Can we add comment `Allocation for primary`

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java [hunk 10]
```diff
@@ -692,6 +745,87 @@ private RoutingAllocation onePrimaryOnNode1And1Replica(AllocationDeciders decide
...
+                Sets.newHashSet(shardIdShardRoutingMap.get(shardIdFromBatch).allocationId().getId())
+            );
+        }
+        Metadata metadata = Metadata.builder().put(indexMetadata).build();
+        // mark shard as delayed if reason is NODE_LEFT
+        boolean delayed = reason == UnassignedInfo.Reason.NODE_LEFT
+            && UnassignedInfo.INDEX_DELAYED_NODE_LEFT_TIMEOUT_SETTING.get(settings).nanos() > 0;
+        int failedAllocations = reason == UnassignedInfo.Reason.ALLOCATION_FAILED ? 1 : 0;
+        IndexRoutingTable.Builder indexRoutingTableBuilder = IndexRoutingTable.builder(index);
+        for (ShardId shardIdFromBatch : shardsInBatch) {
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:787]: Are we marking all the replica shards as delayed ? Should we have mix of UnassignedShards (with & w/o delay) ?

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java [hunk 11]
```diff
@@ -800,15 +934,75 @@ public TestBatchAllocator addData(
             }
             data.put(
                 node,
+                new TransportNodesListShardStoreMetadataBatch.NodeStoreFilesMetadataBatch(
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:937]: How were the batch tests working earlier without this change ? Trying to understand as to why is this change required now ?

File: server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java [hunk 12]
```diff
@@ -135,34 +158,54 @@ public HashMap<ShardRouting, AllocateUnassignedDecision> makeAllocationDecision(
...
+                        );
+                        Decision allocationDecision = result.v1();
+                        if (allocationDecision.type() != Decision.Type.YES && (!explain || !hasInitiatedFetching(unassignedShard))) {
+                            // only return early if we are not in explain mode, or we are in explain mode but we have not
+                            // yet attempted to fetch any shard data
+                            logger.trace("{}: ignoring allocation, can't be allocated on any node", unassignedShard);
+                            allocateUnassignedDecision = AllocateUnassignedDecision.no(
+                                UnassignedInfo.AllocationStatus.fromDecision(allocationDecision.type()),
+                                result.v2() != null ? new ArrayList<>(result.v2().values()) : null
+                            );
```
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java:194]: Its a bit difficult to extract this common block to a separate method because this code block along with making ineligibility decision is also computing the value for ```Tuple<Decision, Map<String, NodeAllocationResult>> result``` ,  a reference to the result has to be maintained to get the final allocation decision.

If we still want to refactor we can pass the reference to the result variable from caller method to the common method and assign this variable method inside it. This approach though doesn't look cleaner to me.  What do you think?

File: server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java [hunk 13]
```diff
@@ -61,50 +62,58 @@ protected FetchResult<TransportNodesListGatewayStartedShards.NodeGatewayStartedS
...
-            List<NodeGatewayStartedShard> nodeShardStates = adaptToNodeShardStates(unassignedShard, shardsState);
-            // get allocation decision for this shard
-            shardAllocationDecisions.put(unassignedShard, getAllocationDecision(unassignedShard, allocation, nodeShardStates, logger));
+        RoutingNodes.UnassignedShards.UnassignedIterator iterator = allocation.routingNodes().unassigned().iterator();
+        while (iterator.hasNext()) {
+            ShardRouting unassignedShard = iterator.next();
+            AllocateUnassignedDecision allocationDecision;
+
+            if (shardRoutings.contains(unassignedShard)) {
+                if (ineligibleShardAllocationDecisions.containsKey(unassignedShard.shardId())) {
```
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java:108]: Do we need this assertion, ideally the deciders should be able to ignore the replica shard assignment request if the primary of the shard is not assigned?

File: server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java [hunk 14]
```diff
@@ -98,35 +100,56 @@ protected FetchResult<TransportNodesListShardStoreMetadata.NodeStoreFilesMetadat
...
+    public void allocateUnassignedBatch(List<ShardRouting> shardRoutings, RoutingAllocation allocation) {
         final boolean explain = allocation.debugDecision();
         List<ShardRouting> eligibleShards = new ArrayList<>();
         List<ShardRouting> ineligibleShards = new ArrayList<>();
-        HashMap<ShardRouting, Tuple<Decision, Map<String, NodeAllocationResult>>> nodeAllocationDecisions = new HashMap<>();
-        for (ShardRouting shard : shards) {
+        HashMap<ShardRouting, AllocateUnassignedDecision> ineligibleShardAllocationDecisions = new HashMap<>();
+
+        for (ShardRouting shard : shardRoutings) {
             if (!isResponsibleFor(shard)) {
```
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java:140]: Done.

File: server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java [hunk 15]
```diff
@@ -135,34 +158,54 @@ public HashMap<ShardRouting, AllocateUnassignedDecision> makeAllocationDecision(
...
+        while (iterator.hasNext()) {
+            ShardRouting unassignedShard = iterator.next();
+            // There will be only one entry for the shard in the unassigned shards batch
+            // for a shard with multiple unassigned replicas, hence we are comparing the shard ids
+            // instead of ShardRouting in-order to evaluate shard assignment for all unassigned replicas of a shard.
+            if (!unassignedShard.primary() && shardIdsFromBatch.contains(unassignedShard.shardId())) {
+                AllocateUnassignedDecision allocateUnassignedDecision;
+                if (ineligibleShardAllocationDecisions.containsKey(unassignedShard)) {
+                    allocateUnassignedDecision = ineligibleShardAllocationDecisions.get(unassignedShard);
+                } else {
```
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java:178]: Added.

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java [hunk 16]
```diff
@@ -85,61 +81,60 @@ private void allocateAllUnassignedBatch(final RoutingAllocation allocation) {
...
-        assertEquals(AllocationDecision.AWAITING_INFO, allDecisions.get(shard).getAllocationDecision());
-    }
-
-    public void testMakeAllocationDecisionForReplicaShard() {
-        final RoutingAllocation allocation = routingAllocationWithOnePrimary(noAllocationDeciders(), CLUSTER_RECOVERED, "allocId1");
+    public void testAllocateUnassignedBatch() {
+        ClusterSettings clusterSettings = new ClusterSettings(Settings.EMPTY, ClusterSettings.BUILT_IN_CLUSTER_SETTINGS);
+        AllocationDeciders allocationDeciders = randomAllocationDeciders(Settings.builder().build(), clusterSettings, random());
+        setUpShards(2);
+        final RoutingAllocation routingAllocation = routingAllocationWithMultiplePrimaries(
```
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:88]: No. Did add a test case where if the index has 2 shards, we validate on shard is getting assigned while another is unassigned as part of throttling verification. Do we need this one too?

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java (hunk 7 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:769]: Yes, currently index can only be```test``` but avoiding the hard-coding helps in keeping the method more generic.

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java (hunk 8 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:753]: Would routingAllocationWithMultipleUnassignedShards be a better? this particular method has nothing specific to do with delaying shard assignment,  at high level it is creating shards with their replicas unassigned.

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java (hunk 10 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:787]: I will have to evaluate it how this property effects the shard assignment for the test cases we have.

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java (hunk 11 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:937]: Earlier Batch data response object was getting constructed as part of fetchData implementation.

I had to make this change because the current fetchData implementation in this test class assumes there is only one primary shard required for the test setup. For new test case on throttling deciders I required a setup with multiple shards hence storing the data in batch format so that fetchData call can return the data cache as it is. This is similar to what we also have in PrimaryShardBatchAllocatorTests.

**Comment by shwetathareja** [comment]
@SwethaGuptha please add more details in PR description

File: server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java [hunk 17]
```diff
@@ -98,71 +100,123 @@ protected FetchResult<TransportNodesListShardStoreMetadata.NodeStoreFilesMetadat
...
+                            unassignedShard,
+                            allocation
+                        );
+                        Decision allocationDecision = result.v1();
+                        if (allocationDecision.type() != Decision.Type.YES && (!explain || !hasInitiatedFetching(unassignedShard))) {
+                            // only return early if we are not in explain mode, or we are in explain mode but we have not
+                            // yet attempted to fetch any shard data
+                            logger.trace("{}: ignoring allocation, can't be allocated on any node", unassignedShard);
+                            allocateUnassignedDecision = AllocateUnassignedDecision.no(
+                                UnassignedInfo.AllocationStatus.fromDecision(allocationDecision.type()),
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java:180]: duplicate code with above ```makeAllocationDecision``` method and again duplicated below - ```getInEligibleShardDecision```

File: server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java [hunk 18]
```diff
@@ -61,50 +62,58 @@ protected FetchResult<TransportNodesListGatewayStartedShards.NodeGatewayStartedS
...
+
         // only fetch data for eligible shards
         final FetchResult<NodeGatewayStartedShardsBatch> shardsState = fetchData(eligibleShards, inEligibleShards, allocation);
 
-        // process the received data
-        for (ShardRouting unassignedShard : eligibleShards) {
-            List<NodeGatewayStartedShard> nodeShardStates = adaptToNodeShardStates(unassignedShard, shardsState);
-            // get allocation decision for this shard
-            shardAllocationDecisions.put(unassignedShard, getAllocationDecision(unassignedShard, allocation, nodeShardStates, logger));
+        RoutingNodes.UnassignedShards.UnassignedIterator iterator = allocation.routingNodes().unassigned().iterator();
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java:102]: please add a note why you need to iterate all the unassigned shards again here

Comment (shwetathareja) [reply server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java:102]: Also, any noticable performance regression after the code to iterate all unassigned shards for every batch?

Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java:102]: Ack. No regression was observed. Measured performance of this fix on a 20 node cluster with 20 K shards and these were the numbers observed:

```
Batch mode disabled:
14: 30 to 14:32 [Red-yellow]
14:32  to 14:41 [yellow - green]
Batch mode enabled:
13:45 to 13:47[ Red-yellow]
13:47 to 13:55 [ yellow-green] 
```

We did slightly better by a minute.

File: server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java]: Refactored.

**Comment by SwethaGuptha** [comment]
Failures:

```
[org.opensearch.http.SearchRestCancellationIT.testAutomaticCancellationDuringFetchPhase](https://build.ci.opensearch.org/job/gradle-check/40496/testReport/junit/org.opensearch.http/SearchRestCancellationIT/testAutomaticCancellationDuringFetchPhase/)
    [org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode](https://build.ci.opensearch.org/job/gradle-check/40496/testReport/junit/org.opensearch.gateway/RecoveryFromGatewayIT/testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode/)
    [org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode](https://build.ci.opensearch.org/job/gradle-check/40496/testReport/junit/org.opensearch.gateway/RecoveryFromGatewayIT/testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode_2/)
    [org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode](https://build.ci.opensearch.org/job/gradle-check/40496/testReport/junit/org.opensearch.gateway/RecoveryFromGatewayIT/testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode_3/)
    [org.opensearch.gateway.RecoveryFromGatewayIT.testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode](https://build.ci.opensearch.org/job/gradle-check/40496/testReport/junit/org.opensearch.gateway/RecoveryFromGatewayIT/testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode_4/)
    [org.opensearch.indices.IndicesRequestCacheIT.testCacheCleanupOnEqualStalenessAndThreshold {p0={"search.concurrent_segment_search.enabled":"false"}}](https://build.ci.opensearch.org/job/gradle-check/40496/testReport/junit/org.opensearch.indices/IndicesRequestCacheIT/testCacheCleanupOnEqualStalenessAndThreshold__p0___search_concurrent_segment_search_enabled___false___/)
    [org.opensearch.indices.IndicesRequestCacheIT.classMethod](https://build.ci.opensearch.org/job/gradle-check/40496/testReport/junit/org.opensearch.indices/IndicesRequestCacheIT/classMethod/)
```
testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentNodeStartTimeInBatchMode - Open PR https://github.com/opensearch-project/OpenSearch/pull/14107

testAutomaticCancellationDuringFetchPhase flaky: https://github.com/opensearch-project/OpenSearch/issues/5426

testDynamicStalenessThresholdUpdate flaky: https://github.com/opensearch-project/OpenSearch/issues/13503

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java [hunk 19]
```diff
@@ -85,61 +81,60 @@ private void allocateAllUnassignedBatch(final RoutingAllocation allocation) {
         batchAllocator.allocateUnassignedBatch(shardsToBatch, allocation);
     }
 
-    public void testMakeAllocationDecisionDataFetching() {
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:88]: Can we put back the existing tests ? Lets change the method calls of the batchAllocator accordingly

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java [hunk 20]
```diff
@@ -85,61 +81,60 @@ private void allocateAllUnassignedBatch(final RoutingAllocation allocation) {
...
-        HashMap<ShardRouting, AllocateUnassignedDecision> allDecisions = batchAllocator.makeAllocationDecision(shards, allocation, logger);
-        // verify we get decisions for all the shards
-        assertEquals(shards.size(), allDecisions.size());
-        assertEquals(shards, new ArrayList<>(allDecisions.keySet()));
-        assertEquals(AllocationDecision.AWAITING_INFO, allDecisions.get(shard).getAllocationDecision());
-    }
-
-    public void testMakeAllocationDecisionForReplicaShard() {
-        final RoutingAllocation allocation = routingAllocationWithOnePrimary(noAllocationDeciders(), CLUSTER_RECOVERED, "allocId1");
+    public void testAllocateUnassignedBatch() {
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:84]: Should we name this `testInitializePrimaryShards`

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java [hunk 21]
```diff
@@ -85,61 +81,60 @@ private void allocateAllUnassignedBatch(final RoutingAllocation allocation) {
...
-        assertEquals(AllocationDecision.YES, allDecisions.get(shard).getAllocationDecision());
+        assertEquals(0, routingAllocation.routingNodes().unassigned().size());
+        List<ShardRouting> initializingShards = routingAllocation.routingNodes().shardsWithState(ShardRoutingState.INITIALIZING);
+        assertEquals(2, initializingShards.size());
+        assertTrue(shardsInBatch.contains(initializingShards.get(0).shardId()));
+        assertTrue(shardsInBatch.contains(initializingShards.get(1).shardId()));
+        assertEquals(2, routingAllocation.routingNodes().getInitialPrimariesIncomingRecoveries(node1.getId()));
     }
 
-    public void testMakeAllocationDecisionDataFetchedMultipleShards() {
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:128]: Lets put back the tests

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java [hunk 22]
```diff
@@ -692,6 +745,78 @@ private RoutingAllocation onePrimaryOnNode1And1Replica(AllocationDeciders decide
         );
     }
 
+    private RoutingAllocation twoAssignedPrimaryShardsAnd1UnassignedReplicaPerShard(AllocationDeciders deciders)
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:748]: 1->one, Can be named as `twoPrimaryAndOneUnAssignedReplica`

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java [hunk 23]
```diff
@@ -634,6 +643,50 @@ public void testDoNotCancelForBrokenNode() {
...
+                    node3,
+                    shardIdFromBatch,
+                    "MATCH",
+                    null,
+                    new StoreFileMetadata("file1", 10, "MATCH_CHECKSUM", MIN_SUPPORTED_LUCENE_VERSION)
+                );
+        }
+        allocateAllUnassignedBatch(routingAllocation);
+        // Verify the throttling decider was throttled, incoming recoveries on a node should be
+        // lesser than or equal to allowed concurrent recoveries
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:683]: Can we verify the Unassigned Reason of the shard for the throttling ?

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java [hunk 24]
```diff
@@ -634,6 +643,50 @@ public void testDoNotCancelForBrokenNode() {
...
+        assertEquals(0, routingAllocation.routingNodes().getIncomingRecoveries(node2.getId()));
+        assertEquals(1, routingAllocation.routingNodes().getIncomingRecoveries(node3.getId()));
+        List<ShardRouting> initializingShards = routingAllocation.routingNodes().shardsWithState(ShardRoutingState.INITIALIZING);
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:686]: Could we also assert that remaining shards are unassigned

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java (hunk 19 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:88]: Added.

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java (hunk 21 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:128]: Added.

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java (hunk 22 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:748]: Done.

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java (hunk 20 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:84]: Done.

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java (hunk 24 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:686]: Added. Other shards are marked as ignored.

File: server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java (hunk 23 above)
Comment (SwethaGuptha) [reply server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java:683]: The Unassigned reason for the shard is not updated for replicas shards that are ignored. 
For our test case unassigned shard was created with NO_ATTEMPT status, the status doesn't change but its marked is as ignored after the delayed allocation run.

File: server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java [hunk 25]
```diff
@@ -98,71 +101,91 @@ protected FetchResult<TransportNodesListShardStoreMetadata.NodeStoreFilesMetadat
...
+            ShardRouting unassignedShard = iterator.next();
+            // There will be only one entry for the shard in the unassigned shards batch
+            // for a shard with multiple unassigned replicas, hence we are comparing the shard ids
+            // instead of ShardRouting in-order to evaluate shard assignment for all unassigned replicas of a shard.
+            if (!unassignedShard.primary() && shardIdsFromBatch.contains(unassignedShard.shardId())) {
+                AllocateUnassignedDecision allocateUnassignedDecision;
+                if (ineligibleShardAllocationDecisions.containsKey(unassignedShard)) {
+                    allocateUnassignedDecision = ineligibleShardAllocationDecisions.get(unassignedShard);
+                } else {
+                    // The shard is eligibility is being recomputed again for two reason because
```
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java:149]: Fixed.

File: server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java [hunk 26]
```diff
@@ -98,71 +101,91 @@ protected FetchResult<TransportNodesListShardStoreMetadata.NodeStoreFilesMetadat
...
         List<ShardRouting> eligibleShards = new ArrayList<>();
         List<ShardRouting> ineligibleShards = new ArrayList<>();
-        HashMap<ShardRouting, Tuple<Decision, Map<String, NodeAllocationResult>>> nodeAllocationDecisions = new HashMap<>();
-        for (ShardRouting shard : shards) {
-            if (!isResponsibleFor(shard)) {
-                // this allocator n is not responsible for allocating this shard
+        HashMap<ShardRouting, AllocateUnassignedDecision> ineligibleShardAllocationDecisions = new HashMap<>();
+
+        for (ShardRouting shard : shardRoutings) {
+            AllocateUnassignedDecision inEligibleShardDecision = getUnassignedShardAllocationDecision(shard, allocation, null);
```
[the remark this answers is not in the document]
Comment (SwethaGuptha) [reply server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java:125]: Added.

**Comment by shwetathareja** [comment]
@SwethaGuptha the newly added tests are failing gardle check - https://build.ci.opensearch.org/job/gradle-check/40679/

**Review by rajiv-kv — APPROVED** [review]
Thanks for making the changes !

**Comment by SwethaGuptha** [comment]
> ❌ Gradle check result for [b452150](https://github.com/opensearch-project/OpenSearch/commit/b452150d06fe1da47f55c4f979f0dddad4ff37fe): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/40679/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Fixed in https://github.com/opensearch-project/OpenSearch/pull/14107

**Review by shwetathareja — APPROVED** [review]
