### PR TITLE
Disable concurrent aggs for Diversified Sampler and Sampler aggs

### LINKED ISSUE #10046: [BUG] org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testNestedSamples {p0={"search.concurrent_segment_search.enabled":"true"}} is flaky
**Describe the bug**
The test case org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testNestedSamples {p0={"search.concurrent_segment_search.enabled":"true"}} is flaky:

```
org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testNestedSamples {p0={"search.concurrent_segment_search.enabled":"true"}}

java.lang.AssertionError: 
Expected: a value less than or equal to <4L>
     but: <5L> was greater than <4L>
	at __randomizedtesting.SeedInfo.seed([D30D5DEAC663DE87:9ECE7E7BADC6DF04]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testNestedSamples(DiversifiedSamplerIT.java:248)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**To Reproduce**
- https://build.ci.opensearch.org/job/gradle-check/25586/
- https://build.ci.opensearch.org/job/gradle-check/25543/
- 
**Expected behavior**
Test should always pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**

### LINKED ISSUE #10822: [BUG] org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testSimpleDiversity {p0={"search.concurrent_segment_search.enabled":"true"}} is flkay
**Describe the bug**
`org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testSimpleDiversity {p0={"search.concurrent_segment_search.enabled":"true"}}` test is flaky.

**To Reproduce**
Follow build failure - https://build.ci.opensearch.org/job/gradle-check/28692/testReport/junit/org.opensearch.search.aggregations.bucket/DiversifiedSamplerIT/testSimpleDiversity__p0___search_concurrent_segment_search_enabled___true___/

**Expected behavior**
The test must always pass.

### LINKED ISSUE #10893: [BUG] Flaky test org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT
**Describe the bug**
Observed two flaky test for org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.

* [org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testSimpleDiversity {p0={"search.concurrent_segment_search.enabled":"true"}}](https://build.ci.opensearch.org/job/gradle-check/28910/testReport/junit/org.opensearch.search.aggregations.bucket/DiversifiedSamplerIT/testSimpleDiversity__p0___search_concurrent_segment_search_enabled___true___/)
* [org.opensearch.search.aggregations.bucket.DiversifiedSamplerIT.testNestedDiversity {p0={"search.concurrent_segment_search.enabled":"true"}}](https://build.ci.opensearch.org/job/gradle-check/28910/testReport/junit/org.opensearch.search.aggregations.bucket/DiversifiedSamplerIT/testNestedDiversity__p0___search_concurrent_segment_search_enabled___true___/)

Observed in [build](https://build.ci.opensearch.org/job/gradle-check/28910/) of [PR](https://github.com/opensearch-project/OpenSearch/pull/10889).

### PR DESCRIPTION
**Pull request by jed326**
### Description
Disable concurrent aggs for Diversified Sampler and Sampler aggs. See https://github.com/opensearch-project/OpenSearch/issues/11075#issuecomment-1793077372 for more details.

### Related Issues
Resolves #10046
Resolves #10893
Resolves #10822

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
@reta @sohami could you please help review this? Thanks!

File: server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java [hunk 1]
```diff
@@ -132,13 +132,14 @@ public void setupSuiteScopeCluster() throws Exception {
             client().prepareIndex("test")
                 .setId("" + i)
                 .setSource("author", parts[5], "name", parts[2], "genre", parts[8], "price", Float.parseFloat(parts[3]))
+                .setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE)
```
Comment (reta) [inline server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java:135]: This changes seem to be unnecessary, the `client().admin().indices().refresh(new RefreshRequest("test")).get();` would have done the same, no?

Comment (jed326) [reply server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java:135]: The purpose of this is to refresh with each document and hopefully create enough segments to go down the concurrent search path (which from my local testing it did seem to do so). Currently it just refreshes once after indexing all the documents which I believe contributed to why this test was flaky instead of always failing.

File: server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/SamplerIT.java [hunk 2]
```diff
@@ -195,6 +196,23 @@ public void testSimpleSampler() throws Exception {
         assertThat(maxBooksPerAuthor, equalTo(3L));
     }
 
+    public void testSimpleSamplerShardSize() throws Exception {
+        final int SHARD_SIZE = randomIntBetween(1, 3);
+        SamplerAggregationBuilder sampleAgg = sampler("sample").shardSize(SHARD_SIZE);
```
Comment (sohami) [inline server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/SamplerIT.java:201]: Thanks for adding the test with smaller `shard_size` parameter

**Review by sohami — APPROVED** [review]

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@jed326 please send manual backport to `2.x`, thank you

**Comment by jed326** [comment]
@reta could you help merge https://github.com/opensearch-project/OpenSearch/pull/11050 first? That backport needs to be merged before this one else there will be a merge conflict. Thanks!

**Comment by reta** [comment]
> That backport needs to be merged before this one else there will be a merge conflict. I'll send out the manual backport PR as soon as that one is merged. Thanks!

Sorry about the delay @jed326 , it seems like @peternied just merged it
