### PR TITLE
Fix Segment Replication integ tests

### LINKED ISSUE #2285: [Segment Replication] - Fix Integ test with reproducible seeds
**Describe the bug**
From #2284. We have about 20% of the test runs failing with reproducible seeds.  The test is comparing doc counts after indexing, and refreshing, then indexing some more and then flushing. It's counting the first set of docs fine but fails on the replica to read the entire second set.  The OpenSearchReaderManager is refreshing the reader and the reader logs the correct number of docs, perhaps the Searcher is stale or caching results.

### PR DESCRIPTION
**Pull request by mch2**
### Description
This PR is a combination of three changes that gets Segrep integ tests to reliably pass.
 
Fixes:
1. Updates the tests to use a single BackgroundIndexer.  This ensures we correctly index the expected amount of documents. BackgroundIndexers start indexing with docId of 0, so using multiple indexers creates conflicts.
2. Fix Index shards to correctly compare checkpoint version instead of segment gen when determining
    if a received checkpoint should be processed. Without this change replicas will ignore checkpoints for merges.
3. Store the latest checkpoint received and process it after a copy event completes.  This ensures we are always processing the latest checkpoint if it is received during an active copy.

Improvements:
- Update tests to compare result of segments() API.  This will compare the segments on all replicas to the primary's version.
- Renamed UpdateCurrentInfos to `FinalizeReplication` inside of InternalEngine and moved cleanup logic there instead of ReplicationTarget.  This method will now also refresh the InternalEngine's latestCommittedSegmentInfos reference that is required to accurately update the committed & searchable properties on the segment data returned from Segments API.

### Issues Resolved
#2285
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 1]
```diff
@@ -305,6 +305,9 @@ Runnable getGlobalCheckpointSyncer() {
 
     private final CheckpointRefreshListener checkpointRefreshListener;
 
+    private volatile ReplicationCheckpoint latestUnprocessedCheckpoint;
+    private volatile long latestSeqNo;
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:309]: This is a hack until https://github.com/opensearch-project/OpenSearch/pull/2576 is merged to correctly track the local cp on replicas.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 2]
```diff
@@ -122,5 +172,61 @@ public void testReplicaSetupAfterPrimaryIndexesDocs() throws Exception {
...
+                    final IndexSegments value = indexSegmentsEntry.getValue();
+                    final Map<Integer, IndexShardSegments> shardGroup = value.getShards();
+                    for (IndexShardSegments shardEntry : shardGroup.values()) {
+                        // get a list of segments across the whole replication group.
+                        final ShardSegments[] shardSegments = shardEntry.getShards();
+
+                        // separate Primary & replica shards ShardSegments.
+                        final Map<Boolean, List<ShardSegments>> segmentListMap = Arrays.stream(shardSegments)
+                            .collect(Collectors.groupingBy(s -> s.getShardRouting().primary()));
+                        final Optional<ShardSegments> primaryOptional = segmentListMap.get(true).stream().findFirst();
```
Comment (kartg) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:193]: Nit - Do we need to assert that the size of this list is one?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 3]
```diff
@@ -122,5 +172,61 @@ public void testReplicaSetupAfterPrimaryIndexesDocs() throws Exception {
...
+        client().admin().indices().segments(new IndicesSegmentsRequest(), new ActionListener<>() {
+            @Override
+            public void onResponse(IndicesSegmentResponse indicesSegmentResponse) {
+                final Map<String, IndexSegments> indices = indicesSegmentResponse.getIndices();
+                for (Map.Entry<String, IndexSegments> indexSegmentsEntry : indices.entrySet()) {
+                    final IndexSegments value = indexSegmentsEntry.getValue();
+                    final Map<Integer, IndexShardSegments> shardGroup = value.getShards();
+                    for (IndexShardSegments shardEntry : shardGroup.values()) {
+                        // get a list of segments across the whole replication group.
+                        final ShardSegments[] shardSegments = shardEntry.getShards();
```
Comment (kartg) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:188]: Nit - You can compress this using streams.

Option 1 - get a list of arrays to iterate over:

```
List<ShardSegments[]> shardSegmentsList = 
indicesSegmentResponse.getIndices().values().stream() // get list of IndexSegments
.flatMap(is -> is.getShards().values().stream()) // Map to shard group
.map(IndexShardSegments::getShards) // get list of segments across group
.collect(Collectors.toList());
```

Option 2 (less readable) - Generate a list of maps directly

```
List<Map<Boolean, List<ShardSegments>>> shardGroupList = 
indicesSegmentResponse.getIndices().values().stream() // get list of IndexSegments
.flatMap(is -> is.getShards().values().stream()) // Map to shard group
.map(IndexShardSegments::getShards) // get subarray of segments across group

.map(s -> Arrays.stream(s)) // convert each subarray to stream
.map(s -> s.collect(Collectors.groupingBy(
    ss -> ss.getShardRouting().primary() // group each sublist by primary
)))
.collect(Collectors.toList());
```

**Comment by kartg** [comment]
> Store the latest checkpoint received and process it after a copy event completes. This ensures we are always processing the latest checkpoint if it is received during an active copy.

If the replica keeps receiving new checkpoints before it can complete replication of preceding ones, then this may end up being an endless process that takes away compute bandwidth from other operations. One possible mitigation is to build  instrumentation in segment replication that allows for an integration with indexing pressure. This way, we could log a warning or even reject indexing requests outright if replicas are continuously lagging behind.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 1 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:309]: #2576 has been merged, so you can rebase and remove this part

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 3 above)
Comment (mch2) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java]: Updated with option 1.  Thanks for this.

**Review by Poojita-Raj — APPROVED** [review]

**Comment by mch2** [comment]
> ❌   Gradle Check failure [0d1c8ae](https://github.com/opensearch-project/OpenSearch/commit/0d1c8ae1d42da373143c6495fcf1a5597a34ef8b) [Log 4218](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_4218.log)
> 
> [Reports 4218](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_4218_reports.zip)

https://github.com/opensearch-project/OpenSearch/issues/1703

**Comment by mch2** [comment]
start gradle check

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 4]
```diff
@@ -3652,32 +3657,38 @@ public synchronized void onNewCheckpoint(
...
+        if (requestCheckpoint.isAheadOf(latestUnprocessedCheckpoint)) {
+            latestUnprocessedCheckpoint = requestCheckpoint;
         }
+
+        if (isValidCheckpoint(requestCheckpoint) == false) return;
         try {
-            final ReplicationCheckpoint checkpoint = request.getCheckpoint();
-            logger.trace("Received new checkpoint {}", checkpoint);
+            final ReplicationCheckpoint checkpoint = requestCheckpoint;
+            logger.debug("Processing new checkpoint {}", checkpoint);
```
[the remark this answers is not in the document]
Comment (mch2) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java]: Yes, I thought it was useful when debugging to know if a checkpoint is ignored or processed.  Changed to debug to be consistent with the other log lvl used in this method.
