### PR TITLE
Fix snapshot repository registration failure in mixed OpenSearch version setups

### LINKED ISSUE #16830: [BUG] Snapshot repository fails if minNode version is below OS 2.17
### Describe the bug

The repository registration fails if there are nodes with OS version 2.17 and any other 1.x or 2.x prior versions. This is due to the handling for test path being differently in OS 2.17. This means that during version upgrades, the snapshot registration can fail. After the nodes have moved to same version, then repository registration works correctly.

### Related component

Storage:Snapshots

### To Reproduce

1. Create cluster with nodes from OS 2.15.
2. Add cluster manager nodes with version OS 2.17. Try registering repository with `prefix_mode_verification` value as true in metadata settings.
3. This will fail with below error response like below -
```
{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[snap_repo] [[lyNFwsLOTzOUMw267tNWxQ, 'RemoteTransportException[[opensearch-node1][172.18.0.3:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[snap_repo] a file written by cluster-manager to the store [/usr/share/opensearch/repo/snapshot] cannot be accessed on the node [{opensearch-node1}{lyNFwsLOTzOUMw267tNWxQ}{drLxKtXESaOo8Juhm10UXQ}{172.18.0.3}{172.18.0.3:9300}{dir}{shard_indexing_pressure_enabled=true}]. This might indicate that the store [/usr/share/opensearch/repo/snapshot] is not shared between this node and the cluster-manager node or that permissions on the store don't allow reading files written by the cluster-manager node]; nested: NoSuchFileException[/usr/share/opensearch/repo/snapshot/tests-WP7FHBeXSW2Tgkrnyukv_Q/master.dat];'], [pxgtWUq1SnKK6BHB41Gjkg, 'RemoteTransportException[[opensearch-node2][172.18.0.2:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[snap_repo] a file written by cluster-manager to the store [/usr/share/opensearch/repo/snapshot] cannot be accessed on the node [{opensearch-node2}{pxgtWUq1SnKK6BHB41Gjkg}{REv8TvybTTKkSNV8BEVx1w}{172.18.0.2}{172.18.0.2:9300}{dir}{shard_indexing_pressure_enabled=true}]. This might indicate that the store [/usr/share/opensearch/repo/snapshot] is not shared between this node and the cluster-manager node or that permissions on the store don't allow reading files written by the cluster-manager node]; nested: NoSuchFileException[/usr/share/opensearch/repo/snapshot/tests-WP7FHBeXSW2Tgkrnyukv_Q/master.dat];']]"}],"type":"repository_verification_exception","reason":"[snap_repo] [[lyNFwsLOTzOUMw267tNWxQ, 'RemoteTransportException[[opensearch-node1][172.18.0.3:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[snap_repo] a file written by cluster-manager to the store [/usr/share/opensearch/repo/snapshot] cannot be accessed on the node [{opensearch-node1}{lyNFwsLOTzOUMw267tNWxQ}{drLxKtXESaOo8Juhm10UXQ}{172.18.0.3}{172.18.0.3:9300}{dir}{shard_indexing_pressure_enabled=true}]. This might indicate that the store [/usr/share/opensearch/repo/snapshot] is not shared between this node and the cluster-manager node or that permissions on the store don't allow reading files written by the cluster-manager node]; nested: NoSuchFileException[/usr/share/opensearch/repo/snapshot/tests-WP7FHBeXSW2Tgkrnyukv_Q/master.dat];'], [pxgtWUq1SnKK6BHB41Gjkg, 'RemoteTransportException[[opensearch-node2][172.18.0.2:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[snap_repo] a file written by cluster-manager to the store [/usr/share/opensearch/repo/snapshot] cannot be accessed on the node [{opensearch-node2}{pxgtWUq1SnKK6BHB41Gjkg}{REv8TvybTTKkSNV8BEVx1w}{172.18.0.2}{172.18.0.2:9300}{dir}{shard_indexing_pressure_enabled=true}]. This might indicate that the store [/usr/share/opensearch/repo/snapshot] is not shared between this node and the cluster-manager node or that permissions on the store don't allow reading files written by the cluster-manager node]; nested: NoSuchFileException[/usr/share/opensearch/repo/snapshot/tests-WP7FHBeXSW2Tgkrnyukv_Q/master.dat];']]"},"status":500}%                                                                                                                                                                  
```

### Expected behavior

The version should be handled on the new cluster manager node and the new mode should be allowed only after all nodes have moved to the sufficient version.

### Additional Details

NA

### PR DESCRIPTION
**Pull request by ashking94**
### Description
This PR addresses issue #16830, where snapshot repository registration fails in clusters with mixed OpenSearch versions, specifically when nodes running OS 2.17 are present alongside nodes running earlier 1.x or 2.x versions.

Problem:
- Repository registration fails due to different handling of test paths in OS 2.17 compared to earlier versions.
- This issue occurs during version upgrades, causing snapshot functionality to break.

Solution:
- Implement version-aware logic for handling test paths.
- Ensure backward compatibility with earlier OpenSearch versions.
- Add checks to use the appropriate test path handling method based on the minimum node version in the cluster.

Changes:
1. Modified code to include version checks.
2. Updated test path handling logic to accommodate mixed version scenarios.

Testing:
- Tested repository registration in clusters with:
  - OS 2.15 and OS 2.17 nodes
- Verified successful repository registration in all scenarios.
- Ensured existing functionality remains intact for homogeneous version clusters.

This fix ensures smooth operation of snapshot repositories during cluster upgrades and in environments where different OpenSearch versions coexist.

### Related Issues
Resolves #16830

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ashking94 — COMMENTED** [review]
It's difficult to add unit tests as the BlobStoreRepositoryTest.java is actually a single node spin up and testing. There are existing integration tests that invokes this flow. The code is partially tested in the ITs that spins up the remote store nodes.

**Comment by ashking94** [comment]
> ❌ Gradle check result for [51a6e67](https://github.com/opensearch-project/OpenSearch/commit/51a6e67e7b4ab2041cd3f2c4d47979c0f87130bd): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/51425/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test - https://github.com/opensearch-project/OpenSearch/issues/15831

**Comment by ashking94** [comment]
> ❌ Gradle check result for [51a6e67](https://github.com/opensearch-project/OpenSearch/commit/51a6e67e7b4ab2041cd3f2c4d47979c0f87130bd): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/51429/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test - https://github.com/opensearch-project/OpenSearch/issues/16015

File: server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java [hunk 1]
```diff
@@ -2994,7 +2994,12 @@ public String startVerification() {
      */
     private BlobContainer testContainer(String seed) {
         BlobPath testBlobPath;
-        if (prefixModeVerification == true) {
+
+        if (prefixModeVerification == true
+            && (clusterService.isStateInitialised() == false
```
Comment (linuxpi) [inline server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java:2999]: can this check pass for an older version node if its restarting in mixed opensearch version setup?

Comment (ashking94) [reply server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java:2999]: No, it wont pass due to the added check now. Earlier it could pass this check even if all the nodes were not on the minimum supported version for prefix mode verification.

**Review by gbbafna — APPROVED** [review]

**Review by linuxpi — APPROVED** [review]

**Comment by ashking94** [comment]
> ## [Codecov](https://app.codecov.io/gh/opensearch-project/OpenSearch/pull/16831?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=opensearch-project) Report
> Attention: Patch coverage is `40.00000%` with `3 lines` in your changes missing coverage. Please review.
> 
> > Project coverage is 72.15%. Comparing base [(`5ba909a`)](https://app.codecov.io/gh/opensearch-project/OpenSearch/commit/5ba909a982e35172cd8774eabb726b6636d0018d?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=opensearch-project) to head [(`51a6e67`)](https://app.codecov.io/gh/opensearch-project/OpenSearch/commit/51a6e67e7b4ab2041cd3f2c4d47979c0f87130bd?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=opensearch-project).
> > Report is 7 commits behind head on main.
> 
> [Files with missing lines](https://app.codecov.io/gh/opensearch-project/OpenSearch/pull/16831?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=opensearch-project)	Patch %	Lines
> [...ch/repositories/blobstore/BlobStoreRepository.java](https://app.codecov.io/gh/opensearch-project/OpenSearch/pull/16831?src=pr&el=tree&filepath=server%2Fsrc%2Fmain%2Fjava%2Forg%2Fopensearch%2Frepositories%2Fblobstore%2FBlobStoreRepository.java&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=opensearch-project#diff-c2VydmVyL3NyYy9tYWluL2phdmEvb3JnL29wZW5zZWFyY2gvcmVwb3NpdG9yaWVzL2Jsb2JzdG9yZS9CbG9iU3RvcmVSZXBvc2l0b3J5LmphdmE=)	33.33%	[0 Missing and 2 partials ⚠️ ](https://app.codecov.io/gh/opensearch-project/OpenSearch/pull/16831?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=opensearch-project)
> [...nsearch/cluster/service/ClusterApplierService.java](https://app.codecov.io/gh/opensearch-project/OpenSearch/pull/16831?src=pr&el=tree&filepath=server%2Fsrc%2Fmain%2Fjava%2Forg%2Fopensearch%2Fcluster%2Fservice%2FClusterApplierService.java&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=opensearch-project#diff-c2VydmVyL3NyYy9tYWluL2phdmEvb3JnL29wZW5zZWFyY2gvY2x1c3Rlci9zZXJ2aWNlL0NsdXN0ZXJBcHBsaWVyU2VydmljZS5qYXZh)	0.00%	[0 Missing and 1 partial ⚠️ ](https://app.codecov.io/gh/opensearch-project/OpenSearch/pull/16831?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=opensearch-project)
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/opensearch-project/OpenSearch/pull/16831?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=opensearch-project). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=opensearch-project).

Some of the changes needs mixed version tests for which there is an issue created.

**Comment by ashking94** [comment]
> The backport to `2.x` failed:
> 
> ```
> The process '/usr/bin/git' failed with exit code 128
> ```
> 
> To backport manually, run these commands in your terminal:
> 
> ```shell
> # Navigate to the root of your repository
> cd $(git rev-parse --show-toplevel)
> # Fetch latest updates from GitHub
> git fetch
> # Create a new working tree
> git worktree add ../.worktrees/OpenSearch/backport-2.x 2.x
> # Navigate to the new working tree
> pushd ../.worktrees/OpenSearch/backport-2.x
> # Create a new branch
> git switch --create backport/backport-16831-to-2.x
> # Cherry-pick the merged commit of this pull request and resolve the conflicts
> git cherry-pick -x --mainline 1 d37cc9b32600faef17b3c898f8c86b0fd7640d72
> # Push it to GitHub
> git push --set-upstream origin backport/backport-16831-to-2.x
> # Go back to the original working tree
> popd
> # Delete the working tree
> git worktree remove ../.worktrees/OpenSearch/backport-2.x
> ```
> 
> Then, create a pull request where the `base` branch is `2.x` and the `compare`/`head` branch is `backport/backport-16831-to-2.x`.

Manually backporting this PR.

**Comment by ashking94** [comment]
Created manual backport https://github.com/opensearch-project/OpenSearch/pull/16849
