### PR TITLE
Fix NPE when minBound/maxBound is not set before being called.

### LINKED ISSUE #3604: [BUG] NPE when minBound/maxBound is not set before being called
**Describe the bug**
A `NullPointerException` occurs when the methods `minBound()` and `maxBound` 
https://github.com/opensearch-project/OpenSearch/blob/8844f0590a96a791f56902b9c3e004d3beb91d10/server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java#L228-L236
are called before they are set in `DoubleBounds`

https://github.com/opensearch-project/OpenSearch/blob/8844f0590a96a791f56902b9c3e004d3beb91d10/server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DoubleBounds.java#L154-L160

**To Reproduce**
A unit test that does not set the min and max values, example for the minBound:

```
public void testNPE() {
        HistogramAggregationBuilder factory = new HistogramAggregationBuilder("foo");

        try {
            factory.minBound();
        }
        catch (Exception e) {
            assertThat(e, instanceOf(NullPointerException.class));
        }
    }
```

**Expected behavior**
It should return `null` 

**Host/Environment (please complete the following information):**
- Java version : 11
 - OS: Ubuntu 
 - Version 20.04.4 LTS

### PR DESCRIPTION
**Pull request by GeorgeAp**
### Description
Resolves a NullPointerException which occurs when the methods minBound() and maxBound
https://github.com/opensearch-project/OpenSearch/blob/8844f0590a96a791f56902b9c3e004d3beb91d10/server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java#L228-L236
are called before they are set in DoubleBounds
https://github.com/opensearch-project/OpenSearch/blob/8844f0590a96a791f56902b9c3e004d3beb91d10/server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DoubleBounds.java#L154-L160
 
### Issues Resolved
#3604 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java [hunk 1]
```diff
@@ -227,12 +227,12 @@ public HistogramAggregationBuilder offset(double offset) {
 
     /** Get the current minimum bound that is set on this builder. */
     public double minBound() {
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java:229]: @GeorgeAp there is obviously an issue with these methods handling `null`s but I have not find any usages of these methods in the codebase, I am curious what flow you run into NPEs?

Comment (GeorgeAp) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java:229]: @reta the flow is mainly, we create an aggregator using this builder but choose to use the default values i.e. `POSITIVE_INFINITY` and `NEGATIVE_INFINITY` but check to ensure that is this is the case. To check, the methods are called and since they are not set, they throw NPE.

**Review by dblock — APPROVED** [review]

**Review by reta — APPROVED** [review]
