### PR TITLE
Check CircuitBreaker before put/compute in FileCache to avoid entry removal

### LINKED ISSUE #18658: [BUG] Transfer Manager removes entries from FileCache if CircuitBreaker trips while downloading blob
### Describe the bug

In TransferManager, the [fetchBlob function always calls compute method of the FileCache](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java#L77) even if the entry is already present in the FileCache.

This causes an unforeseen scenario when CircuitBreaker starts tripping because the flow in FileCache compute is such that we first compute the key and then check if the circuit breaker is tripping. If yes, [we remove the computed entry from the cache](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java#L210). As a result of this, even if the entry is already present in FileCache, when fetchBlob is called, we recompute again but since CircuitBreaker is tripping, the file entry already present is evicted.

The above scenario can result in cases when the IndexInput is not yet closed but since the entry is evicted from the FileCache the underlying exception points in a different direction which can derail debugging as it points towards an altogether different area.

Example exception when IndexInput is not closed but file is deleted.

```
Caused by: java.io.EOFException: seek past EOF (pos=7987177): MemorySegmentIndexInput(path="/<path>/var/es/data/nodes/0/indices/000010UHjS4EilSI2zEIIZ7IGZ1Q/1/index/_2t.cfs_block_1")
```

### Related component

Storage:Remote

### To Reproduce

Prerequisite for reproduction - High JVM on node so that Circuit Breaker trips.

### Expected behavior

For entries already present in FileCache that are not closed, TransferManager should simply return those entries instead of recomputing.

### Additional Details

N/A

### PR DESCRIPTION
**Pull request by rayshrey**
### Description
Check CircuitBreaker before put/compute in FileCache to avoid entry removal

### Related Issues
Resolves #18658 

### Check List
- [x] Functionality includes testing.
- [ ] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java [hunk 1]
```diff
@@ -74,17 +74,13 @@ public IndexInput fetchBlob(BlobFetchRequest blobFetchRequest) throws IOExceptio
...
-                        logger.trace("Transfer Manager - IndexInput closed or not in cache");
-                        // Doesn't exist or is closed, either way create a new one
-                        return new DelayedCreationCachedIndexInput(fileCache, streamReader, blobFetchRequest);
-                    } else {
-                        logger.trace("Transfer Manager - Already in cache");
-                        // already in the cache and ready to be used (open)
-                        return cachedIndexInput;
-                    }
-                });
+                CachedIndexInput cacheEntry = fileCache.get(key);
```
Comment (skumawat2025) [inline server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: Trying to understand what was the issue in the existing code?

I think when we do compute we compute the value for a key and put it back to fileCache and that's why we have to do a `decRef()` in `finally{}` block.  

Now with the new code, we are doing a get call for a key and still trying to do `decRef()` in finally block. Can this lead to wrong behaviour?

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java [hunk 2]
```diff
@@ -74,17 +74,13 @@ public IndexInput fetchBlob(BlobFetchRequest blobFetchRequest) throws IOExceptio
...
+                if (cacheEntry == null || cacheEntry.isClosed()) {
+                    cacheEntry = fileCache.compute(
+                        key,
+                        (path, cachedIndexInput) -> new DelayedCreationCachedIndexInput(fileCache, streamReader, blobFetchRequest)
+                    );
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: `compute` again does a get and increases the miss count again post `fileCache.get(key)` . Instead should we just do `fileCache.put` ?

Comment (rayshrey) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: Correct, cache misses would be counted as 2 in this case, will make the change to directly put instead of using compute.

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java (hunk 1 above)
Comment (rayshrey) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: >Trying to understand what was the issue in the existing code?

This fix wasn't done to mange the refCount but to prevent the cache entry from being evicted during compute call when circuit breaker is hit.


>we are doing a get call for a key and still trying to do decRef() in finally block. Can this lead to wrong behavior?

Also get call on filecache increases the refCount so we won't cause any wrong behavior here.

**Review by gbbafna — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java [hunk 3]
```diff
@@ -74,17 +74,11 @@ public IndexInput fetchBlob(BlobFetchRequest blobFetchRequest) throws IOExceptio
...
-                    } else {
-                        logger.trace("Transfer Manager - Already in cache");
-                        // already in the cache and ready to be used (open)
-                        return cachedIndexInput;
-                    }
-                });
+                CachedIndexInput cacheEntry = fileCache.get(key);
+                if (cacheEntry == null || cacheEntry.isClosed()) {
+                    cacheEntry = new DelayedCreationCachedIndexInput(fileCache, streamReader, blobFetchRequest);
+                    fileCache.put(key, cacheEntry);
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: This doesn't look thread safe. What happens if two threads both observe a null `cacheEntry` and then one ends up overwriting the other?

Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: Good catch @andrross .  I think we need `putIfAbsent` to solve this  . wdyt ?

Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: If I understand the issue correctly, the bug is that the compute() invocation [here](https://github.com/opensearch-project/OpenSearch/blob/33d8fce5879ed27f06865b23a7ce99063be07856/server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java#L82) may create a new cache entry or it may return an existing entry (which is the correct contract of compute), but the subsequent check to the circuit breaker is operating under the assumption we have just added a new entry to the cache and will evict if the circuit breaker is breached. That's wrong, so it seems the implementation of `FileCache#compute` is broken and should be fixed as opposed to working around it by not calling that method.

Can we fix this by changing the circuit breaker check to do a best-effort check for existence of the key in the underlying cache before [this line](https://github.com/opensearch-project/OpenSearch/blob/33d8fce5879ed27f06865b23a7ce99063be07856/server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java#L82)?

I don't think simply using `putIfAbsent` will work here because there are actually 3 cases being handled by compute:
- if the key does not exist, create a new one
- if the key exists but is closed, create a new one and replace the closed instance
- if the key exists and is open, then return it.

`putIfAbsent` does not handle the case where we need to replace a closed instance.

Comment (rayshrey) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: Even if we make the change in `FileCache#compute` then also it won't be thread safe as we will be making a get call before the compute to the underlying LRUCache (Until and unless we add CircuitBreaker at LRUCache level, such checks will never be thread safe)

If these calls aren't thread safe then we will again run into the same condition. 
Example scenario(if we do a get before compute in `FileCache#compute`:

- On thread 1, GET will say entry not present in file cache. So after COMPUTE we will trigger check circuit breaker
- Thread 2 will do COMPUTE and entry will now be present in file cache (suppose circuit breaker has not tripped at this point)
- In case circuit breaker trips now, thread 1 will do a COMPUTE (value will remain unchanged though since entry is already there) and now the entry will be deleted as earlier GET had returned that there was no entry.

The only concrete solution I can think of right now is combining the get and put in synchronized block in Transfer Manager (as in the current PR) or similarly putting get and compute in `LRUCache#compute` method in a synchronized block as well. But that would degrade performance I think.

Thoughts on way forward @andrross ?

Comment (rayshrey) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: Thinking of implementing the CircuitBreaker in the LRUCache itself - that should make the operations thread safe.
Do you see any concerns around that @andrross ?

Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: @rayshrey I agree putting the circuit breaker inside the synchronized code is the only way to make it thread safe. The risk is that we're putting more logic into critical-section code.

The alternative I was suggesting was to make the circuit breaker best-effort, which would allow for oversubscribing the breaker in certain race conditions (i.e. there is only enough headroom for one more file, two threads observe that there is enough space and both add their files, therefore oversubscribing by one file).

Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: @rayshrey Is there also a bug here?

https://github.com/opensearch-project/OpenSearch/blob/33d8fce5879ed27f06865b23a7ce99063be07856/server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java#L70-L75

It seems like it's possible for thread 1 to put a new file, which could then be observed by thread 2, but then thread 1 trips the breaker and the file is removed and thread 2 is left with a broken reference to the file.

Comment (rayshrey) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: Yes the race condition can occur in put method as well.
But since the usage of compute is more profound (mostly because of Transfer Manager), it is more common in compute.

One more option that came to my mind right now to avoid adding the circuitbreaker in the LRUCache is to add the checkCircuitBreaker() check first rather than doing the operation and then checking - that would solve the problem altogether. (Since we will check beforehand, there will be no need to remove entry if circuit breaker trips since we won't be adding it in the first place)

Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java]: > One more option that came to my mind right now to avoid adding the circuitbreaker in the LRUCache is to add the checkCircuitBreaker() check first rather than doing the operation and then checking - that would solve the problem altogether. (Since we will check beforehand, there will be no need to remove entry if circuit breaker trips since we won't be adding it in the first place)

@rayshrey This is what I was suggesting with the best-effort approach. You'll still have a race condition described above that can result in exceeding the circuit breaker. This is probably acceptable in practice though.

**Comment by rayshrey** [comment]
@andrross made the changes as discussed, can you please review

File: server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java [hunk 4]
```diff
@@ -79,8 +79,8 @@ public CachedIndexInput compute(
         Path key,
         BiFunction<? super Path, ? super CachedIndexInput, ? extends CachedIndexInput> remappingFunction
     ) {
+        checkParentBreaker();
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java:82]: This will throw an exception even in the case where compute() is going to return an existing entry and not write anything new. That means all reads going through TransferManager::fetchBlob will fail once the circuit breaker is breached.

Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java:82]: I'm thinking we need to guard this with something like:

```
if (!theCache.exists(key)) {
    checkParentBreaker();
}
return theCache.compute(key, remappingFunction);
```

The breaker check is still best-effort as another thread could add the key between the exists() check and the call to `checkParentBreaker()`, but it wouldn't persistently fail so it is probably okay.

Note that the `RefCountedCache.exists` method does not exist and would need to be added.

Comment (rayshrey) [reply server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java:82]: >This will throw an exception even in the case where compute() is going to return an existing entry and not write anything new. That means all reads going through TransferManager::fetchBlob will fail once the circuit breaker is breached.

Yes that is the case even now as well, so should be acceptable I guess.

But this won't remove any existing entries from FileCache, so already served IndexInputs will continue to work (and we won't encounter unexpected errors during reads)

Comment (rayshrey) [reply server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java:82]:
```
if (!theCache.exists(key)) {
    checkParentBreaker();
}
return theCache.compute(key, remappingFunction);
```

The problem with this will again be the check for entries which exists but are closed - will need to check that as well. So it should essentially boil down to below (might refactor the logic to a separate function like `checkParentBreakerIfKeyMissingOrClosed`):

```
try {
    CachedIndexInput indexInput = fileCache.get(key);
    if (indexInput == null || indexInput.isClosed()) {
        checkParentBreaker();
    }
} finally {
    fileCache.decRef(key);
}
return theCache.compute(key, remappingFunction);
```

Is this what we are looking for @andrross ?

Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java:82]: > Yes that is the case even now as well, so should be acceptable I guess.

Good point. I think this is okay. We can change it if it becomes problematic.

**Review by andrross — APPROVED** [review]
