### PR TITLE
Fix flaky RemoteIndexRecoveryIT testRerouteRecovery test #9580

### LINKED ISSUE #9580: [CI]flaky test faiure - org.opensearch.remotestore.RemoteIndexRecoveryIT.testRerouteRecovery
Seen in https://github.com/opensearch-project/OpenSearch/pull/9506#issuecomment-1695648462, build No.[23062](https://build.ci.opensearch.org/job/gradle-check/23602/)
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteIndexRecoveryIT.testRerouteRecovery" -Dtests.seed=8D8D1A98A3C03275 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=zh-Hans-CN -Dtests.timezone=Africa/Nairobi -Druntime.java=20

org.opensearch.remotestore.RemoteIndexRecoveryIT > testRerouteRecovery FAILED
    java.lang.AssertionError: 
    Expected: <1>
         but: was <0>
        at __randomizedtesting.SeedInfo.seed([8D8D1A98A3C03275:2026A9CC96985037]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.indices.recovery.IndexRecoveryIT.lambda$testRerouteRecovery$1(IndexRecoveryIT.java:528)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1085)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1058)
        at org.opensearch.indices.recovery.IndexRecoveryIT.testRerouteRecovery(IndexRecoveryIT.java:526)
...
```

### PR DESCRIPTION
**Pull request by ashking94**
### Description
This PR fixes the flakiness in the testRerouteRecovery of RemoteIndexRecoveryIT.

The issue is happening due to 2 reasons as we have seen the stack trace -

1. Index not found
```
org.opensearch.remotestore.RemoteIndexRecoveryIT > testRerouteRecovery FAILED
    [test-idx-1/gUdo_ZgeQSeTKz75x2BNLA] IndexNotFoundException[no such index [test-idx-1]]
        at __randomizedtesting.SeedInfo.seed([216A80F8C219BD32:8CC133ACF741DF70]:0)
        at app//org.opensearch.indices.IndicesService.indexServiceSafe(IndicesService.java:689)
        at app//org.opensearch.indices.recovery.IndexRecoveryIT.lambda$testRerouteRecovery$1(IndexRecoveryIT.java:528)
```

2. Assertion failure 
```
java.lang.AssertionError: 
Expected: <1>
     but: was <0>
	at __randomizedtesting.SeedInfo.seed([A66685B0FBDCA162:BCD36E4CE84C320]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.indices.recovery.IndexRecoveryIT.lambda$testRerouteRecovery$1(IndexRecoveryIT.java:528)
```

The first issue happens due to cluster state publication cleaning up the index shard on the old primary node between 2 assertion check interval. The current assertBusy has exponential backoff between 2 assertion checks and between these 2 checks, the condition of assertion becomes true and the index shard itself gets cleared from the old node. However, due to high interval, it misses hitting the assertion true condition. The fix for this issue is to have the assertion checks done at fixed interval.

The second issue occurs due to the same reason as above but in this case the peer recovery has completed and changed the state of recovery state of the index shard.  

### Related Issues
Resolves #9580

### Check List
- [ ] ~New functionality includes testing.~
  - [x] All tests pass
- [ ] ~New functionality has been documented.~
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ashking94** [comment]
Running the testRerouteRecovery for RemoteIndexRecoveryIT and IndexRecoveryIT both for 1K iterations atleast. Without the fix, the test currently fails around 20th iteration.

**Comment by ashking94** [comment]
> ❌ Gradle check result for [ff8fc99](https://github.com/opensearch-project/OpenSearch/commit/ff8fc99e8211d1ec37156ab02f172cb88f996d2d): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/32281/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test - https://github.com/opensearch-project/OpenSearch/issues/9891

**Comment by ashking94** [comment]
> RemoteIndexPrimaryRelocationIT

Flaky test - https://github.com/opensearch-project/OpenSearch/issues/9191

**Comment by ashking94** [comment]
The test has been run on iteration for more than 1K iterations without any failure yet.

**Comment by andrross** [comment]
> However, due to high interval, it misses hitting the assertion true condition. The fix for this issue is to have the assertion checks done at fixed interval.

Are you actually fixing the race condition here, or just making it much less likely? How can we make the test pass in a way that isn't dependent on the timing of the assertions?

**Comment by ashking94** [comment]
> > However, due to high interval, it misses hitting the assertion true condition. The fix for this issue is to have the assertion checks done at fixed interval.
> 
> Are you actually fixing the race condition here, or just making it much less likely? How can we make the test pass in a way that isn't dependent on the timing of the assertions?

There is no underlying problem here. The test tries to assert an intermediate state which is there transiently and for a very short period. The problem exists in the underlying doc rep test as well.

File: test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java [hunk 1]
```diff
@@ -1095,6 +1096,38 @@ public static void assertBusy(CheckedRunnable<Exception> codeBlock, long maxWait
...
+            Thread.sleep(sleepTimeInMillis);
+        }
+        try {
+            codeBlock.run();
+        } catch (AssertionError e) {
+            for (AssertionError failure : failures) {
+                e.addSuppressed(failure);
+            }
+            throw e;
+        }
```
Comment (gbbafna) [inline test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java:1128]: why do we need this extra `try..catch` block ?

Comment (ashking94) [reply test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java:1128]: This is just the final attempt to try run the code to be asserted one last time along with adding previous assertion errors and throwing it back.

**Review by gbbafna — APPROVED** [review]
