### PR TITLE
[Remote Store] Fix refresh lag bug on primary term change

### LINKED ISSUE #10917: [BUG] Race condition in RemoteStoreRefreshListener that leads to refresh lag increasing
**Describe the bug**
There is a bug in RemoteStoreRefreshListener class which is occurring on primary term change when a retry is happening. This is more prominent during index creation and failover. 

**To Reproduce**
On a stable remote store cluster, create an index or fail the node holding shard abruptly. You will notice that the `max_refresh_time_lag_in_millis` from node stats api starts increasing gradually while the `refresh_size_lag` field shows 0 byte lag.

**Expected behavior**
The refresh lag should be zero.

### PR DESCRIPTION
**Pull request by ashking94**
### Description
There is a bug in RemoteStoreRefreshListener class which is occurring on primary term change when a retry is happening. This is more prominent during index creation and failover.

### Related Issues
Resolves #10917

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 1]
```diff
@@ -150,25 +149,34 @@ protected void runAfterRefreshExactlyOnce(boolean didRefresh) {
...
 
-    private boolean shouldSync(boolean didRefresh) {
-        return this.primaryTerm != indexShard.getOperationPrimaryTerm()
-            // If the readers change, didRefresh is always true.
-            || didRefresh
+    /**
+     * This checks if there is a sync required to remote.
+     *
+     * @param didRefresh             if the readers changed.
+     * @param avoidPrimaryTermChange consider change in primary term or not for should sync
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:164]: We don't change primary term in this method. Parameter can be named as `avoidPrimaryTermCheck` or `checkPrimaryTermChange` or something which denotes that we don't need to check primary term in order to proceed further.

Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java]: Incorporated

**Review by sachinpkale — APPROVED** [review]

**Comment by mch2** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29022/
> * **CommitID:** [8175cb3](https://github.com/opensearch-project/OpenSearch/commit/8175cb340ded0786363785d613d0590ae6751a00)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

https://github.com/opensearch-project/OpenSearch/issues/7557
