### PR TITLE
Fix object field exists query

### LINKED ISSUE #17808: [BUG] Object Field exists query returns wrong result
### Describe the bug

Today, we skip all subfields with a prefix `'_'` when generating the exists query clause for the object field to avoid UOE thrown by some internal fields, like prefix field of search_as_you_type field or prefix/phrase field of text field, but this can cause unexpected behavior if a user subfield name starts with `'_'`. Moreover, if a object field has a derived type subfield, exists query throws a IAE.

### Related component

Search

### A user subfield name starts with '_'
1. create index
```
PUT test
{
  "mappings": {
    "properties": {
      "outer": {
        "properties": {
          "_inner": {
            "type": "keyword"
          }
        }
      }
    }
  }
}
```
2. index some data
```
POST test/_bulk?refresh=true
{"index": {}}
{"outer": {"_inner": "foo"}}
```
3. exists query
```
POST test/_search
{
  "query": {
    "exists": {
      "field": "outer"
    }
  }
}
```
which matches no docs

### A object field has a derived type subfield
1. create index
```
PUT test
{
  "mappings": {
    "properties": {
      "log": {
        "properties": {
          "request": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword"
              }
            }
          }
        }
      }
    },
    "derived": {
      "log.timestamp": {
        "type": "date",
        "format": "MM/dd/yyyy",
        "script": {
          "source": "emit(Long.parseLong(doc[\"log.request.keyword\"].value.splitOnToken(\" \")[0]))"
        }
      }
    }
  }
}
```
2. index some data
```
POST test/_bulk?refresh=true
{"index": {}}
{"log": {"request": "894030400 GET /english/images/france98_venues.gif HTTP/1.0 200 778"}}
```
3. exists query
```
POST test/_search
{
  "query": {
    "exists": {
      "field": "log"
    }
  }
}
```
which throws a IAE
```
"failed_shards": [
      {
        "shard": 0,
        "index": "test",
        "node": "5vtqUIDFSVuf1iPbEJ7Qig",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to create query: Field [log.timestamp] of type [derived] does not support exist queries",
          "index": "test",
          "index_uuid": "oR_xg-kuTE-G_KWZX6Q0ZQ",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Field [log.timestamp] of type [derived] does not support exist queries"
          }
        }
      }
    ]
```

### Expected behavior

The exists query should match all docs.

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by bugmakerrrrrr**
### Description
To fix #17808, there are three methods:
1. Ignore subfields that throw exceptions, i.e., do not support the exists query;
2. Make all fields that do not support the exists query return MatchNoDocsQuery and do not throw exceptions;
3. Provide a flag to indicate that a field is derived from another field, and ignore subfields of this type when creating an object field exists query

This PR chooses method 1 because it's simple and can cover all fields.

### Related Issues
Resolves #17808

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java [hunk 1]
```diff
@@ -202,13 +202,13 @@ private static Query newObjectFieldExistsQuery(QueryShardContext context, String
...
         Collection<String> fields = context.simpleMatchToIndexNames(objField + ".*");
         for (String field : fields) {
-            int dotPos = field.lastIndexOf('.');
-            if (dotPos > 0 && field.charAt(dotPos + 1) == '_') {
-                // This is a subfield (e.g. prefix) of a complex field type. Skip it.
-                continue;
+            try {
+                Query existsQuery = context.getMapperService().fieldType(field).existsQuery(context);
+                booleanQuery.add(existsQuery, Occur.SHOULD);
+            } catch (Exception e) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java:208]: Am thinking rather than adding this catch all we can check if the field type is `DerivedFieldType` here instead and leave the subfield check above?

```java
            MappedFieldType mappedFieldType = context.getMapperService().fieldType(field);
            if (mappedFieldType instanceof DerivedFieldType) continue;
```

Comment (mch2) [reply server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java:208]: I see, In that case I like your suggestion of catching UOE specifically over the Exception catch all.

**Review by mch2 — APPROVED** [review]

**Review by mch2 — APPROVED** [review]

**Review by deshsidd — APPROVED** [review]
