### PR TITLE
Fix stats API of SubdirectoryAwareStore

### LINKED ISSUE #19468: [BUG] Fix stat API for SubdirectoryAwareStore
### Describe the bug

SubdirectoryStore's stat API is not reporting the correct value since the Store class is initialized with the directory reference which points to /index directory only. This refactoring fixes the issue by passing the wrapped directory instance which acts as a delegate in base class.

### Related component

Other

### Expected behavior

SubdirectoryAwareStore' stat API should report the correct store size.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by bpatelcs**
### Description
This change refactors the SubdirectoryAwareStore so that base class's stats API can use the instance of SubdirectoryAwareStore as delegate to find all the relevant files via listAll() to estimate the store size.

### Related Issues
Resolves #19468

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: modules/store-subdirectory/src/main/java/org/opensearch/plugin/store/subdirectory/SubdirectoryAwareStore.java [hunk 1]
```diff
@@ -254,17 +250,30 @@ public String[] listAll() throws IOException {
...
-                Path relativePath = dataPath.relativize(file);
-                // Only add files that are in subdirectories (have a parent directory)
-                if (relativePath.getParent() != null) {
-                    String relativePathStr = relativePath.toString();
-                    // Exclude index dir (handled in super.listAll()), translog dir, and _state dir
-                    if (EXCLUDED_SUBDIRECTORIES.stream().noneMatch(relativePathStr::startsWith)) {
-                        allFiles.add(relativePathStr);
+                @Override
+                public FileVisitResult visitFileFailed(Path file, IOException e) throws IOException {
+                    if (e instanceof NoSuchFileException) {
```
Comment (xuxiong1) [inline modules/store-subdirectory/src/main/java/org/opensearch/plugin/store/subdirectory/SubdirectoryAwareStore.java:272]: I saw in server/src/main/java/org/opensearch/index/store/ByteSizeCachingDirectory.java we are ignoring:
```
            } catch (NoSuchFileException | FileNotFoundException | AccessDeniedException e) {
                // ignore, the file is not there no more; on Windows, if one thread concurrently deletes a file while
                // calling Files.size, you can also sometimes hit AccessDeniedException
            }
```
we may also add the other two exceptions to be more defensive.

Comment (bpatelcs) [reply modules/store-subdirectory/src/main/java/org/opensearch/plugin/store/subdirectory/SubdirectoryAwareStore.java:272]: ByteSizeCachingDirectory catches those from directory.fileLength()call and not from listAll().

**Review by xuxiong1 — APPROVED** [review]

**Review by yupeng9 — APPROVED** [review]
