### PR TITLE
Fix testCacheFilesAreClosedAfterUse for Searchable Snapshots

### LINKED ISSUE #6888: [BUG] SearchableSnapshotIT.testCacheFilesAreClosedAfterUse test failures
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.SearchableSnapshotIT.testCacheFilesAreClosedAfterUse" -Dtests.seed=FABDEC96AAADA3F2 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-EG -Dtests.timezone=America/Antigua -Druntime.java=19

org.opensearch.snapshots.SearchableSnapshotIT > testCacheFilesAreClosedAfterUse FAILED
    java.lang.AssertionError: Cache file path isn't deleted.
        at __randomizedtesting.SeedInfo.seed([FABDEC96AAADA3F2:A74AFD6D02D27FBD]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.snapshots.SearchableSnapshotIT.testCacheFilesAreClosedAfterUse(SearchableSnapshotIT.java:564)
```

https://build.ci.opensearch.org/job/gradle-check/13061/console

### PR DESCRIPTION
**Pull request by kotwanikunal**
### Description
- Fixes `testCacheFilesAreClosedAfterUse` to check all the `search` nodes for cache locations
- There are two checks - one which happens after restore and another which happens after deletions
- Ensures that the index exists on cache when restored and cache folder for the location is cleared when index is deleted

### Issues Resolved
- Resolves #6888 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java [hunk 1]
```diff
@@ -547,24 +554,58 @@ public void testCacheFilesAreClosedAfterUse() throws Exception {
...
+        List<Path> searchNodeFileCachePaths = StreamSupport.stream(nodeEnvironments.spliterator(), false)
+            .filter(nodeEnv -> nodeEnv.fileCache() != null)
+            .map(nodeEnv -> nodeEnv.fileCacheNodePath().fileCachePath)
+            .collect(Collectors.toList());
+
+        for (Path fileCachePath : searchNodeFileCachePaths) {
+            assertTrue(Files.exists(fileCachePath));
+            assertTrue(Files.isDirectory(fileCachePath));
+            try (DirectoryStream<Path> pathStream = Files.newDirectoryStream(fileCachePath)) {
+                for (Path dataPath : pathStream) {
```
Comment (andrross) [inline server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java:577]: Do we expect there to only be one here as well? This test would pass if the path stream was empty, I think. Maybe better to do something like `pathStream.iterator().next()` to rely on there being exactly one.

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java [hunk 2]
```diff
@@ -547,24 +554,58 @@ public void testCacheFilesAreClosedAfterUse() throws Exception {
...
+        Iterable<NodeEnvironment> nodeEnvironments = internalCluster().getInstances(NodeEnvironment.class);
+
+        // Filter out search NodeEnvironment(s) since FileCache is initialized only on search nodes and
+        // collect the path for all the cache locations on search nodes.
+        List<Path> searchNodeFileCachePaths = StreamSupport.stream(nodeEnvironments.spliterator(), false)
+            .filter(nodeEnv -> nodeEnv.fileCache() != null)
+            .map(nodeEnv -> nodeEnv.fileCacheNodePath().fileCachePath)
+            .collect(Collectors.toList());
+
+        for (Path fileCachePath : searchNodeFileCachePaths) {
```
Comment (andrross) [inline server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java:573]: Can this be refactored into a method like `assertCacheDirectoryCount(int)` or something similar?

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java (hunk 1 above)
Comment (kotwanikunal) [reply server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java:577]: That's the subdirectory within the cache folder for the `nodeLockId`. There should be only 1 folder there. 
https://github.com/opensearch-project/OpenSearch/blob/71a76da0d894181e909237f50522c3e475a9540e/server/src/main/java/org/opensearch/env/NodeEnvironment.java#L1359-L1363

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java (hunk 2 above)
Comment (kotwanikunal) [reply server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java:573]: Sure.

**Comment by kotwanikunal** [comment]
Intermittent failure:
```
-----------
* What went wrong:
Execution failed for task ':distribution:docker:buildDockerImage'.
> A failure occurred while executing org.opensearch.gradle.docker.DockerBuildTask$DockerBuildAction
   > Failed to pull Docker **** image [centos:8], all attempts failed

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
```

**Comment by kotwanikunal** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/13169/
> * **CommitID:** [529537f](https://github.com/opensearch-project/OpenSearch/commit/529537fc42d406771bcc6a2227220f0a240b770a)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

```
AILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':test:fixtures:azure-fixture:composeBuild'.
> Exit-code 1 when calling /usr/bin/docker-compose, stdout: Step 1/5 : FROM ubuntu:18.04

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':test:fixtures:krb5kdc-fixture:composeBuild'.
> Exit-code 1 when calling /usr/bin/docker-compose, stdout: Step 1/9 : FROM ubuntu:14.04

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':test:fixtures:gcs-fixture:composeBuild'.
> Exit-code 1 when calling /usr/bin/docker-compose, stdout: Step 1/11 : FROM ubuntu:18.04

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
```

Looks like CI is facing issues

**Review by andrross — APPROVED** [review]
