### PR TITLE
Fix slice collectors to leaves association with post filter

### LINKED ISSUE #10767: [Concurrent Segment Search][BUG] Incorrect slice collectors to leaves association with profile enabled
**Describe the bug**
In the concurrent search case, we found there is no `associateCollectorToLeaves()` called for `FilteredCollector:getLeafCollector()` to build the scorer. This issue caused the issue to create profile result.
```
ContextIndexSearcher.searchLeaf() collector.getLeafCollector() -> FiliteredCollectorManager.newCollector() -> FilteredCollector.getLeafCollector() -> scorerSupplier(context)
```
**To Reproduce**
```
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.query.QueryProfilePhaseTests" -Dtests.method="testIndexSortingEarlyTermination [p0=5 p1=org.opensearch.search.query.ConcurrentQueryPhaseSearcher@487db668]" -Dtests.seed=82745E9780FC847D -Dtests.security.manager=false -Dtests.locale=fr-FR -Dtests.timezone=Kwajalein -Druntime.java=18
```
```
java.lang.AssertionError: OpenSearchException[Unexpected size: 6 of leaf breakdown in ConcurrentQueryProfileBreakdown of rewritten query for a leaf.]

	at __randomizedtesting.SeedInfo.seed([82745E9780FC847D:FAAC3E093A92215F]:0)
	at org.opensearch.search.profile.query.ConcurrentQueryProfileBreakdown.toBreakdownMap(ConcurrentQueryProfileBreakdown.java:95)
	at org.opensearch.search.profile.query.ConcurrentQueryProfileTree.createProfileResult(ConcurrentQueryProfileTree.java:44)
	at org.opensearch.search.profile.query.ConcurrentQueryProfileTree.createProfileResult(ConcurrentQueryProfileTree.java:24)
	at org.opensearch.search.profile.AbstractInternalProfileTree.doGetTree(AbstractInternalProfileTree.java:183)
	at org.opensearch.search.profile.AbstractInternalProfileTree.getTree(AbstractInternalProfileTree.java:155)
	at org.opensearch.search.profile.query.ConcurrentQueryProfileTree.getTree(ConcurrentQueryProfileTree.java:77)
	at org.opensearch.search.profile.query.ConcurrentQueryProfiler.getTree(ConcurrentQueryProfiler.java:74)
	at org.opensearch.search.profile.SearchProfileShardResults.buildShardResults(SearchProfileShardResults.java:202)
	at org.opensearch.search.query.QueryProfilePhaseTests.assertProfileData(QueryProfilePhaseTests.java:1494)
	at org.opensearch.search.query.QueryProfilePhaseTests.assertProfileData(QueryProfilePhaseTests.java:1483)
	at org.opensearch.search.query.QueryProfilePhaseTests.testIndexSortingEarlyTermination(QueryProfilePhaseTests.java:857)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: OpenSearchException[Unexpected size: 6 of leaf breakdown in ConcurrentQueryProfileBreakdown of rewritten query for a leaf.]
	... 49 more
```
**Expected behavior**

**Plugins**
Standard

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - CI

**Additional context**

### PR DESCRIPTION
**Pull request by ticheng-aws**
### Description
In the post filter query, a profile node is created during the creation of the filtered collector context, which occurred before the concurrent path in `ContextIndexSearcher::search()`. However, there is no association call for the filtered collector to leaves. Consequently, this led to an unexpected context size when generating the profile results.

This PR adds the association for the collector to leaves before building the scorer on the post-filter profile node. Following this modification, we can identify the missing association call for `sliceCollectorsToLeave@739870973`, and we can also confirm that the leaf counts in the `contexts` map match those in `sliceCollectorsToLeaves` when we invoke `toBreakdownMap() `to build the result.

``` ruby
------------ post filter query with 2 slices and 1 leaf/slice -------------
-- query rewrite --
-- query rewrite --
[T#21] ConcurrentQueryProfileBreakdown.sliceCollectorsToLeaves@2013178468
[T#21] searcher.search(query, collectorManager)
-- query rewrite --
[T#21] ConcurrentQueryProfileBreakdown.sliceCollectorsToLeaves@739870973
[T#21] ConcurrentQueryProfileBreakdown.sliceCollectorsToLeaves@208094559
[T#26] == search ===
[T#27] == search ===
[T#26] = searchLeaf() =
[T#27] = searchLeaf() =
[T#27] ConcurrentQueryProfileBreakdown.associateCollectorToLeaves() | sliceCollectorsToLeaves@739870973
[T#26] ConcurrentQueryProfileBreakdown.associateCollectorToLeaves() | sliceCollectorsToLeaves@739870973
[T#27] FilteredCollector.getLeafCollector() called
[T#26] FilteredCollector.getLeafCollector() called
[T#27] ConcurrentQueryProfileBreakdown.associateCollectorToLeaves() | sliceCollectorsToLeaves@2013178468
[T#26] ConcurrentQueryProfileBreakdown.associateCollectorToLeaves() | sliceCollectorsToLeaves@2013178468
[T#27] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_1(9.8.0):C76 | sliceCollectorsToLeaves@2013178468
[T#26] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_0(9.8.0):C524 | sliceCollectorsToLeaves@2013178468
[T#27] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_1(9.8.0):C76 | sliceCollectorsToLeaves@2013178468
[T#26] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_0(9.8.0):C524 | sliceCollectorsToLeaves@2013178468
[T#27] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_1(9.8.0):C76 | sliceCollectorsToLeaves@739870973
[T#26] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_0(9.8.0):C524 | sliceCollectorsToLeaves@739870973
[T#27] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_1(9.8.0):C76 | sliceCollectorsToLeaves@208094559
[T#26] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_0(9.8.0):C524 | sliceCollectorsToLeaves@208094559
[T#27] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_1(9.8.0):C76 | sliceCollectorsToLeaves@208094559
[T#26] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_0(9.8.0):C524 | sliceCollectorsToLeaves@208094559
[T#27] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_1(9.8.0):C76 | sliceCollectorsToLeaves@739870973
[T#26] ConcurrentQueryProfileBreakdown.context() context=LeafReaderContext(FilterLeafReader(_0(9.8.0):C524 | sliceCollectorsToLeaves@739870973
[T#21] ConcurrentQueryProfileBreakdown.associateCollectorsToLeaves() | sliceCollectorsToLeaves@208094559
[T#21] toBreakdownMap() contexts=2 | sliceCollectorsToLeaves@2013178468=2
...
[T#21] toBreakdownMap() contexts=2 | sliceCollectorsToLeaves@208094559=2
...
[T#21] toBreakdownMap() contexts=2 | sliceCollectorsToLeaves@739870973=2
...
```

### Related Issues
Resolves #10767

### Check List
- [ ] ~New functionality includes testing.~
  - [X] All tests pass
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ticheng-aws** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** UNSTABLE ❕
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.search.SearchWeightedRoutingIT.testShardRoutingWithNetworkDisruption_FailOpenEnabled
> ```
> 
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29772/
> * **CommitID:** [9e90dfa](https://github.com/opensearch-project/OpenSearch/commit/9e90dfab5bc6abc1f29ef076676599645972181c)
>   Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

This is a known flaky test https://github.com/opensearch-project/OpenSearch/issues/10673

**Comment by ticheng-aws** [comment]
Hi @sohami and @reta, please help to review. Thank you in advance.

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java [hunk 1]
```diff
@@ -83,7 +83,12 @@ public Map<String, Long> toBreakdownMap() {
             // creates a new weight and breakdown map for each rewritten query. This new breakdown map captures the timing information for
             // the new rewritten query. The sliceCollectorsToLeaves is empty because this breakdown for rewritten query gets created later
             // in search leaf path which doesn't have collector. Also, this is not needed since this breakdown is per leaf and there is no
-            // concurrency involved. An empty sliceCollectorsToLeaves could also happen in the case of early termination.
+            // concurrency involved.
+            assert contexts.size() == 1 : new OpenSearchException(
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:87]: Why do we need to create `OpenSearchException` here? 

```suggestion
            assert contexts.size() == 1 : "Unexpected size: "
                    + contexts.size() + " of leaves breakdown in ConcurrentQueryProfileBreakdown of rewritten query for a leaf."
```

should be enough?

Comment (ticheng-aws) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:87]: Hi @reta, thanks for the review. This assertion could help us to catch unknown edge cases. For example, before this PR, post filter profile breakdown could have more than 1 context here. And `assert contexts.size() == 1` is because we only expect 1 context in the case mentioned from L82 to L86.

Comment (reta) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java]: Thanks @ticheng-aws , the assertion is fine, I was wondering why we create `OpenSearchException` here?

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java [hunk 2]
```diff
@@ -83,7 +83,13 @@ public Map<String, Long> toBreakdownMap() {
             // creates a new weight and breakdown map for each rewritten query. This new breakdown map captures the timing information for
             // the new rewritten query. The sliceCollectorsToLeaves is empty because this breakdown for rewritten query gets created later
             // in search leaf path which doesn't have collector. Also, this is not needed since this breakdown is per leaf and there is no
-            // concurrency involved. An empty sliceCollectorsToLeaves could also happen in the case of early termination.
+            // concurrency involved.
+            assert contexts.size() == 1 : "Unexpected size: "
+                    + contexts.size() + " of leaves breakdown in ConcurrentQueryProfileBreakdown of rewritten query for a leaf."
+                "Unexpected size: "
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:89]: Uh ... sorry about that, Github messed up the suggestion :(

Comment (ticheng-aws) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java]: Oops! I have fixed it now.

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java (hunk 1 above)
Comment (ticheng-aws) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java]: Got it... thanks. It has been addressed now.

**Review by reta — APPROVED** [review]

**Comment by ticheng-aws** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** UNSTABLE ❕
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.search.SearchWeightedRoutingIT.testStrictWeightedRoutingWithCustomString_FailOpenEnabled
>       1 org.opensearch.remotestore.RemoteStoreStatsIT.testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs
>       1 org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness
> ```
> 
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29779/
> * **CommitID:** [a19ce33](https://github.com/opensearch-project/OpenSearch/commit/a19ce33183c53cecc4d4aec0efe06df8ca699df9)
>   Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

https://github.com/opensearch-project/OpenSearch/issues/3603
https://github.com/opensearch-project/OpenSearch/issues/8030
https://github.com/opensearch-project/OpenSearch/issues/11149
