### PR TITLE
Fix terms lookup subquery to use cluster max_clause_count setting

### LINKED ISSUE #20820: [BUG] TermsQueryBuilder uses wrong setting key for max_clause_count
### Describe the bug

In `TermsQueryBuilder.java` (line 611), the terms lookup fetch-size logic reads the setting key `"indices.query.max_clause_count"` instead of the correct `"indices.query.bool.max_clause_count"`.

```java
// Current (incorrect) — TermsQueryBuilder.java:611
int maxClauseCount = idxSettings.getAsInt("indices.query.max_clause_count", 1024);
```

The correct setting key, as defined in `SearchService.INDICES_MAX_CLAUSE_COUNT_SETTING`, is:

```java
// SearchService.java:398
"indices.query.bool.max_clause_count"
```

Because `"indices.query.max_clause_count"` is never a registered setting, `getAsInt` always falls back to the hardcoded default of `1024`, making any user/operator configuration of `indices.query.bool.max_clause_count` silently ignored when computing the terms lookup fetch size.

### To reproduce

1. Set the cluster setting `indices.query.bool.max_clause_count` to a value other than 1024 (e.g., 4096).
2. Run a `terms` query with a `terms_lookup` that would benefit from a larger fetch size.
3. Observe that the fetch size is still capped at 1024 regardless of the configured value.

### Expected behavior

The terms lookup fetch-size calculation should read `"indices.query.bool.max_clause_count"` (or ideally use the typed `SearchService.INDICES_MAX_CLAUSE_COUNT_SETTING` constant) so that the operator-configured value is respected.

### Suggested fix

```java
// Option A: Use the typed Setting (preferred)
int maxClauseCount = SearchService.INDICES_MAX_CLAUSE_COUNT_SETTING.get(idxSettings);

// Option B: Use the correct string key
int maxClauseCount = idxSettings.getAsInt("indices.query.bool.max_clause_count", 1024);
```

The test in `TermQueryWithDocIdAndQueryTests.java:380` also uses the wrong key and should be updated to match.

### OpenSearch version

main (HEAD)

### Operating system

All

### Additional context

The `.bool.` segment was likely dropped during development. The setting was made dynamically updateable in [#13568](https://github.com/opensearch-project/OpenSearch/pull/13568) (2.16.0), but this code path was not updated to use the correct key.

### PR DESCRIPTION
**Pull request by bcsimoes**
### Description

`TermsQueryBuilder.fetch()` reads `indices.query.max_clause_count` (without `.bool.`) from index settings — a non-existent, unregistered setting path — with a hardcoded fallback of 1024. The actual cluster setting `indices.query.bool.max_clause_count` is never consulted, making the fetch limit unconfigurable.

**Fix:** Replace the raw `idxSettings.getAsInt(...)` call with `IndexSearcher.getMaxClauseCount()`, which already reflects the cluster setting via `SearchService.INDICES_MAX_CLAUSE_COUNT_SETTING`.

**Test:** Added `testTermsLookupFetchLimitUsesClusterMaxClauseCount` validating that the fetch limit mechanism reads from `IndexSearcher.getMaxClauseCount()` (backed by the registered cluster setting) rather than a hardcoded value.

Introduced in PR #18195.

### Related Issues

Resolves #20820
Relates to #17599 (partially — the feature works but the limit is misconfigured)

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/index/query/TermQueryWithDocIdAndQueryTests.java [hunk 1]
```diff
@@ -372,13 +373,8 @@ public void testTermsLookupSubqueryTotalHitsExceedsFetchSize() throws Exception
...
 
-        // Settings that produce a small fetch size
-        int maxTermsCount = 5, maxResultWindow = 5, maxClauseCount = 5;
-        Settings idxSettings = Settings.builder()
-            .put("index.max_terms_count", maxTermsCount)
-            .put("index.max_result_window", maxResultWindow)
-            .put("indices.query.max_clause_count", maxClauseCount)
-            .build();
+        // Set maxTermsCount and maxResultWindow high so maxClauseCount (3) is the limiting factor
+        Settings idxSettings = Settings.builder().put("index.max_terms_count", 100).put("index.max_result_window", 100).build();
```
Comment (gaobinlong) [inline server/src/test/java/org/opensearch/index/query/TermQueryWithDocIdAndQueryTests.java]: Could we use the setting key like `IndexSettings.MAX_TERMS_COUNT_SETTING.getKey()` instead?

Comment (bcsimoes) [reply server/src/test/java/org/opensearch/index/query/TermQueryWithDocIdAndQueryTests.java]: hey @gaobinlong  gaobinlong thank you for taking time to review this pr, 100% will do in a sec
