### PR TITLE
Fix flaky RepositoriesServiceIT.testCreatSnapAndUpdateReposityCauseInfiniteLoop

### LINKED ISSUE #15842: [AUTOCUT] Gradle Check Flaky Test Report for RepositoriesServiceIT
## Flaky Test Report for `RepositoriesServiceIT`

Noticed the `RepositoriesServiceIT` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| 5d308e084d8e9b26fe5e33178f2d7db4faed0baf | [18067](https://github.com/opensearch-project/OpenSearch/pull/18067) | [57240](https://build.ci.opensearch.org/job/gradle-check/57240/testReport/) | `org.opensearch.repositories.RepositoriesServiceIT.testCreatSnapAndUpdateReposityCauseInfiniteLoop` |
| b32fcef2422694b432a6baa3df0767e7dd886da2 | [17977](https://github.com/opensearch-project/OpenSearch/pull/17977) | [57061](https://build.ci.opensearch.org/job/gradle-check/57061/testReport/) | `org.opensearch.repositories.RepositoriesServiceIT.testCreatSnapAndUpdateReposityCauseInfiniteLoop` |
| c308b9857e7cd83d7cea243416cf2cc36b1ebad2 | [15426](https://github.com/opensearch-project/OpenSearch/pull/15426) | [46080](https://build.ci.opensearch.org/job/gradle-check/46080/testReport/) | `org.opensearch.repositories.RepositoriesServiceIT.testUpdateRepository` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `RepositoriesServiceIT` class are:

- [14809](https://github.com/opensearch-project/OpenSearch/pull/14809)
- [17532](https://github.com/opensearch-project/OpenSearch/pull/17532)
- [18069](https://github.com/opensearch-project/OpenSearch/pull/18069)
- [17759](https://github.com/opensearch-project/OpenSearch/pull/17759)
- [17988](https://github.com/opensearch-project/OpenSearch/pull/17988)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by kkewwei**
### Description
[Describe what this change achieves]

### Related Issues
Resolves #15842

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java [hunk 1]
```diff
@@ -173,16 +172,20 @@ public void testCreatSnapAndUpdateReposityCauseInfiniteLoop() throws Interrupted
...
-        repoSettings = Settings.builder().put("location", randomRepoPath()).put("max_snapshot_bytes_per_sec", "300mb");
-        OpenSearchIntegTestCase.putRepositoryWithNoSettingOverrides(
-            client().admin().cluster(),
-            repositoryName,
-            FsRepository.TYPE,
-            true,
-            repoSettings
-        );
-        logger.info("--> finish to reset repository");
+        try {
```
Comment (kkewwei) [inline server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java:175]: The original intention of the unit test is to test that there will be no more dead loops. Occasional throwing exception is expected, as long as there is no more infinate loop.

**Review by andrross — APPROVED** [review]
