### PR TITLE
Fix default tracer flaky test

### LINKED ISSUE #9780: [BUG] org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans is flaky
**Describe the bug**
The org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans is flaky

```
org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans

java.lang.AssertionError: expected:&lt;org.opensearch.test.telemetry.tracing.MockSpan@19146f98&gt; but was:&lt;null&gt;
	at __randomizedtesting.SeedInfo.seed([D9BCB54305D17127:BF4A5911DBDD9525]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans(DefaultTracerTests.java:385)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)</pre>org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans
```

**To Reproduce**
```
 ./gradlew ':libs:opensearch-telemetry:test' --tests "org.opensearch.telemetry.tracing.DefaultTracerTests.testSpanAcrossThreadsMultipleSpans" -Dtests.seed=D9BCB54305D17127 
```

**Expected behavior**
Test must always pass

**Plugins**
Standard

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - CI
 - 
**Additional context**
https://build.ci.opensearch.org/job/gradle-check/24505/testReport/junit/org.opensearch.telemetry.tracing/DefaultTracerTests/testSpanAcrossThreadsMultipleSpans/

### PR DESCRIPTION
**Pull request by Gaganjuneja**
### Description
Fixes flaky tests #9780

### Related Issues
Resolves #9780 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java [hunk 1]
```diff
@@ -265,32 +267,41 @@ public void testSpanAcrossThreads() {
...
                 Span spanT2 = defaultTracer.startSpan(new SpanCreationContext("span_name_t_2", Attributes.EMPTY));
                 SpanScope spanScopeT2 = defaultTracer.withSpanInScope(spanT2);
                 spanT2Ref.set(spanT2);
 
                 currentSpanRefThread2.set(defaultTracer.getCurrentSpan().getSpan());
 
-                spanT2.endSpan();
                 spanScopeT2.close();
+                spanT2.endSpan();
                 currentSpanRefAfterEndThread2.set(getCurrentSpanFromContext(defaultTracer));
```
Comment (reta) [inline libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java:285]: Since you are using futures, you could assert directly,  no need to use external context:

```
assertEquals(getCurrentSpanFromContext(defaultTracer), equalTo(null)));
```

File: libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java [hunk 2]
```diff
@@ -265,32 +267,41 @@ public void testSpanAcrossThreads() {
...
             });
+            try {
+                asyncTask1.get();
```
Comment (reta) [inline libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java:288]: Please use:

```suggestion
                asyncTask1.join();
```

no need to manage exceptions

File: libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java [hunk 3]
```diff
@@ -249,75 +250,66 @@ public void testEndSpanByClosingSpanScopeMultiple() {
...
             spanScope.close();
-            currentSpanRefThread1.set(getCurrentSpanFromContext(defaultTracer));
-        });
-        assertEquals(spanT2Ref.get(), currentSpanRefThread2.get());
-        assertEquals(spanRef.get(), currentSpanRefAfterEndThread2.get());
-        assertEquals(null, currentSpanRefThread1.get());
+            span.endSpan();
+            assertEquals(null, defaultTracer.getCurrentSpan());
+        }, executorService);
+        asyncTask.get();
```
Comment (reta) [inline libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java:282]: Please use `join` as well:

```suggestion
        asyncTask.join();
```

File: libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java [hunk 4]
```diff
@@ -249,75 +250,66 @@ public void testEndSpanByClosingSpanScopeMultiple() {
...
 
                 @Override
                 public void onFailure(Exception e) {
 
                 }
-            }));
-            currentSpanRefThread1.set(defaultTracer.getCurrentSpan());
+            }), executorService);
+            assertEquals(span, defaultTracer.getCurrentSpan().getSpan());
+            asyncTask.get();
```
Comment (reta) [inline libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java:311]:
```suggestion
            asyncTask.join();
```

File: libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java [hunk 5]
```diff
@@ -249,75 +250,66 @@ public void testEndSpanByClosingSpanScopeMultiple() {
...
-        assertEquals(spanRef.get(), currentSpanRefAfterEndThread2.get());
-        assertEquals(null, currentSpanRefThread1.get());
+            span.endSpan();
+            assertEquals(null, defaultTracer.getCurrentSpan());
+        }, executorService);
+        asyncTask.get();
     }
 
-    public void testSpanCloseOnThread2() {
+    public void testSpanCloseOnThread2() throws ExecutionException, InterruptedException {
```
Comment (reta) [inline libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java:285]:
```suggestion
    public void testSpanCloseOnThread2()  {
```

File: libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java [hunk 6]
```diff
@@ -334,60 +326,48 @@ private void async(ActionListener<Boolean> actionListener) {
      * 6. verify the current_span is still the same on async thread as the 2
      * 7. verify the main thread has current span as null.
      */
-    public void testSpanAcrossThreadsMultipleSpans() {
+    public void testSpanAcrossThreadsMultipleSpans() throws ExecutionException, InterruptedException {
```
Comment (reta) [inline libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java:329]:
```suggestion
    public void testSpanAcrossThreadsMultipleSpans()  {
```

**Review by reta — APPROVED** [review]
