### PR TITLE
[Flaky Tests] Fixing flaky tests related to derived source tests

### LINKED ISSUE #18485: [BUG] Flaky testNewChangesSnapshotWithDerivedSource
### Describe the bug

following tests are flaky - 

[org.opensearch.index.engine.InternalEngineTests.testNewChangesSnapshotWithDerivedSource](https://build.ci.opensearch.org/job/gradle-check/59066/testReport/junit/org.opensearch.index.engine/InternalEngineTests/testNewChangesSnapshotWithDerivedSource/)
[org.opensearch.index.engine.InternalEngineTests.testNewChangesSnapshotWithDeleteAndUpdate](https://build.ci.opensearch.org/job/gradle-check/59066/testReport/junit/org.opensearch.index.engine/InternalEngineTests/testNewChangesSnapshotWithDeleteAndUpdate/)

### Related component

Build

### To Reproduce

https://build.ci.opensearch.org/job/gradle-check/59066/testReport/junit/org.opensearch.index.engine/InternalEngineTests/testNewChangesSnapshotWithDerivedSource/
Following commit introduced the test - https://github.com/opensearch-project/OpenSearch/commit/190ea02372f9d21ab7ab051ca62aec9434bd2633 

### Expected behavior

Fix the flakiness

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by tanik98**
### Related Issues
Resolves #18485 #18490
1. org.opensearch.common.lucene.index.DerivedSourceLeafReaderTests:

**Issue**:
```
java.lang.IndexOutOfBoundsException: Index 8 out of bounds for length 8
        at __randomizedtesting.SeedInfo.seed([7EFEA17C239307B5:480F885B0D6542F4]:0)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at org.apache.lucene.index.CodecReader$1.document(CodecReader.java:100)
        at org.opensearch.common.lucene.index.DerivedSourceStoredFieldsReader$DerivedSourceStoredFields.document(DerivedSourceStoredFieldsReader.java:108)
        at org.opensearch.common.lucene.index.DerivedSourceLeafReaderTests.testWithRandomDocuments(DerivedSourceLeafReaderTests.java:184)
```

**Fix**:
- Doing force merge with a single segement

2. org.opensearch.index.engine.InternalEngineTests.testNewChangesSnapshotWithDerivedSource
org.opensearch.index.engine.InternalEngineTests.testNewChangesSnapshotWithDeleteAndUpdate
```
java.io.IOException: could not remove the following files (in the order of attempts):
   /var/jenkins/workspace/gradle-check/search/server/build/testrun/test/temp/org.opensearch.index.engine.InternalEngineTests_E3B2B6D726C65840-001/translog-primary-019/translog-2.tlog: java.io.IOException: access denied: /var/jenkins/workspace/gradle-check/search/server/build/testrun/test/temp/org.opensearch.index.engine.InternalEngineTests_E3B2B6D726C65840-001/translog-primary-019/translog-2.tlog
   /var/jenkins/workspace/gradle-check/search/server/build/testrun/test/temp/org.opensearch.index.engine.InternalEngineTests_E3B2B6D726C65840-001/translog-primary-019/translog.ckp: java.io.IOException: access denied: /var/jenkins/workspace/gradle-check/search/server/build/testrun/test/temp/org.opensearch.index.engine.InternalEngineTests_E3B2B6D726C65840-001/translog-primary-019/translog.ckp
   /var/jenkins/workspace/gradle-check/search/server/build/testrun/test/temp/org.opensearch.index.engine.InternalEngineTests_E3B2B6D726C65840-001/translog-primary-019: java.nio.file.DirectoryNotEmptyException: /var/jenkins/workspace/gradle-check/search/server/build/testrun/test/temp/org.opensearch.index.engine.InternalEngineTests_E3B2B6D726C65840-001/translog-primary-019

	at __randomizedtesting.SeedInfo.seed([E3B2B6D726C65840:F3AC8BE61A359754]:0)
	at org.opensearch.common.util.io.IOUtils.rm(IOUtils.java:222)
	at org.opensearch.index.translog.Translog.createEmptyTranslog(Translog.java:2070)
	at org.opensearch.index.translog.Translog.createEmptyTranslog(Translog.java:2038)
	at org.opensearch.index.translog.Translog.createEmptyTranslog(Translog.java:2010)
	at org.opensearch.index.translog.Translog.createEmptyTranslog(Translog.java:2000)
	at org.opensearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:686)
	at org.opensearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:673)
	at org.opensearch.index.engine.InternalEngineTests.testNewChangesSnapshotWithDerivedSource(InternalEngineTests.java:8243)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

**Fix**:
- Closing the engine

3. org.opensearch.recovery.FullRollingRestartIT.testDerivedSourceWithConcurrentUpdatesRollingRestart 
```
Бэс 10, 2025 9:11:07 ЭК com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#4762,opensearch[node_t0][generic][T#1],5,TGRP-FullRollingRestartIT]
java.lang.AssertionError: seqNo [100] was processed twice in generation [5], with different data. prvOp [Index{id='76', seqNo=100, primaryTerm=2, version=3, autoGeneratedIdTimestamp=-1}], newOp [Index{id='76', seqNo=100, primaryTerm=2, version=3, autoGeneratedIdTimestamp=-1}]
	at __randomizedtesting.SeedInfo.seed([33B7FED8D60FC88D]:0)
	at org.opensearch.index.translog.TranslogWriter.assertNoSeqNumberConflict(TranslogWriter.java:341)
	at org.opensearch.index.translog.TranslogWriter.add(TranslogWriter.java:289)
	at org.opensearch.index.translog.Translog.add(Translog.java:579)
```

**Fix**:
- Same doc was getting updated concurrently which was leading into sequence no conflict and eventually timing out.
- Updating doc sequencially instead of random docs

4. RecoveryWhileUnderLoadIT
- These are also failing due to concurrent updates
**Fix**
- Using auto generated doc ids, instead of fix id

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by msfroh** [comment]
The fact that this PR has run a couple of Gradle checks that actually passed, it definitely feels like an improvement.

File: server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java [hunk 1]
```diff
@@ -601,74 +601,86 @@ public void testDerivedSourceWithConcurrentUpdatesRollingRestart() throws Except
...
+
         } finally {
+            // Clean shutdown
             stop.set(true);
-            updateThread.join();
+            updateThread.join(TimeValue.timeValueSeconds(30).millis());
+            if (updateThread.isAlive()) {
+                updateThread.interrupt();
+                updateThread.join(TimeValue.timeValueSeconds(5).millis());
+            }
```
Comment (msfroh) [inline server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java:677]: These durations on `Thread#join` feel like they could be far too short if the build server is busy. We could get zombie thread test failures. Maybe I'm being paranoid, though.

I would feel more comfortable at least making the second one wait for up to ~5 seconds (1000x increase should be safe, I think). If it does return in less than 5 millis, that's fine.

Also, since Java 19, you can use `Thread#join(Duration)` and write it like `Thread.join(Duration.ofSeconds(5))`.

**Review by msfroh — APPROVED** [review]
I only have a mild concern over the duration passed to `Thread#join`. 

As I mentioned in my other comment, it looks like this PR improves the current flaky test situation. I think we should increase the timeout on `Thread#join`, but I'd be happy to let that wait for another PR.

**Review by andrross — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java (hunk 1 above)
Comment (msfroh) [reply server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java:677]: Oh... of course, @andrross just pointed out to me that `TimeValue.timeValueSeconds(30).millis()` means "A time value of 30 seconds, converted to milliseconds". So, the second value is already 5 seconds. 🤦 

I'm an idiot. Please proceed. 😁
