### PR TITLE
Toggle replication strategy based on segrep index setting

### LINKED ISSUE #2197: [Segment Replication] -  Toggle replication strategy based on segrep index setting.
**Describe the bug**
Commented code breaks document replication.
- Uncomment code and replace with calls to IndexShard's isSegmentReplicationEnabled.
https://github.com/opensearch-project/OpenSearch/pull/2075/files#r804147317
- Remove condition from IndexService and move to scheduledRefresh(); - https://github.com/opensearch-project/OpenSearch/pull/2075/files#r804177770
- StartRecovery inside IndexShard should use existing PeerRecoveryTargetService when setting is off.

### PR DESCRIPTION
**Pull request by Poojita-Raj**
### Description
Docrep and segrep should be able to work in parallel with this change. Previously, commented code was breaking docrep
- test docrep by running IndexRecoveryIT 

Resolves #2197 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/engine/InternalEngine.java [hunk 1]
```diff
@@ -277,17 +277,25 @@ public InternalEngine(EngineConfig engineConfig) {
                 );
                 this.localCheckpointTracker = createLocalCheckpointTracker(localCheckpointTrackerSupplier);
                 // TODO: Segrep - should have a separate read only engine rather than all this conditional logic.
-                if (engineConfig.isPrimary()) {
+                if (engineConfig.getIndexSettings().isSegrepEnabled()) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/engine/InternalEngine.java:280]: Wiring up primary shards is the same in both cases. We can remove some duplication here with:

```
if (engineConfig.getIndexSettings().isSegrepEnabled && engineConfig.isPrimary() == false) {
 ... setup replica
} else {
 ..setup primary
}
```

File: server/src/main/java/org/opensearch/index/engine/OpenSearchReaderManager.java [hunk 2]
```diff
@@ -38,13 +38,8 @@
 
 import org.apache.logging.log4j.LogManager;
 import org.apache.logging.log4j.Logger;
-import org.apache.lucene.index.DirectoryReader;
-import org.apache.lucene.index.LeafReader;
-import org.apache.lucene.index.LeafReaderContext;
-import org.apache.lucene.index.SegmentInfos;
-import org.apache.lucene.index.StandardDirectoryReader;
+import org.apache.lucene.index.*;
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/engine/OpenSearchReaderManager.java:41]: we should leave the specific imports as is here.  My Intellij sometimes does this by default and had to change in Preferences > code style > java and mark use single class import and change `Class count to use import with '*' to a high number.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 3]
```diff
@@ -3910,8 +3912,10 @@ ReplicationTracker getReplicationTracker() {
     public boolean scheduledRefresh() {
         // skip if not primary shard.
         // TODO: Segrep - should split into primary/replica classes.
-        if (shardRouting.primary() == false) {
-            return false;
+        if (indexSettings.isSegrepEnabled()) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:3915]: nit - can be on one line.

**Review by mch2 — COMMENTED** [review]
Looks like a great start!

We will also need to conditionally wire up the CheckpointRefreshListener [here](https://github.com/opensearch-project/OpenSearch/blob/7c75c35ac33561126d39c11a73cb4d3a6120e760/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L3318) so that checkpoints are not published on primary refresh.  We should probably also add a condition in IndexShard's onNewCheckpoint method to be safe.

File: server/src/main/java/org/opensearch/index/engine/OpenSearchReaderManager.java [hunk 4]
```diff
@@ -32,10 +32,6 @@
 
 package org.opensearch.index.engine;
 
-import java.io.IOException;
```
[the remark this answers is not in the document]
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/engine/OpenSearchReaderManager.java:35]: I left it in since this seems to be the standard order followed by all other files

File: server/src/main/java/org/opensearch/index/engine/InternalEngine.java [hunk 5]
```diff
@@ -582,7 +582,8 @@ private void recoverFromTranslogInternal(TranslogRecoveryRunner translogRecovery
                 translog.currentFileGeneration()
             )
         );
-        if (engineConfig.isPrimary()) {
+        boolean segrep = engineConfig.getIndexSettings().isSegrepEnabled();
+        if ((segrep == false) || (segrep && engineConfig.isPrimary())) {
```
[the remark this answers is not in the document]
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/engine/InternalEngine.java]: Done

File: server/src/main/java/org/opensearch/index/IndexSettings.java [hunk 6]
```diff
@@ -883,7 +883,7 @@ public int getNumberOfReplicas() {
     }
 
     public boolean isSegrepEnabled() {
-        return isSegrepEnabled;
+        return Boolean.TRUE.equals(isSegrepEnabled);
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/IndexSettings.java:886]: nit - this isn't required bc we always initialize this variable in the constructor.
`isSegrepEnabled = settings.getAsBoolean(IndexMetadata.SETTING_SEGMENT_REPLICATION, false);`

File: server/src/main/java/org/opensearch/index/engine/InternalEngine.java [hunk 7]
```diff
@@ -346,7 +350,7 @@ public InternalEngine(EngineConfig engineConfig) {
 
     @Override
     public void updateCurrentInfos(byte[] infosBytes, long gen, long seqNo) throws IOException {
-        assert engineConfig.isPrimary() == false : "Only replicas should update Infos";
+        assert engineConfig.isReadOnly() == true : "Only replicas should update Infos";
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/engine/InternalEngine.java:353]: nit - this failure message is a bit confusing with the rename.  Perhaps 'Only read only replicas should update Infos'

**Review by mch2 — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/IndexSettings.java (hunk 6 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/IndexSettings.java:886]: True but leaving it in to convert to boolean which is faster since we don't need a thread safe implementation.
