### PR TITLE
Flaky MetricAggregatorTests

### LINKED ISSUE #18110: [AUTOCUT] Gradle Check Flaky Test Report for MetricAggregatorTests
## Flaky Test Report for `MetricAggregatorTests`

Noticed the `MetricAggregatorTests` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| 16e9fed6b5595bced8f4efde26e90a994ae03495 | [18221](https://github.com/opensearch-project/OpenSearch/pull/18221) | [57830](https://build.ci.opensearch.org/job/gradle-check/57830/testReport/) | `org.opensearch.search.aggregations.startree.MetricAggregatorTests.testStarTreeDocValues` |
| 18c64dbd7c1d379623a55b017c1d023e08630d25 | [18112](https://github.com/opensearch-project/OpenSearch/pull/18112) | [57314](https://build.ci.opensearch.org/job/gradle-check/57314/testReport/) | `org.opensearch.search.aggregations.startree.MetricAggregatorTests.testStarTreeDocValues` |
| 1b48dbdb6b26dbf8f5b6ca3584be644e40ca66d8 | [18090](https://github.com/opensearch-project/OpenSearch/pull/18090) | [57280](https://build.ci.opensearch.org/job/gradle-check/57280/testReport/) | `org.opensearch.search.aggregations.startree.MetricAggregatorTests.testStarTreeDocValues` |
| 92b90fa32a4c3fbc2cc8ec6aadb4fe100e52ec4f | [18220](https://github.com/opensearch-project/OpenSearch/pull/18220) | [58259](https://build.ci.opensearch.org/job/gradle-check/58259/testReport/) | `org.opensearch.search.aggregations.startree.MetricAggregatorTests.testStarTreeDocValues` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `MetricAggregatorTests` class are:

- [17275](https://github.com/opensearch-project/OpenSearch/pull/17275)
- [16481](https://github.com/opensearch-project/OpenSearch/pull/16481)
- [18106](https://github.com/opensearch-project/OpenSearch/pull/18106)
- [17100](https://github.com/opensearch-project/OpenSearch/pull/17100)
- [18070](https://github.com/opensearch-project/OpenSearch/pull/18070)
- [15289](https://github.com/opensearch-project/OpenSearch/pull/15289)
- [17759](https://github.com/opensearch-project/OpenSearch/pull/17759)
- [17855](https://github.com/opensearch-project/OpenSearch/pull/17855)
- [17941](https://github.com/opensearch-project/OpenSearch/pull/17941)
- [17989](https://github.com/opensearch-project/OpenSearch/pull/17989)
- [18054](https://github.com/opensearch-project/OpenSearch/pull/18054)
- [18088](https://github.com/opensearch-project/OpenSearch/pull/18088)
- [18116](https://github.com/opensearch-project/OpenSearch/pull/18116)
- [18119](https://github.com/opensearch-project/OpenSearch/pull/18119)
- [18124](https://github.com/opensearch-project/OpenSearch/pull/18124)
- [18162](https://github.com/opensearch-project/OpenSearch/pull/18162)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by ajleong623**
### Description
This change will make sure that the MetricAggregatorTests does not fail on the range query. What happened was that in the test, the range query was applied on a terms, but the difference between the expected aggregation and the actual aggregation was not zero. On a field called "keyword_field", the boolean query had 2 should queries (range from 18 to 0) and (exact match of 37). 

In the expected aggregation, only the documents which matched on 37 were added together, but in the actual aggregation, more documents which somehow satisfied the range from 18 to 0 were added together. I think what happened was that the "keyword_field" was a string value, and in the range query, the values are interpreted as mapped ordinals in the star tree filters (https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/startree/filter/RangeMatchDimFilter.java), but it seems like in the expected query which does not use star tree filters, the strings are compared as its byte ref value (https://lucene.apache.org/core/6_6_0/core/org/apache/lucene/search/TermRangeQuery.html). At least for now, I think that we should avoid using keyword strings for a range query.  

### Related Issues
Resolves #18110

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by sandeshkr419 — COMMENTED** [review]
Hi @ajleong623 

Appreciate your time to debug this case.
I have minor comments.

Also, along with this change, can you also ensure that instead of assigning raw queryBuilders using RangeQueryBuilder/TermQueryBuilder constructors at places, we use `getTermQueryBuilder()`, `getRangeQueryBuilder()` methods directly. I know this is not part of your changes, but a little code cleanup can certainly help.

Also, please run the test some n(100-500) times (can be configured with intellij) to assert we are solving the flakiness correctly.

Thanks!

**Comment by ajleong623** [comment]
@sandeshkr419 Thank you so much for the suggestions and review. I believe I made the requested changes and also ran the test 100 times. Let me know if there are any other suggestions.

File: server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java [hunk 1]
```diff
@@ -555,26 +554,36 @@ public QueryBuilder getTermsQueryBuilder() {
         }
 
         public QueryBuilder getRangeQueryBuilder() {
-            return new RangeQueryBuilder(fieldName).from(valueSupplier.get())
+            RangeQueryBuilder qb = new RangeQueryBuilder(fieldName).from(valueSupplier.get())
```
Comment (sandeshkr419) [inline server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java:557]: nit: I don't think you need this change in method.

File: server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java [hunk 2]
```diff
@@ -555,26 +554,36 @@ public QueryBuilder getTermsQueryBuilder() {
...
                 .includeLower(randomBoolean())
                 .includeUpper(randomBoolean());
+            return qb;
         }
 
         public QueryBuilder getBoolQueryBuilder() {
             // MUST only
-            BoolQueryBuilder mustOnly = new BoolQueryBuilder().must(getTermQueryBuilder()).must(getRangeQueryBuilder());
+            BoolQueryBuilder mustOnly = new BoolQueryBuilder().must(getTermQueryBuilder());
+            // Keyword terms are not always supported for range queries.
```
Comment (sandeshkr419) [inline server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java:567]: nit: // Keyword terms are not ~always~ supported for range queries.

(remove always)

File: server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java [hunk 3]
```diff
@@ -555,26 +554,36 @@ public QueryBuilder getTermsQueryBuilder() {
...
-                        .should(new TermQueryBuilder(fieldName, valueSupplier.get()))
-                );
+                .must(new BoolQueryBuilder().should(getTermQueryBuilder()).should(getTermQueryBuilder()));
 
             // SHOULD only on same dimension
-            BoolQueryBuilder shouldOnly = new BoolQueryBuilder().should(new TermQueryBuilder(fieldName, valueSupplier.get()))
-                .should(new RangeQueryBuilder(fieldName).from(valueSupplier.get()).to(valueSupplier.get()));
+            BoolQueryBuilder shouldOnly = new BoolQueryBuilder().should(getTermQueryBuilder());
+
+            // Keyword terms are not always supported for range queries.
```
Comment (sandeshkr419) [inline server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java:581]: nit: // Keyword terms are not ~always~ supported for range queries.

(remove always)

**Review by sandeshkr419 — APPROVED** [review]
Just added a few minor nit-picks. The rest looks good.

**Comment by ajleong623** [comment]
The new changes are ready.

**Review by sandeshkr419 — APPROVED** [review]

**Review by andrross — APPROVED** [review]
