### PR TITLE
Rebuild Rest client after setting interceptor

### LINKED ISSUE #890: [BUG] Custom interceptor not attached to the Remote reindex Rest client
**Describe the bug**
Remote Reindex plugin was extended in PR #547 to be able to add a custom interceptor. But the when adding a custom interceptor, it is not getting attached to the Rest client as the Rest client was initialized before the interceptor was set. This should be fixed by correcting the initialization of Rest client to use the interceptor.

**Additional context**
Follow up on the PR : https://github.com/opensearch-project/OpenSearch/pull/547

### PR DESCRIPTION
**Pull request by soosinha**
### Description
The interceptor that was added in this [PR](https://github.com/opensearch-project/OpenSearch/pull/547), is not being applied as it is not set in the Rest client created to connect to remote cluster.
This change rebuilds the Rest client after the interceptor has been initialized. Once pushed to main branch, this should be ported to 1.0 branch.
 

### Issues Resolved
#890 

### Check List
- [ x] New functionality includes testing.
  - [ x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by shwetathareja — APPROVED** [review]

File: modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java [hunk 1]
```diff
@@ -240,6 +240,9 @@ static RestClient buildRestClient(RemoteInfo remoteInfo, ReindexSslConfig sslCon
                 request.getDestination().versionType() != VersionType.INTERNAL,
                 false, logger, client, threadPool, request, listener, scriptService, sslConfig);
             this.interceptor = interceptor;
+            if (mainRequest.getRemoteInfo() != null) {
```
Comment (shwetathareja) [inline modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java:243]: I am wondering, you can initialize at one place only instead of having an if check and reload

Comment (soosinha) [reply modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java:243]: I can pass the `interceptor` argument to the super constructor `AsyncIndexBySearchAction`. Then I do not need to invoke `buildScrollableResultSource` again. But then would have to change reference of `AsyncIndexBySearchAction` to pass empty `interceptor` from other sub classes or create a wrapper constructor which passes empty `interceptor` to the constructor with the extra argument. Does that sound fine ?

**Comment by CEHENKLE** [comment]
start gradle check

**Comment by nknize** [comment]
Do we have an issue opened for this? Is this a bug?

> Once pushed to main branch, this should be ported to 1.0 branch.

Is this a blocker for GA release?

**Comment by nknize** [comment]
For now I'll remove this as a blocker. I think we can get this in a quick patch release post GA?

**Comment by soosinha** [comment]
> Do we have an issue opened for this? Is this a bug?

Created issue #890 . It is a bug for the custom interceptor interface we want to provide in remote reindex. If someone wants to use this feature to implement a custom interceptor for remote reindex, it would not work.

> Is this a blocker for GA release? 

It is not a blocker. It can be added as a patch after GA release.

File: modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java (hunk 1 above)
Comment (shwetathareja) [reply modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java:243]: passing it in constructor seems like the right option. yeah, you can create the wrapper constructor to pass if other sub classes don't need the interceptor.

File: modules/reindex/src/main/java/org/opensearch/index/reindex/TransportUpdateByQueryAction.java [hunk 2]
```diff
@@ -105,7 +106,7 @@ protected void doExecute(Task task, UpdateByQueryRequest request, ActionListener
                 clusterState.nodes().getMinNodeVersion().onOrAfter(LegacyESVersion.V_6_7_0) == false,
                 // all nodes support sequence number powered optimistic concurrency control and we can use it
                 clusterState.nodes().getMinNodeVersion().onOrAfter(LegacyESVersion.V_6_7_0),
-                logger, client, threadPool, request, listener, scriptService, null);
+                logger, client, threadPool, request, listener, scriptService, null, Optional.empty());
```
Comment (shwetathareja) [inline modules/reindex/src/main/java/org/opensearch/index/reindex/TransportUpdateByQueryAction.java:109]: I thought you will create wrapper constructor in AbstractAsyncBulkByScrollAction.java, so that other sub classes are untouched if they don't need the interceptor.

Comment (soosinha) [reply modules/reindex/src/main/java/org/opensearch/index/reindex/TransportUpdateByQueryAction.java:109]: Yeah. Sorry for the misunderstanding. Will update the PR.

Comment (soosinha) [reply modules/reindex/src/main/java/org/opensearch/index/reindex/TransportUpdateByQueryAction.java]: Created a wrapper constructor

**Comment by CEHENKLE** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle precommit

**Comment by shwetathareja** [comment]
you will need backport for 1.x & 1.0

**Comment by CEHENKLE** [comment]
We are already locked for 1.0.0.  What is the impact if this is not merged for 1.0.0?

**Comment by soosinha** [comment]
@CEHENKLE This fix is required for remote reindex extension feature. There is no impact on the core remote reindex feature. But if someone creates a custom interceptor to be used in remote reindex, then the custom interceptor would not work.

**Comment by nknize** [comment]
Is this a heavily used feature that necessitates it for GA or can we merge this in a bug fix release?

**Comment by CEHENKLE** [comment]
Just an update -- we're testing now, so if we find any issue that requires us to rebuild the bundle, @saratvemulapalli will merge this one in.  If not, then we're thinking this will go post GA.

**Comment by soosinha** [comment]
This bug fix is for the Remote Reindex extension which is a new feature introduced in the PR #547, so it is not used currently. The basic remote reindex feature is used often but that is not impacted. If the bug fix is not taken in 1.0, can we remove the PR #547 from the release notes?

**Comment by shwetathareja** [comment]
@nknize we should remove PR #547 from release notes (to prevent any confusion ) for 1.0 GA and can pick this bug fix later.
