### PR TITLE
Remove awaits fix for ApproximatePointRangeQuery tests

### LINKED ISSUE #15600: [BUG] Flaky 'org.opensearch.search.approximate.ApproximatePointRangeQueryTests.testApproximateRangeShortCircuit' test
### Describe the bug

https://build.ci.opensearch.org/job/gradle-check/46344/
https://build.ci.opensearch.org/job/gradle-check/46340/
https://build.ci.opensearch.org/job/gradle-check/46333/

Many gradle builds are failing

### Related component

Search

### Expected behavior

Test must pass

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by harshavamsi**
### Description
Remove awaits fix for flaky tests that have been fixed in #15590 

### Related Issues
Resolves #15600 

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by harshavamsi** [comment]
@dblock @msfroh when you have time, not urgent

File: server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java [hunk 1]
```diff
@@ -256,8 +257,7 @@ public void testApproximateRangeShortCircuitAscSort() throws IOException {
                     for (int v = 0; v < dims; v++) {
                         scratch[v] = i;
                     }
-                    doc.add(new LongPoint("point", scratch));
-                    iw.addDocument(doc);
+                    iw.addDocument(asList(new LongPoint("point", scratch[0]), new NumericDocValuesField("point", scratch[0])));
```
Comment (jainankitk) [inline server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java:260]: Why is this change needed? Is `testApproximateRangeShortCircuitAscSort` also one of the failing test?

Comment (harshavamsi) [reply server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java:260]: I ran each test about 1000 times, `testApproximateRangeShortCircuitAscSort` fails about 1% of the time interestingly. I then realized that we had to force the sorting behavior after collecting docIDs since the two different queries are collecting docIds in different order

Comment (jainankitk) [reply server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java:260]: Can we also try running these tests individually until failure and ensure they are not failing before removing awaits annotation?

Comment (harshavamsi) [reply server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java:260]: I ran all tests until failure and it kept going until 5000+ iterations, I think I can safely say that there is no flakiness here

**Review by msfroh — APPROVED** [review]

File: server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java (hunk 1 above)
Comment (jainankitk) [reply server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java:260]: Thanks @harshavamsi for the due diligence! I was slightly concerned with 1% within 1000 iterations.
