### PR TITLE
Catch task description error

### LINKED ISSUE #12324: [BUG] Some GeoShapeQueryBuilder instances cannot be toString()'d
### Describe the bug

Executing this line of code will always fail:

```
new GeoShapeQueryBuilder("test", new LinearRing(new double[] { 0, 0, 0 }, new double[] { 0, 0, 0 })).toString();
```

The specific case where this is known to be problematic is if TRACE logging is enabled and the TaskManager attempts to log a query containing a linear ring instance. See #11688 for a case where somehow trace logging was enabled in the CI system which resulted in failing tests. For example:

```
java.lang.UnsupportedOperationException: line ring cannot be serialized using GeoJson
	at __randomizedtesting.SeedInfo.seed([D24747E5E9B452AE:CFF1D9D2D64D1980]:0)
	at org.opensearch.common.geo.GeoJson$3.visit(GeoJson.java:561)
	at org.opensearch.common.geo.GeoJson$3.visit(GeoJson.java:543)
	at org.opensearch.geometry.LinearRing.visit(LinearRing.java:84)
	at org.opensearch.common.geo.GeoJson.getGeoJsonName(GeoJson.java:543)
	at org.opensearch.common.geo.GeoJson.toXContent(GeoJson.java:103)
	at org.opensearch.index.query.AbstractGeometryQueryBuilder.doXContent(AbstractGeometryQueryBuilder.java:452)
	at org.opensearch.index.query.AbstractQueryBuilder.toXContent(AbstractQueryBuilder.java:101)
	at org.opensearch.core.xcontent.XContentBuilder.value(XContentBuilder.java:887)
	at org.opensearch.core.xcontent.XContentBuilder.value(XContentBuilder.java:880)
	at org.opensearch.core.xcontent.XContentBuilder.field(XContentBuilder.java:872)
	at org.opensearch.search.builder.SearchSourceBuilder.innerToXContent(SearchSourceBuilder.java:1350)
	at org.opensearch.search.builder.SearchSourceBuilder.toXContent(SearchSourceBuilder.java:1490)
	at org.opensearch.core.xcontent.XContentHelper.toXContent(XContentHelper.java:46)
	at org.opensearch.search.builder.SearchSourceBuilder.toString(SearchSourceBuilder.java:1810)
	at org.opensearch.action.search.SearchRequest.buildDescription(SearchRequest.java:715)
	at org.opensearch.action.search.SearchTask.getDescription(SearchTask.java:83)
	at org.opensearch.tasks.TaskManager.register(TaskManager.java:210)
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:99)
```

### Related component

Other

### To Reproduce

Add the following unit test to `GeoShapeQueryBuilderGeoShapeTests`:

```
public void testToString() {
    new GeoShapeQueryBuilder("test", new LinearRing(new double[] { 0, 0, 0 }, new double[] { 0, 0, 0 })).toString();
}
```

### Expected behavior

`toString()` should never fail for a valid object.

### Additional Details

The base `AbstractQueryBuilder` implements toString() as:

```
@Override
public final String toString() {
    return Strings.toString(MediaTypeRegistry.JSON, this, true, true);
}
```

`Strings.toString()` convents the given instance to XContent then invokes toString on the XContentBuilder. The class `AbstractGeometryQueryBuilder` ultimately implements toXContent as GeoJson, and the `LinearRing` type [cannot be converted to GeoJson](https://github.com/opensearch-project/OpenSearch/blob/aca2e9de7daaadee77c33e21ff5215c3f1e8600f/server/src/main/java/org/opensearch/common/geo/GeoJson.java#L129).

### PR DESCRIPTION
**Pull request by dblock**
### Description

Alternative to (just the first two commits) to https://github.com/opensearch-project/OpenSearch/pull/12831.

A user that enables trace-level logging with OpenSearch will run into a serialization error on geo tasks that they otherwise would not run into. It comes from [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/geo/GeoJson.java#L129). This also happens in a test, and https://github.com/opensearch-project/OpenSearch/pull/12783 attempts to ignore the failed serialization error. This PR always returns a task description.

Reproduce with

```
./gradlew ':server:test' --tests "org.opensearch.search.geo.GeoPointShapeQueryTests.testQueryLinearRing" -Dtests.opensearch.logger.level=TRACE
``` 
### Related Issues

Closes https://github.com/opensearch-project/OpenSearch/issues/11688
Closes #12324

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by andrross** [comment]
I like this better than #12783 as this actually fixes the user-facing bug described by #11688. However, it does indeed feel a bit gross but feels safer than trying to actually serialize a linear ring as GeoJSON given I know nothing about linear rings or GeoJSON.

@reta Do you see any bad unintended consequences here?

File: server/src/main/java/org/opensearch/action/search/SearchTask.java [hunk 1]
```diff
@@ -80,7 +80,11 @@ public SearchTask(
 
     @Override
     public final String getDescription() {
-        return descriptionSupplier.get();
+        try {
+            return descriptionSupplier.get();
+        } catch (UnsupportedOperationException e) {
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/action/search/SearchTask.java:85]: UnsupportedOperationException is broad category of error and we shouldn't catch it and swallow. This may help in surfacing more issues like this in future.

do you want to rethrow this as wrapped OpenSearchException instead of swallowing the exception

**Comment by shwetathareja** [comment]
@andrross : there could be other flow which may serialize the object before search execution starts. I don't think we should be catching UnsupportedOperationException everywhere like this.
I do agree that when trace logging is enabled, the behavior shouldn't change.

File: server/src/main/java/org/opensearch/action/search/SearchTask.java (hunk 1 above)
Comment (dblock) [reply server/src/main/java/org/opensearch/action/search/SearchTask.java:85]: This won't fix the original problem where with the trace enabled the user-facing behavior is different.

**Comment by andrross** [comment]
> I don't think we should be catching UnsupportedOperationException everywhere like this.

@shwetathareja I don't love this solution either but can possibly be convinced that it's okay because this catch is relatively narrow in a "getDescription()" method that (I think) is returning text for human entertainment rather than any sort of machine-to-machine communication. We could potentially push the error handling a bit lower down into [SearchSourceBuilder#toString](https://github.com/opensearch-project/OpenSearch/blob/f90baa26894c66bb85f74bb3aaf201d6dd2329a6/server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java#L1839) but that's not fundamentally different than this solution.

File: server/src/main/java/org/opensearch/action/search/SearchTask.java (hunk 1 above)
Comment (shwetathareja) [reply server/src/main/java/org/opensearch/action/search/SearchTask.java:85]: Ideally this should be caught in the validation when it is creating the search request upfront whether a shape is supported or not in ```AbstractGeometryQueryBuilder``` instead of generating the request, create SearchTask for it and then fail during execution. Failing fast is better in case it is not supported at all.

Comment (reta) [reply server/src/main/java/org/opensearch/action/search/SearchTask.java:85]: @dblock I think there is a way to solve in a way to make the behaviour acceptable:

- `SearchSourceBuilder`:

```
    public String toString(Params params) {
        try {
            return XContentHelper.toXContent(this, MediaTypeRegistry.JSON, params, true).utf8ToString();
        } catch (IOException e) {
            throw new OpenSearchException(e);
        } catch (UnsupportedOperationException ex) {
            throw new OpenSearchException(ex);
        }
    }
```

- `SearchRequest`
```
    public final String buildDescription() {
        StringBuilder sb = new StringBuilder();
        sb.append("indices[");
        Strings.arrayToDelimitedString(indices, ",", sb);
        sb.append("], ");
        sb.append("search_type[").append(searchType).append("], ");
        if (scroll != null) {
            sb.append("scroll[").append(scroll.keepAlive()).append("], ");
        }
        if (source != null) {
            try {
                sb.append("source[").append(source.toString(FORMAT_PARAMS)).append("]");
            } catch (final OpenSearchException ex) {
                sb.append("source[").append("n/a").append("]");
            }
        } else {
            sb.append("source[]");
        }
        return sb.toString();
    }

```

**Comment by reta** [comment]
> @reta Do you see any bad unintended consequences here?

No, thanks @andrross , I also feel like this is the direction we should be taking, I've suggested a bit more wider fix here https://github.com/opensearch-project/OpenSearch/pull/12834#discussion_r1534263680

File: server/src/main/java/org/opensearch/action/search/SearchTask.java (hunk 1 above)
Comment (shwetathareja) [reply server/src/main/java/org/opensearch/action/search/SearchTask.java:85]: On a different note, it would be good to repro this error first. As per documentation there is no direct way to pass LinearRing as shape type - https://opensearch.org/docs/latest/field-types/supported-field-types/geo-shape/
It should fail in parsing, early on.

Only Polygon type internally uses this. 
https://github.com/opensearch-project/OpenSearch/blob/e673b6194fab6f672b62dfdaf8f082bc8dec403f/server/src/main/java/org/opensearch/common/geo/builders/PolygonBuilder.java#L72

From the documentation
```
          Per GeoJSON spec (http://geojson.org/geojson-spec.html#linestring)
          A LinearRing is closed LineString with 4 or more positions. The first and last positions
          are equivalent (they represent equivalent points). Though a LinearRing is not explicitly
          represented as a GeoJSON geometry type, it is referred to in the Polygon geometry type definition.
```

Just check, this problem does exist today.

**Comment by dblock** [comment]
@reta implemented your suggested approach + test

File: server/src/main/java/org/opensearch/action/search/SearchTask.java (hunk 1 above)
Comment (reta) [reply server/src/main/java/org/opensearch/action/search/SearchTask.java]: @shwetathareja correct, one the ways to fail earlier is to add checks in `GeoShapeQueryBuilder` / `AbstractGeometryQueryBuilder`, the issue though is that this class deals with `Supplier<Geometry>` (the resolution is delayed later).

File: server/src/main/java/org/opensearch/action/search/SearchRequest.java [hunk 2]
```diff
@@ -712,7 +713,13 @@ public final String buildDescription() {
             sb.append("scroll[").append(scroll.keepAlive()).append("], ");
         }
         if (source != null) {
-            sb.append("source[").append(source.toString(FORMAT_PARAMS)).append("]");
+            sb.append("source[");
+            try {
+                sb.append(source.toString(FORMAT_PARAMS));
+            } catch (final OpenSearchException ex) {
+                sb.append(ex.getMessage());
```
Comment (reta) [inline server/src/main/java/org/opensearch/action/search/SearchRequest.java:720]: I think we should not include the exception message as is, may be we could say:
```
  `sb.append("<exception thrown>");` 
```
Or

```
  `sb.append("n/a");` 
```

Just setting the source to error message gives an impression that this is the exact source, not a placeholder because of error

Comment (dblock) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:720]: The exception is useful IMO.

```
indices[], search_type[QUERY_THEN_FETCH], source[java.lang.UnsupportedOperationException: line ring cannot be serialized using GeoJson]
```

I don't want to die on this hill, what would you prefer?

Comment (reta) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:720]: :D Fair enough, what about:  `sb.append("<error: " + ex.getMessage() +">");` @andrross wdyt?

Comment (dblock) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java]: I like it, updated.

Comment (andrross) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java]: `sb.append("<error: " + ex.getMessage() +">");` looks good to me

**Comment by andrross** [comment]
A bit of a side note, given that a linear ring is a line string with some special constraints (start and end point must be the same), I wonder why `ShapeType.LINEARRING` was introduced? It seems like LinearRing could have just been a child of Line (which it currently is) with a constructor enforcing its special constraint, but otherwise could have delegated all other logic to the parent Line class.

**Comment by reta** [comment]
> A bit of a side note, given that a linear ring is a line string with some special constraints (start and end point must be the same), I wonder why `ShapeType.LINEARRING` was introduced?

Hard to say to be fair, wanna take a look? ;-)

**Review by reta — APPROVED** [review]

**Review by andrross — APPROVED** [review]

**Comment by reta** [comment]
It all yours @dblock !

**Comment by reta** [comment]
@dblock could you please backport to 2.x manually? thank you!

File: server/src/main/java/org/opensearch/action/search/SearchRequest.java [hunk 3]
```diff
@@ -712,7 +713,13 @@ public final String buildDescription() {
             sb.append("scroll[").append(scroll.keepAlive()).append("], ");
         }
         if (source != null) {
-            sb.append("source[").append(source.toString(FORMAT_PARAMS)).append("]");
+            sb.append("source[");
+            try {
+                sb.append(source.toString(FORMAT_PARAMS));
+            } catch (final OpenSearchException ex) {
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: @reta / @dblock / @andrross : This is not right. buildDescription() shouldn't swallow exception. Anything unexpected should fail the request as early as possible. Earlier, IOException was wrapped and thrown and now that also gets swallowed. Why an object which is throwing UnsupportedOperationException not handled properly and reached till here at all? In order to fix an user behavior (which may not be an issue, as actual request may not reach till this point as well, unless someone has tested an actual user rest request and confirmed the behavior?). Tomorrow, somebody would wrap NPE also as OpenSearchException and start swallowing here as apparently buildDescription should succeed for some reason.

Comment (reta) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: >  Why an object which is throwing UnsupportedOperationException not handled properly and reached till here at all?

@shwetathareja There are few levels this exception will be raised and **it will be handled properly**, it is not swallowed.  The issue that the description of the request (serialization of the POJO) - the string representation - triggers the problem first, even before the request is processed (and validated). So the suggested fix here is to provide partial description of the request that will eventually fail for exactly the same cause. This is what tests are verifying.

**Comment by dblock** [comment]
> @dblock could you please backport to 2.x manually? thank you!

https://github.com/opensearch-project/OpenSearch/pull/12858

File: server/src/main/java/org/opensearch/action/search/SearchRequest.java (hunk 3 above)
Comment (shwetathareja) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: It is not an end-to-end test, The test simply testing a particular flow for ```GeoShapeQueryBuilder``` and expecting an exception.

Comment (shwetathareja) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: > Specifically in the request path the request is read, then traced (including its description, which throws exception), then validated & al.

@dblock : Request has to be parsed first/ deserialized. How can we trigger toContent() on object without creating the object?

Comment (dblock) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: Ok that's fair, I think you know a lot more than me about the sequence of what's happening here and I don't have an actual example of when a linearring comes in as input (@andrross was asking for the same). 

So stepping back, I don't understand then why this code is present at all. If we can never submit a request with a linearring, should we delete all related code?

Comment (dblock) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: Btw, I do think our fix of handling errors in `description` was right. We clearly have a case where `getDescription()` fails, and we always want a task to be able to describe itself.

Comment (shwetathareja) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: @dblock : I feel, the code we are fixing is actually dead code. Instead of changing exception handling here. +1 on cleaning up the dead code causing more confusion.

Comment (shwetathareja) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: > Will see if I can queue it, but I don't know the system well enough to be sure this is dead code though.

Same here, agree, not an expert on this.

Comment (reta) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: > The builder could validate the supported shapes in ` AbstractGeometryQueryBuilder` when creating the POJO itself.

I already replied to that here https://github.com/opensearch-project/OpenSearch/pull/12834#discussion_r1534520414

Comment (shwetathareja) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: @dblock : Are you reverting this change?

Comment (dblock) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: No, I am still convinced that the implementation merged here is better than what we had. Today tasks can fail to `getDescription()` and the better place to guard it is in the code we added it in. If we get rid of `LinearRing`, then we don't need to protect from failed serialization.

Comment (shwetathareja) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: Once we remove the Linearring, the only exception, you are taking care in getDescription() is IOException which we shouldn't catch and swallow even for getDescription() to work. I don't think there is need for this exception handling considering it has always been like this, not impacting any other tests/ flow yet.

Comment (dblock) [reply server/src/main/java/org/opensearch/action/search/SearchRequest.java:719]: I agree re:once we remove the Linearring. I opened https://github.com/opensearch-project/OpenSearch/issues/12910, I'll try to get to it.
