### PR TITLE
Fix multi-value sort for unsigned long

### LINKED ISSUE #16698: Sort on multi-value unsigned long field is incorrect
### Describe the bug

Recently, I worked on supporting the reuse of doc values to reconstruct the source field and avoid storing it. Then, I found that the number fields are ordered when fetching from sorted numeric doc values except the unsigned long field. This is because Lucene treats it as a signed number. IMO, this is not a problem in many situations, but if an unsigned long field has multiple values per doc, the sort result may be wrong, because in the current implementation, [the sort mode](https://opensearch.org/docs/latest/search-plugins/searching-data/sort/#sort-mode) uses signed long to pick the value.

### Related component

Search

### To Reproduce

1. create index
```
{
  "mappings": {
    "properties": {
      "field1": {
        "type": "unsigned_long"
      }
    }
  }
}
```
2. index some docs
```
{"index": {"_id": 1}}
{"field1": [13835058055282163712, 3]}
{"index": {"_id": 2}}
{"field1": [13835058055282163713, 2]}
{"index": {"_id": 3}}
{"field1": [13835058055282163714, 1]}
```
3. search with sort
```
{
  "query": {
    "match_all": {}
  },
  "sort": [
    {
      "field1": {
        "order": "desc",
        "mode": "max"
      }
    }
  ]
}
```

### Expected behavior

The sort result should be correct.

**Possible solution**: create a dedicated `UnsignedLongMultiValueMode` for unsigned long, then convert the normal mode to unsigned long mode and use the converted mode to pick the sort value in `UnsignedLongValuesComparatorSource`.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by bugmakerrrrrr**
### Description
Fix #16698

### Related Issues
Resolves #16698

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by bugmakerrrrrr** [comment]
@reta ping :)

**Comment by reta** [comment]
> @reta ping :)

My apologies @bugmakerrrrrr , I haven't had time to look at the issue yet, I believe your approach is viable but there could be a simpler option to fall back to doubles for unsigned long, I will check it shortly and get back to you. Thanks !

**Comment by bugmakerrrrrr** [comment]
@reta Thank you for your reply. I actually considered the double method, but I think there are two issues with it. One is that the maximum integer value that double can accurately represent is 2^53, if we use double to handle unsigned long, there may be loss of precision and we get wrong result. The other is that doc values in a document is possible unsorted, so we still need to special handling of min/max/median. Please correct me if I misunderstood something.

**Comment by bugmakerrrrrr** [comment]
> they are "sorted" as longs but in case of unsigned long, they are "unsorted"

Yes, and perhaps later we can consider changing the storage format(flip the signed bit) to simplify the process.

>  Do you mind if I push some rest api specs into your pull request? 

Not at all, feel free to make any change as you need.

**Comment by reta** [comment]
@bugmakerrrrrr my apologies for delay, I haven't forgotten about this PR, we are working on [1] and it seems like there the violation of the sort guarantees for `SortedDocValues` may have more profound implications. It may warrant the fix on storage part so the navigation over the doc values would emit the right values. 

[1] https://github.com/opensearch-project/OpenSearch/pull/16366

**Comment by bugmakerrrrrr** [comment]
> it seems like the violation of the sort guarantees for `SortedDocValues` may have more profound implications. 
Thank you for the update. AFAIW, this could affect sorting and scripting, other than that, are there any potential effects?

> It may warrant the fix on storage part so the navigation over the doc values would emit the right values.
+1, [as I said before](https://github.com/opensearch-project/OpenSearch/issues/16698#issuecomment-2491697409), we can fix this in new version. But is there anything we can do to fix an index that already exists other than reindex? 

BTW, after the storage part is fixed, I think we still need to special handling of median/avg mode.

**Comment by reta** [comment]
> Thank you for the update. AFAIW, this could affect sorting and scripting, other than that, are there any potential effects?

Thanks @bugmakerrrrrr  I think we've touched all the places where doc values traversal happens and indeed the fix could be isolated in the `MultiValueMode` , I think we should be fine there. 

Could you please add  more tests to rest-api specs? I have added a few but we need to have full coverage for at least unsigned_long / long / double. Thank you.

File: test/framework/src/main/java/org/opensearch/test/rest/yaml/section/MatchAssertion.java [hunk 1]
```diff
@@ -110,6 +111,25 @@ protected void doAssert(Object actualValue, Object expectedValue) {
         }
 
         if (expectedValue.equals(actualValue) == false) {
+            if (expectedValue instanceof ArrayList
```
Comment (bugmakerrrrrr) [inline test/framework/src/main/java/org/opensearch/test/rest/yaml/section/MatchAssertion.java:114]: The sort part of response may be parsed as BigInteger, but the expect value in yaml is parsed as int/long.

File: test/framework/src/main/java/org/opensearch/test/rest/yaml/section/MatchAssertion.java [hunk 2]
```diff
@@ -110,6 +111,28 @@ protected void doAssert(Object actualValue, Object expectedValue) {
         }
 
         if (expectedValue.equals(actualValue) == false) {
+            if (expectedValue instanceof ArrayList && actualValue instanceof ArrayList) {
```
Comment (reta) [inline test/framework/src/main/java/org/opensearch/test/rest/yaml/section/MatchAssertion.java:114]: You don't need to workaround the comparison, please use index based comparison (instead of array):

```
- match: { hits.hits.0.sort: [7] }
```

Would become

```
- match: { hits.hits.0.sort.0: 7 }
```

And works out of the box

Comment (reta) [inline test/framework/src/main/java/org/opensearch/test/rest/yaml/section/MatchAssertion.java:114]: You don't need to workaround the comparison, please use index based comparison (instead of array):

```
- match: { hits.hits.0.sort: [7] }
```

Would become

```
- match: { hits.hits.0.sort.0: 7 }
```

And works out of the box

**Comment by bugmakerrrrrr** [comment]
> ❌ Gradle check result for [92843d0](https://github.com/opensearch-project/OpenSearch/commit/92843d04b2d569b616e1ea6ade9d3de21e6337b0): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/51460/)

After executing query phase on data node, the search result will be sent to the coordinator. If the coordinator is on a different node, the result will be serialized before sending, and [the sort field will be reduced to the primary type during serialization](https://github.com/opensearch-project/OpenSearch/blob/ef44e86705eef46f394a686c20d6faaccc31f91b/server/src/main/java/org/opensearch/common/lucene/Lucene.java#L614-L618). But if the coordinator is on the same node, the response will be passed to the handler directly and won't be serialized. In some cases, this may cause different sort field types when merging search results even for one field of one index. When merging top field docs, if the sort field types are not equal, the current implementation uses double to widen sort fields. In this case, the sort values exceeds the MAX_SAFE_INTEGER (`2^53 – 1`), the sort result is wrong when using double to compare. I have opened #16860 to track this issue.

**Comment by bugmakerrrrrr** [comment]
> ❌ Gradle check result for [92843d0](https://github.com/opensearch-project/OpenSearch/commit/92843d04b2d569b616e1ea6ade9d3de21e6337b0): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/51460/)

@reta I believe that this can be fixed with #16881, would you mind taking a look at #16881 if you get a chance?

**Comment by reta** [comment]
> @reta I believe that this can be fixed with #16881, would you mind taking a look at #16881 if you get a chance?

Apologies @bugmakerrrrrr , I am not be able to find the time for it, just finished with this change, would appreciate your feedback. The `MultiValueMode` now properly supports `unsigned_long`, the dedicated `XxxMultiValueMode` classes are not needed, I think it is aligned with other types of doc values.

**Comment by bugmakerrrrrr** [comment]
@reta Sorry for disturbing you during the holidays. Thank you for sharing this update. I like the idea, it's more clean and consistent. I'll review the latest change soon. Hope you have a wonderful holiday.

File: server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericUnsignedLongValues.java [hunk 3]
```diff
@@ -0,0 +1,82 @@
+/*
+ * SPDX-License-Identifier: Apache-2.0
+ *
+ * The OpenSearch Contributors require contributions made to
+ * this file be licensed under the Apache-2.0 license or a
+ * compatible open source license.
+ */
+
+/*
+ * Licensed to Elasticsearch under one or more contributor
```
Comment (bugmakerrrrrr) [inline server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericUnsignedLongValues.java:10]: do we need to add this license for new file?

File: server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericUnsignedLongValues.java [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+/**
+ * Exposes multi-valued view over a single-valued instance.
+ * <p>
+ * This can be used if you want to have one multi-valued implementation
+ * that works for single or multi-valued types.
+ *
+ * @opensearch.internal
+ */
+
+final class SingletonSortedNumericUnsignedLongValues extends SortedNumericUnsignedLongValues {
```
Comment (bugmakerrrrrr) [inline server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericUnsignedLongValues.java:48]: This doesn't seem to be a singleton values, but simply a wrapper around LongValues, perhaps renamed LongToNumericUnsignedLongValues?

File: server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericUnsignedLongValues.java (hunk 3 above)
Comment (reta) [reply server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericUnsignedLongValues.java:10]: Ah we certainly don't need it, thank you

File: server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericUnsignedLongValues.java (hunk 4 above)
Comment (reta) [reply server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericUnsignedLongValues.java:48]: Yes, it is a wrapper, I was "inspired" by equivalent construct for doubles, but I will think more about your suggestion, perhaps we could simplify things as well, thank you

**Comment by reta** [comment]
> @reta Sorry for disturbing you during the holidays.

Thanks @bugmakerrrrrr , no worries at all, just a bit difficult to find the time, happy holidays to you as well!

**Comment by rishabh6788** [comment]
@bugmakerrrrrr  Do you think it is a good idea to run a quick benchmark as well to check if there is any impact on the query performance as well? If yes, check out https://github.com/opensearch-project/OpenSearch/blob/main/PERFORMANCE_BENCHMARKS.md, `id_5` will be good candidate.

File: server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericUnsignedLongValues.java (hunk 4 above)
Comment (reta) [reply server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericUnsignedLongValues.java]: Replaced with `LongToSortedNumericUnsignedLongValues`, thanks!

**Comment by bugmakerrrrrr** [comment]
> @bugmakerrrrrr Do you think it is a good idea to run a quick benchmark as well to check if there is any impact on the query performance as well? 

I don't think so, this is simply a bugfix, not an enhancement :)

**Comment by bugmakerrrrrr** [comment]
@reta I have an additional concern. Users may specify the `numeric_type` option for the `sort` field in their request, or scripts may depend on the ordered values obtained from the field data. It may be necessary for us to sort the values before returning the document values.(just like we did in `SortingBinaryDocValues`)

**Comment by reta** [comment]
> @reta I have an additional concern. Users may specify the `numeric_type` option for the `sort` field in their request, or scripts may depend on the ordered values obtained from the field data. It may be necessary for us to sort the values before returning the document values.(just like we did in `SortingBinaryDocValues`)

Thanks @bugmakerrrrrr , it would make sense very likely, I think we could make it a separate issue / fix, right?  (since it seems to be not related to multivalues).

**Comment by bugmakerrrrrr** [comment]
> > @reta I have an additional concern. Users may specify the `numeric_type` option for the `sort` field in their request, or scripts may depend on the ordered values obtained from the field data. It may be necessary for us to sort the values before returning the document values.(just like we did in `SortingBinaryDocValues`)
> 
> Thanks @bugmakerrrrrr , it would make sense very likely, I think we could make it a separate issue / fix, right? (since it seems to be not related to multivalues).

@reta Certainly, I will create a new issue to deal with this.

**Comment by reta** [comment]
> ❌ Gradle check result for [bbb1858](https://github.com/opensearch-project/OpenSearch/commit/bbb18582641b756394c9dcdb2527f2d54300c684): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/51821/)

[org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/260_sort_unsigned_long/test sorting against unsigned_long only fields}](https://build.ci.opensearch.org/job/gradle-check/51821/testReport/junit/org.opensearch.smoketest/SmokeTestMultiNodeClientYamlTestSuiteIT/test__yaml_search_260_sort_unsigned_long_test_sorting_against_unsigned_long_only_fields_/)

@bugmakerrrrrr  these failures should be addressed by  https://github.com/opensearch-project/OpenSearch/pull/16881  (whatever the fix would be), correct? thank you

**Comment by bugmakerrrrrr** [comment]
> > ❌ Gradle check result for [bbb1858](https://github.com/opensearch-project/OpenSearch/commit/bbb18582641b756394c9dcdb2527f2d54300c684): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/51821/)
> 
> [org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/260_sort_unsigned_long/test sorting against unsigned_long only fields}](https://build.ci.opensearch.org/job/gradle-check/51821/testReport/junit/org.opensearch.smoketest/SmokeTestMultiNodeClientYamlTestSuiteIT/test__yaml_search_260_sort_unsigned_long_test_sorting_against_unsigned_long_only_fields_/)
> 
> @bugmakerrrrrr these failures should be addressed by #16881 (whatever the fix would be), correct? thank you

@reta Yes

**Review by reta — APPROVED** [review]
