### PR TITLE
Delete Operations on Replicas when Segment Replication is enabled

### LINKED ISSUE #2330: [Segment Replication] Fix delete operations to only write to xlog on replicas.
**Describe the bug**
[This](https://github.com/opensearch-project/OpenSearch/commit/4822c2856fc77dec29a5a326d7e214829990e98e) change allowed index operations to noop on replicas and only write to the xlog.  We need a similar change to noop delete operations.  Right now these still get passed to the engine and invoke methods on a null indexwriter.

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR fixes delete operations to only write to xlog on replicas. Integration Test for this is also added
 
### Issues Resolved
#2330 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 1]
```diff
@@ -229,4 +229,41 @@ public void onFailure(Exception e) {
...
         });
     }
+
+    public void testDeleteOperations() throws Exception {
+        final String nodeA = internalCluster().startNode();
+        final String nodeB = internalCluster().startNode();
+
+        createIndex(
+            INDEX_NAME,
+            Settings.builder()
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:239]: Sorry I missed this on the last PR.  You shouldn't need to set these settings here because we override the indexSettings() method at the top of this file.

```
        createIndex(INDEX_NAME);

```
Will create the index with the default settings we override.

File: server/src/main/java/org/opensearch/index/engine/InternalEngine.java [hunk 2]
```diff
@@ -716,11 +717,13 @@ private ExternalReaderManager createReaderManager(RefreshWarmerListener external
     }
 
     private DirectoryReader getDirectoryReader() throws IOException {
-        // for segment replication: replicas should create the reader from store, we don't want an open IW on replicas.
+        // for segment replication: replicas should create the reader from store and, we don't want an open IW on replicas.
+        /* We should always wrap replicas with a SoftDeletesDirectoryReaderWrapper as we use soft deletes when segment replication is on for
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/engine/InternalEngine.java:721]: nit - "We should always wrap the DirectoryReader used on replicas with `SoftDeletesDirectoryReaderWrapper` so that we filter out soft deletes.

Comment (mch2) [inline server/src/main/java/org/opensearch/index/engine/InternalEngine.java:721]: nit - "We should always wrap the DirectoryReader used on replicas with `SoftDeletesDirectoryReaderWrapper` so that we filter out soft deletes.

File: server/src/main/java/org/opensearch/index/engine/InternalEngine.java [hunk 3]
```diff
@@ -716,11 +717,13 @@ private ExternalReaderManager createReaderManager(RefreshWarmerListener external
...
+        deletions */
         if (engineConfig.isReadOnly()) {
-            return DirectoryReader.open(store.directory());
+            return new SoftDeletesDirectoryReaderWrapper(DirectoryReader.open(store.directory()), Lucene.SOFT_DELETES_FIELD);
         }
-        return DirectoryReader.open(indexWriter);
+        return DirectoryReader.open(indexWriter, true, true);
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/engine/InternalEngine.java:726]: is this required? does your test pass without this like with the first PR?

**Review by mch2 — APPROVED** [review]
LGTM few nits.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 1 above)
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:239]: Yeah sorry I too missed it

**Review by mch2 — APPROVED** [review]
