### PR TITLE
[Remote Segments] Retry segment uploads to remote store on failure

### LINKED ISSUE #7363: [Remote Segments] Retry segment uploads to remote store on failure
As mentioned in #6851, this is the second task to retry if the afterRefresh method in RemoteStoreRefreshListener fails.

### PR DESCRIPTION
**Pull request by ashking94**
### Description
This PR does the following -
 - Introduces retry on failed sync segment attempts during remote refresh.
 - Uses dedicated threadpool for `RemoteStoreRefreshListener.afterRefresh(didRefresh)`
 - Integ test that introduces random failures during remote store operations and retries to sync the segments from local to remote store.

### Related Issues
Resolves #7363 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 1]
```diff
@@ -46,6 +51,25 @@
...
+
+    public static final int REMOTE_REFRESH_RETRY_INTERVAL_DEFAULT_VALUE = 1;
+
+    private static final int MAX_CONCURRENT_SCHEDULED_REMOTE_REFRESH_RETRIES = 1;
+
+    /**
+     * If the remote refresh segment sync fails, we retry to sync the segments scheduling it after a retry interval
+     * which is controlled by the below setting.
+     */
+    public static final Setting<Integer> INDEX_REMOTE_REFRESH_RETRY_INTERVAL = Setting.intSetting(
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:65]: evaluating exponential back off here

**Comment by ashking94** [comment]
FYI - One of the other is to make changes in `scheduleRefresh()` method of `IndexShard` class. 
https://github.com/opensearch-project/OpenSearch/blob/01e5c294eba1be7fef5dfbb87f2ecc3012d9dc4f/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L4147-L4176

In the first if condition can be changed to 
`if (isReadAllowed() && (listenerNeedsRefresh || getEngine().refreshNeeded()) || noRemoteSegmentsLag()) {`
However, this is relatively more intrusive and will lead to complete refresh process getting triggered although most of it will be no-op. And on failures this will continue to get retried after every `index.refresh_interval` time which can be catastrophic if the retries induce more failures (throttling due to more retries).

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 2]
```diff
@@ -57,7 +88,15 @@ public final class RemoteStoreRefreshListener implements ReferenceManager.Refres
     private final RemoteSegmentStoreDirectory remoteDirectory;
     private final Map<String, String> localSegmentChecksumMap;
     private long primaryTerm;
-    private static final Logger logger = LogManager.getLogger(RemoteStoreRefreshListener.class);
+
+    /**
+     * Semaphore that ensures there is only 1 retry scheduled at any time.
+     */
+    private final Semaphore retrySemaphore = new Semaphore(MAX_CONCURRENT_SCHEDULED_REMOTE_REFRESH_RETRIES);
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:95]: Is it possible that normal refresh and retried refresh (of previous failed normal refresh) are happening at the same time?

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 3]
```diff
@@ -83,92 +123,149 @@ public void beforeRefresh() throws IOException {
...
-                        this.primaryTerm = indexShard.getOperationPrimaryTerm();
-                        this.remoteDirectory.init();
+        try {
+            indexShard.getThreadPool().executor(ThreadPool.Names.REMOTE_REFRESH).submit(() -> syncSegments(false)).get();
+        } catch (InterruptedException | ExecutionException e) {
+            logger.info("Exception occurred while scheduling syncSegments", e);
+        }
+    }
+
+    private synchronized void syncSegments(boolean retry) {
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:138]: nit: `isRetry` makes it more clear similar to how you added it in `afterSegmentsSync`

File: server/src/main/java/org/opensearch/threadpool/ThreadPool.java [hunk 4]
```diff
@@ -410,14 +416,14 @@ public ExecutorService executor(String name) {
...
+     * @param delay    delay before the task executes
      * @param executor the name of the thread pool on which to execute this task. SAME means "execute on the scheduler thread" which changes
-     *        the meaning of the ScheduledFuture returned by this method. In that case the ScheduledFuture will complete only when the
-     *        command completes.
+     *                 the meaning of the ScheduledFuture returned by this method. In that case the ScheduledFuture will complete only when the
+     *                 command completes.
      * @return a ScheduledFuture who's get will return when the task is has been added to its target thread pool and throw an exception if
-     *         the task is canceled before it was added to its target thread pool. Once the task has been added to its target thread pool
-     *         the ScheduledFuture will cannot interact with it.
+     * the task is canceled before it was added to its target thread pool. Once the task has been added to its target thread pool
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/threadpool/ThreadPool.java:425]: Whitespaces got added in this file.

**Comment by sachinpkale** [comment]
Regarding PR title: `Retry remote refresh on failure` - not sure what we mean by remote refresh here but could be `Retry segment uploads to remote store on failure`

**Comment by ashking94** [comment]
> 

Remote refresh is basically the entire process of syncing segments on local to remote store - is what I meant, but can change the title.

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java (hunk 2 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:95]: No, that wont happen as there is `syncSegments(boolean isRetry)` method  which is synchronised. But this can happen that a retry has been scheduled to happen after some x seconds, and there is a normal refresh that is happening now. If this normal refresh fails, it can not schedule another retry as the previous has already acquired the single permit.

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 5]
```diff
@@ -83,92 +123,149 @@ public void beforeRefresh() throws IOException {
...
+                    shouldRetry = true;
+                    // We don't want to fail refresh if upload of new segments fails. The missed segments will be re-tried
+                    // in the next refresh. This should not affect durability of the indexed data after remote trans-log integration.
+                    logger.warn("Exception while uploading new segments to the remote segment store", e);
                 }
-            } catch (Throwable t) {
-                logger.error("Exception in RemoteStoreRefreshListener.afterRefresh()", t);
             }
+        } catch (Throwable t) {
+            logger.error("Exception in RemoteStoreRefreshListener.afterRefresh()", t);
```
[the remark this answers is not in the document]
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:222]: Missed this, added here as well. We must retry here also as the `this.remoteDirectory.init()` can fail due to remote store interaction failures.

File: server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+        indexData(randomIntBetween(5, 10), randomBoolean());
+        IndicesStatsResponse response = client().admin().indices().stats(new IndicesStatsRequest()).get();
+        assertEquals(1, response.getShards().length);
+
+        String indexUuid = response.getShards()[0].getShardRouting().index().getUUID();
+        Path segmentDataRepoPath = location.resolve(String.format(Locale.ROOT, "%s/0/segments/data", indexUuid));
+        String segmentDataLocalPath = String.format(Locale.ROOT, "%s/indices/%s/0/index", response.getShards()[0].getDataPath(), indexUuid);
+
+        assertBusy(
+            () -> assertEquals(getSegmentFiles(location.getRoot().resolve(segmentDataLocalPath)), getSegmentFiles(segmentDataRepoPath))
```
[the remark this answers is not in the document]
Comment (ashking94) [reply server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java:110]: Added logs and comments.

File: server/src/main/java/org/opensearch/threadpool/ThreadPool.java [hunk 7]
```diff
@@ -261,6 +263,10 @@ public ThreadPool(
         );
         builders.put(Names.TRANSLOG_SYNC, new FixedExecutorBuilder(settings, Names.TRANSLOG_SYNC, allocatedProcessors * 4, 10000));
         builders.put(Names.REMOTE_PURGE, new ScalingExecutorBuilder(Names.REMOTE_PURGE, 1, halfProcMaxAt5, TimeValue.timeValueMinutes(5)));
+        builders.put(
+            Names.REMOTE_REFRESH,
+            new ScalingExecutorBuilder(Names.REMOTE_REFRESH, 1, allocatedProcessors * 4, TimeValue.timeValueMinutes(5))
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/threadpool/ThreadPool.java:268]: Basis follow up performance test, this will be tuned if required.

Comment (sachinpkale) [reply server/src/main/java/org/opensearch/threadpool/ThreadPool.java:268]: Unless we have strong reasons, let's start with smaller threadpool and increase the size based on threadpool queue observed during perf tests. Larger threadpools may work fine in perf tests but can cause non-trivial issues where CPU spent more time context switching than actual work due to too many threads.

**Review by sachinpkale — APPROVED** [review]

File: server/src/main/java/org/opensearch/threadpool/ThreadPool.java (hunk 7 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/threadpool/ThreadPool.java:268]: makes sense, making it to halfProcMaxAt10 (same as refresh TP) for now.

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 8]
```diff
@@ -46,6 +54,29 @@
  * @opensearch.internal
  */
 public final class RemoteStoreRefreshListener implements ReferenceManager.RefreshListener {
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:56]: can we add UTs for this change and cover the four cases of `isRetry` and `shouldRetry` ?

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 9]
```diff
@@ -46,6 +54,29 @@
...
+
+    /**
+     * Exponential back off policy with max retry interval.
+     */
+    private static final BackoffPolicy EXPONENTIAL_BACKOFF_POLICY = BackoffPolicy.exponentialEqualJitterBackoff(
+        REMOTE_REFRESH_RETRY_BASE_INTERVAL_SECONDS,
+        REMOTE_REFRESH_RETRY_MAX_INTERVAL_SECONDS
+    );
+
+    private static final int MAX_CONCURRENT_SCHEDULED_REMOTE_REFRESH_RETRIES = 1;
```
[the remark this answers is not in the document]
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:78]: these are more of permits - i see usage of both mutex and permits, but permits make more sense.

[the remark this answers is not in the document]
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:78]: `private final Semaphore SCHEDULE_RETRY_PERMITS = new Semaphore(1);` - removed the constant.

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 10]
```diff
@@ -83,92 +123,150 @@ public void beforeRefresh() throws IOException {
...
-                        this.primaryTerm = indexShard.getOperationPrimaryTerm();
-                        this.remoteDirectory.init();
+        try {
+            indexShard.getThreadPool().executor(ThreadPool.Names.REMOTE_REFRESH).submit(() -> syncSegments(false)).get();
+        } catch (InterruptedException | ExecutionException e) {
+            logger.info("Exception occurred while scheduling syncSegments", e);
+        }
+    }
+
+    private synchronized void syncSegments(boolean isRetry) {
```
[the remark this answers is not in the document]
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:138]: consider this - normal refresh triggered upload failed, it scheduled a retry scheduled at n seconds from the failure time. Now meanwhile another normal refresh triggered upload failed, it will try to trigger another retry scheduled at 2*n seconds from then but the first retry is yet to happen. If we do not have the semaphore (permits check), multiple retry can get scheduled while not even a single retry has really happened. Also, semaphore helps schedule deterministic exponential back off retries by ensuring one retry can be scheduled at a time. when the retry fails, it will schedule next refresh at 2*n seconds from then. hope this makes sense.

File: server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java [hunk 11]
```diff
@@ -204,6 +210,120 @@ public void onFailure(Exception e) {
...
     }
 
+    public void testRefreshSuccessOnFirstAttempt() throws Exception {
+        // This is the case of isRetry=false, shouldRetry=false
+        // Succeed on 1st attempt
+        int succeedOnAttempt = 1;
+        // We spy on IndexShard.getReplicationTracker() to validate that we have tried running remote time as per the expectation.
+        CountDownLatch refreshCountLatch = new CountDownLatch(succeedOnAttempt);
+        // We spy on IndexShard.getEngine() to validate that we have successfully hit the terminal code for ascertaining successful upload.
+        CountDownLatch successLatch = new CountDownLatch(2);
```
[the remark this answers is not in the document]
Comment (ashking94) [reply server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java:220]: Yes, getEngine is getting called thrice in a successful upload scenario.

File: server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java [hunk 12]
```diff
@@ -204,6 +210,120 @@ public void onFailure(Exception e) {
...
+        AtomicLong counter = new AtomicLong();
+        // Mock indexShard.getSegmentInfosSnapshot()
+        doAnswer(invocation -> {
+            if (counter.incrementAndGet() <= SucceedOnAttempt - 1) {
+                throw new RuntimeException("Inducing failure in upload");
+            }
+            return indexShard.getSegmentInfosSnapshot();
+        }).when(shard).getSegmentInfosSnapshot();
+
+        when(shard.getEngine()).thenReturn(indexShard.getEngine());
```
[the remark this answers is not in the document]
Comment (ashking94) [reply server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java:305]: removed. ty!

**Comment by ashking94** [comment]
[org.opensearch.cluster.shards.ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting](https://build.ci.opensearch.org/job/gradle-check/15026/testReport/junit/org.opensearch.cluster.shards/ClusterShardLimitIT/testCreateIndexWithMaxClusterShardSetting/)
Looks to be a flaky test, will create an issue for the same if it does not exist.

**Comment by ashking94** [comment]
Looks to be unrelated flaky test again.

File: server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java [hunk 13]
```diff
@@ -217,7 +217,8 @@ public void testRefreshSuccessOnFirstAttempt() throws Exception {
         // We spy on IndexShard.getReplicationTracker() to validate that we have tried running remote time as per the expectation.
         CountDownLatch refreshCountLatch = new CountDownLatch(succeedOnAttempt);
         // We spy on IndexShard.getEngine() to validate that we have successfully hit the terminal code for ascertaining successful upload.
-        CountDownLatch successLatch = new CountDownLatch(2);
+        // Value has been set as 3 as during a successful upload IndexShard.getEngine() is hit thrice and with mockito we are counting down
+        CountDownLatch successLatch = new CountDownLatch(3);
```
Comment (gbbafna) [inline server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java:222]: thanks . won't we need to do same for other tests as well ?

Comment (ashking94) [reply server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java:222]: added the missed condition..

**Review by gbbafna — APPROVED** [review]
