### PR TITLE
Fix flaky SearchCancellationIT tests to avoid race condition

### LINKED ISSUE #2242: [BUG] org.opensearch.search.SearchCancellationIT.testMSearchChildRequestCancellationWithClusterLevelTimeout
Below test failure identified in https://github.com/opensearch-project/OpenSearch/pull/2238

```
**REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchCancellationIT.testMSearchChildRequestCancellationWithClusterLevelTimeout" -Dtests.seed=36921F5835FAE3A1 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-IN -Dtests.timezone=Etc/GMT+5 -Druntime.java=17

org.opensearch.search.SearchCancellationIT > testMSearchChildRequestCancellationWithClusterLevelTimeout FAILED
    java.lang.AssertionError: Actual child request with cancellation failure is different that expected expected:<[0, 1]> but was:<[]>
        at __randomizedtesting.SeedInfo.seed([36921F5835FAE3A1:882FD4BDA4EC03D6]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.opensearch.search.SearchCancellationIT.ensureMSearchWasCancelled(SearchCancellationIT.java:194)
        at org.opensearch.search.SearchCancellationIT.testMSearchChildRequestCancellationWithClusterLevelTimeout(SearchCancellationIT.java:537)
```

### LINKED ISSUE #2311: [BUG] o.o.search.SearchCancellationIT.testCancellationDuringFetchPhaseUsingRequestParameter
Non-reproducible test failure caught on #2262

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchCancellationIT.testCancellationDuringFetchPhaseUsingRequestParameter" -Dtests.seed=6C5BC8BF8BF27536 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fr-BE -Dtests.timezone=Europe/Astrakhan -Druntime.java=17
```

```
  2> java.lang.AssertionError: At least one shard should have failed. Actual: 0
        at __randomizedtesting.SeedInfo.seed([6C5BC8BF8BF27536:ECD39451EE78990B]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failEquals(Assert.java:187)
        at org.junit.Assert.assertNotEquals(Assert.java:201)
        at org.opensearch.search.SearchCancellationIT.ensureSearchWasCancelled(SearchCancellationIT.java:167)
        at org.opensearch.search.SearchCancellationIT.testCancellationDuringFetchPhaseUsingRequestParameter(SearchCancellationIT.java:301)
```

### LINKED ISSUE #2763: [BUG] testCancellationDuringQueryPhaseUsingRequestParameter flakey test
**Describe the bug**

testCancellationDuringQueryPhaseUsingRequestParameter

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchCancellationIT.testCancellationDuringQueryPhaseUsingRequestParameter" -Dtests.seed=181F3F6D79C48BB2 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=lv -Dtests.timezone=Africa/Monrovia -Druntime.java=17

org.opensearch.search.SearchCancellationIT > testCancellationDuringQueryPhaseUsingRequestParameter FAILED
    java.lang.AssertionError: At least one shard should have failed. Actual: 0
        at __randomizedtesting.SeedInfo.seed([181F3F6D79C48BB2:9A8D0FA37A08DEA1]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failEquals(Assert.java:187)
        at org.junit.Assert.assertNotEquals(Assert.java:201)
        at org.opensearch.search.SearchCancellationIT.ensureSearchWasCancelled(SearchCancellationIT.java:167)
        at org.opensearch.search.SearchCancellationIT.testCancellationDuringQueryPhaseUsingRequestParameter(SearchCancellationIT.java:247)

```

https://github.com/opensearch-project/OpenSearch/pull/2654

### PR DESCRIPTION
**Pull request by dbwiddis**
Signed-off-by: Daniel Widdis <widdis@gmail.com>

### Description

[`Thread.sleep()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Thread.html#sleep(long)) does not sleep for precise amounts:
> Causes the currently executing thread to sleep (temporarily cease execution) for the specified number of milliseconds, **subject to the precision and accuracy of system timers and schedulers**.

Tests in the `SearchCancellationIT` class relied on sleeping for exactly the cancellation timeout, which creates potential race conditions and occasional test failures.

This PR adds an extra 100ms of sleep time before checking the cancellation status.

### Issues Resolved
Fixes #2242 
Fixes #2311
Fixes #2763

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/search/SearchCancellationIT.java [hunk 1]
```diff
@@ -241,7 +241,8 @@ public void testCancellationDuringQueryPhaseUsingRequestParameter() throws Excep
             .execute();
         awaitForBlock(plugins);
         // sleep for cancellation timeout to ensure scheduled cancellation task is actually executed
```
Comment (andrross) [inline server/src/internalClusterTest/java/org/opensearch/search/SearchCancellationIT.java:243]: This comment is no longer accurate. How about a static `sleepForTimeout()` or similar method so you only have to write the comment once?

Also, any idea why 2 seconds is used everywhere here? Would be great to make that something shorter (like 100ms) to speed up the test.

Comment (dbwiddis) [reply server/src/internalClusterTest/java/org/opensearch/search/SearchCancellationIT.java:243]: But I was having so much fun copying and pasting with _The Key_.   Sure, I'll make a static call.  Not sure what the best minimum should be, but I'm guessing I could make it 1 second at least?

Comment (andrross) [reply server/src/internalClusterTest/java/org/opensearch/search/SearchCancellationIT.java:243]: Sure. You'll make it twice as fast!

**Review by andrross — APPROVED** [review]
