### PR TITLE
Fix broken backward compatibility from 2.7 for IndexSorted field indices

### LINKED ISSUE #10044: [BUG] Fix broken backward comparibility from 2.7 for IndexSorted field indices
### Description
Upgrade to OpenSearch 2.7 is breaking with change #6424 . Not for all scenarios but when any index contains IndexSorted field of either BYTE, BOOLEAN, SHORT, INTEGER, where the IndexSortField we created in prior version was upcasted to LONG for all above types, which was removed in #6424 to achieve better performance for sort queries.
The SortField for IndexSort is stored in SegmentInfo and that gets retained when index is migrating from old cluster to new 2.7 cluster, and hence in IndexWriter creation, Lucene throws Excetion because on 2.7, IndexWriteConfiguration has IndexSort with non-upcasted type while in SegmentInfo Lucene finds the same sort field with up-casted.

i.e, check below scenario, where Index sort is on Integer field, and the index is migrating from older version to 2.7 version, and on newer version, the IndexWriterCreation fails with IndexSort mismatch between IndexWriteIndexSort & Lucene segmentinfo contained indexsort.

```
"sort" : {
          "field" : "position",
          "order" : "desc"
        },
"position" : {
          "type" : "integer"
        },


Caused by: RemoteTransportException[[d3aea48e6d44f0fc824a9051f26d9969][:9300][internal:index/shard/recovery/prepare_translog]]; nested: IllegalArgumentException[cannot change previous indexSort=<sortednumeric: "position">! missingValue=-9223372036854775808 selector=MAX type=LONG (from segment=_8g9x(9.4.2):C61519:[indexSort=<sortednumeric: "position">! missingValue=-9223372036854775808 selector=MAX type=LONG]:[diagnostics={os=Linux, os.version=5.10.149-133.644.amzn2.aarch64, timestamp=1694560481039, mergeMaxNumSegments=-1, lucene.version=9.4.2, source=merge, os.arch=aarch64, java.runtime.version=11.0.18+10-LTS, mergeFactor=4, java.vendor=Amazon.com Inc.}]:[attributes={Lucene90StoredFieldsFormat.mode=BEST_SPEED}]:fieldInfosGen=36:dvGen=36 :softDel=27709 :id=5gdgx085ys6f3xyyb68rpx85c) to new indexSort=<sortednumeric: "position">! missingValue=-2147483648 selector=MAX type=INT];
Caused by: java.lang.IllegalArgumentException: cannot change previous indexSort=<sortednumeric: "position">! missingValue=-9223372036854775808 selector=MAX type=LONG (from segment=_8g9x(9.4.2):C61519:[indexSort=<sortednumeric: "position">! missingValue=-9223372036854775808 selector=MAX type=LONG]:[diagnostics={os=Linux, os.version=5.10.149-133.644.amzn2.aarch64, timestamp=1694560481039, mergeMaxNumSegments=-1, lucene.version=9.4.2, source=merge, os.arch=aarch64, java.runtime.version=11.0.18+10-LTS, mergeFactor=4, java.vendor=Amazon.com Inc.}]:[attributes={Lucene90StoredFieldsFormat.mode=BEST_SPEED}]:fieldInfosGen=36:dvGen=36 :softDel=27709 :id=5gdgx085ys6f3xyyb68rpx85c) to new indexSort=<sortednumeric: "position">! missingValue=-2147483648 selector=MAX type=INT
        at org.apache.lucene.index.IndexWriter.validateIndexSort(IndexWriter.java:1208)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1119)
        at org.opensearch.index.engine.InternalEngine.createWriter(InternalEngine.java:2437)
        at org.opensearch.index.engine.InternalEngine.createWriter(InternalEngine.java:2425)
        at org.opensearch.index.engine.InternalEngine.<init>(InternalEngine.java:305)
        at org.opensearch.index.engine.InternalEngine.<init>(InternalEngine.java:223)
        at org.opensearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:43)
        at org.opensearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2286)
        at org.opensearch.index.shard.IndexShard.openEngineAndSkipTranslogRecovery(IndexShard.java:2259)
        at org.opensearch.indices.recovery.RecoveryTarget.lambda$prepareForTranslogOperations$1(RecoveryTarget.java:256)
```

This fix we need to release as patch release for >=2.7 versions.

### PR DESCRIPTION
**Pull request by gashutos**
### Description
Upgrade to OpenSearch 2.7 is breaking with change #6424 . Not for all scenarios but when any index contains IndexSorted field of either BYTE, BOOLEAN, SHORT, INTEGER, where the IndexSortField we created in prior version was upcasted to LONG for all above types, which was removed in #6424 to achieve better performance for sort queries.
The SortField for IndexSort is stored in SegmentInfo and that gets retained when index is migrating from old cluster to new 2.7 cluster, and hence in IndexWriter creation, Lucene throws Exception because on 2.7, IndexWriteConfiguration has IndexSort with non-upcasted type while in SegmentInfo Lucene finds the same sort field with up-casted.

i.e, check below scenario, where Index sort is on Integer field, and the index is migrating from older version to 2.7 version, and on newer version, the IndexWriterCreation fails with IndexSort mismatch between IndexWriteIndexSort & Lucene segmentinfo contained indexsort.

```
"sort" : {
          "field" : "position",
          "order" : "desc"
        },
"position" : {
          "type" : "integer"
        },


Caused by: RemoteTransportException[[d3aea48e6d44f0fc824a9051f26d9969][:9300][internal:index/shard/recovery/prepare_translog]]; nested: IllegalArgumentException[cannot change previous indexSort=<sortednumeric: "position">! missingValue=-9223372036854775808 selector=MAX type=LONG (from segment=_8g9x(9.4.2):C61519:[indexSort=<sortednumeric: "position">! missingValue=-9223372036854775808 selector=MAX type=LONG]:[diagnostics={os=Linux, os.version=5.10.149-133.644.amzn2.aarch64, timestamp=1694560481039, mergeMaxNumSegments=-1, lucene.version=9.4.2, source=merge, os.arch=aarch64, java.runtime.version=11.0.18+10-LTS, mergeFactor=4, java.vendor=Amazon.com Inc.}]:[attributes={Lucene90StoredFieldsFormat.mode=BEST_SPEED}]:fieldInfosGen=36:dvGen=36 :softDel=27709 :id=5gdgx085ys6f3xyyb68rpx85c) to new indexSort=<sortednumeric: "position">! missingValue=-2147483648 selector=MAX type=INT];
Caused by: java.lang.IllegalArgumentException: cannot change previous indexSort=<sortednumeric: "position">! missingValue=-9223372036854775808 selector=MAX type=LONG (from segment=_8g9x(9.4.2):C61519:[indexSort=<sortednumeric: "position">! missingValue=-9223372036854775808 selector=MAX type=LONG]:[diagnostics={os=Linux, os.version=5.10.149-133.644.amzn2.aarch64, timestamp=1694560481039, mergeMaxNumSegments=-1, lucene.version=9.4.2, source=merge, os.arch=aarch64, java.runtime.version=11.0.18+10-LTS, mergeFactor=4, java.vendor=Amazon.com Inc.}]:[attributes={Lucene90StoredFieldsFormat.mode=BEST_SPEED}]:fieldInfosGen=36:dvGen=36 :softDel=27709 :id=5gdgx085ys6f3xyyb68rpx85c) to new indexSort=<sortednumeric: "position">! missingValue=-2147483648 selector=MAX type=INT
        at org.apache.lucene.index.IndexWriter.validateIndexSort(IndexWriter.java:1208)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1119)
        at org.opensearch.index.engine.InternalEngine.createWriter(InternalEngine.java:2437)
        at org.opensearch.index.engine.InternalEngine.createWriter(InternalEngine.java:2425)
        at org.opensearch.index.engine.InternalEngine.<init>(InternalEngine.java:305)
        at org.opensearch.index.engine.InternalEngine.<init>(InternalEngine.java:223)
        at org.opensearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:43)
        at org.opensearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2286)
        at org.opensearch.index.shard.IndexShard.openEngineAndSkipTranslogRecovery(IndexShard.java:2259)
        at org.opensearch.indices.recovery.RecoveryTarget.lambda$prepareForTranslogOperations$1(RecoveryTarget.java:256)
```

I have added check to treat old migrating indices to treat as Sort field type upcatsed when they are moving to OpenSearch 2.7.

### Related Issues
Resolves #10044

### Testing done
- [x] Tested below scenarions for all BYTE, BOOLEAN, INTEGER, SHORT types with Index sort
- [x] Migrating indices from OpenSearch 2.5 to OpenSearch 2.7
- [x] Indexing more documents to above migrated indices in OpenSearch 2.7
- [x] Fresh index on OpenSearch 2.7
- [x] Old index created on OpenSearch 2.7 iteself and upgraded to new OpenSearch 2.7 version with this patch
- [x] Sort queries on all above scenarios in asc/desc order

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gashutos** [comment]
@reta @nknize @backslasht @shwetathareja @Bukhtawar 
This needs urgent attention. 
We need to patch this OpenSearch 2.7+ else upgrade will break.

File: server/src/main/java/org/opensearch/index/IndexSettings.java [hunk 1]
```diff
@@ -857,6 +858,13 @@ public IndexSettings(final IndexMetadata indexMetadata, final Settings nodeSetti
         mergeOnFlushEnabled = scopedSettings.get(INDEX_MERGE_ON_FLUSH_ENABLED);
         setMergeOnFlushPolicy(scopedSettings.get(INDEX_MERGE_ON_FLUSH_POLICY));
         defaultSearchPipeline = scopedSettings.get(DEFAULT_SEARCH_PIPELINE);
+        /* There was unintentional breaking change got introduced with OpenSearch-6424 (version 2.7).
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/IndexSettings.java:861]:
```suggestion
        /* There was unintentional breaking change got introduced with [OpenSearch-6424](https://github.com/opensearch-project/OpenSearch/pull/6424) (version 2.7).
```

File: server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java [hunk 2]
```diff
@@ -428,6 +428,7 @@ public SortFieldAndFormat build(QueryShardContext context) throws IOException {
             }
             IndexNumericFieldData numericFieldData = (IndexNumericFieldData) fieldData;
             NumericType resolvedType = resolveNumericType(numericType);
+            System.out.println("CHETAN LOGS : " + resolvedType);
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java:431]: Probably should not be there

**Comment by gashutos** [comment]
@reta do you know if we have version upgrade integ tests ? I am not able to find...

File: .idea/runConfigurations/Debug_OpenSearch.xml
Comment (gashutos) [inline .idea/runConfigurations/Debug_OpenSearch.xml:1]: I will be restoring this in next iteration.

File: server/src/main/java/org/opensearch/index/IndexSettings.java [hunk 3]
```diff
@@ -857,6 +859,13 @@ public IndexSettings(final IndexMetadata indexMetadata, final Settings nodeSetti
         mergeOnFlushEnabled = scopedSettings.get(INDEX_MERGE_ON_FLUSH_ENABLED);
         setMergeOnFlushPolicy(scopedSettings.get(INDEX_MERGE_ON_FLUSH_POLICY));
         defaultSearchPipeline = scopedSettings.get(DEFAULT_SEARCH_PIPELINE);
+        /* There was unintentional breaking change got introduced with [OpenSearch-6424](https://github.com/opensearch-project/OpenSearch/pull/6424) (version 2.7).
+         * For indices created prior version (prior to 2.7) which has IndexSort type, they used to type caste the SortField.Type
+         * to higher bytes size like integer to long. This behavior was changed from OpenSearch 2.7 version not to
+         * up caste the SortField to gain some sort query optimizations.
+         * Now this sortField (IndexSort) is stored in SegmentInfo and we need to maintain backward compatibility for them.
+         */
+        widenIndexSortType = IndexMetadata.SETTING_INDEX_VERSION_CREATED.get(settings).onOrBefore(LegacyESVersion.V_2_6_1);
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/IndexSettings.java:868]: No need to use `LegacyESVersion`:

```suggestion
        widenIndexSortType = IndexMetadata.SETTING_INDEX_VERSION_CREATED.get(settings).onOrBefore(Version.V_2_6_1);
```

File: server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java [hunk 4]
```diff
@@ -128,6 +137,7 @@ public final SortField sortField(
             || nested != null
             || (sortMode != MultiValueMode.MAX && sortMode != MultiValueMode.MIN)
             || targetNumericType != getNumericType()) {
+            System.out.println("Custom comparator logic.....");
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java:140]: Debug leftovers?

Comment (gashutos) [reply server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java:140]: :( Removing in next iteration.

File: server/src/main/java/org/opensearch/index/IndexSortConfig.java [hunk 5]
```diff
@@ -200,6 +200,7 @@ public boolean hasPrimarySortOnField(String field) {
      * or returns null if this index has no sort.
      */
     public Sort buildIndexSort(
+        boolean shouldWidenIndexSortTpe,
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/IndexSortConfig.java:203]: I think you don't need this parameter, we could get it from `indexSettings` on construction:

```
 public IndexSortConfig(IndexSettings indexSettings)
```

File: server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java [hunk 6]
```diff
@@ -96,6 +99,12 @@ public final boolean isFloatingPoint() {
         public final ValuesSourceType getValuesSourceType() {
             return valuesSourceType;
         }
+
+        public void setSortFieldType(SortField.Type type) {
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java:103]: May be we could use constructor for that (with `usePointBasedOptimization` argument) instead of inplace modification?

File: server/src/main/java/org/opensearch/index/IndexSortConfig.java (hunk 5 above)
Comment (gashutos) [reply server/src/main/java/org/opensearch/index/IndexSortConfig.java]: Done

File: server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java (hunk 6 above)
Comment (gashutos) [reply server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java:103]: The numeric type is already initialized here. We are chaning that during run time to make it backward compatible.
To change the NumericType upfront thrugh constructor, that change will be lot of overlapping chnage where this case is not applicable at all...

**Comment by gashutos** [comment]
> @reta do you know if we have version upgrade integ tests ? I am not able to find...

Added as a part of mixed cluster scenario where replicas are kept on other versions. Which is similar usecase herer.

File: server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java (hunk 6 above)
Comment (reta) [reply server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java:103]: I understand that the numeric type is already initialized here. The solution clearly violates the `NumericType` invariants and I would argue that should not be the case. We have to look for a better ways to propagate `usePointBasedOptimization` change.

Comment (gashutos) [reply server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java]: Damn !! My bad.
Yeah, I reaized I modified enum and that is the reason it was giving type mimatch during search as well hence I had to disable optimization.

But that is absolutely not needed. I am not modifying enum now but just up-casting SortField.Type works fine during IndexSortField creation for IndexWriter.

Comment (reta) [reply server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java]: > But that is absolutely not needed. I am not modifying enum now but just up-casting SortField.Type works fine during IndexSortField creation for IndexWriter.

My apologies, for some reason your reply was not showing up when I posted the suggestion, please feel free to discard it if simpler option works, thanks!

File: server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java [hunk 7]
```diff
@@ -151,6 +151,25 @@ public final SortField sortField(Object missingValue, MultiValueMode sortMode, N
         return sortField(getNumericType(), missingValue, sortMode, nested, reverse);
     }
 
+    @Override
+    public final SortField wideSortField(Object missingValue, MultiValueMode sortMode, Nested nested, boolean reverse) {
+        // This is to support backward compatibility, the minimum number of bytes prior to OpenSearch 2.7 were 8 bytes,
+        // i.e all sort fields were upcasted to Long/Double with 16 bytes.
+        // Now from OpenSearch 2.7, the minimum number of bytes for sort field is 8 bytes, so if it comes as SortField INT,
+        // we need to up caste it to LONG to support backward compatibility info stored in segment info
+        if (getNumericType().sortFieldType == SortField.Type.INT) {
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java:160]: :+1: much better, thanks @gashutos !

**Review by reta — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java (hunk 6 above)
Comment (gashutos) [reply server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java]: No problem.
Yes, I think now that `usePointBasedOptimization` is not required, lets not touch the existing NumericTypes and `sortField` methods. Everything is contained within `wideSortField` method for this backward compatibility handling.

File: server/src/main/java/org/opensearch/index/fielddata/IndexFieldData.java [hunk 8]
```diff
@@ -94,6 +94,13 @@ public interface IndexFieldData<FD extends LeafFieldData> {
      */
     SortField sortField(@Nullable Object missingValue, MultiValueMode sortMode, Nested nested, boolean reverse);
 
+    /**
+     * Returns the {@link SortField} to use for index sorting where we widen the sort field type to higher or equal bytes.
+     */
+    default SortField wideSortField(@Nullable Object missingValue, MultiValueMode sortMode, Nested nested, boolean reverse) {
+        return sortField(missingValue, sortMode, nested, reverse);
+    }
+
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/fielddata/IndexFieldData.java:103]: For my understanding in which flows will this default be exercised?

Comment (gashutos) [reply server/src/main/java/org/opensearch/index/fielddata/IndexFieldData.java:103]: For non-numeric types, when it tries to create IndexSort to put in IndexWriterConfig. It is only `String` as of now.
```
/** We only allow index sorting on these types */
    private static final EnumSet<SortField.Type> ALLOWED_INDEX_SORT_TYPES = EnumSet.of(
        SortField.Type.STRING,
        SortField.Type.LONG,
        SortField.Type.INT,
        SortField.Type.DOUBLE,
        SortField.Type.FLOAT
    );
```
[Code](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/IndexSortConfig.java#L263)

**Comment by reta** [comment]
@Bukhtawar all cleared out from your side? thanks!

File: server/src/main/java/org/opensearch/index/IndexSettings.java [hunk 9]
```diff
@@ -857,6 +859,13 @@ public IndexSettings(final IndexMetadata indexMetadata, final Settings nodeSetti
         mergeOnFlushEnabled = scopedSettings.get(INDEX_MERGE_ON_FLUSH_ENABLED);
         setMergeOnFlushPolicy(scopedSettings.get(INDEX_MERGE_ON_FLUSH_POLICY));
         defaultSearchPipeline = scopedSettings.get(DEFAULT_SEARCH_PIPELINE);
+        /* There was unintentional breaking change got introduced with [OpenSearch-6424](https://github.com/opensearch-project/OpenSearch/pull/6424) (version 2.7).
+         * For indices created prior version (prior to 2.7) which has IndexSort type, they used to type caste the SortField.Type
```
Comment (backslasht) [inline server/src/main/java/org/opensearch/index/IndexSettings.java:863]:
```suggestion
         * For indices created prior version (prior to 2.7) which has IndexSort type, they used to type cast the SortField.Type
```

**Review by backslasht — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java [hunk 10]
```diff
@@ -151,6 +151,25 @@ public final SortField sortField(Object missingValue, MultiValueMode sortMode, N
         return sortField(getNumericType(), missingValue, sortMode, nested, reverse);
     }
 
+    @Override
+    public final SortField wideSortField(Object missingValue, MultiValueMode sortMode, Nested nested, boolean reverse) {
+        // This is to support backward compatibility, the minimum number of bytes prior to OpenSearch 2.7 were 16 bytes,
+        // i.e all sort fields were upcasted to Long/Double with 16 bytes.
+        // Now from OpenSearch 2.7, the minimum number of bytes for sort field is 8 bytes, so if it comes as SortField INT,
+        // we need to up caste it to LONG to support backward compatibility info stored in segment info
+        if (getNumericType().sortFieldType == SortField.Type.INT) {
```
[the remark this answers is not in the document]
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java:160]: +1

**Review by Bukhtawar — COMMENTED** [review]
Do we need to have a BWC IT test for this?

File: server/src/test/java/org/opensearch/index/fielddata/AbstractFieldDataImplTestCase.java [hunk 11]
```diff
@@ -144,6 +145,27 @@ public void testSingleValueAllSet() throws Exception {
...
+
+        // long to long no widening should happen
+        indexFieldData = getForField("long", "value");
+        sortField = indexFieldData.wideSortField(null, MultiValueMode.MIN, null, false);
+        assertTrue(((SortedNumericSortField) sortField).getNumericType() == SortField.Type.LONG);
+
+        // float to float no widening should happen
+        indexFieldData = getForField("float", "value");
+        sortField = indexFieldData.wideSortField(null, MultiValueMode.MIN, null, false);
+        assertTrue(((SortedNumericSortField) sortField).getNumericType() == SortField.Type.FLOAT);
```
[the remark this answers is not in the document]
Comment (gashutos) [reply server/src/test/java/org/opensearch/index/fielddata/AbstractFieldDataImplTestCase.java:165]: @backslasht Float is mapped to Float only. In prior versions as well current versions.

[the remark this answers is not in the document]
Comment (backslasht) [reply server/src/test/java/org/opensearch/index/fielddata/AbstractFieldDataImplTestCase.java:165]: Got it! thanks!

File: server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (gashutos) [reply server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java:160]: Float is mapped to float only, so not requred here as well.

File: server/src/test/java/org/opensearch/index/IndexServiceTests.java [hunk 12]
```diff
@@ -526,4 +528,60 @@ public void testUpdateRemoteTranslogBufferIntervalDynamically() {
...
+    public void testIndexSortBackwardCompatible() {
+        Settings settings = Settings.builder()
+            .put(IndexSettings.INDEX_TRANSLOG_SYNC_INTERVAL_SETTING.getKey(), "0ms") // disable
+            .put(IndexMetadata.SETTING_INDEX_VERSION_CREATED.getKey(), Version.V_2_6_1)
+            .putList("index.sort.field", "sortfield")
+            .build();
+        try {
+            // Integer index sort should be converted to long sort type
+            IndexService index = createIndex("test", settings, createTestMapping("integer"));
+            assertTrue(index.getIndexSortSupplier().get().getSort()[0].getType() == SortField.Type.LONG);
```
[the remark this answers is not in the document]
Comment (gashutos) [reply server/src/test/java/org/opensearch/index/IndexServiceTests.java]: Makse sense. Added.

**Comment by gashutos** [comment]
Thanks for reviews @reta @backslasht @Bukhtawar 

@reta help me merging this once @backslasht approves.

File: qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java [hunk 13]
```diff
@@ -46,6 +46,7 @@
 import org.opensearch.common.xcontent.json.JsonXContent;
 import org.opensearch.common.xcontent.support.XContentMapValues;
 import org.opensearch.core.common.Strings;
+import org.opensearch.core.xcontent.XContentBuilder;
```
Comment (backslasht) [inline qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java:49]: unused import

File: qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java [hunk 14]
```diff
@@ -63,17 +64,19 @@
 
 import static org.hamcrest.Matchers.contains;
 import static org.hamcrest.Matchers.equalTo;
+import static org.opensearch.common.xcontent.XContentFactory.jsonBuilder;
```
Comment (backslasht) [inline qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java:67]: unused import

**Review by backslasht — APPROVED** [review]
Looks good to me! Thanks @gashutos for quickly fixing it.

File: qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java (hunk 13 above)
Comment (gashutos) [reply qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java]: Oops

File: qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java (hunk 14 above)
Comment (gashutos) [reply qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java]: Done
