### PR TITLE
Fix node local term/version log truncation with long host provider addresses

### LINKED ISSUE #19249: [BUG] Node's local term and version truncated when IP address provided by host providers is huge
### Describe the bug

After a quorum loss event, surviving nodes in the cluster can be identified by the master node's local term and version logged in [ClusterFormationHelper](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java#L194-L195). 

`                "discovery will continue using %s from hosts providers and %s from last-known cluster state; "
                    + "node term %d, last-accepted version %d in term %d",`

But when the list of IP address by host providers is big, the node's local term and version information gets truncated and there's no way to identify surviving nodes because a node's local cluster state term and version information is not exposed by any API.  

Example log line where term and version were truncated after 400+ Ips from host provider

```
[2025-08-11T09:47:30,984][WARN ][o.o.c.c.ClusterFormationFailureHelper] [c1188a2094fd05e8a9f0518fef26e7d7] cluster-manager not discovered or elected yet, an election requires a node with id [JT26AxO0Qzy21H3OJHbHZg], have discovered [{c1188a2094fd05e8a9f0518fef26e7d7}{Spsem31RRZSeR2a2M-uz9Q}{aSH2uw2DQWeXxMdQYZrpGQ}{172.16.45.203}{172.16.45.203:9300}{dimr}{dp_version=20210501, admission_control_resource_tracker_feature_present=true, search_reactivation_counter_feature_present=true, adv_sec_enabled=false, cross_cluster_transport_address=2a05:d016:494:9082:aa6f:e87b:85a1:df77, awareness_features_enabled=true, internal_term_version_enabled=true, search_backpressure_feature_present=true, coordinator_nodes_stats_feature_present=true, distributed_snapshot_deletion_enabled=false, cold_enabled=false, zone=eu-north-1b, indices.doc_status_stats_enabled=true, local_term_version_enabled=true, global_cpu_usage_ac_supported=true, shard_indexing_pressure_enabled=true, di_number=7, task_cancellation_monitoring_feature_present=true}, {be28647301c767d6021b8ddf59952b10}{q8rgJ9gcQgCGQFRscDMPvQ}{cBIkyHJoTjyX2JaYjOSGvg}{172.16.16.74}{172.16.16.74:9300}{dimr}{dp_version=20210501, admission_control_resource_tracker_feature_present=true, search_reactivation_counter_feature_present=true, adv_sec_enabled=false, cross_cluster_transport_address=2a05:d016:494:9081:46e0:62d0:9577:ad07, awareness_features_enabled=true, internal_term_version_enabled=true, search_backpressure_feature_present=true, coordinator_nodes_stats_feature_present=true, distributed_snapshot_deletion_enabled=false, cold_enabled=false, zone=eu-north-1a, indices.doc_status_stats_enabled=true, local_term_version_enabled=true, global_cpu_usage_ac_supported=true, shard_indexing_pressure_enabled=true, di_number=7, task_cancellation_monitoring_feature_present=true}] which is not a quorum; discovery will continue using [127.0.0.1:9301, 127.0.0.1:9302, 127.0.0.1:9303, 127.0.0.1:9304, 127.0.0.1:9305, [::1]:9301, [::1]:9302, [::1]:9303, [::1]:9304, [::1]:9305, 172.16.16.116:9300, 172.16.16.123:9300, 172.16.16.124:9300, 172.16.16.130:9300, 172.16.16.147:9300, 172.16.16.166:9300, 172.16.16.166:9300, 172.16.16.169:9300, 172.16.16.175:9300, 172.16.16.179:9300, 172.16.16.180:9300, 172.16.16.181:9300, 172.16.16.195:9300, 172.16.16.203:9300, 172.16.16.234:9300, 172.16.16.31:9300, 172.16.16.33:9300, 172.16.16.44:9300, 172.16.16.47:9300, 172.16.16.50:9300, 172.16.16.65:9300, 172.16.16.74:9300, 172.16.17.102:9300, 172.16.17.138:9300, 172.16.17.167:9300, 172.16.17.175:9300, 172.16.17.177:9300, 172.16.17.192:9300, 172.16.17.208:9300, 172.16.17.210:9300, 172.16.17.245:9300, 172.16.17.38:9300, 172.16.17.64:9300, 172.16.17.70:9300, 172.16.18.106:9300, 172.16.18.11:9300, 172.16.18.120:9300, 172.16.18.160:9300, 172.16.18.167:9300, 172.16.18.202:9300, 172.16.18.203:9300, 172.16.18.241:9300, 172.16.18.245:9300, 172.16.18.49:9300, 172.16.18.69:9300, 172.16.19.139:9300, 172.16.19.140:9300, 172.16.19.142:9300, 172.16.19.156:9300, 172.16.19.191:9300, 172.16.19.196:9300, 172.16.19.225:9300, 172.16.19.234:9300, 172.16.19.29:9300, 172.16.19.34:9300, 172.16.19.42:9300, 172.16.19.54:9300, 172.16.19.73:9300, 172.16.19.77:9300, 172.16.19.86:9300, 172.16.20.108:9300, 172.16.20.131:9300, 172.16.20.163:9300, 172.16.20.171:9300, 172.16.20.176:9300, 172.16.20.207:9300, 172.16.20.222:9300, 172.16.20.235:9300, 172.16.20.249:9300, 172.16.20.30:9300, 172.16.20.31:9300, 172.16.20.53:9300, 172.16.20.62:9300, 172.16.20.68:9300, 172.16.20.98:9300, 172.16.21.141:9300, 172.16.21.15:9300, 172.16.21.151:9300, 172.16.21.170:9300, 172.16.21.190:9300, 172.16.21.192:9300, 172.16.21.202:9300, 172.16.21.204:9300, 172.16.21.210:9300, 172.16.21.36:9300, 172.16.21.5:9300, 172.16.21.54:9300, 172.16.21.64:9300, 172.16.21.70:9300, 172.16.21.91:9300, 172.16.22.101:9300, 172.16.22.136:9300, 172.16.22.157:9300, 172.16.22.169:9300, 172.16.22.185:9300, 172.16.22.186:9300, 172.16.22.217:9300, 172.16.22.250:9300, 172.16.22.27:9300, 172.16.22.5:9300, 172.16.22.70:9300, 172.16.22.8:9300, 172.16.22.84:9300, 172.16.22.92:9300, 172.16.23.142:9300, 172.16.23.162:9300, 172.16.23.164:9300, 172.16.23.205:9300, 172.16.23.211:9300, 172.16.23.217:9300, 172.16.23.222:9300, 172.16.23.222:9300, 172.16.23.241:9300, 172.16.23.8:9300, 172.16.24.13:9300, 172.16.24.138:9300, 172.16.24.161:9300, 172.16.24.198:9300, 172.16.24.215:9300, 172.16.24.219:9300, 172.16.24.222:9300, 172.16.24.245:9300, 172.16.24.253:9300, 172.16.24.254:9300, 172.16.24.26:9300, 172.16.24.3:9300, 172.16.24.5:9300, 172.16.24.87:9300, 172.16.24.92:9300, 172.16.24.92:9300, 172.16.24.99:9300, 172.16.25.19:9300, 172.16.25.193:9300, 172.16.25.199:9300, 172.16.25.232:9300, 172.16.25.27:9300, 172.16.25.28:9300, 172.16.25.62:9300, 172.16.25.71:9300, 172.16.25.79:9300, 172.16.25.90:9300, 172.16.25.92:9300, 172.16.26.106:9300, 172.16.26.144:9300, 172.16.26.159:9300, 172.16.26.164:9300, 172.16.26.174:9300, 172.16.26.235:9300, 172.16.26.242:9300, 172.16.26.32:9300, 172.16.26.33:9300, 172.16.26.48:9300, 172.16.26.52:9300, 172.16.26.62:9300, 172.16.26.78:9300, 172.16.26.9:9300, 172.16.27.109:9300, 172.16.27.119:9300, 172.16.27.123:9300, 172.16.27.137:9300, 172.16.27.138:9300, 172.16.27.145:9300, 172.16.27.168:9300, 172.16.27.207:9300, 172.16.27.214:9300, 172.16.27.226:9300, 172.16.27.229:9300, 172.16.27.238:9300, 172.16.27.26:9300, 172.16.27.46:9300, 172.16.27.56:9300, 172.16.27.72:9300, 172.16.28.11:9300, 172.16.28.112:9300, 172.16.28.116:9300, 172.16.28.119:9300, 172.16.28.134:9300, 172.16.28.138:9300, 172.16.28.157:9300, 172.16.28.173:9300, 172.16.28.205:9300, 172.16.28.208:9300, 172.16.28.236:9300, 172.16.28.245:9300, 172.16.28.247:9300, 172.16.28.55:9300, 172.16.28.82:9300, 172.16.28.90:9300, 172.16.29.108:9300, 172.16.29.118:9300, 172.16.29.125:9300, 172.16.29.150:9300, 172.16.29.212:9300, 172.16.29.236:9300, 172.16.29.33:9300, 172.16.29.45:9300, 172.16.29.69:9300, 172.16.29.77:9300, 172.16.29.90:9300, 172.16.30.112:9300, 172.16.30.131:9300, 172.16.30.197:9300, 172.16.30.198:9300, 172.16.30.207:9300, 172.16.30.209:9300, 172.16.30.231:9300, 172.16.30.232:9300, 172.16.30.249:9300, 172.16.30.253:9300, 172.16.30.30:9300, 172.16.30.35:9300, 172.16.30.4:9300, 172.16.30.85:9300, 172.16.30.98:9300, 172.16.31.101:9300, 172.16.31.110:9300, 172.16.31.127:9300, 172.16.31.133:9300, 172.16.31.136:9300, 172.16.31.137:9300, 172.16.31.162:9300, 172.16.31.167:9300, 172.16.31.190:9300, 172.16.31.235:9300, 172.16.31.250:9300, 172.16.31.33:9300, 172.16.31.84:9300, 172.16.31.91:9300, 172.16.31.92:9300, 172.16.32.109:9300, 172.16.32.123:9300, 172.16.32.154:9300, 172.16.32.163:9300, 172.16.32.196:9300, 172.16.32.213:9300, 172.16.32.30:9300, 172.16.32.75:9300, 172.16.32.79:9300, 172.16.32.9:9300, 172.16.32.99:9300, 172.16.33.1:9300, 172.16.33.149:9300, 172.16.33.157:9300, 172.16.33.163:9300, 172.16.33.170:9300, 172.16.33.174:9300, 172.16.33.187:9300, 172.16.33.25:9300, 172.16.34.163:9300, 172.16.34.19:9300, 172.16.34.211:9300, 172.16.34.235:9300, 172.16.34.25:9300, 172.16.34.253:9300, 172.16.34.73:9300, 172.16.34.85:9300, 172.16.34.94:9300, 172.16.35.124:9300, 172.16.35.125:9300, 172.16.35.151:9300, 172.16.35.164:9300, 172.16.35.165:9300, 172.16.35.186:9300, 172.16.35.206:9300, 172.16.35.21:9300, 172.16.35.215:9300, 172.16.35.3:9300, 172.16.35.63:9300, 172.16.36.129:9300, 172.16.36.138:9300, 172.16.36.14:9300, 172.16.36.167:9300, 172.16.36.173:9300, 172.16.36.177:9300, 172.16.36.216:9300, 172.16.36.36:9300, 172.16.36.66:9300, 172.16.36.79:9300, 172.16.37.145:9300, 172.16.37.151:9300, 172.16.37.168:9300, 172.16.37.179:9300, 172.16.37.194:9300, 172.16.37.199:9300, 172.16.37.219:9300, 172.16.37.235:9300, 172.16.37.238:9300, 172.16.37.31:9300, 172.16.37.62:9300, 172.16.37.64:9300, 172.16.37.66:9300, 172.16.37.76:9300, 172.16.37.85:9300, 172.16.37.99:9300, 172.16.38.146:9300, 172.16.38.165:9300, 172.16.38.177:9300, 172.16.38.183:9300, 172.16.38.233:9300, 172.16.38.27:9300, 172.16.38.96:9300, 172.16.39.124:9300, 172.16.39.130:9300, 172.16.39.132:9300, 172.16.39.178:9300, 172.16.39.191:9300, 172.16.39.192:9300, 172.16.39.216:9300, 172.16.39.223:9300, 172.16.39.65:9300, 172.16.39.81:9300, 172.16.40.0:9300, 172.16.40.107:9300, 172.16.40.112:9300, 172.16.40.131:9300, 172.16.40.157:9300, 172.16.40.173:9300, 172.16.40.185:9300, 172.16.40.192:9300, 172.16.40.195:9300, 172.16.40.204:9300, 172.16.40.207:9300, 172.16.40.232:9300, 172.16.40.64:9300, 172.16.40.90:9300, 172.16.41.102:9300, 172.16.41.106:9300, 172.16.41.156:9300, 172.16.41.167:9300, 172.16.41.183:9300, 172.16.41.191:9300, 172.16.41.255:9300, 172.16.41.52:9300, 172.16.41.75:9300, 172.16.42.140:9300, 172.16.42.169:9300, 172.16.42.171:9300, 172.16.42.206:9300, 172.16.42.213:9300, 172.16.42.220:9300, 172.16.42.253:9300, 172.16.42.44:9300, 172.16.42.46:9300, 172.16.42.48:9300, 172.16.43.153:9300, 172.16.43.160:9300, 172.16.43.20:9300, 172.16.43.213:9300, 172.16.43.228:9300, 172.16.43.236:9300, 172.16.43.25:9300, 172.16.43.54:9300, 172.16.43.75:9300, 172.16.43.98:9300, 172.16.44.102:9300, 172.16.44.119:9300, 172.16.44.13:9300, 172.16.44.133:9300, 172.16.44.134:9300, 172.16.44.182:9300, 172.16.44.198:9300, 172.16.44.216:9300, 172.16.44.220:9300, 172.16.44.230:9300, 172.16.44.240:9300, 172.16.44.246:9300, 172.16.44.253:9300, 172.16.44.34:9300, 172.16.44.96:9300, 172.16.45.130:9300, 172.16.45.140:9300, 172.16.45.146:9300, 172.16.45.149:9300, 172.16.45.154:9300, 172.16.45.171:9300, 172.16.45.210:9300, 172.16.45.23:9300, 172.16.45.251:9300, 172.16.45.253:9300, 172.16.45.28:9300, 172.16.45.45:9300, 172.16.45.46:9300, 172.16.45.58:9300, 172.16.45.60:9300, 172.16.45.84:9300, 172.16.46.124:9300, 172.16.46.134:9300, 172.16.46.136:9300, 172.16.46.165:9300, 172.16.46.19:9300, 172.16.46.224:9300, 172.16.46.233:9300, 172.16.46.3:9300, 172.16.47.118:9300, 172.16.47.135:9300, 172.16.47.143:9300, 172.16.47.152:9300, 172.16.47.174:9300, 172.16.47.189:9300, 172.16.47.206:9300, 172.16.47.207:9300, 172.16.47.213:9300, 172.16.47.244:9300, 172.16.47.32:9300, 172.16.47.47:9300, 172.16.47.52:9300, 172.16.47.67:9300] from hosts providers and [{c1188a2094fd05e8a9f0518fef26e7d7}{Spsem31RRZSeR2a2M-uz9Q}{aSH2uw2DQWeXxMdQYZ
[2025-08-11T09:47:30,988][INFO ][o.o.n.c.logger           ] [c1188a2094fd05e8a9f0518fef26e7d7] GET /_nodes/_local/stats/
```

### Related component

Cluster Manager

### To Reproduce

A cluster with 400+ Ips

### Expected behavior

Change the log format to deterministically log the term and version.

### PR DESCRIPTION
**Pull request by srikanthpadakanti**
### Description
This change fixes an issue where a node’s local term and version information could be truncated in cluster formation failure logs when host providers return very long IP addresses or host strings.

The truncation made critical coordination diagnostics difficult, especially in environments with custom or dynamic host providers that emit unusually large address values. This update ensures that the full local term and version information is preserved and logged correctly, improving observability and debuggability during cluster formation failures.

The fix includes:
- Safer handling of long host provider address strings during log construction.
- Adjustments to avoid truncation of local term and version fields.
- Expanded test coverage to validate behavior with large host/IP inputs.

### Related Issues
Resolves #19249

### Check List
- [ X] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java [hunk 1]
```diff
@@ -74,6 +74,27 @@ public class ClusterFormationFailureHelper {
         Setting.Property.NodeScope
     );
 
+    public static final Setting<Integer> DISCOVERY_CLUSTER_FORMATION_WARNING_ADDRESS_LIMIT_SETTING = Setting.intSetting(
```
Comment (andrross) [inline server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java]: I would really like to avoid the complexity of another setting. I think reordering the log message is probably sufficient. Log the critical data first, followed by the addresses and nodes. If the data gets truncated then at least you still have the term and version data. What do you think?

Comment (srikanthpadakanti) [reply server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java]: I agree reordering is the core fix, and I’ve already done that so term/version are logged first and remain visible even if the line truncates.

I also added bounded printing of the hosts-provider list since reordering alone can still produce very large, repeatedly emitted log lines when many addresses are present. This keeps logs readable and reduces noise while preserving context via a small sample and remaining count.
If you ask me, I want to keep this setting as is. But to your point, to keep this minimal, I’m happy to drop the new setting and use a small fixed internal limit instead. 

Let me know your 2cents on this.

Comment (andrross) [reply server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java]: The problem with truncating the list is that it's really hard to know at what value to truncate. The original issue only mentioned loosing important information, which is fixed by the reordering. If log noise is a problem then I'd suggest potentially splitting the message across different log statements at different log levels. I'd be careful about bounding the list unless we know for sure that log noise is a problem. Maybe @SwethaGuptha can weigh in here?

Comment (srikanthpadakanti) [reply server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java]: The original issue is addressed by reordering, and I don’t want to optimize further without clear evidence that log noise is a problem. To keep this minimal, I’ll drop the new setting and truncation logic and keep only the reordering so term and version are always logged first.

If log volume becomes an issue later, we can revisit bounded output or split logging in a followup. I’ll update the PR accordingly.

File: CHANGELOG.md [hunk 2]
```diff
@@ -43,6 +43,8 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 - LeafReader should not remove SubReaderWrappers incase IndexWriter encounters a non aborting Exception ([#20193](https://github.com/opensearch-project/OpenSearch/pull/20193))
 - Fix Netty deprecation warnings in transport-reactor-netty4 module ([20429](https://github.com/opensearch-project/OpenSearch/pull/20429))
 - Fix stats aggregation returning zero results with `size:0`. ([20427](https://github.com/opensearch-project/OpenSearch/pull/20427))
+- Fix node local term and version being truncated in logs when host providers return very long IP or host strings ([19249](https://github.com/opensearch-project/OpenSearch/pull/19249))
```
Comment (andrross) [inline CHANGELOG.md]: Duplicate entry?

Comment (srikanthpadakanti) [reply CHANGELOG.md]: Yeah. Removed.

**Comment by srikanthpadakanti** [comment]
Hello @andrross 

The failure is in :distribution:docker:buildArm64DockerImage
Root cause: AlmaLinux mirror 404 during dnf install.   

Re-ran the CI pipeline but issue still persists. Any inputs on, how to address this?
