### PR TITLE
Fix 1.x compatibility bug with stored Tasks

### LINKED ISSUE #5376: [BUG] after upgrade to OpenSearch 2.0, finished tasks no longer get stored in .tasks index
**Describe the bug**
We've upgraded from OpenSearch 1.3 to OpenSearch 2.0. The index mapping of .tasks index didn't get updated to include the cancelled field. Since the mapping on this index is strict, results of finished tasks no longer get stored in the index and are gone from OS as soon as the task is finished. This makes it impossible to track the results of long running tasks.

**To Reproduce**
1. Install OS 1.3
2. Run a longer update by query operation (e.g. scripted) (or run it async to get the task id)
3. Issue a GET on /_tasks, make note of the task id
4. Issue a GET on /_tasks/taskId. You will get a result while the task is running and after it has finished.
5. Upgrade to 2.0
6. Repeat steps 2-4
7. The task results will be available while the task is running and will disappear right after the task is finished.

**Expected behavior**
The result of the task is visible even after the task is finished.

### PR DESCRIPTION
**Pull request by andrross**
When the new 'cancelled' field was introduced it was a miss not to increment the version number on the mapping definitions for the .tasks index. This commit fixes that oversight, as well as modifies the existing backward compatiblity test to ensure that it will catch future mistakes like this one.

Closes #5376

Signed-off-by: Andrew Ross <andrross@amazon.com>

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/SystemIndicesUpgradeIT.java [hunk 1]
```diff
@@ -115,4 +101,29 @@ public void testSystemIndicesUpgrades() throws Exception {
...
     }
+
+    /**
+     * Completed tasks get persisted into the .tasks index, so this method waits
+     * until the task is completed in order to verify that it has been successfully
+     * written to the index and can be retrieved.
+     */
+    private static void createAndVerifyStoredTask() throws Exception {
+        // Use update by query to create an async task
+        final Request updateByQueryRequest = new Request("POST", "/test_index_old/_update_by_query");
```
Comment (reta) [inline qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/SystemIndicesUpgradeIT.java:112]: Just curious, `_reindex` was replaced with `_update_by_query`, is there some particular reason?

**Review by reta — APPROVED** [review]

File: qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/SystemIndicesUpgradeIT.java (hunk 1 above)
Comment (andrross) [reply qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/SystemIndicesUpgradeIT.java:112]: Because it is done twice, once for the old cluster and again for the updated cluster. Reindex creates a new index so you can't make the exact same request twice (unless you closed or deleted the new index). Update by query is simpler because it takes no parameters and doesn't create any new resources :)

Comment (andrross) [reply qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/SystemIndicesUpgradeIT.java:112]: (Previously this step was only being done on the old cluster, so there was no problem. My change does this test for both the old and updated clusters.)

**Review by dreamer-89 — APPROVED** [review]
LGTM! Thanks @andrross for this quick fix.

**Comment by dreamer-89** [comment]
> ```
>       1 org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex
> ```



> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** UNSTABLE ❕
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex
> ```
> 
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/7453/
> * **CommitID:** [319aecc](https://github.com/opensearch-project/OpenSearch/commit/319aecc2b447064b5847826883f8bb9cf2101ff2)
>   Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

Created https://github.com/opensearch-project/OpenSearch/issues/5414 to track this.
