### PR TITLE
Fix flaky segrep test testPrimaryStopped_ReplicaPromoted

### LINKED ISSUE #5669: [Meta] Segment Replication flaky test failures
Coming from https://github.com/opensearch-project/OpenSearch/pull/4959, which enables yml based feature flag settings; reveals flakyness in Segment replication tests. 

- [x] testAddNewReplicaFailure
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationIT.testAddNewReplicaFailure" -Dtests.seed=D3DBF1C239661FF6 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=it -Dtests.timezone=Brazil/West -Druntime.java=19

org.opensearch.indices.replication.SegmentReplicationIT > testAddNewReplicaFailure FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([D3DBF1C239661FF6:F35C3295F5C37311]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertFalse(Assert.java:65)
        at org.junit.Assert.assertFalse(Assert.java:75)
        at org.opensearch.indices.replication.SegmentReplicationIT.testAddNewReplicaFailure(SegmentReplicationIT.java:267)
```
- [x] testSnapshotOnSegRep_RestoreOnSegRepDuringIngestion
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.SegmentReplicationSnapshotIT.testSnapshotOnSegRep_RestoreOnSegRepDuringIngestion" -Dtests.seed=857112ECE4907AD3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=mk-MK -Dtests.timezone=Africa/Porto-Novo -Druntime.java=19

org.opensearch.snapshots.SegmentReplicationSnapshotIT > testSnapshotOnSegRep_RestoreOnSegRepDuringIngestion FAILED
    java.lang.AssertionError: timed out waiting for green state
        at __randomizedtesting.SeedInfo.seed([857112ECE4907AD3:AAFEB48B53C084CE]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1001)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:932)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:921)
        at org.opensearch.snapshots.SegmentReplicationSnapshotIT.testSnapshotOnSegRep_RestoreOnSegRepDuringIngestion(SegmentReplicationSnapshotIT.java:180)
```
- [x] testReplicationAfterPrimaryRefreshAndFlush
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationIT.testReplicationAfterPrimaryRefreshAndFlush" -Dtests.seed=857112ECE4907AD3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-SY -Dtests.timezone=Antarctica/McMurdo -Druntime.java=19

org.opensearch.indices.replication.SegmentReplicationIT > testReplicationAfterPrimaryRefreshAndFlush FAILED
    java.lang.AssertionError: Count is 0 hits but 73 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
        at __randomizedtesting.SeedInfo.seed([857112ECE4907AD3:6CAB602C42AF5D02]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.hamcrest.OpenSearchAssertions.assertHitCount(OpenSearchAssertions.java:303)
        at org.opensearch.indices.replication.SegmentReplicationIT.testReplicationAfterPrimaryRefreshAndFlush(SegmentReplicationIT.java:296)
```
For tracking added to meta #1715 

- [x] org.opensearch.indices.replication.SegmentReplicationIT.testStartReplicaAfterPrimaryIndexesDocs
https://github.com/opensearch-project/OpenSearch/pull/5704#issuecomment-1372301014

- [x] org.opensearch.indices.replication.SegmentReplicationIT.testRestartPrimary
https://github.com/opensearch-project/OpenSearch/pull/5722#issuecomment-1374254422
- [x] https://github.com/opensearch-project/OpenSearch/issues/6065
- [x] #6259
- [x] testSegmentReplicationStatsResponse flaky failure https://github.com/opensearch-project/OpenSearch/pull/6370

### PR DESCRIPTION
**Pull request by mch2**
Signed-off-by: Marc Handalian <handalm@amazon.com>

### Description
Unmute segrep test testPrimaryStopped_ReplicaPromoted.  This test was muted with PR: https://github.com/opensearch-project/OpenSearch/pull/5739/files# and fixed with https://github.com/opensearch-project/OpenSearch/issues/6015 that waits until replicas have done a sync until asserting doc count.

### Issues Resolved
#5669

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 1]
```diff
@@ -65,7 +65,7 @@ public void testPrimaryStopped_ReplicaPromoted() throws Exception {
         assertHitCount(client(replica).prepareSearch(INDEX_NAME).setSize(0).setPreference("_only_local").get(), 2);
 
         // assert we can index into the new primary.
-        client().prepareIndex(INDEX_NAME).setId("3").setSource("bar", "baz").setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE).get();
+        client().prepareIndex(INDEX_NAME).setId("3").setSource("bar", "baz").setRefreshPolicy(WriteRequest.RefreshPolicy.WAIT_UNTIL).get();
```
Comment (dreamer-89) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:68]: How does changing from `IMMEDIATE` to `WAIT_UNTIL` fixes the flakyness ? The`IMMEDIATE` refresh policy forces refresh with indexing request which means doc should already be searchable.

Comment (mch2) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java]: You are right it doesn't, IMMEDIATE blocks until a refresh completes, wait_until waits until the next refresh cycle to complete.  Neither of these was the reason for flakiness, removed this change.

Comment (mch2) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java]: Updated PR description for when this test was fixed, this is simply to unmute it.

Comment (dreamer-89) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java]: Thanks @mch2 for confirmation.  I see this was muted in https://github.com/opensearch-project/OpenSearch/pull/5898 without any description (though I know it failed once in a while before).

**Review by dreamer-89 — APPROVED** [review]

**Comment by mch2** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/10979/
> * **CommitID:** [639aa3f](https://github.com/opensearch-project/OpenSearch/commit/639aa3f31e7862b2d0392ef9b0564a15e152472d)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

https://github.com/opensearch-project/OpenSearch/issues/6251
