### PR TITLE
Fix non-x64 bwc build targets

### LINKED ISSUE #16535: [BUG] Task `:distribution:bwc:minor:buildBwcLinuxArm64Tar` fails on Linux ARM
### Describe the bug

```
> Task :distribution:bwc:minor:buildBwcLinuxArm64Tar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:bwc:minor:buildBwcLinuxArm64Tar'.
> Building 2.19.0 didn't generate expected file /home/ubuntu/OpenSearch/distribution/bwc/minor/build/bwc/checkout-2.x/distribution/archives/linux-arm64-tar/build/distributions/opensearch-min-2.19.0-SNAPSHOT-linux-arm64-x64.tar.gz
```

### Related component

Build

### To Reproduce

Execute `./gradlew :distribution:bwc:minor:buildBwcLinuxArm64Tar` on a Graviton AWS EC2 instance with Ubuntu installed.

It expects the file `opensearch-min-2.19.0-SNAPSHOT-linux-arm64-x64.tar.gz` but the actual file that is created is `opensearch-min-2.19.0-SNAPSHOT-linux-arm64.tar.gz` (there's an extra "-x64" in the expected file).

I believe the problem is here:

https://github.com/opensearch-project/OpenSearch/blob/d158ec6d431615b16192c34490b46752f3eb3e0f/buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java#L184

If I remove that trailing `"-x64"` then it works, though I'm sure that change would break the build for the non-ARM case.

### Expected behavior

task succeeds

### Additional Details

`m8g.4xlarge` EC2 instance running Ubuntu 24.04

### PR DESCRIPTION
**Pull request by andrross**
There were a few issues here: the '-x64' suffix was being unconditionally appeneded, debian uses underscores not hyphens, and the rpm target uses the '.86_64' suffix.

This feels like a hack, but the `./gradlew distribution:bwc:minor:buildBwc` task now succeeds with this commit, whereas previously several of the targets failed. I've tested this on Intel Linux, Arm Linux, and Apple Silicon Mac. I think during a normal `check` run only the target that corresponds to the platform doing the building is executed, which is why the other targets were broken but no one had noticed. I'll happily entertain any suggestions on how to add a test for this!

### Related Issues
Resolves #16535

### Check List
- [x] Functionality includes testing.
- [ ] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java [hunk 1]
```diff
@@ -181,15 +181,19 @@ private static List<DistributionProject> resolveArchiveProjects(File checkoutDir
...
                     extension = name.substring(index + 1);
                     if (extension.equals("tar")) {
                         extension += ".gz";
                     }
                 } else if (name.contains("deb")) {
-                    classifier = "-amd64";
+                    classifier = "_amd64";
                 } else if (name.contains("rpm")) {
-                    classifier = "-x64";
+                    classifier = ".x86_64";
```
Comment (reta) [inline buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java:196]: I think this change is not right, here is the `.deb` and `.rpm` for latest release:
`https://artifacts.opensearch.org/releases/bundle/opensearch/2.18.0/opensearch-2.18.0-linux-x64.deb`
`https://artifacts.opensearch.org/releases/bundle/opensearch/2.18.0/opensearch-2.18.0-linux-x64.rpm`

Comment (andrross) [reply buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java:196]: If I understand things correctly, you're linking to the distribution target built by the scripts that live in opensearch-build. Here's what I get when running the gradle tasks in this repo:

```
$ ./gradlew distribution:bwc:minor:buildBwcRpm
...
$ ls /home/ubuntu/OpenSearch/distribution/bwc/minor/build/bwc/checkout-2.x/distribution/packages/rpm/build/distributions
opensearch-min-2.19.0-SNAPSHOT.x86_64.rpm
```

Comment (reta) [reply buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java:196]: Oh I see, correct, but shouldn't those be the same? Or there is a separate build for those? To be fair, `x86_64` looks correct to me, but difference is quite confusing

Comment (andrross) [reply buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java:196]: I believe opensearch-build takes the RPM built by the min distribution, opens it up, adds all the other plugins, then packages it back into an RPM which is the artifact that is released. I suppose ideally the artifact names would be the same (except for the "-min" part) but I'm not sure it is worth the effort to change it.

Comment (reta) [reply buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java:196]: I see, thanks @andrross

**Review by reta — APPROVED** [review]
