### PR TITLE
Painless compilation threshold breach with correct error status

### LINKED ISSUE #1064: [BUG] Wrong error code for Painless scripts compilation thresholds
**Describe the bug**
When compilation threshold is breached a circuit breaker exception is called and end status of the error is 500.

**To Reproduce**
1. Create a Opensearch cluster with `./gradlew -p ./distribution/archives/no-jdk-linux-tar assemble distZip  -Drepos.mavenLocal=true` and extracting the tar.
2. Add `script.disable_max_compilations_rate: false` in config/opensearch.yml
3. After running the Opensearch, change setting by runnning this command 
`curl --location --request PUT 'localhost:9200/_cluster/settings' \
--header 'Content-Type: application/json' \
--data-raw '{
    "persistent":{
        "script.max_compilations_rate": "use-context",
        "script.context.field.max_compilations_rate": "0/1m"
    }
}'`
4. Add a doc in _test_ index, using `curl --location --request POST 'localhost:9200/test/_doc/1' \
--header 'Content-Type: application/json' \
--data-raw '{
  "my_field": 10
}'`
5. Run a painless script, run `curl --location --request GET 'localhost:9200/test/_search' \
--header 'Content-Type: application/json' \
--data-raw '{
  "script_fields": {
    "my_doubled_field": {
      "script": {
        "lang":   "painless",
        "source": "return doc['\''my_field'\''].value * params.get('\''multiplier'\'');",
        "params": {
          "multiplier": 17
        }
      }
    }
  }
}'`

**Expected behaviour**
We should get error with code 429.

### PR DESCRIPTION
**Pull request by shiv0408**
### Description
When a circuit breaker occurs due to compilation threshold breach, then OpenSearchRejectedExecutionException is called.
 
### Issues Resolved
Resolves #1064 
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/script/ScriptCache.java [hunk 1]
```diff
@@ -130,6 +131,9 @@
             Throwable cause = executionException.getCause();
             if (cause instanceof ScriptException) {
                 throw (ScriptException) cause;
+            } else if (cause instanceof CircuitBreakingException) {
+                throw new OpenSearchRejectedExecutionException(
+                    "Failed to compile " + type + " script [" + id + "] using lang [" + lang + "]", cause);
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/script/ScriptCache.java:136]: `CircuitBreakingException` already returns 429?

Comment (shiv0408) [reply server/src/main/java/org/opensearch/script/ScriptCache.java:136]: `CircuitBreakingException` was wrapped in `GeneralScriptException` which return 500 error. You can have a look at reproduced [error](https://gist.github.com/shiv0408/02a56c4b8eb306f2781551521cdd4d12).

Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/script/ScriptCache.java:136]: Ideally the status is determined by the underlying cause https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/OpenSearchException.java#L253-L260. Can you check if there is something amiss here. In this case since

Also please update the steps to reproduce

**Review by Bukhtawar — APPROVED** [review]
LGTM!

**Comment by Bukhtawar** [comment]
Pinging @dblock @adnapibar for help with approval and merge

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
Whatever the external behavior change here, it's not captured. I think this needs a test.

**Comment by shiv0408** [comment]
Updated the linked issue with better reproduction steps.

**Comment by shiv0408** [comment]
Earlier when `CircuitBreakingException` was thrown if compilation limit exceeded, then new `GeneralScriptException` was thrown with `CircuitBreakingException` as cause. But then status of call was return 500. Here, I made `GeneralScriptException` an implementation of `OpenSearchWrapperException` and now status of `GeneralScriptException` is same as that of `CircuitBreakingException` because it is now able to unwrap the exception and find root cause.

@dblock do you want me to create a unit test to check this behaviour change?

**Comment by dblock** [comment]
> @dblock do you want me to create a unit test to check this behaviour change?

Yes, a test that shows that the response is now a 429, instead of a 500.

**Comment by shiv0408** [comment]
@Bukhtawar @dblock created a test to check the status. Please review the changes. Any feedback is welcome 😄 .

**Comment by dblock** [comment]
> @Bukhtawar @dblock created a test to check the status. Please review the changes. Any feedback is welcome 😄 .

The unit test is great, it happens at the lowest compilation level, keep it!

Because the original issue and the repro is at REST level, try also adding a REST test? One that makes an HTTP request, and gets back a 429 whereas before this fix it would cause a 500?

**Comment by shiv0408** [comment]
> Because the original issue and the repro is at REST level, try also adding a REST test? One that makes an HTTP request, and gets back a 429 whereas before this fix it would cause a 500?

I manually tested code by running the commands. Is the there any example in the codebase to run automated REST test?

**Comment by adnapibar** [comment]
start gradle check

**Comment by shiv0408** [comment]
@dblock Can you please go through the integTest I created?

**Comment by dblock** [comment]
start gradle check

**Review by dblock — APPROVED** [review]

**Comment by shiv0408** [comment]
Opened a new [issue](https://github.com/opensearch-project/OpenSearch/issues/1297) for unrelated test failures. @dblock Can please `start gradle check` again?

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
start gradle check

**Review by dblock — APPROVED** [review]
