### PR TITLE
Fix flaky test testDropPrimaryDuringReplication.

### LINKED ISSUE #8059: [BUG] org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testDropPrimaryDuringReplication is flaky
**Describe the bug**
`org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testDropPrimaryDuringReplication` is flaky

https://build.ci.opensearch.org/job/gradle-check/17543/testReport/junit/org.opensearch.remotestore/SegmentReplicationUsingRemoteStoreIT/testDropPrimaryDuringReplication/

https://github.com/opensearch-project/OpenSearch/pull/8057#issuecomment-1590873556

**Assertion Failure**
```
java.lang.AssertionError: Expected search hits on node: node_t3 to be at least 111 but was: 110
	at __randomizedtesting.SeedInfo.seed([5E122859418B05B6:F3568B11F61BBC1C]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.lambda$waitForSearchableDocs$0(SegmentReplicationBaseIT.java:122)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1084)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:117)
	at org.opensearch.indices.replication.SegmentReplicationBaseIT.waitForSearchableDocs(SegmentReplicationBaseIT.java:112)
	at org.opensearch.indices.replication.SegmentReplicationIT.testDropPrimaryDuringReplication(SegmentReplicationIT.java:739)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testDropPrimaryDuringReplication" -Dtests.seed=5E122859418B05B6 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CO -Dtests.timezone=Asia/Bishkek -Druntime.java=20
```

### PR DESCRIPTION
**Pull request by mch2**
### Description
This change fixes flaky test testDropPrimaryDuringReplication.  This test would hit an edge case where after an updateSegments call on NRTReplicationReaderManager the reader is not actually refreshed because of another concurrent refresh call. Fixes by using a blocking refresh during updateSegments to ensure a refresh has happened.  This also removes unnecessary synchronization on the updateSegments method.  This is to avoid a deadlock case where the concurrent refresh picks up the new segments but is unable to acquire the object monitor to refresh internally in ReferenceManager.swapReference.

### Related Issues
resolves #8059 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mch2** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/20268/
> * **CommitID:** [5399335](https://github.com/opensearch-project/OpenSearch/commit/53993356d4160fad2f7b9d748c9ddca93598ddd0)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

https://github.com/opensearch-project/OpenSearch/issues/7643

File: server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java [hunk 1]
```diff
@@ -98,12 +98,12 @@ protected OpenSearchDirectoryReader refreshIfNeeded(OpenSearchDirectoryReader re
      * @param infos {@link SegmentInfos} infos
      * @throws IOException - When Refresh fails with an IOException.
      */
-    public synchronized void updateSegments(SegmentInfos infos) throws IOException {
+    public void updateSegments(SegmentInfos infos) throws IOException {
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java:101]: Thanks @mch2 for this quick fix. I have couple of questions. 
1. Why do we want the guarantee that update thread performs a refresh. I assume the refresh thread would be doing the same ?
2. How do we know the issue is fixed with your change ?

File: server/src/test/java/org/opensearch/index/engine/NRTReplicationReaderManagerTests.java [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+            readerManager.updateSegments(infos_2);
+            assertEquals(infos_2, readerManager.getSegmentInfos());
+            try (final OpenSearchDirectoryReader acquire = readerManager.acquire()) {
+                final StandardDirectoryReader standardReader = NRTReplicationReaderManager.unwrapStandardReader(acquire);
+                assertEquals(infos_2, standardReader.getSegmentInfos());
+            }
+        }
+    }
+
+    public void testUpdateSegmentsWhileRefreshing() throws IOException, InterruptedException {
```
Comment (dreamer-89) [inline server/src/test/java/org/opensearch/index/engine/NRTReplicationReaderManagerTests.java:50]: What error scenario does this test represent that gets resolved with this PR ?

File: server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java (hunk 1 above)
Comment (mch2) [reply server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java:101]: 1. The refresh lock could still be held by a different thread after it has returned null (no refresh )from refreshIfNeeded.  So we need to ensure a refresh has executed if the update thread does not immediately get the lock.
2. I've added a unit test that reproduces this scenario, it is fixed with the update.

File: server/src/test/java/org/opensearch/index/engine/NRTReplicationReaderManagerTests.java (hunk 2 above)
Comment (mch2) [reply server/src/test/java/org/opensearch/index/engine/NRTReplicationReaderManagerTests.java:50]: Similar to other comment - another thread holds the refresh lock while updateSegments is executing.

File: server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java (hunk 1 above)
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java:101]: Thanks @mch2 for the prompt response. :)

**Review by dreamer-89 — APPROVED** [review]
