### PR TITLE
Optimize NodeIndicesStats output behind flag

### LINKED ISSUE #13340: [BUG] Level aggregations for node stats API should be processed on data nodes
### Describe the bug

While reviewing #13237, I noticed that the node stats API does not pass the value of `level` parameter from coordinator to data node. Taking example of indices stats, that is inefficient due to 2 reasons:

1. The data/coordinator nodes are serializing/deserializing all index shards information while that is not generally needed
2. The coordinator node alone is responsible for aggregating the information from all the nodes, which can increase the overall latency of this operation

### Related component

Other

### To Reproduce

The [writeTo](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/NodeIndicesStats.java#L196) method is serializing the most granular information for transport layer and the [filtering is happening on the rest layer](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/NodeIndicesStats.java#L212)

### Expected behavior

The data nodes should return only the information used for preparing the client response

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu-S**
### Description:

As of today the APIs which fetch Node Stats with indices stats currently returns all shard statistics regardless of the requested level (node, level, or indices) to the coordinator node (node where-in or from which the rest request was created). This unnecessary iteration on the coordinator node leads to overhead and potential health issues. Furthermore,  the coordinator node repeats index-level statistics calculation for each node response even when the requested level is indices. 

This pull request proposes optimizations to the NodeStats API to pre-compute and return only the necessary information to generate the response. The APIs would now perform pre-computation of shard or index-level statistics on remote nodes (individual nodes which respond to the coordinator node) based on the level parameter in the REST request - `nodes`, `indices` or `shards`.  Only for level = `shards` does the response contains the shard level stats.

The optimisation hides behind a flag transport level flag `optimizeNodeIndicesStatsOnLevel` part of CommonStatsFlag. This is enabled in RestNodeStatsAction as well as RestNodeAction API calls as we do not require it during these code paths.

Pre-computation on remote nodes minimizes data transfer and processing on the coordinator node, leading to significant performance gains, especially in large clusters. Reduced load on the coordinator node contributes to a healthier state by minimizing GC pauses and CPU spikes.

Testing:

Extensive testing with a 20k shards cluster has validated the effectiveness of these optimizations.
| Stats | Without Optimisation | With Optimisation |
| -- | -- | -- |
| Average | 0.857280048 | 0.4961762  |
| P90 |  1.1514673 |  0.7631599  |
| Max | 1.78542 | 1.423496  |
| Min | 0.444184 | 0.212655 |

### Related Issues
Resolves #13340 

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/indices/IndicesService.java [hunk 1]
```diff
@@ -622,7 +635,9 @@ public NodeIndicesStats stats(CommonStatsFlags flags) {
                     break;
             }
         }
-
+        if (optimizedNodesStatsEnabled) {
+            return new NodeIndicesStats(commonStats, statsByShard(this, flags), searchRequestStats, flags.getLevels());
```
Comment (vikasvb90) [inline server/src/main/java/org/opensearch/indices/IndicesService.java:639]: On a quick read of your PR, it looks like the optimization you are referring to is to compute stats on the respective remote nodes instead of doing it in coordinator node which essentially distributes the compute. If this is correct then and if as per your benchmarks it has helped then it is certainly a good optimization. I have few questions though :
1. Can you please tell me how the new `statsByIndex` is being used? 
I can see that it is a new structure being passed to coordinator but I am not sure how it is helping in lesser compute. 
2. Initial read of the overview gave a hint that you are trying to change the default REST api but that is not the case right? It isn't the API but the data passed by transport actions. Your intention is to filter it out on respective nodes instead of passing the whole bunch to coordinator. If this is true then can you tell me how exactly you are achieving this? Is there some code still pending to be pushed in this PR?

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 2]
```diff
@@ -112,6 +113,57 @@ public NodeIndicesStats(CommonStats oldStats, Map<Index, List<IndexShardStats>>
...
+                }
+            }
+        }
+
+        if (this.stats.search != null) {
+            this.stats.search.setSearchRequestStats(searchRequestStats);
+        }
+
+        if (levels != null) {
+            if (Arrays.stream(levels).anyMatch(NodeIndicesStats.levels.indices::equals)) {
```
Comment (vikasvb90) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:137]: Can you switch to a switch statement instead as firstly streams are compute and memory expensive and secondly it would be cleaner.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 3]
```diff
@@ -276,6 +351,14 @@ public List<IndexShardStats> getShardStats(Index index) {
         }
     }
 
+    public CommonStats getIndexStats(Index index) {
```
Comment (vikasvb90) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:354]: Can you please rewrite this properly? Also, do we really need it here if it is only used in tests? I think you can a new class with extend `NodeIndicesStats`.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 4]
```diff
@@ -284,4 +367,28 @@ public List<IndexShardStats> getShardStats(Index index) {
     static final class Fields {
         static final String INDICES = "indices";
     }
+
+    /**
+     * Levels for the NodeIndicesStats
+     */
+    public enum levels {
```
Comment (vikasvb90) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:374]: Please follow the right language naming conventions.

File: server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java [hunk 5]
```diff
@@ -243,6 +250,53 @@ public void testNodeIndicesStatsDocStatusStatsCreateDeleteUpdate() {
         }
     }
 
+    public void testNodeIndicesStatsResponseOptimised() {
```
Comment (vikasvb90) [inline server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java:253]: Can you also add some mixed cluster tests to test the compatibility between different versions?

File: server/src/main/java/org/opensearch/indices/IndicesService.java (hunk 1 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/IndicesService.java:627]: Hey @vikasvb90 thanks for taking a look at the PR. 
1. In the current approach, we compute Index level stats if level is passed from the rest layer as `indices`. This computation of IndexStats is done on the coordinator node instead of the data node from where the stats are coming in. By introducing the statsByIndex in the class, I am not just making sure that if the level is `indices`, we are still pre-computing the Index Stats.
2. I did some rework on the default behavior - that was indeed my original intention but since we do not want a breaking change in 2.x, I am have introduced a transport level flag which can be enabled for utilising this feature instead. Did not publish this PR as it was still in the discussion stage.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 4 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:379]: Sure Vikas, will fix these before raising the PR. 
Thanks

**Comment by Pranshu-S** [comment]
```
[Test Result](https://build.ci.opensearch.org/job/gradle-check/42419/testReport/) (3 failures / -5)
[org.opensearch.discovery.ClusterDisruptionIT.classMethod](https://build.ci.opensearch.org/job/gradle-check/42419/testReport/junit/org.opensearch.discovery/ClusterDisruptionIT/classMethod/)
[org.opensearch.index.ShardIndexingPressureSettingsIT.testShardIndexingPressureLastSuccessfulSettingsUpdate](https://build.ci.opensearch.org/job/gradle-check/42419/testReport/junit/org.opensearch.index/ShardIndexingPressureSettingsIT/testShardIndexingPressureLastSuccessfulSettingsUpdate/)
[org.opensearch.indices.replication.SegmentReplicationIT.testReplicaAlreadyAtCheckpoint](https://build.ci.opensearch.org/job/gradle-check/42419/testReport/junit/org.opensearch.indices.replication/SegmentReplicationIT/testReplicaAlreadyAtCheckpoint/)
```

For [org.opensearch.discovery.ClusterDisruptionIT.classMethod](https://build.ci.opensearch.org/job/gradle-check/42419/testReport/junit/org.opensearch.discovery/ClusterDisruptionIT/classMethod/)

```
java.lang.AssertionError: SpanData validation failed for validator org.opensearch.test.telemetry.tracing.validators.AllSpansAreEndedProperly
MockSpanData{spanID='aa1534630900e459', parentSpanID='f8c436a5e84c915f', traceID='d7fd33dd4c374128', spanName='dispatchedShardOperationOnPrimary', startEpochNanos=2792950755631, endEpochNanos=0, hasEnded=false, attributes={index=restart_while_indexing, refresh_policy=false, thread.name=opensearch[node_t1][write][T#1], bulk_request_items=1, shard_id=0, node_id=uRqO2n91TTCp5ocLhE5MQA}, stackTrace=null}
```

Similar to failures in Flaky Test Issue - #14308 

--- 

For [org.opensearch.index.ShardIndexingPressureSettingsIT.testShardIndexingPressureLastSuccessfulSettingsUpdate](https://build.ci.opensearch.org/job/gradle-check/42419/testReport/junit/org.opensearch.index/ShardIndexingPressureSettingsIT/testShardIndexingPressureLastSuccessfulSettingsUpdate/)

```
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.opensearch.index.ShardIndexingPressureSettingsIT.lambda$waitForTwoOutstandingRequests$13(ShardIndexingPressureSettingsIT.java:939)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1128)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1101)
	at org.opensearch.index.ShardIndexingPressureSettingsIT.waitForTwoOutstandingRequests(ShardIndexingPressureSettingsIT.java:938)
	at 
```
Similar failures in Flaky Test Issue - #14331 

---

For [org.opensearch.index.ShardIndexingPressureSettingsIT.testShardIndexingPressureLastSuccessfulSettingsUpdate](https://build.ci.opensearch.org/job/gradle-check/42419/testReport/junit/org.opensearch.index/ShardIndexingPressureSettingsIT/testShardIndexingPressureLastSuccessfulSettingsUpdate/)
Flaky Test - #14328

**Comment by Pranshu-S** [comment]
> ❌ Gradle check result for [8416ec8](https://github.com/opensearch-project/OpenSearch/commit/8416ec8d70100fb1f2ab340d1973a9f7bb520fee): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/42693/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[Test Result](https://build.ci.opensearch.org/job/gradle-check/42693/testReport/) (1 failure / +1)
[org.opensearch.action.admin.indices.create.RemoteCloneIndexIT.testCreateCloneIndexLowPriorityRateLimit](https://build.ci.opensearch.org/job/gradle-check/42693/testReport/junit/org.opensearch.action.admin.indices.create/RemoteCloneIndexIT/testCreateCloneIndexLowPriorityRateLimit/)


Flaky - https://github.com/opensearch-project/OpenSearch/issues/14292

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 6]
```diff
@@ -74,23 +76,22 @@
...
 public class NodeIndicesStats implements Writeable, ToXContentFragment {
-    private CommonStats stats;
-    private Map<Index, List<IndexShardStats>> statsByShard;
+    protected CommonStats stats;
+    protected Map<Index, CommonStats> statsByIndex;
+    protected Map<Index, List<IndexShardStats>> statsByShard;
 
     public NodeIndicesStats(StreamInput in) throws IOException {
         stats = new CommonStats(in);
+        if (in.getVersion().onOrAfter(Version.V_3_0_0)) {
```
Comment (Pranshu-S) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:85]: By default, we only send and receive `Map<Index, List<IndexShardStats>> statsByShard` even when the level passed on the rest layer may be `indices`. This optimisation we will be sending and receiving `Map<Index, CommonStats> statsByIndex` which is `CommonStats` aggregated on a per Index on a Node. 

This is an optimisation as this was earlier done on the coordinator node side [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/NodeIndicesStats.java#L226). This computation was earlier done by the coordinator node right before building the XContent(JSON)

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 7]
```diff
@@ -74,23 +76,22 @@
...
-            for (int i = 0; i < entries; i++) {
-                Index index = new Index(in);
-                int indexShardListSize = in.readVInt();
-                List<IndexShardStats> indexShardStats = new ArrayList<>(indexShardListSize);
-                for (int j = 0; j < indexShardListSize; j++) {
-                    indexShardStats.add(new IndexShardStats(in));
-                }
-                statsByShard.put(index, indexShardStats);
-            }
+            readStatsByShards(in);
```
Comment (Pranshu-S) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:94]: `readStatsByShards()` is just reading the same statsByShard as it does normally in other cases and previous versions. Made another function for improved code readability and simplicity.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 8]
```diff
@@ -112,6 +113,63 @@ public NodeIndicesStats(CommonStats oldStats, Map<Index, List<IndexShardStats>>
         }
     }
 
+    public NodeIndicesStats(
```
Comment (Pranshu-S) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:116]: Created another constructor as `NodeIndicesStats` is a [Public API](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/NodeIndicesStats.java#L75). 

The whole point of this new constructor is to:
- Firstly, build the `CommonStats` as it would do in previous versions as well (This is the node level aggregations of the stats)
- Then depending on the level passed, we decide to either create `statsByIndex` (Index level aggregations) or just return `statsByShards` as we would do normally.

The ser/de accordingly handles the `statsByIndex` and `statsByShards` if they are null or not.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 9]
```diff
@@ -112,6 +113,63 @@ public NodeIndicesStats(CommonStats oldStats, Map<Index, List<IndexShardStats>>
...
+                }
+            }
+        }
+
+        if (this.stats.search != null) {
+            this.stats.search.setSearchRequestStats(searchRequestStats);
+        }
+
+        if (levels != null) {
+            Arrays.stream(levels).anyMatch(level -> {
```
Comment (Pranshu-S) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:137]: Making this `anyMatch` since we by default only accept 1 level. We cannot give both `indices` and `shards` at the same time.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 10]
```diff
@@ -195,7 +253,31 @@ public RecoveryStats getRecoveryStats() {
     @Override
     public void writeTo(StreamOutput out) throws IOException {
         stats.writeTo(out);
+
+        if (out.getVersion().onOrAfter(Version.V_3_0_0)) {
```
Comment (Pranshu-S) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:257]: As explained in StreamInput, this is the new behaviour introduced as an optimisation.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 11]
```diff
@@ -210,39 +292,56 @@ public void writeTo(StreamOutput out) throws IOException {
...
 
         // "node" level
         builder.startObject(Fields.INDICES);
         stats.toXContent(builder, params);
 
-        if ("indices".equals(level)) {
-            Map<Index, CommonStats> indexStats = createStatsByIndex();
+        if (Fields.INDICES.equals(level)) {
+            if (statsByIndex == null && statsByShard != null) {
+                statsByIndex = createStatsByIndex(statsByShard);
```
Comment (Pranshu-S) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:320]: Added this because since we anyways have `statsByShards`, we can still generate the `statsByIndices`. This is ensure that the behaviour does not break if the response is coming from an older version node which does not support sending `statsByIndex`. In such cases, we just go back to the original behaviour and generate `statsByIndex` right before the building the `ToXContent`.

File: server/src/test/java/org/opensearch/action/RestStatsActionTests.java [hunk 12]
```diff
@@ -0,0 +1,48 @@
...
+public class RestStatsActionTests extends OpenSearchTestCase {
+    private final TestThreadPool threadPool = new TestThreadPool(RestStatsActionTests.class.getName());
+    private final NodeClient client = new NodeClient(Settings.EMPTY, threadPool);
+
+    @After
+    public void terminateThreadPool() {
+        terminate(threadPool);
+    }
+
+    public void testClusterStatsActionPrepareRequestNoError() throws IOException {
```
Comment (Pranshu-S) [inline server/src/test/java/org/opensearch/action/RestStatsActionTests.java:34]: Just to test the wording of `prepareRequest` for RestActions and to assert no failures. Majorly for code coverage.

File: server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java [hunk 13]
```diff
@@ -124,6 +128,9 @@ public void writeTo(StreamOutput out) throws IOException {
             out.writeEnumSet(includeCaches);
             out.writeStringArrayNullable(levels);
         }
+        if (out.getVersion().onOrAfter(Version.V_3_0_0)) {
```
Comment (Pranshu-S) [inline server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java:131]: Since nodes with older versions will never enter this code path, we will send them the default RestNodesStatsRequest without any additional boolean. This will therefore not break during version upgrade.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 14]
```diff
@@ -112,6 +113,63 @@ public NodeIndicesStats(CommonStats oldStats, Map<Index, List<IndexShardStats>>
...
+    ) {
+        // make a total common stats from old ones and current ones
+        this.stats = oldStats;
+        for (List<IndexShardStats> shardStatsList : statsByShard.values()) {
+            for (IndexShardStats indexShardStats : shardStatsList) {
+                for (ShardStats shardStats : indexShardStats.getShards()) {
+                    stats.add(shardStats.getStats());
+                }
+            }
+        }
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:130]: If we are computing `statsByIndex` - can we compute in same loop ?

File: server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java [hunk 15]
```diff
@@ -127,6 +127,16 @@ public NodesStatsRequest indices(boolean indices) {
         return this;
     }
 
+    /**
+     * Use Aggregated Response based on level passed
+     */
+    public NodesStatsRequest aggregateResponsesOnLevel(boolean aggregateNodeResponsesOnLevel) {
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java:133]: Makes sense, will modify. 
Thanks!

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:137]: I have done this Rajiv - by default when no param or an unknown param is passed, we return only the aggregated stats. See [test - testNodeIndicesStatsWithAggregationOnNodes](https://github.com/opensearch-project/OpenSearch/pull/14454/files#diff-dea6917e2e6b0fe4c9107bde94f38e373d49627d216dd6a29e5a9abc4de745c1R424-R436)

File: server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java [hunk 16]
```diff
@@ -139,6 +139,7 @@ public void processResponse(final NodesInfoResponse nodesInfoResponse) {
                         nodesStatsRequest.timeout(request.param("timeout"));
                         nodesStatsRequest.clear()
                             .indices(true)
+                            .aggregateResponsesOnLevel(true)
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java:142]: Not having any param passed will only result in AggregatedStats and nothing else.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 17]
```diff
@@ -74,23 +76,22 @@
  */
 @PublicApi(since = "1.0.0")
 public class NodeIndicesStats implements Writeable, ToXContentFragment {
-    private CommonStats stats;
-    private Map<Index, List<IndexShardStats>> statsByShard;
+    protected CommonStats stats;
+    protected Map<Index, CommonStats> statsByIndex;
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:80]: We could but my concern was more in the line of version upgrade scenarios, when the response does not contain this aggregationLevel as nodes with prior version will not contain it.

[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:80]: This is why I am resolving this information dynamically as the stream input is coming in. The logic is as follows:

1. If the response is coming from a previous version node, it will only have statsByShards and so we just backfill it and accordingly generate the XContent later.
2. If the response is coming from a current version node or later, it may contain statsByIndex. In this case, we check for it and act accordingly when generating the XContent.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 18]
```diff
@@ -281,7 +380,10 @@ public List<IndexShardStats> getShardStats(Index index) {
      *
      * @opensearch.internal
      */
-    static final class Fields {
-        static final String INDICES = "indices";
+    public static final class Fields {
+        public static final String INDICES = "indices";
+        public static final String SHARDS = "shards";
+        public static final String NODE = "node";
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:386]: Yes, will make this an ENUM

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 14 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:130]: Makes sense, will update.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 19]
```diff
@@ -281,7 +390,24 @@ public List<IndexShardStats> getShardStats(Index index) {
      *
      * @opensearch.internal
      */
-    static final class Fields {
-        static final String INDICES = "indices";
+    @PublicApi(since = "2.0.0")
```
Comment (Pranshu-S) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:393]: Had to add `@PublicApi(since = "2.0.0")` for the introduced enum as per the check conditions. Please do let me know if this may cause issues or if there are any concerns over it.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 14 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:132]: Looking back, I noticed that while computing statsByIndex, we are iterating over each key in the map and accordingly making the Index Level CommonStats entry. However for node level CommonStats, we are simply going over each value in the hash-map irrespective of the key. 

I think keeping the computation on the same loop will just add more complexity as well as computational effort when level is not provided. Kept it separate itself for now

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 20]
```diff
@@ -112,6 +115,71 @@ public NodeIndicesStats(CommonStats oldStats, Map<Index, List<IndexShardStats>>
...
+                    this.statsByIndex = createStatsByIndex(statsByShard);
+                    break;
+                case SHARDS:
+                    this.statsByShard = statsByShard;
+                    break;
+            }
+        }
+    }
+
+    public static Fields getFirstAcceptedLevel(String[] levels) {
```
Comment (Pranshu-S) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:151]: Gets the first level which is accepted by the NodeIndicesStats for aggregation, we ignore if any of such level is not present and return null or multiple levels present.

**Comment by Pranshu-S** [comment]
> ❕ Gradle check result for [8029c78](https://github.com/opensearch-project/OpenSearch/commit/8029c783f109ca5f61cd4636ced789d91d709195): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/42914/)
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

[Test Result](https://build.ci.opensearch.org/job/gradle-check/42914/testReport/) (1 failure / ±0)
[org.opensearch.http.SearchRestCancellationIT.testAutomaticCancellationDuringFetchPhase](https://build.ci.opensearch.org/job/gradle-check/42914/testReport/junit/org.opensearch.http/SearchRestCancellationIT/testAutomaticCancellationDuringFetchPhase/)

https://github.com/opensearch-project/OpenSearch/issues/14311

**Comment by Pranshu-S** [comment]
> ❕ Gradle check result for [1128006](https://github.com/opensearch-project/OpenSearch/commit/11280062476e1f672fd03ad9c37c26871993040e): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/42919/)
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

[Test Result](https://build.ci.opensearch.org/job/gradle-check/42919/testReport/) (1 failure / -1)
[org.opensearch.cluster.MinimumClusterManagerNodesIT.testThreeNodesNoClusterManagerBlock](https://build.ci.opensearch.org/job/gradle-check/42919/testReport/junit/org.opensearch.cluster/MinimumClusterManagerNodesIT/testThreeNodesNoClusterManagerBlock/)

Flaky - https://github.com/opensearch-project/OpenSearch/issues/14289

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 21]
```diff
@@ -112,6 +119,83 @@ public NodeIndicesStats(CommonStats oldStats, Map<Index, List<IndexShardStats>>
...
+     * Passing the level information to the nodes allows us to aggregate the stats based on the level passed. This
+     * allows us to aggregate based on NodeLevel (default - if no level is passed) or Index level if `indices` level is
+     * passed and finally return the statsByShards map if `shards` level is passed. This allows us to reduce ser/de of
+     * stats and return only the information that is required while returning to the client.
+     */
+    public NodeIndicesStats(
+        CommonStats oldStats,
+        Map<Index, List<IndexShardStats>> statsByShard,
+        SearchRequestStats searchRequestStats,
+        String[] levels
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:132]: Can we move the level array validation to caller and accept only one level (`String level`) here ?

File: server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java [hunk 22]
```diff
@@ -273,4 +488,22 @@ private void updateExpectedDocStatusCounter(Exception e) {
         expectedDocStatusStats.inc(ExceptionsHelper.status(e));
     }
 
+    private enum MockFields {
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java:491]: Do we need MockFields ? Can we instead use `NodeIndicesStats.Fields` ?

File: server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java [hunk 23]
```diff
@@ -243,6 +259,205 @@ public void testNodeIndicesStatsDocStatusStatsCreateDeleteUpdate() {
...
+                    builder.endObject();
+
+                    xContentMap = xContentBuilderToMap(builder);
+                    indicesStatsMap = (LinkedHashMap) xContentMap.get(NodeIndicesStats.Fields.INDICES.getRestName());
+                    indicesStats = (LinkedHashMap) indicesStatsMap.get(NodeIndicesStats.Fields.INDICES.getRestName());
+                    shardStats = (LinkedHashMap) indicesStatsMap.get(NodeIndicesStats.Fields.SHARDS.getRestName());
+                    switch (testLevel) {
+                        case SHARDS:
+                        case INDICES:
+                            assertNull(shardStats);
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java:440]: Can we include deep verifications on the stats - if the aggregated value is as per the expectedStatus

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 24]
```diff
@@ -281,7 +406,24 @@ public List<IndexShardStats> getShardStats(Index index) {
      *
      * @opensearch.internal
      */
-    static final class Fields {
-        static final String INDICES = "indices";
+    @PublicApi(since = "2.0.0")
+    public enum Fields {
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:410]: Should we call them StatsLevel  ?

File: server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java [hunk 25]
```diff
@@ -1065,4 +1083,257 @@ private static RemoteTranslogTransferTracker.Stats getRandomRemoteTranslogTransf
     private OperationStats getPipelineStats(List<IngestStats.PipelineStat> pipelineStats, String id) {
         return pipelineStats.stream().filter(p1 -> p1.getPipelineId().equals(id)).findFirst().map(p2 -> p2.getStats()).orElse(null);
     }
+
+    public static class MockNodeIndicesStats extends NodeIndicesStats {
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java:1087]: Do we need Mock class ? Can we instead directly use NodeIndicesStats ?

File: server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java [hunk 26]
```diff
@@ -1065,4 +1083,257 @@ private static RemoteTranslogTransferTracker.Stats getRandomRemoteTranslogTransf
...
+        commonStats.docs = new DocsStats(numDocs, numDeletedDocs, 0);
+        commonStats.store = new StoreStats(100, 0L);
+        commonStats.indexing = new IndexingStats();
+
+        CommonStatsFlags commonStatsFlags = new CommonStatsFlags();
+        commonStatsFlags.clear();
+        commonStatsFlags.set(CommonStatsFlags.Flag.Docs, true);
+        commonStatsFlags.set(CommonStatsFlags.Flag.Store, true);
+        commonStatsFlags.set(CommonStatsFlags.Flag.Indexing, true);
+        commonStatsFlags.setAggregateNodeIndicesStatsResponsesOnLevel(true);
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java:1239]: Can we have a test which compares the toXContent of aggregate response with that of the non-aggregate one. Assert if the responses are identical.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 27]
```diff
@@ -112,6 +119,83 @@ public NodeIndicesStats(CommonStats oldStats, Map<Index, List<IndexShardStats>>
...
+     * @return Corresponding identified enum {@link Fields}
+     */
+    private static Fields getFirstAcceptedLevel(String[] levels) {
+        if (levels != null) {
+            Optional<Fields> level = Arrays.stream(levels)
+                .flatMap(passedLevel -> Arrays.stream(Fields.values()).filter(field -> field.getRestName().equals(passedLevel)))
+                .findFirst();
+            return level.orElse(null);
+        }
+        return null;
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java]: Got it. Will do.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 21 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:132]: We can add a validation to the caller to accept only 1 level but that is anyways done on the toXContent method - 
See - https://github.com/opensearch-project/OpenSearch/pull/14454/files#diff-b79bb7aee566fa9c63b9f972aaa2b26206e0717a7e7d831307c0794161ec64bfR326-R337

File: server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java (hunk 22 above)
Comment (Pranshu-S) [reply server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java]: I added additional unknown fields such as `null` and `unknown` to test the working. These are not needed in `NodeIndicesStats.Fields` and hence I introduced  `MockFields`.

File: server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java (hunk 25 above)
Comment (Pranshu-S) [reply server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java:1092]: I wanted to extract out `statsByIndex`  and `statsByShard` for my testing which is currently not provided as a public method in `NodeIndicesStats`. Instead of adding this to public in the main class, I made these variables protected and extracted it out by extending it.

File: server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java (hunk 23 above)
Comment (Pranshu-S) [reply server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java:440]: Added a test - `testNodeIndicesStatsWithAndWithoutAggregations` which calls the MockNodeIndicesStats with and without aggregations passed and compares the ToXContent. This is deep in the sense that it compares common stats for 
1.  CommonStatsFlags.Flag.Docs
2. CommonStatsFlags.Flag.Store,
3. CommonStatsFlags.Flag.Indexing,
4. CommonStatsFlags.Flag.Completion,
5. CommonStatsFlags.Flag.Flush,
6. CommonStatsFlags.Flag.FieldData,
7. CommonStatsFlags.Flag.QueryCache,
8. CommonStatsFlags.Flag.Segments

File: server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java (hunk 26 above)
Comment (Pranshu-S) [reply server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java]: Added the test - `testNodeIndicesStatsWithAndWithoutAggregations` on next revision

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 28]
```diff
@@ -210,39 +318,56 @@ public void writeTo(StreamOutput out) throws IOException {
...
+            }
+            builder.startObject(StatsLevel.INDICES.getRestName());
+            if (statsByIndex != null) {
+                for (Map.Entry<Index, CommonStats> entry : statsByIndex.entrySet()) {
+                    builder.startObject(entry.getKey().getName());
+                    entry.getValue().toXContent(builder, params);
+                    builder.endObject();
+                }
             }
             builder.endObject();
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:356]: If both are not assert - should we fail ?

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 29]
```diff
@@ -210,39 +318,56 @@ public void writeTo(StreamOutput out) throws IOException {
...
-            builder.startObject("shards");
-            for (Map.Entry<Index, List<IndexShardStats>> entry : statsByShard.entrySet()) {
-                builder.startArray(entry.getKey().getName());
-                for (IndexShardStats indexShardStats : entry.getValue()) {
-                    builder.startObject().startObject(String.valueOf(indexShardStats.getShardId().getId()));
-                    for (ShardStats shardStats : indexShardStats.getShards()) {
-                        shardStats.toXContent(builder, params);
+        } else if (StatsLevel.SHARDS.getRestName().equals(level)) {
+            builder.startObject(StatsLevel.SHARDS.getRestName());
+            if (statsByShard != null) {
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:359]: Again fail if this is not set in the response

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 30]
```diff
@@ -281,7 +406,24 @@ public List<IndexShardStats> getShardStats(Index index) {
...
+
+        StatsLevel(String restName) {
+            this.restName = restName;
+        }
+
+        public String getRestName() {
+            return restName;
+        }
+
+        public static List<String> acceptedValues() {
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:425]: seems to be unused

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 31]
```diff
@@ -112,6 +118,82 @@ public NodeIndicesStats(CommonStats oldStats, Map<Index, List<IndexShardStats>>
...
+    /**
+     * By default, the levels passed from the transport action will be a list of strings, since NodeIndicesStats can
+     * only aggregate on one level, we pick the first accepted level else we ignore if no known level is passed.
+     * @param levels - levels sent in the request.
+     * @return Corresponding identified enum {@link StatsLevel}
+     */
+    public static StatsLevel getAcceptedLevel(String[] levels) {
+        if (levels != null && levels.length > 0) {
+            Optional<StatsLevel> level = Arrays.stream(StatsLevel.values())
+                .filter(field -> field.getRestName().equals(levels[0]))
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:168]: Can you update javadoc comment as to why we are picking `levels[0]` and not failing the request if multiple levels are provided.

**Review by rajiv-kv — APPROVED** [review]
LGTM ! Thanks for making the changes.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 32]
```diff
@@ -210,29 +316,47 @@ public void writeTo(StreamOutput out) throws IOException {
...
+        final boolean isLevelValid = StatsLevel.NODE.getRestName().equalsIgnoreCase(level)
+            || StatsLevel.INDICES.getRestName().equalsIgnoreCase(level)
+            || StatsLevel.SHARDS.getRestName().equalsIgnoreCase(level);
         if (!isLevelValid) {
-            throw new IllegalArgumentException("level parameter must be one of [indices] or [node] or [shards] but was [" + level + "]");
+            throw new IllegalArgumentException(
+                "level parameter must be one of ["
+                    + StatsLevel.INDICES.getRestName()
+                    + "] or "
+                    + "["
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:328]: can we have this in 1 single line?

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 33]
```diff
@@ -210,29 +316,47 @@ public void writeTo(StreamOutput out) throws IOException {
...
+                    + StatsLevel.SHARDS.getRestName()
+                    + "] but was ["
+                    + level
+                    + "]"
+            );
         }
 
         // "node" level
-        builder.startObject(Fields.INDICES);
+        builder.startObject(StatsLevel.INDICES.getRestName());
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:339]: Any specific reason for changing this?

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 34]
```diff
@@ -251,7 +375,7 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
         return builder;
     }
 
-    private Map<Index, CommonStats> createStatsByIndex() {
+    private Map<Index, CommonStats> createStatsByIndex(Map<Index, List<IndexShardStats>> statsByShard) {
         Map<Index, CommonStats> statsMap = new HashMap<>();
         for (Map.Entry<Index, List<IndexShardStats>> entry : statsByShard.entrySet()) {
             if (!statsMap.containsKey(entry.getKey())) {
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:381]: `if (!statsMap.containsKey(entry.getKey())) {` check looks unnecessary.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 35]
```diff
@@ -210,29 +316,47 @@ public void writeTo(StreamOutput out) throws IOException {
...
-        builder.startObject(Fields.INDICES);
+        builder.startObject(StatsLevel.INDICES.getRestName());
         stats.toXContent(builder, params);
 
-        if ("indices".equals(level)) {
-            Map<Index, CommonStats> indexStats = createStatsByIndex();
-            builder.startObject(Fields.INDICES);
-            for (Map.Entry<Index, CommonStats> entry : indexStats.entrySet()) {
+        if (StatsLevel.INDICES.getRestName().equals(level)) {
+            assert statsByIndex != null || statsByShard != null : "Expected shard stats or index stats in response for generating ["
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:343]: Shouldn't this only have `assert statsByIndex != null`?

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 36]
```diff
@@ -281,7 +405,21 @@ public List<IndexShardStats> getShardStats(Index index) {
      *
      * @opensearch.internal
      */
-    static final class Fields {
-        static final String INDICES = "indices";
+    @PublicApi(since = "2.0.0")
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:408]: The version value is incorrect.

**Review by ashking94 — COMMENTED** [review]
LGTM overall, left some minor comments.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 37]
```diff
@@ -74,26 +77,29 @@
...
 public class NodeIndicesStats implements Writeable, ToXContentFragment {
-    private CommonStats stats;
-    private Map<Index, List<IndexShardStats>> statsByShard;
+    protected CommonStats stats;
+    protected Map<Index, CommonStats> statsByIndex;
+    protected Map<Index, List<IndexShardStats>> statsByShard;
 
     public NodeIndicesStats(StreamInput in) throws IOException {
         stats = new CommonStats(in);
+        if (in.getVersion().onOrAfter(Version.V_3_0_0)) {
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:86]: Yes. All the version checks are updated to `V_3_0_0` - [1](https://github.com/opensearch-project/OpenSearch/pull/14454/files#diff-84bd2b34e3d5da0f853a5581a4cc79ad262ce036bc5fd4b94ba42e459a1e272aR104), [2](https://github.com/opensearch-project/OpenSearch/pull/14454/files#diff-84bd2b34e3d5da0f853a5581a4cc79ad262ce036bc5fd4b94ba42e459a1e272aR131), [3](https://github.com/opensearch-project/OpenSearch/pull/14454/files#diff-b79bb7aee566fa9c63b9f972aaa2b26206e0717a7e7d831307c0794161ec64bfR86), [4](https://github.com/opensearch-project/OpenSearch/pull/14454/files#diff-b79bb7aee566fa9c63b9f972aaa2b26206e0717a7e7d831307c0794161ec64bfR281)

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 33 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:339]: Nothing in specific. StatsLevel is a more concise representation of the usecase.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 34 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:381]: Don't quite understand what you are referring to. A node can contain multiple indices and for every shard, we first check the index and if that index does not exists, we create a new object and insert else we add it to the existing object.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 35 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:343]: Not really. For a mixed cluster case, a node with pre-2.17 version will not return statsByIndex, in those cases we will utilise statsByShard to generate the index level aggregations.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 36 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java]: Updated in next revision. [Ref](https://github.com/opensearch-project/OpenSearch/pull/14454/files#diff-b79bb7aee566fa9c63b9f972aaa2b26206e0717a7e7d831307c0794161ec64bfR413)

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 38]
```diff
@@ -112,6 +118,82 @@ public NodeIndicesStats(CommonStats oldStats, Map<Index, List<IndexShardStats>>
...
+     * By default, the levels passed from the transport action will be a list of strings, since NodeIndicesStats can
+     * only aggregate on one level, we pick the first accepted level else we ignore if no known level is passed.
+     * @param levels - levels sent in the request.
+     * @return Corresponding identified enum {@link StatsLevel}
+     */
+    public static StatsLevel getAcceptedLevel(String[] levels) {
+        if (levels != null && levels.length > 0) {
+            Optional<StatsLevel> level = Arrays.stream(StatsLevel.values())
+                .filter(field -> field.getRestName().equals(levels[0]))
+                .findFirst();
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:171]: Added the reasoning in the java docs. [Ref](https://github.com/opensearch-project/OpenSearch/pull/14454/files#diff-b79bb7aee566fa9c63b9f972aaa2b26206e0717a7e7d831307c0794161ec64bfR162-R163)

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 31 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:170]: Addressed in next revision.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 39]
```diff
@@ -74,26 +77,27 @@
...
-            statsByShard = new HashMap<>();
-            for (int i = 0; i < entries; i++) {
-                Index index = new Index(in);
-                int indexShardListSize = in.readVInt();
-                List<IndexShardStats> indexShardStats = new ArrayList<>(indexShardListSize);
-                for (int j = 0; j < indexShardListSize; j++) {
-                    indexShardStats.add(new IndexShardStats(in));
-                }
-                statsByShard.put(index, indexShardStats);
+        if (in.getVersion().onOrAfter(Version.V_3_0_0)) {
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:86]: can we make all the newly added references to `Version.V_3_0_0` as `Version.CURRENT`? This will help in backports.

**Review by ashking94 — APPROVED** [review]
LGTM

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 39 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:86]: I will be raising separate PRs for 2.x and main branch after this PR is merged.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java [hunk 40]
```diff
@@ -281,7 +410,21 @@ public List<IndexShardStats> getShardStats(Index index) {
      *
      * @opensearch.internal
      */
-    static final class Fields {
-        static final String INDICES = "indices";
+    @PublicApi(since = "3.0.0")
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:413]: does it need to be Public?

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 39 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:86]: Why do you need separate PRs. Have this as CURRENT, CURRENT In main will point to 3.0 and 2.17 in 2.x. The backport of this PR will lead to successful builds at both places. Then create a PR on main moving the version to 2.17 branch and backport the same to 2.x. This is how typically I have done version related changes to avoid any build failure.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 40 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java:413]: Enums I think are required to be defined @PublicApi. The pre-commit checks were failing without it.

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 39 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java]: I see. This is efficient, have raised a commit with `Version.CURRENT`

File: server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java [hunk 41]
```diff
@@ -100,6 +101,9 @@ public CommonStatsFlags(StreamInput in) throws IOException {
             includeCaches = in.readEnumSet(CacheType.class);
             levels = in.readStringArray();
         }
+        if (in.getVersion().onOrAfter(Version.CURRENT)) {
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java:104]: why did you change version check to Version.CURRENT, it should 3.0.0

File: server/src/main/java/org/opensearch/indices/NodeIndicesStats.java (hunk 39 above)
Comment (shwetathareja) [reply server/src/main/java/org/opensearch/indices/NodeIndicesStats.java]: using Version.CURRENT sounds risky to me in case you miss updating. I would rather prefer failing the build then silent issues.

File: server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java (hunk 41 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java]: Reverted

File: server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java [hunk 42]
```diff
@@ -67,6 +67,7 @@ public class CommonStatsFlags implements Writeable, Cloneable {
     // Used for metric CACHE_STATS, to determine which caches to report stats for
     private EnumSet<CacheType> includeCaches = EnumSet.noneOf(CacheType.class);
     private String[] levels = new String[0];
+    private boolean aggregateNodeIndicesStatsResponsesOnLevel = false;
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java]: I think `aggregateNodeIndicesStatsResponsesOnLevel` is a better representation on the variable name. This is because aggregations on Tiered caching is also based on level and this might become misleading if we generalise it.
