### PR TITLE
Removing unused fetch sub phase processor initialization during fetch…

### LINKED ISSUE #12502: [BUG] Unused fetch sub phase processors initialized during fetch phase
### Describe the bug

Opensearch initializes sub processors even if are not getting used during the fetch phase. Can be prevented by validating if size of fields is greater than zero in addition to it being non-null. Take below snippet from `InnerHitsPhase` class:

```
public FetchSubPhaseProcessor getProcessor(FetchContext searchContext) {
        if (searchContext.innerHits() == null) {
            return null;
        }
```

This should not get initialized if the innerHits count is 0

### Related component

Search:Performance

### To Reproduce

1. Add data http_logs into Opensearch
2. Run below query:
```
curl -XGET "http://localhost:9200/logs-241998/_search?pretty" -H 'Content-Type: application/json' -d'
{"size": 1000,
  "query": {
    "match_all": {}
  },"docvalue_fields":["clientip"],
 "sort": [{"size":"asc"}]
}'
```
3. Attach debugger to above code reference

### Expected behavior

Unnecessary initialization of fetch sub phase processor should be skipped

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by jainankitk**
… phase execution

### Description
Prevent initialization of unused fetch sub phase processor initialization during fetch phase execution

### Related Issues
Resolves #12502 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- ~[ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/search/fetch/subphase/InnerHitsPhaseTests.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
+/*
+ * SPDX-License-Identifier: Apache-2.0
+ *
+ * The OpenSearch Contributors require contributions made to
+ * this file be licensed under the Apache-2.0 license or a
+ * compatible open source license.
+ */
+
+/*
+ * Licensed to Elasticsearch under one or more contributor
```
Comment (andrross) [inline server/src/test/java/org/opensearch/search/fetch/subphase/InnerHitsPhaseTests.java:10]: Assuming this is all new content then you don't need this header

Comment (jainankitk) [reply server/src/test/java/org/opensearch/search/fetch/subphase/InnerHitsPhaseTests.java:10]: Will remove

**Comment by jainankitk** [comment]
@andrross - Can you take another look?

File: server/src/main/java/org/opensearch/search/internal/SearchContext.java [hunk 2]
```diff
@@ -188,6 +188,10 @@ public final void close() {
 
     public abstract void highlight(SearchHighlightContext highlight);
 
+    public boolean hasInnerHits() {
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/internal/SearchContext.java:191]: @jainankitk I don't understand what this pull request is doing to be fair (apologies for that): to me, it replaces the `null` checks with `hasXxx` method (which conceptually is cleaner) but it does not remove any unused sub phase initialization logic (instead introduce weird dependency between  `hasInnerHits()`  and `innerHits()` methods, whichever is called first, which does not look right)

Comment (jainankitk) [reply server/src/main/java/org/opensearch/search/internal/SearchContext.java:191]: @reta - Thats a fair question, and I am glad you asked. During the node initialization, possible fetch sub phase handlers are registered [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/SearchModule.java#L1047) and during fetch phase execution, the fetch sub processors for the ones relevant to search request get initialized. While debugging code, I noticed that the scriptFields and innerHits subprocessors are always initialized irrespective of the search request. For example - below request does not have anything to do with either:

```
curl -XGET "http://localhost:9200/logs-241998/_search?pretty" -H 'Content-Type: application/json' -d'
{"size": 1000,
  "query": {
    "match_all": {}
  },"docvalue_fields":["clientip"],
 "sort": [{"size":"asc"}]
}'
```
Then, I noticed that implementation of `scriptFields()` and `innerHits()` always returns non-null values:

```
public InnerHitsContext innerHits() {
        if (innerHitsContext == null) {
            innerHitsContext = new InnerHitsContext();
        }
        return innerHitsContext;
    }
```

so existing checks were useless:

```
if (fetchContext.innerHits() == null) //It is always non-null!!
```

Hence, I went ahead and fixed the logic by introducing another `hasInnerHits()` method to not change anything else with original and regress elsewhere.

Comment (reta) [reply server/src/main/java/org/opensearch/search/internal/SearchContext.java:191]: Thanks @jainankitk , so why we need to initialize in first place if the code seems to deal with `null` properly?

```
public InnerHitsContext innerHits() {
        return innerHitsContext;
    }

```

Comment (jainankitk) [reply server/src/main/java/org/opensearch/search/internal/SearchContext.java:191]: Because all the other references of `innerHits()` & `scriptFields()` assume implicit initialization. This was the only place where the method was used for checking the initialization which is of course incorrect as output is guaranteed to be non-null. For example - below invocation assumed scriptFields is non-null:

```
for (ScriptFieldsContext.ScriptField field : scriptFields) {
            subSearchContext.scriptFields().add(field);
        }
```

Similarly, for innerHits:

```
if (innerHitBuilders.size() > 0) {
            for (Map.Entry<String, InnerHitContextBuilder> entry : innerHitBuilders.entrySet()) {
                try {
                    entry.getValue().build(context, context.innerHits());
                } catch (IOException e) {
                    throw new SearchException(shardTarget, "failed to build inner_hits", e);
                }
            }
        }
```

Comment (reta) [reply server/src/main/java/org/opensearch/search/internal/SearchContext.java:191]: Thanks @jainankitk , fair enough, so here the issue I have with this change:  calling `innerHits()` and `hasInnerHits()` != calling `hasInnerHits()` and `innerHits()`, this is for obvious reasons not a good design decision. I would suggest to explore the routes to:
a) let `innerHits()` return `Optional<InnerHitsContext>`
b) always initialize the `innerHitsContext`

Comment (jainankitk) [reply server/src/main/java/org/opensearch/search/internal/SearchContext.java:191]: Sorry I am not exactly clear about your concern here. We have similar `hasScriptFields` for `scriptFields` already, it was not getting used. Regarding the approaches, I am not completely sure what you're suggesting:

> always initialize the innerHitsContext

Why should we do that if innerHitsContext is not needed for many cases?

> let innerHits() return Optional<InnerHitsContext>

Since I am not sure how it will work, maybe you can take a quick first stab at it. Also, to make it consistent with other attributes like `scriptFields`, we need to change others as well. Does it make sense to make that change separately?

Comment (reta) [reply server/src/main/java/org/opensearch/search/internal/SearchContext.java:191]: @jainankitk you are very right :((( we sadly have this pattern all over the place, it is not worth addressing one place :(

File: server/src/main/java/org/opensearch/search/fetch/subphase/ScriptFieldsPhase.java [hunk 3]
```diff
@@ -54,7 +54,7 @@ public final class ScriptFieldsPhase implements FetchSubPhase {
 
     @Override
     public FetchSubPhaseProcessor getProcessor(FetchContext context) {
-        if (context.scriptFields() == null) {
+        if (!context.hasScriptFields()) {
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/fetch/subphase/ScriptFieldsPhase.java:57]: Super nit, `if (context.hasScriptFields() == false) {` - this is just the convention we are trying to stick to across codebase

Comment (jainankitk) [reply server/src/main/java/org/opensearch/search/fetch/subphase/ScriptFieldsPhase.java]: Done!

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@andrross mind please retaking a look ? thank you

**Review by andrross — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [2bd910e](https://github.com/opensearch-project/OpenSearch/commit/2bd910ef933e176cb8a6aaa88a4b2f418f4875c3): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/34794/)

https://github.com/opensearch-project/OpenSearch/issues/12593

**Comment by jainankitk** [comment]
> ❌ Gradle check result for [2bd910e](https://github.com/opensearch-project/OpenSearch/commit/2bd910ef933e176cb8a6aaa88a4b2f418f4875c3): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/34794/)

#12593

**Review by reta — APPROVED** [review]
