### PR TITLE
implicitly set replication type SEGMENT in remote store enabled cluster if nothing specified by user

### LINKED ISSUE #9249: [BUG] Index creation fails when index.replication.type is not mentioned while cluster setting cluster.remote_store.enabled is true
**Describe the bug**
As the title says, the index creation in a remote store enabled cluster fails when the `index.replication.type` is not mentioned. The index.replication.type index setting is implied to be `SEGMENT` when `cluster.remote_store.enabled` is set to true in `opensearch.yml` before the bootstrap.

Response when we try to create an index without specifying `index.replication.type` on a remote enabled cluster -
```
➜  opensearch curl -X PUT "localhost:9200/test-index?pretty" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1,
    "index.remote_store.translog.buffer_interval" : "300ms"
  }
}
'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "To enable index.remote_store.enabled, index.replication.type should be set to SEGMENT"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "To enable index.remote_store.enabled, index.replication.type should be set to SEGMENT"
  },
  "status" : 400
}
```

**To Reproduce**
Steps 1 - Update the `opensearch.yml` with below settings -
 1. `cluster.remote_store.enabled=true`
 2. `cluster.remote_store.segment.repository=<valid_repo>`
 3. `cluster.remote_store.translog.repository=<valid_repo>`

Step 2 - Register the <valid_repo> as mentioned in above step.

Step 3 - Create index as mentioned in *Describe the bug* section. 

**Expected behavior**
The index creation should pick the `SEGMENT` replication implicitly and not fail index creation.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by linuxpi**
### Description
- During index creation in a remote store enabled cluster, user needs to explicitly set replication type to SEGMENT, either in index settings or cluster settings
- With this change, user will not have to explicitly specify replication type SEGMENT for remote enabled clusters. 

### Related Issues
Resolves #9249 

### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java [hunk 1]
```diff
@@ -925,15 +926,15 @@ static Settings aggregateIndexSettings(
...
-        if (CLUSTER_REPLICATION_TYPE_SETTING.exists(clusterSettings) && INDEX_REPLICATION_TYPE_SETTING.exists(requestSettings) == false) {
-            settingsBuilder.put(SETTING_REPLICATION_TYPE, CLUSTER_REPLICATION_TYPE_SETTING.get(clusterSettings));
-            return;
-        }
         if (INDEX_REPLICATION_TYPE_SETTING.exists(requestSettings) == true) {
             settingsBuilder.put(SETTING_REPLICATION_TYPE, INDEX_REPLICATION_TYPE_SETTING.get(requestSettings));
-            return;
+        } else if (CLUSTER_REPLICATION_TYPE_SETTING.exists(clusterSettings) == true) {
+            settingsBuilder.put(SETTING_REPLICATION_TYPE, CLUSTER_REPLICATION_TYPE_SETTING.get(clusterSettings));
+        } else if (CLUSTER_REMOTE_STORE_ENABLED_SETTING.get(clusterSettings) == true) {
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java:933]: Any chance we can add in unit tests for this?

**Review by kotwanikunal — CHANGES_REQUESTED** [review]
This change needs a `CHANGELOG` entry since it changes the default behavior for certain scenarios.

File: server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java (hunk 1 above)
Comment (linuxpi) [reply server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java:933]: We already have ITs for this, but let me check if we can add UTs as well

File: server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java [hunk 2]
```diff
@@ -925,15 +926,15 @@ static Settings aggregateIndexSettings(
...
+            settingsBuilder.put(SETTING_REPLICATION_TYPE, ReplicationType.SEGMENT);
+        } else {
+            settingsBuilder.put(SETTING_REPLICATION_TYPE, CLUSTER_REPLICATION_TYPE_SETTING.get(clusterSettings));
```
Comment (BhumikaSaini-Amazon) [inline server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java:936]: Should this be `get()` or `getDefault()`?

File: server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java [hunk 3]
```diff
@@ -925,15 +926,15 @@ static Settings aggregateIndexSettings(
...
-            settingsBuilder.put(SETTING_REPLICATION_TYPE, CLUSTER_REPLICATION_TYPE_SETTING.get(clusterSettings));
-            return;
-        }
         if (INDEX_REPLICATION_TYPE_SETTING.exists(requestSettings) == true) {
             settingsBuilder.put(SETTING_REPLICATION_TYPE, INDEX_REPLICATION_TYPE_SETTING.get(requestSettings));
-            return;
+        } else if (CLUSTER_REPLICATION_TYPE_SETTING.exists(clusterSettings) == true) {
+            settingsBuilder.put(SETTING_REPLICATION_TYPE, CLUSTER_REPLICATION_TYPE_SETTING.get(clusterSettings));
+        } else if (CLUSTER_REMOTE_STORE_ENABLED_SETTING.get(clusterSettings) == true) {
+            settingsBuilder.put(SETTING_REPLICATION_TYPE, ReplicationType.SEGMENT);
```
Comment (BhumikaSaini-Amazon) [inline server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java:934]: nit : What I have seen in the repo is that we compare the boolean return value with a boolean literal only in cases where we expect a `false` value (this is being done for readability). Hence, we can skip the `== true` comparisons here.

File: server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java (hunk 2 above)
Comment (linuxpi) [reply server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java:936]: both should work in this case. but yeah at this point it would just be getting the default value

File: server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java [hunk 4]
```diff
@@ -48,6 +49,7 @@ protected Settings nodeSettings(int nodeOriginal) {
         Settings.Builder builder = Settings.builder()
             .put(remoteStoreClusterSettings("my-segment-repo-1", "my-translog-repo-1"))
             .put(settings);
+        builder.remove(CLUSTER_REPLICATION_TYPE_SETTING.getKey());
         return builder.build();
     }
```
[the remark this answers is not in the document]
Comment (linuxpi) [reply server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java:54]: sure, we can add randomness

**Review by BhumikaSaini-Amazon — APPROVED** [review]
LGTM, thanks 🙌

**Review by sachinpkale — APPROVED** [review]

**Comment by sachinpkale** [comment]
> This change needs a `CHANGELOG` entry since it changes the default behavior for certain scenarios.

This is added
