### PR TITLE
Avoid negative scores returned from `multi_match` query with `cross_fields`

### LINKED ISSUE #7860: [BUG] function score query returned an invalid (negative) score with multi match cross fields query
**Describe the bug**

The cross_fields scoring type can produce negative scores when some documents are missing fields. 

This bug [was already reported for Elasticsearch](https://github.com/elastic/elasticsearch/issues/44700) and [fixed with this MR](https://github.com/elastic/elasticsearch/pull/89016) for Elasticsearch >= 8.4. 

We encounter it randomly on production for certain queries when we search a field that does not exist in all documents. 
It appears deterministically for these search queries. 

Error message:

`{
    "error":
    {
        "root_cause":
        [
            {
                "type": "exception",
                "reason": "function score query returned an invalid score: -0.05202394 for doc: 1123896"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards":
        [
            {
                "shard": 0,
                "index": "my_index",
                "node": "my_node",
                "reason":
                {
                    "type": "exception",
                    "reason": "function score query returned an invalid score: -0.05202394 for doc: 1123896"
                }
            }
        ]
    },
    "status": 500
}`

The document number mentioned in the error message does not exist. 

**To Reproduce**

The steps to reproduce are in the above mentioned bug report for Elasticsearch. 

**Expected behavior**

The function score should never return a negative value. 

**Plugins**

None.

**Host/Environment (please complete the following information):**
 
OpenSearch version: 2.5

### PR DESCRIPTION
**Pull request by msfroh**
### Description
Under specific circumstances, when using `cross_fields` scoring on a `multi_match` query, we can end up with negative scores from the inverse document frequency calculation in the BM25 formula.

Specifically, the IDF is calculated as:

```
log(1 + (N - n + 0.5) / (n + 0.5))
```

where `N` is the number of documents containing the field and `n` is the number of documents containing the given term in the field. Obviously, `n` should always be less than or equal to `N`.

Unfortunately, `cross_fields` makes up a new value for `n` and tries to use it across all fields.

This change finds the minimum (nonzero) value of `N` and uses that as an upper bound for the new value of `n`.

### Related Issues
Resolves #7860

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [ ] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java [hunk 1]
```diff
@@ -133,11 +134,15 @@ protected void blend(final TermStates[] contexts, int maxDoc, IndexReader reader
                 // we need to find out the minimum sumTTF to adjust the statistics
                 // otherwise the statistics don't match
                 minSumTTF = Math.min(minSumTTF, reader.getSumTotalTermFreq(terms[i].field()));
+                minDocCount = Math.min(minDocCount, reader.getDocCount(terms[i].field()));
             }
         }
         if (maxDoc > minSumTTF) {
             maxDoc = (int) minSumTTF;
         }
```
Comment (msfroh) [inline server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java:142]: This is probably redundant now.

`minSumTTF` is guaranteed to be `<= minDocCount`.

**Comment by msfroh** [comment]
For some context, I came up with this fix after talking myself through the logic of the (previously) failing test in https://github.com/opensearch-project/OpenSearch/pull/13627/files#r1614240922

**Comment by msfroh** [comment]
Oh... I thought of another way to fix it.

When we're adjusting the df per term, we could limit the df for the term based on the total doc count of the field. It's a bit more localized than this change, which potentially lowers the df for all terms.

File: server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java [hunk 2]
```diff
@@ -133,11 +134,15 @@ protected void blend(final TermStates[] contexts, int maxDoc, IndexReader reader
                 // we need to find out the minimum sumTTF to adjust the statistics
                 // otherwise the statistics don't match
                 minSumTTF = Math.min(minSumTTF, reader.getSumTotalTermFreq(terms[i].field()));
+                minDocCount = Math.min(minDocCount, reader.getDocCount(terms[i].field()));
```
Comment (reta) [inline server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java:137]: Could we please add a small summary from the description to explain why we are doing this (for future maintainers / us), thank you

Comment (msfroh) [reply server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java:137]: I think I will go ahead and move the change later in the method, targeting just the fields that could go negative.

Identifying the min doc counts can still be up top, but I'll save them in an array, then consume them in the part that calls `adjustDF`.

Comment (msfroh) [reply server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java:137]: And I'll add a comment explaining why we're doing it of course 😀

Comment (msfroh) [reply server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java]: Done!

**Review by reta — APPROVED** [review]

**Comment by msfroh** [comment]
> [Test Result](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/) (8 failures / +8)
[org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.smoketest/SmokeTestMultiNodeClientYamlTestSuiteIT/test__yaml_search_50_multi_match_Cross_fields_do_not_return_negative_scores_/)
[org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.smoketest/SmokeTestMultiNodeClientYamlTestSuiteIT/test__yaml_search_50_multi_match_Cross_fields_do_not_return_negative_scores__2/)
[org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.smoketest/SmokeTestMultiNodeClientYamlTestSuiteIT/test__yaml_search_50_multi_match_Cross_fields_do_not_return_negative_scores__3/)
[org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.smoketest/SmokeTestMultiNodeClientYamlTestSuiteIT/test__yaml_search_50_multi_match_Cross_fields_do_not_return_negative_scores__4/)
[org.opensearch.test.rest.ClientYamlTestSuiteIT.test {p0=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.test.rest/ClientYamlTestSuiteIT/test__p0_search_50_multi_match_Cross_fields_do_not_return_negative_scores_/)
[org.opensearch.test.rest.ClientYamlTestSuiteIT.test {p0=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.test.rest/ClientYamlTestSuiteIT/test__p0_search_50_multi_match_Cross_fields_do_not_return_negative_scores__2/)
[org.opensearch.test.rest.ClientYamlTestSuiteIT.test {p0=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.test.rest/ClientYamlTestSuiteIT/test__p0_search_50_multi_match_Cross_fields_do_not_return_negative_scores__3/)
[org.opensearch.test.rest.ClientYamlTestSuiteIT.test {p0=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.test.rest/ClientYamlTestSuiteIT/test__p0_search_50_multi_match_Cross_fields_do_not_return_negative_scores__4/)[Test Result](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/) (8 failures / +8)
[org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.smoketest/SmokeTestMultiNodeClientYamlTestSuiteIT/test__yaml_search_50_multi_match_Cross_fields_do_not_return_negative_scores_/)
[org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.smoketest/SmokeTestMultiNodeClientYamlTestSuiteIT/test__yaml_search_50_multi_match_Cross_fields_do_not_return_negative_scores__2/)
[org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.smoketest/SmokeTestMultiNodeClientYamlTestSuiteIT/test__yaml_search_50_multi_match_Cross_fields_do_not_return_negative_scores__3/)
[org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.smoketest/SmokeTestMultiNodeClientYamlTestSuiteIT/test__yaml_search_50_multi_match_Cross_fields_do_not_return_negative_scores__4/)
[org.opensearch.test.rest.ClientYamlTestSuiteIT.test {p0=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.test.rest/ClientYamlTestSuiteIT/test__p0_search_50_multi_match_Cross_fields_do_not_return_negative_scores_/)
[org.opensearch.test.rest.ClientYamlTestSuiteIT.test {p0=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.test.rest/ClientYamlTestSuiteIT/test__p0_search_50_multi_match_Cross_fields_do_not_return_negative_scores__2/)
[org.opensearch.test.rest.ClientYamlTestSuiteIT.test {p0=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.test.rest/ClientYamlTestSuiteIT/test__p0_search_50_multi_match_Cross_fields_do_not_return_negative_scores__3/)
[org.opensearch.test.rest.ClientYamlTestSuiteIT.test {p0=search/50_multi_match/Cross fields do not return negative scores}](https://build.ci.opensearch.org/job/gradle-check/39404/testReport/junit/org.opensearch.test.rest/ClientYamlTestSuiteIT/test__p0_search_50_multi_match_Cross_fields_do_not_return_negative_scores__4/)

The specific exception is:

> java.lang.AssertionError: Failure at [search/50_multi_match:32]: cast error while checking (field [hits.hits.2._score] is not greater than [0.0]): java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Float (java.lang.Double and java.lang.Float are in module java.base of loader 'bootstrap')

Hmm... that's odd. This *just* changed after I rebased onto the latest `main`. (I swear the test was passing before I pushed the latest commit!) I wonder what changed the type of the scores...

**Comment by msfroh** [comment]
Oh... interesting. Sometimes it fails on my machine and sometimes it passes. 

I haven't been able to figure out yet why my `0.0` in the test YAML sometimes gets parsed as `float` and sometimes as `double`.

**Comment by msfroh** [comment]
It feels like this was kind of a long-standing bug that we never really encountered until now. I found that the test would fail on my machine with certain seeds. 

The only existing tests with floating point comparisons were all related to `rank_eval`, where the evaluation outputs have type `double`, so the conversions worked.

Anyway, I added some basic conversion for numeric types in assertions in the most recent commit https://github.com/opensearch-project/OpenSearch/pull/13829/commits/8c9ac3c68d4fbd5b4d9403c06d0c9c55f6a5d51d.

**Comment by msfroh** [comment]
Grr... failed due to https://github.com/opensearch-project/OpenSearch/issues/10735

File: server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java (hunk 1 above)
Comment (msfroh) [reply server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java]: I changed the logic anyway, so we're not modifying `maxDoc` twice anymore. We can leave this check in place.

File: test/framework/src/main/java/org/opensearch/test/rest/yaml/section/Assertion.java [hunk 3]
```diff
@@ -79,6 +81,41 @@ protected final Object getActualValue(ClientYamlTestExecutionContext executionCo
         return executionContext.response(field);
     }
 
+    static Object convertActualValue(Object actualValue, Object expectedValue) {
```
Comment (reta) [inline test/framework/src/main/java/org/opensearch/test/rest/yaml/section/Assertion.java:84]: @msfroh could you please explain why do we need this? I remember you've mentioned flipping between `float` and `double`, but I am curious how come we run into that now and not before?

Comment (msfroh) [reply test/framework/src/main/java/org/opensearch/test/rest/yaml/section/Assertion.java:84]: From what I found, the existing uses of `gt`, `lt`, `gte`, and `lte` were comparing integers (no decimal in the expected value) or they were looking at `metric_score` from the `rank-eval` plug-in, which has type `double`.

I think this is the first time that someone has tried using one of those comparisons on a `float`.

What I'm still confused about is that the test would sometimes pass. I would have expected `0.0` to consistently get parsed as `double` and the test would fail.

**Review by reta — APPROVED** [review]

File: test/framework/src/main/java/org/opensearch/test/rest/yaml/section/Assertion.java (hunk 3 above)
Comment (reta) [reply test/framework/src/main/java/org/opensearch/test/rest/yaml/section/Assertion.java:84]: Interesting, I will try to look (but not blocking the fix), thanks for explaining!

**Comment by reta** [comment]
@msfroh mind please backport to 2.x manually? thank you

**Comment by msfroh** [comment]
Backport PR is ready: https://github.com/opensearch-project/OpenSearch/pull/13983
