### PR TITLE
Avoid infinite loop in flat_object parsing

### LINKED ISSUE #15982: [BUG] Unbounded execution for write threads when parsing a flat_object field provided as array
### Describe the bug

Unbounded execution for write threads when parsing a flat_object field provided as array.
Ideally, this should error out gracefully.

### Related component

Indexing

### To Reproduce

```
PUT dummy
{
    "mappings": {
        "properties": {
            "ArrField": {
                "type": "flat_object"
            }
        }
    }
}

# Succeeds
POST dummy/_doc
{
    "ArrField": {
        "ObjKey": "ObjVal"
    }
}

# Stuck forever
POST dummy/_doc
{
    "ArrField": ["ArrVal"]
}
```

### Expected behavior

Error out due to lack of support.

### Additional Details

**Plugins**
none

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Mac
 - Version: Sonoma

**Additional context**

### PR DESCRIPTION
**Pull request by msfroh**
### Description
We had logic in flat_object parsing that would:

1. Try parsing a flat object field that is not an object or null.
2. Would see an END_ARRAY token, ignore it, and not advance the parser.

Combined, this would create a scenario where passing an array of strings for a flat_object would parse the string values, then loop infinitely on the END_ARRAY token.

### Related Issues
Resolves #15982

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by msfroh** [comment]
@kkewwei -- would you mind taking a look at this change?

File: server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java [hunk 1]
```diff
@@ -117,8 +118,6 @@ private boolean parseToken(Deque<String> path, String currentFieldName) throws I
                 isChildrenValueValid |= parseToken(path, currentFieldName);
             }
             this.parser.nextToken();
-        } else if (this.parser.currentToken() == Token.END_ARRAY) {
-            // skip
```
Comment (msfroh) [inline server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:121]: By removing this clause, we guarantee that every branch has a call to `this.parser.nextToken()`, so we can't go into an infinite loop (since we'll eventually run out of tokens).

Comment (msfroh) [reply server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:121]: Hmm... actually the `if` on line 91 might still hurt us. I believe we can safely remove it, though. I worked through that logic and I don't think it should actually be needed. (That condition should already be covered by the `else` clause in the big `if` block.)

Comment (kkewwei) [reply server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:121]: The initial idea of adding the `if` is to compatible with this case:
```
PUT dummy/_doc/2
{
    "ArrField": "dddd"
}
```
The goal is that we can accept any input(json, string, array), I'm not sure if it is reasonable.

**Comment by kkewwei** [comment]
In additional, if we should attempt to delete `currentFieldName` from the `parseToken` in the pr?(https://github.com/opensearch-project/OpenSearch/pull/14069#issuecomment-2320016491)

File: server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java (hunk 1 above)
Comment (msfroh) [reply server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:121]: Hmm... I think we should require that the `flat_object` field be an object at the top level. Another way of thinking of it is that the path should never be empty.

Comment (kkewwei) [reply server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:121]: It sounds good.

Comment (jainankitk) [reply server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:121]: > I think we should require that the flat_object field be an object at the top level

That sounds like a reasonable assumption to me! Although, I am wondering if this has any breaking change implications for users already providing below as input. And, does it impact the data already indexed anyhow for search scenarios (I don't think so)?

```
PUT dummy/_doc/2
{
    "ArrField": "dddd"
}
```

Comment (msfroh) [reply server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:121]: To the best of my knowledge, we were already failing for input like:

```
PUT dummy/_doc/2
{
    "ArrField": "dddd"
}
```

So, I believe it's safe. Let me confirm with a test on 2.17.

Comment (msfroh) [reply server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:121]: Yeah -- after disabling the assertion that the first token is `START_OBJECT` (to simulate production behavior), I got the following response:

```
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"object mapping for [_doc] tried to parse field [catalog] as object, but got EOF, has a concrete value been provided to it?"}],"type":"mapper_parsing_exception","reason":"object mapping for [_doc] tried to parse field [catalog] as object, but got EOF, has a concrete value been provided to it?"},"status":400}%  
```

The new exception message is much better, IMO:

```
{"error":{"root_cause":[{"type":"parsing_exception","reason":"[catalog] unexpected token [VALUE_STRING] in flat_object field value","line":1,"col":12}],"type":"mapper_parsing_exception","reason":"failed to parse field [catalog] of type [flat_object] in document with id '1'. Preview of field's value: 'foo'","caused_by":{"type":"parsing_exception","reason":"[catalog] unexpected token [VALUE_STRING] in flat_object field value","line":1,"col":12}},"status":400}% 
```

**Review by jainankitk — APPROVED** [review]

**Comment by msfroh** [comment]
Manual backport PR: https://github.com/opensearch-project/OpenSearch/pull/16026
