### PR TITLE
Avoid logging duplicate deprecation warnings multiple times

### LINKED ISSUE #1108: [BUG] Deprecation message spamming logs from Security plugin
**Describe the bug**
Deprecation message spamming the logs
```

**To Reproduce**
Steps to reproduce the behavior:
1. Stream logs from logstash to OpenSearch with username, password. 

**Expected behavior**
No spamming of logs

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
This PR adds logic to avoid logging duplicate deprecation messages. It resolves the issue #1108 and all other deprecation message instances. (Coming from https://github.com/opensearch-project/OpenSearch/pull/1537#pullrequestreview-805281149). There are also test changes since a lot of tests verify the deprecation warnings.
 
### Issues Resolved
Closes #1108 
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Nice work. I would appreciate another pair of eyes other than myself. Maybe @andrross?

File: server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java [hunk 1]
```diff
@@ -58,4 +74,12 @@ public DeprecatedMessage(String key, String xOpaqueId, String messagePattern, Ob
         }
         return builder.immutableMap();
     }
+
+    public boolean isAlreadyLogged() {
+        if (keys.contains(this.keyWithXOpaqueId)) {
+            return true;
+        }
+        keys.add(this.keyWithXOpaqueId);
```
Comment (andrross) [inline server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java:82]: Is this safe on an unsynchronized HashSet? I'm assuming this method can be accessed concurrently from any number of threads. It's likely fine for the de-duplication logic to be best effort and a duplicate log entry emitted due to a race is not a big deal, but I'm more concerned about undefined behavior now or in future JDK versions if the underlying data structure is modified in the middle of a `contains()` invocation.

File: test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java [hunk 2]
```diff
@@ -127,6 +127,10 @@
     public static final String CLIENT_SOCKET_TIMEOUT = "client.socket.timeout";
     public static final String CLIENT_PATH_PREFIX = "client.path.prefix";
 
+    // This set will contain the warnings already asserted since we are eliminating logging duplicate warnings.
+    // This ensures that no matter in what order the tests run, the warning is asserted once.
+    private static Set<String> assertedWarnings = new HashSet<>();
```
Comment (andrross) [inline test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java:132]: Is this potentially introducing a race condition if tests run concurrently (or if a test just happens to create multiple threads that log concurrently) due to the non-synchronized de-duplication implemenation?

File: server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java (hunk 1 above)
Comment (VachaShah) [reply server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java:82]: Definitely agree! We can use the SynchronizedSet, the only downside might be performance since the collection will be locked by a single thread at a time. If that is not a concern, we can make this synchronized. WDYT?

**Comment by VachaShah** [comment]
start gradle check

File: server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java (hunk 1 above)
Comment (andrross) [reply server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java:82]: I think ConcurrentHashMap will give the concurrency guarantees while also allowing lock-free reads. Something like:

```
private final Set<String> keys = ConcurrentHashMap.newKeySet();

...

public boolean isAlreadyLogged() {
    return !keys.add(keyWithXOpaqueId);
}
```

Under the hood it looks like the KeySetView of ConcurrentHashMap is using the same method as `putIfAbsent` in its `add` method. That should be lock-free in the case that the key is present, and only incur any synchronization overhead in the case that it is newly adding a key.

**Comment by VachaShah** [comment]
> ❌   Gradle Check failure [931bb72](https://github.com/opensearch-project/OpenSearch/commit/931bb72d6bac52526117977513ac38c475fea8bb) [Log 1502](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1502.log)
> 
> [Reports 1502](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1502_reports.zip)

```
Execution failed for task ':distribution:bwc:bugfix:buildBwcLinuxTar'.
> Building 1.2.1 didn't generate expected file /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/distribution/bwc/bugfix/build/bwc/checkout-1.2/distribution/archives/linux-tar/build/distributions/opensearch-min-1.2.1-SNAPSHOT-linux-x64.tar.gz
``` 

This should resolve after PR #1731 is merged.

File: server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java (hunk 1 above)
Comment (VachaShah) [reply server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java]: Sorry for the delay! That makes sense. I have updated the implementation to use the keySet() from ConcurrentHashMap.

File: test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java (hunk 2 above)
Comment (VachaShah) [reply test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java]: Using ConcurrentHashMap keySet here.

File: server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java [hunk 3]
```diff
@@ -37,15 +37,32 @@
...
+    }
+
+    /**
+     * This method is to reset the key set which is used to log unique deprecation logs only.
+     * The key set helps avoiding the deprecation messages being logged multiple times.
+     * This method is a utility to reset this set for tests so they can run independent of each other.
+     * Otherwise, a warning can be logged by some test and the upcoming test can be impacted by it.
+     */
+    public static void resetDeprecatedMessageForTests() {
+        keys = new HashSet<>();
```
Comment (andrross) [inline server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java:65]: This isn't right because you're resetting the field to the non-concurrent hashset implementation. I would actually replace this with `keys.clear()` since the ConcurrentHashMap is thread safe.

File: server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java [hunk 4]
```diff
@@ -37,15 +37,32 @@
...
+import java.util.concurrent.ConcurrentHashMap;
+
 /**
  * A logger message used by {@link DeprecationLogger}.
  * Carries x-opaque-id field if provided in the headers. Will populate the x-opaque-id field in JSON logs.
  */
 public class DeprecatedMessage extends OpenSearchLogMessage {
     public static final String X_OPAQUE_ID_FIELD_NAME = "x-opaque-id";
+    private static Set<String> keys = ConcurrentHashMap.newKeySet();
+    private String keyWithXOpaqueId;
```
Comment (andrross) [inline server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java:51]: Both of these can be final (see comment below about a change to the reset method).

File: modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/indices.analyze/10_analyze.yml [hunk 5]
```diff
@@ -19,10 +19,10 @@
     - skip:
         version: " - 6.2.99"
         reason: deprecated in 6.3
-        features: "warnings"
+        features: "allowed_warnings"
```
Comment (andrross) [inline modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/indices.analyze/10_analyze.yml:22]: I admit that I don't really understand what these files mean, but why did you change "warnings" to "allowed_warnings"?

File: server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java (hunk 3 above)
Comment (VachaShah) [reply server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java:65]: Oh my bad! I missed this, I will change it.

File: modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/indices.analyze/10_analyze.yml (hunk 5 above)
Comment (VachaShah) [reply modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/indices.analyze/10_analyze.yml:22]: `allowed_warnings` asserts if the warning occurs but does not fail the test if it doesn't. This is in a lot of files and there is no order in which they run so it is very difficult to determine when the first warning will occur given that a lot of tests  assert the same duplicate warnings.

**Review by andrross — APPROVED** [review]

**Comment by dblock** [comment]
Nice job @VachaShah and thanks for a thorough code review @andrross!
