### PR TITLE
[Segment Replication] Fix timeout issue by calculating time needed to process getSegmentFiles.

### LINKED ISSUE #4392: Adjust dynamic timeout for `get_segment_files` operation to prevent request timeouts
GetSegmentFiles transport request times out during requests with the current timeout of 1 minute from the recovery setting - indices.recovery.internal_action_retry_timeout. 

To come up with a better timeout option, we can set it dynamically according to the total file segment size (from FileStoreMetadata) and the cluster's network bandwidth. 

Without having access to knowledge of the cluster's network bandwidth, we can experiment to set a value of timeout that takes into account segment files' size. 

```
Caused by: org.opensearch.transport.ReceiveTimeoutTransportException: [seed][10.9.0.166:9300][internal:index/shard/replication/get_segment_files] request_id [552738] timed out after [599988ms]
```

Failure stack trace from benchmarking
```
2022-09-02T09:34:08,220][ERROR][o.o.i.r.SegmentReplicationTargetService] [data-e20223d0] replication failure
org.opensearch.OpenSearchException: Segment Replication failed
        at org.opensearch.indices.replication.SegmentReplicationTargetService$3.onFailure(SegmentReplicationTargetService.java:293) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.action.ActionListener$1.onFailure(ActionListener.java:88) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:103) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:54) [opensearch-2.2.0.jar:2.2.0]        at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:112) [opensearch-2.2.0.jar:2.2.0]        at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
        at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:112) [opensearch-2.2.0.jar:2.2.0]        at org.opensearch.common.util.concurrent.BaseFuture.setException(BaseFuture.java:178) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.common.util.concurrent.ListenableFuture.onFailure(ListenableFuture.java:149) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.action.StepListener.innerOnFailure(StepListener.java:82) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.action.NotifyOnceListener.onFailure(NotifyOnceListener.java:62) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.action.ActionListener$4.onFailure(ActionListener.java:190) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.action.ActionListener$6.onFailure(ActionListener.java:309) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.action.support.RetryableAction$RetryingListener.onFinalFailure(RetryableAction.java:201) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.action.support.RetryableAction$RetryingListener.onFailure(RetryableAction.java:193) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:74) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1379) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1270) [opensearch-2.2.0.jar:2.2.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.2.0.jar:2.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.opensearch.transport.ReceiveTimeoutTransportException: [seed][10.9.0.166:9300][internal:index/shard/replication/get_segment_files] request_id [552738] timed out after [599988ms]
        at org.opensearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1273) ~[opensearch-2.2.0.jar:2.2.0]
        ... 4 more
```

### PR DESCRIPTION
**Pull request by Rishikesh1159**
Signed-off-by: Rishikesh1159 <rishireddy1159@gmail.com>

### Description
This PR fixes timeout issue temporarily for experimental release of segment-replication.

### Issues Resolved
#4392 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java [hunk 1]
```diff
@@ -78,14 +80,33 @@ public void getSegmentFiles(
...
+
+        // Storing the size of files to fetch in bytes.
+        long sizeOfSegmentFiles = 0;
+        for (int i = 0; i < filesToFetch.size(); i++) {
+            sizeOfSegmentFiles += filesToFetch.get(i).length();
+        }
+        // Making sure files size is in correct format to perform time calculation.
+        sizeOfSegmentFiles = Math.abs(sizeOfSegmentFiles);
+        // Maximum size of files to fetch (segment files), that can be processed in 1 minute for a m5.xlarge machine.
+        long baseSegmentFilesSize = 300000000;
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:96]: 1. Can you share steps performed to identify this baseline ? 
2. This baseline is calculated for `m5.xlarge` instance type, which means all instance types with lower throughput may fail persistently ? Can we relax(reduce) this baseline to smaller value to accomodate lower grade instance types. It doesn't hurt to reduce this limit for high grade instance type, only side-effect is that we estimate higher number of minutes but it will complete faster. But, it will fix timeout issues on lower grade machines.

File: server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java [hunk 2]
```diff
@@ -78,14 +80,33 @@ public void getSegmentFiles(
...
+
+        long timeToGetSegmentFiles = 1;
+        // Formula for calculating time needed to process a replication event's files to fetch process
+        timeToGetSegmentFiles += sizeOfSegmentFiles / baseSegmentFilesSize;
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:100]: Can this be simplified with below ?
```
final long timeToGetSegmentFiles = Math.max (1, sizeOfSegmentFiles / baseSegmentFilesSize);
```

File: server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java [hunk 3]
```diff
@@ -78,14 +80,33 @@ public void getSegmentFiles(
...
+        long sizeOfSegmentFiles = 0;
+        for (int i = 0; i < filesToFetch.size(); i++) {
+            sizeOfSegmentFiles += filesToFetch.get(i).length();
+        }
+        // Making sure files size is in correct format to perform time calculation.
+        sizeOfSegmentFiles = Math.abs(sizeOfSegmentFiles);
+        // Maximum size of files to fetch (segment files), that can be processed in 1 minute for a m5.xlarge machine.
+        long baseSegmentFilesSize = 300000000;
+
+        long timeToGetSegmentFiles = 1;
```
[the remark this answers is not in the document]
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:98]: I think this initialization can reduced as mentioned in below comment.

File: server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java [hunk 4]
```diff
@@ -78,14 +80,35 @@ public void getSegmentFiles(
...
+
+        // Storing the size of files to fetch in bytes.
+        long sizeOfSegmentFiles = 0;
+        for (int i = 0; i < filesToFetch.size(); i++) {
+            sizeOfSegmentFiles += filesToFetch.get(i).length();
+        }
+        // Making sure files size is in correct format to perform time calculation.
+        if(sizeOfSegmentFiles<0){
+            sizeOfSegmentFiles *=-1;
+        }
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:94]: Why this change is needed ?

File: server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java (hunk 1 above)
Comment (mch2) [reply server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:96]: +1.   This feels a bit high, maybe bump by 1M for every 100mb? This value should be toggleable with a setting, we can shoot for that in next release.

File: server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java (hunk 4 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:94]: So, while testing benchmarks there are scenarios where the size of files to fetch will be in negative. May be something like this "-1239252992" bytes. If size of files to fetch is negative then time value will also be negative, which doesn't makes sense and throws error. I tried to use Math.abs() but that is forbidden so I have no other option. Please suggest if there are any ways to overcome this?

Comment (dreamer-89) [reply server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:94]: This is interesting. Where do you see negative file length value @Rishikesh1159. @mch2 : Do you know when do we have negative file length value ?

File: server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java (hunk 1 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:96]: Steps to identify baseline:
-> I started a 3 node cluster and ran opensearch-benchmarks with SO dataset. I logged files to fetch size and check the logs later for every replication event. After checking all replication event logs i observed the maximum files to fetch size that has finished within 1min time was 330mb, so I took 330mb as baseline. Later after this change no timeouts happened.

->As I mentioned above that after observing logs I put baseline as 330mb, but as both @dreamer-89 and @mch2 mentioned it makes sense to reduce the baseline, so that lower throughput machines don't have a timeout. I will use bump by 1min for every 100 mb as @mch2 suggested.

File: server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java (hunk 2 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:100]: Let's take example where baseline is 100000000 bytes (100mb) and size of segment files is 250000000(250mb). When we do a sizeOfSegmentFiles / baseSegmentFilesSize result will be 2min. But we need 3min to process this size of segment, so we will have a timeout. To avoid this we need to add a 1 before and after " sizeOfSegmentFiles / baseSegmentFilesSize"

File: server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java (hunk 4 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:94]: When running benchmarks I was logging size of files to fetch, I observed that with couple of replication events. I also observed time taken to process both  "-1239252992" bytes size and "1239252992" bytes size is same. So, I was looking for it to convert to a positive value

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java]: Sorry for confusion. Size of files to fetch will never be in negative. When I was testing locally I was using int type to store the size, so for bigger value int was overflowing and I was negative size of files to fetch in logs. Later I used Long type and this is no more an issue.

Comment (dreamer-89) [reply server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java]: 👍

**Review by dreamer-89 — APPROVED** [review]
LGTM! Thanks @Rishikesh1159 for the quick fix. This is a critical change.

File: server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java [hunk 5]
```diff
@@ -78,14 +80,28 @@ public void getSegmentFiles(
...
             targetAllocationId,
             targetNode,
             filesToFetch,
             checkpoint
         );
-        transportClient.executeRetryableAction(GET_SEGMENT_FILES, request, responseListener, reader);
+        final TransportRequestOptions options = TransportRequestOptions.builder()
+            .withTimeout(TimeValue.timeValueMinutes(timeToGetSegmentFiles))
+            .build();
+        transportClient.executeRetryableAction(GET_SEGMENT_FILES, request, options, responseListener, reader);
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java:104]: nit: We can add a unit test to verify the timeouts here. I am fine taking up this in separate PR.

**Comment by dreamer-89** [comment]
@Rishikesh1159 : Backport PR failed. Do you mind raising manual backport PR ?
