### PR TITLE
Ignore attribute awareness when custom preference is set

### LINKED ISSUE #18817: [BUG] Custom string preference with awareness attributes does not produce consistent routing
### Describe the bug

Using a custom string preference does not appear to consistently route searches to the same shard when awareness attributes are enabled on a cluster.

When executing a search with a custom preference string we do not strictly route based on this string, and instead use it to [build a `routingHash`](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java#L429) which deterministically shuffles shards, ensuring the same shard order is always produced for a given preference string. 

When awareness attributes are present on a cluster the coordinating node will prefer shards which share its own awareness attribute(rack/zone/ect). The coordinator will then build a list of shards which [share its own attribute](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java#L920-L921), and a list of shards which do not share its attribute. Within these lists the custom preference string still deterministically shuffles the order of shards, however shards with the same attribute are always preferred for routing.

From a user perspective they will only see the expected behavior of their custom preference string if their coordinating node always has the same attribute. Users will typically place a load balancer in front of their cluster to randomly select a coordinator and with this common use case it will appear to clients as if the custom string preference is doing nothing as the nodes awareness attribute takes precedent over the custom pref string.

### Related component

Search

### To Reproduce

IT to reproduce the behavior -
https://github.com/finnegancarroll/OpenSearch/commit/46b2192e606f9fcc09f143f341a3bc06699a64b2

### Expected behavior

Every other preference type skips attribute awareness completely and provides its own shard iterator. I think it would make sense for custom strings to behave the same way and ignore attributes.

https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java#L402-L427

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by finnegancarroll**
### Description
This change addresses a bug which appears when a custom preference string is included with a query while awareness attributes are present on the cluster.

In this scenario it can seem as if the custom preference string included with query is not being honored. This is due to how awareness attributes preference shards which share an attribute with the coordinating node when routing a search request. Awareness attributes take priority and the custom string preference is only applied after this step. A search request with the same custom string preference can then be routed differently depending on which node is acting as coordinator.

All other preference types[ exit early and ignore awareness attributes](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java#L403-L427) with custom string preference being the one exception that attempts to deterministically route requests **within** awareness attribute groups.

This change ignores awareness attributes when a custom string preference is present. 

### Related Issues
Resolves #18817 

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by finnegancarroll** [comment]
Flaky - #18850

File: server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java [hunk 1]
```diff
@@ -857,4 +861,72 @@ public void testReadWriteWeightedRoutingMetadataOnNodeRestart() throws Exception
...
+            )
+        );
+
+        ensureGreen("test_index");
+
+        // Index test documents
+        for (int i = 0; i < 30; i++) {
+            client().prepareIndex("test_index").setId(String.valueOf(i)).setSource("field", "value" + i).get();
+        }
+        refresh("test_index");
```
Comment (andrross) [inline server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java]: Maybe prefer `refreshAndWaitForReplication("test_index")` so that this test will work with segment replication?

**Comment by finnegancarroll** [comment]
Flaky test #18872

**Comment by finnegancarroll** [comment]
Same flaky test #18872.

**Review by andrross — APPROVED** [review]
