### PR TITLE
Fix Flaky IntervalQueryBuilderTests

### LINKED ISSUE #19167: [AUTOCUT] Gradle Check Flaky Test Report for IntervalQueryBuilderTests
## Flaky Test Report for `IntervalQueryBuilderTests`

Noticed the `IntervalQueryBuilderTests` has some flaky, failing tests that failed during **post-merge actions** and **timer trigerred run on main branch**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| main | [null](https://github.com/opensearch-project/OpenSearch/pull/null) | [58158](https://build.ci.opensearch.org/job/gradle-check/58158/testReport/) <br><br>[62941](https://build.ci.opensearch.org/job/gradle-check/62941/testReport/) | `org.opensearch.index.query.IntervalQueryBuilderTests.testToQuery` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `IntervalQueryBuilderTests` class are:

- [13850](https://github.com/opensearch-project/OpenSearch/pull/13850)
- [15612](https://github.com/opensearch-project/OpenSearch/pull/15612)
- [13637](https://github.com/opensearch-project/OpenSearch/pull/13637)
- [14487](https://github.com/opensearch-project/OpenSearch/pull/14487)
- [18375](https://github.com/opensearch-project/OpenSearch/pull/18375)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by ajleong623**
### Description
I noticed that when the flaky test fails, this is because there are too many disjunctions in the `IntervalsSource`. https://github.com/apache/lucene/blob/main/lucene/queries/src/java/org/apache/lucene/queries/intervals/Disjunctions.java#L44. What I changed was to detect the number of total disjunctions there would be when combining the list of `IntervalsSource` earlier in the stack trace and throwing an error if the list of `IntervalsSource` cannot be combined. I also skipped the test instances that provided the list that would reach this violation. 

### Related Issues
Resolves #19167 

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
@ajleong623 I think you need to do another push. The CI checks are stuck and I don't have a way to trigger them without pushing to your branch.

**Comment by ajleong623** [comment]
@cwperks weirdly enough, I tried a rerun, and some of the workflows still did not run.

**Comment by ajleong623** [comment]
@cwperks The tests have all run and passed. I think I am ready for review and possibly merge. The only times the tests failed were from flaky one.

File: server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java [hunk 1]
```diff
@@ -443,6 +443,9 @@ public IntervalsSource getSource(QueryShardContext ctx, MappedFieldType fieldTyp
             for (IntervalsSourceProvider provider : subSources) {
                 ss.add(provider.getSource(ctx, fieldType));
             }
+            if (maxGaps == 0 && mode == IntervalMode.ORDERED && IntervalBuilder.canCombineSources(ss) == false) {
```
Comment (cwperks) [inline server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java:446]: Is `maxGaps` == 0 important here?

Comment (ajleong623) [reply server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java:446]: The path that did not pass the tests is through https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/query/IntervalBuilder.java#L155-L157. I wanted to catch the potential error for that one case, however for the other cases with combining sources, there is a chance similar errors might occur, but I have not looked into that yet.

**Review by cwperks — APPROVED** [review]
