### PR TITLE
Read docker location from PATH env variable

### LINKED ISSUE #3476: [BUG] Docker & Docker compose installed from Homebrew not recognized
**Describe the bug**

I am trying to setup dev environment on Mac M1 and I have docker installed from Homebrew (`brew install docker docker-compose;`). When I start `assemble` task I get an exception about missing Docker binaries like this:

```
Docker (checked [/usr/bin/docker, /usr/local/bin/docker]) is required to run the following tasks: 
```

I think the issue is that `brew` by default installs binaries into different location. See:

```
% which docker docker-compose
/opt/homebrew/bin/docker
/opt/homebrew/bin/docker-compose
```

```sh
# Just FYI my version of Docker-compose and Docker

% docker-compose version
Docker Compose version 2.5.1

% docker version
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.18.2
 Git commit:        aa7e414fdc
 Built:             Wed May 11 16:22:17 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:48:38 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        f46b6ba2c9314cfc8caae24a32ec5fe9ef1059fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

The exception seems to be coming from `DockerSupportService.java`

https://github.com/opensearch-project/OpenSearch/blob/e9b19a095c2cf90274c41aa701432a2748c03468/buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java#L165

It does not currently check for Docker binaries in the location where brew installs it.

**To Reproduce**

A fresh pull from `main`:
```sh
% git pull upstream main
From github.com:opensearch-project/OpenSearch
 * branch                    main       -> FETCH_HEAD
Already up to date.

% git log --oneline -n 1
e9b19a095c2 (HEAD -> main, upstream/main, lukas/main) [Segment Replication] Add SegmentReplicationTargetService to orchestrate replication events. (#3439)

```
Run `assemble` task.

```sh
% ./gradlew assemble    

> Configure project :qa:os
Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Mac OS X 12.3.1 (aarch64)
  JDK Version           : 17 (Eclipse Temurin JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
  Random Testing Seed   : 86D4E779628BC837
  In FIPS 140 mode      : false
=======================================

FAILURE: Build failed with an exception.

* What went wrong:
Docker (checked [/usr/bin/docker, /usr/local/bin/docker]) is required to run the following tasks: 
:distribution:docker:buildArm64DockerImage
:distribution:docker:buildDockerImage
you can address this by attending to the reported issue, or removing the offending tasks from being executed.
```

**Expected behavior**

`DockerSupportService.java` should be able to detect Docker tools in location used by `brew`.

**Host/Environment (please complete the following information):**
 - OS: Mac OS,  chip M1: ```% uname -a
Darwin Lukass-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64```

### PR DESCRIPTION
**Pull request by WojciechKrakowiak**
### Description
This allows to run the OpenSearch in environments with docker installation in various locations (like from HomeBrew or Rancher Desktop). The previous paths are still held as default fallback if the docker is not detected in locations from env variable.

### Related Issues
Resolves #3476

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java [hunk 1]
```diff
@@ -66,16 +68,24 @@
 public abstract class DockerSupportService implements BuildService<DockerSupportService.Parameters> {
 
     private static Logger LOGGER = Logging.getLogger(DockerSupportService.class);
+
+    private static String[] DEFAULT_PATH_UNIX = { "/usr/bin", "/usr/local/bin" };
+
+    // Get unix path from PATH env variable, with fallback to DEFAUL_PATH_UNIX
+    private static String[] PATH_UNIX = DockerSupportService.getUnixPath(System.getenv("PATH"), DEFAULT_PATH_UNIX);
```
Comment (reta) [inline buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java]: @WojciechKrakowiak I think using `PATH` (in addition to known location) would be quite valuable, I would suggest to make the implementation a bit more robust, something along these lines https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/utility/CommandLine.java#L51 (so we will cover Windows as well), thank you.

File: buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java [hunk 2]
```diff
@@ -166,12 +156,13 @@ public void execute(Task task) {
             final Integer timeout = ext.has("dockerComposeHttpTimeout") ? (Integer) ext.get("dockerComposeHttpTimeout") : 120;
             composeExtension.getEnvironment().put("COMPOSE_HTTP_TIMEOUT", timeout);
 
-            Optional<String> dockerCompose = Arrays.asList(DOCKER_COMPOSE_BINARIES)
-                .stream()
-                .filter(path -> project.file(path).exists())
-                .findFirst();
+            DockerAvailability dockerAvailability = dockerSupport.get().getDockerAvailability();
```
Comment (reta) [inline buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java]:
```suggestion
            final DockerAvailability dockerAvailability = dockerSupport.get().getDockerAvailability();
            if (dockerAvailability.isAvailable && dockerAvailability.isDockerComposeAvailable()) {
                composeExtension.getExecutable().set(dockerAvailability.dockerComposeAvailability.getPath());
            }

```

Comment (reta) [reply buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java]: We know for sure that if `isDockerComposeAvailable == true`, the `dockerAvailability.dockerComposeAvailability.getPath()` is also set

**Comment by reta** [comment]
@WojciechKrakowiak could you please rebase / merge with latest `main` ? Thank you.

File: buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java (hunk 2 above)
Comment (WojciechKrakowiak) [reply buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java]: Yeah, maybe I oversafeguarded here, fair point.

**Comment by WojciechKrakowiak** [comment]
@reta thank you for the review! :)

**Comment by reta** [comment]
> ❌ Gradle check result for [35fc2e3](https://github.com/opensearch-project/OpenSearch/commit/35fc2e3898f0dbb01cee8da3b3406afd169bd7c7): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/73806/)

```
* What went wrong:
Execution failed for task ':build-tools:spotlessJavaCheck'.
> The following files had format violations:
      src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java
          @@ -43,7 +43,6 @@
           import·org.opensearch.gradle.docker.DockerSupportPlugin;
           import·org.opensearch.gradle.docker.DockerSupportService;
           import·org.opensearch.gradle.docker.DockerSupportService.DockerAvailability;
          -import·org.opensearch.gradle.docker.DockerSupportService.DockerComposeAvailability;
           import·org.opensearch.gradle.docker.DockerSupportService.DockerComposeV2Availability;
           import·org.opensearch.gradle.info.BuildParams;
           import·org.opensearch.gradle.precommit.TestingConventionsTasks;
  Run './gradlew spotlessApply' to fix all violations.

* Try:
```

File: buildSrc/src/main/java/org/opensearch/gradle/util/ExecutableUtils.java [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+        }).findFirst();
+    }
+
+    /**
+     * Find executable with given name in paths defined in PATH environment or in fallback path.
+     * @param executableFileName A filename of executable (with extension included if present).
+     * @param fallbackPath Array of paths where to look for executable if it wasn't found in system PATH.
+     * @return An optional path to found executable.
+     */
+    public static Optional<String> findExecutableInPathWithFallback(String executableFileName, String[] fallbackPath) {
```
Comment (reta) [inline buildSrc/src/main/java/org/opensearch/gradle/util/ExecutableUtils.java]: I think we want to preserve the current logic and try the known path first, and after that inspect PATH, what about:

```
public static Optional<String> findExecutableWithKnownPaths(String executableFileName, String[] knownPaths) {
        String[] mergedPath = mergePaths(knownPaths, getPathEnv());
        return findExecutable(executableFileName, mergedPath);
    }
}
```

File: buildSrc/src/main/java/org/opensearch/gradle/util/ExecutableUtils.java [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+    }
+
+    /**
+     * Find executable with given name in provided paths.
+     * @param executableFileName A filename of executable (with extension included if present).
+     * @param path Array of paths where to look for executable.
+     * @return An optional path to found executable.
+     */
+    public static Optional<String> findExecutable(String executableFileName, String[] path) {
+        return Arrays.stream(path).map(p -> p + getFileSeparator() + executableFileName).filter(p -> {
```
Comment (reta) [inline buildSrc/src/main/java/org/opensearch/gradle/util/ExecutableUtils.java]: Minor, but a bit more straightforward using `Path.of`:

```suggestion
        return Arrays.stream(path).map(p -> Path.of(p, executableFileName)
            .map(Path::toFile)
            .filter(File::exists)
            .filter(File::canExecute)
            .findFirst();
```

**Comment by reta** [comment]
A few minor comments, LGTM otherwise! Thanks a lot @WojciechKrakowiak !

File: buildSrc/src/main/java/org/opensearch/gradle/util/ExecutableUtils.java (hunk 3 above)
Comment (WojciechKrakowiak) [reply buildSrc/src/main/java/org/opensearch/gradle/util/ExecutableUtils.java]: Yeah, I was wondering about that which approach to take. Changes applied.

File: buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java [hunk 5]
```diff
@@ -177,10 +173,11 @@ void failIfDockerUnavailable(List<String> tasks) {
 
         // No Docker binary was located
         if (availability.path == null) {
+            final String[] dockerPaths = ExecutableUtils.mergePaths(ExecutableUtils.getPathEnv(), DEFAULT_PATH);
```
Comment (reta) [inline buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java]: @WojciechKrakowiak apologies, missed this one (aligning with with `ExecutableUtils.findExecutableInKnownPaths`)

```suggestion
            final String[] dockerPaths = ExecutableUtils.mergePaths(DEFAULT_PATH, ExecutableUtils.getPathEnv());
```

**Comment by reta** [comment]
Sandbox failures are unrelated, merging this change

**Comment by lukas-vlcek** [comment]
Thanks!
