### PR TITLE
fix local processed checkpoint update

### LINKED ISSUE #2358: [Segment Replication] Fix replicas to correctly update their processed local checkpoint.
We currently have a bug where replicas are attempting to replicate to checkpoints they are already on.  This is because updating the processedLocalCheckpoint on replicas is ignored.  We currently attempt to increment the sequence number [here](https://github.com/opensearch-project/OpenSearch/blob/b87d5aff26e30bb044b616bb25b241cc09261c8b/server/src/main/java/org/opensearch/index/engine/InternalEngine.java#L347).

This bug can be observed by turning on debug logging and observing the checkpoints receive in `IndexShard.onNewCheckpoint`.

### PR DESCRIPTION
**Pull request by Poojita-Raj**
Signed-off-by: Poojita Raj <poojiraj@amazon.com>

### Description
For segment replication, previously the local processed checkpoint was not being updated. This is now fixed along with unit tests for the same.
 
### Issues Resolved
Resolves #2358 
 
### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java [hunk 1]
```diff
@@ -134,6 +134,29 @@ public synchronized void markSeqNoAsPersisted(final long seqNo) {
...
+        markSegrepSeqNo(seqNo, processedCheckpoint, persistedCheckpoint);
+    }
+
+    @SuppressForbidden(reason = "Object#notifyAll")
+    private void markSegrepSeqNo(final long seqNo, final AtomicLong processedCheckpoint, final AtomicLong persistedCheckpoint) {
+        assert Thread.holdsLock(this);
+        advanceMaxSeqNo(seqNo);
+        if ((seqNo > persistedCheckpoint.get()) || (seqNo <= processedCheckpoint.get())) {
+            return;
+        }
```
Comment (kartg) [inline server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java:152]: A fair amount of this code is duplicated from the existing `markSeqNo` method. Since the first check is simply a bounds check, we can write a `shouldUpdateSeqNo` method that does this and returns a boolean to decide if further processing is necessary. This can be invoked by wrapper methods that perform the update by `compareAndSet` (as below) or via `updateCheckpoint` (as with the original method)

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java [hunk 2]
```diff
@@ -134,6 +134,29 @@ public synchronized void markSeqNoAsPersisted(final long seqNo) {
...
+        try {
+            processedCheckpoint.compareAndSet(processedCheckpoint.get(), seqNo);
```
Comment (kartg) [inline server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java:154]: Shouldn't this be using `updateCheckpoint` to ensure that the `persistedSeqNo` is kept up to date?

File: server/src/test/java/org/opensearch/index/seqno/SegmentReplicationLocalCheckpointTrackerTests.java [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+    }
+
+    @Override
+    @Before
+    public void setUp() throws Exception {
+        super.setUp();
+        tracker = createEmptyTracker();
+    }
+
+    public void testSimpleSegrepPrimaryProcessed() {
```
Comment (kartg) [inline server/src/test/java/org/opensearch/index/seqno/SegmentReplicationLocalCheckpointTrackerTests.java:31]: These should really be 3 separate tests since you're testing different use-cases

1. Base case
2. Idempotency
3. Persisted-vs-processed being out-of-sync, checkpoint update for seg-rep, and finally idempotency again

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java (hunk 2 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java:154]: The call to updateCheckpoint to ensure persistedSeqNo is up to date still takes place when markSeqNoAsPersisted is called. In the case of segrep, we update processedSeqNo just once at the end since indexing doesn't take place on the replica - we omit the call to updateCheckpoint since it checks that all seq numbers till that point are consecutively processed.

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java [hunk 4]
```diff
@@ -134,6 +134,29 @@ public synchronized void markSeqNoAsPersisted(final long seqNo) {
         markSeqNo(seqNo, persistedCheckpoint, persistedSeqNo);
     }
 
+    /**
+     * Updates the processed checkpoint with the provided sequence number if segment replication is enabled
+     *
+     * @param seqNo the sequence number to mark as processed
+     */
+    public synchronized void segrepMarkSeqNoAsProcessed(final long seqNo) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java:142]: A suggestion here, can we name this after what it's doing (fast forwarding to seqNo) vs the replication strategy that invokes it?

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java [hunk 5]
```diff
@@ -131,22 +131,49 @@ public synchronized void markSeqNoAsProcessed(final long seqNo) {
...
+        if (shouldUpdateSeqNo(seqNo, segrep, checkPoint) == false) {
             // this is possible during recovery where we might replay an operation that was also replicated
             return;
         }
-        final CountedBitSet bitSet = getBitSetForSeqNo(bitSetMap, seqNo);
-        final int offset = seqNoToBitSetOffset(seqNo);
-        bitSet.set(offset);
-        if (seqNo == checkPoint.get() + 1) {
-            updateCheckpoint(checkPoint, bitSetMap);
+        if (segrep) {
```
Comment (kartg) [inline server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java:164]: I realize that this was done in response to my comment, but this may be too far in the direction of unification 😄 

What do you think of the following structure?

1. Instead of branching on this boolean value, have this method return the boolean from `shouldUpdateSeqNo` (or in-line that method's logic here). 
2. Have a single method that executes the `else` part of this - both `markSeqNoAsPersisted` and `markSeqNoAsProcessed` can invoke this method. This will cover the existing code flows.
3. Finally, move the `if` clause portion directly  into `fastForwardProcessedSeqNo` - this will cover the seg-rep code flow.

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java [hunk 6]
```diff
@@ -131,22 +131,49 @@ public synchronized void markSeqNoAsProcessed(final long seqNo) {
...
+    /**
+     * Updates the processed checkpoint to the provided sequence number if segment replication is enabled
+     *
+     * @param seqNo the sequence number to mark as processed
+     */
+    public synchronized void fastForwardProcessedSeqNo(final long seqNo) {
+        markSeqNo(seqNo, processedCheckpoint, null, true);
+    }
+
+    private boolean shouldUpdateSeqNo(final long seqNo, boolean segrep, final AtomicLong checkpoint) {
```
Comment (kartg) [inline server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java:146]: As @mch2 alluded to in an earlier comment - if you're having to write variables to model use-cases, then that's usually a sign of an overfit. Consider having this method signature be:

```
private boolean shouldUpdateSeqNo(final long seqNo, final AtomicLong lowerBound, @Nullable final AtomicLong upperBound)
```

Also see my other comment.

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java (hunk 5 above)
Comment (mch2) [inline server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java:164]: I don't think we need this segrep specific logic and it can be inside of `fastForwardProcessedSeqNo ` leaving this method as is.  This class shouldn't care about segrep vs non segrep.  

It also looks like `waitForProcessedOpsToComplete` is called from tests only, I'm not sure we have a use case for it with this call path?  If not then we won't need to wait/notify.

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java (hunk 2 above)
Comment (kartg) [reply server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java]: Thanks for the explanation! I think we should capture this bit in the Javadoc for `fastForwardProcessedSeqNo`:

> In the case of segrep, we update processedSeqNo just once at the end since indexing doesn't take place on the replica - we omit the call to updateCheckpoint since it checks that all seq numbers till that point are consecutively processed.

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java [hunk 7]
```diff
@@ -131,22 +131,49 @@ public synchronized void markSeqNoAsProcessed(final long seqNo) {
...
+        return !((seqNo <= checkpoint.get()) || (segrep && seqNo > persistedCheckpoint.get()));
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java:147]: I think you can put the check against the persisted checkpoint inside of `fastForwardProcessedSeqNo` and avoid the segrep specific flag.

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java (hunk 5 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java]: Removed the wait/notify and separated out the segrep specific logic

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java (hunk 7 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java]: Changed the logic in the check to avoid segrep specific flag

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java (hunk 6 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java]: Followed the signature suggested

File: server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java (hunk 5 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java]: shouldUpdateSeqNo doesn't have the logic to return a boolean representing segrep, but followed the other suggestions to have separate code flows
