### PR TITLE
[Remote Store] Handoff refreshes, translog uploads during relocation from old to new primary

### LINKED ISSUE #11320: [BUG] Close refresh listeners during primary relocation of remote enabled indexes
**Describe the bug**
During the peer recovery relocation, we close Closeable internal refresh listeners. This is present to ensure that we drain all ongoing refreshes before primary hand-off. There is a code bug that is causing the listeners to not close.

https://github.com/opensearch-project/OpenSearch/blob/fe2d58529aacc1270afc49693cc2be95b1b9ef6e/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L860-L864

This has been found by the below check during shard creation.
https://github.com/opensearch-project/OpenSearch/blob/5bb6caec906f9e89d330332ebb74789571409eb1/server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java#L85-L102

**To Reproduce**
Simulate conditions so that there is a retry ongoing in RemoteStoreRefreshListener. The upload can succeed after the new primary mode has started uploading segment and translog files.

**Expected behavior**
The older primary should not upload once the handoff has been done.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by ashking94**
### Description
This PR fixes an edge case during primary relocation that can lead to both existing primary and new primary uploading segments/translog metadata having same combination of primary term, segment info generation, translog generation under following scenarios.
### Situations - 
1. Internal flush triggered during shard inactivity or snapshot just before the primary mode of the existing primary is set to false. This is race condition where the new primary starts itself with generation n, but n+1 generation gets uploaded to remote store by existing primary. 
2. New primary does a syncTranslog in [here](https://github.com/opensearch-project/OpenSearch/blob/5bb6caec906f9e89d330332ebb74789571409eb1/server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java#L256-L259) before actually becoming a primary from cluster manager’s perspective. It is possible that the old primary can continue to be primary due to relocation handoff failure.

This can lead to following impact: 
#### situation no. 1  -
1. Red or Yellow index if the primary or replica shard goes unassigned due to any reasons (like node leaving cluster).
2. Primary relocation failure if there is no indexing happening.

The above can be mitigated by flushing multiple times if the index is not red. This can still be fixed by deleting the metadata file uploaded by old primary.

#### situation no. 2  -
1. In cases where the translog gets uploaded from new primary, but metadata files fails. If a node drop happens, remote store restore will restore a translog that has been overwritten by new primary

The above issue can go away if the indexing continues for some more time.

### Related Issues
Resolves #11320, #11322, #11323

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ashking94** [comment]
Need to validate that we are able to not reproduce the issue mentioned in https://github.com/opensearch-project/OpenSearch/pull/10839

File: server/src/main/java/org/opensearch/index/translog/TranslogManager.java [hunk 1]
```diff
@@ -135,5 +136,10 @@ public interface TranslogManager {
      */
     void onDelete();
 
+    /**
+     * Drains ongoing syncs to the underlying store. It returns a releasable which can be closed to resume the syncs back.
+     */
+    Releasable drainSyncToStore();
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/index/translog/TranslogManager.java:142]: nit: Do we need `ToStore` here? It is implied in `sync`

File: server/src/main/java/org/opensearch/index/translog/Translog.java [hunk 2]
```diff
@@ -1817,6 +1817,13 @@ protected void setMinSeqNoToKeep(long seqNo) {}
 
     protected void onDelete() {}
 
+    /**
+     * Drains ongoing syncs to the underlying store. It returns a releasable which can be closed to resume the syncs back.
+     */
+    protected Releasable drainSyncToStore() {
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/index/translog/Translog.java:1823]: Will local translog use this implementation? In that case, a no-op may not be the expected behavior. Until we get the actual implementation added to local translog, can we throw `NotSupportedException`?

File: server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java [hunk 3]
```diff
@@ -184,23 +187,38 @@ private void scheduleRetry(boolean afterRefreshSuccessful, boolean didRefresh) {
...
     protected abstract Logger getLogger();
 
+    // Made available for unit testing purpose only
+    /**
+     * Returns the timeout which is used while draining refreshes.
+     */
+    protected TimeValue getDrainTimeout() {
+        return DRAIN_TIMEOUT;
+    }
+
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java:221]: Make this package private?

File: server/src/main/java/org/opensearch/index/translog/Translog.java (hunk 2 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/Translog.java]: Local translog will use the above no-op implementation. This code will be executed for non-remote store indexes as well. There are multiple test/ITs failure if we throw exception for local translog case. 

With the no-op implementation, we let the status quo behaviour be there for non-remote store cases. Otherwise we will need to have multiple if else block to run this only for remote indexes.

File: server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java [hunk 4]
```diff
@@ -26,14 +27,16 @@
  * is closed, all the permits are acquired and there are no available permits to afterRefresh. This abstract class provides
  * necessary abstract methods to schedule retry.
  */
-public abstract class CloseableRetryableRefreshListener implements ReferenceManager.RefreshListener, Closeable {
+public abstract class CloseableRetryableRefreshListener implements ReferenceManager.RefreshListener {
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java:30]: Want to rename this to `ReleasableRetryableRefreshListener`

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 5]
```diff
@@ -316,13 +322,13 @@ private boolean prepareAndUpload(Long primaryTerm, Long generation) throws IOExc
...
-        // primary, the engine is reset to InternalEngine which also initialises the RemoteFsTranslog which in turns
-        // downloads all the translogs from remote store and does a flush before the relocation finishes.
-        if (primaryModeSupplier.getAsBoolean() == false) {
-            logger.debug("skipped uploading translog for {} {}", primaryTerm, generation);
+        // During primary relocation, both the old and new primary have engine created with RemoteFsTranslog and having
+        // ReplicationTracker.primaryMode() as true. However, before we perform the `internal:index/shard/replication/segments_sync`
+        // action which re-downloads the segments and translog on the new primary. We are ensuring 2 things here -
+        // 1. Using primaryModeSupplier, we prevent the new primary to do pre-emptive syncs
+        // 2. Using syncPermits, we prevent syncs at the desired time during primary relocation.
+        if (primaryModeSupplier.getAsBoolean() == false || syncPermits.tryAcquire(1) == false) {
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:330]: nit: avoid hard coding use `SYNC_PERMITS`

Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:330]: With these new permits we are strictly serialising the uploads, could it have been possible to have concurrent uploads in the present world?

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 6]
```diff
@@ -423,11 +431,35 @@ protected void setMinSeqNoToKeep(long seqNo) {
...
+                    syncPermits.release(SYNC_PERMITS);
+                    assert syncPermits.availablePermits() == SYNC_PERMITS : "Available permits is " + syncPermits.availablePermits();
+                    logger.info("All permits released");
+                });
+            } else {
+                throw new TimeoutException("Timeout while acquiring all permits");
+            }
+        } catch (TimeoutException | InterruptedException e) {
+            throw new RuntimeException("Failed to acquire all permits", e);
+        }
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:449]: 1. Move logger to debug or provide more context
2. Does 1 min align with SDK retries and timeouts, I doubt?

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 7]
```diff
@@ -896,6 +903,15 @@ public void relocated(
...
             throw new IndexShardClosedException(shardId(), "timed out waiting for relocation hand-off to complete");
+        } finally {
+            // If the primary mode is still true after the end of handoff attempt, it basically means that the relocation
+            // failed. The existing primary will continue to be the primary, so we need to allow the segments and translog
+            // upload to resume.
+            if (replicationTracker.isPrimaryMode()) {
+                for (Releasable releasable : releasablesOnNoHandoff) {
+                    releasable.close();
+                }
+            }
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:914]: Lets use explicit exception block to catch a relocation failure and add an assertion on primary mode

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 8]
```diff
@@ -896,6 +903,15 @@ public void relocated(
...
             failShard("timed out waiting for relocation hand-off to complete", null);
             throw new IndexShardClosedException(shardId(), "timed out waiting for relocation hand-off to complete");
+        } finally {
+            // If the primary mode is still true after the end of handoff attempt, it basically means that the relocation
+            // failed. The existing primary will continue to be the primary, so we need to allow the segments and translog
+            // upload to resume.
+            if (replicationTracker.isPrimaryMode()) {
+                for (Releasable releasable : releasablesOnNoHandoff) {
+                    releasable.close();
+                }
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:913]: You can use the utilitity `Releasables.close`

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 9]
```diff
@@ -857,11 +860,15 @@ public void relocated(
...
-                    .close();
+                // Ensures all in-flight remote store refreshes drain, before we perform the performSegRep.
+                for (ReferenceManager.RefreshListener refreshListener : internalRefreshListener) {
+                    if (refreshListener instanceof CloseableRetryableRefreshListener) {
+                        releasablesOnNoHandoff.add(((CloseableRetryableRefreshListener) refreshListener).drainRefreshes());
+                    }
+                }
+
+                // Ensure all in-flight remote store translog upload drains, before we perform the performSegRep.
+                releasablesOnNoHandoff.add(getEngineOrNull().translogManager().drainSync());
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:871]: It will throw a NPE if engine returned is null, lets handle it explicitly

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 10]
```diff
@@ -845,6 +845,9 @@ public void relocated(
         final Runnable performSegRep
     ) throws IllegalIndexShardStateException, IllegalStateException, InterruptedException {
         assert shardRouting.primary() : "only primaries can be marked as relocated: " + shardRouting;
+        // The below list of releasable ensures that if the relocation does not happen, we undo the activity of close and
+        // acquire all permits. This will ensure that the remote store uploads can still be done by the existing primary shard.
+        List<Releasable> releasablesOnNoHandoff = new ArrayList<>();
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:850]: Initialise with size 2

Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:850]: nit : `releasablesOnAbortHandoff`

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 8 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:913]: Should we move this `release` part to `abortRelocationHandoff` ? This is a much better fit there .

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 11]
```diff
@@ -3883,6 +3899,15 @@ public boolean isRemoteTranslogEnabled() {
...
     }
 
+    /**
+     * This checks if we are in state to upload to remote store. Until the cluster-manager informs the shard through
+     * cluster state, the shard will not be in STARTED state. This method is used to prevent pre-emptive segment or
+     * translog uploads.
+     */
+    public boolean isStartedPrimary() {
+        return getReplicationTracker().isPrimaryMode() && state() == IndexShardState.STARTED;
+    }
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:3909]: will this affect the shards we are initializing from snapshot/remote store restore/local recovery ? As per the code , it shouldn't  . But would be good to double check this .

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 12]
```diff
@@ -3865,10 +3881,10 @@ private EngineConfig newEngineConfig(LongSupplier globalCheckpointSupplier) thro
             circuitBreakerService,
             globalCheckpointSupplier,
             replicationTracker::getRetentionLeases,
-            () -> getOperationPrimaryTerm(),
+            this::getOperationPrimaryTerm,
             tombstoneDocSupplier(),
             isReadOnlyReplica,
-            replicationTracker::isPrimaryMode,
+            this::isStartedPrimary,
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:3887]: Lets rename the argument name from `primaryModeSupplier` to `isStartedPrimary` as well in `EngineConfigFactory` .

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 13]
```diff
@@ -53,7 +57,6 @@
 public class RemoteFsTranslog extends Translog {
 
     private final Logger logger;
-    private final BlobStoreRepository blobStoreRepository;
     private final TranslogTransferManager translogTransferManager;
     private final FileTransferTracker fileTransferTracker;
     private final BooleanSupplier primaryModeSupplier;
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:62]: nit : rename to `startedPrimarySupplier`.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java (hunk 5 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:330]: Concurrent uploads per shard is not possible today due to the write lock and read lock acquired during the sync. The lock sequencing ensures that there is only 1 upload any time.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java (hunk 6 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:449]: For no 1, adding more context in the logs. For no 2, when this method is called during primary relocation, the translog upload has already finished for all indexing that has happened until the indexing block kicked in. This acquire is to ensure that if there is any ongoing internal flush (triggered by flushOnIdle, Snapshot or similar) which has no additional data, should finish before we start the force segrep step on the new primary. This has been set a bit lenient for general happy cases across all possible repository plugin implementation.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java (hunk 5 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:330]: yes, it is possible for concurrent uploads case. However i am not able to find a better way to allow that in the current flow.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 7 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:914]: Added an explicit catch block as suggested. fyi - The primaryMode is the indication for the final handoff status while exiting the below method -
https://github.com/opensearch-project/OpenSearch/blob/5bb6caec906f9e89d330332ebb74789571409eb1/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L848

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 8 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:913]: The abortRelocationHandoff might not run if the failure happens before the control reaches the below code -
https://github.com/opensearch-project/OpenSearch/blob/5bb6caec906f9e89d330332ebb74789571409eb1/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L877-L890

The failures can happen during draining refreshes or translog sync. With this being in finally, we ensure that the rollback step runs irrespective of where the failure occurred.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 11 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:3909]: have planned this already - https://github.com/opensearch-project/OpenSearch/pull/11330/#issuecomment-1826215993

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java (hunk 5 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:330]: @gbbafna How are you deducing that there are concurrent uploads cases? The `upload` method in RemoteFsTranslog is only called by another instance method `prepareAndUpload`. For control to enter inside the method, it needs the write lock which is later downgraded to read lock. Still, as the read lock is acquired, no one else can acquire the write lock so any other upload needs to wait until the current upload is over. 

Let me know if there is any case where we can upload concurrently.

**Comment by ashking94** [comment]
> ❌ Gradle check result for [bdb92d4](https://github.com/opensearch-project/OpenSearch/commit/bdb92d478dc83f7f448dd3e4dc76f845cbc5d58b): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/30386/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky tests - https://github.com/opensearch-project/OpenSearch/issues/10755, https://github.com/opensearch-project/OpenSearch/issues/11258

**Comment by ashking94** [comment]
> ❌ Gradle check result for [37f713a](https://github.com/opensearch-project/OpenSearch/commit/37f713a9f00ae8199c3d192057de77ed1fe126d2): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/30387/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

One flaky test https://github.com/opensearch-project/OpenSearch/issues/5329, and one failure in newly written test. Currently reproducing the failure. Will fix it.

**Comment by ashking94** [comment]
> ❌ Gradle check result for [954a43d](https://github.com/opensearch-project/OpenSearch/commit/954a43dbc5f521783632b05696b2d140520c3a3f): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/30388/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test - https://github.com/opensearch-project/OpenSearch/issues/10006

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 14]
```diff
@@ -3883,6 +3901,15 @@ public boolean isRemoteTranslogEnabled() {
         return indexSettings() != null && indexSettings().isRemoteTranslogStoreEnabled();
     }
 
+    /**
+     * This checks if we are in state to upload to remote store. Until the cluster-manager informs the shard through
+     * cluster state, the shard will not be in STARTED state. This method is used to prevent pre-emptive segment or
+     * translog uploads.
+     */
+    public boolean isStartedPrimary() {
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:3909]: The same check is now used for translog and segments upload both.

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 15]
```diff
@@ -503,11 +502,11 @@ private boolean isReadyForUpload() {
             if (indexShard.getEngineOrNull() != null) {
                 sb.append(" engineType=").append(indexShard.getEngine().getClass().getSimpleName());
             }
-            if (isLocalOrSnapshotRecovery() == false) {
+            if (indexShard.recoveryState() != null) {
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:505]: isLocalOrSnapshotRecovery() checks for recoveryState. recoveryState can be null in which case this check throw NPE. Hence adding this check.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 16]
```diff
@@ -341,10 +348,17 @@ private boolean upload(long primaryTerm, long generation, long maxSeqNo) throws
                 transferSnapshotProvider,
                 new RemoteFsTranslogTransferListener(generation, primaryTerm, maxSeqNo)
             );
+        } finally {
+            syncPermit.release(SYNC_PERMIT);
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:352]: This is deterministic to run if `syncPermit.tryAcquire(SYNC_PERMIT) == false` does not hold true.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 17]
```diff
@@ -341,10 +348,17 @@ private boolean upload(long primaryTerm, long generation, long maxSeqNo) throws
...
         }
 
     }
 
+    // Made available for testing only
+    void induceDelayForTest() {
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:358]: merely for testing a case which otherwise is difficult to test.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 18]
```diff
@@ -505,11 +543,7 @@ public static void cleanup(Repository repository, ShardId shardId, ThreadPool th
     }
 
     protected void onDelete() {
-        if (primaryModeSupplier.getAsBoolean() == false) {
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:508]: The delete is invoked from IndexShard where the primaryMode check is present already.

https://github.com/opensearch-project/OpenSearch/blob/5bb6caec906f9e89d330332ebb74789571409eb1/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L1989-L1992

This code is only triggered in case of index deletion in which case we should let the deletion complete.

Here, we have added to assert that this can only be called by cluster applier thread. Will add a comment as well.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java (hunk 17 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:358]: The way to do this is to use an overridden(mock) version of `RemoteFsTranslog` that induces the delay before the base method invocation

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 19]
```diff
@@ -896,6 +903,17 @@ public void relocated(
...
+        } catch (Exception ex) {
+            logger.warn("exception occurred during relocation hand-off to complete errorMsg={}", ex.getMessage());
+            assert replicationTracker.isPrimaryMode();
+            throw ex;
+        } finally {
+            // If the primary mode is still true after the end of handoff attempt, it basically means that the relocation
+            // failed. The existing primary will continue to be the primary, so we need to allow the segments and translog
+            // upload to resume.
+            if (replicationTracker.isPrimaryMode()) {
+                Releasables.close(releasablesOnHandoffFailures);
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:915]: why can't this be moved to the catch block above?

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java (hunk 15 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:505]: You can always re-add `isLocalOrSnapshotRecovery` after a null check?

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 20]
```diff
@@ -503,11 +502,11 @@ private boolean isReadyForUpload() {
...
                 sb.append(" recoverySourceType=").append(indexShard.recoveryState().getRecoverySource().getType());
                 sb.append(" primary=").append(indexShard.shardRouting.primary());
             }
-            logger.trace(sb.toString());
+            logger.info(sb.toString());
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:509]: Why info?

Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:509]: This is helpful in debugging cases where the refresh listener's refresh method is invoked but it is not ready for upload due to any reason.

Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:509]: There will be very few instances when this will be logged. for eg - create index, failover, relocation. This will not bombard the logs.

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java (hunk 15 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:505]: yes, but we need to log the variables regardless of the final return value.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 21]
```diff
@@ -423,11 +437,35 @@ protected void setMinSeqNoToKeep(long seqNo) {
...
     public void trimUnreferencedReaders() throws IOException {
         // clean up local translog files and updates readers
         super.trimUnreferencedReaders();
 
+        // This is to ensure that after the permits are acquired during primary relocation, there are no further modification on remote
+        // store.
+        if (syncPermit.availablePermits() != SYNC_PERMIT) {
+            return;
+        }
+
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:468]: This can also impact other flows while like when a concurrent upload is happening

File: server/src/main/java/org/opensearch/index/translog/Translog.java [hunk 22]
```diff
@@ -1817,6 +1817,13 @@ protected void setMinSeqNoToKeep(long seqNo) {}
 
     protected void onDelete() {}
 
+    /**
+     * Drains ongoing syncs to the underlying store. It returns a releasable which can be closed to resume the syncs back.
+     */
+    protected Releasable drainSync() {
+        return () -> {}; // noop
+    }
+
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/translog/Translog.java:1826]: Will prefer this abstract and make LocalTranslog noop instead so that new implementors explicitly override this

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 23]
```diff
@@ -489,8 +489,7 @@ private void initializeRemoteDirectoryOnTermUpdate() throws IOException {
      * @return true iff primaryMode is true and index shard is not in closed state.
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:489]: modify the java. doc as well

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 24]
```diff
@@ -516,8 +515,8 @@ private boolean isLocalOrSnapshotRecovery() {
         // In this case when the primary mode is false, we need to upload segments to Remote Store
         // This is required in case of snapshots/shrink/ split/clone where we need to durable persist
         // all segments to remote before completing the recovery to ensure durability.
-
         return (indexShard.state() == IndexShardState.RECOVERING && indexShard.shardRouting.primary())
+            && indexShard.recoveryState() != null
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:519]: `recoveryState` is never null . It is set to `DONE` after the recovery is completed  .

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 25]
```diff
@@ -316,17 +322,18 @@ private boolean prepareAndUpload(Long primaryTerm, Long generation) throws IOExc
...
+        // During primary relocation, both the old and new primary have engine created with RemoteFsTranslog and having
+        // ReplicationTracker.primaryMode() as true. However, before we perform the `internal:index/shard/replication/segments_sync`
+        // action which re-downloads the segments and translog on the new primary. We are ensuring 2 things here -
+        // 1. Using startedPrimarySupplier, we prevent the new primary to do pre-emptive syncs
+        // 2. Using syncPermits, we prevent syncs at the desired time during primary relocation.
+        if (startedPrimarySupplier.getAsBoolean() == false || syncPermit.tryAcquire(SYNC_PERMIT) == false) {
+            logger.debug("skipped uploading translog for {} {} syncPermits={}", primaryTerm, generation, syncPermit.availablePermits());
             // NO-OP
             return true;
         }
```
Comment (gbbafna) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:334]: should we move this to `prepareAndUpload` ? There is no point creating another generation locally , if we can't rotate it .

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java (hunk 24 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:519]: The recoveryState is nullable and is not set in the ctor as well. There is a possibility that recoveryState can be null.

https://github.com/opensearch-project/OpenSearch/blob/74b2d7daf4f5caf42d71724b2dcb745a31e6a884/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L297-L298

https://github.com/opensearch-project/OpenSearch/blob/74b2d7daf4f5caf42d71724b2dcb745a31e6a884/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L2539-L2546

Let me know if you still think it can never be null.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java (hunk 25 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:334]: Do you mean to say `upload` instead of `roatate`?

In context of upload, I will check this a bit more if we can move this check to prepareAndUpload and I think we might have discussed this in the older PR. Also, we might need similar change for segments i.e. prevent segments or segment infos creation if we can't upload.

**Comment by ashking94** [comment]
> ❌ Gradle check result for [2efefd9](https://github.com/opensearch-project/OpenSearch/commit/2efefd97bd933942ef8f443eecce1b67e305c355): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/30405/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test - https://github.com/opensearch-project/OpenSearch/issues/10704 with same stack trace as earlier.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java (hunk 21 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:462]: Used the same approach used in ReleasableRefreshListener. This would not be impacted by concurrent upload now.

**Comment by ashking94** [comment]
> ❌ Gradle check result for [a15e6d6](https://github.com/opensearch-project/OpenSearch/commit/a15e6d6bb564fa7b48c96e193eba2f8c9b8490b5): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/30406/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

flaky test - https://github.com/opensearch-project/OpenSearch/issues/10785 (same assertion failure as reported earlier)

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java (hunk 25 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:336]: This would be tricky for segments as the creation of local segments in not in our control as of now , unlike translog .

**Comment by gbbafna** [comment]
LGTM. Thanks for the changes @ashking94 . Would be merge ready post resolving outstanding comments/issue.

**Comment by ashking94** [comment]
> LGTM. Thanks for the changes @ashking94 . Would be merge ready post resolving outstanding comments/issue.

@gbbafna  The below are the open comments - 
Open comments - https://github.com/opensearch-project/OpenSearch/pull/11330#discussion_r1405429203, https://github.com/opensearch-project/OpenSearch/pull/11330#discussion_r1405181625

@Bukhtawar @sachinpkale  I have addressed your comments. Please take a look.

**Review by gbbafna — APPROVED** [review]

**Comment by ashking94** [comment]
> > LGTM. Thanks for the changes @ashking94 . Would be merge ready post resolving outstanding comments/issue.
> 
> @gbbafna The below are the open comments - Open comments - [#11330 (comment)](https://github.com/opensearch-project/OpenSearch/pull/11330#discussion_r1405429203), [#11330 (comment)](https://github.com/opensearch-project/OpenSearch/pull/11330#discussion_r1405181625)
> 
> @Bukhtawar @sachinpkale I have addressed your comments. Please take a look.

I have resolved all the comments.

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 26]
```diff
@@ -423,11 +433,39 @@ protected void setMinSeqNoToKeep(long seqNo) {
...
+    }
+
     @Override
     public void trimUnreferencedReaders() throws IOException {
         // clean up local translog files and updates readers
         super.trimUnreferencedReaders();
 
+        // This is to ensure that after the permits are acquired during primary relocation, there are no further modification on remote
+        // store.
+        if (pauseSync.get()) {
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:465]: Thinking if we need a check if primary mode started here as well

**Comment by ashking94** [comment]
> ❌ Gradle check result for [61a7fc3](https://github.com/opensearch-project/OpenSearch/commit/61a7fc31a19f6ecfff620a103e56efd66a13cb9c): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/30424/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Known and existing flaky test - https://github.com/opensearch-project/OpenSearch/issues/6542

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java (hunk 26 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java]: Made the change.

**Review by sachinpkale — APPROVED** [review]

**Comment by ashking94** [comment]
> testDelayWithALargeAmountOfShards

Flaky test - https://github.com/opensearch-project/OpenSearch/issues/10558 with same error.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 27]
```diff
@@ -896,6 +903,14 @@ public void relocated(
             // Fail primary relocation source and target shards.
             failShard("timed out waiting for relocation hand-off to complete", null);
             throw new IndexShardClosedException(shardId(), "timed out waiting for relocation hand-off to complete");
+        } catch (Exception ex) {
+            logger.warn("exception occurred during relocation hand-off to complete errorMsg={}", ex.getMessage());
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:907]: logger.error("Exception occurred during relocation hand-off to complete", ex);

Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:907]: Removing this log line as we are throwing the same exception as is. I have verified that the original exception shows up from the logger of `IndicesClusterStateService`. Having same log with complete stack trace twice will only litter the code and logs.

Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java]: resolving this.

**Comment by ashking94** [comment]
> ❕ Gradle check result for [ea629f4](https://github.com/opensearch-project/OpenSearch/commit/ea629f41c25e0bf5015a23594cd24b169b4690e6): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/30490/)
> 
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing
>       1 org.opensearch.cluster.allocation.ClusterRerouteIT.testDelayWithALargeAmountOfShards
> ```
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

Flaky test - https://github.com/opensearch-project/OpenSearch/issues/10558

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 28]
```diff
@@ -267,6 +275,16 @@ public void rollGeneration() throws IOException {
...
+        // During primary relocation, both the old and new primary have engine created with RemoteFsTranslog and having
+        // ReplicationTracker.primaryMode() as true. However, before we perform the `internal:index/shard/replication/segments_sync`
+        // action which re-downloads the segments and translog on the new primary. We are ensuring 2 things here -
+        // 1. Using startedPrimarySupplier, we prevent the new primary to do pre-emptive syncs
+        // 2. Using syncPermits, we prevent syncs at the desired time during primary relocation.
+        if (startedPrimarySupplier.getAsBoolean() == false || syncPermit.tryAcquire(SYNC_PERMIT) == false) {
+            logger.debug("skipped uploading translog for {} {} syncPermits={}", primaryTerm, generation, syncPermit.availablePermits());
+            // NO-OP
+            return false;
+        }
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:287]: Why can't we simply use `ReleasableLock#tryAcquire` to make it consistent with read/write locks instead of introducing new permits?

Comment (ashking94) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:287]: Will be evaluating other sempahores as well and replace with ReleasableLock. Created issue - https://github.com/opensearch-project/OpenSearch/issues/11360

**Comment by ashking94** [comment]
Raising manual backport since the automated one failed.
