### PR TITLE
Bugfix to guard against stack overflow errors caused by very large reg-ex input

### LINKED ISSUE #1992: [BUG] StackOverflow crash - large regex produced by Discover filter not limited by index.regex_max_length
**Describe the bug**
It seems to possible to crash Opensearch nodes by providing a very large string when attempting to filter on a field value (StackOverflow related to regexp processing). When filtering on a field value, a query containing a 'suggestions' aggregation is sent to the cluster in the background before the filter is saved, in order to populate an autocomplete drop down. This aggregation includes a regex which is constructed from taking the large string and suffixing with a ".*" . The resulting regexp does not seem to respect the default index.max_regex_length limit of 1000 - the query is submitted causing an instant crash of nodes.

**To Reproduce**
Reproduced using the latest Opensearch Docker images - 

```
{
  "name" : "opensearch-node1",
  "cluster_name" : "opensearch-cluster",
  "cluster_uuid" : "ftk3wyp1RqOa0Yq5SS4ELA",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.2.4",
    "build_type" : "tar",
    "build_hash" : "e505b10357c03ae8d26d675172402f2f2144ef0f",
    "build_date" : "2022-01-14T03:38:06.881862Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

* load sample data in the dashboard
* in the Discover pane, add a Filter , select a Field, select 'is' , paste a huge string into the search box - 50k chars will do the trick. The node receiving the query will crash.

**Expected behavior**
Expect that the query will be terminated before being allowed to crash the cluster. The bug is present in some versions of Elasticsearch, but does not appear to be present in the latest version (7.16) . It's present in 7.10.2 , the last version tracked before the Opensearch split - so it probably needs to be addressed in the Opensearch codebase now. In Elasticsearch 7.16 the following response is returned - 

`{"_shards":{"total":1,"successful":0,"failed":1,"failures":[{"shard":0,"index":"kibana_sample_data_ecommerce","status":"INTERNAL_SERVER_ERROR","reason":{"type":"broadcast_shard_operation_failed_exception","reason":"java.lang.IllegalArgumentException: input automaton is too large: 1001.......................`

**Plugins**
Nothing additional to default plugins (security etc..) 

**Host/Environment (please complete the following information):**
```
~ ❯❯❯ uname -a
5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

~ ❯❯❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

### PR DESCRIPTION
**Pull request by kartg**
### Description

This change fixes a code path that did not properly impose the index-level max_regex_length limit. Therefore, it was possibly to provide an arbitrarily large string as the include/exclude reg-ex value under search aggregations. This exposed the underlying node to crashes from a StackOverflowError, due to how the Lucene RegExp class processes strings using stack frames.

Signed-off-by: Kartik Ganesh <gkart@amazon.com>
 
### Issues Resolved
closes #1992 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
This is super great work!

**Comment by kartg** [comment]
@dblock should this be backported?

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java [hunk 1]
```diff
@@ -584,26 +577,54 @@ public boolean isPartitionBased() {
         return incNumPartitions > 0;
     }
 
-    private Automaton toAutomaton() {
-        Automaton a = null;
+    private Automaton toAutomaton(@Nullable IndexSettings indexSettings) {
+        int maxRegexLength = indexSettings == null ? -1 : indexSettings.getMaxRegexLength();
```
Comment (andrross) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java:581]: When can index settings be null? Seems like this would result in an odd exception message of "...the allowed maximum of [-1]...".

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java [hunk 2]
```diff
@@ -584,26 +577,54 @@ public boolean isPartitionBased() {
...
+        Automaton a;
         if (include != null) {
-            a = include.toAutomaton();
+            if (include.length() > maxRegexLength) {
+                throw new IllegalArgumentException(
```
Comment (andrross) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java:585]: The exception text is identical in both cases, right? Maybe an opportunity to have a static helper like `validateRegexLength(String regex, IndexSettings settings)` or similar

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java (hunk 1 above)
Comment (kartg) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java:581]: Oops, good catch. This condition should really be:

```
if (maxRegexLength > 0 && include.length() > maxRegexLength) {
```

I'll make this change

Comment (kartg) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java:581]: https://github.com/opensearch-project/OpenSearch/pull/2814

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java (hunk 2 above)
Comment (kartg) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java:585]: https://github.com/opensearch-project/OpenSearch/pull/2814

**Review by dreamer-89 — COMMENTED** [review]
@kartg : Thanks for pulling up this change and fixing the bug in a short time.

I wanted to share one observation I have around search API response, get feedback and decide if we need to track further. The API returns empty successful result instead of an exception when providing a large string (> max_regex_length) in `include` on a random field. I think one way to fix it, is to gate the length check in `AggregatorFactories` where other parsing exceptions are handled (though it would need to index settings reference and is much bigger change). 
Or we can return a response suggesting the referenced field is not found. 

```
curl -X POST "localhost:9200/test-index/_search?pretty" -H "Content-Type: application/json" -d '
{
  "query": {
  	"bool":{"filter":[]}
  },
  "aggs":{"suggestions":{"terms":{"field":"random_field", "include":"<large string>","execution_hint":"map","shard_size":10}}}
}
```
Actual Response: Empty result even though `include` field exceeds `max_regex_length`. 

```
{
    "took": 3,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 0,
            "relation": "eq"
        },
        "max_score": null,
        "hits": []
    },
    "aggregations": {
        "suggestions": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": []
        }
    }
}
```

Expected: Should fail before with max_regex_length exception instead of empty response. 
```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "The length of regex [50001] used in the request has exceeded the allowed maximum of [1000]. This maximum can be set by changing the [index.max_regex_length] index level setting."
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "test-index",
                "node": "w4M35XX3Rtq10akMmt0crg",
                "reason": {
                    "type": "illegal_argument_exception",
                    "reason": "The length of regex [50001] used in the request has exceeded the allowed maximum of [1000]. This maximum can be set by changing the [index.max_regex_length] index level setting."
                }
            }
        ],
        "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "The length of regex [50001] used in the request has exceeded the allowed maximum of [1000]. This maximum can be set by changing the [index.max_regex_length] index level setting.",
            "caused_by": {
                "type": "illegal_argument_exception",
                "reason": "The length of regex [50001] used in the request has exceeded the allowed maximum of [1000]. This maximum can be set by changing the [index.max_regex_length] index level setting."
            }
        }
    },
    "status": 400
}
```

**Comment by kartg** [comment]
@dreamer-89 Discussed here - https://github.com/opensearch-project/OpenSearch/issues/1992#issuecomment-1092186161

Assuming `random_field` is not a valid field on `test-index`, then [this code path does not actually parse](https://github.com/opensearch-project/OpenSearch/blob/996d33adb22ac6a523962166f3677f8dc6ac9c1f/server/src/main/java/org/opensearch/search/aggregations/support/ValuesSourceAggregatorFactory.java#L68-L71) the input string as a `RegExp`. Given that this then [returns an empty aggregation](https://github.com/opensearch-project/OpenSearch/blob/996d33adb22ac6a523962166f3677f8dc6ac9c1f/server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java#L265-L270), this feels like reasonable behavior. Thoughts?

**Comment by dblock** [comment]
@kartg Take a look above, open another issue if you agree

**Comment by kartg** [comment]
@dblock Tracking in #2858

**Comment by jromeroch** [comment]
This fix can be backported to version 1.35? We faced this issue, but currently we can't upgrade as we have some blockers.

**Comment by dblock** [comment]
@jromeroch I think this can qualify, I'll mark it backport 1.x to start, but if auto-backport fails it will need to be done by someone (you?) by hand.

**Comment by jameshinsta** [comment]
My understanding is that this will be included in 1.3.12 as it is marked for backport 1.x. 

Does auto-backport then include all 1.x versions, so we should expect it in 1.3.11?
