### PR TITLE
Reset isPipelineResolved to false to resolve the system ingest pipeline again.

### LINKED ISSUE #18909: [BUG] System ingest pipeline not triggered when request is from a non-ingest node
### Describe the bug

When we have a non-ingest node(e.g. a dedicated master node) receiving an index request with the system ingest pipeline then we will resolve it on that non-ingest node and also create the pipeline. But we will not execute it because it's not an ingest node. We will forward the request to an ingest node. If that ingest node hasn't processed any index request for the same target index before then it will not have the system pipeline in the cache. In that case we will try to resolve the system pipeline again. But we didn't reset the `indexRequest.isPipelineResolved` so we will think the pipeline is already resolved and do no thing.

### Related component

Indexing

### Expected behavior

Even when the index request is forwarded from a non-ingest node to an ingest node the system ingest pipeline should be resolved and created properly.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by bzhangam**
### Description
Reset isPipelineResolved to false to resolve the system ingest pipeline again. If we don't reset it as false we simply skip resolving the pipeline.

### Related Issues
Resolves #18909

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/ingest/IngestService.java [hunk 1]
```diff
@@ -1266,9 +1266,12 @@ private Pipeline getPipeline(
...
         if (IngestPipelineType.SYSTEM_FINAL.equals(pipelineType)) {
             Pipeline indexPipeline = systemIngestPipelineCache.getSystemIngestPipeline(pipelineId);
-            // In very edge case it is possible the cache is invalidated after we resolve the
-            // pipeline. So try to resolve the system ingest pipeline again here.
+            // In some edge cases it is possible the cache is invalidated after we resolve the
+            // pipeline or the request is forwarded from a non-ingest node. In that case we should try to resolve the
+            // system ingest pipeline on this node one more time.
             if (indexPipeline == null) {
+                // reset isPipelineResolved as false so that we can resolve it again
+                indexRequest.isPipelineResolved(false);
```
Comment (owaiskazi19) [inline server/src/main/java/org/opensearch/ingest/IngestService.java:1274]: Would we have to check in the cache if the system pipeline exist and then resolve?

Comment (bzhangam) [reply server/src/main/java/org/opensearch/ingest/IngestService.java:1274]: We first check in the cache and no found. This can happen if the cache is invalidated or this request is forwarded from another non-ingest node since our cache is local node cache. In this case we should try to resolve the pipeline one more time. To do that we need to reset this field otherwise we will do nothing.

Comment (owaiskazi19) [reply server/src/main/java/org/opensearch/ingest/IngestService.java:1274]: I see, can we have a test for this edge case?

Comment (bzhangam) [reply server/src/main/java/org/opensearch/ingest/IngestService.java:1274]: added

File: server/src/main/java/org/opensearch/ingest/SystemIngestPipelineCache.java [hunk 2]
```diff
@@ -83,6 +83,7 @@ private void evictOldestAndExpiredCacheEntry() {
      * @return cached system ingest pipeline
      */
     public Pipeline getSystemIngestPipeline(final String index) {
+        System.out.println(index);
```
Comment (owaiskazi19) [inline server/src/main/java/org/opensearch/ingest/SystemIngestPipelineCache.java]: Leftover?

File: server/src/main/java/org/opensearch/ingest/IngestService.java [hunk 3]
```diff
@@ -1265,10 +1265,15 @@ private Pipeline getPipeline(
     ) {
         final PipelineHolder holder = pipelines.get(pipelineId);
         if (IngestPipelineType.SYSTEM_FINAL.equals(pipelineType)) {
+            System.out.println("[SYSTEM_FINAL] pipeline [" + pipelineId + "] is system final");
```
Comment (owaiskazi19) [inline server/src/main/java/org/opensearch/ingest/IngestService.java]: Here

File: server/src/main/java/org/opensearch/ingest/IngestService.java [hunk 4]
```diff
@@ -1265,10 +1265,15 @@ private Pipeline getPipeline(
...
             Pipeline indexPipeline = systemIngestPipelineCache.getSystemIngestPipeline(pipelineId);
-            // In very edge case it is possible the cache is invalidated after we resolve the
-            // pipeline. So try to resolve the system ingest pipeline again here.
+            // In some edge cases it is possible the cache is invalidated after we resolve the
+            // pipeline or the request is forwarded from a non-ingest node. In that case we should try to resolve the
+            // system ingest pipeline on this node one more time.
             if (indexPipeline == null) {
+                System.out.println("[SYSTEM_FINAL] pipeline [" + pipelineId + "] is not found");
```
Comment (owaiskazi19) [inline server/src/main/java/org/opensearch/ingest/IngestService.java]: And here as well

**Comment by owaiskazi19** [comment]
@bzhangam can you run `./gradlew :server:spotlessApply`, spotless is failing precommit and other checks

**Comment by bzhangam** [comment]
> @bzhangam can you run `./gradlew :server:spotlessApply`, spotless is failing precommit and other checks

fixed
