### PR TITLE
Fix decommission status update to non leader nodes

### LINKED ISSUE #4799: [BUG] [Zone Decommission] MetadataDiff is 0 when publishing cluster state for status update
**Describe the bug**
While updating the decommission status, the cluster state update is not applied to non leader nodes, and the local state of the nodes doesn't receive the status update. The reason being, while executing the cluster state update for decommission status update, the same instance of metadata was being update causing the relative diff to be 0 for non leader nodes and hence, the leader though had the appropriate decommission status but rest of the nodes had a stale decommission state.

**To Reproduce**
1. Execute attribute decommission - `curl -X PUT "localhost:9201/_cluster/decommission/awareness/zone/zone-2?pretty` 
2. Check the local cluster state of any node - `curl -X GET "localhost:9202/_cluster/state?local&pretty"`
3. Check the cluster level cluster state - `curl -X GET "localhost:9202/_cluster/state?pretty"`
4. The cluster state from (3) would have the latest updated the status but cluster state from (2) has status as `INIT`

**Expected behavior**
The latest cluster state and decommission status to be published to all nodes.

### PR DESCRIPTION
**Pull request by imRishN**
### Description
This PR resolves decommission status update metadata bug where in the non leader nodes were not getting status update locally as the same object was updated during submit state update causing the diff to be 0. Detailed explanation can be found in the issue.

### Issues Resolved
#4799 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by anshu1106** [comment]
Thanks @imRishN. Fix looks good to me. Please add tests.

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java [hunk 1]
```diff
@@ -0,0 +1,164 @@
+/*
+ * SPDX-License-Identifier: Apache-2.0
+ *
+ * The OpenSearch Contributors require contributions made to
+ * this file be licensed under the Apache-2.0 license or a
+ * compatible open source license.
+ */
+
+package org.opensearch.cluster.coordination;
```
Comment (imRishN) [inline server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java:9]: Added it in this package as all the integ test for decommissioning the zone need access to pkg private methods of Coordinator.
PR for integ tests - https://github.com/opensearch-project/OpenSearch/pull/4715

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+            );
+        }
+
+        // assert status on decommissioned node
+        // Here we will verify that until it got kicked out, it received appropriate status updates
+        // decommissioned nodes hence will have status as IN_PROGRESS as it will be kicked out later after this
+        // and won't receive status update to SUCCESSFUL
+        String randomDecommissionedNode = randomFrom(clusterManagerNodes.get(2), dataNodes.get(2));
+        ClusterService decommissionedNodeClusterService = internalCluster().getInstance(ClusterService.class, randomDecommissionedNode);
+        assertEquals(
```
Comment (anshu1106) [inline server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java:145]: This is done with the assumption that decommission can take some time and during this check status would mostly be in progress?

Comment (imRishN) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java:145]: No, when the decommissioned nodes were kicked out they would be having status as `IN_PROGRESS`. Status is updated to `SUCCESSFUL` when the decommissioned nodes are kicked out. And hence the last status that decommissioned nodes would be seeing is `IN_PROGRESS`. If not, the test must fail

**Review by anshu1106 — APPROVED** [review]

**Comment by imRishN** [comment]
@Bukhtawar Can you please review this?

File: server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java [hunk 3]
```diff
@@ -79,35 +79,29 @@ public DecommissionStatus status() {
...
      */
     // synchronized is strictly speaking not needed (this is called by a single thread), but just to be safe
-    public synchronized DecommissionAttributeMetadata setUpdatedStatus(DecommissionStatus newStatus) {
-        // if the current status is the expected status already, we return the same instance
-        if (newStatus.equals(status)) {
-            return this;
+    public synchronized void validateNewStatus(DecommissionStatus newStatus) {
+        // if the current status is the expected status already or new status is FAILED, we let the check pass
+        if (newStatus.equals(status) || newStatus.equals(DecommissionStatus.FAILED)) {
+            return;
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java:87]: This is assuming that all steps can have a self-loop for state transitions

Comment (imRishN) [reply server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java:87]: Didn't get this. This is added to ensure that if any step wants to mark the status as `FAILED` during decommission, we will allow it to do so. Let me know if you have any specific case in mind

Comment (imRishN) [reply server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java:87]: And this behaviour is same as before. Had to refactor this method a bit because we were updating the same instance which led to relative diff as 0 for decommission state update

Comment (imRishN) [reply server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java:87]: The self loops which we might come up during multiple concurrent requests is handled seperately as part of this PR https://github.com/opensearch-project/OpenSearch/pull/4684. Today we need status to get into same state as per current service implementation

Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java:87]: The other condition makes it look paranoid

**Review by Bukhtawar — APPROVED** [review]
Lets revisit this as a part of https://github.com/opensearch-project/OpenSearch/pull/4684
