### PR TITLE
Fix AbstractStringFieldDataTestCase tests to account for TotalHits lower bound

### LINKED ISSUE #4238: [BUG] Flakey test failure in SortedSetDVStringFieldDataTests testSortMissingLast
**Describe the bug**

First observed in https://github.com/opensearch-project/OpenSearch/pull/4183#issuecomment-1215586520, but I hit the same failure several times in #4222 and was able to reproduce it locally:

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.fielddata.SortedSetDVStringFieldDataTests.testSortMissingLast" -Dtests.seed=BC7C1431A4F70C5D -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ga-IE -Dtests.timezone=Europe/Belgrade -Druntime.java=17

org.opensearch.index.fielddata.SortedSetDVStringFieldDataTests > testSortMissingLast FAILED
    java.lang.AssertionError: expected:<1105> but was:<1023>
```

**To Reproduce**
See above

**Expected behavior**
Test consistently passes

**Plugins**
None

**Screenshots**
N/A

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by dbwiddis**
Signed-off-by: Daniel Widdis <widdis@gmail.com>

### Description
From Lucene's [`IndexSearcher`](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/IndexSearcher.html?is-external=true) javaDoc:
> NOTE: The [search(org.apache.lucene.search.Query, int)](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/IndexSearcher.html?is-external=true#search(org.apache.lucene.search.Query,int)) and [searchAfter(org.apache.lucene.search.ScoreDoc, org.apache.lucene.search.Query, int)](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/IndexSearcher.html?is-external=true#searchAfter(org.apache.lucene.search.ScoreDoc,org.apache.lucene.search.Query,int)) methods are configured to only count top hits accurately up to 1,000 and may return a [lower bound](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/TotalHits.Relation.html) of the hit count if the hit count is greater than or equal to 1,000. On queries that match lots of documents, counting the number of hits may take much longer than computing the top hits so this trade-off allows to get some minimal information about the hit count without slowing down search too much. 

The `AbstractStringFieldDataTestCase` assumed the `totalHits` value was exact.

This fixes the test to test for either exact accuracy or lower bound, as appropriate.
 
### Issues Resolved
Fixes #4238
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java [hunk 1]
```diff
@@ -340,7 +341,12 @@ public void testSortMissing(boolean first, boolean reverse) throws IOException {
             randomBoolean() ? numDocs : randomIntBetween(10, numDocs),
             new Sort(sortField)
         );
-        assertEquals(numDocs, topDocs.totalHits.value);
+        // As of Lucene 9.0.0, totalHits may be a lower bound
+        if (topDocs.totalHits.relation == TotalHits.Relation.EQUAL_TO) {
+            assertEquals(numDocs, topDocs.totalHits.value);            
+        } else {
+            assertTrue(numDocs >= topDocs.totalHits.value);
```
Comment (owaiskazi19) [inline server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java:348]: Can't we just have 
```
assertTrue(numDocs >= topDocs.totalHits.value); 
```
rather the whole confition?

**Comment by owaiskazi19** [comment]
Pre-commit failing because of the usual Spotless
```
Execution failed for task ':server:spotlessJavaCheck'.
> The following files had format violations:
      src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java
          @@ -343,9 +343,9 @@
           ········);
           ········//·As·of·Lucene·9.0.0,·totalHits·may·be·a·lower·bound
           ········if·(topDocs.totalHits.relation·==·TotalHits.Relation.EQUAL_TO)·{
          -············assertEquals(numDocs,·topDocs.totalHits.value);············
          +············assertEquals(numDocs,·topDocs.totalHits.value);
           ········}·else·{
          -············assertTrue(numDocs·>=·topDocs.totalHits.value);························
          +············assertTrue(numDocs·>=·topDocs.totalHits.value);
           ········}
           ········BytesRef·previousValue·=·first·?·null·:·reverse·?·UnicodeUtil.BIG_TERM·:·new·BytesRef();
           ········for·(int·i·=·0;·i·<·topDocs.scoreDocs.length;·++i)·{

File: server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java (hunk 1 above)
Comment (dbwiddis) [reply server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java:348]: In the test, our total documents (`numDocs`) is not always over 1000, and so it is more precise to test for equality in the 1/3 of cases where a more accurate result will apply.  
https://github.com/opensearch-project/OpenSearch/blob/05a58192433f6e007ade61b4b4f21d0f068d50e0/server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java#L261

This will protect against a bug where `totalHits` is always some small constant like 1, which would pass the lower bound test.

Comment (dbwiddis) [reply server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java:348]: (I might argue we could add another assertion that `totalHits.value >= 1000` in this case, but that might be overkill.)

**Review by owaiskazi19 — APPROVED** [review]

File: server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java (hunk 1 above)
Comment (nknize) [reply server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java]: Agree it's overkill...

**Review by nknize — APPROVED** [review]
LGTM! Thx for adding this check @dbwiddis! I had completely forgot about this change.

**Comment by heemin32** [comment]
Shouldn't we back port this PR to 2.x branch?

**Comment by dblock** [comment]
I labeled it to backport, let's see.

**Comment by dblock** [comment]
@dbwiddis Looking at the implementation here: not in love with conditions in specs. When is it one or the other?

**Comment by dbwiddis** [comment]
> @dbwiddis Looking at the implementation here: not in love with conditions in specs. When is it one or the other?

@dblock answering nearly two years later, sorry.  The initial PR comment javadoc explains the difference.  Lucene can comute the hit count and if it's > 1000 it makes it an approximate bound, indicated by the enum used for the conditional.
