### PR TITLE
Prevent setting maxParallelForks=0 on single-cpu machines

### LINKED ISSUE #554: [BUG] Cannot run OpenSearch "A problem occurred evaluating project ':benchmarks'."
**Describe the bug**
The gradle run process is not working. I have tried on clean installations of Ubuntu 20.04.02 and 20.10

**To Reproduce**
1. Install ubuntu version
2. apt install git openfdk-14-jre
3. git clone https://github.com/opensearch-project/OpenSearch.git
4. ./gradlew --stacktrace run 
 (works as expected, downloaded Gradle 6.6.1)

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jkowall/opensearch/OpenSearch/benchmarks/build.gradle' line: 40

* What went wrong:
A problem occurred evaluating project ':benchmarks'.
> Could not create task ':benchmarks:test'.
   > Cannot set maxParallelForks to a value less than 1.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':benchmarks'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
```

**Expected behavior**
Expected compile and run to work

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 20.04.02 and 20.10

### PR DESCRIPTION
**Pull request by rmuir**
The maxParallelForks is currently numJavaCpus / 2, but this evaluates to zero (illegal value) if numJavaCpus is 1 and breaks the build.

Remove large chunk of complex dead code above this calculation, as it is always overwritten by the simple calculation anyway.

Closes #554

Signed-off-by: Robert Muir <rmuir@apache.org>

### CODE REVIEW

**Comment by rmuir** [comment]
The checkstyle failed, but the output doesn't tell me what's wrong: looks like a potential improvement to these automated checks? It would be great if it ran with --info or whatever is needed to see the issue? I'll try to run it locally and somehow provoke more output myself.

**Review by nknize — APPROVED** [review]
LGTM

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
> The checkstyle failed, but the output doesn't tell me what's wrong: looks like a potential improvement to these automated checks? It would be great if it ran with --info or whatever is needed to see the issue? I'll try to run it locally and somehow provoke more output myself.

run `./gradlew spotlessApply`

**Comment by rmuir** [comment]
> run `./gradlew spotlessApply` it should take care of it

@nknize It was the unused imports (see above 2nd commit). When I ran the task locally it printed what I need to know, probably because I set `org.gradle.console=verbose` in my `~/.gradle/gradle.properties` 

But for some reason the log from the CI builds here don't run with enough verbosity to tell the end-user what they need to fix. Could we increase verbosity to make it easier on contributors?

File: buildSrc/src/main/java/org/opensearch/gradle/info/GlobalBuildInfoPlugin.java [hunk 1]
```diff
@@ -298,47 +292,7 @@ private static int findDefaultParallel(Project project) {
         // Since it costs IO to compute this, and is done at configuration time we want to cache this if possible
```
Comment (adnapibar) [inline buildSrc/src/main/java/org/opensearch/gradle/info/GlobalBuildInfoPlugin.java:292]: Remove this comment line? Otherwise LGTM.

Comment (rmuir) [reply buildSrc/src/main/java/org/opensearch/gradle/info/GlobalBuildInfoPlugin.java:292]: thanks, indeed this is outdated now.

**Comment by adnapibar** [comment]
start gradle check
