### PR TITLE
[Segment Replication] Trigger a round of replication for replica shards during peer recovery when segment replication is enabled

### LINKED ISSUE #5313: [BUG][Segment Replication] With Segment Replication enabled new Replica shards are falling behind Primary until an operation happens on index
**Describe the bug**
With Segment Replication enabled when a new replica shard is recovered/created/added to an existing cluster, then replica shards don't get a checkpoint (latest segments) from primary until an operation is performed on index. So, replica will fall behind until a new operation happens on index.

Explanation:
-> In Ideal Segment Replication scenario, when a refresh happens on index and if a new reference is opened (happens only after some operation on index) then primary shard publishes checkpoint to replicas and send segment files for replica's to catch up.

-> But in case of new replica shards added to existing cluster, replicas don't receive any checkpoint from primary until an operation (index/update/delete) happens on index. Even if we manually refresh the index, a new reference will not opened until an operation (index/update/delete) happens on index and checkpoint is never published from primary to replica. So replica will fall behind.

**To Reproduce**
1. Start a cluster and create a new index with a primary shard.
2. Insert some documents into the index
3. Add new replica shard to existing cluster.
4. Search for docs inserted in step 2 on new replica.
5. Search on new replica will return empty even though documents are inserted successfully and present on primary.

**Expected behavior**
-> Search for documents on replica should not be empty if they are successfully inserted before.

**Expected Solution**
-> In segment replication when a new replica shard is added to existing cluster, it goes through process of peer recovery and finally mark it as STARTED.
-> After peer recovery is completed and before shard is marked as STARTED, we have to force new replica shard to start a round of replication (segment replication) to fetch latest segment files from primary shard. Then after this replication event is completed then we should mark the shard as STARTED.
-> This way replica shard will have all the latest segment files before it is STARTED and ready to be searched.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR adds logic of triggering a round of replication during peer recovery before shard is marked as STARTED. It fixes the bug of newly added replica shards falling behind primary shard until an operation is performed on index when segment replication is enabled. More detail about bug is present on issue #5313.

### Solution used to fix bug
With segment replication enabled when a new replica is added to cluster it goes through peer recovery process. During this recovery process after peer recovery process is completed and before replica shard is marked as STARTED, we are triggering a replication event from replica to copy all latest segment from primary shard.

### Issues Resolved
Resolves #5313 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 1]
```diff
@@ -194,6 +197,48 @@ public void testCancelPrimaryAllocation() throws Exception {
...
+        final String node_1 = internalCluster().startNode();
+
+        logger.info("--> creating test index ...");
+        prepareCreate(INDEX_NAME, Settings.builder().put("index.number_of_shards", 1).put("index.number_of_replicas", 1)).get();
+
+        logger.info("--> index 10 docs");
+        for (int i = 0; i < 10; i++) {
+            client().prepareIndex(INDEX_NAME).setId(Integer.toString(i)).setSource("field", "value" + i).execute().actionGet();
+        }
+        logger.info("--> flush so we have an actual index");
```
Comment (dreamer-89) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:216]: Did you mean by `actual index` -> `segment files on disk` ?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 2]
```diff
@@ -194,6 +197,48 @@ public void testCancelPrimaryAllocation() throws Exception {
...
     }
 
+    /**
+     * This test adds a new replica shard to an existing cluster which already has few docs inserted before adding replica.
+     * We don't perform any refresh on index and assert new replica shard on doc hit count.
+     * This test makes sure that when a new replica is added to an existing cluster it gets all latest segments from primary even without a refresh.
+     */
+    public void testAddNewReplica() throws Exception {
+        logger.info("--> starting [node1] ...");
+        final String node_1 = internalCluster().startNode();
```
Comment (dreamer-89) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:207]: nit: Usually I find it better to call nodes by their role. This makes it easier to understand when we perform any node specific actions (e.g. restart(primary), stop (replica) etc). Otherwise, we need to look back when node_i was created and its role.

File: server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java [hunk 3]
```diff
@@ -774,7 +780,52 @@ public synchronized void handleRecoveryFailure(ShardRouting shardRouting, boolea
...
     public void handleRecoveryDone(ReplicationState state, ShardRouting shardRouting, long primaryTerm) {
         RecoveryState RecState = (RecoveryState) state;
-        shardStateAction.shardStarted(shardRouting, primaryTerm, "after " + RecState.getRecoverySource(), SHARD_STATE_ACTION_LISTENER);
+        AllocatedIndex<? extends Shard> indexService = indicesService.indexService(shardRouting.shardId().getIndex());
+        IndexShard indexShard = (IndexShard) indexService.getShardOrNull(shardRouting.id());
+        // For Segment Replication enabled indices, we want replica shards to start a replication event to fetch latest segments before it
+        // is marked as Started.
+        if (indexShard.indexSettings().isSegRepEnabled()
+            && shardRouting.primary() == false
+            && ShardRoutingState.RELOCATING != shardRouting.state()) {
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:789]: Should this condition be `ShardRoutingState.STARTED == shardRouting.state()` ? Existing condition applies for UNASSIGNED and INITIALIED shards, is that correct ?

File: server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java [hunk 4]
```diff
@@ -774,7 +780,52 @@ public synchronized void handleRecoveryFailure(ShardRouting shardRouting, boolea
...
+                    logger.trace(
+                        () -> new ParameterizedMessage(
+                            "[shardId {}] [replication id {}] Replication failed, timing data: {}",
+                            indexShard.shardId().getId(),
+                            state.getReplicationId(),
+                            state.getTimingData()
+                        )
+                    );
+                    if (sendShardFailure == true) {
+                        logger.error("replication failure", e);
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:820]: nit: These are logged at debug level on failShard call. May be we can remove it from here

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 1 above)
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:216]: Yes, let me change the terminology here. `actual index` might be confusing.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 2 above)
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:207]: Sure, makes sense. I will rename both nodes accordingly

**Comment by andrross** [comment]
Minor, but I would change the commit message/PR title to explain _what_ you've done, as opposed to the side effect you're fixing. Something like "Trigger a round of replication during recovery" or whatever makes sense. In the description you can describe the bug you're fixing and any other details, but the message header should be a clear and concise description of what is changed.

**Comment by Rishikesh1159** [comment]
> Minor, but I would change the commit message/PR title to explain _what_ you've done, as opposed to the side effect you're fixing. Something like "Trigger a round of replication during recovery" or whatever makes sense. In the description you can describe the bug you're fixing and any other details, but the message header should be a clear and concise description of what is changed.

Thanks @andrross for pointing out. Sure, what you said makes sense. I will update the commit message and PR title.

**Review by dreamer-89 — APPROVED** [review]
Thanks @Rishikesh1159 for this quick fix. LGTM!

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 5]
```diff
@@ -194,6 +197,48 @@ public void testCancelPrimaryAllocation() throws Exception {
         assertSegmentStats(REPLICA_COUNT);
     }
 
+    /**
+     * This test adds a new replica shard to an existing cluster which already has few docs inserted before adding replica.
+     * We don't perform any refresh on index and assert new replica shard on doc hit count.
+     * This test makes sure that when a new replica is added to an existing cluster it gets all latest segments from primary even without a refresh.
+     */
+    public void testAddNewReplica() throws Exception {
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:205]: This test is very similar to `testStartReplicaAfterPrimaryIndexesDocs`, can we reuse that test?  That test currently indexes a doc after the replica is recovered to force another round of replication, but you could assert the doc count is sync'd on line 412 after ensureGreen().

**Review by mch2 — CHANGES_REQUESTED** [review]
a few small changes required here - particularly the null check in `handleRecoveryDone`

File: server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java [hunk 6]
```diff
@@ -774,7 +781,61 @@ public synchronized void handleRecoveryFailure(ShardRouting shardRouting, boolea
 
     public void handleRecoveryDone(ReplicationState state, ShardRouting shardRouting, long primaryTerm) {
         RecoveryState RecState = (RecoveryState) state;
-        shardStateAction.shardStarted(shardRouting, primaryTerm, "after " + RecState.getRecoverySource(), SHARD_STATE_ACTION_LISTENER);
+        AllocatedIndex<? extends Shard> indexService = indicesService.indexService(shardRouting.shardId().getIndex());
+        IndexShard indexShard = (IndexShard) indexService.getShardOrNull(shardRouting.id());
+        // For Segment Replication enabled indices, we want replica shards to start a replication event to fetch latest segments before it
+        // is marked as Started.
+        if (indexShard.indexSettings().isSegRepEnabled()
```
[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:788]: Sure, I will add null check.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 7]
```diff
@@ -194,6 +197,48 @@ public void testCancelPrimaryAllocation() throws Exception {
...
+        logger.info("--> starting [Primary Node] ...");
+        final String primary = internalCluster().startNode();
+
+        logger.info("--> creating test index ...");
+        prepareCreate(INDEX_NAME, Settings.builder().put("index.number_of_shards", 1).put("index.number_of_replicas", 1)).get();
```
[the remark this answers is not in the document]
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:210]: Yes sure

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 5 above)
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:205]: Yes, I think you right. Let me see if we can reuse it

File: server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java (hunk 6 above)
Comment (mch2) [inline server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:788]: You could also read the setting from indexSettings before fetching a reference to the IndexShard.

`indexService.getIndexSettings().isSegRepEnabled()`.

File: server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java [hunk 8]
```diff
@@ -774,7 +781,61 @@ public synchronized void handleRecoveryFailure(ShardRouting shardRouting, boolea
...
+                            () -> new ParameterizedMessage(
+                                "[shardId {}] [replication id {}] Replication failed, timing data: {}",
+                                indexShard.shardId().getId(),
+                                state.getReplicationId(),
+                                state.getTimingData()
+                            )
+                        );
+                        if (sendShardFailure == true) {
+                            logger.error("replication failure", e);
+                            indexShard.failShard("replication failure", e);
```
Comment (mch2) [inline server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:830]: I think we can reuse `handleRecoveryFailure` here instead of this added block.

Comment (mch2) [reply server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:830]: Err sorry I'm off here, we'll need both `indexShard.failShard("replication failure", e);` that fails the engine, followed by `handleRecoveryFailure` which removes the shard.

Comment (mch2) [reply server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:830]: On that note - could you pls add test here for the failure case?

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:830]: Yes this is important. Thanks for catching this. I will update it and an unit/integ test for failure case.

File: server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java (hunk 6 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:788]: Sure I can add that

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 9]
```diff
@@ -194,6 +199,65 @@ public void testCancelPrimaryAllocation() throws Exception {
...
+        }
+        logger.info("--> flush so we have some segment files on disk");
+        client().admin().indices().prepareFlush().execute().actionGet();
+        logger.info("--> index more docs so we have something in the translog");
+        for (int i = 10; i < 20; i++) {
+            client().prepareIndex(INDEX_NAME).setId(Integer.toString(i)).setSource("field", "value" + i).execute().actionGet();
+        }
+
+        logger.info("--> verifying count");
+        client().admin().indices().prepareRefresh().execute().actionGet();
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:227]: nit - you can call ` refresh(INDEX_NAME);`

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 10]
```diff
@@ -194,6 +199,65 @@ public void testCancelPrimaryAllocation() throws Exception {
...
+        ClusterHealthResponse clusterHealthResponse = client().admin()
+            .cluster()
+            .prepareHealth()
+            .setWaitForEvents(Priority.LANGUID)
+            .setWaitForNodes("2")
+            .setWaitForGreenStatus()
+            .setTimeout(TimeValue.timeValueSeconds(2))
+            .execute()
+            .actionGet();
+        assertThat(clusterHealthResponse.isTimedOut(), equalTo(true));
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:255]: nit - `assertTrue(clusterHealthResponse.isTimedOut());` and `assertFalse(indicesService.hasIndex(resolveIndex(INDEX_NAME)));`

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 11]
```diff
@@ -194,6 +199,65 @@ public void testCancelPrimaryAllocation() throws Exception {
...
+        for (int i = 10; i < 20; i++) {
+            client().prepareIndex(INDEX_NAME).setId(Integer.toString(i)).setSource("field", "value" + i).execute().actionGet();
+        }
+
+        logger.info("--> verifying count");
+        client().admin().indices().prepareRefresh().execute().actionGet();
+        assertThat(client().prepareSearch(INDEX_NAME).setSize(0).execute().actionGet().getHits().getTotalHits().value, equalTo(20L));
+
+        logger.info("--> start replica node");
+        final String replica = internalCluster().startNode();
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:231]: as soon as this is invoked the node will start & shard will recover, I think we may hit a rare race condition here where the sendBehavior is not added before the shard starts recovery/replication?

What about starting 2 nodes with no replicas so you can configure the send behavior.  Then adding a second replica with:
```
        assertAcked(
            client().admin()
                .indices()
                .prepareUpdateSettings(INDEX_NAME)
                .setSettings(Settings.builder().put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, 1))
        );
```

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 9 above)
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:227]: sure will make that change

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 10 above)
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:255]: sure will make that change

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 11 above)
Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:231]: can you elaborate a bit more on what is sendBehavior not getting added. You mean that node might be still starting and not ready to make transport service to other nodes in cluster ?

Comment (Rishikesh1159) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java]: Synced up with @mch2  offline. As there is possibility of flakiness if replica shard starts before sendBehavior logic hits, I am moving adding replica after the sendBehavior logic. Thanks @mch2 for pointing this out.

File: server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java [hunk 12]
```diff
@@ -773,8 +780,77 @@ public synchronized void handleRecoveryFailure(ShardRouting shardRouting, boolea
...
+            } else {
+                shardStateAction.shardStarted(
+                    shardRouting,
+                    primaryTerm,
+                    "after " + recoveryState.getRecoverySource(),
+                    SHARD_STATE_ACTION_LISTENER
+                );
+            }
+        } else {
+            shardStateAction.shardStarted(
```
Comment (mch2) [inline server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:847]: Nit - this is now invoked 3x. You could clean this up by using a StepListener that when completes marks the shard started.

**Review by mch2 — APPROVED** [review]
Only a nit so approving. Thanks for this change.

File: server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java (hunk 12 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java:847]: Thanks @mch2 sure I can do that
