### PR TITLE
Fix the script sort related ITs

### LINKED ISSUE #8510: [Concurrent Segment Search] Fix Sort related ITs
Subtask for #7357 to focus on Sort related failures

```
org.opensearch.search.sort.FieldSortIT.testScriptFieldSort
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.sort.FieldSortIT.testScriptFieldSort" -Dtests.seed=F657C804A435520E -Dtests.locale=cs -Dtests.timezone=Pacific/Auckland -Druntime.java=17

java.lang.AssertionError: 
Expected: <0.0>
     but: was <2.0>
Expected :<0.0>
Actual   :<2.0>
<Click to see difference>


	at __randomizedtesting.SeedInfo.seed([F657C804A435520E:DB88407EB070FA46]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.search.sort.FieldSortIT.testScriptFieldSort(FieldSortIT.java:1993)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

```
org.opensearch.search.sort.SimpleSortIT.testSimpleSorts
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.search.sort.SimpleSortIT.testSimpleSorts" -Dtests.seed=DC7EE9541460FD12 -Dtests.locale=es-NI -Dtests.timezone=America/Campo_Grande -Druntime.java=17

java.lang.AssertionError: 
Expected: "1"
     but: was "2"
Expected :1
Actual   :2
<Click to see difference>


	at __randomizedtesting.SeedInfo.seed([DC7EE9541460FD12:9E050C9C2006810C]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.opensearch.search.sort.SimpleSortIT.testSimpleSorts(SimpleSortIT.java:216)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

### PR DESCRIPTION
**Pull request by neetikasinghal**
### Description
Solves the sort related ITs

### Related Issues
Resolves #8510 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java [hunk 1]
```diff
@@ -355,32 +357,35 @@ private IndexFieldData.XFieldComparatorSource fieldComparatorSource(QueryShardCo
...
                 return new BytesRefFieldComparatorSource(null, null, valueMode, nested) {
-                    StringSortScript leafScript;
+                    // introducing a map to keep a mapping between the leaf reader context and leaf script
+                    // such that the functions of the class are thread safe in case of concurrent search
+                    final Map<LeafReaderContext, StringSortScript> leafContextSortScriptMap = new ConcurrentHashMap<>();
 
                     @Override
                     protected SortedBinaryDocValues getValues(LeafReaderContext context) throws IOException {
-                        leafScript = searchScript.newInstance(context);
+                        StringSortScript leafScript = searchScript.newInstance(context);
```
Comment (sohami) [inline server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java:366]: `final StringSortScript leafScript`

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java [hunk 2]
```diff
@@ -355,32 +357,35 @@ private IndexFieldData.XFieldComparatorSource fieldComparatorSource(QueryShardCo
...
+                        leafContextSortScriptMap.put(context, leafScript);
                         final BinaryDocValues values = new AbstractBinaryDocValues() {
                             final BytesRefBuilder spare = new BytesRefBuilder();
 
                             @Override
                             public boolean advanceExact(int doc) throws IOException {
-                                leafScript.setDocument(doc);
+                                leafContextSortScriptMap.get(context).setDocument(doc);
```
Comment (sohami) [inline server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java:373]: we can use the `final` instance here instead of fetching from map

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java [hunk 3]
```diff
@@ -355,32 +357,35 @@ private IndexFieldData.XFieldComparatorSource fieldComparatorSource(QueryShardCo
...
                                 return true;
                             }
 
                             @Override
                             public BytesRef binaryValue() {
-                                spare.copyChars(leafScript.execute());
+                                spare.copyChars(leafContextSortScriptMap.get(context).execute());
```
Comment (sohami) [inline server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java:379]: same to use `final` instance

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java [hunk 4]
```diff
@@ -403,29 +408,32 @@ public BucketedSort newBucketedSort(
...
                 return new DoubleValuesComparatorSource(null, Double.MAX_VALUE, valueMode, nested) {
-                    NumberSortScript leafScript;
+                    // introducing a map to keep a mapping between the leaf reader context and leaf script
+                    // such that the functions of the class are thread safe in case of concurrent search
+                    final Map<LeafReaderContext, NumberSortScript> leafContextSortScriptMap = new ConcurrentHashMap<>();
 
                     @Override
                     protected SortedNumericDoubleValues getValues(LeafReaderContext context) throws IOException {
-                        leafScript = numberSortScript.newInstance(context);
+                        NumberSortScript leafScript = numberSortScript.newInstance(context);
```
Comment (sohami) [inline server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java:417]: similar change to use `final` and use that for other methods

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java (hunk 3 above)
Comment (neetikasinghal) [reply server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java]: done

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java (hunk 4 above)
Comment (neetikasinghal) [reply server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java]: done

**Review by sohami — APPROVED** [review]

**Comment by neetikasinghal** [comment]
@reta waiting for your review.

**Comment by sohami** [comment]
> @reta waiting for your review.

@reta planning to merge it today unless you have some feedback.

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java [hunk 5]
```diff
@@ -355,11 +357,14 @@ private IndexFieldData.XFieldComparatorSource fieldComparatorSource(QueryShardCo
...
                 return new BytesRefFieldComparatorSource(null, null, valueMode, nested) {
-                    StringSortScript leafScript;
+                    // introducing a map to keep a mapping between the leaf reader context and leaf script
+                    // such that the functions of the class are thread safe in case of concurrent search
+                    final Map<LeafReaderContext, StringSortScript> leafContextSortScriptMap = new ConcurrentHashMap<>();
 
                     @Override
                     protected SortedBinaryDocValues getValues(LeafReaderContext context) throws IOException {
-                        leafScript = searchScript.newInstance(context);
+                        final StringSortScript leafScript = searchScript.newInstance(context);
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java:366]:
```suggestion
final StringSortScript leafScript = leafContextSortScriptMap.computeIfEmpty(context,  context -> searchScript.newInstance(context);
```

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java [hunk 6]
```diff
@@ -403,11 +408,14 @@ public BucketedSort newBucketedSort(
...
                 return new DoubleValuesComparatorSource(null, Double.MAX_VALUE, valueMode, nested) {
-                    NumberSortScript leafScript;
+                    // introducing a map to keep a mapping between the leaf reader context and leaf script
+                    // such that the functions of the class are thread safe in case of concurrent search
+                    final Map<LeafReaderContext, NumberSortScript> leafContextSortScriptMap = new ConcurrentHashMap<>();
 
                     @Override
                     protected SortedNumericDoubleValues getValues(LeafReaderContext context) throws IOException {
-                        leafScript = numberSortScript.newInstance(context);
+                        final NumberSortScript leafScript = numberSortScript.newInstance(context);
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java:417]: Same here, we are better off with computeIfAbsent

**Comment by reta** [comment]
> > @reta waiting for your review.
> 
> @reta planning to merge it today unless you have some feedback.

@neetikasinghal sincere apologies, added few comments but LGTM as approach (have nothing better to suggest)

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java (hunk 5 above)
Comment (neetikasinghal) [reply server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java]: done

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java (hunk 6 above)
Comment (neetikasinghal) [reply server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java]: done

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java [hunk 7]
```diff
@@ -403,11 +413,19 @@ public BucketedSort newBucketedSort(
...
+                    final Map<LeafReaderContext, NumberSortScript> leafContextSortScriptMap = new ConcurrentHashMap<>();
 
                     @Override
                     protected SortedNumericDoubleValues getValues(LeafReaderContext context) throws IOException {
-                        leafScript = numberSortScript.newInstance(context);
+                        final NumberSortScript leafScript = leafContextSortScriptMap.computeIfAbsent(context, ctx -> {
+                            try {
+                                return numberSortScript.newInstance(ctx);
+                            } catch (IOException e) {
+                                throw new RuntimeException(e);
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java:426]:
```suggestion
                                throw new UncheckedIOException(e);
```

File: server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java [hunk 8]
```diff
@@ -355,11 +357,19 @@ private IndexFieldData.XFieldComparatorSource fieldComparatorSource(QueryShardCo
...
+                    final Map<LeafReaderContext, StringSortScript> leafContextSortScriptMap = new ConcurrentHashMap<>();
 
                     @Override
                     protected SortedBinaryDocValues getValues(LeafReaderContext context) throws IOException {
-                        leafScript = searchScript.newInstance(context);
+                        final StringSortScript leafScript = leafContextSortScriptMap.computeIfAbsent(context, ctx -> {
+                            try {
+                                return searchScript.newInstance(ctx);
+                            } catch (IOException e) {
+                                throw new RuntimeException(e);
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java:370]:
```suggestion
                                throw new UncheckedIOException(e);
```

**Review by reta — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/BytesRefFieldComparatorSource.java [hunk 9]
```diff
@@ -134,9 +134,11 @@ protected SortedDocValues getSortedDocValues(LeafReaderContext context, String f
         }
 
         return new FieldComparator.TermValComparator(numHits, null, sortMissingLast) {
+            LeafReaderContext leafReaderContext;
 
             @Override
             protected BinaryDocValues getBinaryDocValues(LeafReaderContext context, String field) throws IOException {
+                leafReaderContext = context;
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/BytesRefFieldComparatorSource.java:141]: This is the only place that concerns: the `getBinaryDocValues` could be called from multiple index searcher / search threads, right?

Comment (neetikasinghal) [reply server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/BytesRefFieldComparatorSource.java:141]: the `getBinaryDocValues` is called by the `getLeafComparator` which is called during the initialization of the `TopFieldLeafCollector` (instance of this is created per leaf) - we should be fine here.
