### PR TITLE
Ignore BaseRestHandler unconsumed content check as it's always consumed

### LINKED ISSUE #13011: [BUG] The RestController always consumes content when handling real HTTP requests
TLDR:
 - Behavior was added in https://github.com/opensearch-project/OpenSearch/commit/687978b7d167d4c20a29861b2558b2749c349529 to reject REST requests containing a body, that did not use that body, in January 2019.
 - That behavior was inadvertently disabled for real-world HTTP-sourced requests in https://github.com/opensearch-project/OpenSearch/commit/1cd464d675b3cc3fd478b5b530b2d3a316bc2c6b in August 2019 but remained enabled in testing with mocked clients.
 - Unit tests remain from the first commit, and new tests written for Flow Framework demonstrate that the unit-tested behavior does not match the actual behavior (this is the bug)
 - Solutions involve reverting the first change (since it's effectively disabled, and a poor design IMO) or enabling the first change's intended behavior (which could break a lot of scripts unknowingly relying on the existing behavior). I favor the reverting option but want feedback first.

### Describe the bug

The `BaseRestHandler` includes a check whether content (the REST body) has been consumed by an API, throwing an exception here if it does not do so:

https://github.com/opensearch-project/OpenSearch/blob/c25b00c6b62fd6766999c09fd06dd1f7b281b3eb/server/src/main/java/org/opensearch/rest/BaseRestHandler.java#L125-L127

This exception is tested in OpenSearch [in a few places](https://github.com/search?q=repo%3Aopensearch-project%2FOpenSearch%20%22does%20not%20support%20having%20a%20body%22&type=code).

Unfortunately, it appears that these unit tests which rely on the behavior of the `BaseRestHandler` do not take into account the fact that the `RestController` always consumes content here when a REST request arrives via the HTTP handler:
https://github.com/opensearch-project/OpenSearch/blob/2dc071ff2546b0c6483b9e0a382badf9ac353cdc/server/src/main/java/org/opensearch/rest/RestController.java#L296

It appears that in an actual cluster handling HTTP requests, the above exception is dead code.  

However, it is actively tested directly calling the Rest Handler without using the Rest Controller code path which reads the content.

This is confusing to developers, undocumented and inconsistent behavior, and leads to incorrect assumptions, ultimately returning a confusing 500 error code to end users without any hint of why.

### Related component

Other

### To Reproduce

1. Run OpenSearch with the Flow Framework plugin installed, which relied on this exception handling
2. Query a workflow that does not support a body, but include a body in the request, for example
```json
localhost:9200/_plugins/_flow_framework/workflow/any_id_here
{}
```
3. Get this response:
```json
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_state_exception",
                "reason": "Channel is already closed"
            }
        ],
        "type": "illegal_state_exception",
        "reason": "Channel is already closed"
    },
    "status": 500
}
```

### Expected behavior

Given the multiple tests of the error message, one would suggest the expected behavior is a 400-series REST response with error message: "request [GET /_plugins/_flow_framework/workflow/{workflow_id}] does not support having a body"

However, testing the other OpenSearch APIs with unit tests for this behavior, it appears they silently ignore the body.  In particular, [the commit which added the exception](https://github.com/opensearch-project/OpenSearch/commit/687978b7d167d4c20a29861b2558b2749c349529) indicated that it should have triggered on deleting an index while including a body.

Given that this behavior has existed for 5 years, and the exception was only put in a year before that, and there are probably many hundreds (thousands? millions?) of scripts which might break if we restore the "tested" expected behavior, it seems that perhaps users should "expect" the presence of a body to be silently ignored.

### Additional Details

**Plugins**

Reproduced with only the Flow Framework plugin installed as reported in https://github.com/opensearch-project/flow-framework/issues/638

**Additional context**

I'm happy to submit a PR to "fix" this but would like some input from other maintainers on how they'd like it fixed.  I see two options:

1. In the REST controller content length check, use the overload that does not consume the content, e.g.,
```java
final int contentLength = request.content(false).length();
```
This will restore the "intended" behavior and probably break scripts worldwide.

2. Delete the consumed content check entirely and remove any tests that rely on it; explicitly code this behavior if desired; or appropriately document that content is ignored.

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description

Removes the `BaseRestHandler` check for unconsumed content added in https://github.com/opensearch-project/OpenSearch/commit/687978b7d167d4c20a29861b2558b2749c349529 as this check was inadvertently made dead code (when using real HttpRequests and not mocked ones) in https://github.com/opensearch-project/OpenSearch/commit/1cd464d675b3cc3fd478b5b530b2d3a316bc2c6b

### Related Issues
Resolves #13011 
Related to https://github.com/opensearch-project/flow-framework/issues/638

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- ~[ ] New functionality has been documented.~ (This behavior was undocumented and remains so.)
  - ~[ ] New functionality has javadoc added~ (No new functionality)
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~ (This behavior was undocumented and remains so.)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/rest/BaseRestHandler.java [hunk 1]
```diff
@@ -122,9 +122,8 @@ public final void handleRequest(RestRequest request, RestChannel channel, NodeCl
             throw new IllegalArgumentException(unrecognized(request, unconsumedParams, candidateParams, "parameter"));
         }
 
-        if (request.hasContent() && request.isContentConsumed() == false) {
-            throw new IllegalArgumentException("request [" + request.method() + " " + request.path() + "] does not support having a body");
-        }
+        // ignore whether content is consumed
+        // https://github.com/opensearch-project/OpenSearch/issues/13011
```
Comment (peternied) [inline server/src/main/java/org/opensearch/rest/BaseRestHandler.java:126]: Nit: I'd rather remove the comment to keep the file cleaner (nothing to see here!) If folks are interested in new behavior they can look at the commit history

**Review by peternied — APPROVED** [review]

**Review by kkmr — APPROVED** [review]

**Review by cwperks — COMMENTED** [review]
LGTM!

File: server/src/main/java/org/opensearch/rest/BaseRestHandler.java [hunk 2]
```diff
@@ -122,10 +122,6 @@ public final void handleRequest(RestRequest request, RestChannel channel, NodeCl
             throw new IllegalArgumentException(unrecognized(request, unconsumedParams, candidateParams, "parameter"));
         }
 
-        if (request.hasContent() && request.isContentConsumed() == false) {
-            throw new IllegalArgumentException("request [" + request.method() + " " + request.path() + "] does not support having a body");
-        }
-
```
Comment (owaiskazi19) [inline server/src/main/java/org/opensearch/rest/BaseRestHandler.java:128]: Do we also have to remove this check from [other files](https://github.com/search?q=repo%3Aopensearch-project%2FOpenSearch%20request.hasContent()&type=code) as well?

Comment (peternied) [reply server/src/main/java/org/opensearch/rest/BaseRestHandler.java:128]: I don't see any other references `request.hasContent()` still seems valid use case to me.

Comment (dbwiddis) [reply server/src/main/java/org/opensearch/rest/BaseRestHandler.java:128]: It's possible some plugins use those methods so I deliberately chose not to revert the entire commit and just "intentionally ignore behavior that was already ignored accidentally".   Devs should still be allowed to enforce body-related checks in their plugins if they want, they just shouldn't expect OpenSearch to do it for them.

**Review by owaiskazi19 — APPROVED** [review]
