### PR TITLE
Fix NPE in ConcurrentQueryProfile while computing the breakdown map for slices

### LINKED ISSUE #9815: [Concurrent Segment Search][BUG] org.opensearch.search.profile.query.QueryProfilerIT.testProfileQuery {p0={"search.concurrent_segment_search.enabled":"true"} p1=true} is flaky
**Describe the bug**

The test case org.opensearch.search.profile.query.QueryProfilerIT.testProfileQuery {p0={"search.concurrent_segment_search.enabled":"true"} p1=true} is flaky:

```
Failed to execute phase [query], all shards failed; shardFailures {[NozaKKq8RO29Gdqj-Bi9WQ][test][0]: RemoteTransportException[[node_s4][127.0.0.1:41257][indices:data/read/search[phase/query]]]; nested: NullPointerException[Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null]; }{[jmngMMEcTbqleNF9QtB2ZA][test][1]: RemoteTransportException[[node_s3][127.0.0.1:37065][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute concurrent segment search thread]]; nested: NotSerializableExceptionWrapper[assertion_error: null]; }{[NozaKKq8RO29Gdqj-Bi9WQ][test][2]: RemoteTransportException[[node_s4][127.0.0.1:41257][indices:data/read/search[phase/query]]]; nested: NullPointerException[Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null]; }
```

```
Failed to execute phase [query], all shards failed; shardFailures {[NozaKKq8RO29Gdqj-Bi9WQ][test][0]: RemoteTransportException[[node_s4][127.0.0.1:41257][indices:data/read/search[phase/query]]]; nested: NullPointerException[Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null]; }{[jmngMMEcTbqleNF9QtB2ZA][test][1]: RemoteTransportException[[node_s3][127.0.0.1:37065][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute concurrent segment search thread]]; nested: NotSerializableExceptionWrapper[assertion_error: null]; }{[NozaKKq8RO29Gdqj-Bi9WQ][test][2]: RemoteTransportException[[node_s4][127.0.0.1:41257][indices:data/read/search[phase/query]]]; nested: NullPointerException[Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null]; }
	at __randomizedtesting.SeedInfo.seed([E0A359380AF3E50D:1B83BAD4F773DAEC]:0)
	at app//org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:677)
	at app//org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:373)
	at app//org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:716)
	at app//org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:485)
	at app//org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:295)
	at app//org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104)
	at app//org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:75)
	at app//org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:749)
	at app//org.opensearch.transport.TransportService$6.handleException(TransportService.java:875)
	at app//org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1483)
	at app//org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:421)
	at app//org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341)
	at app//org.opensearch.transport.InboundHandler.handleException(InboundHandler.java:419)
	at app//org.opensearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:411)
	at app//org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:159)
	at app//org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:115)
	at app//org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:767)
	at app//org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175)
	at app//org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150)
	at app//org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115)
	at app//org.opensearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:341)
	at app//org.opensearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:246)
	at app//org.opensearch.nio.BytesChannelContext.read(BytesChannelContext.java:59)
	at app//org.opensearch.nio.EventHandler.handleRead(EventHandler.java:152)
	at app//org.opensearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:167)
	at app//org.opensearch.nio.NioSelector.handleRead(NioSelector.java:438)
	at app//org.opensearch.nio.NioSelector.processKey(NioSelector.java:264)
	at app//org.opensearch.nio.NioSelector.singleLoop(NioSelector.java:191)
	at app//org.opensearch.nio.NioSelector.runLoop(NioSelector.java:148)
	at java.base@20.0.2/java.lang.Thread.run(Thread.java:1623)
Caused by: OpenSearchException[Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null]; nested: NullPointerException[Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null];
	at app//org.opensearch.OpenSearchException.guessRootCauses(OpenSearchException.java:708)
	at app//org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:371)
	... 28 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null
	at org.opensearch.search.profile.query.ConcurrentQueryProfileBreakdown.buildSliceLevelBreakdown(ConcurrentQueryProfileBreakdown.java:185)
	at org.opensearch.search.profile.query.ConcurrentQueryProfileBreakdown.toBreakdownMap(ConcurrentQueryProfileBreakdown.java:83)
	at org.opensearch.search.profile.query.ConcurrentQueryProfileTree.createProfileResult(ConcurrentQueryProfileTree.java:43)
	at org.opensearch.search.profile.query.ConcurrentQueryProfileTree.createProfileResult(ConcurrentQueryProfileTree.java:24)
	at org.opensearch.search.profile.AbstractInternalProfileTree.doGetTree(AbstractInternalProfileTree.java:183)
	at org.opensearch.search.profile.AbstractInternalProfileTree.doGetTree(AbstractInternalProfileTree.java:174)
	at org.opensearch.search.profile.AbstractInternalProfileTree.doGetTree(AbstractInternalProfileTree.java:174)
	at org.opensearch.search.profile.AbstractInternalProfileTree.getTree(AbstractInternalProfileTree.java:155)
	at org.opensearch.search.profile.query.ConcurrentQueryProfileTree.getTree(ConcurrentQueryProfileTree.java:73)
	at org.opensearch.search.profile.AbstractProfiler.getTree(AbstractProfiler.java:69)
	at org.opensearch.search.profile.SearchProfileShardResults.buildShardResults(SearchProfileShardResults.java:202)
	at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:162)
	at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:546)
	at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:610)
	at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:579)
	at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74)
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1623)
```

**To Reproduce**

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.profile.query.QueryProfilerIT" -Dtests.method="testProfileMatchesRegular {p0={"search.concurrent_segment_search.enabled":"true"} p1=true}" -Dtests.seed=E0A359380AF3E50D 
```

**Expected behavior**

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
[Add any other context about the problem here.](https://build.ci.opensearch.org/job/gradle-check/24535/testReport/junit/org.opensearch.search.profile.query/QueryProfilerIT/testProfileQuery__p0___search_concurrent_segment_search_enabled___true___p1_true_/)

@ticheng-aws this is another one, but this time it is NPE, please take a look

### PR DESCRIPTION
**Pull request by sohami**
### Description

There can be cases where one or more slice may not have timing related information for its leaves in contexts map. During creation of slice and query level breakdown map it needs to handle such cases by using default values correctly. Also updating the min/max/avg sliceNodeTime to not include time to create weight and wait times by slice threads. It will reflect the min/max/avg execution time of each slice whereas totalNodeTime will reflect the total query time.

### Related Issues
Resolves #9815 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sohami** [comment]
@ticheng-aws @reta Can you please help with review.

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java [hunk 1]
```diff
@@ -182,15 +189,24 @@ Map<Collector, Map<String, Long>> buildSliceLevelBreakdown(long createWeightStar
...
+                    currentSliceBreakdown.getOrDefault(timingTypeSliceEndTimeKey, 0L) - currentSliceBreakdown.getOrDefault(
+                        timingTypeSliceStartTimeKey,
+                        0L
+                    )
                 );
             }
-            // currentSliceNodeTime includes the create weight time as well which will be same for all the slices
-            long currentSliceNodeTime = sliceMaxEndTime - createWeightStartTime;
+            // currentSliceNodeTime does not include the create weight time, as that is computed in non-concurrent part
+            long currentSliceNodeTime = (sliceMaxEndTime == Long.MIN_VALUE && sliceMinStartTime == Long.MAX_VALUE)
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:207]: We probably should use || here to make sure both values are properly calculated:

```suggestion
            long currentSliceNodeTime = (sliceMaxEndTime == Long.MIN_VALUE || sliceMinStartTime == Long.MAX_VALUE)
```

**Comment by ticheng-aws** [comment]
We need to update CHANGELOG.md as well.

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java [hunk 2]
```diff
@@ -73,14 +73,14 @@ public Map<String, Long> toBreakdownMap() {
             // If there are no leaf contexts, then return the default concurrent query level breakdown, which will include the
             // create_weight time/count
             queryNodeTime = createWeightTime;
-            maxSliceNodeTime = queryNodeTime;
-            minSliceNodeTime = queryNodeTime;
-            avgSliceNodeTime = queryNodeTime;
+            maxSliceNodeTime = 0;
+            minSliceNodeTime = 0;
+            avgSliceNodeTime = 0;
```
Comment (ticheng-aws) [inline server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:78]: nit: 
```
maxSliceNodeTime = 0L;
minSliceNodeTime = 0L;
avgSliceNodeTime = 0L;
```

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java (hunk 1 above)
Comment (sohami) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:207]: @reta May be I can add an assert before this that we expect both the variables to be set with valid values or both to  have default values.

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java [hunk 3]
```diff
@@ -234,7 +250,7 @@ public Map<String, Long> buildQueryBreakdownMap(
 
             long queryTimingTypeEndTime = Long.MIN_VALUE;
             long queryTimingTypeStartTime = Long.MAX_VALUE;
-            long queryTimingTypeCount = 0L;
+            long queryTimingTypeCount = 0;
```
[the remark this answers is not in the document]
Comment (sohami) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:253]: didn't see a need to be explicit with 0L as type already denotes that.

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java [hunk 4]
```diff
@@ -276,17 +292,27 @@ public Map<String, Long> buildQueryBreakdownMap(
...
+                    queryTimingTypeEndTime,
+                    sliceBreakdown.getValue().getOrDefault(sliceEndTimeForTimingType, Long.MIN_VALUE)
+                );
+                queryTimingTypeStartTime = Math.min(
+                    queryTimingTypeStartTime,
+                    sliceBreakdown.getValue().getOrDefault(sliceStartTimeForTimingType, Long.MAX_VALUE)
+                );
                 queryTimingTypeCount += sliceBreakdownTypeCount;
             }
+            assert queryTimingTypeStartTime != Long.MAX_VALUE && queryTimingTypeEndTime != Long.MIN_VALUE : "Unexpected queryTimingType "
```
[the remark this answers is not in the document]
Comment (sohami) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:305]: This is an assert which is verifying that both variables are set to non default values as we expect this function to be called only when there is valid leaf contexts for slices.

**Review by ticheng-aws — APPROVED** [review]

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java (hunk 1 above)
Comment (reta) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:207]: Sure, please be aware the assertions could be turned off, so you still have to properly check the conditions

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (reta) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:305]: @sohami  assertions are great but they could be turned off, so for calculation you should better check the conditions nonetheless since no exception will be raised but bogus results returned.

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (reta) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:253]: @sohami why are you changing that?

File: server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdownTests.java [hunk 5]
```diff
@@ -269,9 +268,67 @@ public void testBreakDownMapWithMultipleSlices() throws Exception {
...
+        final long createWeightEndTime = createWeightEarliestStartTime + createWeightTimer.getApproximateTiming();
+        final Map<String, Long> leafProfileBreakdownMap_1 = getLeafBreakdownMap(createWeightEndTime + 10, 10, 1);
+        final AbstractProfileBreakdown<QueryTimingType> leafProfileBreakdown_1 = new TestQueryProfileBreakdown(
+            QueryTimingType.class,
+            leafProfileBreakdownMap_1
+        );
+        testQueryProfileBreakdown.associateCollectorToLeaves(sliceCollector_1, directoryReader.leaves().get(0));
+        testQueryProfileBreakdown.associateCollectorToLeaves(sliceCollector_2, directoryReader.leaves().get(1));
+        testQueryProfileBreakdown.getContexts().put(directoryReader.leaves().get(0), leafProfileBreakdown_1);
+        // leaf2 profile breakdown is not present in contexts map
```
Comment (ticheng-aws) [inline server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdownTests.java:293]: nit: We can clean up this comment.

Comment (sohami) [reply server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdownTests.java:293]: kept it purposefully to highlight that leaf corresponding to collector 2 doesn't have context in the `contexts` map

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (sohami) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java]: Have added the check here and above to throw `exception` instead to return 0 in these unexpected use cases. Returning `0` will be same as returning bogus values and can hide these cases

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (sohami) [reply server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java]: no specific reason. but have reverted this and made other usage consistent with 0L notation.

File: server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java [hunk 6]
```diff
@@ -182,15 +190,36 @@ Map<Collector, Map<String, Long>> buildSliceLevelBreakdown(long createWeightStar
...
-            long currentSliceNodeTime = sliceMaxEndTime - createWeightStartTime;
+            // currentSliceNodeTime does not include the create weight time, as that is computed in non-concurrent part
+            long currentSliceNodeTime;
+            if (sliceMinStartTime == Long.MAX_VALUE && sliceMaxEndTime == Long.MIN_VALUE) {
+                currentSliceNodeTime = 0L;
+            } else if (sliceMinStartTime == Long.MAX_VALUE || sliceMaxEndTime == Long.MIN_VALUE) {
+                throw new OpenSearchException(
+                    "Unexpected value of sliceMinStartTime ["
+                        + sliceMinStartTime
+                        + "] and sliceMaxEndTime ["
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java:215]: Super nit:

```suggestion
                        + "] or sliceMaxEndTime ["
```

Similarly with `queryTimingTypeStartTime`

**Comment by sohami** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:**  ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/25965/
> * **CommitID:** [9fb011c](https://github.com/opensearch-project/OpenSearch/commit/9fb011cb3bb769f0385c14e40b8c5b5e9a8e1ed0)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

All known issues: 
https://github.com/opensearch-project/OpenSearch/issues/5030
https://github.com/opensearch-project/OpenSearch/issues/10133

**Comment by reta** [comment]
@sohami I understand the frustration regarding failing checks but we should not merge pull requests that have them failed

**Comment by ticheng-aws** [comment]
Resolves https://github.com/opensearch-project/OpenSearch/issues/9869
