### PR TITLE
Skip remote-repositories validations for node-joins when RepositoriesService is not in sync with cluster-state

### LINKED ISSUE #16762: [BUG] Commit Failures During Node Joins with Repositories Configured Result in Persistent NullPointerExceptions
### Issue Overview
During node joins, when a new node containing new repository metadata joins the cluster, the cluster-manager attempts to publish the updated cluster state that includes the node and its metadata. While during this update if the publish operation succeeds and the commit fails due to other issues (like network disruption or joining leader in term), it leads to a persistent cycle of `NullPointerExceptions` which prevents the cluster to become stable. This is because as part of the publish, the last accepted version and cluster state are updated but due to commits not run, the cluster-state appliers are not executed. This results in the repositories service not in sync with the repositories metadata in the cluster state. Now when the current cluster-manager (leader) steps down and another cluster-manager is elected:

1. The newly elected cluster-manager attempts to verify repository metadata as part of its leadership transition.
2. It checks the metadata in the cluster state for the presence of a specific repository. If the repository exists, it attempts to fetch its corresponding object from the repository service.
3. Since the repository service was not updated earlier (due to the cluster appliers not being executed), this leads to a `NullPointerException`, causing instability in the cluster-manager election and transition process.

[Logs from IT used to repro the issue]
```
[2024-12-03T17:32:27,926][INFO ][o.o.c.c.JoinHelper       ] [node_t0] failed to join {node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true}, minimumTerm=1, optionalJoin=Optional[Join{term=2, lastAcceptedTerm=1, lastAcceptedVersion=8, sourceNode={node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true}, targetNode={node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true}}]}
org.opensearch.transport.RemoteTransportException: [node_t0][127.0.0.1:50328][internal:cluster/coordination/join]
Caused by: java.lang.NullPointerException: Cannot invoke "org.opensearch.repositories.Repository.getRestrictedSystemRepositorySettings()" because "repository" is null
	at org.opensearch.repositories.RepositoriesService.ensureValidSystemRepositoryUpdate(RepositoriesService.java:907) ~[main/:?]
	at org.opensearch.node.remotestore.RemoteStoreNodeService.updateRepositoriesMetadata(RemoteStoreNodeService.java:194) ~[main/:?]
	at org.opensearch.cluster.coordination.JoinTaskExecutor.execute(JoinTaskExecutor.java:210) ~[main/:?]
	at org.opensearch.cluster.coordination.JoinHelper$1.execute(JoinHelper.java:197) ~[main/:?]
	at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:917) ~[main/:?]
	at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:469) ~[main/:?]
	at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:329) [main/:?]
	at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:229) [main/:?]
	at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:206) [main/:?]
	at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:264) [main/:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:932) [main/:?]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:283) [main/:?]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:246) [main/:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```

### Related component

Cluster Manager

### To Reproduce

1. Create a cluster without repositories configured and allow it to become stable.
2. Start a new node with repositories configured
3. Disrupt the cluster-manager by allowing the publish to succeed and the commit to fail

### Expected behavior

1. The repository service should remain in sync with the cluster state, even if a commit failure occurs during node joins.
2. The newly elected cluster-manager should initialise without errors and correctly fetch repository objects.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu-S**
### Description

During node joins, when a new node containing new repository metadata joins the cluster, the cluster-manager attempts to publish the updated cluster state that includes the node and its metadata. While during this update if the publish operation succeeds and the commit fails due to other issues (like network disruption or joining leader in term), it leads to a persistent cycle of NullPointerExceptions which prevents the cluster to become stable. This is because as part of the publish, the last accepted version and cluster state are updated but due to commits not run, the cluster-state appliers are not executed. This results in the repositories service not in sync with the repositories metadata in the cluster state. Now when the current cluster-manager (leader) steps down and another cluster-manager is elected:

1. The newly elected cluster-manager attempts to verify repository metadata as part of its leadership transition.
2. It checks the metadata in the cluster state for the presence of a specific repository. If the repository exists, it attempts to fetch its corresponding object from the repository service.
3. Since the repository service was not updated earlier (due to the cluster appliers not being executed), this leads to a NullPointerException, causing instability in the cluster-manager election and transition process.

### Related Issues
Resolves #16762

### Check List
- [x] Functionality includes testing.
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~~
- ~~[] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Pranshu-S** [comment]
Flaky - [Test Result](https://build.ci.opensearch.org/job/gradle-check/51109/testReport/) (1 failure / +1)
[org.opensearch.cluster.MinimumClusterManagerNodesIT.testThreeNodesNoClusterManagerBlock](https://build.ci.opensearch.org/job/gradle-check/51109/testReport/junit/org.opensearch.cluster/MinimumClusterManagerNodesIT/testThreeNodesNoClusterManagerBlock/)

File: server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java [hunk 1]
```diff
@@ -183,6 +183,17 @@ public RepositoriesMetadata updateRepositoriesMetadata(DiscoveryNode joiningNode
                 boolean repositoryAlreadyPresent = false;
                 for (RepositoryMetadata existingRepositoryMetadata : existingRepositories.repositories()) {
                     if (newRepositoryMetadata.name().equals(existingRepositoryMetadata.name())) {
+                        // This is to handle cases where-in the during a previous node-join attempt if the publish operation succeeded but
+                        // the commit operation failed, the cluster-state may have the repository metadata which is not applied into the
+                        // repository service. This may lead to assertion failures down the line.
+                        if (!repositoriesService.get().isRepositoryPresent(newRepositoryMetadata.name())) {
```
Comment (soosinha) [inline server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java:189]: Should we validate the the repositories using the metadata in cluster state instead of fetching from repositories service ?

Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java]: I think the following method `ensureValidSystemRepositoryUpdate` fetches the repository object corresponding to the repo name and validates the `RestrictedSystemRepositorySettings` corresponding to the same. I believe we would need the repositories from the RepositoryService to validate.

[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java]: Since the existing meta-data is not applied to the repository service, it will not cause any discrepancies in such cases.

File: server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java [hunk 2]
```diff
@@ -250,4 +260,87 @@ public void testNodeNotReachableFromClusterManager() throws Exception {
         ensureStableCluster(3);
     }
 
+    /**
+     * Test Repositories Configured Node Join Commit failures.
+     */
+    public void testElectClusterManagerRemotePublicationConfigurationNodeJoinCommitFails() throws Exception {
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java:271]:
```
OpenSearch % ./gradlew ':server:internalClusterTest' --tests "org.opensearch.discovery.DiscoveryDisruptionIT.testElectClusterManagerRemotePublicationConfigurationNodeJoinCommitFails" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar -Dtests.timezone=Atlantic/Stanley -Dtests.iters=500 

> Configure project :
========================= WARNING =========================
         Backwards compatibility tests are disabled!
See https://github.com/opensearch-project/OpenSearch/issues/4173
===========================================================
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.11.1
  OS Info               : Mac OS X 15.1 (aarch64)
  JDK Version           : 21 (Oracle JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
  Random Testing Seed   : ED7FEC2998B4451C
  In FIPS 140 mode      : false
=======================================

> Task :server:internalClusterTest
WARNING: Using incubator modules: jdk.incubator.vector


BUILD SUCCESSFUL in 16m 21s
59 actionable tasks: 1 executed, 58 up-to-date

````

File: server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java [hunk 3]
```diff
@@ -183,6 +184,21 @@ public RepositoriesMetadata updateRepositoriesMetadata(DiscoveryNode joiningNode
                 boolean repositoryAlreadyPresent = false;
                 for (RepositoryMetadata existingRepositoryMetadata : existingRepositories.repositories()) {
                     if (newRepositoryMetadata.name().equals(existingRepositoryMetadata.name())) {
+                        try {
+                            // This is to handle cases where-in the during a previous node-join attempt if the publish operation succeeded
+                            // but
+                            // the commit operation failed, the cluster-state may have the repository metadata which is not applied into the
+                            // repository service. This may lead to assertion failures down the line.
+                            String repositoryName = newRepositoryMetadata.name();
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java:192]: local variable can be removed

File: server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java [hunk 4]
```diff
@@ -183,6 +184,21 @@ public RepositoriesMetadata updateRepositoriesMetadata(DiscoveryNode joiningNode
                 boolean repositoryAlreadyPresent = false;
                 for (RepositoryMetadata existingRepositoryMetadata : existingRepositories.repositories()) {
                     if (newRepositoryMetadata.name().equals(existingRepositoryMetadata.name())) {
+                        try {
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java:187]: Can the `try` block combined with the existing `try` in line#215

File: test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java [hunk 5]
```diff
@@ -2322,10 +2322,24 @@ public List<String> startNodes(int numOfNodes, Settings settings) {
         return startNodes(Collections.nCopies(numOfNodes, settings).toArray(new Settings[0]));
     }
 
+    /**
+     * Starts multiple nodes with the given settings and returns their names
+     */
+    public List<String> startNodes(int numOfNodes, Settings settings, Boolean ignoreNodeJoin) {
```
Comment (rajiv-kv) [inline test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java:2328]: nit: can be named as `waitForNodeJoin`

File: server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java [hunk 6]
```diff
@@ -250,4 +263,112 @@ public void testNodeNotReachableFromClusterManager() throws Exception {
...
+            Repository routingTableRepo = repositoriesService.repository(remoteRoutingTableRepoName);
+            if (Objects.nonNull(routingTableRepo)) {
+                isRemoteRoutingTableRepoConfigured = Boolean.TRUE;
+            }
+        } catch (RepositoryMissingException e) {
+            isRemoteRoutingTableRepoConfigured = Boolean.FALSE;
+        }
+
+        Assert.assertTrue("RemoteState Repo is not set in RepositoryService", isRemoteStateRepoConfigured);
+        Assert.assertTrue("RemoteRoutingTable Repo is not set in RepositoryService", isRemoteRoutingTableRepoConfigured);
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java:369]: is this code repeated ?

File: server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java [hunk 7]
```diff
@@ -250,4 +263,112 @@ public void testNodeNotReachableFromClusterManager() throws Exception {
...
+                }
+                connection.sendRequest(requestId, action, request, options);
+            });
+        });
+
+        logger.info("Starting Node with remote publication settings");
+        // Start a node with remote-publication repositories configured. This will lead to the active cluster-manager create
+        // a new cluster-state event with the new node-join along with new repositories setup in the cluster meta-data.
+        internalCluster().startDataOnlyNodes(1, remotePublicationSettings, Boolean.TRUE);
+
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java:313]: Should we wait until the existing cluster-manager steps down due to failure in commits ?

Comment (Pranshu-S) [reply server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java:314]: Updated the test to ensure it is not flaky

File: server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java (hunk 6 above)
Comment (Pranshu-S) [reply server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java]: Simplified

File: test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java (hunk 5 above)
Comment (Pranshu-S) [reply test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java]: Updated

File: server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java (hunk 4 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java:187]: I think its better to keep it separate for better readability? Also I don't think we should couple the skip flow with the execution/validation flow

File: server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java (hunk 3 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java]: Updated

File: server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java [hunk 8]
```diff
@@ -183,6 +184,21 @@ public RepositoriesMetadata updateRepositoriesMetadata(DiscoveryNode joiningNode
...
+                            // This is to handle cases where-in the during a previous node-join attempt if the publish operation succeeded
+                            // but
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java]: Addressed.

File: server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java [hunk 9]
```diff
@@ -250,4 +264,132 @@ public void testNodeNotReachableFromClusterManager() throws Exception {
...
+            for (RepositoryMetadata repo : repositoriesMetadata.repositories()) {
+                if (repo.name().equals(remoteStateRepoName)) {
+                    isRemoteStateRepoConfigured = Boolean.TRUE;
+                } else if (repo.name().equals(remoteRoutingTableRepoName)) {
+                    isRemoteRoutingTableRepoConfigured = Boolean.TRUE;
+                }
+            }
+            assertTrue(isRemoteStateRepoConfigured);
+            assertTrue(isRemoteRoutingTableRepoConfigured);
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java:336]: Could we also assert that RepoService has not initialized the metadata ?

File: server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java [hunk 10]
```diff
@@ -1378,6 +1379,72 @@ public void testJoinRemoteStoreClusterWithRemotePublicationNodeInMixedMode() {
         JoinTaskExecutor.ensureNodesCompatibility(joiningNode, currentState.getNodes(), currentState.metadata());
     }
 
+    public void testUpdatesClusterStateWithRepositoryMetadataNotInSync() throws Exception {
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java:1382]: Based on the stacktrace shared in the issue, the remote nodes are part of cluster-state but the repos are not initialized in RepoService. Could we have it covered in the test ?
```
[2024-12-03T17:32:27,926][INFO ][o.o.c.c.JoinHelper       ] [node_t0] failed to join {node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true}, minimumTerm=1, optionalJoin=Optional[Join{term=2, lastAcceptedTerm=1, lastAcceptedVersion=8, sourceNode={node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true}, targetNode={node_t0}{HI4LDSiRQserbA7_FDq4Dw}{fWSEQusjSgiDULZF2oBNEw}{127.0.0.1}{127.0.0.1:50328}{m}{shard_indexing_pressure_enabled=true}}]}
org.opensearch.transport.RemoteTransportException: [node_t0][127.0.0.1:50328][internal:cluster/coordination/join]
Caused by: java.lang.NullPointerException: Cannot invoke "org.opensearch.repositories.Repository.getRestrictedSystemRepositorySettings()" because "repository" is null
	at org.opensearch.repositories.RepositoriesService.ensureValidSystemRepositoryUpdate(RepositoriesService.java:907) ~[main/:?]
	at org.opensearch.node.remotestore.RemoteStoreNodeService.updateRepositoriesMetadata(RemoteStoreNodeService.java:194) ~[main/:?]
	at org.opensearch.cluster.coordination.JoinTaskExecutor.execute(JoinTaskExecutor.java:210) ~[main/:?]
```

**Review by rajiv-kv — COMMENTED** [review]
LGTM

File: server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java (hunk 10 above)
Comment (Pranshu-S) [reply server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java:1382]: Updated the test to assert for this failure condition where in the persisted metadata has the repositories but the repository service does not.

File: server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java (hunk 9 above)
Comment (Pranshu-S) [reply server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java:337]: Updated the test to assert for this.

**Review by rajiv-kv — APPROVED** [review]

**Review by shwetathareja — APPROVED** [review]

**Review by shwetathareja — APPROVED** [review]

**Comment by Pranshu-S** [comment]
[Test Result](https://build.ci.opensearch.org/job/gradle-check/51268/testReport/) (1 failure / ±0)
[org.opensearch.remotestore.RemoteRestoreSnapshotIT.testRestoreShallowSnapshotIndexAfterSnapshot](https://build.ci.opensearch.org/job/gradle-check/51268/testReport/junit/org.opensearch.remotestore/RemoteRestoreSnapshotIT/testRestoreShallowSnapshotIndexAfterSnapshot/)

Flaky - https://github.com/opensearch-project/OpenSearch/issues/14324

**Comment by Pranshu-S** [comment]
[Test Result](https://build.ci.opensearch.org/job/gradle-check/51269/testReport/) (2 failures / +1)
[org.opensearch.remotestore.multipart.RemoteStoreMultipartIT.testCloseIndexWithNoOpSyncAndFlushForSyncTranslog](https://build.ci.opensearch.org/job/gradle-check/51269/testReport/junit/org.opensearch.remotestore.multipart/RemoteStoreMultipartIT/testCloseIndexWithNoOpSyncAndFlushForSyncTranslog/)
[org.opensearch.snapshots.DeleteSnapshotIT.testDeleteShallowCopySnapshot](https://build.ci.opensearch.org/job/gradle-check/51269/testReport/junit/org.opensearch.snapshots/DeleteSnapshotIT/testDeleteShallowCopySnapshot/)

Flaky - https://github.com/opensearch-project/OpenSearch/issues/15819, https://github.com/opensearch-project/OpenSearch/issues/9115

**Review by shwetathareja — APPROVED** [review]
