### PR TITLE
[Segment Replication] Unmute Test SegmentReplicationTargetServiceTests.testShardAlreadyReplicating

### LINKED ISSUE #8928: [BUG] org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating is flaky
**Describe the bug**
- org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating is flaky
- Sample run: https://build.ci.opensearch.org/job/gradle-check/21062/testReport/org.opensearch.indices.replication/SegmentReplicationTargetServiceTests/testShardAlreadyReplicating/
- Failed twice on #8506 

**To Reproduce**
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testShardAlreadyReplicating" -Dtests.seed=D8312943A799670E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-AE -Dtests.timezone=America/Manaus -Druntime.java=20
```

**Expected behavior**
- Test to pass

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR unmutes Test `SegmentReplicationTargetServiceTests.testShardAlreadyReplicating`

### Related Issues
Resolves #8928 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Can you please look at the flaky gradle checks in this PR and link the issues for those?

File: server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java [hunk 1]
```diff
@@ -246,7 +246,6 @@ public void testAlreadyOnNewCheckpoint() {
         verify(spy, times(0)).startReplication(any(), any(), any());
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/opensearch-project/OpenSearch/issues/8928")
```
Comment (mch2) [inline server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java:249]: lets please add @TestLogging on the replication package so we have more logs if this does pop up again.

`    @TestLogging(reason = "Getting trace logs from replication package", value = "org.opensearch.indices.replication:TRACE")
`

**Comment by Rishikesh1159** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/28121/
> * **CommitID:** [ac8cde9](https://github.com/opensearch-project/OpenSearch/commit/ac8cde9540e5127b6b0b5316bdb88110cc600502)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Failure reason: ':server:spotlessJavaCheck'

**Comment by Rishikesh1159** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/28138/
> * **CommitID:** [a7e948d](https://github.com/opensearch-project/OpenSearch/commit/a7e948dcb75133aae82256a2774b0cc23944e8c6)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test:
-> [org.opensearch.percolator.PercolatorQuerySearchIT.testManyPercolatorFields {p0={"search.concurrent_segment_search.enabled":"true"}}](https://build.ci.opensearch.org/job/gradle-check/28138/testReport/junit/org.opensearch.percolator/PercolatorQuerySearchIT/testManyPercolatorFields__p0___search_concurrent_segment_search_enabled___true___/)

-> [org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown](https://build.ci.opensearch.org/job/gradle-check/28138/testReport/junit/org.opensearch.common.util.concurrent/QueueResizableOpenSearchThreadPoolExecutorTests/testResizeQueueDown/)

-> [org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod](https://build.ci.opensearch.org/job/gradle-check/28138/testReport/junit/org.opensearch.common.util.concurrent/QueueResizableOpenSearchThreadPoolExecutorTests/classMethod/)

-> [org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod](https://build.ci.opensearch.org/job/gradle-check/28138/testReport/junit/org.opensearch.common.util.concurrent/QueueResizableOpenSearchThreadPoolExecutorTests/classMethod_2/)

-> [org.opensearch.index.shard.RemoteIndexShardTests.testRepicaCleansUpOldCommitsWhenReceivingNew](https://build.ci.opensearch.org/job/gradle-check/28138/testReport/junit/org.opensearch.index.shard/RemoteIndexShardTests/testRepicaCleansUpOldCommitsWhenReceivingNew/) - https://github.com/opensearch-project/OpenSearch/issues/10303

**Comment by Rishikesh1159** [comment]
> @Rishikesh1159 I can't tell from #8928 where this was fixed?

I am not able to reproduce the test failure. I tried running entire test suite class but still not able to reproduce. This flaky test might be fixed from some changes happened in last 2 months.  I am adding trace logging with test, so next time if we see this test failing we can get more info from logs.

**Comment by Rishikesh1159** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** UNSTABLE ❕
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.index.ShardIndexingPressureIT.testShardIndexingPressureTrackingDuringBulkWrites
> ```
> 
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/28168/
> * **CommitID:** [c7aa4f6](https://github.com/opensearch-project/OpenSearch/commit/c7aa4f677a006902c38a4d45248af3fe99a1d495)
>   Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

known flaky test: https://github.com/opensearch-project/OpenSearch/issues/5176
