### PR TITLE
Reject invalid SearchBackpressureMode (#6832)

### LINKED ISSUE #6832: [BUG] Incorrect SearchBackpressureMode can corrupt cluster state
**Describe the bug**

**To Reproduce**
1. Update Cluster settings with an invalid enum type for `search_backpressure` like below.
2. For example, instead of `monitor_only`, `monitor-only` was incorrectly used. 
```PUT localhost:9200/_cluster/settings
{
    "persistent": {
        "search_backpressure": {
            "mode": "monitor-only"
      }
    }
}
```
3. The cluster state will get corrupted. This can put the cluster in an unrecoverable state as no master eligible mode can be voted as current master. All master eligible nodes are out of comission. 

**Expected behavior**
The API call should error out as `monitor-only` is an invalid value. The incorrect value should not get propagated through the nodes. 

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
```
 java.lang.IllegalArgumentException: Invalid SearchBackpressureMode: monitor-only
 	at org.opensearch.search.backpressure.settings.SearchBackpressureMode.fromName(SearchBackpressureMode.java:50) ~[opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.search.backpressure.settings.SearchBackpressureSettings.lambda$new$0(SearchBackpressureSettings.java:124) ~[opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.settings.Setting$Updater.apply(Setting.java:1238) ~[opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:696) ~[opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:232) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:556) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:484) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:186) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:282) [opensearch-2.5.0.jar:2.5.0]
 	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:245) [opensearch-2.5.0.jar:2.5.0]
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
 	at java.lang.Thread.run(Thread.java:833) [?:?]
 [2023-03-25T04:37:43,478][WARN ][o.o.c.s.ClusterApplierService] [416d7c37938c] failed to apply updated cluster state in [0s]:

```

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] Ubunutu
 - Version [e.g. 22] OS 2.5

**Additional context**

### PR DESCRIPTION
**Pull request by austintlee**
ClusterState updates of SearchBackpressureMode are persisted without validation which causes the entire cluster to become unstable or corrupted when a cluster tries to load invalid mode.

### Description
This fixes #6832 that causes cluster state corruption due to a lack of validation of SearchBackpressureMode.

### Related Issues
Resolves #6832 

### Check List
- [ ] New functionality includes testing.
  - [x ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java [hunk 1]
```diff
@@ -46,6 +46,15 @@ private static class Defaults {
     public static final Setting<String> SETTING_MODE = Setting.simpleString(
```
Comment (andrross) [inline server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java:46]: Can we replace this with a typed setting per the [recommendation here](https://github.com/opensearch-project/OpenSearch/blob/c765e3a4bfb4e2d2532e1afde34758e48c644b3d/server/src/main/java/org/opensearch/common/settings/Setting.java#L94-L102):

```
 * It's recommended to use typed settings rather than string based settings. For example adding a setting for an enum type:
 * <pre>{@code
 * public enum Color {
 *     RED, GREEN, BLUE;
 * }
 * public static final Setting<Color> MY_BOOLEAN =
 *     new Setting<>("my.color.setting", Color.RED.toString(), Color::valueOf, Setting.Property.NodeScope);
 * }
 * </pre>
```

Comment (austintlee) [reply server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java]: Done!

**Review by Bukhtawar — APPROVED** [review]
LGTM. Thanks for the change

**Review by Bukhtawar — APPROVED** [review]
LGTM. Thanks for the change

**Comment by austintlee** [comment]
Backwards tests failing.  Will update my YAML tests to run > 2.9.99.

**Comment by austintlee** [comment]
Changelog updated.
