### PR TITLE
Fix flaky ExistsQueryBuilderTests.testToQuery

### LINKED ISSUE #18274: [AUTOCUT] Gradle Check Flaky Test Report for ExistsQueryBuilderTests
## Flaky Test Report for `ExistsQueryBuilderTests`

Noticed the `ExistsQueryBuilderTests` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| 60fee58ee5a62b5f7dd56b5fea256fd1b573ab54 | [18201](https://github.com/opensearch-project/OpenSearch/pull/18201) | [57994](https://build.ci.opensearch.org/job/gradle-check/57994/testReport/) | `org.opensearch.index.query.ExistsQueryBuilderTests.testToQuery` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `ExistsQueryBuilderTests` class are:

- [18255](https://github.com/opensearch-project/OpenSearch/pull/18255)
- [18327](https://github.com/opensearch-project/OpenSearch/pull/18327)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by atris**
Test was generating field patterns that matched raw.derived_keyword, which doesnt support exists queries. Fixed by replacing problematic patterns with TEXT_FIELD_NAME.

Fixes #18274

### CODE REVIEW

**Comment by atris** [comment]
@owaiskazi19 @andrross Please review

File: server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java [hunk 1]
```diff
@@ -89,9 +89,14 @@ protected ExistsQueryBuilder doCreateTestQueryBuilder() {
         }
         // also sometimes test wildcard patterns
         if (randomBoolean()) {
-            if (randomBoolean()) {
```
Comment (sandeshkr419) [inline server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java:92]: I think the original intent of having 2 `randomBoolean()` was to reduce the probability of using a wild-card pattern to `0.25` which is implied by the comment `// also sometimes test wildcard patterns`. 

Logically equivalent logic will be:

```
if (randomBoolean() && randomBoolean()) {
....wild-card related logic....
} 
```

Now, honestly I don't know the reason behind having wild-card patters `sometimes` instead of just randomly 50% of the time, and don't have arguments to decide either way. However, let's change the behavior only if we intend to, else let's keep it the way it is.

File: server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java [hunk 2]
```diff
@@ -89,9 +89,14 @@ protected ExistsQueryBuilder doCreateTestQueryBuilder() {
...
-                fieldPattern = fieldPattern + "*";
-            }
+            fieldPattern = fieldPattern + "*";
+        }
+        // Avoid patterns that would match the derived field "raw.derived_keyword"
+        // This includes "raw", "raw*", "raw.xxx", "r*", "ra*", etc.
+        if (fieldPattern.equals("raw")
```
Comment (sandeshkr419) [inline server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java]: Isn't the equality `(fieldPattern.equals("raw")` case redundant with `fieldPattern.startsWith("raw")`?

File: server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java [hunk 3]
```diff
@@ -89,9 +89,14 @@ protected ExistsQueryBuilder doCreateTestQueryBuilder() {
...
+            || fieldPattern.startsWith("raw")
+            || (fieldPattern.contains("*") && "raw.derived_keyword".startsWith(fieldPattern.replace("*", "")))) {
```
Comment (sandeshkr419) [inline server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java]: Can the pattern matching checks can be moved before the wild-card logic block, so that you don't have to worry about replacing `"*"` with `""`?

In case you match the restricted patterns, override early and then when you add `*` to `fieldPattern`, that should be safe to do so.

What do you think?

File: CHANGELOG.md [hunk 4]
```diff
@@ -99,6 +99,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 
 ### Fixed
 - Fix flaky tests in CloseIndexIT by addressing cluster state synchronization issues ([#18878](https://github.com/opensearch-project/OpenSearch/issues/18878))
+- Fix flaky ExistsQueryBuilderTests.testToQuery ([#18274](https://github.com/opensearch-project/OpenSearch/issues/18274))
```
Comment (andrross) [inline CHANGELOG.md]: We generally don't add changelog entries for non-user facing things like test fixes. There is some guidance [here](https://github.com/opensearch-project/OpenSearch/blob/d9a927464ec62634d520bc32bbd34104c4f4c097/CONTRIBUTING.md#changelog).

**Review by sandeshkr419 — CHANGES_REQUESTED** [review]
Thanks @atris for taking time to fix this flaky test. 
I have a few comments to refine it more.

Also. if this was reproduce-able, can you please verify the same (before/after) by running the test in your IDE n-times.

File: CHANGELOG.md (hunk 4 above)
Comment (sandeshkr419) [reply CHANGELOG.md]: @andrross I guess we should get rid of L101 as well then.

File: server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java (hunk 1 above)
Comment (atris) [reply server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java:92]: Good catch. You're right about the 25% probability. I've restored the nested randomBoolean() structure to preserve the original behavior.

 I agree we should only change the probability if there's a specific reason to.

**Comment by atris** [comment]
> Thanks @atris for taking time to fix this flaky test. I have a few comments to refine it more.
> 
> Also. if this was reproduce-able, can you please verify the same (before/after) by running the test in your IDE n-times.

Thanks for the review @sandeshkr419. I've addressed all your comments - removed the redundant check, moved the pattern check before wildcard logic, and preserved the original 25% probability for wildcards.

  I ran the test 30+ times locally with random seeds including the two failing seeds from the issue (8C4D6928119E4426 and D373738A924E04A). All pass now. Before the fix, these seeds  failed with the UnsupportedOperationException.

File: server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java (hunk 3 above)
Comment (atris) [reply server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java]: Agreed, fixed.

File: server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java (hunk 2 above)
Comment (atris) [reply server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java]: Fixed

File: CHANGELOG.md (hunk 4 above)
Comment (atris) [reply CHANGELOG.md]: Fixed

**Review by sandeshkr419 — APPROVED** [review]

**Review by jainankitk — APPROVED** [review]
Thanks @atris for fixing this flaky test!

**Review by andrross — APPROVED** [review]

**Comment by atris** [comment]
Thank you for reviewing. @andrross @jainankitk @sandeshkr419 

If it looks good, can we please merge?

**Review by rishabhmaurya — APPROVED** [review]
