### PR TITLE
Fix download reporting for segment replication

### LINKED ISSUE #10515: [BUG] `_cat/segment_replication` returns no data
I have a remote store-enabled cluster running a pre-release version of 2.11. Often when I invoke the segment_replication API I get the following:

```
GET _cat/segment_replication?v
shardId target_node target_host checkpoints_behind bytes_behind current_lag last_completed_lag rejected_requests
```

This was with a cluster with a single index with 1 replica taking writes. Sometimes an entry shows up in the API response, sometimes not. I don't know exactly how to reproduce this but I'll add more data if I find anything useful.

### PR DESCRIPTION
**Pull request by kotwanikunal**
### Description
- Fixes progress tracking for segment replication 
- `_cat/segment_replication` returns the replica results when the replication event completes successfully which is recorded  here - https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java#L520-L522
- This change ensures that the downloads are tracked and record the completed events correctly. 

### Related Issues
Resolves #10515 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java [hunk 1]
```diff
@@ -170,7 +171,21 @@ public void startReplication(ActionListener<Void> listener) {
             final List<StoreFileMetadata> filesToFetch = getFiles(checkpointInfo);
             state.setStage(SegmentReplicationState.Stage.GET_FILES);
             cancellableThreads.checkForCancel();
-            source.getSegmentFiles(getId(), checkpointInfo.getCheckpoint(), filesToFetch, indexShard, getFilesListener);
+            final BiConsumer<String, Long> fileProgressTracker = (fileName, bytesRecovered) -> {
+                ReplicationLuceneIndex index = state.getIndex();
+                if (index != null && index.getFileDetails(fileName) != null) {
+                    index.addRecoveredBytesToFile(fileName, bytesRecovered);
```
Comment (andrross) [inline server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java:177]: ReplicationLuceneIndex is a thread safe class (all methods are synchronized). However, the "check if present then add bytes" pattern is not thread safe because the file could be removed in between the check and the add.

Comment (kotwanikunal) [reply server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java:177]: Good point. In that case, we do have the scenario covered with proper usage - the files are calculated and fetched [here](https://github.com/kotwanikunal/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java#L222-L225) and the same list is passed down for downloads [here](https://github.com/kotwanikunal/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java#L170-L173). 

And any other incorrect update will lead to an exception - which I think is valid and points to a bug in the code.
Removing the contains check.

File: server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java [hunk 2]
```diff
@@ -58,4 +66,69 @@ void getSegmentFiles(
      * Cancel any ongoing requests, should resolve any ongoing listeners with onFailure with a {@link ExecutionCancelledException}.
      */
     default void cancel() {}
+
+    /**
+     * Directory wrapper that records copy process for replication statistics
+     *
+     * @opensearch.internal
+     */
+    final class ReplicationStatsDirectoryWrapper extends FilterDirectory {
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java:75]: @andrross Thanks for this suggestion. Tested the changes - we have proper progress tracking now, instead of just 0% or 100%.

File: server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java [hunk 3]
```diff
@@ -117,7 +119,12 @@ public void getSegmentFiles(
                         assert directoryFiles.contains(file) == false : "Local store already contains the file " + file;
                         toDownloadSegmentNames.add(file);
                     }
-                    indexShard.getFileDownloader().download(remoteDirectory, storeDirectory, toDownloadSegmentNames);
+                    indexShard.getFileDownloader()
+                        .download(
+                            remoteDirectory,
+                            new ReplicationStatsDirectoryWrapper(storeDirectory, fileProgressTracker),
```
Comment (andrross) [inline server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java:125]: So we're wrapping the `copyFrom` method on `storeDirectory`, then inside copyFrom we wrap the passed in `from` directory and instrument the `readBytes` method. Would it be simpler to just wrap the `from` directory here like the following?

```java
final Directory statsTrackingRemoteDirectory = new FilterDirectory(remoteDirectory) {
    @Override
    public IndexInput openInput(String name, IOContext context) throws IOException {
        final IndexInput input = in.openInput(name, context);
        return new IndexInput("StatsDirectoryWrapper(" + input.toString() + ")") {
            @Override
            public void close() throws IOException {
                input.close();
            }

            @Override
            public long getFilePointer() {
                throw new UnsupportedOperationException("only straight copies are supported");
            }

            @Override
            public void seek(long pos) throws IOException {
                throw new UnsupportedOperationException("seeks are not supported");
            }

            @Override
            public long length() {
                return input.length();
            }

            @Override
            public IndexInput slice(String sliceDescription, long offset, long length) throws IOException {
                throw new UnsupportedOperationException("slices are not supported");
            }

            @Override
            public byte readByte() throws IOException {
                throw new UnsupportedOperationException("use a buffer if you wanna perform well");
            }

            @Override
            public void readBytes(byte[] b, int offset, int len) throws IOException {
                // we rely on the fact that copyFrom uses a buffer
                input.readBytes(b, offset, len);
                fileProgressTracker.accept(dest, (long) len);
            }
        };
    }
};
indexShard.getFileDownloader().download(
    statsTrackingRemoteDirectory,
    storeDirectory,
    toDownloadSegmentNames);
```

Comment (kotwanikunal) [reply server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java:125]: The added benefit with the current approach is we can also wrap `PrimaryShardReplicationSource` with the same class from `SegmentReplicationSource` and reuse it to move away from `MultiFileWriter`. It should be a quick change to split out the logic but I have limited this PR currently to just fix the bug.

**Review by andrross — APPROVED** [review]
