### PR TITLE
Leveraging segment-global ordinal mapping for efficient terms aggrega…

### LINKED ISSUE #20626: Performance regression in terms aggregation with match_all queries
### Describe the bug

Terms aggregations with match_all queries on high-cardinality fields have experienced significant performance regression since PR #11643 introduced the `tryCollectFromTermFrequencies` optimization in `GlobalOrdinalsStringTermsAggregator`. This went unnoticed until recent ClickBench query performance testing revealed severe slowdowns.

### Related component

Search:Performance

### Affected Query Pattern
```json
{
  "size": 0,
  "timeout": "1m",
  "aggregations": {
    "URL": {
      "terms": {
        "field": "URL",
        "size": 10
      }
    }
  }
}
```
Where the field has high cardinality (e.g., 10 million unique values).

### Root Cause
The `tryCollectFromTermFrequencies` method introduced in #11643 uses a merge-join algorithm that iterates through all global ordinals to match them with segment terms:

Location: `GlobalOrdinalsStringTermsAggregator.java:`
```java
TermsEnum indexTermsEnum = segmentTerms.iterator();
BytesRef indexTerm = indexTermsEnum.next();
final SortedSetDocValues globalOrds = this.getGlobalOrds(ctx);
TermsEnum globalOrdinalTermsEnum = globalOrds.termsEnum();
BytesRef ordinalTerm = globalOrdinalTermsEnum.next();

while (indexTerm != null && ordinalTerm != null) {
    int compare = indexTerm.compareTo(ordinalTerm);
    if (compare == 0) {
        if (acceptedGlobalOrdinals.test(globalOrdinalTermsEnum.ord())) {
            ordCountConsumer.accept(globalOrdinalTermsEnum.ord(), indexTermsEnum.docFreq());
        }
        indexTerm = indexTermsEnum.next();
        ordinalTerm = globalOrdinalTermsEnum.next();
    } else if (compare < 0) {
        indexTerm = indexTermsEnum.next();
    } else {
        ordinalTerm = globalOrdinalTermsEnum.next();  // Iterates through millions of non-matching ordinals
    }
}
```

### Performance Impact
For an index with:
- 10 million unique terms globally
- 10 segments
- Each segment containing ~2 million unique terms

**Current behavior**
- Iterates through 10M global ordinals per segment
- Total: 10 segments × 10M iterations = 100M+ global ordinal iterations
- Each iteration involves `BytesRef` fetching and comparison

The compare > 0 branch skips millions of global ordinals that don't exist in the current segment

### Expected behavior

Should only iterate through segment terms (~2M per segment)

Total: 10 segments × 2M lookups = 20M operations

### Why This Happens
The merge-join approach assumes both iterators need to be advanced together, but this is inefficient when:
Global ordinals contain terms from all segments (superset) - (which is always the case? even with deleted docs)

### Solution

Replace the merge-join with direct term lookup?

```
TermsEnum indexTermsEnum = segmentTerms.iterator();
final SortedSetDocValues globalOrds = this.getGlobalOrds(ctx);
BytesRef indexTerm;

while ((indexTerm = indexTermsEnum.next()) != null) {
    long globalOrd = globalOrds.lookupTerm(indexTerm);
    if (globalOrd >= 0 && acceptedGlobalOrdinals.test(globalOrd)) {
        ordCountConsumer.accept(globalOrd, indexTermsEnum.docFreq());
    }
}
```
- Only iterates through segment terms (not all global ordinals)
- Eliminates unnecessary BytesRef comparisons
- Scales better with high cardinality fields

Additionally, **Add Cardinality Threshold**: which @bowenlan-amzn is addressing as part of https://github.com/opensearch-project/OpenSearch/pull/20623

Thanks @rishabh6788 for sharing cpu profile and bringing this issue to attention. 

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
Image
[streaming-profile-q34 (1).html](https://github.com/user-attachments/files/25300259/streaming-profile-q34.1.html)

**Host/Environment (please complete the following information):**
 - Version OS 2.13+

**Additional context**

### PR DESCRIPTION
**Pull request by jainankitk**
…tion

### Description
Address the terms aggregation performance regression using segment to global ordinals mapping without reading the terms from disk for per segment collection

### Related Issues
Resolves #20626

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java [hunk 1]
```diff
@@ -565,11 +557,10 @@ static class LowCardinality extends GlobalOrdinalsStringTermsAggregator {
...
             if (subAggregators.length == 0) {
-                if (mapping != null) {
-                    mapSegmentCountsToGlobalCounts(mapping);
-                }
-                mapping = valuesSource.globalOrdinalsMapping(ctx);
-                return tryCollectFromTermFrequencies(ctx, (ord, docCount) -> incrementBucketDocCount(mapping.applyAsLong(ord), docCount));
+                return tryCollectFromTermFrequencies(
+                    ctx,
+                    (globalOrd, docCount) -> incrementBucketDocCount(collectionStrategy.globalOrdToBucketOrd(0, globalOrd), docCount)
+                );
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java:564]: This kind of seemed like another bug to me in the original implementation. Since, we were always passing the globalOrdinal to the consumer, using segment -> global mapping seems wrong

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java [hunk 2]
```diff
@@ -207,28 +207,20 @@ boolean tryCollectFromTermFrequencies(LeafReaderContext ctx, BiConsumer<Long, In
...
-                }
-                indexTerm = indexTermsEnum.next();
-                ordinalTerm = globalOrdinalTermsEnum.next();
-            } else if (compare < 0) {
-                indexTerm = indexTermsEnum.next();
-            } else {
-                ordinalTerm = globalOrdinalTermsEnum.next();
+        final TermsEnum segmentTermsEnum = segmentTerms.iterator();
+        final LongUnaryOperator globalOrdsMapping = valuesSource.globalOrdinalsMapping(ctx);
+        segmentTermsEnum.next();
```
Comment (rishabhmaurya) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java]: why do we need this next()

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java (hunk 1 above)
Comment (rishabhmaurya) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java:564]: +1! seems unnecessary. @sandeshkr419 could you verify?

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java (hunk 2 above)
Comment (jainankitk) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java]: I believe the iterator is unpositioned without invoking `next()`

**Comment by bowenlan-amzn** [comment]
My only concern is the correctness, because this is based on the assumption that term dictionary ordinals match with term docvalues ordinals. In other word, the same term `foo` is same ordinal like `23` in both term dictionary order and term docvalues ordinals. 

We do have a cluster setting to guard this 
https://github.com/opensearch-project/OpenSearch/blob/38a030fd75aba7f765d6ce1dba6194346cba83e3/server/src/main/java/org/opensearch/search/SearchService.java#L445-L451 

From performance perspective, maybe can relax this setting to the cardinality of the field in clickbench terms query, where we noticed the regression, and trigger a benchmark to see

https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/adf94810a0b6802a1efe92719eb2139b7a46ae13/clickbench/operations/dsl.json#L1849-L1908

**Comment by jainankitk** [comment]
{"run-benchmark-test": "id_16"}

**Comment by jainankitk** [comment]
{"run-benchmark-test": "id_16"}

**Comment by jainankitk** [comment]
{"run-benchmark-test": "id_16"}

**Comment by rishabh6788** [comment]
> Benchmark Baseline Comparison Results

ignore these results as there were a few failures during snapshot restore. 
Have triggered new runs.

**Comment by rishabh6788** [comment]
Seeing below errors for a few queries
```
[ERROR] circuit_breaking_exception ({'error': {'root_cause': [{'type': 'circuit_breaking_exception', 'reason': '[parent] Data too large, data for [<http_request>] would be [8162322916/7.6gb], which is larger than the limit of [8160437862/7.5gb], real usage: [8162322368/7.6gb], new bytes reserved: [548/548b], usages [request=0/0b, fielddata=37220368/35.4mb, in_flight_requests=548/548b]', 'bytes_wanted': 8162322916, 'bytes_limit': 8160437862, 'durability': 'PERMANENT'}], 'type': 'circuit_breaking_exception', 'reason': '[parent] Data too large, data for [<http_request>] would be [8162322916/7.6gb], which is larger than the limit of [8160437862/7.5gb], real usage: [8162322368/7.6gb], new bytes reserved: [548/548b], usages [request=0/0b, fielddata=37220368/35.4mb, in_flight_requests=548/548b]', 'bytes_wanted': 8162322916, 'bytes_limit': 8160437862, 'durability': 'PERMANENT'}, 'status': 429})
```

Need to change the instance type to may be use r5.2xlarge that has more memory compared to c5.2xlarge.

**Comment by jainankitk** [comment]
> From performance perspective, maybe can relax this setting to the cardinality of the field in clickbench terms query, where we noticed the regression, and trigger a benchmark to see

@bowenlan-amzn - Ran the clickbench and I can notice very significant performance improvement for q34 / q35:

|                                                        Metric |                               Task |    Baseline |   Contender |     Diff |   Unit |
|--------------------------------------------------------------:|-----------------------------------:|------------:|------------:|---------:|-------:|
|                                                Min Throughput |             dsl-q34-url-popularity |   0.0281253 |    0.338396 |  0.31027 |  ops/s |
|                                               Mean Throughput |             dsl-q34-url-popularity |   0.0283526 |     0.37488 |  0.34653 |  ops/s |
|                                             Median Throughput |             dsl-q34-url-popularity |   0.0283845 |    0.378126 |  0.34974 |  ops/s |
|                                                Max Throughput |             dsl-q34-url-popularity |    0.028523 |    0.396244 |  0.36772 |  ops/s |
|                                       50th percentile latency |             dsl-q34-url-popularity |      707695 |     40438.6 |  -667257 |     ms |
|                                       90th percentile latency |             dsl-q34-url-popularity |      981042 |       54541 |  -926501 |     ms |
|                                      100th percentile latency |             dsl-q34-url-popularity | 1.03272e+06 |     57240.6 |  -975478 |     ms |
|                                  50th percentile service time |             dsl-q34-url-popularity |     34933.8 |     2281.16 | -32652.7 |     ms |
|                                  90th percentile service time |             dsl-q34-url-popularity |     35553.1 |     2338.47 | -33214.6 |     ms |
|                                 100th percentile service time |             dsl-q34-url-popularity |     35825.3 |     2348.64 | -33476.7 |     ms |
|                                                    error rate |             dsl-q34-url-popularity |           0 |           0 |        0 |      % |
|                                                Min Throughput |          dsl-q35-url-with-constant |   0.0286568 |    0.442814 |  0.41416 |  ops/s |
|                                               Mean Throughput |          dsl-q35-url-with-constant |   0.0287056 |    0.444112 |  0.41541 |  ops/s |
|                                             Median Throughput |          dsl-q35-url-with-constant |   0.0286958 |    0.444153 |  0.41546 |  ops/s |
|                                                Max Throughput |          dsl-q35-url-with-constant |   0.0288048 |    0.445275 |  0.41647 |  ops/s |
|                                       50th percentile latency |          dsl-q35-url-with-constant |      705527 |     36483.2 |  -669044 |     ms |
|                                       90th percentile latency |          dsl-q35-url-with-constant |      981236 |       50293 |  -930943 |     ms |
|                                      100th percentile latency |          dsl-q35-url-with-constant | 1.03363e+06 |     52936.7 |  -980694 |     ms |
|                                  50th percentile service time |          dsl-q35-url-with-constant |     35011.1 |     2242.29 | -32768.8 |     ms |
|                                  90th percentile service time |          dsl-q35-url-with-constant |       35822 |     2308.75 | -33513.2 |     ms |
|                                 100th percentile service time |          dsl-q35-url-with-constant |     36099.7 |     2441.51 | -33658.2 |     ms |
