### PR TITLE
Fix minimum index compatibility error message

### LINKED ISSUE #2936: [BUG] min compatible version error message for 6.8
**Describe the bug**

Error message references non existence version of OpenSearch:
`**index** was created with version [6.8.1] but the minimum compatible version is [7.0.0]. It should be re-indexed in OpenSearch 7.x before upgrading to 2.0.0.`

**To Reproduce**
* With OpenSearch Dashboards
* Run `yarn test:bwc -d https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.0.0-rc1/2963/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.0.0-rc1-linux-x64.tar.gz -o https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.0.0-rc1/latest/linux/x64/tar/dist/opensearch/opensearch-2.0.0-rc1-linux-x64.tar.gz -v odfe-0.10.0`

**Expected behavior**
Error message gives a valid upgrade message.

**Plugins**
all

**Screenshots**
n/a

**Host/Environment (please complete the following information):**

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by andrross**
This is a very simple fix that adds a special case for the backward
compatibility message for OS 1.x/ES 7.x. This basically mirrors a
special case already codified in [Version][1]. I think this is a
reasonable fix because it allows the message to be quite verbose. It
should also only need to exist on the 2.x branch of OpenSearch since it
is a special case that will no longer exist in 3.x when the entire
LegacyESVersion concept can be removed from the code base.

[1]: https://github.com/opensearch-project/OpenSearch/blob/cb238aae616d6a0fd8f82e128a1f94c8e4e8b1f7/server/src/main/java/org/opensearch/Version.java#L398

Signed-off-by: Andrew Ross <andrross@amazon.com>

### Issues Resolved
closes #2936
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kotwanikunal — APPROVED** [review]

**Review by saratvemulapalli — APPROVED** [review]

**Review by VachaShah — APPROVED** [review]

**Review by reta — APPROVED** [review]

File: server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexUpgradeService.java [hunk 1]
```diff
@@ -134,20 +135,35 @@ boolean isUpgraded(IndexMetadata indexMetadata) {
...
-
-                    + minimumIndexCompatibilityVersion
-                    + "]. It should be re-indexed in OpenSearch "
-                    + minimumIndexCompatibilityVersion.major
-                    + ".x before upgrading to "
-                    + Version.CURRENT
-                    + "."
-            );
+            if (minimumIndexCompatibilityVersion.equals(LegacyESVersion.V_7_0_0)) {
+                // This branch can be removed when LegacyESVersion is removed
```
Comment (adnapibar) [inline server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexUpgradeService.java:139]: Can we create an issue and add to the comment?

Comment (andrross) [reply server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexUpgradeService.java:139]: I don't think we will every actually remove this code...it will just stay orphaned on the 2.x branch when the world moves ahead. But in any case, there's an issue for removing this constant from 3.0 (#2747) so the compiler would complain if this code needed to be updated.
