### PR TITLE
skip overriding routing table when it already contains entries with remote recovery source

### LINKED ISSUE #9921: [BUG] [Remote Cluster State] Auto restore from remote cluster state after quorum loss should recover index shards into GREEN state
**Describe the bug**
- After quorum loss recovery if the previous state is completely lost the cluster doesn't have any indices 
- But with remote store clusters, the index data exists in a remote repository
- With Remote Cluster state, the IndexMetadata which is lost with cluster state is also available in remote repository
- Today if cluster has remote cluster state and looses local disk state after quorum loss recovery, we auto restore the IndexMetadata from Remote Cluster State
- This adds the index back to the cluster. 
- **Today there is a bug where the index shards are in UNASSIGNED state when auto restored from Remote Cluster State**

**Expected behavior**
After auto restore, index shards should be ASSIGNED and eventually started and index should be GREEN eventually

### PR DESCRIPTION
**Pull request by linuxpi**
### Description
- After Cluster Manager recovery or a fresh cluster bootstrap, we trigger the `GatewayService.RecoverStateUpdateTask` which performs various mutations to the cluster state.
- One of the mutations blindly overrides the routing table in the cluster state. This makes sense as after recovery or new cluster bootstrap, routing table should be generated from scratch.
- But for Remote Store and Remote Cluster State enabled clusters, we auto restore previous valid cluster state from Remote(Only IndexMetadata in 2.10). So routing tables are generated as part of restore flow with remote store recovery source.
- To avoid `GatewayService.RecoverStateUpdateTask` overriding the pre-generated routing table entries for remote store clusters we have skipped the routing table override.
- If we did not skip this, the new routing table would be created with recovery source as ExistingStoreRecoverySource which looks on local disk for recovery. 
 

### Related Issues
Resolves #9921 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java [hunk 1]
```diff
@@ -540,9 +540,13 @@ public Builder addAsNew(IndexMetadata indexMetadata) {
 
         public Builder addAsRecovery(IndexMetadata indexMetadata) {
             if (indexMetadata.getState() == IndexMetadata.State.OPEN || isIndexVerifiedBeforeClosed(indexMetadata)) {
-                IndexRoutingTable.Builder indexRoutingBuilder = new IndexRoutingTable.Builder(indexMetadata.getIndex())
-                    .initializeAsRecovery(indexMetadata);
-                add(indexRoutingBuilder);
+                if (indexMetadata.getSettings().getAsBoolean(IndexMetadata.SETTING_REMOTE_STORE_ENABLED, false) == false
+                    || indicesRouting.get(indexMetadata.getIndex().getName())
+                        .shardsMatchingPredicateCount(sr -> sr.recoverySource() instanceof RecoverySource.RemoteStoreRecoverySource) == 0) {
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java:545]: for RemoteStoreRecoverySource, RoutingTable will not be populated. Now at what point RoutingTable will be populated. Is there an integ test which would pass now with this change and failing earlier?

Comment (linuxpi) [reply server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java:545]: We populate the routing table when cluster state is updated in RemoteStoreRestoreService. so skipping should be fine. 

We did not have iteg tests which were failing earlier due to this reason.

Some old remote store recovery integ tests which were passing earlier have started to fail, those i need to handle

File: server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java [hunk 2]
```diff
@@ -120,7 +121,19 @@ static ClusterState updateRoutingTable(final ClusterState state) {
         // initialize all index routing tables as empty
         final RoutingTable.Builder routingTableBuilder = RoutingTable.builder(state.routingTable());
         for (final IndexMetadata cursor : state.metadata().indices().values()) {
-            routingTableBuilder.addAsRecovery(cursor);
+            // Whether IndexMetadata is recovered from local disk or remote it doesn't matter to us at this point.
+            // We are only concerted about index data recovery here. Which is why we only check for remote store enabled and not for remote
+            // cluster state enabled.
+            if (cursor.getSettings().getAsBoolean(IndexMetadata.SETTING_REMOTE_STORE_ENABLED, false) == false
+                || state.routingTable()
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:128]: The second check is for remote store indices where remote cluster state is disabled, right?

File: server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java [hunk 3]
```diff
@@ -120,7 +121,19 @@ static ClusterState updateRoutingTable(final ClusterState state) {
...
+                    .shardsMatchingPredicateCount(
+                        shardRouting -> shardRouting.primary()
+                            // We need to ensure atleast one of the primaries is being recovered from remote.
+                            // This ensures we have gone through the RemoteStoreRestoreService and routing table is updated
+                            && shardRouting.recoverySource() instanceof RecoverySource.RemoteStoreRecoverySource
+                    ) == 0) {
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:134]: Ideally, this count should either be 0 or number of shards. If it is neither, we will have red index as some of the shards will be unassigned. But given that this is remote backed index, we should be able to recover it manually using `_remotestore/_restore` API. Is this understanding correct?

File: server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java [hunk 4]
```diff
@@ -120,7 +121,19 @@ static ClusterState updateRoutingTable(final ClusterState state) {
         // initialize all index routing tables as empty
         final RoutingTable.Builder routingTableBuilder = RoutingTable.builder(state.routingTable());
         for (final IndexMetadata cursor : state.metadata().indices().values()) {
-            routingTableBuilder.addAsRecovery(cursor);
+            // Whether IndexMetadata is recovered from local disk or remote it doesn't matter to us at this point.
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:124]: When I restart any one node in the cluster, will this flow be called?

Comment (linuxpi) [reply server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:124]: This would be called only when cluster state recovery is performed. It wont be called on normal node restart

File: server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java (hunk 3 above)
Comment (linuxpi) [reply server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:134]: yes, if IndexMetadata is present in the cluster you can always call the _remotestore/_restore api to make it green

File: server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java (hunk 2 above)
Comment (linuxpi) [reply server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:128]: second check is to make sure we have gone through the remote store restore flow and the routing tables have recovery source are remote store.

> The second check is for remote store indices where remote cluster state is disabled, right? 

yes this understanding is also correct. When remote store is enabled but remote cluster state is not, the second check will pass(`shards with recovery source as remote are 0`) and you will  execute `routingTableBuilder.addAsRecovery(cursor);` which was happening earlier as well

Comment (sachinpkale) [reply server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:128]: Then, why don't we just check if remote cluster state is enabled or not? Is it possible that remote cluster state is enabled but we will still have primary shards with recovery source not set to remote store?

**Review by sachinpkale — APPROVED** [review]

File: server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java (hunk 2 above)
Comment (linuxpi) [reply server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:128]: just checking remote cluster state would not be enough as even if remote cluster state is enabled we might not do a cluster state auto restore if any one of the previous cluster manager survived and was able to recover from local disk. then the cluster UUID would not change and you wont trigger auto restore.

in that case even if your remote cluster state is enabled, you still need to call `routingTableBuilder.addAsRecovery(cursor);`, as is the flow today.

File: server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java [hunk 5]
```diff
@@ -120,7 +121,19 @@ static ClusterState updateRoutingTable(final ClusterState state) {
...
+            // We are only concerted about index data recovery here. Which is why we only check for remote store enabled and not for remote
+            // cluster state enabled.
+            if (cursor.getSettings().getAsBoolean(IndexMetadata.SETTING_REMOTE_STORE_ENABLED, false) == false
+                || state.routingTable()
+                    .shardsMatchingPredicateCount(
+                        shardRouting -> shardRouting.primary()
+                            // We need to ensure atleast one of the primaries is being recovered from remote.
+                            // This ensures we have gone through the RemoteStoreRestoreService and routing table is updated
+                            && shardRouting.recoverySource() instanceof RecoverySource.RemoteStoreRecoverySource
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:133]: it is checking for all shards in the routingTable and not specific to current index. What is the reasoning for this logic though you are running this logic in the for loop

File: server/src/test/java/org/opensearch/gateway/ClusterStateUpdatersTests.java [hunk 6]
```diff
@@ -269,6 +275,214 @@ public void testUpdateRoutingTable() {
         }
     }
 
+    public void testSkipRoutingTableUpdateWhenRemoteRecovery() {
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/gateway/ClusterStateUpdatersTests.java:278]: can you add some comments in the test with respect to different scenarios being tested.

File: server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java (hunk 1 above)
Comment (shwetathareja) [reply server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java]: > Some old remote store recovery integ tests which were passing earlier have started to fail, those i need to handle

why did those test fail?

File: server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java (hunk 5 above)
Comment (linuxpi) [reply server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:133]: this is a miss in refactoring. `shardsMatchingPredicateCount` is supposed to run for the specific index only. will update this

File: server/src/test/java/org/opensearch/gateway/ClusterStateUpdatersTests.java (hunk 6 above)
Comment (linuxpi) [reply server/src/test/java/org/opensearch/gateway/ClusterStateUpdatersTests.java:278]: sure, done

File: server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java (hunk 5 above)
Comment (linuxpi) [reply server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java]: update the code and added a UT to cover this scenario as well.

File: server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java (hunk 1 above)
Comment (linuxpi) [reply server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java]: > We did not have iteg tests which were failing earlier due to this reason.

Correction. The new integ tests which we wrote for Remote Cluster state were already failing and after this change they are passing.

> Some old remote store recovery integ tests which were passing earlier have started to fail, those i need to handle

These were failing with the first version of the PR. now they are not failing as we have moved the check to a place where is less intrusive to existing flows

File: server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java (hunk 4 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java:124]: can we add an assert?

**Review by Bukhtawar — COMMENTED** [review]
Wondering if we can get the local state recovery first and then override with remote state instead of the other way round?

**Comment by linuxpi** [comment]
> Wondering if we can get the local state recovery first and then override with remote state instead of the other way round?

yes @Bukhtawar , we have discussed a similar solution. But one thing to note there is in case of remote state recovery, local state is lost, that is why we went to remote in the first place.

What we can do is instead of populating the routing table during remote state recovery, we can just populate the Metadata and populate the RoutingTable in `ClusterStateUpdaters.updateRoutingTable` with RemoteStoreRecoverySource. 

We would add a check here that if the index is remote enabled then populate with RemoteStoreRecoverySource otherwise the existing flow would run.

CC: @sachinpkale @shwetathareja

**Comment by soosinha** [comment]
LGTM

**Review by soosinha — APPROVED** [review]

**Comment by linuxpi** [comment]
Tests with failures:
 - org.opensearch.snapshots.CloneSnapshotIT.testCloneAfterRepoShallowSettingDisabled {seed=[D5F195028D9B00DD:B154F260AC51D7B4]}

10 tests completed, 1 failed


### Test Failures

[org.opensearch.repositories.azure.AzureBlobContainerRetriesTests.testReadRangeBlobWithRetries](https://build.ci.opensearch.org/job/gradle-check/25667/testReport/junit/org.opensearch.repositories.azure/AzureBlobContainerRetriesTests/testReadRangeBlobWithRetries/)
    [org.opensearch.repositories.azure.AzureBlobContainerRetriesTests.testWriteLargeBlob](https://build.ci.opensearch.org/job/gradle-check/25667/testReport/junit/org.opensearch.repositories.azure/AzureBlobContainerRetriesTests/testWriteLargeBlob/)
    [org.opensearch.remotestore.RemoteRestoreSnapshotIT.testRestoreShallowSnapshotRepositoryOverriden](https://build.ci.opensearch.org/job/gradle-check/25667/testReport/junit/org.opensearch.remotestore/RemoteRestoreSnapshotIT/testRestoreShallowSnapshotRepositoryOverriden/)
    [org.opensearch.remotestore.RemoteStoreRestoreIT.testRateLimitedRemoteDownloads](https://build.ci.opensearch.org/job/gradle-check/25667/testReport/junit/org.opensearch.remotestore/RemoteStoreRestoreIT/testRateLimitedRemoteDownloads/) -- https://github.com/opensearch-project/OpenSearch/pull/9887
    [org.opensearch.snapshots.CloneSnapshotIT.testCloneAfterRepoShallowSettingDisabled](https://build.ci.opensearch.org/job/gradle-check/25667/testReport/junit/org.opensearch.snapshots/CloneSnapshotIT/testCloneAfterRepoShallowSettingDisabled/)

Ran locally as well with 10 iterations. all tests are passing. Only testCloneAfterRepoShallowSettingDisabled failed once out of 10
Tests with failures:
 - org.opensearch.snapshots.CloneSnapshotIT.testCloneAfterRepoShallowSettingDisabled {seed=[D5F195028D9B00DD:B154F260AC51D7B4]}

10 tests completed, 1 failed

File: server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java [hunk 7]
```diff
@@ -187,7 +187,7 @@ private RemoteRestoreResult executeRestore(
             IndexMetadata indexMetadata = indexMetadataEntry.getValue().v2();
             boolean metadataFromRemoteStore = indexMetadataEntry.getValue().v1();
             IndexMetadata updatedIndexMetadata = indexMetadata;
-            if (restoreAllShards || metadataFromRemoteStore) {
+            if (restoreAllShards) {
                 updatedIndexMetadata = IndexMetadata.builder(indexMetadata)
                     .state(IndexMetadata.State.OPEN)
                     .version(1 + indexMetadata.getVersion())
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java:193]: it was decided not to bump up the versions, you are addressing it somewhere else?

**Comment by shwetathareja** [comment]
> What we can do is instead of populating the routing table during remote state recovery, we can just populate the Metadata and populate the RoutingTable in ClusterStateUpdaters.updateRoutingTable with RemoteStoreRecoverySource. This is similar to how we are doing it for local disk state recovery as well.

In case you do this how will you identify it is local shard vs remote shard as you are doing it based on source? is there other way to identify the same?

File: server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java (hunk 7 above)
Comment (linuxpi) [reply server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java:193]: we removed the metadataFromRemoteStore flag in the if block above. whenever remote cluster state restore is done metadataFromRemoteStore is true. so now the versions wont be bumped.

**Comment by linuxpi** [comment]
> > What we can do is instead of populating the routing table during remote state recovery, we can just populate the Metadata and populate the RoutingTable in ClusterStateUpdaters.updateRoutingTable with RemoteStoreRecoverySource. This is similar to how we are doing it for local disk state recovery as well.
> 
> In case you do this how will you identify it is local shard vs remote shard as you are doing it based on source? is there other way to identify the same?

We would identify just based on index setting and the check for recovery source will be removed.

File: server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java (hunk 7 above)
Comment (shwetathareja) [reply server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java:193]: Thats a sneaky check, in case of metadataFromRemoteStore is true and restoreAllShards is true, it will bump the version which is not very explicit.

Comment (linuxpi) [reply server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java:193]: okay. let me update to `metadataFromRemoteStore == false && restoreAllShards`

**Review by shwetathareja — APPROVED** [review]
