### PR TITLE
enabled mockTelemetryPlugin for IT and fixed OOM

### LINKED ISSUE #12615: [BUG] org.opensearch.test.telemetry.tracing.validators.AllSpansHaveUniqueId fails with java.lang.OutOfMemoryError sporadically
### Describe the bug

The `org.opensearch.test.telemetry.tracing.validators.AllSpansHaveUniqueId` fails with java.lang.OutOfMemoryError sporadically:

```
java.lang.OutOfMemoryError: Java heap space
	at __randomizedtesting.SeedInfo.seed([11E79186241F3EB2:AD561042C55D1621]:0)
	at java.base/java.util.HashMap.newNode(HashMap.java:1909)
	at java.base/java.util.HashMap.putVal(HashMap.java:637)
	at java.base/java.util.HashMap.put(HashMap.java:618)
	at java.base/java.util.HashSet.add(HashSet.java:229)
	at org.opensearch.test.telemetry.tracing.validators.AllSpansHaveUniqueId.validate(AllSpansHaveUniqueId.java:42)
	at org.opensearch.test.telemetry.tracing.TelemetryValidators.validate(TelemetryValidators.java:37)
	at org.opensearch.test.telemetry.tracing.StrictCheckSpanProcessor.validateTracingStateOnShutdown(StrictCheckSpanProcessor.java:79)
	at org.opensearch.test.OpenSearchTestClusterRule.afterClass(OpenSearchTestClusterRule.java:99)
	at org.opensearch.test.OpenSearchTestClusterRule.initializeSuiteScope(OpenSearchTestClusterRule.java:399)
	at org.opensearch.test.OpenSearchTestClusterRule.before(OpenSearchTestClusterRule.java:168)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:365)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
```

### Related component

Other

### To Reproduce

Not easy to reproduce by see please:
 - https://build.ci.opensearch.org/job/gradle-check/34686/testReport/junit/org.opensearch.search.aggregations.metrics/ExtendedStatsIT/testScriptSingleValued__p0___search_concurrent_segment_search_enabled___true___/

### Expected behavior

No java.lang.OutOfMemoryError  should be raised

### Additional Details

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/34686/testReport/junit/org.opensearch.search.aggregations.metrics/ExtendedStatsIT/testScriptSingleValued__p0___search_concurrent_segment_search_enabled___true___/
- https://build.ci.opensearch.org/job/gradle-check/33741/testReport/junit/org.opensearch.search.aggregations.metrics/GeoCentroidIT/testMultiValuedField__p0___search_concurrent_segment_search_enabled___true___/

### PR DESCRIPTION
**Pull request by atharvasharma61**
### Description
 PR to test OOM fix during ITs. Since a lot of spans are generated during the testing, by default, we are disabling the stackTraceElement data from the MockSpanData which aims to significantly reduce the memory usage. It can be re-enabled manually if needed for debugging purposes.

### Related Issues
Resolves #12615

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java [hunk 1]
```diff
@@ -2071,7 +2071,7 @@ protected boolean addMockGeoShapeFieldMapper() {
      */
     protected boolean addMockTelemetryPlugin() {
         // setting to false until https://github.com/opensearch-project/OpenSearch/issues/12615 is resolved
```
Comment (kkmr) [inline test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:2073]: Fix this comment?

**Comment by kkmr** [comment]
Can you add some comments in the PR description on why this change fixes the issue?

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java [hunk 2]
```diff
@@ -2071,7 +2071,7 @@ protected boolean addMockGeoShapeFieldMapper() {
...
-        return false;
+        return true;
```
Comment (mch2) [inline test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:2074]: Do we need/want this to run every time? Can we randomly enable [here](https://github.com/opensearch-project/OpenSearch/blob/52ae79d017a8e961cc1bc81fa7eafcc59689a447/test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java#L2121) similar to other mock plugins?

File: test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java [hunk 3]
```diff
@@ -60,7 +60,7 @@ private MockSpanData toMockSpanData(Span span) {
             System.nanoTime(),
             false,
             span.getSpanName(),
-            Thread.currentThread().getStackTrace(),
+            null,
```
Comment (reta) [inline test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java:63]: Please remove `stackTraceElement[] stackTrace` altogether, this was the only place it was used

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java (hunk 2 above)
Comment (atharvasharma61) [reply test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:2073]: @Gaganjuneja @reta What do you guys think we should do there?

File: test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java (hunk 3 above)
Comment (atharvasharma61) [reply test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java]: Putting it behind a flag so that it can be re-enabled if needed for debugging purposes.

**Comment by atharvasharma61** [comment]
> ❌ Gradle check result for [c5edd1a](https://github.com/opensearch-project/OpenSearch/commit/c5edd1a71db5f6964cd215934f01cfe807fbaad9): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/36474/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Failed task -> Execution failed for task ':distribution:bwc:staged:buildBwcLinuxTar'.
Not sure why it is failing.

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java (hunk 2 above)
Comment (reta) [reply test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:2073]: We used to run it every time since this is the only "safety net" we have for it at the moment

**Comment by atharvasharma61** [comment]
@reta Can you please check if it looks good?

File: test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java [hunk 4]
```diff
@@ -29,6 +30,14 @@ public StrictCheckSpanProcessor() {}
 
     private static Map<String, MockSpanData> spanMap = new ConcurrentHashMap<>();
 
+    // If you want to see the stack trace for each spanData, then
+    // update the flag to true or set the corresponding system property to true
+    // This is helpful in debugging the tests. Default value is false.
+    // Note: Enabling this might lead to OOM issues while running ITs.
+    private static final boolean isStackTraceForSpanEnabled = Booleans.parseBoolean(
```
Comment (reta) [inline test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java:37]: Please update `TESTING.md` to document this behaviour (and when could be useful), thank you.

**Comment by reta** [comment]
> ❌ Gradle check result for [15629fc](https://github.com/opensearch-project/OpenSearch/commit/15629fc151cfc861a89f9206f060bc1efb10423f): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/37190/)

https://github.com/opensearch-project/OpenSearch/issues/13240

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@atharvasharma61 could you please backport to `2.x` manually? thank you
