### PR TITLE
Disable scoring of Keyword Term search by default, allow user use old logic using useSimilarity parameter

### LINKED ISSUE #17823: [BUG] Disable scoring of Keyword Term search in order to avoid regression since 2.18
### Describe the bug

As a follow up to https://github.com/opensearch-project/OpenSearch/issues/17078

### Background

In OpenSearch [keyword field](https://opensearch.org/docs/latest/field-types/supported-field-types/keyword/) is intended for match docs instead of full text search. As such, keyword field do not have freq or analysis enabled. 

### Problem

As of 2.18 the simple term query performance regression from 5ms to 200ms using big5's `process.name` keyword field, for details see: https://github.com/apache/lucene/issues/14445

### Proposal

One of the workarounds provided by @msfroh  and @expani is to wrap a keyword term query with https://opensearch.org/docs/latest/query-dsl/compound/constant-score/.

We propose to add the constant scorer for any term search for keyword field by default. The search performance comes back to 2.17 but one side effect is the score. 

For single term it doesn't make a difference but for multi term search, even though there is no freq info but idf is calculated if more than one term matches the doc. We believe this would for very minor set of users, most users only use keyword term match for exists/filter cases. 

#### New Keyword Parameter: useSimilarity

Just in case some reason does require the actual score, we can provide an opt-in setting. We can provide a new Keyword parameter of `useSimilarity` with default value of `false`. For backward compatibility the user can set this value to `true` at the cost of search latency. 

#### Alternative

There is already a paramteter `similarity`. Documentation mentions default is `BM25` but infact its the default of the index option (which often is `BM25` but not neccessarily`). 

One proposal can be change the default to `null`, but there is limitation that if this is expliclty set to `nul` by a user we cannot differentiate it from not existant value: https://github.com/asimmahmood1/OpenSearch/blob/8ca3e6ad51d73b6b89cb88eca8f4c759f708e59b/server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java#L230

This also makes OS upgrades tricky. Even though adding a new parameter has burden adding complexity, in this case the complexity will only for very few users that need the backward compatible query score on keyword term search.

### Related component

_No response_

### To Reproduce

To reproduce this issue, see https://github.com/apache/lucene/issues/14445

### Expected behavior

No regression in latency when upgrading from OS 2.17 to OS 2.19 or 3.0.

### Additional Details

 - Version [2.18,2.19,3.0+]

**Additional context**

### PR DESCRIPTION
**Pull request by asimmahmood1**
### Description
* for motivation see related issue
* Had to modify more unit tests than expected, do review the changes 

### Related Issues
Resolves #17823

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [#9600](https://github.com/opensearch-project/documentation-website/pull/9600), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

### Testing with useSimilarity:true, took time 10ms, score 1.0
```
dev-dsk-asimmahm-2c-a6d21262 %  curl -X PUT "http://localhost:9200/big5/_mapping?pretty" \
-H "Content-Type: application/json" \
-d '{
  "properties": {
    "process.name": {
       "type":"keyword", "useSimilarity": false
    }
  }
}'
{
  "acknowledged" : true
}

(25-04-11 0:12:34) <0> [~/workplace/OpenSearch]
dev-dsk-asimmahm-2c-a6d21262 % curl -X POST "http://localhost:9200/big5/_search?pretty=true" \
-H "Content-Type: application/json" \
-d '{"size":3, "explain": false,
  "query": {
    "term": {
      "process.name": "kernel"
    }
  },"_source":false
}'
{
  "took" : 10,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "big5",
        "_id" : "xDoCtJQBE3c7bAfikzbk",
        "_score" : 1.0
      },
      {
        "_index" : "big5",
        "_id" : "xzoCtJQBE3c7bAfikzbk",
        "_score" : 1.0
      },
      {
        "_index" : "big5",
        "_id" : "yDoCtJQBE3c7bAfikzbk",
        "_score" : 1.0
      }
    ]
  }
}

```

### Testing with useSimilarity:true, took time 200ms, score 0.8...

```
dev-dsk-asimmahm-2c-a6d21262 %  curl -X PUT "http://localhost:9200/big5/_mapping?pretty" \
-H "Content-Type: application/json" \
-d '{
  "properties": {
    "process.name": {
       "type":"keyword", "useSimilarity": true
    }
  }
}'
{
  "acknowledged" : true
}

(25-04-11 0:16:04) <0> [~/workplace/OpenSearch]
dev-dsk-asimmahm-2c-a6d21262 % GET "http://localhost:9200/big5/_mapping/field/process.name?pretty=true"
{
  "big5" : {
    "mappings" : {
      "process.name" : {
        "full_name" : "process.name",
        "mapping" : {
          "name" : {
            "type" : "keyword",
            "useSimilarity" : true
          }
        }
      }
    }
  }
}
dev-dsk-asimmahm-2c-a6d21262 % curl -X POST "http://localhost:9200/big5/_search?pretty=true" \
-H "Content-Type: application/json" \
-d '{"size":3, "explain": false,
  "query": {
    "term": {
      "process.name": "kernel"
    }
  },"_source":false
}'
{
  "took" : 200,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : 0.8844931,
    "hits" : [
      {
        "_index" : "big5",
        "_id" : "xDoCtJQBE3c7bAfikzbk",
        "_score" : 0.8844931
      },
      {
        "_index" : "big5",
        "_id" : "xzoCtJQBE3c7bAfikzbk",
        "_score" : 0.8844931
      },
      {
        "_index" : "big5",
        "_id" : "yDoCtJQBE3c7bAfikzbk",
        "_score" : 0.8844931
      }
    ]
  }
}


By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rishabh6788** [comment]
{"run-benchmark-test": "id_1"}

**Comment by rishabh6788** [comment]
{"run-benchmark-test": "id_4"}

**Comment by asimmahmood1** [comment]
I'm getting this error when trying to update the mapping:

```
dev-dsk-asimmahm-2c-a6d21262 % curl -X PUT "http://localhost:9200/big5/_mapping?pretty" \
-H "Content-Type: application/json" \
-d '{
  "properties": {
    "process.name": {
       "type":"keyword", "useSimilarity": true
    }
  }
}'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "unknown parameter [useSimilarity] on mapper [name] of type [keyword]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "unknown parameter [useSimilarity] on mapper [name] of type [keyword]"
  },
  "status" : 400
}
```

Without that useSimilarity it works:

```
dev-dsk-asimmahm-2c-a6d21262 % curl -X PUT "http://localhost:9200/big5/_mapping?pretty" \
-H "Content-Type: application/json" \
-d '{
  "properties": {
    "process.name": {
       "type":"keyword"
    }
  }
}'
{
  "acknowledged" : true
}
```

File: server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java [hunk 1]
```diff
@@ -425,7 +443,14 @@ public Query termQueryCaseInsensitive(Object value, QueryShardContext context) {
         public Query termQuery(Object value, QueryShardContext context) {
             failIfNotIndexedAndNoDocValues();
             if (isSearchable()) {
-                return super.termQuery(value, context);
+                Query query = super.termQuery(value, context);
+                if (!this.useSimilarity) {
+                    query = new ConstantScoreQuery(super.termQuery(value, context));
```
Comment (expani) [inline server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java:448]: Should we wrap other query types as well ? 
Like `termsQuery` and other variants

**Comment by asimmahmood1** [comment]
{"run-benchmark-test": "id_1"}

**Comment by asimmahmood1** [comment]
{"run-benchmark-test": "id_1"}

**Comment by asimmahmood1** [comment]
{"run-benchmark-test": "id_4"}

File: server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java (hunk 1 above)
Comment (asimmahmood1) [reply server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java:448]: Looks TermInSetQuery already acts like Constant scorer (no regression):

```
dev-dsk-asimmahm-2c-a6d21262 % curl -X POST "http://localhost:9200/big5/_search?pretty=true" \
-H "Content-Type: application/json" \
-d '{
  "size": 3,
  "explain": false,
  "query": {
    "terms": {
      "process.name": ["kernel","journal"]

    }
  },
  "_source": false
}'
{
  "took" : 5,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "big5",
        "_id" : "xDoCtJQBE3c7bAfikzbk",
        "_score" : 1.0
      },
      {
        "_index" : "big5",
        "_id" : "xzoCtJQBE3c7bAfikzbk",
        "_score" : 1.0
      },
      {
        "_index" : "big5",
        "_id" : "yDoCtJQBE3c7bAfikzbk",
        "_score" : 1.0
      }
    ]
  }
}
```

**Comment by asimmahmood1** [comment]
{"run-benchmark-test": "id_1"}

**Comment by asimmahmood1** [comment]
{"run-benchmark-test": "id_4"}

**Comment by asimmahmood1** [comment]
Test report shows no failure: https://build.ci.opensearch.org/job/gradle-check/56196/testReport/


But the log message shows  https://build.ci.opensearch.org/job/gradle-check/56196/

```
* What went wrong:
Execution failed for task ':example-plugins:custom-significance-heuristic:yamlRestTest'.
> Process 'Gradle Test Executor 508' finished with non-zero exit value 1
  This problem might be caused by incorrect test process configuration.
```

Ran this myself 3x and no failures

```
dev-dsk-asimmahm-2c-a6d21262 % ./gradlew :example-plugins:custom-significance-heuristic:yamlRestTest
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.13
  OS Info               : Linux 5.10.234-206.921.amzn2int.x86_64 (amd64)
  JDK Version           : 21 (Amazon Corretto JDK)
  JAVA_HOME             : /usr/lib/jvm/java-21-amazon-corretto
  Random Testing Seed   : 5D850CD2569685D8
  In FIPS 140 mode      : false
=======================================

> Task :example-plugins:custom-significance-heuristic:yamlRestTest
WARNING: Using incubator modules: jdk.incubator.vector

BUILD SUCCESSFUL in 22s
212 actionable tasks: 5 executed, 207 up-to-date

```

**Comment by peterzhuamazon** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':example-plugins:custom-significance-heuristic:yamlRestTest'.
> Process 'Gradle Test Executor 508' finished with non-zero exit value 1
  This problem might be caused by incorrect test process configuration.
  For more on test execution, please refer to https://docs.gradle.org/8.13/userguide/java_testing.html#sec:test_execution in the Gradle documentation.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org/.

BUILD FAILED in 17m 29s
```

**Comment by asimmahmood1** [comment]
I think these are flaky tests:

```
[Test Result](https://build.ci.opensearch.org/job/gradle-check/56212/testReport/) (7 failures / +7)

    [org.opensearch.rest.ReactorNetty4StreamingStressIT.testCloseClientStreamingRequest](https://build.ci.opensearch.org/job/gradle-check/56212/testReport/junit/org.opensearch.rest/ReactorNetty4StreamingStressIT/testCloseClientStreamingRequest/)
    [org.opensearch.remotestore.multipart.RemoteStoreMultipartCoreTestCase.testNoSearchIdleForAnyReplicaCount](https://build.ci.opensearch.org/job/gradle-check/56212/testReport/junit/org.opensearch.remotestore.multipart/RemoteStoreMultipartCoreTestCase/testNoSearchIdleForAnyReplicaCount/)
    [org.opensearch.snapshots.DedicatedClusterSnapshotRestoreIT.testSnapshotWithStuckNode](https://build.ci.opensearch.org/job/gradle-check/56212/testReport/junit/org.opensearch.snapshots/DedicatedClusterSnapshotRestoreIT/testSnapshotWithStuckNode/)
    [org.opensearch.snapshots.DedicatedClusterSnapshotRestoreIT.testSnapshotWithStuckNode](https://build.ci.opensearch.org/job/gradle-check/56212/testReport/junit/org.opensearch.snapshots/DedicatedClusterSnapshotRestoreIT/testSnapshotWithStuckNode_2/)
    [org.opensearch.snapshots.DedicatedClusterSnapshotRestoreIT.testSnapshotWithStuckNode](https://build.ci.opensearch.org/job/gradle-check/56212/testReport/junit/org.opensearch.snapshots/DedicatedClusterSnapshotRestoreIT/testSnapshotWithStuckNode_3/)
    [org.opensearch.snapshots.DedicatedClusterSnapshotRestoreIT.testSnapshotWithStuckNode](https://build.ci.opensearch.org/job/gradle-check/56212/testReport/junit/org.opensearch.snapshots/DedicatedClusterSnapshotRestoreIT/testSnapshotWithStuckNode_4/)
    [org.opensearch.rest.ReactorNetty4StreamingStressIT.classMethod](https://build.ci.opensearch.org/job/gradle-check/56212/testReport/junit/org.opensearch.rest/ReactorNetty4StreamingStressIT/classMethod/)
```

**Review by msfroh — APPROVED** [review]

**Comment by asimmahmood1** [comment]
Current run is going to fail with 

```
Tests with failures:
 - org.opensearch.snapshots.DedicatedClusterSnapshotRestoreIT.testSnapshotWithStuckNode

5261 tests completed, 1 failed, 43 skipped
```

**Comment by msfroh** [comment]
Retriggered the Gradle check

**Comment by asimmahmood1** [comment]
Failure was real. In case I also where we do `X instanceof BoostQuery` to also
  check for `ConstantScoreQuery`

```
»  Caused by: java.lang.IllegalArgumentException: Cannot extract a term from a query of type class org.apache.lucene.search.ConstantScoreQuery: ConstantScore(keyword_field:value1)
»  	at org.opensearch.index.mapper.MappedFieldType.extractTerm(MappedFieldType.java:501) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»  	at org.opensearch.index.query.SpanTermQueryBuilder.doToQuery(SpanTermQueryBuilder.java:104) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»  	at org.opensearch.index.query.SpanTermQueryBuilder.doToQuery(SpanTermQueryBuilder.java:54) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
```

**Review by peterzhuamazon — APPROVED** [review]
