### PR TITLE
Fixing allocation filters to persist existing state on settings update

### LINKED ISSUE #1716: Excluding some attribute from allocation filter overrides the existing exclusion attributes
**Describe the bug**
Excluding some attribute from allocation filter overrides the existing exclusion attributes. Same is the case for include/require as FilterAllocationDecider recreates the filters from the difference passed to settings update consumer

**To Reproduce**
Exclude an ip from cluster settings:

```
curl -H "Content-Type: application/json" -XPUT localhost:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._ip" : "10.212.1.19"
    }
}'
```
Exclude another attribute say zone:
```
curl -H "Content-Type: application/json" -XPUT localhost:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude.zone" : "us-west-2a"
    }
}'
```
Even though cluster setting shows both ip and zone, only zone filtering is honored as it was applied later

**Expected behavior**
For the reproduced behavior, both zone and ip exclusion should have been honored

**Host/Environment (please complete the following information):**
 - Impacts all Opensearch versions

### PR DESCRIPTION
**Pull request by jainankitk**
Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>

### Description
Instead of recreating the filters from the difference passed to settings update consumer, existing filters are updated to preserve original settings as well
 
### Issues Resolved
#1716
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
This needs tests, please.

As a nice to have, there's a bit of duplication going on, I think we can do better with a helper, maybe something along these lines?

```java
clusterExcludeFilters = DiscoveryNodeFilters.trimTier(
   DiscoveryNodeFilters.createOrAppend(
       clusterExcludeFilters,
       OR,
       filters
   )
)
```

**Comment by jainankitk** [comment]
> This needs tests, please.

Thanks dblock@! Already working on that

> As a nice to have, there's a bit of duplication going on, I think we can do better with a helper, maybe something along these lines?
> 
> ```java
> clusterExcludeFilters = DiscoveryNodeFilters.trimTier(
>    DiscoveryNodeFilters.createOrAppend(
>        clusterExcludeFilters,
>        OR,
>        filters
>    )
> )
> ```

Since clusterExcludeFilters is volatile setting, reading and writing it on same line gives warning. Maybe we can ignore that warning, anyways we are cloning `clusterExcludeFilters` before editing?

**Comment by dblock** [comment]
> Since clusterExcludeFilters is volatile setting, reading and writing it on same line gives warning. Maybe we can ignore that warning, anyways we are cloning `clusterExcludeFilters` before editing?

Possibly. Can this code be called in parallel? Meaning, is there a thread safety problem where I make two calls to `setClusterRequireFilters` that adds some filters, and only get the second result applied?

**Comment by jainankitk** [comment]
> Possibly. Can this code be called in parallel? Meaning, is there a thread safety problem where I make two calls to setClusterRequireFilters that adds some filters, and only get the second result applied?

Actually thinking more on this, it cannot happen as this code runs from cluster applier which is single threaded. I have updated the code with your feedback.

File: server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeFilters.java [hunk 1]
```diff
@@ -69,18 +69,30 @@
...
-    public static DiscoveryNodeFilters buildFromKeyValue(OpType opType, Map<String, String> filters) {
-        Map<String, String[]> bFilters = new HashMap<>();
+    /**
+     * Creates or updates filters returning a new {@link DiscoveryNodeFilters} object.
+     * If the new object has no filters, {@code null} is returned.
+     */
+    @Nullable
+    public static DiscoveryNodeFilters buildOrUpdateFromKeyValue(
+        final DiscoveryNodeFilters original,
+        final OpType opType,
```
Comment (andrross) [inline server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeFilters.java:79]: The thing I don't like about this method signature is that `opType` is unused if `original` is non-null. What if this is called where `original.opType != opType`? Seems like opportunity for confusion. Unfortunately this seems like a consequence of using null to represent no filters and I don't really have a suggestion that avoids some code duplication. I would at least add a unit test that asserts the behavior if there is an opType mismatch.

Comment (jainankitk) [reply server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeFilters.java:79]: > The thing I don't like about this method signature is that opType is unused if original is non-null. What if this is called where original.opType != opType? Seems like opportunity for confusion. Unfortunately this seems like a consequence of using null to represent no filters and I don't really have a suggestion that avoids some code duplication.

Good catch! I also found it weird, but could not think of clean solution

> I would at least add a unit test that asserts the behavior if there is an opType mismatch.

I have added change to assert the behavior. Let me know what you think.

**Comment by jainankitk** [comment]
@dblock - Can you restart gradle check? Looks intermittent failure to me

**Comment by jainankitk** [comment]
@dblock - Can you restart gradle check? Looks intermittent failure to me

File: server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java [hunk 2]
```diff
@@ -224,6 +224,97 @@ public void testTierFilterIgnored() {
...
+        decision = (Decision.Single) filterAllocationDecider.canAllocate(
+            routingTable.index("idx").shard(0).shards().get(0),
+            state.getRoutingNodes().node("node2"),
+            allocation
+        );
+        assertEquals(decision.toString(), type2, decision.type());
+        assertEquals(explanation2, decision.getExplanation());
+    }
+
+    public void testFilterUpdate1() {
```
Comment (andrross) [inline server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java:273]: Nitpick, but can you give these tests meaningful names? Like this one could be (if I understand it correctly) "testFilterUpdateAddFillter". Same comment applies to the following two tests.

**Review by andrross — APPROVED** [review]
Looks good, just a nitpick about test names.

File: server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java (hunk 2 above)
Comment (jainankitk) [reply server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java]: Updated test names to make them more meaningful!

**Comment by jainankitk** [comment]
@dblock - Can you restart gradle check? Looks intermittent failure to me

**Comment by dblock** [comment]
> @dblock - Can you restart gradle check? Looks intermittent failure to me

doing it; can you please look at the log and make sure there's a bug on the random failure(s)

**Comment by dblock** [comment]
start gradle check

**Review by andrross — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Thanks, please backport to 1.x

**Comment by jainankitk** [comment]
> Thanks, please backport to 1.x

https://github.com/opensearch-project/OpenSearch/pull/1780
