### PR TITLE
Fix race condition in IndexServiceTests

### LINKED ISSUE #14407: [AUTOCUT] Gradle Check Flaky Test Report for IndexServiceTests
## Flaky Test Report for `IndexServiceTests`

Noticed the `IndexServiceTests` has some flaky, failing tests that failed during **post-merge actions** and **timer trigerred run on main branch**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| main | [null](https://github.com/opensearch-project/OpenSearch/pull/null) | [65028](https://build.ci.opensearch.org/job/gradle-check/65028/testReport/) <br><br>[65063](https://build.ci.opensearch.org/job/gradle-check/65063/testReport/) <br><br>[63984](https://build.ci.opensearch.org/job/gradle-check/63984/testReport/) <br><br>[64101](https://build.ci.opensearch.org/job/gradle-check/64101/testReport/) <br><br>[64110](https://build.ci.opensearch.org/job/gradle-check/64110/testReport/) <br><br>[64482](https://build.ci.opensearch.org/job/gradle-check/64482/testReport/) <br><br>[64542](https://build.ci.opensearch.org/job/gradle-check/64542/testReport/) <br><br>[64721](https://build.ci.opensearch.org/job/gradle-check/64721/testReport/) <br><br>[64901](https://build.ci.opensearch.org/job/gradle-check/64901/testReport/) <br><br>[41808](https://build.ci.opensearch.org/job/gradle-check/41808/testReport/) <br><br>[47833](https://build.ci.opensearch.org/job/gradle-check/47833/testReport/) <br><br>[51801](https://build.ci.opensearch.org/job/gradle-check/51801/testReport/) <br><br>[52008](https://build.ci.opensearch.org/job/gradle-check/52008/testReport/) <br><br>[55011](https://build.ci.opensearch.org/job/gradle-check/55011/testReport/) <br><br>[60323](https://build.ci.opensearch.org/job/gradle-check/60323/testReport/) <br><br>[60667](https://build.ci.opensearch.org/job/gradle-check/60667/testReport/) <br><br>[60866](https://build.ci.opensearch.org/job/gradle-check/60866/testReport/) <br><br>[60986](https://build.ci.opensearch.org/job/gradle-check/60986/testReport/) <br><br>[61789](https://build.ci.opensearch.org/job/gradle-check/61789/testReport/) <br><br>[61830](https://build.ci.opensearch.org/job/gradle-check/61830/testReport/) <br><br>[62116](https://build.ci.opensearch.org/job/gradle-check/62116/testReport/) <br><br>[62314](https://build.ci.opensearch.org/job/gradle-check/62314/testReport/) <br><br>[62450](https://build.ci.opensearch.org/job/gradle-check/62450/testReport/) <br><br>[62482](https://build.ci.opensearch.org/job/gradle-check/62482/testReport/) <br><br>[62598](https://build.ci.opensearch.org/job/gradle-check/62598/testReport/) <br><br>[63329](https://build.ci.opensearch.org/job/gradle-check/63329/testReport/) <br><br>[63336](https://build.ci.opensearch.org/job/gradle-check/63336/testReport/) <br><br>[63475](https://build.ci.opensearch.org/job/gradle-check/63475/testReport/) <br><br>[63628](https://build.ci.opensearch.org/job/gradle-check/63628/testReport/) <br><br>[63696](https://build.ci.opensearch.org/job/gradle-check/63696/testReport/) <br><br>[63747](https://build.ci.opensearch.org/job/gradle-check/63747/testReport/) <br><br>[63750](https://build.ci.opensearch.org/job/gradle-check/63750/testReport/) <br><br>[63774](https://build.ci.opensearch.org/job/gradle-check/63774/testReport/) <br><br>[63793](https://build.ci.opensearch.org/job/gradle-check/63793/testReport/) <br><br>[63844](https://build.ci.opensearch.org/job/gradle-check/63844/testReport/) <br><br>[63850](https://build.ci.opensearch.org/job/gradle-check/63850/testReport/) <br><br>[63855](https://build.ci.opensearch.org/job/gradle-check/63855/testReport/) <br><br>[63875](https://build.ci.opensearch.org/job/gradle-check/63875/testReport/) <br><br>[63880](https://build.ci.opensearch.org/job/gradle-check/63880/testReport/) <br><br>[63897](https://build.ci.opensearch.org/job/gradle-check/63897/testReport/) <br><br>[63922](https://build.ci.opensearch.org/job/gradle-check/63922/testReport/) <br><br>[63940](https://build.ci.opensearch.org/job/gradle-check/63940/testReport/) <br><br>[63950](https://build.ci.opensearch.org/job/gradle-check/63950/testReport/) <br><br>[63969](https://build.ci.opensearch.org/job/gradle-check/63969/testReport/) <br><br>[63989](https://build.ci.opensearch.org/job/gradle-check/63989/testReport/) <br><br>[63998](https://build.ci.opensearch.org/job/gradle-check/63998/testReport/) <br><br>[64023](https://build.ci.opensearch.org/job/gradle-check/64023/testReport/) <br><br>[64061](https://build.ci.opensearch.org/job/gradle-check/64061/testReport/) <br><br>[64181](https://build.ci.opensearch.org/job/gradle-check/64181/testReport/) <br><br>[64255](https://build.ci.opensearch.org/job/gradle-check/64255/testReport/) <br><br>[64279](https://build.ci.opensearch.org/job/gradle-check/64279/testReport/) <br><br>[64336](https://build.ci.opensearch.org/job/gradle-check/64336/testReport/) <br><br>[64345](https://build.ci.opensearch.org/job/gradle-check/64345/testReport/) <br><br>[64358](https://build.ci.opensearch.org/job/gradle-check/64358/testReport/) <br><br>[64404](https://build.ci.opensearch.org/job/gradle-check/64404/testReport/) <br><br>[64416](https://build.ci.opensearch.org/job/gradle-check/64416/testReport/) <br><br>[64432](https://build.ci.opensearch.org/job/gradle-check/64432/testReport/) <br><br>[64472](https://build.ci.opensearch.org/job/gradle-check/64472/testReport/) <br><br>[64502](https://build.ci.opensearch.org/job/gradle-check/64502/testReport/) <br><br>[64509](https://build.ci.opensearch.org/job/gradle-check/64509/testReport/) <br><br>[64554](https://build.ci.opensearch.org/job/gradle-check/64554/testReport/) <br><br>[64567](https://build.ci.opensearch.org/job/gradle-check/64567/testReport/) <br><br>[64650](https://build.ci.opensearch.org/job/gradle-check/64650/testReport/) <br><br>[64714](https://build.ci.opensearch.org/job/gradle-check/64714/testReport/) <br><br>[64719](https://build.ci.opensearch.org/job/gradle-check/64719/testReport/) <br><br>[64745](https://build.ci.opensearch.org/job/gradle-check/64745/testReport/) <br><br>[64781](https://build.ci.opensearch.org/job/gradle-check/64781/testReport/) <br><br>[64861](https://build.ci.opensearch.org/job/gradle-check/64861/testReport/) <br><br>[64862](https://build.ci.opensearch.org/job/gradle-check/64862/testReport/) <br><br>[64941](https://build.ci.opensearch.org/job/gradle-check/64941/testReport/) <br><br>[64960](https://build.ci.opensearch.org/job/gradle-check/64960/testReport/) <br><br>[64977](https://build.ci.opensearch.org/job/gradle-check/64977/testReport/) <br><br>[64987](https://build.ci.opensearch.org/job/gradle-check/64987/testReport/) <br><br>[65010](https://build.ci.opensearch.org/job/gradle-check/65010/testReport/) <br><br>[65017](https://build.ci.opensearch.org/job/gradle-check/65017/testReport/) <br><br>[65025](https://build.ci.opensearch.org/job/gradle-check/65025/testReport/) <br><br>[65045](https://build.ci.opensearch.org/job/gradle-check/65045/testReport/) <br><br>[65050](https://build.ci.opensearch.org/job/gradle-check/65050/testReport/) <br><br>[65059](https://build.ci.opensearch.org/job/gradle-check/65059/testReport/) <br><br>[65061](https://build.ci.opensearch.org/job/gradle-check/65061/testReport/) <br><br>[65093](https://build.ci.opensearch.org/job/gradle-check/65093/testReport/) <br><br>[65112](https://build.ci.opensearch.org/job/gradle-check/65112/testReport/) <br><br>[65119](https://build.ci.opensearch.org/job/gradle-check/65119/testReport/) <br><br>[67757](https://build.ci.opensearch.org/job/gradle-check/67757/testReport/) <br><br>[68087](https://build.ci.opensearch.org/job/gradle-check/68087/testReport/) <br><br>[71724](https://build.ci.opensearch.org/job/gradle-check/71724/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex`<br><br>`org.opensearch.index.IndexServiceTests.testBaseAsyncTaskWithFixedIntervalEnabledAndLongerRefresh` |
| 133e9d937293aa8d2bb1d45c7194a850ec73fa5b | [19687](https://github.com/opensearch-project/OpenSearch/pull/19687) | [65923](https://build.ci.opensearch.org/job/gradle-check/65923/testReport/) | `org.opensearch.index.IndexServiceTests.testBaseAsyncTaskWithFixedIntervalEnabledAndLongerRefresh` |
| 06d465f72a467ef67f2ab3358088f7b971c24238 | [19586](https://github.com/opensearch-project/OpenSearch/pull/19586) | [65259](https://build.ci.opensearch.org/job/gradle-check/65259/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 7a6b911b6d6bbec7c3e5653470177c0bff69d8d2 | [19565](https://github.com/opensearch-project/OpenSearch/pull/19565) | [65215](https://build.ci.opensearch.org/job/gradle-check/65215/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 39dc09bbdf1b5ceecc4dbf06d846e261f5957642 | [19540](https://github.com/opensearch-project/OpenSearch/pull/19540) | [65087](https://build.ci.opensearch.org/job/gradle-check/65087/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 54be22a2b778ad7bef3ab9bc7ebd2734e746834f | [19517](https://github.com/opensearch-project/OpenSearch/pull/19517) | [64997](https://build.ci.opensearch.org/job/gradle-check/64997/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 0f360bb54db61edc25742b31546cf2d490d2da46 | [19508](https://github.com/opensearch-project/OpenSearch/pull/19508) | [64957](https://build.ci.opensearch.org/job/gradle-check/64957/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 7dfe238f1a010fd16217f8699449dea090c59a1d | [19396](https://github.com/opensearch-project/OpenSearch/pull/19396) | [64947](https://build.ci.opensearch.org/job/gradle-check/64947/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 4269bdd5c0e780a41446a81fbcee3d8a78265c8c | [19497](https://github.com/opensearch-project/OpenSearch/pull/19497) | [64893](https://build.ci.opensearch.org/job/gradle-check/64893/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 1633e1ab24060b2a74a82a3c087a8f234dd97c1a | [19362](https://github.com/opensearch-project/OpenSearch/pull/19362) | [64875](https://build.ci.opensearch.org/job/gradle-check/64875/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 281702928a05f1f4d17a2707a3764b64f8d274dd | [18732](https://github.com/opensearch-project/OpenSearch/pull/18732) | [64829](https://build.ci.opensearch.org/job/gradle-check/64829/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 7de6eb8c643aaeb79bea9514318a7bf414bd5e51 | [19470](https://github.com/opensearch-project/OpenSearch/pull/19470) | [64824](https://build.ci.opensearch.org/job/gradle-check/64824/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 259add36d0ab51f04613efff9bdcdb6d148b3a09 | [19453](https://github.com/opensearch-project/OpenSearch/pull/19453) | [64811](https://build.ci.opensearch.org/job/gradle-check/64811/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 51a091bbde1baafe91f48acee59e292cbbf09f0e | [19373](https://github.com/opensearch-project/OpenSearch/pull/19373) | [64780](https://build.ci.opensearch.org/job/gradle-check/64780/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 08191974e6853d81417954c66f3a8d6c9a58b7d5 | [19340](https://github.com/opensearch-project/OpenSearch/pull/19340) | [64749](https://build.ci.opensearch.org/job/gradle-check/64749/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 765160067b3aa51ade52690a6f8c975c7a84ba21 | [19229](https://github.com/opensearch-project/OpenSearch/pull/19229) | [64740](https://build.ci.opensearch.org/job/gradle-check/64740/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 3965f6fe5d9abc26bc6f0299e21faa2753da1bcf | [19455](https://github.com/opensearch-project/OpenSearch/pull/19455) | [64699](https://build.ci.opensearch.org/job/gradle-check/64699/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| cef8d986c2e1ea8389716bd0cdcab452dd38121d | [19278](https://github.com/opensearch-project/OpenSearch/pull/19278) | [64666](https://build.ci.opensearch.org/job/gradle-check/64666/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 63eeb0d4e21cf57c1521372199439838294ee31a | [19443](https://github.com/opensearch-project/OpenSearch/pull/19443) | [64539](https://build.ci.opensearch.org/job/gradle-check/64539/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 1a7aa0dd470859710473148eda27af9fb34011ac | [19425](https://github.com/opensearch-project/OpenSearch/pull/19425) | [64469](https://build.ci.opensearch.org/job/gradle-check/64469/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 1103b3f2a99a0ecbe9a5ef371ada0f841fe6c947 | [19142](https://github.com/opensearch-project/OpenSearch/pull/19142) | [64263](https://build.ci.opensearch.org/job/gradle-check/64263/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| bb5f0e8bc6d27c7337c8ac290c0ff2f999444fab | [19356](https://github.com/opensearch-project/OpenSearch/pull/19356) | [64220](https://build.ci.opensearch.org/job/gradle-check/64220/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| af75e0b1cb32c957a7deeb8bfdc6e434d1878880 | [19152](https://github.com/opensearch-project/OpenSearch/pull/19152) | [64197](https://build.ci.opensearch.org/job/gradle-check/64197/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| a132bb562af966ac1daa815544d7607dc9a8edbd | [19360](https://github.com/opensearch-project/OpenSearch/pull/19360) | [64116](https://build.ci.opensearch.org/job/gradle-check/64116/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 7886c6f28bb603d4ebe76f6557014078c6f915ad | [19361](https://github.com/opensearch-project/OpenSearch/pull/19361) | [64042](https://build.ci.opensearch.org/job/gradle-check/64042/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| ff854c33a89e622ae48620bf3619ad486c3dc4dc | [19097](https://github.com/opensearch-project/OpenSearch/pull/19097) | [63938](https://build.ci.opensearch.org/job/gradle-check/63938/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| cae754d5b5e6580f3a5e67a771ec85df8f1872dc | [19316](https://github.com/opensearch-project/OpenSearch/pull/19316) | [63930](https://build.ci.opensearch.org/job/gradle-check/63930/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| c56da6897e8336398b9fe4187a97c90e42e06024 | [19296](https://github.com/opensearch-project/OpenSearch/pull/19296) | [63885](https://build.ci.opensearch.org/job/gradle-check/63885/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 28597dcc69b03b4e12f805f04f289c2545c1dd60 | [19191](https://github.com/opensearch-project/OpenSearch/pull/19191) | [63874](https://build.ci.opensearch.org/job/gradle-check/63874/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 1f9eb87ed9872cf24ecd25fd41644896f40cd2da | [19327](https://github.com/opensearch-project/OpenSearch/pull/19327) | [63857](https://build.ci.opensearch.org/job/gradle-check/63857/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| f6faa2f87bc71b87a1540d402441a1b89f51deeb | [19273](https://github.com/opensearch-project/OpenSearch/pull/19273) | [63826](https://build.ci.opensearch.org/job/gradle-check/63826/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| b9c5bc70661380650e769707cef8127ba9becd80 | [19184](https://github.com/opensearch-project/OpenSearch/pull/19184) | [63789](https://build.ci.opensearch.org/job/gradle-check/63789/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 01b34a89f80cfa5bf865e552c648c3ea86c4cb03 | [19281](https://github.com/opensearch-project/OpenSearch/pull/19281) | [63739](https://build.ci.opensearch.org/job/gradle-check/63739/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 2b9a968038b2b11eb37602a79b5c900debd6116c | [19153](https://github.com/opensearch-project/OpenSearch/pull/19153) | [62917](https://build.ci.opensearch.org/job/gradle-check/62917/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| c9eb7fbfa0da3186711b77d100ca152929f440c9 | [18922](https://github.com/opensearch-project/OpenSearch/pull/18922) | [62635](https://build.ci.opensearch.org/job/gradle-check/62635/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| e37b2cd3b646efdffd84f0209660d220e9a8d160 | [19107](https://github.com/opensearch-project/OpenSearch/pull/19107) | [62620](https://build.ci.opensearch.org/job/gradle-check/62620/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 9f28ef8a67de572ba18932e542aa880342db453a | [18825](https://github.com/opensearch-project/OpenSearch/pull/18825) | [62305](https://build.ci.opensearch.org/job/gradle-check/62305/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 7ff34ac31b8f9e757db1c0a872636d7ecd4beb85 | [18979](https://github.com/opensearch-project/OpenSearch/pull/18979) | [61983](https://build.ci.opensearch.org/job/gradle-check/61983/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 84b46d7c6132715414f70e01b2cc1c8dcf407370 | [18877](https://github.com/opensearch-project/OpenSearch/pull/18877) | [61513](https://build.ci.opensearch.org/job/gradle-check/61513/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 548e46791a0aa65067e13a6a8063e32252138f12 | [18775](https://github.com/opensearch-project/OpenSearch/pull/18775) | [60626](https://build.ci.opensearch.org/job/gradle-check/60626/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| ec5addab82d459743c5c6bb579e6573ecd610e03 | [18500](https://github.com/opensearch-project/OpenSearch/pull/18500) | [59161](https://build.ci.opensearch.org/job/gradle-check/59161/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 6de6f9354d2c3a10d33215ce5769a86c0538c660 | [18280](https://github.com/opensearch-project/OpenSearch/pull/18280) | [58081](https://build.ci.opensearch.org/job/gradle-check/58081/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 46955ff787ab990b12d1537b08512314be66f542 | [18199](https://github.com/opensearch-project/OpenSearch/pull/18199) | [57690](https://build.ci.opensearch.org/job/gradle-check/57690/testReport/) | `org.opensearch.index.IndexServiceTests.testBaseAsyncTaskWithFixedIntervalEnabledAndLongerRefresh` |
| 852011aac6ed5faecc38e3d285789a630a34168d | [16021](https://github.com/opensearch-project/OpenSearch/pull/16021) | [53136](https://build.ci.opensearch.org/job/gradle-check/53136/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| faabd10a28b1885fa25b206527b1b0cc5153f656 | [17229](https://github.com/opensearch-project/OpenSearch/pull/17229) | [53037](https://build.ci.opensearch.org/job/gradle-check/53037/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 8a5c3b53922a9bddc969ccd991401a369eb13ef5 | [17020](https://github.com/opensearch-project/OpenSearch/pull/17020) | [52460](https://build.ci.opensearch.org/job/gradle-check/52460/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| fa4595cf853f2f55b6a4ffc9f653330f6a25688d | [16757](https://github.com/opensearch-project/OpenSearch/pull/16757) | [52204](https://build.ci.opensearch.org/job/gradle-check/52204/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| d37cc9b32600faef17b3c898f8c86b0fd7640d72 | [16831](https://github.com/opensearch-project/OpenSearch/pull/16831) | [51449](https://build.ci.opensearch.org/job/gradle-check/51449/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| b75f27aa347f26aa528e291db81809491c79142f | [16737](https://github.com/opensearch-project/OpenSearch/pull/16737) | [51044](https://build.ci.opensearch.org/job/gradle-check/51044/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| d4d70d886ed5da1b657dca4c1e5af80ce9cd07ef | [16628](https://github.com/opensearch-project/OpenSearch/pull/16628) | [50777](https://build.ci.opensearch.org/job/gradle-check/50777/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 20536eef239031af1161fa341a57597e7219fcd5 | [16276](https://github.com/opensearch-project/OpenSearch/pull/16276) | [49322](https://build.ci.opensearch.org/job/gradle-check/49322/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| b2a7136722e9972edcf14ff03abd4f86ae4923b9 | [15945](https://github.com/opensearch-project/OpenSearch/pull/15945) | [47954](https://build.ci.opensearch.org/job/gradle-check/47954/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 3db252541cc843eb405c6dbb7c42712d3d612146 | [15192](https://github.com/opensearch-project/OpenSearch/pull/15192) | [44346](https://build.ci.opensearch.org/job/gradle-check/44346/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 170ea27a173c8a126bb2f031da9d3504eeb82208 | [14464](https://github.com/opensearch-project/OpenSearch/pull/14464) | [44287](https://build.ci.opensearch.org/job/gradle-check/44287/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 79f45be4a544dd3519521294b63bd1630c3dfd54 | [14437](https://github.com/opensearch-project/OpenSearch/pull/14437) | [43732](https://build.ci.opensearch.org/job/gradle-check/43732/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 0d01d1755e282763e5ea020112617ba25459863c | [14486](https://github.com/opensearch-project/OpenSearch/pull/14486) | [41616](https://build.ci.opensearch.org/job/gradle-check/41616/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |
| 21d3aaa8d2235b0e6fc2e9ce69f98b333c5aa293 | [14399](https://github.com/opensearch-project/OpenSearch/pull/14399) | [41157](https://build.ci.opensearch.org/job/gradle-check/41157/testReport/) | `org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `IndexServiceTests` class are:

- [15258](https://github.com/opensearch-project/OpenSearch/pull/15258)
- [18683](https://github.com/opensearch-project/OpenSearch/pull/18683)
- [19346](https://github.com/opensearch-project/OpenSearch/pull/19346)
- [17881](https://github.com/opensearch-project/OpenSearch/pull/17881)
- [15016](https://github.com/opensearch-project/OpenSearch/pull/15016)
- [19416](https://github.com/opensearch-project/OpenSearch/pull/19416)
- [19436](https://github.com/opensearch-project/OpenSearch/pull/19436)
- [19178](https://github.com/opensearch-project/OpenSearch/pull/19178)
- [19352](https://github.com/opensearch-project/OpenSearch/pull/19352)
- [16760](https://github.com/opensearch-project/OpenSearch/pull/16760)
- [18565](https://github.com/opensearch-project/OpenSearch/pull/18565)
- [19209](https://github.com/opensearch-project/OpenSearch/pull/19209)
- [19335](https://github.com/opensearch-project/OpenSearch/pull/19335)
- [19345](https://github.com/opensearch-project/OpenSearch/pull/19345)
- [19403](https://github.com/opensearch-project/OpenSearch/pull/19403)
- [19449](https://github.com/opensearch-project/OpenSearch/pull/19449)
- [19671](https://github.com/opensearch-project/OpenSearch/pull/19671)
- [20065](https://github.com/opensearch-project/OpenSearch/pull/20065)
- [16976](https://github.com/opensearch-project/OpenSearch/pull/16976)
- [18664](https://github.com/opensearch-project/OpenSearch/pull/18664)
- [18924](https://github.com/opensearch-project/OpenSearch/pull/18924)
- [19233](https://github.com/opensearch-project/OpenSearch/pull/19233)
- [19263](https://github.com/opensearch-project/OpenSearch/pull/19263)
- [19332](https://github.com/opensearch-project/OpenSearch/pull/19332)
- [19376](https://github.com/opensearch-project/OpenSearch/pull/19376)
- [19438](https://github.com/opensearch-project/OpenSearch/pull/19438)
- [19451](https://github.com/opensearch-project/OpenSearch/pull/19451)
- [19502](https://github.com/opensearch-project/OpenSearch/pull/19502)
- [13637](https://github.com/opensearch-project/OpenSearch/pull/13637)
- [14528](https://github.com/opensearch-project/OpenSearch/pull/14528)
- [15651](https://github.com/opensearch-project/OpenSearch/pull/15651)
- [15988](https://github.com/opensearch-project/OpenSearch/pull/15988)
- [16030](https://github.com/opensearch-project/OpenSearch/pull/16030)
- [18254](https://github.com/opensearch-project/OpenSearch/pull/18254)
- [18333](https://github.com/opensearch-project/OpenSearch/pull/18333)
- [18568](https://github.com/opensearch-project/OpenSearch/pull/18568)
- [19007](https://github.com/opensearch-project/OpenSearch/pull/19007)
- [19115](https://github.com/opensearch-project/OpenSearch/pull/19115)
- [19116](https://github.com/opensearch-project/OpenSearch/pull/19116)
- [19181](https://github.com/opensearch-project/OpenSearch/pull/19181)
- [19317](https://github.com/opensearch-project/OpenSearch/pull/19317)
- [19343](https://github.com/opensearch-project/OpenSearch/pull/19343)
- [19344](https://github.com/opensearch-project/OpenSearch/pull/19344)
- [19347](https://github.com/opensearch-project/OpenSearch/pull/19347)
- [19379](https://github.com/opensearch-project/OpenSearch/pull/19379)
- [19392](https://github.com/opensearch-project/OpenSearch/pull/19392)
- [19404](https://github.com/opensearch-project/OpenSearch/pull/19404)
- [19405](https://github.com/opensearch-project/OpenSearch/pull/19405)
- [19429](https://github.com/opensearch-project/OpenSearch/pull/19429)
- [19432](https://github.com/opensearch-project/OpenSearch/pull/19432)
- [19458](https://github.com/opensearch-project/OpenSearch/pull/19458)
- [19484](https://github.com/opensearch-project/OpenSearch/pull/19484)
- [19488](https://github.com/opensearch-project/OpenSearch/pull/19488)
- [19496](https://github.com/opensearch-project/OpenSearch/pull/19496)
- [19520](https://github.com/opensearch-project/OpenSearch/pull/19520)
- [19522](https://github.com/opensearch-project/OpenSearch/pull/19522)
- [19524](https://github.com/opensearch-project/OpenSearch/pull/19524)
- [19668](https://github.com/opensearch-project/OpenSearch/pull/19668)
- [13172](https://github.com/opensearch-project/OpenSearch/pull/13172)
- [13592](https://github.com/opensearch-project/OpenSearch/pull/13592)
- [13788](https://github.com/opensearch-project/OpenSearch/pull/13788)
- [13809](https://github.com/opensearch-project/OpenSearch/pull/13809)
- [13810](https://github.com/opensearch-project/OpenSearch/pull/13810)
- [13829](https://github.com/opensearch-project/OpenSearch/pull/13829)
- [13836](https://github.com/opensearch-project/OpenSearch/pull/13836)
- [13850](https://github.com/opensearch-project/OpenSearch/pull/13850)
- [13865](https://github.com/opensearch-project/OpenSearch/pull/13865)
- [13887](https://github.com/opensearch-project/OpenSearch/pull/13887)
- [13888](https://github.com/opensearch-project/OpenSearch/pull/13888)
- [13909](https://github.com/opensearch-project/OpenSearch/pull/13909)
- [13911](https://github.com/opensearch-project/OpenSearch/pull/13911)
- [13998](https://github.com/opensearch-project/OpenSearch/pull/13998)
- [14106](https://github.com/opensearch-project/OpenSearch/pull/14106)
- [14208](https://github.com/opensearch-project/OpenSearch/pull/14208)
- [14221](https://github.com/opensearch-project/OpenSearch/pull/14221)
- [14230](https://github.com/opensearch-project/OpenSearch/pull/14230)
- [14383](https://github.com/opensearch-project/OpenSearch/pull/14383)
- [14479](https://github.com/opensearch-project/OpenSearch/pull/14479)
- [14641](https://github.com/opensearch-project/OpenSearch/pull/14641)
- [14680](https://github.com/opensearch-project/OpenSearch/pull/14680)
- [14684](https://github.com/opensearch-project/OpenSearch/pull/14684)
- [14785](https://github.com/opensearch-project/OpenSearch/pull/14785)
- [14817](https://github.com/opensearch-project/OpenSearch/pull/14817)
- [14832](https://github.com/opensearch-project/OpenSearch/pull/14832)
- [14912](https://github.com/opensearch-project/OpenSearch/pull/14912)
- [14979](https://github.com/opensearch-project/OpenSearch/pull/14979)
- [14983](https://github.com/opensearch-project/OpenSearch/pull/14983)
- [14991](https://github.com/opensearch-project/OpenSearch/pull/14991)
- [15010](https://github.com/opensearch-project/OpenSearch/pull/15010)
- [15012](https://github.com/opensearch-project/OpenSearch/pull/15012)
- [15017](https://github.com/opensearch-project/OpenSearch/pull/15017)
- [15033](https://github.com/opensearch-project/OpenSearch/pull/15033)
- [15053](https://github.com/opensearch-project/OpenSearch/pull/15053)
- [15072](https://github.com/opensearch-project/OpenSearch/pull/15072)
- [15077](https://github.com/opensearch-project/OpenSearch/pull/15077)
- [15145](https://github.com/opensearch-project/OpenSearch/pull/15145)
- [15160](https://github.com/opensearch-project/OpenSearch/pull/15160)
- [15173](https://github.com/opensearch-project/OpenSearch/pull/15173)
- [15206](https://github.com/opensearch-project/OpenSearch/pull/15206)
- [15207](https://github.com/opensearch-project/OpenSearch/pull/15207)
- [15256](https://github.com/opensearch-project/OpenSearch/pull/15256)
- [15289](https://github.com/opensearch-project/OpenSearch/pull/15289)
- [15333](https://github.com/opensearch-project/OpenSearch/pull/15333)
- [15465](https://github.com/opensearch-project/OpenSearch/pull/15465)
- [15497](https://github.com/opensearch-project/OpenSearch/pull/15497)
- [15514](https://github.com/opensearch-project/OpenSearch/pull/15514)
- [15521](https://github.com/opensearch-project/OpenSearch/pull/15521)
- [15524](https://github.com/opensearch-project/OpenSearch/pull/15524)
- [15557](https://github.com/opensearch-project/OpenSearch/pull/15557)
- [15558](https://github.com/opensearch-project/OpenSearch/pull/15558)
- [15565](https://github.com/opensearch-project/OpenSearch/pull/15565)
- [15568](https://github.com/opensearch-project/OpenSearch/pull/15568)
- [15573](https://github.com/opensearch-project/OpenSearch/pull/15573)
- [15592](https://github.com/opensearch-project/OpenSearch/pull/15592)
- [15627](https://github.com/opensearch-project/OpenSearch/pull/15627)
- [15695](https://github.com/opensearch-project/OpenSearch/pull/15695)
- [15862](https://github.com/opensearch-project/OpenSearch/pull/15862)
- [15916](https://github.com/opensearch-project/OpenSearch/pull/15916)
- [15925](https://github.com/opensearch-project/OpenSearch/pull/15925)
- [15938](https://github.com/opensearch-project/OpenSearch/pull/15938)
- [15946](https://github.com/opensearch-project/OpenSearch/pull/15946)
- [15950](https://github.com/opensearch-project/OpenSearch/pull/15950)
- [15981](https://github.com/opensearch-project/OpenSearch/pull/15981)
- [16047](https://github.com/opensearch-project/OpenSearch/pull/16047)
- [16067](https://github.com/opensearch-project/OpenSearch/pull/16067)
- [16089](https://github.com/opensearch-project/OpenSearch/pull/16089)
- [16103](https://github.com/opensearch-project/OpenSearch/pull/16103)
- [16142](https://github.com/opensearch-project/OpenSearch/pull/16142)
- [16201](https://github.com/opensearch-project/OpenSearch/pull/16201)
- [16273](https://github.com/opensearch-project/OpenSearch/pull/16273)
- [16282](https://github.com/opensearch-project/OpenSearch/pull/16282)
- [16359](https://github.com/opensearch-project/OpenSearch/pull/16359)
- [16384](https://github.com/opensearch-project/OpenSearch/pull/16384)
- [16444](https://github.com/opensearch-project/OpenSearch/pull/16444)
- [16445](https://github.com/opensearch-project/OpenSearch/pull/16445)
- [16488](https://github.com/opensearch-project/OpenSearch/pull/16488)
- [16532](https://github.com/opensearch-project/OpenSearch/pull/16532)
- [16564](https://github.com/opensearch-project/OpenSearch/pull/16564)
- [16573](https://github.com/opensearch-project/OpenSearch/pull/16573)
- [16707](https://github.com/opensearch-project/OpenSearch/pull/16707)
- [16958](https://github.com/opensearch-project/OpenSearch/pull/16958)
- [17055](https://github.com/opensearch-project/OpenSearch/pull/17055)
- [17093](https://github.com/opensearch-project/OpenSearch/pull/17093)
- [17286](https://github.com/opensearch-project/OpenSearch/pull/17286)
- [17299](https://github.com/opensearch-project/OpenSearch/pull/17299)
- [17342](https://github.com/opensearch-project/OpenSearch/pull/17342)
- [17400](https://github.com/opensearch-project/OpenSearch/pull/17400)
- [17447](https://github.com/opensearch-project/OpenSearch/pull/17447)
- [17507](https://github.com/opensearch-project/OpenSearch/pull/17507)
- [17562](https://github.com/opensearch-project/OpenSearch/pull/17562)
- [17674](https://github.com/opensearch-project/OpenSearch/pull/17674)
- [17760](https://github.com/opensearch-project/OpenSearch/pull/17760)
- [17796](https://github.com/opensearch-project/OpenSearch/pull/17796)
- [17797](https://github.com/opensearch-project/OpenSearch/pull/17797)
- [17817](https://github.com/opensearch-project/OpenSearch/pull/17817)
- [17927](https://github.com/opensearch-project/OpenSearch/pull/17927)
- [17935](https://github.com/opensearch-project/OpenSearch/pull/17935)
- [17941](https://github.com/opensearch-project/OpenSearch/pull/17941)
- [17961](https://github.com/opensearch-project/OpenSearch/pull/17961)
- [18074](https://github.com/opensearch-project/OpenSearch/pull/18074)
- [18102](https://github.com/opensearch-project/OpenSearch/pull/18102)
- [18103](https://github.com/opensearch-project/OpenSearch/pull/18103)
- [18106](https://github.com/opensearch-project/OpenSearch/pull/18106)
- [18184](https://github.com/opensearch-project/OpenSearch/pull/18184)
- [18193](https://github.com/opensearch-project/OpenSearch/pull/18193)
- [18195](https://github.com/opensearch-project/OpenSearch/pull/18195)
- [18215](https://github.com/opensearch-project/OpenSearch/pull/18215)
- [18229](https://github.com/opensearch-project/OpenSearch/pull/18229)
- [18249](https://github.com/opensearch-project/OpenSearch/pull/18249)
- [18255](https://github.com/opensearch-project/OpenSearch/pull/18255)
- [18257](https://github.com/opensearch-project/OpenSearch/pull/18257)
- [18268](https://github.com/opensearch-project/OpenSearch/pull/18268)
- [18277](https://github.com/opensearch-project/OpenSearch/pull/18277)
- [18300](https://github.com/opensearch-project/OpenSearch/pull/18300)
- [18351](https://github.com/opensearch-project/OpenSearch/pull/18351)
- [18375](https://github.com/opensearch-project/OpenSearch/pull/18375)
- [18408](https://github.com/opensearch-project/OpenSearch/pull/18408)
- [18424](https://github.com/opensearch-project/OpenSearch/pull/18424)
- [18435](https://github.com/opensearch-project/OpenSearch/pull/18435)
- [18469](https://github.com/opensearch-project/OpenSearch/pull/18469)
- [18479](https://github.com/opensearch-project/OpenSearch/pull/18479)
- [18498](https://github.com/opensearch-project/OpenSearch/pull/18498)
- [18518](https://github.com/opensearch-project/OpenSearch/pull/18518)
- [18536](https://github.com/opensearch-project/OpenSearch/pull/18536)
- [18540](https://github.com/opensearch-project/OpenSearch/pull/18540)
- [18573](https://github.com/opensearch-project/OpenSearch/pull/18573)
- [18583](https://github.com/opensearch-project/OpenSearch/pull/18583)
- [18621](https://github.com/opensearch-project/OpenSearch/pull/18621)
- [18661](https://github.com/opensearch-project/OpenSearch/pull/18661)
- [18680](https://github.com/opensearch-project/OpenSearch/pull/18680)
- [18698](https://github.com/opensearch-project/OpenSearch/pull/18698)
- [18715](https://github.com/opensearch-project/OpenSearch/pull/18715)
- [18720](https://github.com/opensearch-project/OpenSearch/pull/18720)
- [18735](https://github.com/opensearch-project/OpenSearch/pull/18735)
- [18748](https://github.com/opensearch-project/OpenSearch/pull/18748)
- [18749](https://github.com/opensearch-project/OpenSearch/pull/18749)
- [18773](https://github.com/opensearch-project/OpenSearch/pull/18773)
- [18777](https://github.com/opensearch-project/OpenSearch/pull/18777)
- [18883](https://github.com/opensearch-project/OpenSearch/pull/18883)
- [18889](https://github.com/opensearch-project/OpenSearch/pull/18889)
- [18891](https://github.com/opensearch-project/OpenSearch/pull/18891)
- [18929](https://github.com/opensearch-project/OpenSearch/pull/18929)
- [18951](https://github.com/opensearch-project/OpenSearch/pull/18951)
- [19005](https://github.com/opensearch-project/OpenSearch/pull/19005)
- [19008](https://github.com/opensearch-project/OpenSearch/pull/19008)
- [19012](https://github.com/opensearch-project/OpenSearch/pull/19012)
- [19130](https://github.com/opensearch-project/OpenSearch/pull/19130)
- [19164](https://github.com/opensearch-project/OpenSearch/pull/19164)
- [19174](https://github.com/opensearch-project/OpenSearch/pull/19174)
- [19220](https://github.com/opensearch-project/OpenSearch/pull/19220)
- [19226](https://github.com/opensearch-project/OpenSearch/pull/19226)
- [19230](https://github.com/opensearch-project/OpenSearch/pull/19230)
- [19245](https://github.com/opensearch-project/OpenSearch/pull/19245)
- [19248](https://github.com/opensearch-project/OpenSearch/pull/19248)
- [19280](https://github.com/opensearch-project/OpenSearch/pull/19280)
- [19304](https://github.com/opensearch-project/OpenSearch/pull/19304)
- [19306](https://github.com/opensearch-project/OpenSearch/pull/19306)
- [19307](https://github.com/opensearch-project/OpenSearch/pull/19307)
- [19309](https://github.com/opensearch-project/OpenSearch/pull/19309)
- [19313](https://github.com/opensearch-project/OpenSearch/pull/19313)
- [19321](https://github.com/opensearch-project/OpenSearch/pull/19321)
- [19331](https://github.com/opensearch-project/OpenSearch/pull/19331)
- [19357](https://github.com/opensearch-project/OpenSearch/pull/19357)
- [19371](https://github.com/opensearch-project/OpenSearch/pull/19371)
- [19377](https://github.com/opensearch-project/OpenSearch/pull/19377)
- [19385](https://github.com/opensearch-project/OpenSearch/pull/19385)
- [19391](https://github.com/opensearch-project/OpenSearch/pull/19391)
- [19397](https://github.com/opensearch-project/OpenSearch/pull/19397)
- [19428](https://github.com/opensearch-project/OpenSearch/pull/19428)
- [19437](https://github.com/opensearch-project/OpenSearch/pull/19437)
- [19462](https://github.com/opensearch-project/OpenSearch/pull/19462)
- [19486](https://github.com/opensearch-project/OpenSearch/pull/19486)
- [19491](https://github.com/opensearch-project/OpenSearch/pull/19491)
- [19493](https://github.com/opensearch-project/OpenSearch/pull/19493)
- [19499](https://github.com/opensearch-project/OpenSearch/pull/19499)
- [19510](https://github.com/opensearch-project/OpenSearch/pull/19510)
- [19513](https://github.com/opensearch-project/OpenSearch/pull/19513)
- [19533](https://github.com/opensearch-project/OpenSearch/pull/19533)
- [19541](https://github.com/opensearch-project/OpenSearch/pull/19541)
- [19546](https://github.com/opensearch-project/OpenSearch/pull/19546)
- [19551](https://github.com/opensearch-project/OpenSearch/pull/19551)
- [19553](https://github.com/opensearch-project/OpenSearch/pull/19553)
- [19576](https://github.com/opensearch-project/OpenSearch/pull/19576)
- [19593](https://github.com/opensearch-project/OpenSearch/pull/19593)
- [19709](https://github.com/opensearch-project/OpenSearch/pull/19709)
- [19732](https://github.com/opensearch-project/OpenSearch/pull/19732)
- [19789](https://github.com/opensearch-project/OpenSearch/pull/19789)
- [19821](https://github.com/opensearch-project/OpenSearch/pull/19821)
- [19833](https://github.com/opensearch-project/OpenSearch/pull/19833)
- [19976](https://github.com/opensearch-project/OpenSearch/pull/19976)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by andrross**
One test method had a race condition when getting an index after closing. This change extracts the common pattern of polling until the index is available and uses it everywhere.

Fixes #14407

### Check List
- [x] Functionality includes testing.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/index/IndexServiceTests.java [hunk 1]
```diff
@@ -886,6 +877,9 @@ public void testRefreshTaskUpdatesWithDynamicShardLevelRefreshes() throws Except
 
         // OS test case fails if test leaves behind transient cluster setting so need to clear it.
         client().admin().cluster().prepareUpdateSettings().setTransientSettings(Settings.builder().putNull("*")).get();
+    }
 
+    private IndexService getIndexService(Index index) {
+        return await().until(() -> getInstanceFromNode(IndicesService.class).indexService(index), notNullValue());
```
Comment (reta) [inline server/src/test/java/org/opensearch/index/IndexServiceTests.java]: May be bound it by (reasonable) time, fe 10 seconds? 

```suggestion
        return await().atMost(10, TimeUnit.SECONDS).until(() -> getInstanceFromNode(IndicesService.class).indexService(index), notNullValue());
```

**Review by prudhvigodithi — APPROVED** [review]
