### PR TITLE
Remove unnecessary refresh listeners from NRTReplicationReaderManager.

### LINKED ISSUE #8858: [BUG] Test SegmentReplicationRelocationIT.testPrimaryRelocation is flaky.
https://github.com/opensearch-project/OpenSearch/pull/8827#issuecomment-1646515038

This test is failing due to a deadlock situation introduced with [this](https://github.com/opensearch-project/OpenSearch/commit/7642e435eecd9d5e390dc7906bff38ae2483c304) PR because of the introduced blocking refresh.  This is because [this](https://github.com/opensearch-project/OpenSearch/blob/e3542011cd9584c354405ba6cbf9a31ced7bc5ce/server/src/main/java/org/opensearch/index/store/Store.java#L857) method is holding the metadataLock on the store while invoking `                consumer.accept(buildSegmentInfos(infosBytes, segmentsGen));
` which loads the newly built SegmentInfos onto the DirectoryReader and invokes maybeRefreshBlocking.  If a concurrent scheduled refresh is invoked before updateSegments is able to aquire the refresh lock, it will block until the scheduled refresh completes, however if the scheduled refresh swaps the SegmentInfos reference it will decRef the previous DirectoryReader that in turn tries to blockingly acquire the metadataLock.

### PR DESCRIPTION
**Pull request by mch2**
### Description
This change removes RefreshListeners used by IndexShard & InternalEngine to provide waitFor functionality from NRT replicas. These listeners were previously registered onto NRT replicas only to be force released on the next scheduled refresh cycle without actually refreshing the reader.

This change also removes the unnecessary blocking refresh from NRTReaderManager because we no longer have conflicting refresh invocations from scheduledRefresh, resolving the deadlock in #8858.

Added test to ensure refreshListeners are not registered.  This is also covered by existing tests testDropPrimaryDuringReplication and testPrimaryRelocation.

### Related Issues
Resolves #8858
related https://github.com/opensearch-project/OpenSearch/pull/8859

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mch2** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** UNSTABLE ❕
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.indices.replication.SegmentReplicationRelocationIT.testPrimaryRelocation
> ```
> 
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/20866/
> * **CommitID:** [320723a](https://github.com/opensearch-project/OpenSearch/commit/320723adf455f50465f6724c0afa2a8d19df6efb)
>   Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

This test is failing with a timeout over 1m for relocation to execute.  I've made a change to reduce the amount of docs ingested with testPrimaryRelocation and testPrimaryRelocationWithSegRepFailure.
    
These tests were ingesting 100-1k docs and randomly selecting a refresh policy. With the IMMEDIATE refresh policy a blocking refresh is performed that acquires a primary operation permit and increases the time required for the primary to block operations for relocation.  On my machine this change reduces the test time with max docs from 1m to 5-6s.

File: server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java [hunk 1]
```diff
@@ -322,22 +323,12 @@ public List<Segment> segments(boolean verbose) {
 
     @Override
     public void refresh(String source) throws EngineException {
-        maybeRefresh(source);
+        // Refresh on this engine should only ever happen in the reader after new segments arrive.
     }
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java:327]: Should we throw an `UnsupportedOperationException` instead to detect any hidden invocation?

Comment (mch2) [reply server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java:327]: Will give this a try and run tests to see where it breaks.  I'm a bit worried we'll have to add too much conditional logic where refresh is invoked from IndexShard & api, but it may not be too bad...

Comment (mch2) [reply server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java:327]: @Bukhtawar Took a look at this, I would prefer we not have implementation specific logic in the shard and leave as a NoOp in the Engine implementation.  There are 6 invocations of the blocking refresh on the abstract Engine from IndexShard.  All of these methods are still invoked on the shard so we would need conditional logic to skip the call or significant refactoring at a higher level.

- Direct refresh - API - req still routed to replica.
- acquireLastIndexCommitAndRefresh - not invoked with nrt replicas
- postRecovery - still invoked through multiple recovery paths
- finalizeRecovery  - still invoked through multiple recovery paths
- resetEngineToGLobalCheckpoint - used to reset engine after failover/relocation.

**Comment by mch2** [comment]
> https://github.com/opensearch-project/OpenSearch/issues/7556

**Review by kotwanikunal — APPROVED** [review]

**Review by Poojita-Raj — APPROVED** [review]
