### PR TITLE
Fix getTime field name to time in GetStats (#16894)

### LINKED ISSUE #16894: [BUG] GetStats class serializes the `time` field as `getTime` in XContent/JSON
### Describe the bug

The [`GetStats` class](https://github.com/opensearch-project/OpenSearch/blob/2.x/server/src/main/java/org/opensearch/index/get/GetStats.java#L158) serializes what should be the `time` field as `getTime` instead.

This issue was introduced in a refactoring from nearly twelve years ago (ie. very pre-fork) where a find & replace appears to have gone awry: https://github.com/opensearch-project/OpenSearch/commit/cc83c2f848be69a77f1275fe1ff5363dcdd4c955#diff-f7abcc8f5eb3ec75bb9be11b7fe88baa0bcedf62c3c481552a0e98ceb7125a27R124

This means that when getting stats for an index, the "human" variant of `time_in_millis` becomes `getTime` rather than just `time` as expected.

### Related component

Other

### To Reproduce

1. Create an empty index: `PUT /movies`
2. Get stats for the index enabling the "human" fields: `GET /movies/_stats?human&filter_path=_all.primaries.get`
3. See response:
```
{
  "_all": {
    "primaries": {
      "get": {
        "total": 0,
        "getTime": "0s",
        "time_in_millis": 0,
        "exists_total": 0,
        "exists_time": "0s",
        "exists_time_in_millis": 0,
        "missing_total": 0,
        "missing_time": "0s",
        "missing_time_in_millis": 0,
        "current": 0
      }
    }
  }
}
```

### Expected behavior

The `getTime` field should be named simply `time` to align with all other "human" `_in_millis` pairings.

### Additional Details

**Screenshots**
Screenshot 2024-12-23 at 12 52 18 PM

### PR DESCRIPTION
**Pull request by hye-on**
### Description
Updated GetStats to deprecate the getTime field and introduce a new time field.

### Related Issues
Resolves #16894

### Comments
Since the API schema has been updated, I’ve prepared this PR to reflect the changes. [#785](https://github.com/opensearch-project/opensearch-api-specification/pull/785)
Being new to open source, I’m open to any suggestions or feedback. I appreciate your guidance and support! 

### Check List
- [x] Functionality includes testing.
  - Tested via curl commands:
    1. `curl -X PUT "localhost:9200/movies"`
    2. `curl "localhost:9200/movies/_stats?human&filter_path=_all.primaries.get`

image (1)

- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.   🌟 [#785](https://github.com/opensearch-project/opensearch-api-specification/pull/785)
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/get/GetStats.java [hunk 1]
```diff
@@ -155,7 +155,7 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
     static final class Fields {
         static final String GET = "get";
         static final String TOTAL = "total";
-        static final String TIME = "getTime";
+        static final String TIME = "time";
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/get/GetStats.java:158]: @hye-on thanks for this fix, since this is API change, changing the field name is a breaking change. We may need to expose this field as `getTime` (deprecated) and `time` (new one) for the time being.

Comment (hye-on) [reply server/src/main/java/org/opensearch/index/get/GetStats.java:158]: @reta Thanks for the comment. I'll keep getTime as is and add time :)

File: server/src/main/java/org/opensearch/index/get/GetStats.java [hunk 2]
```diff
@@ -155,6 +156,11 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
     static final class Fields {
         static final String GET = "get";
         static final String TOTAL = "total";
+        /**
+         * Deprecated field name for time. Use {@link #TIME} instead.
+         */
+        @Deprecated
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/get/GetStats.java:162]:
```suggestion
        @Deprecated(forRemoval = true)
```

File: server/src/main/java/org/opensearch/index/get/GetStats.java [hunk 3]
```diff
@@ -137,6 +137,7 @@ public long current() {
     public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
         builder.startObject(Fields.GET);
         builder.field(Fields.TOTAL, getCount());
+        builder.humanReadableField(Fields.TIME_IN_MILLIS, Fields.GET_TIME, getTime());
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/get/GetStats.java:140]: 👍

**Comment by reta** [comment]
Last thing, could you please add a test case for it (see please https://github.com/opensearch-project/OpenSearch/tree/main/rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats for existing tests), happy to help if you find it difficult. Thank you.

**Comment by hye-on** [comment]
@reta Thank you for letting me know and offering your help! I’ll work on adding the test case and reach out if I run into any issues. I really appreciate your support. :)

**Comment by hye-on** [comment]
@reta Thank you for your patience! I’ve added tests and updated the method handling the getTime field to address the `time_in_millis` duplication issue. Let me know if there’s anything else I should adjust :)

**Comment by reta** [comment]
Thank you @hye-on , the build fails with:

```
* What went wrong:
Execution failed for task ':server:spotlessJavaCheck'.
> The following files had format violations:
      src/main/java/org/opensearch/index/get/GetStats.java
          @@ -138,7 +138,7 @@
           ····public·XContentBuilder·toXContent(XContentBuilder·builder,·Params·params)·throws·IOException·{
           ········builder.startObject(Fields.GET);
           ········builder.field(Fields.TOTAL,·getCount());
          -········builder.field(·Fields.GET_TIME,·Objects.toString(getTime()));
          +········builder.field(Fields.GET_TIME,·Objects.toString(getTime()));
           ········builder.humanReadableField(Fields.TIME_IN_MILLIS,·Fields.TIME,·getTime());
           ········builder.field(Fields.EXISTS_TOTAL,·existsCount);
           ········builder.humanReadableField(Fields.EXISTS_TIME_IN_MILLIS,·Fields.EXISTS_TIME,·getExistsTime());
  Run './gradlew :server:spotlessApply' to fix these violations.
```

**Comment by hye-on** [comment]
> Thank you @hye-on , the build fails with:
> 

Apologies I missed that and thanks for pointing that out! [40ac728](https://github.com/opensearch-project/OpenSearch/pull/17009/commits/40ac7289acd4b09614ed92e291dfc75f1f29746b)

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/60_time_fields.yml.yml
Comment (reta) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/60_time_fields.yml.yml:1]: Seems like file name is a bit messed up: 60_time_fields.yml

Comment (hye-on) [reply rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/60_time_fields.yml.yml:1]: @reta 
How about these options?

- 60_stats_time_field_migration.yml
- 60_stats_time_fields.yml
- 60_stats_time.yml

Thank you for your continued review :)

Comment (hye-on) [reply rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/60_time_fields.yml.yml:1]: Thank you! I've renamed it to `60_include_both_time_and_gettime_in_stats.yml`

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/60_include_both_time_and_gettime_in_stats.yml [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+        id: 1
+        body: { "foo": "bar" }
+
+  - do:
+      indices.refresh:
+        index: test1
+
+---
+"Test _stats API includes both time and getTime metrics with human filter":
+  - do:
```
Comment (reta) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/60_include_both_time_and_gettime_in_stats.yml:24]: @hye-on this is great, there are some tests failing, we need to add this section (just before `do` section) to exclude older OS versions (where this change is not present):

```
  - skip:
      version:  " - 2.19.99"
      reason:   "this change is added in 3.0.0"
```

File: server/src/main/java/org/opensearch/index/get/GetStats.java [hunk 5]
```diff
@@ -137,6 +138,7 @@ public long current() {
     public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
         builder.startObject(Fields.GET);
         builder.field(Fields.TOTAL, getCount());
+        builder.field(Fields.GET_TIME, Objects.toString(getTime()));
```
Comment (reta) [inline server/src/main/java/org/opensearch/index/get/GetStats.java:141]: @hye-on I am very sorry, missed that, I think we should use `humanReadableField` here, the same way the `Fields.TIME` was serialized before (no need to use `Objects.toString`):

```suggestion
        builder.humanReadableField(Fields.TIME_IN_MILLIS, Fields.GET_TIME, getTime());
```

Comment (hye-on) [reply server/src/main/java/org/opensearch/index/get/GetStats.java:141]: @reta 
Initially, I tried using `humanReadableField`, but this method added both the first and second arguments, causing a duplicate error with `TIME_IN_MILLIS`.
To include only `getTime`, I checked the implementation of humanReadableField and found that it uses `Objects.toString(value)` for serialization.
For reference, calling `toString `on a `TimeValue` includes units like `s`or `ms`. 

#### Error details:
java.lang.RuntimeException: Failure at [indices.stats/60_time_fields.yml:11]: Duplicate field 'time_in_millis' at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 150].

#### humanReadableField
```java
public XContentBuilder humanReadableField(String rawFieldName, String readableFieldName, Object value) throws IOException {
    assert rawFieldName.equals(readableFieldName) == false : "expected raw and readable field names to differ, but they were both: "
        + rawFieldName;
    if (humanReadable) {
        field(readableFieldName, Objects.toString(value)); // Adds the human-readable field using Objects.toString(value)
    }
    HumanReadableTransformer transformer = HUMAN_READABLE_TRANSFORMERS.get(value.getClass());
    if (transformer != null) {
        Object rawValue = transformer.rawValue(value);
        field(rawFieldName, rawValue); // Adds the raw field transformed 
    } else {
        throw new IllegalArgumentException("no raw transformer found for class " + value.getClass());
    }
    return this;
}

```

**Comment by hye-on** [comment]
@reta 
Sorry, I've removed the unnecessary changelog entries. Please check it again. Thank you!
[2754fcb](https://github.com/opensearch-project/OpenSearch/pull/17009/commits/2754fcb3c6063bda5ac6090aa7754b59dc4054b8)

File: server/src/main/java/org/opensearch/index/get/GetStats.java (hunk 5 above)
Comment (reta) [reply server/src/main/java/org/opensearch/index/get/GetStats.java:141]: Ah, you are totally right, thank you

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Thanks a lot @hye-on !
