### PR TITLE
Fix client-rest-high-level tests for ppc64le

### LINKED ISSUE #12313: Fixing client:rest-high-level tests for ppc64le.
### Describe the bug

Hi Team, I am working on validating Opensearch v2.11.1 on ppc64le, while running the testsuite the tests `client:rest-high-level:integTest`  and `client:rest-high-level:asyncIntegTest` were failing due to the floating point difference between x86 and ppc64le. I had to make the following change fo get the tests passing.

```
diff --git a/client/rest-high-level/src/test/java/org/opensearch/client/RankEvalIT.java b/client/rest-high-level/src/test/java/org/opensearch/client/RankEvalIT.java
index 47add92ecac..ad274f24fb9 100644
--- a/client/rest-high-level/src/test/java/org/opensearch/client/RankEvalIT.java
+++ b/client/rest-high-level/src/test/java/org/opensearch/client/RankEvalIT.java
@@ -151,7 +151,7 @@ public class RankEvalIT extends OpenSearchRestHighLevelClientTestCase {
             DiscountedCumulativeGain::new,
             () -> new ExpectedReciprocalRank(1)
         );
-        double expectedScores[] = new double[] { 0.4285714285714286, 1.0, 0.75, 1.6408962261063627, 0.4407738095238095 };
+        double expectedScores[] = new double[] { 0.4285714285714286, 1.0, 0.75, 1.6408962261063629, 0.4407738095238095 };
         int i = 0;
```

### Related component

Other

### To Reproduce

1. Build following instructions from https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md
2. Execute test suite using ./gradlew check
3. See error

### Expected behavior

Tests should pass.

### Additional Details

**Host/Environment (please complete the following information):**
 - OS: Ubuntu
 - Version : 20.04.6

ppc64le specific code is needed to be added here to pass this test. Please let me know how to proceed further on this. Thank you.

### PR DESCRIPTION
**Pull request by prachi-gaonkar**
### Description
Continuing from PR #12860 . Fixes tests for ppc64le mentioned in #12313

### Related Issues
Resolves #12313 

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: client/rest-high-level/src/test/java/org/opensearch/client/RankEvalIT.java [hunk 1]
```diff
@@ -158,7 +158,8 @@ public void testMetrics() throws IOException {
 
             RankEvalRequest rankEvalRequest = new RankEvalRequest(spec, new String[] { "index", "index2" });
             RankEvalResponse response = execute(rankEvalRequest, highLevelClient()::rankEval, highLevelClient()::rankEvalAsync);
-            assertEquals(expectedScores[i], response.getMetricScore(), Double.MIN_VALUE);
+            double delta = 0.0001; // Set a practical
```
Comment (reta) [inline client/rest-high-level/src/test/java/org/opensearch/client/RankEvalIT.java:161]: Could you please introduce constant to `OpenSearchRestHighLevelClientTestCase`, fe

```
static final double DOUBLE_DELTA = 0.000001;
```

and use it here? I suspect we may run into other cases

**Comment by reta** [comment]
@prachi-gaonkar apologies, you may need to rebase against latest `main` to have green checks, thank you

**Review by reta — APPROVED** [review]
