### PR TITLE
Optimization in Numeric Terms Aggregation query for Large Bucket Counts

### LINKED ISSUE #18703: [Performance] Optimize num agg using quick select for topN
### Describe the bug

Problem: If the number of requested top-N buckets (N) often exceeded or was close to the maximum bucket ordinal, making the use of a PriorityQueue for top-N selection inefficient or redundant.

Solution: Introduced conditional logic to optimize bucket selection:
    * If N > max bucket ordinal: No-op (return all buckets).
    * If N < max bucket ordinal but N is bellow 10% of max bucket ordinal: Use quickselect for top-N.
    * Otherwise: Use PriorityQueue for top-N.

### Related component

Search:Performance

### Additional Details

**Plugins**
NA

**Screenshots**
NA

**Host/Environment (please complete the following information):**
 -  Tests using r5.xl host with EBS Gp3 16000 IOPS, 500Gb and 1000 throughput.

**Additional context**

### PR DESCRIPTION
**Pull request by vinaykpud**
### Description
In bucket aggregations, data node sends topN bucket requested to the coordinator. The contract here is to return the buckets sorted by key but topN on the basis of value. 
If the number of requested top-N buckets exceeds or close to the maximum bucket ordinal, making the use of a PriorityQueue for top-N selection inefficient or redundant. So we made following modifications:

1. use `quickselect` for topN if the requested size is greater than the 20% of the total buckets.
2. If the requested size is greater than the bucket size then return all the bucket.

### Benchmarking test results :
 https://github.com/opensearch-project/OpenSearch/issues/18703#issuecomment-3075221182

### Related Issues
Resolves #18703
Related #18650

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by vinaykpud** [comment]
### Performance Analysis to choose the decision Logic

This PR implements a dynamic algorithm selection strategy for retrieving topN items based on request size relative to bucket size. The algorithm selection is based on performance characteristics where Priority Queue performs better for smaller datasets, while Quick Select is more efficient for larger datasets.

Decision Logic
```
if (request size < 20% of bucketSize) {
    // use Priority Queue
} else {
    // use Quick Select
}
```

I conducted latency testing using the following parameters:

### Test Setup
- **Index Size**: 102,000 documents
- **Test Field**: Custom field with 100,000 unique values  
- **Bucket Size**: 100,000
-  `shard_size` is calculated like this : `shard_size = size × 1.5 + 10`

*Note: The shard_size is used for decision logic in each shard*

### Test Results

#### Test 1: 10% Bucket Size Threshold
- size: 6,670
- shard_size: 10,015 (6,670 × 1.5 + 10)
- **Percentage**: 10% of bucket size
- **Result**: Higher latency with algorithm change

#### Test 2: 15% Bucket Size Threshold  
- size: 10,000
- shard_size: 15,010 (10,000 × 1.5 + 10)
- **Percentage**: 15% of bucket size
- **Result**: Higher latency with algorithm change

#### Test 3: 20% Bucket Size Threshold
- size: 13,400
- shard_size: 20,110 (13,400 × 1.5 + 10)
- **Percentage**: 20% of bucket size  
- **Result**: Lower latency with algorithm change

### Conclusion

Based on the performance testing results, **20% of bucket size** was identified as the optimal threshold where the algorithm change provides latency improvements. This threshold serves as the breakpoint for algorithm selection between Priority Queue and Quick Select.

**Comment by vinaykpud** [comment]
adding @rishabhmaurya @getsaurabh02

File: server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java [hunk 1]
```diff
@@ -38,6 +38,7 @@ protected FeatureFlagSettings(
         FeatureFlags.APPLICATION_BASED_CONFIGURATION_TEMPLATES_SETTING,
         FeatureFlags.TERM_VERSION_PRECOMMIT_ENABLE_SETTING,
         FeatureFlags.ARROW_STREAMS_SETTING,
-        FeatureFlags.MERGED_SEGMENT_WARMER_EXPERIMENTAL_SETTING
+        FeatureFlags.MERGED_SEGMENT_WARMER_EXPERIMENTAL_SETTING,
+        FeatureFlags.TERMS_AGGREGATION_OPTIMIZATION_ENABLE_SETTING
```
Comment (rishabhmaurya) [inline server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java]: This is not a feature hence should not be a feature flag, please remove it

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregator.java [hunk 2]
```diff
@@ -255,40 +261,84 @@ private InternalAggregation[] buildAggregations(long[] owningBucketOrds) throws
...
-                    long docCount = bucketDocCount(ordsEnum.ord());
-                    otherDocCounts[ordIdx] += docCount;
-                    if (docCount < localBucketCountThresholds.getMinDocCount()) {
-                        continue;
+
+                // When request size is smaller than 20% of total buckets, use priority queue to get topN buckets
+                // When request size is smaller than 20% of total buckets, use priority queue to get topN buckets
+                // partiallyBuiltBucketComparator is null for significantTerm Aggregations use case and the way buckets sorted in the
+                // priority queue is based on the significanceScore
+                if (!FeatureFlags.isEnabled(FeatureFlags.TERMS_AGGREGATION_OPTIMIZATION_ENABLE_SETTING)
```
Comment (rishabhmaurya) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregator.java]: I think this logic needs refactoring, we need to create Enum for all strategies and provide it relevant input. It should contain logic both determine the strategy and also execute it. 
I'm thinking something like (generated with the help of AI)
```java
/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

package org.opensearch.search.aggregations.bucket.terms;

import org.apache.lucene.util.ArrayUtil;
import org.apache.lucene.util.PriorityQueue;
import org.opensearch.common.util.FeatureFlags;
import org.opensearch.search.aggregations.InternalMultiBucketAggregation;
import org.opensearch.search.aggregations.BucketOrder;
import org.opensearch.search.aggregations.InternalOrder;
import org.opensearch.search.aggregations.bucket.LocalBucketCountThresholds;
import org.opensearch.search.aggregations.bucket.terms.LongKeyedBucketOrds.BucketOrdsEnum;

import java.io.IOException;
import java.util.Arrays;
import java.util.Iterator;
import java.util.function.Supplier;

import static org.opensearch.search.aggregations.InternalOrder.isKeyOrder;

/**
 * Enum defining different strategies for selecting top buckets from aggregation results.
 */
public enum ResultSelectionStrategy {
    
    PRIORITY_QUEUE("priority_queue") {
        @Override
        public <B extends InternalMultiBucketAggregation.InternalBucket> SelectionResult<B> selectTopBuckets(
            SelectionInput<B> input
        ) throws IOException {
            PriorityQueue<B> ordered = input.buildPriorityQueue.buildPriorityQueue();
            B spare = null;
            long otherDocCount = 0;
            
            while (input.ordsEnum.next()) {
                long docCount = input.bucketDocCount.bucketDocCount(input.ordsEnum.ord());
                otherDocCount += docCount;
                if (docCount < input.localBucketCountThresholds.getMinDocCount()) {
                    continue;
                }
                if (spare == null) {
                    spare = input.emptyBucketBuilder.get();
                }
                input.updateBucket.updateBucket(spare, input.ordsEnum, docCount);
                spare = ordered.insertWithOverflow(spare);
            }
            
            B[] topBuckets = input.buildBuckets.buildBuckets(ordered.size());
            if (isKeyOrder(input.order)) {
                for (int b = ordered.size() - 1; b >= 0; --b) {
                    topBuckets[b] = ordered.pop();
                    otherDocCount -= topBuckets[b].getDocCount();
                }
            } else {
                Iterator<B> itr = ordered.iterator();
                for (int b = ordered.size() - 1; b >= 0; --b) {
                    topBuckets[b] = itr.next();
                    otherDocCount -= topBuckets[b].getDocCount();
                }
            }
            
            return new SelectionResult<>(topBuckets, otherDocCount);
        }
    },
    
    QUICK_SELECT("quick_select") {
        @Override
        public <B extends InternalMultiBucketAggregation.InternalBucket> SelectionResult<B> selectTopBuckets(
            SelectionInput<B> input
        ) throws IOException {
            B[] bucketsForOrd = input.buildBuckets.buildBuckets((int) input.bucketsInOrd);
            int validBucketCount = 0;
            long otherDocCount = 0;
            B spare = null;
            
            while (input.ordsEnum.next()) {
                long docCount = input.bucketDocCount.bucketDocCount(input.ordsEnum.ord());
                otherDocCount += docCount;
                if (docCount < input.localBucketCountThresholds.getMinDocCount()) {
                    continue;
                }
                spare = input.emptyBucketBuilder.get();
                input.updateBucket.updateBucket(spare, input.ordsEnum, docCount);
                bucketsForOrd[validBucketCount++] = spare;
            }
            
            B[] topBuckets;
            if (validBucketCount > input.size) {
                ArrayUtil.select(
                    bucketsForOrd,
                    0,
                    validBucketCount,
                    input.size,
                    (b1, b2) -> input.partiallyBuiltBucketComparator.compare((InternalTerms.Bucket<?>) b1, (InternalTerms.Bucket<?>) b2)
                );
                topBuckets = Arrays.copyOf(bucketsForOrd, input.size);
                for (int b = 0; b < input.size; b++) {
                    otherDocCount -= topBuckets[b].getDocCount();
                }
            } else {
                topBuckets = Arrays.copyOf(bucketsForOrd, validBucketCount);
                otherDocCount = 0L;
            }
            
            return new SelectionResult<>(topBuckets, otherDocCount);
        }
    };
    
    private final String name;
    
    ResultSelectionStrategy(String name) {
        this.name = name;
    }
    
    public String getName() {
        return name;
    }
    
    /**
     * Determines which strategy to use based on the given parameters.
     */
    public static ResultSelectionStrategy determineStrategy(
        int size,
        long bucketsInOrd,
        BucketOrder order,
        boolean hasPartiallyBuiltBucketComparator
    ) {
        if (!FeatureFlags.isEnabled(FeatureFlags.TERMS_AGGREGATION_OPTIMIZATION_ENABLE_SETTING)
            || (size < 0.2 * bucketsInOrd)
            || isKeyOrder(order)
            || !hasPartiallyBuiltBucketComparator) {
            return PRIORITY_QUEUE;
        }
        return QUICK_SELECT;
    }
    
    /**
     * Selects the top buckets based on the strategy implementation.
     */
    public abstract <B extends InternalMultiBucketAggregation.InternalBucket> SelectionResult<B> selectTopBuckets(
        SelectionInput<B> input
    ) throws IOException;
    
    /**
     * Input parameters for bucket selection.
     */
    public static class SelectionInput<B extends InternalMultiBucketAggregation.InternalBucket> {
        public final BucketOrdsEnum ordsEnum;
        public final LocalBucketCountThresholds localBucketCountThresholds;
        public final int size;
        public final long bucketsInOrd;
        public final BucketOrder order;
        public final Supplier<B> emptyBucketBuilder;
        public final java.util.Comparator<InternalTerms.Bucket<?>> partiallyBuiltBucketComparator;
        public final BucketDocCountFunction bucketDocCount;
        public final BucketUpdateFunction<B> updateBucket;
        public final BucketArrayBuilder<B> buildBuckets;
        public final PriorityQueueBuilder<B> buildPriorityQueue;
        
        public SelectionInput(
            BucketOrdsEnum ordsEnum,
            LocalBucketCountThresholds localBucketCountThresholds,
            int size,
            long bucketsInOrd,
            BucketOrder order,
            Supplier<B> emptyBucketBuilder,
            java.util.Comparator<InternalTerms.Bucket<?>> partiallyBuiltBucketComparator,
            BucketDocCountFunction bucketDocCount,
            BucketUpdateFunction<B> updateBucket,
            BucketArrayBuilder<B> buildBuckets,
            PriorityQueueBuilder<B> buildPriorityQueue
        ) {
            this.ordsEnum = ordsEnum;
            this.localBucketCountThresholds = localBucketCountThresholds;
            this.size = size;
            this.bucketsInOrd = bucketsInOrd;
            this.order = order;
            this.emptyBucketBuilder = emptyBucketBuilder;
            this.partiallyBuiltBucketComparator = partiallyBuiltBucketComparator;
            this.bucketDocCount = bucketDocCount;
            this.updateBucket = updateBucket;
            this.buildBuckets = buildBuckets;
            this.buildPriorityQueue = buildPriorityQueue;
        }
    }
    
    /**
     * Result of bucket selection.
     */
    public static class SelectionResult<B extends InternalMultiBucketAggregation.InternalBucket> {
        public final B[] topBuckets;
        public final long otherDocCount;
        
        public SelectionResult(B[] topBuckets, long otherDocCount) {
            this.topBuckets = topBuckets;
            this.otherDocCount = otherDocCount;
        }
    }
    
    @FunctionalInterface
    public interface BucketDocCountFunction {
        long bucketDocCount(long ord) throws IOException;
    }
    
    @FunctionalInterface
    public interface BucketUpdateFunction<B> {
        void updateBucket(B spare, BucketOrdsEnum ordsEnum, long docCount) throws IOException;
    }
    
    @FunctionalInterface
    public interface BucketArrayBuilder<B> {
        B[] buildBuckets(int size);
    }
    
    @FunctionalInterface
    public interface PriorityQueueBuilder<B> {
        PriorityQueue<B> buildPriorityQueue();
    }
}
```

File: server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java (hunk 1 above)
Comment (vinaykpud) [reply server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java]: Sure

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregator.java (hunk 2 above)
Comment (vinaykpud) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregator.java]: Agree with this, will do the refactor, but i am not sure how much it will be useful. It looks like the implementation is different in StringTermAggregation also Coordinator logic is different.

**Comment by vinaykpud** [comment]
### Condition Introduced in the PR

##### High level logic:
```
size =  min(bucketsInOrd, requestSize)
size < 0.2 * bucketsInOrd: PQ
size >= 0.2 * bucketsInOrd: QS or Return All
```
-------------------------------------------

Lets do the case by case breakdown:

##### case 1: bucketsInOrd <= requestSize
```
size = bucketsInOrd : return all buckets
size allocated for array = bucketsInOrd
```

##### case 2: bucketsInOrd > requestSize

```
    size = requestSize 
    case 2.1:
        requestSize < 0.2 * bucketsInOrd
        use PQ to select buckets
        size allocated for PQ = requestSize
    case 2.2:
       requestSize >= 0.2 * bucketsInOrd
       size allocated for array = bucketsInOrd
       calculate validBucketCount based on the all buckets which are above the MinDocCount
       if validBucketCount > requestSize: 
           use QS to select buckets
       else:
           return all buckets
```

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/BucketSelectionStrategy.java [hunk 3]
```diff
@@ -0,0 +1,239 @@
...
+import java.util.Iterator;
+import java.util.function.Supplier;
+
+import static org.opensearch.search.aggregations.InternalOrder.isKeyOrder;
+
+/**
+ * Strategy for selecting top buckets from aggregation results.
+ *
+ */
+public enum BucketSelectionStrategy {
```
Comment (rishabhmaurya) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/terms/BucketSelectionStrategy.java]: it doesn't have to be public enum

File: server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java [hunk 4]
```diff
@@ -196,4 +196,30 @@ private void testSearchCase(
...
+        testSearchCase(new MatchAllDocsQuery(), dataSet, aggregation -> aggregation.field(LONG_FIELD).size(2), agg -> {
+            assertEquals(2, agg.getBuckets().size());
+            for (int i = 0; i < 2; i++) {
+                LongTerms.Bucket bucket = (LongTerms.Bucket) agg.getBuckets().get(i);
+                assertThat(bucket.getKey(), equalTo((long) i));
+                assertThat(bucket.getDocCount(), equalTo(1L));
+            }
+        }, ValueType.NUMERIC);
+
+        // QuickSelect
```
Comment (rishabhmaurya) [inline server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java]: can we assert in the test which algo is used? 
also, maybe write test for all 3 cases i.e - 
```
when size >= bucketsInOrd : return all
bucketsInOrd> size && bucketsInOrd <= 5*size : quick select
else i.e. bucketsInOrd> size &&   bucketsInOrd > 5*size : pq
```

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/BucketSelectionStrategy.java [hunk 5]
```diff
@@ -0,0 +1,239 @@
...
+        We select the strategy based on the following condition
+            case 1: size < 0.2 * bucketsInOrd: PRIORITY_QUEUE
+            case 2: size > 0.2 * bucketsInOrd: QUICK_SELECT
+            case 3: size = bucketsInOrd : return all buckets
+        case 2 and 3 are encapsulated in QUICK_SELECT method.
+
+        Along with the above conditions, we also go with the original PRIORITY_QUEUE based approach
+        if isKeyOrder or its significant term aggregation
+        */
+        if ((size < 0.2 * bucketsInOrd) || isKeyOrder(order) || partiallyBuiltBucketComparator == null) {
```
Comment (rishabhmaurya) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/terms/BucketSelectionStrategy.java]: I would avoid floating point computation when you can just do 5*size

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/BucketSelectionStrategy.java (hunk 3 above)
Comment (vinaykpud) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/terms/BucketSelectionStrategy.java]: will make it package private

File: server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java (hunk 4 above)
Comment (vinaykpud) [reply server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java]: In this tests we may not be able to assert the algo used, since here we dont have reference to the `NumericTermsAggregator` class. But I can add one more test to cover the cases.

Comment (rishabhmaurya) [reply server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java]: check https://github.com/opensearch-project/OpenSearch/blob/e3a6ccadc942c64e83bd224031bc4d1c6ab14623/server/src/test/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorTests.java#L231

File: server/src/main/java/org/opensearch/search/DefaultSearchContext.java [hunk 6]
```diff
@@ -215,6 +216,7 @@ final class DefaultSearchContext extends SearchContext {
     private final int maxAggRewriteFilters;
     private final int filterRewriteSegmentThreshold;
     private final int cardinalityAggregationPruningThreshold;
+    private final int bucketSelectionStrategyMultiplier;
```
Comment (rishabhmaurya) [inline server/src/main/java/org/opensearch/search/DefaultSearchContext.java]: nitpick: `bucketSelectionStrategyFactor` for consistent naming

Comment (vinaykpud) [reply server/src/main/java/org/opensearch/search/DefaultSearchContext.java]: missed this, thanks

File: server/src/main/java/org/opensearch/search/SearchService.java [hunk 7]
```diff
@@ -369,6 +369,16 @@ public class SearchService extends AbstractLifecycleComponent implements IndexEv
...
 
+    public static final int DEFAULT_BUCKET_SELECTION_STRATEGY_FACTOR = 5;
+    public static final Setting<Integer> BUCKET_SELECTION_STRATEGY_FACTOR_SETTING = Setting.intSetting(
+        "search.aggregation.bucket_selection_strategy_factor",
+        DEFAULT_BUCKET_SELECTION_STRATEGY_FACTOR,
+        0,
+        10,
+        Setting.Property.NodeScope,
+        Setting.Property.Dynamic
+    );
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/SearchService.java:380]: Are we planning to use this setting for both terms and numeric aggregation?

Comment (vinaykpud) [reply server/src/main/java/org/opensearch/search/SearchService.java:380]: Yes, We are already using it for numeric aggregation. We will add it for terms.

**Comment by vinaykpud** [comment]
@jainankitk 
> Approach is similar to terms aggregation. Can you answer the questions in [#18732 (review)](https://github.com/opensearch-project/OpenSearch/pull/18732#pullrequestreview-3098352631) ?

Sure,
> 1. I am curious how we arrived at 20% as the right threshold for choosing between pq approach vs quickselect?

Compared with different threshold starting from 10% and analyzed for which value QuickSelects performs better. I have added the results here:
https://github.com/opensearch-project/OpenSearch/pull/18702#issuecomment-3075431370

> 2. Does this have any memory usage implications when the size is above 20% of value count?

There is no much difference in the memory usage is observed for the size above 20%.  When we use quickSelect we create an array with size equal to the bucketOrdinal and copy all buckets to it to perform the topN selection. Bellow link has JVM metrics comparison. 

https://github.com/opensearch-project/OpenSearch/issues/18703#issuecomment-3075221182
