### PR TITLE
[Segment Replication] Add new background task to fail stale replica shards.

### LINKED ISSUE #6606: [Segment Replication] Send Remote shard failure for lagging replicas
As last part of #4478, we need a mechanism to recognize shards are stale (with metrics introduced with #6520) for too long and send a remote shard failure. This is a remote failure as these metrics are collected by the primary shard.

I am thinking we add a background task that checks on a short schedule (30s) and invokes https://github.com/opensearch-project/OpenSearch/blob/da244c216cc6e58ddcb78a8c879c1f973ac3bc6d/server/src/main/java/org/opensearch/cluster/action/shard/ShardStateAction.java#L247

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
-> This PR adds new async task to send remote shard failure for lagging replica shard. 
-> This Works only with Segment Replication backpressure enabled. 
-> This Async task fails any replica shards which are stale (few checkpoints behind primary shard) and having current replication time twice the max replication time limit.

### Issues Resolved
Resolves #6606 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java [hunk 1]
```diff
@@ -154,4 +181,70 @@ public void setMaxAllowedStaleReplicas(double maxAllowedStaleReplicas) {
...
+        protected void runInternal() {
+            if (isSegmentReplicationBackpressureEnabled) {
+                final SegmentReplicationStats stats = tracker.getStats();
+                for (Map.Entry<ShardId, SegmentReplicationPerGroupStats> entry : stats.getShardStats().entrySet()) {
+                    final Set<SegmentReplicationShardStats> staleReplicas = getStaleReplicas(entry.getValue().getReplicaStats());
+                    final ShardId shardId = entry.getKey();
+                    final IndexService indexService = indicesService.indexService(shardId.getIndex());
+                    final IndexShard primaryShard = indexService.getShard(shardId.getId());
+                    for (SegmentReplicationShardStats staleReplica : staleReplicas) {
+                        if (staleReplica.getCurrentReplicationTimeMillis() > 2 * maxReplicationTime.millis()) {
```
Comment (Poojita-Raj) [inline server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java:213]: What would the default value be for max replication time? Is there any documentation we're providing on how to set this value when people enable backpressure?

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java:213]: the default value for [max replication time](https://github.com/opensearch-project/OpenSearch/blob/7b708c45558e9557d7306833e013eb8e6d00c5ec/server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java#L58) is 5min. For documentation, we need to open an issue with documentation repo documenting all changes/usages of segrep backpressure. I will open that issue after this PR gets merged in.

**Comment by Rishikesh1159** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/13034/
> * **CommitID:** [282ca4f](https://github.com/opensearch-project/OpenSearch/commit/282ca4ffe7ea35f3cd5e7ff4ffa61b52bed124a0)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Unrelated failure. Looks like flaky test. Created new issue to track the failure: https://github.com/opensearch-project/OpenSearch/issues/6873

File: server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java [hunk 2]
```diff
@@ -181,6 +191,36 @@ public void testIsSegrepLimitBreached_underStaleNodeLimit() throws Exception {
...
+            Set<SegmentReplicationShardStats> replicationStats = primaryShard.getReplicationStats();
+            assertEquals(1, replicationStats.size());
+            SegmentReplicationShardStats shardStats = replicationStats.stream().findFirst().get();
+            assertEquals(5, shardStats.getCheckpointsBehindCount());
+
+            // call the background task
+            service.getFailStaleReplicaTask().runInternal();
+
+            // verify that remote shard failed method is called which fails the replica shards falling behind.
+            verify(shardStateAction, times(1)).remoteShardFailed(any(), anyString(), anyLong(), anyBoolean(), anyString(), any(), any());
```
Comment (dreamer-89) [inline server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java:219]: nit: Instead of random values, we can use actual values i.e. `shardId`, `allocationId`, `primaryOperationTerm`, `true`, `"replica too far behind primary, marking as stale",`, `null`.

**Review by dreamer-89 — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java [hunk 3]
```diff
@@ -154,4 +181,70 @@ public void setMaxAllowedStaleReplicas(double maxAllowedStaleReplicas) {
...
         this.maxReplicationTime = maxReplicationTime;
     }
+
+    @Override
+    public void close() throws IOException {
+        failStaleReplicaTask.close();
+    }
+
+    // Background Task to fail replica shards if they are too far behind primary shard.
+    final class AsyncFailStaleReplicaTask extends AbstractAsyncTask {
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java:191]: The base class defaults to `ThreadPool.SAME`, so which thread pool will this run on? It looks like it initially gets scheduled during initialization so I honestly don't know what thread pool that is. I think it is worth being explicit by overriding `getThreadPool()`

Another point, and this is a bit of a style concern, but I really dislike non-static inner classes in Java because it implicitly binds the instance to the `this` pointer of the outer class instance that creates it. I would recommend making this static. If you need access to lots of members of the outer class, you can explicitly pass in a reference [like is done here](https://github.com/opensearch-project/OpenSearch/blob/eb78246b93766e31a47112ab01872fc2d9052374/server/src/main/java/org/opensearch/index/IndexService.java#L1064).

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java:191]: @andrross thanks for review. Yes I think it uses default `ThreadPool.SAME` as you said. I think using generic pool `ThreadPool.Names.GENERIC` here might make sense as we do [here](https://github.com/opensearch-project/OpenSearch/blob/eb78246b93766e31a47112ab01872fc2d9052374/server/src/main/java/org/opensearch/index/IndexService.java#L1157) for few other async tasks.

And for style concern, I have updated the inner class to static as you said.

File: server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java (hunk 2 above)
Comment (Rishikesh1159) [reply server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java:219]: I tried doing this, but to verify exact values we need the reference of listener (last parameter), we cannot pass as verify would fail and also I cannot do any() for just last parameter because we cannot combine any() with other parameters.

Comment (andrross) [reply server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java:219]: Is there a race condition here? Is it possible for the explicit `runInternal()` call to happen as well as the one that gets scheduled by default which would then cause the `times(1)` assertion to fail?

Comment (Rishikesh1159) [reply server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java:219]: > nit: Instead of random values, we can use actual values i.e. `shardId`, `allocationId`, `primaryOperationTerm`, `true`, `"replica too far behind primary, marking as stale",`, `null`.

If we try to combine any() with other regular parameters in method call, then we get an exception.

```
This exception may occur if matchers are combined with raw values:
    //incorrect:
    someMethod(any(), "raw String");
When using matchers, all arguments have to be provided by matchers.
For example:
    //correct:
    someMethod(any(), eq("String by matcher"));

For more info see javadoc for Matchers class.
```

Comment (Rishikesh1159) [reply server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java:219]: > Is there a race condition here? Is it possible for the explicit `runInternal()` call to happen as well as the one that gets scheduled by default which would then cause the `times(1)` assertion to fail?

No there is no race condition in this unit test. So, there are two ways to start background task either use runInternal() or by rescheduleIfNecessary(). In actual cluster or in an integration test when new instance of class is created and we start the background task. But here as this is a unit test and we are using mocks, so rescheduleIfNecessary() would not trigger the runInternal() because the class is just a mock. So, to verify that task actually works in unit test, I am making an explicit `service.getFailStaleReplicaTask().runInternal()`. So, this way task will run only once.

**Review by andrross — COMMENTED** [review]
> This Async task fails any replica shards which are stale (few checkpoints behind primary shard) and having current replication time twice the max replication time limit.

What does "max replication time limit" mean if the shard isn't failed until the time is double the max limit?

File: server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java [hunk 4]
```diff
@@ -200,6 +202,44 @@ public void testBelowReplicaLimit() throws Exception {
...
+        assertEqualSegmentInfosVersion(replicaNodes, primaryShard);
+        IndexShard replicaShard = getIndexShard(replicaNode, INDEX_NAME);
+
+        final CountDownLatch latch = new CountDownLatch(1);
+        final AtomicInteger totalDocs = new AtomicInteger(0);
+        try (final Releasable ignored = blockReplication(replicaNodes, latch)) {
+            // Index docs until replicas are staled.
+            Thread indexingThread = new Thread(() -> { totalDocs.getAndSet(indexUntilCheckpointCount()); });
+            indexingThread.start();
+            indexingThread.join();
```
Comment (andrross) [inline server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java:226]: Why use another thread if you immediately block on it to complete? Can you just replace this with `totalDocs.getAndSet(indexUntilCheckpointCount());` ?

File: server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java [hunk 5]
```diff
@@ -92,6 +117,8 @@ public SegmentReplicationPressureService(Settings settings, ClusterService clust
 
         this.maxAllowedStaleReplicas = MAX_ALLOWED_STALE_SHARDS.get(settings);
         clusterSettings.addSettingsUpdateConsumer(MAX_ALLOWED_STALE_SHARDS, this::setMaxAllowedStaleReplicas);
+
+        this.failStaleReplicaTask = new AsyncFailStaleReplicaTask(this, TimeValue.timeValueSeconds(30));
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java:121]: Style nitpick, but I'd move this interval to be a constant `INTERVAL` inside `AsyncFailStaleReplicaTask` since it is never set to a value other than 30 seconds.

File: server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java [hunk 6]
```diff
@@ -154,4 +181,80 @@ public void setMaxAllowedStaleReplicas(double maxAllowedStaleReplicas) {
...
+        @Override
+        protected boolean mustReschedule() {
+            return true;
+        }
+
+        @Override
+        protected void runInternal() {
+            if (pressureService.isSegmentReplicationBackpressureEnabled) {
+                final SegmentReplicationStats stats = pressureService.tracker.getStats();
+                for (Map.Entry<ShardId, SegmentReplicationPerGroupStats> entry : stats.getShardStats().entrySet()) {
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java:210]: Have you considered not being so aggressive with failing every lagging shard on a single execution? Like, lets say you've got one really hot shard that is causing the host to brown out, so all shards start to lag behind. Once they cross the threshold then you'll fail them all and the host will then be more-or-less idle. An alternative would be to fail at most 1 shard per iteration (or some other fixed number other than 1), so it would more gradually shed load.

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java:218]: Thanks @andrross for your input. I think what you said makes sense. I have updated the background task logic to fail stale replicas of only one shardId's in a single iteration of background task. This way we can gradually reduce the load on node.

File: server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java [hunk 7]
```diff
@@ -154,4 +181,100 @@ public void setMaxAllowedStaleReplicas(double maxAllowedStaleReplicas) {
...
+
+                // Find the shardId in node which is having stale replicas with highest current replication time.
+                // This way we only fail one shardId's stale replicas in every iteration of this background async task and there by decrease
+                // load gradually on node.
+                for (Map.Entry<ShardId, SegmentReplicationPerGroupStats> entry : stats.getShardStats().entrySet()) {
+                    final Set<SegmentReplicationShardStats> staleReplicas = pressureService.getStaleReplicas(
+                        entry.getValue().getReplicaStats()
+                    );
+                    for (SegmentReplicationShardStats staleReplica : staleReplicas) {
+                        if (staleReplica.getCurrentReplicationTimeMillis() > highestCurrentReplicationTimeMillis) {
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java:223]: `highestCurrentReplicationTimeMillis` is never set to a value other than zero, is it? I think you can use the stream API, something like this:

```
stats.getShardStats().entrySet().stream()
    .flatMap(entry -> pressureService.getStaleReplicas(entry.getValue().getReplicaStats()).stream()
        .map(r -> Tuple.tuple(entry.getKey(), r.getCurrentReplicationTimeMillis())))
    .max(Comparator.comparingLong(Tuple::v2))
    .map(Tuple::v1);
    .ifPresent(shardId -> {
        ...
    });
```

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java]: Sorry you are right, I missed reassigning `highestCurrentReplicationTimeMillis` in if condition. But Actually as you suggested using stream API makes this entire logic much cleaner. Thanks, I have updated the PR

File: server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java [hunk 8]
```diff
@@ -154,4 +182,95 @@ public void setMaxAllowedStaleReplicas(double maxAllowedStaleReplicas) {
     public void setMaxReplicationTime(TimeValue maxReplicationTime) {
         this.maxReplicationTime = maxReplicationTime;
     }
+
+    @Override
+    public void close() throws IOException {
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java:187]: Where does this newly added method get called?

**Review by andrross — COMMENTED** [review]
Asking again, but why is the limit implemented as double the "max replication time limit" setting?

**Comment by Rishikesh1159** [comment]
> Asking again, but why is the limit implemented as double the "max replication time limit" setting?

Sorry I missed this question previously. The "max replication time limit"(MAX_REPLICATION_TIME_SETTING), is the maximum time a replica can take to catch up to primary shard without triggering backpressure mechanism. Once this MAX_REPLICATION_TIME_SETTING limit along with MAX_INDEXING_CHECKPOINTS hit limit we trigger the backpressure mechanism to kick in. Once backpressure mechanism kicks in we temporarily stop indexing/writes requests to primary shard so that the replica shards can catch up with all the previous checkpoints.

Currently the default value of MAX_REPLICATION_TIME_SETTING is 5min, @mch2 came up with this number after running few benchmarks but users have the option to change this setting.

Now, to answer your question of why the limit of failing replicas is double the "max replication time limit" setting?:
Once backpressure mechanism kicks in we stop writes to primary shards, so replicas can catch up. So essentially if default of 5min is used, after backpressure kicks-in we give each replica 5min more to finish the replication, if it is not able to finish within given 5min then replica shard might be stuck (taking too long) so we just fail the shard and new shard can recover directly from primary and catch up. 
The reason we just wait for double the MAX_REPLICATION_TIME_SETTING is we don't want primary shards to be idle and block write requests for too long. If one replica shard is having trouble catching up in a replication group then instead of waiting forever for the replica to catch up, it is better to just fail the replica shard and move on.

**Comment by andrross** [comment]
@Rishikesh1159 Great explanation, thanks! I suggest documenting this in the code, probably either the SegmentReplicationPressureService classdoc or on the `SEGMENT_REPLICATION_INDEXING_PRESSURE_ENABLED` setting definition. Something like:

> When enabled, writes will be rejected when a replica shard falls behind by both the MAX_REPLICATION_TIME_SETTING time value and MAX_INDEXING_CHECKPOINTS number of checkpoints. Once a shard falls behind double the MAX_REPLICATION_TIME_SETTING time value it will be marked as failed.

**Review by andrross — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java (hunk 8 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java:187]: Currently, it is not called directly from anywhere. I took the reference from [PersistentTasksClusterService](https://github.com/opensearch-project/OpenSearch/blob/4511354122f8b423bbb78d95b7ed6d699450a9b1/server/src/main/java/org/opensearch/persistent/PersistentTasksClusterService.java#L126), just to make sure when service is closed this async task is also closed.

**Comment by Rishikesh1159** [comment]
> @Rishikesh1159 Great explanation, thanks! I suggest documenting this in the code, probably either the SegmentReplicationPressureService classdoc or on the `SEGMENT_REPLICATION_INDEXING_PRESSURE_ENABLED` setting definition. Something like:
> 
> > When enabled, writes will be rejected when a replica shard falls behind by both the MAX_REPLICATION_TIME_SETTING time value and MAX_INDEXING_CHECKPOINTS number of checkpoints. Once a shard falls behind double the MAX_REPLICATION_TIME_SETTING time value it will be marked as failed.

Sure I will add this code doc in next commit. Thanks @andrross  for your review on this PR.

**Review by andrross — APPROVED** [review]

**Comment by dreamer-89** [comment]
@Rishikesh1159 : Looks like backport workflow has some trouble with backporting. Care to raise manual backport ?
