### PR TITLE
fix compiler warning and base blob path case for searchable snapshots

### LINKED ISSUE #6557: [BUG] blob base path not taken into account in searchable snapshot implementation
**Describe the bug**
Currently searchable snapshot is assuming that there is never a base path configured for a repository. 
This seems to work just fine for the `FsRepository` but will fail on pretty much every object storage (S3/GCP/Azure/OCI) implementation as this is very often configured.

**To Reproduce**

1. Attempt to configure repository
```bash
OCI_REGION=us-phoenix-1
OCI_TENANCY=my_prod_tenancy
OCI_BUCKET=opensearch-repository
OCI_BUCKET_COMPARTMENT='ocid1.tenancy.oc1..aaaaaaaarjna4lgtentm4jcujqgb3pjkk422h5dfblctgz4sd62tpacikinq'
CREDENTIALS_FILE_PATH='/Users/saherman/my_sample_key.pem'

curl -XPUT "http://localhost:9200/_snapshot/oci_repository" -H 'Content-Type: application/json' -d"
{
  \"type\": \"oci\",
  \"settings\": {
    \"client\": \"default\",
    \"region\": \"${OCI_REGION}\",
    \"endpoint\": \"https://objectstorage.${OCI_REGION}.oraclecloud.com\",
    \"bucket\": \"${OCI_BUCKET}\",
    \"namespace\": \"myNamespace\",
    \"forceBucketCreation\" : true,
   \"base_path\" : \"my_base_path\",
    \"bucket_compartment_id\": \"${OCI_BUCKET_COMPARTMENT}\",
    \"userId\" : \"ocid1.user.oc1..aaaaaaaa5vtbkg4omdvni7t67izxphsvmqdnkfhhspn54hvo7n5noexample\",
    \"tenantId\" : \"ocid1.tenancy.oc1..aaaaaaaafi4l6qecddifs7kew5uzc24xwvtraosoiyvjgc5rq26example\",
    \"fingerprint\" : \"89:36:28:98:a4:er:0b:ad:46:10:a8:12:7e:2e:1a:a1\",
    \"credentials_file\": \"${CREDENTIALS_FILE_PATH}\"
  }
}
"
```
2. take a snapshot
```bash
curl -XPUT "http://localhost:9200/_snapshot/oci_repository/snapshot_1?wait_for_completion=true"
```

3. Restore as searchable snapshot
```bash
curl -X POST "http://localhost:9200/_snapshot/oci_repository/snapshot_1/_restore?pretty" -H 'Content-Type: application/json' -d'
{
  "storage_type": "remote_snapshot",
  "ignore_unavailable": true,
  "include_global_state": false,
  "rename_pattern": "(.+)",
  "rename_replacement": "restored_index_$1",
  "include_aliases": false
}
'
```
```
404 object not found
```

**Expected behavior**
Expected behavior is for that to work and find all objects

### PR DESCRIPTION
**Pull request by sam-herman**
### Description
Fixing base blob path scenario for searchable snapshots
1. Adding base blob path configuration for FS directory
2. Add base blob path scenario in searchable snapshot tests and fix bug
3. Fix compiler warnings

### Issues Resolved
Closes #6557

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kotwanikunal** [comment]
@samuel-oci Thanks for the contribution. 
Can you please run `./gradlew spotlessApply` to fix spotless errors and `./gradlew precommit` to validate other checks? 

More on that [here.](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md)

**Comment by samuel-oci** [comment]
> @samuel-oci Thanks for the contribution. Can you please run `./gradlew spotlessApply` to fix spotless errors and `./gradlew precommit` to validate other checks?
> 
> More on that [here.](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md)

Hi @kotwanikunal thanks for the feedback, done.
I do notice that there are some flakey IT tests that are not related to this change, but the gradle check seems to be passing.
Let me know if anything else is needed.

**Comment by kotwanikunal** [comment]
@samuel-oci This LGTM! 
@andrross Can you please have a look as well?

**Review by kotwanikunal — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java [hunk 1]
```diff
@@ -193,7 +193,7 @@ public void testAllocationWithDisruption() throws Exception {
 
     /**
      * Utility method which ensures cluster has balanced primary shard distribution across a single index.
-     * @throws Exception
+     * @throws Exception exception
```
Comment (andrross) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java:196]: Just an FYI, if you've been getting javadoc warnings/failures in the tests, it might be due to building with JDK 14. The javadoc rules are supposed to be ignored for tests, but JDK-14 doesn't seem to do the right thing, though it has been end-of-life for quite awhile now.

**Review by andrross — COMMENTED** [review]
Looks great, thanks @samuel-oci!

I actually think it makes sense to add a changelog entry here for "Add 'base_path' setting to File System Repository" since this is a user-facing feature. @kotwanikunal what do you think?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java (hunk 1 above)
Comment (kotwanikunal) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java:196]: Ahh. Yep. I think since we have a new setting for `FsRepository`, an entry makes sense. 
@samuel-oci You can follow the `CHANGELOG` guide here - https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#changelog
Please add an entry into the `Unreleased 2.x` section since this will be backported to `2.x`

**Comment by kotwanikunal** [comment]
> Looks great, thanks @samuel-oci!
> 
> I actually think it makes sense to add a changelog entry here for "Add 'base_path' setting to File System Repository" since this is a user-facing feature. @kotwanikunal what do you think?

Ahh. Yep. I think since we have a new setting for `FsRepository`, an entry makes sense.
@samuel-oci You can follow the `CHANGELOG` guide here - https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#changelog
Please add an entry into the `Unreleased 2.x` section since this will be backported to 2.x

**Comment by kotwanikunal** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/12095/
> * **CommitID:** [94e3be3](https://github.com/opensearch-project/OpenSearch/commit/94e3be3be6ebe91b137da809636d4ba7f7941961)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Unrelated failure due to heap space usage.

**Comment by samuel-oci** [comment]
Thanks for your comments @kotwanikunal @andrross , added a `CHANGELOG` entry.

**Comment by kotwanikunal** [comment]
Backport: https://github.com/opensearch-project/OpenSearch/pull/6584
