### PR TITLE
fix - replica shards trying to send replica checkpoints

### LINKED ISSUE #2815: [Segment Replication] Bug - Replica shards are incorrectly trying to send checkpoints.
Only Primary shards should publish checkpoints through PublishCheckpointAction
```
Caused by: org.opensearch.action.support.replication.ReplicationOperation$RetryOnPrimaryException: actual shard is not a primary [test-idx-1][0], node[jIi2oYnqTL-wfw47bWmscQ], [R], s[STARTED], a[id=_2eluHvrT4GavY2-pUjOuw]
	at org.opensearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:411) [classes/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [classes/:?]
	at org.opensearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:377) [classes/:?]
	at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:98) [classes/:?]
	at org.opensearch.transport.TransportService$8.doRun(TransportService.java:937) [classes/:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:792) [classes/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-04-07T23:01:21,115][WARN ][o.o.i.r.c.PublishCheckpointAction] [node_t0] [test-idx-1][0] segment replication checkpoint publishing failed
```

To reproduce run any of the tests in SegmentReplicationIT.  These errors will be logged but it does not fail the test.

### PR DESCRIPTION
**Pull request by Poojita-Raj**
Signed-off-by: Poojita Raj <poojiraj@amazon.com>

### Description
This fix stops the replica shards from incorrectly trying to send checkpoints by avoiding wiring up the replica's internalRefreshListeners with CheckpointRefreshListener.
 
### Issues Resolved
Resolves #2815 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 1]
```diff
@@ -3231,7 +3231,7 @@ private EngineConfig newEngineConfig(LongSupplier globalCheckpointSupplier) {
             }
         };
         final List<ReferenceManager.RefreshListener> internalRefreshListener;
-        if (indexSettings.isSegrepEnabled()) {
+        if (indexSettings.isSegrepEnabled() && shardRouting.primary()) {
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:3234]: Do we have tests for all the branches?

Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:3234]: We're working through adding the tests in this issue - https://github.com/opensearch-project/OpenSearch/issues/2355 - before we merge the feature branch back into main. This change was just to remove the failure/warning.

**Review by kotwanikunal — APPROVED** [review]
