### PR TITLE
[Flaky Test] Fix Flaky Test SearchTimeoutIT.testSimpleTimeout

### LINKED ISSUE #16056: [AUTOCUT] Gradle Check Flaky Test Report for SearchTimeoutIT
## Flaky Test Report for `SearchTimeoutIT`

Noticed the `SearchTimeoutIT` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| 5c19809ec05d0a2cf03a5105c5333303bc21cb0d | [14991](https://github.com/opensearch-project/OpenSearch/pull/14991) | [43688](https://build.ci.opensearch.org/job/gradle-check/43688/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"true"}}` |
| 6ad57bf393bda06da1c463d7c276d4a61d3cb299 | [14750](https://github.com/opensearch-project/OpenSearch/pull/14750) | [42519](https://build.ci.opensearch.org/job/gradle-check/42519/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"true"}}` |
| 9225aa270d15d4c49327c70b3780b96895e364c0 | [16212](https://github.com/opensearch-project/OpenSearch/pull/16212) | [49148](https://build.ci.opensearch.org/job/gradle-check/49148/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"true"}}` |
| 0b1650de442d7c84f532bd23ae8e766abf1d5c45 | [16154](https://github.com/opensearch-project/OpenSearch/pull/16154) | [48758](https://build.ci.opensearch.org/job/gradle-check/48758/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"false"}}`<br><br>`org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"true"}}` |
| a20058dd5cadcc1aeb2d615f8e7b9a490d48c1f8 | [16507](https://github.com/opensearch-project/OpenSearch/pull/16507) | [50344](https://build.ci.opensearch.org/job/gradle-check/50344/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"true"}}` |
| 66852cfd733271cd23c4ad6ee06d1e826c85f63a | [16186](https://github.com/opensearch-project/OpenSearch/pull/16186) | [48877](https://build.ci.opensearch.org/job/gradle-check/48877/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"false"}}` |
| 936cdb9043fb183cabe208fd7f7fc44a44b8f842 | [16472](https://github.com/opensearch-project/OpenSearch/pull/16472) | [50078](https://build.ci.opensearch.org/job/gradle-check/50078/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"false"}}` |
| 9b7681c1e56db5dd61787bd6f1ff9015781a8717 | [16583](https://github.com/opensearch-project/OpenSearch/pull/16583) | [50524](https://build.ci.opensearch.org/job/gradle-check/50524/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"false"}}` |
| c4a9cc1ccbbc49ef19d0f020522e1409505ed718 | [16398](https://github.com/opensearch-project/OpenSearch/pull/16398) | [49805](https://build.ci.opensearch.org/job/gradle-check/49805/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"false"}}` |
| d4d70d886ed5da1b657dca4c1e5af80ce9cd07ef | [16628](https://github.com/opensearch-project/OpenSearch/pull/16628) | [50777](https://build.ci.opensearch.org/job/gradle-check/50777/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"false"}}` |
| e9f77e38998bf42a17e34392bfa6683b1ec837d6 | [16612](https://github.com/opensearch-project/OpenSearch/pull/16612) | [50654](https://build.ci.opensearch.org/job/gradle-check/50654/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"true"}}` |
| eeb2f3997bb84f33f13b848e125051ecf2c2a1c7 | [16048](https://github.com/opensearch-project/OpenSearch/pull/16048) | [48315](https://build.ci.opensearch.org/job/gradle-check/48315/testReport/) | `org.opensearch.search.SearchTimeoutIT.testSimpleTimeout {p0={"search.concurrent_segment_search.enabled":"true"}}` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `SearchTimeoutIT` class are:

- [16681](https://github.com/opensearch-project/OpenSearch/pull/16681)
- [16388](https://github.com/opensearch-project/OpenSearch/pull/16388)
- [13131](https://github.com/opensearch-project/OpenSearch/pull/13131)
- [13461](https://github.com/opensearch-project/OpenSearch/pull/13461)
- [14022](https://github.com/opensearch-project/OpenSearch/pull/14022)
- [14474](https://github.com/opensearch-project/OpenSearch/pull/14474)
- [15341](https://github.com/opensearch-project/OpenSearch/pull/15341)
- [15376](https://github.com/opensearch-project/OpenSearch/pull/15376)
- [16802](https://github.com/opensearch-project/OpenSearch/pull/16802)
- [13799](https://github.com/opensearch-project/OpenSearch/pull/13799)
- [16233](https://github.com/opensearch-project/OpenSearch/pull/16233)
- [14631](https://github.com/opensearch-project/OpenSearch/pull/14631)
- [15204](https://github.com/opensearch-project/OpenSearch/pull/15204)
- [15367](https://github.com/opensearch-project/OpenSearch/pull/15367)
- [16030](https://github.com/opensearch-project/OpenSearch/pull/16030)
- [13474](https://github.com/opensearch-project/OpenSearch/pull/13474)
- [13772](https://github.com/opensearch-project/OpenSearch/pull/13772)
- [14273](https://github.com/opensearch-project/OpenSearch/pull/14273)
- [14394](https://github.com/opensearch-project/OpenSearch/pull/14394)
- [14555](https://github.com/opensearch-project/OpenSearch/pull/14555)
- [14574](https://github.com/opensearch-project/OpenSearch/pull/14574)
- [14659](https://github.com/opensearch-project/OpenSearch/pull/14659)
- [14668](https://github.com/opensearch-project/OpenSearch/pull/14668)
- [14742](https://github.com/opensearch-project/OpenSearch/pull/14742)
- [14785](https://github.com/opensearch-project/OpenSearch/pull/14785)
- [14790](https://github.com/opensearch-project/OpenSearch/pull/14790)
- [14853](https://github.com/opensearch-project/OpenSearch/pull/14853)
- [14901](https://github.com/opensearch-project/OpenSearch/pull/14901)
- [15017](https://github.com/opensearch-project/OpenSearch/pull/15017)
- [15088](https://github.com/opensearch-project/OpenSearch/pull/15088)
- [15166](https://github.com/opensearch-project/OpenSearch/pull/15166)
- [15326](https://github.com/opensearch-project/OpenSearch/pull/15326)
- [15333](https://github.com/opensearch-project/OpenSearch/pull/15333)
- [15360](https://github.com/opensearch-project/OpenSearch/pull/15360)
- [15379](https://github.com/opensearch-project/OpenSearch/pull/15379)
- [15420](https://github.com/opensearch-project/OpenSearch/pull/15420)
- [15430](https://github.com/opensearch-project/OpenSearch/pull/15430)
- [15524](https://github.com/opensearch-project/OpenSearch/pull/15524)
- [15664](https://github.com/opensearch-project/OpenSearch/pull/15664)
- [15671](https://github.com/opensearch-project/OpenSearch/pull/15671)
- [15778](https://github.com/opensearch-project/OpenSearch/pull/15778)
- [15916](https://github.com/opensearch-project/OpenSearch/pull/15916)
- [15970](https://github.com/opensearch-project/OpenSearch/pull/15970)
- [16040](https://github.com/opensearch-project/OpenSearch/pull/16040)
- [16046](https://github.com/opensearch-project/OpenSearch/pull/16046)
- [16076](https://github.com/opensearch-project/OpenSearch/pull/16076)
- [16129](https://github.com/opensearch-project/OpenSearch/pull/16129)
- [16179](https://github.com/opensearch-project/OpenSearch/pull/16179)
- [16191](https://github.com/opensearch-project/OpenSearch/pull/16191)
- [16211](https://github.com/opensearch-project/OpenSearch/pull/16211)
- [16236](https://github.com/opensearch-project/OpenSearch/pull/16236)
- [16237](https://github.com/opensearch-project/OpenSearch/pull/16237)
- [16314](https://github.com/opensearch-project/OpenSearch/pull/16314)
- [16331](https://github.com/opensearch-project/OpenSearch/pull/16331)
- [16370](https://github.com/opensearch-project/OpenSearch/pull/16370)
- [16375](https://github.com/opensearch-project/OpenSearch/pull/16375)
- [16408](https://github.com/opensearch-project/OpenSearch/pull/16408)
- [16418](https://github.com/opensearch-project/OpenSearch/pull/16418)
- [16455](https://github.com/opensearch-project/OpenSearch/pull/16455)
- [16484](https://github.com/opensearch-project/OpenSearch/pull/16484)
- [16504](https://github.com/opensearch-project/OpenSearch/pull/16504)
- [16641](https://github.com/opensearch-project/OpenSearch/pull/16641)
- [16644](https://github.com/opensearch-project/OpenSearch/pull/16644)
- [16706](https://github.com/opensearch-project/OpenSearch/pull/16706)
- [16716](https://github.com/opensearch-project/OpenSearch/pull/16716)
- [16751](https://github.com/opensearch-project/OpenSearch/pull/16751)
- [16800](https://github.com/opensearch-project/OpenSearch/pull/16800)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by kkewwei**
### Description
When numDocs=1000:
1. The `testSimpleTimeout` will cost several  minutes, when scoring each doc, it will cost 500ms, it's a long time to iterating all the doc in `queryphase`.
https://github.com/opensearch-project/OpenSearch/blob/5aa65096ff3ca3aec8eb563a8ac52c5e42bf5009/server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java#L138
2. `ReaderContext` is created before executing `queryphase` and released after the `fetchphase`.
3. the life time of `ReaderContext` is 1min(determined by `search.keep_alive_interval`)
4. If `queryPhase` costs too much time, the `ReaderContext` may be released before `fetchphase`, so the `fetch/Id` will be failed, which hit the case.
image

### Related Issues
Resolves #16056 #9401

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kkewwei** [comment]
> ❌ Gradle check result for [d1fc8be](https://github.com/opensearch-project/OpenSearch/commit/d1fc8be0ede384f1dc6b5ec64d0685272d6ba01f): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/51406/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes #15944

**Comment by kkewwei** [comment]
@reta @jed326, please have a look when you are free.

**Review by jed326 — APPROVED** [review]
Thanks @kkewwei this was a great find!

**Comment by reta** [comment]
> @reta @jed326, please have a look when you are free.

Thanks @kkewwei , I am actually a bit surprised by your findings

> If queryPhase costs too much time, the ReaderContext may be released before fetchphase, so the fetch/Id will be failed, which hit the case.

The query phase has to be terminated early by timeout, right? So it should be not much longer then timeout itself?

**Comment by kkewwei** [comment]
> timeout

timeout

> ❕ Gradle check result for [d1fc8be](https://github.com/opensearch-project/OpenSearch/commit/d1fc8be0ede384f1dc6b5ec64d0685272d6ba01f): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/51483/)
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

Yes, the query phase has to be terminated early by timeout, but the fetch phase is not affected by the `timeout`. `timeout` is checked every bulk docs, In case the size of bulk docs exceeds 120, the query phase will consume more than 1min.

**Comment by reta** [comment]
> @reta Yes, the query phase has to be terminated early by timeout, but it may be much longer than `timeout`. `timeout` is checked every bulk docs(`scoreRange`, initial_interval=1024), In case the size of bulk docs exceeds 120, the query phase will consume more than 1min.

Thanks @kkewwei , I think this is the problem, not the test, right? If timeout does not early terminate the query within reasonable time margin, it is not very useful.

**Comment by kkewwei** [comment]
> right



> > @reta Yes, the query phase has to be terminated early by timeout, but it may be much longer than `timeout`. `timeout` is checked every bulk docs(`scoreRange`, initial_interval=1024), In case the size of bulk docs exceeds 120, the query phase will consume more than 1min.
> 
> Thanks @kkewwei , I think this is the problem, not the test, right? If timeout does not early terminate the query within reasonable time margin, it is not very useful.

@reta  `timeout` is a  shard-level setting,  there exists a possibility where the actual timeout could be several times of the `timeout`, I tried to use `cancel_after_time_interval` instead of `timeout` (maybe not suitable) #11642.

To avoid excessive timeouts, maybe we should decrease the upper interval(100m), such as 100k?

**Comment by reta** [comment]
> @reta `timeout` is a shard-level setting, there exists a possibility where the actual timeout could be several times of the `timeout`, I tried to use `cancel_after_time_interval` instead of `timeout` (maybe not suitable) #11642.

@kkewwei thanks for staying with me, `timeout` is search request based setting (which we pass to shards), the intuition regarding the `timeout` (at least the one I built out of documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html#search-timeout) is that each shard has to respect the timeout (more or less), it is fine to be not precise but the search request with timeout of 5ms should not take 1m to complete for this specific test. 

I only briefly looked at overall implementation and it looks like we may lost some `timeout` handling guarantees, likely while implementing the concurrent search. Do you mind if I push some changes into your pull request? Thank you.

**Comment by kkewwei** [comment]
> > @reta `timeout` is a shard-level setting, there exists a possibility where the actual timeout could be several times of the `timeout`, I tried to use `cancel_after_time_interval` instead of `timeout` (maybe not suitable) #11642.
> 
> @kkewwei thanks for staying with me, `timeout` is search request based setting (which we pass to shards), the intuition regarding the `timeout` (at least the one I built out of documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html#search-timeout) is that each shard has to respect the timeout (more or less), it is fine to be not precise but the search request with timeout of 5ms should not take 1m to complete for this specific test.
> 
> I only briefly looked at overall implementation and it looks like we may lost some `timeout` handling guarantees, likely while implementing the concurrent search. ~Do you mind if I push some changes into your pull request?~ Thank you.
> 
> Opened up #16882

@reta  Of course, please free free to go ahead.

**Comment by kkewwei** [comment]
@reta, it seems #16882  can't solve the flay test. Short-circuiting only accelerates the response time of the shard, if first searchLeaf call costs 1min(for example, 150 docs, each wait time is 500ms), it will also continue hit the case.

**Comment by reta** [comment]
> @reta, it seems #16882 can't completely solve the flay test.

You are absolutely correct @kkewwei , we only check for timeouts in some places, but in general - we could not preemptively abort the process. Thanks!

File: server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java [hunk 1]
```diff
@@ -82,7 +82,7 @@ protected Settings nodeSettings(int nodeOrdinal) {
     }
 
     public void testSimpleTimeout() throws Exception {
-        final int numDocs = 1000;
+        final int numDocs = 10;
         for (int i = 0; i < numDocs; i++) {
```
Comment (reta) [inline server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java:86]: This is super nit, but could we bring in with line with 1.x / 1.3 line (since we figured out the previous change has introduced flakyness), thank you:

```suggestion
        for (int i = 0; i < 32; i++) {
```

**Review by reta — APPROVED** [review]
