### PR TITLE
[Segment Replication] Update peer recovery logic for segment replication

### LINKED ISSUE #5242: [Segment Replication] [BUG] Primary to primary recovery (relocation) breaks with segment conflicts.
From https://github.com/opensearch-project/OpenSearch/issues/4665 & [related](https://github.com/opensearch-project/OpenSearch/issues/3923) .  Primary-Primary recovery operates the same under segment replication as it does today by using Peer recovery.  

This process works by copying segments out to the new primary and then any operations received during the copy duration to be replayed, followed by the relocation handoff.  With segment replication the old primary shard will continue to copy out to other replicas during the relocation process.  Once the new primary is recovered it will reindex the operations received.  This means the new primary will reindex operations already sent out to the replication group, causing a segment conflict.  This will cause the replicas to fail and recover again from the new primary.

Ideas to fix: 
1. Bump SegmentInfos counter on the new primary to write segments with a different name.  Will mean segments containing the same ops will be copied twice. This conflict & solution is similar to the same problem encountered within failover steps.  However, with failover we do not have the luxury of a graceful handoff.
2. Recover the soon to be new primary as a replica. Once complete, block the old primary from copying out new segments to the group and force a segrep event to the new primary.  Recover from xlog any ops received during segment copy & perform handoff.
3. Block old primary from syncing to the rest of the replication group while relocation is in progress.  Could cause replicas to fall far of sync with primary & after relocation is complete will trigger expensive syncs.

### PR DESCRIPTION
**Pull request by dreamer-89**
Signed-off-by: Suraj Singh <surajrider@gmail.com>

### Description
Update the peer recovery logic to work with segment replication. The existing primary relocation is broken because of segment files conflicts. This happens because of target (new primary) is started with InternalEngine writes its own version of segment files which later on conflicts with file copies on replicas (copied from older primary); when this target is promoted as primary.

This change patches the recovery flow by first recovering the primary target with `NRTReplicationEngine` engine (to prevent target from generating segment files). Post phase 1 file copy operation, the older primary is blocked from performing segment file copy events to replicas (prevent segment file copy to replicas from auto refreshes). Post phase 2 before finalizeRecovery and handoff, the target (new primary) is forced to refresh segment files from older primary (to catch up with other replicas) followed by switching engine to InternalEngine. 

### Issues Resolved
#5242 

### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass
- [x] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dreamer-89** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/7257/
> * **CommitID:** [1414c09](https://github.com/opensearch-project/OpenSearch/commit/1414c093f57b9eca62dd949a48aad0ab333cb756)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Looks like a legit test failure. Looking into it. 
```
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.shard.IndexShardTests.testPrimaryHandOffUpdatesLocalCheckpoint" -Dtests.seed=EF62886CB90D105 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=lv-LV -Dtests.timezone=Atlantic/St_Helena -Druntime.java=19
  2> java.lang.AssertionError: RecoveryFailedException[[index][0]: Recovery failed from {dsEyIzXaub}{dsEyIzXaub}{Lyp3hhGUQ6KLW2cur9rZLQ}{0.0.0.0}{0.0.0.0:72}{dimrs} into {VrZdpzmpJk}{VrZdpzmpJk}{yNPgntL_ROidrq8BPYEYrw}{0.0.0.0}{0.0.0.0:71}{dimrs} ([index][0]: Recovery failed from {VrZdpzmpJk}{VrZdpzmpJk}{yNPgntL_ROidrq8BPYEYrw}{0.0.0.0}{0.0.0.0:71}{dimrs} into {dsEyIzXaub}{dsEyIzXaub}{Lyp3hhGUQ6KLW2cur9rZLQ}{0.0.0.0}{0.0.0.0:72}{dimrs})]; nested: RecoveryFailedException[[index][0]: Recovery failed from {VrZdpzmpJk}{VrZdpzmpJk}{yNPgntL_ROidrq8BPYEYrw}{0.0.0.0}{0.0.0.0:71}{dimrs} into {dsEyIzXaub}{dsEyIzXaub}{Lyp3hhGUQ6KLW2cur9rZLQ}{0.0.0.0}{0.0.0.0:72}{dimrs}]; nested: RecoveryEngineException[Phase[1] prepare target for translog failed]; nested: IllegalArgumentException[Shard can only be wired as a read only replica with Segment Replication enabled];
        at __randomizedtesting.SeedInfo.seed([EF62886CB90D105:92C2488BA82DB989]:0)
        at org.opensearch.index.shard.IndexShardTestCase$2.onFailure(IndexShardTestCase.java:187)
        at org.opensearch.indices.recovery.RecoveryTarget.notifyListener(RecoveryTarget.java:141)
        at org.opensearch.indices.replication.common.ReplicationTarget.fail(ReplicationTarget.java:175)
        at org.opensearch.index.shard.IndexShardTestCase.recoverUnstartedReplica(IndexShardTestCase.java:899)
        at org.opensearch.index.shard.IndexShardTestCase.recoverReplica(IndexShardTestCase.java:824)
        at org.opensearch.index.shard.IndexShardTestCase.recoverReplica(IndexShardTestCase.java:806)
        at org.opensearch.index.shard.IndexShardTests.testPrimaryHandOffUpdatesLocalCheckpoint(IndexShardTests.java:2431)
```

File: server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java [hunk 1]
```diff
@@ -219,7 +220,15 @@ public void prepareForTranslogOperations(int totalTranslogOps, ActionListener<Vo
 
     @Override
     public void finalizeRecovery(final long globalCheckpoint, final long trimAboveSeqNo, ActionListener<Void> listener) {
-        ActionListener.completeWith(listener, () -> {
+        final StepListener<Void> segrepListener = new StepListener<>();
+        // Force segment refresh on primary relocation which is recovered as replica initially & reset engine
+        if (this.indexShard.indexSettings().isSegRepEnabled() && this.state().getPrimary() == true) {
+            logger.info("--> Force segment replication event on new primary and switch to ReadWrite (Internal) engine");
+            this.indexShard.performSegmentReplicationRefresh(segrepListener);
```
Comment (mch2) [inline server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java:227]: I think we should look at a solution here that doesn't couple IndexShard to our SegmentReplicationTargetService.

What if we added a new req handler inside of SegmentReplicationTargetService that could be invoked from the primary before this step?  It would be similar to a publischeckpoint, but only route to a single shard.

File: CHANGELOG.md [hunk 2]
```diff
@@ -13,6 +13,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 - [Test] Add IAE test for deprecated edgeNGram analyzer name ([#5040](https://github.com/opensearch-project/OpenSearch/pull/5040))
 - Allow mmap to use new JDK-19 preview APIs in Apache Lucene 9.4+ ([#5151](https://github.com/opensearch-project/OpenSearch/pull/5151))
 - Add feature flag for extensions ([#5211](https://github.com/opensearch-project/OpenSearch/pull/5211))
+- [Segment Replication] Update peer recovery logic for segment replication ([#5344](https://github.com/opensearch-project/OpenSearch/pull/5344))
```
Comment (ashking94) [inline CHANGELOG.md:16]: We could make a generic line item stating `Segment replication bug fixed` unless we want this to explicitly show in the release note.

File: server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java [hunk 3]
```diff
@@ -40,7 +40,10 @@ public void beforeRefresh() throws IOException {
 
     @Override
     public void afterRefresh(boolean didRefresh) throws IOException {
-        if (didRefresh && shard.state() != IndexShardState.CLOSED && shard.getReplicationTracker().isPrimaryMode()) {
+        if (didRefresh
+            && shard.state() != IndexShardState.CLOSED
+            && shard.getReplicationTracker().isPrimaryMode()
+            && shard.isBlockInternalCheckPointRefresh() == false) {
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java:46]: Why is primary mode not sufficient for publishing?

Lets assume the condition is correct, how do we ensure that the publisher stops lets say in usecase where once publish starts and then this condition becomes false? The primary term validation is present only for certain TransportReplicationActions. Is it possible that a particular target node could be receiving segment files from old primary as well a new primary given the afterRefresh method is async. If this understanding is correct, pls do help with the concerned code that handles this.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 4]
```diff
@@ -308,6 +312,25 @@ Runnable getGlobalCheckpointSyncer() {
     private final Store remoteStore;
     private final TranslogFactory translogFactory;
 
+    public boolean isBlockInternalCheckPointRefresh() {
+        return blockInternalCheckPointRefresh;
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:316]: Is it possible to create this boolean tracker variable elsewhere? May be segmentReplicationTargetService through an index event update? just thinking aloud.

Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:316]: but i get this should be set in a place such that both the source and target could access it through a standard access pattern.

File: server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java [hunk 5]
```diff
@@ -219,7 +220,15 @@ public void prepareForTranslogOperations(int totalTranslogOps, ActionListener<Vo
 
     @Override
     public void finalizeRecovery(final long globalCheckpoint, final long trimAboveSeqNo, ActionListener<Void> listener) {
-        ActionListener.completeWith(listener, () -> {
+        final StepListener<Void> segrepListener = new StepListener<>();
+        // Force segment refresh on primary relocation which is recovered as replica initially & reset engine
+        if (this.indexShard.indexSettings().isSegRepEnabled() && this.state().getPrimary() == true) {
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java:225]: `this.state().getPrimary()` - would this start returning true before the relocation handoff is complete?

File: server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java (hunk 1 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java:227]: +1 - we could pass a consumer (something like SegmentReplicationTargetService:: performSegmentReplicationRefresh) to the recovery process and decouple index shard and the segrep service.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 6]
```diff
@@ -417,6 +441,44 @@ public boolean shouldCache(Query query) {
...
+     */
+    public void performSegmentReplicationRefresh(StepListener<Void> listener) {
+        this.segmentReplicationTargetService.startReplication(
+            ReplicationCheckpoint.empty(this.shardId()),
+            this,
+            new SegmentReplicationTargetService.SegmentReplicationListener() {
+                @Override
+                public void onReplicationDone(SegmentReplicationState state) {
+                    try {
+                        indexShardOperationPermits.blockOperations(30, TimeUnit.MINUTES, () -> { resetEngineToGlobalCheckpoint(); });
```
[the remark this answers is not in the document]
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:464]: i guess we are rolling back to the safe commit to ensure that any flushes that could have happened on the new primary can be reverted. Is there a way that we can prevent flushes to happen while on the new primary until the relocation handoff is complete. That way you can ensure that you do not have to handle syncing the segment files again.

File: server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java (hunk 5 above)
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java:225]: For primary relocation, the `state().getPrimary()` on target would be true as it is primary relocation.

File: server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java (hunk 3 above)
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java:46]: Thats correct primary term bump does not happen during peer primary recoveries

File: server/src/main/java/org/opensearch/indices/recovery/ForceSyncRequest.java [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+import org.opensearch.index.shard.ShardId;
+
+import java.io.IOException;
+
+/**
+ * Request to force a round of segment replication on primary target
+ *
+ * @opensearch.internal
+ */
+public class ForceSyncRequest extends RecoveryTransportRequest {
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/indices/recovery/ForceSyncRequest.java:22]: How long can the force sync take with remote store and bigger segments? Do we need wait_for params?

File: server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java [hunk 8]
```diff
@@ -188,6 +188,20 @@ public void recoverToTarget(ActionListener<RecoveryResponse> listener) {
...
+        // Disable this shard from performing segment replication on replicas
+        if (shard.indexSettings().isSegRepEnabled() && request.isPrimaryRelocation() == true) {
+            shard.setBlockInternalCheckPointRefresh(true);
+        }
+    }
+
+    protected void resumeSegmentReplicationRefresh() {
+        // Enable this shard from performing segment replication on replicas
+        if (shard.indexSettings().isSegRepEnabled() && request.isPrimaryRelocation() == true) {
+            shard.setBlockInternalCheckPointRefresh(false);
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java:201]: Can we assert if the previous state was blocked before unblocking

File: server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java (hunk 3 above)
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java:46]: I think it can be handled in `clusterChanged` event inside [SegmentReplicationSourceService](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java#L159)

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 9]
```diff
@@ -308,6 +308,23 @@ Runnable getGlobalCheckpointSyncer() {
...
+    }
+
+    /**
+     * Used with segment replication only.
+     *
+     * The flag is meant to block the segment replication events to all replicas from existing primary. This is done in
+     * order to ensure that file copied during peer recovery does not conflict with segment files from new primary post
+     * peer recovery.
+     */
+    private boolean blockInternalCheckPointRefresh;
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:326]: During a primary relocation handoff all operation to the older primary is drained to a queue which means there will be no operations indexed into older primary, at this point can we perform a final commit/refresh, wondering if we need to explicitly block refreshes at this point since refreshes wouldn't create segments

File: server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java (hunk 8 above)
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java:201]: Updated.

File: server/src/main/java/org/opensearch/indices/recovery/ForceSyncRequest.java (hunk 7 above)
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/indices/recovery/ForceSyncRequest.java:22]: Thank you @Bukhtawar for raising this point. 
During `phase1` of recovery process, the target is synced with the source node. This action to force segment replication step (before finalize recovery) ensures new segments (if any) sync resulted from auto refreshes on older primary post phase 1 and thus should be light weight. Based on this, I think `wait_for` may not be needed. WDYT ?

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 9 above)
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:326]: Thank you @Bukhtawar for suggesting this. Yes, it makes sense to delay the segment replication round on primary target till relocation handoff in order to avoid blocking refresh. Let me try this approach.

Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:326]: We need to just make sure it doesn't take too long else operations would pile up and the indexing operation permits blocked for longer

Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:326]: I updated the logic and it seems to work fine (integ tests inside SegmentReplicationRelocationIT passes). I suspect the force segment replication shouldn't take much time as target is already synced during phase 1. I am planning to quantify the lag added by Segment replication with different shard/segment sizes on a real cluster. I will update with results here.

File: server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java (hunk 3 above)
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java]: @Bukhtawar : Tried the changes on local machine and I see seg rep took additional ~3.5 secs during relocation handoff. [More details](https://github.com/opensearch-project/OpenSearch/issues/5242#issuecomment-1368133952)

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 9 above)
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java]: @Bukhtawar @mch2  : Tried the changes on local machine and I see seg rep took additional ~3.5 secs during relocation handoff. https://github.com/opensearch-project/OpenSearch/issues/5242#issuecomment-1368133952

Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java]: > With our current impl I believe any ongoing event will simply cancel and start over from new primary.

@mch2 : I think this is not currently handled as peer recovery doesn't make primary term bump. I wrote a integ test which detects this [here](https://github.com/opensearch-project/OpenSearch/commit/647f6b860c40c17398ad3bc523ed25d5f59adf62). It was brought up previously by @ashking94 in [thread above](https://github.com/opensearch-project/OpenSearch/pull/5344#discussion_r1042555829)

File: server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java [hunk 10]
```diff
@@ -122,17 +124,21 @@ public static class Actions {
 
     private final ReplicationCollection<RecoveryTarget> onGoingRecoveries;
 
+    private final SegmentReplicationTargetService segmentReplicationTargetService;
```
Comment (mch2) [inline server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java:127]: Would prefer we didn't have these services coupled.  Though I understand moving the req handler into SegmentReplicationTargetServices would require some refactoring in RecoverySourceHandler to depend on a RemoteRecoveryTargetHandler (or renamed client component) directly.  Maybe not so bad?

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 11]
```diff
@@ -1605,6 +1620,10 @@ static Engine.Searcher wrapSearcher(
         }
     }
 
+    public void resetEngine() throws IOException, InterruptedException, TimeoutException {
```
[the remark this answers is not in the document]
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:1623]: Updated

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 12]
```diff
@@ -3304,6 +3323,13 @@ private EngineConfig newEngineConfig(LongSupplier globalCheckpointSupplier) thro
         if (this.checkpointPublisher != null && indexSettings.isSegRepEnabled() && shardRouting.primary()) {
             internalRefreshListener.add(new CheckpointRefreshListener(this, this.checkpointPublisher));
         }
+        /**
+         * With segment replication enabled for primary relocation, recover replica shard initially as read only and
+         * promote to during relocation handoff post segment replication.
+         */
+        boolean isReadOnlyReplica = indexSettings.isSegRepEnabled()
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:3330]: nit - does the variable name sound intuitive when the shard is actually a bootstrapping primary(`shardRouting.primary() == true`). May be let's rename it?

**Review by ashking94 — APPROVED** [review]
Thank you for making this change. It definitely simplifies by bootstrapping the new primary as a read replica and handling copying segment files in the relocated method right before the handoff compared to the previous approach. Looks like this way we stop the segment files to diverge on the new primary from the old primary and also at the same time ensuring that the new primary does not publish checkpoints.

File: server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java (hunk 3 above)
Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java]: Discussed this offline with @mch2, will take this up in a separate task. Created https://github.com/opensearch-project/OpenSearch/issues/5706 to track this separately.

**Review by mch2 — APPROVED** [review]
LGTM

**Comment by dreamer-89** [comment]
Windows precommit failure to memorry error. Refiring!

```
> Task :modules:lang-painless:forbiddenApisTest
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000795600000, 716177408, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 716177408 bytes for Failed to commit area from 0x0000000795600000 to 0x00000007c0100000 of length 716177408.

```

**Comment by dreamer-89** [comment]
@Bukhtawar @ashking94 : Please have a look in latest changes.

**Comment by dreamer-89** [comment]
@Bukhtawar : Please feel free to leave any comment in case you have any concerns.

**Comment by ashking94** [comment]
@dreamer-89  are you planning to backport this PR to 2.x?

**Comment by dreamer-89** [comment]
> @dreamer-89 are you planning to backport this PR to 2.x?

Yes @ashking94. I am planning to backport this along with the fix. Right now, I am testing the fix on actual cluster with setup you mentioned in #5848

**Comment by andrross** [comment]
> > @dreamer-89 are you planning to backport this PR to 2.x?
> 
> I am planning to backport this along with the fix. Right now, I am testing the fix on actual cluster with setup you mentioned in #5848

It is probably best to stay on top of the backports (even if for this case it means backporting a muted integration test). When you don't backport a change that touches the same files as a subsequent change that is to be backported, then the cherry-pick will fail and it will be harder for everyone. #5944 is a backport of a change that touched the new integration test introduced in this PR. I had to resolve a conflict on the cherry-pick to exclude the new file, but it also means when you do backport you'll need to manually apply the subsequent changes to that integration test that happened on main.

**Comment by dreamer-89** [comment]
> ```shell
> git fetch
> ```

Thank you @andrross for the comment and apologies for inconvenience. Backport was initially delayed to avoid the change in `2.5.0`. I am backporting this change now.

**Comment by dreamer-89** [comment]
> Thank you @andrross for the comment and apologies for inconvenience. Backport was initially delayed to avoid the change in `2.5.0`. I am backporting this change now.



> > > @dreamer-89 are you planning to backport this PR to 2.x?
> > 
> > 
> > I am planning to backport this along with the fix. Right now, I am testing the fix on actual cluster with setup you mentioned in #5848
> 
> It is probably best to stay on top of the backports (even if for this case it means backporting a muted integration test). When you don't backport a change that touches the same files as a subsequent change that is to be backported, then the cherry-pick will fail and it will be harder for everyone. #5944 is a backport of a change that touched the new integration test introduced in this PR. I had to resolve a conflict on the cherry-pick to exclude the new file, but it also means when you do backport you'll need to manually apply the subsequent changes to that integration test that happened on main.

Thank you @andrross for the comment and apologies for inconvenience. Backport was initially delayed to avoid the change in 2.5.0. I am backporting this change now.
