### PR TITLE
Fix URLDecodeProcessor random test failure

### LINKED ISSUE #5327: [BUG] URLDecodeProcessorTests.testTargetField failure
See https://build.ci.opensearch.org/job/gradle-check/7160/

This is deterministically reproducible with the following seed:

```
./gradlew ':modules:ingest-common:test' --tests "org.opensearch.ingest.common.URLDecodeProcessorTests.testTargetField" -Dtests.seed=F804ECD53FDB8C02
```

```
org.opensearch.ingest.common.URLDecodeProcessorTests > testTargetField FAILED
    java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "𷔆"
        at __randomizedtesting.SeedInfo.seed([F804ECD53FDB8C02:93429A1B227C6933]:0)
        at java.base/java.net.URLDecoder.decode(URLDecoder.java:237)
        at java.base/java.net.URLDecoder.decode(URLDecoder.java:147)
        at org.opensearch.ingest.common.URLDecodeProcessor.apply(URLDecodeProcessor.java:52)
        at org.opensearch.ingest.common.URLDecodeProcessor.process(URLDecodeProcessor.java:60)
        at org.opensearch.ingest.common.URLDecodeProcessor.process(URLDecodeProcessor.java:42)
        at org.opensearch.ingest.common.AbstractStringProcessor.execute(AbstractStringProcessor.java:108)
        at org.opensearch.ingest.common.AbstractStringProcessorTestCase.testTargetField(AbstractStringProcessorTestCase.java:173)
```

### PR DESCRIPTION
**Pull request by andrross**
The randomly-generated input for this test may contain non-URL-safe characters (such as `%`) so it needs to be URL encoded as well.

### Issues Resolved
Closes #5327

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by adnapibar — APPROVED** [review]
LGTM

File: modules/ingest-common/src/main/java/org/opensearch/ingest/common/URLDecodeProcessor.java [hunk 1]
```diff
@@ -48,11 +48,7 @@ public final class URLDecodeProcessor extends AbstractStringProcessor<String> {
     }
 
     public static String apply(String value) {
-        try {
-            return URLDecoder.decode(value, "UTF-8");
```
Comment (dblock) [inline modules/ingest-common/src/main/java/org/opensearch/ingest/common/URLDecodeProcessor.java:52]: I think there was a reason to throw `IllegalArgumentException` here. What are the consequences on a REST API status code for example (this would need tests)?

**Review by dblock — CHANGES_REQUESTED** [review]
I think we may have subtly altered behavior here, let's make sure we didn't.

File: modules/ingest-common/src/main/java/org/opensearch/ingest/common/URLDecodeProcessor.java (hunk 1 above)
Comment (adnapibar) [reply modules/ingest-common/src/main/java/org/opensearch/ingest/common/URLDecodeProcessor.java:52]: I don't think so. The `UnsupportedEncodingException` depends on which `URLDecoder.decode()` we use, if you pass the encoding as a string (earlier), then you need to handle the checked exception while if you use the class `CharSet` (now) as the encoding you don't.

File: modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java [hunk 2]
```diff
@@ -32,13 +32,14 @@
...
-import java.io.UnsupportedEncodingException;
 import java.net.URLDecoder;
+import java.net.URLEncoder;
+import java.nio.charset.StandardCharsets;
 
 public class URLDecodeProcessorTests extends AbstractStringProcessorTestCase<String> {
     @Override
     protected String modifyInput(String input) {
-        return "Hello%20G%C3%BCnter" + input;
+        return "Hello%20G%C3%BCnter" + urlEncode(input);
```
Comment (reta) [inline modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java:42]: @andrross this is very interesting, why the test needs to manually do `urlEncode`? Shouldn't the input there be properly encoded before?

Comment (adnapibar) [reply modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java:42]: I think the input is a random string and the test works as long as it doesn't have a '%' in it.

Comment (reta) [reply modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java:42]: Sure, the random string could be equally encoded before feeding it to `URLDecodeProcessorTests`, the part which concerns - the test itself does manipulation in order to pass, but apparently that not how the things are working.

File: modules/ingest-common/src/main/java/org/opensearch/ingest/common/URLDecodeProcessor.java (hunk 1 above)
Comment (andrross) [reply modules/ingest-common/src/main/java/org/opensearch/ingest/common/URLDecodeProcessor.java:52]: Yeah, it is no longer possible for this line of code to generate an `UnsupportedEncodingException`.

File: modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java (hunk 2 above)
Comment (andrross) [reply modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java:42]: The test takes a random string and prefixes it with some URL-encoded content, and verifies that the result is the URL-decoded version of what was input into it. `AbstractStringProcessorTestCase` doesn't know anything about URL encoding. The previous version of this test assumed that the random part of the string was URL decode-able, which is not a valid assumption for all random strings. The easiest way to make sure the random string is decode-able is to just URL-encode it to start with. I agree it looks weird. Honestly I'm not sure the random string part is important. I could change it to just do the following:

```java
@Override
protected String modifyInput(String input) {
    return "Hello%20G%C3%BCnter";
}

@Override
protected String expectedResult(String input) {
    return "Hello Günter";
}
```

What do you think? There is in fact precedent for this approach: 
https://github.com/opensearch-project/OpenSearch/blob/9168f1fb43015cf7f33eab30f1300ec85f4d4305/modules/ingest-common/src/test/java/org/opensearch/ingest/common/GsubProcessorTests.java#L44-L52

Comment (reta) [reply modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java:42]: thanks @andrross, I had something like this in mind - generate random input in  `urlEncode` form:

```
@Override
    protected AbstractStringProcessor<String> newProcessor(String field, boolean ignoreMissing, String targetField) {
        return new URLDecodeProcessor(urlEncode(randomAlphaOfLength(10)), null, field, ignoreMissing, targetField);
    }
```

> AbstractStringProcessorTestCase doesn't know anything about URL encoding.

That's I think is what should be preserved, but using `urlEncode` breaks that

Comment (andrross) [reply modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java:42]: That's not the randomness that is causing the problem though. The problem is [here](https://github.com/opensearch-project/OpenSearch/blob/37ac3788a3937ed415039edb2671da08e6450ed5/modules/ingest-common/src/test/java/org/opensearch/ingest/common/AbstractStringProcessorTestCase.java#L169), which I believe is why that `modifyInput` method was added to the base test class to provide a hook to modify what was generated.

Comment (reta) [reply modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java:42]: Oh I see @andrross , apologies for confusion, I think you change makes sense: the `modifyInput` is use to ingest the field and `URLDecodeProcessor` assumes that the field is URL encoded.

**Comment by andrross** [comment]
@dblock Just curious about the backporting. I understand 2.x and 1.x because future releases will come from those branches and it is great to have test fixes there, but why 1.1? (and why not 2.4 for example?)

**Comment by dblock** [comment]
I think @reta wanted it in 1.1? Did I do it? :)
