### PR TITLE
Fix flaky test testStatsOnShardUnassigned in RemoteStoreStatsIT

### LINKED ISSUE #9036: [BUG] org.opensearch.remotestore.RemoteStoreStatsIT.testStatsOnShardUnassigned is flaky
**Describe the bug**
org.opensearch.remotestore.RemoteStoreStatsIT.testStatsOnShardUnassigned test is flaky on main branch. Encountered this failure during PR build of #8758. 

**To Reproduce**
REPRODUCE WITH: 
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteStoreStatsIT.testStatsOnShardUnassigned" -Dtests.seed=1EE76B3CC8051A6 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=hu-HU -Dtests.timezone=Africa/Bissau -Druntime.java=20
```

**Expected behavior**
Test should pass.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**
Jenkins - https://build.ci.opensearch.org/job/gradle-check/21584/testReport/junit/org.opensearch.remotestore/RemoteStoreStatsIT/testStatsOnShardUnassigned/

### PR DESCRIPTION
**Pull request by ashking94**
### Description
This fixes the flaky test for different type of failures mentioned in the issue #9036.
 - Assertion count for successful shards
 - Due to node being stopped and failover not completing, during the teardown there were assertion failures on primaryMode. 

### Related Issues
Resolves #9036

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mch2** [comment]
https://github.com/opensearch-project/OpenSearch/pull/8718/files needs to be backported to 2.x that introduced this test

**Review by Poojita-Raj — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java [hunk 1]
```diff
@@ -443,12 +445,19 @@ public void testStatsOnShardUnassigned() throws IOException {
...
+        String nodeToBeStopped = randomBoolean() ? primaryNodeName(INDEX_NAME) : replicaNodeName(INDEX_NAME);
+        internalCluster().stopRandomNode(InternalTestCluster.nameFilter(nodeToBeStopped));
+        ensureYellowAndNoInitializingShards(INDEX_NAME);
+        ensureStableCluster(nodeCount - 1);
         RemoteStoreStatsResponse response = client().admin().cluster().prepareRemoteStoreStats(INDEX_NAME, "0").get();
         int dataNodeCountAfterStop = client().admin().cluster().prepareHealth().get().getNumberOfDataNodes();
         assertEquals(dataNodeCountBeforeStop, response.getTotalShards());
         assertEquals(dataNodeCountAfterStop, response.getSuccessfulShards());
+        // Indexing docs to ensure that the primary has started
+        indexSingleDoc(INDEX_NAME);
```
Comment (shourya035) [inline server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java:460]: Why are we indexing docs at the end of the test? Can we not just delete the index to wipe the slate clean? Our test assertions would have been completed by this time.

**Review by shourya035 — CHANGES_REQUESTED** [review]

**Review by shourya035 — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java (hunk 1 above)
Comment (ashking94) [reply server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java:460]: There are certain sanity and validations that happen during/after the teardown of the individual test. Decided to keep indexing to get around the current issue in hand and also ensure that the common teardown sanity works as well for the created index.

**Review by sachinpkale — APPROVED** [review]
