### PR TITLE
Attempt to fix ThreadLeakControl issues in S3BlobContainerRetriesTests

### LINKED ISSUE #17540: [BUG] [Flaky Test] S3BlobContainerRetriesTests is flaky
### Describe the bug

Not sure why this didn't get an autocut. Looks like threads are leaking in org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod. 

Example failures: 
https://build.ci.opensearch.org/job/gradle-check/54203/testReport/junit/org.opensearch.repositories.s3/S3BlobContainerRetriesTests/classMethod_2/ (run from https://github.com/opensearch-project/OpenSearch/pull/17344) 

https://build.ci.opensearch.org/job/gradle-check/54203/testReport/junit/org.opensearch.repositories.s3/S3BlobContainerRetriesTests/classMethod_2/ (run from https://github.com/opensearch-project/OpenSearch/pull/17513)

### Related component

Build

### To Reproduce

See linked jenkins builds

### Expected behavior

Test should not be flaky.

### LINKED ISSUE #17551: [AUTOCUT] Gradle Check Flaky Test Report for S3BlobContainerRetriesTests
## Flaky Test Report for `S3BlobContainerRetriesTests`

Noticed the `S3BlobContainerRetriesTests` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| 1294506439e8ea64bb4e02ba5bc16b4446a05292 | [18061](https://github.com/opensearch-project/OpenSearch/pull/18061) | [57060](https://build.ci.opensearch.org/job/gradle-check/57060/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| 47f9bdb98418ab1eb08d6774d4c7bca0865459ef | [18165](https://github.com/opensearch-project/OpenSearch/pull/18165) | [57479](https://build.ci.opensearch.org/job/gradle-check/57479/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| 60aa7a51c56c4b9fb83012b0c404a959f9e7c4cc | [18212](https://github.com/opensearch-project/OpenSearch/pull/18212) | [57844](https://build.ci.opensearch.org/job/gradle-check/57844/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| 6719b1f52bc949c38a247725d61702c26f37b215 | [18057](https://github.com/opensearch-project/OpenSearch/pull/18057) | [57116](https://build.ci.opensearch.org/job/gradle-check/57116/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| 816787d3e58d3f843207e77b6cb8eb99cd3512da | [18044](https://github.com/opensearch-project/OpenSearch/pull/18044) | [57010](https://build.ci.opensearch.org/job/gradle-check/57010/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| 8964f63653fadd5363267e0ef2edf2dd7bfe0105 | [17873](https://github.com/opensearch-project/OpenSearch/pull/17873) | [56048](https://build.ci.opensearch.org/job/gradle-check/56048/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| cc82be9cda7414f919cf64a52880135c2f4937f0 | [17515](https://github.com/opensearch-project/OpenSearch/pull/17515) | [54208](https://build.ci.opensearch.org/job/gradle-check/54208/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| e0a67fd9ca949b14b90dc206231d90158bc35b38 | [17674](https://github.com/opensearch-project/OpenSearch/pull/17674) | [55181](https://build.ci.opensearch.org/job/gradle-check/55181/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| fc78200cd33121c2a7f52250b19816870495dc26 | [17732](https://github.com/opensearch-project/OpenSearch/pull/17732) | [55229](https://build.ci.opensearch.org/job/gradle-check/55229/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| fcb0649b14536889a6f4c28197cf485c33dfff5e | [17668](https://github.com/opensearch-project/OpenSearch/pull/17668) | [54996](https://build.ci.opensearch.org/job/gradle-check/54996/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `S3BlobContainerRetriesTests` class are:

- [17950](https://github.com/opensearch-project/OpenSearch/pull/17950)
- [17718](https://github.com/opensearch-project/OpenSearch/pull/17718)
- [17768](https://github.com/opensearch-project/OpenSearch/pull/17768)
- [17490](https://github.com/opensearch-project/OpenSearch/pull/17490)
- [17513](https://github.com/opensearch-project/OpenSearch/pull/17513)
- [17711](https://github.com/opensearch-project/OpenSearch/pull/17711)
- [17730](https://github.com/opensearch-project/OpenSearch/pull/17730)
- [17769](https://github.com/opensearch-project/OpenSearch/pull/17769)
- [17771](https://github.com/opensearch-project/OpenSearch/pull/17771)
- [17792](https://github.com/opensearch-project/OpenSearch/pull/17792)
- [17817](https://github.com/opensearch-project/OpenSearch/pull/17817)
- [18119](https://github.com/opensearch-project/OpenSearch/pull/18119)
- [17753](https://github.com/opensearch-project/OpenSearch/pull/17753)
- [17901](https://github.com/opensearch-project/OpenSearch/pull/17901)
- [16731](https://github.com/opensearch-project/OpenSearch/pull/16731)
- [17273](https://github.com/opensearch-project/OpenSearch/pull/17273)
- [17299](https://github.com/opensearch-project/OpenSearch/pull/17299)
- [17336](https://github.com/opensearch-project/OpenSearch/pull/17336)
- [17344](https://github.com/opensearch-project/OpenSearch/pull/17344)
- [17365](https://github.com/opensearch-project/OpenSearch/pull/17365)
- [17447](https://github.com/opensearch-project/OpenSearch/pull/17447)
- [17457](https://github.com/opensearch-project/OpenSearch/pull/17457)
- [17521](https://github.com/opensearch-project/OpenSearch/pull/17521)
- [17535](https://github.com/opensearch-project/OpenSearch/pull/17535)
- [17559](https://github.com/opensearch-project/OpenSearch/pull/17559)
- [17575](https://github.com/opensearch-project/OpenSearch/pull/17575)
- [17607](https://github.com/opensearch-project/OpenSearch/pull/17607)
- [17611](https://github.com/opensearch-project/OpenSearch/pull/17611)
- [17612](https://github.com/opensearch-project/OpenSearch/pull/17612)
- [17622](https://github.com/opensearch-project/OpenSearch/pull/17622)
- [17631](https://github.com/opensearch-project/OpenSearch/pull/17631)
- [17663](https://github.com/opensearch-project/OpenSearch/pull/17663)
- [17670](https://github.com/opensearch-project/OpenSearch/pull/17670)
- [17699](https://github.com/opensearch-project/OpenSearch/pull/17699)
- [17712](https://github.com/opensearch-project/OpenSearch/pull/17712)
- [17756](https://github.com/opensearch-project/OpenSearch/pull/17756)
- [17774](https://github.com/opensearch-project/OpenSearch/pull/17774)
- [17791](https://github.com/opensearch-project/OpenSearch/pull/17791)
- [17796](https://github.com/opensearch-project/OpenSearch/pull/17796)
- [17843](https://github.com/opensearch-project/OpenSearch/pull/17843)
- [17849](https://github.com/opensearch-project/OpenSearch/pull/17849)
- [17855](https://github.com/opensearch-project/OpenSearch/pull/17855)
- [17868](https://github.com/opensearch-project/OpenSearch/pull/17868)
- [17893](https://github.com/opensearch-project/OpenSearch/pull/17893)
- [17894](https://github.com/opensearch-project/OpenSearch/pull/17894)
- [17910](https://github.com/opensearch-project/OpenSearch/pull/17910)
- [17912](https://github.com/opensearch-project/OpenSearch/pull/17912)
- [17917](https://github.com/opensearch-project/OpenSearch/pull/17917)
- [17922](https://github.com/opensearch-project/OpenSearch/pull/17922)
- [17961](https://github.com/opensearch-project/OpenSearch/pull/17961)
- [17978](https://github.com/opensearch-project/OpenSearch/pull/17978)
- [17987](https://github.com/opensearch-project/OpenSearch/pull/17987)
- [17989](https://github.com/opensearch-project/OpenSearch/pull/17989)
- [18006](https://github.com/opensearch-project/OpenSearch/pull/18006)
- [18043](https://github.com/opensearch-project/OpenSearch/pull/18043)
- [18047](https://github.com/opensearch-project/OpenSearch/pull/18047)
- [18049](https://github.com/opensearch-project/OpenSearch/pull/18049)
- [18054](https://github.com/opensearch-project/OpenSearch/pull/18054)
- [18067](https://github.com/opensearch-project/OpenSearch/pull/18067)
- [18075](https://github.com/opensearch-project/OpenSearch/pull/18075)
- [18085](https://github.com/opensearch-project/OpenSearch/pull/18085)
- [18088](https://github.com/opensearch-project/OpenSearch/pull/18088)
- [18093](https://github.com/opensearch-project/OpenSearch/pull/18093)
- [18097](https://github.com/opensearch-project/OpenSearch/pull/18097)
- [18103](https://github.com/opensearch-project/OpenSearch/pull/18103)
- [18134](https://github.com/opensearch-project/OpenSearch/pull/18134)
- [18145](https://github.com/opensearch-project/OpenSearch/pull/18145)
- [18148](https://github.com/opensearch-project/OpenSearch/pull/18148)
- [18161](https://github.com/opensearch-project/OpenSearch/pull/18161)
- [18163](https://github.com/opensearch-project/OpenSearch/pull/18163)
- [18166](https://github.com/opensearch-project/OpenSearch/pull/18166)
- [18218](https://github.com/opensearch-project/OpenSearch/pull/18218)
- [18243](https://github.com/opensearch-project/OpenSearch/pull/18243)
- [18247](https://github.com/opensearch-project/OpenSearch/pull/18247)
- [12982](https://github.com/opensearch-project/OpenSearch/pull/12982)
- [13568](https://github.com/opensearch-project/OpenSearch/pull/13568)
- [14512](https://github.com/opensearch-project/OpenSearch/pull/14512)
- [15181](https://github.com/opensearch-project/OpenSearch/pull/15181)
- [16178](https://github.com/opensearch-project/OpenSearch/pull/16178)
- [16670](https://github.com/opensearch-project/OpenSearch/pull/16670)
- [17926](https://github.com/opensearch-project/OpenSearch/pull/17926)
- [17927](https://github.com/opensearch-project/OpenSearch/pull/17927)
- [17942](https://github.com/opensearch-project/OpenSearch/pull/17942)
- [17953](https://github.com/opensearch-project/OpenSearch/pull/17953)
- [9151](https://github.com/opensearch-project/OpenSearch/pull/9151)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by nomoa**
The Default aws client might create its own ScheduledExecutorService which is closed via ExecutorService.shutdown() when the client is closed. Calling shutdown might not ensure that all threads are gone when ThreadLeakControl is ran.
Provide our own ScheduledExecutorService during this test so that it runs thrown our tearDown method which calls ThreadPool#terminate waiting for 5 seconds.

### Description
Seen in build https://build.ci.opensearch.org/job/gradle-check/57676/:
```
  2> May 05, 2025 12:38:10 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> WARNING: Will linger awaiting termination of 2 leaked thread(s).
  2> May 05, 2025 12:38:16 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> SEVERE: 1 thread leaked from SUITE scope at org.opensearch.repositories.s3.S3BlobContainerRetriesTests: 
  2>    1) Thread[id=99, name=sdk-ScheduledExecutor-4-0, state=TIMED_WAITING, group=TGRP-S3BlobContainerRetriesTests]
  2>         at java.****/jdk.internal.misc.Unsafe.park(Native Method)
  2>         at java.****/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
  2>         at java.****/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1763)
  2>         at java.****/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
  2>         at java.****/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
  2>         at java.****/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
  2>         at java.****/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  2>         at java.****/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  2>         at java.****/java.lang.Thread.run(Thread.java:1583)
  2> May 05, 2025 12:38:16 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
```

I believe the only thread remaining from a ScheduledThreadPoolExecutor should be the ones created by the default s3 client.

### Related Issues
Resolves #17551

### Check List
- ~~[ ] Functionality includes testing.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by andrross** [comment]
Thanks for looking into this @nomoa!

I shared some findings here: https://github.com/opensearch-project/OpenSearch/issues/17551#issuecomment-2840219916. It's true that ExecutorService.shutdown() won't ensure all threads are stopped when it returns, but the leak control logic seems to wait 5 seconds, then forcibly interrupt the running threads, waits 3 more seconds, and only then fails the test. I think if the client had actually been closed, then waiting/interrupting would have succeeded in stopping the threads. The only way I can explain this behavior is if we're somehow leaking a client and not closing it. What do you think? Am I missing something here?

Also I'm going to close #17540 in favor of #17551 so that we don't have duplicate issues.

**Comment by nomoa** [comment]
@andrross thanks for taking a look at this PR!
It hadn't occurred to me to look what's happening in [ThreadLeakControl](https://github.com/randomizedtesting/randomizedtesting/blob/release/2.7.1/randomized-runner/src/main/java/com/carrotsearch/randomizedtesting/ThreadLeakControl.java#L578). What I understand from it is that indeed it will wait for 5000 (`@ThreadLeakLingering(linger = 5000)` annotation on `OpenSearchTestCase`) and because of `@ThreadLeakAction({Action.WARN, Action.INTERRUPT})` on `LuceneTestCase` it will attempt to interrupt and warn about the leaked threads.
The reason I believe it does not work is that `ExecutorService` threads are immune to `Thread#interrupt()`, probably because that these threads might run user code that can be interrupted and the outer loop (fetching tasks) cannot distinguish an interruption that's meant to stop the user process or meant to stop the executor service.
Simple test case showing that you cannot stop an execution service thread using interrupt:
```java
        Collection<Thread> threads = Collections.synchronizedCollection(new ArrayList<>());
        ThreadFactory factory = new ThreadFactory() {
            @Override
            public Thread newThread(Runnable runnable) {
                Thread thread = new Thread(runnable);
                threads.add(thread);
                return thread;
            }
        };
        ScheduledExecutorService service = Executors.newScheduledThreadPool(1, factory);
        service.execute(() -> {});
        while (threads.isEmpty()) {
            Thread.sleep(10);
        }
        System.out.println("Thread started");
        while (true) {
            boolean oneAlive = false;
            for (Thread t: threads) {
                System.out.println("Interrupting thread " + t.getName() + " is alive: " + t.isAlive());
                t.interrupt();
                t.join(100);
                oneAlive |= t.isAlive();
            }
            if (!oneAlive) {
                break;
            }
        }
        System.out.println("Never end");
```
So relying on `Thread#interrupt` in `ThreadLeakControl` to take care of leaked threads from an ExecutorService does not work.

My initial assumption (the one implemented in this PR) is that the default SDK client simply runs `#shutdown()` on client close and any scheduled tasks will have to be run/cancelled before the scheduler actually stops its threads.
I thought that possibly some tasks got scheduled and the scheduler did not have time to gracefully shutdown in the 5s grace time allowed by `ThreadLeakControl`.

On further look while still theoretically possible I'm not sure that's what happening, if that's the case this PR would have to be adapted to do the same on `S3AsyncService`.

The other possibility is that a client simply gets leaked and its executor service is never shutdown.

Possible reasons I can think of could be:
* race & improper ref counting in `AmazonAsyncS3Reference` causing the `client.close` to never happen (from S3AsyncService)
* a client is leaked in the `client()` method from S3Service and/or S3AsyncService
* A client reference is not closed by its user (not used with a try-with-ressource block?)

**Comment by andrross** [comment]
> My initial assumption (the one implemented in this PR) is that the default SDK client simply runs #shutdown() on client close and any scheduled tasks will have to be run/cancelled before the scheduler actually stops its threads.

Ah, I think you might be right. I though that `ExecutorService::shutdown` would cancel any scheduled-but-not-yet-started tasks, but that is not the case (`shutdownNow()` does that). If the AWS SDK were submitting a scheduled task more than about 8 seconds in the future right before the test finishes, then I think it would explain the behavior we're seeing. It would also explain the flakiness because the timing might have to line up just right for that task to get scheduled and then not finish.

**Comment by nomoa** [comment]
The last version of this PR is applying the same strategy for both S3Service & S3AsyncService based on the assumption that the leaked threads are coming from the clients own ScheduledExecutorService that is not able to shutdown in due time because some scheduled tasks are still waiting to be run/cancelled.
I was hoping to find ways to detect if a client was leaked (which is also a reason why this test might fail on ThreadLeakControl) but unfortunately was not able to do so.
Please let me know what you think. Also, please feel free to close this PR if you believe this is headed in the wrong direction.

File: plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java [hunk 1]
```diff
@@ -130,15 +130,15 @@ public class S3BlobContainerRetriesTests extends AbstractBlobContainerRetriesTes
...
+        scheduler = new ScheduledThreadPoolExecutor(1);
+        service = new S3Service(configPath(), scheduler);
+        asyncService = new S3AsyncService(configPath(), scheduler);
 
         futureCompletionService = Executors.newSingleThreadExecutor();
         streamReaderService = Executors.newSingleThreadExecutor();
         transferNIOGroup = new AsyncTransferEventLoopGroup(1);
         remoteTransferRetry = Executors.newFixedThreadPool(20);
         transferQueueConsumerService = Executors.newFixedThreadPool(2);
-        scheduler = new ScheduledThreadPoolExecutor(1);
```
Comment (andrross) [inline plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java:141]: This `scheduler` field was previously unused, right?

File: plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java [hunk 2]
```diff
@@ -243,8 +257,12 @@ static ClientOverrideConfiguration buildOverrideConfiguration(final S3ClientSett
                 )
                 .build()
         );
+        ClientOverrideConfiguration.Builder builder = ClientOverrideConfiguration.builder();
+        if (scheduledExecutorService != null) {
+            builder = builder.scheduledExecutorService(scheduledExecutorService);
+        }
 
-        return ClientOverrideConfiguration.builder()
+        return builder.scheduledExecutorService(scheduledExecutorService)
```
Comment (andrross) [inline plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java:265]: You conditionally call `.scheduledExecutorService(scheduledExecutorService)` above. I think this should not be here?

Comment (nomoa) [reply plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java:265]: indeed, thanks for catching this, fixing

File: plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java (hunk 1 above)
Comment (nomoa) [reply plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java:141]: it's still being used but got moved to the beginning of the method

**Review by nomoa — COMMENTED** [review]
thanks for the review!

File: plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java (hunk 1 above)
Comment (nomoa) [reply plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java:141]: actually you're right it was not being used before this patch, unsure what was the intent behind it

**Review by andrross — APPROVED** [review]
