### PR TITLE
Adding a null pointer check to fix index_prefix query

### LINKED ISSUE #2826: [BUG] NPE happens on short prefix query on a field with `index_prefixes`
**Describe the bug**
( `index_prefixes` is not documented in OpenSearch’s documentation but AFAIK OpenSearch is compatible with ElasticSearch 7.10, which has [index_prefixes](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/index-prefixes.html) parameter.)

When a `prefix` query run on a field with `index_prefixes`, if the length of characters in the query is [`min_chars` of the `index_prefixes` option] - 1, an error is responded.
The root cause seems to be NullPointerException.

**To Reproduce**
1. Create an index which has a field with `index_prefixes` option; its `min_chars` is implicitly 2.
```
PUT test
{
  "mappings": {
    "properties": {
      "t": {
        "type": "text",
        "index_prefixes": {}
      }
    }
  }
}
```

2. Search by `prefix` query with one character on the field.
```
GET test/_search
{"query":{"prefix":{"t": "a"}}}
```

3. An error is responded. It says the root cause is NullPointerException.
```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "failed to create query: Cannot invoke \"Object.hashCode()\" because \"this.rewriteMethod\" is null",
        "index" : "test",
        "index_uuid" : "XPqfSP1xT7WJt9Sxzt65qg"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "test",
        "node" : "QA35rulpSza20Wsx6rNSEg",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "failed to create query: Cannot invoke \"Object.hashCode()\" because \"this.rewriteMethod\" is null",
          "index" : "test",
          "index_uuid" : "XPqfSP1xT7WJt9Sxzt65qg",
          "caused_by" : {
            "type" : "null_pointer_exception",
            "reason" : "Cannot invoke \"Object.hashCode()\" because \"this.rewriteMethod\" is null"
          }
        }
      }
    ]
  },
  "status" : 400
}
```

4. simple_query_string also fails.
```
# fails with the same error
GET test/_search
{"query":{"simple_query_string":{"fields":["t"], "query":"a*"}}}
```

**Expected behavior**
Run without errors. I know it is not efficient.

A similar `query_string` runs without any errors.
```
GET test/_search
{"query":{"query_string":{"fields":["t"], "query":"a*"}}}
```

I tried some patterns (`min_chars` = 2, 3, 5), and it seems that the prefix query with characters the length of which is `min_chars` - 1 fails. When the length is less than `min_chars` - 1, the query succeeds.

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - Version: 1.3.1

**Additional context**

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha Shah <vachshah@amazon.com>

### Description
When the length of the query prefix is = minChars-1, the code follows the path in TextFieldMapper and throws an NPE [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java#L586). Adding a null check for the method, the query returns a result without an NPE now:

```
curl -XPUT localhost:9200/test --data '{                                                                             
"mappings": {
    "properties": {
      "t": {
        "type": "text",
        "index_prefixes": { "min_chars": "3" }
      }
    }
  }
}' -H "Content-Type:Application/json"
{{"acknowledged":true,"shards_acknowledged":true,"index":"test"}
```
```
curl 'localhost:9200/test/_search?pretty' --data '{"query":{"prefix":{"t": "st"}}}' -H "Content-Type:Application/json"
{
  "took" : 9,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

Tested with various scenarios mentioned in the issue. Adding the details in the comments of this PR.
 
### Issues Resolved
#2826 
 
### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VachaShah** [comment]
**For index `test` with `minChars=3` for `index_prefixes`:**

```
curl -XPUT localhost:9200/test --data '{                                                                             
"mappings": {
    "properties": {
      "t": {
        "type": "text",
        "index_prefixes": { "min_chars": "3" }
      }
    }
  }
}' -H "Content-Type:Application/json"
{{"acknowledged":true,"shards_acknowledged":true,"index":"test"}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test/_search?pretty' --data '{"query":{"prefix":{"t": ""}}}' -H "Content-Type:Application/json"                                                             
{
  "took" : 38,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test/_search?pretty' --data '{"query":{"prefix":{"t": "s"}}}' -H "Content-Type:Application/json"
{
  "took" : 5,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test/_search?pretty' --data '{"query":{"prefix":{"t": "st"}}}' -H "Content-Type:Application/json"
{
  "took" : 9,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test/_search?pretty' --data '{"query":{"prefix":{"t": "str"}}}' -H "Content-Type:Application/json"
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

**For index `test-2` with `minChars=2` for `index_prefixes`:**

```
curl -XPUT localhost:9200/test-2 --data '{                                                                             
"mappings": {
    "properties": {
      "t": {
        "type": "text",
        "index_prefixes": { "min_chars": "2" }
      }
    }
  }
}' -H "Content-Type:Application/json"
{"acknowledged":true,"shards_acknowledged":true,"index":"test-2"}ubuntu@ip-172-31-51-78:~$ 
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test-2/_search?pretty' --data '{"query":{"prefix":{"t": ""}}}' -H "Content-Type:Application/json"
{
  "took" : 36,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test-2/_search?pretty' --data '{"query":{"prefix":{"t": "s"}}}' -H "Content-Type:Application/json"
{
  "took" : 10,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test-2/_search?pretty' --data '{"query":{"prefix":{"t": "st"}}}' -H "Content-Type:Application/json"
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test-2/_search?pretty' --data '{"query":{"prefix":{"t": "str"}}}' -H "Content-Type:Application/json"
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

**For index `test` with `minChars=5` for `index_prefixes`:**

```
curl -XPUT localhost:9200/test-3 --data '{                                                                             
"mappings": {
    "properties": {
      "t": {
        "type": "text",
        "index_prefixes": { "min_chars": "5" }
      }
    }
  }
}' -H "Content-Type:Application/json"
{"acknowledged":true,"shards_acknowledged":true,"index":"test-3"}ubuntu@ip-172-31-51-78:~$ 
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test-3/_search?pretty' --data '{"query":{"prefix":{"t": ""}}}' -H "Content-Type:Application/json"
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test-3/_search?pretty' --data '{"query":{"prefix":{"t": "s"}}}' -H "Content-Type:Application/json"
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test-3/_search?pretty' --data '{"query":{"prefix":{"t": "st"}}}' -H "Content-Type:Application/json"
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test-3/_search?pretty' --data '{"query":{"prefix":{"t": "str"}}}' -H "Content-Type:Application/json"
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test-3/_search?pretty' --data '{"query":{"prefix":{"t": "strt"}}}' -H "Content-Type:Application/json"
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
ubuntu@ip-172-31-51-78:~$ curl 'localhost:9200/test-3/_search?pretty' --data '{"query":{"prefix":{"t": "strtt"}}}' -H "Content-Type:Application/json"
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

File: server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java [hunk 1]
```diff
@@ -583,7 +583,9 @@ public Query prefixQuery(String value, MultiTermQuery.RewriteMethod method, bool
             }
             Automaton automaton = Operations.concatenate(automata);
             AutomatonQuery query = new AutomatonQuery(new Term(name(), value + "*"), automaton);
-            query.setRewriteMethod(method);
+            if (method != null) {
```
Comment (saratvemulapalli) [inline server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java:586]: This approach solves the problem but the real root cause is the check for min, max chars. 
The right fix here is to not accept (on line #562) the query if the len is less than `min_chars`. 

```suggestion
        boolean accept(int length) {
            return length >= minChars && length <= maxChars;
        }
```

**Review by saratvemulapalli — COMMENTED** [review]
You are faster than me :)
Thanks for taking care of this. 

I think the right fix is to take care of the acceptance check.
Also could you add tests to make sure it doesn't fail?

File: server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java (hunk 1 above)
Comment (VachaShah) [reply server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java:586]: Oh I didn't know we should not be accepting the value less than minChars. I will make that change and add tests as well.

Comment (saratvemulapalli) [reply server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java:586]: Also take a look at: https://github.com/opensearch-project/OpenSearch/commit/dd540ef6180b8838c79aad31efc69e4ad1e2b5f8. 
There might be other cases which might fail.

Comment (VachaShah) [reply server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java:586]: Looks like the support for minChars - 1 was specifically added. Would the fix in this PR then be the solution since it changes the behavior if we don't accept the minChars - 1 length?

Comment (VachaShah) [reply server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java:586]: From the commit, the operation for the index_prefix query for length = minChars-1 is remapped to a? from a* to make it less expensive. Also, looking at the current code base, I see that the setRewriteMethod is wrapped by a null check at other places: for example https://github.com/opensearch-project/OpenSearch/blame/3c5d997a765e24ffa32d35219fd5026cfb143a9d/server/src/main/java/org/opensearch/index/mapper/StringFieldType.java#L116.

Comment (saratvemulapalli) [reply server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java:586]: Thanks Vacha for this. 
I take back my suggestion, as its probably not supporting the optimization in performance.
I agree with you that, verifying the method being `null` solves the problem while being efficient.

Could you add some tests and we should be good to go.

Comment (dblock) [reply server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java:586]: Also, is `query.setRewriteMethod(null)` a valid thing by itself? Can the rewrite method be `null`? If not throw in an `assert` or something like that to prevent hiding other errors.

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
Looks good to me. Thanks @VachaShah !

File: server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java [hunk 2]
```diff
@@ -583,7 +583,9 @@ public Query prefixQuery(String value, MultiTermQuery.RewriteMethod method, bool
...
+                query.setRewriteMethod(method);
```
Comment (nknize) [inline server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java:587]: `query.setRewriteMethod` is [removed in Lucene 9.2](https://github.com/apache/lucene/pull/726). I've [opened an issue](https://github.com/opensearch-project/OpenSearch/issues/2896) to remove all references to the method and use [`CONSTANT_SCORE_REWRITE`](https://github.com/apache/lucene/blob/e6fb74f9090db2bc274af94c17d80739697bdc01/lucene/core/src/java/org/apache/lucene/search/MultiTermQuery.java#L81) in places where `null` is passed in as the `method` parameter.

**Review by nknize — APPROVED** [review]
I'm fine approving and merging this PR to fix the immediate bug but we should open a follow-up PR for #2896. Let us know if you'd like to take care of that as well @VachaShah

**Comment by VachaShah** [comment]
> I'm fine approving and merging this PR to fix the immediate bug but we should open a follow-up PR for #2896. Let us know if you'd like to take care of that as well @VachaShah

Thanks @nknize! Sure I can take care of that.

File: server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java (hunk 1 above)
Comment (VachaShah) [reply server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java:586]: `null` looks to be valid, also @nknize opened an issue #2896 to remove these usages next since the method is deprecated.
