### PR TITLE
Attempt to fix ThreadLeakControl issues in S3BlobStoreRepositoryTests

### LINKED ISSUE #14299: [AUTOCUT] Gradle Check Flaky Test Report for S3BlobStoreRepositoryTests
## Flaky Test Report for `S3BlobStoreRepositoryTests`

Noticed the `S3BlobStoreRepositoryTests` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| cf628bb1df9c756c5045ad06c8baeb20ce3556e4 | [16452](https://github.com/opensearch-project/OpenSearch/pull/16452) | [50013](https://build.ci.opensearch.org/job/gradle-check/50013/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testSnapshotWithLargeSegmentFiles` |
| c3325064d44d86a876c4960834c1eed44361189f | [17591](https://github.com/opensearch-project/OpenSearch/pull/17591) | [54632](https://build.ci.opensearch.org/job/gradle-check/54632/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testSnapshotAndRestore` |
| fe0284715d17a00ac8567e800230ae18fcf11cc7 | [17043](https://github.com/opensearch-project/OpenSearch/pull/17043) | [52290](https://build.ci.opensearch.org/job/gradle-check/52290/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testSnapshotAndRestore` |
| 36d798cc42c473bdb49f4bf39093dd3dd9191b70 | [16445](https://github.com/opensearch-project/OpenSearch/pull/16445) | [54685](https://build.ci.opensearch.org/job/gradle-check/54685/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testSnapshotAndRestore` |
| f7aca63337abfbb51be5a47a4e5fe81b443258b0 | [17571](https://github.com/opensearch-project/OpenSearch/pull/17571) | [54440](https://build.ci.opensearch.org/job/gradle-check/54440/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testSnapshotAndRestore` |
| d835bca46f22d68508c3ca1c4507359d157afc79 | [17925](https://github.com/opensearch-project/OpenSearch/pull/17925) | [56863](https://build.ci.opensearch.org/job/gradle-check/56863/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testSnapshotAndRestore` |
| 32e3effee75076b21c0fd846c3a7dd5a633a8b71 | [17793](https://github.com/opensearch-project/OpenSearch/pull/17793) | [55608](https://build.ci.opensearch.org/job/gradle-check/55608/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testSnapshotAndRestore` |
| 5e1273793480b6c50a74e84ceb4a7d682b9b5542 | [17039](https://github.com/opensearch-project/OpenSearch/pull/17039) | [52759](https://build.ci.opensearch.org/job/gradle-check/52759/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testSnapshotAndRestore` |
| 931c1aadaed0d8eccee0839d74d706fb47dbd4be | [17080](https://github.com/opensearch-project/OpenSearch/pull/17080) | [52544](https://build.ci.opensearch.org/job/gradle-check/52544/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testSnapshotAndRestore` |
| 9bc536d82da7a2cc1750320c4ad8ce7bf54cd89c | [14036](https://github.com/opensearch-project/OpenSearch/pull/14036) | [40018](https://build.ci.opensearch.org/job/gradle-check/40018/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testDeleteBlobs`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testMultipleSnapshotAndRollback`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testReadRange`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testRequestStats`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testSnapshotAndRestore`<br><br>`org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testWriteRead` |
| 45360db1bcef97ae363463d1295a71332e31aef2 | [13850](https://github.com/opensearch-project/OpenSearch/pull/13850) | [39341](https://build.ci.opensearch.org/job/gradle-check/39341/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testRequestStats` |
| 59043524466b9d3354bd43bb21b7d32ce4c7c311 | [18250](https://github.com/opensearch-project/OpenSearch/pull/18250) | [57976](https://build.ci.opensearch.org/job/gradle-check/57976/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 5cde176918744b9640d2ef84cf9ede4226950cea | [13814](https://github.com/opensearch-project/OpenSearch/pull/13814) | [39246](https://build.ci.opensearch.org/job/gradle-check/39246/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testRequestStats` |
| 983297289325bdd1c832bfe18d105bd3e9727ab5 | [13860](https://github.com/opensearch-project/OpenSearch/pull/13860) | [39395](https://build.ci.opensearch.org/job/gradle-check/39395/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testRequestStats` |
| 994bfae0c0beddd8416ab88ed6138e2792638c4e | [13842](https://github.com/opensearch-project/OpenSearch/pull/13842) | [39305](https://build.ci.opensearch.org/job/gradle-check/39305/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testRequestStats` |
| b9befaa12524744ffe71d3f12699cb27cb8fca5e | [13131](https://github.com/opensearch-project/OpenSearch/pull/13131) | [39377](https://build.ci.opensearch.org/job/gradle-check/39377/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testRequestStats` |
| 032f4095cf797059e718d74fd2d337d95f8a09a9 | [17714](https://github.com/opensearch-project/OpenSearch/pull/17714) | [56112](https://build.ci.opensearch.org/job/gradle-check/56112/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 087e4735fbd4644957df29fc9cab074bcaafefca | [17857](https://github.com/opensearch-project/OpenSearch/pull/17857) | [55995](https://build.ci.opensearch.org/job/gradle-check/55995/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 08dc95ee1bd7af3f02dc9e11892bcd624208257f | [17507](https://github.com/opensearch-project/OpenSearch/pull/17507) | [54857](https://build.ci.opensearch.org/job/gradle-check/54857/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 0aea92ba7fb7d57b51b7b9c03ac3105a46f5f887 | [18159](https://github.com/opensearch-project/OpenSearch/pull/18159) | [57606](https://build.ci.opensearch.org/job/gradle-check/57606/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 18b0d1c7dbb756e52274cad2098664bdef7cacc5 | [17861](https://github.com/opensearch-project/OpenSearch/pull/17861) | [55981](https://build.ci.opensearch.org/job/gradle-check/55981/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 20d56d2e4b8e383e997ee1321d1903de95d6e8bd | [18304](https://github.com/opensearch-project/OpenSearch/pull/18304) | [58134](https://build.ci.opensearch.org/job/gradle-check/58134/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 379e4643fe13740f6ef7075de98de53fe05902c8 | [18194](https://github.com/opensearch-project/OpenSearch/pull/18194) | [57705](https://build.ci.opensearch.org/job/gradle-check/57705/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 3a7d8fa465641bb1f5f5c58075ffbc9fefc8aceb | [17976](https://github.com/opensearch-project/OpenSearch/pull/17976) | [56634](https://build.ci.opensearch.org/job/gradle-check/56634/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 3c3d380e267f6ed12de8cf30fce42fa48d25f89a | [18072](https://github.com/opensearch-project/OpenSearch/pull/18072) | [57136](https://build.ci.opensearch.org/job/gradle-check/57136/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 3fb09c770a4359a90d0cc7e88b64c898101fd6c0 | [17690](https://github.com/opensearch-project/OpenSearch/pull/17690) | [55006](https://build.ci.opensearch.org/job/gradle-check/55006/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 436038d2be54df8979466841fccc6db4971bcb75 | [18041](https://github.com/opensearch-project/OpenSearch/pull/18041) | [56989](https://build.ci.opensearch.org/job/gradle-check/56989/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 4c76c1da1983cb8e04f0cf1769deac0ee57f7666 | [18027](https://github.com/opensearch-project/OpenSearch/pull/18027) | [57085](https://build.ci.opensearch.org/job/gradle-check/57085/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 557ea3a7117d8ccbe8bb7735c4663a0611d2b355 | [18269](https://github.com/opensearch-project/OpenSearch/pull/18269) | [58149](https://build.ci.opensearch.org/job/gradle-check/58149/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 5d308e084d8e9b26fe5e33178f2d7db4faed0baf | [18067](https://github.com/opensearch-project/OpenSearch/pull/18067) | [57240](https://build.ci.opensearch.org/job/gradle-check/57240/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 6ff44d9b5e1f1f6f22b9935d21e408957383e940 | [17908](https://github.com/opensearch-project/OpenSearch/pull/17908) | [56245](https://build.ci.opensearch.org/job/gradle-check/56245/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 70e890a978cebbe2eae206f7ddd97c4bad0f1ce6 | [17989](https://github.com/opensearch-project/OpenSearch/pull/17989) | [57723](https://build.ci.opensearch.org/job/gradle-check/57723/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 8948c1fda4b2d7287f921cc8cb0d519aaf4072ab | [18018](https://github.com/opensearch-project/OpenSearch/pull/18018) | [57124](https://build.ci.opensearch.org/job/gradle-check/57124/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 8a847f22a157f3cc1d8d851f04d9f7326a70cc78 | [18301](https://github.com/opensearch-project/OpenSearch/pull/18301) | [58128](https://build.ci.opensearch.org/job/gradle-check/58128/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| 96481ccadb8e7fd40fac3dd09629bd00b2bf5c94 | [17782](https://github.com/opensearch-project/OpenSearch/pull/17782) | [56747](https://build.ci.opensearch.org/job/gradle-check/56747/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| b34b8cba4bf9d6e6326368dc1617d5bce8c65a9f | [17460](https://github.com/opensearch-project/OpenSearch/pull/17460) | [54911](https://build.ci.opensearch.org/job/gradle-check/54911/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| b9046eb3df6adbfe6d2a355bb85eaa34ddc68f20 | [17953](https://github.com/opensearch-project/OpenSearch/pull/17953) | [56830](https://build.ci.opensearch.org/job/gradle-check/56830/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| bb0dff04b93d5c433d21dde94ccd2a3173f24589 | [18075](https://github.com/opensearch-project/OpenSearch/pull/18075) | [57307](https://build.ci.opensearch.org/job/gradle-check/57307/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| e27cf58335ee9cf0f8b1a5811128732ed4ce6bcb | [17490](https://github.com/opensearch-project/OpenSearch/pull/17490) | [54610](https://build.ci.opensearch.org/job/gradle-check/54610/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |
| e9d8e0007b58f96a89b1a400a14eb2ed9f7aa597 | [17726](https://github.com/opensearch-project/OpenSearch/pull/17726) | [55668](https://build.ci.opensearch.org/job/gradle-check/55668/testReport/) | `org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.classMethod` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `S3BlobStoreRepositoryTests` class are:

- [15426](https://github.com/opensearch-project/OpenSearch/pull/15426)
- [15024](https://github.com/opensearch-project/OpenSearch/pull/15024)
- [16788](https://github.com/opensearch-project/OpenSearch/pull/16788)
- [17299](https://github.com/opensearch-project/OpenSearch/pull/17299)
- [17576](https://github.com/opensearch-project/OpenSearch/pull/17576)
- [17005](https://github.com/opensearch-project/OpenSearch/pull/17005)
- [16988](https://github.com/opensearch-project/OpenSearch/pull/16988)
- [17888](https://github.com/opensearch-project/OpenSearch/pull/17888)
- [13829](https://github.com/opensearch-project/OpenSearch/pull/13829)
- [13853](https://github.com/opensearch-project/OpenSearch/pull/13853)
- [17446](https://github.com/opensearch-project/OpenSearch/pull/17446)
- [17667](https://github.com/opensearch-project/OpenSearch/pull/17667)
- [18069](https://github.com/opensearch-project/OpenSearch/pull/18069)
- [13461](https://github.com/opensearch-project/OpenSearch/pull/13461)
- [15568](https://github.com/opensearch-project/OpenSearch/pull/15568)
- [15621](https://github.com/opensearch-project/OpenSearch/pull/15621)
- [17759](https://github.com/opensearch-project/OpenSearch/pull/17759)
- [17021](https://github.com/opensearch-project/OpenSearch/pull/17021)
- [17225](https://github.com/opensearch-project/OpenSearch/pull/17225)
- [17718](https://github.com/opensearch-project/OpenSearch/pull/17718)
- [16962](https://github.com/opensearch-project/OpenSearch/pull/16962)
- [17575](https://github.com/opensearch-project/OpenSearch/pull/17575)
- [17721](https://github.com/opensearch-project/OpenSearch/pull/17721)
- [17894](https://github.com/opensearch-project/OpenSearch/pull/17894)
- [17912](https://github.com/opensearch-project/OpenSearch/pull/17912)
- [18107](https://github.com/opensearch-project/OpenSearch/pull/18107)
- [18115](https://github.com/opensearch-project/OpenSearch/pull/18115)
- [18166](https://github.com/opensearch-project/OpenSearch/pull/18166)
- [15124](https://github.com/opensearch-project/OpenSearch/pull/15124)
- [17309](https://github.com/opensearch-project/OpenSearch/pull/17309)
- [17880](https://github.com/opensearch-project/OpenSearch/pull/17880)
- [17961](https://github.com/opensearch-project/OpenSearch/pull/17961)
- [17968](https://github.com/opensearch-project/OpenSearch/pull/17968)
- [18167](https://github.com/opensearch-project/OpenSearch/pull/18167)
- [17129](https://github.com/opensearch-project/OpenSearch/pull/17129)
- [17203](https://github.com/opensearch-project/OpenSearch/pull/17203)
- [17228](https://github.com/opensearch-project/OpenSearch/pull/17228)
- [17619](https://github.com/opensearch-project/OpenSearch/pull/17619)
- [17107](https://github.com/opensearch-project/OpenSearch/pull/17107)
- [17212](https://github.com/opensearch-project/OpenSearch/pull/17212)
- [17393](https://github.com/opensearch-project/OpenSearch/pull/17393)
- [18154](https://github.com/opensearch-project/OpenSearch/pull/18154)
- [13772](https://github.com/opensearch-project/OpenSearch/pull/13772)
- [16731](https://github.com/opensearch-project/OpenSearch/pull/16731)
- [17831](https://github.com/opensearch-project/OpenSearch/pull/17831)
- [17699](https://github.com/opensearch-project/OpenSearch/pull/17699)
- [17668](https://github.com/opensearch-project/OpenSearch/pull/17668)
- [17712](https://github.com/opensearch-project/OpenSearch/pull/17712)
- [13577](https://github.com/opensearch-project/OpenSearch/pull/13577)
- [15333](https://github.com/opensearch-project/OpenSearch/pull/15333)
- [15557](https://github.com/opensearch-project/OpenSearch/pull/15557)
- [15769](https://github.com/opensearch-project/OpenSearch/pull/15769)
- [18229](https://github.com/opensearch-project/OpenSearch/pull/18229)
- [14338](https://github.com/opensearch-project/OpenSearch/pull/14338)
- [17817](https://github.com/opensearch-project/OpenSearch/pull/17817)
- [17950](https://github.com/opensearch-project/OpenSearch/pull/17950)
- [12782](https://github.com/opensearch-project/OpenSearch/pull/12782)
- [13367](https://github.com/opensearch-project/OpenSearch/pull/13367)
- [13866](https://github.com/opensearch-project/OpenSearch/pull/13866)
- [13895](https://github.com/opensearch-project/OpenSearch/pull/13895)
- [13896](https://github.com/opensearch-project/OpenSearch/pull/13896)
- [13917](https://github.com/opensearch-project/OpenSearch/pull/13917)
- [17517](https://github.com/opensearch-project/OpenSearch/pull/17517)
- [17631](https://github.com/opensearch-project/OpenSearch/pull/17631)
- [17768](https://github.com/opensearch-project/OpenSearch/pull/17768)
- [17873](https://github.com/opensearch-project/OpenSearch/pull/17873)
- [17890](https://github.com/opensearch-project/OpenSearch/pull/17890)
- [17907](https://github.com/opensearch-project/OpenSearch/pull/17907)
- [17941](https://github.com/opensearch-project/OpenSearch/pull/17941)
- [18003](https://github.com/opensearch-project/OpenSearch/pull/18003)
- [18189](https://github.com/opensearch-project/OpenSearch/pull/18189)
- [18196](https://github.com/opensearch-project/OpenSearch/pull/18196)
- [18309](https://github.com/opensearch-project/OpenSearch/pull/18309)
- [17409](https://github.com/opensearch-project/OpenSearch/pull/17409)
- [16489](https://github.com/opensearch-project/OpenSearch/pull/16489)
- [17275](https://github.com/opensearch-project/OpenSearch/pull/17275)
- [17336](https://github.com/opensearch-project/OpenSearch/pull/17336)
- [17389](https://github.com/opensearch-project/OpenSearch/pull/17389)
- [17447](https://github.com/opensearch-project/OpenSearch/pull/17447)
- [17457](https://github.com/opensearch-project/OpenSearch/pull/17457)
- [17532](https://github.com/opensearch-project/OpenSearch/pull/17532)
- [17546](https://github.com/opensearch-project/OpenSearch/pull/17546)
- [17555](https://github.com/opensearch-project/OpenSearch/pull/17555)
- [17556](https://github.com/opensearch-project/OpenSearch/pull/17556)
- [17565](https://github.com/opensearch-project/OpenSearch/pull/17565)
- [17568](https://github.com/opensearch-project/OpenSearch/pull/17568)
- [17580](https://github.com/opensearch-project/OpenSearch/pull/17580)
- [17583](https://github.com/opensearch-project/OpenSearch/pull/17583)
- [17598](https://github.com/opensearch-project/OpenSearch/pull/17598)
- [17606](https://github.com/opensearch-project/OpenSearch/pull/17606)
- [17615](https://github.com/opensearch-project/OpenSearch/pull/17615)
- [17623](https://github.com/opensearch-project/OpenSearch/pull/17623)
- [17635](https://github.com/opensearch-project/OpenSearch/pull/17635)
- [17643](https://github.com/opensearch-project/OpenSearch/pull/17643)
- [17649](https://github.com/opensearch-project/OpenSearch/pull/17649)
- [17652](https://github.com/opensearch-project/OpenSearch/pull/17652)
- [17682](https://github.com/opensearch-project/OpenSearch/pull/17682)
- [17703](https://github.com/opensearch-project/OpenSearch/pull/17703)
- [17740](https://github.com/opensearch-project/OpenSearch/pull/17740)
- [17749](https://github.com/opensearch-project/OpenSearch/pull/17749)
- [17750](https://github.com/opensearch-project/OpenSearch/pull/17750)
- [17757](https://github.com/opensearch-project/OpenSearch/pull/17757)
- [17764](https://github.com/opensearch-project/OpenSearch/pull/17764)
- [17771](https://github.com/opensearch-project/OpenSearch/pull/17771)
- [17778](https://github.com/opensearch-project/OpenSearch/pull/17778)
- [17792](https://github.com/opensearch-project/OpenSearch/pull/17792)
- [17796](https://github.com/opensearch-project/OpenSearch/pull/17796)
- [17809](https://github.com/opensearch-project/OpenSearch/pull/17809)
- [17843](https://github.com/opensearch-project/OpenSearch/pull/17843)
- [17879](https://github.com/opensearch-project/OpenSearch/pull/17879)
- [17889](https://github.com/opensearch-project/OpenSearch/pull/17889)
- [17893](https://github.com/opensearch-project/OpenSearch/pull/17893)
- [17909](https://github.com/opensearch-project/OpenSearch/pull/17909)
- [17917](https://github.com/opensearch-project/OpenSearch/pull/17917)
- [17918](https://github.com/opensearch-project/OpenSearch/pull/17918)
- [17923](https://github.com/opensearch-project/OpenSearch/pull/17923)
- [17939](https://github.com/opensearch-project/OpenSearch/pull/17939)
- [17969](https://github.com/opensearch-project/OpenSearch/pull/17969)
- [17978](https://github.com/opensearch-project/OpenSearch/pull/17978)
- [17988](https://github.com/opensearch-project/OpenSearch/pull/17988)
- [18042](https://github.com/opensearch-project/OpenSearch/pull/18042)
- [18044](https://github.com/opensearch-project/OpenSearch/pull/18044)
- [18049](https://github.com/opensearch-project/OpenSearch/pull/18049)
- [18054](https://github.com/opensearch-project/OpenSearch/pull/18054)
- [18066](https://github.com/opensearch-project/OpenSearch/pull/18066)
- [18082](https://github.com/opensearch-project/OpenSearch/pull/18082)
- [18085](https://github.com/opensearch-project/OpenSearch/pull/18085)
- [18097](https://github.com/opensearch-project/OpenSearch/pull/18097)
- [18101](https://github.com/opensearch-project/OpenSearch/pull/18101)
- [18102](https://github.com/opensearch-project/OpenSearch/pull/18102)
- [18144](https://github.com/opensearch-project/OpenSearch/pull/18144)
- [18155](https://github.com/opensearch-project/OpenSearch/pull/18155)
- [18161](https://github.com/opensearch-project/OpenSearch/pull/18161)
- [18163](https://github.com/opensearch-project/OpenSearch/pull/18163)
- [18169](https://github.com/opensearch-project/OpenSearch/pull/18169)
- [18230](https://github.com/opensearch-project/OpenSearch/pull/18230)
- [18254](https://github.com/opensearch-project/OpenSearch/pull/18254)
- [18255](https://github.com/opensearch-project/OpenSearch/pull/18255)
- [18256](https://github.com/opensearch-project/OpenSearch/pull/18256)
- [18272](https://github.com/opensearch-project/OpenSearch/pull/18272)
- [18280](https://github.com/opensearch-project/OpenSearch/pull/18280)
- [18288](https://github.com/opensearch-project/OpenSearch/pull/18288)
- [18299](https://github.com/opensearch-project/OpenSearch/pull/18299)
- [18300](https://github.com/opensearch-project/OpenSearch/pull/18300)
- [18316](https://github.com/opensearch-project/OpenSearch/pull/18316)
- [18330](https://github.com/opensearch-project/OpenSearch/pull/18330)
- [16989](https://github.com/opensearch-project/OpenSearch/pull/16989)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### LINKED ISSUE #17551: [AUTOCUT] Gradle Check Flaky Test Report for S3BlobContainerRetriesTests
## Flaky Test Report for `S3BlobContainerRetriesTests`

Noticed the `S3BlobContainerRetriesTests` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| 1294506439e8ea64bb4e02ba5bc16b4446a05292 | [18061](https://github.com/opensearch-project/OpenSearch/pull/18061) | [57060](https://build.ci.opensearch.org/job/gradle-check/57060/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| 47f9bdb98418ab1eb08d6774d4c7bca0865459ef | [18165](https://github.com/opensearch-project/OpenSearch/pull/18165) | [57479](https://build.ci.opensearch.org/job/gradle-check/57479/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| 60aa7a51c56c4b9fb83012b0c404a959f9e7c4cc | [18212](https://github.com/opensearch-project/OpenSearch/pull/18212) | [57844](https://build.ci.opensearch.org/job/gradle-check/57844/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| 6719b1f52bc949c38a247725d61702c26f37b215 | [18057](https://github.com/opensearch-project/OpenSearch/pull/18057) | [57116](https://build.ci.opensearch.org/job/gradle-check/57116/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| 816787d3e58d3f843207e77b6cb8eb99cd3512da | [18044](https://github.com/opensearch-project/OpenSearch/pull/18044) | [57010](https://build.ci.opensearch.org/job/gradle-check/57010/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| 8964f63653fadd5363267e0ef2edf2dd7bfe0105 | [17873](https://github.com/opensearch-project/OpenSearch/pull/17873) | [56048](https://build.ci.opensearch.org/job/gradle-check/56048/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| cc82be9cda7414f919cf64a52880135c2f4937f0 | [17515](https://github.com/opensearch-project/OpenSearch/pull/17515) | [54208](https://build.ci.opensearch.org/job/gradle-check/54208/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| e0a67fd9ca949b14b90dc206231d90158bc35b38 | [17674](https://github.com/opensearch-project/OpenSearch/pull/17674) | [55181](https://build.ci.opensearch.org/job/gradle-check/55181/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| fc78200cd33121c2a7f52250b19816870495dc26 | [17732](https://github.com/opensearch-project/OpenSearch/pull/17732) | [55229](https://build.ci.opensearch.org/job/gradle-check/55229/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |
| fcb0649b14536889a6f4c28197cf485c33dfff5e | [17668](https://github.com/opensearch-project/OpenSearch/pull/17668) | [54996](https://build.ci.opensearch.org/job/gradle-check/54996/testReport/) | `org.opensearch.repositories.s3.S3BlobContainerRetriesTests.classMethod` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `S3BlobContainerRetriesTests` class are:

- [17950](https://github.com/opensearch-project/OpenSearch/pull/17950)
- [17718](https://github.com/opensearch-project/OpenSearch/pull/17718)
- [17768](https://github.com/opensearch-project/OpenSearch/pull/17768)
- [17490](https://github.com/opensearch-project/OpenSearch/pull/17490)
- [17513](https://github.com/opensearch-project/OpenSearch/pull/17513)
- [17711](https://github.com/opensearch-project/OpenSearch/pull/17711)
- [17730](https://github.com/opensearch-project/OpenSearch/pull/17730)
- [17769](https://github.com/opensearch-project/OpenSearch/pull/17769)
- [17771](https://github.com/opensearch-project/OpenSearch/pull/17771)
- [17792](https://github.com/opensearch-project/OpenSearch/pull/17792)
- [17817](https://github.com/opensearch-project/OpenSearch/pull/17817)
- [18119](https://github.com/opensearch-project/OpenSearch/pull/18119)
- [17753](https://github.com/opensearch-project/OpenSearch/pull/17753)
- [17901](https://github.com/opensearch-project/OpenSearch/pull/17901)
- [16731](https://github.com/opensearch-project/OpenSearch/pull/16731)
- [17273](https://github.com/opensearch-project/OpenSearch/pull/17273)
- [17299](https://github.com/opensearch-project/OpenSearch/pull/17299)
- [17336](https://github.com/opensearch-project/OpenSearch/pull/17336)
- [17344](https://github.com/opensearch-project/OpenSearch/pull/17344)
- [17365](https://github.com/opensearch-project/OpenSearch/pull/17365)
- [17447](https://github.com/opensearch-project/OpenSearch/pull/17447)
- [17457](https://github.com/opensearch-project/OpenSearch/pull/17457)
- [17521](https://github.com/opensearch-project/OpenSearch/pull/17521)
- [17535](https://github.com/opensearch-project/OpenSearch/pull/17535)
- [17559](https://github.com/opensearch-project/OpenSearch/pull/17559)
- [17575](https://github.com/opensearch-project/OpenSearch/pull/17575)
- [17607](https://github.com/opensearch-project/OpenSearch/pull/17607)
- [17611](https://github.com/opensearch-project/OpenSearch/pull/17611)
- [17612](https://github.com/opensearch-project/OpenSearch/pull/17612)
- [17622](https://github.com/opensearch-project/OpenSearch/pull/17622)
- [17631](https://github.com/opensearch-project/OpenSearch/pull/17631)
- [17663](https://github.com/opensearch-project/OpenSearch/pull/17663)
- [17670](https://github.com/opensearch-project/OpenSearch/pull/17670)
- [17699](https://github.com/opensearch-project/OpenSearch/pull/17699)
- [17712](https://github.com/opensearch-project/OpenSearch/pull/17712)
- [17756](https://github.com/opensearch-project/OpenSearch/pull/17756)
- [17774](https://github.com/opensearch-project/OpenSearch/pull/17774)
- [17791](https://github.com/opensearch-project/OpenSearch/pull/17791)
- [17796](https://github.com/opensearch-project/OpenSearch/pull/17796)
- [17843](https://github.com/opensearch-project/OpenSearch/pull/17843)
- [17849](https://github.com/opensearch-project/OpenSearch/pull/17849)
- [17855](https://github.com/opensearch-project/OpenSearch/pull/17855)
- [17868](https://github.com/opensearch-project/OpenSearch/pull/17868)
- [17893](https://github.com/opensearch-project/OpenSearch/pull/17893)
- [17894](https://github.com/opensearch-project/OpenSearch/pull/17894)
- [17910](https://github.com/opensearch-project/OpenSearch/pull/17910)
- [17912](https://github.com/opensearch-project/OpenSearch/pull/17912)
- [17917](https://github.com/opensearch-project/OpenSearch/pull/17917)
- [17922](https://github.com/opensearch-project/OpenSearch/pull/17922)
- [17961](https://github.com/opensearch-project/OpenSearch/pull/17961)
- [17978](https://github.com/opensearch-project/OpenSearch/pull/17978)
- [17987](https://github.com/opensearch-project/OpenSearch/pull/17987)
- [17989](https://github.com/opensearch-project/OpenSearch/pull/17989)
- [18006](https://github.com/opensearch-project/OpenSearch/pull/18006)
- [18043](https://github.com/opensearch-project/OpenSearch/pull/18043)
- [18047](https://github.com/opensearch-project/OpenSearch/pull/18047)
- [18049](https://github.com/opensearch-project/OpenSearch/pull/18049)
- [18054](https://github.com/opensearch-project/OpenSearch/pull/18054)
- [18067](https://github.com/opensearch-project/OpenSearch/pull/18067)
- [18075](https://github.com/opensearch-project/OpenSearch/pull/18075)
- [18085](https://github.com/opensearch-project/OpenSearch/pull/18085)
- [18088](https://github.com/opensearch-project/OpenSearch/pull/18088)
- [18093](https://github.com/opensearch-project/OpenSearch/pull/18093)
- [18097](https://github.com/opensearch-project/OpenSearch/pull/18097)
- [18103](https://github.com/opensearch-project/OpenSearch/pull/18103)
- [18134](https://github.com/opensearch-project/OpenSearch/pull/18134)
- [18145](https://github.com/opensearch-project/OpenSearch/pull/18145)
- [18148](https://github.com/opensearch-project/OpenSearch/pull/18148)
- [18161](https://github.com/opensearch-project/OpenSearch/pull/18161)
- [18163](https://github.com/opensearch-project/OpenSearch/pull/18163)
- [18166](https://github.com/opensearch-project/OpenSearch/pull/18166)
- [18218](https://github.com/opensearch-project/OpenSearch/pull/18218)
- [18243](https://github.com/opensearch-project/OpenSearch/pull/18243)
- [18247](https://github.com/opensearch-project/OpenSearch/pull/18247)
- [12982](https://github.com/opensearch-project/OpenSearch/pull/12982)
- [13568](https://github.com/opensearch-project/OpenSearch/pull/13568)
- [14512](https://github.com/opensearch-project/OpenSearch/pull/14512)
- [15181](https://github.com/opensearch-project/OpenSearch/pull/15181)
- [16178](https://github.com/opensearch-project/OpenSearch/pull/16178)
- [16670](https://github.com/opensearch-project/OpenSearch/pull/16670)
- [17926](https://github.com/opensearch-project/OpenSearch/pull/17926)
- [17927](https://github.com/opensearch-project/OpenSearch/pull/17927)
- [17942](https://github.com/opensearch-project/OpenSearch/pull/17942)
- [17953](https://github.com/opensearch-project/OpenSearch/pull/17953)
- [9151](https://github.com/opensearch-project/OpenSearch/pull/9151)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by nomoa**
### Description
Similar to #18201 but applied via the TestPlugin used in S3BlobStoreRepositoryTests.

### Related Issues
Resolves #14299

### Check List
- [x] Functionality includes testing.
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java [hunk 1]
```diff
@@ -234,6 +236,7 @@ public Collection<Object> createComponents(
 
         this.lowTransferQConsumerService = threadPool.executor(LOW_TRANSFER_QUEUE_CONSUMER);
         this.normalTransferQConsumerService = threadPool.executor(NORMAL_TRANSFER_QUEUE_CONSUMER);
+        this.scheduler = threadPool.scheduler();
```
Comment (andrross) [inline plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java:239]: Is this needed?

Comment (nomoa) [reply plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java]: no, sorry. This is a leftover of a failed attempt to re-use elastic scheduler. Could possibly be a good idea but turned out to be a bit more involved than I anticipated and did not feel confident enough to pursue on this route.

**Review by andrross — APPROVED** [review]
