### PR TITLE
Make search pipelines asynchronous

### LINKED ISSUE #10248: [BUG] Search pipeline seen executing on transport_worker thread
**Describe the bug**
I have a search processor that uses a `org.opensearch.client.Client` object to execute a `TransportAction`.  This invocation returns a `BaseFuture` and the processor does `.get()`, blocking until the client returns a response.  Occasionally, the get() call blocks indefinitely and brings the whole cluster into bad state.

A thread dump on the node that hung revealed that the search processor was executing on a `transport_worker` thread.

```
"opensearch[opensearch-node1][transport_worker][T#2]" #32 daemon prio=5 os_prio=0 cpu=61810.65ms elapsed=43062.56s allocated=2771M defined_classes=251      tid=0x0000fffef4009140 nid=0x13d waiting on condition  [0x0000ffff88cda000]
    java.lang.Thread.State: WAITING (parking)
     at jdk.internal.misc.Unsafe.park(java.base@17.0.8/Native Method)
     - parking to wait for  <0x00000000ee75b640> (a org.opensearch.common.util.concurrent.BaseFuture$Sync)
     at java.util.concurrent.locks.LockSupport.park(java.base@17.0.8/LockSupport.java:211)
     at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.8/AbstractQueuedSynchronizer.java:715)
     at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@17.0.8/AbstractQueuedSynchronizer.java:1047)
     at org.opensearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:272)
     at org.opensearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:104)
     at org.opensearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:74)
     at org.opensearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:55)
     at org.opensearch.searchpipelines.questionanswering.generative.llm.DefaultLlmImpl.doChatCompletion(DefaultLlmImpl.java:84)
     at org.opensearch.searchpipelines.questionanswering.generative.GenerativeQAResponseProcessor.processResponse(GenerativeQAResponseProcessor.java:109)
     at org.opensearch.search.pipeline.Pipeline.transformResponse(Pipeline.java:177)
     at org.opensearch.search.pipeline.PipelinedRequest.transformResponse(PipelinedRequest.java:31)
     at org.opensearch.action.search.TransportSearchAction.lambda$executeRequest$0(TransportSearchAction.java:398)
     at org.opensearch.action.search.TransportSearchAction$$Lambda$4884/0x0000003001d5d850.accept(Unknown Source)
     at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82)
     at org.opensearch.core.action.ActionListener$5.onResponse(ActionListener.java:268)
     at org.opensearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:671)
     at org.opensearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:132)
     at org.opensearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:428)
     at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:422)
```

I do see in a few other thread dumps I captured the same processor running on a `search` thread.

From:
https://github.com/opensearch-project/OpenSearch/blob/8807d7a801898c416dfefa532bb075a8edde0d5c/server/src/main/java/org/opensearch/common/util/concurrent/BaseFuture.java#L109

And:
https://github.com/opensearch-project/OpenSearch/blob/8807d7a801898c416dfefa532bb075a8edde0d5c/modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/Netty4MessageChannelHandler.java#L86-L89

I can see that we don't expect a blocking call to happen on transport threads and there is code specifically in `BaseFuture.get` to disallow invocations on transport threads, although `assert` won't trigger unless the OpenSearch process is run with the `ea` JVM flag.

Can we ensure that search processors run on `search` threads?  Or are they really allowed to run on transport threads which means that I should not have any blocking calls in my search processor? 

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by msfroh**
### Description
If a search processor needs to make a call out to another service, we should not risk blocking on the transport thread. We should support async execution.

### Related Issues
Resolves #10248

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/search/pipeline/Pipeline.java [hunk 1]
```diff
@@ -117,92 +119,135 @@ protected void afterResponseProcessor(Processor processor, long timeInNanos) {}
...
-            } finally {
-                long took = TimeUnit.NANOSECONDS.toMillis(relativeTimeSupplier.getAsLong() - pipelineStart);
-                afterTransformRequest(took);
             }
+        } catch (IOException e) {
+            requestListener.onFailure(new SearchPipelineProcessingException(e));
+            return;
+        }
+
+        long[] pipelineStart = new long[1];
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/pipeline/Pipeline.java:140]: Shouldn't we assign the value here? 

```suggestion
        long[] pipelineStart = new long[1] { relativeTimeSupplier.getAsLong() };
```

Comment (reta) [reply server/src/main/java/org/opensearch/search/pipeline/Pipeline.java:140]: I think it will be easier this way and we could have it `final` as well, wdyt?

Comment (austintlee) [reply server/src/main/java/org/opensearch/search/pipeline/Pipeline.java:140]: I think assignment happens on line 186.

Comment (reta) [reply server/src/main/java/org/opensearch/search/pipeline/Pipeline.java:140]: It is but could it be moved up?

File: server/src/main/java/org/opensearch/search/pipeline/Pipeline.java [hunk 2]
```diff
@@ -117,92 +119,135 @@ protected void afterResponseProcessor(Processor processor, long timeInNanos) {}
...
+            onTransformRequestFailure();
+            requestListener.onFailure(new SearchPipelineProcessingException(e));
+        });
+
+        // Chain listeners back-to-front
+        ActionListener<SearchRequest> currentListener = finalListener;
+        for (int i = searchRequestProcessors.size() - 1; i >= 0; i--) {
+            final ActionListener<SearchRequest> nextListener = currentListener;
+            SearchRequestProcessor processor = searchRequestProcessors.get(i);
+            currentListener = ActionListener.wrap(r -> {
```
Comment (austintlee) [inline server/src/main/java/org/opensearch/search/pipeline/Pipeline.java:158]: Worked through this logic with pen & paper.

Say you have two request processors P1 & P2.

1) Set up the `finalListener` which takes the last (P2) transformed `SearchRequest` and returns it by wrapping it in a `PipedRequest` object to `TransportSearchAction`.  The chain being set up needs to lead to this.

2) `currentListener` points to `finalListener`.
3) `nextListener` points to what `currentListener` points to, i.e. `finalListener`.
4) `currentListener` sets up the next listener of P2 to point to what `nextListener` points to, i.e. `finalListener`.  Now, P2 correctly executes the final listener.
5) `nextListener` is re-assigned to point to what `currentListener` points to, i.e. P2's listener.
6) `currentListener` sets up the next listener of P1 to point to what `nextListener` points to, i.e. P2's listener.
7) Loop exits.
8) `currentListener` executes, i.e. P1.

File: server/src/main/java/org/opensearch/search/pipeline/Pipeline.java [hunk 3]
```diff
@@ -117,92 +119,135 @@ protected void afterResponseProcessor(Processor processor, long timeInNanos) {}
...
+            originalListener.onFailure(e);
+        });
+        ActionListener<SearchResponse> finalListener = responseListener; // Jump directly to this one on exception.
+
+        for (int i = searchResponseProcessors.size() - 1; i >= 0; i--) {
+            final ActionListener<SearchResponse> currentFinalListener = responseListener;
+            final SearchResponseProcessor processor = searchResponseProcessors.get(i);
+
+            responseListener = ActionListener.wrap(r -> {
+                beforeResponseProcessor(processor);
```
Comment (austintlee) [inline server/src/main/java/org/opensearch/search/pipeline/Pipeline.java:217]: I worked through this logic as well.  I actually tested this code with my own search processor and verified this works.

File: server/src/main/java/org/opensearch/search/pipeline/Pipeline.java (hunk 1 above)
Comment (austintlee) [reply server/src/main/java/org/opensearch/search/pipeline/Pipeline.java:140]: But then it would be a few nano seconds too soon!  😄   I think the argument that you can make it final is a good one.

Also, I thought there was a particular reason Michael wanted it on heap (new long[]).

Comment (msfroh) [reply server/src/main/java/org/opensearch/search/pipeline/Pipeline.java:140]: > But then it would be a few nano seconds too soon! 

That was the reasoning. :)

The construction of the chain should be pretty fast, but it's technically outside of the time spent executing the pipeline. 

Or is it? We do have the short-circuit logic up top to avoid constructing the listener chain if there are no request processors. One could argue that the time spent constructing the listener chain is a cost of pipeline execution that should be tracked.

I'm happy to just assign this one directly.

File: server/src/main/java/org/opensearch/search/pipeline/Pipeline.java (hunk 2 above)
Comment (msfroh) [reply server/src/main/java/org/opensearch/search/pipeline/Pipeline.java:158]: Correct. (Or at least that's what I was trying to do. It hurt my brain.)

If we didn't have the darned metrics to track (and the `ignoreFailure` flag), the code would be a lot shorter.

File: server/src/main/java/org/opensearch/search/pipeline/Pipeline.java (hunk 1 above)
Comment (reta) [reply server/src/main/java/org/opensearch/search/pipeline/Pipeline.java:140]: > I'm happy to just assign this one directly.

I would just do that to be fair, it make code much simpler and readable

**Review by austintlee — APPROVED** [review]

File: server/src/main/java/org/opensearch/search/pipeline/SearchResponseProcessor.java [hunk 4]
```diff
@@ -10,10 +10,37 @@
...
+
+    /**
+     * Transform a {@link SearchResponse}, possibly based on the executed {@link SearchRequest}.
+     * <p>
+     * Expert method: Implement this if the processor needs to make asynchronous calls. Otherwise, implement processResponse.
+     * @param request the executed {@link SearchRequest}
+     * @param response the current {@link SearchResponse}, possibly modified by earlier processors
+     * @param responseListener callback to be invoked on successful processing or on failure
+     */
+    default void asyncProcessResponse(SearchRequest request, SearchResponse response, ActionListener<SearchResponse> responseListener) {
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/pipeline/SearchResponseProcessor.java:39]: This is the convention we use for the codebase (xxxAsync), (RestClient, AsyncMultiStreamBlobContainer, TransferService ...)

```suggestion
    default void processResponseAsync(SearchRequest request, SearchResponse response, ActionListener<SearchResponse> responseListener) {
```

**Comment by reta** [comment]
> @reta can you take a look and approve if this looks good?

@harshavamsi there comments we agreed to address but they aren't

File: server/src/main/java/org/opensearch/search/pipeline/SearchRequestProcessor.java [hunk 5]
```diff
@@ -9,10 +9,37 @@
...
+
+    /**
+     * Transform a {@link SearchRequest}. Executed on the coordinator node before any {@link org.opensearch.action.search.SearchPhase}
+     * executes.
+     * <p>
+     * Expert method: Implement this if the processor needs to make asynchronous calls. Otherwise, implement processRequest.
+     * @param request the executed {@link SearchRequest}
+     * @param requestListener callback to be invoked on successful processing or on failure
+     */
+    default void asyncProcessRequest(SearchRequest request, ActionListener<SearchRequest> requestListener) {
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/pipeline/SearchRequestProcessor.java:38]: For the same reasons as https://github.com/opensearch-project/OpenSearch/pull/10598/files#r1373695799, please: 

```suggestion
    default void processRequestAsync(SearchRequest request, ActionListener<SearchRequest> requestListener) {
```

**Comment by msfroh** [comment]
> > @reta can you take a look and approve if this looks good?
> 
> @harshavamsi there comments we agreed to address but they aren't

Oh -- yeah, sorry. I got sidetracked with some other stuff. I didn't consider this one ready to merge yet. I'll let y'all know once I've addressed the outstanding issues.

**Review by reta — APPROVED** [review]
