### PR TITLE
[BugFix] Hide stracktrace in response while translog transfer upload failure

### LINKED ISSUE #16890: [BUG] Stacktrace visible to end-users while performing translog upload
### Describe the bug

When uploading translog files to remote store, if any translog file upload fails, the user could see the entire stackstrace of the error occurred. This can also reveal the remote file system's exceptions details. 

**Root Cause:**

For logging, we add all the exceptions as suppressed under a single exception. However, while reporting an error to users, we are throwing the same exception which contains all the suppressed exceptions. This causes the users to be able to see all the exceptions and stacktrace. 

### Related component

Storage:Remote

### To Reproduce

When translog files are being uploaded to remote store, drop any file or any packet to reproduce the issue. 

### Expected behavior

Details of exceptions and stacktrace about remote filesystems should not be visible to users in a response, since it can reveal sensitive info about remote file-system's implementation. 

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by meet-v25**
### Description
When uploading translog files to remote store, if any translog file upload fails, the user can see the entire stacktrace of the error occurred. This can also reveal the remote file system's exceptions details. This code-change will hide the details of those exceptions and stacktrace about remote filesystems which should not be visible to users in a response.

### Old Response 
-> without `error_trace` parameter in the request
-> Same for `http.detailed_errors.enabled=true` and `http.detailed_errors.enabled=false`

```{
    "took" : 595,
    "errors": true,
    "items": [
        {
            "create" : {
                "_index": "sample-index1",
                "_id" : "2",
                "status": 500,
                "error" : {
                    "type": "translog_upload_failed_exception",
                    "reason" : "Failed to upload 2 files during transfer", 
                    "suppressed" : [
                        {
                            "type": "exception",
                            "reason": "My manual exception 1. Resprestents File <1>."
                        },
                        {
                            "type": "exception",
                            "reason": "My manual exception 2. Resprestents File <2>."
                        }
                    ]
                }
            }
        },
        {
            "create" : {
                "_index": "sample-index1",
                "_id" : "3",
                "status": 500,
                "error" : {
                    "type": "translog_upload_failed_exception",
                    "reason" : "Failed to upload 2 files during transfer", 
                    "suppressed" : [
                        {
                            "type": "exception",
                            "reason": "My manual exception 1. Resprestents File <1>."
                        },
                        {
                            "type": "exception",
                            "reason": "My manual exception 2. Resprestents File <2>."
                        }
                    ]
                }
            }
        }
    ]
}
```

### New Response 
-> without `error_trace` parameter in the request
-> Same for `http.detailed_errors.enabled=true` and `http.detailed_errors.enabled=false`

```{
    "took" : 595,
    "errors": true,
    "items": [
        {
            "create" : {
                "_index": "sample-index1",
                "_id" : "2",
                "status": 500,
                "error" : {
                    "type": "translog_upload_failed_exception",
                    "reason" : "Failed to upload 2 files during transfer"
                }
            }
        },
        {
            "create" : {
                "_index": "sample-index1",
                "_id" : "3",
                "status": 500,
                "error" : {
                    "type": "translog_upload_failed_exception",
                    "reason" : "Failed to upload 2 files during transfer"
                }
            }
        }
    ]
}
```

### Related Issues
Resolves #16890 

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java [hunk 1]
```diff
@@ -206,7 +206,8 @@ public boolean transferSnapshot(TransferSnapshot transferSnapshot, TranslogTrans
         } catch (Exception ex) {
             logger.error(() -> new ParameterizedMessage("Transfer failed for snapshot {}", transferSnapshot), ex);
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java:207]: Would this still log the complete trace?

Comment (meet-v25) [reply server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java:207]: Hi! Currently working on the comments received on issue 16890, will update regarding this. 
Reply to your question: Yes, it will log the complete stacktrace of the errors/exceptions.

**Comment by sachinpkale** [comment]
Few comments on the PR title and description:
1. Instead of `Fix Issue 16890` in the title, just use `[BugFix]` followed by PR title. 
2. In the Check List, to select the box, you need to provide `[x]` to keep it de-secleted, use `[ ]` (I have made this change)

**Comment by meet-v25** [comment]
> Few comments on the PR title and description:
> 
> 1. Instead of `Fix Issue 16890` in the title, just use `[BugFix]` followed by PR title.
> 2. In the Check List, to select the box, you need to provide `[x]` to keep it de-secleted, use `[ ]` (I have made this change)

Thanks for the guidance! Corrected the title.

**Comment by andrross** [comment]
Just highlighting a comment I left on the issue: https://github.com/opensearch-project/OpenSearch/issues/16890#issuecomment-2557378879

There is a mechanism for hiding details like this, curious if that works here.

**Comment by meet-v25** [comment]
@andrross Yes, I was working on it, and it is done. I'll share the updates there on the issue.

File: server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java [hunk 2]
```diff
@@ -206,6 +206,80 @@ public void onUploadFailed(TransferSnapshot transferSnapshot, Exception ex) {
...
+            @Override
+            public void onUploadFailed(TransferSnapshot transferSnapshot, Exception ex) {
+                translogTransferFailed.incrementAndGet();
+                exception.set(ex);
+            }
+        }));
+
+        assertNotNull(exception.get());
+        assertTrue(exception.get() instanceof TranslogUploadFailedException);
+        assertEquals("Failed to upload 1 files during transfer", exception.get().getMessage());
```
Comment (skumawat2025) [inline server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java:274]: What are we trying to test here?

File: server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java [hunk 3]
```diff
@@ -206,7 +206,8 @@ public boolean transferSnapshot(TransferSnapshot transferSnapshot, TranslogTrans
...
             captureStatsOnUploadFailure();
-            translogTransferListener.onUploadFailed(transferSnapshot, ex);
+            Exception exWithoutSuppressed = new TranslogUploadFailedException(ex.getMessage());
```
Comment (skumawat2025) [inline server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java:209]: This looks good to me. But can we please add the stack-trace that we see without this change and with this change in this PR description.

**Comment by skumawat2025** [comment]
> > Few comments on the PR title and description:
> > 
> > 1. Instead of `Fix Issue 16890` in the title, just use `[BugFix]` followed by PR title.
> > 2. In the Check List, to select the box, you need to provide `[x]` to keep it de-secleted, use `[ ]` (I have made this change)
> 
> Thanks for the guidance! Corrected the title.

@meet-v25 Let's please change the PR title as suggested by @sachinpkale .

File: server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java (hunk 2 above)
Comment (meet-v25) [reply server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java:274]: This UT is supposed to throw an exception when calling the `transferSnapshot` function. I am testing that the exception is thrown, and its contents are as required - the error message of the exception and absence of any suppressed exceptions/stacktrace.

**Review by skumawat2025 — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java (hunk 3 above)
Comment (meet-v25) [reply server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java:209]: Sure.

**Review by ashking94 — COMMENTED** [review]
can we add an IT that checks that the response is intended during cases where translog upload fails due to remote store failure?

**Review by sachinpkale — APPROVED** [review]
