### PR TITLE
update index random function to fix the bogus document deletion

### LINKED ISSUE #10900: [BUG] HighlighterSearchIT.testHighlightNoMatchSizeWithMultivaluedFields, HighlighterSearchIT.testHighlightNoMatchSize, testHighlightNoMatchSizeNumberOfFragments for concurrent search are is flaky
**Describe the bug**
Following tests are flaky:
- org.opensearch.search.fetch.subphase.highlight.HighlighterSearchIT.testHighlightNoMatchSizeWithMultivaluedFields {p0={"search.concurrent_segment_search.enabled":"true"}}
- org.opensearch.search.fetch.subphase.highlight.HighlighterSearchIT.testHighlightNoMatchSize {p0={"search.concurrent_segment_search.enabled":"true"}}

**To Reproduce**
```
java.lang.AssertionError: 
Expected: map containing ["text"->ANYTHING]
     but: map was []
	at __randomizedtesting.SeedInfo.seed([571D12C4D227BEC2:5FF7F21F2365C629]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.opensearch.test.hamcrest.OpenSearchAssertions.assertHighlight(OpenSearchAssertions.java:430)
	at org.opensearch.test.hamcrest.OpenSearchAssertions.assertHighlight(OpenSearchAssertions.java:420)
	at org.opensearch.test.hamcrest.OpenSearchAssertions.assertHighlight(OpenSearchAssertions.java:399)
	at org.opensearch.search.fetch.subphase.highlight.HighlighterSearchIT.testHighlightNoMatchSizeWithMultivaluedFields(HighlighterSearchIT.java:2147)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

```
java.lang.AssertionError: 
Expected: map containing ["text"->ANYTHING]
     but: map was []
	at __randomizedtesting.SeedInfo.seed([571D12C4D227BEC2:51641BEB8A14FF7D]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.opensearch.test.hamcrest.OpenSearchAssertions.assertHighlight(OpenSearchAssertions.java:430)
	at org.opensearch.test.hamcrest.OpenSearchAssertions.assertHighlight(OpenSearchAssertions.java:420)
	at org.opensearch.test.hamcrest.OpenSearchAssertions.assertHighlight(OpenSearchAssertions.java:399)
	at org.opensearch.search.fetch.subphase.highlight.HighlighterSearchIT.testHighlightNoMatchSize(HighlighterSearchIT.java:2058)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```
**Expected behavior**
The test should always pass

**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/28869/testReport/junit/org.opensearch.search.fetch.subphase.highlight/HighlighterSearchIT/testHighlightNoMatchSizeWithMultivaluedFields__p0___search_concurrent_segment_search_enabled___true___/
- https://build.ci.opensearch.org/job/gradle-check/28869/testReport/junit/org.opensearch.search.fetch.subphase.highlight/HighlighterSearchIT/testHighlightNoMatchSize__p0___search_concurrent_segment_search_enabled___true___/
- https://build.ci.opensearch.org/job/gradle-check/28937/testReport/junit/org.opensearch.search.fetch.subphase.highlight/HighlighterSearchIT/testHighlightNoMatchSizeNumberOfFragments__p0___search_concurrent_segment_search_enabled___true___/

### PR DESCRIPTION
**Pull request by neetikasinghal**
### Description
This change updates the index random function to delete the bogus documents and add a refresh in the function such that the bogus documents are deleted and refresh ensures that the search doesnt account for the deleted segments.
This should fix some flaky issues encountered after adding the indexRadomForConcurrentSearch function to the tests.

Also, added [TransportTwoNodesSearchIT.java](https://github.com/opensearch-project/OpenSearch/compare/main...neetikasinghal:OpenSearch:slices-testing?expand=1#diff-cdddd7663031228dcf7a60e865cfb9bfa7a374c830ec86f12bb9fbec637dcd3e) to use indexRandomForConcurrentSearch.

### Related Issues
Resolves #10900

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by neetikasinghal** [comment]
@reta @andrross @jed326 please review the changes.

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java [hunk 1]
```diff
@@ -1686,6 +1682,9 @@ public void indexRandom(boolean forceRefresh, boolean dummyDocuments, boolean ma
                 client().admin().indices().prepareRefresh(indicesArray).setIndicesOptions(IndicesOptions.lenientExpandOpen()).get()
             );
         }
+        if (dummyDocuments) {
+            indexRandomForMultipleSlices(indicesArray);
+        }
```
Comment (jed326) [inline test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1687]: I wonder if there should be a different parameter that controls this? It seems like we are making some distinction with dummy docs for concurrent search and dummy docs not for concurrent search as we are ingesting dummy docs in 2 different ways (to be honest I don't understand why we have that distinction currently), so perhaps we should use a different parameter to control this here?

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java [hunk 2]
```diff
@@ -1731,7 +1730,17 @@ protected Set<List<String>> indexRandomForMultipleSlices(String... indices) thro
                 refresh(index);
             }
         }
-        return bogusIds;
+        if (!bogusIds.isEmpty()) {
+            // delete the bogus types again - it might trigger merges or at least holes in the segments and enforces deleted docs!
```
Comment (jed326) [inline test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1734]: I know this is a copied code comment but I don't think `delete the bogus types again` makes sense here

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java (hunk 1 above)
Comment (neetikasinghal) [reply test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1687]: yes i agree, however having a separate param would require changes in the usages of the current indexRandom function. 
Also, ideally ingesting docs for concurrent search tests should ideally be done by indexRandomForMultipleSlices and indexRandom function call should be replaced by indexRandomForMultipleSlices so then there is no need to have this if block in the indexRandom function. However, again there are a lot of places where the change has to be made.

Comment (jed326) [reply test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1687]: That makes sense to me -- should we use `indexRandomForConcurrentSearch` instead of `indexRandomForMultipleSlices` here though?

Comment (jed326) [reply test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1687]: Actually I thought on this some more -- `indexRandomForConcurrentSearch` doesn't work very well when this indexing happens before the setting is parameterized anyways so I guess it doesn't really make a difference.

**Review by jed326 — APPROVED** [review]

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java [hunk 3]
```diff
@@ -1731,7 +1730,17 @@ protected Set<List<String>> indexRandomForMultipleSlices(String... indices) thro
                 refresh(index);
             }
         }
-        return bogusIds;
+        if (!bogusIds.isEmpty()) {
```
Comment (andrross) [inline test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1733]: I don't think you need the if statement since the for loop is a no-op for an empty set.

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java (hunk 1 above)
Comment (neetikasinghal) [reply test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1687]: yes

File: test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java (hunk 3 above)
Comment (neetikasinghal) [reply test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java:1733]: makes sense, will update it

**Comment by neetikasinghal** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29795/
> * **CommitID:** [06e157e](https://github.com/opensearch-project/OpenSearch/commit/06e157e4ee881bfeefc2727cc7f3608324e8486c)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

https://github.com/opensearch-project/OpenSearch/issues/3603 - flaky test
https://github.com/opensearch-project/OpenSearch/issues/10193 - flay test
https://github.com/opensearch-project/OpenSearch/issues/10006 - flaky test
https://github.com/opensearch-project/OpenSearch/issues/9332 - flaky test

**Comment by neetikasinghal** [comment]
@andrross / @reta can you please help merge the pr? there are other prs pending to be merged that are dependent on this.

**Review by andrross — APPROVED** [review]

**Comment by neetikasinghal** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29795/
> * **CommitID:** [06e157e](https://github.com/opensearch-project/OpenSearch/commit/06e157e4ee881bfeefc2727cc7f3608324e8486c)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

https://github.com/opensearch-project/OpenSearch/issues/10231 - flaky
https://github.com/opensearch-project/OpenSearch/issues/9499 -  flaky
