### PR TITLE
Issue #19319: Fix case-insensitive wildcard + aggregation query crash

### LINKED ISSUE #19319: [BUG] Error when use both wildcard + aggregation
### Describe the bug

The cluster throw an error when I use both wlidcard + aggregation

### Related component

Search:Aggregations

### To Reproduce

Use OS 3.2.
1. Create mapping and ingest data
```
PUT hits
{
    "mappings": {
            "properties": {
                "URL": {
                    "type": "keyword"
                }
            }
        }
}
```
```
POST hits/_doc
{
   "URL": "http:\/\/google1.ru\/news\/post-41494,96205&bt=7&bn=1&bodystyle"
}
POST hits/_doc
{
   "URL": "http:\/\/google2.ru\/news\/post-41494,96205&bt=7&bn=1&bodystyle"
}

```

2. Run query 
```
POST hits/_search
{
  "from": 0,
  "size": 0,
  "timeout": "1m",
  "query": {
    "wildcard": {
      "URL": {
        "wildcard": "*google*",
        "case_insensitive": true,
        "boost": 1.0
      }
    }
  },
  "_source": {
    "includes": [
      "URL"
    ],
    "excludes": []
  },
  "sort": [
    {
      "_doc": {
        "order": "asc"
      }
    }
  ],
  "aggregations": {
    "count()": {
      "value_count": {
        "field": "_index"
      }
    }
  }
}
```
And get error
```
{
    "error": {
        "root_cause": [
            {
                "type": "array_index_out_of_bounds_exception",
                "reason": "Index 10 out of bounds for length 10"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "hits6",
                "node": "CR0Xi69OQi-jZ6quT_q92g",
                "reason": {
                    "type": "array_index_out_of_bounds_exception",
                    "reason": "Index 10 out of bounds for length 10",
                    "suppressed": [
                        {
                            "type": "array_index_out_of_bounds_exception",
                            "reason": "Index -6 out of bounds for length 9"
                        }
                    ]
                }
            }
        ],
        "caused_by": {
            "type": "array_index_out_of_bounds_exception",
            "reason": "Index 10 out of bounds for length 10",
            "caused_by": {
                "type": "array_index_out_of_bounds_exception",
                "reason": "Index 10 out of bounds for length 10",
                "suppressed": [
                    {
                        "type": "array_index_out_of_bounds_exception",
                        "reason": "Index -6 out of bounds for length 9"
                    }
                ]
            }
        }
    },
    "status": 500
}
```
Looks an error in lucene

### Expected behavior

Return correct result.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by ishag4**
### Description
To fix bug where executing a case-insensitive wildcard query combined with aggregations causes an ArrayIndexOutOfBoundsException. The root cause is related to how Lucene’s automaton handles case-insensitive wildcards without determinizing the automaton, leading to instability during query execution.
This PR fixes the issue by explicitly determinizing the automaton generated for case-insensitive wildcard queries before passing it to Lucene’s query execution layer. By converting the automaton to a deterministic finite automaton (DFA), we prevent the exception and ensure stable query execution.

### Related Issues
Resolves #19319

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by msfroh** [comment]
@ishag4  -- can you please add a CHANGELOG entry under the "Fixed" section?

File: server/src/main/java/org/opensearch/common/lucene/search/AutomatonQueries.java [hunk 1]
```diff
@@ -92,7 +93,14 @@ public static AutomatonQuery caseInsensitiveTermQuery(Term term) {
      * Build an automaton matching a wildcard pattern, ASCII case insensitive, if the method is null, then will use {@link  MultiTermQuery#CONSTANT_SCORE_BLENDED_REWRITE}.
      */
     public static AutomatonQuery caseInsensitiveWildcardQuery(Term wildcardquery, MultiTermQuery.RewriteMethod method) {
-        return createAutomatonQuery(wildcardquery, toCaseInsensitiveWildcardAutomaton(wildcardquery), method);
+        Automaton automaton = toCaseInsensitiveWildcardAutomaton(wildcardquery);
+        try {
+            automaton = Operations.determinize(automaton, Operations.DEFAULT_DETERMINIZE_WORK_LIMIT);
+        } catch (TooComplexToDeterminizeException e) {
```
Comment (sandeshkr419) [inline server/src/main/java/org/opensearch/common/lucene/search/AutomatonQueries.java:99]: Quick question: Any other exceptions do we need to handle?

Also, let's add a test case for exception case?

Comment (ishag4) [reply server/src/main/java/org/opensearch/common/lucene/search/AutomatonQueries.java:99]: Hi @sandeshkr419 , Apologies. I missed your first question.

Right now the method explicitly handles TooComplexToDeterminizeException, which is the only expected runtime failure from Operations.determinize() when working with wildcard automatons. Other exceptions like NullPointerException or IllegalArgumentException could theoretically occur, but those would stem from programming or input validation issues rather than determinization itself.  So unless we want to introduce explicit input validation (e.g., null checks for wildcardquery), the current handling is aligned with existing conventions and sufficient for the intended behavior.

Let me know if you'd like me to add validation or just keep the current handling!

**Comment by mishail** [comment]
@sandeshkr419 is it good to be merged?

**Review by sandeshkr419 — APPROVED** [review]
