### PR TITLE
Fix flaky QueryProfilePhaseTests.testTerminateAfterEarlyTermination

### LINKED ISSUE #11611: [BUG] QueryProfilePhaseTests.testTerminateAfterEarlyTermination is flaky
### Describe the bug

from https://github.com/opensearch-project/OpenSearch/issues/11239

### Related component

Search:Query Insights

### To Reproduce

https://build.ci.opensearch.org/job/gradle-check/30102/

### Expected behavior

Test to not be flaky

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by ticheng-aws**
### Description
`QueryProfilePhaseTests.testTerminateAfterEarlyTermination` is flaky not only in the concurrent search case but also in the non-concurrent search case. In cases where the test query returns some total hits, it is possible that the `score` breakdown timing for certain rewritten or sub-queries is still zero. Consequently, we need to update the assertion check accordingly.
Additionally, in the concurrent search case, there is a particular scenario where some slices have zero `score` breakdown timing, while others have non-zero `score` breakdown timing. In this case, the `min_score` stat result will be expected zero. I ran the new changes `1000+` times to make sure that they all passed.

### Related Issues
Resolves #11611

### Check List
- [ ] ~New functionality includes testing.~
  - [X] All tests pass
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [ ] ~Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- [X] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ticheng-aws** [comment]
> ❕ Gradle check result for [3c00409](https://github.com/opensearch-project/OpenSearch/commit/3c00409177889f166b4dd0b40d23c93797b1c732): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/31528/)
> 
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing
> ```
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

Known issue https://github.com/opensearch-project/OpenSearch/issues/9191

File: server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java [hunk 1]
```diff
@@ -615,12 +615,22 @@ public void testTerminateAfterEarlyTermination() throws Exception {
...
-                    assertThat(query.getTimeBreakdown().get("min_score_count"), greaterThan(0L));
-                    assertThat(query.getTimeBreakdown().get("avg_score_count"), greaterThan(0L));
+                    long maxScore = query.getTimeBreakdown().get("max_score");
+                    long minScore = query.getTimeBreakdown().get("min_score");
+                    long avgScore = query.getTimeBreakdown().get("avg_score");
+                    long maxScoreCount = query.getTimeBreakdown().get("max_score_count");
+                    long minScoreCount = query.getTimeBreakdown().get("min_score_count");
+                    long avgScoreCount = query.getTimeBreakdown().get("avg_score_count");
+                    assertThat(maxScore, greaterThan(0L));
+                    assertThat(minScore, greaterThanOrEqualTo(0L));
```
Comment (sohami) [inline server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java:625]: can you share an example with and without concurrent search enabled, where the scores are coming out to be 0 for some subquery ?

Comment (ticheng-aws) [reply server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java:625]: For example, consider the `BooleanQuery` "foo:bar foo:baz" with the seed id `E6C322CFA1FDE270:89327DD80FA3AC95`. The response has only `1` total hit and the score for the second child query (i.e. "foo:bar") is zero.
``` json
{
  "took": ...,
  "timed_out": false,
  "_shards": {...},
  "hits": {...},
  "profile": {
    "shards": [
      {
        "id": ...,
        "inbound_network_time_in_millis": 0,
        "outbound_network_time_in_millis": 0,
        "searches": [
          {
            "query": [
              {
                "type": "BooleanQuery",
                "description": "foo:bar foo:baz",
                "time_in_nanos": 445667,
                "breakdown": {
                  "set_min_competitive_score_count": 0,
                  "match_count": 0,
                  "shallow_advance_count": 0,
                  "set_min_competitive_score": 0,
                  "next_doc": 1870,
                  "match": 0,
                  "next_doc_count": 2,
                  "score_count": 7,
                  "compute_max_score_count": 0,
                  "compute_max_score": 0,
                  "advance": 1787,
                  "advance_count": 1,
                  "score": 10874,
                  "build_scorer_count": 2,
                  "create_weight": 15831,
                  "shallow_advance": 0,
                  "create_weight_count": 1,
                  "build_scorer": 62757
                },
                "children": [
                  {
                    "type": "TermQuery",
                    "description": "foo:bar",
                    "time_in_nanos": 221542,
                    "breakdown": {
                      "set_min_competitive_score_count": 0,
                      "match_count": 0,
                      "shallow_advance_count": 0,
                      "set_min_competitive_score": 0,
                      "next_doc": 597,
                      "match": 0,
                      "next_doc_count": 1,
                      "score_count": 7,
                      "compute_max_score_count": 0,
                      "compute_max_score": 0,
                      "advance": 819,
                      "advance_count": 1,
                      "score": 6958,
                      "build_scorer_count": 3,
                      "create_weight": 4999,
                      "shallow_advance": 0,
                      "create_weight_count": 1,
                      "build_scorer": 9580
                    }
                  },
                  {
                    "type": "TermQuery",
                    "description": "foo:baz",
                    "time_in_nanos": 168125,
                    "breakdown": {
                      "set_min_competitive_score_count": 0,
                      "match_count": 0,
                      "shallow_advance_count": 0,
                      "set_min_competitive_score": 0,
                      "next_doc": 114,
                      "match": 0,
                      "next_doc_count": 1,
                      "score_count": 0,
                      "compute_max_score_count": 0,
                      "compute_max_score": 0,
                      "advance": 158,
                      "advance_count": 1,
                      "score": 0,
                      "build_scorer_count": 3,
                      "create_weight": 959,
                      "shallow_advance": 0,
                      "create_weight_count": 1,
                      "build_scorer": 2976
                    }
                  }
                ]
              }
            ],
            "rewrite_time": ...,
            "collector": [...]
          }
        ],
        "aggregations": []
      }
    ]
  }
}
```

Comment (sohami) [reply server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java:625]: Thanks

**Review by sohami — APPROVED** [review]
