### PR TITLE
Fix flakiness with SegmentReplicationSuiteIT

### LINKED ISSUE #9499: [BUG] Test org.opensearch.indices.replication.SegmentReplicationSuiteIT is flaky
Using the same seed does not always fail the test. We need to run the test multiple times to get the failure (On my local, I got it on the 13th retry)

Build where it failed: https://build.ci.opensearch.org/job/gradle-check/23203/

I was able to reproduce with `main`

```
  2> java.lang.IllegalStateException: Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.
        at __randomizedtesting.SeedInfo.seed([CFC3DCBFE313A077]:0)
        at org.opensearch.node.Node.awaitClose(Node.java:1541)
        at org.opensearch.test.InternalTestCluster$NodeAndClient.close(InternalTestCluster.java:1129)
        at org.opensearch.common.util.io.IOUtils.close(IOUtils.java:89)
        at org.opensearch.common.util.io.IOUtils.close(IOUtils.java:131)
        at org.opensearch.common.util.io.IOUtils.close(IOUtils.java:114)
        at org.opensearch.test.InternalTestCluster.close(InternalTestCluster.java:966)
        at org.opensearch.common.util.io.IOUtils.close(IOUtils.java:89)
        at org.opensearch.common.util.io.IOUtils.close(IOUtils.java:131)
        at org.opensearch.common.util.io.IOUtils.close(IOUtils.java:114)
        at org.opensearch.test.OpenSearchIntegTestCase.clearClusters(OpenSearchIntegTestCase.java:576)
        at org.opensearch.test.OpenSearchIntegTestCase.afterClass(OpenSearchIntegTestCase.java:2283)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:901)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:1623)
  2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationSuiteIT" -Dtests.seed=CFC3DCBFE313A077 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-US -Dtests.timezone=UTC -Druntime.java=20
```

```
Tests with failures:
 - org.opensearch.indices.replication.SegmentReplicationSuiteIT.testFullRestartDuringReplication
 - org.opensearch.indices.replication.SegmentReplicationSuiteIT.testDropRandomNodeDuringReplication
 - org.opensearch.indices.replication.SegmentReplicationSuiteIT.testDeleteIndexWhileReplicating
 - org.opensearch.indices.replication.SegmentReplicationSuiteIT.testBasicReplication
 - org.opensearch.indices.replication.SegmentReplicationSuiteIT.classMethod
```

### PR DESCRIPTION
**Pull request by mch2**
### Description
This PR fixes race conditions while shutting down SegmentReplicationSourceService used for node-node segment replication that cause store refs to not close before checks are made. This is the cause for flakiness with SegmentReplicationSuiteIT and a few others.

The issue here is we are creating new replications on the primary after we have cancelled replications but before the shard is closed.  OngoingSegmentReplications has a `prepareForReplications` method that previously would invoke `getCachedCopyState`.  In that method we would first fetch copyState from the map and incref it if it exists.  This left us open to incref the copyState ref even though the shard is shutting down & no longer in indexService.

To fix this this change removes the responsibility of caching CopyState inside of OngoingSegmentReplications.
1. CopyState was originally cached to prevent frequent disk reads while building segment metadata.  This is now
cached lower down in IndexShard and is not required here.  This eliminates the need to synchronize on the object for create/cancel methods.
2. Change prepareForReplication method to return SegmentReplicationSourceHandler directly.
3. Move responsibility of creating and closing CopyState to the handler.
4. Changes `testDropRandomNodeDuringReplication` to wait until shards have recovered before deleting the index.  The intent of the test was to ensure we can recover after the node drop.  The subsequent test `testDeleteIndexWhileReplicating` covers paths for index deletion while replication is running.

With these changes I have run the entire suite ~2500 times without failure.

### Related Issues
Resolves #9499

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mch2** [comment]
> ❌ Gradle check result for [70e3e37](https://github.com/opensearch-project/OpenSearch/commit/70e3e377d8b550e678d372e5048bcefdde48b634): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/32463/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

https://github.com/opensearch-project/OpenSearch/issues/11032
https://github.com/opensearch-project/OpenSearch/issues/11979

File: server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java [hunk 1]
```diff
@@ -220,7 +220,7 @@ protected void doClose() throws IOException {
      * Cancels any replications on this node to a replica shard that is about to be closed.
```
Comment (Poojita-Raj) [inline server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java:220]: Need to change the comment to reflect this change.

**Review by Poojita-Raj — APPROVED** [review]

File: server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java [hunk 2]
```diff
@@ -137,7 +137,7 @@ void startSegmentCopy(GetSegmentFilesRequest request, ActionListener<GetSegmentF
      * @return {@link CopyState} the built CopyState for this replication event.
      * @throws IOException - When there is an IO error building CopyState.
      */
-    CopyState prepareForReplication(CheckpointInfoRequest request, FileChunkWriter fileChunkWriter) throws IOException {
+    synchronized CopyState prepareForReplication(CheckpointInfoRequest request, FileChunkWriter fileChunkWriter) throws IOException {
```
[the remark this answers is not in the document]
Comment (mch2) [reply server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java:140]: Yeah, this class has become a bit of a mess over time so I think its worth cleaning it up.

- Yep this would eventually become an issue as the amount of shards/node and replica count increases, so would be worthwhile to refactor to not block on the object.

I think we can actually do away with the CopyState map at this point altogether and tie an instance & its lifecycle directly to the handler.  The original intention of holding that map was to reduce the amount of disk reads made while computing file metadata, but this is cached internally in IndexShard now.

[the remark this answers is not in the document]
Comment (mch2) [reply server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java]: @andrross I've made a revision here that removes the synchronization & copystate map entirely from OngoingSegmentReplications.  This should simply the flow a bit and rely on the map implementation for concurrency where we add/start/remove by allocation ID.

The CopyState object still exists, but its lifecycle is handled by the handler itself, and clears it whenever it completes its work or is cancelled.

File: server/src/main/java/org/opensearch/indices/replication/common/CopyState.java [hunk 3]
```diff
@@ -83,7 +67,12 @@ public IndexShard getShard() {
         return shard;
     }
 
-    public ReplicationCheckpoint getRequestedReplicationCheckpoint() {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/indices/replication/common/CopyState.java:86]: This field is no longer required, this was used as the cache key in OngoingSegmentReplications.

**Comment by mch2** [comment]
> ❌ Gradle check result for [e89a440](https://github.com/opensearch-project/OpenSearch/commit/e89a4401518a7a0122972f8486f34abda9e448ad): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/32588/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

looks like my refactoring left a bug here where resources aren't closed on the replica, looking at it

**Comment by mch2** [comment]
> > ❌ Gradle check result for [e89a440](https://github.com/opensearch-project/OpenSearch/commit/e89a4401518a7a0122972f8486f34abda9e448ad): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/32588/)
> > Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?
> 
> looks like my refactoring left a bug here where resources aren't closed on the replica, looking at it

I've combined this with changes in https://github.com/opensearch-project/OpenSearch/pull/12043 and not getting failures after ~1k runs.  Will leave it running a while.  The changes in https://github.com/opensearch-project/OpenSearch/pull/12043 are on the replica side and resolve a separate issue with the bwc IT, while this PR is all on the primary.

**Review by peternied — COMMENTED** [review]
> With these changes I have run the entire suite ~2500 times without failure.

@mch2 This is good - and its a shame we haven't gotten this change reviewed.  

I'll try to prioritize this in my review queue, I'm not familiar with the replication space - is there anything that warrants extra attention that you'd like focused on?

**Comment by mch2** [comment]
@peternied Thanks for taking a look here.  @andrross offered to review this last week and I had asked him to pause until I revisit it as its been a while but I think this is good to go.   I believe this will fix more flakiness with https://github.com/opensearch-project/OpenSearch/issues/12408 that popped up after the introduction of more tests executing with SegRep as the root cause there looks the same.

The key components of this PR that may warrant extra attention are in moving the cancellation to after the shard is closed (beforeIndexShardClosed -> AfterIndexShardClosed) to ensure open file refs are closed only after the shard is, preventing the possibility of a race between cancel & shard closure.  Second is the removal of caching the `CopyState` object on the source/primary side.  That object fetches file refs to ensure they are not discarded until after replication completes.  This logic was buggy and hard to debug.  The object is now all tied 1-1 to a handler that manages closing that state when replication is completed.

**Comment by mch2** [comment]
@andrross Apologies for stalling here - After running both this suite & IndexActionIT I do not get any failures and think this is ready.  
I've made a couple small changes here since this was first cut but its largely the same.  The fix is to create a 1-1 relationship of CopyState to the Source handler so that state is always closed on shard closure.

**Comment by mch2** [comment]
> ❕ Gradle check result for [13522a0](https://github.com/opensearch-project/OpenSearch/commit/13522a0e3c7af2f024c5425347c82d64fbcd2e40): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/36337/)
> 
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex
> ```
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

https://github.com/opensearch-project/OpenSearch/issues/11547

File: server/src/main/java/org/opensearch/indices/replication/common/CopyState.java [hunk 4]
```diff
@@ -58,21 +51,12 @@ public CopyState(ReplicationCheckpoint requestedReplicationCheckpoint, IndexShar
...
-        }
-    }
-
     public ReplicationCheckpoint getCheckpoint() {
         return replicationCheckpoint;
     }
 
     public Map<String, StoreFileMetadata> getMetadataMap() {
-        return metadataMap;
+        return replicationCheckpoint.getMetadataMap();
```
Comment (scrawfor99) [inline server/src/main/java/org/opensearch/indices/replication/common/CopyState.java:59]: Looking at this, it seems like this is no longer fetching the indexShard's metadatamap but instead the checkpoint's metadata map. Are these the same?

**Review by scrawfor99 — APPROVED** [review]
I don't know much about replication but the code looks good. I left one comment/question around the fetching of the metadata map but assuming that is all good should be ready to merge!

**Review by andrross — APPROVED** [review]

File: server/src/main/java/org/opensearch/indices/replication/common/CopyState.java (hunk 4 above)
Comment (mch2) [reply server/src/main/java/org/opensearch/indices/replication/common/CopyState.java:59]: Hey @scrawfor99 thanks for taking a look.  Yes these will be the same.  The metadata is recomputed post every refresh with the new set of segments and stored with its checkpoint.  The change to this class will ensure we aren't recomputing the metadata every time we construct this class & fetch the metadata from the most recently refreshed on checkpoint.
