### PR TITLE
Change InternalSignificantTerms to only sum shard level counts in final reduce

### LINKED ISSUE #8703: [Concurrent Segment Search] SignificantTerms agg should not gather bg_count for each slice
Subtask as a part of https://github.com/opensearch-project/OpenSearch/issues/8509

**To Reproduce**
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testXContentResponse" -Dtests.seed=6D7B107FC7821E62 -Dtests.locale=mk -Dtests.timezone=America/Atka -Druntime.java=17
```

#  Details
This test is failing due to an unexpected result in the query response:
*Expected:*
```
{
    "class": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [{
            "key": "0",
            "doc_count": 4,
            "sig_terms": {
                "doc_count": 4,
                "bg_count": 7,
                "buckets": [{
                    "key": 0,
                    "doc_count": 4,
                    "score": 0.39999999999999997,
                    "bg_count": 5
                }]
            }
        }, {
            "key": "1",
            "doc_count": 3,
            "sig_terms": {
                "doc_count": 3,
                "bg_count": 7,
                "buckets": [{
                    "key": 1,
                    "doc_count": 3,
                    "score": 0.75,
                    "bg_count": 4
                }]
            }
        }]
    }
}
```
*Actual:*
```
{
    "class": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [{
            "key": "0",
            "doc_count": 4,
            "sig_terms": {
                "doc_count": 4,
                "bg_count": 28,
                "buckets": [{
                    "key": 0,
                    "doc_count": 4,
                    "score": 0.39999999999999997,
                    "bg_count": 20
                }]
            }
        }, {
            "key": "1",
            "doc_count": 3,
            "sig_terms": {
                "doc_count": 3,
                "bg_count": 21,
                "buckets": [{
                    "key": 1,
                    "doc_count": 3,
                    "score": 0.75,
                    "bg_count": 12
                }]
            }
        }]
    }
}
```

Specifically, the bg_count is wrong in the concurrent search case. In a Significant terms aggregation, bg_count is the number of docs with the term in the background set while doc_count is the number of docs with the term in the foreground set.

So at the top level, the background set is the number of docs in the index with the “class” field, so the bg_count should simply be the number of docs in the index. Code ref: https://github.com/opensearch-project/OpenSearch/blob/8eea7b986453271cd227a7b98ee09e70d5e28634/server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificanceLookup.java#L100
*Background Set == All documents in the index with “class” field*
At the inner level, the bg_count therefore refers to all of the documents in the background set with the given key in the “text” field. See how index is created here: https://github.com/opensearch-project/OpenSearch/blob/b9f04405d6dfabcc2b8e87a86d4f83b003b3ffe7/server/src/test/java/org/opensearch/test/search/aggregations/bucket/SharedSignificantTermsTestMethods.java#L94-L115
So for key “0” this is 5, and for key “1” this is 4. This value is retrieved through a querying the index from the search thread. Code ref:

* https://github.com/opensearch-project/OpenSearch/blob/8eea7b986453271cd227a7b98ee09e70d5e28634/server/src/main/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregator.java#L647-L656
* https://github.com/opensearch-project/OpenSearch/blob/e3542011cd9584c354405ba6cbf9a31ced7bc5ce/server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java#L897

---
Just to crystalize the meanings of background and foreground sets, let’s break down the example in the ElasticSearch docs here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-significantterms-aggregation.html#_single_set_analysis

Here the outer level bg_count refers to the number of documents with the field crime_type in the background set, which is the entire index. The query is for force == British Transport Police, so doc_count represents the number of documents where the force field matches British Transport Police, also known as our foreground set. 
*Background Set == Number of crimes in the index
Foreground Set == Number of crimes where force == British Transport Police*
So now looking at the inner level, bg_count is going to be the number of documents where crime_type == Bicycle theft in the *Background set*, while doc_count is going to be the number of documents matching the same condition in the *Foreground set*.

References:

* https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-significantterms-aggregation.html#significantterms-aggregation-parameters
* https://stackoverflow.com/questions/49928871/elasticsearch-significant-terms-aggregation-meaning-of-doc-count-and-bg-count
* https://javadoc.io/static/org.elasticsearch/elasticsearch/7.16.3/org/elasticsearch/search/aggregations/bucket/terms/InternalSignificantTerms.Bucket.html#getSupersetDf()
---

During the buildAggregations phase, the bg_count is gathered per collector. In the non-concurrent search case, that means it will only happen once per shard, and then at the coordinator level reduce can just sum up the bg_count across all of the shards to get the total. However, in the concurrent search use case we will have a collector per segment slice, and then at the shard-level reduce these will get summed up, so we will end up with SEGMENT_SLICE_COUNT * BG_COUNT documents. 

Small caveat here is that this will only happen for slices that actually have docs, so in our test example, if a slice does not have any documents that have “text” field “0” then that collector will not contribute to the BG_COUNT miscount.
Here is an example to illustrate this problem:
In a test run, if the buckets look like this

```
0 = {StringTerms@13132} "{"class":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"1","doc_count":2,"sig_terms":{"doc_count":2,"bg_count":7,"buckets":[]}}]}}"
1 = {StringTerms@13133} "{"class":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"0","doc_count":1,"sig_terms":{"doc_count":1,"bg_count":7,"buckets":[]}},{"key":"1","doc_count":1,"sig_terms":{"doc_count":1,"bg_count":7,"buckets":[]}}]}}"
2 = {StringTerms@13134} "{"class":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"0","doc_count":2,"sig_terms":{"doc_count":2,"bg_count":7,"buckets":[]}}]}}"
3 = {StringTerms@13135} "{"class":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"0","doc_count":1,"sig_terms":{"doc_count":1,"bg_count":7,"buckets":[]}}]}}"
```

Then there are 5 buckets total, 2 for key “1” and 3 for key “0”, so if you look at the results below:

*Expected:*
```
{
    "class": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [{
            "key": "0",
            "doc_count": 4,
            "sig_terms": {
                "doc_count": 4,
                "bg_count": 7,
                "buckets": [{
                    "key": 0,
                    "doc_count": 4,
                    "score": 0.39999999999999997,
                    "bg_count": 5
                }]
            }
        }, {
            "key": "1",
            "doc_count": 3,
            "sig_terms": {
                "doc_count": 3,
                "bg_count": 7,
                "buckets": [{
                    "key": 1,
                    "doc_count": 3,
                    "score": 0.75,
                    "bg_count": 4
                }]
            }
        }]
    }
}
```
*Actual:*
```
{
    "class": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [{
            "key": "0",
            "doc_count": 4,
            "sig_terms": {
                "doc_count": 4,
                "bg_count": 21,
                "buckets": [{
                    "key": 0,
                    "doc_count": 4,
                    "score": 0.39999999999999997,
                    "bg_count": 15
                }]
            }
        }, {
            "key": "1",
            "doc_count": 3,
            "sig_terms": {
                "doc_count": 3,
                "bg_count": 14,
                "buckets": [{
                    "key": 1,
                    "doc_count": 3,
                    "score": 0.75,
                    "bg_count": 8
                }]
            }
        }]
    }
}
```

We see that key “1” has 2x the expected count while key “0” has 3x.

Single set case for reference:
```
    "aggregations": {
        "sig_terms": {
            "doc_count": 4,
            "bg_count": 21,
            "buckets": [{
                "key": 0,
                "doc_count": 4,
                "score": 0.39999999999999997,
                "bg_count": 15
            }]
        }
    }
```

# Solutions

Without a deeper understanding of the scoring mechanism, it would be best for a solution to fix the scores in the slice level rather than the coordinator level.

I have added a few possible solutions below, with solution 3 looking the most promising to me and I will be working on a PR for that.

## 1. Divide by the bucket count

Due to the caveat above, in sparse data cases if a bucket is not collected in a segment slice then it won’t contribute to the bg_count. That means we can’t just blindly divide these numbers by the slice count. We would need to figure out some way to get the bucket count per collector to see how to divide the bg_count.

## 2. Separate out the shard-level vs slice-level reduce logic

Slice level reduce: https://github.com/opensearch-project/OpenSearch/blob/064f265362f6ae8296bfeed09aaaf48be86e6a4d/server/src/main/java/org/opensearch/search/aggregations/AggregationCollectorManager.java#L70-L74

Add a flag to reduce context and then don’t sum up supersetDf here: https://github.com/opensearch-project/OpenSearch/blob/e3542011cd9584c354405ba6cbf9a31ced7bc5ce/server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalSignificantTerms.java#L286-L299
Nor supersetSize here: https://github.com/opensearch-project/OpenSearch/blob/e3542011cd9584c354405ba6cbf9a31ced7bc5ce/server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalSignificantTerms.java#L231-L236

## 3. Create a singleton `SignificanceLookup` that will only return backgroundFrequencies and supersetSize once per bucket

This seems to be the best solution to me because the sum `bg_count` will be correct going into the aggs level reduce so we won't need to modify that. Moreover, we're actually doing up to 2 * NUM_SLICES * NUM_BUCKETS extra queries to get the `bg_count` for every single bucket at the slice level, so this singleton solution will eliminate all but up to 2 of these extra queries.

Currently I am thinking we can use `searchContext.isConcurrentSegmentSearchEnabled()` here:

https://github.com/opensearch-project/OpenSearch/blob/9b9158e4cb692dfe04315225ce2b5f9c6c453307/server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTermsAggregatorFactory.java#L290-L295

and then further use the `queryShardContext` to determine when to rest the Singleton.

Note that we will most likely also need to do this in `SignificantTextAggregatorFactory` here: 
https://github.com/opensearch-project/OpenSearch/blob/8eea7b986453271cd227a7b98ee09e70d5e28634/server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java#L157

However I'm seeing assert codec failures in that execution path as mentioned in https://github.com/opensearch-project/OpenSearch/issues/8509#issuecomment-1636306061. Nevertheless the same solution should be applicable in both cases here.

I still need to hash out some of the finer details here, such as how to reset the Singleton class per bucket, however conceptually this solution is both the most intuitive and least intrusive.

### PR DESCRIPTION
**Pull request by jed326**
### Description
Implements solution 2 from https://github.com/opensearch-project/OpenSearch/issues/8703#issue-1805435821

In short: supersetSize and supersetDf are shard level counts that are gathered via count queries. In concurrent segment search these will still be shard level counts rather than segment slice level counts, so we do not want to sum up these counts across segment slices, only at the coordinator level (across shards)

### Related Issues
Resolves #8703

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
Tagging @reta @sohami for some feedback. Thanks 😄

**Review by sohami — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalSignificantTerms.java [hunk 1]
```diff
@@ -291,7 +296,12 @@ protected B reduceBucket(List<B> buckets, ReduceContext context) {
         List<InternalAggregations> aggregationsList = new ArrayList<>(buckets.size());
         for (B bucket : buckets) {
             subsetDf += bucket.subsetDf;
-            supersetDf += bucket.supersetDf;
+            // supersetDf is a shard level count, so we don't sum it for segment slices
```
[the remark this answers is not in the document]
Comment (jed326) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalSignificantTerms.java:299]: I think it would actually produce `bucketCount * actual_supersetDf` since there is not necessarily 1 bucket per slice, but I agree that this could use some more explanation here

**Review by sohami — APPROVED** [review]
lgtm. Thanks!

**Comment by jed326** [comment]
@reta @andrross could one of you take a look at this PR and merge it if it looks good? Thanks!

File: CHANGELOG.md [hunk 2]
```diff
@@ -45,6 +45,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 - Migrate client transports to Apache HttpClient / Core 5.x ([#4459](https://github.com/opensearch-project/OpenSearch/pull/4459))
 - Change http code on create index API with bad input raising NotXContentException from 500 to 400 ([#4773](https://github.com/opensearch-project/OpenSearch/pull/4773))
 - Improve summary error message for invalid setting updates ([#4792](https://github.com/opensearch-project/OpenSearch/pull/4792))
+- Change InternalSignificantTerms to sum shard-level superset counts only in final reduce ([#8735](https://github.com/opensearch-project/OpenSearch/pull/8735))
```
Comment (andrross) [inline CHANGELOG.md:48]: Are you targeting 2.10 for this change? If so, this needs to go in the [Unreleased 2.x] section.

**Review by andrross — APPROVED** [review]

File: CHANGELOG.md (hunk 2 above)
Comment (andrross) [reply CHANGELOG.md]: I honestly don't have a strong opinion about which section. We should not backport to 2.9 though. Only critical fixes or security fixes would go into a 2.9 patch release. A bug in an experimental feature would definitely not rise to that level.

Comment (jed326) [reply CHANGELOG.md]: Got it. I moved it to the `Changed` section under unreleased 2.x i nthe most recent revision, thanks!
