### PR TITLE
Remove MinimizationOperations

### LINKED ISSUE #16975: [BUG] Can (easily) run out of memory with case-insensitive term queries
### Describe the bug

This follows on from @dbwiddis's doc suggestion [here](https://github.com/opensearch-project/documentation-website/issues/9028) and [my reply](https://github.com/opensearch-project/documentation-website/issues/9028#issuecomment-2575913081) in particular.

Basically, Lucene will try to determinize a finite automaton for a case-insensitive string query in a similar way to how it handles regular expressions. That is, a case-insensitive term query for `abc` behaves the same as a regexp query for `[Aa][Bb][Cc]`. That automaton has four states:

```mermaid
stateDiagram-v2
direction LR
[*] --> s1: [Aa]
s1 --> s2: [Bb]
s2 --> [*]: [Cc]
```

The Javadoc on the `determinize` method says `Worst case complexity: exponential in number of states.` It also describes the `workLimit` parameter as:

```
   *  Maximum amount of "work" that the powerset construction will spend before
   *     throwing {@link TooComplexToDeterminizeException}. Higher numbers allow this operation to
   *     consume more memory and CPU but allow more complex automatons. Use {@link
   *     #DEFAULT_DETERMINIZE_WORK_LIMIT} as a decent default if you don't otherwise know what to
   *     specify.
```

Unfortunately, all of our case-insensitive queries (while all go through the [`AutomatonQueries`](https://github.com/opensearch-project/OpenSearch/blob/ad7ce4cd446523d52286530ccfbb1dabc2dc7f86/server/src/main/java/org/opensearch/common/lucene/search/AutomatonQueries.java#L53) helper class) call `MinimizationOperations.minimize` (which calls `determinize`) with a limit of `Integer.MAX_VALUE`, which potentially blows up the memory usage if someone tries a case-insensitive query over a large string.

### Related component

Search:Resiliency

### To Reproduce

Submit a case-insensitive term query over a large (100+ character) string. You'll probably run out of memory.

### Expected behavior

Like with regexp queries, we should have a `max_determinized_states` parameter for any query type the support case-insensitive queries. For backward compatibility on the 2.x branch, we can keep a default value of `Integer.MAX_VALUE`, while 3.0 can switch to the Lucene default of 10000 (overridable by users).

### Additional Details

N/A

### PR DESCRIPTION
**Pull request by msfroh**
### Description
This class was removed from Lucene because it is no longer needed. It was copied into the OpenSearch code base because we were using it and we didn't want our code to break. 

In fact, the correct choice would have been to remove the references to
`MinimizationOperations.minimize()` and either replace them with calls to `Operations.determinize()` or simply drop them altogether because the automaton is deterministic.

### Related Issues
Resolves #16975

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/indices/SystemIndices.java [hunk 1]
```diff
@@ -147,6 +146,8 @@ private static CharacterRunAutomaton buildCharacterRunAutomaton(Collection<Syste
         Optional<Automaton> automaton = descriptors.stream()
             .map(descriptor -> Regex.simpleMatchToAutomaton(descriptor.getIndexPattern()))
             .reduce(Operations::union);
-        return new CharacterRunAutomaton(MinimizationOperations.minimize(automaton.orElse(Automata.makeEmpty()), Integer.MAX_VALUE));
+        return new CharacterRunAutomaton(
+            Operations.determinize(automaton.orElse(Automata.makeEmpty()), Operations.DEFAULT_DETERMINIZE_WORK_LIMIT)
```
Comment (rmuir) [inline server/src/main/java/org/opensearch/indices/SystemIndices.java:150]: For some of these, it looks like we're 
1. parsing wildcard-type expressions with this simpleMatchToAutomaton, 
2. determinizing them (Operations.determinize) presumably just for the next step. 
3. tableizing them (CharRunAutomaton) for fastest execution.

This is a lot of investment, that makes sense if you are going to match gazillions of terms in the term dictionary.

But if you are just matching a couple things, maybe consider less heavy options?
1. `determinize()`, but don't tableize, and then match strings with `Operations.run()`
2. tableize, but don't `determinize()` by using `NFARunAutomaton`

Comment (msfroh) [reply server/src/main/java/org/opensearch/indices/SystemIndices.java:150]: Yeah, for these cases it probably makes the most sense to run them as NFAs. Almost 100% of the time, they're just going to be prefix matches (or exact matches) anyway.

**Review by rmuir — APPROVED** [review]
Thanks for removing this: it is a killer.

A lot of these will just come out minimal-from-the-getgo with lucene, but minimizing is never necessary, and its very costly. Just look at how terrifying the code you deleted is :)

File: server/src/main/java/org/opensearch/indices/SystemIndices.java (hunk 1 above)
Comment (rmuir) [reply server/src/main/java/org/opensearch/indices/SystemIndices.java:150]: The one area i'd say to take caution would be: multiple threads. So this is just a note, something to think about, as it requires some thought.

NFARunAutomaton is mutable and determinizes pieces "as-it-goes" and caches its work. This is different from existing RunAutomaton which is simple immutable arrays.

**Comment by reta** [comment]
Thanks @msfroh , this one is solely on me: I brought it into 3.x line to unlock the Lucene 10 migration, thanks for cleaning things up!

File: server/src/main/java/org/opensearch/indices/SystemIndices.java (hunk 1 above)
Comment (msfroh) [reply server/src/main/java/org/opensearch/indices/SystemIndices.java:150]: Oh -- dang. Thanks a lot for the word of caution!

This `SystemIndices` is a singleton initialized on startup and gets called from all over the place. For example, in a `_bulk` request, each index name gets checked against the registered system index name patterns. Since we regularly process a bunch of bulk requests at once, the NFARunAutomaton would be a no-go.

It sounds like the `Operations.run()` approach is the one that won't blow up.

Of course, given that it's a one-time cost to determinize and tableize on startup, maybe that's the better choice if it shaves even a bit of effort at runtime?

Comment (rmuir) [reply server/src/main/java/org/opensearch/indices/SystemIndices.java:150]: Well nothing there will blow up. but tableizing the thing does have a memory cost. Maybe just keep it the same, for now.

I need to followup and investigate how much performance these RunAutomatons even buy us anymore vs Operations.run(). The (non-tableized) automata representation has become much more efficient, thanks to @mikemccand.

Originally "Automaton" was a typical inefficient java representation, and "RunAutomaton" would tableize it into efficient array, which gives you e.g. cache locality and all that. But now Automaton has that locality, it is represented by two arrays: `states[]` and `transitions[]`. 

So it is possible the entire RunAutomaton is just a waste of code and RAM and that we could nuke it: needs investigation.

**Review by dbwiddis — APPROVED** [review]

**Review by reta — APPROVED** [review]
