### PR TITLE
Segment Replication - Remove seqNo field from ReplicationCheckpoint and use UserData to transfer state.

### LINKED ISSUE #6588: [BUG] [Segment Replication] Error computing max seqNo from SegmentInfos.
**Describe the bug**
Segment replication relies on computing the max seqNo on primary shards so that the seqNo that is sent to replicas is accurate to what is in the infos.  However, this function breaks after deletes are merged away, moving the maxSeqNo back in time.

```
  1> java.lang.AssertionError: null
  1>    at org.opensearch.index.engine.Engine.getMaxSeqNoFromSearcher(Engine.java:317) ~[main/:?]
  1>    at org.opensearch.index.engine.Engine.getMaxSeqNoFromSegmentInfos(Engine.java:291) ~[main/:?]
  1>    at org.opensearch.index.shard.RemoteStoreRefreshListener.uploadSegmentInfosSnapshot(RemoteStoreRefreshListener.java:182) ~[main/:?]
```

This functionality was introduced to pass an accurate seqNo to replicas to
1. pass an accurate seqNo to `setLocalCheckpointOfSafeCommit`, to determine where xlog should be trimmed after a commit is received.
2. Update the replica's processed seqNo.

**To Reproduce**
1. Start a cluster with SR
3. index some documents
4. Delete a portion of the documents.
5. Trigger a force merge.

**Expected behavior**
Replicas should be sent accurate seqNo as computed by the primary.  One way to avoid this is to send only max seqNo as set in userdata by primaries on commit.  On a refresh level this means replica's processed seqNo would not update.

### PR DESCRIPTION
**Pull request by mch2**
### Description
This change removes the seqNo field from ReplicationCheckpoint.  This seqNo is only used on the replica to mark the `setLocalCheckpointOfSafeCommit` used to mark at which point the xlog can be deleted and advance the processed seqNo.  This logic was incorrectly attempting to fetch a max by querying the SegmentInfos directly, which would be incorrectly set after delete operations to a lower value.

Rather than relying on this seqNo, we can safely use the max seqNo of the previous commit point to advance both operations.  For xlog purge, we will continue to purge after a commit is received from the primary and only purge up to the max, which is guaranteed to be in the set of fsynced segments.  For the processed seqno, this ensures that if the replica is promoted primary it continues to replay ops from the xlog starting from this seqNo.

### Issues Resolved
closes #6588

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dreamer-89** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/12152/
> * **CommitID:** [008d466](https://github.com/opensearch-project/OpenSearch/commit/008d466b51839855a86a1ffd324347e61470ef54)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

`testReplicaRestarts` test failure. Looks related to change. 
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.shard.SegmentReplicationIndexShardTests.testReplicaRestarts" -Dtests.seed=2DD7A61971AF88AB -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nb-NO -Dtests.timezone=Poland -Druntime.java=19

org.opensearch.index.shard.SegmentReplicationIndexShardTests > testReplicaRestarts FAILED
    java.lang.AssertionError: expected:<2> but was:<-1>
        at __randomizedtesting.SeedInfo.seed([2DD7A61971AF88AB:D1A5CBB3F240A6A0]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.index.shard.SegmentReplicationIndexShardTests.assertDocCounts(SegmentReplicationIndexShardTests.java:1027)
        at org.opensearch.index.shard.SegmentReplicationIndexShardTests.testReplicaRestarts(SegmentReplicationIndexShardTests.java:613)
```

**Comment by mch2** [comment]
> > ### Gradle Check (Jenkins) Run Completed with:
> > 
> > * **RESULT:** FAILURE ❌
> > * **URL:** https://build.ci.opensearch.org/job/gradle-check/12152/
> > * **CommitID:** [008d466](https://github.com/opensearch-project/OpenSearch/commit/008d466b51839855a86a1ffd324347e61470ef54)
> >   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
> >   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?
> 
> `testReplicaRestarts` test failure. Looks related to change.
> 
> ```
> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.shard.SegmentReplicationIndexShardTests.testReplicaRestarts" -Dtests.seed=2DD7A61971AF88AB -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nb-NO -Dtests.timezone=Poland -Druntime.java=19
> 
> org.opensearch.index.shard.SegmentReplicationIndexShardTests > testReplicaRestarts FAILED
>     java.lang.AssertionError: expected:<2> but was:<-1>
>         at __randomizedtesting.SeedInfo.seed([2DD7A61971AF88AB:D1A5CBB3F240A6A0]:0)
>         at org.junit.Assert.fail(Assert.java:89)
>         at org.junit.Assert.failNotEquals(Assert.java:835)
>         at org.junit.Assert.assertEquals(Assert.java:647)
>         at org.junit.Assert.assertEquals(Assert.java:633)
>         at org.opensearch.index.shard.SegmentReplicationIndexShardTests.assertDocCounts(SegmentReplicationIndexShardTests.java:1027)
>         at org.opensearch.index.shard.SegmentReplicationIndexShardTests.testReplicaRestarts(SegmentReplicationIndexShardTests.java:613)
> ```

Yep, thought I had run these.  Removed that assertion that was tripping, it was asserting our processed seqNo was advanced on the replicas with every segment copy, which is now no longer guaranteed.  We still assert on searchable docs.

**Comment by mch2** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/12153/
> * **CommitID:** [2aa6d9d](https://github.com/opensearch-project/OpenSearch/commit/2aa6d9de12b98f43d4958742ff374aa53edb17d2)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationAllocationIT.testAllocationWithDisruption" -Dtests.seed=C9506E4BC22F9615 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-GT -Dtests.timezone=Pacific/Rarotonga -Druntime.java=19
NOTE: leaving temporary files on disk at: /var/jenkins/workspace/gradle-check/search/server/build/testrun/internalClusterTest/temp/org.opensearch.indices.replication.SegmentReplicationAllocationIT_C9506E4BC22F9615-001
NOTE: test params are: codec=Asserting(Lucene95): {index_uuid=Lucene90, type=PostingsFormat(name=Asserting)}, docValues:{}, maxPointsInLeafNode=1679, maxMBSortInHeap=7.955934483795881, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=es-GT, timezone=Pacific/Rarotonga
NOTE: Linux 5.15.0-1028-aws amd64/Eclipse Adoptium 19.0.2 (64-bit)/cpus=96,threads=1,free=368206256,total=656408576
NOTE: All tests run in this JVM: [ForceMergeBlocksIT, RemoveSettingsCommandIT, IndexRequestBuilderIT, SegmentReplicationAllocationIT]
```

Looks like a flaky unrelated test, that seed was not reproducible.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 1]
```diff
@@ -422,6 +422,68 @@ public void testDeleteOperations() throws Exception {
         }
     }
 
+    /**
+     * This tests that the max seqNo we send to replicas is accurate and that after failover
+     * the new primary starts indexing from the correct maxSeqNo and replays the correct count of docs
+     * from xlog.
+     */
+    public void testReplicationPostDeleteAndForceMerge() throws Exception {
```
Comment (dreamer-89) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:430]: Thank you @mch2 for this quick fix.
1. I am able to have this test pass successfully in my local without other changes. Is it possible to update this test so that it fails without your changes.
2. Not related to this test. Can we add unit tests that verify behaviour of seqNo with deletes & force merges ?

Comment (mch2) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:430]: 1 - hmm this is failing for me if i copy/paste to main as is with
```
三月 09, 2023 5:31:40 下午 com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
警告: Uncaught exception in thread: Thread[#83,opensearch[node_t0][flush][T#1],5,TGRP-SegmentReplicationIT]
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([BC702393CD92400E]:0)
	at org.opensearch.index.engine.Engine.getMaxSeqNoFromSearcher(Engine.java:317)
	at org.opensearch.index.engine.Engine.getMaxSeqNoFromSegmentInfos(Engine.java:291)
	at org.opensearch.index.shard.IndexShard.lambda$getLatestSegmentInfosAndCheckpoint$7(IndexShard.java:1492)
```.

2. Hmm this issue is happening because we were previously invoking `engine.getMaxSeqNoFromSegmentInfos` from the latest SegmentInfos.  I don't see any issue/change with that method's functionality, only that we were using it when we shouldn't have.  So I think this IT better tests for this case?

**Comment by dreamer-89** [comment]
> > ### Gradle Check (Jenkins) Run Completed with:
> > 
> > * **RESULT:** FAILURE ❌
> > * **URL:** https://build.ci.opensearch.org/job/gradle-check/12153/
> > * **CommitID:** [2aa6d9d](https://github.com/opensearch-project/OpenSearch/commit/2aa6d9de12b98f43d4958742ff374aa53edb17d2)
> >   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
> >   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?
> 
> ```
> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationAllocationIT.testAllocationWithDisruption" -Dtests.seed=C9506E4BC22F9615 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-GT -Dtests.timezone=Pacific/Rarotonga -Druntime.java=19
> NOTE: leaving temporary files on disk at: /var/jenkins/workspace/gradle-check/search/server/build/testrun/internalClusterTest/temp/org.opensearch.indices.replication.SegmentReplicationAllocationIT_C9506E4BC22F9615-001
> NOTE: test params are: codec=Asserting(Lucene95): {index_uuid=Lucene90, type=PostingsFormat(name=Asserting)}, docValues:{}, maxPointsInLeafNode=1679, maxMBSortInHeap=7.955934483795881, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=es-GT, timezone=Pacific/Rarotonga
> NOTE: Linux 5.15.0-1028-aws amd64/Eclipse Adoptium 19.0.2 (64-bit)/cpus=96,threads=1,free=368206256,total=656408576
> NOTE: All tests run in this JVM: [ForceMergeBlocksIT, RemoveSettingsCommandIT, IndexRequestBuilderIT, SegmentReplicationAllocationIT]
> ```
> 
> Looks like a flaky unrelated test, that seed was not reproducible.

I see this test fails [here](https://github.com/mch2/OpenSearch/blob/6588/server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java#L191) while asserting per index primary balance is maintained when one-third nodes are stopped. I think this can fail in certain scenarios which restricts primary shard movement to nodes already containing replica copies (due to `SameShardAllocationDecider`). Will raise a PR to fix this.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 1 above)
Comment (dreamer-89) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:430]: 1. Sorry, i was not clear above. I was testing in `2.x` branch, i see it passes. I verified it fails on `main` with similar assertion as you pasted above.
2. Yes, make sense.

**Review by dreamer-89 — APPROVED** [review]
LGTM!
