### PR TITLE
[Batch Fetch] Fix for hasInitiatedFetching to fix allocation explain and manual reroute APIs

### LINKED ISSUE #14903: [BUG] [Batch Mode] Allocation explain API is stuck in AWAITING_INFO even though deciders are returning NO
### Describe the bug

- Allocation explain API is stuck in AWAITING_INFO for some shards even when the deciders are returning NO
- In this case, allocation explain should return NO decision because we already know deciders are returning NO.  Instead , the API ends up calling `AsyncShardFetch.asyncFetch()` which it should not do.
- We will see that this also impacts manual reroute flows, leading to an unnecessary `AsyncShardFetch.asyncFetch()` call.

Both these issues are happening because `ShardsBatchGatewayAllocator.InternalReplicaBatchShardAllocator.hasInitiatedFetching()` function is not correctly implemented, and always returns true.

### Why does hasInitiatedFetching always return true?

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L518-L521

`hasInitiatedFetching()` function checks if a batchId exists for a shard.

However, this will always be true, because the batchId is defined for the shard before this function is ever called.

### Flow for allocation explain API

Here we will explain the flow, show why `hasInitiatedFetching()` always returns true, and how that causes allocation explain API to return AWAITING_INFO instead of NO.

Assume that we have a replica shard for which deciders are returning a NO decision [could be due to low disk, too many replicas], and allocation explain API is called for this shard.

Begin at this code path:
https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L384-L398

Here we see `createAndUpdateBatches()` is called first

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L224

In this function, we assign a batchId for all unassigned shards, and create a new one if required.
At this point, every unassigned shard would have a valid batch id.

Then we call `makeAllocationDecision()`

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L396

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L104-L112

This creates a fetchData supplier, and passes it to `getUnassignedShardAllocationDecision()`

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L171-L197

Line 183 checks `hasInitiatedFetching()`, since `explain=true` and deciders are returning NO:
https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L183

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L518-L521

`hasInitiatedFetching()` checks if a shard has a valid batch ID, which will always be true at this point, as we have previously established.

So we go into this block and call `fetchData()`: 

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L192-L195

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java#L180

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java#L257-L274

`AsyncShardFetch.fetchData()` triggers an `asyncFetch()` and returns the fetcher object. At this point, the fetching  would have just started in async manner. So we don't have any data from the nodes yet, so the `nodeShardStores` is null.

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L194

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java#L231-L247

Since `nodeShardStores` is null, we return `FETCHING_SHARD_DATA` as the final result, which internally maps to `AWAITING_INFO`. This is why we see the `AWAITING_INFO` result instead of a NO result in allocation explain API the first time.

Eventually, when all the nodes respond and the async fetch finally completes (could be seconds or minutes later), `onResponse()` of `asyncFetch()` is called which calls `processAsyncFetch()`

Here we trigger a new reroute, this time with `explain=false`:

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java#L220-L235

This eventually calls `allocateUnassignedBatch()` - decides which shards are eligible or ineligible and calls fetchData accordingly.

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L120-L138

To decide if the shard is eligible, it calls `getUnassignedShardAllocationDecision()`

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L171-L197

This time, this expression evaluates to TRUE because `explain=false`, so the function returns NO, and the shard is marked ineligible.
This is expected behaviour - when deciders return NO, the shard should be ineligible, so this is fine.

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L183

After this loop completes, we call `InternalReplicaBatchShardAllocator.fetchData()`, with this shard being marked as ineligible:

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L138

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L484-L499

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L524

In the above code, we remove all the ineligible shards from the batch, which also wipes the shard entry from the batch cache:

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L634-L640

So any information about this shard is now removed from the batch cache. So all the work from the previous fetchData also goes to waste.

So when we call allocation explain a second time, the cache will be empty, we will again restart the whole flow and return `AWAITING_INFO` forever...

### Flow for manual reroute

The flow for manual reroute is affected in a very similar way.

When we call manual reroute API, the first API call is made with `explain=true`. This is hardcoded in the logic for manual reroutes.
Assume again that deciders are returning NO decision for our replica shard for any reason.

We will start with this entry point for the flow:

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L197-L221

We check for replica shard eligibility here:

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L126-L135

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L183-L191

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L183

Now because `hasInitiatedFetching` returns true, the entire expression above returns False and the function `getUnassignedShardAllocationDecision()` returns null.

So we mark the shard as eligible. 
** This is wrong. At this point, we already know the deciders are returning NO, so the shard should not have been marked eligible **

Because we incorrectly mark the shard as eligible, we trigger `fetchData()` here, which eventually calls `AsyncShardFetch.fetchData()`:

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L138

This again triggers a second reroute, this time with `explain = false` [hardcoded].

Now in the second reroute, because `explain = false`, the shard is correctly marked as ineligible and is wiped from the cache.

So essentially we triggered the first fetchData and second reroute for no reason - The first reroute should have returned NO decision without ever calling fetchData, and we should have never called a second reroute.

### FIX

We need to fix `hasInitiatedFetching()` function to correctly check if fetching has happened at least once or not.
The implementation in non batch mode is correct so we see these issues.

The only case where we SHOULD call `AsyncShardFetch.fetchData()` for decision = NO, is when we already have the data from all nodes available in the cache. This way we know that when we call `AsyncShardFetch.fetchData()`, it won't trigger a new `AsyncShardFetch.asyncFetch()` because all the nodes in the cache will have an entry

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java#L146

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java#L172-L181

Essentially, in allocation explain or reroute flow for shards with decision=NO, we should only call `AsyncShardFetch.fetchData()` when we know that the cache already has the data, so we can guarantee a new `asyncFetch` would not get triggered for this ineligible shard. 

The only point of using the data from the node cache in this case, is that we can also populate shard store info for each node along with the NO decision.

When we call `getAllocationDecision()` with this non empty cache, this function will augment the number of  matching bytes that are there on each node for a specific shard. This gets appended to the NO decision here:

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java#L231

https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java#L271-L287

Check `augmentExplanationsWithStoreInfo()` for more details about this: https://github.com/opensearch-project/OpenSearch/blob/130500218a794f15df522c3ba5a31acbc77209e4/server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java#L377-L393

### Related component

Cluster Manager

### To Reproduce

1. Create a cluster with 1 master node and 5 data nodes and batch mode on
2. Create an index with 1 primary and 4 replicas
3. Stop one data node, now the cluster will go yellow
4. Call allocation/explain API for this yellow shard
5. Allocation explain API will return AWAITING_INFO.

### Expected behavior

Allocation explain API should return NO and not get stuck in AWAITING_INFO

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by rahulkarajgikar**
### Description
This change fixes the bug in `hasInitiatedFetching()` where it always returns true in batch mode, causing allocation explain to show `AWAITING_INFO` even for shards for which decider is returning NO.

The idea here is we want to populate shard store information (number of matching bytes per node) IN ADDITION to the decision made by deciders.
This function is meant to check if it is possible to get the above information, without triggering a new asyncFetch.

The intended behaviour is for this function to return true if a fetch has ever happened before, or is ongoing for a batch.
It should return false if there has never been a fetch for this batch.
This is so that it does not trigger a new asyncFetch call, but also uses the data from existing ones or wait for ongoing ones to populate shard store info.

Details of above points are mentioned in [#14903]

We start by comparing batch mode vs non-batch mode implementations.

Non-batch mode logic for deciding if shard is eligible for fetching

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java#L202-L228

Batch mode logic for deciding if shard is eligible for fetching - logic is same.

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java#L171-L196

`hasInitiatedFetching()` has a different implementation though - this is the key difference. In non batch-mode it works as intended, but in batch mode it always returns true.

#### Implementation in non-batch mode:

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/GatewayAllocator.java#L351-L353

Here, we check if `asyncFetchStore` has an entry for this `shardId`.
The intention here is to check if `fetchData()` call has ever happened for this shard before.

`asyncFetchStore` entries are populated as part of `GatewayAllocator$InternalReplicaShardAllocator.fetchData()`
We are essentially using the fact that if `GatewayAllocator$InternalReplicaShardAllocator.fetchData()` was ever called for this shard, then `asyncFetchStore` would have an entry

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/GatewayAllocator.java#L313-L355

For batch mode, we also need a similar idea - we need to know if `fetchData()` call has ever happened for this **batch** before.
Let's check the corresponding code for fetchData in batch mode and see if there is any property we can check to establish this fact.

#### Implementation in batch mode: 

Corresponding to `asyncFetchStore` in non-batch mode, we have `batchIdToStoreShardBatch`.
However, the logic in batch mode is different, this structure `batchIdToStoreShardBatch` is defined when we create the batches, which happens before any fetching/assignment logic is called. 

Reroute flow:
https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L238-L241

Allocation explain flow:
https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L444-L458

Batch creation logic:

Line 349 - `addBatch` updates this `batchIdToStoreShardBatch` with the entry.
https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L333-L355

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L381-L387

Since `batchIdToStoreShardBatch` is getting updated before `fetchData()`, we cannot use it to determine if fetching has happened before.

Corresponding to `GatewayAllocator$InternalReplicaShardAllocator.fetchData()` in non-batch mode,  we have `ShardsBatchGatewayAllocator$InternalReplicaBatchShardAllocator.fetchData()` in batch mode.
Let's check the implementation of this function in batch mode to see if there are other ways.

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L561-L575

Nothing we can use here either:
https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java#L584-L627

In the case the batch is empty or all nodes are ignored, `asyncFetcher.fetchData()` will not get called. 
If the batch is non empty, then `asyncFetcher.fetchData()` will get called. (line 619)

`asyncFetcher` is of type `AsyncShardBatchFetch` which extends `AsyncShardFetch` class, but does not override `fetchData()`. So we can check `AsyncShardFetch.fetchData()` for the exact implementation here.

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java#L146

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java#L172-L181

We can see in lines 172 that the batch cache entries are created for any missing nodes here.
In line 173, we see if any node still needs to be fetched.
And if so, we mark those nodes as fetching and trigger `asyncFetch()`

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/AsyncShardBatchFetch.java#L94

Structure of batch cache ^

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/AsyncShardFetchCache.java#L94-L103

`initData()` has custom implementation for batch cache:

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/AsyncShardBatchFetch.java#L141-L144

So if this code has run and triggered the async Fetch, we can conclude that the following statements will be true:

1.  The batch cache will be non empty and have at least 1 entry. 
2. All nodes currently part of the cluster will either have data in the cache already, or be marked as fetching and have a fetch ongoing. 

So we can use these 2 facts as an invariant to see if any async fetching has actually happened before for a batch.
We add checks for these 2 facts in `hasInitiatedFetching()` to validate if a fetch has happened before or not.

To check 1, we use:

```
if (shardsBatch.getAsyncFetcher().hasEmptyCache()) {
                logger.trace("Batch cache is empty for batch {} ", batchId);
                return false;
}
```

To check 2, we use the `findNodesToFetch()` function. 

This function returns all nodes that have no data and also have no fetches initiated. So if we have a case where this function returns even 1 node, we can say return false from `hasInitiatedFetching()`,  because we don't info from all nodes to populate all the shard store information.

https://github.com/opensearch-project/OpenSearch/blob/fcc231dfc349e092c3f68e49f49e32a062313f71/server/src/main/java/org/opensearch/gateway/AsyncShardFetchCache.java#L109-L117

### Related Issues
Resolves #14903

### Check List
- [Y] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### Testing

Added a new UT for batch mode and non batch mode to simulate allocation explain case.
Verified that allocation explain returns `NO` decision and does not show `AWAITING_INFO`.

Also manually tested manual reroutes on a 15 data node, 3 master node setup, and verified that shards with decision NO are not getting added to the batches now.

To repro this:
 - Create a cluster with 15 data nodes, 3 master nodes
 - Create an index with 1 primary and 14 replicas
 - After cluster goes green, shut down 1 node
 - Cluster should go yellow now. Run allocation explain - it should show decision NO.
 - Run manual reroute, no asyncFetch() should get triggered. (verified with `inFlightFetches` metric and arthas profiling)

### CODE REVIEW

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java [hunk 1]
```diff
@@ -516,8 +516,33 @@ protected AsyncShardFetch.FetchResult<TransportNodesListShardStoreMetadataBatch.
...
+            logger.trace("Checking if fetching done for batch id {}", batchId);
+            ShardsBatch shardsBatch = shard.primary() ? batchIdToStartedShardBatch.get(batchId) : batchIdToStoreShardBatch.get(batchId);
+
+            // if fetchData has never been called, the per node cache will be empty and have no nodes
+            // this is because cache.fillShardCacheWithDataNodes(nodes) initialises this map and is called in AsyncShardFetch.fetchData
+            if (shardsBatch.getAsyncFetcher().hasEmptyCache()) {
+                logger.trace("Batch cache is empty for batch {} ", batchId);
+                return false;
+            }
+            // this check below is to make sure we already have all the data and that we wouldn't create a new async fetchData call
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:544]: if we have all the data from previous fetch, then also it should be true

Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:544]: We are checking that in the below line 

`return shardsBatch.getAsyncFetcher().getCache().findNodesToFetch().isEmpty();`

This would return true if we have all the data from previous fetch, or if fetch has just triggered

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java [hunk 2]
```diff
@@ -516,8 +516,33 @@ protected AsyncShardFetch.FetchResult<TransportNodesListShardStoreMetadataBatch.
...
+             *
+             * In order to check if a fetch has ever happened, we check 2 things:
+             * 1. If the shard batch cache is empty, we know that fetch has never happened so we return false.
+             * 2. If we see that the list of nodes to fetch from is empty, we know that all nodes have data or are ongoing a fetch. So we return true.
+             * 3. Otherwise we return false.
+             *
+             * see {@link AsyncShardFetchCache#findNodesToFetch()}
+             */
             String batchId = getBatchId(shard, shard.primary());
-            return batchId != null;
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:520]: Can we add to the above comment - What is the case that the shard has batch assigned but fetch is not ongoing ? 

Do we also need to fix [here](https://github.com/rajiv-kv/OpenSearch/blob/63f4f1397f2e47e717f8797eae1e6516360c4052/server/src/main/java/org/opensearch/gateway/GatewayAllocator.java#L351) in the other implementation ?

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 1 above)
Comment (rajiv-kv) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:544]: Could there be a case where some of the nodes are not yet initialized in the Cache. I see it used in tandem in other place where this method is used

```
        cache.fillShardCacheWithDataNodes(nodes);
        List<String> nodeIds = cache.findNodesToFetch();
```

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java [hunk 3]
```diff
@@ -516,8 +516,33 @@ protected AsyncShardFetch.FetchResult<TransportNodesListShardStoreMetadataBatch.
...
+            logger.trace("Checking if fetching done for batch id {}", batchId);
+            ShardsBatch shardsBatch = shard.primary() ? batchIdToStartedShardBatch.get(batchId) : batchIdToStoreShardBatch.get(batchId);
+
+            // if fetchData has never been called, the per node cache will be empty and have no nodes
+            // this is because cache.fillShardCacheWithDataNodes(nodes) initialises this map and is called in AsyncShardFetch.fetchData
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:539]: Can there be a race condition b/w `fillShardCacheWithDataNodes` and `hasEmptyCache` ?

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 1 above)
Comment (shwetathareja) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:544]: is if (shardsBatch.getAsyncFetcher().hasEmptyCache()) { enough. do we need the check on line no. 545?

Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:544]: @shwetathareja I don't think it's enough. There might be a case where the cache has entries for all nodes except a few (say node joined or node left).

 We need to verify that every node has had a fetchData before or in progress - so that In this case, the cache would not be empty, but it would still have entries missing for a few nodes.

Whenever this method is called, we need to make sure we don't trigger a new asyncFetch at all. We want to only use the existing data available to populate the shard store information along with allocation decision NO/THROTTLE.
What we actually want to check is that if we called fetchData now, would it trigger a new asyncFetch.

So in a case like this, we need to also see if **every node** has an entry or has a fetch ongoing - we shouldn't just rely on the cache being empty or not, because it doesn't give the full picture of all the nodes.

Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:544]: @rajiv-kv yeah in this function we are essentially relying on the fact that this code below has run before.
I've mentioned details about this in the PR description.

`hasInitiatedFetching` is more of a check to see if every node has completed or initiated fetching

```        
cache.fillShardCacheWithDataNodes(nodes);
List<String> nodeIds = cache.findNodesToFetch();
```

If some nodes are not initialised in the cache, it means that `cache.findNodesToFetch()` would return a non empty list. In this case, it means our cache does not have all the info available, so if we were to call `fetchData`, it would trigger a new `asyncFetch`. 

We don't want to trigger a new asyncFetch in allocation explain API in this case. So `hasInitiatedFetching` function should return false so that we exit early with decision NO.

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 3 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:539]: i don't think such a race condition is likely - it would require very specific timing of the APIs since only manual rereoutes and allocation explain apis would call this flow.
We have very similar code in non batch mode, which also relies on the fact that a map has entries. Race condition should not be any more more likely than it was in the non-batch mode implementation.


Even if there is, the impact of returning an incorrect false, would be that we don't populate shard store information in allocation explain API, when we can actually just wait for the fetch to complete. So the impact is very minimal.

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java [hunk 4]
```diff
@@ -925,6 +925,202 @@ public void testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentN
...
+        logger.info("--> restarting the stopped node");
+        internalCluster().startDataOnlyNode(
+            Settings.builder().put("node.name", nodesWithReplicaShards.get(0)).put(replicaNodeDataPathSettings).build()
+        );
+
+        ensureStableCluster(6);
+        ensureGreen("test");
+
+        logger.info("--> calling allocation explain API 3rd time");
+        // shard should still have decision NO because there are 6 replicas and 5 data nodes
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:1006]: it is 5 datanodes totally.

We previously stopped one, so we had 4. Now we restarted it, so we have 5 again

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java [hunk 5]
```diff
@@ -925,6 +925,202 @@ public void testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentN
...
+        List<String> nodesWithReplicaShards = findNodesWithShard(false);
+        Settings replicaNodeDataPathSettings = internalCluster().dataPathSettings(nodesWithReplicaShards.get(0));
+        internalCluster().stopRandomNode(InternalTestCluster.nameFilter(nodesWithReplicaShards.get(0)));
+
+        ensureStableCluster(5);
+        ensureYellow("test");
+
+        logger.info("--> calling allocation explain API");
+        // shard should have decision NO because there is no valid node for the extra replica to go to
+        assertEquals(
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:957]: Ack will see if this can be done

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 3 above)
Comment (rajiv-kv) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:539]: Got it. So this the best-effort of not intitiating the fetch again.

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (rajiv-kv) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:1006]: I see ` ensureStableCluster(6);` in line 1002 above

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 1 above)
Comment (rajiv-kv) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:544]: I think it is fair to assume that node-join and node-left will keep the node-list updated in cache.
However there is also a updated node-list in the input(`RoutingAllocation#nodes`) that can be used to compare against the cache to avoid staleness.

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 2 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:520]: Sure can update the comment.

We don't need to fix in the older implementation, because the older implementation checks for an object that is created when fetchData is called, not before. [Details are in the PR/issue description]

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 1 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:544]: Makes sense. I think in most cases, it should be fair to assume that `if(shardsBatch.getAsyncFetcher().hasEmptyCache())` check is sufficient since the nodes list will be updated.
I had just added this extra check to be 100% sure we don't trigger any new `asyncFetch`

On the `RoutingAllocation#nodes` suggestion, are you suggesting that in addition to this, we also check to see if the `RoutingAllocation#nodes` object has any new nodes compared to the list of nodes in the cache?

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:1006]: Yeah it is 1 master node + 5 data nodes

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 3 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:599]: Yes

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 2 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:580]: updated the comment

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java]: added this assertion

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 1 above)
Comment (rajiv-kv) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:606]: Yes i was thinking of checking instead of `findNodesToFetch`. Something like

```allocation#nodes.foreach{node-> cache.hasFetchData(node)}```

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java [hunk 6]
```diff
@@ -797,7 +798,9 @@ public void testBatchModeEnabledWithoutTimeout() throws Exception {
         );
         assertTrue(ExistingShardsAllocator.EXISTING_SHARDS_ALLOCATOR_BATCH_MODE.get(internalCluster().clusterService().getSettings()));
         assertEquals(1, gatewayAllocator.getNumberOfStartedShardBatches());
-        assertEquals(1, gatewayAllocator.getNumberOfStoreShardBatches());
+        // Replica shard would be marked ineligible since there are no data nodes.
+        // It would then be removed from any batch and batches would get deleted, so we would have 0 replica batches
+        assertEquals(0, gatewayAllocator.getNumberOfStoreShardBatches());
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:803]: After starting one datanode and cluster turning yellow, can we validate for 0 started and stored shards ? Could we also add asserts on the Reroute explain `clusterRerouteResponse` ?

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java [hunk 7]
```diff
@@ -797,7 +798,9 @@ public void testBatchModeEnabledWithoutTimeout() throws Exception {
         );
         assertTrue(ExistingShardsAllocator.EXISTING_SHARDS_ALLOCATOR_BATCH_MODE.get(internalCluster().clusterService().getSettings()));
         assertEquals(1, gatewayAllocator.getNumberOfStartedShardBatches());
-        assertEquals(1, gatewayAllocator.getNumberOfStoreShardBatches());
+        // Replica shard would be marked ineligible since there are no data nodes.
+        // It would then be removed from any batch and batches would get deleted, so we would have 0 replica batches
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:802]: Can we add another testcase where we mark the batch as `fetching=true` before calling reroute ?

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java [hunk 8]
```diff
@@ -576,8 +576,35 @@ protected AsyncShardFetch.FetchResult<TransportNodesListShardStoreMetadataBatch.
...
+             * 1. If the shard batch cache is empty, we know that fetch has never happened so we return false.
+             * 2. If we see that the list of nodes to fetch from is empty, we know that all nodes have data or are ongoing a fetch. So we return true.
+             * 3. Otherwise we return false.
+             *
+             * see {@link AsyncShardFetchCache#findNodesToFetch()}
+             */
             String batchId = getBatchId(shard, shard.primary());
-            return batchId != null;
+            logger.trace("Checking if fetching done for batch id {}", batchId);
+            ShardsBatch shardsBatch = shard.primary() ? batchIdToStartedShardBatch.get(batchId) : batchIdToStoreShardBatch.get(batchId);
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:601]: Added null check for both

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java [hunk 9]
```diff
@@ -1051,6 +1058,196 @@ public void testMultipleReplicaShardAssignmentWithDelayedAllocationAndDifferentN
...
+        assertEquals(AllocationDecision.NO, aud.getAllocationDecision());
+        assertEquals("cannot allocate because allocation is not permitted to any of the nodes", aud.getExplanation());
+
+        internalCluster().startDataOnlyNodes(1);
+
+        ensureStableCluster(7);
+        ensureGreen("test2");
+    }
+
+    public void testAllocationExplainReturnsNoWhenExtraReplicaShardInBatchMode() throws Exception {
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:1093]: Done

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java (hunk 6 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:803]: Done

File: server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java (hunk 1 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java:608]: Got it.

I checked the node join and node left flows again.
They are triggered with `explain=false` so `hasInitiatedFetching()` would not get triggered.
They are also URGENT priority tasks, so they would keep the nodes up to date.

I think we don't need to check for stale nodes as of now and the current implementation is fine - we just assume that the nodes list is up to date in the cache and check that every node has an entry, or is actively fetching.

If we do see an edge case for this with node-joins/node-lefts , maybe we can take it up as a follow up issue.

**Comment by rahulkarajgikar** [comment]
Failing tests in gradle check are flaky:

#14311 
#12408 

```
org.opensearch.http.SearchRestCancellationIT.testAutomaticCancellationDuringFetchPhase
org.opensearch.indexing.IndexActionIT.testAutoGenerateIdNoDuplicates {p0={"cluster.indices.replication.strategy":"SEGMENT"}}
```

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java (hunk 7 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:802]: This doesn't seem possible. I don't think we can mock the batch to force it to have `fetching=true` in an IT.

Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:802]: I am trying to simulate blocking the `asyncFetch` in a similar manner to this test: 
https://github.com/rajiv-kv/OpenSearch/blob/7ffcd6500e0bd5956cef5c289ee66d9f99d533fc/server/src/internalClusterTest/java/org/opensearch/gateway/ReplicaShardAllocatorIT.java#L167

Will take this up as a follow up issue as it does not seem trivial to simulate this case

**Comment by rahulkarajgikar** [comment]
Issue already exists for flaky test:

#12802

**Review by rajiv-kv — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java [hunk 10]
```diff
@@ -797,11 +798,26 @@ public void testBatchModeEnabledWithoutTimeout() throws Exception {
         );
         assertTrue(ExistingShardsAllocator.EXISTING_SHARDS_ALLOCATOR_BATCH_MODE.get(internalCluster().clusterService().getSettings()));
         assertEquals(1, gatewayAllocator.getNumberOfStartedShardBatches());
-        assertEquals(1, gatewayAllocator.getNumberOfStoreShardBatches());
+        // Replica shard would be marked ineligible since there are no data nodes.
+        // It would then be removed from any batch and batches would get deleted, so we would have 0 replica batches
+        assertEquals(0, gatewayAllocator.getNumberOfStoreShardBatches());
```
Comment (shwetathareja) [inline server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java:803]: can we run this IT locally in a loop to ensure no flakiness.

**Review by shwetathareja — APPROVED** [review]
