### PR TITLE
[Segment Replication] Ensure replica's store always contains the previous commit point.

### LINKED ISSUE #2331: [Segment Replication] - Fix corrupt index when verifying after file copy.
**Describe the bug**
The SegmentInfos object on primaries can be newer (after index or merge) compared to the segments_N file written to disk.  We are currently deleting segment files based off of a metadata list sent back from primary shards that is generated from the in memory SegmentInfos.  After files are copied we verify the index by reading the on disk segments_N file.  In the event this file is behind the SegmentInfos in memory, this throws an exception because we have deleted files still referenced by the file.

We should update ReplicationTarget to include segments referenced by the on disk Segments_N during deletion.

### PR DESCRIPTION
**Pull request by mch2**
### Description
This change:
1. Updates the cleanup and validation steps on replicas after a replication event occurs to prevent deleting files that are still required by the latest commit point.
2. Computes and sends replicas a list of recently merged away files that are still referenced by the primary's latest commit point.  This allows replicas to fetch these files if not present locally.  This can happen when a replica falls multiple commit points behind or if it starts after a primary has already existed and is in this state.
3. Update initial recovery sequence of replicas to copy from primary before lighting up as active.  This fixes bug where replicas could not be added after primary.
4. Prevent replicas from attempting to a force merge if segrep is enabled.

 
### Issues Resolved
closes #2331 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by Poojita-Raj — APPROVED** [review]

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 1]
```diff
@@ -56,4 +63,63 @@ public void testReplicationAfterPrimaryRefreshAndFlush() throws Exception {
...
+        final String nodeB = internalCluster().startNode();
+        createIndex(INDEX_NAME);
+        ensureGreen(INDEX_NAME);
+
+        final int initialDocCount = scaledRandomIntBetween(0, 200);
+        try (BackgroundIndexer indexer = new BackgroundIndexer(INDEX_NAME, "_doc", client(), initialDocCount)) {
+            waitForDocs(initialDocCount, indexer);
+        }
+        flush(INDEX_NAME);
+        Thread.sleep(1000);
```
[the remark this answers is not in the document]
Comment (mch2) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:78]: This is to ensure the replication event triggered after the flush has a chance to complete before we assert the doc counts on the replica.  Without this there is a slim chance this could happen even though there is no network latency in the test.

File: server/src/main/java/org/opensearch/index/store/Store.java [hunk 2]
```diff
@@ -700,6 +700,49 @@ public void cleanupAndVerify(String reason, MetadataSnapshot sourceMetadata) thr
...
+     * @param remoteSnapshot The remote snapshot sent from primary shards.
+     * @param localSnapshot  The local snapshot from in memory SegmentInfos.
+     * @throws IllegalStateException if the latest snapshot in this store differs from the given one after the cleanup.
+     */
+    public void cleanupAndVerify(String reason, MetadataSnapshot remoteSnapshot, MetadataSnapshot localSnapshot) throws IOException {
+        // fetch a snapshot from the latest on disk Segments_N file. This can be behind
+        // the passed in local in memory snapshot, so we want to ensure files it references are not removed.
+        final Store.MetadataSnapshot latestCommitPointMetadata = getMetadata((IndexCommit) null);
+        metadataLock.writeLock().lock();
+        try (Lock writeLock = directory.obtainLock(IndexWriter.WRITE_LOCK_NAME)) {
```
[the remark this answers is not in the document]
Comment (mch2) [reply server/src/main/java/org/opensearch/index/store/Store.java:717]: Yes, we don't need to explicitly release this because we are using [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html).  It will be closed automatically.

File: server/src/main/java/org/opensearch/indices/replication/SegmentReplicationReplicaService.java [hunk 3]
```diff
@@ -202,6 +204,31 @@ private void doReplication(final long replicationId) {
...
+     * @param replicationListener {@link ReplicationListener} listener.
+     */
+    public void startRecovery(
+        IndexShard indexShard,
+        DiscoveryNode targetNode,
+        DiscoveryNode sourceNode,
+        PrimaryShardReplicationSource replicationSource,
+        SegmentReplicationListener replicationListener
+    ) {
+        indexShard.markAsReplicating();
```
[the remark this answers is not in the document]
Comment (mch2) [reply server/src/main/java/org/opensearch/indices/replication/SegmentReplicationReplicaService.java:224]: This was moved to ReplicationTarget.  I'm not sure having `SegmentReplicationListener` responsible for this state change on the actual shard makes sense, it should only be reacting to a replication event completing.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 4]
```diff
@@ -3669,22 +3662,20 @@ public synchronized void onNewCheckpoint(
...
             logger.trace("Received new checkpoint {}", checkpoint);
-            // TODO: segrep - these are the states set after we perform our initial store recovery.
             segmentReplicationReplicaService.startReplication(
                 checkpoint,
                 this,
                 source,
                 new SegmentReplicationReplicaService.SegmentReplicationListener() {
                     @Override
                     public void onReplicationDone(SegmentReplicationState state) {
-                        markReplicationComplete();
```
[the remark this answers is not in the document]
Comment (mch2) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:3687]: I moved this to when ReplicationTarget's finalize method completes because I didn't like SegmentReplicationListener being responsible for marking it as complete.  With that said I think we can do better by moving it to the onDone/onCancel/onFail methods of SegmentReplicationTarget.  Will also move markAsReplicating to ReplicationTarget as well so these classes don't have to manage that.

[the remark this answers is not in the document]
Comment (mch2) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:3687]: cleaned this up in latest commit, what do you think?

File: server/src/main/java/org/opensearch/index/store/Store.java [hunk 5]
```diff
@@ -700,6 +700,49 @@ public void cleanupAndVerify(String reason, MetadataSnapshot sourceMetadata) thr
...
+            for (String existingFile : directory.listAll()) {
+                if (Store.isAutogenerated(existingFile)
+                    || remoteSnapshot.contains(existingFile)
+                    || latestCommitPointMetadata.contains(existingFile)) {
```
Comment (kartg) [inline server/src/main/java/org/opensearch/index/store/Store.java:721]: Most of the code in this method is identical to the existing `cleanupAndVerify` function. I would suggest reworking this to either:

1. A method that has hooks for the if-condition check and the cleanup steps, and passing in the relevant logic for segrep vs docrep

OR

2. Extracting the cleanup logic to its own class, with hooks for the if-condition and cleanup steps, and having the segrep implementation be a subclass

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (kartg) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:3687]: Wasn't the plan to move `markAsReplicating` to `ReplicationTarget` as well? Right now, that seems to be in `ReplicaService` so the lifecycle management is distributed across two classes, which smells. How do we improve this?

File: server/src/main/java/org/opensearch/indices/replication/checkpoint/TransportCheckpointInfoResponse.java [hunk 6]
```diff
@@ -11,38 +11,45 @@
...
 
 import java.io.IOException;
+import java.util.Set;
 
 public class TransportCheckpointInfoResponse extends TransportResponse {
 
     private final ReplicationCheckpoint checkpoint;
     private final Store.MetadataSnapshot snapshot;
     private final byte[] infosBytes;
+    private final Set<StoreFileMetadata> additionalFiles;
```
Comment (kartg) [inline server/src/main/java/org/opensearch/indices/replication/checkpoint/TransportCheckpointInfoResponse.java:26]: Nitpick - might be worth it to comment what `additionalFiles` is expected to contain

File: server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java [hunk 7]
```diff
@@ -165,7 +167,12 @@ public void messageReceived(StartReplicationRequest request, TransportChannel ch
             logger.trace("Received request for checkpoint {}", checkpoint);
             final CopyState copyState = getCopyState(checkpoint);
             channel.sendResponse(
-                new TransportCheckpointInfoResponse(copyState.getCheckpoint(), copyState.getMetadataSnapshot(), copyState.getInfosBytes())
+                new TransportCheckpointInfoResponse(
+                    copyState.getCheckpoint(),
+                    copyState.getMetadataSnapshot(),
+                    copyState.getInfosBytes(),
+                    copyState.getPendingDeleteFiles()
```
Comment (kartg) [inline server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java:174]: Nitpick - add a comment on why we're using the list of files pending delete as the additional files list

File: server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java [hunk 8]
```diff
@@ -228,7 +235,10 @@ public void messageReceived(TrackShardRequest request, TransportChannel channel,
                 throw new DelayRecoveryException("source node does not have the shard listed in its state as allocated on the node");
             }
             final StepListener<ReplicationResponse> addRetentionLeaseStep = new StepListener<>();
-            final StepListener<ReplicationResponse> responseListener = new StepListener<>();
+            final Consumer<Exception> onFailure = e -> {
+                assert Transports.assertNotTransportThread(this + "[onFailure]");
+                logger.error("Failure", e);
```
Comment (kartg) [inline server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java:240]: Why this change in behavior?

Also, better log message?

File: server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationTarget.java [hunk 9]
```diff
@@ -144,21 +177,31 @@ public void finalizeReplication(TransportCheckpointInfoResponse checkpointInfo,
...
                 }
-                final long segmentsGen = checkpointInfo.getCheckpoint().getSegmentsGen();
-                // force an fsync if we are receiving a new gen.
-                if (segmentsGen > indexShard.getLatestSegmentInfos().getGeneration()) {
-                    final Directory directory = store().directory();
-                    directory.sync(Arrays.asList(directory.listAll()));
-                }
-                indexShard.updateCurrentInfos(segmentsGen, checkpointInfo.getInfosBytes(), checkpointInfo.getCheckpoint().getSeqNo());
+
+                // Deserialize the new SegmentInfos object sent primary the primary.
```
Comment (kartg) [inline server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationTarget.java:188]: "sent _from_ the primary" ?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (kartg) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:78]: Might be worth adding that as a comment to explain why we're sleeping here

File: server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java (hunk 7 above)
Comment (mch2) [reply server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java:174]: updated TransportCheckpointInfoResponse to not generic & added detail there.

File: server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java (hunk 8 above)
Comment (mch2) [reply server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java]: The existing responseListener's onFailure was getting triggered but doing nothing.  This at least logs the error on the primary.  I've updated to also send the exception back to the replica.

**Comment by mch2** [comment]
> Outside of my review comments and the changes in this PR specifically, I wanted to put a high-level question - should we make the seg-rep tests more rigorous to validate the file structure on replica nodes to make sure they are consistent with the primary?
> 
> Our current asserts are around hit count, which seems largely sufficient given that our test case is checking if newly indexed documents show up on the replica. But it doesn't validate that the shards are point-in-time consistent

Good call.  I think we can do a decent comparison with the results of _cat/segments.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (kartg) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:3687]: Could you create a task to track it, so we don't forget?

File: server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java [hunk 10]
```diff
@@ -237,7 +237,13 @@ public void messageReceived(TrackShardRequest request, TransportChannel channel,
             final StepListener<ReplicationResponse> addRetentionLeaseStep = new StepListener<>();
             final Consumer<Exception> onFailure = e -> {
                 assert Transports.assertNotTransportThread(this + "[onFailure]");
-                logger.error("Failure", e);
+                logger.error("Error marking shard {} as tracked for allocation ID {}, {}", shardId, request.getTargetAllocationId(), e);
```
Comment (kartg) [inline server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java:240]: Nit - This seems wonky. Did you mean to print the exception string rather than dump the stack trace?

**Review by kartg — APPROVED** [review]

File: server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java (hunk 10 above)
Comment (mch2) [reply server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationPrimaryService.java]: oops good catch. Updated with ParameterizedMessage.
