### PR TITLE
[Segment Replication] Support realtime TermVector requests with Segment Replication

### LINKED ISSUE #9563: [BUG][Segment Replication] Support realtime reads with TermVector Requests for segrep enabled indices
**Describe the bug**
Currently with segment replication enabled reads with VectorTerm requests give incorrect results if the search request goes to replica shard before it has caught up with primary.

Integration tests in GetTermvectorsIT.java fail with segment replication enabled

```
java.lang.AssertionError: doc id: 9 doesn't exists but should
Expected: <true>
     but: was <false>
	at __randomizedtesting.SeedInfo.seed([F873E5CD32208FA6:279D1107D2CFBEED]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.opensearch.action.termvectors.GetTermVectorsIT.testSimpleTermVectors(GetTermVectorsIT.java:243)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**To Reproduce**
-> Enable segment replication
-> Run GetTermvectorsIT.java

`REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.action.termvectors.GetTermVectorsIT.testRandomSingleTermVectors" -Dtests.seed=F873E5CD32208FA6 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=pt-BR -Dtests.timezone=America/Rainy_River -Druntime.java=20`

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR supports realtime reads for TermVectors requests when segment replication is enabled.
If there are no preferences mentioned for the incoming TermVectors requests then we route it to primary shards

### Related Issues
Resolves #9563 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsRequest.java [hunk 1]
```diff
@@ -63,6 +63,8 @@ public class MultiTermVectorsRequest extends ActionRequest
         RealtimeRequest {
 
     String preference;
+
+    boolean realtime = true;
```
Comment (Poojita-Raj) [inline server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsRequest.java:67]: Not sure if we should introduce a variable for a setting that is not set by users. In this case, we will be setting it to true everytime which we need to investigate if it's needed.

File: server/src/main/java/org/opensearch/action/termvectors/TransportMultiTermVectorsAction.java [hunk 2]
```diff
@@ -123,6 +126,9 @@ protected void doExecute(Task task, final MultiTermVectorsRequest request, final
                 .shardId(clusterState, concreteSingleIndex, termVectorsRequest.id(), termVectorsRequest.routing());
             MultiTermVectorsShardRequest shardRequest = shardRequests.get(shardId);
             if (shardRequest == null) {
+                if (shouldForcePrimaryRouting(clusterState, request.realtime, request.preference, concreteSingleIndex)) {
```
Comment (Poojita-Raj) [inline server/src/main/java/org/opensearch/action/termvectors/TransportMultiTermVectorsAction.java:129]: Rebase this over #9536 once it's merged. Changing parameter to metadata instead of clusterState.

File: server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java [hunk 3]
```diff
@@ -53,6 +54,8 @@
 
 import java.io.IOException;
 
+import static org.opensearch.action.get.TransportGetAction.shouldForcePrimaryRouting;
```
Comment (Poojita-Raj) [inline server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java:57]: Not sure if we should be getting this from TransportGetAction. See if there's a common place we can move this method to for use in both classes.

File: server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsRequest.java (hunk 1 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsRequest.java]: Yes you are right. I also realized that MultiTermVectorsRequest itself cannot be a realtime request. So, there will be no point for us to route these to primary. So I have completely avoided routing MultiTermVectorsRequest to primary

File: server/src/main/java/org/opensearch/action/termvectors/TransportMultiTermVectorsAction.java (hunk 2 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/action/termvectors/TransportMultiTermVectorsAction.java]: Done

File: server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java (hunk 3 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java:57]: I don't see any common place like parent classes that all 3 (TransportGet, TransportMultiGet, TransportTermVector) of these uses.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 4]
```diff
@@ -1622,4 +1627,170 @@ public void testRealtimeMultiGetRequestsUnsuccessful() {
...
+        assertFalse(response.isExists());
+
+        // index doc 1
+        client().prepareIndex(INDEX_NAME)
+            .setId(Integer.toString(1))
+            .setSource(
+                jsonBuilder().startObject()
+                    .field("field", "the quick brown fox jumps over the lazy dog")
+                    // 0the3 4quick9 10brown15 16fox19 20jumps25 26over30
+                    // 31the34 35lazy39 40dog43
```
Comment (Poojita-Raj) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1671]: I didn't understand this comment - what is it for?

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 5]
```diff
@@ -1622,4 +1627,170 @@ public void testRealtimeMultiGetRequestsUnsuccessful() {
...
+            )
+            .execute()
+            .actionGet();
+
+        // non realtime termvectors 1
+        response = client().prepareTermVectors(indexOrAlias(), Integer.toString(1)).setRealtime(false).get();
+        assertFalse(response.isExists());
+
+        // realtime termvectors 1
+        TermVectorsRequestBuilder resp = client().prepareTermVectors(indexOrAlias(), Integer.toString(1))
```
Comment (Poojita-Raj) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1682]: Nit: mention `.setRealtime(true)` to be explicit about creating a realtime request

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 6]
```diff
@@ -1622,4 +1627,170 @@ public void testRealtimeMultiGetRequestsUnsuccessful() {
...
+        assertThat(fields.size(), equalTo(1));
+
+        // index doc 2 with routing
+        client().prepareIndex(INDEX_NAME)
+            .setId(Integer.toString(2))
+            .setRouting(id)
+            .setSource(
+                jsonBuilder().startObject()
+                    .field("field", "the quick brown fox jumps over the lazy dog")
+                    // 0the3 4quick9 10brown15 16fox19 20jumps25 26over30
```
Comment (Poojita-Raj) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1700]: same as above

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 7]
```diff
@@ -1622,4 +1627,170 @@ public void testRealtimeMultiGetRequestsUnsuccessful() {
...
+            .setPositions(true)
+            .setPreference(Preference.REPLICA.type())
+            .setSelectedFields();
+        response = resp.execute().actionGet();
+
+        assertFalse(response.isExists());
+        assertThat(response.getIndex(), equalTo(INDEX_NAME));
+
+        // realtime termvectors (with routing set)
+        resp = client(replica).prepareTermVectors(indexOrAlias(), Integer.toString(1))
```
Comment (Poojita-Raj) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:1783]: Just to confirm - so when routing is set, we don't want to reroute to primary for TermVectors?

The way shouldForcePrimaryRouting exists right now, we never examine the routing parameter when we decide to reroute to primary.

File: server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsRequest.java [hunk 8]
```diff
@@ -63,6 +63,7 @@ public class MultiTermVectorsRequest extends ActionRequest
         RealtimeRequest {
 
     String preference;
+
```
Comment (Poojita-Raj) [inline server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsRequest.java:66]: Nit: unintended

File: server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java [hunk 9]
```diff
@@ -87,15 +90,30 @@ public TransportTermVectorsAction(
 
     @Override
     protected ShardIterator shards(ClusterState state, InternalRequest request) {
+
+        final String preference;
+        // route realtime TermVector requests when segment replication is enabled to primary shards,
+        // iff there are no other preferences/routings enabled for routing to a specific shard
```
Comment (Poojita-Raj) [inline server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java:96]: We are not considering routings in shouldForcePrimaryRouting. Update comment to - 
```suggestion
        // iff there are no other preferences enabled for routing to a specific shard
```

**Review by Poojita-Raj — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java (hunk 3 above)
Comment (kotwanikunal) [reply server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java:57]: Given the condition is pretty straightforward - it might be better to duplicate than import from another transport action.

File: server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java [hunk 10]
```diff
@@ -87,15 +90,30 @@ public TransportTermVectorsAction(
...
+        if (shouldForcePrimaryRouting(
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java:97]: You can potentially refactor it as follows - 

```suggested
 String preference = request.request().preference;
        // For a real time request on a seg rep index, use primary shard as the preferred query shard.
        if (request.request().realtime() && preference == null && state.getMetadata().isSegmentReplicationEnabled(request.concreteIndex())) {
            preference = Preference.PRIMARY.type();
        }
if (request.request().doc() != null && request.request().routing() == null) {
            // artificial document without routing specified, ignore its "id" and use either random shard or according to preference
            GroupShardsIterator<ShardIterator> groupShardsIter = clusterService.operationRouting()
                .searchShards(state, new String[] { request.concreteIndex() }, null, preference);
            return groupShardsIter.iterator().next();
        }
```

**Review by kotwanikunal — APPROVED** [review]

File: server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java [hunk 11]
```diff
@@ -87,15 +88,24 @@ public TransportTermVectorsAction(
...
+            && preference == null
+            && state.getMetadata().isSegmentReplicationEnabled(request.concreteIndex())) {
+            preference = Preference.PRIMARY.type();
+        }
+
         if (request.request().doc() != null && request.request().routing() == null) {
             // artificial document without routing specified, ignore its "id" and use either random shard or according to preference
             GroupShardsIterator<ShardIterator> groupShardsIter = clusterService.operationRouting()
-                .searchShards(state, new String[] { request.concreteIndex() }, null, request.request().preference());
+                .searchShards(state, new String[] { request.concreteIndex() }, null, preference);
```
Comment (andrross) [inline server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java:103]: @Rishikesh1159 I don't think the primary override here is necessary. In this case, an "artificial" document has been supplied and the user is asking to compute term vectors as if this was a real document. I don't think the "real time" parameter is applicable here since it doesn't need to look up any index data.

@msfroh Does that sound right to you?

Comment (msfroh) [reply server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java:103]: That does sound right to me. 

I think the override condition should be:
```
        if (request.request().realtime()
            && preference == null
            && state.getMetadata().isSegmentReplicationEnabled(request.concreteIndex())
            && request.request().doc() == null) {
```

Comment (andrross) [reply server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java:103]: Interestingly the code seems to [unconditionally attempt to fetch the document](https://github.com/opensearch-project/OpenSearch/blob/aca2e9de7daaadee77c33e21ff5215c3f1e8600f/server/src/main/java/org/opensearch/index/termvectors/TermVectorsService.java#L114-L118) even if an artificial document is supplied. Not sure if that complicates things here.

Comment (msfroh) [reply server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java:103]: I think that's probably worth fixing -- from the looks of it, that `GetResult` is ignored, which seems a little wasteful.

That said, I don't think it *hurts* anything. In particular, if the `doc` parameter is specified, then it GETs a document with ID based on an autoincrementing (not really random) integer: https://github.com/opensearch-project/OpenSearch/blob/aca2e9de7daaadee77c33e21ff5215c3f1e8600f/server/src/main/java/org/opensearch/action/termvectors/TermVectorsRequest.java#L315-L323

(`generateRandomInteger` is always true on the REST parsing code path.)

Comment (msfroh) [reply server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java:103]: Still, there is no value in routing to a primary shard if an artificial doc is specified.
