### PR TITLE
Ensure that segments are upload to remote store in case of local and …

### LINKED ISSUE #10957: [Remote Store] Durability issue with indices created via split/shrink/clone/manual snapshot recovery
**Describe the bug**

For remote store backed indices, if a user does split/shrink/clone/manual snapshot recovery, we don't guarantee that the segments created gets uploaded to remote, before taking in new writes. 

In absence of this check, we won't be able to durable persist the index , by just using the Remote Translog for newer writes . This is because Remote Segment Store in combination of Remote Translog won't be able to construct the whole data via `remote restore` api. 

**Expected behavior**

Before we enable writes on indices created via split/shrink/clone/manual snapshot recovery, the segments should be durably persisted. 

This makes sure that at any point of time, the data is durably persisted.

### PR DESCRIPTION
**Pull request by gbbafna**
…snapshot based recovery

### Description
Ensure that segments are upload to remote store in case of local and snapshot recovery before activating the primary mode. 

### Related Issues
Resolves #10957

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
~- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
~- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 1]
```diff
@@ -485,7 +489,9 @@ private void initializeRemoteDirectoryOnTermUpdate() throws IOException {
      * @return true iff primaryMode is true and index shard is not in closed state.
      */
     private boolean isReadyForUpload() {
-        boolean isReady = indexShard.getReplicationTracker().isPrimaryMode() && indexShard.state() != IndexShardState.CLOSED;
+        boolean isReady = (indexShard.getReplicationTracker().isPrimaryMode() && indexShard.state() != IndexShardState.CLOSED)
+            || isLocalOrSnapshotRecovery();
+
         if (isReady == false) {
             StringBuilder sb = new StringBuilder("Skipped syncing segments with");
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:496]: nit: Need to update this log statement.

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 2]
```diff
@@ -179,6 +180,9 @@ private boolean shouldSync(boolean didRefresh, boolean skipPrimaryTermCheck) {
         return this.primaryTerm != indexShard.getOperationPrimaryTerm();
     }
 
+    /*
+     @return true if retry is needed
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:184]: Returns `false` if retry is needed.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 3]
```diff
@@ -1996,6 +1996,23 @@ private RemoteSegmentStoreDirectory getRemoteDirectory() {
         return ((RemoteSegmentStoreDirectory) remoteDirectory);
     }
 
+    /*
+    Returns true iff it is able to verify that there is at least one
+    remote segment metadata uploaded
+     */
+    boolean atLeastOneRemoteSync() {
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:2003]: Can we also check if the segment files are same? `RemoteSegmentStoreDirectory.getSegmentsUploadedToRemoteStore` will provide details of segments uploaded to remote store and `store.directory().listAll()` will give local segments info.

It would be a better check as long as it does not create false positives

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java [hunk 4]
```diff
@@ -485,7 +489,9 @@ private void initializeRemoteDirectoryOnTermUpdate() throws IOException {
      * @return true iff primaryMode is true and index shard is not in closed state.
      */
     private boolean isReadyForUpload() {
-        boolean isReady = indexShard.getReplicationTracker().isPrimaryMode() && indexShard.state() != IndexShardState.CLOSED;
+        boolean isReady = (indexShard.getReplicationTracker().isPrimaryMode() && indexShard.state() != IndexShardState.CLOSED)
+            || isLocalOrSnapshotRecovery();
+
         if (isReady == false) {
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:495]: lets also add condition for `logger.isTraceEnabled()`.

**Review by ashking94 — APPROVED** [review]
LGTM!!

**Comment by ashking94** [comment]
Lets add tests as well. Ty!

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 3 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:2003]: Makes sense . Added it .

File: server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java (hunk 4 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java:495]: added

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 5]
```diff
@@ -1996,6 +1997,29 @@ private RemoteSegmentStoreDirectory getRemoteDirectory() {
         return ((RemoteSegmentStoreDirectory) remoteDirectory);
     }
 
+    /**
+    Returns true iff it is able to verify that there is at least one
+    remote segment metadata uploaded
+     */
+    boolean isRemoteSync() {
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:2004]: nit: `isRemoteInSync` or `isRemoteRecoveryComplete`

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 6]
```diff
@@ -1996,6 +1997,29 @@ private RemoteSegmentStoreDirectory getRemoteDirectory() {
...
+        assert indexSettings.isRemoteStoreEnabled();
+        try {
+            RemoteSegmentStoreDirectory directory = getRemoteDirectory();
+            if (directory.readLatestMetadataFile() != null) {
+                // verifying that all files except EXCLUDE_FILES are uploaded to the remote
+                Collection<String> uploadFiles = directory.getSegmentsUploadedToRemoteStore().keySet();
+                SegmentInfos segmentInfos = store.readLastCommittedSegmentsInfo();
+                Collection<String> localFiles = segmentInfos.files(true);
+                if (uploadFiles.containsAll(localFiles)) {
+                    return true;
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:2014]: We could strengthen the checks by adding checksum comparisons for each file rather than just going with the names.

Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:2014]: Yes , we can , but we have our integrity checks at both upload and download flows. This is done right after upload , so doing that wouldn't add any benefit .

**Review by sachinpkale — APPROVED** [review]

**Comment by sachinpkale** [comment]
Flaky tests are failing.
