### PR TITLE
Fix NPE on restore searchable snapshot

### LINKED ISSUE #12966: [BUG] Searchable snapshot restore - null_pointer_exception
### Describe the bug

Hello,
Recently restoring snapshot as searchable is not working on our cluster.
I've tried to reproduce it on my local cluster, but it worked there...
When I change storage_type from remote_snapshot to local, snapshot is being restored without issue.
Can you please help with this ?

`POST /_snapshot/azure_data_repository/retail-legacy-ppe-000337-2024.03.27-06:44:53.545/_restore
{
  "indices": "*",
  "storage_type": "remote_snapshot",
  "ignore_unavailable": true,
  "include_global_state": false,              
  "rename_pattern": "(.+)",
  "rename_replacement": "observability-searchable-sna2p-test2-$1",
  "include_aliases": false
  }`
  
 Response:
 
 `{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"org.opensearch.index.IndexService.getIndexSettings()\" because the return value of \"org.opensearch.indices.IndicesService.indexService(org.opensearch.core.index.Index)\" is null"
      }
    ],
    "type": "null_pointer_exception",
    "reason": "Cannot invoke \"org.opensearch.index.IndexService.getIndexSettings()\" because the return value of \"org.opensearch.indices.IndicesService.indexService(org.opensearch.core.index.Index)\" is null"
  },
  "status": 500
}`

Logs:
`org.opensearch.transport.RemoteTransportException: [observability-opensearch-master-1][***][cluster:admin/snapshot/restore] Caused by: java.lang.NullPointerException: Cannot invoke "org.opensearch.index.IndexService.getIndexSettings()" because the return value of "org.opensearch.indices.IndicesService.indexService(org.opensearch.core.index.Index)" is null at org.opensearch.snapshots.RestoreService$1.lambda$validateSearchableSnapshotRestorable$5(RestoreService.java:809) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.cluster.routing.RoutingTable.allShardsSatisfyingPredicate(RoutingTable.java:325) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.cluster.routing.RoutingTable.allShardsSatisfyingPredicate(RoutingTable.java:307) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.snapshots.RestoreService$1.validateSearchableSnapshotRestorable(RestoreService.java:813) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.snapshots.RestoreService$1.execute(RestoreService.java:591) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:67) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:882) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:434) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:301) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:212) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:204) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:242) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:854) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:283) ~[opensearch-2.12.0.jar:2.12.0] at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:246) ~[opensearch-2.12.0.jar:2.12.0] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] at java.lang.Thread.run(Thread.java:1583) [?:?]`

### Related component

Storage:Snapshots

### To Reproduce

Restore snapshot as remove storage.

### Expected behavior

Snapshot restored as remote snap

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: k8s
 - Version 2.12.0

**Additional context**

### PR DESCRIPTION
**Pull request by bugmakerrrrrr**
### Description
Two changes here:
1. fix the issue in #12966;
2. make dynamic setting `DATA_TO_FILE_CACHE_SIZE_RATIO_SETTING` take effect.

### Related Issues
Resolves #12966

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by bugmakerrrrrr** [comment]
@andrross @kotwanikunal please help to take a look when you get a chance

**Review by andrross — COMMENTED** [review]
Thanks @bugmakerrrrrr!

Let's add a changelog entry for this fix. Also it looks like there are spotless failures.

File: server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java [hunk 1]
```diff
@@ -743,6 +745,8 @@ private IndexMetadata(
         this.waitForActiveShards = waitForActiveShards;
         this.rolloverInfos = Collections.unmodifiableMap(rolloverInfos);
         this.isSystem = isSystem;
+        this.isRemoteSnapshot = IndexModule.Type.REMOTE_SNAPSHOT.match(this.settings);
+        ;
```
[the remark this answers is not in the document]
Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java:749]: nice catch

File: server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java [hunk 2]
```diff
@@ -1204,6 +1208,10 @@ public boolean isSystem() {
         return isSystem;
     }
 
+    public boolean isRemoteSnapshot() {
+        return isRemoteSnapshot;
```
[the remark this answers is not in the document]
Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java:1212]: I think that we can remove `isRemoteSnapshot` field in `IndexSettings`, and make `IndexSettings.isRemoteSnapshot()` call `IndexMetadata.isRemoteSnapshot()`, what do you think about this?

[the remark this answers is not in the document]
Comment (andrross) [reply server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java:1212]: Sure, sound reasonable

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java [hunk 3]
```diff
@@ -208,6 +215,8 @@ public Decision canAllocate(ShardRouting shardRouting, RoutingNode node, Routing
                 );
             }
             return Decision.YES;
+        } else if (REMOTE_CAPABLE.equals(getShardPool(shardRouting, allocation))) {
```
Comment (andrross) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java:218]: Would this if-else be a bit simpler to follow if structured like the following?

```java
if (REMOTE_CAPABLE.equals(getShardPool(shardRouting, allocation)) {
    if (REMOTE_CAPABLE.equals(getNodePool(node))) {
        ...
    } else {
        return Decision.NO;
    }
}
```

I _think_ that is logically equivalent. Returning "NO" in that else block is much easier to follow in my opinion. It's really a style question (and does result in indenting the code more), so I'll defer to your opinion.

**Review by andrross — APPROVED** [review]

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java (hunk 3 above)
Comment (andrross) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java:218]: Another option:

```java
if (REMOTE_CAPABLE.equals(getShardPool(shardRouting, allocation)) {
    if (REMOTE_CAPABLE.equals(getNodePool(node)) == false) {
        return Decision.NO;
    }
    ...
}
```

Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java:218]: I like the second option

Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java:218]: I suddenly realized that we may not be able to do this, because if a node has both data role and search role and when we try to allocate local storage index, this logic will be executed. I tend not to change this piece of code.

**Comment by andrross** [comment]
Looks like this failure might be related to this change?

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderTests.testFileCacheRemoteShardsDecisions" -Dtests.seed=77C464051AC2A818 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sr-Latn-ME -Dtests.timezone=Pacific/Guam -Druntime.java=21

org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderTests > testFileCacheRemoteShardsDecisions FAILED
    java.lang.AssertionError: 
    Expected: <NO>
         but: was <YES>
        at __randomizedtesting.SeedInfo.seed([77C464051AC2A818:FE27C4DE8AE74CC9]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderTests.testFileCacheRemoteShardsDecisions(DiskThresholdDeciderTests.java:462)
```

**Review by andrross — APPROVED** [review]
