### PR TITLE
Handle canMatchSearchAfter for frozen context scenario

### LINKED ISSUE #11248: [BUG] Handle canMatchSearchAfter for frozen context scenario
### Description
There is a corner case where sort is failing on nested field after this PR https://github.com/opensearch-project/OpenSearch/pull/7453. When nested field is date and have `filter` in nest field has `now()` function call.
OpenSearch prevents SortFields' initialization in such cases more then one time.
This is very corner scenario but I added integ tests for that as we did have any integ test.
As a mitigation, I am pssing already initialized `SortAndFormats` in ContextIndexSearcher in this PR. In fact I also made change to invoke that if clause only if SearchContext contains searchAfter,

### How to repro the issue
```
PUT test_sort_nested_date2
{
  "settings" : {
      "number_of_shards" : 1,
      "number_of_replicas" : 0
  },
  "mappings": {
    "properties": {
      "nested_field": {
        "type": "nested",
        "properties": {
          "date_field": {
            "type": "date",
            "format": "date_optional_time"
          }
        }
      }
    }
  }
}
```

```
POST test_sort_nested_date2/_bulk
{"index": {"_id": "1"}}
{"nested_field": [{"date_field": "2023-10-26T12:00:00+09:00"}, {"date_field": "2025-10-01T12:00:00+09:00"}]}
```

```
GET test_sort_nested_date2/_search
{
  "sort": [
    {
      "nested_field.date_field": {
      "mode": "max",
        "order": "desc",
        "nested": {
          "path": "nested_field",
          "filter": {
            "bool": {
              "filter": [
                {
                  "range": {
                    "nested_field.date_field": {
                      "gte": "now/h",
                      "time_zone": "+09:00"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  ]
}
```

This search query failes with below Exception,
```
{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "could not read the current timestamp"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test_sort_nested_date2",
        "node": "WT1VH4gyTVGVZyi_tNMO-Q",
        "reason": {
          "type": "parse_exception",
          "reason": "could not read the current timestamp",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "features that prevent cachability are disabled on this context"
          }
        }
      }
    ]
  },
  "status": 400
}
```

Server side traces are corelated with canMatchSearchAfter where we are trying to initialize SortAndFormats again to get MinMax values.

```
[2023-10-21T12:21:59,877][DEBUG][o.o.a.s.TransportSearchAction] [bc908df47a785e9192f108cf1282c4e4] All shards failed for phase: [query]
OpenSearchParseException[could not read the current timestamp]; nested: IllegalArgumentException[features that prevent cachability are disabled on this context];
    at org.opensearch.common.time.JavaDateMathParser.parse(JavaDateMathParser.java:83)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.parseToLong(DateFieldMapper.java:510)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.lambda$dateRangeQuery$1(DateFieldMapper.java:464)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.handleNow(DateFieldMapper.java:493)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.dateRangeQuery(DateFieldMapper.java:459)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.rangeQuery(DateFieldMapper.java:434)
    at org.opensearch.index.query.RangeQueryBuilder.doToQuery(RangeQueryBuilder.java:527)
    at org.opensearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:117)
    at org.opensearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:346)
    at org.opensearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:329)
    at org.opensearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:117)
    at org.opensearch.search.sort.SortBuilder.resolveNestedQuery(SortBuilder.java:245)
    at org.opensearch.search.sort.SortBuilder.resolveNested(SortBuilder.java:203)
    at org.opensearch.search.sort.FieldSortBuilder.nested(FieldSortBuilder.java:588)
    at org.opensearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:411)
    at org.opensearch.search.sort.SortBuilder.buildSort(SortBuilder.java:166)
    at org.opensearch.search.sort.FieldSortBuilder.getMinMaxOrNullInternal(FieldSortBuilder.java:631)
    at org.opensearch.search.sort.FieldSortBuilder.getMinMaxOrNullForSegment(FieldSortBuilder.java:626)
    at org.opensearch.search.internal.ContextIndexSearcher.canMatchSearchAfter(ContextIndexSearcher.java:499)
    at org.opensearch.search.internal.ContextIndexSearcher.canMatch(ContextIndexSearcher.java:491)
    at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:309)
    at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:295)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:551)
    at org.opensearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:341)
    at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWithCollector(QueryPhase.java:419)
    at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWith(QueryPhase.java:408)
    at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:263)
    at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:150)
    at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:527)
    at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:591)
    at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:560)
    at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73)
    at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
    at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:815)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: features that prevent cachability are disabled on this context
    at org.opensearch.index.query.QueryShardContext.failIfFrozen(QueryShardContext.java:521)
    at org.opensearch.index.query.QueryShardContext.nowInMillis(QueryShardContext.java:555)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.lambda$handleNow$2(DateFieldMapper.java:491)
    at org.opensearch.common.time.JavaDateMathParser.parse(JavaDateMathParser.java:81)
    ... 41 more
```

**Host/Environment (please complete the following information):**
 - OS: [All]
 - Version [>=2.8]

**Additional context**

### PR DESCRIPTION
**Pull request by gashutos**
### Description
There is a corner case where sort is failing on nested field after this PR https://github.com/opensearch-project/OpenSearch/pull/7453. When nested field is `date` type and have `filter` in nested field has `now()` function call.
OpenSearch prevents SortFields' initialization in such cases more then one time.
This is very corner scenario but I added integ tests for that as we didn't have any integ test.
As a mitigation, I am pssing already initialized `SortAndFormats` in ContextIndexSearcher in this PR. In fact I also made change to invoke that `if clause` only if SearchContext contains searchAfter.

This happens only when nested_sort is having date field type and filter is having range along with now(). Culprit is the now() call that Opensearch is trying to avoid since now() should get called only once.

### How to repro the issue
```
PUT test_sort_nested_date2
{
  "settings" : {
      "number_of_shards" : 1,
      "number_of_replicas" : 0
  },
  "mappings": {
    "properties": {
      "nested_field": {
        "type": "nested",
        "properties": {
          "date_field": {
            "type": "date",
            "format": "date_optional_time"
          }
        }
      }
    }
  }
}
```

```
POST test_sort_nested_date2/_bulk
{"index": {"_id": "1"}}
{"nested_field": [{"date_field": "2023-10-26T12:00:00+09:00"}, {"date_field": "2025-10-01T12:00:00+09:00"}]}
```

```
GET test_sort_nested_date2/_search
{
  "sort": [
    {
      "nested_field.date_field": {
      "mode": "max",
        "order": "desc",
        "nested": {
          "path": "nested_field",
          "filter": {
            "bool": {
              "filter": [
                {
                  "range": {
                    "nested_field.date_field": {
                      "gte": "now/h",
                      "time_zone": "+09:00"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  ]
}
```

This search query failes with below Exception,
```
{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "could not read the current timestamp"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test_sort_nested_date2",
        "node": "WT1VH4gyTVGVZyi_tNMO-Q",
        "reason": {
          "type": "parse_exception",
          "reason": "could not read the current timestamp",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "features that prevent cachability are disabled on this context"
          }
        }
      }
    ]
  },
  "status": 400
}
```

Server side traces are corelated with canMatchSearchAfter where we are trying to initialize SortAndFormats again to get MinMax values.

```
[2023-10-21T12:21:59,877][DEBUG][o.o.a.s.TransportSearchAction] [bc908df47a785e9192f108cf1282c4e4] All shards failed for phase: [query]
OpenSearchParseException[could not read the current timestamp]; nested: IllegalArgumentException[features that prevent cachability are disabled on this context];
    at org.opensearch.common.time.JavaDateMathParser.parse(JavaDateMathParser.java:83)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.parseToLong(DateFieldMapper.java:510)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.lambda$dateRangeQuery$1(DateFieldMapper.java:464)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.handleNow(DateFieldMapper.java:493)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.dateRangeQuery(DateFieldMapper.java:459)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.rangeQuery(DateFieldMapper.java:434)
    at org.opensearch.index.query.RangeQueryBuilder.doToQuery(RangeQueryBuilder.java:527)
    at org.opensearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:117)
    at org.opensearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:346)
    at org.opensearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:329)
    at org.opensearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:117)
    at org.opensearch.search.sort.SortBuilder.resolveNestedQuery(SortBuilder.java:245)
    at org.opensearch.search.sort.SortBuilder.resolveNested(SortBuilder.java:203)
    at org.opensearch.search.sort.FieldSortBuilder.nested(FieldSortBuilder.java:588)
    at org.opensearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:411)
    at org.opensearch.search.sort.SortBuilder.buildSort(SortBuilder.java:166)
    at org.opensearch.search.sort.FieldSortBuilder.getMinMaxOrNullInternal(FieldSortBuilder.java:631)
    at org.opensearch.search.sort.FieldSortBuilder.getMinMaxOrNullForSegment(FieldSortBuilder.java:626)
    at org.opensearch.search.internal.ContextIndexSearcher.canMatchSearchAfter(ContextIndexSearcher.java:499)
    at org.opensearch.search.internal.ContextIndexSearcher.canMatch(ContextIndexSearcher.java:491)
    at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:309)
    at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:295)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:551)
    at org.opensearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:341)
    at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWithCollector(QueryPhase.java:419)
    at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWith(QueryPhase.java:408)
    at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:263)
    at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:150)
    at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:527)
    at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:591)
    at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:560)
    at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73)
    at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
    at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:815)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: features that prevent cachability are disabled on this context
    at org.opensearch.index.query.QueryShardContext.failIfFrozen(QueryShardContext.java:521)
    at org.opensearch.index.query.QueryShardContext.nowInMillis(QueryShardContext.java:555)
    at org.opensearch.index.mapper.DateFieldMapper$DateFieldType.lambda$handleNow$2(DateFieldMapper.java:491)
    at org.opensearch.common.time.JavaDateMathParser.parse(JavaDateMathParser.java:81)
    ... 41 more
```

### Related Issues
Resolves #11248

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gashutos** [comment]
@reta @msfroh @backslasht @sohami ^^ We hit the wild corner case :(

File: server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java [hunk 1]
```diff
@@ -507,14 +507,18 @@ private boolean canMatch(LeafReaderContext ctx) throws IOException {
     }
 
     private boolean canMatchSearchAfter(LeafReaderContext ctx) throws IOException {
-        if (searchContext.request() != null && searchContext.request().source() != null) {
+        if (searchContext.searchAfter() != null
+            && searchContext.sort() != null
```
Comment (noCharger) [inline server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:511]: - Any other component required besides sort? For example, aggregations, rescore?

Comment (msfroh) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:511]: From what I can tell from the logic in `FieldSortBuilder.getMinMaxOrNullInternal`, this logic only applies to custom sorting, identifying opportunities for a `search_after` request to skip an entire segment if the lower/upper bound on the next hits lies outside the segment's bounds.

**Review by msfroh — APPROVED** [review]

File: server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java (hunk 1 above)
Comment (sohami) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:511]: `null` check for sort seems redundant since `getPrimaryFieldSortOrNull` will be null if the request doesn't have `sort`

File: server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java [hunk 2]
```diff
@@ -611,22 +611,32 @@ public static FieldSortBuilder getPrimaryFieldSortOrNull(SearchSourceBuilder sou
      * and configurations return <code>null</code>.
      */
     public static MinAndMax<?> getMinMaxOrNull(QueryShardContext context, FieldSortBuilder sortBuilder) throws IOException {
-        return getMinMaxOrNullInternal(context.getIndexReader(), context, sortBuilder);
+        return getMinMaxOrNullInternal(context.getIndexReader(), context, sortBuilder, null);
```
Comment (sohami) [inline server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java:614]: Instead of passing `null`, we can just create the `SortAndFormat` here and pass it. That way the common method will not have any special null handling.

```
public static MinAndMax<?> getMinMaxOrNull(QueryShardContext context, FieldSortBuilder sortBuilder) throws IOException {
          final SortAndFormats sort = SortBuilder.buildSort(Collections.singletonList(sortBuilder), context).get();
          return getMinMaxOrNullInternal(context.getIndexReader(), context, sortBuilder, sort);
}
```

File: server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java (hunk 1 above)
Comment (gashutos) [reply server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:511]: @noCharger Yeah, this is only applicable to sort. As sohami@ said, if we dont have sort in query, we wont invoke getMinMaxOrNull() function itself.
@sohami Makes sense. I cant think of any scenario where searchContext.sort() is null but request.source.sort is not.
removed the check

File: server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java (hunk 2 above)
Comment (gashutos) [reply server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java:614]: Nice ! Thank you for the suggestion.

**Review by sohami — APPROVED** [review]
Thanks. Lgtm

**Review by backslasht — APPROVED** [review]

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [7b8eeec](https://github.com/opensearch-project/OpenSearch/commit/7b8eeec4ae2f5d34eb94cb12989bcc5943eb34e2): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/30222/)

```
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/240_date_nanos/date with nested sort now}](https://build.ci.opensearch.org/job/gradle-check/30222/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_240_date_nanos_date_with_nested_sort_now_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/240_date_nanos/date with nested sort now}](https://build.ci.opensearch.org/job/gradle-check/30222/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_240_date_nanos_date_with_nested_sort_now__2/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/240_date_nanos/date with nested sort now}](https://build.ci.opensearch.org/job/gradle-check/30222/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_240_date_nanos_date_with_nested_sort_now__3/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/240_date_nanos/date with nested sort now}](https://build.ci.opensearch.org/job/gradle-check/30222/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_240_date_nanos_date_with_nested_sort_now__4/)
```

Those are indeed flaky till we get it to 2.12 (backport)

**Review by noCharger — APPROVED** [review]

**Comment by reta** [comment]
@gashutos sorry but we have merge conflict here ...

**Comment by gashutos** [comment]
> @gashutos sorry but we have merge conflict here ...

Oops, resolved just now.

**Comment by reta** [comment]
@gashutos could you please manually backport to  `2.x`? thank you.

**Comment by lasiltan** [comment]
Using the latest docker version (opensearchproject/opensearch:latest) fails with this error. Curiously the latest version in AWS does not.

**Comment by reta** [comment]
> Using the latest docker version (opensearchproject/opensearch:latest) fails with this error. 
Thank you @lasiltan , that should not be the case, @gashutos could you please double check? Thank you.

**Comment by gashutos** [comment]
The latest image is `2.11.1` version.
```
[gashutos@dev-dsk-gashutos-1c-2320b8cf ~]$ curl https://localhost:9200 -ku 'admin:admin'
{
  "name" : "e566097573d4",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "rKUWMmhWRZmleVAts-28VQ",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.11.1",
    "build_type" : "tar",
    "build_hash" : "6b1986e964d440be9137eba1413015c31c5a7752",
    "build_date" : "2023-11-29T21:43:10.135035992Z",
    "build_snapshot" : false,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

This fix will be available in 2.12 release -> [schedule](https://opensearch.org/releases.html).

For AWS managed OpenSearch services, we have different release schedule and we patched this fix to 2.11 AOS version itself.
