### PR TITLE
Snapshot _status API to return correct status for partial snapshots

### LINKED ISSUE #7952: [BUG] Request _snapshot/repo/snapshot/_status returns wrong status
**Describe the bug**
The  **/_snapshot/repo/snapshot/_status**  returns snapshot.state=SUCCESS for snapshots that have failed shards and are actually in PARTIAL status.

**To reproduce**
1. Make sure you have failed snapshots:
_curl https://endpoint:9200/_cat/snapshots/repo/_
````
snap-2023.06.06 SUCCESS 1686109923 03:52:03 1686112172 04:29:32 37.4m 1 15 0 15
snap-2023.06.07 PARTIAL 1686117675 06:01:15 1686119799 06:36:39 35.4m 1 28 1 29
````
2. Get common info of the failed snapshot:
_curl -ks https://endpoint:9200/_snapshot/repo/snap-2023.06.07/?pretty_
````
     {
       "snapshot" : "snap-2023.06.07",
       "version" : "2.4.1",
       "indices" : [
         "index-2023.06.06"
       ],
       "include_global_state" : true,
       "state" : "PARTIAL",  - - - !!! true !!!
       "failure" : [
         {
           "index" : "index-2023.06.06",
           "shard_id" : 1,
           "reason" : "node shutdown",
           "node_id" : "123",
           "status" : "INTERNAL_SERVER_ERROR"
         }
       ],
       "shards" : {
         "total" : 29
         "failed" : 1,
         "successful" : 28
       }
     }
````
3. Request the status of this snapshot:
_curl -ks https://endpoint:9200/_snapshot/repo/snap-2023.06.07/_status?pretty_
````
   "snapshots" : [
     {
       "snapshot" : "snap-2023.06.07",
       "repository" : "repo",
       "state" : "SUCCESS", - - - !!! false !!!
       "include_global_state" : true,
       "shards_stats" : {
         "initializing" : 0,
         "started" : 0,
         "finalizing" : 0,
         "done" : 28,
         "failed" : 1,
         "total" : 29
       },
       "indices" : {
         "index-2023.06.06" : {
           "shards_stats" : {
             "initializing" : 0,
             "started" : 0,
             "finalizing" : 0,
             "done" : 28,
             "failed" : 1,
             "total" : 29
           },
           "shards" : {
             ...
             "1" : {
               "stage" : "FAILURE",
               "stat" : {
                 "incremental" : {
                   "file_count" : 0,
                   "size_in_bytes" : 0
                 },
                 "total" : {
                   "file_count" : 0,
                   "size_in_bytes" : 0
                 },
                 "start_time_in_millis" : 0,
                 "time_in_millis" : 0
               },
               "reason" : "node shutdown"
             }
           }
         }
       }
     }
   ]
````

**Expected behavior**
The request must return the current snapshot status

**Host/Environment (please complete the following information):**
  OS: Amazon Linux 2
  - Version Opensearch 2.4.1

### PR DESCRIPTION
**Pull request by aggarwalShivani**
### Description
Issue: The /_snapshot/repo/snapshot/_status API endpoint returns snapshot.state=SUCCESS for snapshots that have failed shards and are actually in PARTIAL status.
Change - To fix this behaviour, a new PARTIAL state is added in SnapshotsInProgress.State enum. 
Also, currently, for both successful and partial snapshots, success state was being returned as the response. This is now changed to return PARTIAL for snapshots in partial status.
Test case is also added, to test for partial snapshots.

### Related Issues
Resolves #7952 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- ~[ ] New functionality has been documented.~
  - ~[ ] New functionality has javadoc added~
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by aggarwalShivani** [comment]
> ❌ Gradle check result for [274af5c](https://github.com/opensearch-project/OpenSearch/commit/274af5c1db7e3ba8eae8df89bff713182e42fbf0): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35541/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

All 3 test failures in the CI build are unrelated to the change in this PR and are being tracked by existing flaky tests. 

testTaskResourceTrackingDuringTaskCancellation : https://github.com/opensearch-project/OpenSearch/issues/5329 
testCommitLevelRestoreShardFromRemoteStore   https://github.com/opensearch-project/OpenSearch/issues/10704
testIndexingWithSegRep    https://github.com/opensearch-project/OpenSearch/issues/12336

I have executed them locally on my env and they've passed.

**Comment by kotwanikunal** [comment]
@aggarwalShivani Thanks for your contribution. I have triggered the tests. 
Can you please fix the failing checks?

Also I do not have a lot of historical context on this. @reta / @andrross WDYT?

File: server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java [hunk 1]
```diff
@@ -937,7 +937,8 @@ public enum State {
         STARTED((byte) 1, false),
         SUCCESS((byte) 2, true),
         FAILED((byte) 3, true),
-        ABORTED((byte) 4, false);
+        ABORTED((byte) 4, false),
+        PARTIAL((byte) 5, false);
```
Comment (reta) [inline server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:941]: @aggarwalShivani we changing Public API here and I believe it will cause issues in mixed clusters:  the older versions will not be able to desearialize the `State` enumeration since the new member `PARTIAL` is not known to them

Comment (aggarwalShivani) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:941]: @reta  Thanks for your feedback. I'm making this change, please let me know if this aligns well - 

```
                       case PARTIAL:
                            if (Version.CURRENT.onOrAfter(Version.V_3_0_0))
                                state = SnapshotsInProgress.State.PARTIAL;
                            else
                                // Setting SUCCESS in older versions for backward compatibility
                                state = SnapshotsInProgress.State.SUCCESS;
```

**Comment by aggarwalShivani** [comment]
> ❌ Gradle check result for [d5e1380](https://github.com/opensearch-project/OpenSearch/commit/d5e1380456f28107af887ef3418e1efa5f3e9935): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/36245/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Failure:
```
Execution failed for task ':distribution:bwc:minor:buildBwcLinuxTar'.
> Building 2.13.0 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/minor/build/bwc/checkout-2.x/distribution/archives/linux-tar/build/distributions/opensearch-min-2.13.0-SNAPSHOT-linux-x64.tar.gz
```
I am able to run this task successfully locally. 
I also see other PRs (for ex. build [36230](https://build.ci.opensearch.org/job/gradle-check/36230/console)) where this task has failed. Any suggestions on this issue?

@kotwanikunal  I have resolved other failures reported before.

File: server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java (hunk 1 above)
Comment (reta) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:941]: @aggarwalShivani apologies, the change is not right, it should be done in `Entry::writeTo(StreamOutput)` and `Entry::Entry(StreamInput)` , please let me know if you need help

Comment (aggarwalShivani) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:941]: @reta Thanks for the feedback, apologies for not getting it earlier. 
I'm afraid I will need some help here :(

Is this how the change should be made?
```
        public void writeTo(StreamOutput out) throws IOException {
            snapshot.writeTo(out);
            ....
            if ((out.getVersion().before(Version.V_3_0_0)) && state.value == (byte) 5){
                    out.writeByte((byte) 2);
            } else {
                    out.writeByte(state.value());
            }
```

Also, I didnt really understand the change to be made in the private Entry(StreamInput in) method.

Comment (reta) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:941]: @aggarwalShivani  yeah, but you could use `State` enum members instead of bytes:

```
            if ((out.getVersion().before(Version.V_3_0_0)) && state == State.PARTIAL){
                    out.writeByte(State.SUCCESS.value());
            } else {
                    out.writeByte(state.value());
            }
```

thanks!

Comment (aggarwalShivani) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:941]: Thank you so much! 
And for the in Entry(StreamInput in) method, I am guessing this would work. 
```
        private Entry(StreamInput in) throws IOException {
            snapshot = new Snapshot(in);
            ...
            if ((in.getVersion().before(Version.V_3_0_0)) && State.fromValue(in.readByte()) == State.PARTIAL){
               state = State.SUCCESS;
            } else {
                state = State.fromValue(in.readByte());
            }
```
Please let me know if you have any thoughts on this. 
Meanwhile, I will run the tests with this change and push again.

Comment (reta) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:941]: >  And for the in Entry(StreamInput in) method, I am guessing this would work.

I think for `Entry(StreamInput in)` counterpart I misled you, apologies for that, we don't need to change it. The new code will always be able to make sense of `PARTIAL` status.

**Comment by aggarwalShivani** [comment]
Hi @Reviewers, 
Can someone please retrigger the checks?

There was a github outage today when I had pushed the latest commit. Some github URLs weren't accessible intermittently. It seems like the build failures are a result of the same:
1. Check compatibility - The build stage passed, but the failure showed up in "Upload results" stage.
```
BUILD SUCCESSFUL in 21m 50s
......
Error: Failed to FinalizeArtifact: Unable to make request: ECONNRESET
If you are using self-hosted runners, please make sure your runner has access to all GitHub endpoints: 
```

3. Gradle check (jenkins)
The [build](https://build.ci.opensearch.org/job/gradle-check/36569/) is successful, but still the check failed while updating the results.
`RequestError [HttpError]: invalid json response body at
 https://api.github.com/repos/opensearch-project/OpenSearch/issues/12812/comments reason: Unexpected end of JSON input`

**Comment by reta** [comment]
> ❌ Gradle check result for [2fee046](https://github.com/opensearch-project/OpenSearch/commit/2fee046622bfcfb563b5b1b316f5084dbac3b380): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/36587/)

https://github.com/opensearch-project/OpenSearch/issues/11155

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java [hunk 2]
```diff
@@ -357,6 +357,22 @@ public void testSnapshotStatusOnFailedSnapshot() throws Exception {
         assertEquals(SnapshotsInProgress.State.FAILED, snapshotsStatusResponse.getSnapshots().get(0).getState());
     }
 
+    public void testSnapshotStatusOnPartialSnapshot() throws Exception {
```
Comment (reta) [inline server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java:360]: @aggarwalShivani this test sadly in unreliable (flaky), I run it a few times on mu local machine (`./gradlew :server:test --tests org.opensearch.snapshots.SnapshotStatusApisIT.*`) and it fails with:

```
java.lang.AssertionError: expected:<PARTIAL> but was:<SUCCESS>
	at __randomizedtesting.SeedInfo.seed([B3562D6A3C135EA4:C7EF69AA2482D120]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.opensearch.snapshots.SnapshotStatusApisIT.testSnapshotStatusOnPartialSnapshot(SnapshotStatusApisIT.java:373)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

We cannot integrate flaky tests sadly.

Comment (aggarwalShivani) [reply server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java:360]: @reta Thanks for the feedback. 
I ran these tests now atleast 10+ times in a loop (./gradlew :server:internalClusterTest --tests "org.opensearch.snapshots.SnapshotStatusApisIT.*") on my local machine and they passed everytime :(  
I'm not sure what could be causing the flakiness, and how to even reproduce it :(  . I'll still try to check the test code for improvements.

Comment (andrross) [reply server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java:360]: @aggarwalShivani Unfortunately these non-deterministic test failures can be a real challenge. I'd suggest trying both running the tests from the command line with a shell loop to run it many more than 10 times, and also using the [`-Dtests.iters` parameter](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#seed-and-repetitions) to try to get a reproduction.

**Comment by aggarwalShivani** [comment]
> ❌ Gradle check result for [7d174cc](https://github.com/opensearch-project/OpenSearch/commit/7d174cc90237d2e8fc63da58850b5b9c546a332f): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/36711/)
> 

Flaky test https://github.com/opensearch-project/OpenSearch/issues/6542

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java [hunk 3]
```diff
@@ -357,6 +357,25 @@ public void testSnapshotStatusOnFailedSnapshot() throws Exception {
...
+        createRepository(repoName, "fs");
+        // create an index with a single shard on the data node, that will be stopped
+        createIndex(indexName, singleShardOneNode(dataNode));
+        index(indexName, "_doc", "some_doc_id", "foo", "bar");
+        logger.info("--> stopping data node before creating snapshot");
+        stopNode(dataNode);
+        startFullSnapshot(repoName, snapshotName, true).get();
+        final List<SnapshotStatus> snapshotStatus = clusterAdmin().snapshotsStatus(
+            new SnapshotsStatusRequest(repoName, new String[] { snapshotName })
+        ).actionGet().getSnapshots();
```
Comment (owaiskazi19) [inline server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java:374]: This can be a new method under `AbstractSnapshotIntegTestCase` with the name `getSnapshotStatus`. We can use the same method in `testStatusApiConsistency` test.

File: server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java [hunk 4]
```diff
@@ -747,7 +747,12 @@ public void writeTo(StreamOutput out) throws IOException {
             snapshot.writeTo(out);
             out.writeBoolean(includeGlobalState);
             out.writeBoolean(partial);
-            out.writeByte(state.value());
+            if ((out.getVersion().before(Version.V_3_0_0)) && state == State.PARTIAL) {
```
Comment (owaiskazi19) [inline server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:750]: Shouldn't this be `out.getVersion().before(Version.V_2_14_0))`?

Comment (reta) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:750]: > Shouldn't this be `out.getVersion().before(Version.V_2_14_0))`?

After backport - yes

Comment (aggarwalShivani) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:750]: @owaiskazi19  @reta  There was a comment earlier in TransportSnapshotsStatusAction.java
```
// Translating both PARTIAL and SUCCESS to SUCCESS for now
// TODO: add the differentiation on the metadata level in the next major release
```
So I assumed this change would be only introduced from next major i.e. 3.0.0 release onwards and would not be backported in 2.x branch. Is that view changed now?

Comment (reta) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:750]: I don't see any reasons not backporting to 2.x (since we properly handle state for different versions), @aggarwalShivani do you?

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java (hunk 2 above)
Comment (reta) [reply server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java:360]: Was checking it locally, seems to be pretty stable, thanks @aggarwalShivani !

**Comment by reta** [comment]
@aggarwalShivani there is one issue that I am concerned about, the snapshot state is stored in cluster state:

```
                final SnapshotsInProgress snapshots = currentState.custom(SnapshotsInProgress.TYPE);

```

I believe the cluster state is read by passing local node version, if we backport to 2.x, we may need to check that cluster state for snapshots will be readable in 3.x and 2.x irrespectively which node created it (was cluster manager).

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
I see that some of the @owaiskazi19 comments are not addressed

**Comment by owaiskazi19** [comment]
```
* What went wrong:
Execution failed for task ':server:spotlessJavaCheck'.
> The following files had format violations:
      src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
          @@ -40,7 +40,6 @@
           import·org.opensearch.action.admin.cluster.snapshots.status.SnapshotIndexShardStatus;
           import·org.opensearch.action.admin.cluster.snapshots.status.SnapshotStats;
           import·org.opensearch.action.admin.cluster.snapshots.status.SnapshotStatus;
          -import·org.opensearch.action.admin.cluster.snapshots.status.SnapshotsStatusRequest;
           import·org.opensearch.action.admin.cluster.snapshots.status.SnapshotsStatusResponse;
           import·org.opensearch.client.Client;
           import·org.opensearch.cluster.SnapshotsInProgress;
```

@aggarwalShivani   can you run  './gradlew :server:spotlessApply' to fix these violations.

File: server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java (hunk 3 above)
Comment (aggarwalShivani) [reply server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java]: Hi @owaiskazi19 , Thanks for the feedback. 
I actually noticed that there was already a method getSnapshotStatus() in SnapshotStatusApisIT.java already, that returned the status of the snapshot. So I've re-used the same in both the test-cases testSnapshotStatusOnPartialSnapshot and testStatusApiConsistency.

The only additional change is I've removed the assertion of the snapshotStatus.size() = 1, as the getSnapshotStatus() method anyways returns the result of the 1st item of the list and not the complete list.

**Comment by aggarwalShivani** [comment]
> ❌ Gradle check result for [d1e6656](https://github.com/opensearch-project/OpenSearch/commit/d1e66568a4a5b56e13730b3b55b1603cdeb55c84): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/36939/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky tests:
testTaskResourceTrackingDuringTaskCancellation - https://github.com/opensearch-project/OpenSearch/issues/5329 (existing issue)
FuzzyFilterPostingsFormatTests.classMethod - https://github.com/opensearch-project/OpenSearch/issues/13177 ( I have raised a new issue, as I've executed this test on my local env multiple times and it passed).

**Comment by owaiskazi19** [comment]
@aggarwalShivani this doesn't look like a flaky test anymore from the past 2 runs. Can you run the test with [-Dtests.iters=100](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#seed-and-repetitions) on your local to verify?

```

> Task :server:test

Tests with failures:
 - org.opensearch.index.codec.fuzzy.FuzzyFilterPostingsFormatTests.classMethod
```

**Comment by aggarwalShivani** [comment]
> @aggarwalShivani this doesn't look like a flaky test anymore from the past 2 runs. Can you run the test with [-Dtests.iters=100](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#seed-and-repetitions) on your local to verify?
> 
> ```
> 
> > Task :server:test
> 
> Tests with failures:
>  - org.opensearch.index.codec.fuzzy.FuzzyFilterPostingsFormatTests.classMethod
> ```

@owaiskazi19  I have executed the test with -Dtests.iters=100  on my local, and it passed in all cases. 
` ./gradlew :server:test  -Dtests.iters=100 --tests "org.opensearch.index.codec.fuzzy.FuzzyFilterPostingsFormatTests.*"
`
But it has been failing in CI :(

File: CHANGELOG-3.0.md [hunk 5]
```diff
@@ -98,6 +98,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 - [Bug] Check phase name before SearchRequestOperationsListener onPhaseStart ([#12035](https://github.com/opensearch-project/OpenSearch/pull/12035))
 - Fix Span operation names generated from RestActions ([#12005](https://github.com/opensearch-project/OpenSearch/pull/12005))
 - Fix error in RemoteSegmentStoreDirectory when debug logging is enabled ([#12328](https://github.com/opensearch-project/OpenSearch/pull/12328))
+- Fix snapshot _status API to return correct status for partial snapshots ([#12812](https://github.com/opensearch-project/OpenSearch/pull/12812))
```
Comment (dblock) [inline CHANGELOG-3.0.md:101]: Should move to the regular CHANGELOG since this will get backported to 2.x.

**Comment by aggarwalShivani** [comment]
> @aggarwalShivani there is one issue that I am concerned about, the snapshot state is stored in cluster state:
> 
> ```
>                 final SnapshotsInProgress snapshots = currentState.custom(SnapshotsInProgress.TYPE);
> ```
> 
> I believe the cluster state is read by passing local node version, if we backport to 2.x, we may need to check that cluster state for snapshots will be readable in 3.x and 2.x irrespectively which node created it (was cluster manager).

@reta okay thanks, I'll have to dig deeper to understand that :) But do you think we should not backport it to 2.x?

**Comment by aggarwalShivani** [comment]
> > > @aggarwalShivani there is one issue that I am concerned about, the snapshot state is stored in cluster state:
> > > ```
> > >                 final SnapshotsInProgress snapshots = currentState.custom(SnapshotsInProgress.TYPE);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I believe the cluster state is read by passing local node version, if we backport to 2.x, we may need to check that cluster state for snapshots will be readable in 3.x and 2.x irrespectively which node created it (was cluster manager).
> > 
> > 
> > @reta okay thanks, I'll have to dig deeper to understand that :) But do you think we should not backport it to 2.x?
> 
> @aggarwalShivani the answer depends on if cluster in mixed cluster is correctly handled

Hi @reta , 
I have managed to run some tests on a mixed-cluster - where 2 nodes were on **v3.0.0-SNAPSHOT** and 2 were on **v2.14.0-SNAPSHOT.** 
I reproduced the PARTIAL snapshot scenario and as expected, the status API returns **SUCCESS** in this case. I have issued the snapshot _status REST API to each of the 4 nodes' IPs individually and they all return SUCCESS and not PARTIAL. 

I have repeated this test on 2.x branch too - where 2 nodes were on **v2.14.0-SNAPSHOT** and 2 were on **v2.13.0** - there too the results were same. 
So I think it is okay to backport it to 2.x too. Please let me know if this is fine.

-----------------------------------------------------

Additionally, since we are backporting it to 2.14, I think we can change the version condition right away as suggested by @owaiskazi19, 
> out.getVersion().before(Version.V_2_14_0)). 

The same PR could be backported to 2.x branch as-is. Please let me know if this understanding is right.

File: CHANGELOG-3.0.md (hunk 5 above)
Comment (owaiskazi19) [reply CHANGELOG-3.0.md:101]: @aggarwalShivani this should be under [Unreleased 2.x]

**Comment by owaiskazi19** [comment]
> Additionally, since we are backporting it to 2.14, I think we can change the version condition right away as suggested by @owaiskazi19,

As @reta mentioned since we are backporting this to 2.x, we can change the version in the backport PR. For main we can keep it as 3.0. @reta looks good to merge?

**Comment by reta** [comment]
> As @reta mentioned since we are backporting this to 2.x, we can change the version in the backport PR. For main we can keep it as 3.0. @reta looks good to merge?

Yeah, I approved, thanks @owaiskazi19 !

File: CHANGELOG-3.0.md (hunk 5 above)
Comment (aggarwalShivani) [reply CHANGELOG-3.0.md]: Done, thanks.

**Comment by aggarwalShivani** [comment]
> > Additionally, since we are backporting it to 2.14, I think we can change the version condition right away as suggested by @owaiskazi19,
> 
> As @reta mentioned since we are backporting this to 2.x, we can change the version in the backport PR. For main we can keep it as 3.0. @reta looks good to merge?

Oh okay sure. Thanks :)

Although my understanding was slightly different. Please correct me where i went wrong.
If there is a mixed cluster of version 3.0.0 and 2.14.0: 
- both the versions would support PARTIAL status change.
- In 3.0.0 src code, condition would always check for version>=3.0.0
- So for anything older than 3.0.0, it would set SUCCESS (instead of PARTIAL) due to bwc. Even though 2.14.0 supports it, it wouldn't be able to set PARTIAL.
So I assumed in the main branch (3.0.0) itself, we could check for >= 2.14.0.

**Comment by owaiskazi19** [comment]
@peternied any idea about the failure in detect breaking change GHA?

**Comment by peternied** [comment]
The failure is from a change in how snapshots are resolved with the Lucene version bump [1], another merge from main will resolve this.  I was able to validate the failure on my local machine and confirm it was resolved with a merge from main.

@aggarwalShivani Could you fetch and merge from main to be sure that 39ac2df95dfc1344611d25a958aa54551bfe45b0 is included?

- [1] https://github.com/opensearch-project/OpenSearch/pull/13195

**Comment by reta** [comment]
> So I assumed in the main branch (3.0.0) itself, we could check for >= 2.14.0.

We could do that right after backporting your code to 2.x, otherwise mixed cluster tests will fail since 2.14.0 (2.x) does not know what to do with PARTIAL

File: server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java (hunk 4 above)
Comment (ticheng-aws) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:750]: I think backport to 2.x is a good idea for consistency. @aggarwalShivani  Do we need to update any public documents for this PR?
https://github.com/opensearch-project/documentation-website

**Review by ticheng-aws — APPROVED** [review]

File: server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java (hunk 4 above)
Comment (aggarwalShivani) [reply server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java:750]: @ticheng-aws  No, I don't think we need to make any changes in the documentation. The states are already explained in https://github.com/opensearch-project/documentation-website/blob/main/_api-reference/snapshots/get-snapshot-status.md?plain=1#L391

**Review by owaiskazi19 — APPROVED** [review]
LG! @aggarwalShivani thanks for being patient with the review. I have removed the auto backport 2.x label. Can you raise a manual backport to 2.x PR with `Version.V_2_14_0` change?

**Comment by aggarwalShivani** [comment]
> LGTM! @aggarwalShivani thanks for being patient with the review. I have removed the auto backport 2.x label. Can you raise a manual backport PR to 2.x branch with `Version.V_2_14_0` change as discussed [here](https://github.com/opensearch-project/OpenSearch/pull/12812#discussion_r1561643825)?

Thanks @owaiskazi19 for your review and suggestions. Sure, I will raise another PR on 2.x branch with these changes.

However, I see the changelog-verifier check is now failing with this error - 
```
Run # The check was possibly skipped leading to success for both the jobs
error: Please make sure that the PR has a backport label associated with it when making an entry to the CHANGELOG.md file
```
I'm assuming this is due to removing the auto backport 2.x label. How do we proceed with the merge then?

**Comment by owaiskazi19** [comment]
> I'm assuming this is due to removing the auto backport 2.x label. How do we proceed with the merge then?

Yes, that's correct. I'll go ahead and merge this once you have a manual 2.x PR up.
