### PR TITLE
Return unformatted Segment Replication metrics that take upload time into account for replication lag

### LINKED ISSUE #10666: [Segment Replication] Return unformatted Segment Replication metrics from nodeStats
Today's SegRep metrics within NodeStats are hardcoded as human readable when written to x content.

```
    @Override
    public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
        builder.startObject(Fields.SEGMENT_REPLICATION);
        builder.field(Fields.MAX_BYTES_BEHIND, new ByteSizeValue(maxBytesBehind).toString());
        builder.field(Fields.TOTAL_BYTES_BEHIND, new ByteSizeValue(totalBytesBehind).toString());
        builder.field(Fields.MAX_REPLICATION_LAG, new TimeValue(maxReplicationLag));
        builder.endObject();
        return builder;
    }
```

These values are should be wrapped with `builder.humanReadableField` and only formatted if requested.  This function will handle transforming the value only if requested as human readable.

### LINKED ISSUE #10722: [Segment Replication] Use replication lag that takes into account upload time
**Describe the bug**
Currently, for segment replication stats that is rolled up at an index, node and cluster level we provide maxReplicationLag. Currently, the replication lag that is returned does not take into account the time taken to upload data to the remote store. 
We want to use the replication lag that takes into account upload time as well. 

**Expected behavior**
Replication lag provided is the total replication lag observed.

### PR DESCRIPTION
**Pull request by Poojita-Raj**
### Description
This change does 2 things: 

1. Returns segment replication stats metrics in an unformatted raw format unless requested in a human readable format (query parameter of human=true) 
2. The replication lag metric being returned `MAX_REPLICATION_LAG` now takes into account the total replication lag i.e., it now includes the time taken to upload data to the remote store. 

### Related Issues
Resolves #10666
Resolves #10722 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/ReplicationStats.java [hunk 1]
```diff
@@ -76,9 +76,15 @@ public void writeTo(StreamOutput out) throws IOException {
     @Override
     public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
         builder.startObject(Fields.SEGMENT_REPLICATION);
-        builder.field(Fields.MAX_BYTES_BEHIND, new ByteSizeValue(maxBytesBehind).toString());
-        builder.field(Fields.TOTAL_BYTES_BEHIND, new ByteSizeValue(totalBytesBehind).toString());
-        builder.field(Fields.MAX_REPLICATION_LAG, new TimeValue(maxReplicationLag));
+        if (builder.humanReadable()) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/ReplicationStats.java:79]: you can pass the fields in directly to builder.humanReadableField - [example](https://github.com/opensearch-project/OpenSearch/blob/d426801ae6753e25b8d9f45da36ca4652bad20d3/server/src/main/java/org/opensearch/index/engine/SegmentsStats.java#L248)

Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/ReplicationStats.java:79]: On testing it out, doesn't seem to be a way to use this without breaking bwc.

Comment (ashking94) [reply server/src/main/java/org/opensearch/index/ReplicationStats.java:79]: Lets do something like this -
https://github.com/opensearch-project/OpenSearch/blob/3899d117722e5517c3c02709cffc981bdf677fd5/server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java#L296-L297

`builder.humanReadableField(<>,<>,<>)` - first 2 args are basically name of fields for raw and human readable fields. We can use the existing names for human readable fields and give rational names for raw fields.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 2]
```diff
@@ -2996,8 +2996,9 @@ public ReplicationStats getReplicationStats() {
             final Set<SegmentReplicationShardStats> stats = getReplicationStatsForTrackedReplicas();
             long maxBytesBehind = stats.stream().mapToLong(SegmentReplicationShardStats::getBytesBehindCount).max().orElse(0L);
             long totalBytesBehind = stats.stream().mapToLong(SegmentReplicationShardStats::getBytesBehindCount).sum();
+            // currentReplicationLagMillis is replication lag that takes into account time taken to upload data to remote store
             long maxReplicationLag = stats.stream()
-                .mapToLong(SegmentReplicationShardStats::getCurrentReplicationTimeMillis)
+                .mapToLong(SegmentReplicationShardStats::getCurrentReplicationLagMillis)
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:3001]: I think we should expose both the lags (end to end which includes the remote upload time) and the replication only lag.

**Review by ashking94 — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/opensearch/index/ReplicationStats.java (hunk 1 above)
Comment (ashking94) [reply server/src/main/java/org/opensearch/index/ReplicationStats.java:79]: @mch2  lets add new fields and deprecate this in future releases -
```
builder.humanReadableField("max_lag", "max_lag_in_bytes", new ByteSizeValue(maxBytesBehind).toString());
builder.humanReadableField("total_lag", "total_lag_in_bytes", new ByteSizeValue(totalBytesBehind).toString());
builder.humanReadableField("max_lag_time", "max_lag_time_in_millis", new TimeValue(maxReplicationLag));
```
The above is over and above the existing fields. Constants to be replaced with static strings.

Comment (mch2) [reply server/src/main/java/org/opensearch/index/ReplicationStats.java:79]: This makes sense, lets correct it and deprecate.  Also nit I think the raw key comes first in .humanReadableField

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 2 above)
Comment (mch2) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:3001]: Lets pls take this up as a separate change to this fix.

File: server/src/main/java/org/opensearch/index/ReplicationStats.java (hunk 1 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/ReplicationStats.java]: Thanks for the suggestion @ashking94! Made the changes, take another look.

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 2 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:3013]: Tracking addition of new field here: Once name is fixed, can add it in: https://github.com/opensearch-project/OpenSearch/issues/10775

File: server/src/main/java/org/opensearch/index/ReplicationStats.java [hunk 3]
```diff
@@ -93,5 +96,11 @@ static final class Fields {
         static final String MAX_BYTES_BEHIND = "max_bytes_behind";
         static final String TOTAL_BYTES_BEHIND = "total_bytes_behind";
         static final String MAX_REPLICATION_LAG = "max_replication_lag";
+        static final String MAX_DATA_LAG = "max_data_lag";
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/ReplicationStats.java:99]: nit - lets keep max_lag, total_lag?

**Review by ashking94 — CHANGES_REQUESTED** [review]
one nit comment, but given this is a field name which is user facing, pls incorporate the same.

File: server/src/main/java/org/opensearch/index/ReplicationStats.java (hunk 3 above)
Comment (mch2) [reply server/src/main/java/org/opensearch/index/ReplicationStats.java:99]: We can still preserve the original names. 

'max_bytes_behind_bytes'
'total_bytes_behind_bytes'
'max_replication_lag_millis'

and only show the existing fields if hr is off. If on the method will handle displaying them.

Comment (mch2) [reply server/src/main/java/org/opensearch/index/ReplicationStats.java:99]: What im suggesting would always show the existing fields. It would break compat when hr is set to true as the values would be displayed out of order.

**Review by mch2 — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java [hunk 4]
```diff
@@ -3010,7 +3010,7 @@ public ReplicationStats getReplicationStats() {
             long maxBytesBehind = stats.stream().mapToLong(SegmentReplicationShardStats::getBytesBehindCount).max().orElse(0L);
             long totalBytesBehind = stats.stream().mapToLong(SegmentReplicationShardStats::getBytesBehindCount).sum();
             long maxReplicationLag = stats.stream()
-                .mapToLong(SegmentReplicationShardStats::getCurrentReplicationTimeMillis)
+                .mapToLong(SegmentReplicationShardStats::getCurrentReplicationLagMillis)
```
Comment (dreamer-89) [inline server/src/main/java/org/opensearch/index/shard/IndexShard.java:3013]: nit: Do we need tests around this ?
```suggestion
                .mapToLong(SegmentReplicationShardStats::getCurrentReplicationLagMillis)
```

**Review by dreamer-89 — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/shard/IndexShard.java (hunk 4 above)
Comment (Poojita-Raj) [reply server/src/main/java/org/opensearch/index/shard/IndexShard.java:3013]: We're just changing which replication lag we return. There's no way to check the value, and the flow is handled by existing tests so we should be covered.
