### PR TITLE
Skip Filter Allocation Decider during mixed mode for existing indices…

### LINKED ISSUE #12961: [Remote Migration] Allow replica allocation on excluded nodes during mixed mode
### Describe the bug

OpenSearch Users will cluster's migration from doc rep to remote using `exclude allocation` mechanism . During this when older nodes hosting replica shards goes down, we won't allow new replicas on remote nodes. This is because primary shards always move first . This will cause cluster to remain in yellow state. 

### Related component

Storage:Durability

### Solution

To fix this, we will need to ignore allocation filters for existing replica shards during migration . 

### Expected behavior

Cluster should not go yellow during docrep to remote store migration .

### PR DESCRIPTION
**Pull request by gbbafna**
…' replica copies

### Description

We are ignore allocation filters for existing replica shards during remote store migration .

### Related Issues
Resolves #12961 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java [hunk 1]
```diff
@@ -102,14 +104,32 @@ public class FilterAllocationDecider extends AllocationDecider {
     private volatile DiscoveryNodeFilters clusterRequireFilters;
     private volatile DiscoveryNodeFilters clusterIncludeFilters;
     private volatile DiscoveryNodeFilters clusterExcludeFilters;
+    private volatile RemoteStoreNodeService.Direction migrationDirection;
+    private volatile RemoteStoreNodeService.CompatibilityMode compatibilityMode;
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java:108]: Why not directly take a settings consumer?

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java [hunk 2]
```diff
@@ -127,10 +147,26 @@ public Decision canAllocate(ShardRouting shardRouting, RoutingNode node, Routing
...
                 return allocation.decision(Decision.NO, NAME, explanation, initialRecoveryFilters);
             }
+
+            Decision decision = isMixedModeReplicaDecision(shardRouting, allocation);
+            if (decision != null) return decision;
         }
         return shouldFilter(shardRouting, node.node(), allocation);
     }
 
+    public Decision isMixedModeReplicaDecision(ShardRouting shardRouting, RoutingAllocation allocation) {
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java:157]: Lets be explicit with naming, maybe call "remoteStoreMigrationInProgress"

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java [hunk 3]
```diff
@@ -127,10 +147,26 @@ public Decision canAllocate(ShardRouting shardRouting, RoutingNode node, Routing
...
+        assert shardRouting.unassigned();
+        if (shardRouting.primary() == false
+            && shardRouting.unassignedInfo().getReason() != UnassignedInfo.Reason.INDEX_CREATED
+            && (compatibilityMode.equals(RemoteStoreNodeService.CompatibilityMode.MIXED))
+            && (migrationDirection.equals(RemoteStoreNodeService.Direction.REMOTE_STORE))) {
+            String explanation =
+                "in mixed mode with remote store direction, allocation filters are not applicable for existing replica copies";
+            return allocation.decision(Decision.YES, NAME, explanation);
+        }
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java:166]: The message "mixed mode" is too high level for end users to understand

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java [hunk 4]
```diff
@@ -102,14 +104,32 @@ public class FilterAllocationDecider extends AllocationDecider {
...
         setClusterExcludeFilters(CLUSTER_ROUTING_EXCLUDE_GROUP_SETTING.getAsMap(settings));
         setClusterIncludeFilters(CLUSTER_ROUTING_INCLUDE_GROUP_SETTING.getAsMap(settings));
+        this.migrationDirection = RemoteStoreNodeService.MIGRATION_DIRECTION_SETTING.get(settings);
+        this.compatibilityMode = RemoteStoreNodeService.REMOTE_STORE_COMPATIBILITY_MODE_SETTING.get(settings);
+
         clusterSettings.addAffixMapUpdateConsumer(CLUSTER_ROUTING_REQUIRE_GROUP_SETTING, this::setClusterRequireFilters, (a, b) -> {});
         clusterSettings.addAffixMapUpdateConsumer(CLUSTER_ROUTING_EXCLUDE_GROUP_SETTING, this::setClusterExcludeFilters, (a, b) -> {});
         clusterSettings.addAffixMapUpdateConsumer(CLUSTER_ROUTING_INCLUDE_GROUP_SETTING, this::setClusterIncludeFilters, (a, b) -> {});
+        clusterSettings.addSettingsUpdateConsumer(RemoteStoreNodeService.MIGRATION_DIRECTION_SETTING, this::setMigrationDirection);
+        clusterSettings.addSettingsUpdateConsumer(
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java:121]: We already have settings update consumers attached to these settings in `RemoteStoreMigrationAllocationDecider`. IMO, we can attach consumers at one place and use it wherever required

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java [hunk 5]
```diff
@@ -127,10 +147,26 @@ public Decision canAllocate(ShardRouting shardRouting, RoutingNode node, Routing
...
         }
         return shouldFilter(shardRouting, node.node(), allocation);
     }
 
+    public Decision isMixedModeReplicaDecision(ShardRouting shardRouting, RoutingAllocation allocation) {
+        assert shardRouting.unassigned();
+        if (shardRouting.primary() == false
+            && shardRouting.unassignedInfo().getReason() != UnassignedInfo.Reason.INDEX_CREATED
+            && (compatibilityMode.equals(RemoteStoreNodeService.CompatibilityMode.MIXED))
+            && (migrationDirection.equals(RemoteStoreNodeService.Direction.REMOTE_STORE))) {
```
Comment (sachinpkale) [inline server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java:162]: We also need to check if primary is migrated or not, right?

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java (hunk 3 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java:166]: modified to `in  remote store migration, allocation filters are not applicable for existing replica copies`

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java (hunk 4 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java:121]: That will change the decisions of `RemoteStoreMigrationAllocationDecider` only , whereas we want to influence `FilterAllocationDecider` during migration process. Hence we will need to consume these settings at two places for now .

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java (hunk 5 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java:162]: No, for primary allocation, filter deciders can come in action as is.

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java (hunk 4 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java:121]: `RemoteStoreNodeService` can't have cluster service as it is created much before cluster service is created . This is because it needs to do verification of repo and all .

File: server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java (hunk 5 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java]: Added it now .

**Review by sachinpkale — APPROVED** [review]
