### PR TITLE
Fix for race condition in node-join/node-left loop

### LINKED ISSUE #4874: [BUG] Race in node-left and node-join can prevent node from joining the cluster indefinitely
**Describe the bug**
A node in an OpenSearch cluster can fail due to many reasons(health-check failure/lagging etc)which triggers a `node-left` cluster state update on the leader which is responsible for removing the connections as a part of applying the new(node-left) cluster state. However it is possible that a data node triggers a `node-join` quickly(before the leader has removed the connection as a part of cluster state apply) that reuses the connection and attempts to connect to the leader. At this point the leader starts to process a `node-join` request, updates its followers and schedules a follower checker on the newly joined node. But before the follower checker can get to this connection the in-flight `node-left` cluster state updates cleans up the connection only for the follower checker to realize the node is not connected thereby failing the follower checks and triggering another `node-left`. The leader doesn't even send the `node-join` cluster state to the data node since it thinks it isn't connected as a result the peer finder keeps on sending join request to the leader and the loop goes on.....

####  Node join
```
[2022-10-18T17:00:04,691][INFO ][o.e.c.s.MasterService    ] [684c88cd4e749b366ab49c1f195504da] node-join[{7c1864abfe7e2a2b95a63b437464cfcf}{p12Bffu0Rf2KRQyoqFD_2A}{2Z1b2cXgTHauEVdfXMfspw}{172.xx.xx.xx}{172.xx.xx.xx:9300}{dir} join existing leader
```

#### Follower checker scheduled post `node-join` which fails to find a connection
```
[2022-10-18T17:00:04,788][DEBUG][o.e.c.c.FollowersChecker ] [684c88cd4e749b366ab49c1f195504da] FollowerChecker{discoveryNode={5b7033ca454040458aab223e1090e5f1}{uqcjvUYfSwK-paAxpuwzGA}{dLZWtCQITqa1GwOFQIgelA}{172.xx.xx.xx}{172.xx.xx.xx:9300}{dir}, failureCountSinceLastSuccess=1, [cluster.fault_detection.follower_check.retry_count]=3} disconnected
NodeNotConnectedException[[5b7033ca454040458aab223e1090e5f1][172.xx.xx.xx:9300] Node not connected]
        at org.elasticsearch.transport.ClusterConnectionManager.getConnection(ClusterConnectionManager.java:189)
        at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:682)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:602)
        at org.elasticsearch.cluster.coordination.FollowersChecker$FollowerChecker.handleWakeUp(FollowersChecker.java:326)
        at org.elasticsearch.cluster.coordination.FollowersChecker$FollowerChecker.start(FollowersChecker.java:304)
        at org.elasticsearch.cluster.coordination.FollowersChecker.lambda$setCurrentNodes$3(FollowersChecker.java:155)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.elasticsearch.cluster.coordination.FollowersChecker.setCurrentNodes(FollowersChecker.java:148)
        at org.elasticsearch.cluster.coordination.Coordinator.publish(Coordinator.java:1115)
        at org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:288)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:270)
        at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:155)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:693)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

```
[2022-10-18T17:00:04,790][DEBUG][o.e.c.c.FollowersChecker ] [684c88cd4e749b366ab49c1f195504da] FollowerChecker{discoveryNode={7c1864abfe7e2a2b95a63b437464cfcf}{p12Bffu0Rf2KRQyoqFD_2A}{2Z1b2cXgTHauEVdfXMfspw}{172.xx.xx.xx}{172.xx.xx.xx:9300}{dir}, failureCountSinceLastSuccess=1, [cluster.fault_detection.follower_check.retry_count]=3} marking node as faulty
```

#### Data node gets added without the connection mapped(non-verifiable through logs)
```
[2022-10-18T17:00:21,139][INFO ][o.e.c.s.ClusterApplierService] [684c88cd4e749b366ab49c1f195504da] added {{7c1864abfe7e2a2b95a63b437464cfcf}{p12Bffu0Rf2KRQyoqFD_2A}{2Z1b2cXgTHauEVdfXMfspw}{172.xx.xx.xx}{172.xx.xx.xx:9300}{dir},{5b7033ca454040458aab223e1090e5f1}{uqcjvUYfSwK-paAxpuwzGA}{dLZWtCQITqa1GwOFQIgelA}
```

#### Data node gets removed
```
[2022-10-18T17:00:26,326][INFO ][o.e.c.s.MasterService    ] [684c88cd4e749b366ab49c1f195504da] node-left[{7c1864abfe7e2a2b95a63b437464cfcf}{p12Bffu0Rf2KRQyoqFD_2A}{2Z1b2cXgTHauEVdfXMfspw}{172.xx.xx.xx}{172.xx.xx.xx:9300}{dir} reason: disconnected
```

```
[2022-10-18T17:00:56,363][INFO ][o.e.c.s.ClusterApplierService] [684c88cd4e749b366ab49c1f195504da] removed {{7c1864abfe7e2a2b95a63b437464cfcf}{p12Bffu0Rf2KRQyoqFD_2A}{2Z1b2cXgTHauEVdfXMfspw}{172.xx.xx.xx}{172.xx.xx.xx:9300}{dir},
```

**Expected behavior**
node join and leaves shouldn't interfere and allow transitions to happens cleanly without getting deadlocked

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by rahulkarajgikar**
### Description
Fix for race condition in node-join/node-left loop.

Scenario where race condition can happen:

-  Suppose a node disconnects from the cluster due to some normal reason.
-  This queues a `node-left` task on cluster manager thread.
-  Then cluster manager then computes the new cluster state based on the `node-left` task.
-  The cluster manager now tries to send the new state to all the nodes and waits for all nodes to ack back.
-  Suppose this takes a long time due to lagging nodes or slow applying of the state or any other reason.
-  While this is happening, the node that just left sends a join request to the cluster manager to rejoin the cluster. [This happens in an infinite loop on transport layer and the frequency is controlled by `discovery.find_peers_interval` setting]
-  The role of this join request is to re-establish any required connections and do some pre-validations before queuing a new task.
-  After join request is validated by cluster manager node, cluster manager queues a `node-join` task into its thread.
-  This `node-join` task would only start after the `node-left` task is completed since cluster-manager is single threaded.
-  Now suppose the `node-left` task has completed publication and has started to apply the new state on the cluster manager.
-  As part of applying the cluster state of `node-left` task, cluster manager wipes out the connection to the leaving node.
-  The `node-left` task then completes and the `node-join` task begins.
-  Now the `node-join` task starts. This task assumes that because the previous join request succeeded, that the connection to the joining node would still be there.
-  So then the cluster manager computes the new state.
-  Then it tells the `FollowersChecker` thread to add this new node.
-  Then it tries to publish the new state to all the nodes.
-  However, at this point, the `FollowerChecker` thread fails with `NodeNotConnectedException` because the connection was wiped and triggers a new `node-left` task.
-  If the new `node-left` task also takes time, we end up in an infinite loop of `node-left` and `node-join` tasks.
- Even if the `FollowerChecker` is modified to handle this `NodeNotConnectedException` gracefully without triggering a `node-left` task, the state publication to this joining node still fails because the connection was wiped. So the `node-join` state never completes on the joining node and it forever remains in candidate phase.

To summarise, if we allow a `node-join` task into the queue before the `node-left` task disconnects from the node, we will see the race condition happen.

#### Fix:
 As part of the fix for this, we now reject the initial join request from a node that has an ongoing `node-left` task.
 The join request will only succeed after the `node-left` task completes committing state on cluster manager, so the connection that gets created as part of the join request does not get wiped out and cause `node-join` task to fail.

This is done by marking nodes as pending disconnect right before publish state of `node-left` task.
We mark the nodes as completed disconnect after commit state of `node-left` task, or on re-election of cluster manager.

If there is a connection request from cluster-manager to any other node during this time, we reject the connection request. This blocks join requests because during join requests, cluster-manager tries to connect to the node trying to join. 

The join request will keep retrying, and once the `node-left` succeeds, the join request will be able to make a connection and succeed.

#### Main classes:

 - Coordinator - where publication begins
 - ClusterConnectionManager - low level connection class. has connection logic and book-keeping. Used by both TransportService and NodeConnectionsService. Core changes made here. 
 - ClusterApplierService - entry point of node connects/disconnects in cluster state commit flow.
 - NodeConnectionsService - abstraction used only by ClusterApplierService to handle connections/disconnections.
 - TransportService - called by Coordinator and NodeConnectionsService to connect/disconnect.
 - NodeJoinLeftIT - IT to simulate the issue

### Related Issues
Resolves #4874

### Check List
- [X] Functionality includes testing.
- [N/A] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [N/A] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java [hunk 1]
```diff
@@ -626,9 +632,9 @@ private void handleJoinRequest(JoinRequest joinRequest, JoinHelper.JoinCallback
             return;
         }
 
-        transportService.connectToNode(joinRequest.getSourceNode(), ActionListener.wrap(ignore -> {
+        // cluster manager connects to the node
+        transportService.connectToNodeAndBlockDisconnects(joinRequest.getSourceNode(), ActionListener.wrap(ignore -> {
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java:636]: good point, we would need to handle failure of validateJoinRequest as well, which is not currently done

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 2]
```diff
@@ -64,6 +65,7 @@ public class ClusterConnectionManager implements ConnectionManager {
 
     private final ConcurrentMap<DiscoveryNode, Transport.Connection> connectedNodes = ConcurrentCollections.newConcurrentMap();
     private final ConcurrentMap<DiscoveryNode, ListenableFuture<Void>> pendingConnections = ConcurrentCollections.newConcurrentMap();
+    private final Set<DiscoveryNode> pendingLeft = ConcurrentCollections.newConcurrentSet();
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:68]: can we name it as `pendingDisconnections`

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 3]
```diff
@@ -110,6 +112,22 @@ public void openConnection(DiscoveryNode node, ConnectionProfile connectionProfi
         internalOpenConnection(node, resolvedProfile, listener);
     }
 
+    @Override
+    public Set<DiscoveryNode> getNodesLeftInProgress() {
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:116]: Do we need to expose this to the caller ? 

Can we check during connect & remove from the list once disconnect is completed ?

File: server/src/main/java/org/opensearch/transport/ConnectionManager.java [hunk 4]
```diff
@@ -63,6 +64,12 @@ void connectToNode(
 
     boolean nodeConnected(DiscoveryNode node);
 
+    Set<DiscoveryNode> getNodesLeftInProgress();
+
+    boolean markPendingLeftCompleted(DiscoveryNode node);
+
+    void markPendingLefts(List<DiscoveryNode> nodes);
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/transport/ConnectionManager.java:71]: I think we can add one method to interface `markNodeForDisconnect(node)`. Others should be mostly internal.

File: server/src/main/java/org/opensearch/transport/RemoteConnectionManager.java [hunk 5]
```diff
@@ -119,6 +119,21 @@ public ConnectionProfile getConnectionProfile() {
...
+
+    @Override
+    public boolean markPendingLeftCompleted(DiscoveryNode node) {
+        throw new UnsupportedOperationException("not implemented");
+    }
+
+    @Override
+    public void markPendingLefts(List<DiscoveryNode> nodes) {
+        throw new UnsupportedOperationException("not implemented");
+    }
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/transport/RemoteConnectionManager.java:135]: We can provide a default no-op implementation in the interface.

File: server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java [hunk 6]
```diff
@@ -1353,6 +1368,9 @@ assert getLocalNode().equals(clusterState.getNodes().get(getLocalNode().getId())
                 followersChecker.setCurrentNodes(publishNodes);
                 lagDetector.setTrackedNodes(publishNodes);
                 coordinationState.get().handlePrePublish(clusterState);
+                // trying to mark pending disconnects before publish
+                // if we try to joinRequest during pending disconnect, it should fail
+                transportService.markPendingConnections(clusterChangedEvent.nodesDelta());
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java:1373]: Should we mark connections before we update leaderChecker in line 1367

File: server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java [hunk 7]
```diff
@@ -625,10 +630,19 @@ private void handleJoinRequest(JoinRequest joinRequest, JoinHelper.JoinCallback
...
+        // if node-left is still in progress, we fail the joinRequest early
+        if (transportService.getNodesLeftInProgress().contains(joinRequest.getSourceNode())) {
+            joinCallback.onFailure(
+                new IllegalStateException(
+                    "cannot join node [" + joinRequest.getSourceNode() + "] because node-left is currently in progress for this node"
+
+                )
+            );
+            return;
+        }
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java:642]: this check can be moved to `transportService.connectToNode`

File: server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java [hunk 8]
```diff
@@ -389,8 +390,13 @@ public String toString() {
             protected void doRun() {
                 assert Thread.holdsLock(mutex) == false : "mutex unexpectedly held";
                 transportService.disconnectFromNode(discoveryNode);
+                transportService.markPendingLeftAsCompleted(discoveryNode);
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java:393]: Can this be done as part of `transportService.disconnectFromNode` ?

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 9]
```diff
@@ -110,6 +112,22 @@ public void openConnection(DiscoveryNode node, ConnectionProfile connectionProfi
...
+        return this.pendingLeft;
+    }
+
+    @Override
+    public void markPendingLefts(List<DiscoveryNode> nodes) {
+        logger.info("marking pending left for nodes: [{}]", nodes);
+        pendingLeft.addAll(nodes);
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:123]: this has to probably snapshot the Connection object also from `connectedNodes` that can be later closed.

**Comment by rahulkarajgikar** [comment]
rebased main

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 10]
```diff
@@ -226,6 +244,25 @@ public void disconnectFromNode(DiscoveryNode node) {
             // if we found it and removed it we close
             nodeChannels.close();
         }
+        pendingDisconnections.remove(node);
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:247]: Should we also remove as part of connection close listener in line 173?

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java [hunk 11]
```diff
@@ -0,0 +1,194 @@
...
+        MockTransportService redTransportService = (MockTransportService) internalCluster().getInstance(
+            TransportService.class,
+            redNodeName
+        );
+        redTransportService.addRequestHandlingBehavior(FOLLOWER_CHECK_ACTION_NAME, handlingBehavior);
+
+        // Loop runs 10 times to ensure race condition gets reproduced
+        for (int i = 0; i < 10; i++) {
+            // fail followerchecker by force to trigger node disconnect
+            // now followerchecker should fail and trigger node left
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:155]: Can this test become flaky ?  Lets also add a test to ClusterConnectionManagerTests

File: server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java [hunk 12]
```diff
@@ -174,6 +175,17 @@ public void disconnectFromNodesExcept(DiscoveryNodes discoveryNodes) {
             for (final DiscoveryNode discoveryNode : nodesToDisconnect) {
                 runnables.add(targetsByNode.get(discoveryNode).disconnect());
             }
+
+            // There might be some stale nodes that are in pendingDisconnect set from before but are not connected anymore
+            // This code block clears the pending disconnect for these nodes to avoid permanently blocking node joins
+            // This situation should ideally not happen
+            transportService.removePendingDisconnections(
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java:182]: Right, this is correct.
This check was meant to be specifically to remove nodes that have pending disconnect marked but don't have entries present in `targetsByNode` list, so disconnect would not ever be called for these nodes.

Will update this to also have a check ensuring the node is not there in targetsByNode.

`.filter(discoveryNode -> !discoveryNodes.nodeExists(discoveryNode) && !targetsByNode.containsKey(discoveryNode))`

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 13]
```diff
@@ -122,12 +129,23 @@ public void connectToNode(
         ConnectionValidator connectionValidator,
         ActionListener<Void> listener
     ) throws ConnectTransportException {
+        logger.trace("[{}]connecting to node [{}]", Thread.currentThread().getName(), node);
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:132]: will remove this

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 14]
```diff
@@ -122,12 +129,23 @@ public void connectToNode(
...
         if (node == null) {
             listener.onFailure(new ConnectTransportException(null, "can't connect to a null node"));
             return;
         }
 
+        // if node-left is still in progress, we fail the connect request early
+        if (pendingDisconnections.contains(node)) {
+            listener.onFailure(
+                new IllegalStateException(
+                    "blocked connection to node [" + node + "] because node-left is currently in progress for this node"
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:143]: sure will update this

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 15]
```diff
@@ -122,12 +129,23 @@ public void connectToNode(
...
         ConnectionProfile resolvedProfile = ConnectionProfile.resolveConnectionProfile(connectionProfile, defaultProfile);
         if (node == null) {
             listener.onFailure(new ConnectTransportException(null, "can't connect to a null node"));
             return;
         }
 
+        // if node-left is still in progress, we fail the connect request early
+        if (pendingDisconnections.contains(node)) {
+            listener.onFailure(
+                new IllegalStateException(
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:142]: follower node would retry join infinitely.

PeerFinder.handleWakeUp() runs every `discovery.findPeersInterval` seconds and tries to join the active cluster-manager when it finds it.

Saw this happening in NodeJoinLeftIT logs, but will add a test specifically for this by delaying removing the pending disconnect for some time and validating that join eventually succeeds.

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java (hunk 10 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:247]: Yeah that makes sense since not all disconnect flows will go through this function, good catch.
Ideally this `pendingDisconnects` list would only matter here (since this function is called in applyCommit of node-left flow), but I agree it is much safer to also clear it as part of close listener as well to ensure we don't have any stale entries, similar to how `connectedNodes` is also cleared in both places

File: server/src/main/java/org/opensearch/transport/ConnectionManager.java [hunk 16]
```diff
@@ -65,6 +65,12 @@ void connectToNode(
 
     void disconnectFromNode(DiscoveryNode node);
 
+    Set<DiscoveryNode> getPendingDisconnections();
+
+    void setPendingDisconnections(Set<DiscoveryNode> nodes);
+
+    void removePendingDisconnections(Set<DiscoveryNode> nodes);
+
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ConnectionManager.java:73]: Makes sense, will update this

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 11 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:155]: Test should not become flaky because we are fixing node-join node-left logic at connection level.
And the timeout for cluster health is 60s which is more than enough time.
Just to ensure, will run this test 1000 times and confirm.

Will also add some additional coverage in ClusterConnectionManagerTests.

File: server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (rajiv-kv) [reply server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java:184]: Why would it happen that the node is disconnected but it still part of pendingDisconnect list ?

[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java:184]: This is the scenario we were seeing in `CoordinatorTests` failures

This was due to the custom extension of ClusterApplierService in these tests which are completely skipping connectToNodes logic:

```
@Override
        protected void connectToNodesAndWait(ClusterState newClusterState) {
            // don't do anything, and don't block
        }
```

In this scenario, `targetsByNode` never gets reconstructed when a new node is connected.

In state commit flow, after `connectToNodesAndWait`  is called, `nodeConnectionsService.disconnectFromNodesExcept(newClusterState.nodes());` is then called 

This function uses `targetsByNode` to decide which nodes to disconnect. So in this case, we were seeing that during node-left task for a node, the pendingDisconnections list was never getting cleared up because it didn't have an entry in `targetsByNode`

**Comment by rahulkarajgikar** [comment]
force pushed to rebase from main

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 11 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java]: ran the test 100 times, didn't see any failures. running it more times

**Comment by rahulkarajgikar** [comment]
> ❕ Gradle check result for [9d61e51](https://github.com/opensearch-project/OpenSearch/commit/9d61e51fe70fb9e4cc37f3a24db5660e38c53cf0): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/47585/)
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

https://github.com/opensearch-project/OpenSearch/issues/15806

File: server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java [hunk 17]
```diff
@@ -1354,6 +1362,9 @@ assert getLocalNode().equals(clusterState.getNodes().get(getLocalNode().getId())
                 currentPublication = Optional.of(publication);
 
                 final DiscoveryNodes publishNodes = publishRequest.getAcceptedState().nodes();
+                // marking pending disconnects before publish
+                // if a nodes tries to send a joinRequest while it is pending disconnect, it should fail
+                transportService.setPendingDisconnections(new HashSet<>(clusterChangedEvent.nodesDelta().removedNodes()));
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java:1367]: Instead of calling transportService directly for tracking pending disconnection. I have following suggestion

In ```ClusterConnectionManager.java```  via ```ConnectionManager``` interface add
```
    @Override
    public void trackPendingDisconnection(DiscoveryNode node) {
        //
    }
```
 and add same method in TransportService.java as well.
Then in NodeConnectionsService.java update the disconnect() method to
```
     Runnable disconnect() {
            transportService.trackPendingDisconnection(discoveryNode);   // track pending disconnection
            return addListenerAndStartActivity(
                null,
                ActivityType.DISCONNECTING,
                disconnectActivity,
                "connection cancelled by disconnection"
            );
        }
```

File: server/src/main/java/org/opensearch/transport/ConnectionManager.java [hunk 18]
```diff
@@ -65,6 +65,10 @@ void connectToNode(
 
     void disconnectFromNode(DiscoveryNode node);
 
+    void setPendingDisconnection(DiscoveryNode node);
+
+    void clearPendingDisconnections();
+
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/transport/ConnectionManager.java:71]: these method may not be needed with above suggestion

File: server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java (hunk 17 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java:1367]: I don't think this would work

The idea currently is to mark the pending disconnect at the start of node-left task _before state publication_.
This blocks any node-join tasks from getting queued until node-left task has completed state publication and state commit.

This `disconnect()` runnable runs as part of state commit phase of node-left task which happens after state publication.
So if we mark the disconnect as pending as part of state commit, it could be too late and join request might have already succeeded and queued a node-join task.

Scenario:
1. some node leaves due to a legitimate reason and triggers a node-left task
2. node-left task starts - it updates followerchecker and leaderchecker and starts state publication. 
3. leadercheck requests from leaving node now get rejected by cluster-manager.
4. leaving node sees that leader checks got rejected and goes into candidate mode and starts discovery.
5. leaving node sends a join request when it finds the active cluster-manager.
6. join request succeeds and queues a node-join task into cluster-manager
7. now node-left state publication completes and begins state commit.
8. node-left task marks the leaving node as pending disconnection, wipes the connection, completes the disconnection and removes the pending disconnection entry. node-left task then completes state commit.
9. node-join task starts processing and fails state publication because the connection was wiped.

In this scenario, the join request succeeds before the connection is wiped by node-left state commit. This is why we get into the race condition.
Instead, we need to ensure that join requests fail at any point while node-left is ongoing to avoid the race condition.

In order to do this, we need to mark the pending disconnect before state publication itself.
This wouldn't be possible if we marked as part of disconnect runnable - it has to be done in `Coordinator`

Let me know your thoughts

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java [hunk 19]
```diff
@@ -0,0 +1,393 @@
...
+ So then the cluster manager computes the new state.
+ Then it tells the followerchecker thread to add this new node.
+ Then it tries to publish the new state to all the nodes.
+ However, at this point, the followerchecker thread fails because the connection was wiped and triggers a new node-left task.
+ If the new node-left task also takes time, we end up in an infinite loop of node-left and node-joins.
+
+Fix:
+ As part of the fix for this, we now reject the initial join request from a node that has an ongoing node-left task.
+ The join request will only succeed after the node-left task completes, so the connection that gets created as part of the join request does not get wiped out and cause node-join task to fail.
+ */
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:91]: Ack will move this

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 20]
```diff
@@ -122,12 +131,19 @@ public void connectToNode(
...
             listener.onFailure(new ConnectTransportException(null, "can't connect to a null node"));
             return;
         }
 
+        // if node-left is still in progress, we fail the connect request early
+        if (pendingDisconnections.contains(node)) {
+            listener.onFailure(new IllegalStateException("cannot make a new connection as disconnect to node [" + node + "] is pending"));
+            return;
+        }
+
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:146]: connect requests fail - saw this happening as part of join request flow.

join request keeps retrying infinitely. it would succeed after the node-left task has finished committing state on cluster-manager

File: server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java (hunk 17 above)
Comment (shwetathareja) [reply server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java:1367]: got your point. should we move this ```nodeConnectionsService.disconnectFromNodesExcept(newClusterState.nodes());``` call itself in publish method directly?

Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java:1367]: This would probably work for cluster-manager since it handles publication, but then other nodes would not disconnect from the leaving node once the new state is committed so we might see some other issues.

I think this is why it is currently being done as part of state commit phase - since it runs on all nodes.

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 11 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java]: ran the test 500 more times, no failures

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 19 above)
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:91]: moved this to PR description, will remove this in subsequent commit

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java (hunk 20 above)
[the remark this answers is not in the document]
Comment (Bukhtawar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:146]: Can we optimise this to maintain not more than two connection per node one old and one new. We cut over from old to new connection on new node join. This should allow faster re-connections while waiting on older connections to drain?

[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:146]: closed on this, we are good with the current approach itself

**Comment by rahulkarajgikar** [comment]
> ❌ Gradle check result for [e40289f](https://github.com/opensearch-project/OpenSearch/commit/e40289f89e339ae777bd95bf4101611dbf1b23cd): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/47953/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

#15731

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java [hunk 21]
```diff
@@ -0,0 +1,368 @@
...
+
+import static org.opensearch.cluster.coordination.FollowersChecker.FOLLOWER_CHECK_ACTION_NAME;
+import static org.hamcrest.Matchers.is;
+
+/**
+ Check https://github.com/opensearch-project/OpenSearch/issues/4874 and
+ https://github.com/opensearch-project/OpenSearch/pull/15521 for context
+ */
+@ClusterScope(scope = Scope.TEST, numDataNodes = 0)
+public class NodeJoinLeftIT extends OpenSearchIntegTestCase {
```
Comment (shwetathareja) [inline server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:68]: can we run these tests for 5000 iterations locally to ensure no flakiness.

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java [hunk 22]
```diff
@@ -0,0 +1,368 @@
...
+                    .put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, 0)
+            )
+            .get();
+
+        ClusterService cmClsService = internalCluster().getInstance(ClusterService.class, cm);
+        // Simulate a slow applier on the cm to delay node-left state application
+        cmClsService.addStateApplier(event -> {
+            if (event.nodesRemoved()) {
+                try {
+                    Thread.sleep(3000);
```
Comment (shwetathareja) [inline server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:207]: is this sufficient to generate the race condition, do this test fail without your fix?

**Review by shwetathareja — COMMENTED** [review]
Thanks @rahulkarajgikar for the changes. Minor comments!

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 22 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:207]: yes, the test fails. validated that the same exception in FollowersChecker - `NodeNotConnectedException` is showing up

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 23]
```diff
@@ -226,6 +243,19 @@ public void disconnectFromNode(DiscoveryNode node) {
             // if we found it and removed it we close
             nodeChannels.close();
         }
+        pendingDisconnections.remove(node);
+        logger.debug("Removed node [{}] from pending disconnections list", node);
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java]: updated to trace, thanks for the input

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 24]
```diff
@@ -226,6 +243,19 @@ public void disconnectFromNode(DiscoveryNode node) {
...
+    }
+
+    @Override
+    public void setPendingDisconnection(DiscoveryNode node) {
+        logger.debug("marking disconnection as pending for node: [{}]", node);
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java]: updated to trace

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java [hunk 25]
```diff
@@ -2492,6 +2487,24 @@ protected void assertSnapshotOrGenericThread() {
...
 
+            public NodeConnectionsService createTestNodeConnectionsService(
+                Settings settings,
+                ThreadPool threadPool,
+                TransportService transportService
+            ) {
+                return new NodeConnectionsService(settings, threadPool, transportService) {
+                    @Override
+                    public void connectToNodes(DiscoveryNodes discoveryNodes, Runnable onCompletion) {
+                        // just update targetsByNode to ensure disconnect runs for these nodes
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:2498]: how is this different from `super.connectToNodes` ?

File: test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java [hunk 26]
```diff
@@ -1187,6 +1191,7 @@ protected Optional<DisruptableMockTransport> getDisruptableMockTransport(Transpo
                     new ClusterManagerMetrics(NoopMetricsRegistry.INSTANCE),
                     null
                 );
+                coordinator.setNodeConnectionsService(nodeConnectionsService);
```
Comment (rajiv-kv) [inline test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java:1194]: should this be moved to `setUp` method ?

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java [hunk 27]
```diff
@@ -0,0 +1,368 @@
...
+            .put(NodeConnectionsService.CLUSTER_NODE_RECONNECT_INTERVAL_SETTING.getKey(), "10s")
+            .put(FollowersChecker.FOLLOWER_CHECK_TIMEOUT_SETTING.getKey(), "200ms")
+            .put(FollowersChecker.FOLLOWER_CHECK_INTERVAL_SETTING.getKey(), "100ms")
+            .put(FollowersChecker.FOLLOWER_CHECK_RETRY_COUNT_SETTING.getKey(), 1)
+            .put(NodeConnectionsService.CLUSTER_NODE_RECONNECT_INTERVAL_SETTING.getKey(), "100ms")
+            .build();
+        // start a 3 node cluster with 1 cluster-manager
+        final String cm = internalCluster().startNode(nodeSettings);
+        internalCluster().startNode(Settings.builder().put("node.attr.color", "blue").put(nodeSettings).build());
+        final String redNodeName = internalCluster().startNode(Settings.builder().put("node.attr.color", "red").put(nodeSettings).build());
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:186]: Can we move to setup method ?

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 28]
```diff
@@ -122,12 +131,19 @@ public void connectToNode(
...
     ) throws ConnectTransportException {
+        logger.trace("connecting to node [{}]", node);
         ConnectionProfile resolvedProfile = ConnectionProfile.resolveConnectionProfile(connectionProfile, defaultProfile);
         if (node == null) {
             listener.onFailure(new ConnectTransportException(null, "can't connect to a null node"));
             return;
         }
 
+        // if node-left is still in progress, we fail the connect request early
+        if (pendingDisconnections.contains(node)) {
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:142]: - Can we add a test to ClusterConnectionManagerTests to verify the behviour of `connectToNode` when there are pending disconnect ?

File: server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java [hunk 29]
```diff
@@ -159,6 +164,14 @@ public void connectToNodes(DiscoveryNodes discoveryNodes, Runnable onCompletion)
         runnables.forEach(Runnable::run);
     }
 
+    public void setPendingDisconnections(Set<DiscoveryNode> nodes) {
+        nodes.forEach(transportService::setPendingDisconnection);
+    }
+
+    public void clearPendingDisconnections() {
+        transportService.clearPendingDisconnections();
+    }
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java:173]: Can we add UT's for these new methods ?
We need to verify that the ConnectionChecker is able to handle the error being thrown by TransportService#connectToNode . Lets add tests to `NodeConnectionsServiceTests`

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java [hunk 30]
```diff
@@ -64,6 +64,15 @@ public class ClusterConnectionManager implements ConnectionManager {
 
     private final ConcurrentMap<DiscoveryNode, Transport.Connection> connectedNodes = ConcurrentCollections.newConcurrentMap();
     private final ConcurrentMap<DiscoveryNode, ListenableFuture<Void>> pendingConnections = ConcurrentCollections.newConcurrentMap();
+    /**
+     This set is used only by cluster-manager nodes.
+     Nodes are marked as pending disconnect right before cluster state publish phase.
+     They are cleared up as part of cluster state apply commit phase
+     This is to avoid connections from being made to nodes that are in the process of leaving the cluster
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:71]: We will require tests in `JoinHelperTests` to verify if the followers are able to handle the new error and re-attempt to join the cluster. Can we add them ?

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 25 above)
Comment (rahulkarajgikar) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:2498]: we are only updating `targetsByNode` in the override and skipping all the actual connection logic

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java (hunk 30 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:71]: `JoinHelperTests` is manually calling `sendJoinRequest` and validating the functionality, it might not be possible to verify the retry logic here since that happens through discovery in `PeerFinder`

`Coordinator.handleJoinRequest` already had previous cases where join request could fail and it would call the `JoinCallback.onFailure`. Even the `connectToNode` call in `handleJoinRequest` already had logic to call the join callback if it failed with any exception.

I believe the ITs we have added are sufficient since we are able to validate that the node is joining back successfully

File: server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java (hunk 29 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/cluster/NodeConnectionsService.java:173]: added a test to verify that ConnectionChecker is able to keep running in the background and eventually succeed when pending disconnects is cleared

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java (hunk 28 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:142]: added a test for this

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 21 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:69]: i ran it 1000 times previously, running it more

File: server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java (hunk 30 above)
Comment (rahulkarajgikar) [reply server/src/main/java/org/opensearch/transport/ClusterConnectionManager.java:71]: i have added an assertion in NodeJoinLeftIT that validates that the correct exception is showing up when the join request fails. The test itself validates that the join eventually succeeds

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java [hunk 31]
```diff
@@ -490,6 +492,72 @@ public void testDebugLogging() throws IllegalAccessException {
...
+        // now trigger a disconnect, and then set pending disconnections to true to fail any new connections
+        final long maxDisconnectionTime = 1000;
+        final long disconnectionTime = 100;
+        deterministicTaskQueue.scheduleAt(disconnectionTime, new Runnable() {
+            @Override
+            public void run() {
+                transportService.disconnectFromNode(node);
+                logger.info("--> setting pending disconnections to fail next connection attempts");
+                service.setPendingDisconnections(new HashSet<>(Collections.singleton(node)));
+                transportService.resetConnectToNodeCallCount();
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java:536]: Can this be reset - after verifying that the connect attempt of connection checker failed once with the expected exception message ?

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java [hunk 32]
```diff
@@ -490,6 +492,72 @@ public void testDebugLogging() throws IllegalAccessException {
...
+
+        final AtomicBoolean connectionCompleted = new AtomicBoolean();
+        service.connectToNodes(nodes, () -> connectionCompleted.set(true));
+        deterministicTaskQueue.runAllRunnableTasks();
+        assertTrue(connectionCompleted.get());
+
+        // now trigger a disconnect, and then set pending disconnections to true to fail any new connections
+        final long maxDisconnectionTime = 1000;
+        final long disconnectionTime = 100;
+        deterministicTaskQueue.scheduleAt(disconnectionTime, new Runnable() {
```
Comment (rajiv-kv) [inline server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java:530]: Not sure the intent of running this at fixed schedule ?

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java [hunk 33]
```diff
@@ -0,0 +1,374 @@
...
+        }
+
+        succeedFollowerChecker.set(true);
+        ClusterHealthResponse response = client().admin().cluster().prepareHealth().setWaitForNodes("3").get();
+        assertThat(response.isTimedOut(), is(false));
+
+        // assert that the right exception message showed up in logs
+        assertTrue(
+            "Expected IllegalStateException was not logged",
+            testAppender.containsExceptionMessage("IllegalStateException[cannot make a new connection as disconnect to node")
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:220]: Can we also verify the message logged on the datanode ?

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java [hunk 34]
```diff
@@ -0,0 +1,374 @@
...
+        );
+    }
+
+    public void testRestartDataNode() throws Exception {
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:301]: If the intent is to create node-left in successions, it might be good to see if we can cause n/w disruption rather than restart a node which is slow. The scenario could be something like this
- spin up a 10 node cluster
- cause a network disruption for 5 nodes (randomly)
- verify if the follower check removes
- restore the network (as the nodes are getting removed)
- wait until the cluster has 10 nodes

File: server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java (hunk 25 above)
Comment (rajiv-kv) [reply server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java:2498]: Given that it is an existing test, why is this change required to skip connection logic now ?

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 34 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:301]: The intent behind this test is mainly to just do basic sanity of data node restart and validate that nodes are able to join back in a normal case without any slowness

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java (hunk 31 above)
Comment (rahulkarajgikar) [reply server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java:536]: the tasks (disconnect, subsequent reconnect from connection checker) only run in the `runTasksUntil` blocks and are not running at any other point because of the deterministic task queue. We can't wait in this block for the exception to show up because the connection checker task won't run here.
Because of this deterministicTaskQueue which only runs in `runTasksUntil`, we are also guaranteed that when we clear it here, the next one we are seeing would be the first connection attempt after marking disconnects as pending.

Since we are already waiting for 5 connection attempts after this, and verifying that they all fail, we are validating that the connection checker is working and able to handle the exception.

I do agree we should have an assertion to actually validate that we are seeing the expected exception, so I will add a separate assertion after `runTasksUntil`

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java [hunk 35]
```diff
@@ -490,6 +492,72 @@ public void testDebugLogging() throws IllegalAccessException {
...
+            }
+
+            @Override
+            public String toString() {
+                return "scheduled disconnection of " + node;
+            }
+        });
+
+        // ensure the disconnect task completes, give extra time also for connection checker tasks
+        runTasksUntil(deterministicTaskQueue, maxDisconnectionTime);
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java:546]: yes, we already have a counter we are using.
will make a change to remove this, and instead wait until we see the count condition for reconnection attempts

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java (hunk 32 above)
Comment (rahulkarajgikar) [reply server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java:530]: agree this is not necessary, we can schedule immediately

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 33 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:220]: yes, will add this

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java [hunk 36]
```diff
@@ -0,0 +1,374 @@
...
+            Task task
+        ) throws Exception {
+
+            connectionBreaker.run();
+            handler.messageReceived(request, channel, task);
+        }
+    }
+
+    private static class TestAppender extends AbstractAppender {
+        private final List<String> logs = new ArrayList<>();
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:351]: ack making this change

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 33 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java]: added this

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java (hunk 32 above)
Comment (rahulkarajgikar) [reply server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java]: changed to immediately schedule

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java (hunk 31 above)
Comment (rahulkarajgikar) [reply server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java:546]: updated the test to wait for the required count and also assert on the generated exception

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java (hunk 35 above)
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java]: updated the test to exit the tasks early if it meets the count condition before the timeout

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 36 above)
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java]: made this change

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java (hunk 31 above)
Comment (rajiv-kv) [reply server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java:546]: The suggestion was to wait in the main loop of the test and not in the task. I was thinking of incrementing a counter from the task#run and waiting for the condition from main loop. In that way we need not have a time based bounded wait  `maxDisconnectionTime + maxReconnectionTime`

**Review by rajiv-kv — COMMENTED** [review]
LGTM ! Some minor comments on test.

File: test/framework/src/main/java/org/opensearch/test/TestLogsAppender.java [hunk 37]
```diff
@@ -0,0 +1,74 @@
...
+
+    @Override
+    public void append(LogEvent event) {
+        if (shouldCaptureMessage(event.getMessage().getFormattedMessage())) capturedLogs.add(event.getMessage().getFormattedMessage());
+        if (event.getThrown() != null) {
+            if (shouldCaptureMessage(event.getThrown().toString())) capturedLogs.add(event.getThrown().toString());
+            for (StackTraceElement element : event.getThrown().getStackTrace())
+                if (shouldCaptureMessage(element.toString())) capturedLogs.add(element.toString());
+        }
+    }
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply test/framework/src/main/java/org/opensearch/test/TestLogsAppender.java:42]: - formatting is done as per spotlessApply, not sure if i can change much here.
 - pattern match needs to be on message and any thrown exceptions because we also need to check exception message for our use-case

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java [hunk 38]
```diff
@@ -490,6 +500,93 @@ public void testDebugLogging() throws IllegalAccessException {
...
+        assertTrue(connectionCompleted.get());
+
+        // now trigger a disconnect, and then set pending disconnections to true to fail any new connections
+        final long maxDisconnectionTime = 1000;
+        deterministicTaskQueue.scheduleNow(new Runnable() {
+            @Override
+            public void run() {
+                transportService.disconnectFromNode(node);
+                logger.info("--> setting pending disconnections to fail next connection attempts");
+                service.setPendingDisconnections(new HashSet<>(Collections.singleton(node)));
```
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java:542]: We would need to introduce a new method like `disconnectFromNodeWithoutClearingDisconnection` in multiple classes for this. 3 methods in ConnectionManager classes + additional method in transportService to call the ConnectionManager. 

Essentially we are trying to achieve the same thing - we want the node to actually disconnect but the pending disconnections to remain, and then see what happens.

And the main thing we are asserting here is that the connection reattempt is happening and failing as expected.
I don't feel it is worth adding so many new methods for simulating the same behaviour. Thoughts?

[the remark this answers is not in the document]
Comment (rajiv-kv) [reply server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java:542]: The task that is getting scheduled seems to be performing multiple things
- preparing for the test
- setting Pending Disconnections.
- cleaning up for the test

Could we seperate out concerns and have the task perform only the second one (mimicing the publish thread) ?
Can you move out the prepare (before the schedule) and clean-up (after verification) to test-main ?

I think the methods can be added to TestTransportService (if required) for prepare / verification. Agree that we should not be adding to the main code.

File: test/framework/src/main/java/org/opensearch/test/TestLogsAppender.java (hunk 37 above)
[the remark this answers is not in the document]
Comment (rajiv-kv) [reply test/framework/src/main/java/org/opensearch/test/TestLogsAppender.java:42]: - Got it. The single line if was bit long to read.
- Lets add strict asserts in the test to exactly match the expected part of the log message. It would be good to assert on the actual exception with the expected one (`event.getThrown`) if possible.

**Comment by rahulkarajgikar** [comment]
https://build.ci.opensearch.org/job/gradle-check/48387/

[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/410_nested_aggs/Supported queries}](https://build.ci.opensearch.org/job/gradle-check/48387/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_410_nested_aggs_Supported_queries_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/410_nested_aggs/Supported queries}](https://build.ci.opensearch.org/job/gradle-check/48387/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_410_nested_aggs_Supported_queries__2/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/410_nested_aggs/Supported queries}](https://build.ci.opensearch.org/job/gradle-check/48387/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_410_nested_aggs_Supported_queries__3/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/410_nested_aggs/Supported queries}](https://build.ci.opensearch.org/job/gradle-check/48387/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_410_nested_aggs_Supported_queries__4/)

All 4 tests are flaky

File: server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java (hunk 21 above)
Comment (rahulkarajgikar) [reply server/src/internalClusterTest/java/org/opensearch/cluster/coordination/NodeJoinLeftIT.java:78]: ran it 5000 times and it passed all times

File: server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java (hunk 38 above)
[the remark this answers is not in the document]
Comment (rahulkarajgikar) [reply server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java]: updated this

**Review by shwetathareja — APPROVED** [review]
