### PR TITLE
Optimise TransportNodesAction to not send DiscoveryNodes for NodeStat…

### LINKED ISSUE #14713: [BUG] Stats transport actions based on TransportNodeActions sends large payload of Discovery Nodes to all nodes
### Describe the bug

In the current implementation, every transport action extending TransportNodesAction includes all discovery nodes in the transport request sent to each node in the cluster. This approach leads to performance bottlenecks in large clusters due to redundant data transmission. Specifically:

1. Increased Network Traffic: The same list of discovery nodes is written n^2 times (where n is the number of nodes), causing unnecessary network traffic and increased IO.
2. Write/Read Latency: The excessive data transmission contributes to higher overall latency for both write and read operations.
3. NIO Buffer Bottleneck: When using plugins like Netty for inter-node communication, the buffer becomes overloaded with redundant discovery node information, increasing the size of the request and correspondingly reducing the amount of requests which can fit in the Netty buffer.

image

### Related component

Other

### To Reproduce

If NodeIDs are passed in the TransportNodeAction requests, [we resolve them into DiscoveryNodes](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java#L236-L239). This request is cloned by the individual requests which go to each node [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java#L259) which ends up write the discoveryNodes object.

Essentially for a 200 Node cluster, we are sending writing 200 discoveryNode objects for each request -> implying we write about 200x200 in the entire duration of the send path. This grows exponentially with number of nodes

### Expected behavior

The request path should only be sending information that is to be required on the receive path. 

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu-S**
### Description
In the current implementation, every transport action extending TransportNodesAction includes all discovery nodes in the transport request sent to each node in the cluster. This approach leads to performance bottlenecks in large clusters due to redundant data transmission. Specifically:

1. Increased Network Traffic: The same list of discovery nodes is written n^2 times (where n is the number of nodes), causing unnecessary network traffic and increased IO.
2. Write/Read Latency: The excessive data transmission contributes to higher overall latency for both write and read operations.
3. Netty Buffer Bottleneck: When using plugins like Netty for inter-node communication, the buffer becomes overloaded with redundant discovery node information, increasing the size of the request and correspondingly reducing the amount of requests which can fit in the Netty buffer.

image

This PR proposes a solution to address these bottlenecks by selectively skipping the resolution of concrete nodes at the transport layer. This optimization will significantly reduce redundant data transmission and improve overall performance in large clusters.

To do this, flag was introduced on the BaseNodeRequest Class`populateDiscoveryNodesInTransportRequest`. Requests in this flag overriden to `False` will skip adding the concrete nodes data into the request. Currently it is only implemented in NodeStats, ClusterStats and NodeInfo Call from the rest layer.

The perf gains are significant (tested in a large 1k node domain)
| API            | Stats   | Default (s) | Optimized (s) | % Reduction |
|----------------|---------|-------------|---------------|-------------|
| _nodes/stats   | Average |    10.03409 |       1.41749 | -86%        |
|                | P90     |    12.54658 |       5.80648 | -54%        |
|                | Max     |    16.39159 |      11.61396 | -30%        |
|                | Min     |     6.41173 |       0.35198 | -95%        |
| _nodes         | Average |     8.61528 |       3.66873 | -58%        |
|                | P90     |    13.19499 |       8.30744 | -38%        |
|                | Max     |    19.39874 |      15.91021 | -18%        |
|                | Min     |     6.56645 |       1.17164 | -83%        |
| _cat/nodes     | Average |    21.45014 |        1.0651 | -96%        |
|                | P90     |    26.95066 |       1.79513 | -94%        |
|                | Max     |    36.11789 |      17.46319 | -52%        |
|                | Min     |    15.26925 |       0.20656 | -99%        |
| _cluster/stats | Average |     9.82926 |       2.01671 | -80%        |
|                | P90     |    12.31955 |       6.52061 | -48%        |
|                | Max     |     17.9214 |      12.50545 | -31%        |
|                | Min     |     6.22867 |       0.27218 | -96%        |

### Related Issues
Resolves #14713 

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Pranshu-S** [comment]
[Test Result](https://build.ci.opensearch.org/job/gradle-check/42445/testReport/) (1 failure / +1)
[org.opensearch.cache.common.tier.TieredSpilloverCacheStatsIT.testStatsMatchOldApi](https://build.ci.opensearch.org/job/gradle-check/42445/testReport/junit/org.opensearch.cache.common.tier/TieredSpilloverCacheStatsIT/testStatsMatchOldApi/)

```
java.lang.AssertionError: expected:<org.opensearch.common.cache.stats.ImmutableCacheStats@35accfc> but was:<org.opensearch.common.cache.stats.ImmutableCacheStats@21b5fec>
```
Flaky Test - https://github.com/opensearch-project/OpenSearch/issues/14300

**Comment by Pranshu-S** [comment]
Empty test results. 
https://build.ci.opensearch.org/job/gradle-check/42454/
https://build.ci.opensearch.org/job/gradle-check/42446/

**Comment by Pranshu-S** [comment]
[Test Result](https://build.ci.opensearch.org/job/gradle-check/42506/testReport/) (1 failure / +1)
[org.opensearch.index.remote.RemoteSegmentTransferTrackerTests.testComputeTimeLagOnUpdate](https://build.ci.opensearch.org/job/gradle-check/42506/testReport/junit/org.opensearch.index.remote/RemoteSegmentTransferTrackerTests/testComputeTimeLagOnUpdate/)

---
Logs:
```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([6BDC3291A725F574:398E1293090095EE]:0)
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.opensearch.index.remote.RemoteSegmentTransferTrackerTests.testComputeTimeLagOnUpdate(RemoteSegmentTransferTrackerTests.java:157)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
```

Flaky Test Autocut - https://github.com/opensearch-project/OpenSearch/issues/14325

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java [hunk 1]
```diff
@@ -209,6 +209,15 @@ protected void resolveRequest(NodesRequest request, ClusterState clusterState) {
         request.setConcreteNodes(Arrays.stream(nodesIds).map(clusterState.nodes()::get).toArray(DiscoveryNode[]::new));
     }
 
+    /**
+     * Return the concrete nodes from the request node ids which will be later used for routing requests to nodes.
+     **/
```
Comment (sumitasr) [inline server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:214]: Can we please add this in form of detailed java doc outlining input and output params?

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java [hunk 2]
```diff
@@ -209,6 +209,15 @@ protected void resolveRequest(NodesRequest request, ClusterState clusterState) {
...
+    protected DiscoveryNode[] resolveConcreteNodes(NodesRequest request, ClusterState clusterState) {
```
Comment (sumitasr) [inline server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:215]: Can we call this getConcreteNodes? Since, we are just creating a list of nodes and returning from this method.

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java [hunk 3]
```diff
@@ -234,14 +244,27 @@ class AsyncAction {
...
+                    assert request.concreteNodes() == null;
+                }
+            } else {
+                this.concreteNodes = null;
+            }
+            if (request.concreteNodes() == null) {
+                assert concreteNodes != null;
+                this.responses = new AtomicReferenceArray<>(concreteNodes.length);
+            } else {
+                this.responses = new AtomicReferenceArray<>(request.concreteNodes().length);
```
Comment (sumitasr) [inline server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:262]: Can we please refactor and make it more readable?

File: server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+                }
+            });
+
+            combinedSentRequest.put(node, sentRequestList);
+        });
+
+        return combinedSentRequest;
+    }
+
+    public TestTransportClusterStatsAction getTestTransportClusterStatsAction() {
```
Comment (sumitasr) [inline server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java:100]: why this needs to be public?

File: server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java [hunk 5]
```diff
@@ -0,0 +1,134 @@
...
+import java.util.List;
+import java.util.Map;
+
+public class TransportClusterStatsActionTests extends TransportNodesActionTests {
+
+    /**
+     * By default, we send discovery nodes list to each request that is sent across from the coordinator node. This
+     * behavior is asserted in this test.
+     */
+    public void testDefaultBehavior() {
```
[the remark this answers is not in the document]
Comment (Pranshu-S) [reply server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java:39]: Makes sense, I think in long term we might want to remove the concreteNodes dependency completely. Will change the names of these tests across the board of newly introduced tests.

File: server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java (hunk 4 above)
Comment (Pranshu-S) [reply server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java:100]: No specific reason, these utilities might be helpful for other tests on these TransportActions so I thought we can keep it public and use it across. Since there are no tests right no other than the one I wrote, I think I can make it private.

**Comment by shwetathareja** [comment]
@Pranshu-S can you list down which API really use this list of discoveryNodes being send from the caller.

**Comment by Pranshu-S** [comment]
All Transport Actions extending TransportNodesAction use this list of Discovery Nodes. Namely - 

1. TransportGetAllPitsAction
2. TransportListDanglingIndicesAction
3. TransportNodesHotThreadsAction
4. TransportNodesInfoAction
5. TransportNodesListGatewayMetaState
6. TransportNodesListGatewayStartedShards
7. TransportNodesListGatewayStartedShardsBatch
8. TransportNodesListShardStoreMetadata
9. TransportNodesListShardStoreMetadataBatch
10. TransportNodesReloadSecureSettingsAction
11. TransportNodesSnapshotStatus
12. TransportNodesStatsAction
13. TransportNodesUsageAction


I will be opening a meta issue targeting other optimisations as well.

**Comment by shwetathareja** [comment]
> All Transport Actions extending TransportNodesAction use this list of Discovery Nodes.

@Pranshu-S no, i mean list the API for which we still need to serialize and send it in request instead of resolving from cluster state.

File: server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java [hunk 6]
```diff
@@ -65,6 +65,14 @@ public abstract class BaseNodesRequest<Request extends BaseNodesRequest<Request>
...
      * */
     private DiscoveryNode[] concreteNodes;
+
+    /**
+     * Since do not use the discovery nodes coming from the request in all code paths following a request extended off from
+     * BaseNodeRequest, we do not require it to sent around across all nodes.
+     *
+     * Setting default behavior as `true` but can be explicitly changed in requests that do not require.
+     */
+    private boolean populateDiscoveryNodesInTransportRequest = true;
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java:75]: serializeDiscoveryNodes

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java [hunk 7]
```diff
@@ -226,22 +238,45 @@ class AsyncAction {
...
             this.request = request;
             this.listener = listener;
-            if (request.concreteNodes() == null) {
+
+            // Check if concrete nodes are already available
+            if (request.concreteNodes() != null) {
+                this.responses = new AtomicReferenceArray<>(request.concreteNodes().length);
+
+                if (request.populateDiscoveryNodesInTransportRequest()) {
+                    this.concreteNodes = null;
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:255]: why this has to be set to null explicitly, it not initialized before this point.

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java [hunk 8]
```diff
@@ -226,22 +238,45 @@ class AsyncAction {
...
+            // concrete nodes.
+            if (request.populateDiscoveryNodesInTransportRequest()) {
                 resolveRequest(request, clusterService.state());
                 assert request.concreteNodes() != null;
+                this.responses = new AtomicReferenceArray<>(request.concreteNodes().length);
+                this.concreteNodes = null;
+            } else {
+                this.concreteNodes = getConcreteNodes(request, clusterService.state());
+                assert request.concreteNodes() == null;
+                this.responses = new AtomicReferenceArray<>(concreteNodes.length);
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:274]: The code looks confusing now.

You only need simple logic whether to serialize request.concreteNodes or not. You can request.concreteNodes to false based on the flag. Everything else can remain the same.

File: server/src/test/java/org/opensearch/action/RestStatsActionTests.java [hunk 9]
```diff
@@ -0,0 +1,48 @@
...
+    private final NodeClient client = new NodeClient(Settings.EMPTY, threadPool);
+
+    @After
+    public void terminateThreadPool() {
+        terminate(threadPool);
+    }
+
+    public void testClusterStatsActionPrepareRequestNoError() throws IOException {
+        RestClusterStatsAction action = new RestClusterStatsAction();
+        action.prepareRequest(new FakeRestRequest(), client);
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/action/RestStatsActionTests.java:36]: what are we asserting in this test

File: server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java [hunk 10]
```diff
@@ -0,0 +1,165 @@
...
+                assertEquals(sentRequest.getDiscoveryNodes().length, clusterService.state().nodes().getSize());
+            });
+        });
+    }
+
+    /**
+     * In the optimized ClusterStats Request, we do not send the DiscoveryNodes List to each node. This behavior is
+     * asserted in this test.
+     */
+    public void testClusterStatsActionWithDiscoveryNodesListNotPopulated() {
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java:75]: please rename the test not able to get difference between DiscoveryNodesNotPopulated vs DiscoveryNodesListInRestRequestNotPopulated

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java (hunk 7 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:255]: Since I have set the `concreteNodes` as final, it has to be initialised by the constructor. 
I have set it to `final` since we want the concrete nodes to be immutable at all cost since it decides where to route the requests to.

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java (hunk 8 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:274]: The reason why I am explicitly removing concreteNodes entirely from the request as well is to remove the amount of ConcreteNodes set in JVM memory at the time of the request being made. 

While the serialisation and deserialisation latencies will improve by taking this decision during the IO, the overall pressure on the coordinator node to store these number of heavy requests will remain the same. Also the request payload itself too will remain the same.

**Review by Bukhtawar — COMMENTED** [review]
Why not cache node attributes and just pass node ids. On the data node side each node can cache node attributes against a node id.

**Comment by Pranshu-S** [comment]
> Why not cache node attributes and just pass node ids. On the data node side each node can cache node attributes against a node id.

Hi Bukhtawar, We do not really require the node attributes for these Stats APIs updated in my PR. We can implement caching on data nodes for APIs which require these node attributes and utilise them.

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java [hunk 11]
```diff
@@ -238,10 +239,20 @@ class AsyncAction {
...
+
+            if (request.retainDiscoveryNodes() == false) {
+                // We transfer the ownership of discovery nodes to route the request to into the AsyncAction class.
+                // This reduces the payload of the request and improves the number of concrete nodes in the memory
+                this.concreteNodes = request.concreteNodes();
+                request.setConcreteNodes(null);
+            } else {
+                // initializing it separately as we keep the `concreteNodes` as final since we want it to be immutable.
+                this.concreteNodes = null;
+            }
```
Comment (Pranshu-S) [inline server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:251]: With the current approach, if we decide to retain `DiscoveryNodes`  in the request, we rely on DiscoveryNodes in the request in the AsyncAction.start(). Otherwise if we do not want to retain, we set the concreteNodes on the AsyncAction class and set the request's concreteNodes to `null`. 

This way we reduce the number of DiscoveryNodes in the heap as well as reduce the size of the request being sent.

File: CHANGELOG.md [hunk 12]
```diff
@@ -5,6 +5,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 
 ## [Unreleased 2.x]
 ### Added
+- Optimize TransportNodesAction to not send DiscoveryNodes for NodeStats, NodesInfo and ClusterStats call ([14749](https://github.com/opensearch-project/OpenSearch/pull/14749))
```
Comment (shwetathareja) [inline CHANGELOG.md:8]: move it to the end of the list

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java [hunk 13]
```diff
@@ -238,10 +239,20 @@ class AsyncAction {
...
             this.responses = new AtomicReferenceArray<>(request.concreteNodes().length);
+
+            if (request.retainDiscoveryNodes() == false) {
+                // We transfer the ownership of discovery nodes to route the request to into the AsyncAction class.
+                // This reduces the payload of the request and improves the number of concrete nodes in the memory
+                this.concreteNodes = request.concreteNodes();
+                request.setConcreteNodes(null);
+            } else {
+                // initializing it separately as we keep the `concreteNodes` as final since we want it to be immutable.
+                this.concreteNodes = null;
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:250]: why can't we initialize this.concreteNodes = request.concreteNodes(); irrespective of whether retainDiscoveryNodes() is true or false. It will be release as soon as the request has been sent to all nodes?

Comment (shwetathareja) [reply server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:250]: if check will be for
```
this.concreteNodes = request.concreteNodes();
if (request.retainDiscoveryNodes() == false) {
                request.setConcreteNodes(null);
    }
```
and no need for else

File: server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java [hunk 14]
```diff
@@ -0,0 +1,165 @@
...
+        combinedSentRequest.forEach((node, capturedRequestList) -> {
+            assertNotNull(capturedRequestList);
+            capturedRequestList.forEach(sentRequest -> {
+                assertNotNull(sentRequest.getDiscoveryNodes());
+                assertEquals(sentRequest.getDiscoveryNodes().length, clusterService.state().nodes().getSize());
+            });
+        });
+    }
+
+    public void testClusterStatsActionWithPreFilledConcreteNodesAndWithRetentionOfDiscoveryNodesList() {
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java:55]: how is this test different from above?

File: server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java [hunk 15]
```diff
@@ -119,6 +127,14 @@ public void setConcreteNodes(DiscoveryNode[] concreteNodes) {
         this.concreteNodes = concreteNodes;
     }
 
+    public void retainDiscoveryNodes(boolean value) {
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java:130]: sendConcreteNodes instead

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java (hunk 13 above)
Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:250]: Got it. Just wanted to reduce the number of list of discovery nodes in the heap at any point of time. If we set the concrete nodes but not use it, might as well not use. 

But I think this should not cause any regression as such so will change as per suggestion. Thanks!

File: server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java (hunk 14 above)
Comment (Pranshu-S) [reply server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java:55]: The only difference in these two tests is one we are not backfilling the discovery nodes prior to calling the TransportAction and in the second one we are backfilling and calling.

> testClusterStatsActionWithRetentionOfDiscoveryNodesList()

Tests when the DiscoveryNodes is not in the request. The nodes are correctly resolved in the AsyncAction. This is with `retainDiscoveryNodes` set to `True`.

> testClusterStatsActionWithPreFilledConcreteNodesAndWithRetentionOfDiscoveryNodesList()

We backfill the request with discovery nodes and check if the nodes are still correctly resolved and there are no issue with the new request formed.

File: server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java [hunk 16]
```diff
@@ -238,10 +239,20 @@ class AsyncAction {
...
+            }
         }
 
         void start() {
-            final DiscoveryNode[] nodes = request.concreteNodes();
+            final DiscoveryNode[] nodes = request.concreteNodes() != null ? request.concreteNodes() : concreteNodes;
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java:255]: you can then initialize this with final DiscoveryNode[] nodes = this.concreteNodes;

File: server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java [hunk 17]
```diff
@@ -119,6 +127,14 @@ public void setConcreteNodes(DiscoveryNode[] concreteNodes) {
         this.concreteNodes = concreteNodes;
     }
 
+    public void sendDiscoveryNodes(boolean value) {
```
Comment (Arpit-Bandejiya) [inline server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java:130]: nit: could be better named as `setSendDiscoveryNodes`. and getter as `getSendDiscoveryNodes`.

also should we use the name `includeDiscoveryNodes` as the flag instead of `sendDiscoveryNodes`?

Comment (Pranshu-S) [reply server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java:130]: Sure Arpit, can update the getter and setter, did not change it earlier as I thought it would make reading easier. Will update the variable name as well.

Thanks!

**Comment by Pranshu-S** [comment]
> ❌ Gradle check result for [a69f7e7](https://github.com/opensearch-project/OpenSearch/commit/a69f7e78ed9097319f3061c12b347248721d190d): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/42879/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[Test Result](https://build.ci.opensearch.org/job/gradle-check/42879/testReport/) (1 failure / -3)
[org.opensearch.remotestore.RemoteRestoreSnapshotIT.testRestoreShallowSnapshotIndexAfterSnapshot](https://build.ci.opensearch.org/job/gradle-check/42879/testReport/junit/org.opensearch.remotestore/RemoteRestoreSnapshotIT/testRestoreShallowSnapshotIndexAfterSnapshot/)

Flaky - https://github.com/opensearch-project/OpenSearch/issues/14324

**Review by shwetathareja — APPROVED** [review]
