### PR TITLE
Check UTF16 string size before converting to String to avoid OOME

### LINKED ISSUE #1651: Node drops out with OutOfMemoryError for reasons other than the VM having run out of memory
**Describe the bug**
Node can drop out for OutOfMemory errors other than the VM OutOfMemory like 
```
java.lang.OutOfMemoryError: UTF16 String size is 1089861360, should be less than 1073741823
```
This is coming from the implementation limits of StringUTF16.

```
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
    at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) ~[?:?]
    at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:763) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:952) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:977) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:216) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.transport.TcpTransport$1.doRun(TcpTransport.java:985) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1104) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleResponse(SearchTransportService.java:454) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:54) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:29) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.FetchSearchPhase$2.innerOnResponse(FetchSearchPhase.java:163) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.FetchSearchPhase$2.innerOnResponse(FetchSearchPhase.java:166) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.CountedCollector.onResult(CountedCollector.java:64) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.CountedCollector.countDown(CountedCollector.java:53) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:104) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:206) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:153) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:160) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:120) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:153) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:160) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.FetchSearchPhase$3.run(FetchSearchPhase.java:213) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:50) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:311) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:81) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.sendResponse(RestController.java:497) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.common.text.Text.toString(Text.java:94) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.common.text.Text.string(Text.java:89) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.elasticsearch.common.bytes.BytesReference.utf8ToString(BytesReference.java:98) ~[elasticsearch-6.8.0.jar:6.8.0]
    at org.apache.lucene.util.BytesRef.utf8ToString(BytesRef.java:138) ~[lucene-core-7.7.0.jar:7.7.0-SNAPSHOT bb8faecf0a738cf5294e398973014b0090e9dc51 - akjain - 2020-02-14 16:08:48]
    at java.lang.String.<init>(String.java:276) ~[?:?]
    at java.lang.String.<init>(String.java:3222) ~[?:?]
    at java.lang.StringUTF16.toBytes(StringUTF16.java:151) ~[?:?]
    at java.lang.StringUTF16.newBytesFor(StringUTF16.java:49) ~[?:?]
Caused by: java.lang.OutOfMemoryError: UTF16 String size is 1089861360, should be less than 1073741823
    at java.lang.Thread.run(Thread.java:834) [?:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:856) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
    at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:66) [transport-netty4-client-6.8.0.jar:6.8.0]
java.lang.Exception: java.lang.OutOfMemoryError: UTF16 String size is 1089861360, should be less than 1073741823

```
https://bugs.openjdk.java.net/browse/JDK-8230744

**To Reproduce**

**Expected behavior**
Nodes should not drop off the cluster due to a single request/response that doesn't affect VM directly

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by imRishN**
### Description
Node can drop out for OutOfMemory errors other than the VM OutOfMemory which comes from the implementation limits of StringUTF16.

```
java.lang.OutOfMemoryError: UTF16 String size is 1089861360, should be less than 1073741823
```

This PR attempts to pre check the size and throw an exception proactively before trying a conversion.

### Related Issues
Resolves #1651 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java [hunk 1]
```diff
@@ -82,7 +84,14 @@ public void writeTo(OutputStream os) throws IOException {
 
     @Override
     public String utf8ToString() {
-        return toBytesRef().utf8ToString();
+        BytesRef bytesRef = toBytesRef();
```
Comment (reta) [inline server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:87]: Would be great to have a test for it

File: CHANGELOG.md [hunk 2]
```diff
@@ -103,6 +103,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 - Compress and cache cluster state during validate join request ([#7321](https://github.com/opensearch-project/OpenSearch/pull/7321))
 - [Snapshot Interop] Add Changes in Create Snapshot Flow for remote store interoperability. ([#7118](https://github.com/opensearch-project/OpenSearch/pull/7118))
 - Add new query profile collector fields with concurrent search execution ([#7898](https://github.com/opensearch-project/OpenSearch/pull/7898))
+- Check UTF16 string size before converting to String to avoid OOME ([#7963](https://github.com/opensearch-project/OpenSearch/pull/7963))
```
Comment (BhumikaSaini-Amazon) [inline CHANGELOG.md:106]: Should we also link the GH issue this PR resolves?

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java [hunk 3]
```diff
@@ -82,7 +84,13 @@ public void writeTo(OutputStream os) throws IOException {
...
+        final char[] ref = new char[bytesRef.length];
+        final int len = UnicodeUtil.UTF8toUTF16(bytesRef.bytes, bytesRef.offset, bytesRef.length, ref);
```
Comment (BhumikaSaini-Amazon) [inline server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:89]: nit : The wrapper method `UTF8toUTF16(BytesRef bytesRef, char[] chars)`, which handles passing the correct params, could also be used

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java [hunk 4]
```diff
@@ -82,7 +84,13 @@ public void writeTo(OutputStream os) throws IOException {
...
+        if (len > MAX_LENGTH) {
+            throw new IllegalStateException("UTF16 String size is " + len + ", should be less than " + MAX_LENGTH);
```
Comment (BhumikaSaini-Amazon) [inline server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:91]: 1. Should this throw an `IllegalStateException` or `IllegalArgumentException`? Was `IllegalStateException` chosen for a specific reason?
2. Please could you help add a unit test that validates that an `OutOfMemoryException` is not thrown now and instead the new exception type (which shouldn't cause a node drop) is thrown?

**Review by BhumikaSaini-Amazon — CHANGES_REQUESTED** [review]
Thanks for adding this!

Few minor comments and we should add a unit test

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java (hunk 3 above)
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:89]: The only concern I have is, this might generate garbage as full characters will have to be read. So we will need allocation profiling samples. Is there a way to handle OOM resulting from the current problem at hand, more gracefully.

Comment (imRishN) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:89]: The step was already done in BytesRef - 
```
public String utf8ToString() {
    final char[] ref = new char[length];
    final int len = UnicodeUtil.UTF8toUTF16(bytes, offset, length, ref);
    return new String(ref, 0, len);
  }
```

This change adds a pre-check on length after the moving this conversion to `AbstractBytesReference.java`

File: CHANGELOG.md (hunk 2 above)
Comment (imRishN) [reply CHANGELOG.md:106]: Changelog just captures Pull Request links. Issue link has been already added to the PR overview

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java (hunk 3 above)
Comment (imRishN) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:89]: Good suggestion. Updated

Comment (reta) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java]: I was having the same concern as @Bukhtawar but it seems like there are no available means (at least within UnicodeUtil) to estimate how much the converted string might take ...

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java [hunk 5]
```diff
@@ -82,7 +84,13 @@ public void writeTo(OutputStream os) throws IOException {
...
     @Override
     public String utf8ToString() {
-        return toBytesRef().utf8ToString();
+        BytesRef bytesRef = toBytesRef();
+        final char[] ref = new char[bytesRef.length];
+        final int len = UnicodeUtil.UTF8toUTF16(bytesRef, ref);
+        if (len > MAX_LENGTH) {
+            throw new IllegalStateException("UTF16 String size is " + len + ", should be less than " + MAX_LENGTH);
+        }
+        return new String(ref, 0, len);
```
Comment (dbwiddis) [inline server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:93]: Should explicitly add the UTF_8 charset here.

Comment (reta) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:93]: I am not sure, `ref` is already an array of `char` (not `byte`)

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java [hunk 6]
```diff
@@ -82,7 +84,13 @@ public void writeTo(OutputStream os) throws IOException {
 
     @Override
     public String utf8ToString() {
-        return toBytesRef().utf8ToString();
+        BytesRef bytesRef = toBytesRef();
+        final char[] ref = new char[bytesRef.length];
+        final int len = UnicodeUtil.UTF8toUTF16(bytesRef, ref);
```
Comment (psychbot) [inline server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:89]: I see there is a method maxUTF8Length() in UnicodeUtil maxUTF8Length = Math.multiplyExact(utf16Length, MAX_UTF8_BYTES_PER_CHAR). which essentially means utf16Length*3.

Does it means we can simplify the whole computation of maxUTF16Length = Math.ceil(utf16Length/3).
Can you explore a bit on conversion so that we can simplify the computation and avoid creating new variable and sequential computation happening in UTF8toUTF16 method.

Comment (imRishN) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:89]: That is the max length to ensure that ref's length is large enough to ensure the conversion doesn't overflow. Not sure if I got your comment correctly. Are you saying that we can optimise `UTF8toUTF16` computation? If yes, that could probably be opened up with Lucene

**Comment by BhumikaSaini-Amazon** [comment]
Thanks @imRishN 

To help with the unit test, would it then make sense to maybe move the logic up till getting the expected length into a separate helper function, and then mock this helper function in the unit test to return a number that is > `MAX_LENGTH`?

And to confirm, the test running OOM while creating the ByteReference for size greater than max_length+1 shouldn't be a concern for creation of the actual ByteReference at runtime, right? (I believe this difference is due to a reduced heap space allocated for the tests).

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java (hunk 4 above)
Comment (gashutos) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:91]: It should be `NotSupportedException`

Comment (reta) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:91]: Hm ... which `NotSupportedException` you mean?

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java (hunk 6 above)
Comment (reta) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:89]: I am thinking if it makes sense to introduce `calcUTF8toUTF16Length` method (similar to `calcUTF16toUTF8Length`) to estimate the length of the conversion without allocation? Also could be easier to test without triggering OOMs...

Comment (imRishN) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:89]: Wouldn't it add an additional overhead where in we calculate the length always first?

Comment (reta) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:89]: It may add for sure (we could measure the overhead with `jmh`), ideally we would need a method which does conversion but stops when "limit" reaches (we don't have one sadly). Also, we could be pretty smart and consult `bytesRef.length` before only when we suspect the overlimits:
```
if (bytesRef.length > MAX_LENGTH) {
    final int len = UnicodeUtil.calcUTF8toUTF16Length (bytesRef);
    ...
}
```

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java (hunk 4 above)
Comment (imRishN) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:91]: > It should be NotSupportedException

@gashutos which one do you suggest? There isn't any `NotSupportedException`. Maybe we can go with `IllegalArgumentException`?

File: libs/core/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java [hunk 7]
```diff
@@ -49,6 +50,7 @@
 public abstract class AbstractBytesReference implements BytesReference {
 
     private Integer hash = null; // we cache the hash of this reference since it can be quite costly to re-calculated it
+    static final int MAX_UTF16_LENGTH = Integer.MAX_VALUE >> 1;
```
Comment (Bukhtawar) [inline libs/core/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:53]: Make this private

File: libs/core/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java [hunk 8]
```diff
@@ -80,9 +82,19 @@ public void writeTo(OutputStream os) throws IOException {
         }
     }
 
+    public int getMaxUTF16Length() {
```
Comment (Bukhtawar) [inline libs/core/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java:85]: Want to make this protected instead?

Comment (imRishN) [reply libs/core/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java]: Done

File: libs/core/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java (hunk 7 above)
Comment (imRishN) [reply libs/core/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java]: Done

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java [hunk 9]
```diff
@@ -82,7 +84,13 @@ public void writeTo(OutputStream os) throws IOException {
 
     @Override
     public String utf8ToString() {
-        return toBytesRef().utf8ToString();
+        BytesRef bytesRef = toBytesRef();
+        final char[] ref = new char[bytesRef.length];
+        final int len = UnicodeUtil.UTF8toUTF16(bytesRef.bytes, bytesRef.offset, bytesRef.length, ref);
+        if (len > MAX_LENGTH) {
```
[the remark this answers is not in the document]
Comment (imRishN) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java]: Added

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java (hunk 1 above)
Comment (imRishN) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java]: Added a test

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java (hunk 4 above)
Comment (dblock) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java]: I like that.

File: server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java (hunk 3 above)
Comment (dblock) [reply server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java]: So this seems like there's actually no new garbage being created. @Bukhtawar are you saying otherwise?

**Comment by dblock** [comment]
@Bukhtawar @reta ya'll good with this as is now?

**Review by reta — APPROVED** [review]

**Review by Bukhtawar — APPROVED** [review]

**Comment by reta** [comment]
@imRishN could you please submit manual backport for `2.x`? thank you
