### PR TITLE
Fix null values indexed as "null" strings in flat_object field

### LINKED ISSUE #13880: [BUG] In flat_object fields `null` values indexed as "null" strings
### Describe the bug

[Flat_object documentation](https://opensearch.org/docs/latest/field-types/supported-field-types/flat-object/) doesn't define `null` values indexing rules, though it looks unexpected that documents containing fields with `null` values can be searched with `exists` or even `prefix: "nu"` queries.

### Related component

Indexing

### To Reproduce

1. create a new index with flat_object field mapping

```
PUT demo-flattened
{
  "mappings": {
    "properties": {
      "record": {
        "type": "flat_object",
      }
    }
  }
}
```

2. index a document with `record.name: null`

```
PUT demo-flattened/_doc/1
{
  "record": {
    "name": null
  }
}
```

3. search the document using prefix query:

```
POST demo-flattened/_search
{
  "query": {
    "prefix": {
      "record.name": {
        "value": "nu",
      }
    }
  }
}
```

4. OR search the document using exists query:

```
POST demo-flattened/_search
{
  "query": {
    "exists": {
      "field": "record.name"
    }
  }
}
```

### Expected behavior

Both queries 3 and 4 should return no documents, but they do return the ingested document. Tested using latest opensearchproject/opensearch:2.14.0 image.

### Additional Details

**Host/Environment:**
 - Version opensearchproject/opensearch:2.14.0

**Additional context**
 - validated my expectations with docker.elastic.co/elasticsearch/elasticsearch:7.15.0, with `flattened` field mapping instead of `flat_object`
 - I know that `flat_object` mapping today doesn't support additional parameters (https://github.com/opensearch-project/OpenSearch/issues/7137) including `null_value`, though the currently selected default when null is treated as "null" (based on the behavior described above) doesn't look right.

### PR DESCRIPTION
**Pull request by kkewwei**
Signed-off-by: kkewwei kkewwei@163.com

### Description
The pr soloves three cases:

- fix null value case, I have test too many cases about null value, all of the tests are passed.
- deduplication the  value of fieldName, valueList, valueAndPathList, there is no need to store the duplicate values.
- fix infinite loop with null value ([comment](https://github.com/opensearch-project/OpenSearch/pull/13259#issuecomment-2312755190))

### Related Issues
Resolves #13880

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kkewwei** [comment]
> ❌ Gradle check result for [03be17b](https://github.com/opensearch-project/OpenSearch/commit/03be17bb6682c708c6f093e59583dfdfae10b686): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/40260/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode #13600
RemoteMigrationIndexMetadataUpdateIT.testRemoteIndexPathFileExistsAfterMigration #13939

**Comment by kkewwei** [comment]
@msfroh, @mingshl, please have a look when you are free.

**Comment by kkewwei** [comment]
> ❕ Gradle check result for [a7b8d01](https://github.com/opensearch-project/OpenSearch/commit/a7b8d0199021ec86dfc59eec2b6255f7253e4bc7): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/41527/)
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

ClusterRerouteIT.testDelayWithALargeAmountOfShards #10558

**Comment by ankitkala** [comment]
@dhwanilpatel to take a look

**Comment by kkewwei** [comment]
@dhwanilpatel, please have a look when you are free.

**Comment by mgodwan** [comment]
@shiv0408 Can you please help review this?

File: server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java [hunk 1]
```diff
@@ -133,9 +132,250 @@ public void testDefaults() throws Exception {
...
+        assertEquals(2, fieldValues.length);
+        assertEquals(new BytesRef("dsdsdsd"), fieldValues[0].binaryValue());
+        fieldValueAndPaths = doc.rootDoc().getFields("field" + VALUE_AND_PATH_SUFFIX);
+        assertEquals(2, fieldValueAndPaths.length);
+        assertEquals(new BytesRef("field.name.name1=dsdsdsd"), fieldValueAndPaths[0].binaryValue());
+
+        // test18: {"field":{"name": {"name1": {"name2":null}}}}
+        json = "{\"field\":{\"name\": {\"name1\": {\"name2\":null}}}}";
+        doc = mapper.parse(source(json));
+        assertArrayEquals(new IndexableField[0], doc.rootDoc().getFields("field"));
```
Comment (sandeshkr419) [inline server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java:338]: Minor concern on just code/test readability: 

I think we should group tests - 1, 2, 11, 12, 13, 14, 18 together.

Also, basically if there are other similar assertions and we can abstract out to make the cases more grouped.

**Comment by dblock** [comment]
@kkewwei It would be awesome to take this opportunity to add `flat_object` to https://github.com/opensearch-project/opensearch-api-specification.

**Comment by kkewwei** [comment]
> flat_object

**Comment by kkewwei** [comment]
> @kkewwei It would be awesome to take this opportunity to add `flat_object` to https://github.com/opensearch-project/opensearch-api-specification.

Get it.

**Comment by kkewwei** [comment]
@sandeshkr419 @shiv0408 @mgodwan @dblock, please have a look when you are free. The pr will solve three cases,  the third one `infinite loop with null value` is a bit urgent, If I should create new pr to solve it?

**Comment by kkewwei** [comment]
> FAILURE



> ❌ Gradle check result for [92c8ddd](https://github.com/opensearch-project/OpenSearch/commit/92c8ddd3b1eb170f0e27d1d9c9e39fb19b846a3d): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/45497/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

ReindexBasicTests.testMultipleSources #13913
MasterServiceTests.testClusterStateUpdateLoggingWithDebugEnabled #15117

**Comment by kkewwei** [comment]
> ❌ Gradle check result for [7023bd1](https://github.com/opensearch-project/OpenSearch/commit/7023bd137e2384d60ec4c0912b37131a0c63d3ab): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/45522/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

MasterServiceTests.testClusterStateUpdateLoggingWithDebugEnabled https://github.com/opensearch-project/OpenSearch/issues/15117

File: server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java [hunk 2]
```diff
@@ -72,21 +73,31 @@ public XContentParser parseObject() throws IOException {
...
-            parseToken(path);
+            parseToken(path, null);
         }
-        builder.field(this.fieldTypeName, keyList);
-        builder.field(this.fieldTypeName + VALUE_SUFFIX, valueList);
-        builder.field(this.fieldTypeName + VALUE_AND_PATH_SUFFIX, valueAndPathList);
+        // deduplication the fieldName,valueList,valueAndPathList
+        builder.field(this.fieldTypeName, new HashSet<>(keyList));
+        builder.field(this.fieldTypeName + VALUE_SUFFIX, new HashSet<>(valueList));
+        builder.field(this.fieldTypeName + VALUE_AND_PATH_SUFFIX, new HashSet<>(valueAndPathList));
```
Comment (msfroh) [inline server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:81]: Could you do a `LinkedHashSet<>` instead? It would preserve the order, so the unit tests would remain consistent. (Right now, the unit tests are relying on the order of the `HashSet`, which is hard to reason about.)

**Review by msfroh — COMMENTED** [review]
Hey @kkewwei  -- thank you **so** much for really diving into this fix!

My earlier fix over at https://github.com/opensearch-project/OpenSearch/pull/15375 wasn't nearly so complete. With this fix, I believe we'll finally be `null`-safe.

I left a minor suggestion that should reduce the diff on `JsonToStringXContentParserTests`.

File: server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java (hunk 2 above)
Comment (msfroh) [reply server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:81]: I tried that out and was able to remove most of your unit test diff, just keeping the deduplication of field values: https://github.com/opensearch-project/OpenSearch/compare/main...msfroh:OpenSearch:fix_null_flat_object

File: server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java [hunk 3]
```diff
@@ -72,21 +73,31 @@ public XContentParser parseObject() throws IOException {
...
         builder.endObject();
         String jString = XContentHelper.convertToJson(BytesReference.bytes(builder), false, MediaTypeRegistry.JSON);
         return JsonXContent.jsonXContent.createParser(this.xContentRegistry, this.deprecationHandler, String.valueOf(jString));
     }
 
-    private void parseToken(Deque<String> path) throws IOException {
+    /**
+     * @return true if the child object contains no_null value, false otherwise
+     */
+    private boolean parseToken(Deque<String> path, String currentFieldName) throws IOException {
```
Comment (msfroh) [inline server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:90]: Do we need to pass `currentFieldName` down? 

I see it getting overwritten on line 97, but the value passed is never read anywhere, from what I can see.

Comment (msfroh) [reply server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java:90]: Yeah -- I was able to remove it from the parameter list without breaking anything: https://github.com/opensearch-project/OpenSearch/compare/main...msfroh:OpenSearch:fix_null_flat_object#diff-9b94311ef376a05bce2bbe32e99582f739378209a89aaa6dc4bc192e4b8f2660R90

**Comment by msfroh** [comment]
Actually, while I still agree with my prior review comments, they don't affect the usefulness of this fix. I'm going to approve and merge, and I can take care of the cosmetic changes.

**Review by msfroh — APPROVED** [review]

**Comment by kkewwei** [comment]
@msfroh,  thank you so much.

**Comment by cameronattard** [comment]
I think I'm encountering the infinite loop. Any chance of getting this backported and released into 2.15 any time soon?

**Comment by dblock** [comment]
> I think I'm encountering the infinite loop. Any chance of getting this backported and released into 2.15 any time soon?

@cameronattard only high sev security fixes get released in patch releases, and only on the latest (2.17), so 2.15 is long gone
