### PR TITLE
use the correct type to widen the sort fields when merging top docs

### LINKED ISSUE #16860: Use the correct type to widen the sort fields when merging top field docs
### Describe the bug

To enable numeric sort optimization support for all numeric types, we use double to widen the sort fields in #6424. However, when the sort value exceeds the MAX_SAFE_INTEGER (`2^53 – 1`), it may result in incorrect sorting. 

### Related component

Search

### To Reproduce

```
public class FieldSortIT extends ParameterizedDynamicSettingsOpenSearchIntegTestCase {
    public void testSortMixedNumericField() throws Exception {
            internalCluster().ensureAtLeastNumDataNodes(3);
            index("long", Long.MAX_VALUE);
            index("integer", Integer.MAX_VALUE);
            SearchResponse searchResponse = client().prepareSearch("long", "integer")
                .setQuery(matchAllQuery())
                .setSize(10)
                .addSort(SortBuilders.fieldSort("field").order(SortOrder.ASC).sortMode(SortMode.MAX))
                .get();
            assertNoFailures(searchResponse);
            long[] sortValues = new long[10];
            for (int i = 0; i < 10; i++) {
                sortValues[i] = ((Number) searchResponse.getHits().getAt(i).getSortValues()[0]).longValue();
            }
            for (int i = 1; i < 10; i++) {
                assertThat(Arrays.toString(sortValues), sortValues[i - 1], lessThan(sortValues[i]));
            }
        }
    
        private void index(String type, long end) throws Exception {
            assertAcked(
                prepareCreate(type).setMapping(
                    XContentFactory.jsonBuilder()
                        .startObject()
                        .startObject("properties")
                        .startObject("field")
                        .field("type", type)
                        .endObject()
                        .endObject()
                        .endObject()
                ).setSettings(Settings.builder().put("index.number_of_shards", 3).put("index.number_of_replicas", 0))
            );
            ensureGreen(type);
            for (int i = 0; i < 5; i++) {
                client().prepareIndex(type).setId(Integer.toString(i)).setSource("{\"field\" : " + (end - i) + " }", XContentType.JSON).get();
            }
            client().admin().indices().prepareRefresh(type).get();
        }
}
```

### Expected behavior

When the sort values are all integer values, we can use the `Long` type to widen the sort fields.

To be discussed: 1. When sort values contain both integer values and float values, should we throw an exception or use double to widen sort fields? 2. Should we check the compatibility between sort types when merging top docs?

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by bugmakerrrrrr**
### Description
See #16860

### Related Issues
Resolves #16860

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java [hunk 1]
```diff
@@ -51,7 +57,7 @@ public SortedWiderNumericSortField(String field, Type type, boolean reverse) {
      */
     @Override
     public FieldComparator<?> getComparator(int numHits, Pruning pruning) {
-        return new NumericComparator<Number>(getField(), (Number) getMissingValue(), getReverse(), pruning, Double.BYTES) {
+        return new NumericComparator<Number>(getField(), (Number) getMissingValue(), getReverse(), pruning, byteCounts) {
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java:60]: @bugmakerrrrrr could you please explain this change? AFAIK we always fallback to `double` in case there are mixed numeric types (at least, with respect to aggregations etc). Yes, there could be precision loss, but the widening should always work right?

Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java:60]: I tested sorting on fields containing a mix of long and double data types using a version before the introduction of #6424, and encountered the following exception.

```
{
  "error" : {
    "root_cause" : [ ],
    "type" : "search_phase_execution_exception",
    "reason" : "",
    "phase" : "fetch",
    "grouped" : true,
    "failed_shards" : [ ],
    "caused_by" : {
      "type" : "class_cast_exception",
      "reason" : "class java.lang.Double cannot be cast to class java.lang.Long (java.lang.Double and java.lang.Long are in module java.base of loader 'bootstrap')"
    }
  },
  "status" : 500
}
```

This error indicates that sorting on mixed numeric types was not supported in the version being used.

Comment (reta) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java:60]: @bugmakerrrrrr sorry, not sure I am following, I think https://github.com/opensearch-project/OpenSearch/pull/6424 did the right job, why do we changing that?

Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java:60]: @reta Before #6424, there is no loss of precision if we sorting on integer type fields, I think we should ensure this even after we  supported sorting on mixed numeric types.

Comment (reta) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java:60]: @bugmakerrrrrr oh I see, so you basically check if we are dealing with integer types only (than we could widen to long fe), or non-integer / mixed types, right? I think it make sense, thank you for explaing

File: server/src/main/java/org/opensearch/action/search/SearchPhaseController.java [hunk 2]
```diff
@@ -604,36 +605,53 @@ private static void validateMergeSortValueFormats(Collection<? extends SearchPha
...
-     * It will compare respective SortField between shards to see if any shard results have different
-     * field mapping type, accordingly it will decide to widen the sort fields.
-     */
-    private static boolean isSortWideningRequired(TopFieldDocs[] topFieldDocs, int sortFieldindex) {
-        for (int i = 0; i < topFieldDocs.length - 1; i++) {
-            if (!topFieldDocs[i].fields[sortFieldindex].equals(topFieldDocs[i + 1].fields[sortFieldindex])) {
-                return true;
-            }
+    private static SortField.Type getSortType(SortField sortField) {
+        if (sortField.getComparatorSource() != null) {
```
Comment (reta) [inline server/src/main/java/org/opensearch/action/search/SearchPhaseController.java:646]:
```suggestion
        if (sortField.getComparatorSource() instanceof IndexFieldData.XFieldComparatorSource) {
            return ((IndexFieldData.XFieldComparatorSource) sortField.getComparatorSource()).reducedType();
        }
```

File: server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java [hunk 3]
```diff
@@ -39,6 +43,8 @@ public class SortedWiderNumericSortField extends SortedNumericSortField {
      */
     public SortedWiderNumericSortField(String field, Type type, boolean reverse) {
         super(field, type, reverse);
+        byteCounts = type == Type.LONG ? Long.BYTES : Double.BYTES;
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java:46]: Nit but may simplify the number of conditionals:

```
if (type == Type.LONG) {
    byteCounts = Long.BYTES;
    comparator = Comparator.comparingLong(Number::longValue);
} else {
    byteCounts = Double.BYTES;
    comparator = Comparator.comparingDouble(Number::doubleValue);
}
```

Comment (reta) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java:46]: I think we may have an issue here with `unsigned_long` here: we may need to use double even if all sorted types are integers.

File: server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java (hunk 1 above)
Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java:60]: Yes, you are right. My bad. I didn't express myself clearly.

File: server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java (hunk 3 above)
Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java:46]: As you mentioned in [this comment](https://github.com/opensearch-project/OpenSearch/issues/16860#issuecomment-2546668235), we don't support sorting on fields mixed unsigned_long and other number types, and if we sort the search result that only has the `unsigned_long` type, we use [`Comparable#compareTo`](https://github.com/apache/lucene/blob/072978999ca83be8efc725440b28b79a49147944/lucene/core/src/java/org/apache/lucene/search/FieldComparator.java#L105-L117) to compare values when merging top docs, so I think it is ok.

Comment (reta) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java]: Please correct me if I am wrong here, the widening does work **right now** for all field types (since it is converted to `double`), with a caveat of the possible precision loss. But it won't anymore with this change, it is correct? If yes - this is clearly a regression.

Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java]: > the widening does work right now for all field types in a mix

Yes, but we are not committed to `unsigned_long` as described in limitation, right?

And I do think #6424 is a regression. It destroys the correctness of the sorted results, and correctness is important to the user. I don't even think we should allow mixed sorting of floats and integers, as in the old version, to avoid giving surprising results to the user.

Comment (reta) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java]: @bugmakerrrrrr I think we could take `unsigned_long` off the picture, we do not support mixing different type sorting with `unsigned_long` :

```
                            "Can't do sort across indices, as a field has [unsigned_long] type "
                                + "in one index, and different type in another index!"
```

Please accept my apologies for confusing you there, it has been awhile since this feature was implemented, some details got a bit blurry.

File: server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java [hunk 4]
```diff
@@ -2609,4 +2610,43 @@ public void testSimpleSortsPoints() throws Exception {
 
         assertThat(searchResponse.toString(), not(containsString("error")));
     }
+
+    public void testSortMixedNumericFields() throws Exception {
```
Comment (reta) [inline server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java:2614]: Could you please add test cases for float / half_float / double mix?

File: server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java (hunk 3 above)
Comment (bugmakerrrrrr) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java]: Never mind, These things happen :)

Comment (reta) [reply server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java]: I think it could be a good idea to add the comment here stating the `unsigned_long` is not supported by widening sort since the `unsigned_long` could not be used with other types (we may support that for aggregation though if I am not mistaken, but that is a different flow)

File: server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java (hunk 4 above)
Comment (bugmakerrrrrr) [reply server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java]: Done

**Comment by reta** [comment]
@msfroh @gashutos do you mind taking a look folks, I think it is clever and useful improvement (thanks @bugmakerrrrrr !)

**Review by reta — APPROVED** [review]

**Review by msfroh — APPROVED** [review]
I agree -- it's a neat approach :+1:
