### PR TITLE
Ignore all malformed objects when ignore_malformed is true

### LINKED ISSUE #4002: [BUG] The index setting "ignore_malformed" is not working properly
**Describe the bug**
The "ignore_malformed" option should allow inconsistent data to be indexed, losing only the malformed fields, but it is ignoring the entire item. 

**To Reproduce**
1. Create an empty index with the setting "ignore_malformed": "true".
2. insert the following data {
    "name":"test 1",
    "other_field":"string content"
}
3. insert the following data {
    "name":"test 2",
    "other_field":{"comment":"object content","size":2}
}

**Expected behavior**
In this situation the second item should be indexed only the field "other_field" should be missed, but the hole item is lost.

**Host/Environment (please complete the following information):**
 - OS: centos 8
 - Version 2.1

**Additional context**
I'm using this to index a lot of unstructured data, and sometimes a few fields are invalid, but it shouldn't lose the valid fields.

### PR DESCRIPTION
**Pull request by hauck-jvsh**
### Description
This pull request ignores all malformed items, allowing the other fields to be indexed.

### Issues Resolved
#4002 

### Check List
- [x] All tests pass
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by nknize — APPROVED** [review]
LGTM!! Thank you for the contribution :tada:

File: server/src/main/java/org/opensearch/index/mapper/FieldMapper.java [hunk 1]
```diff
@@ -278,23 +281,27 @@ public void parse(ParseContext context) throws IOException {
                     valuePreview = complexValue.toString();
                 }
             } catch (Exception innerException) {
+                if (!ignore_malformed) {
```
Comment (nknize) [inline server/src/main/java/org/opensearch/index/mapper/FieldMapper.java:284]: We should have a spotless check for this, but for now we just ask contributors use explicit logic checks instead of negations.

```suggestion
                if (ignore_malformed == false) {
```

**Review by nknize — CHANGES_REQUESTED** [review]
Oh, before merging I have one little minor nit that we should cleanup.

File: server/src/main/java/org/opensearch/index/mapper/FieldMapper.java (hunk 1 above)
Comment (hauck-jvsh) [reply server/src/main/java/org/opensearch/index/mapper/FieldMapper.java:284]: Sure!

**Review by nknize — APPROVED** [review]
