### PR TITLE
fix-flaky: MultiCodecReindexTests

### LINKED ISSUE #8980: [BUG] org.opensearch.index.codec.MultiCodecReindexIT.testReindexingMultipleCodecs if flaky
**Describe the bug**
org.opensearch.index.codec.MultiCodecReindexIT.testReindexingMultipleCodecs if flaky

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([747BDC3BFC37662:11810E7B3898F59]:0)
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.opensearch.index.codec.MultiCodecReindexIT.assertReindexingWithMultipleCodecs(MultiCodecReindexIT.java:88)
	at org.opensearch.index.codec.MultiCodecReindexIT.testReindexingMultipleCodecs(MultiCodecReindexIT.java:57)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**To Reproduce**

`./gradlew ':modules:reindex:internalClusterTest' --tests "org.opensearch.index.codec.MultiCodecReindexIT.testReindexingMultipleCodecs" -Dtests.seed=747BDC3BFC37662`

**Expected behavior**
Test should always pass

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
- CI

**Additional context**
Reproducible locally

### PR DESCRIPTION
**Pull request by r1walz**
### Description

The test spawns random number of data, client and manager nodes which sometimes lead to connect_exception when any of the test nodes fail to connect to the other node(s) leading to flakiness. Let's use only one data node as per the requirement of the test to reduce flakiness.

### Related Issues

Resolves #8980 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~

```
rashiwal@local ➜  ./gradlew ':modules:reindex:internalClusterTest' --tests "org.opensearch.index.codec.MultiCodecReindexIT"

> Configure project :
========================= WARNING =========================
         Backwards compatibility tests are disabled!
See https://github.com/opensearch-project/OpenSearch/issues/4173
===========================================================
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.4
  OS Info               : Mac OS X 13.5.2 (x86_64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : /Users/rashiwal/.sdkman/candidates/java/11.0.19-amzn
  Random Testing Seed   : CD1EB507DB38F56C
  In FIPS 140 mode      : false
=======================================
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.BootstrapForTesting (file:/Users/rashiwal/workplace/OpenSearch/test/framework/build/distributions/framework-3.0.0-SNAPSHOT.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.BootstrapForTesting
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/Users/rashiwal/.gradle/wrapper/dists/gradle-8.4-all/56r6xik2f6skrm47et0ibifug/gradle-8.4/lib/plugins/gradle-testing-base-8.4.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release

BUILD SUCCESSFUL in 30s
69 actionable tasks: 1 executed, 68 up-to-date
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by r1walz** [comment]
@sarthakaggarwal97 : Can I have a review? Thanks 😄

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java [hunk 1]
```diff
@@ -61,72 +57,94 @@ public void testReindexingMultipleCodecs() throws InterruptedException, Executio
...
+                    false,
+                    randomBoolean(),
+                    IntStream.range(0, nbDocs)
+                        .mapToObj(i -> client().prepareIndex(index).setId(UUID.randomUUID().toString()).setSource("num", i))
+                        .collect(toList())
+                );
+
+                // perform flush
+                FlushResponse flushResponse = client().admin().indices().prepareFlush(index).setForce(true).execute().actionGet();
+                assertNoFailures(flushResponse);
```
Comment (r1walz) [inline modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:92]: Maybe replace with: https://github.com/opensearch-project/OpenSearch/blob/73bbeb57a8a56de0d1f9cf69e711a8a0ff26afe5/test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java#L1456

```suggestion
                flushAndRefresh(index);
```

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java [hunk 2]
```diff
@@ -61,72 +57,94 @@ public void testReindexingMultipleCodecs() throws InterruptedException, Executio
...
-
-        // creating source index
-        createIndex(
-            index,
-            Settings.builder()
-                .put(IndexMetadata.SETTING_NUMBER_OF_SHARDS, 1)
-                .put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, 0)
-                .put("index.codec", "default")
-                .put("index.merge.policy.max_merged_segment", "1b")
-                .build()
```
Comment (r1walz) [inline modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:85]: Instead of creating a separate `index` for all codec tests, we've replaced it with a unified "source" index containing docs encoded with all kinds of codecs.

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java [hunk 3]
```diff
@@ -142,46 +160,7 @@ private void useCodec(String index, String codec) throws ExecutionException, Int
...
-    private void flushAndRefreshIndex(String index) {
-
-        // Request is not blocked
-        for (String blockSetting : Arrays.asList(
-            SETTING_BLOCKS_READ,
-            SETTING_BLOCKS_WRITE,
-            SETTING_READ_ONLY,
-            SETTING_BLOCKS_METADATA,
-            SETTING_READ_ONLY_ALLOW_DELETE
-        )) {
```
Comment (r1walz) [inline modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:154]: I'm not sure why we wanted to apply index block before executing `flush` and `refresh` and that too for all variants, flushing and refresing. Since, it took unnecessary cycles, I've removed it for now for speed 🚀 

Please, let me know if there's some hidden/tribal knowledge behind this.

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java (hunk 1 above)
Comment (sarthakaggarwal97) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:92]: yes, please replace it with the flushAndRefresh function

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java [hunk 4]
```diff
@@ -61,72 +57,94 @@ public void testReindexingMultipleCodecs() throws InterruptedException, Executio
             "lz4",
             "BEST_SPEED"
         );
-
-        for (Map.Entry<String, String> codec : codecMap.entrySet()) {
-            assertReindexingWithMultipleCodecs(codec.getKey(), codec.getValue(), codecMap);
```
Comment (sarthakaggarwal97) [inline modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:66]: Please reinstate the creation of index with each codec, it helps us verify that there is no break in the create index flow for each codec.

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java (hunk 2 above)
Comment (sarthakaggarwal97) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:85]: https://github.com/opensearch-project/OpenSearch/pull/10980/files#r1375666873

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java [hunk 5]
```diff
@@ -142,46 +160,7 @@ private void useCodec(String index, String codec) throws ExecutionException, Int
...
-                // refresh
-                RefreshResponse refreshResponse = client().admin().indices().prepareRefresh(index).execute().actionGet();
-                assertNoFailures(refreshResponse);
-            } finally {
-                disableIndexBlock(index, blockSetting);
-            }
-        }
-    }
-
-    private void ingestDocs(String index, int nbDocs) throws InterruptedException {
```
Comment (sarthakaggarwal97) [inline modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:170]: Can we use this instead? It helps in abstracting the code to ingest with each codec

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java [hunk 6]
```diff
@@ -142,46 +160,7 @@ private void useCodec(String index, String codec) throws ExecutionException, Int
...
-
-        indexRandom(
-            randomBoolean(),
-            false,
-            randomBoolean(),
-            IntStream.range(0, nbDocs)
-                .mapToObj(i -> client().prepareIndex(index).setId(UUID.randomUUID().toString()).setSource("num", i))
-                .collect(toList())
-        );
-        flushAndRefreshIndex(index);
```
Comment (sarthakaggarwal97) [inline modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:180]: Reinstate this function

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java [hunk 7]
```diff
@@ -34,14 +35,10 @@
...
 import static java.util.stream.Collectors.toList;
-import static org.opensearch.cluster.metadata.IndexMetadata.SETTING_BLOCKS_METADATA;
-import static org.opensearch.cluster.metadata.IndexMetadata.SETTING_BLOCKS_READ;
-import static org.opensearch.cluster.metadata.IndexMetadata.SETTING_BLOCKS_WRITE;
-import static org.opensearch.cluster.metadata.IndexMetadata.SETTING_READ_ONLY;
-import static org.opensearch.cluster.metadata.IndexMetadata.SETTING_READ_ONLY_ALLOW_DELETE;
 import static org.opensearch.test.hamcrest.OpenSearchAssertions.assertAcked;
 import static org.opensearch.test.hamcrest.OpenSearchAssertions.assertNoFailures;
 
+@ClusterScope(scope = Scope.SUITE, numDataNodes = 1, numClientNodes = 0, supportsDedicatedMasters = false)
```
Comment (sarthakaggarwal97) [inline modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:41]: @r1walz looks like the flaky-ness is related to connection issue. 
Are we able to consistently solve the issue with ```ClusterScope(scope = Scope.SUITE, numDataNodes = 1, numClientNodes = 0, supportsDedicatedMasters = false)```?

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java (hunk 4 above)
Comment (r1walz) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:66]: Cool. I'll modify it a lil bit to create index with a random codec.

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java (hunk 7 above)
Comment (r1walz) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:41]: My [other test](https://github.com/opensearch-project/OpenSearch/blob/73bbeb57a8a56de0d1f9cf69e711a8a0ff26afe5/server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java#L41) is holding good. So, it should work fine here as well. There's no node-to-node communication so no chance of flakiness coming from there.

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java (hunk 5 above)
Comment (r1walz) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:170]: I'm not for-or-against using methods/factoring out to methods in tests. But, I do believe all the setup relating to a test should be self-contained and idempotent. As a general rule of thumb, I refrain from factoring out to methods before it's repeated too many times (at least three).

Comment (sarthakaggarwal97) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:170]: In the case of ingestDocs function, we have wrapped both indexing and refresh calls to ensure segments are properly created. Essentially, we are wrapping or factoring out two operations in a single function call. 
The question is, would it be beneficial in the future if we keep the ingestion as is, and make it reusable (in case we want to add more tests)?

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java (hunk 3 above)
Comment (sarthakaggarwal97) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:154]: I think we can remove these blocks for now, don't see a strong reason to keep the blocks since we are only managing ingestion.

**Comment by sarthakaggarwal97** [comment]
@r1walz looks good to me! Please run multiple iterations and confirm if the flaky-ness is fixed.

**Comment by r1walz** [comment]
@sarthakaggarwal97 wrote:

> @r1walz looks good to me! Please run multiple iterations and confirm if the flaky-ness is fixed.

No issues for 500 iteration run:

```sh
$ ./gradlew ':modules:reindex:internalClusterTest' --tests "org.opensearch.index.codec.MultiCodecReindexIT" -Dtests.iters=500 -Dtests.timeoutSuite='500000000!'
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.4
  OS Info               : Linux 5.4.257-177.360.amzn2int.x86_64 (amd64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : /local/home/rashiwal/.sdkman/candidates/java/11.0.19-amzn
  Random Testing Seed   : 20DCD5ADB634C4C9
  In FIPS 140 mode      : false
=======================================
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.BootstrapForTesting (file:/workplace/rashiwal/OpenSearch/test/framework/build/distributions/framework-3.0.0-SNAPSHOT.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.BootstrapForTesting
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/local/home/rashiwal/.gradle/wrapper/dists/gradle-8.4-all/56r6xik2f6skrm47et0ibifug/gradle-8.4/lib/plugins/gradle-testing-base-8.4.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release

BUILD SUCCESSFUL in 1h 20m 40s
69 actionable tasks: 1 executed, 68 up-to-date
```

**Comment by sarthakaggarwal97** [comment]
thanks @r1walz! @reta @shwetathareja please take a look!

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java (hunk 7 above)
Comment (reta) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:38]: Thanks a lot for looking into this issue @r1walz , but I honestly doubt that we've identified the fix.  If you look on test hierarchy, there are dozens or so test cases that inherit from `ReindexTestCase`, I would expect the issue to be widespread but it is not. 

The first thing that looks wrong to me is that `MultiCodecReindexIT` is in a wrong place and test task: it should be renamed to `MultiCodecReindexTests` and moved from `internalClusterTest` to `src/test` folder, where all other tests are placed. 

The connectivity could be an issue sometimes and even with 1 node it could happen.

**Review by peternied — CHANGES_REQUESTED** [review]
> Let's use only one data node as per the requirement of the test to reduce flakiness.

As has been mentioned in this [comment thread](https://github.com/opensearch-project/OpenSearch/pull/10980/files#r1375673583), I don't think this is the right direction. I think by avoiding multi-node setups this is hiding an issue - as a vast majority of tests run on multi-node setups.  

There are some outstanding suggestions; I'd recommend if it isn't clear how to proceed after following those suggestion add telemetry to the logs around the test failure.  It can help our understanding of the issue and better point towards the root cause.

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java (hunk 7 above)
Comment (sarthakaggarwal97) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:38]: @reta @peternied I've a question, is there a way to check the flaky-ness of a test across multiple builds?
I want to understand in what builds it has been been failing in the past month or so, in order to deep dive into the issue. Apologies if this information is shared someplace and I missed it. Thankyou

Comment (peternied) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:38]: Good question, I am not aware of a system to track test failures over time. 

@andrross do you know of one?

Comment (andrross) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:38]: I do have [this script](https://gist.github.com/andrross/ee07a8a05beb63f1173bcb98523918b9) which, while far from ideal, is an example of how to crawl the Jenkins output to find failing tests over time. Feel free to adapt to your needs.

Comment (r1walz) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:38]: Here are `gradle-check` runs which failed for `MultiCodecReindexIT.*` (between 24398 and 30125). Thanks for the script, @andrross.

```sh
21 org.opensearch.index.codec.MultiCodecMergeIT.testForceMergeMultipleCodecs (24465,24696,24733,24738,24749,24750,24765,24781,24792,24810,24848,24853,24860,24861,24862,24863,24864,24875,24876,24892,25084)
15 org.opensearch.index.codec.MultiCodecReindexIT.classMethod (24434,24735,24762,24810,24845,24863,24881,24902,24935,24985,25002,25013,25076,25097,27968)
15 org.opensearch.index.codec.MultiCodecReindexIT.testReindexingMultipleCodecs (24434,24735,24762,24810,24845,24863,24881,24902,24935,24985,25002,25013,25076,25097,28473)
```

cc: @sarthakaggarwal97

Comment (sarthakaggarwal97) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:38]: @ankitkala that's correct, ```index.merge.policy.max_merged_segment``` was configured to ```1b``` to disable merges. The surprising part is even after these settings, the segments are getting merged. Do we know why would that be the case?

Comment (sarthakaggarwal97) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:38]: @r1walz thanks for pulling out the builds where the test failed. It looks like the [last failed build](https://build.ci.opensearch.org/job/gradle-check/28473/) due to this test is around a month back. (10/19)

Comment (ankitkala) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java:38]: > @ankitkala that's correct, `index.merge.policy.max_merged_segment` was configured to `1b` to disable merges. The surprising part is even after these settings, the segments are getting merged. Do we know why would that be the case?

Not sure. I think it's not getting honored somehow. Will need to check more on this. 

Here are the segments after each doc insertion. 

```
[2023-11-17T11:21:00,358][INFO ][o.o.i.c.MultiCodecReindexIT] [testReindexingMultipleCodecs] Segments after ingest [Segment{name='_0', generation=0, committed=true, search=true, sizeInBytes=3402, docCount=5, delDocCount=0, version='9.8.0', compound=true, mergeId='null', attributes={Lucene90StoredFieldsFormat.mode=BEST_SPEED}}]
[2023-11-17T11:21:01,306][INFO ][o.o.i.c.MultiCodecReindexIT] [testReindexingMultipleCodecs] Segments after ingest [Segment{name='_0', generation=0, committed=true, search=true, sizeInBytes=3402, docCount=5, delDocCount=0, version='9.8.0', compound=true, mergeId='null', attributes={Lucene90StoredFieldsFormat.mode=BEST_SPEED}}, Segment{name='_1', generation=1, committed=true, search=true, sizeInBytes=3416, docCount=5, delDocCount=0, version='9.8.0', compound=true, mergeId='null', attributes={Lucene90StoredFieldsFormat.mode=BEST_COMPRESSION}}]
[2023-11-17T11:21:02,253][INFO ][o.o.i.c.MultiCodecReindexIT] [testReindexingMultipleCodecs] Segments after ingest [Segment{name='_0', generation=0, committed=true, search=true, sizeInBytes=3402, docCount=5, delDocCount=0, version='9.8.0', compound=true, mergeId='null', attributes={Lucene90StoredFieldsFormat.mode=BEST_SPEED}}, Segment{name='_1', generation=1, committed=true, search=true, sizeInBytes=3416, docCount=5, delDocCount=0, version='9.8.0', compound=true, mergeId='null', attributes={Lucene90StoredFieldsFormat.mode=BEST_COMPRESSION}}, Segment{name='_2', generation=2, committed=true, search=true, sizeInBytes=3424, docCount=5, delDocCount=0, version='9.8.0', compound=true, mergeId='null', attributes={Lucene90StoredFieldsFormat.mode=BEST_COMPRESSION}}]
[2023-11-17T11:21:03,274][INFO ][o.o.i.c.MultiCodecReindexIT] [testReindexingMultipleCodecs] Segments after ingest [Segment{name='_4', generation=4, committed=true, search=true, sizeInBytes=3362, docCount=4, delDocCount=0, version='9.8.0', compound=true, mergeId='null', attributes={Lucene90StoredFieldsFormat.mode=BEST_SPEED}}, Segment{name='_5', generation=5, committed=true, search=true, sizeInBytes=4047, docCount=16, delDocCount=0, version='9.8.0', compound=false, mergeId='null', attributes={Lucene90StoredFieldsFormat.mode=BEST_SPEED}}]
```

Comment (r1walz) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java]: I've used the `index.merge.enabled` property instead of setting `index.merge.policy.max_merged_segment`. Also, I've moved the test to `test` folder from `internalClusterTest` folder and renamed it to `MultiCodecReindexTests` from `MultiCodecReindexIT`.

**Review by ankitkala — APPROVED** [review]
Hard to see the exact changes since the file was renamed. But I do see that `INDEX_MERGE_ENABLED` setting was added. 

Can you also run the test for couple hundred iterations to ensure no flaky behavior?

**Comment by r1walz** [comment]
Yes, @ankitkala. I'm running these tests in the background. Will wait for 1000+ runs to get completed.

File: modules/reindex/src/test/java/org/opensearch/index/reindex/MultiCodecReindexTests.java [hunk 8]
```diff
@@ -0,0 +1,160 @@
...
+                .updateSettings(new UpdateSettingsRequest(index).settings(Settings.builder().put("index.codec", codec)))
+                .get()
+        );
+
+        assertAcked(client().admin().indices().prepareOpen(index).setWaitForActiveShards(1));
+    }
+
+    private void ingestDocs(String index, int nbDocs) throws InterruptedException {
+        indexRandom(
+            false,
```
Comment (reta) [inline modules/reindex/src/test/java/org/opensearch/index/reindex/MultiCodecReindexTests.java:136]: those used to be random flags, why we changed them?

Comment (r1walz) [reply modules/reindex/src/test/java/org/opensearch/index/reindex/MultiCodecReindexTests.java:136]: I was reducing randomness while trying to debug offline. Seems like I didn't revert back. I'll post another revision reverting the original behavior.

Also, `codecov/patch` is unhappy. Do we need to add extra coverage as well?

**Comment by r1walz** [comment]
1286 runs passed and still running:

image

File: modules/reindex/src/test/java/org/opensearch/index/reindex/MultiCodecReindexTests.java (hunk 8 above)
Comment (reta) [reply modules/reindex/src/test/java/org/opensearch/index/reindex/MultiCodecReindexTests.java:136]: > Also, `codecov/patch` is unhappy. Do we need to add extra coverage as well?

Codecov check could be skipped (for this pull request) I believe (since we essentially moving test case)

**Comment by ankitkala** [comment]
> > Let's use only one data node as per the requirement of the test to reduce flakiness.
> 
> As has been mentioned in this [comment thread](https://github.com/opensearch-project/OpenSearch/pull/10980/files#r1375673583), I don't think this is the right direction. I think by avoiding multi-node setups this is hiding an issue - as a vast majority of tests run on multi-node setups.
> 
> There are some outstanding suggestions; I'd recommend if it isn't clear how to proceed after following those suggestion add telemetry to the logs around the test failure. It can help our understanding of the issue and better point towards the root cause.

Looks like the comment thread where we were discussing the fix got deleted. Does anyone know what happened?

File: modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java (hunk 7 above)
Comment (r1walz) [reply modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java]: @ankitkala here's the thread. I had resolved it earlier.

**Review by peternied — APPROVED** [review]
Thanks for pivoting on the approach, this looks much cleaner.

**Review by sarthakaggarwal97 — APPROVED** [review]

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@r1walz could you please backport to `2.x` manually? thank you
