### PR TITLE
Fix responsibility check for existing shards allocator when timed out

### LINKED ISSUE #15222: [BUG] New shards allocation failure for shards present in timed out batches in batch allocator
### Describe the bug

With https://github.com/opensearch-project/OpenSearch/pull/14848, we introduced capability to make reroute iteration time-bound. Currently OpenSearch uses two primary allocators -`ExistingShardsAllocator` which is responsible for allocating existing shards, and `BalancedShardsAllocator` which handles the allocation of all unassigned shards.

When a new index is created, the responsibility for allocating its shards falls to `BalancedShardsAllocator`. However, if the `ExistingShardsAllocator` times out, the remaining shards are currently marked as ignored, causing them to be skipped in the current round of allocation. Ideally, before marking these shards as ignored, the system should verify whether the `ExistingShardsAllocator` is actually responsible for their allocation. If it's not those shards should not be added to the ignore list.

As a result, when `ExistingShardsAllocator` times out, shards from newly created indices included in the timed out batches fails to get assigned.

### Related component

Other

### Expected behavior

Newly created shards should be allocated by BalancedShardsAllocator.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by imRishN**
### Description
With https://github.com/opensearch-project/OpenSearch/pull/14848, we introduced capability to make reroute iteration time-bound. Currently OpenSearch uses two primary allocators - `ExistingShardsAllocator` which is responsible for allocating existing shards, and `BalancedShardsAllocator` which handles the allocation of all unassigned shards. 

This PR adds responsibility check in `ExistingShardsAllocator` such that newly created shards are not added to ignored list.

### Related Issues
Resolves #15222 

### Check List
- [x] Functionality includes testing.
- ~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java [hunk 1]
```diff
@@ -90,12 +91,33 @@ protected void allocateUnassignedBatchOnTimeout(Set<ShardId> shardIds, RoutingAl
...
+                && (shard.recoverySource().getType() == RecoverySource.Type.EXISTING_STORE
+                    || shard.recoverySource().getType() == RecoverySource.Type.SNAPSHOT);
+        } else {
+            return shard.primary() == false // must be a replica
+                && shard.unassigned() // must be unassigned
+                // if we are allocating a replica because of index creation, no need to go and find a copy, there isn't one...
+                && shard.unassignedInfo().getReason() != UnassignedInfo.Reason.INDEX_CREATED;
+        }
+    }
+
```
[the remark this answers is not in the document]
Comment (imRishN) [reply server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java]: Refactored

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java [hunk 2]
```diff
@@ -322,6 +323,21 @@ public void testAllocateUnassignedBatchOnTimeoutWithNoShards() {
         assertEquals(0, ignoredShards.size());
     }
 
+    public void testAllocateUnassignedBatchOnTimeoutSkipIgnoringNewPrimaryShards() {
```
Comment (Bukhtawar) [inline server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:326]: Should we add a test on ignored being non zero?

**Review by Bukhtawar — APPROVED** [review]

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java (hunk 2 above)
Comment (imRishN) [reply server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:287]: This test is already present - `testAllocateUnassignedBatchOnTimeoutWithMatchingPrimaryShards`

File: server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java [hunk 3]
```diff
@@ -283,40 +284,16 @@ public void testAllocateUnassignedBatchOnTimeoutWithNoMatchingPrimaryShards() {
...
-        final RoutingAllocation routingAllocation = routingAllocationWithOnePrimary(allocationDeciders, CLUSTER_RECOVERED, "allocId-0");
-
-        ShardRouting shardRouting = routingAllocation.routingTable()
-            .getIndicesRouting()
-            .get("test")
-            .shard(shardId.id())
-            .replicaShards()
-            .get(0);
-        Set<ShardId> shardIds = new HashSet<>();
-        batchAllocator.allocateUnassignedBatchOnTimeout(shardIds, routingAllocation, false);
```
Comment (imRishN) [inline server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java:319]: Removing these unnecessary test as it is calling `allocateUnassignedBatchOnTimeout` with `primary = false` for `PrimaryShardBatchAllocator` which can never happen
