### PR TITLE
Fix Bug - Handle unsigned long in sorting order assertion of LongHashSet

### LINKED ISSUE #17206: [BUG] Sorted Order Assertion in LongHashSet.java is incorrect
### Describe the bug

The assertion logic in [LongHashSet.java](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/apache/lucene/util/LongHashSet.java#L51) assumes signed long values, which leads to incorrect validation when dealing with unsigned long values. The sorted order check fails because `value >= previousValue` does not correctly handle unsigned comparisons.

### Related component

Search

### To Reproduce

1. Run `./gradlew run`
2. Create the Index 
`PUT test_index`
```
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0
    }
  },
  "mappings": {
    "properties": {
      "stat": {
        "type": "unsigned_long"
      },
      "latency": {
        "type": "long"
      }
    }
  }
}
```

3. Ingest sample documents 
4. Run Query - 
`POST test_index/_search`
```
{
  "query": {
    "terms": {
      "stat": [
        "9223372036854775814",
        "9223372036854775812",
        "9223372036854775811",
        "1"
      ]
    }
  },
  "aggs": {
    "sum_size": {
      "sum": {
        "field": "latency"
      }
    }
  }
}
```
5. We get - [Please check Additional Details below for Stack trace]
```
»  fatal error in thread [opensearch[runTask-0][search][T#1]], exiting
»  java.lang.AssertionError: values must be provided in sorted order
FAILURE: Build failed with an exception. 
```

### Expected behavior

In the normal flow, the query should correctly apply Terms aggregations without assertion errors.

### Additional Details

**Stack Trace**
```
»  java.lang.AssertionError: values must be provided in sorted order
»       at org.apache.lucene.util.LongHashSet.assertBasedOnDataType(LongHashSet.java:68)
»       at org.apache.lucene.util.LongHashSet.<init>(LongHashSet.java:55)
»       at org.opensearch.index.document.SortedUnsignedLongDocValuesSetQuery.<init>(SortedUnsignedLongDocValuesSetQuery.java:48)
»       at org.opensearch.index.document.SortedUnsignedLongDocValuesSetQuery$2.<init>(SortedUnsignedLongDocValuesSetQuery.java:150)
»       at org.opensearch.index.document.SortedUnsignedLongDocValuesSetQuery.newSlowSetQuery(SortedUnsignedLongDocValuesSetQuery.java:150)
»       at org.opensearch.index.mapper.NumberFieldMapper$NumberType$8.termsQuery(NumberFieldMapper.java:1168)
»       at org.opensearch.index.mapper.NumberFieldMapper$NumberFieldType.termsQuery(NumberFieldMapper.java:1577)
»       at org.opensearch.index.query.TermsQueryBuilder.doToQuery(TermsQueryBuilder.java:556)
»       at org.opensearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:117)
»       at org.opensearch.index.query.QueryShardContext.lambda$toQuery$3(QueryShardContext.java:575)
»       at org.opensearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:587)
»       at org.opensearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:574)
»       at org.opensearch.search.SearchService.parseSource(SearchService.java:1374)
»       at org.opensearch.search.SearchService.createContext(SearchService.java:1110)
»       at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:707)
»       at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:680)
»       at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74)
»       at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89)
»       at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
»       at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
»       at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
»       at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)
»       at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:994)
»       at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»       at java.base/java.lang.Thread.run(Thread.java:1583)
```

### PR DESCRIPTION
**Pull request by Shailesh-Kumar-Singh**
### Description
The assertion logic in [LongHashSet.java](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/apache/lucene/util/LongHashSet.java#L51) assumes signed long values, which leads to incorrect validation when dealing with unsigned long values. The sorted order check fails because value >= previousValue does not correctly handle unsigned comparisons.
I have described the Bug in detail in the issue - #17206

### FIX 
1. Created a new class `UnsignedLongHashSet.java` which does `Long.compareUnsigned(value, previousValue) >= 0` for unsigned long values.
2. Added Tests for this here - `DocValuesUnsignedLongHashSetTests.java`
3. in `SortedUnsignedLongDocValuesSetQuery.java` - We use `new UnsignedLongHashSet` instead of `new LongHashSet`

### Related Issues
Resolves #17206

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/apache/lucene/util/LongHashSet.java [hunk 1]
```diff
@@ -30,8 +30,12 @@ public final class LongHashSet implements Accountable {
     /** maximum value in the set, or Long.MIN_VALUE for an empty set */
     public final long maxValue;
 
-    /** Construct a set. Values must be in sorted order. */
     public LongHashSet(long[] values) {
```
Comment (reta) [inline server/src/main/java/org/apache/lucene/util/LongHashSet.java:33]: @Shailesh-Kumar-Singh Thanks for the fix, I think the cleanest (but a bit more verbose approach) would be to clone `LongHashSet` as `UnsignedLongHashSet`:
 - `MISSING` has to be set to `Numbers.MIN_UNSIGNED_LONG_VALUE_AS_LONG`
 - `minValue` value bound has to be  `Numbers.MIN_UNSIGNED_LONG_VALUE_AS_LONG`
- `maxValue` value bound has to be  `Numbers.MAX_UNSIGNED_LONG_VALUE_AS_LONG`

I actually don't know why we copied the Lucene class, @harshavamsi could you share the context please?

Comment (harshavamsi) [reply server/src/main/java/org/apache/lucene/util/LongHashSet.java:33]: We had to bring in the class because it was package private in lucene @reta

Comment (reta) [reply server/src/main/java/org/apache/lucene/util/LongHashSet.java:33]: Thanks @harshavamsi , I think we could drop it now, in 10.1 it is public (+ public constructors):

```
public class LongHashSet implements Iterable<LongCursor>, Accountable, Cloneable {
```

Comment (reta) [reply server/src/main/java/org/apache/lucene/util/LongHashSet.java:33]: Oh, there are few of them, `org.apache.lucene.document.LongHashSet`, it is gone in 10.x

File: server/src/main/java/org/apache/lucene/util/UnsignedLongHashSet.java [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+import org.apache.lucene.util.packed.PackedInts;
+import org.opensearch.common.Numbers;
+
+import java.util.Arrays;
+import java.util.Objects;
+import java.util.stream.Collectors;
+import java.util.stream.LongStream;
+
+/** Set of unsigned-longs, optimized for docvalues usage */
+public final class UnsignedLongHashSet implements Accountable {
```
Comment (bharath-techie) [inline server/src/main/java/org/apache/lucene/util/UnsignedLongHashSet.java:20]: Can we add tests similar to `TestDocValuesLongHashSet` in Lucene ?

**Comment by reta** [comment]
@Shailesh-Kumar-Singh thank you, please add CHANGELOG.md entry for this change

File: server/src/main/java/org/apache/lucene/util/UnsignedLongHashSet.java (hunk 2 above)
Comment (Shailesh-Kumar-Singh) [reply server/src/main/java/org/apache/lucene/util/UnsignedLongHashSet.java]: done

**Review by dbwiddis — APPROVED** [review]

**Comment by reta** [comment]
@Shailesh-Kumar-Singh could you rebase please? Thank you

File: server/src/main/java/org/opensearch/lucene/util/UnsignedLongHashSet.java [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+                && mask == that.mask
+                && hasMissingValue == that.hasMissingValue
+                && Arrays.equals(table, that.table);
+        }
+        return false;
+    }
+
+    @Override
+    public String toString() {
+        return stream().mapToObj(String::valueOf).collect(Collectors.joining(", ", "[", "]"));
```
Comment (reta) [inline server/src/main/java/org/opensearch/lucene/util/UnsignedLongHashSet.java:127]: I believe the `toString` would not print the unsigned long:

```suggestion
        return stream().mapToObj(Long::toUnsignedString).collect(Collectors.joining(", ", "[", "]"));
```

Comment (Shailesh-Kumar-Singh) [reply server/src/main/java/org/opensearch/lucene/util/UnsignedLongHashSet.java:127]: `I believe the toString would not print the unsigned long:` - the unsigned-long values will be printed as their long number representation
We can go ahead with `Long::toUnsignedString` to actually print the unsigned-long itself.

**Review by reta — APPROVED** [review]
