### PR TITLE
Excluding system indices from max shard limit validator

### LINKED ISSUE #2824: [BUG] System indices creation fails on max shard limit validator
**Describe the bug**
The system index like opensearch dashboard should not be prevented from opening or created due to max shard limit validation

**To Reproduce**
Create single node cluster with 1000 shards and install opensearch dashboard plugin. The plugin will fail to open

**Expected behavior**
Max shard limit should be for user created data indices that consume significant resources on node, not system indices storing the critical information

**Error Message**
```
{"type":"log","@timestamp":"2022-03-31T18:35:45Z","tags":["error","opensearch","data"],"pid":18804,"message":"[illegal_argument_exception]: Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [21295]/[6000] maximum shards open;"}
```

### PR DESCRIPTION
**Pull request by jainankitk**
Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>

### Description
Excluding the system indices from max shard limit validation
 
### Issues Resolved
#2824 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jainankitk** [comment]
start gradle check

File: server/src/main/java/org/opensearch/indices/ShardLimitValidator.java [hunk 1]
```diff
@@ -88,7 +90,12 @@ public int getShardLimitPerNode() {
      * @param state          the current cluster state
      * @throws ValidationException if creating this index would put the cluster over the cluster shard limit
      */
-    public void validateShardLimit(final Settings settings, final ClusterState state) {
+    public void validateShardLimit(final String indexName, final Settings settings, final ClusterState state) {
+        // Validate shard limit only for non system indices as it is not hard limit anyways
```
Comment (saratvemulapalli) [inline server/src/main/java/org/opensearch/indices/ShardLimitValidator.java:94]: Does it harm the system to relax the limit for certain types? What are the consequences?

Comment (jainankitk) [reply server/src/main/java/org/opensearch/indices/ShardLimitValidator.java:94]: This limit is soft to prevent resources going overboard. It is fine to prevent creation or opening of data indices as the impact is constrained to individual index, but doing that for system index can make feature completely unusable. Also, system indices are generally lightweight and well provisioned, hence should not be constrained by this soft limit.

**Comment by jainankitk** [comment]
start gradle check

File: server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java [hunk 2]
```diff
@@ -104,7 +106,54 @@ public void testUnderShardLimit() {
...
+     */
+    public void testSystemIndexCreationSucceeds() {
+        final ShardLimitValidator shardLimitValidator = createTestShardLimitService(1);
+        final Settings settings = Settings.builder()
+            .put(SETTING_VERSION_CREATED, Version.CURRENT)
+            .put(SETTING_NUMBER_OF_SHARDS, 1)
+            .put(SETTING_NUMBER_OF_REPLICAS, 1)
+            .build();
+        final ClusterState state = createClusterForShardLimitTest(1, 1, 0);
+        shardLimitValidator.validateShardLimit(".tasks", settings, state);
```
Comment (saratvemulapalli) [inline server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java:121]: May be validate no `ValidationException` is thrown?
Something like: `@Test(expected = Test.None.class` to annotate on top of the method.

**Review by saratvemulapalli — COMMENTED** [review]
Thanks @jainankitk for this.
Few minor comments, but overall it looks good to me.

File: server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java (hunk 2 above)
Comment (jainankitk) [reply server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java:121]: It seems unnecessary. Adding the annotation `@Test(expected = Test.None.class` gives redundancy warning in Intellij. So, I guess we can skip this?

File: server/src/main/java/org/opensearch/indices/ShardLimitValidator.java [hunk 3]
```diff
@@ -88,7 +90,12 @@ public int getShardLimitPerNode() {
      * @param state          the current cluster state
```
[the remark this answers is not in the document]
Comment (jainankitk) [reply server/src/main/java/org/opensearch/indices/ShardLimitValidator.java:90]: Done!

File: server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java (hunk 2 above)
Comment (saratvemulapalli) [reply server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java:121]: Got it. Thanks for letting me know :).

**Review by saratvemulapalli — APPROVED** [review]
