### PR TITLE
Retaining the old constructors for classes marked as API changed as part of #12333

### LINKED ISSUE #14068: [BUG] Constructors Incompatibility of API classes.
### Describe the bug

As part of https://github.com/opensearch-project/OpenSearch/pull/12333, constructors of some of the classes marked as API were changed to add a new ClusterManagerMetrics parameter. This is causing failures in the respective backport PRs (https://github.com/opensearch-project/OpenSearch/pull/13755 for reference) because of breaking changes. 

Resolution:
The older constructors can use NoOpMetricsRegistry instance and instantiate the ClusterManagerMetrics object.

### Related component

Cluster Manager

### To Reproduce

Reference Backport PR (https://github.com/opensearch-project/OpenSearch/pull/13755) 

### Expected behavior

The constructors compatibility for API classes should be retained. 

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by gargharsh3134**
### Description
As part of #12333, constructors of some of the classes marked as API were changed to add a new ClusterManagerMetrics parameter. This was causing failures in the respective backport PRs (#13755 for reference) because of breaking changes. This PR is targeted to retain those old constructors and maintain compatibility.

### Related Issues
Resolves #14068 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java [hunk 1]
```diff
@@ -125,6 +126,10 @@ public class ClusterApplierService extends AbstractLifecycleComponent implements
     private NodeConnectionsService nodeConnectionsService;
     private final ClusterManagerMetrics clusterManagerMetrics;
 
+    public ClusterApplierService(String nodeName, Settings settings, ClusterSettings clusterSettings, ThreadPool threadPool) {
```
Comment (rajiv-kv) [inline server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java:129]: Can we have a testcase that uses the no-op registery using this constructor and emits metrics ?

Comment (gargharsh3134) [reply server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java:129]: Updated in the revision.

**Review by rajiv-kv — APPROVED** [review]

**Review by sachinpkale — APPROVED** [review]

**Review by sachinpkale — APPROVED** [review]
