### PR TITLE
Fix Flaky Test SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes

### LINKED ISSUE #15944: [AUTOCUT] Gradle Check Flaky Test Report for SpecificClusterManagerNodesIT
## Flaky Test Report for `SpecificClusterManagerNodesIT`

Noticed the `SpecificClusterManagerNodesIT` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| 0a34a9737d483857039f7a46e664bae0f48a9e18 | [16303](https://github.com/opensearch-project/OpenSearch/pull/16303) | [49377](https://build.ci.opensearch.org/job/gradle-check/49377/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 0b1650de442d7c84f532bd23ae8e766abf1d5c45 | [16154](https://github.com/opensearch-project/OpenSearch/pull/16154) | [48758](https://build.ci.opensearch.org/job/gradle-check/48758/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 0cacc98598956595ff2a26f5054eee35a19b5329 | [16624](https://github.com/opensearch-project/OpenSearch/pull/16624) | [50672](https://build.ci.opensearch.org/job/gradle-check/50672/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 0d7ac2c94c6190ae11584146fea61bd7fc4c4b64 | [17104](https://github.com/opensearch-project/OpenSearch/pull/17104) | [52587](https://build.ci.opensearch.org/job/gradle-check/52587/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 12dadcf2aff9ce7e8f1bf4d6afe022684a7d6496 | [15950](https://github.com/opensearch-project/OpenSearch/pull/15950) | [48361](https://build.ci.opensearch.org/job/gradle-check/48361/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 15607b1ec44a8428f66c5d26c46b35fe1fc1bc50 | [16441](https://github.com/opensearch-project/OpenSearch/pull/16441) | [50000](https://build.ci.opensearch.org/job/gradle-check/50000/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 19d8df02444204e2098e012e553066489bb9b679 | [15999](https://github.com/opensearch-project/OpenSearch/pull/15999) | [48138](https://build.ci.opensearch.org/job/gradle-check/48138/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 1e7f6df79c7845ba04ecc4a05979db27965342c7 | [16257](https://github.com/opensearch-project/OpenSearch/pull/16257) | [49258](https://build.ci.opensearch.org/job/gradle-check/49258/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 2f0b607530d971c6d2e9828b9a74725499d628f9 | [16684](https://github.com/opensearch-project/OpenSearch/pull/16684) | [50852](https://build.ci.opensearch.org/job/gradle-check/50852/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 3da97f24ed0fbf90d403ba70d8a09d3850acb94d | [16718](https://github.com/opensearch-project/OpenSearch/pull/16718) | [50980](https://build.ci.opensearch.org/job/gradle-check/50980/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 45a8ed41f0c67f8853e36d95c1cc05d921b92739 | [15947](https://github.com/opensearch-project/OpenSearch/pull/15947) | [47875](https://build.ci.opensearch.org/job/gradle-check/47875/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 468e9259febcbaa113dd9e9182cd8b032ce1b560 | [16587](https://github.com/opensearch-project/OpenSearch/pull/16587) | [50518](https://build.ci.opensearch.org/job/gradle-check/50518/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 481fd38c807024bfdcbc28a5b3ddb67fbfc439ef | [16098](https://github.com/opensearch-project/OpenSearch/pull/16098) | [48529](https://build.ci.opensearch.org/job/gradle-check/48529/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 5068fad53922f992ef651f78c148df6d9170c361 | [16488](https://github.com/opensearch-project/OpenSearch/pull/16488) | [50673](https://build.ci.opensearch.org/job/gradle-check/50673/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 53c9ddf77c5d050d188fd342035f932600a41608 | [16273](https://github.com/opensearch-project/OpenSearch/pull/16273) | [49316](https://build.ci.opensearch.org/job/gradle-check/49316/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 53d41d3fac28c9f72d5883467d5a6211ad09feac | [16489](https://github.com/opensearch-project/OpenSearch/pull/16489) | [50662](https://build.ci.opensearch.org/job/gradle-check/50662/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 5d2d3920f53113340df5b35c6bff6bfa9e9e7adb | [16299](https://github.com/opensearch-project/OpenSearch/pull/16299) | [49358](https://build.ci.opensearch.org/job/gradle-check/49358/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 6111d05b41f270db354f6ec5d9521f91fdc24416 | [16568](https://github.com/opensearch-project/OpenSearch/pull/16568) | [50486](https://build.ci.opensearch.org/job/gradle-check/50486/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 620db0a64950cbd6a38642f0be1f592060dac1ee | [15972](https://github.com/opensearch-project/OpenSearch/pull/15972) | [48071](https://build.ci.opensearch.org/job/gradle-check/48071/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 6c7581ef6c67abc5bab0431b2be430361d8a7392 | [16394](https://github.com/opensearch-project/OpenSearch/pull/16394) | [49856](https://build.ci.opensearch.org/job/gradle-check/49856/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 6dc63c5281f631c8a1921bbd60f2bf975a82e0a5 | [17000](https://github.com/opensearch-project/OpenSearch/pull/17000) | [52086](https://build.ci.opensearch.org/job/gradle-check/52086/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 73e11af21c440c326f3685f5b13b359cf41bba92 | [17030](https://github.com/opensearch-project/OpenSearch/pull/17030) | [52210](https://build.ci.opensearch.org/job/gradle-check/52210/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 77e91c2fe11b86ec682d1d937bec0f2d000392f1 | [17005](https://github.com/opensearch-project/OpenSearch/pull/17005) | [52592](https://build.ci.opensearch.org/job/gradle-check/52592/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 783d3e1850e156161cb64519c2ab471290c3791a | [16308](https://github.com/opensearch-project/OpenSearch/pull/16308) | [49423](https://build.ci.opensearch.org/job/gradle-check/49423/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 7977446398fda5d553f39e2db32a395e917b9c78 | [17057](https://github.com/opensearch-project/OpenSearch/pull/17057) | [52477](https://build.ci.opensearch.org/job/gradle-check/52477/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 81288b1044348d99cce6d23770755a464121f7cc | [15957](https://github.com/opensearch-project/OpenSearch/pull/15957) | [47925](https://build.ci.opensearch.org/job/gradle-check/47925/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 83762c81c8d106ec4b4131369f71c42cf890ea14 | [17003](https://github.com/opensearch-project/OpenSearch/pull/17003) | [52148](https://build.ci.opensearch.org/job/gradle-check/52148/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 99e0c5759f7e6e7e0230d0a577bcad5ffd6c2fa1 | [17116](https://github.com/opensearch-project/OpenSearch/pull/17116) | [52583](https://build.ci.opensearch.org/job/gradle-check/52583/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| 9bb1fbe2d615602971cb786d06ff80ba377d1c7f | [16884](https://github.com/opensearch-project/OpenSearch/pull/16884) | [52065](https://build.ci.opensearch.org/job/gradle-check/52065/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| a2a01f821760f7f27eaf6d30b6a4daaadda9fec8 | [16543](https://github.com/opensearch-project/OpenSearch/pull/16543) | [50334](https://build.ci.opensearch.org/job/gradle-check/50334/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| aa5c39bbbce5bfcb06f4892ff5d6ccaea79126b2 | [16585](https://github.com/opensearch-project/OpenSearch/pull/16585) | [50507](https://build.ci.opensearch.org/job/gradle-check/50507/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| ac456430d6159a21a8899a95bc64208f6f4c9eb5 | [16759](https://github.com/opensearch-project/OpenSearch/pull/16759) | [51094](https://build.ci.opensearch.org/job/gradle-check/51094/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| b3459fdf0f07b3dfe1d8375fbc1db50840f7a8fe | [14948](https://github.com/opensearch-project/OpenSearch/pull/14948) | [49305](https://build.ci.opensearch.org/job/gradle-check/49305/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| bb1359f224158e94523ad1a2ecf5429244a8144f | [16430](https://github.com/opensearch-project/OpenSearch/pull/16430) | [49990](https://build.ci.opensearch.org/job/gradle-check/49990/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| bd26056669f41826a500f944869b198149c476a2 | [15877](https://github.com/opensearch-project/OpenSearch/pull/15877) | [47856](https://build.ci.opensearch.org/job/gradle-check/47856/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| c85ee6898b4e3e2f4a2037e42337a7eb8033de9e | [15988](https://github.com/opensearch-project/OpenSearch/pull/15988) | [48303](https://build.ci.opensearch.org/job/gradle-check/48303/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| d4d70d886ed5da1b657dca4c1e5af80ce9cd07ef | [16628](https://github.com/opensearch-project/OpenSearch/pull/16628) | [50777](https://build.ci.opensearch.org/job/gradle-check/50777/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| d7309a959d932e65dd9fd96a340509f60c732dd5 | [17060](https://github.com/opensearch-project/OpenSearch/pull/17060) | [52348](https://build.ci.opensearch.org/job/gradle-check/52348/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| dccd40f8455b3e1bc39a3f3633d9ebced5c108de | [16665](https://github.com/opensearch-project/OpenSearch/pull/16665) | [50801](https://build.ci.opensearch.org/job/gradle-check/50801/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| df6c12b1c64c47003c3f292be22f4d8b6d4e6f2d | [16362](https://github.com/opensearch-project/OpenSearch/pull/16362) | [49615](https://build.ci.opensearch.org/job/gradle-check/49615/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| e6d71d290e56e93920f8b8efa5ddbf885699607e | [16641](https://github.com/opensearch-project/OpenSearch/pull/16641) | [51613](https://build.ci.opensearch.org/job/gradle-check/51613/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| e8d498d82771f0ff54f8850d43d645bddf291c4f | [16169](https://github.com/opensearch-project/OpenSearch/pull/16169) | [48797](https://build.ci.opensearch.org/job/gradle-check/48797/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| f4fd707469d49f9de3f76cbde60567e36ef5f7bd | [16885](https://github.com/opensearch-project/OpenSearch/pull/16885) | [51626](https://build.ci.opensearch.org/job/gradle-check/51626/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| fccd6c54c14dabc46483f1b6ec3f3b02d08edfdd | [16950](https://github.com/opensearch-project/OpenSearch/pull/16950) | [52089](https://build.ci.opensearch.org/job/gradle-check/52089/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |
| febbc00132a13e04e65e4ef1996cc73eda4729de | [16237](https://github.com/opensearch-project/OpenSearch/pull/16237) | [49083](https://build.ci.opensearch.org/job/gradle-check/49083/testReport/) | `org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `SpecificClusterManagerNodesIT` class are:

- [14383](https://github.com/opensearch-project/OpenSearch/pull/14383)
- [14912](https://github.com/opensearch-project/OpenSearch/pull/14912)
- [16366](https://github.com/opensearch-project/OpenSearch/pull/16366)
- [15289](https://github.com/opensearch-project/OpenSearch/pull/15289)
- [15938](https://github.com/opensearch-project/OpenSearch/pull/15938)
- [16025](https://github.com/opensearch-project/OpenSearch/pull/16025)
- [16474](https://github.com/opensearch-project/OpenSearch/pull/16474)
- [16891](https://github.com/opensearch-project/OpenSearch/pull/16891)
- [14853](https://github.com/opensearch-project/OpenSearch/pull/14853)
- [15424](https://github.com/opensearch-project/OpenSearch/pull/15424)
- [15778](https://github.com/opensearch-project/OpenSearch/pull/15778)
- [15975](https://github.com/opensearch-project/OpenSearch/pull/15975)
- [16091](https://github.com/opensearch-project/OpenSearch/pull/16091)
- [16161](https://github.com/opensearch-project/OpenSearch/pull/16161)
- [16234](https://github.com/opensearch-project/OpenSearch/pull/16234)
- [16265](https://github.com/opensearch-project/OpenSearch/pull/16265)
- [16282](https://github.com/opensearch-project/OpenSearch/pull/16282)
- [16391](https://github.com/opensearch-project/OpenSearch/pull/16391)
- [16445](https://github.com/opensearch-project/OpenSearch/pull/16445)
- [16468](https://github.com/opensearch-project/OpenSearch/pull/16468)
- [16606](https://github.com/opensearch-project/OpenSearch/pull/16606)
- [16636](https://github.com/opensearch-project/OpenSearch/pull/16636)
- [16771](https://github.com/opensearch-project/OpenSearch/pull/16771)
- [16831](https://github.com/opensearch-project/OpenSearch/pull/16831)
- [16923](https://github.com/opensearch-project/OpenSearch/pull/16923)
- [16952](https://github.com/opensearch-project/OpenSearch/pull/16952)
- [17100](https://github.com/opensearch-project/OpenSearch/pull/17100)
- [17107](https://github.com/opensearch-project/OpenSearch/pull/17107)
- [17175](https://github.com/opensearch-project/OpenSearch/pull/17175)
- [12902](https://github.com/opensearch-project/OpenSearch/pull/12902)
- [14641](https://github.com/opensearch-project/OpenSearch/pull/14641)
- [14718](https://github.com/opensearch-project/OpenSearch/pull/14718)
- [14723](https://github.com/opensearch-project/OpenSearch/pull/14723)
- [15249](https://github.com/opensearch-project/OpenSearch/pull/15249)
- [15258](https://github.com/opensearch-project/OpenSearch/pull/15258)
- [15385](https://github.com/opensearch-project/OpenSearch/pull/15385)
- [15430](https://github.com/opensearch-project/OpenSearch/pull/15430)
- [15521](https://github.com/opensearch-project/OpenSearch/pull/15521)
- [15777](https://github.com/opensearch-project/OpenSearch/pull/15777)
- [15943](https://github.com/opensearch-project/OpenSearch/pull/15943)
- [15945](https://github.com/opensearch-project/OpenSearch/pull/15945)
- [15955](https://github.com/opensearch-project/OpenSearch/pull/15955)
- [15986](https://github.com/opensearch-project/OpenSearch/pull/15986)
- [16030](https://github.com/opensearch-project/OpenSearch/pull/16030)
- [16036](https://github.com/opensearch-project/OpenSearch/pull/16036)
- [16037](https://github.com/opensearch-project/OpenSearch/pull/16037)
- [16038](https://github.com/opensearch-project/OpenSearch/pull/16038)
- [16042](https://github.com/opensearch-project/OpenSearch/pull/16042)
- [16046](https://github.com/opensearch-project/OpenSearch/pull/16046)
- [16047](https://github.com/opensearch-project/OpenSearch/pull/16047)
- [16082](https://github.com/opensearch-project/OpenSearch/pull/16082)
- [16083](https://github.com/opensearch-project/OpenSearch/pull/16083)
- [16089](https://github.com/opensearch-project/OpenSearch/pull/16089)
- [16111](https://github.com/opensearch-project/OpenSearch/pull/16111)
- [16133](https://github.com/opensearch-project/OpenSearch/pull/16133)
- [16135](https://github.com/opensearch-project/OpenSearch/pull/16135)
- [16150](https://github.com/opensearch-project/OpenSearch/pull/16150)
- [16206](https://github.com/opensearch-project/OpenSearch/pull/16206)
- [16268](https://github.com/opensearch-project/OpenSearch/pull/16268)
- [16269](https://github.com/opensearch-project/OpenSearch/pull/16269)
- [16278](https://github.com/opensearch-project/OpenSearch/pull/16278)
- [16283](https://github.com/opensearch-project/OpenSearch/pull/16283)
- [16290](https://github.com/opensearch-project/OpenSearch/pull/16290)
- [16297](https://github.com/opensearch-project/OpenSearch/pull/16297)
- [16304](https://github.com/opensearch-project/OpenSearch/pull/16304)
- [16306](https://github.com/opensearch-project/OpenSearch/pull/16306)
- [16321](https://github.com/opensearch-project/OpenSearch/pull/16321)
- [16336](https://github.com/opensearch-project/OpenSearch/pull/16336)
- [16352](https://github.com/opensearch-project/OpenSearch/pull/16352)
- [16358](https://github.com/opensearch-project/OpenSearch/pull/16358)
- [16365](https://github.com/opensearch-project/OpenSearch/pull/16365)
- [16379](https://github.com/opensearch-project/OpenSearch/pull/16379)
- [16383](https://github.com/opensearch-project/OpenSearch/pull/16383)
- [16385](https://github.com/opensearch-project/OpenSearch/pull/16385)
- [16403](https://github.com/opensearch-project/OpenSearch/pull/16403)
- [16444](https://github.com/opensearch-project/OpenSearch/pull/16444)
- [16455](https://github.com/opensearch-project/OpenSearch/pull/16455)
- [16461](https://github.com/opensearch-project/OpenSearch/pull/16461)
- [16477](https://github.com/opensearch-project/OpenSearch/pull/16477)
- [16478](https://github.com/opensearch-project/OpenSearch/pull/16478)
- [16479](https://github.com/opensearch-project/OpenSearch/pull/16479)
- [16494](https://github.com/opensearch-project/OpenSearch/pull/16494)
- [16507](https://github.com/opensearch-project/OpenSearch/pull/16507)
- [16536](https://github.com/opensearch-project/OpenSearch/pull/16536)
- [16540](https://github.com/opensearch-project/OpenSearch/pull/16540)
- [16560](https://github.com/opensearch-project/OpenSearch/pull/16560)
- [16569](https://github.com/opensearch-project/OpenSearch/pull/16569)
- [16571](https://github.com/opensearch-project/OpenSearch/pull/16571)
- [16575](https://github.com/opensearch-project/OpenSearch/pull/16575)
- [16582](https://github.com/opensearch-project/OpenSearch/pull/16582)
- [16583](https://github.com/opensearch-project/OpenSearch/pull/16583)
- [16655](https://github.com/opensearch-project/OpenSearch/pull/16655)
- [16661](https://github.com/opensearch-project/OpenSearch/pull/16661)
- [16669](https://github.com/opensearch-project/OpenSearch/pull/16669)
- [16674](https://github.com/opensearch-project/OpenSearch/pull/16674)
- [16695](https://github.com/opensearch-project/OpenSearch/pull/16695)
- [16717](https://github.com/opensearch-project/OpenSearch/pull/16717)
- [16724](https://github.com/opensearch-project/OpenSearch/pull/16724)
- [16757](https://github.com/opensearch-project/OpenSearch/pull/16757)
- [16760](https://github.com/opensearch-project/OpenSearch/pull/16760)
- [16776](https://github.com/opensearch-project/OpenSearch/pull/16776)
- [16781](https://github.com/opensearch-project/OpenSearch/pull/16781)
- [16802](https://github.com/opensearch-project/OpenSearch/pull/16802)
- [16803](https://github.com/opensearch-project/OpenSearch/pull/16803)
- [16828](https://github.com/opensearch-project/OpenSearch/pull/16828)
- [16842](https://github.com/opensearch-project/OpenSearch/pull/16842)
- [16843](https://github.com/opensearch-project/OpenSearch/pull/16843)
- [16849](https://github.com/opensearch-project/OpenSearch/pull/16849)
- [16857](https://github.com/opensearch-project/OpenSearch/pull/16857)
- [16870](https://github.com/opensearch-project/OpenSearch/pull/16870)
- [16871](https://github.com/opensearch-project/OpenSearch/pull/16871)
- [16898](https://github.com/opensearch-project/OpenSearch/pull/16898)
- [16902](https://github.com/opensearch-project/OpenSearch/pull/16902)
- [16904](https://github.com/opensearch-project/OpenSearch/pull/16904)
- [16908](https://github.com/opensearch-project/OpenSearch/pull/16908)
- [16909](https://github.com/opensearch-project/OpenSearch/pull/16909)
- [16911](https://github.com/opensearch-project/OpenSearch/pull/16911)
- [16919](https://github.com/opensearch-project/OpenSearch/pull/16919)
- [16954](https://github.com/opensearch-project/OpenSearch/pull/16954)
- [16957](https://github.com/opensearch-project/OpenSearch/pull/16957)
- [16958](https://github.com/opensearch-project/OpenSearch/pull/16958)
- [16992](https://github.com/opensearch-project/OpenSearch/pull/16992)
- [17016](https://github.com/opensearch-project/OpenSearch/pull/17016)
- [17040](https://github.com/opensearch-project/OpenSearch/pull/17040)
- [17041](https://github.com/opensearch-project/OpenSearch/pull/17041)
- [17042](https://github.com/opensearch-project/OpenSearch/pull/17042)
- [17049](https://github.com/opensearch-project/OpenSearch/pull/17049)
- [17055](https://github.com/opensearch-project/OpenSearch/pull/17055)
- [17071](https://github.com/opensearch-project/OpenSearch/pull/17071)
- [17117](https://github.com/opensearch-project/OpenSearch/pull/17117)
- [17129](https://github.com/opensearch-project/OpenSearch/pull/17129)
- [17131](https://github.com/opensearch-project/OpenSearch/pull/17131)
- [17137](https://github.com/opensearch-project/OpenSearch/pull/17137)
- [17142](https://github.com/opensearch-project/OpenSearch/pull/17142)
- [17145](https://github.com/opensearch-project/OpenSearch/pull/17145)
- [17152](https://github.com/opensearch-project/OpenSearch/pull/17152)
- [17203](https://github.com/opensearch-project/OpenSearch/pull/17203)
- [17223](https://github.com/opensearch-project/OpenSearch/pull/17223)
- [17229](https://github.com/opensearch-project/OpenSearch/pull/17229)
- [17231](https://github.com/opensearch-project/OpenSearch/pull/17231)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by kkewwei**
### Description
The case is as follows:

1. When the `node_t1` is excluded from the vote config, and the cluster starts a new leader election, but the the node `node_t2` hasn't been elected as the new leader.

2. At the moment, we send request to get the ClusterManager, we first get ClusterManager name, and leads to the NullPointerException.

`internalCluster().nonClusterManagerClient()`-> ......->`getClusterManagerName()`

https://github.com/opensearch-project/OpenSearch/blob/f0ea056a93383c4ca7cac361fdf8c73e8afc3941/test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java#L2171

### Related Issues
Resolves #15944 #16015 

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by msfroh** [comment]
Checking the history of this test, has this been flaky for more than a year? 

The only code related to cluster manager election that I've been able to find changed more recently than ~5 years ago (besides renaming) is the introduction of DecommisionService in 2023.

**Comment by kkewwei** [comment]
> Checking the history of this test, has this been flaky for more than a year?
> 
> The only code related to cluster manager election that I've been able to find changed more recently than ~5 years ago (besides renaming) is the introduction of DecommisionService in 2023.

I'm not clear why it wasn’t reported before, maybe the frequency of occurrence is very low and we ignored it? This issue #15944 collects some of the recent case.

Logically speaking, when the cluster has no cluster manager, It's right to return null from `getClusterManagerNode`, which will hit the case.

**Comment by kkewwei** [comment]
@msfroh please help confirm it when you are free.

File: server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java [hunk 1]
```diff
@@ -255,19 +256,24 @@ public void testElectOnlyBetweenClusterManagerNodes() throws Exception {
...
+                        .getState()
+                        .nodes()
+                        .getClusterManagerNode()
+                        .getName();
+                } catch (Exception e) {
+                    logger.debug("failed to get cluster-manager name", e);
+                    return null;
+                }
+            };
+            assertThat(clusterManagerName.get(), equalTo(nextClusterManagerEligableNodeName));
```
Comment (jed326) [inline server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java:276]: So if we swallow the NPE with the try/catch above, won't this test still fail on the assertion here since `clusterManagerName.get()` would be `null` and `nextClusterManagerEligableNodeName` shouldn't be `null`?

Comment (kkewwei) [reply server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java:276]: @jed326 t`assertBusy` allows the assert failed in 10s, so it seems ok.

File: server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java [hunk 2]
```diff
@@ -255,19 +256,24 @@ public void testElectOnlyBetweenClusterManagerNodes() throws Exception {
...
-                    .prepareState()
-                    .execute()
-                    .actionGet()
-                    .getState()
-                    .nodes()
-                    .getClusterManagerNode()
-                    .getName(),
-                equalTo(nextClusterManagerEligableNodeName)
-            );
+            Supplier<String> clusterManagerName = () -> {
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java:259]: - Can we move the supplier ouside the `assertBusy` block ?
- nit: could be rename as `getClusterManagerIfElected`

File: server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java [hunk 3]
```diff
@@ -255,19 +256,24 @@ public void testElectOnlyBetweenClusterManagerNodes() throws Exception {
...
+                        .admin()
+                        .cluster()
+                        .prepareState()
+                        .execute()
+                        .actionGet()
+                        .getState()
+                        .nodes()
+                        .getClusterManagerNode()
+                        .getName();
+                } catch (Exception e) {
```
Comment (rajiv-kv) [inline server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java:271]: Instead of catching a generic exception, could we catch a specific exception related to ClusterManager Not found.

File: server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java (hunk 1 above)
Comment (rajiv-kv) [reply server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java:276]: We can add an additional assert before this to evaluate it is not null.

**Review by rajiv-kv — COMMENTED** [review]
Thanks @kkewwei for raising a fix

File: server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java (hunk 1 above)
Comment (kkewwei) [reply server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java]: `assertBusy` can retry in 10s, it seems that we shouldn't add a new `assertBusy` before it.

File: server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java (hunk 2 above)
Comment (kkewwei) [reply server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java]: Make sense to me.

File: test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java [hunk 4]
```diff
@@ -2171,7 +2172,7 @@ public String getClusterManagerName(@Nullable String viaNode) {
             return client.admin().cluster().prepareState().get().getState().nodes().getClusterManagerNode().getName();
         } catch (Exception e) {
```
Comment (rajiv-kv) [inline test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java:2173]: Can we have a seperate catch block for `ClusterManagerNotDiscoveredException` and not change the generic exception handler ?

Comment (kkewwei) [reply test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java:2179]: @rajiv-kv I think when null is detected, we should take the initiative to handle it, how about this fix?

**Review by rajiv-kv — APPROVED** [review]

**Comment by shwetathareja** [comment]
Minor comment, thanks for picking it up @kkewwei

File: test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java [hunk 5]
```diff
@@ -2168,7 +2169,13 @@ public String getClusterManagerName() {
...
         try {
             Client client = viaNode != null ? client(viaNode) : client();
-            return client.admin().cluster().prepareState().get().getState().nodes().getClusterManagerNode().getName();
+            DiscoveryNode masterNode = client.admin().cluster().prepareState().get().getState().nodes().getClusterManagerNode();
+            if (masterNode == null) {
+                throw new ClusterManagerNotDiscoveredException("Cluster manager node not discovered");
+            }
+            return masterNode.getName();
+        } catch (ClusterManagerNotDiscoveredException exception) {
+            throw exception;
```
[the remark this answers is not in the document]
Comment (kkewwei) [reply test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java:2178]: Just want to separate ClusterManagerNotDiscoveredException and other generic exception.

File: test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java [hunk 6]
```diff
@@ -2168,7 +2169,13 @@ public String getClusterManagerName() {
     public String getClusterManagerName(@Nullable String viaNode) {
         try {
             Client client = viaNode != null ? client(viaNode) : client();
-            return client.admin().cluster().prepareState().get().getState().nodes().getClusterManagerNode().getName();
+            DiscoveryNode masterNode = client.admin().cluster().prepareState().get().getState().nodes().getClusterManagerNode();
+            if (masterNode == null) {
+                throw new ClusterManagerNotDiscoveredException("Cluster manager node not discovered");
+            }
+            return masterNode.getName();
```
Comment (andrross) [inline test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java:2176]: Just a naming nitpick here...

```suggestion
            DiscoveryNode clusterManagerNode = client.admin().cluster().prepareState().get().getState().nodes().getClusterManagerNode();
            if (clusterManagerNode == null) {
                throw new ClusterManagerNotDiscoveredException("Cluster manager node not discovered");
            }
            return clusterManagerNode.getName();
```

File: test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (andrross) [reply test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java:2178]: I think it's probably fine to do this to avoid wrapping the exception in another RuntimeException.

Did you look at removing the try-catch all together? This code doesn't throw a checked exception as far as I can tell, so why not just let the actual exception bubble up to the calling test code in all cases?

**Comment by kkewwei** [comment]
> ❕ Gradle check result for [366bb52](https://github.com/opensearch-project/OpenSearch/commit/366bb5263fb26f5d5719a7bc7d771c69de55cc2c): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/53092/)
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

org.opensearch.index.ShardIndexingPressureSettingsIT.testShardIndexingPressureEnforcedEnabledDisabledSetting https://github.com/opensearch-project/OpenSearch/issues/14331

**Comment by kkewwei** [comment]
@shwetathareja @andrross please have a look when you are free.

**Review by andrross — APPROVED** [review]

**Review by msfroh — APPROVED** [review]
