### PR TITLE
[Segment Replication] Update version check for segment replication backpressure rejection stats

### LINKED ISSUE #10501: [Remote Store] Include SegRep and Remote Store Rejections in  node/stats api
**Describe the bug**
 We reject write requests when replicas are lagging or remote store segment store is lagging - https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java#L534

We should include this rejections in our node stats in a separate blob of its own on the lines of shard_indexing_pressure/search backpressure 

Proposed blobs are 

```
      "remote_store_pressure" : {
       "rejections" : count,
      },
      "segment_replication_pressure" : {
       "rejections" : count,
      },

```

**Alternate**

We can have one blob as well to account for both of them

```
      "remote_store_pressure" : {
       "upload_rejections" : count,
"lag_rejections" : count
      },
```

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR updates version check for segment replication backpressure rejection stats made in #10656 .

This PR should only be merged after #10834 is merged.

### Related Issues
Resolves #10501 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by mch2 — APPROVED** [review]

File: server/src/main/java/org/opensearch/index/SegmentReplicationRejectionStats.java [hunk 1]
```diff
@@ -34,8 +34,7 @@ public SegmentReplicationRejectionStats(final long totalRejectionCount) {
     }
 
     public SegmentReplicationRejectionStats(StreamInput in) throws IOException {
-        // TODO: change to V_2_12_0 on main after backport to 2.x
-        if (in.getVersion().onOrAfter(Version.V_3_0_0)) {
+        if (in.getVersion().onOrAfter(Version.V_2_12_0)) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/SegmentReplicationRejectionStats.java:37]: didn't catch this before but we don't need to add the wire compat here given the compat is handled in nodestats.

**Comment by ashking94** [comment]
@mch2 We have a fix one of the frequently failing flaky test here - https://github.com/opensearch-project/OpenSearch/pull/10838. This PR is blocked on the MixedClusterClientYAML test failures. Lets merge this so that the flaky test fix PR can be merged as well.

**Review by sachinpkale — APPROVED** [review]

**Comment by mch2** [comment]
> @mch2 We have a fix one of the frequently failing flaky test here - #10838. This PR is blocked on the MixedClusterClientYAML test failures. Lets merge this so that the flaky test fix PR can be merged as well.

I would prefer not to but we've been trying to get this in all day, so lets go ahead and i'll make sure this passes.
