### PR TITLE
Fix flakyness in RemoteStoreRefreshListenerTests

### LINKED ISSUE #8549: [BUG] Flaky test org.opensearch.index.shard.RemoteStoreRefreshListenerTests.testRefreshSuccessOnThirdAttemptAttempt
**Describe the bug**
org.opensearch.index.shard.RemoteStoreRefreshListenerTests.testRefreshSuccessOnThirdAttemptAttempt Test is flaky.

**To Reproduce**
Build - https://build.ci.opensearch.org/job/gradle-check/19505/

**Expected behavior**
Test should pass.

**Plugins**
Standard 

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by ashking94**
### Description
Fix flakyness in `RemoteStoreRefreshListenerTests` -> `testRefreshSuccessOnThirdAttemptAttempt`

### Related Issues
Resolves #8549

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ashking94** [comment]
I will need to rebase after #8547 is merged.

**Comment by sachinpkale** [comment]
> I will need to rebase after #8547 is merged.

https://github.com/opensearch-project/OpenSearch/pull/8547/ is merged. Please rebase.

File: server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java [hunk 1]
```diff
@@ -322,11 +322,12 @@ public void testRefreshSuccessOnThirdAttemptAttempt() throws Exception {
         assertBusy(() -> assertEquals(0, successLatch.getCount()));
         RemoteRefreshSegmentPressureService pressureService = tuple.v2();
         RemoteRefreshSegmentTracker segmentTracker = pressureService.getRemoteRefreshSegmentTracker(indexShard.shardId());
-        assertEquals(0, segmentTracker.getBytesLag());
-        assertEquals(0, segmentTracker.getRefreshSeqNoLag());
-        assertEquals(0, segmentTracker.getTimeMsLag());
-        assertEquals(2, segmentTracker.getTotalUploadsFailed());
-
+        assertBusy(() -> {
```
Comment (sachinpkale) [inline server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java:325]: Do we need similar change for other tests as well? `testRefreshSuccessOnSecondAttempt` is mentioned https://github.com/opensearch-project/OpenSearch/issues/8279 as flaky. Maybe the same issue?

Also, can we please fix the test name? `testRefreshSuccessOnThirdAttemptAttempt` -> `testRefreshSuccessOnThirdAttempt`

**Review by sachinpkale — APPROVED** [review]

**Comment by sachinpkale** [comment]
Re-triggering `precommit`
