### PR TITLE
Fix derived query rewrite

### LINKED ISSUE #19337: [BUG] Removing rewrite for derived fields
### Describe the bug

In #19296, i commented out the rewrite for derived fields. Rewriting certain queries that are wrapped in the derived field type now have issues at the lucene layer. Range queries in lucene now check pointvalues at rewrite time and since derived fields are not indexed, the rewrite returns a `MatchNoDocsQuery` which is incorrect. 

We need to figure out a more concrete rewriting pattern for derived fields. Using this issue to track discussions.

### Related component

Search

### To Reproduce

Running a rewrite on a derived field causes issues while doing range queries

### Expected behavior

Figure out new ways to rewrite derived field queries

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by harshavamsi**
### Description
Reverts derived field rewrite and chooses to rewrite queries based on the type of query

### Related Issues
Resolves #19337 

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java [hunk 1]
```diff
@@ -159,13 +161,20 @@ public IndexFieldData.Builder fielddataBuilder(String fullyQualifiedIndexName, S
     @Override
     public Query termQuery(Object value, QueryShardContext context) {
         Query query = typeFieldMapper.mappedFieldType.termQuery(value, context);
+        boolean rewrite = true;
+        if (query instanceof IndexOrDocValuesQuery) {
+            if (((IndexOrDocValuesQuery) query).getIndexQuery() instanceof PointRangeQuery) {
+                rewrite = false;
+            }
+        }
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java]: We can abstract this logic into a method and directly have it as part of `DerivedFieldQuery`? instead of passing this rewrite parameter from `DerivedFieldType`?

Comment (harshavamsi) [reply server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java]: So the alternative would be 
```
        if((query instanceof IndexOrDocValuesQuery && ((IndexOrDocValuesQuery) query).getIndexQuery() instanceof PointRangeQuery) || query instanceof PointRangeQuery) {
            return this;
        }
```

in the rewrite.

I assumed that the current way of implementing it is clearer than this?

Comment (jainankitk) [reply server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java]: You can put this whole logic in a private method `f` that returns booleans and have some logic:

```
if (f() == false) {
            return this;
        }
```

Comment (harshavamsi) [reply server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java]: @jainankitk made the change

**Review by jainankitk — APPROVED** [review]

**Comment by jainankitk** [comment]
@harshavamsi - Can you merge main into your branch?
