### PR TITLE
Mock correct method in SegmentReplicationTargetServiceTests

### LINKED ISSUE #15829: [AUTOCUT] Gradle Check Flaky Test Report for SegmentReplicationTargetServiceTests
## Flaky Test Report for `SegmentReplicationTargetServiceTests`

Noticed the `SegmentReplicationTargetServiceTests` has some flaky, failing tests that failed during **post-merge actions**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| e21f6b8e768870d5426d1d1b04815a17a7a05ab3 | [14625](https://github.com/opensearch-project/OpenSearch/pull/14625) | [44368](https://build.ci.opensearch.org/job/gradle-check/44368/testReport/) | `org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testStartReplicationListenerSuccess` |
| e76dcf968ce417eda479115276e6c616dd0e4f0e | [15716](https://github.com/opensearch-project/OpenSearch/pull/15716) | [47106](https://build.ci.opensearch.org/job/gradle-check/47106/testReport/) | `org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testStartReplicationListenerSuccess` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `SegmentReplicationTargetServiceTests` class are:

- [15333](https://github.com/opensearch-project/OpenSearch/pull/15333)
- [15511](https://github.com/opensearch-project/OpenSearch/pull/15511)
- [13724](https://github.com/opensearch-project/OpenSearch/pull/13724)
- [14095](https://github.com/opensearch-project/OpenSearch/pull/14095)
- [14345](https://github.com/opensearch-project/OpenSearch/pull/14345)
- [14993](https://github.com/opensearch-project/OpenSearch/pull/14993)
- [15416](https://github.com/opensearch-project/OpenSearch/pull/15416)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by andrross**
The test was mocking the wrong overload of startReplication(), which caused the real method to be invoke and would result in a failure + retry. The test assertion would then be racing with the retry and fail if the retry invoked startReplication() a second time.

Resolves #15829

### Check List
- [x] Functionality includes testing.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java [hunk 1]
```diff
@@ -673,8 +673,8 @@ public void testDoNotProcessLatestCheckpointIfCheckpointIsBehind() {
 
     public void testProcessLatestCheckpointIfCheckpointAhead() {
         SegmentReplicationTargetService service = spy(sut);
-        doNothing().when(service).startReplication(any());
         doReturn(mock(SegmentReplicationTarget.class)).when(service).startReplication(any(), any(), any());
+        doReturn(mock(SegmentReplicationTarget.class)).when(service).startReplication(any(), any(), anyBoolean(), any());
```
Comment (cwperks) [inline server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java:677]: are both this line and the line directly above this necessary?

**Review by cwperks — APPROVED** [review]

File: server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java (hunk 1 above)
Comment (andrross) [reply server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java:677]: Yes, there are cases where it may hit both overloads
