### PR TITLE
Treat Setting value with empty array string as empty array

### LINKED ISSUE #3412: [BUG] OpenSearch app is not able to pick up empty `node.roles=` environment variable to run as coordinating node.
**Describe the bug**
Coming from the issue https://github.com/opensearch-project/opensearch-build/issues/2129, OpenSearch app is not able to pick up empty `node.roles=` environment values, to allow to run as coordinating node. This works fine when added to `opensearch.yml` as `node.roles: []`, but not able to pick when passed as environment variable. However when passed a specific role as `node.roles=master` OpenSearch app  is able to pick up and pass the role as `master`. 
```
docker run -e 'node.roles=master,data' opensearchproject/opensearch:1.3.2 |grep role
[2022-05-20T01:31:30,027][INFO ][o.o.n.Node               ] [9a683cb05664] node name [9a683cb05664], node ID [vgu0pnrgQRytmfj2ZC6siw], cluster name [docker-cluster], roles [master, data]
```

As per the document https://opensearch.org/docs/latest/opensearch/cluster/, passing  empty list`node.roles: []` should allow the node to run with coordinating role.

**To Reproduce**
```
docker run -e 'node.roles=' opensearchproject/opensearch:1.3.2 |grep role
[2022-05-20T01:26:25,169][INFO ][o.o.n.Node               ] [5e7b9fa617b3] node name [5e7b9fa617b3], node ID [pEkc98u4Q-SdZLr4ojZ-QQ], cluster name [docker-cluster], roles [master, remote_cluster_client, data, ingest]
```

 ```
docker run -e 'node.roles=[]' opensearchproject/opensearch:1.3.2 |grep role
uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown role [[]]
Caused by: java.lang.IllegalArgumentException: unknown role [[]]
java.lang.IllegalArgumentException: unknown role [[]]
```

```
docker run -e 'node.roles=" "' opensearchproject/opensearch:1.3.2 |grep role
uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown role [" "]
Caused by: java.lang.IllegalArgumentException: unknown role [" "]
java.lang.IllegalArgumentException: unknown role [" "]

```
**Expected behavior**
`docker run -e 'node.roles=' ` should allow to run the node as coordinating node.

**Host/Environment (please complete the following information):**
 - OS:  docker

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by machenity**
### Description
[According to the documentation](https://opensearch.org/docs/latest/tuning-your-cluster/index/#coordinating-node), to create a dedicated coordinating node , empty array (`[]`) should be set as `node.roles` setting in the opensearch.yml document. The problem is that when I pass the setting value `"[]"`(env variables are always strings) via an environment variable, OpenSearch's environment variable parser does not determine it as an empty array and [uses it as a string](https://forum.opensearch.org/t/how-can-i-pass-an-empty-array-when-putting-settings-as-an-environment-variable/16247) of `"[]"`. As a result, it was not possible to create a dedicated coordinating node using an environment variable.

This PR fixes this so that if a listSetting value that is `"[]" + any whitespaces`, it is treated as an empty array.

### Related Issues
Resolves #3412

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by msfroh** [comment]
I'm concerned about the potential blast-radius of this change. `Setting` is used **everywhere**, so this may have unintended consequences. The string `"[]"` is not the same thing as the empty array.

Can we apply this logic only when reading settings from environment variables instead?

**Comment by machenity** [comment]
The change is in class`ListSetting`, the subclass of `Setting`, and only applies to one of the static factory methods below it.
I think any settings which is an instance of `ListSetting`, expect its value to be either a yaml array or a comma-separated values string.
The only settings that instantiated by that certain factor method are affected by the change, so I don't think the blast-radius would be that large.

Also, the code that reads in the environment variable is located in `ResolvePlaceholder`, and I don't think it makes any checks or judgments about the content of the value of the retrieved environment variable. Rather, I'm concerned that reading the content, determining that it's an empty array of strings or something else and changing it might exceed its responsibility range.

File: server/src/main/java/org/opensearch/common/settings/Setting.java [hunk 1]
```diff
@@ -2337,11 +2337,17 @@ public static <T> Setting<List<T>> listSetting(
         if (defaultStringValue.apply(Settings.EMPTY) == null) {
             throw new IllegalArgumentException("default value function must not return null");
         }
-        Function<String, List<T>> parser = (s) -> parseableStringToList(s).stream().map(singleValueParser).collect(Collectors.toList());
+        Function<String, List<T>> parser = (s) -> isParsedAsEmptyArray(s)
```
Comment (reta) [inline server/src/main/java/org/opensearch/common/settings/Setting.java:2340]: @machenity this is not how the list setting is supposed to be processed, the `[]` string from YAML file is processed correctly, you could check it by improving the SettingsTests::testSimpleYamlSettings

```
test1:
  value1: value1
  test2:
    value2: value2
    value3: 2
  test3:
    - test3-1
    - test3-2
test4: []
```

```
    public void testSimpleYamlSettings() throws Exception {
        final String yaml = "/org/opensearch/common/settings/loader/test-settings.yml";
        final Settings settings = Settings.builder().loadFromStream(yaml, getClass().getResourceAsStream(yaml), false).build();

        assertThat(settings.get("test1.value1"), equalTo("value1"));
        assertThat(settings.get("test1.test2.value2"), equalTo("value2"));
        assertThat(settings.getAsInt("test1.test2.value3", -1), equalTo(2));

        // check array
        assertNull(settings.get("test1.test3.0"));
        assertNull(settings.get("test1.test3.1"));
        assertThat(settings.getAsList("test1.test3").size(), equalTo(2));
        assertThat(settings.getAsList("test1.test3").get(0), equalTo("test3-1"));
        assertThat(settings.getAsList("test1.test3").get(1), equalTo("test3-2"));
        assertThat(settings.getAsList("test4"), hasSize(0));
    }
```

File: server/src/test/java/org/opensearch/node/NodeRoleSettingsTests.java [hunk 2]
```diff
@@ -72,4 +72,10 @@ public void testUnknownNodeRoleOnly() {
         assertEquals(testRole, nodeRoles.get(0).roleName());
         assertEquals(testRole, nodeRoles.get(0).roleNameAbbreviation());
     }
+
+    public void testNodeRoleOfEmptyArrayNameShouldBeIgnored() {
+        String testRole = "[ ]";
+        Settings roleSettings = Settings.builder().put(NodeRoleSettings.NODE_ROLES_SETTING.getKey(), testRole).build();
```
Comment (reta) [inline server/src/test/java/org/opensearch/node/NodeRoleSettingsTests.java:78]: Since NODE_ROLES_SETTING is a list setting, `put` add value to the list and should not be treated as special string I believe

File: server/src/main/java/org/opensearch/common/settings/Setting.java (hunk 1 above)
Comment (machenity) [reply server/src/main/java/org/opensearch/common/settings/Setting.java:2340]: Right. But That's not a point what I want to solve. If we edit the SettingsTests::testSimpleYamlSettings:
```yaml
test1:
  value1: value1
  test2:
    value2: value2
    value3: 2
  test3:
    - test3-1
    - test3-2
  test4: []
  test5: ${NODE_ROLE}
```

```java
public void testSimpleYamlSettings() throws Exception {
        final String yaml = "/org/opensearch/common/settings/loader/test-settings.yml";
        final Settings settings = Settings.builder().loadFromStream(yaml, getClass().getResourceAsStream(yaml), false)
            .replacePropertyPlaceholders() // Replace placeholders with env vars
            .build();

       // ...

        // check array
        assertThat(settings.getAsList("test1.test4"), empty()); // this succeeded
        assertThat(settings.getAsList("test1.test5"), empty()); // this failed
    }
```
If we run the test above with an environment variable `NODE_ROLE=[]`, you can see the last assertion failed.
image

image

Comment (reta) [reply server/src/main/java/org/opensearch/common/settings/Setting.java:2340]: Got the use case now, thanks @machenity (it was a long tail issue). I think the difficulty here is that we don't know what the setting value should be since the placeholders are applied after parsing the YAML / JSON and the semantic of the value is not known anymore. We could enhance the placeholder substitution to recognize that:

```
                // if the values exists and has length, we should maintain it in the map
                // otherwise, the replace process resolved into removing it
                if ("[]".equalsIgnoreCase(value)) { 
                    entry.setValue(Collections.emptyList());
                } else if (Strings.hasLength(value)) {
                    entry.setValue(value);
                } else  {
                    entryItr.remove();
                }
```

But that would be not sufficient as per https://github.com/opensearch-project/OpenSearch/issues/3412#issuecomment-1134724811 (if we accept `[]`, we should accept `["a", "b", "c"]` as well. However changing the behaviour of treating the setting values is super sensitive.

Comment (reta) [reply server/src/main/java/org/opensearch/common/settings/Setting.java:2340]: @machenity I think I have drafted an acceptable solution, do you mind if I push the change there or you would prefer me to open a separate pull request? Thank you.

Comment (machenity) [reply server/src/main/java/org/opensearch/common/settings/Setting.java:2340]: > But that would be not sufficient as per https://github.com/opensearch-project/OpenSearch/issues/3412#issuecomment-1134724811 (if we accept [], we should accept ["a", "b", "c"] as well). However changing the behaviour of treating the setting values is super sensitive.

You're right. I want to minimize the impact to the user semantics by treating only [] as a special case, but we should accept ["a", "b", "c"] as well if we accept [], as you told.

@reta Feel free to push here or do other way you prefer. Thanks for your kind reviews and comments.

Comment (reta) [reply server/src/main/java/org/opensearch/common/settings/Setting.java]: Done, @msfroh may I ask you please to recheck this change? I came up to the same conclusion as you, the change is now isolated to placeholders  (environment variables) only, thanks!

**Comment by reta** [comment]
@machenity could you please rebase against latest `main`? thank you

**Comment by reta** [comment]
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/28280/

Broken by https://github.com/opensearch-project/OpenSearch/pull/10696/files#r1364151268

**Comment by reta** [comment]
@msfroh friendly ping please

File: server/src/main/java/org/opensearch/common/settings/Setting.java (hunk 1 above)
Comment (msfroh) [reply server/src/main/java/org/opensearch/common/settings/Setting.java]: Awesome! Thanks for scoping it down 👍

**Review by msfroh — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [6f21088](https://github.com/opensearch-project/OpenSearch/commit/6f21088c0da34914029bfbb885d2605a3e889faf): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/30053/)

https://github.com/opensearch-project/OpenSearch/issues/11208
