### PR TITLE
Fix double invocation of postCollection when MultiBucketCollector is present

### LINKED ISSUE #14000: [BUG] Additional aggregation in search request is changing results
### Describe the bug

We have discovered erratic behavior for aggregation results introduced in `v2.14.0` (double-checked against `v2.13.0`, results are okay there). We have the following query (the actual queries we are using make more sense, this is the minimal query we have found to trigger the issue):

```json
{
	"size": 0,
	"aggs": {
		"http_method": {
			"terms": {
				"script": {
					"source": "doc['http_method']",
					"lang": "painless"
				}
			},
			"aggs": {
				"filter_aggregation": {
					"filters": {
						"filters": [
							{
								"bool": {}
							}
						]
					}
				}
			}
		},
		"timestamp-min": {
			"min": {
				"field": "timestamp"
			}
		}
	}
}
```

The underlying data in the index are test fixtures from out integration tests (check [here](https://github.com/Graylog2/graylog2-server/blob/6.0.3/full-backend-tests/src/test/resources/org/graylog/plugins/views/aggregations/random-http-logs.json)) - format is that each document in `$.documents[*].document` has a `index` metadata object containing the index name/document id/document type and `data` containing the actual document.

Starting with `v2.14.0`, the result looks like this:

```json
{
	"took": 102,
	"timed_out": false,
	"_shards": {
		"total": 1,
		"successful": 1,
		"skipped": 0,
		"failed": 0
	},
	"hits": {
		"total": {
			"value": 1000,
			"relation": "eq"
		},
		"max_score": null,
		"hits": []
	},
	"aggregations": {
		"timestamp-min": {
			"value": 1.664201539998E12,
			"value_as_string": "2022-09-26 14:12:19.998"
		},
		"http_method": {
			"meta": {},
			"doc_count_error_upper_bound": 0,
			"sum_other_doc_count": 0,
			"buckets": [
				{
					"key": "GET",
					"doc_count": 860,
					"filter_aggregation": {
						"meta": {},
						"buckets": [
							{
								"doc_count": 1720
							}
						]
					}
				},
				{
					"key": "DELETE",
					"doc_count": 52,
					"filter_aggregation": {
						"meta": {},
						"buckets": [
							{
								"doc_count": 104
							}
						]
					}
				},
				{
					"key": "POST",
					"doc_count": 45,
					"filter_aggregation": {
						"meta": {},
						"buckets": [
							{
								"doc_count": 90
							}
						]
					}
				},
				{
					"key": "PUT",
					"doc_count": 43,
					"filter_aggregation": {
						"meta": {},
						"buckets": [
							{
								"doc_count": 86
							}
						]
					}
				}
			]
		}
	}
}
```

What is noteworthy is that for each of the buckets generated by the filter aggregations, the document count of the bucket that goes _into_ the filter aggregation is **half** of the document count that comes _out_ of the filter aggregation:

```json
[...]
			"buckets": [
				{
					"key": "GET",
					"doc_count": 860,
					"filter_aggregation": {
						"meta": {},
						"buckets": [
							{
								"doc_count": 1720 <--- more documents in leaf bucket than in parent bucket
							}
						]
					}
				},
[...]
```

 The initial document count (e.g. `860` for the `GET` bucket) is correct, the one in the bucket produced by the filter aggregation is not. When adding e.g. a `sum` metric aggregation as a leaf, the value returned is **double** of what is expected, so it looks like for some reason the actual documents are duplicated during the aggregation.

What is very strange is:

  - the exact same query returns correct results in all versions _before_ `v2.14.0`
  - when removing the `timestamp-min` metric, the results are okay
  - when using a terms aggregation instead of a scripted terms aggregation (i.e. replacing `"script": {...}` with `"field": "http_method"`, the results are okay
  

### Related component

Search:Aggregations

### To Reproduce

1. Use this query:
```json
{
	"size": 0,
	"aggs": {
		"http_method": {
			"terms": {
				"script": {
					"source": "doc['http_method']",
					"lang": "painless"
				}
			},
			"aggs": {
				"filter_aggregation": {
					"filters": {
						"filters": [
							{
								"bool": {}
							}
						]
					}
				}
			}
		},
		"timestamp-min": {
			"min": {
				"field": "timestamp"
			}
		}
	}
}
```
2. Execute query against sample data

### Expected behavior

Expecting a result like this:
```json
{
	"took": 4,
	"timed_out": false,
	"_shards": {
		"total": 1,
		"successful": 1,
		"skipped": 0,
		"failed": 0
	},
	"hits": {
		"total": {
			"value": 1000,
			"relation": "eq"
		},
		"max_score": null,
		"hits": []
	},
	"aggregations": {
                "timestamp-min": {
			"value": 1.664201539998E12,
			"value_as_string": "2022-09-26 14:12:19.998"
		},
		"http_method": {
			"meta": {},
			"doc_count_error_upper_bound": 0,
			"sum_other_doc_count": 0,
			"buckets": [
				{
					"key": "GET",
					"doc_count": 860,
					"filter_aggregation": {
						"meta": {},
						"buckets": [
							{
								"doc_count": 860
							}
						]
					}
				},
				{
					"key": "DELETE",
					"doc_count": 52,
					"filter_aggregation": {
						"meta": {},
						"buckets": [
							{
								"doc_count": 52
							}
						]
					}
				},
				{
					"key": "POST",
					"doc_count": 45,
					"filter_aggregation": {
						"meta": {},
						"buckets": [
							{
								"doc_count": 45
							}
						]
					}
				},
				{
					"key": "PUT",
					"doc_count": 43,
					"filter_aggregation": {
						"meta": {},
						"buckets": [
							{
								"doc_count": 43
							}
						]
					}
				}
			]
		}
	}
}
```

### Additional Details

**Plugins**
No plugins installed

**Screenshots**
-- Not applicable --

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by jed326**
### Description
Fixes a bug where `postCollection` would be called twice when a `MultiBucketCollector` is present. This was resulting in double counting the docs in the last segment for deferred bucket collectors.

### Related Issues
Resolves #14000 

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
@sohami @reta @dennisoelkers could you please take a look?

Thanks!

**Comment by dennisoelkers** [comment]
@jed326: Tested it locally and it fixes the problem. Great work! Many thanks for the quick investigation and fix, as well as providing a workaround for 2.14!

**Review by dennisoelkers — APPROVED** [review]
Fixes the problem described in #14000.

File: server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java [hunk 1]
```diff
@@ -71,10 +71,10 @@ public void processPostCollection(Collector collectorTree) throws IOException {
                     collectors.offer(innerCollector);
                 }
             } else if (currentCollector instanceof BucketCollector) {
-                ((BucketCollector) currentCollector).postCollection();
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java:74]: :+1:

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Thank you @jed326 !

File: server/src/main/java/org/opensearch/search/aggregations/bucket/BestBucketsDeferringCollector.java [hunk 2]
```diff
@@ -161,6 +162,7 @@ public void preCollection() throws IOException {
 
     @Override
     public void postCollection() throws IOException {
+        assert searchContext.searcher().getLeafContexts().isEmpty() || finished != true;
```
Comment (sohami) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/BestBucketsDeferringCollector.java:165]: Why we need first check here ?

Comment (reta) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/BestBucketsDeferringCollector.java:165]: Was curios as well, comes from constructor: `this.finished = context.searcher().getLeafContexts().isEmpty();`

**Review by reta — APPROVED** [review]

**Review by sohami — APPROVED** [review]
