### PR TITLE
Fix NPE in validateSearchableSnapshotRestorable when shard size is unavailable 

### LINKED ISSUE #19349: [BUG] NullPointerException when creating remote index from snapshot
### Describe the bug

A NullPointerException can be thrown when calculating the total size of existing shards created from remote snapshots. This appears to happen while shards are being allocated.

### Related component

Search:Searchable Snapshots

### To Reproduce

Use the `POST /_snapshot/<repository>/<snapshot>/_restore` to restore indices from multiple snapshots using `remote_snapshot` as the `storage_type` in a tight loop.

### Expected behavior

The indices are restored.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

- all defaults
- repository-s3
- prometheus-exporter

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Amazon Linux container
 - Version 3.2.0

**Additional context**

```
java.lang.NullPointerException: null
        at java.base/java.util.stream.ReferencePipeline$5$1.accept(ReferencePipeline.java:249) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215) ~[?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1716) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[?:?]
        at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:502) ~[?:?]
        at java.base/java.util.stream.LongPipeline.sum(LongPipeline.java:460) ~[?:?]
        at org.opensearch.snapshots.RestoreService$1.validateSearchableSnapshotRestorable(RestoreService.java:906) ~[opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.snapshots.RestoreService$1.execute(RestoreService.java:588) ~[opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:67) ~[opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.cluster.service.ClusterManagerService.executeTasks(ClusterManagerService.java:890) ~[opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.cluster.service.ClusterManagerService.calculateTaskOutputs(ClusterManagerService.java:441) ~[opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.cluster.service.ClusterManagerService.runTasks(ClusterManagerService.java:301) [opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.cluster.service.ClusterManagerService$Batcher.run(ClusterManagerService.java:214) [opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:206) [opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:264) [opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916) [opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:299) [opensearch-3.2.0.jar:3.2.0]
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:262) [opensearch-3.2.0.jar:3.2.0]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:1447) [?:?]
```

### PR DESCRIPTION
**Pull request by lawofcycles**
### Description
This PR fixes a NullPointerException that occurs when restoring remote snapshots when shard size information is not available in the ClusterInfo cache.

The `validateSearchableSnapshotRestorable` method in RestoreService attempts to calculate the total size of existing remote snapshot shards.
When `ClusterInfo.getShardSize()` returns null (which is valid behavior when shard size info is unavailable), the stream operation mapToLong(Long::longValue) throws a NullPointerException.

### Related Issues
Resolves #19349

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by lawofcycles** [comment]
The CI failure appears to be unrelated to my changes. The error is occurring in the Azure fixture Docker containers:
```
ERROR: for azure-fixture_azure-fixture-repositories-metering_1  cannot stop container: 
container PID is zombie and can not be killed
```

This seems to be an infrastructure/flaky test issue rather than a problem with the NPE fix in RestoreService.

File: server/src/main/java/org/opensearch/snapshots/RestoreService.java [hunk 1]
```diff
@@ -909,11 +909,27 @@ private void validateSearchableSnapshotRestorable(long totalRestorableRemoteInde
                             .routingTable()
                             .allShardsSatisfyingPredicate(isRemoteSnapshotShard);
 
-                        long totalRestoredRemoteIndexesSize = shardsIterator.getShardRoutings()
-                            .stream()
-                            .map(clusterInfo::getShardSize)
-                            .mapToLong(Long::longValue)
-                            .sum();
+                        long totalRestoredRemoteIndexesSize = 0;
```
Comment (sandeshkr419) [inline server/src/main/java/org/opensearch/snapshots/RestoreService.java]: nit: `totalRestoredRemoteIndexesSize` -> `totalRestoredRemoteIndicesSize`

**Review by sandeshkr419 — APPROVED** [review]
Thanks for fixing this.

LGTM with a small rename suggestion. Can you please address this and rebase.

File: server/src/main/java/org/opensearch/snapshots/RestoreService.java (hunk 1 above)
Comment (lawofcycles) [reply server/src/main/java/org/opensearch/snapshots/RestoreService.java]: addressed!

**Comment by lawofcycles** [comment]
Apologies for the force push confusion. I accidentally included unrelated commits while cleaning up the merge commit, which notified many code owners unnecessarily.
PR is now properly rebased, so please check for merge.
Thanks
