### PR TITLE
Disable shard/segment level search_after short cutting if track_total_hits != false

### LINKED ISSUE #9013: [BUG] Total hits value behavior change in the response when using search_after in paginated search requests
**Describe the bug**

Recently we upgraded to Opensearch 2.8.0 from 2.6.0 and noticed that a behavior change in the total hits value in the response when using search_after in paginated search requests.  In this case, there were no ongoing indexing activities (same search requests would return the same number of documents/total hits).  Once we started using search_after parameter in the search request to page through the results and came to the very last page result, if we make another search_after request using the sort value, the response returned with no documents and total hits value of 1, whereas the total hits in previous search_after responses all had the same value as in the initial search response.  In 2.6.0, total hits value remained the same even for search_after request using the sort value of the very last page result (and no documents).

We also tried upgrading to 2.9.0 and performed the same test, and found the total hits value was not only different from the initial search_after request but also different for each search_after request with the total hits value decreasing for each subsequent request.

Is this behavior an intended change?  Keep in mind, no new documents were indexed during the test.

**To Reproduce**

See description.

**Expected behavior**

Total hits value remained the same even for search_after request using the sort value of the very last page result (and no documents).

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Linux

**Additional context**

### PR DESCRIPTION
**Pull request by gashutos**
### Context
Any `_search` query return `hits.total.value` in response like mentioned in below example. Which specifies how many hits are matching actual query (sort/search_after are not part of query).

i.e, check response for below query
```
GET logs-*/_search
{
        "query": {
          "match_all": {}
        },
        "sort" : [
          {"@timestamp" : "asc"}
        ],
        "search_after": ["1998-06-01"]
}
```
Response [partial]
```
{
  "took": 25,
  "timed_out": false,
  "_shards": {
    "total": 35,
    "successful": 35,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 10000,
      "relation": "gte"
    },
    "max_score": null,
    "hits": [
      {
        "_ind
```

This `hits.total.value` is capped at `10000` max as lucene can match at max 10000 documents in results.

If you want exact match in `hits.total.value`, we need to add `track_total_hits=true` in request parameter.
i.e.
```
GET logs-*/_search?track_total_hits=true
{
        "query": {
          "match_all": {}
        },
        "sort" : [
          {"@timestamp" : "asc"}
        ],
        "search_after": ["1998-06-01"]
}
```
Response for above query [partial]
```
{
  "took": 32,
  "timed_out": false,
  "_shards": {
    "total": 35,
    "successful": 35,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 247249096,
      "relation": "eq"
    },
    "max_score": null,
    "hits": [
```
If you check, it has exact matching value `247249096` in `hits.total.value`.

Above calculation results on additional computational costs on `_search` query to track total matching hits. So for performance sensitive queries, it is recommended to provide `track_total_hits=falsle`.
i.e
```
GET logs-*/_search?track_total_hits=false
{
        "query": {
          "match_all": {}
        },
        "sort" : [
          {"@timestamp" : "asc"}
        ],
        "search_after": ["1998-06-01"]
}
```
Response from above search query [partial]
```
{
  "took": 14,
  "timed_out": false,
  "_shards": {
    "total": 35,
    "successful": 35,
    "skipped": 25,
    "failed": 0
  },
  "hits": {
    "max_score": null,
```

Default behaviour for _search queries if `track_total_hits` is not provided as request input, is track matching hits up to 10000 documents as mentioned above.

### Issue
Now with introduction of shard/segment level shortcutting [#6596] for `search_after` queries, it will skip issuing _search request for those shards/segments. So we will end up *NOT* tracking those documents hits which are matching query for that skipped shards/segmetns because of `search_after` based skipping.
This was caught in this issue. https://github.com/opensearch-project/OpenSearch/issues/9013.

### Related Issues
Resolves #9013 

### Resolution in this PR
Use `search_after` shortcutting only if `track_total_hits=false` provided.

### Additional note
There is no latency impact on _search queries even if we dont use shard/segment level skipping logic, now that we have this optimization available in Lucene itself with https://github.com/apache/lucene/pull/12334.
It will end up issuing network call for search request for that shard but lucene query will return immediately since no matching documents and there wont be any fetch phase.
yeah I agree it will end up issuing additional network calls from coordinator to shard replica hosted data nodes.

I tested with 3 nodes cluster `http_logs` with 5 indices with 5 shards each. Latencies are almost similar. So no side -effect on performance with disabling this shortcutting if track_total_hits is not false.
This is P50, units are in ms.
No difference for P90, p99 as well.

| Data Node Type.      | Sort Mode | With track_total_hits != false | track_total_hits = false |
| ----------- | ----------- | -------- | -------- |
| r6g.2xlarge  | asc with after    | 41       | 39  |
| r6g.2xlarge  | desc with after | 103        | 101 |

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gashutos** [comment]
@dblock @backslasht , when you get chance. 
Hopefuly last bug of `search_after`.

I dont understand why `hits.total.value` is not considering `search_after`. I raised the PR to keep behaviour same, but it does not make sense to return `matching` hits same in all paginated responses.
Also it is capped @`10000`.

Anyway, lets make behaviour same as it used to be before, as we dont take any latency hit after lucene fix as mentioned

File: server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java [hunk 1]
```diff
@@ -511,7 +511,12 @@ private boolean canMatchSearchAfter(LeafReaderContext ctx) throws IOException {
                     ctx,
                     primarySortField
                 );
-                return SearchService.canMatchSearchAfter(searchContext.searchAfter(), minMax, primarySortField);
+                return SearchService.canMatchSearchAfter(
+                    searchContext.searchAfter(),
+                    minMax,
+                    primarySortField,
+                    searchContext.request().source()
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java:518]:
```suggestion
searchContext.trackTotalHitsUpTo()
```

File: server/src/main/java/org/opensearch/search/SearchService.java [hunk 2]
```diff
@@ -1558,17 +1558,28 @@ private CanMatchResponse canMatch(ShardSearchRequest request, boolean checkRefre
                     canMatch = aliasFilterCanMatch;
                 }
                 final FieldDoc searchAfterFieldDoc = getSearchAfterFieldDoc(request, context);
-                canMatch = canMatch && canMatchSearchAfter(searchAfterFieldDoc, minMax, sortBuilder);
+                canMatch = canMatch && canMatchSearchAfter(searchAfterFieldDoc, minMax, sortBuilder, request.source());
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/SearchService.java:1561]: You don't need to pass whole `source()`, right? 

```suggestion
                canMatch = canMatch && canMatchSearchAfter(searchAfterFieldDoc, minMax, sortBuilder, request.source().trackTotalHitsUpTo());
```

File: server/src/main/java/org/opensearch/search/SearchService.java [hunk 3]
```diff
@@ -1597,6 +1608,10 @@ private static FieldDoc getSearchAfterFieldDoc(ShardSearchRequest request, Query
         return null;
     }
 
+    private static boolean isTrackTotalHitsDisabled(SearchSourceBuilder source) {
+        return source.trackTotalHitsUpTo() != null && source.trackTotalHitsUpTo() == SearchContext.TRACK_TOTAL_HITS_DISABLED;
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/SearchService.java:1612]:
```suggestion
        return Object.equals( rackTotalHitsUpTo, SearchContext.TRACK_TOTAL_HITS_DISABLED);
```

**Comment by reta** [comment]
@gashutos please add change log, this is a bugfix

**Comment by reta** [comment]
> I dont understand why `hits.total.value` is not considering `search_after`. I raised the PR to keep behaviour same, but it does not make sense to return `matching` hits same in all paginated responses. Also it is capped @`10000`.

I don't know the reasons as well, logically I could only find it useful when using paged navigation, so to hint how many results are in total (taking the cap into account), but that does not help much to related this number to where the one might be currently (new results before ? after? ...)

File: server/src/main/java/org/opensearch/search/SearchService.java (hunk 2 above)
Comment (gashutos) [reply server/src/main/java/org/opensearch/search/SearchService.java]: Yeah, lets just pass totalHits....

**Comment by gashutos** [comment]
> @gashutos please add change log, this is a bugfix

Makes sense

**Review by reta — APPROVED** [review]

File: server/src/main/java/org/opensearch/search/SearchService.java [hunk 4]
```diff
@@ -1558,17 +1558,28 @@ private CanMatchResponse canMatch(ShardSearchRequest request, boolean checkRefre
...
         // Check for sort.missing == null, since in case of missing values sort queries, if segment/shard's min/max
         // is out of search_after range, it still should be printed and hence we should not skip segment/shard.
-        if (searchAfter != null && minMax != null && primarySortField != null && primarySortField.missing() == null) {
+        // Skipping search on shard/segment entirely can cause mismatch on total_tracking_hits, hence skip only if
+        // track_total_hits is false.
+        if (searchAfter != null
+            && minMax != null
+            && primarySortField != null
+            && primarySortField.missing() == null
+            && Object.equals(trackTotalHitsUpto, SearchContext.TRACK_TOTAL_HITS_DISABLED)) {
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/SearchService.java:1582]:
```suggestion
            && Objects.equals(trackTotalHitsUpto, SearchContext.TRACK_TOTAL_HITS_DISABLED)) {
```

**Comment by gashutos** [comment]
> I don't know the reasons as well, logically I could only find it useful when using paged navigation, so to hint how many results are in total (taking the cap into account), but that does not help much to relate this number to where the one might be currently (new results before ? after? ...)

Yeah, `search_after` should be taken into account to let user know where they currently are in poagination instaed showing just query matched hits.

**Review by backslasht — APPROVED** [review]
We could try to optimize for ```track_total_hits``` set to 1000 (default value) as well. But, that is a topic for separate PR. This is good to go.

**Comment by reta** [comment]
@gashutos could you please do manual backport to `2.x`? than you

**Comment by gashutos** [comment]
Thanks for reviews !
@backslasht 
I opened feature requst https://github.com/opensearch-project/OpenSearch/issues/9717
If we can honor `search_after` while tracking total hits, it will be usuful for long paginated searches.

File: server/src/main/java/org/opensearch/search/SearchService.java [hunk 5]
```diff
@@ -1558,17 +1559,29 @@ private CanMatchResponse canMatch(ShardSearchRequest request, boolean checkRefre
...
         // Check for sort.missing == null, since in case of missing values sort queries, if segment/shard's min/max
         // is out of search_after range, it still should be printed and hence we should not skip segment/shard.
-        if (searchAfter != null && minMax != null && primarySortField != null && primarySortField.missing() == null) {
+        // Skipping search on shard/segment entirely can cause mismatch on total_tracking_hits, hence skip only if
+        // track_total_hits is false.
+        if (searchAfter != null
+            && minMax != null
+            && primarySortField != null
+            && primarySortField.missing() == null
+            && Objects.equals(trackTotalHitsUpto, SearchContext.TRACK_TOTAL_HITS_DISABLED)) {
```
Comment (happyjoblzp) [inline server/src/main/java/org/opensearch/search/SearchService.java:1584]: @gashutos 
Hello, I have a question. In these two scenarios：trackTotalHitsUpto=null and trackTotalHitsUpto < DEFAULT_TRACK_TOTAL_HITS_UP_TO，Is it possible to go through the optimization of shard/segment level shortcutting？

Comment (gashutos) [reply server/src/main/java/org/opensearch/search/SearchService.java:1584]: `trackTotalHitsUpto=null`
This should trigger optimization.
`trackTotalHitsUpto < DEFAULT_TRACK_TOTAL_HITS_UP_TO`
This should not.

However, We have made a fix in Lucene itself for this optimizations.
https://github.com/apache/lucene/pull/12334

With this lucene optimization, even if we have this OpenSearch shortcutting disabled, it wont spend much time in actual lucene logic and it would be up par with shortcutting.

Comment (happyjoblzp) [reply server/src/main/java/org/opensearch/search/SearchService.java:1584]: @gashutos  Tks，there may be another problem for query with ` "search_after": [null, 1000000]`; searchAfterPrimary equal null,  minMax.compareMin will throw NPE, this behaviour will not  same as before

example:

```
curl -XGET "127.0.0.1:9200/test/_search?pretty&track_total_hits=false" -H'Content-Type:application/json' -d'
{              
   "query": {                                
     "match_all": {}
   },                                        
   "sort":[{"name":{"order":"asc"}}, {"Id":{"order":"desc"}}],
   "search_after": [null, 1000000]
 }'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : null
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "can_match",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 112820878,
        "index" : "search_qingzhi",
        "node" : "127.0.0.1,51651,1711676797164",
        "reason" : {
          "type" : "null_pointer_exception",
          "reason" : null
        }
      }
    ],
    "caused_by" : {
      "type" : "null_pointer_exception",
      "reason" : null,
      "caused_by" : {
        "type" : "null_pointer_exception",
        "reason" : null
      }
    }
  },
  "status" : 500
}
```
