### PR TITLE
Fix concurrent search NPE with track_total_hits, size=0, and terminate_after

### LINKED ISSUE #10054: [Concurrent Segment Search] NPE with size and terminate_after parameters when using concurrent search
When `size=0` and `terminate_after` parameters are used in a search request and concurrent search path is used, an NPE is thrown

**To Reproduce**
This was done on `nyc_taxis` data set.

```
dev-dsk-dengjay-2b-698455fb % curl -X GET "--/_search?size=0&track_total_hits=true&pretty&terminate_after=1000000" -H 'Content-Type: application/json' -d'
{
    "query": {
        "match_all": {}
    }
}
'

{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : "Cannot invoke \"org.apache.lucene.search.CollectorManager.newCollector()\" because \"this.manager\" is null"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "nyc_taxis",
        "node" : "K7DzKxU4Tyin-01SQBj-7A",
        "reason" : {
          "type" : "null_pointer_exception",
          "reason" : "Cannot invoke \"org.apache.lucene.search.CollectorManager.newCollector()\" because \"this.manager\" is null"
        }
      }
    ],
    "caused_by" : {
      "type" : "null_pointer_exception",
      "reason" : "Cannot invoke \"org.apache.lucene.search.CollectorManager.newCollector()\" because \"this.manager\" is null",
      "caused_by" : {
        "type" : "null_pointer_exception",
        "reason" : "Cannot invoke \"org.apache.lucene.search.CollectorManager.newCollector()\" because \"this.manager\" is null"
      }
    }
  },
  "status" : 500
}

```

This was found while doing some debugging for
- https://github.com/opensearch-project/OpenSearch/issues/8371

### PR DESCRIPTION
**Pull request by jed326**
### Description
Change `EmptyTopDocsCollectorContext::createManager` to not return a null manager.

Same query no longer returns NPE:
```
curl -X GET "localhost:9200/_search?size=0&track_total_hits=true&pretty&terminate_after=1000000" -H 'Content-Type: application/json' -d'
{
    "query": {                        
        "match_all": {}                         
    }      
}                  
'  
{
  "took" : 889,
  "timed_out" : false,
  "terminated_early" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

### Related Issues
Resolves #10054 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
@reta @sohami could you help review this PR? Thanks!

File: server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java [hunk 1]
```diff
@@ -6,258 +6,24 @@
...
-        assertHitCount(searchResponse, 0L);
-
-        searchResponse = client().prepareSearch("test")
-            .setQuery(QueryBuilders.queryStringQuery("field:[2010-01-03||+2d TO 2010-01-04||+2d/d]"))
-            .get();
-        assertHitCount(searchResponse, 2L);
-    }
-
+    // TODO: Move this test to ParameterizedSimpleSearchIT after https://github.com/opensearch-project/OpenSearch/issues/8371
     public void testSimpleTerminateAfterCount() throws Exception {
```
Comment (jed326) [inline server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java:27]: I realize the diff here is quite confusing but basically I parameterized the `SimpleSearchIT` class except for this test which we know is flakey from https://github.com/opensearch-project/OpenSearch/issues/9946

As a part of the follow-up for https://github.com/opensearch-project/OpenSearch/issues/8371 I will parameterize this test as well since the flakiness should be resolved with that.

File: server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java [hunk 2]
```diff
@@ -183,7 +183,9 @@ CollectorManager<?, ReduceableSearchResult> createManager(CollectorManager<?, Re
                 );
             } else {
                 if (hitCount == -1) {
-                    if (trackTotalHitsUpTo != SearchContext.TRACK_TOTAL_HITS_ACCURATE) {
+                    if (trackTotalHitsUpTo == SearchContext.TRACK_TOTAL_HITS_ACCURATE) {
```
Comment (reta) [inline server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java:186]: This is my bad, missed that sadly :( thanks @jed326 !

**Review by reta — APPROVED** [review]

File: server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java (hunk 2 above)
Comment (sohami) [reply server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java:186]: This condition is when `track_total_hits=true` and there is `terminate_after` as well in the request. For non-concurrent case, that seem to return the relation always with `Eq` in response (See [here](https://github.com/opensearch-project/OpenSearch/pull/10082/files#diff-b8c66f0b315e7a5e88a41e8567ac0fe2d32c93175758e397078334dff4724a1cR156)). Whereas for non-concurrent case I think it will return different relation in the response (either `gte` or `eq`) depending on if request was early terminated (code ref [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/query/TotalHitCountCollectorManager.java#L75)). So we will need to handle this case by checking if track_total_hits is set to accurate or not. This is similar to the case 2 you are calling out [here](https://github.com/opensearch-project/OpenSearch/issues/8371#issuecomment-1726761922) but for size 0.

Comment (jed326) [reply server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java:186]: @sohami agreed that we should fix this behavior. I'm already planning on taking this up in the follow-up to https://github.com/opensearch-project/OpenSearch/issues/8371 (and will include a lot more testing in that change), so why don't we take up the `size=0` case in that follow-up as well?

Comment (sohami) [reply server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java:186]: fine with that. thanks!

**Review by sohami — APPROVED** [review]
