### PR TITLE
Fix missing bucket in terms aggregation with missing value

### LINKED ISSUE #17391: [BUG] Missing bucket in terms aggregation with missing value
### Describe the bug

When executing a terms aggregation with a specified missing value, the expected bucket for documents without the specified field is not appearing in the result. This is identified via an SQL IT comparing v3.0.0 alpha1 to non-alpha1 snapshot.

### Related component

_No response_

### To Reproduce

Example docs

```
{
  "_shards": {
    "total": 1,
    "failed": 0,
    "successful": 1,
    "skipped": 0
  },
  "hits": {
    "hits": [
      {
        "_index": "opensearch-sql_test_index_game_of_thrones",
        "_source": {
          "gender": "F",
          "name": {
            "ofHerName": 1,
            "firstname": "Daenerys",
            "lastname": "Targaryen"
          },
          "nickname": "Daenerys \"Stormborn\"",
          "titles": [
            "motherOfDragons",
            "queenOfTheAndals",
            "breakerOfChains",
            "Khaleesi"
          ],
          "house": "Targaryen",
          "parents": {
            "mother": "Rhaella",
            "father": "Aerys"
          }
        },
        "_id": "1",
        "_score": 1
      },
      {
        "_index": "opensearch-sql_test_index_game_of_thrones",
        "_source": {
          "gender": "M",
          "name": {
            "firstname": "Eddard",
            "ofHisName": 1,
            "lastname": "Stark"
          },
          "titles": [
            "lordOfWinterfell",
            "wardenOfTheNorth",
            "handOfTheKing"
          ],
          "house": "Stark",
          "parents": {
            "mother": "Lyarra",
            "father": "Rickard"
          }
        },
        "_id": "2",
        "_score": 1
      },
      {
        "_index": "opensearch-sql_test_index_game_of_thrones",
        "_source": {
          "gender": "M",
          "name": {
            "firstname": "Brandon",
            "ofHisName": 4,
            "lastname": "Stark"
          },
          "titles": [
            "princeOfWinterfell"
          ],
          "house": "Stark",
          "parents": {
            "mother": "Catelyn",
            "father": "Eddard"
          },
          "@wolf": "Summer"
        },
        "_id": "3",
        "_score": 1
      },
      {
        "_index": "opensearch-sql_test_index_game_of_thrones",
        "_source": {
          "gender": "M",
          "name": {
            "firstname": "Jaime",
            "ofHisName": 1,
            "lastname": "Lannister"
          },
          "titles": [
            "kingSlayer",
            "lordCommanderOfTheKingsguard",
            "Ser"
          ],
          "house": "Lannister",
          "parents": {
            "mother": "Joanna",
            "father": "Tywin"
          }
        },
        "_id": "4",
        "_score": 1
      },
      {
        "_index": "opensearch-sql_test_index_game_of_thrones",
        "_source": {
          "seat": "Dragonstone",
          "sigil": "Dragon",
          "words": "fireAndBlood",
          "hname": "Targaryen"
        },
        "_id": "5",
        "_score": 1
      },
      {
        "_index": "opensearch-sql_test_index_game_of_thrones",
        "_source": {
          "seat": "Winterfell",
          "sigil": "direwolf",
          "words": "winterIsComing",
          "hname": "Stark"
        },
        "_id": "6",
        "_score": 1
      },
      {
        "_index": "opensearch-sql_test_index_game_of_thrones",
        "_source": {
          "seat": "CasterlyRock",
          "sigil": "lion",
          "words": "hearMeRoar",
          "hname": "Lannister"
        },
        "_id": "7",
        "_score": 1
      }
    ],
    "total": {
      "value": 7,
      "relation": "eq"
    },
    "max_score": 1
  },
  "took": 57,
  "timed_out": false
}
```

Example Query 

```
{
  "from": 0,
  "size": 0,
  "_source": {
    "includes": [
      "COUNT"
    ],
    "excludes": []
  },
  "aggregations": {
    "nick": {
      "terms": {
        "field": "nickname",
        "missing": "no_nickname",
        "size": 10,
        "min_doc_count": 1,
        "shard_min_doc_count": 0,
        "show_term_doc_count_error": false,
        "order": [
          {
            "_count": "desc"
          },
          {
            "_key": "asc"
          }
        ]
      },
      "aggregations": {
        "COUNT_0": {
          "value_count": {
            "field": "_index"
          }
        }
      }
    }
  }
}
```

Example result on 3.0.0 alpha1

```
 1> Query Result:
  1> {
  1>   "_shards": {
  1>     "total": 1,
  1>     "failed": 0,
  1>     "successful": 1,
  1>     "skipped": 0
  1>   },
  1>   "hits": {
  1>     "hits": [],
  1>     "total": {
  1>       "value": 7,
  1>       "relation": "eq"
  1>     },
  1>     "max_score": null
  1>   },
  1>   "took": 78,
  1>   "timed_out": false,
  1>   "aggregations": {"nick": {
  1>     "doc_count_error_upper_bound": 0,
  1>     "sum_other_doc_count": 0,
  1>     "buckets": [
  1>       {
  1>         "COUNT(*)": {"value": 1},
  1>         "doc_count": 1,
  1>         "key": "daenerys"
  1>       },
  1>       {
  1>         "COUNT(*)": {"value": 1},
  1>         "doc_count": 1,
  1>         "key": "stormborn"
  1>       }
  1>     ]
  1>   }}
  1> }
```

### Expected behavior

Expect result (from non-alpha1)

```
    {
      "_shards": {
        "total": 1,
        "failed": 0,
        "successful": 1,
        "skipped": 0
      },
      "hits": {
        "hits": [],
        "total": {
          "value": 7,
          "relation": "eq"
        },
        "max_score": null
      },
      "took": 76,
      "timed_out": false,
      "aggregations": {"nick": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [
          {
            "COUNT(*)": {"value": 6},
            "doc_count": 6,
            "key": "no_nickname"
          },
          {
            "COUNT(*)": {"value": 1},
            "doc_count": 1,
            "key": "daenerys"
          },
          {
            "COUNT(*)": {"value": 1},
            "doc_count": 1,
            "key": "stormborn"
          }
        ]
      }}
    }
```

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by kkewwei**
Signed-off-by: kkewwei <kewei.11@bytedance.com>
Signed-off-by: kkewwei <kkewwei@163.com>

Fix missing bucket in terms aggregation with missing value

### Description
[Describe what this change achieves]

### Related Issues
Resolves #17391

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java [hunk 1]
```diff
@@ -359,7 +359,7 @@ public long getValueCount() {
 
             @Override
             public int docValueCount() {
-                return values.docValueCount();
+                return Math.max(1, values.docValueCount());
```
Comment (kkewwei) [inline server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java:362]: I prefer to fix in `MissingValues`, not in `GlobalOrdinalsStringTermsAggregator`, `MissingValues` ​​may also be called from other places.

File: CHANGELOG.md [hunk 2]
```diff
@@ -37,6 +37,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 - Add highlighting for wildcard search on `match_only_text` field ([#17101](https://github.com/opensearch-project/OpenSearch/pull/17101))
 - Fix illegal argument exception when creating a PIT ([#16781](https://github.com/opensearch-project/OpenSearch/pull/16781))
 - Fix HTTP API calls that hang with 'Accept-Encoding: zstd' ([#17408](https://github.com/opensearch-project/OpenSearch/pull/17408))
+- Fix missing bucket in terms aggregation with missing value ([#17418](https://github.com/opensearch-project/OpenSearch/pull/17418))
```
Comment (andrross) [inline CHANGELOG.md:40]: This needs to be in CHANGELOG-3.0.md since this is a fix specific for the 3.0 update.

**Review by andrross — COMMENTED** [review]
Thanks @kkewwei!

Are there other places where the logical change in GlobalOrdinalsStringTermsAggregator might cause problems?

**Comment by kkewwei** [comment]
> Thanks @kkewwei!
> 
> Are there other places where the logical change in GlobalOrdinalsStringTermsAggregator might cause problems?

We just change three same code in #7c46f8f14e1beefdd24eb2fe61792c6737fe9023, I think it will not cause other problems.

**Review by andrross — APPROVED** [review]

**Review by noCharger — COMMENTED** [review]
Can we add another case where field is in text but has two words?

**Comment by andrross** [comment]
> Can we add another case where field is in text but has two words?

@noCharger The test that was added here failed for the text case without the fix so I think it probably gives sufficient coverage.
