### PR TITLE
Fix flaky testMinScoreDisablesCountOptimization in query profile phase tests

### LINKED ISSUE #10518: [BUG] Flaky test: org.opensearch.search.query.QueryProfilePhaseTests.testMinScoreDisablesCountOptimization
**Describe the bug**
QueryProfilePhaseTests.testMinScoreDisablesCountOptimization is flaky. See [this CI failure](https://build.ci.opensearch.org/job/gradle-check/27451/testReport/junit/org.opensearch.search.query/QueryProfilePhaseTests/testMaxScore__p0_5_p1_org_opensearch_search_query_ConcurrentQueryPhaseSearcher_5d1a859c_/).

**To Reproduce**
Run `./gradlew ':server:test' --tests "org.opensearch.search.query.QueryProfilePhaseTests"`

**Expected behavior**
Test should succeed when run.

**Additional context**
Found through failed Jenkins build, reproduced on main branch.

### PR DESCRIPTION
**Pull request by ticheng-aws**
### Description
This flaky test uses [min_score](https://opensearch.org/docs/latest/query-dsl/compound/function-score/#filtering-documents-that-dont-meet-a-threshold) to filter documents. Documents with lower score are excluded from the search results, but it still makes sense to include the actual score time and count in the profile response. As a result, the score time_in_nanos should not always be greater than or equal to `100`, and we need to revise the test accordingly. I run the new changes 1000+ times to make sure that they all passed.

### Related Issues
Resolves #10518

### Check List
- [ ] ~New functionality includes testing.~
  - [X] All tests pass
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [ ] ~Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- [X] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

File: server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java [hunk 1]
```diff
@@ -336,12 +336,12 @@ public void testMinScoreDisablesCountOptimization() throws Exception {
         assertEquals(TotalHits.Relation.EQUAL_TO, context.queryResult().topDocs().topDocs.totalHits.relation);
         assertProfileData(context, "MatchAllDocsQuery", query -> {
             assertThat(query.getTimeBreakdown().keySet(), not(empty()));
-            assertThat(query.getTimeBreakdown().get("score"), greaterThanOrEqualTo(100L));
+            assertThat(query.getTimeBreakdown().get("score"), greaterThanOrEqualTo(1L));
```
Comment (jed326) [inline server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java:339]: It's not clear to me how `1L` vs `100L` was determined. If we're just testing if this is a positive number should we just use `0L`?

File: server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java [hunk 2]
```diff
@@ -336,12 +336,12 @@ public void testMinScoreDisablesCountOptimization() throws Exception {
...
             assertThat(query.getTimeBreakdown().get("score_count"), equalTo(1L));
             if (executor != null) {
-                assertThat(query.getTimeBreakdown().get("max_score"), greaterThanOrEqualTo(100L));
-                assertThat(query.getTimeBreakdown().get("min_score"), greaterThanOrEqualTo(100L));
-                assertThat(query.getTimeBreakdown().get("avg_score"), greaterThanOrEqualTo(100L));
+                assertThat(query.getTimeBreakdown().get("max_score"), greaterThanOrEqualTo(1L));
+                assertThat(query.getTimeBreakdown().get("min_score"), greaterThanOrEqualTo(1L));
+                assertThat(query.getTimeBreakdown().get("avg_score"), greaterThanOrEqualTo(1L));
```
Comment (jed326) [inline server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java:344]: Maybe we should check `min <= avg <= max` instead?

File: server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java (hunk 1 above)
Comment (ticheng-aws) [reply server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java:339]: Hey @jed326, thanks for the review. This test uses `RandomIndexWriter` to add random number of documents to the search index, so we expect varying score time in nanos here. A `0L` score time is not anticipated in this test because we expect the score count to be equal to 1 below.

File: server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java (hunk 2 above)
Comment (ticheng-aws) [reply server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java:344]: Only checking `min <= avg <= max` is insufficient here. We must ensure that they have positive values.

**Review by sohami — APPROVED** [review]
