### PR TITLE
Fix checkpoint handling to prevent segment replication infinite loop

### LINKED ISSUE #18605: [BUG] Infinite loop of S3 GET/LIST requests during segment replication recovery after node loss/restart
### Describe the bug

After S3 remote-backed storage was fixed in v3, we enabled it with segment replication. After doing so, we noticed our OpenSearch cluster began issuing millions of S3 ListObjectsV2 and GetObject requests per hour to the configured S3 bucket.

This behavior appears pathological and triggered only after the shutdown of one OpenSearch node, leading to:

- Persistent get and list requests to the `/<index_uuid>/0/segments/metadata/metadata` prefixes across all indices
- Sustained high CPU usage on one surviving node (likely due to the looping requests)

This causes a HUGE spike in cluster costs ($1,000+ / month) even for our very small dataset (<100MB) since over the course of a month this has generated 200M requests to S3 (and we got fairly lucky since this fortunately wasn't occurring all the time ):

Image

In our debugging, here is what we have observed:

- This behavior is not observed during normal operations, only when a node is lost. 
- It doesn't appear to matter whether the lost node is a leader or follower.
- In a three-node cluster, will only impacts one of the remaining two nodes.
- It doesn't occur all the time (~25% incident rate for us).
- The issue cannot be fixed without deleting the malfunctioning node.
- Oddly, the cluster itself appears to be functioning fine even while this is occurring -- even for indices with shards on the degenerate node.

### Related component

Storage:Remote

### To Reproduce

1. Deploy a 3-node opensearch cluster on kubernetes using these `opensearch.yml` settings:
   
  ```yaml
  "cluster.allocator.existing_shards_allocator.batch_enabled": true
  "cluster.indices.replication.strategy": "SEGMENT"
  "cluster.initial_cluster_manager_nodes":
    - "opensearch-7d0b-0"
    - "opensearch-7d0b-1"
    - "opensearch-7d0b-2"
  "cluster.name": "opensearch-7d0b"
  "cluster.remote_store.publication.enabled": true
  "cluster.remote_store.routing_table.path.prefix": "routing/"
  "cluster.remote_store.state.enabled": true
  "cluster.remote_store.state.path.prefix": "state/"
  "cluster.routing.allocation.balance.prefer_primary": true
  "cluster.routing.allocation.disk.watermark.high": "90%"
  "cluster.routing.allocation.shard_movement_strategy": "PRIMARY_FIRST"
  "discovery.seed_hosts":
    - "opensearch-7d0b-headless"
  "indices.recovery.max_bytes_per_sec": "0mb"
  "logger._root": "WARN"
  "logger.org.opensearch.alerting.util.destinationmigration.DestinationMigrationCoordinator": "WARN"
  "network.host": "0.0.0.0"
  "node.attr.remote_store.repository.s3.settings.bucket": "default-opensearch-7d0b-storage-15cf133175f73b63"
  "node.attr.remote_store.repository.s3.settings.region": "us-east-2"
  "node.attr.remote_store.repository.s3.type": "s3"
  "node.attr.remote_store.routing_table.repository": "s3"
  "node.attr.remote_store.segment.repository": "s3"
  "node.attr.remote_store.state.repository": "s3"
  "node.attr.remote_store.translog.repository": "s3"
  "node.roles":
    - "cluster_manager"
    - "ingest"
    - "data"
    - "remote_cluster_client"
  "s3.client.default.endpoint": "s3.us-east-2.amazonaws.com"
  "s3.client.default.region": "us-east-2"
  "segrep.pressure.enabled": true
  ```

2. Launch each node with the following bash script:

```bash
#!/usr/bin/env bash

set -euo pipefail
./bin/opensearch-plugin install -b repository-s3

echo "$AWS_ACCESS_KEY_ID" | ./bin/opensearch-keystore add --stdin --force s3.client.default.access_key
echo "$AWS_SECRET_ACCESS_KEY" | ./bin/opensearch-keystore add --stdin --force s3.client.default.secret_key

# Set JVM heap size dynamically to 50% of container memory request
HEAP_SIZE=$((CONTAINER_MEMORY_REQUEST / 2000000))
export OPENSEACH_JAVA_OPTS="-Xmx${HEAP_SIZE}M -Xms${HEAP_SIZE}M --enable-native-access=ALL-UNNAMED"

./bin/opensearch \
  -Enode.name="$POD_NAME" \
  -Eplugins.query.datasources.encryption.masterkey="$OPENSEARCH_MASTER_KEY"
```

3. Deploy the demo data that comes with the OpenSearch Dashboard
 
4. Restart a node (doesn't occur every restart -- looks to occur 25% of the time for us).

### Expected behavior

The infinite loop of requests should not occur.

### Additional Details

**Plugins**

- repository-s3

**Screenshots**

Image

**Host/Environment (please complete the following information):**
 - Environment: AWS EKS 1.30
 - OS: Bottlerocket 
 - Version: 3.0.0

**Additional context**

Count of the list requests that occurred in a single minute based on the CloudTrail events logs:

```
   1220 1vO1bkUERFWvJp2p9vNo9w/0/segments/metadata/metadata
   1195 eFMZ2857RDKzqWOKoEhjmg/0/segments/metadata/metadata
   1166 LZcXfsUHQoOfZ-VAe82Smw/0/segments/metadata/metadata
   1142 UZA4K5ruT-Opx6EmbOKbvg/0/segments/metadata/metadata
   1138 TaxiBYmZS4ypJ2DrGdxZEw/0/segments/metadata/metadata
   1105 NlAaRqFzRku2H2A7ABCYlA/0/segments/metadata/metadata
   1088 EkPLvxHwTZOWIWkS6_UgEA/0/segments/metadata/metadata
   1077 tJPUeD9ESA6X1XsPZxUxcg/0/segments/metadata/metadata
   1068 04mQ2jgvSMejOlTaUB9k6Q/0/segments/metadata/metadata
   1050 OJMqg9FsSy2m76o3vxZvVQ/0/segments/metadata/metadata
```

I also capture all the DEBUG logs across the entire cluster during a 5-minute segment when this issue occurred. Due to the insane amount of requests, the log file is quite large (2GB): [log file](https://drive.google.com/file/d/1G3NQGAK0VlJPU_kM8dc00CWWcG3m__uc/view?usp=sharing).

### PR DESCRIPTION
**Pull request by ashking94**
### Description
This fixes an issue in segrep flow which causes infinite segrep loop. The analysis is present in the issue - https://github.com/opensearch-project/OpenSearch/issues/18605. 

### Related Issues
Resolves #18605

### Check List
- [x] Functionality includes testing.
- ~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ashking94** [comment]
I have not been able to repro the issue in ITs. I have tried reproducing it, will try to understand why doesn't it happen on local.

File: server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java [hunk 1]
```diff
@@ -625,6 +625,7 @@ public void testStartReplicationListenerSuccess() throws InterruptedException {
 
         latch.await(2, TimeUnit.SECONDS);
         verify(spy, (atLeastOnce())).updateVisibleCheckpoint(eq(0L), eq(replicaShard));
+        verify(spy, times(1)).processLatestReceivedCheckpoint(any(), any());
```
Comment (ashking94) [inline server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java:628]: This test fails without the above code change all the time.

**Comment by ashking94** [comment]
> I have not been able to repro the issue in ITs. I have tried reproducing it, will try to understand why doesn't it happen on local.

I was able to modify an unit test that was showing the behaviour where the cyclic loop of segrep is seen always. 

```
REPRODUCE WITH: ./gradlew 'null' --tests 'org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testStartReplicationListenerSuccess' -Dtests.seed=B17175E6A29DDE01 -Dtests.locale=bg-Cyrl-BG -Dtests.timezone=Europe/Vatican -Druntime.java=21

org.mockito.exceptions.verification.TooManyActualInvocations: 
segmentReplicationTargetService.processLatestReceivedCheckpoint(
    <any>,
    <any>
);
Wanted 1 time:
-> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testStartReplicationListenerSuccess(SegmentReplicationTargetServiceTests.java:628)
But was 27 times:
-> at org.opensearch.indices.replication.SegmentReplicationTargetService.afterIndexShardStarted(SegmentReplicationTargetService.java:235)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)
-> at org.opensearch.indices.replication.SegmentReplicationTargetService$1.onReplicationDone(SegmentReplicationTargetService.java:351)

```

**Review by sachinpkale — APPROVED** [review]

**Comment by ashking94** [comment]
@mch2 I have tried making the above change which should fix the recursion loop. Do review if you can.

**Review by mch2 — APPROVED** [review]

**Comment by ashking94** [comment]
I have run following tests for 1000+ iterations and have not seen any single failure:
 - PublishCheckpointActionTests
 - SegmentReplicationTargetServiceTests
 - SegmentReplicationIT

**Comment by ashking94** [comment]
Raised manual backport for 2.19 minor version releases - https://github.com/opensearch-project/OpenSearch/pull/18677.

**Comment by ashking94** [comment]
It appears that the test `org.opensearch.indices.replication.SegmentReplicationIT.testNodeDropWithOngoingReplication` may have become flaky as I saw a test failure in random iterations run. I will fix the same.

**Comment by fullykubed** [comment]
@ashking94 @gbbafna Not sure what the policy here is, but is it possible to cut a new patch release for the backported version channels now that this is merged? This bug unfortunately makes remote storage functionally unusable, and it would be nice to make it usable again.

**Comment by ashking94** [comment]
@fullykubed This change has been backported to 2.19 and should be released as part of 2.19.3. You can refer the schedule of planned releases at https://opensearch.org/releases/.

**Comment by fullykubed** [comment]
@ashking94 Got it! Thanks for the clarification.

To confirm, no plans to backport this to 3.x release branches?

**Comment by ashking94** [comment]
AFAIK, I dont think there are any planned releases for 3.x.x minor/patch versions. The fix will be released in 3.2.0 which is scheduled to be released around August 19th, 2025.
