### PR TITLE
[Remote Store] Fix stats reporting for multistream downloads.

### LINKED ISSUE #10283: [Repository] Report proper statistics for multistream downloads
Multistream downloads should be properly reflected in download statistics.

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR reports stats for multistream downloads. With addition of copyTo() in [PR](https://github.com/opensearch-project/OpenSearch/pull/9710/files#diff-f57628264c235a133d2d6db458404e07a43f18026e40ed5e956536c03add9925) proper stats are no longer reported. This PR fixes the issue and reports proper stats.

### Related Issues
Resolves #10283

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] GitHub issue/PR created in [OpenSearch documentation repo](https://github.com/opensearch-project/documentation-website) for the required public documentation changes (#[Issue/PR number])

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Rishikesh1159** [comment]
This PR fixes the stats reporting for multistream downloads. I have tested the working of fix by following testing:

Testing:
-> Created a cluster with remote store enabled and repository registered.
-> Ingested some data and call `_remotestore/stats` api to get download stats.

-> Without this PR fix (download stats are empty for replicas):
```
{
 "_shards" : {
  "total" : 2,
  "successful" : 2,
  "failed" : 0
 },
 "indices" : {
  "nyc_taxis" : {
   "shards" : {
    "0" : [
     {
      "routing" : {
       "state" : "STARTED",
       "primary" : true,
       "node" : "eGJVITx2QAmhJ0Y6ywgKvw"
      },
      "segment" : {
       "download" : { },
       "upload" : {
        "local_refresh_timestamp_in_millis" : 1696445223665,
        "remote_refresh_timestamp_in_millis" : 1696445223665,
        "refresh_time_lag_in_millis" : 0,
        "refresh_lag" : 0,
        "bytes_lag" : 0,
        "backpressure_rejection_count" : 0,
        "consecutive_failure_count" : 0,
        "total_uploads" : {
         "started" : 129,
         "succeeded" : 129,
         "failed" : 0
        },
        "total_upload_size" : {
         "started_bytes" : 3756462697,
         "succeeded_bytes" : 3756462697,
         "failed_bytes" : 0
        },
        "remote_refresh_size_in_bytes" : {
         "last_successful" : 0,
         "moving_avg" : 7.698216395E7
        },
        "upload_speed_in_bytes_per_sec" : {
         "moving_avg" : 4.59313421E7
        },
        "remote_refresh_latency_in_millis" : {
         "moving_avg" : 829.4
        }
       }
      },
      "translog" : {
       "upload" : {
        "last_successful_upload_timestamp" : 1696445164677,
        "total_uploads" : {
         "started" : 554,
         "failed" : 0,
         "succeeded" : 554
        },
        "total_upload_size" : {
         "started_bytes" : 3308030813,
         "failed_bytes" : 0,
         "succeeded_bytes" : 3308030813
        },
        "total_upload_time_in_millis" : 209010433,
        "upload_size_in_bytes" : {
         "moving_avg" : 5061984.05
        },
        "upload_speed_in_bytes_per_sec" : {
         "moving_avg" : 7328.3
        },
        "upload_time_in_millis" : {
         "moving_avg" : 715100.5
        }
       },
       "download" : { }
      }
     },
     {
      "routing" : {
       "state" : "STARTED",
       "primary" : false,
       "node" : "W7neivyKQpiIxwffoZCXrw"
      },
      "segment" : {
       "download" : { },
       "upload" : { }
      },
      "translog" : {
       "upload" : { },
       "download" : { }
      }
     }
    ]
   }
  }
 }
}
```

-> With this PR fix (download stats for replica are reported):

```
curl localhost:9200/_remotestore/stats/nyc_taxis?pretty
{
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "indices" : {
    "nyc_taxis" : {
      "shards" : {
        "0" : [
          {
            "routing" : {
              "state" : "STARTED",
              "primary" : true,
              "node" : "2C-7q8IkR4aM4N1Uj1jsJA"
            },
            "segment" : {
              "download" : { },
              "upload" : {
                "local_refresh_timestamp_in_millis" : 1696446555174,
                "remote_refresh_timestamp_in_millis" : 1696446555174,
                "refresh_time_lag_in_millis" : 0,
                "refresh_lag" : 0,
                "bytes_lag" : 0,
                "backpressure_rejection_count" : 0,
                "consecutive_failure_count" : 0,
                "total_uploads" : {
                  "started" : 103,
                  "succeeded" : 103,
                  "failed" : 0
                },
                "total_upload_size" : {
                  "started_bytes" : 2589972453,
                  "succeeded_bytes" : 2589972453,
                  "failed_bytes" : 0
                },
                "remote_refresh_size_in_bytes" : {
                  "last_successful" : 0,
                  "moving_avg" : 5.309439115E7
                },
                "upload_speed_in_bytes_per_sec" : {
                  "moving_avg" : 4.399847085E7
                },
                "remote_refresh_latency_in_millis" : {
                  "moving_avg" : 822.1
                }
              }
            },
            "translog" : {
              "upload" : {
                "last_successful_upload_timestamp" : 1696446532704,
                "total_uploads" : {
                  "started" : 431,
                  "failed" : 0,
                  "succeeded" : 431
                },
                "total_upload_size" : {
                  "started_bytes" : 2596014317,
                  "failed_bytes" : 0,
                  "succeeded_bytes" : 2596014317
                },
                "total_upload_time_in_millis" : 127155781,
                "upload_size_in_bytes" : {
                  "moving_avg" : 5638599.25
                },
                "upload_speed_in_bytes_per_sec" : {
                  "moving_avg" : 10546.45
                },
                "upload_time_in_millis" : {
                  "moving_avg" : 536076.7
                }
              },
              "download" : { }
            }
          },
          {
            "routing" : {
              "state" : "STARTED",
              "primary" : false,
              "node" : "y6DkskhCRECaNG2zq2rF5A"
            },
            "segment" : {
              "download" : {
                "last_sync_timestamp" : 1696446709535,
                "total_download_size" : {
                  "started_bytes" : 2161626590,
                  "succeeded_bytes" : 2161626590,
                  "failed_bytes" : 0
                },
                "download_size_in_bytes" : {
                  "last_successful" : 337,
                  "moving_avg" : 1.18097258E7
                },
                "download_speed_in_bytes_per_sec" : {
                  "moving_avg" : 1.31509003E7
                }
              },
              "upload" : { }
            },
            "translog" : {
              "upload" : { },
              "download" : { }
            }
          }
        ]
      }
    }
  }
}
```

File: server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java [hunk 1]
```diff
@@ -489,28 +489,48 @@ public void copyFrom(Directory from, String src, IOContext context, ActionListen
...
         final String blobName = getExistingRemoteFilename(source);
         if (destinationPath != null && remoteDataDirectory.getBlobContainer() instanceof AsyncMultiStreamBlobContainer) {
+            long length = 0L;
+            try {
+                length = fileLength(source);
+            } catch (IOException ex) {
+                logger.error("Unable to fetch segment length for stats tracking", ex);
+            }
+            final long fileLength = length;
+            final long startTime = System.currentTimeMillis();
```
Comment (Bukhtawar) [inline server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java:508]: Please use nano time for measuring elapsed time

Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java:508]: Sure I will update this

File: server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java [hunk 2]
```diff
@@ -489,28 +489,48 @@ public void copyFrom(Directory from, String src, IOContext context, ActionListen
      * @param destinationPath The destination path (if multipart is supported)
      * @param fileCompletionListener The listener to notify of completion
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java:490]: Please add documentation for `@param tracker`

File: server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java [hunk 3]
```diff
@@ -489,28 +489,48 @@ public void copyFrom(Directory from, String src, IOContext context, ActionListen
...
      */
-    public void copyTo(String source, Directory destinationDirectory, Path destinationPath, ActionListener<String> fileCompletionListener) {
+    public void copyTo(
+        String source,
+        Directory destinationDirectory,
+        Path destinationPath,
+        DirectoryFileTransferTracker tracker,
```
Comment (kotwanikunal) [inline server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java:496]: nit: lets rename all instances to `fileTransferTracker`

File: server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java (hunk 1 above)
Comment (andrross) [reply server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java:508]: Let's stick with using the wall clock here in this PR since it is baked into the class already. @Rishikesh1159 can you take #10407 as a follow up to refactor after this PR?

File: server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java [hunk 4]
```diff
@@ -489,28 +489,48 @@ public void copyFrom(Directory from, String src, IOContext context, ActionListen
...
+        ActionListener<String> fileCompletionListener
+    ) {
         final String blobName = getExistingRemoteFilename(source);
         if (destinationPath != null && remoteDataDirectory.getBlobContainer() instanceof AsyncMultiStreamBlobContainer) {
+            long length = 0L;
+            try {
+                length = fileLength(source);
```
Comment (andrross) [inline server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java:503]: This makes a remote call to the repository to fetch the file length. I _think_ we actually already know the file length before making this call. Can we wire in the length instead of doing a remote call to fetch it?

Comment (kotwanikunal) [reply server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java:503]: The method does that for us. It tries to use the cached value from the metadata map before making the network call. 
We can prevent it all together too though - that was the initial logic that we had, but this seemed better suited to report true stats.

File: server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java (hunk 1 above)
Comment (Rishikesh1159) [reply server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java:508]: Sure I will take #10407 as follow up.

**Review by kotwanikunal — APPROVED** [review]
