### PR TITLE
Segment Replication stats throwing NPE when shards are unassigned or are in delayed allocation phase

### LINKED ISSUE #11945: [BUG] Segment Replication stats throwing NPE when shards are unassigned or are in delayed allocation phase
### Describe the bug

We are seeing NPEs coming up from the NodesStats API when there are nodes data nodes dropping out of the cluster because of resource constraints. NodesStats API fired at that point of time when there are shards getting unassigned from the data nodes (because of data nodes leaving the cluster), fails with this error:

```
java.lang.NullPointerException: Cannot invoke "org.opensearch.cluster.routing.AllocationId.getId()" because the return value of "org.opensearch.cluster.routing.ShardRouting.allocationId()" is null
    at org.opensearch.index.seqno.ReplicationTracker.lambda$isPrimaryRelocation$18(ReplicationTracker.java:1246)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
    at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
    at org.opensearch.index.seqno.ReplicationTracker.isPrimaryRelocation(ReplicationTracker.java:1247)
    at org.opensearch.index.seqno.ReplicationTracker.lambda$getSegmentReplicationStats$23(ReplicationTracker.java:1318)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
    at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at org.opensearch.index.seqno.ReplicationTracker.getSegmentReplicationStats(ReplicationTracker.java:1321)
    at org.opensearch.index.shard.IndexShard.getReplicationStatsForTrackedReplicas(IndexShard.java:3120)
    at org.opensearch.index.shard.IndexShard.getReplicationStats(IndexShard.java:3125)
    at org.opensearch.index.shard.IndexShard.segmentStats(IndexShard.java:1500)
    at org.opensearch.action.admin.indices.stats.CommonStats.<init>(CommonStats.java:228)
    at org.opensearch.action.admin.indices.stats.TransportIndicesStatsAction.shardOperation(TransportIndicesStatsAction.java:146)
    at org.opensearch.action.admin.indices.stats.TransportIndicesStatsAction.shardOperation(TransportIndicesStatsAction.java:66)
    at org.opensearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.onShardOperation(TransportBroadcastByNodeAction.java:495)
    at org.opensearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:469)
    at org.opensearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:456)
    at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceivedDecorate(SecuritySSLRequestHandler.java:224)
    at org.opensearch.security.transport.SecurityRequestHandler.messageReceivedDecorate(SecurityRequestHandler.java:323)
    at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceived(SecuritySSLRequestHandler.java:172)
    at org.opensearch.security.OpenSearchSecurityPlugin$6$1.messageReceived(OpenSearchSecurityPlugin.java:797)
    at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:113)
    at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43)
    at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106)
    at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:471)
    at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917)
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

This seems to be coming up from the SegmentReplicationStats code, specifically from this code block which tries to detect if a primary shard is being relocated by cross checking the current `allocationId` with all the `allocationIds` from the shard routing table.

https://github.com/opensearch-project/OpenSearch/blob/774e7d41b5ab146f3316eab667b54efe9b16aa33/server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java#L1233-L1239

### Related component

Storage

### To Reproduce

N/A

### Expected behavior

NodesStats API should not fail even during transient data node drops

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by rampreeth**
### Description
Fixes segment Replication stats throwing NPE when shards are unassigned or are in delayed allocation phase

### Related Issues
Resolves #11945

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — DISMISSED** [review]
Thanks for submitting this change, however, I am sure this won't fix the problem since the allocation id is a nullable value. [1]  Maybe start by editing/creating a unit test that can reproduce the issue in ReplicationTrackerTests.java [2]

- [1] 
https://github.com/opensearch-project/OpenSearch/blob/d9e9944670ffc02dfef6c6a5e50dabd14779b67a/server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java#L271-L274

- [2] https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java

**Comment by rampreeth** [comment]
Thanks for the pointers @peternied. I'll take a look at this.

**Comment by peternied** [comment]
@rampreeth Nice - this looks much better; however, I'm not going to be the right person to review this.  @mch2 Can you help find someone to review this contribution?

**Comment by rampreeth** [comment]
Hi @peternied , just wanted to check if an entry needs to be added for this change in the changelog? Currently, the failure is due to that. Since this is a user-facing bug, we would need one? 

 @mch2 , please do help with reviewing this change. Thanks.

**Comment by mch2** [comment]
> Hi @peternied , just wanted to check if an entry needs to be added for this change in the changelog? Currently, the failure is due to that. Since this is a user-facing bug, we would need one?
> 
> @mch2 , please do help with reviewing this change. Thanks.

Thanks for the fix @rampreeth this looks good.  assignedShards will include the target relocating shard that should always have an allocationId according to the [routing table](https://github.com/opensearch-project/OpenSearch/blob/1084ba9b167af8342be0acea075c83fa1673dcb1/server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java#L136).

File: server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java [hunk 1]
```diff
@@ -1252,7 +1252,7 @@ public ReplicationCheckpoint getLatestReplicationCheckpoint() {
     }
 
     private boolean isPrimaryRelocation(String allocationId) {
-        Optional<ShardRouting> shardRouting = routingTable.shards()
+        Optional<ShardRouting> shardRouting = routingTable.assignedShards()
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java:1255]: a nitpick, we can simplify this function a bit and still include the null check to be defensive...

```java
    private boolean isPrimaryRelocation(String allocationId) {
        return routingTable.assignedShards()
            .stream()
            .filter(routing -> Objects.nonNull(routing.allocationId()))
            .filter(routing -> routing.allocationId().getId().equals(allocationId))
            .anyMatch(ShardRouting::primary);
    }
```

**Review by mch2 — APPROVED** [review]

File: server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java [hunk 2]
```diff
@@ -1214,7 +1214,9 @@ public void testPeerRecoveryRetentionLeaseCreationAndRenewal() {
         IndexShardRoutingTable.Builder routingTableBuilder = new IndexShardRoutingTable.Builder(routingTable);
         for (ShardRouting replicaShard : routingTable.replicaShards()) {
             routingTableBuilder.removeShard(replicaShard);
-            routingTableBuilder.addShard(replicaShard.moveToStarted());
+            if (replicaShard.assignedToNode()) {
```
Comment (mch2) [inline server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java:1217]: I'd expect this to impact other tests, does it not?

Comment (rampreeth) [reply server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java:1217]: In all of the other tests, the replica shards are always assigned to a node, so the existing tests are passing.

**Comment by rampreeth** [comment]
> just wanted to check if an entry needs to be added for this change in the changelog? Currently, the failure is due to that. Since this is a user-facing bug, we would need one?

Thanks for the review. @mch2 , could you also please let me know regarding the above?

**Comment by mch2** [comment]
> > just wanted to check if an entry needs to be added for this change in the changelog? Currently, the failure is due to that. Since this is a user-facing bug, we would need one?
> 
> 
> 
> Thanks for the review. @mch2 , could you also please let me know regarding the above?

Yes you're right it is user facing so let's please add a changelog entry under unreleased 2.x.

**Comment by rampreeth** [comment]
@mch2 , thanks. I have made the necessary changes. Could you please provide an approval again?

**Review by mch2 — APPROVED** [review]

**Comment by mch2** [comment]
gradle check doesn't appear to be running, https://build.ci.opensearch.org/job/gradle-check/42261/console just gives a blank page.  Will retry it again

**Comment by rampreeth** [comment]
> gradle check doesn't appear to be running, https://build.ci.opensearch.org/job/gradle-check/42261/console just gives a blank page. Will retry it again

@mch2 , I still see the gradle check is failing. Is there some other issue?

**Comment by mch2** [comment]
> > gradle check doesn't appear to be running, https://build.ci.opensearch.org/job/gradle-check/42261/console just gives a blank page. Will retry it again
> 
> @mch2 , I still see the gradle check is failing. Is there some other issue?

Yes this is unrelated to your change.  

From jenkins - https://build.ci.opensearch.org/blue/organizations/jenkins/gradle-check/detail/gradle-check/42368/pipeline
```
java.io.FileNotFoundException: /var/jenkins_home/jobs/gradle-check/builds/42368/log (No such file or directory)
```

Going to try closing/re-opening the pr.

**Comment by rampreeth** [comment]
Looks like some other tests are [failing](https://build.ci.opensearch.org/job/gradle-check/42450/console), seems to be related to my change, will fix that

**Comment by mch2** [comment]
> Looks like some other tests are [failing](https://build.ci.opensearch.org/job/gradle-check/42450/console), seems to be related to my change, will fix that

Are you able to repro this locally? `isPrimaryRelocation` is only invoked when fetching stats for segrep, i'd be surprised if this is related to those failures?

**Comment by rampreeth** [comment]
> > Looks like some other tests are [failing](https://build.ci.opensearch.org/job/gradle-check/42450/console), seems to be related to my change, will fix that
> 
> Are you able to repro this locally? `isPrimaryRelocation` is only invoked when fetching stats for segrep, i'd be surprised if this is related to those failures?

Yes, I'm able to repro it locally. The other tests are failing due to addition of an unassigned shard in the routing table.

**Comment by rampreeth** [comment]
Hi @mch2 , please review this again. Tests seem to be running fine now.

**Comment by rampreeth** [comment]
Hi @mch2 , gentle reminder to review this

File: server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTestCase.java [hunk 3]
```diff
@@ -104,13 +104,22 @@ static String nodeIdFromAllocationId(final AllocationId allocationId) {
     }
 
     static IndexShardRoutingTable routingTable(final Set<AllocationId> initializingIds, final AllocationId primaryId) {
-        return routingTable(initializingIds, Collections.singleton(primaryId), primaryId);
+        return routingTable(initializingIds, Collections.singleton(primaryId), primaryId, false);
```
[the remark this answers is not in the document]
Comment (rampreeth) [reply server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTestCase.java:107]: Will make that change

**Comment by shourya035** [comment]
@rampreeth Let us know if you are blocked on this. I see that @mch2 has left some comments.

**Comment by rampreeth** [comment]
@shourya035 , I didn't get a chance to address the comments, will be doing that this week

**Review by mch2 — APPROVED** [review]

**Comment by mch2** [comment]
Thanks for the fix @rampreeth, FYI @vinaykpud is working on a change to simplify segrep stats by pushing the computation to the replicas - https://github.com/opensearch-project/OpenSearch/pull/17055.

**Comment by rampreeth** [comment]
> Thanks for the fix @rampreeth, FYI @vinaykpud is working on a change to simplify segrep stats by pushing the computation to the replicas - #17055.

Got it. Thanks @mch2 for the review.

**Comment by sachinpkale** [comment]
@rampreeth Please update the PR description

**Comment by rampreeth** [comment]
@sachinpkale , would you be able to merge the PR?
