### PR TITLE
[Segment Replication] Prevent store clean up post reader close and refactor

### LINKED ISSUE #8286: [BUG] [Segment Replication] replica fails after write some data
**Describe the bug**
Replica shard fails with segment replication enabled.
I have a cluster with 2 nodes, OpenSearch 2.8.0

**To Reproduce**
1. create index
```
PUT my-index1
{
  "settings": {
    "number_of_shards": 3, 
    "index": {
      "replication.type": "SEGMENT"
    }
  }
}
```
2. enable balanced primary  allocation and backpressure
```
PUT _cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.balance.prefer_primary": true,
    "segrep.pressure.enabled": true
  }
}
```
4. use `_bulk` API send data to `my-index1`
5. replica fails, see error attached
[stack.txt](https://github.com/opensearch-project/OpenSearch/files/11881526/stack.txt)

6. cluster allocation explain
```
shard has exceeded the maximum number of retries [5] on failed allocation attempts - manually call [/_cluster/reroute?retry_failed=true] to retry, [unassigned_info[[reason=ALLOCATION_FAILED], at[2023-06-27T09:36:09.126Z], failed_attempts[5], failed_nodes[[WMstn7uvRqKhylJPSxyTAg]], delayed=false, details[failed shard on node [WMstn7uvRqKhylJPSxyTAg]: failed to create shard, failure IOException[failed to obtain in-memory shard lock]; nested: ShardLockObtainFailedException[[my-index1][1]: obtaining shard lock for [starting shard] timed out after [5000ms], lock already held for [closing shard] with age [41447ms]]; ], allocation_status[no_attempt]]]
```

**Expected behavior**
replica shard should not fail.

**Plugins**
all default plugins

**Screenshots**
image

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version 2.8.0

**Additional context**

### PR DESCRIPTION
**Pull request by dreamer-89**
### Description
1. Prevents the store clean up via cleanupAndPreserveLatestCommitPoint method on OpenSearchReaderManager close operation. Removes the `cleanupTempFiles` boolean flag from store cleanup as only files which are dec'ref to 0 are cleaned.
2. Refactors SegmentReplicationTarget finalize replication by moving to store.
3. Refactor Store clean up utilities.

### Related Issues
Resolves #8286 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/store/Store.java [hunk 1]
```diff
@@ -840,18 +859,15 @@ public void cleanupAndPreserveLatestCommitPoint(
...
     ) throws IOException {
         assert metadataLock.isWriteLockedByCurrentThread();
         for (String existingFile : directory.listAll()) {
             if (Store.isAutogenerated(existingFile)
                 || localSnapshot != null && localSnapshot.contains(existingFile)
                 || (additionalFiles != null && additionalFiles.contains(existingFile))
                 // also ensure we are not deleting a file referenced by an active reader.
-                || replicaFileTracker != null && replicaFileTracker.canDelete(existingFile) == false
-                // prevent temporary file deletion during reader cleanup
-                || deleteTempFiles == false && existingFile.startsWith(REPLICATION_PREFIX)) {
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/store/Store.java:854]: We still need to check if the file starts with the tmp prefix.  I think tmp file deletion should be done by MultiFileWriter only.  Or move the check to `canDelete` in ReplicaFileTracker.

Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/store/Store.java:854]: Added back logic to prevent temporary file deletion.

**Comment by dreamer-89** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:**  ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/19469/
> * **CommitID:** [fd2a05c](https://github.com/opensearch-project/OpenSearch/commit/fd2a05cb16cc7db538f8e2009dbcd0cd182d9e0b)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test failure. Tracked in https://github.com/opensearch-project/OpenSearch/issues/6287

File: server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java [hunk 2]
```diff
@@ -123,21 +123,7 @@ private NRTReplicationReaderManager buildReaderManager() throws IOException {
...
-                        getLastCommittedSegmentInfos(),
-                        false
-                    );
-                } catch (IOException e) {
-                    // Log but do not rethrow - we can try cleaning up again after next replication cycle.
-                    // If that were to fail, the shard will as well.
-                    logger.error("Unable to clean store after reader closed", e);
-                }
-            }
+            store::decRefFileDeleter
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java:126]: Thanks for cleaning this up!

File: server/src/main/java/org/opensearch/index/store/Store.java [hunk 3]
```diff
@@ -871,6 +836,53 @@ private void cleanupFiles(
...
+     * This method takes the segment info bytes to build SegmentInfos. It inc'refs files pointed by passed in SegmentInfos
+     * bytes to ensure they are not deleted.
+     *
+     * @param tmpToFileName Map of temporary replication file to actual file name
+     * @param infosBytes bytes[] of SegmentInfos supposed to be sent over by primary excluding segment_N file
+     * @param segmentsGen segment generation number
+     * @param consumer consumer for generated SegmentInfos
+     * @throws IOException Exception while reading store and building segment infos
+     */
+    public void buildInfosFromStore(
```
Comment (mch2) [inline server/src/main/java/org/opensearch/index/store/Store.java:851]: nit - I think we should rename this to indicate the infos is provided via replication vs from store, since it is not yet part of a commit on store.  `buildInfosFromBytes` ?

As a follow up it would be great to reuse this logic with remote store with https://github.com/opensearch-project/OpenSearch/issues/7802

Comment (dreamer-89) [reply server/src/main/java/org/opensearch/index/store/Store.java]: Updated.

**Review by mch2 — APPROVED** [review]
lgtm, thanks for cleaning this up.

File: server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java [hunk 4]
```diff
@@ -272,6 +274,58 @@ public void testIndexReopenClose() throws Exception {
         verifyStoreContent();
     }
 
+    public void testScrollWithConcurrentIndexAndSearch() throws Exception {
+        final String primary = internalCluster().startDataOnlyNode();
```
Comment (mch2) [inline server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:278]: Sorry didn't realize this on first pass - remote store code is not invoking the new store method yet until https://github.com/opensearch-project/OpenSearch/issues/7802 is done.  I think we need to skip this for remote store case or we will see flaky failures.

Comment (dreamer-89) [reply server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java:279]: Thanks @mch2 for pointing this out. Updated test.

**Comment by dreamer-89** [comment]
@mch2 : Is this fix also needed in `2.7` and `2.8` branch ?
