### PR TITLE
Fix a flaky test for issue 20058

### LINKED ISSUE #20058: [AUTOCUT] Gradle Check Flaky Test Report for CloneSnapshotIT
## Flaky Test Report for `CloneSnapshotIT`

Noticed the `CloneSnapshotIT` has some flaky, failing tests that failed during **post-merge actions** and **timer trigerred run on main branch**.

### Details

| Git Reference | Merged Pull Request | Build Details | Test Name |
|---------------|----------------------|---------------|-----------|
| main | [null](https://github.com/opensearch-project/OpenSearch/pull/null) | [66601](https://build.ci.opensearch.org/job/gradle-check/66601/testReport/) <br><br>[60523](https://build.ci.opensearch.org/job/gradle-check/60523/testReport/) <br><br>[60733](https://build.ci.opensearch.org/job/gradle-check/60733/testReport/) <br><br>[65108](https://build.ci.opensearch.org/job/gradle-check/65108/testReport/) <br><br>[65549](https://build.ci.opensearch.org/job/gradle-check/65549/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testCloneShallowSnapshotIndex`<br><br>`org.opensearch.snapshots.CloneSnapshotIT.testShallowCloneNameAvailability`<br><br>`org.opensearch.snapshots.CloneSnapshotIT.testCloneAfterRepoShallowSettingDisabled` |
| 1f761f2ab050e82d8b852eb960d7ac595045363a | [18832](https://github.com/opensearch-project/OpenSearch/pull/18832) | [61096](https://build.ci.opensearch.org/job/gradle-check/61096/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testCloneAfterRepoShallowSettingDisabled` |
| e2deff63b16f3c04d4a2881ad1e463d4629e3eea | [18580](https://github.com/opensearch-project/OpenSearch/pull/18580) | [59508](https://build.ci.opensearch.org/job/gradle-check/59508/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testCloneAfterRepoShallowSettingDisabled` |
| c677397504c09c8cbd61224c0b8ddd7b65053ae5 | [18082](https://github.com/opensearch-project/OpenSearch/pull/18082) | [57886](https://build.ci.opensearch.org/job/gradle-check/57886/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testShallowCloneNameAvailability` |
| c3325064d44d86a876c4960834c1eed44361189f | [17591](https://github.com/opensearch-project/OpenSearch/pull/17591) | [54632](https://build.ci.opensearch.org/job/gradle-check/54632/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testCloneShallowSnapshotIndex` |
| e93791bc97b9791c422fa21e365df340cb8e2aa2 | [17309](https://github.com/opensearch-project/OpenSearch/pull/17309) | [53277](https://build.ci.opensearch.org/job/gradle-check/53277/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testShallowCloneNameAvailability` |
| 1ec5bcb8c88c7672b83764ac3b1592fbabd61803 | [16502](https://github.com/opensearch-project/OpenSearch/pull/16502) | [50248](https://build.ci.opensearch.org/job/gradle-check/50248/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testCloneShallowSnapshotIndex` |
| 760e67641a063adfec05721ef676e47d347b17a5 | [16422](https://github.com/opensearch-project/OpenSearch/pull/16422) | [49967](https://build.ci.opensearch.org/job/gradle-check/49967/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testCloneShallowSnapshotIndex` |
| 5a46c0a37bb2fd5a755e120aa0aede1f89d93bd8 | [16277](https://github.com/opensearch-project/OpenSearch/pull/16277) | [49298](https://build.ci.opensearch.org/job/gradle-check/49298/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testCloneShallowSnapshotIndex` |
| b180569ff1c3dc57ae9cef7912293b6c5464ce9d | [16112](https://github.com/opensearch-project/OpenSearch/pull/16112) | [48544](https://build.ci.opensearch.org/job/gradle-check/48544/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testCloneSnapshotIndex` |
| a26db336e20df1bd6b5b997ba801ebcff4881afa | [14726](https://github.com/opensearch-project/OpenSearch/pull/14726) | [42303](https://build.ci.opensearch.org/job/gradle-check/42303/testReport/) | `org.opensearch.snapshots.CloneSnapshotIT.testCloneShallowSnapshotIndex` |

The other pull requests, besides those involved in post-merge actions, that contain failing tests with the `CloneSnapshotIT` class are:

- [15524](https://github.com/opensearch-project/OpenSearch/pull/15524)
- [15557](https://github.com/opensearch-project/OpenSearch/pull/15557)
- [14631](https://github.com/opensearch-project/OpenSearch/pull/14631)
- [15656](https://github.com/opensearch-project/OpenSearch/pull/15656)
- [15664](https://github.com/opensearch-project/OpenSearch/pull/15664)
- [16831](https://github.com/opensearch-project/OpenSearch/pull/16831)
- [18333](https://github.com/opensearch-project/OpenSearch/pull/18333)
- [16908](https://github.com/opensearch-project/OpenSearch/pull/16908)
- [14084](https://github.com/opensearch-project/OpenSearch/pull/14084)
- [14143](https://github.com/opensearch-project/OpenSearch/pull/14143)
- [14221](https://github.com/opensearch-project/OpenSearch/pull/14221)
- [14223](https://github.com/opensearch-project/OpenSearch/pull/14223)
- [14409](https://github.com/opensearch-project/OpenSearch/pull/14409)
- [14614](https://github.com/opensearch-project/OpenSearch/pull/14614)
- [14798](https://github.com/opensearch-project/OpenSearch/pull/14798)
- [14817](https://github.com/opensearch-project/OpenSearch/pull/14817)
- [14853](https://github.com/opensearch-project/OpenSearch/pull/14853)
- [15026](https://github.com/opensearch-project/OpenSearch/pull/15026)
- [16042](https://github.com/opensearch-project/OpenSearch/pull/16042)
- [16239](https://github.com/opensearch-project/OpenSearch/pull/16239)
- [16478](https://github.com/opensearch-project/OpenSearch/pull/16478)
- [16560](https://github.com/opensearch-project/OpenSearch/pull/16560)
- [16660](https://github.com/opensearch-project/OpenSearch/pull/16660)
- [16759](https://github.com/opensearch-project/OpenSearch/pull/16759)
- [17273](https://github.com/opensearch-project/OpenSearch/pull/17273)
- [17619](https://github.com/opensearch-project/OpenSearch/pull/17619)
- [17764](https://github.com/opensearch-project/OpenSearch/pull/17764)
- [17953](https://github.com/opensearch-project/OpenSearch/pull/17953)
- [18006](https://github.com/opensearch-project/OpenSearch/pull/18006)
- [18800](https://github.com/opensearch-project/OpenSearch/pull/18800)
- [19294](https://github.com/opensearch-project/OpenSearch/pull/19294)
- [19396](https://github.com/opensearch-project/OpenSearch/pull/19396)
- [19966](https://github.com/opensearch-project/OpenSearch/pull/19966)

For more details on the failed tests refer to [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083) dashboard.

### PR DESCRIPTION
**Pull request by liuguoqingfz**
### Description
Fix a flaky test where there's a timing/race where the snapshot sometimes starts while one primary shard is still initializing/relocating, so createFullSnapshot() observes totalShards=11 but only successfulShards=10.

### Related Issues
Resolves #20058 

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

## Summary by CodeRabbit

* **Tests**
  * Enhanced snapshot cloning test stability by adding cluster health waits around key steps and replacing direct checks with polling assertions for lock file counts, reducing flakiness during snapshot, shallow-snapshot, and clone operations.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java [hunk 1]
```diff
@@ -177,25 +177,57 @@ public void testCloneShallowSnapshotIndex() throws Exception {
         createIndex(remoteStoreEnabledIndexName, remoteStoreEnabledIndexSettings);
         indexRandomDocs(remoteStoreEnabledIndexName, randomIntBetween(5, 10));
 
+        assertBusy(
```
Comment (andrross) [inline server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java]: I don't think `assertBusy()` will do anything here since you're not asserting anything. I believe it will only retry AssertionErrors, and your code block would throw a different exception upon timeout or failure. I think you don't actually need assertBusy() here since the client call will block until that status is reached. I'd also consider looking at whether one of the `ensureYellow()` helper methods in the base class can be used here.

Comment (liuguoqingfz) [reply server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java]: I've made the change, please take a look again.

**Review by andrross — APPROVED** [review]
