### PR TITLE
Optimization in String Terms Aggregation query for Large Bucket Counts

### LINKED ISSUE #18704: [BUG] Optimize String terms agg
### Describe the bug

**Problem**
String terms aggregations has similar inefficiencies as numeric terms(#18703), with redundant sorting and suboptimal top-N selection.

**Solution**
Applied analogous optimizations to string terms aggregations, avoiding double sorting and optimizing bucket selection based on N relative to bucket counts.
https://github.com/rishabhmaurya/OpenSearch/commit/27d71e8337b3415f889ab7aa5c578d9b5f4bc7a7

**Impact**
Achieved performance improvements, enhancing aggregation efficiency for string-term aggregation queries.

### Related component

Search:Performance

### Expected behavior

```

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by vinaykpud**
### Description
If the number of requested top-N buckets exceeds or close to the maximum bucket ordinal, making the use of a PriorityQueue for top-N selection inefficient or redundant. So we made following modifications:
1. use quickselect for topN if the requested size is greater than the 20% of the total buckets.
2. If the requested size is greater than the bucket size then return all the bucket.

### Benchmark test results here : 
https://github.com/opensearch-project/OpenSearch/issues/18704#issuecomment-3075524228

### Related Issues
Resolves #18704
Related #18650

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rishabhmaurya** [comment]
Please check my comment in your other PR, i think we can reuse bunch of code here - https://github.com/opensearch-project/OpenSearch/pull/18702#discussion_r2249011975

**Comment by vinaykpud** [comment]
Although the high level selection strategies looks same for NumericTerm and StringTerm aggregations there are some changes in the implementation.
If we check the implementation for StringTermAggregations ie this PR,

1. Here we use `collectionStrategy` to get all the ordinals
2. Updating the bucket requires different arguments
3. While selecting the topBuckets we need to covert buckets ie `convertTempBucketToRealBucket`

whereas in NumericTermAggregation we do it differently.

So it will be hard to reuse the code here or may require lot of other refactors not related to the change.

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java [hunk 1]
```diff
@@ -851,30 +852,88 @@ private InternalAggregation[] buildAggregations(long[] owningBucketOrds) throws
...
-                    @Override
-                    public void accept(long globalOrd, long bucketOrd, long docCount) throws IOException {
-                        otherDocCount[finalOrdIdx] += docCount;
-                        if (docCount >= localBucketCountThresholds.getMinDocCount()) {
-                            if (spare == null) {
+                // When request size is smaller than 20% of total buckets, use priority queue to get topN buckets
+                // partiallyBuiltBucketComparator is null for significantTerm Aggregations use case and the way buckets sorted in the
+                // priority queue is based on the significanceScore
+                if ((size < 0.20 * valueCount) || isKeyOrder(order) || partiallyBuiltBucketComparator == null) {
+                    PriorityQueue<TB> ordered = buildPriorityQueue(size);
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java]: I am curious how we arrived at 20% as the right threshold for choosing between `pq` approach vs `quickselect`?

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java [hunk 2]
```diff
@@ -851,30 +852,88 @@ private InternalAggregation[] buildAggregations(long[] owningBucketOrds) throws
...
+                        Iterator<TB> itr = ordered.iterator();
+                        for (int i = ordered.size() - 1; i >= 0; --i) {
+                            topBucketsPreOrd[ordIdx][i] = convertTempBucketToRealBucket(itr.next());
+                            otherDocCount[ordIdx] -= topBucketsPreOrd[ordIdx][i].getDocCount();
+                        }
+                    }
+                } else {
+                    final int finalOrdIdx = ordIdx;
+                    Object[] bucketsForOrdArr = new Object[(int) valueCount];
+                    int[] tot = { 0 };
```
Comment (jainankitk) [inline server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java:916]: Does this have any memory usage implications when the size is above 20% of value count?

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java (hunk 1 above)
Comment (vinaykpud) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java]: Compared with different threshold starting from 10% and analyzed for which value QuickSelects performs better. I have added the results here:
https://github.com/opensearch-project/OpenSearch/pull/18702#issuecomment-3075431370

File: server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java (hunk 2 above)
Comment (vinaykpud) [reply server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java:916]: There is no much difference in the memory usage is observed for the size above 20%.  When we use quickSelect we create an array with size equal to the bucketOrdinal and copy all buckets to it to perform the topN selection. Following comparison has JVM metrics
https://github.com/opensearch-project/OpenSearch/issues/18704#issuecomment-3075524228###

**Comment by rishabhmaurya** [comment]
I'm guessing we are reusing the same logic we used for numeric terms  https://github.com/opensearch-project/OpenSearch/pull/18702 i.e.
```
when size >= bucketsInOrd : return all
bucketsInOrd> size && bucketsInOrd <= 5*size : quick select
else i.e. bucketsInOrd> size &&   bucketsInOrd > 5*size : pq
```

LGTM

**Comment by vinaykpud** [comment]
Correct, decision logic is same.
