### PR TITLE
limit the max value of cluster.max_shards_per_node to avoid int overflow 

### LINKED ISSUE #13907: [BUG] cluster.max_shards_per_node should have an upper limit
### Describe the bug

In our product, at first, user set cluster.max_shards_per_node to 500_000_000 to avoid shard unassigned. after days later, the nodes of the cluster are extended from 10 to 15.  and the new created shard can't be unassigned because of the error:
```
"Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [30101]/[-1089934592] maximum shards open;"
```
image

If we should limit the upper of cluster.max_shards_per_node, such as 5000_000, it can't be reached in the current struct.

### Related component

Cluster Manager

### To Reproduce

xxx

### Expected behavior

xxx

### Additional Details

**Host/Environment (please complete the following information):**
 - OS2.9

### PR DESCRIPTION
**Pull request by kkewwei**
Signed-off-by: kkewwei kkewwei@163.com

### Description
Limit the max value of cluster.max_shards_per_node to avoid int overflow. We can't reach  1_500_000 in the current opensearch struct.

### Related Issues
Resolves #13907

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java [hunk 1]
```diff
@@ -214,6 +214,19 @@ public void testNonSystemIndexCreationFailsWithMaxShardLimitOnCluster() {
...
     }
 
+    public void testMaxValueOfMaxShardLimitOnCluster() {
+        final int maxShardLimitOnCluster = 2_000_000;
+        Settings limitOnlySettings = Settings.builder().put(SETTING_CLUSTER_MAX_SHARDS_PER_NODE.getKey(), maxShardLimitOnCluster).build();
+        final IllegalArgumentException exception = expectThrows(
+            IllegalArgumentException.class,
+            () -> createTestShardLimitService(limitOnlySettings)
+        );
+        assertEquals(
```
Comment (dblock) [inline server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java:224]: Does this fail with something like the `Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [30101]/[-1089934592] maximum shards open;` error without this fix?

Comment (kkewwei) [reply server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java:224]: Yes, if the user set the cluster.max_shards_per_node too large(such as 500_000_000), it will hit this case. 

In our product, user will manage the cluster directly, he is not familiar with the parameter. To save trouble, 500_000_000 is set, which caused the rollover index to be unable to be allocated the next day.

**Comment by dblock** [comment]
@shwetathareja Any issues with this? This is a new limit, so anyone setting it higher than 1.5M will see a failure in upgrade.

File: CHANGELOG.md [hunk 2]
```diff
@@ -72,6 +72,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 - Pass parent filter to inner hit query ([#13903](https://github.com/opensearch-project/OpenSearch/pull/13903))
 - Fix NPE on restore searchable snapshot ([#13911](https://github.com/opensearch-project/OpenSearch/pull/13911))
 - Fix double invocation of postCollection when MultiBucketCollector is present ([#14015](https://github.com/opensearch-project/OpenSearch/pull/14015))
+- Fix limit the max value of cluster.max_shards_per_node to avoid int overflow ([#14155](https://github.com/opensearch-project/OpenSearch/pull/14155))
```
Comment (shwetathareja) [inline CHANGELOG.md:75]: [minor]: Fix the max value of cluster.max_shards_per_node to avoid int overflow

File: server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java [hunk 3]
```diff
@@ -214,6 +214,19 @@ public void testNonSystemIndexCreationFailsWithMaxShardLimitOnCluster() {
         );
     }
 
+    public void testMaxValueOfMaxShardLimitOnCluster() {
```
Comment (shwetathareja) [inline server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java:217]: testMaxValueOfMaxShardLimitOnCluster -> testMaxValueOfMaxShardLimitPerNode

File: server/src/main/java/org/opensearch/indices/ShardLimitValidator.java [hunk 4]
```diff
@@ -68,6 +68,7 @@ public class ShardLimitValidator {
         "cluster.max_shards_per_node",
         1000,
         1,
+        1_500_000,
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/indices/ShardLimitValidator.java:71]: This can also result in int overflow when executing
```
Math.min(maxShardsInCluster, maxShardsPerNodeSetting * nodeCount);
``` in ShardLimitValidator.java as it depends on nodeCount

Make the change here and handle the multiplication in long and check if it is exceed Integer.MAX_VALUE
```
        if (maxShardsInCluster == -1) {
            maxShardsInCluster = maxShardsPerNodeSetting * nodeCount;
        } else {
            maxShardsInCluster = Math.min(maxShardsInCluster, maxShardsPerNodeSetting * nodeCount);
        }
```

**Comment by kkewwei** [comment]
> a flaky test

AwarenessAttributeDecommissionIT.testConcurrentDecommissionAction #12197

**Comment by kkewwei** [comment]
@dblock @shwetathareja please have another look.

**Comment by kkewwei** [comment]
> ❌ Gradle check result for [b2cf752](https://github.com/opensearch-project/OpenSearch/commit/b2cf7521c5a38a1df37706eb071af77c04afc90d): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/40819/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

ReindexBasicTests.testMultipleSources #13913

File: server/src/main/java/org/opensearch/indices/ShardLimitValidator.java [hunk 5]
```diff
@@ -261,14 +261,15 @@ static Optional<String> checkShardLimit(
...
         if (maxShardsInCluster == -1) {
-            maxShardsInCluster = maxShardsPerNodeSetting * nodeCount;
+            maxShardsInCluster = computedMaxShards;
         } else {
-            maxShardsInCluster = Math.min(maxShardsInCluster, maxShardsPerNodeSetting * nodeCount);
+            maxShardsInCluster = Math.min(maxShardsInCluster, computedMaxShards);
         }
 
-        int currentOpenShards = state.getMetadata().getTotalOpenIndexShards();
+        long currentOpenShards = state.getMetadata().getTotalOpenIndexShards();
```
Comment (shwetathareja) [inline server/src/main/java/org/opensearch/indices/ShardLimitValidator.java:272]: it can be int only?

**Review by shwetathareja — COMMENTED** [review]
Thanks @kkewwei , minor comment otherwise looks good.

File: server/src/main/java/org/opensearch/indices/ShardLimitValidator.java (hunk 5 above)
Comment (kkewwei) [reply server/src/main/java/org/opensearch/indices/ShardLimitValidator.java:272]: just want the `testComputedMaxShardsOfClusterIntOverFlow` throwing exception, if currentOpenShards is int type, 
`
if ((currentOpenShards(2) + newShards(Integer.MAX_VALUE - 1)) > maxShardsInCluster(Integer.MAX)) 
` will be false, int overflow occurred, we can't see any exception.

**Comment by kkewwei** [comment]
@shwetathareja  please see again.

File: server/src/main/java/org/opensearch/indices/ShardLimitValidator.java (hunk 5 above)
Comment (rajiv-kv) [reply server/src/main/java/org/opensearch/indices/ShardLimitValidator.java:272]: @shwetathareja  - The return type of `getTotalOpenIndexShards` is declared to be integer and this is computed by  accumulating the count (integer type) across all the indices in cluster. Instead of changing the local variable `currentOpenShards` to integer we might need to change the return type of `getTotalOpenIndexShards` to return long.

Comment (kkewwei) [reply server/src/main/java/org/opensearch/indices/ShardLimitValidator.java:272]: @rajiv-kv, The shard count of the cluster cannot reach the Integer.MAX,  so it seems no need to change the return type of getTotalOpenIndexShards.

Comment (rajiv-kv) [reply server/src/main/java/org/opensearch/indices/ShardLimitValidator.java:272]: Got it @kkewwei . I think in that case we can leave `currentOpenShards` as int and modify the test.

**Review by shwetathareja — APPROVED** [review]

**Comment by shwetathareja** [comment]
@kkewwei please fix the conflict in ChangeLog.md

**Review by shwetathareja — APPROVED** [review]
