### PR TITLE
Retry download of RemoteFSTranslog to fix transient race conditions

### LINKED ISSUE #9191: [BUG] org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing flaky failure
**Describe the bug**

4 failures in org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing (21818,21853,22063,22065)

Meta issue - https://github.com/opensearch-project/OpenSearch/issues/8279

### PR DESCRIPTION
**Pull request by gbbafna**
### Description

Retrying translog download if it fails due to no file found for a finite time

In Primary to Primary relocation , there can be concurrent upload and download of translog.
While translog files are getting downloaded by new primary, it might hence be deleted by the primary
Hence we retry if tlog/ckp files are not found .

This doesn't happen in last download , where it is ensured that older primary has stopped modifying tlog data.

### Related Issues
Resolves #9191

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 1]
```diff
@@ -142,7 +145,28 @@ public static void download(Repository repository, ShardId shardId, ThreadPool t
...
+        for (int i = 0; i <= DOWNLOAD_RETRIES; i++) {
+            try {
+                downloadOnce(translogTransferManager, location, logger);
+                return;
+            } catch (FileNotFoundException | NoSuchFileException e) {
+                // continue till download retries
+                ex = e;
+            }
+        }
+        throw ex;
```
Comment (ashking94) [inline server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:166]: Should we use the constantBackoff with maxRetries method present in `BackoffPolicy` class?

**Review by ashking94 — COMMENTED** [review]
>In Primary to Primary relocation , there can be concurrent upload and download of translog.

When you say concurrent upload and download, are we referring to concurrency due to old primary uploading and new primary downloading?

> While translog files are getting downloaded by new primary, it might hence be deleted by the primary
Hence we retry if tlog/ckp files are not found .

I did not follow through this. The older primary can delete the translog when the new primary is trying to download the same? If so, is there a way we can disable the translog deletion somehow and disallow the erroneous state.

File: server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java [hunk 2]
```diff
@@ -1384,6 +1391,40 @@ public void testCloseIntoReader() throws IOException {
...
+        when(mockTransfer.readMetadata()).thenReturn(translogTransferMetadata);
+
+        // Always File not found
+        when(mockTransfer.downloadTranslog(any(), any(), any())).thenThrow(new NoSuchFileException("File not found"));
+        TranslogTransferManager finalMockTransfer = mockTransfer;
+        assertThrows(NoSuchFileException.class, () -> RemoteFsTranslog.download(finalMockTransfer, location, logger));
+
+        // File not found in first attempt . File found in second attempt.
+        mockTransfer = mock(TranslogTransferManager.class);
+        when(mockTransfer.downloadTranslog(any(), any(), any())).thenThrow(new NoSuchFileException("File not found")).thenReturn(true);
```
Comment (BhumikaSaini-Amazon) [inline server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java:1412]: When should we expect `FileNotFoundException` vs `NoSuchFileException` (as per the new change)? I see we are simulating only `NoSuchFileException` here and not `FileNotFoundException`

File: server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
Comment (BhumikaSaini-Amazon) [inline server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java:1]: Do we have a test that validates the behaviour when all attempts to download tlog fail?

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java (hunk 1 above)
Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:166]: `BackoffPolicy` and `RetryableAction` are made for transport  requests  . For our usecase , this will only complicate the code. .

File: server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java [hunk 3]
```diff
@@ -142,7 +145,28 @@ public static void download(Repository repository, ShardId shardId, ThreadPool t
...
+    }
+
+    static void downloadOnce(TranslogTransferManager translogTransferManager, Path location, Logger logger) throws IOException {
```
[the remark this answers is not in the document]
Comment (gbbafna) [reply server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java:169]: Good point . We shouldn't allow it . Made it private .

File: server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
Comment (gbbafna) [reply server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java:1]: Yes the first test does the same.

File: server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java (hunk 2 above)
Comment (gbbafna) [reply server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java:1412]: In our flaky tests , we are getting `NoSuchFileException` only . 

```
java.nio.file.NoSuchFileException: /var/jenkins/workspace/gradle-check/search/server/build/testrun/internalClusterTest/temp/org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT_E5702EA51B217BD6-002/tempDir-002/node_t0/d0/nodes/0/indices/-GQpazvARuyR8a4ej61XRA/0/index/_2h_1_Asserting_0.dvm
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:224) ~[?:?]
```

`FSBlobContainer` thrown `NoSuchFileException`  when it doesn't find a file . Even `S3BlobContainer` throws `NoSuchFileException`.  It is converting `FileNotFoundException` into  `NoSuchFileException` .  However we are not sure what other BlobContainers might throw. The contract just says `IOException` .  So this is just to make the code more comprehensive and catch this specific issue broadly .

**Review by BhumikaSaini-Amazon — APPROVED** [review]
Thanks for fixing this 🙌

**Comment by ashking94** [comment]
Lets close this once we have good confidence on https://github.com/opensearch-project/OpenSearch/pull/9603.

**Comment by gbbafna** [comment]
Flaky test failing : https://github.com/opensearch-project/OpenSearch/issues/9688
