### PR TITLE
Fix flaky test testReplicaReceivesGenIncrease.

### LINKED ISSUE #5232: [BUG] org.opensearch.index.shard.SegmentReplicationIndexShardTests.testReplicaReceivesGenIncrease flaky
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.shard.SegmentReplicationIndexShardTests.testReplicaReceivesGenIncrease" -Dtests.seed=AF518467E7BD5FFF -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-MT -Dtests.timezone=Pacific/Wallis -Druntime.java=19

org.opensearch.index.shard.SegmentReplicationIndexShardTests > testReplicaReceivesGenIncrease FAILED
    java.lang.AssertionError: expected:<0> but was:<31>
        at __randomizedtesting.SeedInfo.seed([AF518467E7BD5FFF:223BC64F10A3EBDF]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.index.shard.SegmentReplicationIndexShardTests.testReplicaReceivesGenIncrease(SegmentReplicationIndexShardTests.java:276)
```

https://github.com/opensearch-project/OpenSearch/pull/5223

### PR DESCRIPTION
**Pull request by mch2**
Signed-off-by: Marc Handalian <handalm@amazon.com>

### Description
This fixes a race condition in segment replication specific test code where a CountDownLatch would complete before replication.  If the latch completes before the actual replication event the replica state is unpredictable.  This change removes the latch's wait limit of 1 second.

### Issues Resolved
closes #5232

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java [hunk 1]
```diff
@@ -1301,7 +1301,7 @@ public void onReplicationFailure(
                 }
             );
             ids.add(target);
-            countDownLatch.await(1, TimeUnit.SECONDS);
+            countDownLatch.await();
```
Comment (reta) [inline test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java:1304]: I think we shouldn't wait unconditionally (potentially hanging the build), having reasonable timeout is needed - let the test fail but build moves on.

Comment (mch2) [reply test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java]: Changed to 30s with an assert after the timeout that replication completed.

**Review by adnapibar — APPROVED** [review]

**Comment by mch2** [comment]
Hmm I broke some other segrep tests with this.. taking a look.

**Comment by adnapibar** [comment]
> Hmm I broke some other segrep tests with this.. taking a look.

Interesting!

File: test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java [hunk 2]
```diff
@@ -1301,8 +1301,9 @@ public void onReplicationFailure(
                 }
             );
             ids.add(target);
-            countDownLatch.await(1, TimeUnit.SECONDS);
         }
+        countDownLatch.await(30, TimeUnit.SECONDS);
+        assertEquals("Replication should complete successfully", 0, countDownLatch.getCount());
```
Comment (adnapibar) [inline test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java:1306]: 👍
