### PR TITLE
Single line comments can end in newline or EOF. Fixes #11815

### LINKED ISSUE #11815: [BUG] Painless Script Single Line Comment at EOF Causes Parsing Error
### Describe the bug

The Painless language as implemented has a papercut that scripts cannot end in a single-line comment without a newline/carriage-return. 

Was there a specific motivation why EOF wasn't a valid end token for single-line comments?

If so, it could be helpful to document that as leaving a comment without newline leads to an un-intuitive error: `"type":"illegal_argument_exception","reason":"unexpected character [/ I am an unparsable comment].","caused_by":{"type":"lexer_no_viable_alt_exception","reason":null`

If not, then suggesting a change to the lexer/grammar (like #11816)

### Related component

Other

From my understanding, this is actually a bug from when this was forked from ElasticSearch, based on this definition of a comment: https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-comments.html

### To Reproduce

```bash
docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" public.ecr.aws/opensearchproject/opensearch:2.11.1

# wait for single-node cluster to init

curl -ku 'admin:admin' -XGET "https://localhost:9200/_scripts/painless/_execute" -H 'Content-Type: application/json' -d'{ 
    "script": 
        { 
            "source": "return 5 // I am an unparsable comment" 
        } 
}'


{"error":{"root_cause":[{"type":"script_exception","reason":"compile error","script_stack":["return 5 // I am an unparsable comm ...","          ^---- HERE"],"script":"return 5 // I am an unparsable comment","lang":"painless","position":{"offset":10,"start":0,"end":35}}],"type":"script_exception","reason":"compile error","script_stack":["return 5 // I am an unparsable comm ...","          ^---- HERE"],"script":"return 5 // I am an unparsable comment","lang":"painless","position":{"offset":10,"start":0,"end":35},"caused_by":{"type":"illegal_argument_exception","reason":"unexpected character [/ I am an unparsable comment].","caused_by":{"type":"lexer_no_viable_alt_exception","reason":null}}},"status":400}%
```

### Expected behavior

Comments at EOF without newline do not

```
curl -ku 'admin:admin' -XGET "https://localhost:9200/_scripts/painless/_execute" -H 'Content-Type: application/json' -d' { "script": { "source": "return 5 // I am an unparsable comment" } }'
{"result":"5"}
```

### Additional Details

**Plugins**
Please list all plugins currently enabled.:

N/A NONE

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Linux (from Docker Desktop for Mac)
 - Version 2.11.1

**Additional context**

### PR DESCRIPTION
**Pull request by camerondurham**
### Description
Changes grammar of painless language to accept single-line comments that end in `\n`, `\r` or `EOF`.

### Related Issues
Resolves #11815 

#### To Reproduce Bug Before Fix

```bash
docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" public.ecr.aws/opensearchproject/opensearch:2.11.1

# wait for single-node cluster to init

curl -ku 'admin:admin' -XGET "https://localhost:9200/_scripts/painless/_execute" -H 'Content-Type: application/json' -d'{ 
    "script": 
        { 
            "source": "return 5 // I am an unparsable comment" 
        } 
}'


{"error":{"root_cause":[{"type":"script_exception","reason":"compile error","script_stack":["return 5 // I am an unparsable comm ...","          ^---- HERE"],"script":"return 5 // I am an unparsable comment","lang":"painless","position":{"offset":10,"start":0,"end":35}}],"type":"script_exception","reason":"compile error","script_stack":["return 5 // I am an unparsable comm ...","          ^---- HERE"],"script":"return 5 // I am an unparsable comment","lang":"painless","position":{"offset":10,"start":0,"end":35},"caused_by":{"type":"illegal_argument_exception","reason":"unexpected character [/ I am an unparsable comment].","caused_by":{"type":"lexer_no_viable_alt_exception","reason":null}}},"status":400}%
```

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] ~~New functionality has been documented.~~ (skipping since no new functionality added)
  - [ ] ~~New functionality has javadoc added~~
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] ~~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~~ (not including since this is a "bug fix" that wasn't documented before)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java [hunk 1]
```diff
@@ -1,35 +1,4 @@
-/*
```
Comment (camerondurham) [inline modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java:1]: Looks like I accidentally removed these when re-generating parser config. Will add back once actions finish running.

Comment (camerondurham) [reply modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java]: Added back in https://github.com/opensearch-project/OpenSearch/pull/11816/commits/fdfb6407e386029f636c5df68b68f41c2b60272e

File: modules/lang-painless/src/main/antlr/PainlessLexer.g4 [hunk 2]
```diff
@@ -25,7 +25,7 @@ protected abstract boolean isSlashRegex();
 }
 
 WS: [ \t\n\r]+ -> skip;
-COMMENT: ( '//' .*? [\n\r] | '/*' .*? '*/' ) -> skip;
+COMMENT: ( '//' .*? ([\n\r] | EOF) | '/*' .*? '*/' ) -> skip;
```
Comment (reta) [inline modules/lang-painless/src/main/antlr/PainlessLexer.g4:28]: It looks like a legit change, thank you @camerondurham

File: modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java [hunk 3]
```diff
@@ -30,6 +30,7 @@
  * Modifications Copyright OpenSearch Contributors. See
  * GitHub history for details.
  */
+
```
Comment (reta) [inline modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java:33]: @camerondurham could you please revert this change please? (it is not harmful but adds a noise to history), thank you

**Comment by reta** [comment]
Ah ... conflicts, could you please rebase against latest `main`? Thank you.

File: modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java (hunk 3 above)
Comment (camerondurham) [reply modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java]: For sure, sorry, let this slip in. Removed from files changed.

File: modules/lang-painless/src/main/antlr/PainlessLexer.g4 (hunk 2 above)
Comment (reta) [inline modules/lang-painless/src/main/antlr/PainlessLexer.g4:28]: @camerondurham this is just a question, do you think we could simplify it to something like:

```
COMMENT: ( '//' ~[\r\n]* | '/*' .*? '*/' ) -> skip;
```

`EOF` does work but it looks like super edge case

Comment (camerondurham) [reply modules/lang-painless/src/main/antlr/PainlessLexer.g4]: Yes, I think your definition makes more sense instead of coding for the edge case. From a quick test in [ANTLR LAB](http://lab.antlr.org/) also seems this works with the edge cases I tried. Rebased regenerated the lexer Java with this change.

Thanks!

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@dblock @msfroh could you please back me up here folks in case I am missing something, thank you!

**Comment by dblock** [comment]
> @dblock @msfroh could you please back me up here folks in case I am missing something, thank you!

LGTM. The fact that no tests broke is promising, but @camerondurham if you want to spend a bit more time looking through existing tests around scripting to see if there are uncovered areas, that'd be grand.
